### ISSUE TITLE
Add other new ways for reward points to be auto added (can be done as plugins using events)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#10]
1. when a customer leaves a product review (once approved). Also display a text something like "You will earn 5 points for writing a review and 4 points for rating this product". also see contribution at http://www.nopcommerce.com/boards/t/33963/feature-request-give-reward-points-for-writing-a-product-review.aspx#138422. we also have appropriate events added in version 3.60
2. when a customer subscribes to a newsletter (ensure it's not done twice when unsubcribe/subscribe)
3. when a customer leaves a blog comment (ensure it's not done twice when activated/deactived)
4. when a customer leaves a news comment (ensure it's not done twice when activated/deactived)

Make it configurable on "reward points" settings page 

Maybe, just add appropriate events and use them in plugins (IMiscPlugins)

before starting let's discuss a list of events to use (add reward points)

**Comment by RomanovM** [comment]
Implemented as a plugin https://github.com/nopSolutions/reward-points-plugin
