### ISSUE TITLE
Product history (log) + logging stock quantity changes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#100]
Catalog setting side if we can add option for product history enable or disable will be perfect for site owner. If enabled (can be disabled) we keep every updates for products so later we can use it for analyze - reports etc . Basicly we can shows product details page price history etc.. We can display it on the "History (log) tab on the product details page (admin area) 

Source: http://www.nopcommerce.com/boards/t/37161/feature-product-history-enable.aspx

___________________________________

It is about logging stock quantity changes, so that owners can see the history of a product stock quantity. At the moment, we can only see the current stock quantity in the system but not how it has changed from the backend. 

There is already a good work item about adjusting stock quantities: 
https://nopcommerce.codeplex.com/workitem/12562 

Based on the new work item above, changes could be:
* increased
* descrease
* set

There are definitly multiple options but here are two for a start:
* the core would "log" changes to stock quantities with needed info about product names, warehouse, amount,...
* the core would provide corresponding events (increased, descreased, set) that a plugin could consume

Depending if the core would log the changes there are a few options where this info could be shown:
* create an own admin page where it will list all changes to stock quantity (warehouse, product number, name, amount,...) where owners could browse through or export the list to Excel
* or show it on the product edit page in its on tab

Source: http://www.nopcommerce.com/boards/t/36603/nopcommerce-370-roadmap-and-estimated-release-date-lets-discuss.aspx?p=2#148482

**Comment by AndreiMaz** [comment]
duplicate
