### ISSUE TITLE
Bulk edit products. Allow a store owner to filter "low stock" products (or by "qty")

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1000]
It would be very useful to be able to edit the quantities in the low stock report directly, rather than having to go to the individual product pages. 

An alternative method could be to enhance the Bulk Edit Products page to have an extra filter on quantity. In our case we could select all products with quantity = 0 but that may not be useful for everybody. 

Source: http://www.nopcommerce.com/boards/t/35219/low-stock-report-suggested-enhancement.aspx

**Comment by bulutkartal** [comment]
Filtering by vendor would be great as well.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
