### ISSUE TITLE
Restrict shipping to states of specific country

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1001]
I see nopCommerce offers the ability to restrict shipping to specific countries. 

Can this be further extended to enable us to restrict shipping to specific states within a given country? 

Source: http://www.nopcommerce.com/boards/t/35206/restrict-shipping-to-states-of-specific-country.aspx

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
