### ISSUE TITLE
Returns and Exchanges - Provide Return Button without logging in first

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1003]
There needs to be a more transparent way for customers to do exchanges or returns. There is currently an issue that could be mitigated where customers are returning items on their own to incorrect addresses and it cost extra to forward them to the correct warehouse. One solution would be to offer a "Return" button on the Shipping & Returns and Contact us screens. The idea is to ensure all returns are initiated through the store and to prevent customers from sending packages on their own to incorrect addresses. 

Source: http://www.nopcommerce.com/boards/t/35126/feature-request-returns-and-exchanges-provide-return-button-without-logging-in-first.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
