### ISSUE TITLE
Vendor Ratings

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#101]
1) Vendor Ratings.
2) Vendor Contact and Address details.
3) Vendor Policies (Terms, Privacy etc)
4) Shipping Locations (Where the vendor would ship too, to avoid disappointing potential customers)
5) The ability to display Vendors and Products based on the clients location.

I am sure there are more, but these would certainly satisfy most developers needs.

Source: http://www.nopcommerce.com/boards/t/28316/vendor-page.aspx#117992

**Comment by AndreiMaz** [comment]
Duplicate #54. Also split to several work items

**Comment by sumit7034** [comment]
How the feature for "Ability to display Vendors and Products based on the clients location" 
will be implemented?

Will it be based on google map longitute, Latitute?
