### ISSUE TITLE
Search products by SKU should be exact match (not "contains")

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1017]
I mean "SearchProducts" method of "IProductService" (stored procedure) and not "GetProductBySku" one 

Maybe, we should do it configurable

**Comment by techdigitroll** [comment]
@AndreiMaz is there any specific reason for this change? We have a customer that want to search for partial SKUs, and partial custom-fields. Could we change the storedProcedure to CONTAINS as it was in 3.7 version of nopcommerce, or would this scramble the pagespeed?
