### ISSUE TITLE
nopCommerce - Google Shopping - problems with Product attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1018]
Hi, 

I am updating my nopCommerce site with suits. There are 3 variations on a pair of trousers : Leg length (4 sizes), waist length(12 sizes) and colour(3 colours). We intend to put all our items up on google shopping but I was told that google shopping can not take all the possible variations (e.g. 4 X 12 X 3 = 144 ).

As a work around I was told that I need to create a different product page for each colour. Is this true or can I just keep the one page with all the product attributes ?

**Comment by varghesep** [comment]
That may not be correct. As per this Google [guideline ](https://support.google.com/merchants/answer/6324507) the items can be grouped.
