### ISSUE TITLE
Add Minimum Shipping Charge to USPS Plugin

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1024]
Add a minimum shipping charge for the USPS plugin. In some cases, store owners want to charge a minimum amount for shipping regardless of what is returned from the actual USPS rate.

![nopcommerce-minimumshippingcharge 1](https://cloud.githubusercontent.com/assets/16681184/12418206/e656efbe-bebe-11e5-8f2b-a3dbb121547c.png)

**Comment by sumo300** [comment]
Can this be added to nop core itself if not in the provided shipping modules like USPS?  Store owners do need to be able to set minimum shipping charges.  I've added this to my own "re-write" of the USPS module, but it's really needed in your provided modules (USPS, UPS, FedEx).

**Comment by sumo300** [comment]
Closed as "will never implement?"  I've solved it by using the Shipping Director plug-in, but it was not a terribly difficult feature to write and you could have just used the code I wrote to add it.

**Comment by AndreiMaz** [comment]
USPS is not available out of the box anyway. it'll be available on our marketplace only starting version 4.00
