### ISSUE TITLE
Shopping cart item update when having a product with the same attributes. Summarize quantity?

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1025]
When updating the attributes of a cart item to match the attributes of another cart item, the updated item is deleted (at least appears to be a deletion, could be an summing error). I expected the cart to sum the quantity of the matching items, or at least leave both items in the cart. To duplicate the issue: 

From the sample store items, add the "adidas Women's Supernova CSH 7 Running Shoe" to the cart as a size 8 and in the White/Blue color. Next add the same item to the cart with a size 8 but in the White/Black color. Go to the shopping cart summary, then select the "edit" link of the first cart item. Modify the color to match the second item (change from blue to black) and click the "Update" button. Navigate back to the shopping cart summary. Notice that rather than summing the two matching items to a quantity of 2, one of the items is simply removed. 

Source: http://www.nopcommerce.com/boards/t/32755/items-are-removed-from-shopping-cart-on-update.aspx 

Think it's better to leave it as it's implemented now. A customer enters qty he want to have

**Comment by AndreiMaz** [comment]
Think it's better to leave it as it's implemented now. A customer enters qty he want to have
