### ISSUE TITLE
More localizable entities

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1046]
But where will it be used? Localizable properties are used only in public store. But these suggestions are not displayed in public store. So there's no need in its localization 

001- Customer Role Name 
002- Discount Name 
003- Discount Name 
004- SEO settings in setting in General And Miscellaneous Settings 
specialty : 
height recommend 
Default title 
Default meta keywords 
Default meta description 

low recommend 
Page title SEO adjustment 
Page title separator 

005- Language Name 
006- Currency Custom formatting 
007- Weight Name 
008- Dimension Name 
009- Email Account > Email display name 
010- Payment Method Friendly name 
011- Shipping Rate Computation Method Friendly name 
012- Warehouse proprietaries 
Name 
City 
Address 1 

013- Tax Provider Friendly name 

Forum source: http://www.nopcommerce.com/boards/t/26877/tax-provider-friendly-name-proprietary-localizable.aspx and http://www.nopcommerce.com/boards/t/26866/customer-role-name-proprietary-localizable.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
