### ISSUE TITLE
full text search with ranking using FREETEXTTABLE()

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1047]
Full text as is currently implemented by NopCommerce does not make use built in ranking feature of full text implementation in sql server. It can be very usefull to show more relevant results first before showing less relevant results. My personal experience is that the full text implementation in nopcommerce is currently quite limited.

[loadallpaged.txt](https://github.com/nopSolutions/nopCommerce/files/95875/loadallpaged.txt)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
