### ISSUE TITLE
Add "product downloading" event

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1053]
I also feel the need to strengthen the functions of nopCommerce plugin interface. 
Currently, we offer a plugin "DynamicPdf" for e-book sites, but it is necessary to change the original source to get the event of downloading digital products. 

http://www.nopcommerce.com/p/799/dynamic-pdf.aspx 

nopCommerce has now plugin interfaces for Payment Method, Shipping Rate, Widget, Tax Provider, Discount and so on, but there is no mechanism to get the event of downloading digital products. 

So our plugin needs to modify slightly "Presentation/Nop.Web/Controllers/DownloadControllers.cs". 

On the other hand, in EC-CUBE which is the most popular eCommerce software(PHP Base) in Japan, each plugin can handle the event of downloading digital products and it is very easy to add the plugin. 

http://en.ec-cube.net/ 

We would like to expect the more flexible structure in nopCommerce plugin interface. 

Forum source: http://www.nopcommerce.com/boards/t/25154/nopcommerce-320-roadmap-and-estimated-release-date-lets-discuss.aspx#102902

**Comment by AndreiMaz** [comment]
duplicate
