### ISSUE TITLE
Blog/Forum Comment Enhancement: Selective Quote on Replies

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1078]
The comment system on one blog I frequent had a nice feature that would allow you to select the text in a prior post or comment and include only the the selected text in the quotation when you hit Quote/Reply button. It cuts down on whole long comments being unnecessarily repeated when only a sentence or two is required for context. 

Forum source: http://www.nopcommerce.com/boards/t/16355/blogforum-comment-enhancement-selective-quote-on-replies.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
