### ISSUE TITLE
Add the subtitle field to the blog post

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1082]
It would be great to have an ability to display the list of blog posts on the blog home page not with the full posts but with the subtitles (just a few sentences). This will look much more better and can be the next step to improve the blog usability. 
I had alrady implemented this in my project so if you need I can post the steps. (its just about a couple of code lines)

**Comment by ngtrian** [comment]
Can you make manage tag blog in Admin Area easier?

**Comment by ngtrian** [comment]
Is it possible to consider this issue?

**Comment by AndreiMaz** [comment]
leaving it for customization
