### ISSUE TITLE
VAT issue with customers created in admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1084]
"The problem is that the user I used before to check this procedure was created from scratch in the admin area, and not from the public registration page." 

I havent changed a single line of code so I can confirm it's a bug: 

If you create a user from the admin area the address that is used to determine if EU VAT = 0% is applicable is apparently not set and therefore it only shows prices without tax after the user has selected a Shipping (or Billing) address in the checkout procedure once. 

When you create a user via the store it all works fine (so EU VAT = 0% based on the address of the customer without registering a Shipping or Billing address. 

Although not many people will bump into this I think it is worthwhile to fix this bug it can highly annoy customers and administrators because tax is calculated when it shouldnt and all the settings look ok.... 

Source: http://www.nopcommerce.com/boards/t/7455/vat-configuration-guide.aspx?p=2

**Comment by jhaydens** [comment]
Perhaps when creating a user in admin, we should be prompted/required also to enter an address before the user is created ( that might circumvent the issue ? )
~~~
Could I also suggest that when we create a user in admin that a customer role is pre checked - prob 'registered'
