### ISSUE TITLE
Create an RSS feed in admin for anything which might be useful to storeowner - the storeowner can then monitor activity without logging on

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1086]
the store owner can link to it from a desktop feed reader eg google rss reader gadet - and have up to date information of store activities from their desktop without having to log into the store 

make it user configurable so admin can choose what's included in the feed 

things like : 

new orders 
new customer registrations 
return requests 
new reviews 
new comments ( news, blog etc) 
maybe also new forum activity ( broken down to post activity ? ) - maybe not so important

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
