### ISSUE TITLE
Create a setting to Show/Hide Vendor images on the Vendors page.

### ISSUE THREAD

**Issue by VMLNOP84** [nopSolutions/nopCommerce#1088]
One of our customers suggested in our forum to have a setting to Show/Hide Vendor images on the Vendors page.
I think that such a feature does make sense since not all vendors could have images and some businesses may not even want to show images.

More details are on http://www.nopcommerce.com/boards/t/40062/suggestion-enabledisable-vendor-images-on-public-site.aspx and http://www.nop-templates.com/boards/topic/2009/feature-requests/page/2#10572

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
