### ISSUE TITLE
Admin area. Add "quantity adjustment" (increase/decrease) field to the product details page (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#109]
We should also leave "quantity" field. Let a store owner to choose which field he wants to use (the current "qty" one or "quantity adjustment") . Let's make it configurable

Stock editing and database concurrency. More info at http://www.nopcommerce.com/boards/t/35041/stock-quantity-bulk-edit.aspx and http://www.nopcommerce.com/boards/t/32326/database-concurrency-entity-tracking-question-maybe-bug.aspx 

also see the following comment http://www.nopcommerce.com/boards/t/35041/stock-quantity-bulk-edit.aspx#142749 (stock change tracking)

Note 1: Don't forget about attribute combination. think about excel import, warehouses
Note 2: where should we do it? Product details page? Or new page with a list of products with list of quantities to increase/decrease

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
