### ISSUE TITLE
All delete functionality should use "POST" (XSRF validation)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1092]
1. Forum post or topic delete.
2. RemoveExternalAssociation

We should implement it similar to https://github.com/nopSolutions/nopCommerce/commit/ee71f7e068b86a202117309fda80f7b83c7f7322 and https://github.com/nopSolutions/nopCommerce/commit/0cf1dd5e7145da74d149a367f7493cb2a7e421f9

**Comment by odises** [comment]
Please assign it to me. I will do it.

**Comment by AndreiMaz** [comment]
odeses, thanks a lot for interest on contribution. Please create a new pull request as described at http://docs.nopcommerce.com/display/nc/Working+with+source+code+and+contributions

**Comment by odises** [comment]
@AndreiMaz Ok, thanks, I read it. In the second paragraph "branch description and naming" I think this is "till January 2016" not 1016. I will create the pull request soon.

**Comment by odises** [comment]
I checked all of the forms and realized that we send antiForgeryToken from client-side. I mean all of the views contains **Html.AntiForgeryToken()**
But no validation before related actions.
I should say antiForgery validation is necessary not just for delete action but for all the actions with post verb. I fixed them all, and made a pull request.

**Comment by odises** [comment]
Can I have a question? This issue mean all delete functionality in public area? Can you make it more clear for me?

**Comment by AndreiMaz** [comment]
Sure. Please see the issue description:

1. Forum post or topic delete.
2. RemoveExternalAssociation


We should implement it similar to https://github.com/nopSolutions/nopCommerce/commit/ee71f7e068b86a202117309fda80f7b83c7f7322 and https://github.com/nopSolutions/nopCommerce/commit/0cf1dd5e7145da74d149a367f7493cb2a7e421f9
