### ISSUE TITLE
When we create a user in admin,a customer role should be pre checked - prob 'registered'

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1094]
When we create a user in admin,a customer role should be pre checked - prob 'registered'

**Comment by manojkulkarni30** [comment]
Please assign it to me. I will do it.

**Comment by AndreiMaz** [comment]
Hi,

Sure. Please create a pull request as described at http://docs.nopcommerce.com/display/nc/Working+with+source+code+and+contributions
