### ISSUE TITLE
Upgrade Paypal (Direct and Standard) plugins to support TLS1.2

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1096]
It's required to update the PaypalDirect plugin to support TLS1.2. Otherwise the following error will occur The request was aborted: Could not create SSL/TLS secure channel

Quick Fix:

Those using the existing plugins and facing the issue can fix the issue by adding the following line to their PaypalDirect plugin.

File Name: PaypalDirectPaymentProcessor.cs

Changes:
Add the following code (in bold). Line number 209
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
var service = GetService();
DoDirectPaymentResponseType response = service.DoDirectPayment(req);

Source: http://www.nopcommerce.com/boards/t/40117/upgrade-paypaldirect-plugin-to-support-tls12.aspx

also see http://www.nopcommerce.com/boards/t/40117/upgrade-paypaldirect-plugin-to-support-tls12.aspx?p=2#160445 and http://stackoverflow.com/questions/34945002/the-request-was-aborted-could-not-create-ssl-tls-secure-channel-system-net-webe

We should make it configurable (add a setting)

**Comment by Andrey-Pavlov** [comment]
PayPalStandart also not works

<url>/Plugins/PaymentPayPalStandard/PDTHandler
Could not create SSL/TLS secure channel

**Comment by AndreiMaz** [comment]
fixed
