### ISSUE TITLE
Export/import with product attributes (Excel)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1097]
Allow to Export/Import products including product attributes

**Comment by ofekpc** [comment]
Think need to add ability to import and expoet
Not all the filed for exmpla only sku and price
That the admin will choose witch filed will export
And import
Also need ability to import and export category

**Comment by skoshelev** [comment]
Already sold #440

**Comment by skoshelev** [comment]
Closed #1097
