### ISSUE TITLE
Move some functionality to plugins

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#11]
Good candidates are forums, blog, polls, news. It can simplify the solution.

Let's think what else functionality we can move to plugins. Just several ideas but not confirmed - vendor support, import/export, GDPR, EU cookie law, reCAPTCHA. Other ideas?

Forum source: https://www.nopcommerce.com/boards/topic/19325/moving-baked-in-modules-to-plugins

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
