### ISSUE TITLE
New product property to exclude some products from any discount (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#110]
Can we create a working item to add new property to product which can exclude the product from any discount? This is actually a very common scenario and there is genuine requirement there for setting up some special one as non-discount (Although there is discount for its category). 

Searched the forum, similar questions have been raised before like below. Just no working item has been created yet. 

I think we should add add this checkbox to "Discounts" tab

See http://www.nopcommerce.com/boards/t/4584/setup-a-product-so-a-coupon-discount-code-can-not-be-applied.aspx  and http://www.nopcommerce.com/boards/t/34165/new-product-property-to-exclude-some-products-from-any-discount.aspx 

Contribution (fork) - https://nopcommerce.codeplex.com/SourceControl/network/forks/chrismcbride76/contributions/contribution/8349

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
