### ISSUE TITLE
The ability to display Vendors and Products based on the clients location.

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1103]
The ability to display Vendors and Products based on the clients location.

Source: http://www.nopcommerce.com/boards/t/28316/vendor-page.aspx#117992

**Comment by sumit7034** [comment]
Is ability to display Vendors and Products based on the clients location based on google map Longitude and latitude?

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
