### ISSUE TITLE
Rental products. Allow a store owner to specify allowed date range

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#111]
ability to set Minimal and Maximal limit for Duration .

See http://jqueryui.com/datepicker/#min-max

**Comment by tigran-avdalyan** [comment]
you can use http://www.daterangepicker.com/#examples

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
