### ISSUE TITLE
There is no Html.AntiForgeryToken in customer addresses page

### ISSUE THREAD

**Issue by odises** [nopSolutions/nopCommerce#1129]
There is no Html.AntiForgeryToken in customer addresses page, so addAntiForgeryToken(postData) does not work properly.
Also AddressDelete action in CustomerController does not have PublicAntiForgery attribute to validate requests.

**Comment by AndreiMaz** [comment]
Could yo please clarify. Do you mean admin area?

**Comment by odises** [comment]
No, in public store area.
in this file **\Presentation\Nop.Web\Views\Customer\Addresses.cshtml** we have no Html.AntiForegeryToken.
But there is a javascript method **addAntiForgeryToken** that is trying to fetch antiForgeryToken from the page to attach it to requestData and send the request via ajax.
Also in server side we have no validation attribute.

**Comment by AndreiMaz** [comment]
Thanks a lot! You're absolutely right. It'll be fixed soon
