### ISSUE TITLE
USPS. First-class Postcards and Letters should be hidden in some cases

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#113]
Postcard rates are showing up during shipping calculation for items that are obviously too large or heavy. 

I'm also seeing that I'm only ever given the rate for Priority and Express and Post card but not Standard Post. Is there another known bug with Standard Post showing up? Note that this seems to be prevalent in US domestic shipping, not international. 

This has been posted and discussed in further detail on this forum: http://www.nopcommerce.com/boards/t/31893/usps-update-september-7th-web-tools-release.aspx?p=2#130389

[AM] We an simply add a new setting (checkbox) allowing to disable these options for the first class. Just filter them in the "ParseResponse" method of the \plugins\nop.plugin.shipping.usps\uspscomputationmethod.cs file as suggested at http://www.nopcommerce.com/boards/t/31893/usps-update-september-7th-web-tools-release.aspx?p=3#136378

Also see http://www.noptools.com/blog/58/exclude-letter-and-postcards-from-usps-first-class

and one more topic: http://www.nopcommerce.com/boards/t/40152/extra-usps-first-class-mail-options-showing-up-but-not-wanted.aspx and http://www.nopcommerce.com/boards/t/40152/extra-usps-first-class-mail-options-showing-up-but-not-wanted.aspx#161045

**Comment by RomanovM** [comment]
It solved in https://github.com/nopSolutions/nopCommerce/commit/7d5d1b9ec81f5a55890466374b21a5da160c2554
