### ISSUE TITLE
Fix AutoMapper warnings

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1141]
Mapper.CreateMap<TSource, TDestination>()' is obsolete: 'The static API will be removed in version 5.0. Use a MapperConfiguration instance and store statically as needed. Use CreateMapper to create a mapper instance

**Comment by ArturAlekseev** [comment]
Maybe this way:
https://github.com/nopSolutions/nopCommerce/pull/1173
