### ISSUE TITLE
KendoUI grids. Allow " char in grid column titles

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#115]
If a grid column title contains " char, then the grid won't be loaded. We can use "@Html.Raw(HttpUtility.JavaScriptStringEncode(T("resource name").Text))". But it'll make source code less readable and will require a lot of chanages 

maybe, extend @T method with a new "java-script encode parameter? 

Forum source: http://www.nopcommerce.com/boards/t/29756/when-adding-new-language-admin-data-not-shown-in-other-admin-language-in-version-33.aspx

also see related https://github.com/nopSolutions/nopCommerce/issues/75 (in this case we should not do it)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box
