### ISSUE TITLE
RSS fails validation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1162]
I am not specialist in RSS, but I see the error.

atom:id must be a full and valid URL

Try to validate http://demo.nopcommerce.com/blog/rss/1

http://feedvalidator.org
http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fdemo.nopcommerce.com%2Fblog%2Frss%2F1

https://validator.w3.org
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fdemo.nopcommerce.com%2Fblog%2Frss%2F1

Source: http://www.nopcommerce.com/boards/t/40360/rss-feed-validator.aspx

**Comment by skoshelev** [comment]
I can fix the validation. But not recommendation.
![valid_rss](https://cloud.githubusercontent.com/assets/16875599/13004986/fec1057e-d18f-11e5-8d59-8ddc0076ba13.png)
