### ISSUE TITLE
Limit the first and last name length

### ISSUE THREAD

**Issue by iordan93** [nopSolutions/nopCommerce#1172]
If you register a user with too long first and last names (say 10,000 symbols each), and the mailing service is enabled for the site, the registration completes but throws a DB exception.
What happens is that the `Nop.Web.Controllers.CustomerController.Register()` action completes the registration successfully and writes all properties to the database. But then, the `Nop.Services.Messages.QueuedEmailService` tries to populate the **To:** field of the email and crashes. The limit of the **To:** field is 500 characters and this is what throws the DB exception.

**Steps to reproduce:**
1. Make sure the cart has sending emails enabled
2. Register a user with long first and last names
3. Observe the exception

**Improvement suggestion:**
Add more validations while registering or editing names. If there are some other actions which lead to adding first and last names, validate them too. Let's limit first and last names to 200 chars (no need for localization). Do it for registration page, customer info page, addresses (used during checkout)

Similar to #99

**Comment by AndreiMaz** [comment]
Similar to #1172
