### ISSUE TITLE
Rename TierPrices to something else (Advanced pricing)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1176]
Now it's not just "tier prices". It also allows to create customer prices per customer role. it'll also allow to create prices per custom periods (#365).

Maybe, we should find a better name for them? Suggestions?

'Advanced Pricing' as suggested in the comments would be great!

But maybe, we should leave it as it is now. Let's just create a new tab - "Prices" on the product details page. And move all price settings to it

**Comment by eadameg** [comment]
Suggestions: Special prices or Advanced pricing,

**Comment by illutian** [comment]
I'd vote for 'Advanced Pricing'. With a hyperlink -THAT SAVES THE PRODUCT- to take you to 'Advanced Pricing'.

Or, depending on how big of a change it'd be, You check 'Advanced Pricing' and it opens up another section...just like how "Require other products added to the cart" does when checked.

Just doesn't feel right to split up the pricing in the first place; you'd expect it to be all in one place.

**Comment by cybernexus** [comment]
I've been thinking about this and how it applies to the customization's I've made. In my opinion it feels like calculating pricing has become one of the most extremely complex code segments in the core installation Perhaps it might be doable to abstract it all away and create a core pricing engine that allows you to create pricing engine types that can be installed as plugins (with the defaults being, 'simple price','tier price', 'pricing by attribute combination','customer enters price', etc). Doing this would allow you could develop custom pricing scenario's that would have their own admin ui and portable  logic code base that outputs the needed price info for the core abstract engine. 

It seems like it might be a good deal of work and thought needed to achieve so this might be something to think about for version 4.0? Any thoughts or am I completely insane for even mentioning it!?

**Comment by eadameg** [comment]
Hi Cybernexus:
I fully agree with you. Furthermore I think this becomes much more complex when we take into account discounts and promotions. I feel this is an area that has to be rethought and V4.00 could be the moment.  Due to its relevance I suggest you post your suggestion as a new topic in the Nop forum

**Comment by samdubey** [comment]
Step Pricing
Row Pricing
Rank Pricing
Line Pricing
Group Pricing
Layered Pricing

Hope this helps for selection

**Comment by sukeshak** [comment]
I use it for setting up dealer pricing with Role criteria.
