### ISSUE TITLE
Preserve View Mode when navigating through catalog

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#119]
1. Allow a store owner to choose the default value in UI - move "catalogSettings.AllowProductViewModeChanging" setting to catalog settings page (admin area)
2. Let's make it configurable - Preserve View Mode when navigating through catalog

Source: http://www.nopcommerce.com/boards/t/39375/enhancement-preserve-view-mode-when-navigating-through-catalog.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by RomanovM** [comment]
See also https://www.nopcommerce.com/boards/t/62230/display-per-page-not-being-preserved.aspx
