### ISSUE TITLE
Flyout (mini) login box (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#12]
Just like the mini shopping cart, many websites have a mini login button also. I myself leave many website once I get redirected to a login page and then return to the home page and not the previous page before the login. 

As we hover on the Shopping cart link, in the same way the register link should also have a small flyout for login and should remain on the same page after authentication. 

Think how it would be better ti display external authentication methods such as Facebook, twitter, etc. Maybe, just add a "Login using other providers, etc" hyperlink to the login page if we have at least one external authentication methods

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
