### ISSUE TITLE
Logistic Integration

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1212]
As it is need of time, in nopCommerce there is payment gateway integration, but there is no logistics support. (The shipping calculation methods are only to calculate shipping rates). See examples from Shopify here (https://apps.shopify.com/delhivery-indian-logistics-service). You can integrate all the possible logistics partners all over world by creating the plugins for it. This will help the customer as well as admin to manage and track the delivery of products. 

Source:http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=4#158382

**Comment by AndreiMaz** [comment]
should be done as plugin

**Comment by shanthsp2002** [comment]
Hi @AndreiMaz ,

      Whats the status of this implementation? Eagerly waiting for this plugin, its very difficult to handle logistics without this ,  Almost every person using nope commerce  in India will need this. India is a huge market and not having this plugin in nope commerce will be a huge drawback . Please make sure this will be implemented.
