### ISSUE TITLE
Do not allow administrators to be impersonated as other administrators

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1224]
We should display as warning "Administrators cannot be impersonated as other administrators" when such attempt is made. We should validate "Administrators" customer role. The question is whether we should validate "access to admin area" permission? I think, yes. But in this case a store owner won't be able to impersonate as vendor.

Steps:
1)Login as administrator A
2)Impersonate B
3)Go to store frontend and there click Administration button to go back to the backend
4)Now user A has all permissions of B and all his activities will be registered in the log as activities of B

also see http://www.nopcommerce.com/boards/t/26096/acl-redundant-permissions-and-administrator-role-not-protected-properly.aspx

**Comment by SilhouetteBS** [comment]
If a user is impersonating another user, it would be nice if the system noted that some how so you could always go back and find out who did the impersonating.

**Comment by AndreiMaz** [comment]
@SilhouetteBS thanks! done
