### ISSUE TITLE
Pluggable price engine

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1235]
Adding this to the forums for a larger discussion.

I've been thinking about the price engine and how it applies to the customization's I've made. 

In my opinion it feels like price calculations have become one of the most extremely complex code segments in the core installation. Perhaps it might be doable to abstract it all away and create a core pricing engine that allows you to create pricing engine types that can be installed as plugins ('simple price','tier price', 'pricing by attribute combination','customer enters price', etc). Doing this would allow you to develop custom pricing scenario's that would have their own admin ui and portable logic code base that outputs the needed price info for the core abstract engine.

Source: http://www.nopcommerce.com/boards/t/40783/suggestion-plug-able-price-engine.aspx

**Comment by rudgr** [comment]
Would really like to have this feature! :)

http://www.nopcommerce.com/boards/t/43227/nopcommerce-custom-price-calculation-rules.aspx

I guess this won't make it to 3.80 ?

**Comment by dcbasstroosnijder** [comment]
This sounds like the perfect thing for a current project we are working on. Currently we have to check at every step (having event consumers on the shoppingcartitem) to make sure the price stays correct, we use customer enters price and fill it ourselfs.

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.

**Comment by rudgr** [comment]
sorry, I don't see how users could customize this without forking the source (which seems undesirable?) I mean, we need something to hook in to right?
