### ISSUE TITLE
Set default tax category for product

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1236]
Source: http://www.nopcommerce.com/boards/t/40789/suggestions-set-default-tax-category-for-product.aspx and http://www.nopcommerce.com/boards/t/33995/default-tax-setting-when-creating-a-new-product.aspx

Let's add a new tax setting - "Default tax category" (Select tax category pre-selected when creating a new product). This dropdownlist will also have "None" default item. Place it after "Force tax exclusion from order subtotal	"

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/10e7357c0d35c78fa7250d55fa52295882f8bf7d
