### ISSUE TITLE
Allow Topics to be used as Message tokens

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#125]
I've just been looking for an easy way to add a common footer to the messages sent to customers from the website and decided that the easiest way was just to create the email footer HTML as a topic and allow topics to be added as tokens in the message templates. There are a couple of plugins that offer message templating functionality beyond this level but the only one that I found that currently supports v3.6 didn't work for me so this is what I came up with. 

In MessageTokenProvider.cs add an extra method for adding the topic tokens: 

```
public virtual void AddTopicTokens(IList<Token> tokens, Store store) 
{ 
IList<Topic> topics = _topicService.GetAllTopics(store.Id); 

foreach (Topic topic in topics) 
{
tokens.Add(new Token(string.Format("Topic.{0}.Title", topic.SystemName), topic.GetLocalized(x => x.Title)));
tokens.Add(new Token(string.Format("Topic.{0}.Body", topic.SystemName), topic.GetLocalized(x => x.Body), true));
} 
} 
```

The AddTopicTokens method is called by the AddStoreTokens method (since that already runs for all sent messages) like: 
AddTopicTokens(tokens, store); 

The HTML topic body can then be used as a standard email footer just by adding a token to the message template in the format: %Topic.SystemName.Body% 

It would be easy to improve on this but it gives a good level of functionality for minimal changes to the current code and means it's possible to make changes to the footer in a single place rather than having to edit each message template individually. 

Source: http://www.nopcommerce.com/boards/t/37686/suggestion-allow-topics-to-be-used-as-message-tokens.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
