### ISSUE TITLE
Customer settings - default hash format

### ISSUE THREAD

**Issue by f1ana** [nopSolutions/nopCommerce#1259]
Hello,

Just a suggestion, but the default hash format for customer passwords (SHA1) may need to be changed in the future to something stronger, such as SHA256.  In addition, the salt produced is only 40 bits.  It would be nice if that were 64 bits or higher.
With respect to the hash format, it seems like this change would need special care to only be implemented for new installations only.

-Chris

**Comment by AndreiMaz** [comment]
duplicates #295
