### ISSUE TITLE
PayPal Standard - Multi-currency and dollar limit support

### ISSUE THREAD

**Issue by f1ana** [nopSolutions/nopCommerce#1269]
Please refer to this page:
https://developer.paypal.com/docs/classic/api/currency_codes/

There is the potential in nopCommerce, in some currencies, to fail to process payments.  The methods in the PayPal Standard plugin are generally converting amounts to "0.00" format, meaning two decimals.  Some currencies, like HUF, JPY, TWD, LRY do not accept decimal amounts.  Other currencies have a per-transaction limit, which probably will never be encountered, but should be addressed as well.
JPY - 1,000,000 limit
USD - 10,000 limit

**Comment by AndreiMaz** [comment]
duplicated
