### ISSUE TITLE
Remove packages from source control.

### ISSUE THREAD

**Issue by SamPlusPlus** [nopSolutions/nopCommerce#1283]
We should remove the packages from source control and rely on nuget to fetch them. Maybe only exception is nopCommerceCustom, but I would argue that could become it's own package too.

also see http://www.nopcommerce.com/boards/t/45776/could-remove-nuget-packages-folder-from-git-source-repo-to-reduce-repo-size.aspx

**Comment by jeremypaskalicimpress** [comment]
Yea, it would be best to have all third-party dependencies fetched at dependency retrieval time.

**Comment by SamPlusPlus** [comment]
@AndreiMaz I would be willing to do this work, if you are willing to except a pull request.  Can you share some insight if there was a reason packages were committed to source control to begin with?

**Comment by AndreiMaz** [comment]
done
