### ISSUE TITLE
Allow a store owner to specify rules (allowed chars, etc) for usernames

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#129]
Let's define them on the customer settings page (when usernames are enabled)

Is it better for a store owner to enter a regex expression? If yes, then ensure that no exception is thrown when wrong regex is specified

Source: http://www.nopcommerce.com/boards/t/37354/nop-360-username-have-space-issue.aspx

also see http://www.nopcommerce.com/boards/t/45792/username-issues.aspx

**Comment by skoshelev** [comment]
Closed #129
