### ISSUE TITLE
Track download history (IP address and date)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1290]
Could you add ip address and date of download, to downloadable products?

One of our customers had to send to paypal such a data, because of dispute with own customers. Such information like IP and time of download was required by payment provider.

And http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=14#163981

[AM] Let's implemented as poyker suggested (in the comment below). See related issue #1297 (should be done first)

**Comment by poyker** [comment]
We use the Activity Log for keeping track of the downloaded products from our website.
So you can have a new activity type i.e "Public Store. Download product" and then write in the Activity Log when a customer downloads a product. This way you will have the exact time. The IP could be added in the Log message as well as the name of the downloaded product.
