### ISSUE TITLE
Move first and last name to the Customer record

### ISSUE THREAD

**Issue by oumiller21** [nopSolutions/nopCommerce#1294]
I think since the First Name and Last Name fields are always required when creating a new customer they should be moved to the customer record. Company name is also important for B2B organizations and even though it may not be required for everyone, the gains you will get on the backend through the Customer and Order searches on large data sets will be well worth the effort. 

The changes will also make this issue [Search by Customer First or Last Name Under 'Orders' ](https://github.com/nopSolutions/nopCommerce/issues/996) easier to implement.

**Comment by poyker** [comment]
Agree. First name, last name and maybe email should not be generic properties but be part of the customer. This will make the search for customers by name, email much easier.
