### ISSUE TITLE
Azure Blob. Set CacheControl

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1296]
Contribution: http://www.nopcommerce.com/boards/t/41131/azure-blob-cachecontrol.aspx

[AM] I think we should not hard-code it and use "clientCache" attribute in web.config. Or make it somehow configurable. For example, add a string setting that will be used (if specified)

**Comment by lintho** [comment]
So, this wont be coming in 3.9?

**Comment by lintho** [comment]
Amazing work guys!
