### ISSUE TITLE
Serving static content from Azure CDN

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#1299]
I think it will be great to be able to serve static content from Azure CDN. Now we can only serve dynamic contents via azure blobs but need to find a way to serve static content as well.

**Comment by kwestground** [comment]
I have same problem when using Roxy Fileman and having continuous deployment connected to Azure App Services. First step would be to abstract File access into an FileService. So you can implement an Azure CDN File Service similar to AzurePictureService.

**Comment by dorofeev-serdg** [comment]
What exactly should be done as a part of this ticket?
If it's required to configure an Azure CND Endpoint for the nopCommerce, then it should be done from the azure portal. Here's a description, how to do it
https://docs.microsoft.com/en-us/azure/cdn/cdn-add-to-web-app

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality
