### ISSUE TITLE
Ability to generate massive and personalized discount coupons

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#13]
Let's discuss it first 

Forum source: http://www.nopcommerce.com/boards/t/18705/suggestion-a-simple-way-to-generate-massive-and-personalized-discount-coupons.aspx and http://www.nopcommerce.com/boards/t/18705/suggestion-a-simple-way-to-generate-massive-and-personalized-discount-coupons.aspx?p=2#171255

**Comment by aabozkurt** [comment]
Is it going to be implemented in 3.80?

**Comment by rudgr** [comment]
any news if this will be included in 4.0?

also I would like to add option to import unique codes from excel


tx

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leaving it for customization

Furthermore, it's already available as a plugin - https://www.nopcommerce.com/en/discount-coupon-generator
