### ISSUE TITLE
Fix for bug in GetCurrencyString in PriceFormatter

### ISSUE THREAD

**Issue by turbochris** [nopSolutions/nopCommerce#1307]
I've played around with custom currency format. I wanted to display "C0" and I discovered that the method did not format the currency correct..

So this is the original snippet in GetCurrencyString:

```
  if (!String.IsNullOrEmpty(targetCurrency.CustomFormatting))
            {
                //custom formatting specified by a store owner
                result = amount.ToString(targetCurrency.CustomFormatting);
            }
```
I have changed it to this:

```
 if (!String.IsNullOrEmpty(targetCurrency.CustomFormatting))
            {
                //custom formatting specified by a store owner
                result = amount.ToString(targetCurrency.CustomFormatting, new CultureInfo(targetCurrency.DisplayLocale));
            }
```

It now works as intended. So my test was for swedish kroner:

Before it would for swedish kroner write "$866" for "C0" in format string for  that currency. After corrections it writes "866 kr" as it should.

_____________
Let's investigate it

**Comment by AndreiMaz** [comment]
just enter "0 kr" instead of "C0"
