### ISSUE TITLE
Integration with Orchard

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1308]
As announced on nopdevdays'2015. We can significantly help these CMS and us

Also see #63

**Comment by devustocomp** [comment]
what en detail was announced/discussed?

**Comment by compito** [comment]
I think that some other possibilities would be even more interesting. Orchard and Umbraco are great products, but can be way to complex to deal with. We should have an option for really powerful and simple CMS where we could define custom types/pages and be very flexible. Shared authentication for example is good to have, navigation control, etc. Kind of a "pluggable" CMS. 

One that comes to mind is definitely Piranha CMS, it's really nice system and is going to be even better... Just check it out at https://github.com/PiranhaCMS, especially the piranha.core project.
There are probably many other systems, but Piranha is nice and lean and pluggable.

**Comment by AndreiMaz** [comment]
should be done as plugin
