### ISSUE TITLE
Prevent cookie replay attacks (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#131]
The issue with approach below is that it'll cause logouts after each application restart. So we should make it configurable (disabled by default). 

Contribution: http://www.nopcommerce.com/boards/t/36192/security-issues-on-version-350.aspx but it works only for admin area. So I've attached my version of FormsAuthenticationService class. But it doesn't work now because session is not available  during authentication yet. The only solution here is to store session GUID and "valid until" in "Customer" table. Reset it when a customer logouts

[FormsAuthenticationService.zip](https://github.com/nopSolutions/nopCommerce/files/533445/FormsAuthenticationService.zip)

It already can fixed quite easily by enabling SSL for the entire site. And no extra coding is required (and more secure)

also see http://stackoverflow.com/questions/16062808/form-authentication-cookie-replay-attack-protection

**Comment by AndreiMaz** [comment]
just enable SSL for the entire site it many sites do nowadays
