### ISSUE TITLE
Maintenance page. Add "Re-index tables" functionality

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1322]
Let's do it the same way as it was implemented in version 1.90 (stored procedure)

similar task https://github.com/nopSolutions/nopCommerce/issues/2921

**Comment by illutian** [comment]
*Possibly a way to delete images that are no longer used
((Nop keeps images even if the item that used the image is removed))
*Delete the ***_<image dimension>.jpeg/gif/png images that are created dynamically as visitors call up images
((Nop is quickly filling the 000,001,002 folders with images; filling the webserver's drive))

**Comment by DmitriyKulagin** [comment]
Closed #1322
