### ISSUE TITLE
Allow customers to purchase reward points (account balance)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1323]
This way customers will be able to purchase reward points and spend them later

Something similar to http://addons.prestashop.com/en/19143-personal-purse-of-the-buyer-prepayment-account.html (we already have reward points supported)

**Comment by sreesudey** [comment]
will the reward point remain integer or it will be updated up to 2 decimal places. e.g. if customer buy a product of X.XX amount. or this need to be updated in exchange rate.
Thanks

**Comment by shababnet** [comment]
some currency have 3 decimal places if we will use reward points as account balance need to be 3 or 4 decimal places.

Thanks

**Comment by GoldenRabbit** [comment]
how can the customers purchase reward points in nopcommerce ("This way customers will be able to purchase reward points and spend them later") ? is there any payment method for this? please advice.

**Comment by AndreiMaz** [comment]
duplicated - https://github.com/nopSolutions/nopCommerce/issues/1919
