### ISSUE TITLE
Admin approval, account activated emails missing

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#1328]
There are no emails being sent to the customer on registration, if you set admin approval registration method.

There should be an email sent when the customer registers, telling him his account awaits admin approval. And after the account has been activated, there should be another email sent to the customer (actually admin already can send "welcome email" after approval in admin area)

**Comment by AndreiMaz** [comment]
We already display a message to a customer (after registration) that his account will be activated by a store owner.

And we also have "Send Welcome Message" button on the customer details page in admin area. It's used to notify a customer when his account is activated

**Comment by shurub3l** [comment]
I think the welcome email should be sent automatically upon account activation.
