### ISSUE TITLE
Use product sliders (such as Featured Products, Related Products, New Products, Cross- Sells, etc)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1330]
It would be really nice if product sliders were added to the different aspects of the nopCommerce default theme. Such as Featured Products, Related Products, New Products, Cross- Sells, etc.

Source:http://www.nopcommerce.com/boards/t/41346/add-product-sliders-to-default-theme.aspx

**Comment by bulutkartal** [comment]
This would also be great if it has continuous loop :smile:

**Comment by suloveoun** [comment]
@bulutkartal support u :dart:
