### ISSUE TITLE
refname HEAD is ambiguous 

### ISSUE THREAD

**Issue by odises** [nopSolutions/nopCommerce#1331]
Hey Guys;
There is a tag has been created on Feb 1, 2016 named **HEAD** that is causing a problem.

Reproduction:

1. `git clone 'cloneurl'`
2. `git checkout -b something`

Result:

- warning: refname 'HEAD' is ambiguous.
- fatal: Ambiguous object name: 'HEAD'.

And when you remove this tag, the problem will be solved.
`git tag -d HEAD`

**Comment by AndreiMaz** [comment]
thx
