### ISSUE TITLE
Home Page Categories model cache issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1336]
a customer of ours reported an issue, that I tested after that and seemed really odd. When you setup a Home Page Categories panel, then change the dimensions of the images from the Media Settings (Category thumbnail image size) and click Save, nothing actually happens. No matter how many times you refresh the page, the setting doesn't do anything. That is really inconsistent with the way the other Media Settings work and even the rest of the Administration. 

What fixed it was clicking Clear cache/Restart application and then if you refresh the page you will see the new dimensions of the category images. It turns out that the HomepageCategories action caches the whole list of category models and after the media settings are changed, the model is taken from the cache. 

I think it is more intuitive to have this settings' effect visible immediately, without the need of something as major as Clear cache/Restart application.

Source: http://www.nopcommerce.com/boards/t/41393/home-page-categories-model-cache.aspx

**Comment by skoshelev** [comment]
Resolved #1336
