### ISSUE TITLE
PayPalDirect enable partial refund (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#134]
Source: http://www.nopcommerce.com/boards/t/35964/paypaldirect-enable-partial-refund.aspx#148140 (see the latest post by "a.m.": 

We should investigate possible scenario when refund is made twice (only on nopCommerce site - plugin and IPN). If it's so we should use "response.RefundTransactionID" 

```
if (refundPaymentRequest.IsPartialRefund)
        {
            //partial
            req.RefundTransactionRequest.RefundType = RefundType.PARTIAL;
            req.RefundTransactionRequest.Amount.currencyID = PaypalHelper.GetPaypalCurrency(_currencyService.GetCurrencyById(_currencySettings.PrimaryStoreCurrencyId));
            req.RefundTransactionRequest.Amount.value = refundPaymentRequest.AmountToRefund.ToString();
        }
        else
        {
            //full
            req.RefundTransactionRequest.RefundType = RefundType.FULL;
        }
```

**Comment by f1ana** [comment]
Please see #1268 for a proposed solution.  Please note that I used a different method for determining the currency ID.  I am using the currency code within the Order table and mapping to the PayPal currency ID.  This should cover a case of a store accepting more than one type of currency.
