### ISSUE TITLE
Ability to localize URLs like login, register, contact us, ... (SEO)

### ISSUE THREAD

**Issue by odises** [nopSolutions/nopCommerce#1344]
Users (non-english languages) should be able to rewrite static routes in RouteProvider.cs to get better results in search engines. (Localized Internal Site Links For Top Search Results)

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.
