### ISSUE TITLE
"Require other products added to the cart". Remove required products from the cart if the main one is removed

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1348]
If the customer changes his mind and removes the main product from the cart the required product is still displayed in cart contents. Correct behavior is the required product be also removed from the cart when the customer has removed the main product from the cart.

ensure that circular reference won't happen

Source: http://www.nopcommerce.com/boards/t/40596/bugnop-37-require-other-products-added-to-the-cart.aspx#165822

Let's make it configurable (disabled by default) - "Remove required products from the cart if the main one is removed" cataglo setting

**Comment by skoshelev** [comment]
Closed #1348
