### ISSUE TITLE
Use Same Terminology for Terms of Service

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#135]
When looking at the Order Settings page there are two settings that refer to showing "Terms of Service". When enabled and browsing the public site and checking out, it also refers to "Terms of Service". When looking at Topics in the admin console though, the topic that "Terms of Service" links to is called "Conditions of Use". It would be less confusing if they were all called either "Terms of Service" or "Conditions of Use". 

There should also be instructions when setting up the catalog settings as to where the terms of use are set up. 

Source: http://www.nopcommerce.com/boards/t/35378/use-same-terminology-for-terms-of-service.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
