### ISSUE TITLE
"Buy Button" should be re-enabled after canceling the order contains stock managed product

### ISSUE THREAD

**Issue by odises** [nopSolutions/nopCommerce#1355]
- Assume **Stock quantity** is set to **10** for a product, and **Minimum stock availablity** is **0**, and also **Low stock activity** is set to **Disable buy button**.
- A user buys all the **10**.
- **Reserved quantity** automatically will be set to **10**.
- And then **Add to Cart** button becomes disabled.
- Admin cancels the order.
- Reserved quantity returns to **0**.
- But the product's **Add to Cart** button is still unavailble. (event after cleaning the cache or restarting the application)

**Comment by odises** [comment]
After reporting this issue I noticed that there is an advanced setting for this to republish product (PublishBackProductWhenCancellingOrders). But I believe it's hard to find this setting for users. So I made a pull request and put this in Catalog setting.

**Comment by AndreiMaz** [comment]
thanks.
