### ISSUE TITLE
Estimate shipping with AJAX

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1357]
several times we've received complaints from customers about the fact that when you are on a smaller mobile device and click on estimate shipping (shopping cart page), the page reloads, you are taken to the top of the page and you need to scroll back down to the Estimate shipping block which is both tedious and confusing. 

This does not pose such a problem on desktop, because of the bigger viewport. However, since nopCommerce is Mobile First now and the percentage of shoppers on mobile devices increases further and further, to the point where they become the majority, I think it is essential that nopCommerce provides smoother UX for small screens.

I suggest implementing AJAX (with a loading animation in the element) for such actions (estimate shipping, discount code etc.) to eliminate the reload and tedious scrolling and show the information immediately, saving the customer time and effort.

Source: http://www.nopcommerce.com/boards/t/41561/estimate-shipping-with-ajax.aspx

do not forget about loading icons, etc

**Comment by suloveoun** [comment]
Ah, I want to report it too but now it become reality. Thank for taken immediately fixed.

**Comment by AndreiMaz** [comment]
displayAjaxLoading
