### ISSUE TITLE
Ensure that a store owner cannot open configuration pages of uninstalled plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1361]
Recently I see this thing. If I call HTTPGET method of a uninstalled plugin controller, it works. I have checked that issue in visual studio. Is this also happened in live server? I dont get chance to check in live server.

Source: http://www.nopcommerce.com/boards/t/41564/get-method-of-uninstalled-plugin.aspx

**Comment by odises** [comment]
I checked it in live server. For example I uninstalled PayPalDirect plugin.
But its configuration page (/Admin/Payment/ConfigureMethod?systemName=Payments.PayPalDirect) redirected me to payment methods list page (/Admin/Payment/Methods).
I also checked it for other kinds of plugins (shipping, etc). @AndreiMaz
