### ISSUE TITLE
robots.txt sitemap https

### ISSUE THREAD

**Issue by zstomp** [nopSolutions/nopCommerce#1370]
robots.txt `Sitemap` entry does not adhere to the store's "require HTTPS" setting. This causes an unnecessary HTTP to HTTPS redirect when the sitemap is accessed.

Actually, since you cannot seem to add HTTPS URLs as site maps to Google Search Console, it would be better to allow accessing the site map via HTTP even if HTTPS is required for the store.

**Comment by DaveHogan** [comment]
@zstomp - Not sure what version you're referring too, but the latest tagged release 3.70 doesn't forward the sitemap.xml over HTTPS as it's decorated with `[NopHttpsRequirement(SslRequirement.No)]`

https://github.com/nopSolutions/nopCommerce/blob/f6b7de7f18b2f8c713ecdf0292aacc71ca23019c/src/Presentation/Nop.Web/Controllers/CommonController.cs#L734

As you mentioned, it's desirable for sitemap.xml to be served over HTTP.

**Comment by zstomp** [comment]
My version is 3.70, and it does redirect to HTTPS. I figured out how to set it up at Google, but let me know if you want to find out why I get the redirect.
