### ISSUE TITLE
SystemKeyword for attributes 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1378]
SystemKeyword is a column used in ActivityLogType, MeasureDimensionTable, MeasureWeight, and Poll tables.

As I understand it, it is intended as a programmatic Id, a way to lookup a the numeric ID for named entities. I'd called this field ProgName (Programmatic Name). The idea is that you have a name that you use in SQL statements or a constant in code that will allow you to refer to a specific entity, even make decisions based on it.

I believe such functionality should also be available for other entities, like SpecificationAttribute and SpecificationAttributeOption - add a SystemKeyword to these tables with optional values.

Source: http://www.nopcommerce.com/boards/t/41742/systemkeyword-for-attributes-suggestion.aspx

**Comment by vasilisf** [comment]
Hello, 

Such an option would be really useful.
It would be a nice idea to add that at the ShippingMethod too.

**Comment by zootie** [comment]
Nearly every entity that has a Name should have a way to refer to it programmaticaly. 
Just came across PO Numbers being stored in localized XML keys?! Why is this such a difficult concept for nopC? Why oversimplifiying everything around a single, user changeable name that makes customization a nightmare?
