### ISSUE TITLE
Display order/payment/shipping statuses on order list and order details pages (public store)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#138]
Appoproate properties already exist. But they are not used in apporpriate cshtml file. 

let's make it configurable 

Source: http://www.nopcommerce.com/boards/t/32828/feature-payment-status-and-shipping-status-on-order-details-and-pdf.aspx#134250

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
