### ISSUE TITLE
Allow to extend GetListOfCampaignAllowedTokens and GetListOfAllowedTokens methods

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1381]
Right now a developer can add new tokens using EntityTokensAddedEvent or MessageTokensAddedEvent. But we should also allow them to extend GetListOfCampaignAllowedTokens and GetListOfAllowedTokens methods. 

And not by creation of a new class derived from MessageTokenProvider and further override of these methods. It should be done using events

**Comment by skoshelev** [comment]
Closed #1381
