### ISSUE TITLE
Refactoring. Merge functionality SaveSetting and DeleteSetting of IsettingService.

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#1382]
For example, you can create an extension method:
```

public static void SettingUpdate<T, TPropType>(this T settings, ISettingService settingService,
    Expression<Func<T, TPropType>> keySelector, bool overrideForStore, int storeScope, bool clearCache)
    where T : ISettings, new()
{
    if (overrideForStore || storeScope == 0)
        settingService.SaveSetting(settings, keySelector, storeScope, clearCache);
    else if (storeScope > 0)
        settingService.DeleteSetting(settings, keySelector, storeScope);
}
```

Then we can replace this code:

```
if (model.ProductThumbPictureSize_OverrideForStore || storeScope == 0)
    _settingService.SaveSetting(mediaSettings, x => x.ProductThumbPictureSize, storeScope, false);
else if (storeScope > 0)
    _settingService.DeleteSetting(mediaSettings, x => x.ProductThumbPictureSize, storeScope);
```

On that:

`mediaSettings.SettingUpdate(_settingService, x => x.ProductThumbPictureSize, model.ProductThumbPictureSize_OverrideForStore, storeScope, false);`

**Comment by AndreiMaz** [comment]
/// <summary>
        /// Save settings object (per store)
        /// </summary>
        /// <typeparam name="T">Entity type</typeparam>
        /// <typeparam name="TPropType">Property type</typeparam>
        /// <param name="settings">Settings</param>
        /// <param name="keySelector">Key selector</param>
        /// <param name="overrideForStore">A value indicating whether to setting is overridden in some store</param>
        /// <param name="storeId">Store ID</param>
        /// <param name="clearCache">A value indicating whether to clear cache after setting update</param>
        public virtual void SaveSettingPerStore<T, TPropType>(T settings,
            Expression<Func<T, TPropType>> keySelector,
            bool overrideForStore, int storeId = 0, bool clearCache = true) where T : ISettings, new()
        {
            if (overrideForStore || storeId == 0)
                SaveSetting(settings, keySelector, storeId, clearCache);
            else if (storeId > 0)
                DeleteSetting(settings, keySelector, storeId);
        }

**Comment by AndreiMaz** [comment]
/// <summary>
        /// Save settings object (per store). If the setting is not overridden per storem then it'll be delete
        /// </summary>
        /// <typeparam name="T">Entity type</typeparam>
        /// <typeparam name="TPropType">Property type</typeparam>
        /// <param name="settings">Settings</param>
        /// <param name="keySelector">Key selector</param>
        /// <param name="overrideForStore">A value indicating whether to setting is overridden in some store</param>
        /// <param name="storeId">Store ID</param>
        /// <param name="clearCache">A value indicating whether to clear cache after setting update</param>
        public virtual void SaveSettingOverridablePerStore<T, TPropType>(T settings,
            Expression<Func<T, TPropType>> keySelector,
            bool overrideForStore, int storeId = 0, bool clearCache = true) where T : ISettings, new()
        {
            if (overrideForStore || storeId == 0)
                SaveSetting(settings, keySelector, storeId, clearCache);
            else if (storeId > 0)
                DeleteSetting(settings, keySelector, storeId);
        }
