### ISSUE TITLE
Taxes. Rounded Then Totaled or Totaled Then Rounded?

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1387]
Source: http://www.nopcommerce.com/boards/t/41788/tax-penny-issue.aspx

Let's investigate it

**Comment by MarkoKrstic** [comment]
Anything new about this? Thanks

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/3949
