### ISSUE TITLE
Customer list page (admin area). Allow filterting by custom customer attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#139]
Source: http://www.nopcommerce.com/boards/t/32888/suggestion-custom-customer-attributes-upgrade.aspx

Similar to https://github.com/nopSolutions/nopCommerce/issues/144

Let's consider this issue after #2830

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
