### ISSUE TITLE
Drop "AuthorizationTransactionCode" property of "Order"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1396]
Anyway it's not used somehow. We already have AuthorizationTransactionId and AuthorizationTransactionResult for other purposes

Let's investigate it

**Comment by odises** [comment]
For some payment methods its necessary to persist more than two or three value (callback result and etc). So I think keeping fields like this is not a bad idea just as a reserved field. Of course in my case I'm storing a bunch of data in JSON or XML format in AuthorizationTransactionResult.
