### ISSUE TITLE
Magnifying product pictures

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#14]
Magnifying capability when hovering over a product picture. Right now we have a setting to show a popup window. Let's extend the existing setting to support three behaviours - "do nothing", "display popup", "zoom/magnify" (the new one)

Forum source: http://www.nopcommerce.com/boards/t/14518/enhancement-hovering-over-additional-photos-needs-to-change-the-main-product-picture.aspx 

Zoom and magnifying (below): 
Here is a contribution - http://nopcommerce.codeplex.com/SourceControl/network/forks/breakskater/zoomlens 

Here is one more contribution http://www.nopcommerce.com/boards/t/9904/zoom-professor-cloud-integration-working-fine.aspx 

http://www.nopcommerce.com/boards/t/19134/a-zoom-of-a-project.aspx

See related work item https://github.com/nopSolutions/nopCommerce/issues/2186

**Comment by tigran-avdalyan** [comment]
for example: https://www.flipkart.com/samsung-galaxy-on5-gold-8-gb/p/itmedhx3uy3qsfks?pid=MOBECCA5FHQD43KA&srno=b_1_1&otracker=nmenu_sub_Electronics_0_Samsung&lid=LSTMOBECCA5FHQD43KAIOIURP

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leaving it for customization

Furthermore, it's already available as a plugin
