### ISSUE TITLE
Multiple rating values (configurable)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1405]
Right now customers can set only one rating (from 1 to 5) and write a review. Allow a store owner to configure multiple rating lists (name, description). For example,

- Accuracy rating (indicate how close the product's condition received by customer is the same as its described in detail page)
- Quality rating (indicate the product quality)
- etc
By default we'll have only one rating value (like it's already done now)

Right now we have reviews settings in admin area > configuration > settings > catalog settings. Maybe, we should create a new page for reviews (e.g. Prouct review settings)? Or just leave all of them on the catalog settings (IMHO, a little bit bloated) and add a new grid with multiple rating lists to them as well? Let's discuss.

Also update admin area > catalog > product reviews page. Display all values in the grid. And don't forget about product review details page (in admin area)

Let's discuss and decide how we should calculate total product rating (affect perfomance). Maybe, if we have multiple ratings, then store only one "average" one for product review. This way we won't have to change much logic when calculating current product ratings and reviews. And entered ones will be stored in a new table

**Comment by DmitriyKulagin** [comment]
Closed #1405
