### ISSUE TITLE
Performance. Move away from AutoMapper

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#141]
We can also easily replace AutoMapper with some other mapper (e.g. http://www.nopcommerce.com/boards/t/30596/automapper-could-leak-to-memory-leaks.aspx) 

but first, let's ensure that it's really slow. after some investigation (remove automapper, tested in red-gate memory profiler) I've found out that it works just fine and does not effect performance (about 1-2%) 

See http://www.nopcommerce.com/boards/t/30596/automapper-could-leak-to-memory-leaks.aspx 

also http://endyourif.com/automapper-performance-testing/ 

also http://www.andriybuday.com/2010/02/question-about-automapper-performance.html 

UPDATE: see comment by "m1dst" below - https://lostechies.com/jimmybogard/2016/06/24/automapper-5-0-speed-increases/

also see post about ExpressMapper - http://www.nopcommerce.com/boards/t/45977/memory-leak-on-38.aspx#182754 (not actively developed)

**Comment by AndreiMaz** [comment]
Comment by sergey koshelev: Я прогнал код через профайлер (Red Gate). С памятью я до конца не разобрался, но похоже он ничего лишнего не сохраняет, только информация о методах рефлексии. По производительности вообще все ровно, он не тратить процессорное время вовсе. Профайлер говорит что нужно ускорять метод Nop.Services.Tasks.Task.Execute и больше пока ничего.

**Comment by m1dst** [comment]
Before we get too excited about replacing AutoMapper please read https://lostechies.com/jimmybogard/2016/06/24/automapper-5-0-speed-increases/

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box
