### ISSUE TITLE
Ability to search all settings.

### ISSUE THREAD

**Issue by SamPlusPlus** [nopSolutions/nopCommerce#1411]
Currently in the admin control panel there are over 500 settings, It would be nice to be able to search and filter these settings in an easy manner.

**Comment by odises** [comment]
@SamPlusPlus there is an other issue for this feature #1142.

**Comment by SamPlusPlus** [comment]
@odises thanks for pointing this out.

Closing as duplicate see issue #1142

**Comment by odises** [comment]
@SamPlusPlus your welcome!
