### ISSUE TITLE
Admin area. Remove extra spaces from some "onclick" event handlers

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1419]
example, onclick = " event "; in  _OrderDetails.Info.cshtml  and other files

**Comment by MaxMommersteeg** [comment]
I couldn't find any extra spaces around onclick events at _OrderDetails.Info.cshtml. Even was not able to find any other places in the whole Nop.Admin project that had extra spaces? Has this issue already been resolved?
