### ISSUE TITLE
TinyMCE picture browser does not work in a virtual directory and plugins

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#142]
TinyMCE picture browser does not work in a virtual directory. Now a store owner have to edit the \Administration\Views\Shared\EditorTemplates\RichEditor.cshtml file. Just uncomment the code below:

```
//allowJbimages = true;
//allowRoxyFileman = false;
```

in order to support ANY picture uploading (not picture browsing). 

We should find a way to detect whether a site is run in a virtual directory. And then configure \Administration\Views\Shared\EditorTemplates\RichEditor.cshtml file based on it. How can it be done programmatically? 

also see http://www.nopcommerce.com/boards/t/35370/virtual-directory-not-included-in-the-images-urls.aspx and http://www.nopcommerce.com/boards/t/35370/virtual-directory-not-included-in-the-images-urls.aspx#177873 (contribution to be checked)

regarding plugins - http://www.nopcommerce.com/boards/t/42272/error-at-richeditor-at-arvixe-server.aspx
![roxy_file_man](https://cloud.githubusercontent.com/assets/5019111/15934339/e4704598-2e6b-11e6-9f9f-a56ba93b23c4.png)

**Comment by AndreiMaz** [comment]
под вопросом надо ли
