### ISSUE TITLE
 "My Product Reviews" in "my account" (contribution)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1420]
Another minor enhancement I'd like to see would be to add a new navigation item in the customer account for "My Product Reviews." 

It is important now because it is possible for customers to earn Reward Points for giving product reviews. Customers need an easy way to see a list of which products they have already reviewed.

This view would display a list of all reviews created by this customer. The list should include columns with Product name, Date Reviewed, and Current Approval Status (Approved/Disapproved). Maybe also include paging for list..some admins have many products.

Contirbution (see whether it's good and could be merged): https://github.com/nopSolutions/nopCommerce/pull/1440

**Comment by DaveHogan** [comment]
Is this up-for-grabs @AndreiMaz

**Comment by AndreiMaz** [comment]
@DaveHogan hi. yeah. this work item is not assigned yet

**Comment by DaveHogan** [comment]
@AndreiMaz - assign to me. I'll be happy to pick this up.

**Comment by AndreiMaz** [comment]
@DaveHogan please create a fork. If it's good, then we'll merge it. thanks
