### ISSUE TITLE
Add the ability to create tabs through plugin regardless of the presence of tabs on the page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1422]
We can add a tab through plugin only if target page contains tabs using AdminTabStripCreated event. But we need to be able to add it to pages which doesn't contain tabs. It means that if we have no tabs on then we should create it.

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/488
