### ISSUE TITLE
Customer reward points. Rename "Add points" to ""Add/Remove Points"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1423]
On Admin >> Customers >> Edit screen >> Reward Points tab, it would be very helpful if there was also a way to remove reward points from the customer account. Either similar to the current "Add Points" form, or maybe just a in-line delete button on each row of the list of points customer has earned.

Currently, the only solution is to find the record in the database table and delete it manually...which is very tedious.

-------------
Nevermind..
I feel so stupid.
I did not realize the "Add Points form accepted negative values until a minute after I posted this suggestion... (embarassed)

Maybe, however, it would be wise to change the button text to "Add/Remove Points" so admins like me understand that the form can do both tasks.

**Comment by infinito62** [comment]
Great feature! The only way now is to load negative points. An unelegant workaround
