### ISSUE TITLE
More user friendly way to remove a product from cart

### ISSUE THREAD

**Issue by ratulbside** [nopSolutions/nopCommerce#1425]
A user can remove a product from shopping cart by selecting desired product under 'Remove' column and pressing 'Update Shopping Cart'. But from my real life experience, I recognize that most end user doesn't understand how to remove a product from cart. It will be very user friendly if a direct remove button will be placed instead of check box for each product.

**Comment by praveenksharma** [comment]
Exactly. I was confused myself years back when I started with NopCommerce. @AndreiMaz Please give us the option to have a button there instead of checkbox.

Thanks
