### ISSUE TITLE
Allow a store owner to filter by checkout attribute on the order list page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#144]
Make checkout attribute filterable on orders. Once done we should also update appropriate reports in the "order list" grid (summary)

Similar to https://github.com/nopSolutions/nopCommerce/issues/139

Let's consider this issue after #2830

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
