### ISSUE TITLE
Show product count beside each specification attribute (used for filtering on category details page)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#145]
Show product count beside each specification attribute (used for filtering on category details page). This option should be configurable 

Forum source: http://www.nopcommerce.com/boards/t/15464/25-performance-filtering-using-specification-attributes.aspx#64137

We should think how optimize it (cache). It could be quite resource consuming. 

This option should also be configurable (enabled by default).

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
