### ISSUE TITLE
English grammar. Should we write "product number" or "number of products" or "product count"?

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1450]
Assistance from native English speakers is highly appreciated

We have a lot of such comments (search by "product number"). For example, " Gets product number by vendor identifier". Should we write it this way?

**Comment by JorneDeRoeck** [comment]
Hey Andrei,

If you refer to the product ID as "product number" i would keep it as simple as:

search by "product ID" or Get product ID by vendor identifier.

that way it stays self-explanatory

**Comment by m1dst** [comment]
Sounds like you should be writing "number of products" or even "# products" unless as JorneDeRoeck says you are referring to the Id.

**Comment by AndreiMaz** [comment]
thanks a lot, guys!
