### ISSUE TITLE
Hide Downloadable Products and Back In Stock Subscription URL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1452]
When we hide two URLs from "My Account" we are still able to enter these pages. We should validate appropriate settings when opening them. If not allowed, then redirect to "Customer info" page

Source: http://www.nopcommerce.com/boards/t/42135/hide-downloadable-products-and-back-in-stock-subscription-url.aspx

**Comment by skoshelev** [comment]
For Back In Stock Subscription already implemented

**Comment by skoshelev** [comment]
Closed #1452
