### ISSUE TITLE
Performance. Add support for "async" for javascript files

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1455]
1. We should do it when files are NOT bundled
2. Do it for both "Add" and "Append" script methods (just add a new bool parameter)

Source: http://www.nopcommerce.com/boards/t/40012/htmlappendscriptparts-scripts-are-in-wrong-order.aspx#168782

**Comment by agametov** [comment]
Add support "async" attribute when are not bundled and bundling is disabled, added new bool parameter **isAsync,** 
more info [https://github.com/agametov/nopCommerce/tree/Task_N1455](https://github.com/agametov/nopCommerce/commit/214997d10b4b277390fb71259c495316fcb9fb1d)

If all is well, I will make a pull request.

**Comment by AndreiMaz** [comment]
Hi Rustam,

Looks good. Please make the the pull request.

P.S. Спасибо

**Comment by agametov** [comment]
Ok, thx
