### ISSUE TITLE
Double click at confirm button during checkout

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1456]
Not sure whether anyone notice that, when accidentally click twice at the confirm button, it will direct you to a empty cart screen, but I was expecting a payment screen.

This may be a minor bug, but might affect the user experience.

Source: http://www.nopcommerce.com/boards/t/42164/double-click-at-confirm-button-during-checkout.aspx

also http://stackoverflow.com/questions/8757963/avoiding-duplicate-form-submission-in-asp-net-mvc-by-clicking-submit-twice

**Comment by Xzelsius** [comment]
A similar bug exists for customer registration.
The same script should work there too.
