### ISSUE TITLE
Get 100 points on Google tools (and other performance tools)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1457]
There are just some minor changes. We're much faster than competitors. We're almost here (almost 100 of 100) =))
1. https://developers.google.com/speed/pagespeed/insights
2. https://gtmetrix.com/

Right now our internal demo site (4.20) gets 99/100 for mobile  and 100/100 for desktop. Several recommendations:
1. Combine images using CSS sprites. For example, /Themes/DefaultClean/Content/images/ajax-loader-small.gif and /Themes/DefaultClean/Content/images/compare-button.png
2. Defer parsing of JavaScript. Actually it's jQuery library that cannot be moved to the footer - https://github.com/nopSolutions/nopCommerce/issues/2644
3. Use cookie-free domains. For example, /Themes/DefaultClean/Content/images/logo.png or /thumbs/0000077_banner_1.jpg or ...min.css).

Let's see whether we can (should) fix them. For example, 
1. It's better not to implement point 1 in open-source solution as it'll make customization more complex for third-party developers
2. TODO
3. It can be "fixed" by moving static content to a separate domain (e.g. Azure BLOB) but it's not part of the default solution

So the question is what should we fix? Everything is already done (for "out of the box" solution)

**Comment by sumit7034** [comment]
Great feature Nopcommerce should get 100/100 score from Google PageSpeed Insight

**Comment by sumit7034** [comment]
Can we Get 100 points on Google tools implemented as plugin as implemented in http://www.nop-store.com/en/pagespeed-insights?

**Comment by DarthSonic** [comment]
You really should be cautious about doing everything to get 100 points on Google PageSpeed. For as there are some optimiziations that are nearly obsolte when using http/2. Domain Sharding and combining static ressources are not necessary with http/2 and would even decrease loading time because http/2 will load much more ressources parallel/synchronous and do not need a TLS handshake on every request. So 20 tiny ressources are much faster loaded parallel than as a big combined ressource.

There should be an option to active "http/2 mode" of optimizations.

**Comment by turbochris** [comment]
Just my 50 cents. I've found that loading <style>...</style> in head is what makes the most difference. (Difference between 80's range and 90's range). This is of course something that is done in views. But would be cool with some kind of "engine" that can do it for you. IISSpeed does this for you for instance.

**Comment by entwicklerRepo** [comment]
boost it by removing jquery call from the public pages that doesn't use it. Add "native html" css preloaders and "defer" attribute for js files calls and you'll get 100 without any problems.

**Comment by AndreiMaz** [comment]
Right now our internal demo site (4.20) gets 99/100 for mobile  and 100/100 for desktop. Several recommendations:
1. Combine images using CSS sprites. For example, /Themes/DefaultClean/Content/images/ajax-loader-small.gif and /Themes/DefaultClean/Content/images/compare-button.png
2. Defer parsing of JavaScript. Actually it's jQuery library that cannot be moved to the footer - https://github.com/nopSolutions/nopCommerce/issues/2644
3. Use cookie-free domains. For example, /Themes/DefaultClean/Content/images/logo.png or /thumbs/0000077_banner_1.jpg or ...min.css)

Let's see whether we can (should) fix them. For example, it's better not to implement point 1 in open-source solution as it'll make customization more complex for third-party developers

**Comment by eadameg** [comment]
> Right now our internal demo site (4.20) gets 99/100 for mobile and 100/100 for desktop. Several recommendations:
> 
> 1. Combine images using CSS sprites. For example, /Themes/DefaultClean/Content/images/ajax-loader-small.gif and /Themes/DefaultClean/Content/images/compare-button.png
> 2. Defer parsing of JavaScript. Actually it's jQuery library that cannot be moved to the footer - #2644
> 3. Use cookie-free domains. For example, /Themes/DefaultClean/Content/images/logo.png or /thumbs/0000077_banner_1.jpg or ...min.css)
> 
> Let's see whether we can (should) fix them. For example, it's better not to implement point 1 in open-source solution as it'll make customization more complex for third-party developers

These kind of recommendations should be included in documentation

**Comment by AndreiMaz** [comment]
As per my comment posted 15 days we've done all standard optimizations. So closing it now.
