### ISSUE TITLE
Mac Chrome is detected as search engine in version 3.80

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1463]
http://www.nopcommerce.com/boards/t/42200/mac-chrome-cant-login.aspx

screenshots are below

**Comment by odises** [comment]
Yeah, that's right. It happened to me last night.

**Comment by AndreiMaz** [comment]
![chrome](https://cloud.githubusercontent.com/assets/5019111/15850287/e4243810-2c9f-11e6-818b-aa6d568ce844.jpg)
![safari](https://cloud.githubusercontent.com/assets/5019111/15850291/e6c38288-2c9f-11e6-8707-919bf4273675.jpg)
