### ISSUE TITLE
Use new  inputs

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1470]
These ones - http://www.virtuosoft.eu/code/bootstrap-touchspin/ - Currency symbols are supported, etc

also think about checkbox и radiobutton - https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html (icheck -  http://icheck.fronteed.com/)

let's make some sample screenshots and decide whether it's really required

**Comment by onebox-dev** [comment]
I think, we need Date and time range of Date picker, maybe it use booking(reserve) system
