### ISSUE TITLE
Discount for combination overriden price is not applied

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#1475]
Some times we need to have different price for each product combination. Then the only option to do it is to use Overriden Price property.
But for these prices discounts are not applied (but should):

In GetUnitPrice there is a check:

if (combination != null && combination.OverriddenPrice.HasValue)

then discount is not applied.

A way to fix it:

**decimal? initialprice = null;
                if (combination != null && combination.OverriddenPrice.HasValue)
                {
                    initialprice = combination.OverriddenPrice.Value;
                }**

finalPrice = GetFinalPrice(product,
                        customer,
                        attributesTotalPrice,
                        includeDiscounts,
                        qty,
                        product.IsRental ? rentalStartDate : null,
                        product.IsRental ? rentalEndDate : null,
                        out discountAmount, out appliedDiscount, **initialprice**);

In GetFinalPrice
//initial price
                decimal price;
                if (InitialPrice.HasValue) price = InitialPrice.Value; else price = product.Price;

**Comment by AndreiMaz** [comment]
thanks. we should also not forget about caching in GetFinalPrice
