### ISSUE TITLE
Refactoring of BrowscapXmlHelper

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1477]
Should we store values in _crawlerUserAgents and _notCrawlerUserAgents? I don't think so. Otherwise, hackers can send millions of HTTP requests with distinct (not existing) user agent strings. And all of them will be stored into _notCrawlerUserAgents variable. It'll take all memory

And we also have to ensure that non-existing user strings are not detected as search engines http://www.nopcommerce.com/boards/t/42200/mac-chrome-cant-login.aspx

**Comment by skoshelev** [comment]
Closed #1477
