### ISSUE TITLE
PagedList should not be implemented in Nop.Core, causing EF Query Plan Caching issues.

### ISSUE THREAD

**Issue by zbarrier** [nopSolutions/nopCommerce#1489]
PagedList should not be implemented in Nop.Core.  The implementation needs to reference System.Data.Entity so that Skip and Take can be parameterized to avoid EF query plan caching issues.  See 4.2 here: https://msdn.microsoft.com/en-us/data/hh949853.aspx

**Comment by mcliment** [comment]
The only usage of `PagedList` in `Nop.Core` is in `OfficialFeedManager`, this should be definitely doable. Reducing pressure on the EF query cache can be quite useful.

**Comment by mcliment** [comment]
Any explanation on why is this closed?

**Comment by AndreiMaz** [comment]
@mcliment we haven't found any explanation or reference in the mentioned document why it should be moved to Nop.Data (or where?) or any other library. Where exactly does it state that it should reference "System.Data.Entity"?

**Comment by zbarrier** [comment]
Hi @AndreiMaz and @mcliment  , it should be moved to Nop.Data because a reference to System.Data.Entity is required to parameterize the skip and take to prevent EF Query plan caching issues (Queryable Extensions https://msdn.microsoft.com/en-us/library/dn344947.aspx).  System.Data.Entity depends on the Entity Framework.  Based on the architecture, I assumed that Nop.Core should not reference the Entity Framework.  So, the correct solution would be to move the implementation of IPagedList, PagedList, to Nop.Data.

**Comment by zbarrier** [comment]
@AndreiMaz I can refactor the code to parameterize the skip and take when I get time and create a pull request (within the next month or so).  It was my intention initially when I submitted the issue.

**Comment by AndreiMaz** [comment]
@zbarrier sure. you're more than welcome to contribute! Thanks!

**Comment by zbarrier** [comment]
@AndreiMaz EntityFramework Core handles .Skip and .Take  correctly by default now (https://github.com/aspnet/EntityFrameworkCore/issues/3726).  This can probably be closed now.
