### ISSUE TITLE
Ensure tabs can be added from plugins to administration pages

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1498]
Source: http://www.nopcommerce.com/boards/t/29531/recommended-procedure-to-add-tabs-in-administration-pages-via-plugin.aspx?p=2#169603

also have a look at http://www.nopcommerce.com/boards/t/29531/recommended-procedure-to-add-tabs-in-administration-pages-via-plugin.aspx?p=2#169685 (comment below) - ensure that it works. once done we have to update our documentation

**Comment by kwscroggins** [comment]
Here is what I came up with (if it helps):


			if (eventMessage.TabStripName == "customer-edit")
			{
				int num = Convert.ToInt32(HttpContext.Current.Request.RequestContext.RouteData.Values["ID"]);
				UrlHelper urlHelper = new UrlHelper(HttpContext.Current.Request.RequestContext);
				RouteValueDictionary routeValueDictionaries = new RouteValueDictionary()
				{
					{ "area", null },
					{ "customerId", num }
				};
				string str = urlHelper.Action("myAction", "myController", routeValueDictionaries, HttpContext.Current.Request.Url.Scheme);

                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("<script language=\"javascript\" type=\"text/javascript\">");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("  $(document).ready(function() ");
				stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("  {");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("      $(\"#customer-edit ul\").append( \"<li class='ui-state-default ui-corner-top'><a aria-expanded='true' href='#tab-myTab' data-toggle='tab' data-tab-name='tab-myTab'>Customer Pricing</a></li>\" );");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("      $(\"#customer-edit\").find(\".tab-content\").append( \"<div id='tab-myTab' class='tab-pane'><div class='panel-group'><div class='panel panel-default'><div class='panel-body' id='loadCSHTMLhere'></div></div></div></div>\");");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("      $(\"#loadCSHTMLhere\").load('" + str + "');");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("  });");
                stringBuilder.Append(Environment.NewLine);
                stringBuilder.Append("</script>");
                stringBuilder.Append(Environment.NewLine);

				eventMessage.BlocksToRender.Add(MvcHtmlString.Create(stringBuilder.ToString()));

**Comment by vishalkotecha** [comment]
Why is this closed? I don't see proper instructions about adding tabs to admin part. This is only piece of code! Andrei, you might want to re-open it

**Comment by AndreiMaz** [comment]
see comment above by kwscroggins and http://www.nopcommerce.com/boards/t/29531/recommended-procedure-to-add-tabs-in-administration-pages-via-plugin.aspx?p=2#169685

**Comment by oumiller21** [comment]
Not sure if anyone will find value in this but here's a helper class that wires everything up and includes an option for only showing the tab in advanced mode. Props to @kwscroggins for getting this started

```
        /// <summary>
        /// Adds a tab to the BootStrap TabStrip on an Admin Page.
        /// </summary>
        /// <param name="eventMessage">AdminTabStripCreated Event Message</param>
        /// <param name="id">Internal Identifier for the Entity</param>
        /// <param name="tabName">Name of the Tab</param>
        /// <param name="actionName">Action Name</param>
        /// <param name="controllerName">Controller Name</param>
        /// <param name="advancedSetting">Only display the tab in Advanced Mode</param>
        public static void CreateAdminTab(AdminTabStripCreated eventMessage, int id, string tabName, string actionName, string controllerName, bool advancedSetting = false)
        {
            var routeValues = new RouteValueDictionary()
                                  {
                                      {"area", "admin"},
                                      {"id", id}
                                  };
            var urlHelper = new UrlHelper(eventMessage.Helper.ViewContext.RequestContext);
            string strContent = urlHelper.Action(actionName, controllerName, routeValues, HttpContext.Current.Request.Url.Scheme);

            //Create an Id for the tab
            string tabId = string.Format("{0}-{1}", controllerName, actionName).ToLower();

            //Specify the Setting Mode
            string settingModeClass = (advancedSetting) ? "advanced-setting" : ""; 

            eventMessage.BlocksToRender.Add(new MvcHtmlString(@"<script>
                                                                    $(document).ready(function() {
                                                                        $('#" + eventMessage.TabStripName + @" ul:first').append(""<li class='" + settingModeClass + @"'><a aria-expanded='true' href='#tab-" + tabId + @"' data-toggle='tab' data-tab-name='tab-" + tabId + @"'>" + tabName + @"</a></li>""); 
                                                                        $('#" + eventMessage.TabStripName + @"').find('.tab-content').append(""<div id='tab-" + tabId + @"' class='tab-pane'><div class='panel-group'><div class='panel panel-default'><div class='panel-body' id='" + tabId + @"-content-placeholder'></div></div></div></div>""); 
                                                                        $('#" + tabId + @"-content-placeholder').load('" + strContent + @"'); 
                                                                     });
                                                                </script>"));


        }
```
