### ISSUE TITLE
Ability to limit payment plugins by customer role (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#15]
Would be a great feature to be able to restrict Payment Method to one or many Customer Roles. 
Eg. Only your "trusted" customers can order with Purchase Order, others have to pay with Credit Card. 

Forum source: http://www.nopcommerce.com/boards/t/28362/suggestion-payment-method-restrictions-on-customer-roles.aspx 
Please note that in version 3.50 you can easily put this logic into new "HidePaymentMethod" method in payment plugins 

Currently can be done in ShippingDirector and PaymentDirector third-party plugins

**Comment by AndreiMaz** [comment]
duplicated
