### ISSUE TITLE
New configurable category template view

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1501]
Is it possible to made new category template view?
For this moment we may swich between grid and list (BTW - maybe it is time to move setting to catalog settings from advanced options?).

It would be nice, if we will be able to switch also between views like:
- one column (without any sidebar pannel)
- left sidebar (for this moment default view and only possible with standard installation)
- right sidebar
- left and right

Source: http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=21#169468

Something like on the picture below
![panel-1](https://cloud.githubusercontent.com/assets/5019111/16106938/73dd6992-33a1-11e6-9a25-bd19e87234c7.png)

**Comment by imxuhao** [comment]
Good Idea! 
sometimes we need category list   shown as left sidebar  and sub categorys as list-view with pictures.

**Comment by tigran-avdalyan** [comment]
Good iDEA

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It's better to have distinct category templates
