### ISSUE TITLE
Require other products added to the cart. Add URL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1503]
When we add product to the cart without required product we receive error:
![j1bshvnbbcu2](https://cloud.githubusercontent.com/assets/5019111/16117524/40cabdae-33db-11e6-8568-bc044ead40f0.png)

Product name is just text, what do you think about adding URL to this product name? Customer will be able to go directly to the desired product, without having to search for it manually.

Source: http://www.nopcommerce.com/boards/t/42371/require-other-products-added-to-the-cart-feature.aspx

**Comment by hkreklame** [comment]
That would be great.
