### ISSUE TITLE
Errors after serwer down

### ISSUE THREAD

**Issue by MarioPrograms** [nopSolutions/nopCommerce#1508]
(0): error CS0006: Metadata file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\a67a341c\14413304\Nop.Plugin.ExchangeRate.EcbExchange.dll' could not be found

(0): error CS0006: Metadata file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\a67a341c\14413304\Nop.Plugin.Payments.AuthorizeNet.dll' could not be found

**Comment by AndreiMaz** [comment]
please post all technical questions on our forums
