### ISSUE TITLE
Search noise words

### ISSUE THREAD

**Issue by zstomp** [nopSolutions/nopCommerce#1512]
Including noise words (e. g. single letter "a") to the search query results in failed search. The [transform noise words](https://msdn.microsoft.com/en-us/library/ms187914%28v=sql.120%29.aspx) SQL Server option did not fix it, so it must be something about the way the query is processed and passed from nopCommerce.

nopCommerce v3.70 (full-text search is on, "AND" mode), SQL Server Express 2014

**Comment by zstomp** [comment]
@AndreiMaz Could you please comment on "maybe won't?"

**Comment by AndreiMaz** [comment]
@zstomp we've postponed this task. Maybe it'll be implemented later (on hold). Maybe we won't implement.

But actually this certain task is just postponed
