### ISSUE TITLE
Admin section - javascript error: Object doesn't support property or method 'backTop'

### ISSUE THREAD

**Issue by MagicMaxxx** [nopSolutions/nopCommerce#1514]
IE11 used in debug and every time when I need to browse to the ADMIN section I can see that kind of exception:
![image](https://cloud.githubusercontent.com/assets/19684558/16205028/6578548e-372a-11e6-848f-ed6fb52a6968.png)

**Comment by AndreiMaz** [comment]
@mariannk please check it out

**Comment by MagicMaxxx** [comment]
Please disregard this issue - after I cleaned up browser's cache everything works fine.

thanks!
