### ISSUE TITLE
Rework: Order Details page mark-up

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1522]
Source: http://www.nopcommerce.com/boards/t/42437/rework-order-details-page-mark-up.aspx

**Comment by Al3ksBG** [comment]
I had to upload the file in a different server, because doesn't allow me to upload a ZIP file although it is supported... very confusing. 

http://www.filedropper.com/details_1

**Comment by AndreiMaz** [comment]
@Al3ksBG the link doesn't work

**Comment by Al3ksBG** [comment]
That is really unfortunate, because it works here... probably there's some localization restriction. I'm probably going to send it to you via email, because Git still throws an error...
