### ISSUE TITLE
Add setting to sort Reviews by Date Created Desc OR Asc

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1524]
Right now the default sort is in ascending order which means the oldest post will show up first. I think it's worth having an option that allows the store owner to decide if the post should be sorted in Ascending or Descending order. 

Also, in the admin console the posts are sorted in Ascending order which means you have to click through to the last page to approve new reviews.

Source: http://www.nopcommerce.com/boards/t/42443/add-setting-to-sort-reviews-by-date-created-desc-or-asc.aspx

**Comment by bradhof** [comment]
I agree.  This would be a valuable little enhancement on the admin panel. Perhaps just sort the entire list by created date (descending).  In our company's workflow, we always want to view/approve the most recent reviews.

**Comment by skoshelev** [comment]
Closed #1524
