### ISSUE TITLE
Discounts do not have multistore support

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#1537]
Each created discount (in 2.7) works for all stores. There is no option to limit it to specific store.

**Comment by shurub3l** [comment]
There is a plugin for this. You can find it here: [http://www.nopcommerce.com/p/986/restricted-to-store-discount-requirement-rule.aspx](http://www.nopcommerce.com/p/986/restricted-to-store-discount-requirement-rule.aspx)

**Comment by ArturAlekseev** [comment]
Why it is made as plugin? Multistore is a core feature and discounts too.

**Comment by shurub3l** [comment]
I don't know exactly why they decided to add it as a plugin. I made a pull request to add the store discounts feature. We'll see if they accept it.
