### ISSUE TITLE
Add javascript events

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#154]
We started working on Google Analytics Enhanced ecommerce plugin for nopCommerce. 
Unfortunately nopCommerce is lacking any javascript events for any user actions. For example there is no way to know when a product has been added to the cart. 
It would be nice if you raise javascript events like "productAddedToCart" etc. for the actions that happen via Ajax.
For example when you add a product via Ajax it would be nice to have something like this: 

$.event.trigger({ type: "nopAjaxCartProductAddedToCartEvent", productId: productId, quantity: addToCartProductQuantity }); 

This way we can subscribe to such events and submit the data to Google Anaytics for example. 
Unfortunately the Remove from Cart does not use Ajax, so there is no way this to be done for now. 

Source: http://www.nopcommerce.com/boards/t/38391/suggestions-for-the-upcoming-version-370.aspx?p=2#156114

also see http://www.nopcommerce.com/boards/t/43297/improvements-before-380-release.aspx#171728

also see http://www.nopcommerce.com/boards/t/39325/add-javascript-events-in-the-payment-flow.aspx

P.S. We already have such event defined in \Views\Product_ProductAttributes.cshtml

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
