### ISSUE TITLE
Catagory's CategoryTemplateId and ParentCategoryId has rule or not?

### ISSUE THREAD

**Issue by ismailyilmaz** [nopSolutions/nopCommerce#1540]
I tried your awesome project's admin panel and i deleted all category templates by following **System>Templates>CategoryTemplates** steps. And  i tried to add a new category without Category Template and i got an error message. I downloaded source code of your awesome project and debugged and i couldnt see any problem with your code. But the issue exists. The problem is  may be with FluentValidations framework? Because there is no rule for CategoryTemplateId  and ParentCategoryId in validator file. And when i remove validator for CategoryModel, it posts.
![ekran alintisi](https://cloud.githubusercontent.com/assets/9105939/16358473/07a7b8c2-3b1c-11e6-9399-c0944568d28c.PNG)

**Comment by AndreiMaz** [comment]
please post all questions on our forums
