### ISSUE TITLE
Add confirmation to "Delete setting" and "Delete locale" button

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1543]
There is a possibility of accidental click on Delete button instead of Edit on All Settings page.

A confirmation would be a good idea for any accidental deletions.

Source: http://www.nopcommerce.com/boards/t/43026/display-a-confirmation-when-a-setting-is-deleted-from-all-settings.aspx

**Comment by skoshelev** [comment]
Closed #1543
