### ISSUE TITLE
Integration with DNN Platform

### ISSUE THREAD

**Issue by renderfarmer** [nopSolutions/nopCommerce#1548]
Would love to see Integration with .NET based CMS system DNN Platform.

More: http://www.dnnsoftware.com/platform

**Comment by dchmir** [comment]
Please make suggestions on integration at an official [forum](http://www.nopcommerce.com/boards/f/7/suggestions-and-feedback.aspx)

**Comment by AndreiMaz** [comment]
Leave it for third-party integrations (not out of the box)

**Comment by rudgr** [comment]
hi @AndreiMaz 

will there be some generic nopcommerce interface that needs to be implemented for custom cms integrations?

or some guidelines on what should be implemented on nop/cms side?

tx

**Comment by AndreiMaz** [comment]
@rudgr we already have Web API (https://github.com/SevenSpikes/nopCommerce/tree/Web-Api-3.70). it can be used for any kind of synchronization/integrations

**Comment by AndreiMaz** [comment]
not for core
