### ISSUE TITLE
Campaigns. Allow a store owner to choose an email account

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1549]
What do you think about changing the way of sending the campaigns? Currently, is only one email account, from which we can send the campaign, and it is the default account of the whole store. What happens if in the store, default account is store@store.com, but store owner wants to send campaigns from email sales@store.com. Maybe we should give the opportunity to select from which account send campaign?

Notes:
1. Hide this field if only one email account is configured (like stores)
2. Campaigns should work fine if associated email account is deleted. in this case a default one will be used. So when implementing do not add navigation property to "Campaign" entity. And do not make this property localizable (selectable for each language in multi-language environment)

**Comment by VahidNaderi** [comment]
That's nice, but I'm not agree with hiding the field when only one email is configured, IMO the ability to use any email address should be obvious there.
