### ISSUE TITLE
"Free shipping for first purchase" and new field on the customer "Free shipping for next purchase"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1566]
Source: http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=25#171291

**Comment by orrTechnologies** [comment]
Should this be submitted to the extension store, or just a pull request when done? Thinking about coding it.

**Comment by orrTechnologies** [comment]
@AndreiMaz Have the code done, just not sure where I should submit it?

**Comment by AndreiMaz** [comment]
@orrTechnologies Thanks. please submit a pull request as described at http://www.nopcommerce.com/contribute.aspx
