### ISSUE TITLE
More presentation model caching

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#157]
EF entities (e.g. Customer or Order) cannot be cached between requests (EF limitation). And we can cache presentation layer objects only. 

1. ProductReviewModel (do not forget about UTC datetime converted to a local one in some cases)
2. News and blog records (do not forget about UTC datetime converted to a local one in some cases). 
Regarding points 1-2 and dates. We can use the original UTC date in models. And convert dates  (to the current customer timezone) only in cshtml files. It'll allow us to cache many models where dates are used. The issue is that in this case we won't be consistent with admin area where we have to convert dates in controllers because in some cases dates are returned using JSON

3. Countries and states

**Comment by dchmir** [comment]
BlogCommentModel,
BlogPostTagListModel,
ForumGroupModel,
ForumRowModel,
ForumPostModel,
NewsCommentModel,
ForumTopicRowModel

**Comment by AndreiMaz** [comment]
After some investigate we've decided not to implement caching of any additional models. We already cache all required models. And all further "caching" changes will be just "ugly" workarounds that reduce source code readability.

Furthermore, most of them are not used so ofterm (e.g. product reviews or news/blog comments)

There are other way to improve performance except model caching
