### ISSUE TITLE
Multiple return requests

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1571]
That is as suggestion as bug, but just wrote it here. 

I know, that is rather rare, and every case is investigate carefully (well, should be), but for sure it will help  and avoid futher problems if you will redesign return requests.

Scenario:

Customer making return request. But if open order list from own account, is able to click again return request, and make another request (even if order is with just one position - and in a fact previous request was send already). Customers may send request multiple times without any limit, and return request status do not change anything!

I think, return request should be disable if there was request send (if just one position on the order). If multiple items on order, then it should be disable product (or decrease quantity). In a fact, decrease quantity will do the job (if no item choosen, then request is not send).

Source: http://www.nopcommerce.com/boards/t/43245/suggestionbug-multiple-return-requests.aspx

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)

**Comment by lodha13** [comment]
can you please help in customizing this. I want to prevent having multiple return request.
