### ISSUE TITLE
Product details page. Basic-advanced mode minor issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1589]
When you are in the admin area, in a products edit page, you can choose whether to see basic or advanced page.
If you have advanced mode selected and click the SEO tab and then switch back to basic mode, should the SEO fields disappear ? 

Source: http://www.nopcommerce.com/boards/t/43350/nopcommerce-380-beta-released-please-share-your-impressions.aspx?p=5#171977

**Comment by tigran-avdalyan** [comment]
needs to go by Default to Product info tab if the tab is not available in Basic Mode
