### ISSUE TITLE
Admin area. We can use highlight icons in the menu (nofitications)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1594]
demo https://almsaeedstudio.com/themes/AdminLTE/index.html (menu). for example, to display some notification about new orders, low stock, etc)

First, we have to prepare a list of such notifications (for approval). Then, we should decide to optimize it (performance) because we should not load them for each request (not recommended but maybe sometimes acceptable - caching?)

**Comment by viewtance** [comment]
If we can use SignalR to push messages and notifications to browser? At the background end, using schedule task to run the query.

we can reference below implementations:
http://aspnetboilerplate.com/Pages/Documents/Notification-System
http://aspnetboilerplate.com/Pages/Documents/SignalR-Integration
