### ISSUE TITLE
Ability to import /export choosen field

### ISSUE THREAD

**Issue by ofekpc** [nopSolutions/nopCommerce#1597]
For example only sku and price
And import only sku and price
This for update only price
Or for examle sku and picture
Or any field adnin choose to import
Like have in magento
That the import and export more advance

**Comment by eadameg** [comment]
This is already available in v3.80:
You only need to import sku columns and only columns that you want to modify
For export only columns available in the Basic view (if it is chosen) will be exported

**Comment by ofekpc** [comment]
I hop is ok  I write here or is better in GitHub

 

Thanks for your replay

 

Great for that, I check that and it work fine 

 

 

For import category I check that also

And the import is  work

But have bug I notice , when import

In the frot the category not push, not linked

Unless I open it in the admin and save it again then it start to puth in the front

I give example

 

Nop.sale10.co.il

See all the category are imported

And this 2 category I open it in admin and save again

This 2 work

http://nop.sale10.co.il/xbox-360one

 

http://nop.sale10.co.il/%D7%A1%D7%9C%D7%95%D7%9C%D7%A8

 

http://nop.sale10.co.il/ <http://nop.sale10.co.il/סלולר> סלולר

 

 

 

also when there is Hebrew url

in chrome it show ok

but in explorer it is show as last link

 

3. what about extension of redirect , most of costumer who migrate to nop system 

Afraid of the redirect , and need this very

 

 

Regrads guy

**Comment by AndreiMaz** [comment]
@ofekpc could you please clarify issue with importing? a list of steps to reproduce

**Comment by ofekpc** [comment]
1.category

 

The importing of category

Is success

 

But in the front the category not push

Unless I open the category on the admin and save it again

Then I can open it and push the link 

I did give you example of category that I save and they work

And give you example of category that do not linked

And I wonder where is go the tree view of the category

 

Nop.sale10.co.il

 

See only this 2 category that I save after the importing in the admin work in the front

http://nop.sale10.co.il/xbox-360one

 

http://nop.sale10.co.il/%D7%A1%D7%9C%D7%95%D7%9C%D7%A8

 

 

2.hebrew url show in explorer like this

http://nop.sale10.co.il/%D7%A1%D7%9C%D7%95%D7%9C%D7%A8

while in croome show the Hebrew url fine in the url

http://nop.sale10.co.il/ <http://nop.sale10.co.il/סלולר> סלולר

 

 

3. build in redirect

**Comment by AndreiMaz** [comment]
Thanks! I've just created a separate work item https://github.com/nopSolutions/nopCommerce/issues/1602
