### ISSUE TITLE
Product editor setting. Add manufacturers

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1609]
Suggestion: In Product Edit page, Manufacturers should be a selectable "Mapping" for Basic Settings, because many stores don't use it.

**Comment by noptools** [comment]
Andrei

Similar for:
Inventory method
Shipping enabled

For example, when you do prevent Vendors from changing Settings, the Basic settings would allow for limiting what fields Vendors could set - useful in some types of 'marketplaces'.

**Comment by skoshelev** [comment]
Closed #1609
