### ISSUE TITLE
Performance. Pictures. Avoid unnecessary loading of binary image data.

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1610]
Branch: https://github.com/nopSolutions/nopCommerce/commit/6e9a9ec549d25b743880d1347faf00d0d105a536

Let's think what we can do

**Comment by kingmotley** [comment]
The picture binary blob should be moved to it's own table to keep EF from loading a potentially large amount of data from the server to the client when it isn't required.  The web pages should only need to know the id of the picture, not the size or contents of the binary blob, so why put it in the same table which will make it always be loaded and sent to the client whenever you want to get the picture id?  Bad design.

**Comment by skoshelev** [comment]
Closed #1610
