### ISSUE TITLE
product Tier Prices

### ISSUE THREAD

**Issue by JasonCSharpCoder** [nopSolutions/nopCommerce#1613]
Hi,guys
     by reading your code, find my configuration for product tier price could not be applied for web presentation, the product tier price  always is product price. your code 
File : Nop.Web\Controllers\ProductController.cs 
Line: 833

**Comment by JasonCSharpCoder** [comment]
Hi,guys
by reading your code, find my configuration for product tier price could not be applied for web presentation, the product tier price always is product price. your code 
File : Nop.Web\Controllers\ProductController.cs 
Line: 833

**Comment by AndreiMaz** [comment]
please post all suggestions / questions on our forums
