### ISSUE TITLE
Allow customer to apply multiple discount coupon codes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1617]
If use two discount coupon codes with the same discount type and make the "Cumulative with other discounts" checked, then only one of them could be applied.

We should allow to enter multiple coupon codes. The question is how we should store it? The current approach is not acceptable

Source: http://www.nopcommerce.com/boards/t/43403/discount-with-coupon-code-applied-not-corrected-and-usage-history-not-updated.aspx

**Comment by viewtance** [comment]
Happy to see the bug been fixed
