### ISSUE TITLE
Allow a plugin project to have multiple plugin interfaces implemented

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#162]
I've attached "PluginController.cs" where we have made a small, but important change. 

We have changed it to allow a plugin to have several interfaces. I currently use it for a plugin that uses: IWidgetPlugin, IShippingRateComputationMethod 

This enables me to get some extra functionality to a shipping plugin encapsulated in the same plugin. 

I have simply change the nested "if else" 

I use it like this: @Html.Widget("shipping_option_extra", Model.ShippingGroupModels[i].ShippingOptions[j]) 

Then then plugin can do extra stuff if it's the correct shipping option (javascript popup and such)

Also - for inspiration - I mingled around a few hours before I found that a widget zone has to be enabled i admin. You should make a change for IWidgetPlugin that says "ActivateWidgetZonesOnInstall", to enable default settings here...

Med venlig hilsen / Best Regards 

Christoffer Munck // PostMe.com - PostMeNetwork 
CTO // Partner

[PluginController.zip](https://github.com/nopSolutions/nopCommerce/files/91678/PluginController.zip)

**Comment by AndreiMaz** [comment]
duplicated
