### ISSUE TITLE
Re-design installation page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#163]
Let it match our design colors and style. Let's make it consistent with the rest nopcommerce sites and pages.

We can also simply and approve it. Let's discuss it

Please suggest some ideas for the new design of the installation page.

also see https://github.com/nopSolutions/nopCommerce/issues/597 (other contribution)

**Comment by mariannk** [comment]
http://dl2.joxi.net/drive/2016/06/15/0015/3873/1011489/89/5156232247.jpg

**Comment by MeysamNaderi** [comment]
![nopcommerce installation recommend design](https://cloud.githubusercontent.com/assets/7395845/16625499/26f93178-43ba-11e6-9f87-19ef1c209499.jpg)
what do you think about this?

**Comment by AndreiMaz** [comment]
@MeysamNaderi looks good. would you like to contribute it?

**Comment by MeysamNaderi** [comment]
Sure, I'll implement it and make a pull request.
