### ISSUE TITLE
Display image squares (admin area)

### ISSUE THREAD

**Issue by nstefan1992** [nopSolutions/nopCommerce#1631]
To see the image of the attribute in /Admin/Product/EditAttributeValues (if you use ImageSquares type )
![imagesquares](https://cloud.githubusercontent.com/assets/9924211/17270452/78750f0e-566b-11e6-8a77-046d4df7fce8.JPG)
![sample imagesquares](https://cloud.githubusercontent.com/assets/9924211/17270453/787da7b8-566b-11e6-84a5-f6dbfd1bcf55.JPG)

**Comment by AndreiMaz** [comment]
Right now we display product picture (main picture to be changed). But we don't do it for square images. Let's think what we can do. How an where to display them. I don't believe it should be done the suggested way as it becomes confusing
