### ISSUE TITLE
Migrate project to ASP.NET Core and Entity Framework Core

### ISSUE THREAD

**Issue by joe704la** [nopSolutions/nopCommerce#1632]
I have been using nopCommerce for a couple of years now. Our project is stuck on 3.10 because of some previous developers heavily customizing the core files. I am going to start redeveloping our store into a new version but I would love to see nopCommerce move to ASP.NET Core and Entity Framework Core. 

This will give nopCommerce the ability to be platform independent, much faster, support for YEOMAN, Grunt, Gulp, Bower, NPM and more optimized for cloud computing like Azure. 

Probably the biggest benefit is the removal of System.web which was slowling the heck out of previous version of ASP.NET MVC.

The list goes on with the benefits.

**Comment by odises** [comment]
@joe704la #215

**Comment by AndreiMaz** [comment]
duplicate
