### ISSUE TITLE
Integration with Google Enhanced Ecommerce 

### ISSUE THREAD

**Issue by odises** [nopSolutions/nopCommerce#1635]
- Measuring Product Impressions
- Measuring Product Clicks
- Measuring Views of Product Details
- Measuring Additions or Removals from a Shopping Cart
- Removing a Product from a Shopping Cart
- Measuring Promotions
- Measuring Promotion Clicks
- Measuring a Checkout
- Measuring Purchases
- Measuring Refunds

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development.
