### ISSUE TITLE
Page not found in Admin area - v3.8

### ISSUE THREAD

**Issue by B-Esmaili** [nopSolutions/nopCommerce#1636]
Hi
I have downloaded `Dev` branch just now , but when i attempt to enter admin area i face up with following error :

```
Page not found
The page you requested was not found, and we have a fine guess why.

If you typed the URL directly, please make sure the spelling is correct.
The page no longer exists. In this case, we profusely apologize for the inconvenience and for any damage this may cause.
```
any suggestion why this happens?

**Comment by odises** [comment]
@B-Esmaili I think you should build Nop.Admin project in presentation section in the solution.

**Comment by AndreiMaz** [comment]
please post all questions on our forums
