### ISSUE TITLE
Estimated Shipping Form. Make zip code required

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1646]
I just wanted to suggest that there be some validation elements displayed on the 'Estimate Shipping' form when no ZIP code is submitted. Currently, no errors are shown when the ZIP code input is empty upon submission. All that is displayed is the 'In-Store Pickup' shipping method (estimate).

It also seems like the ZIP code should be labelled 'required', as many of the shipping rate calculators seem to use the ZIP to calculate rates.

Source: http://www.nopcommerce.com/boards/t/43513/estimated-shipping-form-nopcommerce-380.aspx

**Comment by sukeshak** [comment]
Zip code validation is not there (I guess) in customer address data entry too for shipping. I had a failed transaction since payment gateway reject with wrong data in ZipCode text, which was some text content and not number.

**Comment by noptools** [comment]
The Estimate Shipping should also respect the setting shippingsettings.returnvalidoptionsifthereareany for Pickup In Store.  I.e. if False, and there are Errors, then Pickup In Store should not show.  (Just the errors should show).
