### ISSUE TITLE
Layout bug after adding language pack

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1654]
Today I added a language pack for nopCommerce (Dutch). A dropdownlist appears when adding the second language to nopCommerce. This dropdownlist breaks styling for the username in the upper right corner.
1. nopCommerce version: 
   3.80
2. Any private modifications you made to your nopCommerce: 
   None
3. The version of MS SQL database you're running nopCommerce with: 
   Sql Server 2008 R2
4. Anything else that could possibly be relevant. Err on the side of too much information, rather than too little.
   See text above

http://imgur.com/a/w6gYN
![no6jahi](https://cloud.githubusercontent.com/assets/5019111/17429727/ebe07816-5af8-11e6-8066-378c185e6329.png)

Ask me if more info needs to be provided.

Edit:

This also causes a problem when installing and uninstalling plug-ins. The green overlay is not the highest layer on some places. Deleting the language pack instantly fixed the issue for me. Seems to me there is something wrong with the dropdownlist's html.

**Comment by mariannk** [comment]
Can't reproduce this bug 
http://dl1.joxi.net/drive/2016/11/24/0015/3873/1011489/89/f275887934.jpg
