### ISSUE TITLE
Forums. Add karma points (similar to official nopCommerce site) - contribution

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#166]
Karma points (similar to official nopCommerce site) 

Allow a store owner to enable/disable it. And allow him to specify number of points to be earned/redeemed for any action (e.g. "Create a topic", "New post", "vote up" and "vote down"). I think we should do it only after voting support - #203

Contribution (Anshul agreed to contributed) - http://www.nopcommerce.com/p/2102/roasted-forum-plus-roastedbytescom.aspx

**Comment by AndreiMaz** [comment]
duplicate
