### ISSUE TITLE
Bulk Edit Product - Add Product Cost Field

### ISSUE THREAD

**Issue by pdmarty** [nopSolutions/nopCommerce#1660]
9 times out of 10 when you update the sell price you need to update the product cost.  It would speed things along if that could be done from the bulk edit product screen.

**Comment by sukeshak** [comment]
Bulk updating price is also a challenge when we use Attribute combination which is the case most of the time.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
