### ISSUE TITLE
Allow for approved buyer to override call for price

### ISSUE THREAD

**Issue by pdmarty** [nopSolutions/nopCommerce#1663]
Feature Request.

It would be nice to have a field in the customer record to allow for overriding the call for price feature so that any customer that has been authorized can view pricing.  We have requirements from some manufactures to not show pricing on certain items but we have a select group of customers that are authorized to view and buy.  It would be nice to just allow them to see the pricing thus keeping our manufacturer requirement in place.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
