### ISSUE TITLE
Generate all possible combinations - stock quantity default value should be zero

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1677]
When using "Track inventory by product attributes" and click on "Generate all possible combinations" in "Attribute combinations", the grid populates items but the stock quantity default value is set to 10000.

This is annoying since we need to go and remove it individually.
The default value of "Stock quantity" should be zero.

**Comment by skoshelev** [comment]
Closed #1677

**Comment by stephdep** [comment]
Why not having a setting(s) for this ? With 0, you will have to change most of the combinations again anyway in my opinion. Many fashion shops need to enter the same recurring pattern of
small 1 medium 2 large 2 and Extra Large 1
