### ISSUE TITLE
Bulk update stock quantity while using Track inventory by product attributes

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1679]
When using "Track inventory by product attributes" and click on "Generate all possible combinations" in "Attribute combinations",  stock quantity option is available. This is great option.

Now in this scenario, bulk edit does not work so each product stock quantity change requires going to the individual product > click Product attribute tab > Attribute Combinations tab and click edit to change the stock quantity.

Hope to have some easier option keeping in mind, most products being sold would need to use Product attributes for sizes, colors etc...

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
