### ISSUE TITLE
Tier pricing should not change main price listed on the product page

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1681]
Tier pricing should not change the MRP or the main price listed on the page, even if Tier pricing is configured with quantity as 1.

I have used Tier Pricing to configure dealer pricing and put the quantity as 1. Dealer is a user role here.

I would like the dealer to see the MRP on the product page, but when he purchases apply the dealer price configured using Tier pricing option.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
