### ISSUE TITLE
Customer Role based Payment method restrictions

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1682]
Payment method restrictions needs new options:
Currently the payment methods are restricted according to Country. We should have a new option so that payment methods can be restricted for specific roles.

For example, I would like to have Bank Transfer as the only option for dealers. 
But for all normal users offer Credit card and other options.

**Comment by FredBell** [comment]
This is something that we need as well.
It would be a very useful feature.

Typically where we use this is for wholesale account - we give them the ability to place order without paying for it right away. Then we generate a PO and process the payment offline.
Of course regular customer use CC.

Hope this helps

Frederic

**Comment by sukeshak** [comment]
I agree @FredBell same requirement for me too

**Comment by AndreiMaz** [comment]
Supported in 3.90
