### ISSUE TITLE
Message templates. Support HTML body

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#169]
We should support "body" HTML tag when editing message templates (rich editor) similar to how it's done for campaigns. But the issue is that when we have multiple languages, then "body" HTML tag is automatically added to the editors for other languages (other tabs). And that's why they are saved as localized values (as not empty) - so you cannot have empty value for HTML templates for other languages

Also see http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=6#160458

see https://github.com/nopSolutions/nopCommerce/issues/1913 (when done this work item can be closed)

**Comment by odises** [comment]
What if we consider 
`<!DOCTYPE html>\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>` 
as empty in server side, and set the **Body** value to **null** manually.

**Comment by AndreiMaz** [comment]
It's more a workaround. I don't like this approach. There should be more elegant way to fix it
