### ISSUE TITLE
Widget support for Admin Dashboard Page

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1691]
It would be great help if we can have Widget support for Admin Dashboard so that anyone can customize the Dashboard with graphs showing different important data they want to see.

The graphs shown currently (Orders & New Customers) are not very useful information for most of the admin users. This would also includes the big colorful  boxes under "Common Statistics"

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
