### ISSUE TITLE
Wallet features like ecommerce website

### ISSUE THREAD

**Issue by patelsagu** [nopSolutions/nopCommerce#1692]
Add wallet features
- Customer can add money to his wallet**
- Customer buy item from his wallet**
- admin / vendor can add refund amount to his wallet**

**Comment by sumit7034** [comment]
It will be a great feature to have wallet feature like paytm and mobikwik in nopcommerce

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/1919
