### ISSUE TITLE
Downloadable product small CSS issue

### ISSUE THREAD

**Issue by DevPartner** [nopSolutions/nopCommerce#1693]
![downlodable_products](https://cloud.githubusercontent.com/assets/5019111/17835421/6fa087f4-6774-11e6-8766-76bb4894c75b.png)

Environment: Ie Edge

**Comment by MaxMommersteeg** [comment]
@DevPartner What resolution did you record this on? It looks valid when using a 1920x1080 resolution.

![Printscreen at 1920x1080](https://cloud.githubusercontent.com/assets/9657173/17837467/0868cba6-67b4-11e6-8ab7-a6d93fcf73e8.png)

When resizing the browser window it will change as image you uploaded. Not only for Edge, but Chrome too.
