### ISSUE TITLE
Encrypt email account passwords

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1699]
In the [EmailAccount] table, the passwords for the email accounts is not being ecnrypted, its a very big vulnerability, since no one besides the owner of the account should have access to any password whatsoever, and now anyone with access to the db can lookup the password, which is extremely vulnerable issue.

Source: http://www.nopcommerce.com/boards/t/43865/email-accounts-not-hashing-password.aspx

Similar task - https://github.com/nopSolutions/nopCommerce/issues/451

**Comment by rudgr** [comment]
Seems duplicate of: https://github.com/nopSolutions/nopCommerce/issues/345 ?

**Comment by AndreiMaz** [comment]
@rudgr Thanks! you're right
