### ISSUE TITLE
Support for bulk operations in entity services

### ISSUE THREAD

**Issue by tskaiser** [nopSolutions/nopCommerce#1700]
A lot of the services _(eg. CategoryService)_ only expose Insert / Update / Delete as single entity operations. It is my experience that this inflicts are large amount of overhead for each operation when implementing bulk automation _(eg. sync with third party, price automation, etc)_.

The workaround to this is acquiring the respective repositories and then working directly on those, but this breaks the abstraction and has potential issues such as with cache and events.

It would be desirable if these services, by default, implement both single and collection operations.

**Comment by tskaiser** [comment]
Regarding the label, is there a design choice against it or would it simply be more expedient if I found the time to code and issue a pull request with the necessary changes? :)

**Comment by tskaiser** [comment]
After researching it the problem seems central the Entity Framework, so the proposed solution would most likely not work. In essence, when enough entities have been touched the performance degrades catastrophically.

Our local solution is to manually chunk up the work using Autofac scopes and then recreating a new scope after an arbitrary (30) number of iterations. This indirectly leads to a new EF context being created where used. With this method the running time of the problem task has been reduced from unsustainable (>1 day) to manageable (minutes).

**Comment by MaxMommersteeg** [comment]
Yesterday I dealt with a similar issue. We need to sync products from one database to another. At last we ended up writing a single stored procedure that does this for us. Synchronizing 20.000 products took us about 3 to 4 days (that is with optimizing EF for our needs: recreating context,  AsNoTracking enabled and AutoDetectChanges disabled). We were done in 50 seconds using the Stored Procedure. The big downside of our approach is not being able to use the safe nopCommerce services. We now need to check if our sync still runs with a new version of nop (with possibly a changing database design).

The main issue making our sync slow was inserting records in the nopCommerce database. A bulk insert function, a switch to Dapper (https://github.com/nopSolutions/nopCommerce/issues/239) or implementing dapper or plain queries for the heavy database actions could improve performance significantly.

**Comment by tskaiser** [comment]
We're syncing/inserting in the vicinity of 10k products using EF within the order of minutes when recreating the contexts using Autofac scopes. Have you tried profiling to detect any hot paths? We discovered some of our plugins caught every product update event and manually resolved a logger using the request lifetime scope. This alone triggered the EF degradation issue massively slowing down everything.

That said you're not going to beat an optimized stored procedure using EF, so now that you have one I could understanding sticking with it - I would. The reason I'm staying with scopes is exactly to avoid breaking the abstractions and maintainability.

**Comment by MaxMommersteeg** [comment]
The performance degradation is indeed massive. For now we don't mind having to write some stored procedures in order to make our synchronization processes work fast. However like you said, it is a shame we can't (because of performacne) use the services like other plugins do.  Especially when looking at the future. We will need to compare database sheme's carefully, whenever we are trying to update to a new version of nopCommerce. On the other hand we can easy rewrite the plugin to work with services, when in the future (especially) insert performance improves.

The performance gain you achieved with 10K products is not bad at all. Will do some investigations at my end. Thanks for your reply.

**Comment by turbochris** [comment]
@MaxMommersteeg : Just tuning in. You mention "recreating context". If you really did this per. 100 product there should not be a serious issue using EF. So my guess is that you forgot about events. We had a solr plugin that consumed most of our resources. I believe that nop's buildin REDIS cache must be similar (did not check though)..

**Comment by kfuglsang** [comment]
@tskaiser Would you mind posting a snippet of how you recreate the Autofac scope in your bulk import process?

**Comment by tskaiser** [comment]
@kfuglsang Sure.

You can use `var scope = EngineContext.Current.ContainerManager.Container.BeginLifetimeScope()` to fetch a new scope object. You can use this object to resolve types registered with Autofac, which will be independent from the current scope eg.

`var products = scope.Resolve<IRepository<Product>>();`

Be aware that EF does not support mixing of entities from different contexts, so beware of doing this. A good rule of thumb is to use no reference types from previous scopes and to be done with all data from the current process chunk before starting on a new one with a new scope.

**Comment by tskaiser** [comment]
I originally made this service interface to reuse this pattern of "chunking"

`public interface IScoped { ILifetimeScope SetScope(ILifetimeScope scope);  }`

Where SetScope is meant to be implemented so it re-resolves all Autofact references in a service, eg.

```
public class SomeService : IScoped {
  private IProductService _productService;
  private ICategoryService _categoryService;

  public SomeService(IProductService productService, ICategoryService categoryService) {
    _productService = productService;
    _categoryService = categoryService;
  }

  public SetScope(ILifetimeScope scope) {
    _productService = scope.Resolve<IProductService>();
    _categoryService = scope.Resolve<ICategoryService>();
  }
}
```

I then made extension methods to facilitate chunked processing of data:

```
public static class ScopedExtensions {

  private static ILifetimeScope NewScope => EngineContext.Current.ContainerManager.Container.BeginLifetimeScope();

  private static ILifetimeScope RequestScope => EngineContext.Current.ContainerManager.Scope();

  public static void ChunkedScopeProcessing<T>(
    this IScoped self,
    IEnumerable<T> input,
    int chunkSize,
    Action<T> action
  ) {
    var scope = self.SetNewScope();
    try {
      var i = 1;
      foreach (var arg in input) {
        if (i%chunkSize == 0) {
          scope.Dispose();
          scope = self.SetNewScope();
        }
        i++;
        action(arg);
      }
    }
    finally {
      scope.Dispose();
      self.SetRequestScope();
    }
  }

  public static ILifetimeScope SetRequestScope(this IScoped self) {
    return self.SetScope(RequestScope);
  }

  public static ILifetimeScope SetNewScope(this IScoped self) {
    return self.SetScope(NewScope);
  }
}
```

This enables an `IScoped` service to call `this.ChunkedScopeProcessing<T>(this, input, chunkSize, action)` where action is some void lambda, such as a void method group on `this`. The result is that it runs action on the elements of the input, recreating the scope every chunkSize iterations.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
