### ISSUE TITLE
Caching is not working or some configurations are needed?

### ISSUE THREAD

**Issue by ismailyilmaz** [nopSolutions/nopCommerce#1701]
I'm debuging caching mechanism of this awesome app, but i think there is a problem with caching. I will write everything step by step to explain.

**Step 1 :**  I put a break point on "**IsSet**" method of "**PerRequestCacheManager**" and added a new "**Manufacturer**". (Cache is cleared for manufacturers after insert. It is done by "**RemoveByPattern**" method)

**Step 2:** I went to details of inserted manufacturer(In this step manufacturer is not in cache which is expected. Therefore its added to cache with its Id and now its in cache.)

**Step 3:** I  **DIDNT** do any change and **DIDNT** click save button and i clicked **PRODUCTS** link in navigation menu to see products list.  

**Step 4:** From products page, i again went to manufacturers list and went to details of inserted manufacturer and boom. There is no manufacturer with this id in cache.(Actually other keys have gone too. Cache is totally empty.) But we already and definatelly added it to cache when we first went to details of it.

This is bug or feature?:)

**Comment by AndreiMaz** [comment]
cache could be cleared by a schedule task

**Comment by ismailyilmaz** [comment]
So could you please tell me that default task? it's really important! I couldn't see any task that triggers clear function of cache manager. And i also recognized another strange thing. I installed Redid and made its configuration for local. It works and your implementation for redis as clear as "litsa adnoy ruskoy devushkoy":) you first use perrequest caching before redis, but when you remove something from redid it doesn't remove it from it from perrequest cache, is this a design choice?

**Comment by AndreiMaz** [comment]
The schedule task name is "Clear cache"

P.S. Could you please post all questions on our forums.
