### ISSUE TITLE
Localize dates in admin area (dashboard, footer)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1702]
please see some screenshots attached

![footer](https://cloud.githubusercontent.com/assets/5019111/17994454/80043ca8-6b61-11e6-9204-b66590aa1374.PNG)
![weekdays](https://cloud.githubusercontent.com/assets/5019111/17994462/83c7ff6e-6b61-11e6-9ffd-8d840d73f9c6.PNG)

**Comment by Crilando** [comment]
Found another section: "All plugins and themes" In the headline section. "Here you can find third-party extensions and themes which..."

Another request: Some of the pages in 3.8 admin area contains just a help phrase in the headline section. Would be great for beginner, if all pages could have some help information in that sections.

**Comment by Crilando** [comment]
The same subject: under 'configuration > email accounts' there are no mor ehints, but they are in the resource table. 
![helpmissing](https://cloud.githubusercontent.com/assets/21255405/18040864/a592af92-6db2-11e6-8498-07d2d02cbb91.PNG)

**Comment by Crilando** [comment]
Hello, i've found one another part to translate. The PayPal Standard plugin where is something to do...
First the Instruction part, second the field hint "Your PDT token here...". Attached the Screen.
![paypal](https://cloud.githubusercontent.com/assets/21255405/18199420/7aacfe44-7100-11e6-845b-8cf2b567f69c.png)

**Comment by AndreiMaz** [comment]
split to multiple tasks #1788, #1787, #1789
