### ISSUE TITLE
Allow add to basket from catalog page for products that have "readonly" product attributes only

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1705]
Source: http://www.nopcommerce.com/boards/t/43893/suggestion-allow-add-to-basket-from-catalog-page-for-products-that-have-readonly-product-attriubutes.aspx

put an appropriate logic into AddProductToCart_Catalog method of ShoppingCartController

**Comment by skoshelev** [comment]
Closed #1705
