### ISSUE TITLE
Combine "Fixed Rate Shipping" and "Shipping by weight" plugins into single one

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1706]
They use the same shipping methods.
1. Let's just introduce "Basic" and"Advanced" modes.
2. Then let's choose a new name for this plugin.

Similar task #1757

**Comment by skoshelev** [comment]
Upgrade instructions: do not forget to manually delete "/Plugins/Shipping.FixedRateShipping" and "/Plugins/Shipping.ByWeight" directories (they are not used anymore), and replace the plugin «Shipping.Fixed Rate» or «Shipping.ByWeight» by the plugin «Shipping.FixedOrByWeight» in the App_Data/InstalledPlugins.txt file.

Closed #1706
