### ISSUE TITLE
Robots.txt rules incorrect match

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nopSolutions/nopCommerce#1714]
Aadd / to the end/ For example "/cart" rule disallow all product urls starting with "/cart*". For example http://sitename.com/cart{oon}

P.S. Anyway, it's also wrong according to https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt. We should find some other solution.

**Comment by Xzelsius** [comment]
If you add / to the end it allows sitename.com/cart but blocks sitename.com/cart/someaction.
So you should better add allow rules for the other urls.

A solution may be to add all active url slugs to robots.txt under allow section.

**Comment by AndreiMaz** [comment]
Anyway, it's also wrong according to https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt. We should find some other solution.
