### ISSUE TITLE
We shouldn't allow a store owner to insert negative values, while there is no support for it.

### ISSUE THREAD

**Issue by MaxMommersteeg** [nopSolutions/nopCommerce#1716]
Discounts, prices, etc

For example, we shouldn't allow users to insert negative discounts, while there is no support for it.
. At of this moment, NopCommerce 3.80 does not calculate negative discounts. However it is possible to insert a negative discount in percentage. It is also possible to set a negative discount amount in currency. 
![negative_discount](https://cloud.githubusercontent.com/assets/9657173/18141165/b9e1a0f4-6fb8-11e6-8328-6b214358c8e4.png)

This suggests that inserting a negative discount succeeded and is active from now on. However this is not the case. Also See following issue: https://github.com/nopSolutions/nopCommerce/issues/258

alse see http://www.nopcommerce.com/boards/t/47232/bug-maximum-discounted-quantity-should-not-be-allowed-to-have-zero-or-negative-values.aspx

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
