### ISSUE TITLE
Issue with "Terms of service" dialog size

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nopSolutions/nopCommerce#1718]
![dialog size](https://cloud.githubusercontent.com/assets/7976740/18159844/4211b64c-7033-11e6-909e-ff0c7baa4c13.png)

**Comment by AndreiMaz** [comment]
Please clarify. Do you suggest to make the window width bigger?

**Comment by Andrey-Pavlov** [comment]
Hello, I suggest to add X/Y center alignment, a scrollbar and size in percentage for this dialog.

**Comment by AndreiMaz** [comment]
Андрей, спасибо!

**Comment by praveenksharma** [comment]
I am also looking for a solution for this @AndreiMaz .

Can you please guide me how can we add scrollbar to it. I have a big Terms of Service and it looks really odd.

Thanks,
Praveen
