### ISSUE TITLE
Use <ul><li> instead of <br> when formatting attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#172]
We format checkout/address/product attributes (e.g. IProductService formatter). Usage of < ul >< li > instead of < br > could benefit. 

But we also have PdfService to print order details. PDF does not support < br / >. It uses line breaks (\n). It uses “ConvertHtmlToPlainText” of HtmlHelper which currently does not support conversion of < ul >< li > to “\n”. Without it PDF invoices won’t be printed well.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
