### ISSUE TITLE
Products have references to deleted Tax Categories and use them (even when deleted)

### ISSUE THREAD

**Issue by RoboBurned** [nopSolutions/nopCommerce#1722]
"Fixed tax rate provider"

![ca334870-705f-11e6-9fc2-b856b3363b28](https://cloud.githubusercontent.com/assets/5019111/18192426/c60c36ee-70dc-11e6-84ba-0ba82d7c624a.png)
Steps to reproduce

1. - Create a tax category
2. - Assign tax category to the product
3. - Delete tax category

Expected results:
TaxCategoryId of Product is set to 0

Actual results:
TaxCategoryId of Product points to non-existing tax category

The same is about "Tax By Country & State & Zip" provider

**Comment by RoboBurned** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/14316268/18168766/f6a08e72-705f-11e6-9952-142ba63426c0.png)

**Comment by AndreiMaz** [comment]
not the issue as it'll be handled as set to 0

**Comment by RoboBurned** [comment]
Can you please clarify. Do you mean it "will" be handled so in next version or it should be handled as 0 right now? Because as I can see on my site it does not work this way. I had a situation where no Tax Category is displayed on Categories page, no category is displayed on product page, no tax rates are displayed on FixedRate tax plugin configuration page but the price on site is displayed with tax value.
I had nice time investigating why it displays price with extra fee.

As I can see from code below and from going through the call chain, on product details page the method CreateCalculateTaxRequest is called by GetProductPrice and it is called with 0  tax category id. In this case category ID is taken directly from product without any checks for its existing and then passed directly into tax plugin. 

```
public virtual decimal GetProductPrice(Product product, decimal price,
    bool includingTax, Customer customer, out decimal taxRate)
{
    bool priceIncludesTax = _taxSettings.PricesIncludeTax;
    int taxCategoryId = 0;
    return GetProductPrice(product, taxCategoryId, price, includingTax, 
        customer, priceIncludesTax, out taxRate);
}
.....
protected virtual CalculateTaxRequest CreateCalculateTaxRequest(Product product, 
    int taxCategoryId, Customer customer)
{
...

    var calculateTaxRequest = new CalculateTaxRequest();
    calculateTaxRequest.Customer = customer;
    if (taxCategoryId > 0)
    {
        calculateTaxRequest.TaxCategoryId = taxCategoryId;
    }
    else
    {
        if (product != null)
            calculateTaxRequest.TaxCategoryId = product.TaxCategoryId;
    }
...
```
Am I missing something?

**Comment by AndreiMaz** [comment]
"In this case category ID is taken directly from product without any checks for its existing and then passed directly into tax plugin"

**Comment by AndreiMaz** [comment]
After some more investigation I can confirm that you're absolutely right. I've just merged your second ticket with this open. Thanks a lot!

**Comment by AndreiMaz** [comment]
Fixed. Thanks a lot again!
