### ISSUE TITLE
Plugin.Tax.FixedRate Settings not cleared after removing TaxCategory

### ISSUE THREAD

**Issue by RoboBurned** [nopSolutions/nopCommerce#1723]
After settings for FixedRate Tax plugin were saved for categories they remain in database even after tax category is deleted. They should be deleted.

**Comment by RoboBurned** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/14316268/18168726/ca334870-705f-11e6-9fc2-b856b3363b28.png)

**Comment by AndreiMaz** [comment]
merged with https://github.com/nopSolutions/nopCommerce/issues/1722#
