### ISSUE TITLE
Delete unused images from filesystem and database

### ISSUE THREAD

**Issue by MaxMommersteeg** [nopSolutions/nopCommerce#1724]
The Thumbs and Content folder store a lot of images. Considering a nopCommerce instance to run several years, both folders will grow and become bloated.

Thumbs and images should be removed when no relation exist between a Picture entity and a Product/Category in the database. 

A ScheduledTask for deleting unused images from filesystem and database would be ideal imho.

**Comment by AndreiMaz** [comment]
"when no relation exist between a Picture entity and a Product/Category in the database" - pictures could be used a in a lot of other cases (e.g. in settings, custom plugins, etc). It they cannot be deleted automatically.

But we can clear thumbs directory periodically

**Comment by turbochris** [comment]
I disagree with this. At least it should be manual (or very old ones). Reason being that google images also counts as SEO. So at least we are from a store perspective not interested in deleting images.

**Comment by turbochris** [comment]
An advanced (and cool feature) would be is a plugin that catch the "jpg" request and maybe serve a "This picture is depreciated, please visit xxx instead" default image would be nice. 

I have played around with this in the past. But the performance hit on IIS is severe because the mime type have to be treated as dynamic content and thus not cached static by iis.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box.

**Comment by SPCteam** [comment]
There could be a fixed or user-defined folder structure (under "images") where specific content could be insulated from each other. With such a structure (say: "images/system" & "images/category" & "images/product"), there could be somewhat easier identification of images which are no longer desired in any form, and be deleted. 

There could also be a method of linking to an "original" image in a user designed structure on the web server (still under "images" if required). This would allow more flexibility & transparency for store admins wishing to work with the images directly. Currently, (as I understand it) there is no way to reference an existing original image that is already on the web server (except by import & then image gets a filename change & duplicated)... and no practical way to identify which image should be "overwritten" manually with an updated 'original' if the store admin wishes to do so.

IMO, there is no reason for most of our products to 'automatically' duplicate the exact same image (unless I choose for that to be the case for a specific SEO benefit)...  IMO, there should be a work-flow that allows for using "originals" in-place.

**Comment by AxelAndersen** [comment]
I have the same issue with a lot of images related to products that we do not sell any more (dont exist).

Would be nice to have method to delete a product, and everything associated with that product, both i database and file system.
And this method should proper delete, not soft delete like it is now.
