### ISSUE TITLE
Sorting issue when filtering categories by store

### ISSUE THREAD

**Issue by turbochris** [nopSolutions/nopCommerce#1726]
The SD here is self explanatory:

![bug in filtering](https://cloud.githubusercontent.com/assets/15609238/18198752/a8b61882-70fd-11e6-8346-49f6cc67ea69.png)

When you have alot of categories, this becomes confusing. Expecially since the "tree" view have been discontinued...

**Comment by turbochris** [comment]
BTW: its only when filtering by store. The order is fine when no filter is applied....

**Comment by AndreiMaz** [comment]
@turbochris  Could you please share the entire screenshot (with "Display order" column)?

**Comment by turbochris** [comment]
@AndreiMaz . Sure. I am now a bit confused actually. Seems it have something to do with the store mappings.

So here is two screenshot (I added which of my stores it's mapped to)

main store is called PostMe:
![screendump postme](https://cloud.githubusercontent.com/assets/15609238/18288032/fda27712-7479-11e6-9159-a76033316f50.png)

This store is called PostMeDentalSweden:
![screendump postmedentalsweden](https://cloud.githubusercontent.com/assets/15609238/18288050/162b7ef0-747a-11e6-9b0d-a03881b2dfb5.png)

The store "PostMe" is the only one mapped to "Dental Care". PostMeDentalSweden is mapped to all below "Dental Care"

**Comment by turbochris** [comment]
I think it's a minor bug. Most people will probably make seperate category tree for each store...

**Comment by AndreiMaz** [comment]
@turbochris Which is the value of "commonSettings.UseStoredProcedureForLoadingCategories" setting?

**Comment by turbochris** [comment]
That is set to False

**Comment by AndreiMaz** [comment]
@turbochris Chris, we still cannot reproduce the issue. Please try to debug it for your local copy. "GetAllCategories" method invokes "SortCategoriesForTree" method (Libraries\Nop.Services\Catalog\CategoryExtensions.cs), And "SortCategoriesForTree" method sorts all categories property. Child subcategories go right after a parent one

If you can find the issue, then re-open this ticket
