### ISSUE TITLE
Recently viewed products should be horizontally centered

### ISSUE THREAD

**Issue by MaxMommersteeg** [nopSolutions/nopCommerce#1727]
When dealing with different product image widths, we can see following result:
![wrongaligned](https://cloud.githubusercontent.com/assets/9657173/18199823/5e14e8b2-7102-11e6-8f15-573198ec157d.png)

This is due to the difference in width:
![imagewidth](https://cloud.githubusercontent.com/assets/9657173/18199831/6a7acea0-7102-11e6-977e-66552998bafa.png)

And

![imagesize2](https://cloud.githubusercontent.com/assets/9657173/18199836/712a5f54-7102-11e6-8af9-85c6109b0072.png)

Adding `text-align: center;` to the product-picture style class resolves this issue:
![correctaligned](https://cloud.githubusercontent.com/assets/9657173/18199863/879146c2-7102-11e6-9f7b-8fea881adff2.png)

I can create a new pull-request in a couple of days for this issue, if desired.

P.S. I used the default theme that ships with nopCommerce.

**Comment by AndreiMaz** [comment]
Actually they're aligned. According to your screenshots your picture of 7up has some padding but Fanta doesn't

**Comment by MaxMommersteeg** [comment]
So by default they are aligned left/start? This does solve the issue where some pictures would have padding  (whitespace in image) and some don't have padding.

**Comment by AndreiMaz** [comment]
yes
