### ISSUE TITLE
Pre-configuration of a store during installation (based on a specified country)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1730]
Allow a store owner to pre-configure store. For example, during installation we can ask some questions such as "Your country". Based on a country we can:

1. download and pre-install a language pack from the official site
2. pre-configure some settings (e.g. PangV or "Display tax/shipping info" settings for Germany)
3. pre-configure some shipping details, VAT settings, currencies, measures, etc
4. pre-download some regional plugins
5. other ideas?

Maybe, we won't implement anything but some points can be definitely finished (a language pack installation) 

Other idea is to have other kind of "country" packs that will contain country specific information (e.g. taxes, currency, etc, as above)

**Comment by eadameg** [comment]
Other ideas:
Multi-store? if not hide multi-store options
Multi-language? if not hide multi-language options
Track inventory? If not set values accordingly for inventory control section
Ability to st some default values for product, categories, etc. such as pages sizes, etc.

**Comment by DmitriyKulagin** [comment]
Cosed #1730
