### ISSUE TITLE
Switching media storage to file system times out and throws 500 error

### ISSUE THREAD

**Issue by sumo300** [nopSolutions/nopCommerce#1734]
Version: 3.40
Host: Azure

When switching from DB storage to file system storage for media (~17K images), the admin page times out and then the site throws a 500 error.  Navigating back to the site makes it seem like the switch worked.  However, the database and file system are left in an unknown state and it is likely that some images have gone missing (as explained in my [forum post about the topic](http://www.nopcommerce.com/boards/t/43991/switched-to-filesystem-from-db-for-picture-storage-500-error.aspx)).

I intend to upgrade to the latest version (thought it is a drastic upgrade due to some themes no longer being available), but was hoping this issue could be tested on the latest version.  As stated in other forum posts, this is supposed to work and nopCommerce is supposed to write the images stored in the database out to the file system (and vice versa).

If this is still an issue in the latest version, I recommend making this a queued and threaded operation so that request timeouts cannot abort the operation (if that's what the actual problem is).  Doing so would actually also allow the site to function completely without breaking images (update them one at a time regardless of how long it takes).

**Comment by AndreiMaz** [comment]
it was significantly improved in the latest versions

**Comment by leo-tabakov** [comment]
Same issue here on Version: 3.80. @AndreiMaz Could you please advise on which version it was fixed and is there any workarounds for this issue?
