### ISSUE TITLE
Option to easily integrate 3rd party comments

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1737]
Please think of a way to easily integrate/replace 3rd party comments like Facebook, Disqus etc for 
- Products page
- News
- Blogs
etc...

**Comment by AndreiMaz** [comment]
already supported with Web API.

**Comment by sukeshak** [comment]
Thank you 👍

**Comment by sukeshak** [comment]
@AndreiMaz which Web API were you referring to? Anything officially coming up?

**Comment by AndreiMaz** [comment]
https://github.com/SevenSpikes/nopCommerce/tree/Web-Api-3.70

**Comment by sukeshak** [comment]
I have seen that. 
Any update when(or if) this would become part of nopCommerce?
If you see its still on 3.7

**Comment by sukeshak** [comment]
Looks like here now
https://github.com/SevenSpikes/api-plugin-for-nopcommerce

**Comment by AndreiMaz** [comment]
it won'r be part of nopCommerce. it'll be available as third-party plugin. you can contact nop-templates team to get more info about it

**Comment by sukeshak** [comment]
Ok thank you 👌
A UWP app for Windows 10 would be awesome.
Hope I find time to build one, if none jumps in before me :)
