### ISSUE TITLE
Bug: Tier pricing with attribute combination not working

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1745]
I have a product A
Product attributes - sizes => Small, Medium & Large

I add Tier pricing for quantity
Actual price - 1200
>=5   - Price 1000
>=10 - Price 800 

Now if customer purchase 3 Small & 2 Medium (Total 5 pieces), Price should be 1000.
This does not work :(

Tier pricing works only if the purchased product is of the same Size (Product attribute).
I believe its a bug, please take a look at it.

**Comment by AndreiMaz** [comment]
It works fine with "shoppingCartSettings.GroupTierPricesForDistinctShoppingCartItems" setting enabled.

Could you please post all questions on our forums (better suits for discussion)?

**Comment by sukeshak** [comment]
Sure. Thank you 👍
