### ISSUE TITLE
Support conditions for customer and address attributes

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#1746]
Similar to product &.checkout attributes

**Comment by AndreiMaz** [comment]
What conditions? Please clarify

**Comment by mehmetkurt** [comment]
Yes, such as product attributes. According to a customer attributes selection of different attributes it must be listed.

**Comment by noptools** [comment]
Also, ability to hide customer attribute from showing in public store.  (It's related but maybe this should be another issue ;)

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
