### ISSUE TITLE
ThemeableVirtualPathProviderViewEngine caching issue

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#175]
Source: http://www.nopcommerce.com/boards/t/35247/themeablevirtualpathproviderviewengine-misbehaves.aspx

**Comment by AndreiMaz** [comment]
It's the same as in https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Mvc/VirtualPathProviderViewEngine.cs - so it's fine
