### ISSUE TITLE
Database Maintenance - Rebuild or Reorganize Indexes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1752]
Let's add a new button to the Maintenance page. We should also check whether database supports it (stored procedures). also see how we did it in 1.X versions - [Nop_Maintenance_ReindexTables] stored procedure

Contribution: http://www.nopcommerce.com/boards/t/44246/database-maintenance-rebuild-or-reorganize-indexes.aspx

also see post (!!!) - http://www.nopcommerce.com/boards/t/44246/database-maintenance-rebuild-or-reorganize-indexes.aspx#175429 - a more cautious approach with the provided stored procedure that just generates a fragmentation report. but it's a task for DBA

**Comment by DarthSonic** [comment]
There is a nice script by Ola Hallengren to rebuild/reorganize indexes and statistics: https://ola.hallengren.com/sql-server-index-and-statistics-maintenance.html

As for Azure Db there is no Sql Server Agent it would be a very nice addition to be able to maintain a job from nopCommerce Administration to do these maintenance tasks.

Our experience with the script (using standalone sql enterprise server) is very good and satisfying (1.5 TB database, weekly maintenance task).

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
