### ISSUE TITLE
Tier pricing for attribute combinations

### ISSUE THREAD

**Issue by MehrdadKamelzadeh** [nopSolutions/nopCommerce#1759]
It would be nice to have tier pricing for attribute combinations. now just overridden price is supported.
sometimes if you buy a special configuration of a product with higher quantity there might be a discount for that combination. however, in  other cases it won't change the price.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
