### ISSUE TITLE
Allow a store owner to see product/checkout attributes and custom values in standard language (currently it's displayed in a customer language)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#176]
see http://www.nopcommerce.com/boards/t/33570/payment-info-custom-values-localize-for-admin-show-on-confirm-order-page.aspx

The issue that we store them in two formats (text and XML). Text is not localizable. But XML is. On the other hand it can cause issues if a store owner deletes or renames some attributes or their values

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
