### ISSUE TITLE
Make configurable what vendor can edit on the product details page

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#1767]
for example Deny Vendors see or edit  Shipping box, or Gift Card box, or else ....  in product info page.

**Comment by tigran-avdalyan** [comment]
limitation to select vendor in search page, when we have multi-store

**Comment by tigran-avdalyan** [comment]
@AndreiMaz  Vendor in Store1 can map product to Store2.
Needs Limitation by store for Vendors.

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
Let ability to limit Payment Method for Vendors
Let ability to limit Shipping method for Vendors

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
