### ISSUE TITLE
Add  Geography latitude, longitude support in product info if item is Real Estate .

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#1768]
Its very important if you Sale or Rent Real Estate.

**Comment by tigran-avdalyan** [comment]
http://www.nopcommerce.com/p/2567/nop-google-maps-integrate-plugin-for-showing-product-locations.aspx

for example

**Comment by tigran-avdalyan** [comment]
https://github.com/openstreetmap

**Comment by tigran-avdalyan** [comment]
http://greatmaps.codeplex.com/

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
