### ISSUE TITLE
Add external authentication to register page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1771]
I think external authentication should be added to register page as  well.
if a user wishes to register and press the register link he does not know about the external login/register option.

Source: http://www.nopcommerce.com/boards/t/44416/add-external-authontication-to-register-page.aspx

**Comment by suddenelfilio** [comment]
I think it would be wise to look at an existing solution like IdentityServer to integrate into nopcommerce as it already has lots of web auth scenario's out of the box. Also looking at the 4.0 release including an upgrade to Asp.Net Core the IdentityServer v4 is already up to the task.
