### ISSUE TITLE
Remove My Account and Search From Default Top Menu

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1776]
I would like to suggest the removal of the menu items My Account and Search from the default top menu. With the default template and most other templates, there is a search box and a My Account link at the top. Having those links also display on the top menu are redundant and take up valuable real estate.

Source: http://www.nopcommerce.com/boards/t/44443/remove-my-account-and-search-from-default-top-menu.aspx

**Comment by tigran-avdalyan** [comment]
We can add setting that enable/disable My Account and Search from top menu.
