### ISSUE TITLE
PayPalStandard and PDT (IPN) validation 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1780]
We are having some problems with PayPalStandard plugin that I'd like to discuss and see if you've gone through something similar.

In one of our NopCommerce instances we have the setting RoundPricesDuringCalculation set to FALSE. This has allowed us to solve some rounding issues and to reflect more accurate computations. 

In PayPalStandard PostProcessPayment method, the prices of the products, shipping, payment and taxes are rounded in each step and sent to PayPal. The RoundPricesDuringCalculation  = FALSE circumstance is not checked, and precission is lost in every step. After the processing, if everything is correct PayPal will send back an mc_gross field, with the total of the order.

If we assume that we're using PDTHandler (at PaymentPayPalStandardController) we can activate PdtValidateOrderTotal setting to check that the total provided by PayPal and the total stored in the database match. In my case, this validation (that is very important because it allow us to avoid some fraud cases) usually fails because there is a slight differente between the amounts:
- (payPalStandardPaymentSettings.PdtValidateOrderTotal && !Math.Round(total, 2).Equals(Math.Round(order.OrderTotal, 2)))
- PayPal PDT. Returned order total 29,50 doesn't equal order total 29,4847

As you can see, the order total amount is perfectly valid, but the comparison fails. I'm assuming that quantities are transfered to PayPal with only two decimal places because it has to be like that. But, if it has to be like that, isn't this comparison too strict?. Shouldn't it allow a small deviation?.

And also, does anybody know why this check is performed in the PDTHandler but not in the IPNHandler?. As far as I know, it seems that mc_gross is returned by PayPal in both methods.

Source: http://www.nopcommerce.com/boards/t/35862/concerns-about-paypalstandard-and-rounding.aspx

**Comment by mcliment** [comment]
A I've commented in @RomanovM commit, the error accumulates with the number of items. A rough solution we've adopted is proposed in the comment and involves multiplying the error by the number of items in the cart.
