### ISSUE TITLE
Customers. Add a column indicating in which store a customer registered

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1784]
It can be helpful for reports.

We can display this field (static label) on a customer details page. But we should do it only when we have two or more stores configured.

Upgrade. Set it to 0 if we have only two or more stores. Set to the only existing store ID if we have only one store. If set to 0, then hide this field. If store cannot be loaded (e.g. deleted), then also hide it.

Don't forget to update CodeFirstInstallationService

Source: http://www.nopcommerce.com/boards/t/44504/multistore-registered-customers.aspx

**Comment by sukeshak** [comment]
Also an option to restrict the user to a specific store.

**Comment by skoshelev** [comment]
Closed #1784
