### ISSUE TITLE
Localize grids

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1787]
![browseractions](https://cloud.githubusercontent.com/assets/5019111/17994443/75b6a970-6b61-11e6-8638-48147445e074.PNG)
![browserstatus](https://cloud.githubusercontent.com/assets/5019111/17994446/78a96262-6b61-11e6-855e-d39d08b02ea4.PNG)
![browsertotals](https://cloud.githubusercontent.com/assets/5019111/17994447/7a812da4-6b61-11e6-87bd-6587252661ed.PNG)

but we also have a task to replace the grid. let's do it first

**Comment by skoshelev** [comment]
Closed #1787
