### ISSUE TITLE
Localize all hard-coded intructions

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1788]
Plugins, etc

For example,
![captcha](https://cloud.githubusercontent.com/assets/5019111/17994450/7c3d40f6-6b61-11e6-9451-b6806b4e63ac.PNG)

 "All plugins and themes" In the headline section. "Here you can find third-party extensions and themes which..."

**Comment by skoshelev** [comment]
Closed #1788 ([code](https://github.com/nopSolutions/nopCommerce/commit/3827404ae38aed8f30c7a24bf7d124f00e693ea1))
