### ISSUE TITLE
Publish Inserted, Changed and Deleted Events for OrderItems for Fulfillment

### ISSUE THREAD

**Issue by comperiotech** [nopSolutions/nopCommerce#1790]
For fulfilling orders via third parties, it would be convenient if events regarding inserted, changed and deleted to OrderItems were published individually. Currently, the only way to do this properly is with custom checks.

I have never tried a pull request and I am a crappy coder, but I could try to tackle this.

Source: http://www.nopcommerce.com/boards/t/44525/fulfillment-feature-request.aspx

**Comment by AndreiMaz** [comment]
if we do it, then for all entities. but in this case we'll have to create separate insert/update/delete for ALL entities.
