### ISSUE TITLE
Excel Export broken with too many vendors

### ISSUE THREAD

**Issue by pccruiser** [nopSolutions/nopCommerce#1798]
The validator does not work correctly in the WriteToXlsx function at this code block:

 foreach (var enumItem in dropDownElements)
                    {
                        validator.Formula.Values.Add(enumItem);
                    }

When you have too many vendors.  The way that code works is essentially like a CSV and only allows up to 255 characters.  So the sum total of characters can't be over 255.  That doesn't work for us.  We have a lot of vendors.  People who do a lot of drop shipping will.

The way to fix this is to move the validator to another sheet and put these in cells then give a formula to that method (it is looking for a formula anyway).

**Comment by AndreiMaz** [comment]
Thanks! But already fixed

**Comment by pccruiser** [comment]
Awesome thanks!  Do you have a link to the changeset with the fix?

**Comment by AndreiMaz** [comment]
Ohh, sorry it's not fixed yet. But here is a work item - https://github.com/nopSolutions/nopCommerce/issues/1778

**Comment by AndreiMaz** [comment]
here it is https://github.com/nopSolutions/nopCommerce/commit/2f38d15d9745786b1100e58ea570fd67137fbb7f
