### ISSUE TITLE
Enhance Product Attributes for selling by dimensions

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#18]
Sometimes products are sold by dimensions (lenght, surface, volume, weight, etc.) for that and other cases it will be convenient to: 

1) Have 1 or 2 types of new product variant attributes (Number (decimals accepted) and/or Integer). 
In this case Total Price (TP) and Total Weight (TW) for the product would have to be adjusted by a Price/Weight Factor (FPi/FWi) for the corresponding attribute multiplied by the attribute value (Vi) entered and by the original Price/Weight of the product variant (OP/OW); that is TP=OP \* V1 \* FP1 \* V2 \* FP2 ...; and likewise for weight. 

Example (a more general than your case) of playwood sold by surface defined by (1)length and (2)height. The price (OP) per sq.mt. would be 25 and the weight (OW) 2 per sq.mt. In this case FP1 and FP2 would be both equal to 1. 
Then applying the formula if customer buys an item of lenght 3 and height 5: 
TP=OP \* V1 \* FP1 \* V2 \* FP2 ... 
TP=25 \* 3 \* 1 \* 5 + 1 = 375 

If there are other product variant attributes there price/weight adjustments would have to be added at the end to TP/TW. 

2) Include price/weight adjustments by factor for attributes with Drop-down, Radio and Check-boxes control. 
This would be for the same reasons as described above, since some products are sold with some fiexed dimensions (example: height: 1.0 mt, 1.5 mts, 2.0 mts., 3.0 mts, etc.); thus in these cases (for discreete dimensions) some of those attribute controls must be used. 
This could be use in other situations. For example when the price adjustment is related to variant price. Examle pizza ingredients related to size/price; insurance/guranty extensions for appliances, etc. In these cases price adjustments are easier to configure. 

3) Let the storeowner configure the text used for the price adjustment. 
Now the options for the different attribute values with Drop-down, Radio and Check-boxes controls are shown as: "Value (+ PriceAdjustment)". It would be nice to have an additional option to define the price adjustment text . Examples 
"Value (+$50.00)" 
"Value ($150.00)" 
"Value (+10%)" 
"Value , $2.50 per sq.mt" 

Forum source: http://www.nopcommerce.com/boards/t/16762/suggestion-enhance-product-attributes-for-selling-by-dimensions.aspx

**Comment by dotcontrol** [comment]
any news on this? :) tx

**Comment by lesktr** [comment]
+1

**Comment by samdubey** [comment]
+1

**Comment by a3406007** [comment]
+1 PLEASE!

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/663
