### ISSUE TITLE
Add Address Token for shipping and billing address on Shipping Email

### ISSUE THREAD

**Issue by justinhof** [nopSolutions/nopCommerce#1801]
In addition to having each address item broken down as a token, have an overall address token that takes Name, Business Name, Address Line 1, Address Line 2, City, State and Zip, and remove empty line feeds if company name or address line 2 is null.

%Order.ShippingAddress% and %Order.BillingAddress%

Would need to be added for Order Notification template, Shipping Sent template, and Shipping Delivery Template.

[AM] Also see related work item - https://github.com/nopSolutions/nopCommerce/issues/48

**Comment by AndreiMaz** [comment]
We already have tokens for address parts (zip, country, address, etc). So  decided not to implement it out of the box
