### ISSUE TITLE
Qty inputs. Use "spin" buttons (arrows) or "dropdownlists"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1804]
Let's decide whether we need it (keep design simple?). Or make it configurable

Product details page: "qty". "customer enter qty" for product attributes associated to other products
Shopping cart/ wishlist buttons

**Comment by kingmotley** [comment]
The qty field in the car should be `<input type="number"` not `<input type="text"`, then most browsers will display the spin buttons automatically (which can be removed via CSS if you don't like them).  It will also cause the correct onscreen keyboard to show up, and also disallow entering letters into the box.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
