### ISSUE TITLE
Add validation to some fields on the product edit/create page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1805]
For example, 'Minimum cart qty' can't be 0

**Comment by sukeshak** [comment]
Even zip code in address does not have validation. It should be only numbers

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box (validate int < 0)

**Comment by sukeshak** [comment]
What about having only numbers in zip code in address?
I had failed payment issues due to that 😐

**Comment by ratulbside** [comment]
@sukeshak So far I know, not every country has only numeric zip codes. e.g. London has a zip code - **WC1V**.

**Comment by sukeshak** [comment]
Ah didn't know that. Thank you @ratulbside
