### ISSUE TITLE
GetLowStockProducts requires SQL Index

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#1813]
v. 3.8
I have a lot of products in test database (> 500000).
When GetLowStockProducts is executed from HomeController in Admin area I get an exception because query execution is very long.
When i'v added index for used fields in query - execution took ~700 ms.
So I think its better to add it.

**Comment by AndreiMaz** [comment]
Hi,

What exactly index have you added? Which columns?

**Comment by ArturAlekseev** [comment]
For Product table:
Index key column: Id
Included columns:
Deleted
VendorId
ProductTypeId
ManageInventoryMethodId
StockQuantity
MinStockQuantity
UseMultipleWarehouses

**Comment by ArturAlekseev** [comment]
Same optimizations are needed for Products table.
When there are a lot of products in it (>600k) I get 45% time consumption in SearchProducts procedure when navigating from category to category.
But if products table is fully indexed (all columns) then its still not very fast (around 16-20%) - maybe SearchProducts procedure should be made not so complex.

**Comment by skoshelev** [comment]
Closed #1813 (https://github.com/nopSolutions/nopCommerce/commit/c066f3d36cee7e4157dd11e156b00f2039ca8cb5)
