### ISSUE TITLE
Redis connection in Admin area

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#1814]
Issue is explained here in details: http://www.nopcommerce.com/boards/t/44397/problem-when-saving-shipping-restrictions-in-38.aspx

During RedirectToAction and so on after POST you get an exception.
To resolve the issue you need to comment or remove:
```
<sessionState mode="Custom"
...
</sessionState>
```
block in web.config
Otherwise looks like this string causes problems:
```
<add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="" accessKey="" ssl="true" />
```

**Comment by AndreiMaz** [comment]
It works fine. RedisSessionStateProvider string just was NOT properly configured (no host, no accessKey, etc)
