### ISSUE TITLE
Enable GZIP compression out of the box

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1816]
It can improve performance out of the box

also see http://www.nopcommerce.com/boards/t/44827/how-to-enable-gzip.aspx and http://stackoverflow.com/questions/1324481/setting-the-gzip-compression-in-asp-net

**Comment by suddenelfilio** [comment]
If you are enabling this thorugh settings for IIS. Please keep in mind that the dynamic compression module must be installed on the server for it to work, also enabling this might increase load on the server. There are known cases where this degraded the performance.

**Comment by AndreiMaz** [comment]
we should not do it because it can depend on the permissions on the server, installed modules, etc

**Comment by AndreiMaz** [comment]
we made it configurable in 4.00
