### ISSUE TITLE
Ability to add custom Registration method from plugin

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#1825]
Hello,
I would like to request a custom "Registration method" in nopCommerce under "Settings -> Customer settings" via plugin.
Idea is to extend registration method via some interface and ability to use that interface in plugin class same as nopCommerce scheduler as it provides ability to add scheduled tasks via plugin in nopCommerce.
This would let plugin developer to list their custom registration method via plugin without changing nopCommerce default source code and would also give customers (store owners) an ability to ask developers for some custom registration work flow.
Moreover, developer should also be able to call nopCommerce default registration method via some contract or function so for example if customer needs a custom SMS verification as well as default email verification so developer would not be needed to write his own code when that is already available in nopCommerce.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
