### ISSUE TITLE
Changing order status to "cancelled" do not update stock quantity

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#1827]
Hello, 

I have came across case where I have to cancel order from admin panel. It works fine when I use Cancel Order button to cancel order. It updates stock quantity with respect to quantity in order. For eg. If I have stock quantity = 0 after clicking Cancel Order Button stock quantity updates to 1. 

But it will not update stock quantity when you update "Cancelled" status using Change Status Button. 
For eg. If I have stock quantity = 0 after updating order status to Cancelled stock quantity remains same as 0. 

1 more problem I found, we have event like when stock quantity < min stock quantity then unpublish product. 
but if you consider 1 case then when stock quantity is updated to 1 due to cancel order at that time it must update Published flag = true. 

Nopcommerce version = 3.60 

Thanks

**Comment by AndreiMaz** [comment]
it's by design (as stated in description of this button)
