### ISSUE TITLE
Configurable fields for contact us form

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1832]
Phone and How Did You Hear About Us? Field on contact us page.

**Comment by iammourya** [comment]
This is an excellent feature and must have option. 
Please don't keep this on hold. 
In fact you may give the flexibility giving the option to add as many custom fields as per admin requirement. Mandatory or optional requirements. Finally when the user submits the contact us form, all the fields should be sent to the admin as a email or support ticket.

**Comment by eadameg** [comment]
There is a [plugin](http://www.nopcommerce.com/p/1461/build-your-own-contact-form-nop4youcom.aspx) for this

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. @eadameg  is right

**Comment by RenishSkills** [comment]
What if this is moved to a plugin instead, making customization much easier for developers and minimizing the need to modify the core application?

**Comment by exileDev** [comment]
Closed #1832
