### ISSUE TITLE
Email validation. cs_test@cs_test.com is not accepted

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1834]
See two commits:
https://github.com/nopSolutions/nopCommerce/pull/1830/commits/eb0bc13d0ab33b104fb651a78ac8a29e72627f3c
and
https://github.com/nopSolutions/nopCommerce/pull/1830/commits/e136e39d0edaf45558902b65f93995b65dc8be17

But actually I don't like that domain zones are hard-coded. Let's find some other validator (e.g. have a look at how FluentValidation implements it)

**Comment by skoshelev** [comment]
related #1628

**Comment by AndreiMaz** [comment]
duplicated
