### ISSUE TITLE
Add detailed description to the formula to calculate rates (Shipping by weight plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#1835]
additional info: http://www.nopcommerce.com/boards/t/34585/shipping-by-weight-problem.aspx

actually already on the documentation portal - http://docs.nopcommerce.com/display/en/Shipping+by+weight

**Comment by eadameg** [comment]
A couple of examples would be helpful

**Comment by eadameg** [comment]
[Combine it with the Shipping by [](Total](http://www.nopcommerce.com/boards/t/45416/suggestion-combine-shipping-by-weight-and-shipping-by-total-shipping-providers.aspx))
