### ISSUE TITLE
Reference wrong version of Microsoft.Data.Edm in plugins

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#185]
See http://www.nopcommerce.com/boards/t/39439/microsoftdataedm.aspx  and  premium support ticket 12221. The issue was that Nop.Web.Framework was copied to output (it should be ignored)

We can fix it. But it requires a lot of other third-party libraries to be added to our core libraries or plugins

**Comment by AndreiMaz** [comment]
not actual in 4.00
