### ISSUE TITLE
CashOnDelivery update to 3.90

### ISSUE THREAD

**Issue by Remedij** [nopSolutions/nopCommerce#1852]

**Comment by AndreiMaz** [comment]
this version is not released yet

**Comment by Remedij** [comment]
I was going to submit a merge request with that upgrade, so I've created a bug to link with branch. Ok then, whats the proper way to contribute?
Ondrej






On Tue, Nov 8, 2016 at 4:12 PM +0100, "Andrei Mazulnitsyn" <notifications@github.com> wrote:












this version is not released yet

**Comment by AndreiMaz** [comment]
there's no need to do it. 3.90 is not released yet. furthermore, this plugin is available out of the box
