### ISSUE TITLE
Estimate shipping cost when creating/editing product

### ISSUE THREAD

**Issue by networkfusion** [nopSolutions/nopCommerce#1861]
It would be helpful for one of my customers if it were possible to estimate the shipping cost when creating/editing a product taking into account the weight and additional shipping charges. At the moment they are complaining that they have to go to the shop and add the item to the basket every time they add a product in order to make sure shipping costs are covered.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization. Furthermore, it depends on shipping origin and destination that ar not known when adding a products (destination)
