### ISSUE TITLE
Affiliate details page. Remove "Affiliate identifier" field

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1863]
Anyway it's not useful anymore (we have "Affiliate URL" field)

**Comment by manojkulkarni30** [comment]
@AndreiMaz means remove the Affiliate identifier from the view in admin section right ?

**Comment by AndreiMaz** [comment]
@manojkulkarni30 yes

**Comment by manojkulkarni30** [comment]
Thank you for the reply @AndreiMaz . Please assign it to me. I will work on it.

**Comment by AndreiMaz** [comment]
@manojkulkarni30 please, go on
