### ISSUE TITLE
Questions of future changes 

### ISSUE THREAD

**Issue by vascofernandes** [nopSolutions/nopCommerce#1868]
Hello,

I have been looking for a new eCommerce solution for .NET.
nopCommerce is certainly interesting. Good work. 
After spending some days testing and poking around the code base, I have some questions/concerns.

There a quite a few pull requests (some I would say very important) siting around, some for months. Why is that ?

Typescript: What are your views ? Is there any plan to use Typescript ? If yes, what is the time frame ?

Javascript in Razor views: I noticed that there is Javascript sprinkled around the Razor views. For me this is a no go because you can't write unit tests for Javascript when you do this. Would you guys be open to have all Javascript in files ?

C# 6: I don't see use of C# 6 syntax in the code. Is there anything preventing this? Would it be OK to make pull requests using C# 6 syntax ?

**Comment by AndreiMaz** [comment]
Sure, you're more than welcome to contribute

But we do not plan to use Typescript

P.S. Actually this is not a work item. please post all further questions on our forums
