### ISSUE TITLE
Admin area. Add links to our social networks

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1880]
I mean pages like https://www.facebook.com/nopCommerce/ and twitter.com/nopcommerce

To the bottom of the menu? Footer?

**Comment by MaxMommersteeg** [comment]
'our social networks' as in nopCommerce's social networks or the webshop owner's social networks?

**Comment by AndreiMaz** [comment]
@MaxMommersteeg pages like https://www.facebook.com/nopCommerce/ and twitter.com/nopcommerce

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box.
