### ISSUE TITLE
Find a new default exchange rate provider to support USD as primary exchange currency. Or update ECB to support USD

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#190]
ECB plugin is limited to EUR currency. It should be limited (at least USD should be supported)

actually we can update ECB to support it. If we know EUR/USD and EUR/RUR rate, it means that we can find USD/RUR rate

Source: http://www.nopcommerce.com/boards/t/39333/regarding-modifying-noppluginexchangerateecbexchange-plugin-to-support-usd-as-primary-currency.aspx

also see http://www.nopcommerce.com/boards/t/41695/recommendations-for-exchange-rate-web-service.aspx

**Comment by AndreiMaz** [comment]
also see pull request (let's check it out) - https://github.com/nopSolutions/nopCommerce/pull/1441
