### ISSUE TITLE
Use one input and one output parameter for some methods (e.g. IPriceCalculationService and IOrderTotalCalculationService)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1900]
IPriceCalculationService, IOrderTotalCalculationService, ITaxService, etc. What else?

Right now we have a lot of input and output parameters. A lot of methods with the same names but different signatures. Let's use one input and one output parameter. Similar to "PlaceOrderResult PlaceOrder(ProcessPaymentRequest processPaymentRequest)" of IOrderProcessingService

**Comment by rchamorro** [comment]
I know it is not the what is being discussed here but taking that pattern to the extreme gets to the Mediator pattern that I find very neat and flexible.

And there is a good implementation of the MediaR pattern by @jbogard
https://github.com/jbogard/MediatR/wiki

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2448
