### ISSUE TITLE
Product Attributes - Can not add condition on attribute of type TextBox or FileUpload

### ISSUE THREAD

**Issue by vishalkotecha** [nopSolutions/nopCommerce#1904]
When adding attributes in a product, there is an option to View/Edit Conditions. I am able to add condition when the attribute type is Dropdown or Color Square or Radio Button list. But When I would want a condition like 

> if a user provides value in a textbox then only a dropdown menu should appear

, its not possible as of now.

**Comment by AndreiMaz** [comment]
no, it's supported please post all questions on our forums

**Comment by vishalkotecha** [comment]
No, It is not supported.

**Comment by AndreiMaz** [comment]
sure. you're right. I made a type. It's NOT supported (not planned to support now)
