### ISSUE TITLE
Do not require "shipment tracker" to have an active shipping rate computation provider

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1911]
Well, I guess I never noticed, but it appears that still "Tracking won't work with SD".  It's because when using Shipping Director, it is supposed to be the only ACTIVE shipping provider (rate calc method).  That's because otherwise duplicate methods would appear to customer since SD can conditionally call other shipping rate plugins to get their methods.  However, when getting a tracker, the core code is checking to see if the rate calc method is active...

The offending ;) code is in (3.80) \Libraries\Nop.Services\Shipping\Tracking\ShipmentExtensions.cs

var shippingRateComputationMethod = shippingService.LoadShippingRateComputationMethodBySystemName(shipment.Order.ShippingRateComputationMethodSystemName);
if (shippingRateComputationMethod != null && shippingRateComputationMethod.PluginDescriptor.Installed &&
    shippingRateComputationMethod.IsShippingRateComputationMethodActive(shippingSettings))
    return shippingRateComputationMethod.ShipmentTracker;

I don't see any downside to allowing Tracking when a shipping provider is not active.  Even if not using SD, a store owner may have had a provider active in the past, and then decides to no longer use it;  they should still be able to track prior orders.

Source: http://www.nopcommerce.com/boards/t/37036/shippingservice-sets-the-systemname-please-change-to-do-that-conditionally.aspx#179484

**Comment by sukeshak** [comment]
Can we also have a default option for tracking?
When you create a shipment, 
- Manually select a provider 
- Add tracking number?
this would help to show a clickable URL in the order shipment details for customers.

API interface is only available for bigger players and we tend to use smaller companies when its local shipping or cheaper.

**Comment by sukeshak** [comment]
Something suggested to me before here
http://www.nopcommerce.com/boards/t/44536/feature-request-option-for-shipment-tracking-and-tracking-url.aspx
