### ISSUE TITLE
Admin overides Call for price when impersonating via the admin console

### ISSUE THREAD

**Issue by pdmarty** [nopSolutions/nopCommerce#1916]
If someone calls and our staff impersonates the customer to enter the order they should be able to add these products to the cart and check out.  Otherwise they are as stuck as the customer.

**Comment by AndreiMaz** [comment]
please provide a complete list of steps to reproduce the issue and expected behaviour

**Comment by pdmarty** [comment]
With the call for price feature active on a number of products a customer calls into our staff.

- The staff looks up the customer or creates a customer account.
- Once the customer account is created they click on the impersonate tab then click Place Order.
- The staff should now be able add products marked call for price to the cart and finish the order.

Right now our staff is in the same position our customers are in.  They can't place the order without going to each product they want and disabling the call for price feature and then having to go back and re-enable the feature once the order is complete.

So when they click on place order in the impersonate tab, when it opens the frontend of the store it needs to somehow override the call for price feature.  Unless it would be easier to enable or disable this on a per customer basis.

Let me know if you need any more information/details.

**Comment by AndreiMaz** [comment]
thx. duplicates - https://github.com/nopSolutions/nopCommerce/issues/477

**Comment by pdmarty** [comment]
Sorry.  Missed that during the search.
