### ISSUE TITLE
More bulk operations

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1926]
•  Bulk Connect products with Categories
•  Bulk Copy products from one category to another
•  Bulk Increase / decrease product price by amount or percentage
•  Bulk set discount amount for multiple products
•  Bulk publish/unpublish products
•  Bulk Edit Products
___________________________________________

It is useful when there are several orders per day, to bulk edit order/payment/shipping status/dates and tracking number, similar to product bulk edition. Maybe some restriction would apply when an order is split in various shippings.

Let's think about what exactly could be moved to bulk edit functionality

Forum source: http://www.nopcommerce.com/boards/t/27284/suggestion-bulk-edition-of-orders.aspx

**Comment by tigran-avdalyan** [comment]
Bulk edit "Product tags"

**Comment by AndreiMaz** [comment]
decide to leave it for customization
