### ISSUE TITLE
Better vendor support

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1928]
TODO: We should split this work item to separate ones

•  Vendors. Support both consolidated and separate orders (https://github.com/nopSolutions/nopCommerce/issues/56)
•  Configurable shipping options and rates per vendor (https://github.com/nopSolutions/nopCommerce/issues/27)
•  Allow vendors to manage his own discounts (https://github.com/nopSolutions/nopCommerce/issues/7241)
•  A store owner can choose categories in which vendors can place their products (https://github.com/nopSolutions/nopCommerce/issues/7242)
•  PM support for vendors (allow customers to PM vendors) (https://github.com/nopSolutions/nopCommerce/issues/7243)
•  Vendor reviews (https://github.com/nopSolutions/nopCommerce/issues/7244)

**Comment by jack131900** [comment]
Hi Andrei, Would there be any enhancement or feature regarding vendor to specify their own shipping rates? For example, the customer will be able to select different shipping options per product and on checkout process under shipping method, only one method will be selected and that is the total shipping cost for the entire items in the cart. This is similar to Etsy. 

Also combined items. Primary and Secondary rates.
https://www.etsy.com/help/article/191

**Comment by tigran-avdalyan** [comment]
#2257

**Comment by tigran-avdalyan** [comment]
Limit Multi-store for Vendor(ability to deny access to current Store)

**Comment by onebox-dev** [comment]
2 years ago

**Comment by beceke** [comment]
Will this development be released with 4.50?

**Comment by loid345** [comment]
Compared with the features of vendor for magento, there was practically no work in this direction
https://www.vnecoms.com/magento2-marketplace/features.html

**Comment by pradeepgururani** [comment]
All the features mentioned are required to make nop-commerce a true marketplace platform. What an irony that these work-items are thought about in 2016 and not moved forward.

I would like to see these features done by the nop team instead of each marketplace customer implementing their own flavor.

**Comment by AndreiMaz** [comment]
I've just create separate work items for each task:

•  Vendors. Support both consolidated and separate orders (https://github.com/nopSolutions/nopCommerce/issues/56)
•  Configurable shipping options and rates per vendor (https://github.com/nopSolutions/nopCommerce/issues/27)
•  Allow vendors to manage his own discounts (https://github.com/nopSolutions/nopCommerce/issues/7241)
•  A store owner can choose categories in which vendors can place their products (https://github.com/nopSolutions/nopCommerce/issues/7242)
•  PM support for vendors (allow customers to PM vendors) (https://github.com/nopSolutions/nopCommerce/issues/7243)
•  Vendor reviews (https://github.com/nopSolutions/nopCommerce/issues/7244)
