### ISSUE TITLE
Multiple pictures associated to product attribute value and product attribute combination

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1934]
it would be great if we could have multiple images that define color per product. when we have a red shoe we can relate the red color (not with the square color box) but with an image that shows a red shoe. However we cannot have multiple images that are related with the red show. so when we see it in the product page we see below in the thumbnails images of the show with the green color e.t.c

also see http://www.nopcommerce.com/boards/t/45275/nopcommerce-enterprise-discussion.aspx#179825

**Comment by exantasNop** [comment]
Waiting !!!

**Comment by skoshelev** [comment]
Closed by https://github.com/nopSolutions/nopCommerce/commit/92296a1956220fa9ddfd2b3f72ed582103b9616c
