### ISSUE TITLE
Autofac warning about "ContainerBuilder.Update" method

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1935]
'ContainerBuilder.Update(IContainer)' is obsolete: 'Containers should generally be considered immutable. Register all of your dependencies before building/resolving. If you need to change the contents of a container, you technically should rebuild the container. This method may be removed in a future major release.'

we have to fix it

**Comment by agametov** [comment]
In future, may be helpful for fix  https://github.com/autofac/Autofac/issues/811

**Comment by AndreiMaz** [comment]
@agametov Thanks, Rustam!
