### ISSUE TITLE
Add "Shipping by Total" functionality to "Shipping by Weight" plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1955]
It is only needed to add the "Order subtotal From" and "Order subtotal to" columns (defaults: 0 and 1000000 respectively) to the Shipping by Weight plugin and it will cover both cases weight and total. Then rename existing "From" and "To" properties to "Weight from" and "Weight to" respectively. We alread have "fixed" fee supported (use AdditionalFixedCost property). Now we just have to add appropriate filtering to "FindRecord" method of \Nop.Plugin.Shipping.FixedOrByWeight\Services\ShippingByWeightService.cs

And of course, now we have to rename the plugin, appropriate database table, etc to soemthing else. Ideas? FixedWeightTotal? ShippingByWeightTotalRecord? Let's decide

Source: http://www.nopcommerce.com/boards/t/45416/suggestion-combine-shipping-by-weight-and-shipping-by-total-shipping-providers.aspx

At the same moment we already have a plugin (http://www.nopcommerce.com/p/669/shipping-by-total.aspx). Should we do it?

**Comment by AndreiMaz** [comment]
also see https://github.com/nopSolutions/nopCommerce/issues/2550 (plus volume)

**Comment by skoshelev** [comment]
Closed #1955
