### ISSUE TITLE
Allow VAT number to be entered in the anonymous (guest) checkout. Or notify guest that it's possible only after registration

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1961]
also see https://www.nopcommerce.com/boards/t/47929/eu-vat-customer-with-invalid-vat-should-not-be-able-to-order.aspx

Let's just decide what we have to do what VAT number requires some validation from a store owner (a tax setting). At least we should decide what we have to display or allow so guests understand that they can enter VAT numbers (e.g. only after registration)

So let's add setting 1. It will only be considered when `EuVatEnabled` is enabled.
If this new setting is disabled, then during anonymous checkout a warning that the VAT number can be entered and used only after registration should be displayed.
If it's enabled, then we add a new field on the billing address page to enter the VAT number. When saving the address, we check the validity of this number (`GetVatNumberStatus` method), if it's valid, then save the VAT number and its status for the customer (guest). When placing an order, this number will be saved in the order details.

**Comment by alecrt** [comment]
Any update on this?
I think also **required** custom customer fields should be considered.

So, during guest checkout process, required properties from both customer and customer-addresses should be merged in order to populate form inputs.
