### ISSUE TITLE
BrowscapXmlHelper performance issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1964]
Intro and details: http://www.nopcommerce.com/boards/t/45428/reducing-the-memory-usage-on-startup.aspx

I decided to get to the bottom of this and downloaded the trial version of dotMemory and snapshot the memory usage during the peak time memory consumption (you need to be very quick as the GC may reduce the memory at any point).
It turned out the there are 500 MB ... yes 500 MB in Strings allocated in the memory heap.
When investigated who allocated so much stings in the memory it turned out that it is the constructor of the BrowscapXmlHelper class.
You can easily spot why this happens as there is a huge 40 MB file App_Data\browscap.xml that is being loaded in a String into the memory. Then there are several Replace methods that actually create new strings rather than modifying the existing one.

By simply commenting the the Initialize method invocation in the constructor of the BrowscapXmlHelper, then I couldn't make my nopCommerce to take more than 200 MB even after several restarts.

So the implementation of the BrowscapXmlHelper class needs to be corrected to ensure all nopCommerce users will run smoothly their nopCommerce websites on a shared hosting.

see http://stackoverflow.com/questions/6524528/string-replace-vs-stringbuilder-replace

**Comment by skoshelev** [comment]
Closed #1964
