### ISSUE TITLE
Performance. Delete a lot of records as one SQL query

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#197]
Sometime we delete multiple records using iteration. We should do it in bulk.

Find more info at http://stackoverflow.com/questions/21568479/how-can-i-delete-1-000-rows-with-ef6/21568526#21568526

**Comment by skoshelev** [comment]
resolved [#80df241](https://github.com/nopSolutions/nopCommerce/commit/80df2412f91fd190f8ecf0ec93fa1e545d64bf33)
