### ISSUE TITLE
"Pay in store" payment methods and vendors (configurable)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1971]
If payment option "Pay in store" is available (or any other) and customer do not make any payment via on-line store (just making payment at local store), then vendor is not able to change payment status. 

Source: http://www.nopcommerce.com/boards/t/45434/vendor-admin-panel-information.aspx

But the issue is that partial payments are not supported right now. Should we hide this payment method when products from vendors are used? At least until partial payments are supported. Let's decide whether we should hide it when all products are from one vendor or not, with products without vendors, etc

Especially considering that there could be multiple places (stores)

**Comment by eadameg** [comment]
If I understand well As it is working now the payment is maid to the storeowner and he then distributes it manually to the vendor(s) involved in the order. Even if partial payments is implemented the payment would be done to the store owner and some portions of it will be credited to the vendor(s). Therefore INMO the store owner is the only one that can change the payment status.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/payinstore-plugin-for-nopcommerce/issues/1 (not a core plugin)
