### ISSUE TITLE
Display used discounts to vendors

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1972]
If in store is available any discount (and let`s assume that are 3 available), then vendor do not have any information which discount has been used. That information may be needed to plan any further promotions. 

Source: http://www.nopcommerce.com/boards/t/45434/vendor-admin-panel-information.aspx

At least we should display discounts applied to products

On the other hand vendors don't see totals (order subtotal, shipping, order total details, etc). Discounts could be also applied to other vendor products. Let's think what we can do

**Comment by vikasnopcommerce** [comment]
Settings should be provide to admin , that Per Vendor Products should be added into Basket and Process for Checkout. 
if yes then While Add to Basket , if products is belongs to other Vendors , it should be allowed.
in this case Vendor Can see  totals (order subtotal, shipping, order total details, etc) and vendor can see discount applied.

In the Discount , need to add functionality like : Discount Type  as " Discount per Vendor Products", and  this can be mapped with the Vendors.

Like CouponVendorA, CouponVendorB

so this CouponVendorA and CouponVendor B , can be  added to the Products of Vendor A, Vendor B.
and Vendor can see only if "Discount per Vendor Products" is applied.

**Comment by AndreiMaz** [comment]
Also see https://github.com/nopSolutions/nopCommerce/issues/107

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
