### ISSUE TITLE
Admin area. Allow a store owner to delete shopping carts and wishlists

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1973]
In admin area on the list pages. The same is about customer details page

**Comment by MaxMommersteeg** [comment]
What is the difference between this and impersonating the customer? Impersonating allows store owners to do the same thing am I right (only difference would be a few more clicks)?

**Comment by AndreiMaz** [comment]
less steps

**Comment by skoshelev** [comment]
Closed #1973
