### ISSUE TITLE
Performance. Cache the most used queries

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#198]
We should prepare a list of such places that could be optimized. In mean presentation layer because EF entitie (e.g. Customer or Order) cannot be cached between requests (EF limitation). And we can cache presentation layer objects only. Or we should created some entities for caching (e.g. SettingForCaching)

For example,
1. Cache the current store (return some model), current language, currency, etc. But how?

**Comment by AndreiMaz** [comment]
Moved to issue #157
