### ISSUE TITLE
"View all" blog tags

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#1982]
I'd like to suggest a simple feature be added to the existing blog tag cloud.."View all"
It should work just like the /producttags/all method, but show a page with all of the blog tags instead of the product tags

Source: http://www.nopcommerce.com/boards/t/45462/suggestion-add-method-for-view-all-blog-tags.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by SteveEmbry** [comment]
OK...so it didn't make it into version 3.90 or 4.0...maybe in 4.1??
