### ISSUE TITLE
PluginManager.cs PerformFileDeploy question when full trust

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#1984]
In Nop.Core.Plugins.PluginManager.cs file,
You reference this blog, [http://shazwazza.com/post/Developing-a-plugin-framework-in-ASPNET-with-medium-trust.aspx ](url)

And the blog says : 
Working in Full Trust, the simplest solution is to shadow copy your plugin DLLs into your AppDomain DynamicDirectory. 
Working in Medium Trust you’ll need to do the following: (copy the shadow folder and reference by BuildManager)

The blog says when in full trust mode, we can simply copy dll to AppDomain DynamicDirectory, it doesn't say using BuildManager reference it.

But in Nop.Core.Plugins.PluginManager.cs,  PerformFileDeploy method,  you always reference the dll : 
`BuildManager.AddReferencedAssembly(shadowCopiedAssembly);`
I think if we do this, there's no difference with full trust and others, just copy to some folder and reference it.

And my test result seems that if we copy dll to AppDomain DynamicDirectory when PreApplicationStart, the AppDomain.CurrentDomain.GetAssemblies() will automatically reference this dll, we don't need to reference it using BuildManager.

**Comment by JohnsonYuan** [comment]
The blog also says:

> Shadow copy your plugin DLLs into the AppDomain’s DynamicDirectory.
> 
>     This is the directory that the BuildManager compiles it’s dynamic assemblies into and is also a directory that the AppDomain looks to when resolving Type’s from Assemblies. 

So I think it will auto load dll, we don't need to manually using BuildManager

**Comment by AndreiMaz** [comment]
I think we can simplify this code already. Since aynway ASP.NET doesn't support medium trust anymore
