### ISSUE TITLE
Gift card usage history is not deleted on order cancel

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#1986]
If you place an order using a gift card, after you cancel the order you do not get back the gift card amount spent.

At least we can make it configurable

**Comment by TomKnox** [comment]
I think that is a big issue, is there any reason why this is on hold?  I found nothing about this in the forum.

**Comment by skoshelev** [comment]
Closed #1986 (https://github.com/nopSolutions/nopCommerce/commit/63bad29d442407e8ac19e5de711538eb9430ee82)
