### ISSUE TITLE
DataValidation list cannot exceed 255 characters when exporting products.

### ISSUE THREAD

**Issue by jlnunez89** [nopSolutions/nopCommerce#1987]
Getting a "The total length of a DataValidation list cannot exceed 255 characters" error when trying to export the product list to Excel within the admin area.

Steps to duplicate:
1) Login as an admin, go to admin area
2) Go to product list
3) On top, select Export... Select all (or selected but first select some products).
4) Get the error there or check the logs.

Solution:
http://stackoverflow.com/questions/28197219/exceptionthe-total-length-of-a-datavalidation-list-cannot-exceed-255-characters

Change implementation on PropertyManager.cs, method:
public void WriteToXlsx(ExcelWorksheet worksheet, int row, int cellOffset);

P.S. (noob question) How do I become contributor? I don't have permissions to push into dev branch :S

**Comment by MaxMommersteeg** [comment]
@jlnunez89 Of course you don't have direct push access for this repository. You will need to fork the project, make changes to the forked project. When you are done, open up a Pull Request. Explain what modifications you made.

The nopCommerce team will label and check your Pull Request. Code will be merged into this repository when Pull Request has been approved.

**Comment by AndreiMaz** [comment]
@jlnunez89 already fixed in the upcoming version 3.90. as for contribution please see http://docs.nopcommerce.com/display/nc/Working+with+source+code+and+contributions
