### ISSUE TITLE
Reduce the size of cached values to be more Redis friendly

### ISSUE THREAD

**Issue by mcliment** [nopSolutions/nopCommerce#1988]
I've been trying to use Redis with NopCommerce and there are some issues with the size of the keys that create a lot of traffic between the Redis server and the application.

The biggest values are:
* `Nop.lsr.all` (about 580Kb) - Only if you enable loading all the strings at once
* `Nop.setting.all` (about 80Kb) - All the settings, used several times per request

For the language stuff, a simple option would be disabling `LoadAllLocaleRecordsOnStartup` when Redis is enabled. Or at least informing the user that this should be disabled when using Redis.

For the settings, they should be stored in their own keys (one per setting) to avoid this excessive network pressure. Every call on `GetSetting` and `GetSettingByKey` retrieve the entire value and this happens several times on each request. I don't think this would be very difficult to implement and this is the only key that has given me timeouts on Redis from time to time.

What do you think?

also see http://www.nopcommerce.com/boards/t/45927/reducing-the-cache-key-sizes-to-use-with-redis.aspx

**Comment by RomanovM** [comment]
@mcliment Hi.
We have added warning to admin about high traffic to Redis server when LoadAllLocaleRecordsOnStartup setting is enabled. 
With regard to the settings, we have decided to leave the current implementation with one-time caching all settings. 
Thanks for the suggestions.

**Comment by mcliment** [comment]
Well, the problem is not only storing the settings in one big value but that it's retrieved from Redis several times per request if I recall correctly.
What's the advantage of having it in a monolithic way?
If I can make it work properly, would you accept a PR?

**Comment by RomanovM** [comment]
Sure. Any contribution is welcome.

**Comment by AndreiMaz** [comment]
@mcliment But it's not retrieved from Redis several times per request. Once it's loaded from Redis we cache during HTTP request in memory. Please see "Get<T>(string key)" method of \Nop.Core\Caching\RedisCacheManager.cs
