### ISSUE TITLE
Do not display product availability until all required product attributes are selected

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/nopCommerce#1991]
:>Sample Product : Shirt
Sizes configured as Radio Button List with attribute combination
Styled using CSS to show each Size as button
Using Attribute Combinations for stock
Stock availability is enabled

* This solves the default selection issue of drop-down list showing out-of-stock when the first size has zero quantity, since none of them would be selected by default.
Reference:
http://www.nopcommerce.com/boards/t/28267/how-to-show-out-of-stock-in-dropdown-product-attribute-value-combinations-32.aspx?p=5

* Also easier to disable 'Size' button if there is no stock for that

**But Availability shows "In Stock" even if none of the combinations have stock.**

:>Traced the reason to the below line
\Libraries\Nop.Services\Catalog\ProductExtensions.cs

:>Function name:
public static string FormatStockMessage

:>Else part of 
if (combination != null)
                            
else
{
stockMessage = localizationService.GetResource("Products.Availability.InStock");
}

**::SUMMARY::**
Even if the sizes are not selected and even if all the sizes have zero quantity
Availability shows 'In Stock' till one of the sizes are selected.

I think availability can be shows as empty till the required attribute (size) is selected.
(changes would be required in _Availability.cshtml since there is an if condition)

**Comment by sukeshak** [comment]
To disable sizes not available (stock quantity == 0)... I need the Quantity available for each combination.
How can I get that in _ProductAttributes.cshtml ?

With that, we can add attribute, disabled='disabled' where stock quantity == 0

Any ideas?

**Comment by sukeshak** [comment]
This is how the radio-button list looks like
[https://img42.com/zmbHk](url)

**Comment by skoshelev** [comment]
Closed #1991
