### ISSUE TITLE
Multiple Warehouses for Products with attributes

### ISSUE THREAD

**Issue by GellCel** [nopSolutions/nopCommerce#2013]
First I would like to say thank you so much for a wonderful product in NOP Commerce. 

I have a request to further increase the value of NOP Commerce.

Here is the challenge - When we set "Track Inventory By Product Attributes" we can no longer track inventory by multiple warehouses. 

For example: If we want to use attributes for red and blue shoes and track the inventory we cannot use multiple warehouses.

Can we please look at adding in tracking inventory by attribute combinations by multiple warehouses.

I am aware of the complexity this might create from a software architecture perspective for products with multiple attribute types but it should be achievable with warehouses tracking on the Attribute Combinations Only? 

Example might be an attribute combination like color/size. The user sets up 2 attribute types of color and size and then generates the combinations that they wish to track. 

Example
Amsterdam warehouse has attribute combinations of :
10 x Red size 7
5 x Red size 6
5 x Blue size 7
5 x Blue size 6

New York warehouse  has attribute combinations of :
20 x Red size 7
10 x Red size 6
10 x Blue size 7
7 x Blue size 6

So the user MUST set up all attribute combinations for the stock they wish to track by warehouse. 

I think this solution would satisfy 80% - 90% of the users who use the attributes section.

Thank you.

**Comment by 1jmj** [comment]
Definitely a useful feature.

**Comment by HeuHax** [comment]
Much needed feature

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2432
