### ISSUE TITLE
Change PrepareSpecificationsAttribute to config setting

### ISSUE THREAD

**Issue by justinhof** [nopSolutions/nopCommerce#2014]
Currently PrepareSpecificationsAttribute is set to false by default in CatalogController.PrepareProductOverviewModels. 

Request that this be changed to a config setting so it can be changed, allowing views to show specification attributes on catalog views. Example below:
https://www.deepblueyachtsupply.com/non-metal-cutlass-bearings

Plugins from nop-templates.com made similar change when using AJAX filtering and works great, but this would allow the initial load to allow showing of attributes should the store owner want to.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
