### ISSUE TITLE
Import categories. Import by name?

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2017]
Right now it's almost not possible to insert the entire category structure from scratch (when no categories exist). It should be done step by step (first level, then second level, etc). Because "ParentCategoryId" doesn't exist yet.

Right now we import them by ID (find existing ones). Why not use some more-user friendly field (e.g. Name). In this case also consider ParentCategoryId field (ParentCategoryName). The issue is that some stores have duplicated category names (in different subcategories). How can we resolve it? 

1. We can try to find by [Id] first. If a record doesn't exist, then search by "Name" (exact match). The same is about parent categories.
2. Make it configurable? So the default behavior can be enabled (by ID)?
3. Just ignore it. In this case import can be done with two steps. In the first one, we import all categories. Then import them again with valid IDs

Let's think about it

**Comment by skoshelev** [comment]
Closed #2017
