### ISSUE TITLE
languageId issue with Url records

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#2019]
Hello,

I try to fetch to slug for category using "GetActiveSlug" method where we need to pass languageId.
If I use _workContext.WorkingLanguage.Id gives me Id = 1

when I see UrlRecord table in database it has all values with "0". do I pass hardcoded value 0 or there is fault in database when record inserted.

**Comment by AndreiMaz** [comment]
please post all questions on our forums http://www.nopcommerce.com/boards
