### ISSUE TITLE
Digital products. Versioning and multiple files

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2020]
See http://www.nopcommerce.com/boards/t/38157/how-to-upload-multiple-files-for-downloadable-product.aspx

See http://www.nopcommerce.com/boards/t/43205/feature-request-add-field-for-version-number-of-digital-products.aspx

Related work item - https://github.com/nopSolutions/nopCommerce/issues/409 and https://github.com/nopSolutions/nopCommerce/issues/433

**Comment by danielfungca** [comment]
HI, may you advise me if multiple file attachments in the Downloadable product is still on the roadmap for the v4.20 ?.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
