### ISSUE TITLE
Replace gear icon in the category menu 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2021]
I hope I am not flooding the forum with suggestions here. I do like nopCommerce and think it has tons of potential!

The gear Icon in the category bar in the mobile version needs to be replaced with something relevant. In the design world, the Gear Icons represent editable settings and the Category bar is not an editable setting. How about an down arrow that changes to an up arrow?

source: http://www.nopcommerce.com/boards/t/45750/gear-icon-in-the-category-bar-needs-to-go.aspx

**Comment by armanforghani** [comment]
I suggest to change that icon to bars (like http://fontawesome.io/icon/bars/).
But what I am wondering if why you don't use an iconic font (like Font Awesome) instead of images.

**Comment by jhaydens** [comment]
here's an icon - if its useful ...
![menu-icon](https://cloud.githubusercontent.com/assets/16783039/23400654/9cae13e2-fd9c-11e6-88fb-64732b3c7d30.png)

**Comment by jhaydens** [comment]
mmmmm, i did upload it but its white on a white background here - its below the writing...
----   ![menu-icon](https://cloud.githubusercontent.com/assets/16783039/23400754/f52d74fe-fd9c-11e6-9982-2cf17448fce7.png)     ----
________________________
hold your mouse over the space above

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
