### ISSUE TITLE
Allow a store owner to decide which fields (built-in or custom ones) are available on the registration page or customer info one

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2023]
In the admin section, there is a way to gather customer details during registration such as gender and date of birth. If these values are not enabled, these fields are subsequently not available in the customer profile page. Am I missing something here?

The registration process should be as quick as possible in order to acquire more accounts so I do not want to enable these fields by default, yet the customer should be able to edit a full profile once logged into their account.

From previous experience, I can say for sure that customers will go in and update their profile on their own and once they have established a trust level will also provide more details... Sometimes, you can make them give more details by offering incentives.

Why is the data valuable? Marketing and segmentation. For example, if you can tell who is a male or female without running complex database filters, then you can target customers better...

I hope to see the customer profile section a bit smarter in the business sense.

Also, why not let customers manage things like newsletters from there and tick their intersects from product categories etc..

Source: http://www.nopcommerce.com/boards/t/45747/customer-profile-enhancement.aspx

**Comment by sateeshmunagala** [comment]
Is there any way that it can go into at least version 4.3?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
