### ISSUE TITLE
Let's make configurable whether admin menu is on the left or at the top

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2024]
AdminLTE has this setting (CSS class)

Let's add a setting in nopCommerce to support it (do not add it to UI, it'll be available at the "advanced settings" page only)

**Comment by iammourya** [comment]
Good one. This will be great for full length pages (if admins want the menu to be on top).

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
