### ISSUE TITLE
Forums. Allow user to vote for posts (similar to official nopCommerce site)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#203]
Allow user to vote for posts (similar to official nopCommerce site).

This option should be configurable (enabled by default)

The post author should not be able to vote for its own posts. Duplicated votes also won't be allowed. But users should be able to change his/her vote later if required 

So a new [ForumPostVote] table is required (int Id, int PostId, int CustomerId, bit IsUp, datetime CreatedOnUtc) to store this info

**Comment by AndreiMaz** [comment]
Also make it configurable (enabled by default) so a store owner can disable it

**Comment by AndreiMaz** [comment]
updated description
