### ISSUE TITLE
Fix product rating view in Opera

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#2034]
![b1effd6448](https://cloud.githubusercontent.com/assets/16681184/23056769/1429e376-f4fe-11e6-9e84-3ea90c73e01b.jpg)
It happens only in Opera when zoom is 100%. 
I have two options how to fix it at the moment:
- use a full 5-star image to fill rating instead of 1-star  
- decrease size of the star-picture. It's done for http://www.nopcommerce.com/marketplace.aspx. I don't actually know why but it worked there,

I don't really like both of these ways.

**Comment by tigran-avdalyan** [comment]
Change in CSS file parameter Width to 90px+(Yellow_Stars_Count-1) px

.item-box .rating {
    background: url(/Themes/DefaultClean/Content/images/rating1.png) repeat-x;
    width: 93px;
    height: 14px;
}
