### ISSUE TITLE
missing "</td>" element in "Administration/Views/Product/_CreateOrUpdate.Info.cshtml"

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#2036]
in "Presentation/Nop.Web/Administration/Views/Product/_CreateOrUpdate.Info.cshtml" ProductWarehouseInventoryModels part, the warehouse_used checkbox parent <td> without ending "</td>

at line 1497, <td style="width: 10%;">
ther should be a "</td>" at line 1515
but start a new <td>

paste code:

`
  line 1497                                             <td style="width: 10%;">
                                                    <input type="checkbox" id="warehouse_used_@(item.WarehouseId)" name="warehouse_used_@(item.WarehouseId)" value="@item.WarehouseId" checked="@item.WarehouseUsed" />
                                                    <script type="text/javascript">
                                                    </script>
                                 **// there's no ending </td> element**
                                                <td style="width: 18%;">

`

**Comment by manojkulkarni30** [comment]
Please assign it to me i will work on it.

**Comment by AndreiMaz** [comment]
@manojkulkarni30 Thanks a lot! Please fix it
