### ISSUE TITLE
Admin menu. Update documentation link.

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2039]
We should reference http://docs.nopcommerce.com/ now. The current link is outdated

**Comment by manojkulkarni30** [comment]
@AndreiMaz  Link http://docs.nopcommerce.com/ redirect to http://docs.nopcommerce.com/display/en/nopCommerce+Documentation URL. 

So should we use http://docs.nopcommerce.com/ or http://docs.nopcommerce.com/display/en/nopCommerce+Documentation URL. Please suggest.

**Comment by AndreiMaz** [comment]
@manojkulkarni30 we're still thinking about it

it redirect to English version now because we have English only. But very soon we'll have documentation translated to multiple languages

**Comment by manojkulkarni30** [comment]
@AndreiMaz so we should use http://docs.nopcommerce.com/ and replace the old link in admin. Right ?

**Comment by AndreiMaz** [comment]
@manojkulkarni30 still thinking about it
