### ISSUE TITLE
Refactoring of big methods (split to several ones)

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#2042]
Maybe you can think of refactoring the code instead of using regions.

More info about the use of regions:
https://blog.codinghorror.com/the-problem-with-code-folding/
http://softwareengineering.stackexchange.com/questions/53086/are-regions-an-antipattern-or-code-smell

See comments below

**Comment by AndreiMaz** [comment]
What exactly do you suggest to refactor? Why should they be removed?

**Comment by shurub3l** [comment]
For example, the PlaceOrder method from OrderProcessingService uses #region 3 times. The best practice says you shouldn't use regions inside methods. Methods should be short and each method should do only one thing. So instead of separating the method into 3 regions, you should refactor into 3 or more separate methods.

Please also read the StackExchange answer and the article I referenced above for more info.

**Comment by AndreiMaz** [comment]
Agree. But in this case it's better to rename this task. Othwerwise, it sounds like they should be removed everywhere

**Comment by shurub3l** [comment]
The PlaceOrder method is not the only place where region is used inside methods, that's why the title was more general.
Here are other places where #region is used inside methods: Authorize in ExternalAuthorizer, FormatStockMessage in ProductExtensions, SearchProducts in ProductService, GetProductCount in ProductTagService, PrintOrdersToPdf in PdfService, DeleteGuestCustomers in CustomerService, InstallProducts in CodeFirstInstallationService, ProductListToHtmlTable in MessageTokenProvider. And the list can go on ...

Also the constants, fields, properties and constructor are always in the same order so I don't think the use of #region is required.

And #region is also used in some classes to group some related methods. For example, in CustomerService you have 2 regions: Customers and Customer roles. I think the Customer roles region should be moved to it's own CustomerRoleService and so the use of #region will not be necessary.

**Comment by AndreiMaz** [comment]
Thanks! We'll discuss and think about it. I've just renamed a task!

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2448
