### ISSUE TITLE
Product attributes and Specification attributes client side info like in yandex market

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2044]
![untitled](https://cloud.githubusercontent.com/assets/17789934/22112324/f020d45a-de7b-11e6-8c8b-ba525607db49.png)

Like in photo

**Comment by AndreiMaz** [comment]
What exactly do you mean? Hint (popup)? Groups?

How is it related to product attributes?

**Comment by tigran-avdalyan** [comment]
Hint (popup) when clicking on question mark icon.
Нужен вопросителний знак для Product attributes and Specification attributes.
Например в Specification attributes для каждево атрибута нужно будет написат обяснение о том что это за характеристика.
По такой же логике в  Product attributes.(например продажа телефона с MicroSD картой и без, в popup-е  можно будет обяснить что такое MicroSD  или другую информацию)

**Comment by AndreiMaz** [comment]
Спасибо. Но такая задача уже есть - https://github.com/nopSolutions/nopCommerce/issues/373
