### ISSUE TITLE
Device Specification Groups in admin area, and view by Groups in client area

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2045]
Device Specifications grouping  in admin area, and view by Groups in client area like in http://www.devicespecifications.com/en/model/d1423ea6

And can set images for Device Specification Groups

**Comment by tigran-avdalyan** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17789934/22177249/77878a5c-e033-11e6-9285-3b42a175ca71.png)


Like in photo

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/1159

**Comment by tigran-avdalyan** [comment]
I have 700  Specification Attributes(For Mobile Phones, For Cars, for Pc , ....), and it is necessary to identify each group in the future, I think it is necessary to add this functionality in the next release

**Comment by tigran-avdalyan** [comment]
This feature will be available in version 3.9?

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/issues/1159 is not assigned to any version yet
