### ISSUE TITLE
Export/Import of product and specification attributes

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2047]
now we can only add new Products Specification attributes or Product attributes.
its need to be  Like Export/Import in Products.

**Comment by AndreiMaz** [comment]
but product attributes import/export is already supported

**Comment by tigran-avdalyan** [comment]
i'm sorry but how? 
with import/export product , product attributes is  import/export- ing with  product?

**Comment by AndreiMaz** [comment]
yes. since 3.80

**Comment by AndreiMaz** [comment]
renamed a work item

**Comment by tigran-avdalyan** [comment]
and what about import/export product attributes ?

**Comment by AndreiMaz** [comment]
they are already support to import/export in 3.80

**Comment by tigran-avdalyan** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17789934/22176731/0f172bb6-e02a-11e6-958c-e6ce76631dfa.png)

but there is not import/export function

**Comment by AndreiMaz** [comment]
Ohhh. I see now. Actually I meant export/import of products (mapping attributes to them)

**Comment by tigran-avdalyan** [comment]
This feature will be available in version 3.9?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan no

**Comment by tigran-avdalyan** [comment]
Sorry but You write wrong Title
Title is Like "Product Attributes & Specification Attributes Import/Export Support"

**Comment by AndreiMaz** [comment]
Tigran, sure. Sorry. There's another work item for specification attributes - https://github.com/nopSolutions/nopCommerce/issues/2057

**Comment by tigran-avdalyan** [comment]
@AndreiMaz i need to input Specification Attribute "Resolution"
this is the list
https://en.wikipedia.org/wiki/List_of_common_resolutions
and i need to do this, because Nopcommerce dont have support IMPORT/EXPORT Specification Atributes.
This is only one Attribute, but in my store they more then 700.

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave it for customization
