### ISSUE TITLE
When adding  specification attribute in product, let possibility to chose  how filter it, by checkbox, by dropdown list , or by other methods

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2051]

**Comment by tigran-avdalyan** [comment]
This feature will be available in version 3.9?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan milestore is not set yet

**Comment by clearbucketLabs** [comment]
i think range would be a good idea as well that's integer/date at least.  it's come up more than once, such as year / date for cars, or wines etc...  i can implement if i have time.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
