### ISSUE TITLE
Do not delete guest customers that closed the EuCookieLaw notification

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#2056]
There are guest customers that visit the website multiple times. And it is very frustrating for them to have to close the EuCookieLaw notification more than once. 

Now, the Delete guests schedule task deletes the guest users, even if they have closed the EuCookieLaw notification. I think the method for deleting guest customers should check first if there is generic attribute with key EuCookieLaw.Accepted and delete the guest customer only if there isn't one. Maybe add a setting for this feature also.

**Comment by jhaydens** [comment]
probably all users will have read and closed the cookie warning - so in fact, not deleting the ones who have closed it will be almost the same as not deleting any - the table will still be full.

If they close the the box, they have accepted the principle of cookies - would leaving a cookie when cookies have been accepted be the best way forward ?

**Comment by shurub3l** [comment]
I don't know if that is the case. For example, in my production database, right at this moment I have 1.874.532 guest customers (I haven't deleted them in a while), and only 69.957 generic attributes with EuCookieLaw.Accepted (and these are not filtered by the customer role, these are for all the customers). So not every user closes the cookie warning.

But, I agree, another possible solution would be to save a cookie just for the EUCookieLaw notification.

**Comment by jhaydens** [comment]
thats curious - that seems to suggest that most people view your site with the cookie warning obscuring much of the page ?
or perhaps the warning is not displayed in many of the browsers ?

I also suggested implementing the cookie warning as a banner that slides in and out from the top / bottom of the page (as is common on many other sites) so that people who choose not to click accept can continue to browse without the warning obscuring their view

**Comment by stephdep** [comment]
Something must be done about this, I think a banner sliding in would be a good approach

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

I would just sugget to specify larger period to delete guests (schedule tasks). e.g. - one month
