### ISSUE TITLE
Product import/export. Support specification attributes

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2057]
Th same way as we support product attributes

**Comment by tigran-avdalyan** [comment]
I think same problem in Product Attributes  when exporting Product

**Comment by AndreiMaz** [comment]
Thanks. But product attributes import/export is already supported (3.80)

**Comment by iammourya** [comment]
Andrei, I guess the specification attributes import export is not available.  So will the next version of nop include this feature?

**Comment by AndreiMaz** [comment]
@iammourya no, it's not supported yet. most probably 3.90 won't have its support

**Comment by YuriyZaletskyy** [comment]
@tigran-avdalyan do you mean import functionality which is available at admin: /Admin/Product/List ? Can you please provide more detailed example of what you want to achieve?

**Comment by tigran-avdalyan** [comment]
Now when import/export Products  the system import/export Product parameters and Product Attribute parameters but not support import/export Product Specification Attributes:

Example:
Product: CAR                                                                                                   ( import/export Support) 
Product Attribute:Color            Option1:White  Option2:Black                       ( import/export Support)
Product Specification Attribute1: Body Type         Option:Sedan                      Not Support    
Product Specification Attribute2: GearBox Type    Option:Manual                     Not Support

**Comment by YuriyZaletskyy** [comment]
@tigran-avdalyan I've configured sandbox edition at http://bugs.zaletskyy.com. Can you please log in there  and create your case for demo purposes. I'll try to implement your request. Please respond with detailed description of what you want to see, and what is actual result. username/password: admin@yourStore.com/qwertyui

**Comment by tigran-avdalyan** [comment]
i create, Sample Product Name is "Product import/export. Support specification attributes"

**Comment by YuriyZaletskyy** [comment]
I've  got an impression that all attributed were imported. Am I missing something?

**Comment by tigran-avdalyan** [comment]
yes, try export this product , then import again .

And compare that products.

**Comment by clearbucketLabs** [comment]
Hey,

I will implement this,  i had started something but figure i would do it right and do a PR.   A couple things to discuss with the format.   Currently Product attributes like color, size etc... are exported in excel as grouped, under the product row.    adding another group or adding the specification attributes after this seems messy.

I wanted to see what others thought.  However i have an idea.

I propose to make them flat as part of the main product column.  For example:

specification.attributename.TypeId | specification.attributename.SelectedValue | specification.attributename.customvalue | specification.attributename..AllowFiltering | etc...
------------ | ------------- | ------------- | -------------
0 | Purple |  | true |


1. For columns prefixed with specification, they would be treated as specification attributes and the attribute name would be used to look up the attribute in the system with case insensitivity.

2. if the columns are blank, the attribute is skipped.  indicates the product does not have this attribute. (while other products might, so the headers and columns must be present)

3. if not blank the name is used to match the attribute in the system.  if none is found, it makes one.

4. if the type is an option, it uses the selected value to look up if it exists and maps to that.  if not, it creates one.  this would be case insensitive to make sure we're not making duplicates.

**Comment by tigran-avdalyan** [comment]
@skoshelev can you share product with specification attributes exported file Excel template?

**Comment by skoshelev** [comment]
@tigran-avdalyan This is sample file of exported products with their specifications attributes:
[products.xlsx](https://github.com/nopSolutions/nopCommerce/files/1309918/products.xlsx)

**Comment by tigran-avdalyan** [comment]
@skoshelev thanks Sergey 
But how do we know SpecificationAttributeOptionId? SpecificationAttributeOptionId in version 3.9 not show in admin area. 
SpecificationAttributeOptionId will be show in 4.0 version?

**Comment by skoshelev** [comment]
@tigran-avdalyan Sorry, no. We created [this work item](https://github.com/nopSolutions/nopCommerce/issues/2567), but we're not sure of the need to add these data to the admin area.

**Comment by skoshelev** [comment]
Closed #2057
