### ISSUE TITLE
Return request. Add "return to stock" button

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2061]
Source: http://www.nopcommerce.com/boards/t/45931/questions-about-return-request-status.aspx#182272 (see entire discussion)

also ensure that it cannot be clicked twice. maybe, display some warning. maybe, hide this button when it's already clicked and show a message that it's already returned (store a boolean value in "ReturnRequest" table)

**Comment by nidhi1612** [comment]
I am on version 4.3. and it is still allowing me to submit multiple return request for the same order. Is there any solution for this?
