### ISSUE TITLE
[Help required] Custom price per customer

### ISSUE THREAD

**Issue by gevzak** [nopSolutions/nopCommerce#2065]
Hello team,

At first I would like to thank you for your great project.
I am new to nopcommerce and I have a client running B2B company which sells products.
The main featuress my client needs is to have an ability to set custom prices per customers and to assign customer to Sales Manager, therefore tracking the amount of sales done by Sales Managers.
As for per customer prices I know that Nop lets you create customer role tiers, and set a seperate price for each tier. Can you please clarify the performance impact on the system? An example is to have custom price for 2000 customers to even more. Would the system remain stable?
For Sales Managers feature, I know that I have to write an plugin by myself, do you by chance have any similar experience or guides that you can share ? Thank you in advane.

**Comment by eadameg** [comment]
For better results post al your questions in the Nop forum. Are you going to have individual price lists or will you handle a few price lists for types of customer. We have the second with some other individualised price list without any impact in performance.
For Sales Managers check affiliates feature of Nop.
