### ISSUE TITLE
Orders Table - RefundDateUtc

### ISSUE THREAD

**Issue by jmawebtech** [nopSolutions/nopCommerce#2066]
Hi,

I have some feature requests:

1. When I refund orders, I would like to know the refund date. Can you add RefundDateUtc to the order table? Right now, I have to write code to change the order creation date to the date refunded.
2. Can you add ModifiedDateUtc to the order table? In the order service search orders method, can you make this field searchable? 

I run an Accounting software company. Many clients want to pull orders by status, which means I must query the date modified field.

**Comment by AndreiMaz** [comment]
We can have many refund requests. So it's better to implemented it as part of this task - https://github.com/nopSolutions/nopCommerce/issues/5
