### ISSUE TITLE
Minify HTML (configurable)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2072]
It's related to https://github.com/nopSolutions/nopCommerce/issues/1457

According to tests "Minify HTML" (https://developers.google.com/speed/docs/insights/MinifyResources) for the following resources to reduce their size by 877B (13% reduction).

Let's add a setting indicating whether HTMl is minified. By default it should be disabled

For example, https://github.com/Taritsyn/WebMarkupMin. Also see https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=9#195316 and https://github.com/Taritsyn/WebMarkupMin/blob/master/samples/WebMarkupMin.Sample.AspNetCore2.Mvc2/Startup.cs

But maybe, it's better to use some third-party services (e.g. IIS compression or plugins, cloudflare)

**Comment by RomanovM** [comment]
After some discussion decided not to implement it out of the box in next version. We leave it for customization or plugin development
