### ISSUE TITLE
Better image optimization (compression)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2073]
It's related to https://github.com/nopSolutions/nopCommerce/issues/1457 and https://github.com/nopSolutions/nopCommerce/issues/4034

According to tests we have warnings like the following one - "Optimize the following images to reduce their size by 12.7KiB (7% reduction)."

Let's investigate whether it's possible to configure our image resizing library to have maximum compression. So no warnings are displayed in test tools

**Comment by fsefacan** [comment]
You can use webp.
https://developers.google.com/speed/webp/docs/compression

**Comment by bulutkartal** [comment]
> You can use webp.
> https://developers.google.com/speed/webp/docs/compression

webp is not supported for most browsers.

**Comment by alextretij** [comment]
Я использую ImageMagick для создания webp файлов.
Делаю следючий хак, если изображение    ".jpg",".jpeg", ".png"
то к названию добавляю в конце webp.
Пример
testpicture.jpg  =>  testpicture.jpg.webp

fileName - это файл торій нужно конвертировать 

                            var newfileName = "";
                            using (MagickImage image = new MagickImage(fileName))
                            {
                                    /*
                                     * https://developers.google.com/speed/webp/faq
Consistent with the VP8 bitstream, lossy WebP works exclusively with an 8-bit Y'CbCr 4:2:0 (often called YUV420) image format. 
Please refer to Section 2, "Format Overview" of RFC 6386, VP8 Data Format and Decoding Guide for more detail.
Lossless WebP works exclusively with the RGBA format. See the WebP Lossless Bitstream specification.                                     
                                     */
                                    image.Settings.SetDefine(MagickFormat.WebP, "-lossless", true);
                                    //image.Settings.SetDefine(MagickFormat.WebP, "-emulate-jpeg-size", Options.GetWebPEmulateJpeg());
                                    //image.Settings.SetDefine(MagickFormat.WebP, "-alpha", Options.GetWebPRemoveAlpha());
                                    //image.Settings.SetDefine(MagickFormat.WebP, "-quality", Options.GetWebPQuality().ToString(CultureInfo.InvariantCulture));
                                    image.Format = MagickFormat.WebP;
                                    newfileName = fileName + ".webp";
                                    image.Write(newfileName);
                            }

Теперь о плохом. Если использовать AnyCPU, то ImageMagick  имеет вшитыми две DLL и сама во время старта распаковывает нужную в папку темп.
Бывает что запрещено туда писать, поэтому я менял на Plugins/bin
            MagickAnyCPU.CacheDirectory = fileProvider.MapPath("~/Plugins/bin");
            string path = Path.Combine(MagickAnyCPU.CacheDirectory, "Magick.NET.net40.7.11.0.0");
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

**Comment by DmitriyKulagin** [comment]
We have already added support for the `webp` format, and since there are no other directions for the development of this task, I am closing it.
