### ISSUE TITLE
Admin area. Allow to upload favicon

### ISSUE THREAD

**Issue by musakkhir** [nopSolutions/nopCommerce#2074]
Can you add upload favicon icon option in administration section?

**Comment by AndreiMaz** [comment]
First, let's implement https://github.com/nopSolutions/nopCommerce/issues/2794

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/f77ed688a7b0a0f03be538975829d886050b4884
