### ISSUE TITLE
Price adjustment value in checkout attribute is not updating in Total Amout.

### ISSUE THREAD

**Issue by musakkhir** [nopSolutions/nopCommerce#2075]
Hi,

I have added two radiobutton list control (option1 and option2) in checkout attribute and added attribute values with price adjustment 5 and 10. I marked as required and shippable product required as checked. On cart page when I switch the option on cart page the price adjustment value is not added in total value. It works only when I click on **Update shopping cart** button. 

The total value should update automatically when I switch the option on cart page.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/49
