### ISSUE TITLE
Split Manufacturerts by Categories

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2079]
For example i have 2 Categories : Cars , Mobile Phones
And Manufacturers : Audi, BMW , Nokia, Apple

When i go to Mobile Phone category need to show Manufacturers Nokia, Apple
When i go to Cars category need to show Manufacturers  Audi, BMW

**Comment by tigran-avdalyan** [comment]
We can Add "Map to Category" area in manufacturer details page

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

Right now it's better (possible) to implement with this specification attributes (to support additional filtering)

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/topic/91006/creating-categories-for-my-manufacturers
