### ISSUE TITLE
Multi layer Specification Attributes(more then 2)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2080]
For Example You have Specification Attribute "Car Manufacture" with options VW, Audi, BMW
we need next level for VW for example Golf, Passat
we need next level for Audi for example TT, RS4
we need next level for BMW for example 3-series, 5-series

can be a situation when we need one more level

**Comment by eadameg** [comment]
There is a plugin for that: http://www.nopcommerce.com/p/1882/nop-car-parts-filter.aspx

**Comment by tigran-avdalyan** [comment]
Car is a Example , its can be Froot, Mobile Phone or Real Estate

**Comment by tigran-avdalyan** [comment]
Now What We Have
![specification](https://cloud.githubusercontent.com/assets/17789934/22543922/2177fb02-e94c-11e6-9860-08090eab864e.jpg)

**Comment by tigran-avdalyan** [comment]
I suggest 
![specification2](https://cloud.githubusercontent.com/assets/17789934/22543969/57e33080-e94c-11e6-9754-91802f3e30a6.jpg)

**Comment by tigran-avdalyan** [comment]
like in Example: Country>>City>>District>>Address

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
