### ISSUE TITLE
More beautiful and functional slider

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2081]
not slide only static picture 
for example see  http://wowslider.com

**Comment by tigran-avdalyan** [comment]
Example http://demo.aspxcommerce.com

**Comment by tigran-avdalyan** [comment]
Example http://demo.virtocommerce.com/clothing

**Comment by tigran-avdalyan** [comment]
https://codyhouse.co/demo/radial-svg-slider/index.html

**Comment by tigran-avdalyan** [comment]
https://dcrazed.com/free-responsive-jquery-image-sliders/

**Comment by tigran-avdalyan** [comment]
http://demo.nop-station.com/#eShopper

**Comment by AndreiMaz** [comment]
We decide to leave it for plugins
