### ISSUE TITLE
reCAPTCHA V2 add fallback parameter

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2082]
Fallback parameter for enable or disable images for checking. Let's make it configurable

**Comment by AndreiMaz** [comment]
Split to two work items. The second one - https://github.com/nopSolutions/nopCommerce/issues/2106

**Comment by skoshelev** [comment]
Добрый день @tigran-avdalyan, я не смог найти способа принудительно включить второй тип проверки, в документации к v2 есть такое описание:
If you see a green checkmark, congratulations! You’ve passed our robot test (yes, it’s that easy). You can carry on with what you were doing.
Sometimes we need some extra info from you to make sure you’re human and not a robot, so we ask you to solve a challenge
Подскажите, может вы знаете как включить этот тип проверки принудительно?

**Comment by tigran-avdalyan** [comment]
@skoshelev Как я знаю второй метод включаеться автоматический если первый метод не дал уверенности что ползователь не Бот. Можно отключить второй метод проверки.
Но принудительно включить нельзя.
