### ISSUE TITLE
When using SSL behind a proxy (ie Cloudflare), admin locale is not en-US

### ISSUE THREAD

**Issue by mcliment** [nopSolutions/nopCommerce#2083]
In order the admin zone to work properly with numbers, it's important that the Culture is set to 'en-US'. This is done in `SetWorkingCulture` in `Global.asax.cs`, calling `CommonHelper.SetTelerikCulture` when the url matches with admin.
The problem is that it's comparing `WebHelper.GetThisPageUrl(false)` with `WebHelper.GetStoreLocation()'. The former method calls internally to 'WehHelper.GetThisPageUrl` and in this case, just returns `HttpContext.Request.Url`, which does not take in account any header that may indicate that the original request (and the effective store location) is https.
So, the urls don't match and the Culture is not set to `en-US` so if your store culture uses commas instead of dots to indicate decimal numbers, you're screwed.

**Comment by AndreiMaz** [comment]
@mcliment 
1. "WebHelper.GetThisPageUrl(false)" internally invokes "IsCurrentConnectionSecured()". So it'll return string starting with "https://" if a current store is SSL secured
2. webHelper.GetStoreLocation() works aboslutely the same way. It invokes "IsCurrentConnectionSecured()" to detect whether secured URL should be returned

Do you experience it only with CloudFlare?

BTW, please see "IsCurrentConnectionSecured" method of WebHelper. have you enabled "Use_HTTP_CLUSTER_HTTPS" or "Use_HTTP_X_FORWARDED_PROTO" in web.config?

**Comment by mcliment** [comment]
`IsCurrentConnectionSecure` works properly with the `web.config` setting in Cloudflare. That's not a problem.
The problem is here: https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Global.asax.cs#L199

This comparison compares two strings, and as `GetThisPageUrl(false)` return `http://....` and `GetStoreLocation()` honors request headers to determine if is SSL or not, returns a string starting with `https://...`, so it never matches and the culture is not properly set.

I hope I explained myself better this time.

**Comment by AndreiMaz** [comment]
So does "httpContext.Request.Url" return "http://..." in CloudFlare? Please confirm.

And please make screenshot of your admin admin > system > system info

**Comment by mcliment** [comment]
If you have Clouflare with Flex https (meaning you have a certificate in Cloudflare but the connection to your host is not secured), yes. It must rely on `HTTP_X_FORWARDED_PROTO` to determine if you are under SSL and works properly.
But, as you ask, `httpContext.Request.Url` returns `http://` because is not aware of this fact and that's why I added the code to change `http` for `https`.

**Comment by AndreiMaz** [comment]
could you also please share screenshot of your admin admin > system > system info

**Comment by mcliment** [comment]
This is a server without the patch (you can see dates in spanish):

![bad_http](https://cloud.githubusercontent.com/assets/63848/22551552/74a1c764-e955-11e6-9b4f-bf78cdc36e33.png)

An this one is patched:

![good_http](https://cloud.githubusercontent.com/assets/63848/22551562/7dd1ca32-e955-11e6-855a-4e78ca397459.png)

**Comment by AndreiMaz** [comment]
please expand "Variables del servidor"

**Comment by mcliment** [comment]
For the one that is not working (I changed some of them for privacy reasons and added some annotations):

```
APPL_MD_PATH: /LM/W3SVC/23/ROOT
APPL_PHYSICAL_PATH: C:\casarodriguez.com\
AUTH_TYPE: Forms
AUTH_USER: <private>
AUTH_PASSWORD:
LOGON_USER: <private>
REMOTE_USER: <private>
CERT_COOKIE:
CERT_FLAGS:
CERT_ISSUER:
CERT_KEYSIZE:
CERT_SECRETKEYSIZE:
CERT_SERIALNUMBER:
CERT_SERVER_ISSUER:
CERT_SERVER_SUBJECT:
CERT_SUBJECT:
CONTENT_LENGTH: 0
CONTENT_TYPE:
GATEWAY_INTERFACE: CGI/1.1
HTTPS: off
HTTPS_KEYSIZE:
HTTPS_SECRETKEYSIZE:
HTTPS_SERVER_ISSUER:
HTTPS_SERVER_SUBJECT:
INSTANCE_ID: 23
INSTANCE_META_PATH: /LM/W3SVC/23
LOCAL_ADDR: 84.x.x.x <- Server IP
PATH_INFO: /Admin/Common/SystemInfo
PATH_TRANSLATED: C:\casarodriguez.com\Admin\Common\SystemInfo
QUERY_STRING:
REMOTE_ADDR: 141.x.x.x <- Cloudflare IP
REMOTE_HOST: 141.x.x.x <- Cloudflare IP
REMOTE_PORT: 27596
REQUEST_METHOD: GET
SCRIPT_NAME: /Admin/Common/SystemInfo
SERVER_NAME: www.casa-rodriguez.com
SERVER_PORT: 80
SERVER_PORT_SECURE: 0
SERVER_PROTOCOL: HTTP/1.1
SERVER_SOFTWARE: Microsoft-IIS/8.0
URL: /Admin/Common/SystemInfo
HTTP_CONNECTION: Keep-Alive
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_ENCODING: gzip
HTTP_ACCEPT_LANGUAGE: ca,es;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,gl;q=0.2
HTTP_COOKIE: <private>
HTTP_HOST: www.casa-rodriguez.com
HTTP_REFERER: https://www.casa-rodriguez.com/admin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
HTTP_CF_IPCOUNTRY: ES
HTTP_X_FORWARDED_FOR: 79.x.x.x <- My IP
HTTP_CF_RAY: 32ae4b4c1e361049-CDG
HTTP_X_FORWARDED_PROTO: https
HTTP_CF_VISITOR: {"scheme":"https"}
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_DNT: 1
HTTP_CF_CONNECTING_IP: 79.x.x.x <- My IP
```

For the one that is patched:

```
APPL_MD_PATH: /LM/W3SVC/1/ROOT
APPL_PHYSICAL_PATH: C:\pacoperfumerias.com\
AUTH_TYPE: Forms
AUTH_USER: <private>
AUTH_PASSWORD:
LOGON_USER: <private>
REMOTE_USER: <private>
CERT_COOKIE:
CERT_FLAGS:
CERT_ISSUER:
CERT_KEYSIZE:
CERT_SECRETKEYSIZE:
CERT_SERIALNUMBER:
CERT_SERVER_ISSUER:
CERT_SERVER_SUBJECT:
CERT_SUBJECT:
CONTENT_LENGTH: 0
CONTENT_TYPE:
GATEWAY_INTERFACE: CGI/1.1
HTTPS: off
HTTPS_KEYSIZE:
HTTPS_SECRETKEYSIZE:
HTTPS_SERVER_ISSUER:
HTTPS_SERVER_SUBJECT:
INSTANCE_ID: 1
INSTANCE_META_PATH: /LM/W3SVC/1
LOCAL_ADDR: 213.x.x.x <-- Server IP
PATH_INFO: /Admin/Common/SystemInfo
PATH_TRANSLATED: C:\pacoperfumerias.com\Admin\Common\SystemInfo
QUERY_STRING:
REMOTE_ADDR: 108.x.x.x <-- Cloudflare IP
REMOTE_HOST: 108.x.x.x <-- Cloudflare IP
REMOTE_PORT: 31039
REQUEST_METHOD: GET
SCRIPT_NAME: /Admin/Common/SystemInfo
SERVER_NAME: www.pacoperfumerias.com
SERVER_PORT: 80
SERVER_PORT_SECURE: 0
SERVER_PROTOCOL: HTTP/1.1
SERVER_SOFTWARE: Microsoft-IIS/10.0
URL: /Admin/Common/SystemInfo
HTTP_CONNECTION: Keep-Alive
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_ENCODING: gzip
HTTP_ACCEPT_LANGUAGE: ca,es;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,gl;q=0.2
HTTP_COOKIE: <private>
HTTP_HOST: www.pacoperfumerias.com
HTTP_REFERER: https://www.pacoperfumerias.com/admin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
HTTP_CF_IPCOUNTRY: ES
HTTP_X_FORWARDED_FOR: 79.x.x.x <-- My IP
HTTP_CF_RAY: 32ae3fa49912104f-CDG
HTTP_X_FORWARDED_PROTO: https
HTTP_CF_VISITOR: {"scheme":"https"}
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_DNT: 1
HTTP_CF_CONNECTING_IP: 79.x.x.x <-- My IP
```

As you can see, the variables don't change, they are configured equally with Flex SSL.

**Comment by RomanovM** [comment]
@mcliment We made some changes in "GetThisPageUrl" method. You can test it and let us know if the problem persists.

**Comment by mcliment** [comment]
@RomanovM I tested it right now and works well. Admin zone is en-US and shop is configured as es-ES. And the solution is simpler than my patch. Thanks!
