### ISSUE TITLE
Templates for specification attributes/options/groups

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2085]
Like we can  Grouping of Specification Atributes and Options
Group Name- "Vw Golf 5 2.0"
Specification Attribute - Engine    Option- 2.0 L
Specification Attribute - Gearbox  Option- Automat

And We have Product By Name  "VW Golf 5 2.0 from Russia"

in this product specification attributes option opportunity to chose  "Vw Golf 5 2.0"

also see http://www.nopcommerce.com/boards/t/46603/category-specifications-attribute-template.aspx

**Comment by AndreiMaz** [comment]
is it the same as https://github.com/nopSolutions/nopCommerce/issues/1159?

**Comment by tigran-avdalyan** [comment]
no its like https://auto.ru/cars/new/sale/volkswagen/golf/1045637488-ffc36c
You have Product, and Grouped Specifications , in example site called "Характеристики".

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Thanks! Actually it's the same (grouping). But we don't have a task about templates (predefined values). So I've renamed this work to support templates

**Comment by tigran-avdalyan** [comment]
Thanks

**Comment by tigran-avdalyan** [comment]
we can create SubLayer for Manufacturer and set name For example Model, set for model specifications, and then connect to Product(as we do with connecting Manufacturer to product).

For example Manufacturer>>Apple
Model1>> Iphone 6
Model2 >> Iphone 7

we cane create Specifications for Iphone 6 and Iphone 7

when we create product By Name "Iphone 6 from MyStore"
we can connect to Model1 and Product inherit same Specifications

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by glhays** [comment]
Oh wouldn't that be nice. Well needed for how many versions now. Not to
mention you better have saved any changes in the product before you go
add/edit a specification. Sorry short rant.
