### ISSUE TITLE
Category import  BUG

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2086]
When importing Category whith same ID , its not update, its create Duplicate

**Comment by tigran-avdalyan** [comment]
in Excel , i write ID from 1 to 200
But in Database imported from ID 1000 to 1200

**Comment by AndreiMaz** [comment]
you cannot import by ID. it's used by update existing categories

P.S. Tigran, could you please report all further issues (or suggestions) on our forums? 
http://www.nopcommerce.com/boards/f/17/bug-reports.aspx or http://www.nopcommerce.com/boards/f/7/suggestions-and-feedback.aspx

**Comment by tigran-avdalyan** [comment]
i import products by ID from 1 to 200
then i change Parameter show on Menu from True to False , and dont change ID(id steel from 1 to 200)
when i import second time he create Duplicates but need to update 


from Nopcommerce 3.8
Imported categories are distinguished by ID. If the ID already exists, then its corresponding category will be updated.

**Comment by AndreiMaz** [comment]
It works just fine. Try debugging "ImportCategoriesFromXlsx" method. It invokes "_categoryService.GetCategoryById"

**Comment by tigran-avdalyan** [comment]
If i cant import by ID , so i cant import SubCategory whith Parent Category in same time
