### ISSUE TITLE
New social media links for general settings

### ISSUE THREAD

**Issue by jhaydens** [nopSolutions/nopCommerce#2087]
In general settings, we can provide links to facebook, twitter, google+ and youtube

I propose also including inputs for :

instagram
vimeo
pintrest

some logos attached - need to be added to 'socialsprite.jpg' 
css also will also need amended

![pintrestlogofor-social-sprite](https://cloud.githubusercontent.com/assets/16783039/22589124/9552b22e-ea00-11e6-9dca-00e6bc7a052b.png)
![vimeologofor-social-sprite](https://cloud.githubusercontent.com/assets/16783039/22589125/95537218-ea00-11e6-84c5-370f464020e6.png)
![instagramlogofor-social-sprite](https://cloud.githubusercontent.com/assets/16783039/22589127/95552856-ea00-11e6-8f7c-dce31ca8b35a.png)
![pintrestlogo2for-social-sprite](https://cloud.githubusercontent.com/assets/16783039/22589126/9553c1aa-ea00-11e6-9197-f1040d4cee87.png)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
