### ISSUE TITLE
Validation fix for password protected pages with forms

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2091]
Not tested. Let's check

Source: http://www.nopcommerce.com/boards/t/46112/validation-fix-for-password-protected-pages-with-forms.aspx

**Comment by skoshelev** [comment]
Cannot reproduce. Closed #2091.

**Comment by clouser** [comment]
I have provided steps to reproduce this issue [here](http://www.nopcommerce.com/boards/t/46112/validation-fix-for-password-protected-pages-with-forms.aspx#183772).  This issue should not have been closed.

**Comment by skoshelev** [comment]
Closed #2091
