### ISSUE TITLE
Allow a store owner to configure number of levels to render categories on mobile devices (HTML)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2094]
TopMenu.cshtml file. For desktop devices we already validate "IncludeInTopMenu" property. But not for mobile devices.

Otherwise, it can cause performance issues as all of them are rendered in HTML (output). For example, when we have 10,000 categories, then all of them are rendered on mobile devices

Add a setting. Set it to 4 by default. But it's also a bad solution. Maybe, we should render only subcategories of the current one. But onthe other hand, it's not user-friendly

**Comment by RuS984** [comment]
Closed #2094
