### ISSUE TITLE
Allow customer to check a gift card balance

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2098]
Another thing is that if I am a customer on the site and I purchase an item using a voucher code and use a partial amount of the voucher, where do I view my gift voucher balance as a customer? At the moment, I can see voucher balances as an administrator only. I do not see any sort of report section for a customer to go to in their account and view the vouchers that they have used and the view if there are any balances.

If we do it for guests, then ensure that voucher codes cannot be bruteforced. Let's make it configurable and disabled by default

**Comment by DmitriyKulagin** [comment]
Closed #2098
