### ISSUE TITLE
Move back to browscap.org or ua-parser to detect search crawlers

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#210]
UserAgentStringLibrary library is used to parse information about user agents located at \App_Data\uas_20140809-02.ini file. Both of them (DLL and INI files) were downloaded at http://user-agent-string.info (was available for free). Now I see that this project is moved to https://udger.com/ on November 2014 with sone new pricing options. 

We cannot continue usage of the new project because of its new license and pricing option (confirmed by its owner). He recommended to use a classic http://browscap.org/ (as it was done before) 

Some code and suggestions at https://github.com/browscap/browscap/issues/203 and www.gocher.me/C-Sharp-Browscap 

We can also consider https://github.com/ua-parser/uap-csharp

**Comment by skoshelev** [comment]
Closed #210
