### ISSUE TITLE
Azure Active Directory Federated Single Sign-On

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2101]
Based on our last communication, we know that you are currently working on enabling Azure Active Directory Federated Single Sign-On (AAD Federated SSO) for your app.

AAD Federated SSO provides a benefit to both AppSource end users and you. End users get a 1-click trial experience for your app, and you get access to the 750M users with AAD credentials worldwide. Having the user sign in with Azure AD means we know a lot about the user and we use that data to give you qualified actionable leads as well as connect you with the account team of the customer if needed.

We have a team of AAD Federated SSO specialist standing by to help answer any questions you have about enabling AAD Federated SSO. If you want, we can put you on a call with AAD specialists to answer any questions you have about enabling AAD Federated SSO.

also see related work item - https://github.com/nopSolutions/nopCommerce/issues/248

**Comment by AndreiMaz** [comment]
was required for MSAppSource

**Comment by dorofeev-serdg** [comment]
@AndreiMaz This issue is quite old. Is it still required?

**Comment by dorofeev-serdg** [comment]
@AndreiMaz This issue is more than 3 years old. Is it still required to be implemented?

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave it for plugin vendors
