### ISSUE TITLE
Use "Cookie Consent by Insites" for EU cookie warning (open-source and free)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2103]
Looks nice https://cookieconsent.insites.com/

Source: http://www.nopcommerce.com/boards/t/45961/cookie-law-popup.aspx#183066

**Comment by stephdep** [comment]
Indeed, the honeybee theme is exactly what is needed.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
