### ISSUE TITLE
there are no valid services available (code:556) with FedEx plugin

### ISSUE THREAD

**Issue by yechongbo** [nopSolutions/nopCommerce#2105]
Hi Guys,

We are facing an issue with FedEx plugin while calculating the shipping cost. The error message is as the issue title. It seems it happens only when we set the primary currency to be Singapore Dollar(SGD). Any advices will be appreciated, thanks!
![img_09022017_155349](https://cloud.githubusercontent.com/assets/11768463/22774219/24011b0c-eee1-11e6-962c-c64b5246d2f8.png)
![img_09022017_155456](https://cloud.githubusercontent.com/assets/11768463/22774227/2c350388-eee1-11e6-8a71-1c4a17338edc.png)
![img_09022017_151431](https://cloud.githubusercontent.com/assets/11768463/22774243/4084a71c-eee1-11e6-9b96-9ab48cc95f23.png)

**Comment by AndreiMaz** [comment]
the error is self-describing - "there are no valid services available" (

**Comment by RomanovM** [comment]
You are correct, the error related to your currency (Singapore dollar). As you have written you use SGD code, while FedEx expects SID code. You can view information about the FedEx currency codes [here](https://www.fedex.com/us/developer/WebHelp/ws/2014/dvg/WS_DVG_WebHelp/Appendix_F_Currency_Codes.htm).

**Comment by yechongbo** [comment]
@RomanovM, I see, thanks man for the information!
