### ISSUE TITLE
ACL. Allow restrictions per specific users

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2111]
I'm trying to set up a store where-in each of the items for sale will be specific and uniquley available to only one particular customer.

They are bespoke products and the customer will return time and again to reorder.

Because they are bespoke, no-one else should be able to buy them (I havent decided whether i want others to be able to see the items and just not be able to buy them) so not sure if i want to hide the item or just hide the buy button/price) The option would be good.

ACL is not a good solution to this because you would need to set up a role for each customer(imagine trying to manage the list ! the table is already full with just the standard ACL rules)

I envisage a checkbox on the 'advanced' product details page where you can select 'only available to selected customers'
when checked, an input field appears where we can begin typing a name - auto complete pulls the customer name (first and last) and we click to select - the same way as it does for product tags.
We could have a dropdown here asking 'hide item from other customers' or 'disable buy button for other customers'

(i am not suggesting to replace acl for products)

Source: http://www.nopcommerce.com/boards/t/46181/allow-a-product-to-be-restricted-to-specific-customers-without-using-acl.aspx

**Comment by tigran-avdalyan** [comment]
Let ability to create Virtual Group of Products, Virtual Group of Users, Virtual Group of Permissions
And Map this Groups

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It can significantly descrease performance and make development more complex. So it' better to a described workaround (with additional customer role)
