### ISSUE TITLE
Refactor "GetAllCategories" method (performance issues)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2113]
It's quite slow with thousands of categories. The issue is in the "unsortedCategories.SortCategoriesForTree()" line of code. Maybe, we should be better do all sorting on in database layer

Maybe we should use a stored procedure if it's not possible (or slow) with LINQ

**Comment by MaxMommersteeg** [comment]
> (it's much faster in admin area with a large number of categories than the LINQ implementation)

Why does this only affect the Admin area and doesn't improve performance at Shop area? Doesn't the shop make use of `GetAllCategories` method?

**Comment by AndreiMaz** [comment]
It uses. But we load all categories in public store on the first request (not paging is used). So it almost doesn't effect performance. But it slighly increases it with large number of categories (e.g. 1-2K)
