### ISSUE TITLE
Discount requirements.  Better UI/UX to add groups

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2117]
Right now it's together with other requirements. Maybe, we could increase it some way. Make more user-friendly

**Comment by eadameg** [comment]
Is it related to #271 ?

**Comment by AndreiMaz** [comment]
@eadameg yes. the next task

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
