### ISSUE TITLE
360 degree product photography

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2121]

**Comment by AndreiMaz** [comment]
Tigran, please clarify the task

**Comment by tigran-avdalyan** [comment]
add 360 degree picture viewer
example http://www.webrotate360.com/

**Comment by tigran-avdalyan** [comment]
example viewer
https://github.com/mpetroff/pannellum

**Comment by tigran-avdalyan** [comment]
or
https://github.com/leandigo/leanorama

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
