### ISSUE TITLE
Product tags count is not properly calculated in multi-store environment in SQL Compact

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#213]
Product tags count is not properly calculated in multi-store environment in SQL Compact

See GetProductCount method of \Libraries\Nop.Services\Catalog\ProductTagService.cs (when stored procedures are not supported/disabled). When "storeId" > 0

**Comment by RomanovM** [comment]
Fixes. https://github.com/nopSolutions/nopCommerce/commit/355f53c30dc30518c73d846134b5e1e0a2225be4
