### ISSUE TITLE
CSS multilanguage support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2132]
opportunity to have individual CSS for every Language

UPDATE: see the comment below

**Comment by kingmotley** [comment]
If the html tag had the appropriate lang attribute set (best practices anyway), then you would be able to easily have different styles per language.

Ex: <html lang="en-us"><h1>English
vs
<html lang="ru"><h1>Russian

Then using your stylesheet:
h1:lang(en) { color: green; }
h1:lang(ru) { color: red; }

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
