### ISSUE TITLE
_GridPagerMessages.cshtml  typo

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#2142]
In Presentation/Nop.Web/Administration/Views/Shared/_GridPagerMessages.cshtml :
last two lines: 
allPages: "@T("Admin.Pager.All")",
morePages: "@T("Admin.Pager.All")"

morePages should use resource name like "Admin.Pager.MorePages"

**Comment by AndreiMaz** [comment]
Thanks!

**Comment by huynhhoc** [comment]
Hello,

Please help me with _GridPagerMessages.cshtml, I did not see where is this file.

Thanks in advance
