### ISSUE TITLE
Separate page for each product with product attribute

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#2149]
https://www.amazon.com/gp/product/B01LZ4Y41M/ref=s9_dcacsd_dcoop_bw_c_x_1_w?th=1

Above link, iphone 7 have separate page for each iphone 32GB, 64GB, 128GB and 256GB

This optimizes to SEO.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
