### ISSUE TITLE
Move to ASP.NET core

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#215]

**Comment by joe704la** [comment]
I don't think there really is a ASP.NET 5 anymore I think they renamed it ASP.NET Core. http://www.asp.net/core

I would love to see this happen. So many benefits in moving to this.

**Comment by eNTi** [comment]
This would be awesome. I'm currently trying to migrate to Visual Studio Code. Would be great if I could debug nopCommerce there.

**Comment by XcoderTeam** [comment]
@AndreiMaz Can we develop the next nop 4.0 in open way.
What is the roadmap of the product?
Is there any plan to bring the solution to native app (iOS) not responsive version?

**Comment by AndreiMaz** [comment]
@XcoderTeam no, we don't plan to support native apps now (responsive design is enough out of the box). but there are some third-party native apps available on our marketplace.

4.00 will be released after 3.90. please find more details at http://www.nopcommerce.com/boards/t/43815/nopcommerce-390-roadmap-and-estimated-release-date-lets-discuss.aspx

**Comment by ATLSAPI** [comment]
Hi @AndreiMaz , we are just starting a project using NopCommerce 3.80, and we plan to maintain an upgrade path to future versions of NopCommerce. Seeing the decision to move to .NET Core for NopCommerce version 4.0. Will that be a problem for us?

**Comment by AndreiMaz** [comment]
No. There will not be any issues with upgrades

**Comment by inluxc** [comment]
Look for an Magento alternative, but i don't want in windows. So .Net Core will be more them welcome. 👍

**Comment by bustiloo** [comment]
The .Net Core should be the way forward. Visual Studio Code + iOS, Linux or Windows

**Comment by clearbucketLabs** [comment]
i think EF Core is the setback, it still lacks a few important features.   2.0 might solve those for nop, possibly.

**Comment by rolandh** [comment]
Is netcore an option now?

**Comment by eadameg** [comment]
@rolandh It is on [its way ](https://github.com/nopSolutions/nopCommerce/commits/develop)

**Comment by rolandh** [comment]
Is there a beta build that I can play with?

**Comment by AndreiMaz** [comment]
@rolandh it's almost done. we just need need to polish it. you can use the link provider by @eadameg to get the latest version

**Comment by rolandh** [comment]
If I pull the develop branch are the install instructions the same for installing as a netcore webapp?
