### ISSUE TITLE
change Nop.Admin / Controller / ProductController / PrepareProductModel

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2156]
in
                model.IsShipEnabled = true;
                model.AllowCustomerReviews = true;
                model.Published = true;
                model.VisibleIndividually = true;

parameters set to "false"

**Comment by AndreiMaz** [comment]
it's by design. there's another work item - to make default values configurable

**Comment by tigran-avdalyan** [comment]
Make Category and manufacturer default values configurable #669

is it that work?

**Comment by AndreiMaz** [comment]
yeah, I've renamed it
