### ISSUE TITLE
Localizable values in admin area (configurable)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2158]
Some of our entities are localizable (e.g. products or attributes, plugin names, etc). In admin area we already display their default values (not localizable).

Let's add a setting indicating whether we should use localization in admin area or not (for read-only properties). Disable it by default

Also we can support searching by languages

Also see https://github.com/nopSolutions/nopCommerce/issues/4013

**Comment by tigran-avdalyan** [comment]
Same problem when Language in Admin are set for example Russian , and  we go to Specification Attributes, there showing in Standard , but need Russian.
Same problem in Product Attributes .

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Thanks! The same issue can be told about any localizable entity. It was originally by design to disable localization in admin area. I think we can make it configurable

**Comment by tigran-avdalyan** [comment]
configurable- its Good

**Comment by tigran-avdalyan** [comment]
in product page when we map to Categoryes, Categories Localizable values support

**Comment by AndreiMaz** [comment]
see related https://github.com/nopSolutions/nopCommerce/issues/3060

**Comment by AxelAndersen** [comment]
Thanks Andrei, did not find this before :-)
So will this be part of 4.1?

**Comment by AndreiMaz** [comment]
@AxelAndersen no, it's not assigned to 4.10

**Comment by AxelAndersen** [comment]
Ok, we will wait for it :-)
Any dates for 4.10 release?

**Comment by AndreiMaz** [comment]
July 2018

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality.
