### ISSUE TITLE
Product Attributes repeated on product detail page

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#2160]
Hello,

I have found an issue where product attributes are displayed twice or thrice. This issue arise due to Contains query in ProductAttributeService.cs under "GetProductAttributeValuesByProductId" method
Here is code
 `var query = from pav in _productAttributeValueRepository.Table
                                join pam in _productAttributeMappingRepository.Table on pav.ProductAttributeMappingId equals pam.Id
                                join pac in _productAttributeCombinationRepository.Table on pam.ProductId equals pac.ProductId
                                where pac.ProductId == productId && pac.AttributesXml.Contains(pav.Id.ToString())
                                select pav;`

Its better that I will show issue by image

![issue_image1](https://cloud.githubusercontent.com/assets/21276844/23298223/ce7e23fa-faa2-11e6-82e9-d9419b44a741.PNG)

you can see my ProductAttributeMappingId = 25 and product attribute value from 1 to 6. so when you run your query which is **ProductAttributeService.cs** it includes more result because attributeXML have 25. I will show you result with sql 

this result of your query 
![issue_image2](https://cloud.githubusercontent.com/assets/21276844/23298365/6874a84e-faa3-11e6-8a52-11ca797e288e.PNG)

I suggest to modify query like below
![suggestion](https://cloud.githubusercontent.com/assets/21276844/23298395/7d9aa3d6-faa3-11e6-9ccc-d3caf88911a8.PNG)

It can be case with productAttributeMappingId = 10 and product attribute value from 100 to 109 and more combination also  

Hope you get this issue

**Comment by AndreiMaz** [comment]
But there's no such method in ProductAttributeService
