### ISSUE TITLE
New real one-page checkout (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#217]
One click checkout – similar concept as eBay and Amazon, where an existing shopper can purchase an item on a single click. This will require a default shipping address, a default shipping method, a default payment option.

Forum sources: 
http://www.nopcommerce.com/boards/t/15461/new-one-page-checkout.aspx 
http://www.nopcommerce.com/boards/t/16632/our-new-one-page-checkout-any-feedback.aspx 

also http://www.nopcommerce.com/p/1265/simple-checkout-v2.aspx 

File is attached 

Also see http://www.nopcommerce.com/p/899/plugin-onepagecheckout.aspx

[OnePageCheckoutV2.zip](https://github.com/nopSolutions/nopCommerce/files/91944/OnePageCheckoutV2.zip)

**Comment by Ochapparel** [comment]
Thanks for making this. Really appreciate the attempt to improve the 1 page checkout

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin (already available as plugin)
