### ISSUE TITLE
Thread-safe  issue with IEngine

### ISSUE THREAD

**Issue by tangdf** [nopSolutions/nopCommerce#2182]
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Infrastructure/EngineContext.cs#L23

First call the Initialize method, and then set the value

       
    public static IEngine Initialize(bool forceRecreate)  
      {  
         if (Singleton<IEngine>.Instance == null || forceRecreate)
         {   
                NopEngine nopEngine = new NopEngine();   
                var config = ConfigurationManager.GetSection("NopConfig") as NopConfig;
                 nopEngine.Initialize(config);
                  Singleton<IEngine>.Instance = nopEngine;
            }
            return Singleton<IEngine>.Instance;
     }

**Comment by skoshelev** [comment]
Closed #2182. Not relevant anymore
