### ISSUE TITLE
Include mediasettings.defaultpicturezoomenabled on Media settings page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2185]
The mediasettings.defaultpicturezoomenabled setting isn't available from the Media settings page, I think it would be  useful to include it.

Source: http://www.nopcommerce.com/boards/t/46442/suggestion-include-mediasettingsdefaultpicturezoomenabled-on-media-settings-page.aspx

**Comment by skoshelev** [comment]
Closed #2185
