### ISSUE TITLE
Use Twitter Bootstrap

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#219]
Contribution for version 3.60: http://www.nopcommerce.com/boards/t/36904/new-100-bootstrap-theme.aspx and 

Forum source: http://www.nopcommerce.com/boards/t/18801/nopcommerce-with-twitter-bootstrap.aspx 

also see http://www.nopcommerce.com/boards/t/29026/free-bootstrap-default-theme.aspx#118204 

one more theme - http://www.nopcommerce.com/p/1381/noproot-bootstrap-theme-free.aspx 

and more theme (free) - https://github.com/phuochuy-github/Bootswatch-3.2.0-For-Nopcommerce-2.8 

also http://www.nopcommerce.com/boards/t/29026/free-bootstrap-default-theme.aspx

**Comment by sc0ttc0** [comment]
Any further thoughts on this.  I think it would be good - not sure if bootstrap licensing might be an issue (ie it might change in the future).   Certainly appears to be popular and gives developers a layout language they'd be familiar with ... I guess arguably you can do it already if you want to.  Maybe ship the default theme plus a bootstrap theme ?    It would also allow developers to use other design frameworks built on top of bootstrap.

Maybe just too big a job at the moment / not worth it ?

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
