### ISSUE TITLE
Add Phone Number when select Call For Prices

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2191]
When we in Edit Product Details checking Call For Prices , then show Textbox where we can write Phone Number.
And in Product View Page Show for example "Call for price: +7-901-444-444"

**Comment by tigran-avdalyan** [comment]
For example in product page write Call For Price.
Costumer think , Call Vendor , Call Store owner , or search other contact.

another situation when Vendor sale Mobile Phones and Cars, but for Mobile Phones costumer need to call to Number1 and for Cars to Number2

**Comment by tigran-avdalyan** [comment]
i think Vendor can have phone number list:
And when in product page Vendor check Call For Price he can select number from his number list

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
