### ISSUE TITLE
Performance. Cache entities between requests, two-level caching (Entity Framework limitation)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#220]
We need to cache some look-up data between requests (e.g. countries, states etc). We need to allow developers to set how they would prefer caching of database entities to work (cache per request or cache between requests). Caching managers of the each existing service can be easily replaced. But we have problems when caching entities between requests - an entity can only be attached to one ObjectContext at a time. We need to solve it. 

But It's not possible until EF starts supporting it 

Also see EntityFramework.Extended library 

See cacching in EF 6.1 - http://blog.3d-logic.com/2014/03/20/second-level-cache-for-ef-6-1/ 

Useful links:
http://www.nopcommerce.com/boards/t/18548/2nd-level-caching-fork-available.aspx
http://www.nopcommerce.com/boards/t/18332/nopcommerce-270-roadmap.aspx?p=7#75738
http://stackoverflow.com/questions/1147681/how-to-make-entity-framework-cache-some-objects
http://blogs.msdn.com/b/jkowalski/archive/2009/06/11/tracing-and-caching-in-entity-framework-available-on-msdn-code-gallery.aspx?wa=wsignin1.0
http://blogs.msdn.com/b/alexj/archive/2009/04/22/tip-14-caching-entity-framework-reference-data.aspx
http://code.msdn.microsoft.com/EFProviderWrappers
http://social.msdn.microsoft.com/Forums/en/adodotnetentityframework/thread/fdc5c7ac-dcf8-45a8-ab11-2ffbc338b0e5
http://stackoverflow.com/questions/898260/what-value-for-qualifiedentitysetname-do-i-need-for-an-entitykey-constructor
http://www.nopcommerce.com/boards/t/5917/nopcommerce-17-cache-not-working-possible-solution-to-17-slowness.aspx
http://deanhume.com/Home/BlogPost/object-caching----net-4/37
http://www.nopcommerce.com/boards/t/16551/nopcommerce-slow.aspx?p=2#70577
http://blogs.microsoft.co.il/blogs/bnaya/archive/2013/01/13/entity-framework-pro-and-con.aspx

**Comment by AndreiMaz** [comment]
We wait for EF official support (or moving to Dapper will help). But not with the current implementation
