### ISSUE TITLE
Azure Faceted Search

### ISSUE THREAD

**Issue by tomakali** [nopSolutions/nopCommerce#2204]
Shouldn't Nopcommerce have api interface for external search providers?
azure, solr etc

Source: http://www.nopcommerce.com/boards/t/46627/azure-faceted-search-implementation.aspx

**Comment by esbee** [comment]
Yes please!!!

**Comment by tomakali** [comment]
nopcommerce + azure search index + azure customer insights = BOOM for enterprise

Imo, Nopcommerce if it is built for azure and for aws it will become an unmatched ecommerce platform

**Comment by AndreiMaz** [comment]
duplciated https://github.com/nopSolutions/nopCommerce/issues/228
