### ISSUE TITLE
Nopcommerce Core Templates

### ISSUE THREAD

**Issue by tomakali** [nopSolutions/nopCommerce#2205]
i dont know if its possible
but it would be great if nopcommerce can have "core templates"

core template will install required fields only
so that the whole application will be super fast and more relevant to the niche of the store

![nopcommerce-core-template](https://cloud.githubusercontent.com/assets/5163951/23703352/818805ca-0425-11e7-8750-526c5a6eb5cb.jpg)

or, splitting the front end and back end will be more complex but will be favorable for high availability cloud architecture

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
