### ISSUE TITLE
"Featured Products" on the Home page. Sample products

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2206]
We noticed that in the "Featured Products" on the Home page, the box of the third product "HTC One M8 Android L 5.0 Lollipop" is not aligned with the other product boxes. The reason is that the name is longer and it takes 2 lines and moves the add to cart button further down. In the previous version this was not the case as all product titles took 2 lines by default. 
Is this made on purpose in the new version?

Source: http://www.nopcommerce.com/boards/t/46341/nopcommerce-390-beta-released-please-share-your-impressions.aspx?p=7#184539

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/71b35d0f0e58e6b4aee2e7a969a5f3b28060c391
