### ISSUE TITLE
MiniProfiler. Set ProfileLevel to Verbose 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2208]
Also we usually change the verbosity of the MiniProfiler in order to see which actions are taking the most time. I think this should be set to Verbose by default as otherwise the information is useless as it basically shows the page load time which you can see in the network tab in the browser anyway.

Here is the simple change:

MiniProfiler.Start(ProfileLevel.Verbose);

Source: http://www.nopcommerce.com/boards/t/46341/nopcommerce-390-beta-released-please-share-your-impressions.aspx?p=7#184542

**Comment by poyker** [comment]
Maybe this is not needed anymore in 3.90. You can close this issue.

http://www.nopcommerce.com/boards/t/46341/nopcommerce-390-beta-released-please-share-your-impressions.aspx?p=8#184653
