### ISSUE TITLE
Include a buy button in the search autocomplete box

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2214]
just been buying some veg seeds for the garden and saw this feature - check it out:
http://www.marshalls-seeds.co.uk

start typeing onions in their search box

Source: http://www.nopcommerce.com/boards/t/46534/include-a-buy-button-in-the-search-autocomplete-box.aspx

**Comment by ngtrian** [comment]
maybe add price text inline!

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
