### ISSUE TITLE
Unique SEO code is overwritten/lost when "SEO code" has only two chars and "SEO friendly URLs with multiple languages" enabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2216]
Issue: Unique SEO code is overwritten/lost

Expected behaviour:
1. Viewing http://www.yourStore.com/en/nike
2. Changing language with language selector
3. Redirects to http://www.yourStore.com/cn/耐克

Current behaviour:
1. Viewing http://www.yourStore.com/en/nike
2. Changing language with language selector
3. Redirects to homepage with URL http://www.yourStore.com/耐克 (SEO code "cn" disappears)
Only happens with 2 Chinese words (have not tried 1 word). 3 or more words works as normal, so is changing Chinese (/cn/耐克) into English (/en/nike).

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/03a442b65e64aa7fdb97161c1c1f75121ef7236d and https://github.com/nopSolutions/nopCommerce/commit/f89b3ff2b8ee08509312675037e40c2ddbd97348
