### ISSUE TITLE
unsed parameter in PictureService

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#2218]
Libraries/Nop.Services/Media/PictureService.cs, line 316
function GeneratedThumbExists has a parameter thumbFileName which is unuseful.
protected virtual bool GeneratedThumbExists(string thumbFilePath, string thumbFileName)
{
            return File.Exists(thumbFilePath);
}

at line 402, we call GeneratedThumbExists with unuseful parameter thumbFileName
if (!GeneratedThumbExists(thumbFilePath, thumbFileName))

**Comment by AndreiMaz** [comment]
it's not usused. it's used in the \Libraries\Nop.Services\Media\AzurePictureService.cs
