### ISSUE TITLE
The ability to create a configuration for the Categories, Products and apply them to the Admin Panel

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2219]
Ability to create Configuration , and when we connect the configuration to Category , the products(or child categories) in Category can inherit  the configurations.
Configuration can include Specification attributes, Product Attributes, Categories Parameters, Product Parameters.
When we use Configuration for category it can use all parameters, when we use for Product it use only that part of parameters , that touch Products.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We already have "Copy product" functionality that can be used for such purposes
