### ISSUE TITLE
Phone number verification during registration (configurable)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2228]
Its need to fight with Fake profiles, and situation when one person have many accounts.

**Comment by tigran-avdalyan** [comment]
and ability login with Phone Number an Password

**Comment by tigran-avdalyan** [comment]
please see
https://firebase.google.com/docs/auth/web/phone-auth

**Comment by mrnams** [comment]
I am not getting what solution has been implemented while closing this PR?

**Comment by dborovsky** [comment]
@AndreiMaz @RomanovM @mrnams  I can try implement registration by phone number. What do you think?  Or if you have now more priority issue, tell me. Thank you.

**Comment by mrnams** [comment]
Guys,
What's stopping to implement this?
It's highly important than any other issues.

**Comment by dborovsky** [comment]
@AndreiMaz @RomanovM i started implement this issue. Change label to  **functionality / feature**

**Comment by mrnams** [comment]
@dborovsky Thanks,(fyi @AndreiMaz @RomanovM)

@dborovsky As i mentioned in chat,  I implemented using twilio service for demo purpose ,but i am novice to asp.net core, and yet have not understood our site architecture completely,So I feel I may not be right person to implement in our website. @dborovsky Assign me any task if you are busy with other task,even I can do testing of our implementation of phone verification.

**Comment by dborovsky** [comment]
How i undestood feature:

List of registration method in admin panel will include  **Phone number verification during registration** 
When user sign up in store registration page will have additional field **phone number**:

After registration will redirect to page for input verification code. User will receive confirmation code by sms  except email. 

If user didnt verificate phone number and try sign in, the page with input code will automatically open again with message "You didnt verificate your phone" or something like this

And we will need to add in Admin panel->Configuration new tab "Sms service accounts"(it seems like Email accounts) 

Correct?

**Comment by mrnams** [comment]
Sorry for delay,
Yes exactly,along with SMS we should also make verification with call,thats not difficult with twilio service.

Please refer below site,we want exact same behaviour
https://www.flipkart.com

**Comment by dborovsky** [comment]
@AndreiMaz @RomanovM Guys answer please. To implement it will be ok? Or maybe better create as separate plugin?

**Comment by mrnams** [comment]
@AndreiMaz
@RomanovM
@dborovsky
This is basic requirement, so i feel we should implement it, anyway we are controlling the feature through administrator.
So if some one feel they don't need, then they can disable it.

**Comment by mrnams** [comment]
@AndreiMaz
@RomanovM
@dborovsky
Anybody working on this

**Comment by dborovsky** [comment]
sure. i am trying to implement as plugin. If @AndreiMaz @RomanovM will tell me, this feature must be in core nopcommerce, i will open pull request. But they have not answered yet.

**Comment by AndreiMaz** [comment]
Right now we're still considering this feature to be available out of the box. Anyway even if we decide to implement it, it should have a pluggable architecture. So it can support multiple SMS verifacation providers. Right now it's on hold

**Comment by mrnams** [comment]
@AndreiMaz
@RomanovM
@dborovsky
If i am not wrong, we can control SMS verification provider through appsetting.json.
My thought.

**Comment by mrnams** [comment]
@dborovsky Hope you are working on this, either plugin or implement in core

**Comment by dborovsky** [comment]
> @dborovsky Hope you are working on this, either plugin or implement in core

yes

**Comment by mrnams** [comment]
@dborovsky 
I know it's too early to ask update.
Is there anything i can help ? though i m novice i shall try to contribute

**Comment by dborovsky** [comment]
@mrnams  I am almost finished with plugin. I`ll inform you soon. Wait please

**Comment by mrnams** [comment]
@dborovsky tons of thanks for quick response

**Comment by mrnams** [comment]
@dborovsky will it be available in 4.20 version.

**Comment by dborovsky** [comment]
@mrnams I`ve done. trying to test with real data

**Comment by mrnams** [comment]
@dborovsky thanks for update.

**Comment by mrnams** [comment]
@dborovsky I am testing Beta version, can I test this too?

**Comment by dborovsky** [comment]
@mrnams  yea. i`ve created plugin. give me few days.

**Comment by mrnams** [comment]
@dborovsky Thanks, Please notify us when available.

**Comment by mrnams** [comment]
@dborovsky Is it available?

**Comment by mrnams** [comment]
Congratulations @tigran-avdalyan @mrnams @dborovsky @AndreiMaz @mcliment  for releasing nopCommerce 4.20.
@dborovsky we are eagerly waiting to hear from you, Our deployment is pending for this plugin.
Thanks in advance.

**Comment by dborovsky** [comment]
@mrnams Sorry for delay. A lot of work. I will try finish until Friday. This is my first plugin for nopCommerce:)

**Comment by mrnams** [comment]
@dborovsky no issue at all.
Thanks of reply.
I just wanted to know, whether it's been released and missed to update here.

**Comment by mrnams** [comment]
@dborovsky did you get chance to work on this?

**Comment by dborovsky** [comment]
with twilio has already implemented. wait please.

**Comment by mrnams** [comment]
@dborovsky happy to hear that, excited to use it.

**Comment by mrnams** [comment]
@dborovsky any update :P

**Comment by mrnams** [comment]
@dborovsky sorry to interrupt.
 Is this available now? I was busy in other task so could not followed for this plugin.

**Comment by RomanovM** [comment]
@mrnams What third-party services for the phone verification can you suggest to implement this feature?

**Comment by mrnams** [comment]
Sorry for delay
Hi @RomanovM  @dborovsky Already implemented with twilio.
I did little comparison and found Restcomm,Bandwidth provide same service like twilio in cheaper rate.
Still I feel we can make plugin/feature generic to use for any service provider.
But this is really MUST feature, I hope you guys take it on priority.

**Comment by mrnams** [comment]
@RomanovM Can you please change label "on hold / maybe wont", so that  @dborovsky  can work and submit it.

**Comment by mrnams** [comment]
@RomanovM @dborovsky @mrnams @AndreiMaz 
I am sorry for multiple messages, I know everyone is busy with something other task.
But guys I really surprised for this issue, since this is most essential feature to have in any application where users registration is required. 
Also this is pending since first quarter of 2015.
I really love nopCommerce and eagerly waiting to see this application with #2228 issue fixed.
Hope we will see nopCommerce  with user registration module having option to register based on phone OTP and so... 
Sorry If I am too much followed.

**Comment by sinaislam** [comment]
We have already implement https://www.apex4u.com/login by changing source code and using facebook account kit. I will try to move it to plugin.

**Comment by mrnams** [comment]
@sinaislam  Tons of Thanks, eagerly waiting to see this application with #2228 issue fixed.

**Comment by mrnams** [comment]
@tigran-avdalyan @mrnams @dborovsky @AndreiMaz @RomanovM I am surprised to see #2228 in open after 3 years. So sad

**Comment by mrnams** [comment]
Really surprising this issue is still open (on hold).
@tigran-avdalyan  @mrnams   @dborovsky @AndreiMaz @RomanovM  Sorry, I could not follow up this one for long due to my personal work and just started looking at open issues and got disappointed.😥

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
