### ISSUE TITLE
Suggestion: Ouputcache widget

### ISSUE THREAD

**Issue by turbochris** [nopSolutions/nopCommerce#2231]
We have made the following changes in code:

In HtmlExtensions.cs in framework:

```
public static MvcHtmlString WidgetCached(this HtmlHelper helper, string widgetZone, object additionalData = null, string area = null)
        {
            return helper.Action("WidgetsByZoneCached", "Widget", new { widgetZone = widgetZone, additionalData = additionalData, area = area });
        }

```
In WidgetController.cs in Nop.Web

```
[ChildActionOnly]
[OutputCache(Duration = 3600, VaryByCustom = Core.OutputCacheVaryByCustomMethods.StoreAndLanguage)]
public ActionResult WidgetsByZoneCached(string widgetZone, object additionalData = null)
        {
            var model = _widgetModelFactory.GetRenderWidgetModels(widgetZone, additionalData);

            //no data?
            if (!model.Any())
                return Content("");

            return PartialView("~/Views/Widget/WidgetsByZone.cshtml", model);
        }
```

In Global asa's vary by custom, we have just varied the caching by minimum store and language (should probably be currency also)

This works pretty good, and it helps for overview that you in you cshtml page can write @Html.WidgetCached("XXXXX") so you immidiately know it's being output chached.

B.R

Chris & TB

**Comment by keremdemirer** [comment]
I think this won't be necessary with the AsnpNetCore ViewComponent implementation. Static caching of view models and async invoking actions will perform better than OutputCache.

**Comment by AndreiMaz** [comment]
keremdemirer is right
