### ISSUE TITLE
Add Watermark support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2233]
Add watermark support for product images. Configurable for every Product.

**Comment by AndreiMaz** [comment]
already supported in plug-ins

**Comment by tigran-avdalyan** [comment]
it's very important function for information security, we can add as default plugin or import to Nopcommerce

**Comment by tigran-avdalyan** [comment]
we can use http://imageprocessor.org/

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
