### ISSUE TITLE
Product info page- Tab View Description, Specification, Tags

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2234]
![image](https://cloud.githubusercontent.com/assets/17789934/23943435/e81f0b18-0988-11e7-84d7-40fa795d6b9d.png)

**Comment by AndreiMaz** [comment]
Available as plugins now

**Comment by tigran-avdalyan** [comment]
it's more User Friendly View, we can add in default Template
