### ISSUE TITLE
Default Registration Role Configurable 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2235]
Lets Admin choose New Registered user Default Role.

**Comment by AndreiMaz** [comment]
Could please clarify? We already have registered role?

**Comment by tigran-avdalyan** [comment]
we have Role - Costumer(Default Role for Customers)
we have Role - Vendor(Default Role for Vendors)
we create new Role by name Role2 
Role2- is Vendor or is Costumer?
Ability to set Role2 - Default Role for Customers or Vendors

**Comment by tigran-avdalyan** [comment]
when we create a new Role, lets add checkbox "Show in Registration"
and let ability to Users in Registration procedure choose - Costumer, Vendor or new Role.

**Comment by AndreiMaz** [comment]
So when an user is register he will be added to the default "Registered" role. And one more? Please clarify
