### ISSUE TITLE
Product Right side info Add "Condition"

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2238]
Product Right side info, before Add to Cart Button , Add info about Condition: New or Used.
Its need if we Planing Auction function.

Or we can create Specification Attribute by name Condition and Options New & Used.
And we need ability to show This specification attribute in a Product Right side.

**Comment by tigran-avdalyan** [comment]
Can be "refurbished" ; "For parts or not working"

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
