### ISSUE TITLE
Improve the code design: use  the initialization of classes and collections everywhere, replace the “for” loops to LINQ expression (where applicable)

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#2240]
related work items - https://github.com/nopSolutions/nopCommerce/issues/2237 and https://github.com/nopSolutions/nopCommerce/issues/2239

**Comment by pdunleavy** [comment]
Suggest resharper

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2448
