### ISSUE TITLE
Delivery Date connect to Shipping Metod

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2241]
in Product info page we can show a Delivery Date.
But practically Delivery Date is depends on what Shipping Method costumer choose.
Lets put Estimate shipping and Delivery date info to product page

**Comment by tigran-avdalyan** [comment]
Now we have fixed Delivery Dates for Product.
But we can choose Shipping method.
Example: We have 2 shipping methods and customer can choose what shipping method he want.
First shipping method By Car, Second By Air
we need to ship from Moscow to Paris.
By Car it take 15 days
By Air 2 days
What we can do? if Shopping method not fixed but Delivery Date fixed?

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It would be just not possible for online shipping rate providers (e.g. UPS, FedEx, etc)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz we can do it only for offline shipping metods
