### ISSUE TITLE
Improve Attribute Combinations generations

### ISSUE THREAD

**Issue by emiliano84** [nopSolutions/nopCommerce#2243]
At the moment there are two options: add an attribute combination manually one by one, or generate all the possible combinations. Imagine that we have 10 colors and 20 sizes in our attributes, but we want to add shoes with 3 colors and 10 sizes, is really annoying to add all single combinations one by one or generate all possible colors/sizes combinations and than delete the ones that you don't need.

The best way is to generate the all the combinations but only with the attributes you really need, for 
example from colors you choose: red, yellow, black and from size 5-15. Something like prestashop already does:

![capture](https://cloud.githubusercontent.com/assets/7117301/24074287/82fe5a3c-0bfd-11e7-9f2d-6ca747ec2760.PNG)

try it by yourself guys:
http://demo.prestashop.com/

thanks

**Comment by skoshelev** [comment]
Closed #2243
