### ISSUE TITLE
limit shipping method & pickup point for product & payment method

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2244]
By default product inherit Default list of shipping method,pickup point, payment method(can be sets Default lists for each Categories).
Give Admins & Vendors ability to limit shipping method & pickup point for product & payment method.

**Comment by emiliano84** [comment]
totally agree would be really nic in quite common scenarios like:
- pickup pay by cash
- shipping you want to enable only card/paypal payment

**Comment by AndreiMaz** [comment]
We decided to implement only https://github.com/nopSolutions/nopCommerce/issues/2251 out of the box. Do not plan to limit shipping methods by product out of the box
