### ISSUE TITLE
Allow a store owner to choose how to display product review. One final rating or each star separately

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2248]
For Example Where we can see Counts for each Rate: https://www.flipkart.com/shree-creation-embroidered-bollywood-poly-silk-sari/p/itmejyhtuhkhwhjz?pid=SAREJYHTYJCTSKGD&sattr=color&st=color&otracker=hp_omu_Deals%2520Of%2520The%2520Day_2_50-80%2525%2520Off_c1d1ffe6-5633-4d1a-8ae5-6a15b67e9552
![image](https://cloud.githubusercontent.com/assets/17789934/24097528/a86ce102-0d7f-11e7-86d0-94067fcb33b6.png)

Let's make it configurable

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
