### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#225]
Add multi-tenant support 

http://www.nopcommerce.com/boards/t/33913/nopcommerce-multi-tenant-demo-file-source-code.aspx 

something like what orchard has here (http://docs.orchardproject.net/Documentation/Setting-up-a-multi-tenant-orchard-site) or the multisite for wordpress here (http://codex.wordpress.org/Create_A_Network) 

also see http://www.nopcommerce.com/boards/t/24551/developing-multi-tenant-functionally-for-nopcommerce-brain-storming.aspx 

also see blogs - http://www.nopcommerce.com/boards/t/34205/a-blog-about-nopcommerce-and-some-articles-about-multi-tenancy-implementation.aspx 

and https://github.com/joeaudette/cloudscribe

**Comment by tigran-avdalyan** [comment]
http://www.nopcommerce.com/boards/t/44692/in-multi-store-i-need-different-admin-for-each-store.aspx

**Comment by QuanNH88** [comment]
Nopcommerce Multi Tenant Download

Supported Versions: 3.9
http://nopplugin.com/nopcommerce-multi-tenant-download

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by QuanNH88** [comment]
Dear!

We are pleased to announce official nopcommerce multi tenant 4.0 is released (aspnetcore 2.0.0).

In the new version, we continue upgrade the core and improve performance.

View demo: http://nopplugin.com/nopcommerce-multi-tenant-download

Thanks you!

**Comment by reader-man** [comment]
hi,
i wanted to iterate on the subject of multi-tenant, and if u can look at the shared folder, as it has a plugin + video to make nopCommerce Multi-Tenant.
maybe you might make it a feature in your comming release.
It has multiple benifits:
1. sharding the database in a horizontal way with open source projects like: Vitess "https://vitess.io/"
2. some queries in nopCommerce that will need to join multiple tables to retrieve the data related to a specific vendorID, will be direct and faster.

in the following folder, you see:
1> The plugin
2> A video describing what it does:
https://drive.google.com/drive/folders/1U-WtOYJaCSBPSwzk63NAi9kTwLswH5IB?usp=sharing

**Comment by AndreiMaz** [comment]
Plugin for 4.80 - https://www.nopcommerce.com/en/boards/topic/102429/multi-tenant-stores-management-plugin

**Comment by fateixeiradev-glitch** [comment]
> Plugin for 4.80 - https://www.nopcommerce.com/en/boards/topic/102429/multi-tenant-stores-management-plugin

This plugin is offline, where can I find it?
