### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2250]
There is something wrong with "Rounding up with 0.05 intervals (0.06 round to 0.10)".
Test environment: clean installation 3.90
SQL: 2014

Test product: Fahrenheit 451 by Ray Bradbury
Price with default rounding: 27.00
Price with Rounding up with 0.05... : 27.05

What is more. Add to cart with default rounding looks as below:
![roundingcart](https://cloud.githubusercontent.com/assets/5019111/24137838/8f843e5e-0e26-11e7-9323-6eef2d1b299a.png)
While just changing rounding option cause cart would show:
![roundingcart2](https://cloud.githubusercontent.com/assets/5019111/24137848/98e792f2-0e26-11e7-96b0-c9ec683014ee.png)
Suddenly sub-total showing as 27.15, shipping rise to 0.05, tax to 0.10, and two discounts are showing just by changing rounding. 

Source: http://www.nopcommerce.com/boards/t/46681/rounding-issue-390.aspx

**Comment by skoshelev** [comment]
Closed #2250

**Comment by skoshelev** [comment]
https://www.nopcommerce.com/boards/t/46681/rounding-issue-390.aspx#195646

**Comment by skoshelev** [comment]
Closed #2250
