### ISSUE TITLE
Limit pickup points  per product

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2251]
let ability to limitation pickup points for each product.

**Comment by tigran-avdalyan** [comment]
For Example i have 2 Pickup store, in Moscow and in New York.
But product can be only on Moscow store, but Customer can select New York Pickup Store.
What can i do?)))) send product to New York?
i think needs Limitation

**Comment by tigran-avdalyan** [comment]
Vendor can have PickUp Point list.
and in product page when Vendor select Enable  PickUp Point , then chose PickUp Points for this product.

**Comment by tigran-avdalyan** [comment]
Store Have Pickup Points, but Vendor can create own Pickup Point

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
