### ISSUE TITLE
Configurable Limitation for Vendors

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2257]
Let ability to limit Group of Specifications for Vendors 
Let ability to limit List of Categories for Vendors
Let ability to limit enable Downloadable Product for Vendors
Let ability to limit enable Rent Product for Vendors
Let ability to limit enable Available for pre-order for Vendors
Let ability to limit enable Call for price for Vendors
Let ability to limit list of Tax Category for Vendors
Let ability to limit list of Warehouse for Vendors
Let ability to limit enable Not returnable for Vendors
Let ability to limit list of Delivery date	for Vendors
Let ability to limit list of Manufacturers for Vendors
Let ability to limit Limited to stores 	for Vendors
Let ability to limit pickup points for Vendors
Let ability to limit Payment Method for Vendors
Let ability to limit Shipping method  for Vendors

**Comment by jhaydens** [comment]
ability to limit images per prouct
ability to limit amount of proucts

**Comment by tigran-avdalyan** [comment]
For example "group of vendors"  can add products only to allowed categories, add to product only alowed attributes,specifications and else.

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization) 

implement only https://github.com/nopSolutions/nopCommerce/issues/1767
