### ISSUE TITLE
Customers add products(available as plugin)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2258]
Ability to give possibility to place product by your customers in your store. You may use it to create notice board or base of announcements.

https://www.nop4you.com/notice-board-announcements-nopcommerce

**Comment by tigran-avdalyan** [comment]
only allow Sample Functions to Add Product.
Disable  Product Type: Only Sample(can be hiden)
Disable Visible individually: Only Chacked (can be Chacked and Hiden)
Disable SKU
Disable GTIN
Disable Show on home page
Disable Allow customer reviews
Disable Mark as new
Disable Gift card
Disable Downloadable product
Disable Recurring product
Disable Product cost
Disable "Disable buy button"( Disable buy button always Chacked and Hiden)
Disable "Disable wishlist button"
Disable Available for pre-order	
Disable Customer enters price
Disable PAngV (base price) enabled	
Disable Discounts	
Disable Tax exempt	
Disable Tax category	
Disable Telecommunications, broadcasting and electronic services	
Disable Tier prices
Disable Inventory
Disable Shipping
Disable Limited to stores
Disable Vendor
Disable Access control list
Disable Require other products	



Can be out of Admin area, Like Topic Page for Costumers to add Product.

**Comment by tigran-avdalyan** [comment]
we don't need to add access to Admin Area, only need new page For adding products.

**Comment by AndreiMaz** [comment]
Only sellers can add products. Or vendors.

Customers should not be able to do it. At least not out of the box
