### ISSUE TITLE
Email validation. Turkish characters like ş İ ğ ç are accepted. (içŞöĞi@yourstore.com)

### ISSUE THREAD

**Issue by keremdemirer** [nopSolutions/nopCommerce#2263]
Found a problem today looking through logs. Turkish characters like **ş İ ğ** are accepted on most forms, which should not. Email providers not accepting these. I registered to demo store with **içŞöĞi**@yourstore.com. 

Waiting for FluentValidation fix - https://github.com/JeremySkinner/FluentValidation/issues/580. Then sync the updted https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/EmailValidator.cs

see #1628 and #1834.

**Comment by keremdemirer** [comment]
We just received a customer ticket about this issue. When user entered MICHAELL.JACKSON@DOMAIN.COM for shipping address its accepted. While placing the order with same address, CommonHelper throws exception as Email is not valid.

**Comment by AndreiMaz** [comment]
@skoshelev Можешь Иру теперь спросить =))

**Comment by skoshelev** [comment]
We use the same regex as FluentValidation and we don't plan to introduce any changes in order to keep the consistency

Closed #2263
