### ISSUE TITLE
How to choose category or product to display in sitemap.xml

### ISSUE THREAD

**Issue by AlexGeller** [nopSolutions/nopCommerce#2264]
Hi,

I want to choose some categories or products to display in sitemap.xml, there have two reasons to do this, first, when the categories and products become more, the sitemap.xml file is become large, it is waste time to generate it and the search consol file size limited and url count limited. second, there is no way set the priority of categories url or products url in my site that search engine should index them first.

I think there maybe two function to do this. Admin can select which urls of categories or products to show in sitemap.xml, just like Topics, and can set the number of the top urls to display.

Do you think this is reasonable?

Alex

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development. Otherwise, it could be quite complex to configure for most store owners
