### ISSUE TITLE
Fix option filtering in Shipping.FixedOrByWeight and Tax.FixedOrByCountryStateZip plugin

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#2267]
Source: http://www.nopcommerce.com/boards/t/46526/new-ship-by-weight-entries-not-working-with-38.aspx

**Comment by skoshelev** [comment]
Closed #2267 ([https://github.com/nopSolutions/nopCommerce/commit/a70023a453091201a216726d653eccc952c41bbf](https://github.com/nopSolutions/nopCommerce/commit/a70023a453091201a216726d653eccc952c41bbf))
