### ISSUE TITLE
Use JQuery Slideshows for Featured Products, Related Products and Cross Sell

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#227]
I've noticed that when you setup Featured Products, Related Products, and Cross Sells that it just continually lists them down the page. It would be a lot nicer if instead they utilized a jquery slideshow, so that you can add as many products to these lists, but visitors can just scroll through them from left to right. It would like a lot better and would be more friendly to both visitors and administrators 

Source: http://www.nopcommerce.com/boards/t/13683/feature-request-use-jquery-slideshows-for-featured-products-related-products-and-cross-sells.aspx 

Great example - http://www.nopcommerce.com/p/1155/fundamentum-theme.aspx

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
