### ISSUE TITLE
Groups for Manufacturers(in admin area)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2272]
Like we create Group by name Car and put there all car Manufacturers
we create Group by name Mobile Phones and put there all Mobile Phones Manufacturers
and else

**Comment by tigran-avdalyan** [comment]
in Costumer area can be split by Categories

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
