### ISSUE TITLE
Category  Media size -individual 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2273]
let ability to change default media size  for each category

**Comment by AndreiMaz** [comment]
do you mean quality picture for each category? why is it needed? and where will it be placed?

**Comment by tigran-avdalyan** [comment]
![cars](https://cloud.githubusercontent.com/assets/17789934/24332515/de65320e-1258-11e7-8193-2e5a6c7dca9f.PNG)
![cars2](https://cloud.githubusercontent.com/assets/17789934/24332516/de660382-1258-11e7-8a05-ca6037f45a4e.PNG)

**Comment by tigran-avdalyan** [comment]
Now the style is One for all categories(Subcategories of Cars is show 3 categories in 1 line)
but need ability to configure subcategories size in category(in second picture Subcategories of Cars is show 6 categories in 1 line )

**Comment by tigran-avdalyan** [comment]
Now we can change in CSS, but for all categories.
But need to be Configurable for each category.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development. It'll just make configuration too complex for most store owners
