### ISSUE TITLE
Catalog of Products

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2275]
Like we can create Catalogs of Product and set to product his Options
Example : Iphone 7 and set the product Facturary Specifications,Weight , WxHxL , Default Pictures , Default SEO, Manufacturer, and else.
And allow Group of Vendor and Customers to use this Sample.
Vendors needs only select Iphone 7, set price, shipping, payment info.

**Comment by tigran-avdalyan** [comment]
Configurable Catalog Mode
its can be like Product Template for Catalog mode

**Comment by tigran-avdalyan** [comment]
and administrator can set permission for vendor- permission to use Catalog products or/and  permission to create Product

**Comment by tigran-avdalyan** [comment]
Like in Prestoshop - Catalog Mode
in Multi Store Mode  we can set one store as Catalog , other store as Full e-commerce mode

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
