### ISSUE TITLE
Product attribute connect with Specification Attribute

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2280]
Example: We have mobile phone with Product Attribute "Memory" - 32GB or 64GB
And have Specification Attribute "Memory". We need ability to set Multi_Options of Specification Attribute, and each option connect to Product Attribute Option.

when we select 32Gb in specification show 32Gb
when we select 64Gb in specification show 64Gb

**Comment by tigran-avdalyan** [comment]
For example I have Product by Name "Volkswagen Golf 2003 - 2009, 5 поколение / хетчбэк 5-дв."
And the product have many Modifications, and every Modification have Specification like in image
![attributes](https://cloud.githubusercontent.com/assets/17789934/25493661/00fd4dfe-2b88-11e7-9d4a-bc8a53d749d8.PNG)

**Comment by tigran-avdalyan** [comment]
we can add this option in Admin area>>Catalog>>Products>>"Product">>Specification attributes>>Add a new product specification attribute>>Attribute type>>by name "Option Mapped to Product Attribute"
and when we select Attribute type "Option Mapped to Product Attribute" show 2 Dropdown lists of Product Attributes and Values.

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
