### ISSUE TITLE
super slow on azure

### ISSUE THREAD

**Issue by shyandsy** [nopSolutions/nopCommerce#2288]
why its super slow on azure?
containner : app service Web App Standard 1  1.75G memory
database:     sql database standard DTU 20

are there any sugeestion configuration for azure for 1000rpm？？

**Comment by samdubey** [comment]
Hi @shyandsy 
I am running 3 websites on azure, i think speed is reasonably ok
find yourself if they are having good speed

www.CARakeshAgrawal.in
www.AjayAgrawalClasses.com
www.NeerajAroraClasses.com

**Comment by shyandsy** [comment]
hi 

Could you share what u use on azure?

发自我的 iPhone

**Comment by AndreiMaz** [comment]
Duplicate

**Comment by shyandsy** [comment]
@samdubey  
are u seriesly? is that reasonable? ....

**Comment by samdubey** [comment]
Suggest me if you have better options
