### ISSUE TITLE
Check current discounts requirements when a product is removed from the cart

### ISSUE THREAD

**Issue by vfportero** [nopSolutions/nopCommerce#2290]
I'm having an issue with the coupon discounts in v3.90.

If you have a coupon with a product related restriction, you acomplish the requirement and the remove one of the products the `PrepareShoppingCartModel` method fails.

i.e. You have a discount with the requirement of 100€ in the total amount to apply a 10% discount.
In that case you can only add the discount using the coupon when the cart has a total of 100€ or more, this is working well.
But, if you remove one product of your cart decreasing the total bellow 100€ the coupon is not removed and fails here (https://github.com/nopSolutions/nopCommerce/blob/ee977eeb17128a5757f7862ed60751e97aa5ca98/src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs#L823) because `discount` is null.

I've solved this issue removing the discount coupon code of the customer if is not valid but i think that the correct place to do this is in the logic of the removal or update of a cart item.

**Comment by AndreiMaz** [comment]
already fixed. thanks! https://github.com/nopSolutions/nopCommerce/issues/2312
