### ISSUE TITLE
Ability to Add gif image on the main page this will definitely boost sales from clients perspective

### ISSUE THREAD

**Issue by jhonmacaraig** [nopSolutions/nopCommerce#2292]
It would be nice if this can be implemented  nopcommerce 4.0,because it attracts sales,

**Comment by AndreiMaz** [comment]
Please provide mite info. What did? Where will it be displayed?

**Comment by jhonmacaraig** [comment]
I believe it doesn't matter as long as you cater gif images. That would be a great features

**Comment by AlexGeller** [comment]
The nop don't support to upload a gif picture to product. When upload a gif picture, it can save a gif file in server, but the file just leave one frame of gif picture's first frame, all other frames was lost. So please support upload a gif picture to product, this will definitely boost sales from clients perspective.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
