### ISSUE TITLE
Ability to save Order Criteria

### ISSUE THREAD

**Issue by jhonmacaraig** [nopSolutions/nopCommerce#2293]

**Comment by AndreiMaz** [comment]
What criteria do you mean?

**Comment by jhonmacaraig** [comment]
So every time i open the admin order list i always click the order status just to filter my criteria(Pending, Processing)
It would be nice it would have the ability to save my last search criteria.
Please see image below
![image](https://cloud.githubusercontent.com/assets/1201350/24675548/25a68090-19b2-11e7-8e83-d1df2df6be19.png)

**Comment by AndreiMaz** [comment]
duplicated
