### ISSUE TITLE
Facebook plugin doesn't work

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2294]
Source 1: http://www.nopcommerce.com/boards/t/46804/facebook-login-unknown-error.aspx

Source 2: http://www.nopcommerce.com/boards/t/46871/facebook-authentification-unknown-error.aspx

Source 3: http://www.nopcommerce.com/boards/t/46803/facebook-authentication-failed.aspx

**Comment by AlexGeller** [comment]
Hi,

Whether this bug can be fixed preferentially, because it affect the nop production to normally operating.

Thank you.

**Comment by razamemon** [comment]
is this bug fixed?

**Comment by S3ezi** [comment]
Still now working at 4.2
