### ISSUE TITLE
Ability to send email on the on the order list and order details

### ISSUE THREAD

**Issue by jhonmacaraig** [nopSolutions/nopCommerce#2297]
This is request would happen in the Order List and Order Details
On the order , there should be a button to send email , like followup on the orders

![image](https://cloud.githubusercontent.com/assets/1201350/24786053/1b488bda-1b91-11e7-9ef3-0de00348bccd.png)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
