### ISSUE TITLE
"Notify me when available" option for guest users

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#23]
"Notify me when available" option only works if you are locked in as a user. it should be possible to be notified even if you are not a user of the site 

Forum source: http://www.nopcommerce.com/boards/t/18477/notify-me-when-available.aspx
1. Make it configurable - allow a store owner to disable this feature (for guests)
2. We should add some email validation
3. Add CAPTCHA support

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
