### ISSUE TITLE
Grouped Product - Add to Cart button Disable

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2300]
in Grouped Product we have Add to Cart button. But when we click that button, item doesn't adding to cart. 
I think we need to disable that button from Grouped Product. Or change Name and Function
For example : in http://demo.nopcommerce.com/camera-photo Product name:"Nikon D5500 DSLR" Id:13
Product type: Grouped

**Comment by AndreiMaz** [comment]
Right now it's by design. It redirects to the details page

**Comment by tigran-avdalyan** [comment]
i think we need to change Button name or configurable disable it like in sample products.
because costumer click "Add to Cart" and details page- false logic

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It's by design now

**Comment by tigran-avdalyan** [comment]
@AndreiMaz maybe rename it .
for example "Go To Product Page"
