### ISSUE TITLE
Geo-localization of Vendors

### ISSUE THREAD

**Issue by chrjs** [nopSolutions/nopCommerce#2303]
When a Vendor is related a physical place, could be useful to have the possibility to geo-localize the vendor on the map. 
Doing this with plugins is limited to the fact that the model on Vendor cannot be extended. 
Would be nice to have the possibility to add additional fields on Vendor model, or at least add to the Vendor model  latitude/longitude fields.

**Comment by tomakali** [comment]
+1000 for this

Nopcommerce has to evolve online-shop product pages into location aware product pages

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
