### ISSUE TITLE
Implement "3D Bin Packing" algorithm for shipping

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#231]
All of the nopCommerce shipping algorithms have the same problem. They do not work for real world cases with multiple items of various sizes being added to the cart. 

To produce accurate box selection (and shipping estimates) will require implementing "3D Bin Packing" simulation code. Given a set of items of various sizes, and a set of various sized boxes, what is the how many boxes, and of what size, are required? Shipping estimates would then be much more accurate, as the box selection would simulate the actual packing of boxes. 

Useful links:
http://en.wikipedia.org/wiki/Packing_problem
http://en.wikipedia.org/wiki/Bin_packing_problem
http://www.nopcommerce.com/boards/t/9414/bugs-in-shipping-rate-calculation-important.aspx?p=2
http://www.nopcommerce.com/boards/t/17719/bug-in-shipping-size-calculation.aspx
etc (search forums)

Have a look at the following contributions:
https://hg01.codeplex.com/forks/grene/shippingimprovements
https://hg.codeplex.com/forks/grene/packedboxes

[AM] The upcoming version 2.70 already has cube root method of calculating dimensions. That's enough for now. Anyway it's much more accurate than the previous method.

**Comment by keremdemirer** [comment]
I created a repo does the 3d packing stuff in javascript. It needs the box sizes as input to do calculations. I'm posting this because its hard find this algorithm in a c# similar language, can be useful.

https://github.com/keremdemirer/3dbinpackingjs

**Comment by sumo300** [comment]
There are a few services now that offer APIs for this type of packing solution.  Sounds like a plug-in is needed!

https://www.3dbinpacking.com/products/fillContainer

**Comment by AndreiMaz** [comment]
almost not possible to implement
