### ISSUE TITLE
PayPal Standard plugin doesn't work when billing address is disabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2310]
Source: http://www.nopcommerce.com/boards/t/47030/issue-with-paypal-standard-plugin.aspx

**Comment by sailenk** [comment]
any updates on this Andrei. Any fix/patches?

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/20ebb2d443476b56b54e0c55187f36082e3aa2e8

**Comment by sailenk** [comment]
Is this applicable to 3.50 as well?
