### ISSUE TITLE
Product import. Categories by name

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2314]
When we have 2 categories by name "Cat1" and "Cat2", and "Cat1" have subcategory by name "Sub1" and "Sub2". And "Cat2" have subcategory by name "Sub1" and "Sub2".

When We import the product and write in Categoty column "Sub1"  the system don't new in what category import "Cat1">>"Sub1" or "Cat2">>"Sub1", and system choose first.
but need to set a logic.

also see https://www.nopcommerce.com/boards/t/48011/admin-bulk-insert-bugflaw.aspx

**Comment by tigran-avdalyan** [comment]
for example we can in excel file write full name of category like- "Cat2>>Sub1"

**Comment by tigran-avdalyan** [comment]
Or in Excel file Categories Column can be selectable by dropdown list, and have 2 values "CategoriesName" and "CategoriesId" .
if selected CategoriesName then import by name
if selected CategoriesId then import by id

**Comment by Lecher7** [comment]
If all records in the Excel file were uploaded by CategoryID instead of CategoryName, I think that would solve this problem.

**Comment by skoshelev** [comment]
Closed #2314
