### ISSUE TITLE
SQL Server Comcpact. Category products not always listed in defined Display Order

### ISSUE THREAD

**Issue by MarkSizer** [nopSolutions/nopCommerce#2315]
I have a client who has been setting the DisplayOrder of Products listed in a Category. However the results are inconsistent. I believe that the problem occurs when a Product is listed in more than one Category.

Looking at the below code, it appears to pick category zero from the list and not necessarily the current category.

Version: 3.90
Class: Nop.Services.Catalog.ProductService
Method: SearchProducts
Lines: 963 to 968
```
if (orderBy == ProductSortingEnum.Position && categoryIds != null && categoryIds.Any())
{
    //category position
    var firstCategoryId = categoryIds[0];
    query = query.OrderBy(p => p.ProductCategories.FirstOrDefault(pc => pc.CategoryId == firstCategoryId).DisplayOrder);
}
```

**Comment by AndreiMaz** [comment]
That's right. It's done so only in SQL Server Compact (not recommended for live sites). It works fine with full SQL Server version

**Comment by MarkSizer** [comment]
I'm experiencing this behaviour on an Azure hosted DB SQL Server (v12.0.2000.8) with 5 DTUs.

Because the Azure Portal website provides a layer of abstraction from the DB, I don't honestly know if it's  Compact, Express, Standard or Enterprise.  I had assumed it would be compatible / fully supported though.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. as per my comment above
