### ISSUE TITLE
SendOrderPlacedStoreOwnerNotification used an error logic.

### ISSUE THREAD

**Issue by AlexGeller** [nopSolutions/nopCommerce#2316]
Hi,

SendOrderPlacedStoreOwnerNotification function is used to send an order placed notification to a store owner, but It is autually use a stmp to send a emal to itself after I check the code and get the following error.

System.Net.Mail.SmtpException: Failure sending mail. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. -

So I think a store should have a email account to receive notification just like vendor and send email to this account, not smtp account.

SendOrderPlacedStoreOwnerNotification should have same logic like SendOrderPlacedVendorNotification function.

Thank you.

**Comment by AndreiMaz** [comment]
please post all support questions on our forums
