### ISSUE TITLE
Storing thumbnails in Azure blob - multiple issues

### ISSUE THREAD

**Issue by pdunleavy** [nopSolutions/nopCommerce#2317]
I have run a few nop sites on Azure over the last few years and my major issue with performance and scalability is with pictures... We know that storing pictures in the database is a bad option (bandwidth killer, expensive storage). Storing them on the web server is not great either (storage constraints, backups, load on web server, scaling out). So blob storage is the way to go, however...

1. The AzurePictureService needs to be async, looking up and editing blobs is sloooowwww! e.g. a category page can take a couple seconds in server response time just to check if the thumbnails exist. With async it's a few milliseconds using await and WhenAll(). Async will need to be applied all the way up the chain to the controllers. In the .NET core version of the SDK the none async version has been dropped which tells you how bad it is.

2. Because thumbnails are generated on the fly by ImageResizer (with poor compression) there is a further performance hit pulling the image out of blob, generating the thumbs and putting back. In the meantime your customer has bounced to some other site that will load this year. Again, async would help a lot. 

As an aside, another option would be to allow image compression and thumbnail generation to be handed off to a plugin and generated before the product is published. This would remove the need for all the on the fly lookups and generation.
I have developed a tinyPNG plugin for this purpose but the pictureservice interface doesn't have any public methods to affect the thumbs as it is all hard-coded around ImageResizer. We also have a plugin that send images via schedule to a third party to be photoshopped and interface would help here.

**Comment by pdunleavy** [comment]
Please post a link this site that is running nop as an Azure web app and storing pictures in SQL Azure, would love to see what the performance is like.

**Comment by kingmotley** [comment]
Sorry, that site wasn't actually running nop, just using imageresizer.  That version also isn't currently in production, as it was recently replaced, but it was running for years with GREAT performance.  It was an ASP.NET MVC web application running on a physical webserver, remotely accessing most images from an Azure database through imageresizer.  Development/QA/UAT of that code was run as an Azure Website with similar performance.

It was using the following plug-ins: a custom SqlReader plug-in, the DiskCache plug-in, the virtual folder plug-in, the Default Settings plug-in, and the Client Cache plug-in.

Sorry for the confusion.

**Comment by pdunleavy** [comment]
I've been working with Azure tech support on this and from looking at storage diagnostics logs you can be waiting 33MS for one call to Exists(), x100 images on a page and you have a big problem. Microsoft don't seem to make any claims about SLA on server response time for the API, only availability. I also discovered by default the function uses an exponential retry policy where if the call fails it will try again on a sliding scale of time. https://blogs.msdn.microsoft.com/windowsazurestorage/2011/02/02/overview-of-retry-policies-in-the-windows-azure-storage-client-library/

 I have set the retry policy to NoRetry(), the worse thing to happen would be a place holder for the image if it happens the first time someone requested it.

**Comment by kingmotley** [comment]
Yes, that is a problem with the SqlReader as well.  That's why I wrote a custom implementation for it that reduced the number of Exists() calls and we removed the calls checking to see the last update DateTime (since we never allow images to be updated those calls were unnecessary).

I'm sure if you contacted the author of ImageResizer he could make the modifications for you that would be similar to the ones we made.  For sources that aren't local (remote databases and cloud storage) the performance difference is pretty large.  Or maybe the latest versions already do this, I'm not sure, we used an older version of the engine before the licensing changed.

**Comment by pdunleavy** [comment]
I have put a temporary solution in place and the site is now 'lightning fast'. In the GeneratedThumbExists function I am caching the result of the Exists() call in static cache. The server response time is now well under 1 second and the whole site is much more responsive.

**Comment by kingmotley** [comment]
Glad to hear it.  I'm not sure why that isn't a default option, but the performance difference as you can see is well worth it.
