### ISSUE TITLE
Split "big import file". Automaticaly and then import part by part

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2320]
When we import the big data, automaticaly split the data to Multi part data, and then import part by part.
When in importing process time connection lose , then set to Pause mode for sample time , then if connection is comming back , continue importing .

**Comment by clearbucketLabs** [comment]
Technically, you save the file to disk and read it paged, no need to split the file regardless.  Currently it just goes into memory directly i think.   The import should be done into a separate  background process/queue.

**Comment by skoshelev** [comment]
Closed #2320
