### ISSUE TITLE
Scheduled tasks - need cancel, pause, resume

### ISSUE THREAD

**Issue by pdunleavy** [nopSolutions/nopCommerce#2323]
We have a heavy weight scheduled task for importing products from other sites. If this ends up running for a long time or effects performance of the site there is no way to stop it without restarting the site. It would also be a nice feature to have an icons showing which schedules / threads are currently running rather than work it out from the date times. (an async execute would also be great ;) )

**Comment by ivanslater** [comment]
We need to have more control on it, disabling or enabling a task will take effect only after a POOL refresh. We simply can´t do it on stores with large visitors online.

**Comment by a-patel** [comment]
I think, there is one third party library called [Hangfire](https://github.com/HangfireIO/Hangfire) that perform background job processing in easy way with all kind of facilities (e.g. Remove, Pause, Start, Stop).

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization Because it's already possible to disable any task
