### ISSUE TITLE
Extend PictureService and AzurePictureService with CDN

### ISSUE THREAD

**Issue by pdunleavy** [nopSolutions/nopCommerce#2324]
This is a pretty straight forward code hack I've made myself but would be nice to include. Add a setting for the CDN endpoint, if set swap out the url in the getthumburl() methods. Azure thumbs can already be served from blob but blob storage has no sla, much better to use CDN particularly if your site is international.

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/1299
