### ISSUE TITLE
Add Code Editor

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2326]
Edit Nopcommerce files directly in Nopcommerce Admin area.

**Comment by Xzelsius** [comment]
And how do you handle permissions here?

Let's say user with role XY has no access to products, but can edit views in admin area. How to prevent him using EngineContext to get product service or even product repository and doing bad things?

This could and would be a huge security issue!

**Comment by tigran-avdalyan** [comment]
only Administrator(root user) have permission to edit Nopcommerce source files.

**Comment by Xzelsius** [comment]
Well then the problem still exists.
What if a administrator (root user) has restricted access to some parts of nopcommerce?

You aren't forced to give the administrator role all rights.
Sure in this case it would be better to create a new role with restricted access.

**Comment by tigran-avdalyan** [comment]
@Xzelsius Here the hierarchical structure of rights.
"What if a administrator (root user) has restricted access to some parts of nopcommerce?"- this is situation(human factor)

**Comment by AndreiMaz** [comment]
I agree with @Xzelsius . We should not do it out of the box. But the idea is not bad
