### ISSUE TITLE
Add Gallery support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2327]
Add Gallery. Where we can see,filter,edit,add,remove,rename all images of products.

**Comment by Xzelsius** [comment]
You already have a list of images on the product edit page. So what's the advantage of this?

**Comment by tigran-avdalyan** [comment]
@Xzelsius  Add many images in one upload process, use one picture in many products(not upload each time, use uploaded image for many products), ability to have place where you save original images, sample edit functions for images.

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/252
