### ISSUE TITLE
Make methods in the Nop.Web Controller classes somehow callable or extendable from third party extensions

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#233]
Use model factories -  http://www.nopcommerce.com/boards/t/43660/potential-improvement-to-productcontroller-and-its-method-prepareproductdetailspagemodel.aspx (do not forget to add "protected virtual OnCreate" methods)

Forum sources: http://www.nopcommerce.com/boards/t/14398/development-suggestion-make-preparemodel-private-methods-in-the-nopweb-controller-classes-protected-or-somehow-callable-from-thridy-party-extensions.aspx 

also see http://www.nopcommerce.com/boards/t/27964/overriding-the-controllers.aspx 

also see http://www.nopcommerce.com/boards/t/28016/mark-the-nop-controllers-methods-as-virtual.aspx 

also see http://www.nopcommerce.com/boards/t/33275/extract-some-logic-for-better-extensibility-of-the-checkout-process.aspx 

also see http://www.nopcommerce.com/boards/t/34354/access-preparecustomerinfomodel-method-in-customercontrollercs-from-plugin-controller.aspx

let's discuss how exactly

**Comment by dotcontrol** [comment]
any news on this?
