### ISSUE TITLE
Add ability to sale by volume, weight 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2332]
for example ability to sale "apples" - price is 5$/kg
for example sale "apple juice" - price is 10$/liter

**Comment by eadameg** [comment]
this workitem already exists: [https://github.com/nopSolutions/nopCommerce/issues/18](https://github.com/nopSolutions/nopCommerce/issues/18)

**Comment by tigran-avdalyan** [comment]
For example I sale tomatoes  by PandV , and set price 10$ for 1 kg. And costumer want to by 0.3 kg, 0.5 kg or 1.5 kg .How he can do it???? 
We need ability to sale not only with quantity, but with weight and volume.

**Comment by a3406007** [comment]
We would like to sell by surface area from a roll. For example, we have a 1.5m wide roll of cloth and would like the customer to specify a length from the roll, so the amount sold is a decimal value of metres squared (m<sup>2</sup>) (width * length). So if the customer wants a length of 1.2m the quantity sold is 1.8m<sup>2</sup> (1.5 * 1.2).
The calculation is not a problem, but every bit of code and even the columns in the database which deal with order/stock quantities are all integers. This problem could be solved or greatly eased by changing to decimal data types.
We just need the customer to be able to specify - and therefore for stock to be managed in - decimal quantities.
Please, please consider this for the next release!

**Comment by tigran-avdalyan** [comment]
Please see #2615 and #2614 and #2550

**Comment by AndreiMaz** [comment]
We decided to implement only https://github.com/nopSolutions/nopCommerce/issues/2614
