### ISSUE TITLE
Store Link on RSS Pages Always HTTP Even if Site is SSL Only

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2335]
f you visit the newproducts (and other pages) RSS page on an forced SSL site with a valid certificate, the store link at the top is not encrypted (http). This causes an unnecessary redirect to (https) when clicked. Test is on your own store and see. Use IE so the link renders.

Source: http://www.nopcommerce.com/boards/t/47224/store-link-on-rss-page-always-http-even-if-site-is-ssl-only.aspx

**Comment by skoshelev** [comment]
Closed #2335
