### ISSUE TITLE
Add EntityInserting<> EntityDeleting<> EntityUpdating<> events

### ISSUE THREAD

**Issue by pdunleavy** [nopSolutions/nopCommerce#2337]
The existing events are fine If you want to trap some change that has already committed and do something but if you want to effect the state of the entity before it is committed to the database there is no way. You would have to perform an additional update. This would also allow for accessing the objectstate manager to see which properties have actually changed and if we are interested (e.g. price change)

**Comment by a-patel** [comment]
there is one third party library called '[MediatR](https://github.com/jbogard/MediatR)'. I think it handles the even/notification kind of thing.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
