### ISSUE TITLE
Product image change doesn't work with multiple product attributes with associated pictures

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2339]
Source: http://www.nopcommerce.com/boards/t/47231/product-image-change-with-conditional-product-attribute-selection.aspx

**Comment by tigran-avdalyan** [comment]
its good function
its like https://github.com/nopSolutions/nopCommerce/issues/2280

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/290
