### ISSUE TITLE
Add View product link in Edit Product details page

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#2346]
I think this is helpul for store owner.

**Comment by AndreiMaz** [comment]
thanks. but we already have the "preview" button

**Comment by ngtrian** [comment]
Seem some product don't show preview button!

**Comment by AndreiMaz** [comment]
shown for all (existing ones)

**Comment by ngtrian** [comment]
I do not know what is going on, seems to have an error

![image](https://cloud.githubusercontent.com/assets/4327817/25928089/717477be-3624-11e7-888d-268af1eeeaa4.png)

**Comment by ngtrian** [comment]
This issuse should open for disscusion

**Comment by AndreiMaz** [comment]
please provide a complete list of steps to reproduce
