### ISSUE TITLE
Admin area. Disable autocomplete

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2349]
We should disable autocomplete for admin area forms:

Source: http://www.nopcommerce.com/boards/t/47207/add-customer-form-auto-fill-populating-inputs-with-my-email-and-password.aspx#187740

Check whether we can use use the 'autocomplete' attribute on your form element - http://stackoverflow.com/questions/582244/is-there-a-w3c-valid-way-to-disable-autocomplete-in-a-html-form

Maybe we should make in configurable (and enabled by default)

**Comment by f1ana** [comment]
Autocomplete is really weird in that there isn't a good uniform behavior across browsers:
https://caniuse.com/#search=autocomplete

I've had luck in the past disabling autocomplete by passing something clearly invalid to the autocomplete attribute (e.g.  autocomplete="nope").

**Comment by LindenSims** [comment]
This is still a problem for me in 4.5.3. I have tried adding autocomplete attribute to no avail.
