### ISSUE TITLE
Reintroduce ability to ban an IP (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#235]
Forum source: http://www.nopcommerce.com/boards/t/22878/suggestion-reintroduce-ability-to-ban-an-ip.aspx 

Plugin - http://www.nopcommerce.com/p/1316/banned-ip-address-blacklist.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
