### ISSUE TITLE
Daylight saving time issue

### ISSUE THREAD

**Issue by ivanslater** [nopSolutions/nopCommerce#2351]
Since firsts nop version, daylight saving time cause issues on admin dashboard.
Once there is dates with 23:00 hours or less, order report crashes trying to get all orders for that date.

You can test it trying to set a date using a time that doenst not exists on that day, 00:30 for example if you need to forward the clock to 1AM on that day.

https://en.wikipedia.org/wiki/Daylight_saving_time

**Comment by AndreiMaz** [comment]
could you please send the entire error stack trace? from log

**Comment by ivanslater** [comment]
Andrei, there is no log, but you can replicate it easly, just change the time of your server to a day when dayligh saving time starts (the day where 00:00 doesnt exists), where clocks need to be forwarded from 11:59PM to 01:00 AM. So you will see dashboard order reports empty for that day.

**Comment by AndreiMaz** [comment]
@ivanslater what version are you using?

**Comment by ivanslater** [comment]
@AndreiMaz 3.7, but it happens since 1.9 when I started to use nop!

**Comment by AndreiMaz** [comment]
@ivanslater please try 3.90. this method was refactored in latest versions

**Comment by ivanslater** [comment]
@AndreiMaz the method was refactored but the code was reviewed? You can use 00:00 for start date selecion where date hasnt 00:00 clock time on that specific daylight time, for example.

**Comment by jaySolo** [comment]
The fastest fix I can think for that is having the dates stored as UTC (which is unaffected by DST if I remember correctly), but that may affect performance since the time will have to be converted multiple times for read/write operations.

Of course that's assuming that it wasn't fixed by version 3.9.

**Comment by AndreiMaz** [comment]
@jaySolo thanks. but all dates are already stored in UTC

we'll check it soon

**Comment by skoshelev** [comment]
Hi all. I try to reproduce this issue, but I can't. Can you add more details: what time zone, date, time do you use, something else?

**Comment by ivanslater** [comment]
Yes, I can. 10/15 will start daylight saving time in Brazil. You can set your regional settings to SAO PAULO (-3) timezone and check nop dashboard report. This day, (10/15) starts at 1AM time. In windows time, it hasnt 00:00AM time, the clock jumps from 23:59:59 to 01:00:00, so when you try to get orders report from 00:00 it crashes and dont display anything.
