### ISSUE TITLE
Inbuilt flyout windows for wishlist and login/logout/register.

### ISSUE THREAD

**Issue by BeardLantern** [nopSolutions/nopCommerce#2353]
Speaks for itself. Inbuilt extension for flyout option for the wishlist and login/logout/register, in addition to already existing mini-shopping-cart.

**Comment by pdunleavy** [comment]
Agree, customer should be able to register and carry on browsing without disturbing the flow. Relates to #2342

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/12
