### ISSUE TITLE
Canada post. Add instructions on how to get API keys

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2358]
Recommendation of introducing the merchant registration via the Canada Post API which automate the exchange of sensitive information between Canada Post and the solution , currently the end user must copy/paste the credential and there are no instruction where to go to access these API keys.
Please see screenshot#1. It is strongly suggested to incorporate the registration API. It is one of the important item that Canada Post look for when introducing a partner to the partner list on the Canada Post site.
 
 
Reference:  https://www.canadapost.ca/cpo/mc/business/productsservices/developers/services/ecomplatforms/default.jsf
 
 
Demo: http://www.screencast.com/t/PVsbve5O
 
![1](https://cloud.githubusercontent.com/assets/5019111/26296884/4aece488-3ed9-11e7-8106-778b57769a5b.jpg)

**Comment by AndreiMaz** [comment]
@RomanovM перенеси в новый репозиторий для canada post и создай задачу в trello

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/CanadaPost-plugin-for-nopcommerce/issues/1
