### ISSUE TITLE
Registration during checkout

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#236]
As we all know the checkout process should be optimized for conversion. 

One thing I noticed: 

Visit website as anonymous user 
add item to cart 
click checkout 
click register 
fill out registration form 
registration confirmation message is shown 
now user has to click checkout again. 

wouldn't it be better if user clicked register from checkout page, user is returned to checkout page after succesful registration? 

also see http://www.nopcommerce.com/boards/t/28102/feature-request-check-out-as-guest-option-to-create-an-account-at-end.aspx

also see https://www.nopcommerce.com/boards/t/48894/reduce-abandoned-shopping-carts.aspx (Skip the “Check out as guest or register” page and go directly to the checkout page.)

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
