### ISSUE TITLE
Allow to preview blog posts, news, topics

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2364]
It would be nice to be able to see the preview of the articles that are on the verge of being published. 
Indeed that will help the marketers/community managers checking their blog posts before publishing it. 
Let me know your feedbacks, 

Source: http://www.nopcommerce.com/boards/t/47436/add-a-preview-feature-in-the-blog-section.aspx

Ensure that administrators can access them even when unpublished (like it's done for categories, etc)

**Comment by DmitriyKulagin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow to preview blog posts, news, topics](https://trello.com/c/zjm4A99L/1049-allow-to-preview-blog-posts-news-topics)

**Comment by DmitriyKulagin** [comment]
closed #2364
