### ISSUE TITLE
Add support for PayPal Advanced in addition to the Standard and Pro.

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#237]
I would love the see PayPal Advanced supported in Nopcommerce. Currently Nopcommerce supports PayPal Pro and PayPal Standard. 

The great thing about PayPal Advanced is that it allows people to pay without leaving your website like the PayPal Pro plan, but it is only a fraction of the cost. It is only $5 dollars a month instead of $30 a month. 

It works as an Iframe, allowing PayPal to keep it secure. 

You can learn more at: 

https://www.paypal.com/webapps/mpp/paypal-payments-advanced 

For many small retailers or startup companies PayPal Advanced offers the benefit of being inexpensive but still allowing customers to check out without leaving their website. 

I have found that with Paypal Standard some customers get confused or don’t make the payment when they are re-directed to Paypal. But at the same time the PayPal Pro is a bit steep.

I am sure that support for PayPal Advanced would greatly benefit many nopcommerce users. 

source 
http://www.nopcommerce.com/boards/t/19535/suggestion-add-support-for-paypal-advanced-in-addition-to-the-standard-and-pro.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
