### ISSUE TITLE
Custom invoice numbers passed to gateways

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2373]
I specified a custom order number mask and a custom return number mask.
ORDER:
MM-{YY}{MM}{DD}-{ID}

RETURN:
MM-{YY}{MM}{DD}-{ID}-R

However hen I look in PayPal, I only see the {ID} and not the mask I specified.

Here is what our system shows...
MM-170523-13301

Here is what PayPal shows...
13301

Allowing us to make custom masks is helpful in making things easy to track and read.
So why we are ignoring that with 3rd party vendors, like PayPal? Just ensure that all IPN and other usage will also work fine

Source: http://www.nopcommerce.com/boards/t/33848/invoice-number.aspx

**Comment by RomanovM** [comment]
Now in all our out-of-the-box payment plugins we use the order guid or the order custom number
