### ISSUE TITLE
Add AJAX support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2376]
Products in Categories --  Sort by AJAX support
Products in Categories --  Display AJAX support
Products in Categories --  Filter by price AJAX support
Products in Categories --  Filter by attributes AJAX support

**Comment by tigran-avdalyan** [comment]
Example: https://isotope.metafizzy.co/

**Comment by KenXu41** [comment]
it looks so cool of your AJAX support ```

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/276
