### ISSUE TITLE
Product image url changed under load balancing

### ISSUE THREAD

**Issue by OverwindSlash** [nopSolutions/nopCommerce#2377]
**The problem**
Two IIS host two Nop instances behind Nginx.
Each instance run properly when direct access situation.
When access through Nginx, url of product image has been changed from
src="http://**192.168.100.1**/content/images/thumbs/0000059_custom-t-shirt_415.jpeg
to
src="http://**mysvr**/content/images/thumbs/0000059_custom-t-shirt_415.jpeg

this change causes browser report ERR_NAME_NOT_RESOLVED error. 
mysvr is upstream name defined in nginx.conf.

**The Question**
This url modification was done by Nop or Nginx?
If it was done by Nop, how to prevent this behavior?

Thanks a lot!

**Comment by OverwindSlash** [comment]
Found a way to solve this problem， but I think it is not the best way.
In location section of nginx.conf, add below directive:
**proxy_set_header   Host             $host:$server_port;**

Still don't know why this url change happened.

**Comment by carlomz** [comment]
I have the same issue under an AWS ELB. The site logo image does not show. From developer tools I see the image has the internal IP of my EC2 instance
