### ISSUE TITLE
"Request a Quote" Form (available as plugins)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#238]
Customer adds in the cart all items he wants to quote; in the cart there is a button "Get a Quote" which sends an e-mail to customer/store owner with some additional text (such as "this is a quote valid until .....") plus most of the fields including in a normal request. 

This should also work if catalog mode is enabled. 

References: 
http://www.nopcommerce.com/boards/t/5891/adding-request-a-quote-form-in-nopcommerce-project.aspx 
http://www.nopcommerce.com/boards/t/7412/request-quote-form-for-180.aspx 
http://www.nopcommerce.com/boards/t/5909/request-a-quote-form-for-nopcommerce-project.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
