### ISSUE TITLE
Google AMP support

### ISSUE THREAD

**Issue by tomakali** [nopSolutions/nopCommerce#2381]
Google AMP support is missing in Nopcommerce

**Comment by AndreiMaz** [comment]
what is AMP? could you please clarify?

**Comment by tomakali** [comment]
Google AMP is [Accelerated Mobile Pages]

http://searchengineland.com/library/google/google-amp-project
https://www.ampproject.org/


as most of the traffic is shifting from desktop web to mobile web for consumption
its is very critical that the pages and templating engine is optimized for mobile web

**Comment by ivanslater** [comment]
A lot of ecommerce systems are upgrating to allow AMP compatibility. There is pretty nice AMP stores. I see it as a new plugin, but nop could add it to the core. 

You can take a look at ebay, for example.

**Comment by tomakali** [comment]
I will also want to have Xamarin Build of NopCommerce
With Xamarin Build its already optimized for mobile apps and webapp

**Comment by bradranks** [comment]
I can't find any plugins that create AMP pages with the existing content. Can you post a link. I am either going to try a plugin or custom code something. AMP pages are a huge push and I really need to get them implemented to stay ahead of the competition right now. 

Any help is GREATLY appreciated.

**Comment by ivanslater** [comment]
@bradranks there is no such plugin yet.

**Comment by tomakali** [comment]
umbraco has it http://carolelogan.net/blog/amp-implementation-in-umbraco/
nocommerce should have it too.
but IMO,
its time that nopcommerce move out of Entity Framework to dapper with built in AMP support

**Comment by bradranks** [comment]
(IMO) The need for AMP in the project is just as significant as having the ability to have static URLs instead of Dynamic, having the proper tags, and having markup. It is a new layer of SEO that is here to stay and more popular than old RSS feeds. It supports the Mobile First premise and will most definitely be an integral part of exposure, growth and speed initiatives.

If you think of it this way: Old Black hat SEO used doorway and gateway pages. With AMP, Google basically green-lighted doorway and gateway pages, as long as the format is valid.

**Comment by bradranks** [comment]
I just wanted to add an update:

We have put together a few websites now that are replacing native mobile apps. The same functionality now works in the browser (now that apple conceded on WebRTC) and we can simply bypass the app stores and just use a responsive site for everything. No more headaches with devices, resolution, compatibility, etc... Just webpages! and more importantly, AMP pages that are extremely fast and user friendly.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

**Comment by Ajajturkey** [comment]
I wrote a new plugin that Create you a new AMP version from your website,
Very powerful SEO tool, tested result start to show up on google first page after paid search,
Its available at 3.7 3.8 3.9 4.0

Demo can run on localhost. 

https://nop-marketplace.com/en/nop-accelerated-mobile-pages

its works on standard and create both canonical links between original and amp version

**Comment by bradranks** [comment]
Nice Job AJAJ!

I will try and be one of the first to test. Do you have it up and running on any live sites that I can see it on? I want to crawl the site and look at it from a hierarchical perspective as well as SEO perspective.

**Comment by Ajajturkey** [comment]
Thanks, 
here one of my clients
https://www.modamiz.com/
and the amp version https://www.modamiz.com/amp
I provide the amp project with category side navigator so that user can test all site from home > to Category > to product page. 
you can contact me at my website and I will provide you with requested demo version

**Comment by Ajajturkey** [comment]
I have delete last comment as request from the customer, here the alternative link
https://nop-marketplace.com/amp/plugins

Implemented features
1- fully valid pages all pages tested by google amp test
2- all dynamic data, your website in Google and SEO frindlly version
3- Result can be tracked from Google Search Console
4- paged are linked using amphtml tag and cononical tag (https://www.ampproject.org/docs/tutorials/create/prepare_for_discovery)
5- result appears first on mobile search. as google promise
6- allow you to customize home page (add slider and content sections)

https://youtu.be/F9Q4O7qHNgE

-------------------------
later next version,
1- Enable blogs amp
2- Enable google analytics for amp pages,

**Comment by bradranks** [comment]
That is actually very funny.

You built a plugin that enhances their SEO and exposure and you give them an inbound link that has additional SEO benefit, and they asked that you remove it?

"The customer is always right"  ;)

**Comment by Ajajturkey** [comment]
Yeah, they afraid of their competitors, the start to get more result on google search, 
they are right :), 
who now more get more.
