### ISSUE TITLE
Entity Framework vs ADO.net vs Dapper.net

### ISSUE THREAD

**Issue by tomakali** [nopSolutions/nopCommerce#2382]
As of now EF is lagging behind in terms of performance
https://www.exceptionnotfound.net/dapper-vs-entity-framework-vs-ado-net-performance-benchmarking/

https://dontpaniclabs.com/blog/post/2014/05/01/speed-comparison-dapper-vs-entity-framework/

will there be focus on speed on auto scale configurations?

**Comment by patelsagu** [comment]
Entity Framework is slower than either ADO.NET or Dapper.NET

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/239
