### ISSUE TITLE
Export/import products. Support multiple warehouses

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2384]
I have 3 warehouses in my NopCommerce shop. The quantity of each product differs in each warehouse.
When I export the products, some of the products shows warehouse 1 quantities, while the others show warehouse 2 quantities.
It does not export each warehouse quantity separately.
I need this feature to later import products by Excel worksheet.

Source: http://www.nopcommerce.com/boards/t/47595/warehouse-stock-quantity.aspx

**Comment by brprigge** [comment]
Working on a shop that would also need this.

**Comment by ecommerce-tester** [comment]
https://www.codeproject.com/Articles/1194712/Advanced-Excels-With-EPPlus

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
