### ISSUE TITLE
Allow a store owner to configure rules for registration fields

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2394]
For example, are special chars allowed in names? Phone number validation rules? Etc

Source: http://www.nopcommerce.com/boards/t/47691/regsitration-bug.aspx

**Comment by tigran-avdalyan** [comment]
We can add Front-end validation with HTML and Back-end  validation in Server side.

**Comment by AndreiMaz** [comment]
Duplicated
