### ISSUE TITLE
Price Chart

### ISSUE THREAD

**Issue by Arashz22** [nopSolutions/nopCommerce#2395]
Hello dear developers
Please add a feature to show price history chart like the pictures which I had attached.
In my book [HighCharts ](https://www.highcharts.com/) is the best choice because it is more consist with bootstrap.
and  [HighCharts ](https://www.highcharts.com/demo/line-basic) is the demo page

![untitled](https://user-images.githubusercontent.com/10775073/27216324-7ed05efa-528a-11e7-8594-9ae25a80482a.png)
![w](https://user-images.githubusercontent.com/10775073/27216323-7ecf0d8e-528a-11e7-84cf-bf5c0112159e.PNG)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

**Comment by AndreiMaz** [comment]
I think it could achieved now  by our the following plugin https://www.nopcommerce.com/en/omnibus-directive (it saves price history) with minor changes
