### ISSUE TITLE
Home page topic causes duplicated content issue from search engine

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2396]
I got bad news from the search engines.  The pages http://Yourstore.YY/ and http://Yourstore.YY/homepagetext have the same (DUPLICATE) content. And as a result, the pages are removed(DELETE) from indexing. Could someone tell ... am I missing something?  ... and what to do? Any thoughts... really need help.

Source: http://www.nopcommerce.com/boards/t/47702/bad-news-from-the-search-engines.aspx

The same could be told about other topics (e.g. login, contactus). Let's add a new property to a topic indicating whether it could be open or should be "nested" (redirected to other page) -  "Is nested". Description (hint): "When enabled, this topic cannot be open as a separate page. It can be only nested to some other page". Place it after "Include in sitemap" checkbox. And then only move "Accessible when store closed" after this new field.

If a topic page is open with this checkbox enabled, then redirect to a home page.

By default, enable it (in installation service) for CheckoutAsGuestOrRegister, ContactUs, ForumWelcomeMessage, HomePageText, LoginRegistrationInfo, ApplyVendor

**Comment by seanrockster** [comment]
You must the canonical url tag:

https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps
