### ISSUE TITLE
Image cropping (picture editing)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#240]
So what we find with some of our clients is that they are not very graphic literate or at least do not remember what aspect ratio images they are supposed to upload to maintain a consistent design. 

e.g. they are told to only upload square images yet will upload all aspect ratios. 

It would be nice if instead of nop just creating scaled images they could be cropped to the required aspect ratio and then scaled to the required size. 

This would require aspect ratios to be stored for each image type(ProductThumb , tho I suspect most designs will have the same ratio through out and a setting for each to determine if they should be cropped. 

How cropping should work;-
1. Width crop - the crop area should be centered with the edges of the image discarded equally
2. Height crop - crop should probably be taken from the top of the image as most portrait photos will have the interesting bit at the top. However maybe a setting to switch between this and center cropping?

This behavior is somewhat consistent with Facebooks behavior in that while FB allows uploading of all aspect ratios most images are previewed as a square. 

Forum source: http://www.nopcommerce.com/boards/t/19999/image-cropping.aspx

Forum source: http://www.nopcommerce.com/boards/t/16542/feature-request-provide-ability-to-crop-avatar-using-jcrop.aspx

Forum source: http://www.nopcommerce.com/boards/t/47495/customer-photo-editing-tool.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
