### ISSUE TITLE
version 4.0 - is it close to be a product?

### ISSUE THREAD

**Issue by JoseMarcenaro** [nopSolutions/nopCommerce#2405]
Hi Andrei.  Congrats for this great product.
We are considering Nop for a client project that starts now and may go live in three months or so..

The safe path would be to start with the stable v3.90 ... but being developers ourselves, and noticing that the next v4.0 has been ported to ASP.NET Core, we are tempted to start playing around with it while we wait for the next release.

Without committing to any date, would you say that version 4 is more or less close to a first release? Or it is expected to be a kind of beta for several months yet?

Thanks a lot,
Jose

**Comment by AndreiMaz** [comment]
we plan to release in October-November (with beta a month prior). not recommended to use in production until that moment

P.S. Could you please post all questions on our forums. GitHub is for features/issues only

**Comment by stephdep** [comment]
> P.S. Could you please post all questions on our forums. GitHub is for features/issues only
It seems this the only place you really get answers
