### ISSUE TITLE
Change Price when changing primary currency

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2408]
i have product with  price 150 Us Dollar, and Primary Currency sets to US Dollar, in Russian Ruble price is 8800 Rub.
When i change primary Currency to Russian Ruble, in product page it still show 150 Rub.
System change currency but don't change converted price.

**Comment by AndreiMaz** [comment]
It works just fine. I cannot reproduce it. I presume something wasn't configured properly (e.g. exchange rate). Please try to debug CurrencyService ir order to see why it's converted this way in your case (most probably is exchage rate set to 1)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz  i have product, Price 500 USD
i have 2 currency USD and AMD, USD is prinery
USD rate 1 AMD rate is 486

Then i change USD rate to 1/486=0.002 and AMD rate to 1
and set primary currency AMD

then i go to product page, product price is 500 AMD.

Can You repeat this action?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan the same can be told about already placed orders, shipping rates, etc, etc, etc. Primary currency should not be changed in live stores
