### ISSUE TITLE
Setting to include products tags in sitemaps

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2413]
Both: XML and HTML

Source: https://www.nopcommerce.com/boards/t/47808/suggestions-add-seo-properties-for-producttags-and-new-options-to-include-producttag-urls-in-eitherboth-sitemaps.aspx

Related: https://github.com/nopSolutions/nopCommerce/issues/2414

**Comment by skoshelev** [comment]
Closed #2413
