### ISSUE TITLE
Version or Branch

### ISSUE THREAD

**Issue by poolpro2017** [nopSolutions/nopCommerce#2416]
Hello,

Need Help. What version of source should be used? It automatically defaults to Develop, But Nop.Plugin.ExternalAuth.Facebook plugin fails to build against the core project.

Thanks in advance for any help.

**Comment by Xzelsius** [comment]
Depends on what you want. develop = nop 4.0 (work in progress)
If you want to work on 3.9 you have to use release-3.90-bug-fixes
