### ISSUE TITLE
Nop.Plugin.ExternalAuth.Facebook hasn't been updated to .NET Core

### ISSUE THREAD

**Issue by ilich** [nopSolutions/nopCommerce#2420]
develop branch build fails because Nop.Plugin.ExternalAuth.Facebook hasn't been updated to use .NET Core and .NET Framework 4.6.1

**Comment by AndreiMaz** [comment]
@ilich thanks, we know =)) actually we're still working on it (there are a lot of task left in migration to asp.net core)
