### ISSUE TITLE
Display notification when measures or dimensions are changed

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2422]
Once some weight or dimension is changed (set to primary) we have to notify a store owner, then he has to manually update other rates. And ensure that each product has a valid measure (dimension) - they are not adjusted autoamtically

**Comment by tigran-avdalyan** [comment]
Example by Default Weight measure is LB and Ratio is 1 , KG  with Ratio 0.45359237.
When we set Default Weight measure to KG auto set ratio to 1, and auto calculate LB rate to 2,20462262

**Comment by AndreiMaz** [comment]
or better we should ask a store owner whether he wants it to be done automatically

**Comment by drielnox** [comment]
Is it possible to think that the system both system of units? For example, there is some general configuration option where you can choose between the metric system and the imperial system.
In addition, the conversion factor of the magnitude types of both systems are constant.

There is an open source library for this kind of thing: https://github.com/anjdreas/UnitsNet

**Comment by tigran-avdalyan** [comment]
@AndreiMaz "Display notification when measures or dimensions are changed " is right title?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Right. This is how we decided to implement it

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/3043
