### ISSUE TITLE
Category import- not import images

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2425]
i import categories, all importing without images
Sample image path C:\Users\Tigran\Desktop\Food\img\mysite.ru\sites\default\files\perez_b.png

**Comment by tigran-avdalyan** [comment]
Error massage: Value cannot be null. Parameter name: picture

**Comment by tigran-avdalyan** [comment]
its connect with mime type PNG????

**Comment by tigran-avdalyan** [comment]
file is exist, permissions is full, any ideas????

**Comment by skoshelev** [comment]
The same #2077

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/2077
