### ISSUE TITLE
Admin area. Display SKU or picture on product list pages (related products, Cross-sells , Associate a product, etc)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2426]
When we want to select Related products, Cross-sells products, Associate a product    the product list show only Product names, we can have product with same names, how chose right product???
i think need add Column with id or SKU , and product image for сonvenience.

**Comment by tigran-avdalyan** [comment]
add same Column in Categories>>Products tab.

**Comment by tigran-avdalyan** [comment]
![product](https://user-images.githubusercontent.com/17789934/31279574-8e97ea00-aaba-11e7-83e4-e4301b897c1a.gif)

**Comment by AndreiMaz** [comment]
decided to leave it for customization
