### ISSUE TITLE
Replace ImageResizer.NET With ImageProcessor

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2427]
ImageProcessor have more functions support like Image, Png, Exif, JPEG, TIFF, Fluent, Watermark, Resize, Crop, Rotate, Quality, Gif, Jpg, Bitmap, Animated.

https://dotnet.libhunt.com/project/resizer/vs/imageprocessor?rel=cmp-cat

**Comment by tigran-avdalyan** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it
