### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by khoshroomahdi** [nopSolutions/nopCommerce#2428]
1-automatic download digital product after purchase.(it is so essential for me)
2-remove required email filed for guest.
3- user can sign up and sign in with phone number instead of email

**Comment by jaySolo** [comment]
Please explain this one:
> automatic download digital product after purchase.(it is so essential for me)

Do you mean that a link (temporarily available for obvious reasons) which would be used to download the digital product is automatically created and (preferably) emailed to the customer once the payment has been verified?

**Comment by khoshroomahdi** [comment]
Now when a guest customer buy a digital product nopcommerce send it's link to his email. I want after purchase go to a web page and show that link and begin to download automatic instead to send link to email. Understand?

**Comment by AndreiMaz** [comment]
thanks a lot 
1. https://github.com/nopSolutions/nopCommerce/issues/2429
2. already exists
3. https://github.com/nopSolutions/nopCommerce/issues/2430

**Comment by khoshroomahdi** [comment]
2- but it needs email filed for digital product and I mean for digital product.
