### ISSUE TITLE
Track inventory by product attribute in multiple warehouses

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2432]
How can I track product quantity by attribute combination with multiple warehouses? Currently it is possible to track product by attribute in one warehouse but not multiple warehouses!
Here's the scenario:
I have product A with colour and size attributes. I also have warehouse 1 and warehouse 2. I need to track quantity in each warehouse by product with combined attributes i.e. qty of product A in size 100x100 and white colour.

Source: https://www.nopcommerce.com/boards/t/43235/track-inventory-by-product-attribute-in-multiple-warehouses.aspx

Also see https://github.com/nopSolutions/nopCommerce/issues/2013

**Comment by tmotionsglobal** [comment]
@AndreiMaz Any update if this feature is coming in 4.0 or later releases?

**Comment by AndreiMaz** [comment]
@tmotionsglobal No, it was postponed

**Comment by mikedepo** [comment]
I really wish this will be implemented. Much needed.

**Comment by rubyarun** [comment]
Can we do this now?

**Comment by kiranbhadani** [comment]
@AndreiMaz Any updates on this or any alternative?

**Comment by alirezafatehi** [comment]
@AndreiMaz Any progress on implementing this feature?
The alternative way is define warehouses as an attributes and then define qty for each combination of attributes with warehouses but the problem is this attribute show to customer and it is not ideal.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
