### ISSUE TITLE
Shipping (work) time

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2433]
Ability to choose time when customer can buy the product from current Vendor.
Vendor may have Work day from 9:00 to 22:00.
and shipping or paymout can do in work time.

**Comment by tigran-avdalyan** [comment]
Can be add this function to Stores.
Can be add this function to Vendors.
Can be add this function to Categories.
Can be add this function to Products.
Can be add this function to Shipping methods.
Can be add this function to Payment methods.

**Comment by AndreiMaz** [comment]
Do you mean an option to prevent customers from buying in a store in certain time? But it's online (!) store. It works 24 hours per day. Please clarify

**Comment by tigran-avdalyan** [comment]
For example, in a multi-store mode, one store can run from 9:00 to 22:00 and the other will work 24 hours.
In the shipping, one Shipping method be Available from 9:00 to 22:00 (e.g. Fast food shipping  with Courier) and the other will be Available 24 hours.
For example, one vendor can work from 9:00 to 22:00 and the other will work 24 hours.
And so forth, products, payment methods.

**Comment by tigran-avdalyan** [comment]
Online store its not 24/7. 
Web site and product list can be available 24 hours , and you can buy, but when you buy after work day, shipping will be in next day 9:00.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan I see now. Thanks

**Comment by tigran-avdalyan** [comment]
we can have Shipping method -- "Ship in 30 minutes" , but available only from 9:00-22:00.
and we can have Payment method --- Payment can confirmed only from  9:00-22:00.
We can have Warehouses that open from  9:00-22:00.
We can have Vendors who Supply products but they work from  9:00-22:00.

**Comment by tigran-avdalyan** [comment]
https://www.menu.am/en/
this is example internet magazine, where vendors have Work time, and Costumer can Buy only in work time.

**Comment by tigran-avdalyan** [comment]
![work time](https://user-images.githubusercontent.com/17789934/28008969-b619cf8e-656a-11e7-9e6e-9cf0e32ca9e7.png)

**Comment by tigran-avdalyan** [comment]
i think Vendor(all vendor products) need to have Availablety time.
And product Availablety now have parameter Start Date/Time -End Date/Time
i think need to add parameter Every day from Start Time - End time.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
