### ISSUE TITLE
Mobile applications for iOS and Android

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2437]
It'll be based on Flutter

**Comment by AndreiMaz** [comment]
just a note - https://github.com/nopSolutions/nopCommerce/issues/2381

**Comment by tigran-avdalyan** [comment]
We can create Desktop App with https://github.com/ElectronNET/Electron.NET

**Comment by yehia2amer** [comment]
It's Great to know that is there is a plan for Mobile App development.
For our use case, Flutter is much better. One code-base and still almost same performance anyway as this is an eCommerce app not a game or GPU\CPU intensive App.

Very Excited to see this along with  **API support** #4988

**Comment by xcellenceit** [comment]
Flutter app will be great!

**Comment by PanagLtd** [comment]
How will installed plugins and themes work with native apps?

**Comment by glhays** [comment]
Yes, please do tell and as well the numerous theme pkgs.
________________________________

**Comment by AndreiMaz** [comment]
Started working on this task

**Comment by rajupaladiya** [comment]
> Started working on this task

Flutter OR MAUI OR Xamrin?

**Comment by AndreiMaz** [comment]
Flutter

**Comment by nextfool** [comment]
MAUI would be a great choice for .net developers....

**Comment by rajupaladiya** [comment]
> MAUI would be a great choice for .net developers....

I do agree

**Comment by AndreiMaz** [comment]
We've considered MAUI. But it's still not ready for production and doesn't work well

**Comment by nextfool** [comment]
Hi @AndreiMaz , thanks for the clarification,  but still IMHO, being not based on MAUI is a pity.  Maybe you can just release beta(even alpha) versions, and wait till MAUI is mature enough.  Developing with flutter or any other production ready solutions takes lot of time and versions anyway.

**Comment by AndreiMaz** [comment]
@nextfool Sure, we understand that. Once MAUI is mature and stable enough, we can consider release of one more version of the mobile app (based on MAUI). But nowadays Flutter is much better choice for developers and merchants

**Comment by balajivelu147** [comment]
Hi @AndreiMaz , are we sure that this ticket will be completed with next release (version 4.6) at planned timeline(Nov 1) or will there be any delay, if yes please share the expected date of completion.

**Comment by AndreiMaz** [comment]
The mobile is almost completed (80%)

**Comment by balajivelu147** [comment]
great.. good to know, thanks for the quick response.. @AndreiMaz

**Comment by kava81** [comment]
Hi @AndreiMaz Mobile applications will be compatible only with 4.60 or also previous version? thanks

**Comment by AndreiMaz** [comment]
@kava81 Most probably, we'll support 4.50 as well

**Comment by matthewha** [comment]
Hi @AndreiMaz,

Great to see this coming along. Will the app/s cover just customer functions or will there be administration functionality as well?

Thanks

**Comment by DmitriyKulagin** [comment]
@matthewha Customer functions only

**Comment by amirkhanjz** [comment]
I think it's time to send this to next milestone and release 4.6 as this work item was not in 4.6 changelog pdf.

**Comment by AndreiMaz** [comment]
The mobile app will be released in about 2 weeks. We'll support nopCommerce versions 4.50 and 4.60

**Comment by dev3380** [comment]
When mobile app will be released?

**Comment by AndreiMaz** [comment]
In about a week

**Comment by cratosomg** [comment]
We should promote the application by placing difference tempting things to the customers.  Example % offer, free shipping, buy three get one free or other things depending on the business.  So customers will make more use of the app.
