### ISSUE TITLE
Convert BaseEntity to Generic type BaseEntity<Key>

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2439]
Currently, nopCommerce does not support primary key type (e.g. Guid, Short, long) other than int.

BaseEntity, IRepository (EfRepository) should be changed. Both should support any type of primary key.

Note: It will also affect to UrlRecord.

**Comment by a-patel** [comment]
@AndreiMaz 
I can help you to convert BaseEntity, EfRepository to generic repository <PKey, Type> in asp.net core

**Comment by a-patel** [comment]
I already started nop to converting to asp.net core project since 2016.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
