### ISSUE TITLE
Resize Qty textbox to fit content

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2440]
Quantity textbox (or other textboxes ) auto resize to fit content.

<input type="number">

**Comment by tigran-avdalyan** [comment]
add parameter(if need) maxlength
and allow only Digits to write in textbox.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan can you please some examples of sites which support it?

**Comment by AndreiMaz** [comment]
After some investigation decided not to implement this feature out of the box
