### ISSUE TITLE
When add validation rules in attribute no longer can edit attribute

### ISSUE THREAD

**Issue by sergeor** [nopSolutions/nopCommerce#2443]
1) Go to products -> edit -> product attributes.
2) add new record with Textbox control.
3) edit Validation rules and add min  length = 3,  max length = 5, def val = 1000. save
5) Edit attribute  and change the Text prompt.
6) update

Error = $exception	{"A potentially dangerous Request.Form value was detected from the client (ValidationRulesString=\"... length: 0<br />Maximum length...\")."}

**Comment by AndreiMaz** [comment]
Automatically fixed in 4.00 (no validation)
