### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by shyandsy** [nopSolutions/nopCommerce#2444]
### Installation Error
- IDE
Visual Studio 2017 community
- Database     
Use built-in data storage (SQL Server Compact)
- Branch
Develop
- Error Message
Setup failed: The ADO.NET provider with invariant name 'System.Data.SqlServerCe.4.0' is either not registered in the machine or application config file, or could not be loaded. See the inner exception for details.

**Comment by AndreiMaz** [comment]
4.00 is very unstanble now. it's not recommended to use in production enviroment as we rewrite a lot of code (moving to asp.net core). please try again

**Comment by shyandsy** [comment]
just try to study it not for production purpose

发自我的 iPhone
