### ISSUE TITLE
Cancel Order Button (For Customers)

### ISSUE THREAD

**Issue by m1dst** [nopSolutions/nopCommerce#2446]
It would be great to have a "Cancel Order" button for orders which have yet to be paid and the customer decides they no longer want to proceed.  I guess it could be related to #388.

There was a sample provided in the forums for it but I would say it is just a start.  https://www.nopcommerce.com/boards/t/46043/cancel-order-feature-for-customers-in-nopcommerce.aspx

To enhance the forum code I would suggest it needs to be a setting, the code relies on a GET rather than a secure POST so suffers from XSS.  Button text should be localised.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

**Comment by sumo300** [comment]
Don't quite understand why you wouldn't want to make this a feature of the main product.  Isn't this a standard feature of most eCommerce sites, to be able to cancel an order before it's picked or shipped?
