### ISSUE TITLE
Custom customer attributes -  limited per store

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2447]
I have a client with two stores that are in no way related to each other. They have totally different types of products and customers. I have created custom customer form fields for one of the stores that I really don't want to appear on the registration form of the other store.

Please consider adding this capability.

Source: https://www.nopcommerce.com/boards/t/48019/suggestion-custom-customer-attributes-need-to-be-limited-per-store.aspx

**Comment by miladgame** [comment]
so good, i have same problem

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin
