### ISSUE TITLE
Code polishing

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2448]
1. Duplication of logic in two or more places.
2. Undesired dependencies. For applications divided into layers such as persistence, business and user interface, the dependencies between the layers need to be managed. Finding undesired dependencies such as the use of persistence code directly within the user interface layer is a strong indicator of a design problem. Move references to Nop.Core
3. Overly complex logic, like a large switch statement or series of nested if-else statements. Sometimes such logic can be drastically simplified through the use of object-oriented design principles.
4. Too many classes within one package.
5. Overly long file, in excess of a couple thousand lines. Even in Java where each public class is forced to be in its own file, it is possible to end up with very long files. This may be because there is too much logic within the class, or it may be because of many nested classes or private classes in the same file. In the latter case, these can be moved to one or more separate files.
6. Overly long methods. Anything longer than about one screen warrants a closer look to see if it can be simplified, usually via an extract method refactoring.
7. Poorly named classes, methods, fields or local variables. One indicator I look for is a one-sentence comment describing a vaguely named variable or method. Usually the variable or method can be renamed to capture the essence of the comment and the comment can then be deleted.
8. Lack of a class comment. A concise summary of the purpose of the class is often quite useful. If it is difficult to come up with such a summary, it is an indicator that the class may be trying to do too much or does not have a clear focus.
etc..
9. Improve the code design: use the initialization of classes and collections everywhere, replace the “for” loops to LINQ expression (where applicable)
10. Check the code with static analyzers, such as StyleCop and PVS-Studio
-----------------------------------
11. Too many methods within a class, particularly public methods. This is often an indicator that the class is trying to do too much and should be split into multiple classes.
12. Refactoring of big methods (split to several ones). For example, the PlaceOrder method from OrderProcessingService uses #region 3 times. The best practice says you shouldn't use regions inside methods. Methods should be short and each method should do only one thing. So instead of separating the method into 3 regions, you should refactor into 3 or more separate methods. The PlaceOrder method is not the only place where region is used inside methods, that's why the title was more general.
Here are other places where #region is used inside methods: Authorize in ExternalAuthorizer, FormatStockMessage in ProductExtensions, SearchProducts in ProductService, GetProductCount in ProductTagService, PrintOrdersToPdf in PdfService, DeleteGuestCustomers in CustomerService, InstallProducts in CodeFirstInstallationService, ProductListToHtmlTable in MessageTokenProvider. And the list can go on ... Also the constants, fields, properties and constructor are always in the same order so I don't think the use of #region is required. And #region is also used in some classes to group some related methods. For example, in CustomerService you have 2 regions: Customers and Customer roles. I think the Customer roles region should be moved to it's own CustomerRoleService and so the use of #region will not be necessary. More info about the use of regions: https://blog.codinghorror.com/the-problem-with-code-folding/ and http://softwareengineering.stackexchange.com/questions/53086/are-regions-an-antipattern-or-code-smell
13. Use one input and one output parameter for some methods (e.g. IPriceCalculationService and IOrderTotalCalculationService. IPriceCalculationService, IOrderTotalCalculationService, ITaxService, etc. What else? Right now we have a lot of input and output parameters. A lot of methods with the same names but different signatures. Let's use one input and one output parameter. Similar to "PlaceOrderResult PlaceOrder(ProcessPaymentRequest processPaymentRequest)" of IOrderProcessingService
14. use "var" everywhere
15. string or String

related work items - #1978

**Comment by RomanovM** [comment]
1. Duplication of logic in two or more places.
2. Undesired dependencies. For applications divided into layers such as persistence, business and user interface, the dependencies between the layers need to be managed. Finding undesired dependencies such as the use of persistence code directly within the user interface layer is a strong indicator of a design problem.
3. Overly complex logic, like a large switch statement or series of nested if-else statements. Sometimes such logic can be drastically simplified through the use of object-oriented design principles.
4. Too many classes within one package.
5. Too many methods within a class, particularly public methods. This is often an indicator that the class is trying to do too much and should be split into multiple classes.
6. Overly long file, in excess of a couple thousand lines. Even in Java where each public class is forced to be in its own file, it is possible to end up with very long files. This may be because there is too much logic within the class, or it may be because of many nested classes or private classes in the same file. In the latter case, these can be moved to one or more separate files.
7. Overly long methods. Anything longer than about one screen warrants a closer look to see if it can be simplified, usually via an extract method refactoring.
8. Poorly named classes, methods, fields or local variables. One indicator I look for is a one-sentence comment describing a vaguely named variable or method. Usually the variable or method can be renamed to capture the essence of the comment and the comment can then be deleted.
9. Lack of a class comment. A concise summary of the purpose of the class is often quite useful. If it is difficult to come up with such a summary, it is an indicator that the class may be trying to do too much or does not have a clear focus.
etc..

**Comment by AndreiMaz** [comment]
All important points are done. Two new tasks - https://github.com/nopSolutions/nopCommerce/issues/2645 and https://github.com/nopSolutions/nopCommerce/issues/2646
