### ISSUE TITLE
Simplify product picture upload

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#245]
There are too many steps when we upload a product image. 

we click upload then we see the file upload indicator - which is good - 

but then we have to click 'add picture to gallery ' well, we just uploaded it because we want to add it to the gallery so lets just add it to the gallery as soon as its uploaded (and remove the need to click the add to gallery button)

Further reason to simplify : 

did you notice how easy it is to upload an image, click 'add picture to gallery' then accidently 'add picture to gallery' again instead of uploading a new photo ? 

if you do this, it adds the picture to the gallery again - so you have two of the same photos - 

Then .. 

when you delete the duplicate, it deletes both images and you have to upload it again (you can't simply click 'add to gallery' after that action) 
source 
http://www.nopcommerce.com/boards/t/19529/suggestion-simplify-product-picture-upload.aspx

**Comment by AndreiMaz** [comment]
duplciate
