### ISSUE TITLE
"GetAllTasks" fails sometimes.

### ISSUE THREAD

**Issue by jeypeer** [nopSolutions/nopCommerce#2455]
Using the lastest version, sometimes when starting the application from VS 2017(debug mode):
public virtual IList<ScheduleTask> GetAllTasks in ScheduleTaskService.cs 
fails at var tasks = query.ToList();

What other information can I provide to help you with this?

**Comment by skoshelev** [comment]
Hello. Can you specify version of nopCommerce and full error stack trace? If you use develop branch from github, then you must know it's unstable version and we do many changes everyday.

**Comment by AndreiMaz** [comment]
@jeypeer please provide a complete error stack

**Comment by jeypeer** [comment]
Hi both, its version 4.0. Understand its under dev but thought I could point it out. anyhow, its intermittent and I am not having any luck reproducing it today. I will try to update as soon as I can.

**Comment by stephenstroud** [comment]
I had the same issue occur when I was setting up the development branch for the first time, I can't reproduce the error, however, confirm it also fails on line 88  var tasks = query.ToList(); 
I investigated the error by stepping through the code and then it worked. The method appeared to be returning a null list before it had finished executing the query.  I will capture the stack trace if it happens again and post.

**Comment by AndreiMaz** [comment]
@stephenstroud is it possible to try it one more time with the latest "develop" branch?

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/2558
