### ISSUE TITLE
Enable sample download for non-downloadable products

### ISSUE THREAD

**Issue by wezzix** [nopSolutions/nopCommerce#2458]
Use case: If you sell a physical product such as a book, you may want to include a downloadable sample such as a pdf, even though the product itself is not downloadable. Hence the Admin should support this scenario.

Problem: Currently the Sample download area gets hidden when Is Downloadable product is unchecked.
**Fix: Make sample download always visible regardless of "IsDownload".**
Workaround: Check IsDownload, then add sample file, then remember to uncheck IsDownload. When user forgets the last step, it causes all sorts of problems later on.

**Comment by AndreiMaz** [comment]
After discussion we've decided not to implement it

**Comment by wezzix** [comment]
What was the motivation behind the conclusion?
What is the recommended approach for this use case?
Thank you
