### ISSUE TITLE
Upgrade to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2469]
Now we use 1.1. Let's wait for RTM of version 2.0 and upgrade to it

**Comment by joe704la** [comment]
I believe this is realeased https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/2491

**Comment by erjys** [comment]
how can i contribute for this enhancement as i am .net developer with this skill set.
