### ISSUE TITLE
Vendor commissions and adaptive (chained or parallel) PayPal payments

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#247]
We are looking at two options that we want to look into for additional Vendor Features. The requirements are based on existing systems that exist elsewhere. 

The first is based off of an existing extension for Woocommerce. See the following link for details: http://www.woothemes.com/products/product-vendors/. Key Features - commission percentage, PayPal payments, & reporting. 

Forum source: http://www.nopcommerce.com/boards/t/29853/additional-vendor-features.aspx 

For multiple vendors, we should use either a chained PayPal payment API or a parallel PayPal payment API. 

With chained, Store owner can take a percentage and then rest would be split to the vendors. 

With parallel, Store owner can opt out and payments will be split between vendors. 

https://www.x.com/developers/paypal/documentation-tools/adaptive-payments/integration-guide/APIntro 

See also: http://www.nopcommerce.com/boards/t/22403/multi-vendor-roadmap-lets-discuss.aspx?p=6#92687 

[AM] was done is part of one customization projects 

Also note that we already have it as a third-party plugin - http://www.nopcommerce.com/p/1544/paypal-adaptive-payments.aspx and http://www.nopcommerce.com/p/2162/paypal-adaptive-plugin-silhouettewebcom.aspx

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement


Furthermore, it's already available as a plugin
