### ISSUE TITLE
Store Context Not Returning Correct Store ID

### ISSUE THREAD

**Issue by davidcfox** [nopSolutions/nopCommerce#2470]
The Store Context is not returning the correct store ID in controllers derived from the "BasePluginController".

For example, in the Nivo Slider controller "PublicInfo" method, the call to "_storeContext.CurrentStore.Id" does not return the correct store ID.  This is preventing the plugin from working on sites configured with multiple stores.

**Comment by AndreiMaz** [comment]
@davidcfox please provide a complete list of steps to reproduce the issue. It works fine

**Comment by davidcfox** [comment]
@AndreiMaz 
Thanks for the response.  The issue was on our end.  We did not have the HOST name that we were using in our dev environment added to the store.  After reviewing the "WebStoreContext.cs" and "StoreExtensions.cs" source code, it is clear why we were not receiving back the store ID we were expecting.

Sorry for the unnecessary issue request.

David
