### ISSUE TITLE
Replace 'Description.txt' file with 'Description.json' file for plugins

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2472]
this is just enhancement. 
we can easily read/parse json file using newtonsoft.json

**Comment by onuralp** [comment]
I agree with this idea. I think plugin.json is better than Description.txt

**Comment by a-patel** [comment]
@onuralp I am going to edit the issue title

**Comment by a-patel** [comment]
Missing:
Also replace 'InstalledPlugins.txt' with 'InstalledPlugins.json'

**Comment by a-patel** [comment]
@AndreiMaz plugin.json is more suitable.
this issue has been resolved. 
Please close the issue.

**Comment by a-patel** [comment]
All configuration text files should be replaced by json files.
