### ISSUE TITLE
SQL Index Recommendations

### ISSUE THREAD

**Issue by sumo300** [nopSolutions/nopCommerce#2479]
I have been running nopCommerce 3.4 and 3.9 in Azure for almost a year now and Azure has identified several necessary indexes to reduce overall CPU/DTU usage.  I have attached those index recommendations.  These allowed a much more responsive system on Azure (that and removing images from the DB).

[Index-Recommendations.zip](https://github.com/nopSolutions/nopCommerce/files/1202462/Index-Recommendations.zip)

**Comment by AndreiMaz** [comment]
duplicated
