### ISSUE TITLE
Multi-store. Add single sign on (SSO) support (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#248]
- Single Sign On (SSO) for cross-domain
  Please check this article first: http://www.codeproject.com/Articles/106439/Single-Sign-On-SSO-for-cross-domain-ASP-NET-applic
- The implementation explanation
  Proposition 1: There no completely public page in nopComemrce, means any URL try to use the information about the currently authenticated customer, simplest example - each page has a customer info in a header.
  Proposition 2: We have 2 possible SSO models, let's name them (corresponding to the article above) the "basic" and the "proposed".
  - The "basic" model
    - Sequence diagram  
      3 websites: domain1.com, domain2.com and domain3.com
    - user "surfs" a domain2.com
      - no redirects, context will be actualized by using the Cookie browser sends
    - user tries to login
      - take the standard login workflow at the domain2.com(setup cookie)
      - redirect to SSO login of the domain2.com
      - redirect to SSO login of the domain3.com(setup cookie)
      - redirect to SSO login of the domain1.com(setup cookie)
      - redirect to SSO login of the domain2.com
      - no more SSO redirects required -> redirect to the required URL
    - user tries to register
      - take the standard register workflow at the domain2.com(setup cookie)
      - redirect to SSO login of the domain2.com
      - redirect to SSO login of the domain3.com(setup cookie)
      - redirect to SSO login of the domain1.com(setup cookie)
      - redirect to SSO login of the domain2.com
      - no more SSO redirects required -> redirect to the required URL
    - user tries to logout
      - take the standard logout workflow at the domain2.com(drop cookie)
      - redirect to SSO logout of the domain2.com
      - redirect to SSO logout of the domain3.com(drop cookie)
      - redirect to SSO logout of the domain1.com(drop cookie)
      - redirect to SSO logout of the domain2.com
      - no more SSO redirects required -> redirect to the required URL
    - Conclusion
      As you can see this model is running in circles, the initial website initializes and finalizes an SSO round.
      The main problem with this SSO model is about complexity, when there a lot of websites. BUT it has the decisive
      advantage, there no redirects, while customer stays as not logged in. It takes a single SSO round for each of 
      the login/logout/register actions.
  - The "proposed" model
    - Sequence diagram
      4 websites: domain1.com, domain2.com, domain3.com and sso.com, where domain*.com are SSO slaves and sso.com is SSO master
    - user "surfs" a domain2.com
      - if customer is logged in, no redirects
      - if customer is not logged in and page is completely public, no redirects
      - if customer is not logged in, redirect to the SSO master site, to actualize the context
      - if sso.com has authentication cookie -> redirect to domain2.com, approve to setup the cookie -> redirect to the required URL
      - if sso.com doesn't have -> redirect to domain2.com, deny to setup the cookie -> redirect to the required URL
    - user tries to login
      - redirect to the sso.com
      - take the standard login workflow at the sso.com
      - redirect to domain2.com -> the required URL
    - user tries to register
      - redirect to the sso.com
      - take the standard register workflow at the sso.com
      - redirect to domain2.com -> the required URL
    - user tries to logout
      - redirect to the sso.com
      - take the standard logout workflow at the sso.com
      - redirect to domain2.com -> the required URL
  - Conclusion
    As you can see this model is much more suitable, when the most of site pages are completely public.
    BUT as it said in Proposition 1, most of the nC pages aren't completely public. So for each request we will have 3 redirects.
- Decision

In our implementation we have utilized the "basic" model.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement

**Comment by Achal2241** [comment]
I have a client for which I am managing Multiple stores and recently they shifted to Entra ID and wanted to access the Shops with EntraID credentials using SAML.

I found it too difficult to achieve this by doing custom development and finally achieved it using a third-party solution which is cheap and quite useful.
(Reference Link: [https://plugins.miniorange.com/nopcommerce-saml-single-sign-on-sso](https://plugins.miniorange.com/nopcommerce-saml-single-sign-on-sso))
