### ISSUE TITLE
 pluggable architecture

### ISSUE THREAD

**Issue by pentest30** [nopSolutions/nopCommerce#2480]
hello , i want to create a pluggable architecture for my ERP project and i want to adopt your approach, can you explain how it works please ?

**Comment by Xzelsius** [comment]
Just check PluginManager.cs, PluginFinder.cs and all other files in src/Libraries/Nop.Core/Plugins..

**Comment by pentest30** [comment]
without any configuration in the web.config ?

**Comment by Xzelsius** [comment]
Back 3.9 the only relevant thing was under runtime -> assemblybinding -> probing
Best is you analyse the code and learn how it works.

**Comment by AndreiMaz** [comment]
please post all questions on our forums
