### ISSUE TITLE
cache busting mechanism for client resource files like css/js?

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2481]
would be nice if nopcommerce would  support cache busting mechanism for client resource files like css/js?

https://www.keycdn.com/support/what-is-cache-busting/

cached versions of javascript files can be quite annoying

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. Not sure that it's possible to do it out of the box. Just add some query string param to approrpiate JS or CSS files

**Comment by rudgr** [comment]
ok, did find solution:

asp-append-version attribute on script or link tag:

http://blog.lesierse.com/2015/12/20/cache-busting-using-aspnet5.html
