### ISSUE TITLE
Public area. Home page widget/slider should have fixed size (height-width) and it should be configurable

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2484]
Currently home page slider does not has fixed size, it depends on the image size (height-width). If size of all images in the slider are not same then slider changes its size automatically, this behavior is little weird.

**Comment by a-patel** [comment]
Solution should be:
i. fix the slider/widget size.
ii. resize the all slider images to specific size (while uploading)

(slider size should be configurable from admin side)

**Comment by AndreiMaz** [comment]
@a-patel I think that the current solution is better and mroe flexible
