### ISSUE TITLE
Admin area. Use watermark/placeholder in input fields

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2486]
Admin UI enhancement: yes, it is good to have 'info/help' tooltip, but for some/all fields should have placeholder text. e.g.Category Price ranges: 0-199;200-999;1000-;

We need to prepare a list of such suggestions. But they are already in hints

**Comment by a-patel** [comment]
it will be better if we use placeholder in public and admin both areas.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box.
