### ISSUE TITLE
Admin area. Use common/shared view for SEO details (for all entities) #DRY

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2487]
Use shared partial view for SEO details (e.g. Meta keywords, description, title, se name).
These inputs are common for all SEO related entities.

**Comment by a-patel** [comment]
Solution should be:
Create new view model for called  SeoModel which contains seo related fields only, and seo related entities should contain this model as a property.

`
public class SeoModel
{
        [NopResourceDisplayName("Admin.ContentManagement.News.NewsItems.Fields.MetaKeywords")]
        [AllowHtml]
        public string MetaKeywords { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.News.NewsItems.Fields.MetaDescription")]
        [AllowHtml]
        public string MetaDescription { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.News.NewsItems.Fields.MetaTitle")]
        [AllowHtml]
        public string MetaTitle { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.News.NewsItems.Fields.SeName")]
        [AllowHtml]
        public string SeName { get; set; }
}

public partial class NewsItemModel : BaseNopEntityModel
{
        public SeoModel Seo { get; set; }
}
`

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box
