### ISSUE TITLE
does not validate customer 'Phone' number unique value

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2488]
Currently (v3.90), Customer Phone number unique value is missing i.e. more than one customer can have same phone number.
Ideally phone number should be unique.

**Comment by a-patel** [comment]
Steps:
Admin->Configuration->Setting-> Customer settings
Go to 'Customer forms fields' tab
Check 'Phone number' enabled and 'Phone number' required

**Comment by AndreiMaz** [comment]
@a-patel actually even Google allows multiple accounts with the same phone number

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Can we do it Configurable?
'Phone number' is unique or not
