### ISSUE TITLE
Category Icons

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#249]
It would be nice to be able to upload category icons so customers can easily identify and click on categories. The icons would display to the left of the category name. 

Also, it would be awesome if the category menu was like a tree view (with no posts/page loads)! :) 

Forum source: http://www.nopcommerce.com/boards/t/15624/new-feature-category-icons.aspx

**Comment by tigran-avdalyan** [comment]
Now in Menu before Text show Square dot, can be replaced to icon. Configurable in Admin area.
We can Add Menu configuration in settings.

**Comment by tigran-avdalyan** [comment]
![untitled](https://user-images.githubusercontent.com/17789934/30468426-4869b1fe-99fc-11e7-90f8-1efb3892e3cb.png)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
