### ISSUE TITLE
Full web farm support

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2494]
Actually we already fully support Azure web apps with multiple instances. So we can say that this scenario of web farm environment is support. Find more about it at https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-microsoft-azure.html

Let's also add support for multiple servers. For example, multiple real physical servers or multiple virtual machines (on Azure). So there are one thing  to be supported in such environments. It's a shared file system. We have to store files on some shared storage. For example, 

1) Plugin.json and other setting files
2) PDF files (attachments). Source: http://www.nopcommerce.com/boards/t/40525/web-farm-mode-taskscheduler-pdf-invoice-attachment-missing-in-order-place-notification.aspx 
3) Exported files (e.g. excel)
4) Ensure that bundling and minification works in web farms
5) etc - ? (also see comments below)

I think it's not correct to store them in database. So we have to investigate two possible scenarios:
1. File Replication - Each server hosts copies of the load balanced website files and a file replication service is running to ensure that all files on all servers are up to date
2. Centralized file share - The load balanced website files are located on a centralized file share (SAN/NAS/Clustered File Server/Network Share)
Find more info on how it's described (with configuration details) for Umbraco at https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

Once it's done we have to write a good tutorial for our documentation portal on how to configure web farms

Some other useful links:
1. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-5.0
2. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0

Also see how it's implemented at Umbraco:
1. https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps
2. https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

**Comment by lintho** [comment]
Is this working in azure now, or was the enhancement removed for 4.0?

**Comment by biernba** [comment]
"OrderPaymentInfo" in session also has problems with a webfarm configuration,
but ProcessPaymentRequest does hold sensitive data, like creditcard info including creditcard number.
In this case not feasible with cookie-based TempData?

**Comment by ivanslater** [comment]
Will Web Gardens be supported?

**Comment by mynkow** [comment]
I am interested in this. I am planning to host two docker instances.

What problems or issues I might face with version 4.2?

**Comment by xcellenceit** [comment]
I have been testing it with docker for same purpose. I have tried with 4.2 on docker, while i get first instance correctly the second instance is not created / not stable. So I could not test it further. 

Anyone successful with hosting multiple instance on docker on same host machine?

**Comment by mynkow** [comment]
Till now I figured that we need to take care about the following in a load balanced environment:
* app_data folder must be shared (ex: azure blob storage)
* Scheduled tasks must be executed on a single machine. Any idea how to do this?
* Redis cache is a must

What else I am missing?

**Comment by toddca** [comment]
FWIW I am not convinced web farm support is a priority for the nop team. 

You can store plugin and data protection keys in redis but do not use redis for caching as the currently implementation has a ton of issues and is very slow.

I have proposed we use the DB to store the plugin information and submitted a pull for this however it was rejected since I was not using EF to access the DB which is not available at the point we need to pull plugin info.

The schedule task implementation is less than optimal, for one, there is no guarantee a job/task will finish before a site is torn down and as mentioned no way to set server affinity. Ideally the solution should implement IHostedService.

**Comment by xcellenceit** [comment]
I agree about the Redis Cache implementation. And until the issues mynkow mentioned are addressed its not easy to load balance it.

**Comment by jonquickqsense** [comment]
Regarding the Invoice PDF. Why does it need to be persisted to file system at all?  

If the email in the queue can have an AttachInvoiceId property, then call out to the  pdfService, generate in memory and return the PDF as stream for the MailKit client to use to add to attachments collection?

Jon

**Comment by arieldeil** [comment]
In AWS you can use EFS to share filesystem with different docker instances.

Also you should share those folders and files: 
- "Plugins", in case you upload plugins from admin
- "Themes"
- "Logs"
-  "wwwroot", to support bundling, uploads, thumbnails
- "web.config", to allow extra configurations, 
-  "appsettings.json", to share Redis configuration and more..

**Comment by xcellenceit** [comment]
Thanks for sharing. I haven't tried this yet! Sounds interesting.

**Comment by sefacan** [comment]
@arieldeil I'm not sure need to share these folders and files each containers. Becase I believe they can work as seperately inside of containers.

I think we need to share only these things and they should work as single instance:
AppSetting.txt
Plugins.json
Redis Cache
Scheduled Tasks
TempData
Sessions
Uploaded files

**Comment by arieldeil** [comment]
> @arieldeil I'm not sure need to share these folders and files each containers. Becase I believe they can work as seperately inside of containers.

If you have for example 3 instances running and you upload and install a new plugin from Admin area it should be immediately available in all 3 instances. This cloud be done only if you have a shared Plugins folder.

Another reason is because some plugins might have local files that are generated at runtime and need to be available in all instances in case you next request hit's another instance.

**Comment by arieldeil** [comment]
Regarding Scheduled Task. There is already a locker that locks the task from running twice using "ILocker" interface.

When using Redis then "ILocker" is using redis to lock the task while running. So it should already have support from scheduled tasks, but I never tested it. Can anyone confirm that this is working properly?

**Comment by sefacan** [comment]
> > @arieldeil I'm not sure need to share these folders and files each containers. Becase I believe they can work as seperately inside of containers.
> 
> If you have for example 3 instances running and you upload and install a new plugin from Admin area it should be immediately available in all 3 instances. This cloud be done only if you have a shared Plugins folder.
> 
> Another reason is because some plugins might have local files that are generated at runtime and need to be available in all instances in case you next request hit's another instance.

Yes, sorry for this. I forgot.

**Comment by AndreiMaz** [comment]
Done and optimized for web farms. A tutorial will be published after RTM release at https://docs.nopcommerce.com/

**Comment by arieldeil** [comment]
@AndreiMaz Thanks!

What about migrations? They might run in parallel from 2 different instances.
In case of schema updates the worst case scenario is that one of the instances will fail migration due to "column already exists" or so.
But if you have migrations that insert or update data it might cause duplicate data in DB.

Maybe we should use ILocker while running migrations on each plugin/

What do you think?
