### ISSUE TITLE
Code: Singleton class should have private default constructor. #Singleton Pattern

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2499]
Current Singleton class allowed to create singleton class instance outside the class.

**Comment by a-patel** [comment]
`
    public class Singleton
    {
        static Singleton()
        {
            allSingletons = new Dictionary<Type, object>();
        }
        
        **private Singleton()
        {
        }**

        static readonly IDictionary<Type, object> allSingletons;

        /// <summary>Dictionary of type to singleton instances.</summary>
        public static IDictionary<Type, object> AllSingletons
        {
            get { return allSingletons; }
        }
    }
`

**Comment by skoshelev** [comment]
We use Singletone, Singleton<T>, etc. classes as a standardized way to store single instances, not as the implementation of singletone pattern. You can found this information in the description on the Singleton<T> class.

Closed #2499

**Comment by propellingbits** [comment]
Is there any benefit of using this approach to store single instances? You never retrieve any instance out of that collection (AllSingletons)
