### ISSUE TITLE
Issue when changing a password for a customer without a password in admin area (after upgrade from 3.80)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2501]
Reproduce step is.

1. Site should be 3.80
2. Create some customer without password.
3. Upgrade you site to 3.90
4. Edit those customer who having null password entry in CustomerPassword Table.
5. Try to change password you will get error. Because you didn't handle null condition in below line.

 return customerPassword.Password.Equals(savedPassword);

On PasswordsMatch method.

We did below change for solution: 

if(customerPassword.Password == null)
return false;
  
return customerPassword.Password.Equals(savedPassword);

Source: https://www.nopcommerce.com/boards/t/48354/error-object-reference-not-set-to-an-instance-of-an-object-change-customer-password-from-admin-side.aspx

**Comment by a-patel** [comment]
I think, such critical errors should be captured easily in Unit Testing.
Nop should have to add more unit test cases (At least for business logic i.e. Services).
