### ISSUE TITLE
External Inventory Systems Intergration

### ISSUE THREAD

**Issue by eByte23** [nopSolutions/nopCommerce#2503]
Hi,

I am wanting to use this project as our shopping cart system however it will need to integrate with multiple things.

1. A third party software for Inventory Management. This would be a sync style integration where by I plan to use a scheduled task to sync items where the inventory system is the source of truth.
However i would need to be able to check information about the product at the time of purchase.
e.g. Is this product still available, is it on back order etc. essentially adding an extra interface that would get run through the following methods to return warnings. Would this be the best place to do this then in a plugin to add my implementations?

```
//OrderProcessingService.cs
//PreparePlaceOrderDetails()
_shoppingCartService.GetShoppingCartWarnings
and or 
_shoppingCartService.GetShoppingCartItemWarnings
```

2. Integration user creations and all interactions with an external Oauth IndentityServer implementation by default not as standard external provider. which I believe I can just go an implement normal through the provided abstractions. Any advice here?

Thanks,
Elijah

**Comment by AndreiMaz** [comment]
we leave such integartion  for plugins (not for out of the box)
