### ISSUE TITLE
Ability to Sell Services

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2511]
1.Add ability to sell Services
it can be added with Product type	Templates
or with Checkbox(like Rental or Downloadable products)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Hi Tigran, could you please clarify why existing functionality cannot be used? Just disable shipping.

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Hi Andrei, You are right in existing functionality we can add Service as Product, but it will be great to split Products and Services.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan what exactly do you mean? Please clarify how you want to see it in nopCommerce. New fields? How exactly will they be used?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz I think new field or New Template or chekbok(like Rental or Downloadable products) by name Service

**Comment by tigran-avdalyan** [comment]
Service as a Rental product can have Start Date/Time and End Date/Time, can have Location with map

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
