### ISSUE TITLE
Product attribute Control type - Add Location Support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2513]
in product attribute Control type add support to Import with Map Latitude and  Longitude

**Comment by tigran-avdalyan** [comment]
![untitled](https://user-images.githubusercontent.com/17789934/29658146-f60c16f0-88ca-11e7-8c9b-9e2a946a89af.png)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin
