### ISSUE TITLE
Bulk delete customers

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2515]
On the "Customers" page it will be nice if there is an option to delete the selected customers like on the "Products" page. 

Now if you want to delete customers the process is too long: Edit -> Delete -> Confirm Delete.

Source: https://www.nopcommerce.com/boards/t/48399/bulk-delete-customers.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box

**Comment by ChrisEtzerodt** [comment]
Hi Andrei, I was wondering what your point of views on the bulk delete were, because I would be interested in the bulk delete feature. Presently we seem to have a large number of sign ups that are spam related, so a bulk delete would be an excellent choice for us. 
br Chris

**Comment by ayberkcal** [comment]
> Hi Andrei, I was wondering what your point of views on the bulk delete were, because I would be interested in the bulk delete feature. Presently we seem to have a large number of sign ups that are spam related, so a bulk delete would be an excellent choice for us.
> br Chris

I agree with @ChrisEtzerodt . Some features looks not important for nopcommerce dev team but most of nopcommerce user avoid modify original codes and that feature needs modify original codes. Nop dev team may assign to community, like that simple features.
