### ISSUE TITLE
Generate QR code or other identification code in Order

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2517]
When Customer buy a product, and choose shipping method , pick up in store,
when the customer is coming to take his item, we need to identificate a Customer.

When Customer buy a product, we can send him a Order with identification  code , or Customer can take photo of identification code and show in Store.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Situation: User buy item and select pick-up is store, and 2 peoples came to take the item, how we can identify who buy the item?
