### ISSUE TITLE
File Manager for a store owner

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#252]
Allow a store owner to list files and folders inside the root \Content folder.

Image previews: ability to copy URL, improve the resize options, etc

Just ensure that it has valid permission validations and access only to /content/images/uploaded directory

also see http://badpaybad.info/blog-127/nopcommerce-widget-file-upload-manager

Think about some kind of gallerry support

**Comment by AndreiMaz** [comment]
<img width="563" alt="roxyfilemanager5" src="https://cloud.githubusercontent.com/assets/5019111/14776062/43e3d418-0acc-11e6-9205-cd0e1627fc6d.png">
