### ISSUE TITLE
Allow a store owner to configure maximum number of reward points that could be spent

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2524]
I would like to have a functionality where customer will be restricted to use no more than X reward points for a purchase of certain amount. This is to restrict the customer from not using all reward points at once, as sometimes for marketing purposes, most reward points can be given for free. This would be useful for scenarios such as "USE 50% OF YOUR REWARD POINTS TO PAY FOR YOUR CART". Or "USE ONLY 1000 REWARD POINTS PER ORDER". 

Source: https://www.nopcommerce.com/boards/t/48483/advancement-in-nop-commerce-reward-points-functionality.aspx

**Comment by skoshelev** [comment]
Closed #2524
