### ISSUE TITLE
Currency exchange issue

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#2525]
Hi,

I am using nopcommerce 3.90 with ECB rate provider but sometimes exchange rates are *1000. I attached image please check and suggest me to correct any wrong configuration

https://drive.google.com/open?id=0B9rFDkogeiv8SGwxQ0ZyTU45Nkk

If I go to schedule task and run again same task I am getting right exchange rate but causing problem when it runs automatically

**Comment by jigarsangoi** [comment]
Hello @AndreiMaz , I try to figure out issue this & I found that this issue occurs on our server only not my local pc. Our server in Europe may be Italian culture.

**Comment by AndreiMaz** [comment]
I presume your server has not standard settings for US culture. We implicitly use US culture when parsing returned rate. Pleasae check it
