### ISSUE TITLE
Add SQL Server index (Product_Category_Mapping, etc)

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2527]
I'm testing on database with >600000 products and >30000 categories
Using version 3.8

SQL Server load was around 60% CPU.
SQL Server monitoring suggested to add these indexes:
Product_Category_Mapping:
NON CLUSTERED on ProductId and IsFeaturedProduct including CategoryId
NON CLUSTERED on ProductId

Product_Picture_Mapping:
NON CLUSTERED on ProductId

These dropped server load sometimes to zero. And now it mostly runs 10-30%.
So its highly suggested.

**Comment by AndreiMaz** [comment]
@ArturAlekseev thanks a lot! done

**Comment by fsefacan** [comment]
This is very professional approach. Thank you @ArturAlekseev & @AndreiMaz
