### ISSUE TITLE
Issue after "BrowscapXmlHelper performance issue #1964"

### ISSUE THREAD

**Issue by DarthSonic** [nopSolutions/nopCommerce#2529]
Hi there. With the new UserAgentHelper changes there is a bug when UserAgent is not submitted in request. There will be a NullException on line 78 in UserAgentHelper.cs.

My fix is line 78:

return !string.IsNullOrWhiteSpace(userAgent) && bowscapXmlHelper.IsCrawler(userAgent);

**Comment by AndreiMaz** [comment]
@DarthSonic thank a lot!
