### ISSUE TITLE
Customers favourite categories

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#253]
Allow a customer to select categories as being their favourites. Our site sells ink cartridges, so customers usually select the category that sells cartridges for their printer to be their favourite. E.g. Canon MG5150 Ink Cartidges. This serves many functions.
1. They have a quick link from their account pages or homepage when logged in to their favourite category.
2. We can send them personalised email depending on what category they have as favourite.
3. We can restrict customer roles to only be able to see/buy from their favourite categories. This is good with B2B as the employee buyer can only purchase from favourite categories authorised when the account was created.

This feature is easy to implement in the Db. Only 1 table is required. A simple mapping table between customer and category. 

Customer -------------------∞ Customer_Category_Mapping ∞-------------------Category 

Additional Tasks:- 
-"Add to your favourites" button would be needed on product and product detail pages
1. Option in admin to AutoAddToFavoritesWhenPurchasedFrom would be useful (this is what we do now)
2. Menu in account pages to manage favourites would be required
3. The ability to customise email marketing campaigns to only include products that are in a customers favourite categories is very powerful and produces great results for us now. The customer only sees products in the email for their printer (favourite) so they take more note and are more likely to open and convert.

Any ecommerce site owner should be voting for this feature if they want to know what categories customers/potential customers are interested in, and who wouldn't want to know that? 

Forum source: http://www.nopcommerce.com/boards/t/14309/feature-suggestion-favourite-categories.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
