### ISSUE TITLE
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

### ISSUE THREAD

**Issue by ghd258** [nopSolutions/nopCommerce#2533]
Support for .NET Core 2.0 Razor Pages (replacement for MVC)

**Comment by AndreiMaz** [comment]
@ghd258 I think they are already supported as we moved to asp.net core 2. You can use them if you want

**Comment by bdongus** [comment]
@ghd258 Razor Pages are no replacement for MVC. They are built on top of it. So AndreiMaz is right. They should be usable.
