### ISSUE TITLE
Target all project framework to netcoreapp2.0

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2535]
Currently all projects target to framework 'net461'

**Comment by a-patel** [comment]
@AndreiMaz / @RomanovM any update?

**Comment by a-patel** [comment]
Some class library projects' have 'System.Web' dependency. 
e.g. CommonHelper, CommonController

**Comment by a-patel** [comment]
or open new issue to remove System.Web dependency?

**Comment by a-patel** [comment]
#2606

**Comment by AndreiMaz** [comment]
@a-patel thanks. we already did https://github.com/nopSolutions/nopCommerce/issues/2535

**Comment by a-patel** [comment]
@AndreiMaz 
Currently all nop projects are targeted to framework 4.6.1

see the .csproj file:

<PropertyGroup>
     <TargetFramework>net461</TargetFramework>
      ....
 </PropertyGroup>

it should be like this (for .net core 2.0): 

<PropertyGroup>
     <TargetFramework>netcoreapp2.0</TargetFramework>
      ....
 </PropertyGroup>

ref: 
libs:
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/Nop.Data.csproj
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Nop.Core.csproj
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Nop.Web.csproj
....
web:

**Comment by AndreiMaz** [comment]
@a-patel It's by design for 4.00. duplicated - https://github.com/nopSolutions/nopCommerce/issues/2492 (limitations described there_
