### ISSUE TITLE
Consider allowing to prefix table names

### ISSUE THREAD

**Issue by JeanCollas** [nopSolutions/nopCommerce#2536]
A simple config line could allow to prefix all table names generated by nopCommerce.
This "seems" quite easy as all tables seem to be generated using the NopEntityTypeConfiguration base class.
Changing all ToTable calls by ToPrefixedTable with an implementation like

    public EntityTypeConfiguration<T> ToPrefixedTable(string tableName)
    {
        return base.ToTable(_tablesPrefix+tableName);
    }

and feed the _tablesPrefix field from configuration should do the job :)

To make it even better, allow categorize the table names (Payment related tables, catalog, etc) so everything related to a topic could be found at the same place on the SQL Tables list.

    public EntityTypeConfiguration<T> ToNopTable(string tableName)
    {
        return base.ToTable(TablePrefix(typeof(T))+tableName);
    }

But this implies some dev contrary to the previous request. I can provide with a proposal for the implementation if it can speed up the process. But I need to learn your conventions first :)
#

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box

**Comment by JeanCollas** [comment]
Too bad, it would have allowed to use nopCommerce as a service... 
Not interfering with existing content (would have been easier to install nopCommerce on an already existing website).
However I understand the stored procedures issues...
