### ISSUE TITLE
Quick search in admin area. Include plugins

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2539]
Allow to search in plugins (like we do for other menu items). Search in plugin friednly names only. Ensure they results include only plugins with configuration pages (so when clicked it redirects to this configuration page). And ensure appropriate permissions are validated (ACL)

Ensure that it works fine with chars such as ' or "

Put them at the end of found menu items (search results)

**Comment by RuS984** [comment]
#2539 Closed
