### ISSUE TITLE
Add some fields for China customer (move phone to "Customer" table, add "county" support)

### ISSUE THREAD

**Issue by six006** [nopSolutions/nopCommerce#2540]
I have used nopcommerce for several years,every time when upgraded we should add some general extension,

- Add Phone Number field in customer table
In China people usually use  phone number login, can nop team add this field in the customer class.
Also there are many workflow need to change. sms message template.

- Add county field in address table

In China people often use three dropdown selector  to select province,city and county

Also we can set default country,province and city  ,
if the commerce used in only one county we can hide the country field.

**Comment by rujianwang** [comment]
+1

**Comment by marklinapple** [comment]
+1
