### ISSUE TITLE
Decide what to do when wrong plugin directory is uploaded

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2544]
When "mainPluginFile" is null in \Nop.Core\Plugins\PluginManager.cs, then exception is thrown. For example, it could happen when "Source code" version of a plugin is upload instead of the compiled one.

Let's think what we should better do. Ignore such plugins? Something else? Ideas?

Previously a store owner usesd FTP only. So he could easily delete a wrong directory. But now when we support uploading in admin area, it could be a problem for some store owners

**Comment by skoshelev** [comment]
Closed #2544
