### ISSUE TITLE
ASP.NET Core. Allow to inject custom view engine

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2545]
We are very excited about the new Core 2 version of nopCommerce and have been following the development closely, as a plugin developer we are having some issues finding a solution to replace the old Custom ViewEngine and wondered if anyone has come up with a new solution to replace it.

Source: https://www.nopcommerce.com/boards/t/48601/core-2-custom-viewengine.aspx

**Comment by RomanovM** [comment]
There are already ready-made interfaces for view engines (IViewEngine, IRazorViewEngine, etc) in the asp.net core that you can implement and register in the application, so there is no need to additionally add anything for it.
