### ISSUE TITLE
Shipping by Volume & Shipping by Price

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2550]
We have Shipping by Weight.
We need to add ability to shipping by Volume(Length x Width x Height).
And ability Shipping by Product price( for example, if product price from 0-100$ price is 2$, if price from 101-200$ price is 1$, if more then 200$ is free shipping )

Total Shipping price= (Shipping by Weight + Shipping by Volume + Shipping by Price)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan we already have price (subtotal) in our roadmap. All the rest should be done in plugins

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Now we have Plugin "Manual (Fixed or By Weight)" . Can we add this ability to that plugin?
And rename it "Manual (Fixed or By Weight/Volume/Price)"

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Can we reopen with new Title("Manual (Fixed or By Weight)" plugin add By Volume and By Price)?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan for price we have this work item (https://github.com/nopSolutions/nopCommerce/issues/1955). I've added a link to this one to it
