### ISSUE TITLE
Pictures are stored into...	URL Support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2563]
Add ability to have NopCommerce Web server and File Server for pictures.
Now we can store Picture in 1.Database and 2.Local File System
Add ability to store pictures to external Server File System and access to pictures with URL.
In Databese we can put only Picture URL's or URI's(if on local).

**Comment by ljesquivesgh** [comment]
Hi, maybe you can use a CDN plugin, there are some free.

________________________________

**Comment by adiprisacariu** [comment]
@ljesquivesgh  can you give us some links with CDN plugins for nopCommerce?

**Comment by ljesquivesgh** [comment]
I found this free plugin http://www.nopaccelerate.com/nopcommerce-plugins/nopaccelerate-cdn/

**Comment by clearbucketLabs** [comment]
@ljesquivesgh I didn't know $149 was considered Free....

**Comment by AndreiMaz** [comment]
@tigran-avdalyan thanks! but it could quite complex in terms of performance (network request). especially when we need to resize a picture
