### ISSUE TITLE
Display a link to the search page at the bottom of Autocomplete search result list if more than X number of products are found

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2566]
to show your user that there are more products which were not displayed in the list.

var result = (from p in models
select new
{
    label = p.Name,
    producturl = Url.RouteUrl("Product", new { SeName = p.SeName }),
    productpictureurl = p.DefaultPictureModel.ImageUrl,
    //add this line to retrieve total products
    productNumber = products.TotalCount
})
.ToList();

Nop.Web\Views\Catalog\SearchBox.cshtml, Line 23 (replace or edit):

<script type="text/javascript">
    $(document).ready(function() {
        var i //get number of products returned;
        var searchText //get value in textbox user typed;
           $('#small-searchterms').autocomplete({
              delay: 500,
              minLength: @(Model.SearchTermMinimumLength.ToString()),
              source: '@(Url.RouteUrl("ProductSearchAutoComplete"))',
              appendTo: '.search-terms',
              select: function(event, ui) {
              $("#small-searchterms").val(ui.item.label);
              setLocation(ui.item.producturl);
              return false;
              },
              //this does the work - append link to the end of list
              open: function(event, ui) {
                 //display link to search page if product number greater than x (set any number according to your autocomplete settings, here I have set to 9)                               
                 if(i > 9){
                    //get string user has entered
                    searchText = document.getElementById("small-searchterms").value;
                    //add class to li and style how ever you like
                    $(".ui-autocomplete").append("<li class=\"link-to-searchpage\"><a href=\"/search?q="+searchText+"\">View all results...</a></li>");
      }
              }
            })
            .data("ui-autocomplete")._renderItem = function(ul, item) {
                  var t = item.label;
                  //get total number of products found
                  i = item.productNumber;
                  //html encode
                  t = htmlEncode(t);
                  return $("<li></li>")
                  .data("item.autocomplete", item)
                  .append("<a>@(Model.ShowProductImagesInSearchAutoComplete ? Html.Raw("<img src='\" + item.productpictureurl + \"'>") : null)<span>" + t + "</span></a>")
                  .appendTo(ul);
             };
         });
</script>

Source: https://www.nopcommerce.com/boards/t/48728/how-to-improve-searchbox-autocomplete-and-sidebar-ux.aspx

**Comment by DmitriyKulagin** [comment]
Closed #2566
