### ISSUE TITLE
Add Id field to Product attributes list and their options, Specification attributes list and their options on admin area

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#2567]

**Comment by tigran-avdalyan** [comment]
We can don't add id field,  but support import/export prouct attributes and specification attributes whith id in excel/xml .
Now we can't impor/exportt product attributes or specification attributes.

**Comment by tigran-avdalyan** [comment]
@skoshelev @andreymaz what You think about "Add Id field" or issue #2047

**Comment by tigran-avdalyan** [comment]
now we have
![image](https://user-images.githubusercontent.com/17789934/30819031-7e76b3de-a22e-11e7-811c-ef03fc59b914.png)
We need to find SpecificationAttributeOptionId in database

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. Furthermore, it's done only once and it's possible to get ID from database

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Why You think it's done only once?
if we need get ID from database, we can disable all import/export functions and share SQL script for importing/exporting directly in sql server))

**Comment by tigran-avdalyan** [comment]
@AndreiMaz  in most of issues Your answer is "After some discussion decided not to implement it out of the box." . Can Nopcommerce community be a part of discussion ?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan sure, we always welcome discussion. but this is no we're going to implement out of the box.
