### ISSUE TITLE
Vendors per store

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#257]
When I was setting up a vendor today in nop 3.4 there was not a place to say that a vendor should have access to certain stores. However, when you log in as a vendor and add a product they have access to the "Stores" tab and can give themselves access to any store. I believe that the store owner should be able to assign vendors to have access to certain stores and then when a vendor is adding product they can only select from the stores they have been given access to. 

Source: http://www.nopcommerce.com/boards/t/31391/enhancement-request-vendors-should-be-assigned-stores.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
