### ISSUE TITLE
Display product Availability on shopping cart page (configurable)

### ISSUE THREAD

**Issue by moniqueh** [nopSolutions/nopCommerce#2571]
Need my customers to be able to view a product's Availability (estimated factory lead time) during the checkout process without having to open up the individual product pages again. 

Would like Availability displayed on the "Cart preview" page, as well as during the "confirm order" checkout page. 

Example here
![2017-09-19_1518](https://user-images.githubusercontent.com/32110863/30613519-02c27e56-9d4e-11e7-9a89-fd572a82d1ab.png)

**Comment by AndreiMaz** [comment]
we do not plan to implement such functionality out of the box. leave it for customization as it's quite specific
