### ISSUE TITLE
Can't compile the code

### ISSUE THREAD

**Issue by MagicMaxxx** [nopSolutions/nopCommerce#2573]
Hello

I've downloaded Nop code from GIT and can't build the solution. Output is:

1>------ Build started: Project: Nop.Web, Configuration: Debug Any CPU ------
1>Nop.Web -> C:\Users\Maxim\Source\Repos\nopCommerceVS2017\nop\src\Presentation\Nop.Web\bin\Debug\net461\Nop.Web.exe
1>C:\Users\Maxim\Source\Repos\nopCommerceVS2017\nop\src\Build\ClearPluginAssemblies.proj(91,5): **error MSB4044: The "NopClearPluginsPath" task was not given a value for the required parameter "Paths".**
1>Done building project "ClearPluginAssemblies.proj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

**Comment by ChrisJollyAU** [comment]
I've seen that before and while I'm not sure exactly what is going on, I do have a possible workaround.

For me if I get that message the trick is to build at least 1 plugin. Thereafter everything builds with no errors

**Comment by skoshelev** [comment]
This issue fixed by #2547.

**Comment by skoshelev** [comment]
Closed #2573
