### ISSUE TITLE
Add async support for events

### ISSUE THREAD

**Issue by shurub3l** [nopSolutions/nopCommerce#2574]
There are performance issues, because the code runs synchronously in the event consumers. For example, if a plugin does many things in the OrderPlacedEvent consumer, then the customer needs to wait a long time before getting the order confirmation page.

**Comment by AndreiMaz** [comment]
@shurub3l thanks! duplicated work item

**Comment by shurub3l** [comment]
What is the issue number? I can't find it.

**Comment by AndreiMaz** [comment]
@shurub3l it's part of this work item (https://github.com/nopSolutions/nopCommerce/issues/2287). Sorry that it's not implicitly mentioned there

**Comment by shurub3l** [comment]
Ok. Thanks.
