### ISSUE TITLE
The widget zone should be passed to the widget component's Invoke method.

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2575]
The widget zone should be passed to the widget component's Invoke method.

public IViewComponentResult Invoke(string widgetZone)

There are many plugins that could be integrated in multiple widget zones and provide different functionality depending on the widget zone. For example in our Anywhere Sliders plugin you can have many Sliders and have each Slider added to a different widget zone. So without knowing the current widget zone in the Invoke method we will not be able to determine which Sliders to show (we can't show each Slider in every supported widget zone).

Thank you in advance!

Source: https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx

**Comment by poyker** [comment]
This is no working properly when you pass some additionalData.
For example if you pass the ID of the model let's say the category id the additionalData is a simple int value i.e 1. Then with the current implementation the additionalData is simply lost when it is passed to the constructor of the dictionary: new RouteValueDictionary(**additionalData**)
Then in the Invoke method of the component if you have a parameter additionalData it will be null i.e Invoke(string widgetZone, object **additionalData**)

The code should be like this:

//add widget zone to view component arguments
            additionalData = new RouteValueDictionary()
            {
                { "widgetZone", widgetZone },
                { "additionalData", additionalData }
            };

This way the passed additionalData will be available in the Invoke method.
