### ISSUE TITLE
Product Full description pagination support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2577]
In product page Full description mast have pagination if text is to long.

**Comment by ngtrian** [comment]
I think a button Read more for this

**Comment by tigran-avdalyan** [comment]
@ngtrian a button Read more, if we have 2 pages, but if more pagination is better .

**Comment by Xzelsius** [comment]
For nopCommerce default theme a 'read more' button will be sufficient. I don't see why there should be a pagination.

And if you're not using the default theme,  implement it.

**Comment by AndreiMaz** [comment]
agree with @Xzelsius

**Comment by tigran-avdalyan** [comment]
@AndreiMaz  in Default theme we have 'read more' button for Product Full description?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan no. it's left for customization. but I've jsut created a new work item (https://github.com/nopSolutions/nopCommerce/issues/2616) not to lose this idea

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Thanks

**Comment by tigran-avdalyan** [comment]
Example: https://ellislab.com/asset/images/blog/ajax-pagination.gif
