### ISSUE TITLE
Accept negative discounts and include description for each discount

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#258]
In promotion>discount accept negative discounts in percentage and amount. With this simple change the discount feature, which is very flexibel and powerful, could be used to set some special charges under certain conditions. Check this (http://www.nopcommerce.com/boards/t/16596/add-new-fee-in-shopping-cart-payment-percentage-of-sub-total.aspx) 

It would be nice too if discounts to total or subtotal could be detailed separately with a short (i.e. 30 characters) description for each discount. 

Forum source: http://www.nopcommerce.com/boards/t/16642/accept-negative-discounts-and-incude-description-for-each-discount.aspx 
http://www.nopcommerce.com/boards/t/16596/add-new-fee-in-shopping-cart-payment-percentage-of-sub-total.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
