### ISSUE TITLE
Make highlight for menu current active in topmenu

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#2581]
Make highlight for menu current active in topmenu  when view a category or a product.
![image](https://user-images.githubusercontent.com/4327817/30737735-dbe14d38-9fb1-11e7-8224-d8dc1d24389b.png)

**Comment by AndreiMaz** [comment]
@ngtrian thanks! but it's not planned

**Comment by bhumikaverve** [comment]
Hi,
Can you please provide example for this functionality?
