### ISSUE TITLE
Category preview don't show Description

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2583]
When we edit a Category and write text in Description, in preview mode Description not show.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Hi Tigran, could you please provide a complete list of steps to reproduce the issue

**Comment by tigran-avdalyan** [comment]
1.i create a category with name "test" and save it.
2. i edit a created category and add Description "test description" and click preview button.
3. In preview page I don't see a Description text.
4. But when i save it, i see Description text.

In Result preview don't work with Description.
P.S.

Same situation in product Short and Full Descriptions .

**Comment by AndreiMaz** [comment]
Thanks! But it also doesn't work for name, price, etc. It's not the bug. It works only for already saved products (but unpublished yet). Versioning is not supported yet
