### ISSUE TITLE
Allow to delete plugins (admin area)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2587]
Now we support plugin uploading. Let's also add "Delete" button to the plugin list page. But enable this functionality only when a plugin is uninstalled. It should be visible for oninstalled plugins only. This way a store owner has to uninstall it first, hence remove appropropriate tables, etc. 

Also add a confirmation window to this functionality. Once the plugin is deleted we have to restart the site.

**Comment by eadameg** [comment]
It must read: "It should be visible for **un**installed plugins"._

**Comment by AndreiMaz** [comment]
@eadameg sure! Thanks!

**Comment by skoshelev** [comment]
Closed #2587
