### ISSUE TITLE
Refactor so that plugins can encrypt/decrypt settings.txt

### ISSUE THREAD

**Issue by mmccann-umph** [nopSolutions/nopCommerce#2589]
Would a pull request be accepted that refactors the code such that DataSettingsManager is injected rather than hardcoded.  

Doing this would allow the creation of a plugin that encrypts/decrypts settings.txt, enhancing security by no longer storing an unencrypted connection string with username and password on the file system in plain text.

Thank you!

**Comment by AndreiMaz** [comment]
@mmccann-umph sure. please contribute.

**Comment by mmccann-umph** [comment]
Will do, thanks!

**Comment by a-patel** [comment]
suggest you (@mmccann-umph and @AndreiMaz) use json (settings.json) file instead of text file.

**Comment by AndreiMaz** [comment]
@a-patel thanks! we've also thought about it - https://github.com/nopSolutions/nopCommerce/issues/2597

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. IT can cause issues when a new data protecion keys are generated, etc
