### ISSUE TITLE
Auto update ability (including plugins)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#259]
It would be great if nopCommerce implemented an Auto Update functionality so when bugs are fixed, plugins available or any other important update is carried out, we don't have to wait for the next major release in order to have our issues fixed 

There should be a setting allowing to enable/disable it

For example, in version 3.90 our Facebook plugin has been broken

Forum source: http://www.nopcommerce.com/boards/t/14964/auto-updates.aspx and http://www.nopcommerce.com/boards/t/39398/can-you-develop-an-automatic-upgrade-procedure.aspx

**Comment by isaacmananes** [comment]
That would be great, giving full access to nopCommerce to non technical users, that in my experience reject nopCommerce due to the expensive cost of support if they need support every time nopCommerce gets an upgrade.

**Comment by tigran-avdalyan** [comment]
http://www.nopcommerce.com/boards/t/47079/more-frequently-updates.aspx

**Comment by AndreiMaz** [comment]
not in the near years
