### ISSUE TITLE
How to override Plugin view in theme ?

### ISSUE THREAD

**Issue by xiaoyc** [nopSolutions/nopCommerce#2590]
Hi .

Now I want to override the NivoSlider  plugin view in my own theme , it seems the plugin view return physical path ,it only search the plugin folder , so  is it possible to make the view themeable  ,like ~/{Theme}/Plugins/Widgets.NivoSlider/Views/PublicInfo.cshtml' ?

i am using nop 4.0 (not released ).

InvalidOperationException: The view 'Components/WidgetsNivoSlider/~/Plugins/Widgets.NivoSlider/Views/PublicInfo.cshtml' was not found. The following locations were searched:
~/Plugins/Widgets.NivoSlider/Views/PublicInfo.cshtml

Thanks very much !

**Comment by AndreiMaz** [comment]
@xiaoyc pease psot all questions on our forums
