### ISSUE TITLE
"System Information" page. The dates for the assemblies are very strange and very different

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2594]
Visit "System -> System Information" page. The dates for the assemblies are very strange and very different i.e years could be 1969, 1909 etc.

Microsoft.AspNetCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 Release
C:\DEV\nopCommerce_4.0\Presentation\Nop.Web\bin\Debug\net461\Microsoft.AspNetCore.dll
1969-11-18T23:31:51

This is a bit confusing as most of us were not born in 1909 ;)

Source: https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx?p=2#193747

**Comment by skoshelev** [comment]
Closed #2594
