### ISSUE TITLE
Missing locales

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2596]
admin.configuration.settings.generalcommon.blocktitle.adminarea
admin.configuration.settings.generalcommon.adminarea.usericheditorinmessagetemplates

Source: https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx?p=2#193747

**Comment by skoshelev** [comment]
Closed #2596 (https://github.com/nopSolutions/nopCommerce/commit/3f29612ce7cfd48208f5f58272c71535b1bb8c81)
