### ISSUE TITLE
Log ALL errors

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2599]
I am not sure if this is made on purpose but we noticed that in many cases when we have some errors they are not logged in the System -> Log.

Here are some cases in which there is an error but it is not logged in the Log and is quite hard to investigate what is wrong.

- if a Razor view could not be found when doing Ajax calls. You can see the error in the Response in the Network tab in the browser but no error is being logged in the Log. The same is about standard requests

- Missing AntyForgeryToken in Ajax requests. Again no error in the Log (and no details for the error in the response in the browser as you just get bad request 400 error).

I am sure there are other cases when errors are not logged in the Log.

In the previous version of nopCommerce all errors were logged in the System -> Log.

This is quite important for troubleshooting any nopCommerce problems. 
When our clients have any problems we usually ask them to check the Log for any errors that usually help us to understand what is wrong and advise them. If this functionality is missing in nopCommerce 4.0 then the support of nopCommerce will be much harder and more time consuming.

If you need help with this issue please let me know and we can investigate further what could be done to improve the error handling logging as it is very very important!

Source: https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx?p=3#193823

**Comment by poyker** [comment]
In addition to the ViewNotFound we should log also Log when a view could not be compiled. If someone has made some modifications in the Razor files that could not be compiled and the view is accessed the error should be logged in the Log as well. Or if the wrong view is loaded and a different model is passed you will still get a compilation error that needs to be logged.
