### ISSUE TITLE
External authentication cannot be nested in customer registration form tag

### ISSUE THREAD

**Issue by wezzix** [nopSolutions/nopCommerce#2603]
There is a severe issue with external authentication that uses own form tags on customer registration page (we have custom authentication using a form and a couple of inputs and a submit button). In 3.90, this works fine on Login page, because the login form is separate. But on **customer registration** page, the **BeginForm** extends over the whole page and **overlaps with external-authentication** at the bottom. So the forms interfere with each other with validation and submit url, making both registration and ext auth unusable. **_Form tags cannot be nested!_**

I request that the **external-authentication block** on the **customer registration page** as default **be moved outside the BeginForm**.

Origin: #1771

**Comment by AndreiMaz** [comment]
@wezzix thanks a lot! done
