### ISSUE TITLE
Invoking a view component as a Tag Helper

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2609]
<vc:[view-component-name]
  parameter1="parameter1 value"
  parameter2="parameter2 value">
</vc:[view-component-name]>

instead of

@await Component.InvokeAsync("PriorityList", new { maxPriority = 4, isDone = true })

ref: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components

**Comment by a-patel** [comment]
Or Avoiding magic strings from component invocation.
use
@await Component.InvokeAsync(nameof(BlogMonths))

instead of 
@await Component.InvokeAsync("BlogMonths")

**Comment by a-patel** [comment]
but option 1 (tag helper) is preferable

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave the current implementation
