### ISSUE TITLE
TopicSystemName equality check with exact case may occur some problems. 

### ISSUE THREAD

**Issue by kipergil** [nopSolutions/nopCommerce#2610]
https://github.com/nopSolutions/nopCommerce/blob/755772e1009546204ab5fccaf2dc3191b95a7ce0/src/Libraries/Nop.Services/Topics/TopicService.cs#L129

We can change those lines smt. like 

`query = query.Where(t => t.SystemName.Equals(systemName, StringComparison.OrdinalIgnoreCase));
`

**Comment by AndreiMaz** [comment]
@kipergil Hi Mustafa! It's done in database. And nopCommerce requires SQL Server database to be case invariant. So it's always case invariant when filtering in DB
