### ISSUE TITLE
Support "Volume" in Measures

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2614]
Now we have Dimensions, Weights but not have Volume.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan I understand what you mean. But how exactly will it be used? I mean logic (e.g. price change, something else, etc). And I'm also talking about shipping plugins that don't support volumn. All they need is dimention and weight.

**Comment by tigran-avdalyan** [comment]
Volume all sellers use in combination Volume-Price (like Weight-Price and else).

Volume use in shipping, seller can calculate cost of shipping By Volume, By Weight, By Total Price, or with their SUM.
All Shipping provider use Volume with Weight.

Example: product1 with Size 5m X 5m X 5m    with weight 3kg
product2 with Size 5cm x 5cm x 5cm with weight 3kg 

in this functionality we have By Weight and Fixed.
and 2 product have same shipping cost :
or we need manually write additional shipping cost:(this not easy if we have many items)

How we can calculate the item SIZE and include it in shipping price:


Situation: I sale Liquid
Dimention i cant use(because i sale Liquid but not Liquid in bottle).
And i dont want use only weight, because in all world liquid selling by VOLUME:
P.S. 
You see Coca-Cola by Weight?
1 Kg Coca-Cola?

**Comment by tigran-avdalyan** [comment]
My shipping provider calculate whit this function
Shipping price= (Weight price+Volume price)-Bonus of Total Price

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
