### ISSUE TITLE
Add Volume and Dimensions parameters in PangV

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2615]
Now in PangV we can choose Price-Weight combination.
We need to add combinations Price-Volume, Price-Lenght (Dimensions)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan I'm not sure the German laws use it (PangV is used mostly in Germany)

**Comment by tigran-avdalyan** [comment]
I use PangV function because i sale FOOD and i don't live in Germany))
10 gram Product 1 - price is 150$ 
1 gram Product 2 -  price is 20$
and i sale Liquid my Volume (in all world Liquid sale by Volume)
1 liter Liquid 1 - price is 10$
1 gallon  OIL(in USA )
1 barrel Petroleum(in all world)

i think PangV function is not only for Germany.

and i think Volume using in selling like Weight

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin
