### ISSUE TITLE
Discount by Total Price, By Quantity

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2617]
Ability to add Discount connected to total price or quantity, Example if You buy (in one order or range of date) items with total price more then 1000$ you have discount 5%.
Or if you buy 10x(Current product) you have discount 3%.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan  Thanks a lot for suggestion!

1. such discount requirement plugin already exists
2. it can also be achienved with new requirement plugins. but we plan to have minimum number of plugins available out of the box (this github issue tracker is only for "out of the box" tasks)

**Comment by tigran-avdalyan** [comment]
NopCommerce Team not planing create github issue tracker for plugins created by NopCommerce team?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan All of our plugins are available at https://github.com/nopSolutions (source code)
