### ISSUE TITLE
Product Attributes - Edit Design is True?

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2619]
![edit](https://user-images.githubusercontent.com/17789934/31279232-669c472c-aab9-11e7-8555-f81ad3090323.gif)

**Comment by tigran-avdalyan** [comment]
Disable scroll left-right situations, its not User-Friendly.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan what is your screen resolution? Browser?

**Comment by tigran-avdalyan** [comment]
Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Resolution 1366x768

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2620
