### ISSUE TITLE
Upsell products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#262]
We already have related products support. But usually related products are meant to be purchased in addition to the item the customer is viewing. And upsells for this product are items that your customers would ideally buy instead of the product they’re viewing. So just need to rename existing related products to upsells. These upsells will be displayed the same way (just boxes on the product details page). And create a new implementation of related products which will also be displayed on the product details page but with checkboxes (like it's done in magento)

Forums source: http://www.nopcommerce.com/boards/t/14565/new-feature-upselling.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
