### ISSUE TITLE
KendoUI design issues

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2620]
![edit_resize](https://user-images.githubusercontent.com/17789934/31280425-5da76eae-aabd-11e7-89e5-bfba2d213465.gif)

Although not sure that we should fix issues of third-party controls

**Comment by tigran-avdalyan** [comment]
can we do more User-Friendly?
Like this
https://js.devexpress.com/Content/images/doc/15_1/DataGrid/EditingCellMode.gif

**Comment by tigran-avdalyan** [comment]
example:
http://demos.telerik.com/kendo-ui/grid/editing

**Comment by AndreiMaz** [comment]
@tigran-avdalyan It works fine on my computer. What browser and screen resolution are you using?

**Comment by tigran-avdalyan** [comment]
Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Resolution 1366x768

**Comment by AndreiMaz** [comment]
we mvoe away from KendoUI. So closing this issue

**Comment by a-patel** [comment]
@AndreiMaz 
What is next? I mean the alternative of KendoUI for Nop?

**Comment by AndreiMaz** [comment]
@a-patel DataTables
