### ISSUE TITLE
Mark(fill with color or else) bulk edited Volume containers 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2621]
![grid_batchedit 1](https://user-images.githubusercontent.com/17789934/31281396-5e08b5e4-aac0-11e7-86dd-fa81d55a26c3.gif)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan thanks. the question is whether KendoUI Grid supports it

**Comment by tigran-avdalyan** [comment]
i think about #75

**Comment by AndreiMaz** [comment]
@tigran-avdalyan yeah, in this case you're right

**Comment by tigran-avdalyan** [comment]
@AndreiMaz can we update Kendo UI to version 2017.2.504 ??

**Comment by AndreiMaz** [comment]
@tigran-avdalyan no. it doesn't include the grid. please find more at https://www.nopcommerce.com/boards/t/29633/using-kendo-ui-legal.aspx?p=8#194478

**Comment by tigran-avdalyan** [comment]
@AndreiMaz what about  https://github.com/DevExpress/DevExtreme ?

**Comment by AndreiMaz** [comment]
@tigran-avdalyan not sure that our licenses are compatible (For free) - https://js.devexpress.com/Licensing/

**Comment by AndreiMaz** [comment]
moved as comment to https://github.com/nopSolutions/nopCommerce/issues/75
