### ISSUE TITLE
Add availability option to IProductService.SearchProducts method

### ISSUE THREAD

**Issue by Jalalx** [nopSolutions/nopCommerce#2627]
Hello
Is there any option to limit product search result to available items? An available item is a product that has `StockQuantity` greater than zero. 

`var availableProducts = products.where(product => product.StockQuantity > 0);`

If there is no such option, I can add it to both `ProductLoadAllPaged` stored procedure and LINQ expression in `ProductService.SearchProducts` method.

Here is my suggested procedure signature:

```
ALTER PROCEDURE [dbo].[ProductLoadAllPaged]
(
... /*other parameters */,
@AvailableOnly bit = 0, -- limit to available products.
)
AS
/* lots of code */
IF @AvailableOnly = 1
BEGIN
   SET @sql = @sql + '
   AND p.StockQuantity > 0';
END
/* rest of code */

```

@AndreiMaz if you are OK with this, or have any suggestion, please let me know. I'll send a pull request.

**Comment by Xzelsius** [comment]
You should consider calculate stock quantity using Product.ManageInventoryMethodId and Product.UseMultipleWarehouses.

**Comment by Jalalx** [comment]
@Xzelsius  Yes, I can put stock quantity logic inside Stored Procedure.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization. Furthermore, this is an option to hide unpublish products below some low qty
