### ISSUE TITLE
[error] not founded result with keyword "levono" 

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#2628]
The search for "lenovo" can not be found on the demo site nopCommerce and my website

![image](https://user-images.githubusercontent.com/4327817/31346550-ab0a9bca-ad43-11e7-83d6-c21a29d74d61.png)

**Comment by AndreiMaz** [comment]
it works fine
![1](https://user-images.githubusercontent.com/5019111/31346832-1b86f716-ad23-11e7-9701-da66d95720ba.png)

**Comment by AndreiMaz** [comment]
@ngtrian actually you type another word (other chars)
