### ISSUE TITLE
Site Status Pages

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#263]
I would like to be able to set the status of site as such: Live, Maintenance, Closed, Preview Mode. Live would simply have the site available as normal, nothing special there. Maintenance and Closed would allow the admin to create a message to be displayed to anyone that browses to the site using a WYSIWYG editor. This is similar to the current closed state, but allows the admin to set different messages depending on the status and could be set from the admin site. Preview would all the admin to also create a message using a WYSIWYG editor, but also assign a password that they can distribute to whoever they want to in order to preview the website. This is useful to provide feedback before going live with a site redisign, etc. 

Source: http://www.nopcommerce.com/boards/t/13566/feature-request-site-status-pages.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
