### ISSUE TITLE
Setting to ignore tax calculation

### ISSUE THREAD

**Issue by ivanslater** [nopSolutions/nopCommerce#2630]
Hi.

Once some countries dont require tax on products and on orders, we should be able to disable all tax calculations routines on nop configuration, like a "taxsettings.taxcalculationenabled" setting.

It should add some performance on nop once a lot of process should be ignored, when tax is not required.

**Comment by AndreiMaz** [comment]
@ivanslater could you please provide some examples of such countries?

**Comment by ivanslater** [comment]
Sure, Brazil for example. Taxes are paid by the stores, not by customers, and tax is always in price value, we dont use to display tax values to customers. They see product price, for example 10us and it is the final price. Once invoice is created, store owner has to pay the tax to government. It is calculated over order total price and the tax % depends on several store parameters. So, here in Brazil we do not use to calculate tax before orders. Thats why you can set it as configurable, so here and other countries can have some performance advantage.

**Comment by AndreiMaz** [comment]
I don't believe it's really required to such setting. Just delete all tax plugins.
