### ISSUE TITLE
Rename all event classes

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2631]
e.g. EntityDeleted -> EntityDeletedEvent

**Comment by a-patel** [comment]
@RomanovM 
can we use [MediatR](https://github.com/jbogard/MediatR) for entity events?
i think, this is better approach.

**Comment by RomanovM** [comment]
@a-patel Why do you think it would be better to use a third-party library to implement the event mechanism? What are the benefits? What is missing in the current approach?
P.S. Moved the discussion into the new issue https://github.com/nopSolutions/nopCommerce/issues/2785
