### ISSUE TITLE
Need filter by category on the manufacturer page

### ISSUE THREAD

**Issue by pdunleavy** [nopSolutions/nopCommerce#2633]
A common customer requirement we have is to be able to filter by product category on the manufacturer pages. Example.. Gucci make dresses, shoes, jewelry etc. If a customer lands on a manufacturer page they will be faced with a random selection of these products and no way to filter them. If they select a category and navigate to the category page it will include all manufacturers as the filter context is not passed to the page. This is leading to a high bounce rate on the manufacturer pages but we need them for SEO. This makes manufacturers pages a bit pointless unless your site only sells one category of product e.g. shoes.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin. Furthermore, it's already possible on the search page
