### ISSUE TITLE
Allow for schedule tasks to run at a defined time (contribution)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2638]
Source: https://www.nopcommerce.com/boards/t/49063/schedule-tasks-in-nopcommerce-40.aspx#194545

**Comment by kryptus47** [comment]
It is a pitty that this feature has been put on the side, this is absolutely something usefull. 
I would add this feature as well as task depedencies, so one task might trigger several other tasks to run in a defined order.
