### ISSUE TITLE
Multiple "Content" items included in nop.web *.dll.config when plugin has App.config present

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2639]
I am writing a plugin for nopcommerce that references some other projects that include app.config files. With the current develop branch the following line (Nop.Web.csproj line 41)
`<Content Include="Plugins\**" CopyToPublishDirectory="PreserveNewest" Exclude="Plugins\**\*.cshtml;Plugins\**\*.json;" />`

Causes namespace.dll.config to be included as content multiple times. I propose we change the above line to:

`<Content Include="Plugins\**" CopyToPublishDirectory="PreserveNewest" Exclude="Plugins\**\*.cshtml;Plugins\**\*.json;Plugins\**\*.config" />
`
Can this change be merged into the current develop branch?

**Comment by AndreiMaz** [comment]
@rolandh what version? 4.00?

**Comment by rolandh** [comment]
4.00

**Comment by AndreiMaz** [comment]
@rolandh thanks a lot! fixed

**Comment by rolandh** [comment]
Great! Thanks for the quick turn around.
