### ISSUE TITLE
Reseller Portal

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#264]
The creation of a Reseller (or "Partner") Portal where resellers can register customers and order on a customers behalf.

The portal should allow the Partner to see only customers associated with them and orders only they have processed. A Partner Resources section where they can get logos, product descriptions etc would be helpful. Resellers are most useful for overseas and often foreign language sales. 

Resellers purchase products at a discount and have the ability to turn off customer notifications about registration and also the option to hide order information (i.e,. the price paid) from the customer. Resellers whom separately bill the customer can then order products under their own pricing arrangements and can arrange for direct delivery either to the reseller or the customer. 

In the case of downloadable products, the customer can login and download the product, but the reseller can't access the customer download, unless permitted by the store owner. 

Ideally Partners would be organised in separate classes with different administration rights depending on classes. eg. A "Distributor" might have the ability to refund orders, a basic reseller may not. 

This can actually be done using a mashup of the Administration Interface combined the "Affiliate" functionality ("Partner" is a much better term). We have done this by hacking the code a bit which means it is not appropriate to share - it needs to be done properly. 

The result was support for both "Affiliate" and "Reseller" management in one place. Both can login and seeeither how their Affiliate program membership is going or in the case of resellers can administer most features of the affiliated customers (affiliates only see customer name) .

**Comment by adminkaa** [comment]
it's very important

**Comment by samdubey** [comment]
+1 for this

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/31
