### ISSUE TITLE
Redis object serializing problem

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2642]
There is a problem with serializing domain objects when using Redis in the project. This problem is caused by the fact that the navigation elements are not marked as [JsonIgnore].

**Comment by AndreiMaz** [comment]
@fsefacan what version are you using? Please share the entire error stack

**Comment by fsefacan** [comment]
@AndreiMaz I'm using version 3.90.
I got the error information below


> StackExchange.Redis.RedisServerException: ERR Protocol error: invalid bulk length

**Comment by AndreiMaz** [comment]
@fsefacan what exactly entity do you try to serialize? Derived from BaseEntity?

**Comment by fsefacan** [comment]
@AndreiMaz I added multiple price features to the discount table.

I created a table named **DiscountPrice** for this and added it as a `public virtual ICollection <DiscountPrice>` in the **Discount** table.
 In the **DiscountPrice** table I also added the object as `public virtual Discount`. I started to get the fault after that. 

DiscountPrice is derived from BaseEntity.

**Comment by AndreiMaz** [comment]
So it's not the bug (at least not reproducable out of the box). BaseEntity should NOT be serializable because EF doesn't support 2-level caching. Just ensure that your custom entity (and its childs) is serializable
