### ISSUE TITLE
Move jQuery library to the footer (public store)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2644]
We already have other libraries and inline scripts moved to the footer. Should we do it for jQuery?

Just ensure that it'll work fine for \Views\Shared\ _CreateOrUpdateAddress.cshtml which has inline script without moving it to the footer. It should be ignored as it's used in AJAX requests on one-page checkout (e.g. billing and shipping address). This file doesn't have head and footer, hence we cannot move it. For example, states won't be loaded on the billing address step during checkout when you change a country

Ideas?

**Comment by Xzelsius** [comment]
Maybe try to refactor inline scripts into dedicated script files?
I think of something like bootstrap does it.

Instead of inline script you could use data-attributes and initialize handlers in that dedicated JS file which will be loaded after jQuery.

Take this as a sample of what i mean

**_CreateOrUpdateAddress**
` <select asp-for="CountryId" asp-items="Model.AvailableCountries" 
                    data-trigger="country-select" 
                    data-url="@(Url.RouteUrl("GetStatesByCountryId"))" 
                    data-stateprovince="#@Html.IdFor(model => model.StateProvinceId)" 
                    data-loading="#states-loading-progress"></select>`

**public.countryselect.js**
`+function ($) {
    'use strict';

    if ('undefined' == typeof (jQuery)) {
        throw new Error('jQuery JS required');
    }

    if ($(document).has('[data-trigger="country-select"]')) {

        $('select[data-trigger="country-select"]').change(function() {
            var $this = $(this);
            var selectedItem = $this.val();
            var ddlStates = $($this.data('stateprovince'));
            var statesProgress = $($this.data('loading'));
            statesProgress.show();
            $.ajax({
                cache: false,
                type: 'GET',
                url: $this.data('url'),
                data: { 'countryId': selectedItem, 'addSelectStateItem': "true" },
                success: function(data) {
                    ddlStates.html('');
                    $.each(data,
                        function(id, option) {
                            ddlStates.append($('<option></option>').val(option.id).html(option.name));
                        });
                    statesProgress.hide();
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve states.');
                    statesProgress.hide();
                }
            });
        });
    }

}(jQuery);`

**_Root.Head**
`Html.AppendScriptParts(ResourceLocation.Foot, "~/js/public.countryselect.js");`

**Comment by Xzelsius** [comment]
The code above is 'reusable'. So you can replace the inline script within register page with data-attributes as well ;-)

**Comment by AndreiMaz** [comment]
@Xzelsius looks like a very good idea. yes, please make a pull request

**Comment by Xzelsius** [comment]
Pull-Request #2648

**Comment by DmitriyKulagin** [comment]
Closed #2644
