### ISSUE TITLE
Auto emails sent to orders that have shipped, after X days (we assign 7 days, 14 days…). Implement as a plugin

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#265]
it would be great to have auto emails sent to orders that have shipped, after X days (we assign 7 days, 14 days…) to get store/order fulfillment feedback and product review reminder, similar to Amazon merchant feedback. We should then be able to show a customer testimonials page with store/merchant reviews, not a product review but a service review. So two pieces, 1 product review reminder auto email, and 1 service review auto email, all based on X days since shipped. 
It would be nice to be able to send an auto reminder email, with promo X days after shipped order. We only want shipped orders because we know they received their merchandise and we don’t have to deal with people getting a review email for a cancelled, or backordered item, which would generally be a bad review. 

[AM] Already have it done as a plugin for 2.65 as one of the customization works

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
