### ISSUE TITLE
The use of X-Forwarded-For HTTP header should be disabled by default

### ISSUE THREAD

**Issue by MarinaAndreeva** [nopSolutions/nopCommerce#2651]
There is no way to disable the use of X-Forwarded-For when obtaining the client's IP (`Nop.Core.WebHelper.GetCurrentIpAddress()` method). Currently, any client can spoof their IP by setting this header.
Also, X-Forwarded-For header has been changed to X-Forward-For in version 4.00. Is there any reason for this or is it a typo?

**Comment by AndreiMaz** [comment]
@MarinaAndreeva Hi, Marina! You can always use the following workaround. Open the appsettings.json file and set "ForwardedHttpHeader" to something else (non-existing).

I've just fixed the typo/ Thanks!
