### ISSUE TITLE
Item Specifications on Invoice

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#2653]
It would be nice to have an option to list item specifications on the invoice for an item purchased.

**Comment by AndreiMaz** [comment]
@Ochapparel what specifications do you mean? specification attributes?

**Comment by Ochapparel** [comment]
@AndreiMaz the "Specification attributes". I use them for my fundraisers like "Graphic: A", "Color: White" so people don't have to choose that information and it's information that doesn't change. See example invoice pdf.

[Example Invoice.pdf](https://github.com/nopSolutions/nopCommerce/files/1390940/Example.Invoice.pdf)


I modified PdfService.cs in Nop.Services at line 527ish, but I just hate modifying the core files.

`//product specification
                    var productSpecificationAttributes = orderItem.Product.ProductSpecificationAttributes;
                    if (productSpecificationAttributes != null)
                    {
                        foreach (var productSpecificationAttribute in productSpecificationAttributes)
                        {
                            pAttribTable.AddCell(new Paragraph(productSpecificationAttribute.SpecificationAttributeOption.SpecificationAttribute.Name + ": " + productSpecificationAttribute.SpecificationAttributeOption.Name, attributesFont));
                        }
                    }`

It would be nice to have a "configuration" item to display this on invoices or not. 


I hope that makes sense.

**Comment by AndreiMaz** [comment]
thanks. but we'll leave it for customization. Specs are not for invoices

**Comment by Ochapparel** [comment]
Thanks! NP man 👍
