### ISSUE TITLE
Specification attribute Import/Export add by ValueName

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2654]
Now when we Import/Export product with specification attribute we need to find out Specification attribute ValueID, but how? Only with database query.

Need a ability to import/export not only with Specification attribute ValueID, need add Specification attribute ValueName(Like how we import product with product attributes)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan thanks. but duplicated work item - https://github.com/nopSolutions/nopCommerce/issues/2567

**Comment by tigran-avdalyan** [comment]
@AndreiMaz #2567 - work item status is  on hold / maybe wont
we have Function "Import/Export Specification Attributes" but we cant use that function, because we don't have information about ValumeID(in Admin area).
i think we dont need to add ID field.
we need import/export like product attributes. By ValueName or ValueID.
