### ISSUE TITLE
short description box resize to right - is True

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2655]
![short](https://user-images.githubusercontent.com/17789934/31669144-52627b50-b365-11e7-9619-ede461256d8b.gif)

**Comment by tigran-avdalyan** [comment]
if you resize to right , You cant resize back))

**Comment by tigran-avdalyan** [comment]
Same situation in "Admin comment"

**Comment by tigran-avdalyan** [comment]
Same situation in SEO>>Meta description

**Comment by tigran-avdalyan** [comment]
![resize](https://user-images.githubusercontent.com/17789934/31669690-cf57bb42-b366-11e7-9a7c-ea107a4b8c21.gif)

**Comment by wangchengqun** [comment]
You can modify it yourself

**Comment by AndreiMaz** [comment]
But why do you resize it? not sure that it's the issue of nopCommerce. I can reproduce it even in AdminLTE which we use - https://adminlte.io/themes/AdminLTE/pages/mailbox/compose.html

**Comment by tigran-avdalyan** [comment]
@AndreiMaz but why textbox go under Right side? we can resize above Right side, or Right side can go more right when we resize.
or we can disable resize to Right, only allow resize to down,
