### ISSUE TITLE
SQL Update Script - [StorePickupPoint]

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#2656]
I'm running NopCommerce 3.90 in production and when I run the 4.00 upgrade script in on my Localhost I get the below error:

Msg 208, Level 16, State 1, Line 671
Invalid object name 'StorePickupPoint'.
Msg 4902, Level 16, State 1, Line 676
Cannot find the object "StorePickupPoint" because it does not exist or you do not have permissions.

UPDATE [StorePickupPoint]
SET [DisplayOrder] = 0
WHERE [DisplayOrder] IS NULL
GO

I looked in both PROD and LOCALHOST and neither locations have that table.

So I downloaded a new version of 3.90 and installed it on my localhost and it DID install the [StorePickupPoint] table. So not sure where my 3.90 missed it and where the new 3.90 installed it. 

But maybe a check and install it if its not there?

**Comment by AndreiMaz** [comment]
Thanks a lot! I've jsut fixed it

**Comment by Ochapparel** [comment]
Awesome! So glad I could help. Keep up the FANTASTIC work Andrei, honestly,
it's impressive!
