### ISSUE TITLE
Edit Products in Order Detail

### ISSUE THREAD

**Issue by aaxirsoft** [nopSolutions/nopCommerce#2657]
edit products in saved order details:
1.changed rate and saved, but the line total still remains old.
2.changed discount, but the line total still remains old.
3.changed quantity, but the line total still remains old.
4.invoice pdf with old line total and new edited values.
5.added new product, but the bill total remains old.
6.invoice pdf with old total not added new product amount.
7.deleted one product, but the bill total remains old.
8.invoice pdf with old total not deducted the deleted product amount
9.changing the bill total by manually is not pretty good. It should be auto calculated after editing each
products

**Comment by aaxirsoft** [comment]
[wrongtoal1.pdf](https://github.com/nopSolutions/nopCommerce/files/1397084/wrongtoal1.pdf)
![wrongtotal1](https://user-images.githubusercontent.com/32920204/31753862-15b13910-b4b1-11e7-954a-2d7c87710ea3.png)
[wrongtotal2.pdf](https://github.com/nopSolutions/nopCommerce/files/1397085/wrongtotal2.pdf)
![wrongtotal2](https://user-images.githubusercontent.com/32920204/31753863-16213238-b4b1-11e7-995c-b5d8e133c1ef.png)
![wrongtotal3](https://user-images.githubusercontent.com/32920204/31753864-165bcf56-b4b1-11e7-86b4-2c88735f3a25.png)

**Comment by aaxirsoft** [comment]
![wrongtotalpdf1](https://user-images.githubusercontent.com/32920204/31753921-9cd7aa1e-b4b1-11e7-8e90-3dc5ff8cd69c.png)
![wrongtotalpdf2](https://user-images.githubusercontent.com/32920204/31753922-9d0dd8fa-b4b1-11e7-96d1-9589a4b28527.png)

**Comment by AndreiMaz** [comment]
1. Ensure that "orderSettings.AutoUpdateOrderTotalsOnEditingOrder" is set to "true"
2. PDF are cached by your browser. Click F5 to reset it
