### ISSUE TITLE
Code Polishing. Object initializer 

### ISSUE THREAD

**Issue by nruim** [nopSolutions/nopCommerce#2659]
Example:

        `public virtual LoginModel PrepareLoginModel(bool? checkoutAsGuest)
        {
            var model = new LoginModel();
            model.UsernamesEnabled = _customerSettings.UsernamesEnabled;
            model.CheckoutAsGuest = checkoutAsGuest.GetValueOrDefault();
            model.DisplayCaptcha = _captchaSettings.Enabled && _captchaSettings.ShowOnLoginPage;
            return model;
        }

        public virtual LoginModel PrepareLoginModel(bool? checkoutAsGuest)
        {
            var model = new LoginModel
            {
                UsernamesEnabled = _customerSettings.UsernamesEnabled,
                CheckoutAsGuest = checkoutAsGuest.GetValueOrDefault(),
                DisplayCaptcha = _captchaSettings.Enabled && _captchaSettings.ShowOnLoginPage
            };
            return model;
        }`
There are a few instances like this can be changed to follow the rest of the code done to others.

**Comment by Xzelsius** [comment]
Check this #2448, maybe they won't use object initializer since they finished their main code polishing. Although i prefer object initializer over assignment statements.

**Comment by skoshelev** [comment]
Closed #2659
