### ISSUE TITLE
New GoogleAnalytics Plugin implementation

### ISSUE THREAD

**Issue by alecrt** [nopSolutions/nopCommerce#2660]
I  love the new implementation of the transaction tracking via Google API. 
Much more solid!

I don't understand why there's still some old business logic here:
https://github.com/nopSolutions/nopCommerce/blob/bd9c2805bb03053a3c492cadc368c0aff0be4781/src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Components/WidgetsGoogleAnalyticsViewComponent.cs#L50-L55

Order is never used in GetEcommerceScript(Order order) function, there's no need to get last customer order.

Thank you,
A.

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/commit/1c330caf83de699d0be79aeaff986be168e5f592

**Comment by AndreiMaz** [comment]
Thanks a lot!
