### ISSUE TITLE
Ensure that \Plugins\bin directory already exists after publishing (and in solution)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2662]
We create it in the \Nop.Core\Plugins\PluginManager.cs (it it doesn't exist)

But it should already exist. Otherwise some people can experience issues if not required persmission is granted. Example: https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=6#194924 or https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=6#194921

Let's add some placeholder. And use it in Nop.Web.csproj

**Comment by skoshelev** [comment]
Closed #2662 (https://github.com/nopSolutions/nopCommerce/commit/8c7eeab043a8157c747711c5d47c4492cb49891f)
