### ISSUE TITLE
Can't create new customer address in admin v4.00

### ISSUE THREAD

**Issue by totalagility** [nopSolutions/nopCommerce#2663]
Can't create new customer address in admin v4.00:

/Admin/Customer/AddressCreate?customerId=1

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

C:\Dropbox\Development\nopCommerce\src\Presentation\Nop.Web\Areas\Admin\Views\Customer\_CreateOrUpdateAddress.cshtml

'CustomerAddressModel' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'CustomerAddressModel' could be found (are you missing a using directive or an assembly reference?)

[Can't create new customer address in  #admin.txt](https://github.com/nopSolutions/nopCommerce/files/1400236/Can.t.create.new.customer.address.in.admin.txt)

**Comment by totalagility** [comment]
Easy fix in nopCommerce\src\Presentation\Nop.Web\Areas\Admin\Views\Customer_CreateOrUpdateAddress.cshtml

Change line 9: additionalData = Model._**Id**_ To additionalData = Model.**_CustomerId_**
Change line 15:  additionalData = Model.**_Id_** To additionalData = Model.**_CustomerId_**

**Comment by AndreiMaz** [comment]
Thanks. But already reported and fixed https://github.com/nopSolutions/nopCommerce/commit/989f8101044d57e670bd6f4887d57d6f55f3a62d
