### ISSUE TITLE
Can't install plugin 'StorePickupPoint' in admin v4.00

### ISSUE THREAD

**Issue by totalagility** [nopSolutions/nopCommerce#2664]
I tried to install the plugin 'StorePickupPoint' in admin v4.00 but I'm getting the error message:

"There is already an object named 'StorePickupPoint' in the database. "

When I installed the database I selected not to have sample data.

I checked the installedPlugins.json and it is not listed/installed.

![plugin list](https://user-images.githubusercontent.com/32943737/31798374-89965060-b4f0-11e7-9e4e-3a27cc02ea59.PNG)

![plugin error](https://user-images.githubusercontent.com/32943737/31798376-8bf88044-b4f0-11e7-9e82-fcb06dbcd0b2.PNG)

[installedPlugins.json.txt](https://github.com/nopSolutions/nopCommerce/files/1400272/installedPlugins.json.txt)

**Comment by AndreiMaz** [comment]
@totalagility please manually delete this table and try one more time
