### ISSUE TITLE
Where to specify https cert location in nopCommerce 4.0

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2665]
Im trialling nop 4.00 and I want to use https.

I have selected the use https everywhere option but I get "this server cannot provide a secure connection". I assume this is because we are now using kestrel and there is no cert provided. 

How can I specify a certificate to use in this instance?

**Comment by AndreiMaz** [comment]
@rolandh It works absolutely the same way as in 3.90. On the store details page.

**Comment by rolandh** [comment]
I have done that however I cannot figure out where to specify the pfx cert to use. I get "This site can’t provide a secure connection".

I have looked through the forums and documentation but there does not appear to be any documentation on how to set up SSL.

**Comment by rolandh** [comment]
Ah I see. So you still have to modify the Nop.Web project and enabled SSL there, I thought it was enabled dynamically.

Can we add a page to the documentation for this? I see lots of confused people on the forums referencing old posts from Nop 3.00 etc

**Comment by AndreiMaz** [comment]
@rolandh we haveseveral demo sites run on 4.00 and SSL works fine (enabled as in 3.90). What exactly have you customized in Nop.Web? Could you please share your code?

**Comment by rolandh** [comment]
Nothing was customised code wise, it just had to be enabled in Nop.Web project properties under the debug tab. "Enabled SSL" was unticked by default.

https://i.imgur.com/raQKV54.png

**Comment by AndreiMaz** [comment]
@rolandh ohh. So you mean local development only?

**Comment by rolandh** [comment]
Yes. Sorry I didn't mention that earlier.
