### ISSUE TITLE
Middleware plugins

### ISSUE THREAD

**Issue by JeanCollas** [nopSolutions/nopCommerce#2666]
As ASP.NET Core has a great mechanism of middlewares, is there a way to allow adding middlewares using the plugin mechanism (or any other method, without changing core sources) on the new version of nopCommerce?

**Comment by AndreiMaz** [comment]
@JeanCollas You can implement your own "INopStartup" interface and register custom middleware in it
Could you please post all questions on our forums. Github is an issue tracker

**Comment by JeanCollas** [comment]
Perfect, Thanks.
