### ISSUE TITLE
IIS Web Deploy Fails to Deploy Files properly

### ISSUE THREAD

**Issue by neal007** [nopSolutions/nopCommerce#2667]
Hello,

I downloaded your initial beta and ran it in VS 2017 Pro just fine. I then tried using web deploy to deploy it to my server to explore it further and it appears it does not deploy properly using web deploy. I don't even have a /bin folder, all the DLL's are in the root. The file structure does not look correct and therefore does not run. 

As there is no real documentation to follow other than the existing production version I'm not sure if there is an issue server side or what. I'm using Windows Server 2012 R2 with all the latest Windows Updates agains MS SQL 2014. Again, it runs fine locally, this appears to be a deploy issue.

Initial beta 4.0.0 with VS 2017 Pro to Windows Server 2012 R2 / IIS 8

**Comment by AndreiMaz** [comment]
@neal007 this is how asp.net core deploys files =))

When you deploy it to the file system (local), does it look the same way?
