### ISSUE TITLE
Localize "Some comment here..."

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2672]
Hard coded text in Customer edit page.

Text: Some comment here...

Source: https://www.nopcommerce.com/boards/t/49121/find-bugs-in-nopcommerce-400-beta-and-earn-10.aspx?p=2#195032

**Comment by skoshelev** [comment]
Closed #2672 (https://github.com/nopSolutions/nopCommerce/commit/ed3b855d834f006dae7595feaba934ac8ffd55a2)
