### ISSUE TITLE
Ensure CSS Bundling works in virtual directories

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2674]
At moment CSS bundling doesn't work under a virtual directory, coz the BundlerMinifier library does not take into account the application path when transforming relative links

It's limitation of BundlerMinifier  (not nopCommerce). And we already write about it in the hint  of this setting in admin area.

P.S. Do not forget to update the hint of the setting in admin area

Already asked at https://github.com/madskristensen/BundlerMinifier/issues/525

**Comment by RomanovM** [comment]
At moment CSS bundling doesn't work under a virtual directory, coz the BundlerMinifier library does not take into account the path base when transforming relative links

**Comment by Joebeazelman** [comment]
I would strongly suggest switching to a static bundler and minifier.  Along with application path issues, it will also silently fail if it your CSS is malformed and not minify the bundle.  I see little reason to perform any processing on CSS files after deployment. 

I would perform any processing during the build process and stick with the standard ASP.NET method.

**Comment by exileDev** [comment]
IIS Virtual Directories [aren't supported](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md#virtual-directories) with ASP.NET Core apps. An app can be hosted as a sub-application.

CSS bundling works fine when the app is hosted as a sub-application.

Closed #2674

**Comment by exileDev** [comment]
~~CSS bundling works fine when the app is hosted as a sub-application.~~ I was wrong about it =)

**Comment by exileDev** [comment]
Closed #2674
