### ISSUE TITLE
Delete button should be red color

### ISSUE THREAD

**Issue by bakbuz** [nopSolutions/nopCommerce#2676]
suggestion (no bug): delete button should be red color. for ux design.

screen shot:
![ekran alintisi 5](https://user-images.githubusercontent.com/2492378/31931848-296306fa-b8ad-11e7-9a57-cc0b4471ea12.PNG)

**Comment by AndreiMaz** [comment]
@mariannk what do you think?

**Comment by DmitriyKulagin** [comment]
closed #2676
