### ISSUE TITLE
Incorrectly uppercase text with css

### ISSUE THREAD

**Issue by bakbuz** [nopSolutions/nopCommerce#2681]
Incorrectly uppercase text with css. By default uses english lang. Turkish letter "i" is creating a problem.

e.g.
"ılık" to css uppercase "ILIK"
"ilik" to css uppercase "ILIK"

When two different words are converted to uppercase, it means a single word.

Can a similar development?

&lt;html lang="@(this.WorkingLanguage.UniqueSeoCode)" &gt;

or

&lt;html lang="@(this.ShouldUseOtherLanguageAttribute())"  &gt;

**Comment by AndreiMaz** [comment]
@bakbuz 
1. what is "ShouldUseOtherLanguageAttribute"? 
2. Could you please clarify about "lang" attribute of "html" tag? So if we add it, then everything will work fine?

**Comment by bakbuz** [comment]
@AndreiMaz 

Hi Andrei

1. just a suggestion
2. I changed it myself for now. That can be  use as option to  alternative for users. Especially it will be usefull for language except  english


Latin alphabet: ... H h, **I i**, J j...
Turkish alphabet: ... H h, **I ı, İ i**, J j...

**Comment by AndreiMaz** [comment]
@bakbuz could you please clarufy how exactly have you fixed it?

**Comment by AndreiMaz** [comment]
@bakbuz I presume "<html lang="@(this.WorkingLanguage.UniqueSeoCode)" >". Please confirm

**Comment by AndreiMaz** [comment]
@bakbuz found the solution. fixed. thanks again!
