### ISSUE TITLE
Use IQueryable<T> instead of IList<T>

### ISSUE THREAD

**Issue by bashanam** [nopSolutions/nopCommerce#2688]
I suggest to user IQueryable - it will improve performance.

Example:
public virtual IQueryable<ScheduleTask> GetAllTasks(bool showHidden = false)
        {
            var query = _taskRepository.Table;
            if (!showHidden)
            {
                query = query.Where(t => t.Enabled);
            }
            query = query.OrderByDescending(t => t.Seconds);
            return query;
        }
IQueryable<T> only gets evaluated if iterated over ( like toList() ). We can chain another Filter that would be executed in the database as well (in case of DB use) Or in the Example the "toList" will happen twice.
A database is designed to do such tasks and will do it faster than in memory filtering

**Comment by Xzelsius** [comment]
The above code makes nop vulnerable to SQL injection.
I don't see any reason to expose IQueryable up to UI layer.

**Comment by AndreiMaz** [comment]
Agree with @Xzelsius

**Comment by bashanam** [comment]
IQueryable itself is not injection proof because it is just an interface for building a query Expression.

> Avoid Returning IQueryable Results When Exposing Methods to Potentially Untrusted Callers.
https://msdn.microsoft.com/en-us/library/cc716760(v=vs.100).aspx

So if you consider Plugins & controllers untrusted - Locking down the service is a good idea!

Using IQueryable in my code boost my performance in my last .Net adventure (tested with miniprofiler & glimpse)

**Comment by Xzelsius** [comment]
> Using IQueryable in my code boost my performance in my last .Net adventure (tested with miniprofiler & glimpse)

nopCommerce uses IQueryable (Table property from IRepository) in their service layer. 

If you need more filters or paged results, just override services to accept filters/commands you require. But exposing IQueryable up to UI is never a good idea, even if you "trust" controllers.

**Comment by bashanam** [comment]
thank you for you detailed answer.
