### ISSUE TITLE
"~/files/importexport" not being created on azure webapp with nop 4.00

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2689]
On a fresh install the folder ~/files/importexport/ does not exist and hence the following exception is thrown when attempting to generate the PDF after a sale.

> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\wwwroot\files\exportimport\order_c741d120-5cdb-48d2-882d-d0d40da1213d_4996.pdf'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
>    at System.IO.FileStream..ctor(String path, FileMode mode)
>    at Nop.Services.Common.PdfService.PrintOrderToPdf(Order order, Int32 languageId, Int32 vendorId)
>    at Nop.Services.Orders.OrderProcessingService.ProcessOrderPaid(Order order)
>    at Nop.Services.Orders.OrderProcessingService.MarkOrderAsPaid(Order order)
>    at Nop.Plugin.Payments.Pcmtec.Controllers.PcmtecController.SuccessfulPayment(QueryTransactionResponse res)
>    at Nop.Plugin.Payments.Pcmtec.Controllers.PcmtecController.HandleSuccessOrder()
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()

I added the following code to Configure(IApplicationBuilder app) Startup.cs in my plugin to rectify the issue.

`Directory.CreateDirectory(CommonHelper.MapPath("~/files/exportimport"));`

Looking through the code I can't see any calls to CreateDirectory in the whole project so I'm confused how these folders would ever be created.

**Comment by skoshelev** [comment]
@rolandh Thank you for your help, I fixed this problem.
Closed #2689

**Comment by rolandh** [comment]
Great thank you!
