### ISSUE TITLE
Live currency rates. Hide rates for non-exisiting currencies

### ISSUE THREAD

**Issue by bakbuz** [nopSolutions/nopCommerce#2690]
button hidden for non-listed currency

![ekran alintisi 10](https://user-images.githubusercontent.com/2492378/32048074-d169626e-ba50-11e7-91af-ba5addf9cd5f.PNG)

**Comment by AndreiMaz** [comment]
@bakbuz please translate labels. the suggestion is not clear now

**Comment by bakbuz** [comment]
@AndreiMaz of course, I re-uploaded

**Comment by AndreiMaz** [comment]
@bakbuz thanks a lot!
