### ISSUE TITLE
Log all errors

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2699]
I think I found a decent solution for logging errors (not just razor view compilation errors).
Inside the UseNopExceptionHandler extension method you can change the code like this (the code in bold is added):

//or use special exception handler                
application.UseExceptionHandler("/errorpage.htm");
application.UseExceptionHandler(handler =>
   {
     handler.Run(context =>
        {
           var exception = context.Features.Get<IExceptionHandlerFeature>().Error;
           var logger = EngineContext.Current.Resolve<Nop.Services.Logging.ILogger>();
           logger.InsertLog(Nop.Core.Domain.Logging.LogLevel.Error, "Exception", exception.ToString());

           // rethrow the exception to show the errorpage.htm
           throw exception;
         });
    });

It basically logs the error using the nopCommerce ILogger service and then shows the error page.

I would go further and also add the logging in DEV environment not just in production.
It will still be quite useful especially if an error occurs during an ajax request and you can't spot the error message in the browser (unless you open the dev tools and see the network tab). Also having the exact exception in the Log is much better than some formatted html containing the error.

Source: https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx?p=7#195375

**Comment by rolandh** [comment]
I actually built something similar for my Api in my plugin to this. Looking forward to seeing this in the commit.
