### ISSUE TITLE
Could not load DiscountRules.CustomerRoles.dll Access is Denied

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2700]
After running the current nop 4.00 develop branch for a few days Nop gets stuck in an infinite reboot/crash state.

It usually occurs after 2 days of running without restart. First notice I get is my azure ping test fails, then if you visit the website you get the following stack trace (I have the development env flag set in azure).

> An error occurred while starting the application.
> 
> UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> Unknown location
> 
> FileLoadException: Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> System.Reflection.AssemblyName.nGetFileInformation(string s)
> 
> Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in PluginManager.cs, line 622
> 
> Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in PluginManager.cs, line 633
> 
> UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> 
> Show raw exception details
> FileLoadException: Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> System.Reflection.AssemblyName.nGetFileInformation(string s)
> System.Reflection.AssemblyName.GetAssemblyName(string assemblyFile)
> Nop.Core.Plugins.PluginManager.PerformFileDeploy(FileInfo plug, ApplicationPartManager applicationPartManager) in PluginManager.cs
> Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in PluginManager.cs
> 
> Show raw exception details
> Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied.
> Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in PluginManager.cs
> 
> Show raw exception details
> Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. Access is denied. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
> Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in PluginManager.cs
> Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services) in NopEngine.cs
> Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfigurationRoot configuration) in ServiceCollectionExtensions.cs
> Nop.Web.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
> Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
> Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> 

Restarting the webapp in the azure portal does not fix the issue. Stopping the webapp, waiting 10 seconds then starting it again fixes the issue.

I am not using discount rules anywhere in my site so I have uninstalled and deleted any plugins referenced in the above stack trace.

Can you see why this would occur only after 2 days of running? It appears to be a permission issue, is it possible a web crawler/robot is viewing a specific page and triggering this?

Also the stack trace above does not show up in the nop error log. Do you know why this specific stack trace is not getting logged?

**Comment by Xzelsius** [comment]
> Also the stack trace above does not show up in the nop error log. Do you know why this specific stack trace is not getting logged?

Maybe because it's inside of PluginManager.Initialize() which is being called by NopEngine.Initialize().
Thus i think dependencies are not yet ready.

**Comment by skoshelev** [comment]
Hi @rolandh. I'm trying to figure this problem. When you removed the plugin does the problem solved?

@Xzelsius is right, the plugins are loaded before the database is initialized, and so the error log is nowhere to write.

**Comment by rolandh** [comment]
I removed the plugin last night so will wait a few days and report back.

**Comment by AndreiMaz** [comment]
also see https://www.nopcommerce.com/boards/t/49120/nopcommerce-400-beta-released-please-share-your-impressions.aspx?p=11#195473

**Comment by haimca** [comment]
I had same error, solved it by unblocking the DLLs in plugins folder:

1) PayPal.dll
2) RestSharp.dll
3) Square.Connect.dll

(https://www.limilabs.com/blog/unblock-dll-file)

**Comment by skoshelev** [comment]
Hi @rolandh and @haimca, this issue was with assemblies lock, we found a way to fix it in our code, but we need your help, can you check does it work in your instance.

**Comment by rolandh** [comment]
My problem hasn't returned however I have been redeploying my plugin regularly causing a restart which may mask it. Is the fix checked in? I will do a pull tomorrow and report back.

Do you have a link to the commit? Curious what the fix is. 

Thanks

**Comment by skoshelev** [comment]
Of course, this fix is attached to this issue (https://github.com/nopSolutions/nopCommerce/commit/47276d0bee879652178194d6e8c40b48b9e721cc)

**Comment by rolandh** [comment]
Being as I am working from a fresh compile can you think of any way this would have gotten marked as unsafe? All I can think is dropbox uploaded then downloaded the file at some point though that would be unexpected.

Is the new useunsafeassemblies bool set by default? And if I do a redeploy to am existing install do you see any chance of it not updating? I've run into this issue before where it sees a plugin as already installed so it doesn't create new settings.

**Comment by skoshelev** [comment]
I also used this method as you described, uploaded the assembly into the cloud and downloaded again, I have no other solution. The setting will be turned on by default. I think if you redeploy new code to an existing install, you will not have any problems

**Comment by rolandh** [comment]
I haven't seen the issue reoccur yet so fingers crossed it is fixed.

**Comment by rolandh** [comment]
Can we reopen this issue? It reoccurred and I have some more information.

I am running an azure webapp with development slots (eg multiple programs on the same VM I believe). I am running an older commit (with the changes above included) as my production and a second development slot with the current commit.

Both instances failed with identical error at the same time despite using different commits and builds. I suspect what has happened is Microsoft have done some automated patching perhaps, and this has caused the access denied error.

Both instances returned the following error simultaneously. I can give you access to our development environment if you have anything you'd like to check/see.

![image](https://user-images.githubusercontent.com/1109554/33351154-4efefee4-d4f2-11e7-8808-794581d89b73.png)
![image](https://user-images.githubusercontent.com/1109554/33351158-53bb0f7c-d4f2-11e7-8e00-cbba6c88fc25.png)

**Comment by Ochapparel** [comment]
ever get this one fixed?

**Comment by rolandh** [comment]
Nope but it occurs so randomly I just reboot when it does. I've engaged paid microsoft azure support and they have given me the following "solution". After some discussion they don't believe this is the fix. It seems to be something Azure related however so far MS have not been able to pinpoint it. The first few times it happened after an instance change (underlying web app instance) however the last time it did not correlate with an instance change.

https://github.com/aspnet/AspNetCoreModule/issues/260

**Comment by skoshelev** [comment]
Hello @rolandh. Please see [this topic](https://www.nopcommerce.com/boards/t/49851/serious-iis-application-pool-recycling-bugdesign-flaw.aspx?p=4#199793), I think one of solution will fixed you problem.

**Comment by rolandh** [comment]
What is the shadow copy used for? Will there be side effects when updating/installing new plugins by removing this feature?

**Comment by Bedo1212** [comment]
n the file opCommerce_4.10_Source/Libraries/Nop.Core/Infrastructure/NopFileProvider.cs

replace the the following function

`public virtual string MapPath(string path)`
with the following code :
`
public virtual string MapPath(string path)
    {
      //  path = path.Replace("~/", string.Empty).TrimStart('/').Replace('/', '\\');
       path =  Environment.OSVersion.Platform == PlatformID.Win32NT
        ? path.Replace("~/", string.Empty).TrimStart('/').Replace('/', '\\')
        : path.Replace("~/", string.Empty).TrimStart('/');
        return Path.Combine(BaseDirectory ?? string.Empty, path);
    }
`
