### ISSUE TITLE
How to store `download files` in Azure BlobStorage or FileSystem

### ISSUE THREAD

**Issue by hung-doan** [nopSolutions/nopCommerce#2701]
I took a look in the source code and found that
*  `download files` are stored in database (in Download table), can I store it in FileSystem or Azure Blob ?

Currently, I see that :  
* Custom attribute files are stored in database.  (Download table, )
* IPictureService could be Azure Blob storage or FileSystem base on Media.Images.StoreInDB

It make me confusing about storage setting. Some feature stored in database, but some are stored in Azure or File System.

So, at current release 3.90,

1. Can I store `Download Files` in AzureBlobStorage
2. Is there a plan to standardize/centralize Storage Configuration (Database or FileSystem or Cloud Storage). 
3. Currently, If I want to develop a plugin, I want to upload/download files. Which services I have to use ?

**Comment by AndreiMaz** [comment]
please post all questiona on our forums. it's an issue tracker
