### ISSUE TITLE
New Install Error 4.0 - Beta_Source

### ISSUE THREAD

**Issue by Alan911Black** [nopSolutions/nopCommerce#2708]
Hi All,

How do i solve this error?

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet package restore failed.
1>------ Build started: Project: Nop.Core, Configuration: Release Any CPU ------
1>Caching\RedisConnectionWrapper.cs(5,7,5,14): error CS0246: The type or namespace name 'RedLock' could not be found (are you missing a using directive or an assembly reference?)
1>Caching\RedisConnectionWrapper.cs(74,19,74,35): error CS0246: The type or namespace name 'RedisLockFactory' could not be found (are you missing a using directive or an assembly reference?)
1>Caching\RedisConnectionWrapper.cs(21,26,21,42): error CS0246: The type or namespace name 'RedisLockFactory' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Nop.Core.csproj" -- FAILED.
2>------ Build started: Project: Nop.Data, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Core\bin\Release\net461\Nop.Core.dll' could not be found
2>Done building project "Nop.Data.csproj" -- FAILED.
3>------ Build started: Project: Nop.Services, Configuration: Release Any CPU ------
3>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Core\bin\Release\net461\Nop.Core.dll' could not be found
3>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Data\bin\Release\net461\Nop.Data.dll' could not be found
3>Done building project "Nop.Services.csproj" -- FAILED.
4>------ Build started: Project: Nop.Web, Configuration: Release Any CPU ------
4>C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Presentation\Nop.Web\Nop.Web.csproj : error NU1104: Unable to find project 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj'. Check that the project reference is valid and that the project file exists.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1768,5): warning : The referenced project '..\Nop.Web.Framework\Nop.Web.Framework.csproj' does not exist.
4>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Core\bin\Release\net461\Nop.Core.dll' could not be found
4>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Data\bin\Release\net461\Nop.Data.dll' could not be found
4>CSC : error CS0006: Metadata file 'C:\Users\Alan\Documents\Visual Studio 2017\Projects\nopCommerce_4.00_Beta_Source\Libraries\Nop.Services\bin\Release\net461\Nop.Services.dll' could not be found
4>Done building project "Nop.Web.csproj" -- FAILED.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

**Comment by AndreiMaz** [comment]
"NuGet package restore failed" - looks like temporary issue. Try one more time. OR just googly by "NuGet package restore failed". There are a lot of solutions

P.S. could you please post all questions on our forums
