### ISSUE TITLE
NopCommerce PayPal Standard Payments Plugin does not validate currency

### ISSUE THREAD

**Issue by kwerty** [nopSolutions/nopCommerce#2709]
The PayPal Standard payment plugin does order total validation, which is important because a hacker could have changed the original paypal request and put in a lower amount. It could also be a good idea to validate the currency for the same reason.

**Comment by AndreiMaz** [comment]
@kwerty It already validates it - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Payments.PayPalStandard/Controllers/PaymentPayPalStandardController.cs#L248

**Comment by kwerty** [comment]
It validates the address, yes, but not the currency. Not a major, but if the hacker changed the currency they could potentially pay less.
