### ISSUE TITLE
InvalidProgramException: Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2710]
On one of my nopCommerce 4.00 test sites I get the following exception when trying to edit a product. I am running a release build with the development environment flag set (hence the stack trace). Running the site on azure webapp via deploy. 

Restart of the server fixed the issue.

An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred.
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs, line 81
**InvalidProgramException: Common Language Runtime detected an invalid program.**
AspNetCore._Areas_Admin_Views_Product__CreateOrUpdate_Info_cshtml+<>c.<ExecuteAsync>b__21_46()
Stack Query Cookies Headers
AggregateException: One or more errors occurred.
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware+<Invoke>d__6.MoveNext()
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Show raw exception details
**InvalidProgramException: Common Language Runtime detected an invalid program.**
AspNetCore._Areas_Admin_Views_Product__CreateOrUpdate_Info_cshtml+<>c.<ExecuteAsync>b__21_46()
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext+<GetChildContentAsync>d__31.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.TagHelpers.ValidationMessageTagHelper+<ProcessAsync>d__15.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner+<RunAsync>d__0.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AspNetCore._Areas_Admin_Views_Product__CreateOrUpdate_Info_cshtml+<ExecuteAsync>d__21.MoveNext() in _CreateOrUpdate.Info.cshtml
+
							<span asp-validation-for="Gtin"></span>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper+<RenderPartialCoreAsync>d__60.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper+<PartialAsync>d__57.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
AspNetCore._Areas_Admin_Views_Product__CreateOrUpdate_cshtml+<<ExecuteAsync>b__21_3>d.MoveNext() in _CreateOrUpdate.cshtml
+
            <nop-tab asp-name="tab-info" asp-title="@T("Admin.Catalog.Products.Info")" asp-default="true">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-tab>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext+<GetChildContentAsync>d__31.MoveNext()

Show raw exception details
AggregateException: One or more errors occurred.
  Module "Nop.Web.Framework.TagHelpers.Admin.NopTabTagHelper", line 410, in Process
    Void Process(Microsoft.AspNetCore.Razor.TagHelpers.TagHelperContext, Microsoft.AspNetCore.Razor.TagHelpers.TagHelperOutput)
  File "D:\home\site\wwwroot\Areas\Admin\Views\Product\_CreateOrUpdate.cshtml", line 25, in MoveNext
    Void MoveNext()
  Module "Nop.Web.Framework.TagHelpers.Admin.NopTabsTagHelper", line 261, in ProcessAsync
    Void MoveNext()
  File "D:\home\site\wwwroot\Areas\Admin\Views\Product\_CreateOrUpdate.cshtml", line 18, in ExecuteAsync
    Void MoveNext()
  File "D:\home\site\wwwroot\Areas\Admin\Views\Product\Edit.cshtml", line 43, in MoveNext
    Void MoveNext()
...
(104 additional frame(s) were not displayed)

InvalidProgramException: Common Language Runtime detected an invalid program.
  Module "AspNetCore._Areas_Admin_Views_Product__CreateOrUpdate_Info_cshtml+<>c", in ExecuteAsync { <lambda> }
    System.Threading.Tasks.Task <ExecuteAsync>b__21_46()
  File "D:\home\site\wwwroot\Areas\Admin\Views\Product\_CreateOrUpdate.Info.cshtml", line 615, in ExecuteAsync
    Void MoveNext()
  File "D:\home\site\wwwroot\Areas\Admin\Views\Product\_CreateOrUpdate.cshtml", line 25, in MoveNext
    Void MoveNext()
...
(28 additional frame(s) were not displayed)

**Comment by rolandh** [comment]
This might be relevant

https://www.nopcommerce.com/boards/t/4990/installation-error-160-when-i-got-to-the-point-of-go-to-site.aspx

**Comment by AndreiMaz** [comment]
@rolandh 
1. so it happens only for one of your sites? but not for others?
2. is it for the product details page only?

**Comment by rolandh** [comment]
When clicking edit on a all products for a site it occurred. Restarted the site and it went away. Site was running for about a day with no keep alive (would have been asleep for 12 hours). Prior to the half day inactivity it worked fine. After restart it also works fine. 

I have a mirror copy of the site running in debug mode which I've never seen this occur on before. 

I will idle the site overnight and see what happens tomorrow.

**Comment by skoshelev** [comment]
Hello @rolandh.

Possible this is build problem, you can read more in [this topic](http://support.microsoft.com/kb/312544). Also you can find and delete all pdb files (and delete all bin and obj folders) by hand though and then rebuild all project.

**Comment by rolandh** [comment]
I have not seen this problem come back since I last commented so I guess its magically solved itself.

**Comment by skoshelev** [comment]
Closed #2710
