### ISSUE TITLE
using css Image Sprites in default clean theme

### ISSUE THREAD

**Issue by ertebatgharineh** [nopSolutions/nopCommerce#2711]
it's better to using css Image Sprites in nopcommerce default theme as it can increase performance.
using css Image Sprites for all css images or using font icons maybe.

**Comment by bashanam** [comment]
I'm using both in my projects. Sprite for Flags and Icon fonts (flat icon)
for all the rest (button, menu etc..)

2017-11-04 20:21 GMT+02:00 ertebatgharineh <notifications@github.com>:

**Comment by AndreiMaz** [comment]
It's part of https://github.com/nopSolutions/nopCommerce/issues/1457 task. But we do not plan to do it out of the box. The default theme should be easy to customize. Not much people using it in production. So it's betterto leave for customization
