### ISSUE TITLE
Thumbnail generation (performance issue)

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2712]
Hello,

Here is a suggestion that I think will improve performance significantly.
Now we have this order:
1. Picture is inserted with IsNew = true
2. Then when user browses catalog system checks for each picture:
2.1. is thumbnail folder exist.
2.2. is thumbnail generated and if not generated then it is generated.

I'v found that if I insert a lot of new pictures and then I open catalog page that do not even have much pictures (like just 4) then page load is very slow (like 10! seconds) before thumbnails are generated (and its not a server issue).

So I suggest to change code such way that thumbnails are generated right inside InsertPicture function (and regenerated by some thread if thumbnail size is changed in database).
Thumbnails should not be generated during catalog browsing because it slows down customers experience.
Also for performance optimization we should not check for thumbs folder/thumbs file existance. Lets just suppose they are there.

**Comment by AndreiMaz** [comment]
@ArturAlekseev It's not possible just because there are too many sizes to be generated (e.g. catalog, produict details, attributes, shopping cart, etc, etc). Please note that it happens only once. I don't believe that it takes 10 secs to generate 4 thumbnails nowadays

What we really should better fix is this work item https://github.com/nopSolutions/nopCommerce/issues/1610

**Comment by ArturAlekseev** [comment]
I will look more into it. I think it is related to many pictures on file system (I use pictures not in db). Recently I had more than one million pictures with IsNew property set. And it took 13 seconds to show page with 4 pictures of categories.
Maybe code that delete previous thumbnails take long time because of files list is parsed on file system for each picture.
No need to generate all thumbnails. But categories + product thumbnails (that are shown during category browsing) by default.

About workitem #1610.
The best way is to remove binarydata property at all and omit ability to store pictures in database.
If store has few pictures they can be easily copied/backuped from file system. If store has a lot of pictures then database feature is unacceptable. My shops have > than 300gb of pictures.

**Comment by ArturAlekseev** [comment]
Also I think its a good idea to create dbo.ThumbsMap table that will contain references to all Thumbs.
Id
EntityType
EntityId
Size
and maybe filename (because of seo)
This will speed up thumbs deletion because there will be no need to search file system for files.

**Comment by ArturAlekseev** [comment]
Yes. The issue is here (in GetPictureUrl/DeleteThumbs):
string[] currentFiles = System.IO.Directory.GetFiles(thumbDirectoryPath, filter, SearchOption.AllDirectories);
It takes 8 seconds. Else code is fast.

**Comment by AndreiMaz** [comment]
@ArturAlekseev 
1. do you have "MediaSettings.MultipleThumbDirectories" setting enabled". Try to do it (delete all thumbs in advance)
2. how many thumb files do you already have in this directory (images/thumbs)?

**Comment by ArturAlekseev** [comment]
Not using MultipleThumbDirectories. It will not help, because SearchOption.AllDirectories. It will search in all directories anyway...
As I remember in total there are around 6 millions images (original + thumbs).
I'm rebuilding PictureService to use Thumbnail_Mapping table right now.
Also fixed Binary loading only to load it if thumbnail generation is needed (using 3.8 so far).
Don't know is it exist in 4.0. Will check 4.0 once test my changes.

**Comment by ArturAlekseev** [comment]
Did it using extra table. Now everything works fast and easy. Will make branch for 4.0 if it is needed there.

**Comment by Xzelsius** [comment]
I think this is an issue with your web server.

We are running a site with more than 1.7 millions pictures (700+ GB). Our base images have a dimension of around 4196 x 5595. 
The only issue we are facing is the memory usage to resize such a large picture. 

Sure there is room for improvements regarding the default picture service, but using an additional table will either blow up database or your memory cache.

**Comment by ArturAlekseev** [comment]
No. Issue is in this command:
System.IO.Directory.GetFiles(thumbDirectoryPath, filter, SearchOption.AllDirectories).
I have already implemented additional table and everything is very fast with it. Table uses only 138 mb of space on hdd.

**Comment by ArturAlekseev** [comment]
Here is a solution. Try it and you will see that it is much better than using GetFiles: https://github.com/nopSolutions/nopCommerce/pull/2760
