### ISSUE TITLE
Feature Request: Allow selectable whitelist/blacklist for product ACL

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2713]
It would be useful to allow switching the Access Control List for purchasing a product between whitelist or blacklist.

Eg you can purchase this product if you are NOT in a specific group, opposed to only people in a specific group can purchase it.

What I am trying to achieve is we have 3 products and we want customers to only be able to purchase one of them, note this is not per session put permanently. Eg if a customer purchases product A, they cannot purchase product B or C ever.

What I am proposing is the following.

Product A  -> ProductACustomerRole is purchased with this item
Product B  -> ProductBCustomerRole is purchased with this item
Product C  -> ProductCCustomerRole is purchased with this item

Product A ACL: !ProductBCustomerRole AND !ProductCCustomerRole
Product B ACL: !ProductACustomerRole AND !ProductCCustomerRole
Product C ACL: !ProductACustomerRole AND !ProductBCustomerRole

I propose a whitelist/blacklist selector that effectively adds a NOT/! operator to all items in the the ACL.

Currently to achieve the above we have hard coded the inverse ACL logic into the ValidatePaymentForm function of our payment plugin to throw an error if the pre conditions are not met.

**Comment by AndreiMaz** [comment]
@rolandh Thanks! The suggestion is good. But it can decrease the performance and logic to support it . It's better to keep it simpler now

**Comment by rolandh** [comment]
Fair enough. What is the reason it slows things down? Are the ACLs not already cached in memory? Adding a few operators would barely be an increase of 100 cycles per request.
