### ISSUE TITLE
Documentation in spanish

### ISSUE THREAD

**Issue by davidrevoledo** [nopSolutions/nopCommerce#2716]
Hello I'm from Argentina, I want to help with Spanish documentation.

Any want to help me where start and a guideline ? 

Great thanks.

**Comment by AndreiMaz** [comment]
thanks a lot for interest in contribution. GitHut is for development tasks. Please post it at https://www.nopcommerce.com/boards/t/45692/nopcommerce-documentation-translators-wanted.aspx

**Comment by davidrevoledo** [comment]
@AndreiMaz sure, sorry and thanks
