### ISSUE TITLE
Create a new language. Pre-set "Display order"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2717]
When you adding new language by default it is assign as Display order 0. And language is loaded first according to that order. This mean, if you will add any language and set order to 2 or above, language will be not changed. 

Let's get the highest existing language number. And pre-set it by default

Source: https://www.nopcommerce.com/boards/t/46712/nopcommerce-400-roadmap-and-estimated-release-date-lets-discuss.aspx?p=14#195797

The question is whether we should do the same for toher entities?

**Comment by skoshelev** [comment]
Closed #2717
