### ISSUE TITLE
minified css and js issue in multiple vm

### ISSUE THREAD

**Issue by ertebatgharineh** [nopSolutions/nopCommerce#2718]
hi,
i'm using 4 web servers to run my nopcommerce application, i linked them to each other by setting a machine key in web.config and it works fine but there is a problem for loading nopcommerce minified css and js that the application change the name of the minified files so in round robin load balancing method there is 404 not found file issue

**Comment by bashanam** [comment]
At the current state you have cache for each server.
1. You can use distributed cache like memcache. (need code changes/plugin)
2. consider use external cdn for JS files.
3. Code/Buy single page app (SPA) and most of the files will be cached.


בתאריך 10 בנוב׳ 2017 12:28 לפנה״צ,‏ "Amir Ziyaee" <notifications@github.com>
כתב:

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/2494
