### ISSUE TITLE
v. 3.7 Admin Area. New Specification Attribute gets renamed after new Option value submitted.

### ISSUE THREAD

**Issue by homoluden** [nopSolutions/nopCommerce#2719]
Steps:
1. Go to Specification Attributes screen
2. Add new Attribute with name "SomeBoolAttribute" and press "Save and continue editing" (also works with "Save" button)
3. Switch to "Options" tab and press "Add a new Option"
4. Give a new Option name "True" and press "Save"

ER: In attribute list User see new Spec Attribute with name "SomeBoolAttribute" and will see one option "True" in "Options" tab if he/she will click "Edit" link.
AR: In the list of Attributes User see a new Attribute with the name "True".

**Comment by skoshelev** [comment]
Sorry, but I can't reproduce this problem. This functionality works fine both in nopCommerce 4.0 and in nopcommerce 3.70

Closed #2719
