### ISSUE TITLE
Add delete options to the mini-shopping cart (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#272]
Add delete options to the mini-shopping cart. see related contribution - http://www.nopcommerce.com/p/1706/shoppingcart-remove-button-free-ima9inescom.aspx 

Also increase/decrease qty buttons could be added 

please the following plugins - http://www.nopcommerce.com/p/1706/shoppingcart-remove-button-free-ima9inescom.aspx and http://www.nopcommerce.com/p/1718/wishlist-remove-button-free-ima9inescom.aspx

**Comment by johannwalder** [comment]
@AndreiMaz I believe this option would be better in the core as it will increase the usability of the shopping cart. It's just easier to understand. Adding this simple option as a plugin is possible but every additional plugin increases server resources needed. It's just too simple to justify a plugin. I would rather replace the current implementation with a simple remove icon as shown in this good plugin above.
Thanks!

Br,
Johann
