### ISSUE TITLE
GetCurrentIPAddress method IPv6 problem

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2721]
Hi,
GetCurrentIpAddress not supported the IPv6.
Reason:
IPV6 example: 2001:0db8:0a0b:12f0:0000:0000:0000:0001
If execute the GetCurrentIPAddress method, returned result 2001, because if ipaddress is multiple, split result and return the first or default ip adress.
If ipv6 use, returned result 2001.

I found a solution for you,
https://stackoverflow.com/a/32702160

**Comment by skoshelev** [comment]
Closed #2721
