### ISSUE TITLE
Display primary currency code on Value of 'X' (free shipping)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2725]
Like we do for other prices (e.g. product price, etc)

**Comment by skoshelev** [comment]
Closed #2725 (https://github.com/nopSolutions/nopCommerce/commit/5ff49b70c9a40b9f625420ab53ad257311c641c3)

**Comment by nextfool** [comment]
why this is closed? I came here form https://www.nopcommerce.com/en/boards/topic/49437/free-shipping-over-x-support-multi-currency , and I believe "Free shipping over 'X' Support multi currency" means show the "x" value in the cusotmers' currency, but from what I saw here, https://github.com/nopSolutions/nopCommerce/issues/2725 it's only added in the admin area, I think it is totally a misunderstanding here?
