### ISSUE TITLE
dotnet build failure: CodeTaskFactory not supported; NopClearPluginsPath not found

### ISSUE THREAD

**Issue by dahlbyk** [nopSolutions/nopCommerce#2728]
On a fresh clone at `develop` (`release-4.00`), `dotnet build src/NopCommerce.sln` produces a build error for each plugin:

```
src\Build\ClearPluginAssemblies.proj(110,5): error : MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.
src\Build\ClearPluginAssemblies.proj(110,5): error MSB4036: The "NopClearPluginsPath" task was not found. Check the following:
1.) The name of the task in the project file is the same as the name of the task class.
2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface.
3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\dotnet\sdk\2.0.2" directory.
```

A build in Visual Studio completes successfully. Thoughts?

**Comment by dahlbyk** [comment]
cc @skoshelev, since you added this to the build.

**Comment by skoshelev** [comment]
Hello @dahlbyk . We moved the deleting logic to the separate project, that's should fix all problem with clearing. Can you test this change on your environment?

**Comment by dahlbyk** [comment]
👍 clean build seems to work as expected.

**Comment by arunxampr** [comment]
not working

**Comment by udubdave** [comment]
I also just got this error.  Took the 4.00 version from the website and tried deploying it to AWS.

**Comment by vlachmilan** [comment]
The given solution doesn't work for me. Fixed it by deleting the content of `/Build/ClearPluginAssemblies.proj` and commenting line in `/Presentation/Nop.Web`

* `<!--<MSBuild Projects="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" Targets="NopClear" />-->`.

and handling the job manually by using a bash script. I consider this as a solution until there is proper accepted one.

**Comment by OnoNguyen** [comment]
I cherry-picked c53a37d to my local branch and the following error came up:
No executable found matching command "dotnet-C:\Program"
Anyone got the same issue?

**Comment by OnoNguyen** [comment]
FYI I had to change the Exac Command as of following to make it work with powershell:
<Exec Command='dotnet "$(MSBuildProjectDirectory)\ClearPluginAssemblies.dll" Paths=@(PluginsFolders) FileNames=@(DllFileNames) PluginPath=$(PluginPath) SaveLocalesFolders=$(SaveLocalesFolders)' />
