### ISSUE TITLE
Address restriction and "Shipping to the same address" issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2729]
Step to recreate:

1. Create a customer account
2. Make sure shipping to Mexico is allowed
2. Enter an address into the system using Mexico as the ship to country
3. Place an order using this address
4. Change shipping restrictions to NOT allow shipping to Mexico (from admin panel)
5. Using the same customer account, place another order. You will be allowed to choose the address showing Mexico as the country.

Actually we validate addresses. But not when using "Shipping to the same address" option. We should also validate it when "Shipping to the same address" (country for billing is allowed but not for shipping)

Source: https://www.nopcommerce.com/boards/t/49475/address-restriction-does-not-apply-to-existing-addresses.aspx

**Comment by skoshelev** [comment]
Closed #2729
