### ISSUE TITLE
Error sending e-mail. The specified string is not in the form required for an e-mail address.

### ISSUE THREAD

**Issue by dotnetdreamer** [nopSolutions/nopCommerce#2732]
Recently i was getting this error. I investigated alot and it turns out that its because of an Empty space...
Here is the full trace:
`System.FormatException: The specified string is not in the form required for an e-mail address. at System.Net.Mail.MailAddressParser.ParseAddress(String data, Boolean expectMultipleAddresses, Int32& index) at System.Net.Mail.MailAddressParser.ParseAddress(String data) at System.Net.Mail.MailAddress..ctor(String address, String displayName, Encoding displayNameEncoding) at Nop.Services.Messages.EmailSender.SendEmail(EmailAccount emailAccount, String subject, String body, String fromAddress, String fromName, String toAddress, String toName, String replyTo, String replyToName, IEnumerable`1 bcc, IEnumerable`1 cc, String attachmentFilePath, String attachmentFileName, Int32 attachedDownloadId, IDictionary`2 headers) at Nop.Services.Messages.QueuedMessagesSendTask.Execute()`

so what fixed for me was this line https://github.com/nopSolutions/nopCommerce/blob/8315c57d48a2e04b6449009f60f3d049f6a67a7f/src/Libraries/Nop.Services/Messages/WorkflowMessageService.cs#L1924 instead of `String.empty` i changed to `null`

![image](https://user-images.githubusercontent.com/10280821/33023952-21f9bbf8-ce23-11e7-83d3-be4b98dfce1d.png)

In the above image, any email who's cc column is set to empty string would not work. So i have to change it to `null`

**Comment by AndreiMaz** [comment]
@dotnetdreamer could you please some steps to reproduce the issue?
