### ISSUE TITLE
Categories load. Performance optimization

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2737]
Ok. I'v started to update v4.0 for my needs and here is the first issue.
Will try to resolve it myself and publish commit but so far will write about it.

We use this function:
PrepareCategorySimpleModels();
That loads all categories and prepares their models recursively.
This function is used 2 times:
For top menu generation and for navigation.

The problem is seen when there are many categories. For example 20000. Then everything goes extremely slow.

First we do not need to load all categories for top menu because not all are there.
Second we do not need to load all categories for category navigation (only those that are higher than selected and one level lower).
Ofcourse if we load different categories sets then we should not cache results (now result of all is cached). But anyway - with each categories change it will be regenerated and it is not acceptable for large categories list.

And another one:
foreach (var category in categories)
            {
                var categoryModel = new CategorySimpleModel
                {
                    Id = category.Id,
                    Name = category.GetLocalized(x => x.Name),
                    SeName = category.GetSeName(),
                    IncludeInTopMenu = category.IncludeInTopMenu
                };

GetLocalized & GetSeName executes 2 queries to database for each category.
It is very slow.
We should load localized names and se names using IN statement for all categories before foreach word and then use loaded list inside foreach.

I will add CommonSetting called LargeDatabase and create different code for when it is set to true. So that we can use both approaches.

**Comment by Xzelsius** [comment]
GetLocalized and GetSeName use a setting to decide whether to cache all entries at first usage or not. See LocalizationSettings. So this shouldn't be a problem.

But a setting for "LargeDatabase" would be bad. _(Since "large database" depends on the power of your SQL server)_

I think it would be better to just write a plugin for your large database where you override services/factories that struggle with your large database.

**Comment by ArturAlekseev** [comment]
No matter which power of sql server you have - 1000 sql server requests will be nearly 1000 times slower than 1 request.
It is not possible to override PrepareCategorySimpleModels function work using plugin. It is not supported.

**Comment by AndreiMaz** [comment]
@ArturAlekseev it's by design. we load all categories. but we do it only once (for all pages). It takes some time but only during the first site visit. So it's by design

**Comment by ArturAlekseev** [comment]
I know that it is by design and not a bug. But this design is not usable for large categories count. Because first time categories are loaded is very long for large categories count. And for each time cache is cleared it will be regenerated. And these:
Name = category.GetLocalized(x => x.Name),
SeName = category.GetSeName(),
for 20000 categories is like forever.

**Comment by Xzelsius** [comment]
> It is not possible to override PrepareCategorySimpleModels function work using plugin. It is not supported.

Of course it is supported.

Inside your plugin
```
public class CustomCatalogModelFactory : CatalogModelFactory 
{
    public override List<CategorySimpleModel> PrepareCategorySimpleModels(int rootCategoryId, bool loadSubCategories = true, IList<Category> allCategories = null) 
    { 
        //... your new code
    }
}
```

Inside plugin DependencyRegistrar
```
builder.RegisterType<CustomCatalogModelFactory>().As<ICatalogModelFactory>().InstancePerLifetimeScope();
```

**Comment by ArturAlekseev** [comment]
But this code:
`            return _cacheManager.Get(cacheKey, () => PrepareCategorySimpleModels(0));`
uses CatalogModelFactory.PrepareCategorySimpleModels.
Using your code I will create CustomCatalogModelFactory.PrepareCategorySimpleModels method that will not be used by nopcommerce. Am I wrong?

**Comment by Xzelsius** [comment]
> And I think its a wrong idea to change basic nopcommerce parts using plugins

Please do not take offense: I think its a bad idea to change basic nopcommerce to support super high amounts of categories on bad SQL servers out of the box. And this only to increase page load on first visit.

I've nothing against performance optimizations, but running different code parts based on a setting only makes code harder to maintain.

**Comment by ArturAlekseev** [comment]
I don't ague. Just thoughts. Bad SQL Server is not an issue here. Even good SQL server will have much higher load when it gets a lot of requests instead of one.
About super high amount of categories. I don't think that nopcommerce core shold be limited to few categories. It has support for different warehouses, different vendors. So it is planned to be used for large companies. And large companies most likely to sell a lot of different products that need a lot of categories.
Anyway I think it's better to allow user to select whether he wants to load all categories at start and use them from cache (small store with few products and few categories) or not.
For maintenance - I don't think this change will make something much harder to maintain. Because not much change.

And p.s. I don't think I have bad SQL server. Its on dedicated server with 16GB of ram and 2 CPUs at 3Ghz (8 cores total).
Even if you have 1000 categories it will become slower in usage.
I have on one store more than 20000 categories. I was not able to wait till the end of top menu load. It was > 10 minutes.
Even If I count that it is only for the first time. Ok. Store cached all categories and then. When admin changes category, adds new, delete one. Cache is cleared. And store will become unusable for 10+ mins. This is not an option.

**Comment by masterxml** [comment]
@ArturAlekseev 
I have same problem at version 4.10. Home page very slow when I have many category(20k).
But I find a the reason is PrepareCategorySimpleModels is call recursive, beacuase the parameter: bool loadSubCategories default is true.
I think this suppose to be false, becasue on topmenu we load all category.
When I chang 
`public virtual List<CategorySimpleModel> PrepareCategorySimpleModels(int rootCategoryId, bool loadSubCategories = true)`
to
`public virtual List<CategorySimpleModel> PrepareCategorySimpleModels(int rootCategoryId, bool loadSubCategories = false)`
Problem solved.

**Comment by ArturAlekseev** [comment]
This way you will load only root categories.

**Comment by masterxml** [comment]
Yes, You are right, And I forgot [_categoryService.GetAllCategories](https://github.com/nopSolutions/nopCommerce/blob/b16776c35972faf7b72d47bd11197264030874c4/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs#L664) have catch detect.
I think 4.10 slow is beacause [GetSeeName](https://github.com/nopSolutions/nopCommerce/blob/b16776c35972faf7b72d47bd11197264030874c4/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs#L672) access database for each category.
