### ISSUE TITLE
Redis deadlock problem

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2739]
Hi,
I have a problem with RedisCache.

Stack Trace
`
Timeout performing GET Nop.localizedproperty.all, inst: 1357, mgr: ExecuteSelect, err: never, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: WEB-SERVER02, serverEndpoint: Unspecified/localhost:6379, keyHashSlot: 477, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=71,Free=32696,Min=16,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
`

And I found a solution the below link,
https://stackoverflow.com/questions/30797716/deadlock-when-accessing-stackexchange-redis

**Comment by AndreiMaz** [comment]
@fsefacan just disable loading of all locales in admin area > configuration > general settings

**Comment by fsefacan** [comment]
Andrei,
Already disabled. My problem is in intensive user requests.
