### ISSUE TITLE
Site wide general settings are cleared when updating settings for an individual store

### ISSUE THREAD

**Issue by kwerty** [nopSolutions/nopCommerce#2740]
How to reproduce:
* Setup a test environment with two stores
* Go to /Admin/Setting/GeneralCommon
* Ensure 'Multi-store configuration for' is set to All Stores
* Tick 'Popup windows for "terms of service"'
* Save
* Now change ' Multi-store configuration for' to Store 1
* Now click Save
* Note that the 'Popup windows for "terms of service"' setting has now been cleared for All Stores

**Comment by AndreiMaz** [comment]
Please share some screenshots. It works fine (there's one more checkbox to override this setting)

**Comment by kwerty** [comment]
With all due respect Andrei, I don't think you quite understand what I'm saying. I know about the override checkbox, this issue has nothing to with that. Simply selecting a store and clicking save will completely wipe the "all stores" settings back to the defaults. Follow the steps I've outlined, you will see.

**Comment by kwerty** [comment]
Every time I update a general setting for a specific store, the settings for "all stores" are lost, so I have to go back to re set the settings for all stores. It's a bit of a pain having to deal with the bug, but at least I know the steps to work around it. Newbies won't know about this and will no doubt be confused as to why their all store settings keep getting cleared.

**Comment by AndreiMaz** [comment]
@kwerty Thanks again! Fixed
