### ISSUE TITLE
"partial" on EntityFramework mappings

### ISSUE THREAD

**Issue by Xzelsius** [nopSolutions/nopCommerce#2745]
I found several mappings not having the "partial" keyword

- TopicMap
- TaxCategoryMap
- WarehouseMap
- ShippingMethodMap
- ProductAvailabilityRangeMap
- DeliveryDateMap

Intended to not have the keyword? If not, see my pull-request.

**Comment by AndreiMaz** [comment]
@Xzelsius Thanks a lot!
