### ISSUE TITLE
Plugin Installs Fail

### ISSUE THREAD

**Issue by jkergosi** [nopSolutions/nopCommerce#2747]
When trying to install any plugin after upgrade to 4.0, NopCommerce throws the error "No descriptor file is found. It should be in the root of the archive"

I've had the issue with Authorize.Net.  

NOTE: I tried the current version of Authorize.NET, which is compatible with 4.0

**Comment by skoshelev** [comment]
Hello @jkergosi. We know about this issue and we'll fix it in near future. You can fix it yourself, just to rename the file  uploadedPlugins.json to uploadedItems.json. 

This is not problem of nopCommerce core.

**Comment by jkergosi** [comment]
Thanks skoshelev! Will do

**Comment by devrajeev** [comment]
Not worked for me

**Comment by skoshelev** [comment]
Hi @devrajeev. Describe what exactly does not work for you, which plug-in you are trying to install and in what way

**Comment by AbhishekRobosol** [comment]
How to use seven spikes plugin in nopcommerce version 4.2 as it is not there in file?

All help is apprciated!
