### ISSUE TITLE
Authorize.NET Plugin Disappears after upgrade to 4.0

### ISSUE THREAD

**Issue by jkergosi** [nopSolutions/nopCommerce#2748]
Authorize.NET plugin is missing from plugins after upgrade. I've already tried reinstalling and fixing the newline in the config file. Issue remains.

NOTE: I'd tried reinstalling but that doesn't work (posted in an unrelated issue: https://github.com/nopSolutions/nopCommerce/issues/2747)

**Comment by AndreiMaz** [comment]
it's in release notes. we plan to release it lkater on our marketplace
