### ISSUE TITLE
Real-time shipping methods. Automatically set shipping statuses based tracking number (using API)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#275]
After a tracking number is set, then a task can be used to scrape from the carrier's site or request delivery status via a service from the shipping carrier to automatically update the shipping's status to Delivered 

Forum source: http://www.nopcommerce.com/boards/t/27508/feature-request-automatically-set-order-statuses-to-delivered.aspx

**Comment by mobsoftware** [comment]
AutoTracker can do this Mariann irrespective of the shipping carrier. It's configured once then it will keep the order status updated based on the tracking information from shipped to delivered.

[http://market.mobsocial.co/autotracker-for-nopcommerce](http://market.mobsocial.co/autotracker-for-nopcommerce)
