### ISSUE TITLE
NopEngine ServiceProvider() method null result

### ISSUE THREAD

**Issue by Nico-VanHaaster** [nopSolutions/nopCommerce#2750]
Hello,

I have been working with NopCommerce 4.0 for awhile and just started building a long running background task that can either be started via a scheduled task or manually. However in both instances there are thousands of processes happening. I have found what I think is a bug with the method `NopEngine.GetServiceProvider()`

It appears that an HttpContext can be resolved from the service provider however the `RequestedServices` could be null. The orignal code just checks if the `context != null` but we also need to check that the property `RequestedServices` is also not null.

I have refactored this method to.

```
protected IServiceProvider GetServiceProvider()
{ 
    var accessor = ServiceProvider.GetService<IHttpContextAccessor>();
    var context = accessor.HttpContext;
    return context?.RequestServices ?? ServiceProvider; //context != null ? context.RequestServices : ServiceProvider;
}
```
Now as you see we are using Null-Condition checking and Null Collesce to return the ServiceProvider if null.

Now I have tested what this will do for transiant scopes left open but will review.

Also it would be handy if the property `ServiceProvider` was made public not protected.

**Comment by skoshelev** [comment]
@Nico-VanHaaster Thank you for your help, I checked and implemented your suggestion

Closed #2750
