### ISSUE TITLE
UPS - Upgrade to use TLS 1.1 or TLS 1.2

### ISSUE THREAD

**Issue by rahatur** [nopSolutions/nopCommerce#2754]
We recently started to receive this (403) Forbidden exception on the `DoRequest` method of the `UPSComputationMethod.cs` file. Further investigation reviled that the exceptions were thrown by the UPS API at random. For the same address sometime we get response sometime we don’t. When we contacted the UPS support team they gave the following reply:

"_Currently, all of the CIE (test) environment servers have be updated to only accept TLS 1.2 requests. 

UPS will be making changes to the Production servers beginning September 1, 2017 through December 31, 2017 to support enhancing our security. During this time, you may see intermittent failures for transactions using TLS 1.0 or earlier.

As of October 10, 2017, 50% of all API servers have been transitioned over to ignore any traffic using TLS 1.0. 

Effective 12/31/2017, UPS will only accept TLS 1.1 and TLS 1.2 security protocols. It is highly recommended that the most current version, TLS 1.2, be implemented. After that date, any communication requests submitted to UPS using older protocols (TLS 1.0 or earlier) will fail._"

**Comment by AndreiMaz** [comment]
@rahatur what version of nopCommerce are you using?

**Comment by rahatur** [comment]
I am using version 3.3

**Comment by AndreiMaz** [comment]
it's the issue. It was fixed in later versions

**Comment by AndreiMaz** [comment]
please see global.asax file in 3.90 where we set it

**Comment by rahatur** [comment]
Got it.
//most of API providers require TLS 1.2 nowadays
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Adding that should be enough right?

**Comment by AndreiMaz** [comment]
yes

**Comment by vijjendra** [comment]
I am using nop version 3.5, may I know where I can place below line of code 
**ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;**
When I have tried to put this in global.ascx under 
protected void Application_Start(){
**ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;**
}

still I face the problem, may I know how to resolve this TLS 1.2  related issue in Nop 3.5

**Comment by rahatur** [comment]
For nopcommerce 3.3 I placed in as the first line in the _Application_Start_  function of the Global.asax.cs file
```
        protected void Application_Start()
        {
            //most of API providers require TLS 1.2 nowadays
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by vijjendra** [comment]
I have used  **ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;**  
in Global.asax.cs on **Application_Start()** and set **targetFramework="4.6"** in web.config and it start works.
