### ISSUE TITLE
Payment plugins ability to send message to other plugins

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2758]
As you may know in Russia all online stores should use online cash machine to issue cash voucher.
So we can make plugins that issue such cash vouchers.
But for new plugin to know that it needs to issue a cash voucher we need that payment plugin send a message to this new plugin about that payment is succeded.
This way new plugin will generate cach voucher only when real payment is done and not when admin change some order status to "Paid".
So far i'v just changed the code of payment plugins I use to also have setting where I add url of cash machine plugin and password. When payment is done payment plugin makes GET request to this url specifying password and order id. Then cash machine plugin checks for password and if order status is paid then it generates cash voucher (if it was not generated before).

So I propose to add such settings to payment plugins so they were compatiple from the start with such scheme. Maybe in some different way that do not require making requests.
Then it will be possible to publish cash machine plugins on market also. Because now such plugins can't be used without modifying payment plugins.

**Comment by ArturAlekseev** [comment]
Without this feature it will be much harder to develop cach machine plugins, because they will need to make special payment plugins for it (for each gateway).

**Comment by AndreiMaz** [comment]
@ArturAlekseev Thanks. But I think it's easier to implement it as a plugin which will do it for all payment plugins. For example, this plugin will have a new service (derived from "PaymentService") which will override "ProcessPayment" method of "IPaymentService". In this new method the base (original) "ProcessPayment" method will be invoked (it makes an actual payment). And then you can send any information to the cash machine once it's invoked.

I don't think we should add a certain (region specific) implementation to the core (like this one)

**Comment by ArturAlekseev** [comment]
I'll try to make such plugin.

**Comment by AndreiMaz** [comment]
@ArturAlekseev Great! Then you're always welcome to publish it on our marketplace (free or paid, up to you)

**Comment by ArturAlekseev** [comment]
I thought a little and it can't be done this way.
Payment workflow is different:
0. ProcessPayment just sets PaymentStatus.Pending;
1. Plugin sends data to payment gateway about order and sum (in PostProcessPayment).
2. Gateway processes payment and then makes back request to plugin (using get or post method).
3. Get or post plugin method then checks if server request is correct (authorized) and if result is "paid" then plugin should send notification to cash machine.
Its not possible to override custom payment plugin method that processes server request.

**Comment by AndreiMaz** [comment]
@ArturAlekseev Ohh. Please see "OrderPaidEvent" event. You cna subscribe to it

**Comment by ArturAlekseev** [comment]
Ok. I will override MarkOrderAsPaid then.
