### ISSUE TITLE
More user-friendly AJAX filters (price and specification attributes) on catalog pages

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#276]
1. Move them to the left box

2. Price filter as slider (configurable). also see http://www.nopcommerce.com/boards/t/45996/price-range-for-special-customers.aspx Price ranges (display in the "filter" block) are not converted into selected currency when selected currency is changed. For example if I have defined $0-$20; $21-$40, when I change currency to yen it is still 0-20; 21-40 except it is now yen; it should be converted and not only currency changed as the buying power of yen and dollar is much much different. On the other hand (due to currency conversion) prices will bebecome not so friendly as entered by a store owner (not 0-20, but 0-24.34). Possible solution. Now most stores support sliders with price ranges (or input textboxes with preset "min" and"max" possible prices). Maybe we should also re-think it

3. Allow a store owner to choose several specification attribute options (configurable). Examples - http://www.bigbrownbox.com.au/all-tvs/ and http://www.amazon.com/ 

Although we have a lot of third-party plugins, this functionality is really very demanded nowadays. So we have to support it out of the box

**Comment by onebox-dev** [comment]
It's very needs. 
All stores used price and specs filters

**Comment by tigran-avdalyan** [comment]
it's very useful and important feature

**Comment by tigran-avdalyan** [comment]
[https://github.com/nopSolutions/nopCommerce/issues/2080](url)

**Comment by tigran-avdalyan** [comment]
https://github.com/patrickkunka/mixitup

**Comment by tigran-avdalyan** [comment]
Add Categories Filter by Drop Down List
Add Manufacturer Filter by Drop Down List(multi select)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
Why admins need to write price ranges fore categories, let ability to autoset price range(min= minimum price of product in  current categorie and max= maximum price of product in current categorie).
and the customer can select filter with price slider.

**Comment by tigran-avdalyan** [comment]
@AndreiMaz
 Hi
Nopcommerce Team is really think that this function is not high important for Online Store?

**Comment by tigran-avdalyan** [comment]
Move them to the left box(Configurable)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
Hi
When You planning to add this feature? 
Can be a part of 4.20?

**Comment by AndreiMaz** [comment]
See suggestion at https://github.com/nopSolutions/nopCommerce/issues/4104

**Comment by tigran-avdalyan** [comment]
Please see https://www.nopcommerce.com/boards/topic/74433/admin-dashboard-data-based-on-store-for-multi-store-mode

**Comment by holydk** [comment]
Closed #276
