### ISSUE TITLE
Product available for pre-order

### ISSUE THREAD

**Issue by SharePointShaz** [nopSolutions/nopCommerce#2763]
In version 4.00, ProductModelFactory.PrepareProductAddToCartModel fails to flag a product's AddToCart model as pre-order.
To fix the issue, I have changed the code from:
            if (product.AvailableForPreOrder)
            {
                model.AvailableForPreOrder = !product.PreOrderAvailabilityStartDateTimeUtc.HasValue ||
                    product.PreOrderAvailabilityStartDateTimeUtc.Value >= DateTime.UtcNow;
                model.PreOrderAvailabilityStartDateTimeUtc = product.PreOrderAvailabilityStartDateTimeUtc;
            }
to:
            if (product.AvailableForPreOrder)
            {
                model.AvailableForPreOrder = product.PreOrderAvailabilityStartDateTimeUtc.HasValue &&
                    product.PreOrderAvailabilityStartDateTimeUtc.Value <= DateTime.UtcNow;
                model.PreOrderAvailabilityStartDateTimeUtc = product.PreOrderAvailabilityStartDateTimeUtc;
            }

**Comment by AndreiMaz** [comment]
@SharePointShaz 
1. What is the diference? The boolean operation is just reverted. It works by design
2. How can we reproduce the issue?

**Comment by SharePointShaz** [comment]
@AndreiMaz 
I created a product that should be available for pre-order, but couldn't get the 'Add To Cart' to change to 'Pre-Order'.
Perhaps, the issue is less about the boolean operator but the greater than >= changing to less than <=. Ie the available to pre-order start date is in the past, not the future.

**Comment by AndreiMaz** [comment]
@SharePointShaz The hint states "'Pre-order' button will automatically be changed to 'Add to cart' at this moment.". So the design it works fine. 

But you're right that it's better to rename it to the "End date" so it doesn't confuse users. Thanks!

P.S. It worked this way in all previous versions, not in 4.00 only

**Comment by AndreiMaz** [comment]
After one more investigation I can confirm that everything is correct. This field states (even in source code comment) - the start date and time of the product availability (for pre-order products)

So when this product becomes available
