### ISSUE TITLE
remove some css styles in rtl

### ISSUE THREAD

**Issue by amirkhanjz** [nopSolutions/nopCommerce#2764]
hi,
in rtl version of default clean, there is a issue with text style,
rtl languages like persian,arabic,Hebrew or urdo dose not support UPPERCASE in TEXT-TRANSFORM style cause these languages don't have any uppercase like what you have (cause my mother language is persian) in english like "a & A, b & b". 
all of these languages have some letter changes when a letter come at the end of a word.
so
as this style used for about 38 times in style.rtl.css, i think this should be remove.
thanks

**Comment by AndreiMaz** [comment]
@amirkhanjz fixed in 4.10 by adding lang tag to html attribute
