### ISSUE TITLE
NOPCommerce 4.0 PayPal Express Plugin problem

### ISSUE THREAD

**Issue by zamliyconsulting** [nopSolutions/nopCommerce#2765]
I have admin area > configuration > settings > shipping settings configured and all warehouses have address setup.  Yet, I am seeing the following error when I try to use Express checkout.  I can checkout just fine with all other payment methods.

"An error occurred setting up your cart for PayPal."

I find the following error messages in the Log:
SetExpressCheckoutResponseType returned - Part 1 of 1
Error passing cart to PayPal
Shipping (USPS (US Postal Service)). Shipping address is not set
Shipping (FedEx). Shipping address is not set

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/paypalexpress-plugin-for-nopcommerce/issues/11
