### ISSUE TITLE
Product details page. Use tabs

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#277]
Using something like this: 

http://jqueryui.com/tabs/#manipulation 

Tabs on the product pages are such a common feature in ecommerce stores that it would be nice to have native support for tabs in nopcommerce. It also might be a need idea it you could have a setting that automatically made one tab that loaded all the reviews for a product. This would make the reviews in a nice easy to find place.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
