### ISSUE TITLE
WorkflowMessageService.GetActiveMessageTemplate failing to return active template

### ISSUE THREAD

**Issue by krlostoledo** [nopSolutions/nopCommerce#2775]
I have two messages templates for "**ShipmentSent.CustomerNotification**", but I'm sure it works the same for any messageTemplateName. The fist inactive and the second active.

Inside the **SendShipmentSentCustomerNotification** method from the **WorkflowMessageService**,  the next line is expecting an active message template:

`var messageTemplate = GetActiveMessageTemplate(
MessageTemplateSystemNames.ShipmentSentCustomerNotification,
 store.Id);`

In my case is always null cause **GetMessageTemplateByName**(first line in the previous method) is returning the first template, wich in my case is inactive. **GetMessageTemplateByName** should return the first active template instead.

**Comment by AndreiMaz** [comment]
thanks. we'll check. also see https://github.com/nopSolutions/nopCommerce/issues/2249 (related work item)
