### ISSUE TITLE
Multi-store shipping option configuration

### ISSUE THREAD

**Issue by adam3039** [nopSolutions/nopCommerce#2778]
It seems a little insane that I have to pay 90$ per store to get a plugin that allows me to define shipping options for multiple stores. Some of our stores only accept pickup as an option, and because of this, I actually need to pay for the plugin for every store.

The ability to set which shipping options are available on a per-store basis would be a huge feature for us. Even if the shipping configuration was shared (ie didn't need different UPS keys per store) and was just able to be toggled on/off per store would be a good first step.

**Comment by AndreiMaz** [comment]
@adam3039 Actually you already can do it. see demo at http://admin-demo.nopcommerce.com/Admin/FixedOrByWeight/Configure (advanced mode)

**Comment by adam3039** [comment]
Hey Andrei, thanks for the reply.

This seems to be only for the manual shipping option. My scenario is that I have some stores where they are pickup-only, and some stores that use the UPS plugin to get shipping estimates, etc. I don't believe this would work in that case?

**Comment by AndreiMaz** [comment]
@adam3039 it's possible. You can limit plugins by store on the plugin list page ("Edit" button)
