### ISSUE TITLE
Do not change plugin version in csproj files

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2779]
We already do it in plugin.json. Just reset version in csproj files to 1.00 (like we did it previous versions). 

This way we don't have to duplicate the work

**Comment by Xzelsius** [comment]
So you only have plugin.json to identify the exact version of a plugin assembly.
I cannot recommend this.

**Comment by AndreiMaz** [comment]
@Xzelsius why not? we avoid duplications

**Comment by Xzelsius** [comment]
Sure it is a duplication. But now you removed one important way to identify the real version of an assembly.
