### ISSUE TITLE
Allow Customers to Ask Question on Product Page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#278]
I see that Magneto lets customers asks questions about the product on the product page. This is a great feature because other customers can see the questions and answers. 

Forums source: http://www.nopcommerce.com/boards/t/14287/allow-customers-to-ask-question-on-product-page.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
