### ISSUE TITLE
browscap.crawlersonly.xml is not properly created

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2780]
Source: https://www.nopcommerce.com/boards/t/49880/40-not-using-browscapxml.aspx

**Comment by mdlyen** [comment]
I left a message in the forum post as well, but suggest maybe replacing "Elements()" with "Descendants()".  That fixed this problem for me.

**Comment by skoshelev** [comment]
Closed #2780
