### ISSUE TITLE
Unnecessary codes (Html, Js)

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2781]
Hi NopTeam,
You no longer need to use the following code snippets.

<pre><script type="text/javascript">
            $(document).ready(function () {
                    $("#back-in-stock-notify-me").on('click', function () {
                        var subscribeButton = this;
                        $.ajax({
                            cache: false,
                            type: "POST",
                            url: "@(Url.RouteUrl("BackInStockSubscribeSend"))",
                            data: { "productId": '@Model.ProductId' },
                            success: function (data) {
                                $(subscribeButton).closest('.ui-dialog-content').dialog('destroy').remove();
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                alert('Failed to change subscription.');
                            }
                        });
                    });
                });
            </script></pre>

Use these codes instead

<pre>
<script>
          $(function () {
                    $("#back-in-stock-notify-me").on('click', function () {
                        var subscribeButton = this;
                        $.ajax({
                            cache: false,
                            type: "POST",
                            url: "@(Url.RouteUrl("BackInStockSubscribeSend"))",
                            data: { "productId": '@Model.ProductId' },
                            success: function (data) {
                                $(subscribeButton).closest('.ui-dialog-content').dialog('destroy').remove();
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                alert('Failed to change subscription.');
                            }
                        });
                    });
                });
</script>
</pre>

**Comment by AndreiMaz** [comment]
What is the difference?  type="text/javascript"?

**Comment by fsefacan** [comment]
This feature has been removed with html5. JavaScript is detected by default when type="text/javascript" is not defined.
If you are going to use a custom script, you must define it.
For example, type="text/x-kendo-template"
