### ISSUE TITLE
Issue into product picture upload on admin side

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2783]
1. nopCommerce version : 4.0
2. Any private modifications you made to your nopCommerce: No
3. The version of MS SQL database you're running nopCommerce with: MSSQL2016 
4. Anything else that could possibly be relevant: Not sure

Steps of reproduction:

1. Go to admin > product > edit > picture.
2. Select and Upload one picture.
3. Do not remove that picture and add it again
4. Now you can see, there are two same pictures get uploaded.
5. Delete one of from it
6. Try to delete second one, it will give you an error.

![bug](https://user-images.githubusercontent.com/5019111/33982839-1df8d450-e0c3-11e7-9610-ac281fbe1cd2.gif)

Source: https://www.nopcommerce.com/boards/t/49921/issue-into-product-picture-upload-on-admin-side.aspx

**Comment by Xzelsius** [comment]
We had the same issue in one of our plugins where we adapted the logic from product pictures.

**The reason for this behavior is simple**: The "Add a new picture" block doesn't get cleared so the same picture id is added to multiple product picture mappings entries but can only be deleted once.

We resolved this simple by reloading/clearing the "Add a new picture" block.

**Comment by skoshelev** [comment]
Closed #2783
