### ISSUE TITLE
Billing address page, missing country and province

### ISSUE THREAD

**Issue by alexmvubiz** [nopSolutions/nopCommerce#2784]
On checkout/billingaddress page we have user information for country and province.
For some reason  "new address" section not populate this information. (screenshot)

![image](https://user-images.githubusercontent.com/34549404/34004239-57a221aa-e0c5-11e7-8367-cd99d556a4d8.png)

**Comment by skoshelev** [comment]
We ignored country and state for preliminarily because it can cause some issues when posting a pack with errors, but you can uncomment the necessary code in the AddressModelFactory.PrepareAddressModel method and get this functioning.

Closed #2784
