### ISSUE TITLE
Think out about using MediatR for event mechanism

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2785]
From the https://github.com/nopSolutions/nopCommerce/issues/2631#issuecomment-335754467

**Comment by a-patel** [comment]
@RomanovM 
MediatR has two kinds of messages it dispatches:
- Request/response messages, dispatched to a single handler
- Notification messages, dispatched to multiple handlers

It is also easy to integrate with Autofac.

**Comment by RomanovM** [comment]
@a-patel Yes, I see. But what are benefits of using it over our current approach? We can already notify single or multiple handlers, and not using third-party libraries.

**Comment by a-patel** [comment]
@RomanovM , Yes, We already have own handlers, 
By using MediatR, there is no need to write own logic, also in future we can get their updated logic/approach same like other third party libraries (Autofac, AutoMapper).

This is my personal view, nothing else.

**Comment by a-patel** [comment]
I would also suggest Hangfire library for Task/scheduler.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided to leave our current event mechanism
