### ISSUE TITLE
An error occurred while starting the application

### ISSUE THREAD

**Issue by ADoosti** [nopSolutions/nopCommerce#2787]
Hi
When I send a request
the server seys:
An error occurred while starting the application.

.NET Framework 4.6.1590.0 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.0.0-rtm-26452    |    Microsoft Windows 6.3.9600    |   Need help? 

This is my log file:
[stdout_2768_2017121716336.log](https://github.com/nopSolutions/nopCommerce/files/1565835/stdout_2768_2017121716336.log)

**Comment by ADoosti** [comment]
Who can help me to solve this problem?

**Comment by ADoosti** [comment]
I used windows authentication in my connection string

**Comment by AndreiMaz** [comment]
"No database instance" - there's n osuch database as per your connection string

P.S. Please post all technical questions on our forums. Github is only for tasks to be implemented

**Comment by ADoosti** [comment]
Ok
Thanks for your answer.
I create a topic in your forum.
