### ISSUE TITLE
Use full path of images in emails (campaigns, message templates)

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2789]
Do it automatically in rich editor. But let's make it configurable (so it can be disabled). 

Look at https://www.tinymce.com/docs/demo/url-conversion/

**Comment by skoshelev** [comment]
Even though by default, rich editor adds all images with relative paths we can change them to absolute paths without any problem. We can change images' URLs in the templates manually on the "Edit message template details" page.
