### ISSUE TITLE
Move widget zones names to separate class

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2791]
The same way as we do it for customer generic attributes names https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Customers/SystemCustomerAttributeNames.cs

See also: https://www.nopcommerce.com/boards/topic/74676/make-publicwidgetzones-and-adminwidgetzones-constant

**Comment by kwestground** [comment]
Would be nice to have an interface so nop core and plugins can access other plugins widgets zones. 
Eg. 'load all available widgets zones'

**Comment by skoshelev** [comment]
Closed #2791

**Comment by kwestground** [comment]
@skoshelev Just an minor reflection, shouldn't the AdminWidgetZones static properties be constants instead?

**Comment by skoshelev** [comment]
@kwestground It is better to use static properties, as this is a more common practice and there is not much difference for the end-user and speed of access

**Comment by kwestground** [comment]
@skoshelev For example when using AdminWidgetZones in an switch, you cannot use static values, only compile-time constants.

```csharp
        public IViewComponentResult Invoke(string widgetZone, object additionalData)
        {
            switch (widgetZone)
            {
                case AdminWidgetZones.OrderListButtons:
                    return this.View("~/Plugins/Example/Views/OrderListButtons.cshtml");
                case AdminWidgetZones.HeaderBefore:
                    return this.View("~/Plugins/Example/Views/OrderListButtons.form.cshtml");
            }

            return null;
        }
```

**Comment by AndreiMaz** [comment]
Already implemented as planned
