### ISSUE TITLE
Support Bitcoin payment in NopCommerce(as a plugin, by default installing with NopCommerce)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2792]
for example we can use ELECTRUM MERCHANT SERVICE

http://docs.electrum.org/en/latest/merchant.html

**Comment by AndreiMaz** [comment]
Hi Tigran,

Thanks! But we do not plan to add new plugins out of the box. It's better if someone from community will develop it. please see https://www.nopcommerce.com/boards/t/46303/list-of-possible-integrations.aspx
