### ISSUE TITLE
Detrimental multiple redirecting(seocode, www, https)

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2793]
Hi nopTeam,

HttpsRequirementAttribute
WwwRequirementAttribute
CheckLanguageSeoCodeAttribute

You need to merge the operations in the above three filter attribute and make a single redirect.
When I do the Pagespeed Test, I get multiple redirect alerts.

1. Redirects https://domain.com
2. Redirects https://www.domain.com
3. Redirects https://www.domain.com/en

It needs to be this way with one direction
https://www.domain.com/en

**Comment by demckee** [comment]
I don't understand why this has an "on hold/maybe won't" tag. There are multiple spots where multiple redirections are generated. For example: https://www.nopcommerce.com/boards/t/48817/multiple-redirects.aspx

Fixing this should be pretty straightforward. All of these attributes use similar code to form their redirection. Just build one routine in a common spot (like IWebHelper) and use the routine to form the redirected URL.

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave the current implementation (not a real issue)
