### ISSUE TITLE
Payment restrictions>>payment method friendly name

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2799]
We have 3 Credit Card, need to add other Unique identificator.

**Comment by AndreiMaz** [comment]
please clarify

**Comment by tigran-avdalyan** [comment]
![untitled](https://user-images.githubusercontent.com/17789934/34347994-e548bcc6-ea20-11e7-98f7-8013fbe7f6f0.png)

**Comment by tigran-avdalyan** [comment]
we can add Credit Card types like>>Manual , PayPalDirect , Square , WorldpayUS

**Comment by AndreiMaz** [comment]
@tigran-avdalyan It uses friendly name of payment plugins. It's by design. We should not use system name. 

Please note that in live stores a store owner will have only ONE payment plugins with "Credit card" friendly name. Otherwise, it can also confuse customers during checkout
