### ISSUE TITLE
Product Attribute Combination Pictures

### ISSUE THREAD

**Issue by mplummer** [nopSolutions/nopCommerce#2803]
Problem:

Each product (item for sale in the store e.g. Sunglasses) had its own picture, however, each product attribute combination (any possible combination of attributes that the product may have e.g. Frame & Lens Color –> Metal & Blue) would be forced to share the products default image. There are Attribute Images in NopCommerce, but they do not cater for the full permutation. For example, above you could see the different Sunglasses Frames, but each with only one lens color; or each lens color but with only one frame.

We have added a Picture per Product Attribute Combination on the Admin Side, and made the Store Front show this combination if selected (otherwise it defaults back to the previous logic), as well as in the Order List and Shopping Cart. 

We would like to create a pull request for review

**Comment by mplummer** [comment]
#2804 Pull Request Created

**Comment by RomanovM** [comment]
related with https://github.com/nopSolutions/nopCommerce/issues/290

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/290

**Comment by mplummer** [comment]
Are you still going to review the #2804 ? We have done and tested all the code. Thx
