### ISSUE TITLE
Can't see order details page for guest checkout

### ISSUE THREAD

**Issue by tompten111** [nopSolutions/nopCommerce#2809]
Hi,

1. I Open Chrome browser.
2. I do a purchase and checkout as guest.

3. I Open Internet Explorer (another browser, different from the one I used in step 1 and 2.) By doing this I don't have any cached data from the purchase.
4. I open the placed order email I have received, and click on the order details link.
5. The order details page is never showed. So the link is not working.

Much of the order data is of course in the email. But not my order notes that are marked Display for customer. So I don't know if all my customers get the intended information. That's the problem.
This is also why I created the suggestion #2808 

(I'm running version 4.00 in Azure.
The Email account is set up to use SendGrid in Azure)

**Comment by AndreiMaz** [comment]
@tompten111 Thanks! But it's the only way to see order details for guests (use the same computer) because cookies are stored only into it.

It's not secure to allow viewing order details page without cookies (e.g. using query string parameter, etc)
