### ISSUE TITLE
Why has this about s7.addthis.com/js/250  is a trojan

### ISSUE THREAD

**Issue by foxmishy** [nopSolutions/nopCommerce#2810]
PageShareCode = "<div class=\"addthis_toolbox addthis_default_style \"><a class=\"addthis_button_preferred_1\"></a><a class=\"addthis_button_preferred_2\"></a><a class=\"addthis_button_preferred_3\"></a><a class=\"addthis_button_preferred_4\"></a><a class=\"addthis_button_compact\"></a><a class=\"addthis_counter addthis_bubble_style\"></a></div><script type=\"text/javascript\" src=\"http://s7.addthis.com/js/250/addthis_widget.js#pubid=nopsolutions\"></script>",

**Comment by AndreiMaz** [comment]
It's not a trojan of course. Why do ytou think so?
