### ISSUE TITLE
Release compilation

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2813]
Can't compile Release version.
Synced to this point: https://github.com/nopSolutions/nopCommerce/commit/923fe949d07b0a35749b92a18aa77adae44b8c26

Error:
'C:\Projects\NopCommerce4.0\nopCommerce\src\Presentation\Nop.Web\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1/win7-x86'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers.	Nop.Web	C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167

**Comment by ArturAlekseev** [comment]
Switching platform target to Any CPU resolves the problem.

**Comment by ArturAlekseev** [comment]
Also because it is related to publishing. I had a problem. When I'v published release version to file system (to folder) - only some plugins from plugins folder were copied. I don't know why. There were only a few from originally available (like 4-5).

**Comment by AndreiMaz** [comment]
@ArturAlekseev Have you rebuilt the application before publishing? Have you done step 2 from http://docs.nopcommerce.com/pages/viewpage.action?pageId=1442493

**Comment by ArturAlekseev** [comment]
Yes, I'v rebuild it with release settings before (many times).
Strange thing is that now i'v tried it without <RuntimeIdentifier> and it compiled fine and published fine.
Maybe my components cache was damaged (yesterday i'v deleted it).

**Comment by skoshelev** [comment]
Can't reproduce. Closed #2813

**Comment by msmiljanic** [comment]
Could be caused by different target framework in the plugin.
