### ISSUE TITLE
Enable-Migrations not working nop 4.0.0

### ISSUE THREAD

**Issue by dev-siberia** [nopSolutions/nopCommerce#2814]
I want to use code first to change the database.
1) Edit property Order model
2) project Nop.Web add connectionStrings to web.config 
`<connectionStrings>
    <add name="NopObjectContext" connectionString="Data Source=DESKTOP-NU90PN1\\SQLEXPRESS;Initial Catalog=db_name;Persist Security Info=True;User ID=sa;Password=12345678" providerName="System.Data.SqlClient" />
  </connectionStrings>`
3) Package manager console set default project: Libraries\Nop.Data and run command: Enable-Migrations
    console error message: The EntityFramework package is not installed on project 'Nop.Data'.
4) Nop.Data add nuget package: EntityFramework 6.2.0
5) Retry step 2
   console error message:  

> Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToke
n=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\alexu\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:720 char:5
     $domain.SetData('project', $project)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : SerializationException 
Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToke
n=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\alexu\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:721 char:5
     $domain.SetData('contextProject', $contextProject)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : SerializationException
 Exception calling "SetData" with "2" argument(s): "Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToke
n=b03f5f7f11d50a3a' is not marked as serializable."
At C:\Users\alexu\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:722 char:5
     $domain.SetData('startUpProject', $startUpProject)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : SerializationException
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetPropertyValue[T](Project project, String propertyName)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.FindContextToEnable(String contextTypeName)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Object reference not set to an instance of an object.

Used such commands, they did not help:
`Enable-Migrations -ProjectName Nop.Data -StartUpProjectName Nop.Web`

`enable-migrations -ContextProjectName Nop.Data -StartUpProjectName Nop.Web -ContextTypeName Nop.Data.NopObjectContext -ProjectName Nop.Data`

**Comment by AndreiMaz** [comment]
@dev-siberia This github issue tracker is used only for features to be implemented (or bugs). Could you please post all questions on our forums (https://www.nopcommerce.com/boards/)
P.S. We don't use EF migrations
