### ISSUE TITLE
Plugins support Multistore

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2816]
Ability to Configure or Enable/Disable for each store.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan you already can do on the plugin list page (see "Edit" button)  - popup window

**Comment by tigran-avdalyan** [comment]
its  Limited to stores function
i mean Multi-store configuration for function

**Comment by AndreiMaz** [comment]
@tigran-avdalyan 
1. Most plugins already support multi-store configuration on the "configuration" page
2. And "Limited to store" allows you to enable/disable per store
