### ISSUE TITLE
Rental period calculation

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2817]
if we add rental product with price 1 month  100$
and customer select 3 month 20 days price calculating 300$,
i think price is 300$ + (20/month days)*100$

its will work in this calculation method when we add price by day 1 day 100$/30
but its not right method.

**Comment by tigran-avdalyan** [comment]
i think we need rounding function for rental period .

**Comment by AndreiMaz** [comment]
@tigran-avdalyan we don't plan to support it. In this case you have to enter price per day (e.g. $3 per day in admin area) if you allow to rent per days
