### ISSUE TITLE
Support Offer(like in Ebay)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2818]
Let ability to send offer from customer to saler, and from saler to customer.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Could you please provide more info? Like a quote? Auction?

BTW, We also ready this work item https://github.com/nopSolutions/nopCommerce/issues/279. Is it the same?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz I'm not sure
in Ebay there is a button "buy now" (like add to cart in Nopcommerce), and can have Offer button, customer can send his offer and comments. System give the time for seller respond. Seller can accept , reject, counteroffer, or wait until offer expired.

**Comment by AndreiMaz** [comment]
so it's https://github.com/nopSolutions/nopCommerce/issues/279
