### ISSUE TITLE
Notifiying Customer about Failed Payment for Redirect

### ISSUE THREAD

**Issue by wize1** [nopSolutions/nopCommerce#2822]
Hi guys,

I have issue where customers which use redirect payment flow, do not clearly get notified of failed payment. So for example, if error happens on Post Process method or on Redirect Handler, here is no process provided by nopcommerce for plugin developer to let customer know that the payment failed, and they do not actually know that you could retry payment or they need reorder it. Here is also no clear way to display reason for failed payment. I know you get page order details page where customer can retry or reorder, but how does customer know what was reason for failed payment and how does he actually know that he needs to go to that page and retry his payment.

For example if we look at PayPal Standard plugin source code PDTHandler, if payment successful it redirects to CheckoutCompleted, which notifies customer that payment has been processed successfully, but if payment fails it just adds Order Notes and redirects him to homepage(???), no email no nothing... Now if you simple person which never used nopcommerce and have no idea that your payment failed, or what is reason for fail, or that if you can and retry that payment or retry order. Even on OrderDetails view at first glance, its really hard to notice that order that payment is not paid.

I think here needs to be couple of things done for this matter:
1. We need to have similar view to CheckoutCompleted, but PaymentFailed which will display customer with friendly details of why his payment failed and what can he do now to fix it? where he can retry payment or re-create order and buttons to do so.
2. We also need to be able to send standard email, notifying him of failed payment with same details mentioned before, for those payments which dont actually redirect  handler action.
3. NopCommerce documentation needs to clearly explain on what is good practice for handling such process, so meaning it must let developer know that on successful payment in RedirectHandler action  he needs to redirect to CheckoutCompleted, and if the payment fails it needs to go and redirect to the PaymentFailed ..... even better I think there should be standard action for RedirectReturnHandler and method which can be overriten, which is called by that standard action and if method executred wihthout error that standard action will follow succes process and redirects to CheckoutCompleted, else if fails it will execute fail process with sending email and redirecting PaymentFailed view. Same goes for scenarious with webhooks, but only differents it will be sending email, instead for redirecting to view.

I hope that what i wrote make sense, if not please let me know, so i can I try to explain myself more clearly.

Best regards, Dmitriy

**Comment by ArturAlekseev** [comment]
You make payment failed view inside your payment plugin. Then you give link to this view to your payment gateway. If payment is failed then user is redirected by payment gateway to your view.
I have such workflow for my two gateways I use (russian Robokassa & Yandex).
I think all redirect gateways are similiar.

**Comment by wize1** [comment]
Thanks Artur for your input,

I also have payment plugins i wrote myself and I also do have my own failed payment view in it as well.
But the issue I'm trying to address is that here is no standard for this process, every plugin have its own view for it, which will not same as view from other plugin, also some plugin might not even have that view  and if you do not have source of that plugin there is little that you can do fix this. Like I mentioned before good example of this issue is PayPal Standard plugin which comes with NopCommerce, given you have source for that one, but if you didnt you wouldnt be able to fix it.

Thats why i propsosed for NopCommerce to have standard view and action for this process, which will call method which could be overriden and customised in plugin. I think its nice and clean solution for this issue.

**Comment by AndreiMaz** [comment]
@wize1 That's right. Each plugin will have to handle it

Could you please clarify about PayPal Standard? How to reproduce the issue?
