### ISSUE TITLE
project not open in visual studio 2015

### ISSUE THREAD

**Issue by romantiki** [nopSolutions/nopCommerce#2825]
Error : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\nopCommerce-develop\src\Presentation\Nop.Web\Nop.Web.csproj

**Comment by AndreiMaz** [comment]
VS 2017 is required as per our requirements page
