### ISSUE TITLE
Add Control Types for Specification Attributes

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2835]
Ability to add Control Types for Specification Attributes(in "Add a new specification attribute" page), then in Categories customer can filter not only with list like now, but with dropdownlist, radiobutton , checkbox, dropdownlist with checkboxes.

**Comment by tigran-avdalyan** [comment]
![untitled2](https://user-images.githubusercontent.com/17789934/35109791-cb756bb4-fc90-11e7-84f0-5c75e4e5c026.png)

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box and leave it for customization
