### ISSUE TITLE
Settings>>General>>Default Theme

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2837]
.theme-selection-block .checkbox {
    float: left;
}

i think float parameter needs to be right

**Comment by mariannk** [comment]
@tigran-avdalyan Why do you think it should be right?

**Comment by tigran-avdalyan** [comment]
@mariannk i think right for RTL
Left more beautiful  for LTR.

**Comment by mariannk** [comment]
@tigran-avdalyan but now it's right for RTL and left for LTR as you said, and everything looks fine.

**Comment by tigran-avdalyan** [comment]
Sorry all is true

**Comment by tigran-avdalyan** [comment]
@mariannk  in my pc resolution, when i have 5 themes installed , themes go to right, but needs to be left.
Sorry my mistake
