### ISSUE TITLE
Add some new constants values

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2842]
Currently some hard-coded strings used in Linq query, which are used more than one places.
Convert all those hard-coded strings into constants values.
e.g.
- Topic
- Category
- Manufacturer
- Product
- BlogPost
- NewsItem
- Vendor,
- Customer (GenericAttribute)

Which are used in GenericAttribute and UrlRecord tables

1. GenericAttribute.KeyGroup
2. UrlRecord.EntityName

**Comment by a-patel** [comment]
Any update?

**Comment by RuS984** [comment]
#2842 Closed

**Comment by RuS984** [comment]
https://github.com/nopSolutions/nopCommerce/commit/5fb94c1ace5da50ffc35b19cceba7a76a7da29df
