### ISSUE TITLE
Can't test GetLocalized method in service project because work context was resolved in that method

### ISSUE THREAD

**Issue by AliDehghani** [nopSolutions/nopCommerce#2843]
nopCommerce version: 
4.00

Hi
I try to write a test for GetLocalized method from Nop.Service.Test project, but Getlocalized method has following line of code:
`var workContext = EngineContext.Current.Resolve<IWorkContext>();`
this code actually needs Nop.Web.Framework to resolve IWorkContext but service shouldn't have reference to framework and because of that I can't resolve work context and this code throws and exception. I think we should avoid to use resolve in service project and must pass work context to that method.

**Comment by skoshelev** [comment]
Hi @AliDehghani . Please look code in the BaseValidatorTests class, it's show how to replace IEngine instanse in EngineContext.

**Comment by AliDehghani** [comment]
Ok thanks, but how about standard .Net framework versions, for example nopCommerce v3.90?

**Comment by skoshelev** [comment]
@AliDehghani,  I dont know about all version, but this way must working from 3.70 to 4.00 versions

**Comment by AminMozhgani** [comment]
Look at this line:
 var serviceProvider = MockRepository.GenerateMock<IServiceProvider>();
We don't have any IServiceProvider in those versions. Instead we have ContainerManager and we can't mock this class because of lack of IContainerManager interface...
