### ISSUE TITLE
Move all Models and Factories out of Nop.Web

### ISSUE THREAD

**Issue by demckee** [nopSolutions/nopCommerce#2846]
At the moment, all Models and their Factories are in the Nop.Web project. This forces any plugin which uses or changes a model to have a project reference to Nop.Web. This forces the plugin to be built after Nop.Web is built, which means that the "extra" code to delete the copied dlls doesn't always work. This is one of the reasons you have to build the solution multiple times. Publishing the solution would also be cleaned up by this step.

It would be cleaner for the Models to be in Nop.Services. The Factories are really services, and the models are just simple classes with minimal logic. This would simplify things. If you don't want to bloat Nop.Services, I'd suggest a new project.

**Comment by curelom** [comment]
Amen.  With the model's in nop.web, it complicates the builds

**Comment by AndreiMaz** [comment]
@demckee Could you please clarify the following?
"extra code to delete the copied dlls doesn't always work. This is one of the reasons you have to build the solution multiple times"

**Comment by demckee** [comment]
From what I understand, the ClearPluginAssemblies code runs after the Nop.Web project is built. If you have a plugin, it might not be built before Nop.Web is. The result is that the plugin output directories might or might not be cleared. If you have a project that depends on Nop.Web, it will always be built after Nop.Web, and thus the dlls might not be deleted.

If you take the system and Clean it, then build the solution, you will find that not all of the plugin directories are properly cleaned. If you build a second time they will be. You get similar results when you publish - if you don't do a couple of full solution builds before publishing, not all plugins will be properly built.

**Comment by skoshelev** [comment]
Hello @demckee. You are right, but if you open .csproj file from anyone of our plugins you could see a separate execution of cleaning procedure.

**Comment by demckee** [comment]
I'm not going to say I totally understand all of the stuff that's going on when the solution is built. I've read the csproj files, both for plugins and nop.web. From the comments, there is extra work being done in nop.web after the project is built.

That being said, I do know there are lots of weirdness going on during a build. Running a Clean doesn't always work - you have to run it multiple times. Similarly running a build all doesn't always work. Again you have to do this multiple times. Publish is another one like this. I suspect it's mostly a Visual Studio issue, but again I don't know. It really just comes down to it not working well.

Nop.Web is the target of everything - it's what is run. Logically, Nop.Web depends on all of the plugins to operate cleanly, but VS doesn't know/understand that. The models/factories shouldn't be in Nop.Web if you expect anyone to ever need access to them from a plugin. In fact, Nop.Web shouldn't have anything that will need to be used from a plugin.

**Comment by dahlbyk** [comment]
General 👍 for Nop.Web not having anything plugins might depend on. I ended up integrating my plugin back into the main project due to this.

> Logically, Nop.Web depends on all of the plugins to operate cleanly, but VS doesn't know/understand that.

FYI, you can also set up Project Dependencies under Solution Properties in VS, which causes plugins to be built (and copied into `Nop.Web/Plugins`) before Nop.Web.
![image](https://user-images.githubusercontent.com/133987/37214197-e7b63136-2379-11e8-82b7-b8e84e1e18d2.png)

This shows up in the `.sln` as:

```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Nop.Web", "Presentation\Nop.Web\Nop.Web.csproj", "{4F1F649C-1020-45BE-A487-F416D9297FF3}"
        ProjectSection(ProjectDependencies) = postProject
                {446FED73-BCA1-4D8F-BC13-EA1507C7EF29} = {446FED73-BCA1-4D8F-BC13-EA1507C7EF29}
                {681581B5-745F-4B35-A1F4-AA63961BA950} = {681581B5-745F-4B35-A1F4-AA63961BA950}
                {560768D4-7E1D-4431-99F0-CC14C255E167} = {560768D4-7E1D-4431-99F0-CC14C255E167}
                {C2B83AF5-80F6-4B8C-8628-FA7DE10C3BB5} = {C2B83AF5-80F6-4B8C-8628-FA7DE10C3BB5}
        EndProjectSection
EndProject
```

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box

**Comment by demckee** [comment]
Would you be so kind as to explain why this suggestion was rejected? There was no negative feedback (including from the team). Indeed, there was only positive feedback. So, why reject it?
