### ISSUE TITLE
Hot to override admin views in plugin in nopcommerce 4.0

### ISSUE THREAD

**Issue by B-Esmaili** [nopSolutions/nopCommerce#2847]
I am trying to override `DateTime.cshtml` view in my plugin.I created same directory structure as in `Admin\Views\Shared\EditorTemplates\DateTime.cshtml` in my plugin but no luck.any idea ?

**Comment by AndreiMaz** [comment]
@B-Esmaili this issue tracker is only for work item. Could you please post all questions on our forums? Thanks!
