### ISSUE TITLE
Specification attributes & Product attributes limitation by store

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2849]
nopCommerce version: 4.00

Expected behavior: Need to separate attributes for each store. Because if you have Multi store(food and electronics) and have many attributes, and attributes of Store1 not used in Store2, more comfortable to separate.
Actual behavior: set limitation for Attributes

**Comment by AndreiMaz** [comment]
@tigran-avdalyan do you mean in admin area when managing products?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Yes

**Comment by tigran-avdalyan** [comment]
@AndreiMaz For example we have 2 stores FOOD and Cars.
we have Specification attribute -- Engine.
We need to limit that Specification attribute for use only in  Cars store.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan just don't use this specification attribute for products available in the FOOD store

**Comment by tigran-avdalyan** [comment]
@AndreiMaz its easy when you have 10 attributes, but when you have 500, its very hard.

**Comment by tigran-avdalyan** [comment]
@AndreiMaz and no logic, when vendor or admin want to add food product, why he see Engine or Gearbox ?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
This is small list of specification attributes.(Only Mobile Phones & Real estate specification attributes)
![error2](https://user-images.githubusercontent.com/17789934/36483529-da7c079e-172f-11e8-9631-af638e29853e.gif)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
iDEA
Can we Group specification attributes, 
and when we add specification attribute need ability to add Group of attributes. Then like in Bulk editor, selecting the Attribute options.

**Comment by eadameg** [comment]
There is a [plugin](https://www.nopcommerce.com/p/3088/bulk-product-editor-ellasoftwarecom.aspx) which might solve this problem. I think that NopAdming handles grouped  specifications

**Comment by szocco** [comment]
This is an issue for us as well. We have multiple stores trying to manage products that use attributes. The list of product attributes is getting quite large. Each store has it's own administrator in charge of managing products and attributes. It would be very beneficial to us to be able to limit the list of product attributes by store.

**Comment by AndreiMaz** [comment]
We don't plan to implement it out of the box.

But we think about dropdownlists with "Search" functionality (filter textbox) for dropdownlists with a lot of values
