### ISSUE TITLE
Multi store-individual admin for each store 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2850]
nopCommerce version: 4.0

Expected behavior: We have multi-store, and have individual administrators for each store, but Nopcommerce have one Admin for all stores.

Actual behavior: Need to set individual Admins for each store

**Comment by Xzelsius** [comment]
A way to do this is extending PermissionRecord with store id and handle this properly.

**Comment by eadameg** [comment]
There is a multi-tenant plugin that could be used for this purpose

**Comment by AndreiMaz** [comment]
please see https://github.com/nopSolutions/nopCommerce/issues/225
but we do not plan to do it
