### ISSUE TITLE
Installing New Template, Plugins and Theme do not show in Adminstration

### ISSUE THREAD

**Issue by Ramasagar** [nopSolutions/nopCommerce#2858]
nopCommerce version: 4.0

Expected behavior: trying to install darkorange theme from https://www.nop-templates.com copied  all files to themes folder and to plugins folder

Actual behavior: 

Steps to reproduce the problem:

**Comment by AndreiMaz** [comment]
It works fine. Maybe, some 4.00 version is support (or wrong version is uploaded)

But it's better to address nop-templates team to get the support

**Comment by AndreiMaz** [comment]
@poyker Boyko, please check
