### ISSUE TITLE
Idea: Track Wishlist Customer on ShoppingCartItem

### ISSUE THREAD

**Issue by dahlbyk** [nopSolutions/nopCommerce#2859]
nopCommerce version: 4.00

Expected behavior: when a wish list item is added to cart, the cart keeps track of which customer's wish list it came from.

Actual behavior: cart items have no indication they came from a wish list, or whose.

Related: https://github.com/nopSolutions/nopCommerce/issues/1921

-------

I intend to implement something like this for a current project, but before I do I was curious if you would be interested in having this contributed to the core product.

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box and leave it for customization
