### ISSUE TITLE
Bulk edition of orders

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#286]
It is useful when there are several orders per day, to bulk edit order/payment/shipping status/dates and tracking number, similar to product bulk edition. Maybe some restriction would apply when an order is split in various shippings. 

Let's think about what exactly could be moved to bulk edit functionality

Forum source: http://www.nopcommerce.com/boards/t/27284/suggestion-bulk-edition-of-orders.aspx

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/1926
