### ISSUE TITLE
Cant able to Deploy Nop commerce 4.10 to Azure Virtual Machine using Visual studio 2017 

### ISSUE THREAD

**Issue by Ramasagar** [nopSolutions/nopCommerce#2861]
nopCommerce version: 4.10

Expected behavior: Deploying in Azure Virtual machine

Actual behavior: Facing errors while deploying Nop commerce in Azure virtual machine through Visual studio 2017..Even after i publish to local folder and copying the files to root folder of my virtual machine it throws me 500 internal server error.
\

**Comment by DmitriyKulagin** [comment]
@Ramasagar 
You need to make sure that the VM and IIS are configured correctly. Check the permissions on the folder in which the site is deployed. Also I recommend to update [net core sdk](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-windows-x64-installer) and [NET CoreRuntime & Hosting Bundle for Windows](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.2-windows-hosting-bundle-installer)
