### ISSUE TITLE
in Specification Attribute add Text prompt

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2862]
nopCommerce version: 4.0

Expected behavior:
Actual behavior:  Situation when we have Electronic Store, and have Specification "Display Size" for Monitors. "Display Size" have Values 17", 21", 23":

And we have Mobile Phones , Mobile Phones have Specification "Display Size" , if i add mobile phone screen sizes to that list, its wrong, its mean i need to create new Specification, But with different name, but i need to show in product page as Display Size:

Steps to reproduce the problem:

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Thanks. But we don't plan to implement it out of the box.
