### ISSUE TITLE
Support multi language product reviews/ratings

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2863]
would be great to implement ILocalizedEntity for  product reviews/ratings

**Comment by AndreiMaz** [comment]
Thanks for suggestion!

I don't think that anybody will write a review in several languages (ILocalizedEntity). Maybe, we could just add "LanguageId" property to reviews. So we can filter them by current customer language (or sort by the current language)

But after some consideration decided not to implement it out of the box and leave it for customization
