### ISSUE TITLE
Discounts with limitations. Add a note that it's ignored for recurring products

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2864]
The original issue is described at https://www.nopcommerce.com/boards/t/50799/recurring-products-evaluate-discount-coupons-again-for-next-cycles.aspx

also see the second comment at https://www.nopcommerce.com/boards/t/50799/recurring-products-evaluate-discount-coupons-again-for-next-cycles.aspx#200384

So let's add a hint to "Discount limitations" dropdownlist that it could be ignored when used recurring products

**Comment by DmitriyKulagin** [comment]
closed #2864
