### ISSUE TITLE
Product Price - individual Multi currency Support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2868]
nopCommerce version: 4.0

Expected behavior: I have Multi-Store Multi-Vendor and Multi-Currency Store, and my same Vendors Sale by USD, other by RUB, My same Store Sale by USD, same mixed USD & Rub.

Actual behavior: Now i can only set fixed currency by Primary, and use it for All. Its not Flexible.

Steps to reproduce the problem: I need to set price for product with digits, and then choose currency for price.

**Comment by tigran-avdalyan** [comment]
Legal aspect
in Russian you can sale only with RUB's
in Armenia you can sale only with AMD's
and more

**Comment by AndreiMaz** [comment]
@tigran-avdalyan already exists - https://github.com/nopSolutions/nopCommerce/issues/1

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Situation:We have product Price is 1000$ Product cost is 29100 RUB=500$ (But we can write only with USD because USD is primary currency) Exchange rate for now is 1$=58.2RUB

But in next day USD rate go down and 1$= 20 RUB
Now Product cost=500$=10000RUB 
and it is wrong 
i'm right?
