### ISSUE TITLE
Unable to extend NopCommerce models in plugins.

### ISSUE THREAD

**Issue by B-Esmaili** [nopSolutions/nopCommerce#2870]
In nopcommerce there are a lot of partial classes which seems to be there to be extended via plugins.but as mentioned in MS documents partial classes should be reside in same dll file.so the question is  what is the intention behind making models partial?and what is the correct way of extending models in nopcommerce?

**Comment by AndreiMaz** [comment]
@B-Esmaili Could you please psot all questions on our forums? We use github only for  work items
