### ISSUE TITLE
Allow to set shipping plugin restrictions by payment methods

### ISSUE THREAD

**Issue by emiliano84** [nopSolutions/nopCommerce#2872]
Would be nice to select the combinations of payment according to the shipping method, for example if I decide to pickup in store I can pay by cash or card, but if I decide for delivery I can pay only by card. thanks!

![nop](https://user-images.githubusercontent.com/7117301/36144562-57e89b38-10a6-11e8-8b7a-4b1ca8c06380.PNG)

**Comment by emiliano84** [comment]
any plan to squeeze this in 4.20 release? :)

**Comment by Leftyx** [comment]
I've implemented something like this in `PayInStore` Plugin (`PayInStorePaymentProcessor.cs`):

```
/// <summary>
/// Returns a value indicating whether payment method should be hidden during checkout
/// </summary>
/// <param name="cart">Shoping cart</param>
/// <returns>true - hide; false - display.</returns>
public bool HidePaymentMethod(IList<ShoppingCartItem> cart)
{
    //you can put any logic here
    //for example, hide this payment method if all products in the cart are downloadable
    //or hide this payment method if current customer is from certain country
    if (_workContext.CurrentCustomer.ShippingAddress == null)
    {
	return true;
    }

    return false;
}
```

after injecting `_workContext`.

@AndreiMaz: Do you think it can work or is there anything else I need to be aware of ?

**Comment by emiliano84** [comment]
@AndreiMaz any plan to squeeze this in 4.30? :)

**Comment by emiliano84** [comment]
@AndreiMaz  any update on this? hopefully in the next release? :)

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
