### ISSUE TITLE
Canonical URL should lowercase site URL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2874]
nopCommerce version: 400

Steps to reproduce the problem: 
1. Enable  canonnical URLs
2. Enable language prefix. For example, www.site.com/en and www.site.com/ru
3. Go to a product details page www.site.com/en/product-name and to www.site.com/EN/product-name (e.g. Google crawled it)
4. You'll get a notification (warning), then these pages have the same time or meta data. It's because Google thinkgs these pages are distincts
5. We have to lowercase the first part - www.site.com/en/

More details at our premium support portal (ticket 13915)

**Comment by Joebeazelman** [comment]
Has this issue been fixed?  If you click on the following URL:

http://demo.nopcommerce.com/DIGITAL-DOWNLOADS

It will not rewrite it to lowercase.
