### ISSUE TITLE
PayPal Direct doesn't work anymore

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2876]
nopCommerce version: all

Looks lile PayPal doesn't support this API anymore (REST API). We have to decide:

1. Upgrade it to some newer API (also check our previous API)
or
2.  Remove out of the box. Anyway, it doesn't support tokenization, etc. And it can be used only by quite big stores (PCI compliant stores)

**Comment by cklenk** [comment]
Is this why I get a Payment error: The operation has timed out (HTTP request timeout was set to 30000ms) when using PayPal Direct?

**Comment by rahulmistry25425** [comment]
I am also getting "Payment error: The operation has timed out (HTTP request timeout was set to 30000ms)"

Intresting thing is while i'm using my personal client id and secret its working fine, But this is not working with My client's personal clientid and secret.

**Comment by AndreiMaz** [comment]
decided to move the plugin to marketplace
