### ISSUE TITLE
Reward Points - Order details in admin panel

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2879]
nopCommerce version: 4.00

When I've paid an order with reward points and go to admin panel, I saw this:

![rewardpoints - copy 1](https://user-images.githubusercontent.com/5019111/36323021-997a2eba-1360-11e8-897b-fb267c086776.png)

How to reproduce this issue? Just pay order with reward points.

Source: https://www.nopcommerce.com/boards/t/50912/reward-points-order-details-in-admin-panel.aspx

**Comment by skoshelev** [comment]
Closed #2879
