### ISSUE TITLE
Schedule Task "The operation has timed out"

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#2881]
nopCommerce version: 4.00

Expected behavior: Does not throw an Error

Actual behavior: When running a schedule task it will sometimes throw an error:

`Log level	
Error
Short message	
The operation has timed out
Full message	
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at Nop.Services.Tasks.TaskThread.Run()`

I think because in `Nop.Services Tasks TaskThread.cs` it's using `client.UploadValues` which has the opertunity to time out? I was thinking of testing it with `client.UploadValuesAsync(_scheduleTaskUrlUri, postData);` instead. I haven't yet.

Steps to reproduce the problem: It did it on my custom plugins

**Comment by evidentit** [comment]
I find the same errors in the Log and keep alive does not work. Most time it works but somtimes the error occures.

**Comment by AndreiMaz** [comment]
Most probably some network issue or wrong store URL specified in admin area
