### ISSUE TITLE
Basic - Advanced settings multi-store support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2882]
nopCommerce version:4.00 

Expected behavior: We can set setting for Basic - Advanced mode in Product Detail page. But we cant set individual settings for every store.

Actual behavior: Need ability to set setting for every store individual.

Steps to reproduce the problem:

**Comment by Xzelsius** [comment]
I didn't knew that product edit page is store specific

**Comment by tigran-avdalyan** [comment]
@Xzelsius Yes example of product- Cars, Real Estate
in Real Estate store we don't need to show Shipping box
in store where only have Rental services products don't need to show Shipping box
in store where we sale digital keys, we don't need to show Shipping box
and more more examples.
Now i think you know.

**Comment by Xzelsius** [comment]
I already knew that before.

What I mean is that nopCommerce Admin is not store specific.

**Comment by tigran-avdalyan** [comment]
For Administrators not specific, but same Admin Panel use Vendors to, and for Vendors its specific

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box and leave it for customization
