### ISSUE TITLE
Display of Tiered Prices

### ISSUE THREAD

**Issue by demckee** [nopSolutions/nopCommerce#2884]
When a product has tiered prices, the system displays "From price" wherever it would normally display the price. The problem is that the price shown is the lowest possible price. We've found that this confuses the customers, so we changed it so it displays the highest price instead.

This should really be something that can be customized easily. I realize it uses a localized string for the "From", but we really need something more - the ability to select whether to show the highest price, the lowest price or maybe even a price range.

I built this into one of my plugins. I have a localized string in the plugin's settings which is a format string like "{l} to {h}". The {l} gets replaced by the lowest price, while the {h} gets the highest price. If it would help, I could make this code available.

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box and leave it for customization
