### ISSUE TITLE
NoSQL for language resource, settings, localized entities and logs

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#2885]
Hi team,

Do you think you should use a nosql database for language, localized entities, settings, logs and maybe product combination and discount usage history?

As far as I can see they are given the maximum number of transactions.
It would be sensible to abstract this data from SQL so that a website running in high traffic can respond quickly.

MongoDb, Cosmos etc.

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided not to implement it out of the box
