### ISSUE TITLE
Adding Routes in nopcommerce 4.0 plugin

### ISSUE THREAD

**Issue by layinka** [nopSolutions/nopCommerce#2887]
nopCommerce version: 4.0

Expected behavior:  Adding routes through routeproviders in plugin should make routes available

Actual behavior:  Routes not showing up, i.e getting 404 error

Steps to reproduce the problem: 
-Create a plugin 
-add a routeprovider class with some routes
-Try to visit any of the routes

**Comment by dahlbyk** [comment]
@layinka adding routes via plugin is working for me. Pardon the obvious question, but is your plugin installed? If not, it will be ignored in [`RoutePublisher`](https://github.com/nopSolutions/nopCommerce/blob/dae3e4dfe5178443153d11368c4c44931d96e432/src/Presentation/Nop.Web.Framework/Mvc/Routing/RoutePublisher.cs#L48-L51).

**Comment by layinka** [comment]
I have seen what was wrong.

Things have changed in nopcommerce 4 since its now based on asp.net core.

Now   i have to explicitly put the area in the route setup

**Comment by AndreiMaz** [comment]
it works fine. I would suggest to post it on our forums to investigate your plugin
