### ISSUE TITLE
Profit always positive

### ISSUE THREAD

**Issue by haithamo** [nopSolutions/nopCommerce#2888]
nopCommerce version: 3.8

Expected behavior: Profit become negative in case cost price greater than selling price

Actual behavior: Profit is positive even though the cost price is greater than selling price.

In case the culture En-US

Steps to reproduce the problem: Open order has one product which the cost price is greater than selling price

You can find the line which causes this issue
PriceFormatter.cs ==> GetCurrencyString

result = amount.ToString("C", new CultureInfo(targetCurrency.DisplayLocale));

![record_2018_02_26_12_41_25_622](https://user-images.githubusercontent.com/7094596/36666258-b7bb4410-1af2-11e8-8a6e-b803bf5ba4b9.gif)

**Comment by Xzelsius** [comment]
Same in 3.9

**Comment by rao4** [comment]
The software is formatting the string correctly to denote a negative by wrapping it in parentheses. This is a common accounting format for denoting negative numbers under en-US.
