### ISSUE TITLE
uploading html editor files does not honour media settings store in database?

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2891]
nopCommerce version: 3.90

Expected behavior: store source files uploaded using html editor filemanager in database if media setting is database 

and (maybe) serve files using azure blob storage if configured?

Actual behavior: source files uploaded using html editor filemanager are always uploaded to disk

Steps to reproduce the problem: 

- set media setting store in db
- optionally configure azure blob
- upload image using html editor file manager
- file is stored in /Content/Images/upload instead of database

this is an issue when setting up CICD and azure staging slots, this means we lose files uploaded by customer on production

Part of https://github.com/nopSolutions/nopCommerce/issues/2494

**Comment by leo-tabakov** [comment]
Absolutely agree. This is a big issue for CI/CD environments and will not allow using azure staging slot for slot swaps.

Moreover, this behavior might be also an issue for web farms configurations which may lead to data inconsistency between multiple instances.

**Comment by skoshelev** [comment]
Closed #2891(https://github.com/nopSolutions/nopCommerce/commit/f434eca9eb5f1f31efc891256eebdb6c2cc3a533)

**Comment by rudgr** [comment]
Tx for fixing this, great!

Just wondering: this only applies to uploaded images right?
So when user uploads files like for example PDF documents, they are stored on disk and still might get "lost" after swapping deployment slots in azure?
