### ISSUE TITLE
Azure SQL INDEX recommendations

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2896]
nopCommerce version: v3.90

`CREATE NONCLUSTERED INDEX [nci_wi_QueuedEmail_0F39F41CAE67BD5A3A12DAF9C70F365C] ON [dbo].[QueuedEmail] ([SentOnUtc], [DontSendBeforeDateUtc]) INCLUDE ([SentTries]) WITH (ONLINE = ON)`

`CREATE NONCLUSTERED INDEX [nci_wi_QueuedEmail_0F39F41CAE67BD5A3A12DAF9C70F365C] ON [dbo].[QueuedEmail] ([SentOnUtc], [DontSendBeforeDateUtc]) INCLUDE ([SentTries]) WITH (ONLINE = ON)`

**Comment by skoshelev** [comment]
Closed #2896
