### ISSUE TITLE
Unobvious search behavior in admin area when <Ignore option "limit per store" rules> option enabled

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#2898]
nopCommerce version: 4.10

For example: on the "Products" page we try to search all product limitation to specific store, but if the <Ignore option "limit per store" rules> option enabled, this filter isn't working. 
I suggest hiding this filter on all pages that contain this search field when this setting is enabled 

Also note that it's ignored not for all entities. For example, it'll work fine for product reviews and orders

**Comment by RuS984** [comment]
Closed #2898
