### ISSUE TITLE
Shipping Cost VAT calculation in incorrect according to dutch law (probably same for EU?)

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2905]
nopCommerce version: 3.90

Expected behavior: 

Which VAT rate?

> The logical next question is then which VAT rate should you use? The VAT rate of the shipping costs is equal to that of your goods. In short, the tariff is therefore variable. If your goods are taxed at a high rate, this also applies to the shipping costs. However, if there are goods with different VAT rates on the invoice, you use the percentage of the highest VAT rate used. If your goods are free of VAT, you do not have to charge VAT on the shipping costs.

https://www.informer.nl/wel-geen-btw-verzendkosten/

Actual behavior: 

in nopCommerce currently VAT percentage is a fixed setting/category, independent of cart contents

Steps to reproduce the problem: 

- enable VAT on shipping and choose a VAT category/percentage 
- configure 2 products, one with VAT high, the other VAT low
- add low vat product to cart and confirm order > shipping cost vat should be low vat
- add high vat product to cart and confirm order > shipping cost vat should be high vat
- add both products to cart and confirm order > shipping cost vat should be high vat

**Comment by AndreiMaz** [comment]
@rudgr Hi Rutger. Please check the following commit and let me know if it works as expected - https://github.com/nopSolutions/nopCommerce/commit/fd41506c0904234a05e04f838fdb47c7f627ca34

BTW, what shipping rate computation method do you use?

**Comment by RomanovM** [comment]
After some consideration decided not to implement it out of the box right now. But you can use the  changes from this commit https://github.com/nopSolutions/nopCommerce/commit/fd41506c0904234a05e04f838fdb47c7f627ca34
