### ISSUE TITLE
 The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.

### ISSUE THREAD

**Issue by matteobortolazzo** [nopSolutions/nopCommerce#2906]
nopCommerce version: 4.0

Expected behavior: No compiling errors

Actual behavior: compiling errors

Steps to reproduce the problem: run "dotnet build" on a clean project

Hi, running "dotnet build" it fails to compile, this is a problem because I cannot set up a CI/CD properly, what can I do?

src\Build\ClearPluginAssemblies.proj(110,5): error : MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild

**Comment by dahlbyk** [comment]
This is a duplicate of https://github.com/nopSolutions/nopCommerce/issues/2728, fixed by https://github.com/nopSolutions/nopCommerce/commit/c53a37d03558df9afc134dce5d8c6369b6db563e.
