### ISSUE TITLE
Mark attribute combinations as unavailable

### ISSUE THREAD

**Issue by vucetica** [nopSolutions/nopCommerce#2909]
nopCommerce version: 4.0

Expected behavior: When the user selects an attribute value, attribute values for available attribute combinations should be differentiated from the ones that are not available. Screenshot from amazon is attached (page https://smile.amazon.com/Blue-Cache-Desktop-Drive-WD10EZEX/dp/B013HNYVCE):

![untitled](https://user-images.githubusercontent.com/129988/37222614-c6ebe582-239b-11e8-9b97-d2b8fab18ec2.png)

Actual behavior: User has to click on many combinations to figure out which one is in stock.

Steps to reproduce the problem: Open a product page for a product whose inventory is managed through attribute combinations, having some of the combinations unavailable or out of stock.

Suggested solution
=============

Server side
------------
1. shoppingcart/productdetails_attributechange action should receive one more parameter: selected_product_attribute_id, which is the id of the attribute that user clicked on.
2. if shoppingcart/productdetails_attributechange action receives selected_product_attribute_id it should return one more property:
...
accepted_attribute_values: [
{
  attribute_id: 1981,
  accepted_value_ids: [123, 123],
  unaccepted_value_ids: [222]
},
{
  attribute_id: 1981,
  accepted_value_ids: [127, 128],
  unaccepted_value_ids: []
}
]
...

This result will be built using these rules:
2.1. Find all product attribute combinations that are valid for the selected value of selected_product_attribute_id.
2.2. For each attribute in the product, buld a return object with these properties:
attribute_id - id of that attribute
accepted_value_ids - go through all attribute values and pick those that appear in acceptable combinations
unaccepted_value_ids - the opposite from accepted_value_ids

Client side
-----------
When shoppingcart/productdetails_attributechange is completed, for all attribute values remove css classes "accepted" and "unaccepted". For all attribute values in the accepted_value_ids list, add "accepted" css class, for the ones in unaccepted_value_ids add "unaccepted" css class.

**Comment by vucetica** [comment]
@AndreiMaz, I would like to implement this solution as proposed. Is that ok?

**Comment by Araujovski** [comment]
> nopCommerce version: 4.0
> 
> Expected behavior: When the user selects an attribute value, attribute values for available attribute combinations should be differentiated from the ones that are not available. Screenshot from amazon is attached (page https://smile.amazon.com/Blue-Cache-Desktop-Drive-WD10EZEX/dp/B013HNYVCE):
> 
> ![untitled](https://user-images.githubusercontent.com/129988/37222614-c6ebe582-239b-11e8-9b97-d2b8fab18ec2.png)
> 
> Actual behavior: User has to click on many combinations to figure out which one is in stock.
> 
> Steps to reproduce the problem: Open a product page for a product whose inventory is managed through attribute combinations, having some of the combinations unavailable or out of stock.
> 
> # Suggested solution
> ## Server side
> 1. shoppingcart/productdetails_attributechange action should receive one more parameter: selected_product_attribute_id, which is the id of the attribute that user clicked on.
> 2. if shoppingcart/productdetails_attributechange action receives selected_product_attribute_id it should return one more property:
>    ...
>    accepted_attribute_values: [
>    {
>    attribute_id: 1981,
>    accepted_value_ids: [123, 123],
>    unaccepted_value_ids: [222]
>    },
>    {
>    attribute_id: 1981,
>    accepted_value_ids: [127, 128],
>    unaccepted_value_ids: []
>    }
>    ]
>    ...
> 
> This result will be built using these rules:
> 2.1. Find all product attribute combinations that are valid for the selected value of selected_product_attribute_id.
> 2.2. For each attribute in the product, buld a return object with these properties:
> attribute_id - id of that attribute
> accepted_value_ids - go through all attribute values and pick those that appear in acceptable combinations
> unaccepted_value_ids - the opposite from accepted_value_ids
> 
> ## Client side
> When shoppingcart/productdetails_attributechange is completed, for all attribute values remove css classes "accepted" and "unaccepted". For all attribute values in the accepted_value_ids list, add "accepted" css class, for the ones in unaccepted_value_ids add "unaccepted" css class.

Hi Vucetica,

I don't understand.
Can you help me? Please.

Best Regards,
Araujovski.

**Comment by vucetica** [comment]
Hi @Araujovski.

Can you clarify? Which part you don't understand?

**Comment by Araujovski** [comment]
Hi,

I have two lists:
->valid attributes ;
->invalid attributes.
This is developted in "ShoppingCartController".
It's work... but don't work in client side... I think it is "_ProductAtributes.cshtml". I'm so sad.
Can you help me?

Best Regards,
Araujovski.

________________________________
De: Aleksandar Vucetic <notifications@github.com>
Enviado: 20 de dezembro de 2019 14:25
Para: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Araujovski <luyx.bcl@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nopSolutions/nopCommerce] Mark attribute combinations as unavailable (#2909)


Hi @Araujovski<https://github.com/Araujovski>.

Can you clarify? Which part you don't understand?

**Comment by vucetica** [comment]
@Araujovski , I didn't implement this in the end (and not working on nopcommerce stuff these days). Guys from nopcommerce marked it as onhold/won't do. I see that it is active now, and I'm not sure if someone from the nopcommerce team is working on it.

**Comment by Araujovski** [comment]
In atually no one is working on it. Do you know what you can call client side controller values?

Best Regards,
Araujovski.
________________________________
De: Aleksandar Vucetic <notifications@github.com>
Enviado: 20 de dezembro de 2019 14:56
Para: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Araujovski <luyx.bcl@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nopSolutions/nopCommerce] Mark attribute combinations as unavailable (#2909)


@Araujovski<https://github.com/Araujovski> , I didn't implement this in the end (and not working on nopcommerce stuff these days). Guys from nopcommerce marked it as onhold/won't do. I see that it is active now, and I'm not sure if someone from the nopcommerce team is working on it.

**Comment by vucetica** [comment]
Sorry, not on the project anymore.

**Comment by Araujovski** [comment]
but know what you can call client side controller values? Please...
________________________________
De: Aleksandar Vucetic <notifications@github.com>
Enviado: 20 de dezembro de 2019 15:19
Para: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Araujovski <luyx.bcl@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nopSolutions/nopCommerce] Mark attribute combinations as unavailable (#2909)


Sorry, not on the project anymore.

**Comment by vucetica** [comment]
@Araujovski , I really don't understand the question. What do you mean by "what you can call client side controller values"? Can you give me an example?

**Comment by Araujovski** [comment]
I have two lists:
-> disabledAttributeValues;
-> enabledAttributeValues;
In function "ProductDetails_AttributeChange", this function belongs "ShoppingCartController.cs".

How do I analyze these two lists in client side?


Best Regards,
Araujovski.

________________________________
De: Aleksandar Vucetic <notifications@github.com>
Enviado: 20 de dezembro de 2019 16:45
Para: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Araujovski <luyx.bcl@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nopSolutions/nopCommerce] Mark attribute combinations as unavailable (#2909)


@Araujovski<https://github.com/Araujovski> , I really don't understand the question. What do you mean by "what you can call client side controller values"? Can you give me an example?

**Comment by vucetica** [comment]
I'm sorry, I can't help you with that.

**Comment by Araujovski** [comment]
Why?
________________________________
De: Aleksandar Vucetic <notifications@github.com>
Enviado: 20 de dezembro de 2019 17:13
Para: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Araujovski <luyx.bcl@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nopSolutions/nopCommerce] Mark attribute combinations as unavailable (#2909)


I'm sorry, I can't help you with that.

**Comment by holydk** [comment]
Closed #2909
