### ISSUE TITLE
Product Attribute control type  Data Picker (min and max values)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2910]
nopCommerce version: 4.00

Expected behavior: need ability to add Data Picker min and max values

Actual behavior: now customer can set any data

Steps to reproduce the problem: add min and max values for Data picker(in Product Attribute control type)

idea: in future for advanced configuration we can add allowed Data Ranges(from min1 to max1, from min2 to max2 and ....)

**Comment by AndreiMaz** [comment]
Thank. but duplicated https://github.com/nopSolutions/nopCommerce/issues/336
