### ISSUE TITLE
Generate all possible combinations --- generate wrong combinations 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2911]
i add product in admin-demo.nopcommerce.com
with product attributes (all attributes Is Required )
Software - g, gg, ggg
Color - A, B
HDD- 1,2,3      Condition Color:A
Print-  X,Y,Z     Condition  Color:B
Size- XXXXXXX    Condition  Software:g

But when i generate all possible combinations

Software: g
Color: A
HDD: 1
Size:   XXXXXXX

Software: gg
Color: A
HDD: 1
Print:   X

Software: ggg
Color: A
HDD: 1
Print:   X

Software: g
Color: B
Print: X
Size:   XXXXXXX

Software: gg
Color: B
HDD: 1
Print:   X

Software: ggg
Color: B
HDD: 1
Print:   X

Software: g
Color: A
HDD: 2
Size:   XXXXXXX

Software: gg
Color: A
HDD: 2
Print:   X

Software: ggg
Color: A
HDD: 2
Print:   X

Software: gg
Color: B
HDD: 2
Print:   X

Software: ggg
Color: B
HDD: 2
Print:   X

Software: g
Color: A
HDD: 3
Size:   XXXXXXX

Software: gg
Color: A
HDD: 3
Print:   X

Software: ggg
Color: A
HDD: 3
Print:   X

Software: gg
Color: B
HDD: 3
Print:   X

Software: ggg
Color: B
HDD: 3
Print:   X

Software: gg
Color: A
HDD: 1
Print:   Y

Software: ggg
Color: A
HDD: 1
Print:   Y

Software: g
Color: B
Print: Y
Size:   XXXXXXX

Software: gg
Color: B
HDD: 1
Print:   Y

Software: ggg
Color: B
HDD: 1
Print:   Y

Software: gg
Color: A
HDD: 2
Print:   Y

Software: ggg
Color: A
HDD: 2
Print:   Y

Software: gg
Color: B
HDD: 2
Print:   Y

Software: ggg
Color: B
HDD: 2
Print:   Y

Software: gg
Color: A
HDD: 3
Print:   Y

Software: ggg
Color: A
HDD: 3
Print:   Y

Software: gg
Color: B
HDD: 3
Print:   Y

Software: ggg
Color: B
HDD: 3
Print:   Y

Software: gg
Color: A
HDD: 1
Print:   Z

Software: ggg
Color: A
HDD: 1
Print:   Z

Software: g
Color: B
Print: Z
Size:   XXXXXXX

Software: gg
Color: B
HDD: 1
Print:   Z

Software: ggg
Color: B
HDD: 1
Print:   Z

Software: gg
Color: A
HDD: 2
Print:   Z

Software: ggg
Color: A
HDD: 2
Print:   Z

Software: gg
Color: B
HDD: 2
Print:   Z

Software: ggg
Color: B
HDD: 2
Print:   Z

Software: gg
Color: A
HDD: 3
Print:   Z

Software: ggg
Color: A
HDD: 3
Print:   Z

Software: gg
Color: B
HDD: 3
Print:   Z

Software: ggg
Color: B
HDD: 3
Print:   Z

Software: gg
Color: B
Print:   X

Software: ggg
Color: B
Print:   X

Software: gg
Color: B
Print:   Y

Software: ggg
Color: B
Print:   Y

Software: gg
Color: B
Print:   Z

Software: ggg
Color: B
Print:   Z

Software: gg
Color: A
HDD: 1

Software: ggg
Color: A
HDD: 1

Software: gg
Color: A
HDD: 2

Software: ggg
Color: A
HDD: 2

Software: gg
Color: A
HDD: 3

Software: ggg
Color: A
HDD: 3

**Comment by skoshelev** [comment]
Closed #2911
