### ISSUE TITLE
Product attribute New Control type -- Multiselect DropDown List

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2912]
nopCommerce version: 4.00

Expected behavior: Now we have only DropDown List, and we can select only one item

Actual behavior: Need to select Multi items

Steps to reproduce the problem: Add new control type Multiselect DropDown List

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But after some consideration decided to leave it for customization
