### ISSUE TITLE
New category template error -BUG???

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2915]
nopCommerce version: 4.00

i duplicate  the file CategoryTemplate.ProductsInGridOrLines.cshtml and add as second category template.
i dont change the code only file name. 
and when i use it to category who have 2 subcategories, and show error.

**Comment by AndreiMaz** [comment]
What exactly error do you see?

**Comment by tigran-avdalyan** [comment]
Default error template, We're sorry, an internal error occurred. ......

**Comment by tigran-avdalyan** [comment]
@AndreiMaz sorry its my local system issue, i correct it, all works fine

**Comment by AndreiMaz** [comment]
ok
