### ISSUE TITLE
Solution causes VS to freeze/hang very frequently

### ISSUE THREAD

**Issue by travisterrell** [nopSolutions/nopCommerce#2919]
nopCommerce version: 4.00+

I experience terrible performance in Visual Studio when working with the nopCommerce solution, at almost all times. It hangs and freezes for long periods of time (minutes) during loading, editing, and building. At first, I thought it was just a lack of computer power, but I recently loaded it on my much more powerful work development computer. It's got a latest-gen quad core i7 processor with 16GB of RAM and an SSD. It was only _very slightly_ better, if any. It doesn't have any problems with the other, much larger, solutions I have to develop (one of which is an enormous 50gb, 127 project solution). For what it's worth, I disabled all extensions that I could, but to no avail.

Seeing how unexpectedly bad the performance was, even on my reasonably powerful work computer, I thought that it was maybe a problem with my specific solution, as it is one that I've customized significantly. So, I grabbed the latest stable release, but experienced similar poor performance.

Has anybody else experienced this? Does anybody have tips on how to proceed? It's really very difficult to get work completed, because more than half of my development time is spent waiting on Visual Studio to unfreeze. I'd greatly appreciate any advice you can provide. 

Thanks,
Travis

**Comment by Xzelsius** [comment]
I once had problems with and older VS 2017 version.
With current version (2017 Pro 15.6.1) I've no problems. 

What version are you on?

**Comment by travisterrell** [comment]
Hi,

I am running 2017 Enterprise 15.6.1. I just upgraded to the newest 15.6.2, and although I have not tried it yet, I'm not expecting vastly improved performance. I really wish I knew what it was about the project causing the poor performance. I regularly work with a half-dozen much-larger solutions, and do not experience the slow downs.. I can't figure out what is different in these solutions. Many of the projects they contain also use ASP.NET Core MVC, Entity Framework, etc. 

FWIW, during times that the Visual Studio is unresponsive, there is constant CPU usage of around 30-40 percent, usually. This is the only indication that the program is actually doing anything. And it generally does recover. Startup is the very worst, so I try to close the solution as rarely as possible. Building and debugging are actually not nearly as slow as startup. Judging by the lack of responses, I'm assuming not many other people have encountered (or been very bothered by) this issue. Perhaps if I post it in the forum, I'll get a wider range of responses.

I'm still open to any suggestions! Thanks.

**Comment by AndreiMaz** [comment]
We also experienced this issue in previous versions of VS. Now it works quite fine (resharper slowed it down as well)
