### ISSUE TITLE
RichText HTML editor not working

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2923]
nopCommerce version: 
4.00

Steps to reproduce the problem: 
adminareasettings.usericheditorinmessagetemplates = true

But HTML editor doesn't show up?

Previously this was working, all I did was a recompile and publish to azure and now the HTML editor stopped working. Any ideas where to start looking?

**Comment by skoshelev** [comment]
@rolandh I try to reproduce this issue, but I can't. Try to check this setting in the database, or send me your database backup by [PM](https://www.nopcommerce.com/sendpm.aspx?toid=156980).

**Comment by rolandh** [comment]
It turns out cloudflare was breaking the page with its compression. So nothing to do with nop.

**Comment by skoshelev** [comment]
Closed #2923
