### ISSUE TITLE
Associated products link in Grouped products

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2924]
nopCommerce version: 4.00

in Grouped products, if Associated products Visible individually parameter enabled ,then let Associated products is clickable. Link to Associated products detail page.

**Comment by tigran-avdalyan** [comment]
Now when we import products for current store, we can't ((((
product is importing and available  for all stores, then we manualy need to set Limitation.
import/export not support Multistore

**Comment by AndreiMaz** [comment]
@tigran-avdalyan what exactly link do you mean? product details page in public site?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz Yes

**Comment by AndreiMaz** [comment]
Thanks, Tigran. But we don't plan to implement it out of the box
