### ISSUE TITLE
Product Compare not check Product attributes

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2925]
nopCommerce version: 4.00

in demo.nopcommerce.com when we add to compare list "Build your own computer" with selected attributes, the system clean selected attributes, and show only base product without attributes.

Steps to reproduce the problem: Connect Specification attributes to Product attributes  #2280 

![error77](https://user-images.githubusercontent.com/17789934/37570810-e47c9190-2b0d-11e8-9838-537dc7b44261.gif)

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Product attributes are not somehow related to "compare products". It uses only specification attributes. It's by design.
