### ISSUE TITLE
BIG SECURITY RISK - anyone over the internet can run your website scheduled tasks

### ISSUE THREAD

**Issue by aghe** [nopSolutions/nopCommerce#2926]
nopCommerce version: tested on 4.0 (but from what i see even in next version is not fixed)

Steps to reproduce the problem: 

1. post taskType on this url: http://localhost:15536/scheduletask/runtask

See postman image bellow:
![screenshot_1](https://user-images.githubusercontent.com/20487209/37773031-23631d3c-2de5-11e8-92f1-c14a2ca69664.png)

2. on the example above the ClearLogTask is executed (no security check for running those tasks)

**Comment by skoshelev** [comment]
We deliberately did not include security checks for running scheduled tasks, but we restrict the execution of tasks to their time intervals, you can send many requests for running the task, but the task will not be performed until its time comes, it is guaranteed by this code:

// validation (so nobody else can invoke this method when he wants)
if (ScheduleTask.LastStartUtc.HasValue && (DateTime.UtcNow - ScheduleTask.LastStartUtc) .Value.TotalSeconds <ScheduleTask.Seconds)
     // too early
     return;

**Comment by aghe** [comment]
So if I add a new task (let's say to execute at interval for 12 hours) and enable it then someone else can run it before that interval?! (since there is not already executed - LastStartUtc do not have value)

**Comment by aghe** [comment]
This is still a security issue. You should not allow any user to have access to stuff that need admin rights.
Anyway, thanks for clarification.

**Comment by AndreiMaz** [comment]
@aghe there's no such bug. you can open this page but you CANNOT run a schedule task. We have appropriate validation in Task implementation. So everything is fine

**Comment by AndreiMaz** [comment]
UPDATE: please see "Execute" method of \Libraries\Nop.Services\Tasks\Task.cs

**Comment by aghe** [comment]
I did test it. If the task is not already executed anyone from the internet can execute it.
For example i want to have a task that can execute in 2 hours. I just enable it, do something else and when i'm back someone from the internet already started that.

I wanted to help you guys. If you don't want help fine. But the security problem is there.
Form the example I put there in bug. I clean up the log from a browser with no credentials at all.

From my point of view (and  I think from other security guys) this is a big security risk.

**Comment by ivanslater** [comment]
I agree with @aghe... or it is a security breach or, if by design, a design error. You can choose.

you should remove task route, so it cant be ran by GET requests.

**Comment by AndreiMaz** [comment]
Right, it's possible to execute a task that have never been run before. But it's very-very rare case. Because once a store is installed, all active tasks will be run at least once in a quite short period of time.

And it's not possible to run a tasks (that already ha been run at least once) by opening this URL.
