### ISSUE TITLE
Allow editing of Custom text for product specification attribute

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2927]
When adding specification attributes, if you add an Attribute type of [Custom text] and put in a value,  you currently cannot edit that value later.
It would be nice to be able to do this in the admin section.

Source: https://www.nopcommerce.com/boards/t/51351/next-version-allow-editing-of-custom-text-for-product-specification-attribute.aspx

**Comment by YongBoon** [comment]
Ya. It would be nice to be able to do this. More user friendly. Thanks

**Comment by dfoley-CH** [comment]
This feature would be great for us to

**Comment by RomanovM** [comment]
related with https://github.com/nopSolutions/nopCommerce/issues/2417
