### ISSUE TITLE
In-Memory Scheduled Task Lock

### ISSUE THREAD

**Issue by dahlbyk** [nopSolutions/nopCommerce#2930]
nopCommerce version: 4.00

Steps to reproduce the problem: 

1. Without Redis cache...
2. Enqueue email as usual
3. Observe (I use SendGrid's Activity Feed) that some emails are sent more than once

Would you accept a PR for an in-process lock, for those who aren't using Redis?

https://github.com/nopSolutions/nopCommerce/blob/be46bc279c6b9cba5dc7f49693094a654b1f3ab2/src/Libraries/Nop.Services/Tasks/Task.cs#L136-L148

**Comment by AndreiMaz** [comment]
@dahlbyk sure, please do it. and we'll investigate
