### ISSUE TITLE
Automatically add new customers to SendGrid

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2938]
Are there any plugins available that will automatically add new customers to sendgrid?

I want to do this as we use sendgrid to customise unsubscribe groups etc.

Edit: An alternative would be to allow specifying the X-SMTPAPI headers in the email campaigns. This is to allow me to achieve the ability to have multiple "newsletter" groups each with their own unsubscribe buttons.

https://sendgrid.com/docs/User_Guide/Transactional_Templates/create_edit.html#-Unsubscribe-Substitution-Tags
> When using the group unsubscribe substitution tag, you must specify which unsubscribe group you would like to use. If you are sending your email via our SMTP API, please add the group ID into the X-SMTPAPI header. If you are sending via our Web API, please enter the group ID into the x-smtpapi parameter of the mail. Send API call.

Here is the SMTP header that needs to be added
![image](https://user-images.githubusercontent.com/1109554/38069988-ebb13776-3360-11e8-820e-20aa99778b83.png)

**Comment by AndreiMaz** [comment]
@rolandh no, there's no such plugin - https://www.nopcommerce.com/marketplace.aspx?searchterm=sendgrid
