### ISSUE TITLE
Issue with TagHelper rounding decimal value to 2 decimals

### ISSUE THREAD

**Issue by darocker22** [nopSolutions/nopCommerce#2940]
nopCommerce version: 4.00

Steps to reproduce the problem: 
Set a product price to using more than 2 decimal places or added TierPricing and use more than 2 decimal places. When going back to edit the product the value that shows up in the Touchspin control will have the value rounded to 2 decimal places. In the TierPrice grid, it will show the correct value, but when you click the edit popup window you will see it rounded to 2 decimal places.

This didn't occur in version 3.9 since the razor TagHelpers were not used, and the EditorTemplates for decimals were using the TextboxFor.  The rounding is occurring in the default EditorTemplate for decimal.

I was able to make a change to the EditorTemplates\Decimal.cshtml and added the asp-format attribute
`<input asp-for="@Model" asp-format="{0:0.0000}"/> `

**Comment by AndreiMaz** [comment]
@darocker22 looks like the same as in https://github.com/nopSolutions/nopCommerce/issues/2869

**Comment by darocker22** [comment]
@AndreiMaz  thanks, just looked at that ticket# and its the same issue. I tried to look through all of the issues before submitting and didn't see that one. Also updated my original comment when i saw the code portion was  missing.

**Comment by AndreiMaz** [comment]
Thanks a lot. Fixed - https://github.com/nopSolutions/nopCommerce/commit/ba2f9ddacd4ab5bc9a3ddc739a10424d2a4e482f
