### ISSUE TITLE
Bundling and minification issue

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#2941]
nopCommerce version: 3.9

Steps to reproduce the problem: 

Go to admin => configuration => general settings => turn on bundling and minification for css and JavaScript.

Works fine in Chrome and Firefox. Totally breaks the site UI in Edge and internet explorer.

We turn that setting back off and everything is fine again. Another weird issue we are having.

**Comment by AndreiMaz** [comment]
@cklenk "Totally breaks" - what exactly error do you see? 
also try to enable/disable JS and CSS bundling separately
