### ISSUE TITLE
Make schedule task management overridable

### ISSUE THREAD

**Issue by kwestground** [nopSolutions/nopCommerce#2943]
I'm writing an [hangfire](https://www.hangfire.io/) schedule manager plugin instead of the default one for extended scheduling functionality.
But the schedule task classes does not support overriding and interaction as expected.

Some suggested refactoring:
- TaskManager should have an interface
- ScheduleTaskService CRUD operations should publish events.
- ScheduleTaskController.RunNow() should not directly call Task.Execute(), but instead ITaskManager.Execute()

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave current implementation
