### ISSUE TITLE
3.9 Bug fixes for the future

### ISSUE THREAD

**Issue by softwarebybrent** [nopSolutions/nopCommerce#2945]
nopCommerce version: 3.9 vs 4.0

Steps to reproduce the problem: 
N/A

This is more of a question than an issue, but we are evaluating using 3.9 vs 4.0.   Looking at the codebase for 4.0, it looks like a significant amount of effort went to moving to asp.net core 2. (Great work btw).  Am I correct in assuming that if we would choose to use 3.9, there won't be any 3.9.x releases in addition to 4.x releases that might have critical bug fixes in them?  We don't want to choose 3.9 if it means that the support isn't there unless we are on asp.net core 2 going forward.

Thanks!

**Comment by eadameg** [comment]
All bugs and fixes are always done in later versions $.x and never within the same version 3.9.x. By choosing  4.0 you also get the advantage of big performance improvements of AS:NET Core platform

**Comment by softwarebybrent** [comment]
Ok - Thats what we needed to know. Thank you!
