### ISSUE TITLE
MarkOrderAsPaid and concurrency issue

### ISSUE THREAD

**Issue by isupovs** [nopSolutions/nopCommerce#2946]
nopCommerce version: 3.70 (I haven't seen any changes for 4.0 though)

Hi there. I'm wondering if concurrency is an issue for someone else. I haven't found such a problem on forums. MarkOrderAsPaid method is not thread-safe. If a clearing service calls the "return" method twice (for example, but it's not big deal) a customer will be awarded with reward points twice. Even if I use a kind of lock there to check for order payment status, OrderService returns a cached object with the old payment status. I've solved it using direct IRepository injection. Is there a better way to handle this?

**Comment by AndreiMaz** [comment]
there could be a lot of concurrency issues, not just with payments. we'll investigate it
