### ISSUE TITLE
PO Number value is wrapped in double quotes, newlines and square brackets.

### ISSUE THREAD

**Issue by pcamp** [nopSolutions/nopCommerce#2949]
nopCommerce version: 4.10

Steps to reproduce the problem: 
Using the Purchase Order payment method plugin, enter a PO Number in the Payment Information checkout step.  On the Confirm Order step and on the Order Details view, the PO Number value appears wrapped in double quotes and square brackets.  It looks even worse on the PDF invoice, as there are newlines between the double quotes and the square brackets.

![ponumber](https://user-images.githubusercontent.com/7990762/38463778-abeb01ee-3ac7-11e8-91e9-dcc987adcb8e.png)

**Comment by skoshelev** [comment]
Moved to https://github.com/nopSolutions/purchaseorder-plugin-for-nopcommerce/issues/1
