### ISSUE TITLE
Use more secure password hashing algorithm. Other security enhacements

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#295]
With the recent password hash leak by LinkedIn/eHarmony, a lot of people are talking about password hashing algorithms. NopCommerce uses SHA-1 with a 5 character salt that is unique to each customer. That is much better than what LinkedIn was doing (MD5 with no salt) but it looks like even SHA-1 with salts can be brute forced in a reasonable time frame. (days) 

Is there any thought of offering Bcrypt or PBKDF2? I know PBKDF2 is built in to the .net framework (Stackoverflow switched from Bcrypt to PBKDF2). The benefit of these is that it takes .3 seconds to generate a hash versus milliseconds for MD5/SHA-1. That difference isn't a big deal when you're logging in but it greatly increases the time need to crack a hash. It goes from days to thousands of years. 

I was going to ask how one would handle switching hashing methods when customers are already registered and then saw that each customer has a PasswordFormatId. Awesome! 

Forum source: http://www.nopcommerce.com/boards/t/17505/password-hashing-algorithms.aspx 

[AM] It's already supported. Just set to CustomerSettings.HashedPasswordFormat to any new supported value - https://msdn.microsoft.com/ru-ru/library/wet69s13(v=vs.110).aspx

---

There has been some talk in the past about improving hash and encryption methods used in nopCommerce.  Over the past few days, I have worked on a solution that will work with the next version of nop, 3.90.
You can see the commit here:
https://github.com/f1ana/nopCommerce/commit/85ee625f2059519e7a5e0251d9d7484af2d356a9

I made the focus of this on new installations of nop since there was a pretty hard dependency on everything using sha1/3des out of the gate.  More so, this would likely break plugins that have existing data encrypted or hashed, so too many unknowns in my opinion to backport this.

Here's a recap of the changes:
- Stronger default hashes
- Stronger default encryption key
- Select hash and encryption at install time
- Add more unit tests for hash and encryption
- NopDropdownListFor support on installation page (kind of)

The reasons why I made these changes:
SHA1 is on the way out and we should be using some form of SHA2, either 256 or 512.
Unless I'm mistaken, 3DES is only used in 112 bit mode with nop since the keysize reports itself to be 128 bits.
There was a hard dependency in the system for 3DES.  The encryption service now mostly works seamlessly with any algorithm that inherits from the SymmetricAlgorithm class.
The default encryption key size is a 16 digit sequence which I feel makes it vulnerable to brute force attacks.  The new encryption key is a 32 character alphanumeric sequence.
Salts are now 16 bytes instead of 5.

If anyone finds value in this or thinks improvements should be made, please let me know.  If it is all good, I can put together a merge request on GitHub.

Also see contribution with other ehancements at http://www.nopcommerce.com/boards/t/43601/for-review-security-enhancements-for-nopcommerce-390.aspx

pull request: https://github.com/nopSolutions/nopCommerce/pull/1664

**Comment by f1ana** [comment]
PBKDF2 would be a nice feature to have, but would likely be a detriment to high traffic sites.  A high number of iterations on a site that processes several logins and registrations would be starved of CPU time.
It would be nice if nopCommerce were able to support (mostly) seamless upgrades of the hash format without breaking existing users.  If you change CustomerSettings.HashedPasswordFormat on an existing site from SHA1 to SHA256, If I read the code correctly, login attempts would compare passwords with different hash types, effectively breaking the site.
An indicator on the Customer entity of which hash format is used probably wouldn't hurt security.  A determined attacker will likely be able to determine the hash type used by inspecting the number of characters that the hash is anyway.
As an added bonus, if a customer with an older hash format logs into a system currently using a newer hash format, we can write the new value and thus the customer base will progressively migrate to a more secure format.

**Comment by m1dst** [comment]
I did some work on this some time ago...

Here is the hashing class I ended up with.  This is not in production yet but see if it helps you.

```
// Password Hashing With PBKDF2 (http://crackstation.net/hashing-security.htm).

using System;
using System.Security.Cryptography;
using System.Text;

namespace Nop.Services.Security
{
    /// <summary>
    /// Salted password hashing
    /// </summary>
    public class HashingService : IHashingService
    {

        /// <summary>
        /// Create a password hash
        /// </summary>
        /// <param name="password">{assword</param>
        /// <param name="salt">Salt</param>
        /// <param name="passwordFormat">Password format (hash algorithm)</param>
        /// <returns>Password hash</returns>
        public virtual string CreatePasswordHash(string password, string salt, string passwordFormat = "PBKDF2")
        {
            if (String.IsNullOrEmpty(passwordFormat))
                passwordFormat = "PBKDF2";

            var saltAndPassword = String.Concat(password, salt);

            if (passwordFormat == "PBKDF2")
            {
                // Generate a random salt
                var csprng = new RNGCryptoServiceProvider();
                var generatedSalt = new byte[SALT_BYTE_SIZE];
                csprng.GetBytes(generatedSalt);

                // Hash the password and encode the parameters
                var hash = PBKDF2(password, generatedSalt, PBKDF2_ITERATIONS, HASH_BYTE_SIZE);
                return PBKDF2_ITERATIONS + ":" + Convert.ToBase64String(generatedSalt) + ":" + Convert.ToBase64String(hash);
            }

            var algorithm = HashAlgorithm.Create(passwordFormat);
            if (algorithm == null)
                throw new ArgumentException("Unrecognized hash name");

            var hashByteArray = algorithm.ComputeHash(Encoding.UTF8.GetBytes(saltAndPassword));
            return BitConverter.ToString(hashByteArray).Replace("-", "");
        }

        /// <summary>
        /// Validates a password hash
        /// </summary>
        /// <param name="password">Password to validate</param>
        /// <param name="salt">Salt</param>
        /// <param name="correctHash">Saved password hash</param>
        /// <param name="passwordFormat">Password format (hash algorithm)</param>
        /// <returns>Boolean</returns>
        public virtual bool ValidatePasswordHash(string password, string salt, string correctHash, string passwordFormat = "PBKDF2")
        {
            if (String.IsNullOrEmpty(passwordFormat))
                passwordFormat = "PBKDF2";

            if (passwordFormat == "PBKDF2")
            {
                return ValidatePBKDF2Password(password, correctHash);
            }

            var generatedHash = CreatePasswordHash(password, salt, passwordFormat);
            return generatedHash == correctHash;
        }

        /// <summary>
        /// Generate salt
        /// </summary>
        /// <param name="size">Key size</param>
        /// <returns>Salt</returns>
        public virtual string GenerateSalt(int size)
        {
            // Generate a cryptographic random number
            var rng = new RNGCryptoServiceProvider();
            var buff = new byte[size];
            rng.GetBytes(buff);

            // Return a Base64 string representation of the random number
            return Convert.ToBase64String(buff);
        }

        #region PBKDF2

        // The following constants may be changed without breaking existing hashes.
        public const int SALT_BYTE_SIZE = 24;
        public const int HASH_BYTE_SIZE = 24;
        public const int PBKDF2_ITERATIONS = 1000;

        public const int ITERATION_INDEX = 0;
        public const int SALT_INDEX = 1;
        public const int PBKDF2_INDEX = 2;

        /// <summary>
        /// Validates a password given a hash of the correct one.
        /// </summary>
        /// <param name="password">The password to check.</param>
        /// <param name="correctHash">A hash of the correct password.</param>
        /// <returns>True if the password is correct. False otherwise.</returns>
        private bool ValidatePBKDF2Password(string password, string correctHash)
        {
            try
            {
                // Extract the parameters from the hash
                char[] delimiter = { ':' };
                var split = correctHash.Split(delimiter);
                var iterations = Int32.Parse(split[ITERATION_INDEX]);
                var salt = Convert.FromBase64String(split[SALT_INDEX]);
                var hash = Convert.FromBase64String(split[PBKDF2_INDEX]);

                var testHash = PBKDF2(password, salt, iterations, hash.Length);
                return SlowEquals(hash, testHash);

            }
            catch
            {
                // Something is wrong and perhaps it isn't a PBKDF2 Hash.
                return false;
            }

        }

        /// <summary>
        /// Compares two byte arrays in length-constant time. This comparison
        /// method is used so that password hashes cannot be extracted from
        /// on-line systems using a timing attack and then attacked off-line.
        /// </summary>
        /// <param name="a">The first byte array.</param>
        /// <param name="b">The second byte array.</param>
        /// <returns>True if both byte arrays are equal. False otherwise.</returns>
        private bool SlowEquals(byte[] a, byte[] b)
        {
            var diff = (uint)a.Length ^ (uint)b.Length;
            for (var i = 0; i < a.Length && i < b.Length; i++)
                diff |= (uint)(a[i] ^ b[i]);
            return diff == 0;
        }

        /// <summary>
        /// Computes the PBKDF2-SHA1 hash of a password.
        /// </summary>
        /// <param name="password">The password to hash.</param>
        /// <param name="salt">The salt.</param>
        /// <param name="iterations">The PBKDF2 iteration count.</param>
        /// <param name="outputBytes">The length of the hash to generate, in bytes.</param>
        /// <returns>A hash of the password.</returns>
        private byte[] PBKDF2(string password, byte[] salt, int iterations, int outputBytes)
        {
            var pbkdf2 = new Rfc2898DeriveBytes(password, salt) { IterationCount = iterations };
            return pbkdf2.GetBytes(outputBytes);
        }

        #endregion
    }
}

```

and when setting/changing a password you use something like this....

```
var salt = (_customerSettings.HashedPasswordFormat == "PBKDF2") ? null : _hashingService.GenerateSalt(8);
customer.PasswordSalt = salt;
customer.Password = _hashingService.CreatePasswordHash(request.NewPassword, salt, _customerSettings.HashedPasswordFormat);
```

**Comment by m1dst** [comment]
PS: This code will not transparently upgrade a hash as I wouldn't have any users using another hash type in my case.

**Comment by f1ana** [comment]
Please see #1664 for a proposed solution

**Comment by f1ana** [comment]
Hi @AndreiMaz - I was hoping to see a more comprehensive solution merged into develop.  It looks like all we are doing is changing the default hash to SHA2-512 instead of SHA1.  Were you able to look at #1664?

**Comment by rolandh** [comment]
Can someone comment on the state of this. Are we simply using SHA512? Or are we doing something more.

**Comment by AndreiMaz** [comment]
@rolandh right, now it's SHA512 only
