### ISSUE TITLE
reCAPTCHA v2 slow to load in some circumstances

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2950]
nopCommerce version: 4.00

Steps to reproduce the problem: Enable reCAPTCHA v2

Sometimes our users are finding our page loads instantly, but the recaptcha v2 takes 15-20 seconds to load. When it hasn't loaded it shows as transparent and hence they aren't even aware it exists.

Is there any way to disable the "LOG IN" button until it has completely loaded? I am happy to have a got at this myself if anyone can give me some pointers on how to detect it.

**Comment by AndreiMaz** [comment]
@rolandh  not sure that it's possible. anyway I think it's related to Google servers rather to nopCommerce

**Comment by rolandh** [comment]
Turns out it was cloudflare in the end. Their rocketscript wasn't working
