### ISSUE TITLE
Pages that require a customer role, redirect them to a page other than the home page

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2952]
If I have enabled ACLs and set a customer role on a page, if the customer is not in that role I'd like to redirect them to a custom error page, not just back to the home page.

Same with if a page requires a user is registered, I'd like to redirect them to the login page, not the home page.

Which source files should I start looking in to achieve this?

**Comment by Xzelsius** [comment]
Check [TopicController.cs - TopicDetails Action](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/TopicController.cs)

**Comment by rolandh** [comment]
All good I found a way to achieve it. I made my own TopicModelFactory that extends the original Nop one and registered it at startup to overwrite the standard one.
