### ISSUE TITLE
Move POST business logic from the controller "layer" to the model "layer"

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2954]
In MVC "The controller receives the input, optionally validates the input and then passes the input to the model."
We have already moved the preparation of models to model factories, but the business logic of HTTP POST requests is still in controller actions.
Think out about moving this logic into the model layer.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
