### ISSUE TITLE
Use a sitemap to indicate alternate language pages

### ISSUE THREAD

**Issue by chlela** [nopSolutions/nopCommerce#2956]
Any plans to update the sitemap generator to include links to other languages for multi-language stores?

Here's a reference to what I'm talking about
https://support.google.com/webmasters/answer/2620865

**Comment by ehalzombi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use a sitemap to indicate alternate language pages](https://trello.com/c/huL4UDJu/1290-use-a-sitemap-to-indicate-alternate-language-pages)
