### ISSUE TITLE
Allow Unicode characters in file names

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2957]
It could be similar to SeoSettings.AllowUnicodeCharsInUrls but a new setting for filenames (images actually)

**Comment by ni-fara** [comment]
It's such a pity that this important SEO improvement is put on hold. I quote an explanation from yoast SEO (the leading wordpress SEO plugin developer), which i hope can help:
"Image SEO starts with the file name. You want Google to know what the image is about without even looking at it, so use your keyword in the image file name."
you can read the full article at https://yoast.com/image-seo/
But as i explained  at https://github.com/nopSolutions/nopCommerce/pull/2936 nopcommerce turns unicode picture file names to "-".

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
