### ISSUE TITLE
We should not apply additional shipping charge for in-store pickup

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2959]
nopCommerce version: 4.00+

Forum source: http://www.nopcommerce.com/boards/t/51517/v40-negate-additional-shipping-charges-when-local-pickup.aspx

Re-open as still reported at https://www.nopcommerce.com/boards/t/55027/v41-negate-additional-shipping-charges-when-local-pickup.aspx

**Comment by charankasu** [comment]
I couldn't repro this issue in 4.10. Was this fixed in version 4.10 ?

**Comment by DmitriyKulagin** [comment]
Сan not reproduce the error.

**Comment by AndreiMaz** [comment]
Still reported at https://www.nopcommerce.com/boards/t/55027/v41-negate-additional-shipping-charges-when-local-pickup.aspx

**Comment by DmitriyKulagin** [comment]
Closed #2959
