### ISSUE TITLE
Drop SQL Server Compact support

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2960]
Anyway no one uses it in production. Plus it's very slow and it can confuse potential users (who just play with our platform)

Add support for it only for unit tests. Or consider even dropping Nop.Data.Tests (is it really so required?)

**Comment by a-patel** [comment]
Suggestion:
Developer can get idea for some other databases (e.g. MySQL, PostgreSQL) from Compact support code.

**Comment by ChrisJollyAU** [comment]
@AndreiMaz isn't this coming by default with the move to Entity Framework Core as part of #2636 and issue #2492

**Comment by AndreiMaz** [comment]
removed after moving to EF Core
