### ISSUE TITLE
Change readme.txt from  Content to wwwroot

### ISSUE THREAD

**Issue by landlogicit** [nopSolutions/nopCommerce#2961]
nopCommerce version: 4.00

Steps to reproduce the problem: Change readme.txt on *nosource.rar
1. If you stored your pictures on the file system, then also backup them (\Content\Images\) and copy back after upgrade
TO:
1. If you stored your pictures on the file system, then also backup them (\wwwroot\Images\) and copy back after upgrade

**Comment by landlogicit** [comment]
On file nopCommerce_4.00_UpgradeScripts.rar  the readme.txt show this below :
Notes:
1. If you stored your pictures on the file system, then also backup them (\Content\Images\) and copy back after upgrade
It's incorrect. Change please with this:
Notes:
1. If you stored your pictures on the file system, then also backup them (\wwwroot\Images\) and copy back after upgrade

**Comment by DmitriyKulagin** [comment]
closed #2961
