### ISSUE TITLE
Compiling for net471 errors

### ISSUE THREAD

**Issue by umokk** [nopSolutions/nopCommerce#2964]
nopCommerce version: current git.

Steps to reproduce the problem: 
Compiling for net471 with latest packages gives:
src\Presentation\Nop.Web.Framework\Infrastructure\NopMvcStartup.cs (38):
Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Builder.MiniProfilerBuilderExtensions.UseMiniProfiler(Microsoft.AspNetCore.Builder.IApplicationBuilder)' and 'Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseMiniProfiler(Microsoft.AspNetCore.Builder.IApplicationBuilder)'

and
src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs (224):
Error	CS1501	No overload for method 'UseMiniProfiler' takes 1 arguments

**Comment by AndreiMaz** [comment]
right now we use and support 4.6.1 only
