### ISSUE TITLE
Bulk Edit Products > Update Published Field not working

### ISSUE THREAD

**Issue by venta360** [nopSolutions/nopCommerce#2966]
nopCommerce version: 4.0

Steps to reproduce the problem: 
-  go to bulk edit products
-  select a category
-  got to page 2 
-  select product and change from publish = false to true (multiple products)
-  save changes
-  I get the attached error

CHROME / MacBook Air
![2018-04-17_2017](https://user-images.githubusercontent.com/16600505/38905148-ac210ca0-427c-11e8-8819-922783008081.png)

**Comment by AndreiMaz** [comment]
@venta360 it works fine at http://admin-demo.nopcommerce.com/Admin/Product/BulkEdit
can you reproduce it there?
