### ISSUE TITLE
Downloadable product - Download URL not working

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2968]
nopCommerce version: 4.00

when we add Downloadable product and add File URL or Sample File URL, then in store want to download, URL not working.
URL is https://site.com/File.zip and https://site.com/SampleFile.zip

when we click the button to download, system redirect to https://site.com

**Comment by AndreiMaz** [comment]
@tigran-avdalyan I cannot reproduce it. It works fine

**Comment by tigran-avdalyan** [comment]
@AndreiMaz  i reproduce. Please see GIF file.
![aaa](https://user-images.githubusercontent.com/17789934/39268366-b7e2cf64-48e0-11e8-8512-843d80898374.gif)
first link is: https://www.network.am/More/KDWin/KDWin2014.zip
second link is: https://www.network.am/More/MSOfficeArmenianLIP/MSOffice2007ArmenianLIP.exe

but when i click the button to download, system redirect to https://www.network.am/More/KDWin/  and
https://www.network.am/More/MSOfficeArmenianLIP/

**Comment by Arashz22** [comment]
You should remove the address **https://www.network.am**
just this is enough **/More/KDWin/KDWin2014.zip**
