### ISSUE TITLE
allow specifying postalcode regex/wildcards and/or ranges in shipping rule configuration

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#2972]
nopCommerce version: 
4.00

from premium support ticket: 14085

Steps to reproduce the problem: 

We need to configure shipping rules for a country which has a lot of remote regions

So was wondering if we could use postal code ranges or regex/wildcards in shipping rules?

http://docs.nopcommerce.com/pages/viewpage.action?pageId=10256905

this would save a ton of shipping rule database records

**Comment by eadameg** [comment]
There is a [plugin](https://www.nopcommerce.com/p/2252/restrict-shipping-by-zipcode-pincode-atluz.aspx) which might do the job.
Check [these](https://www.nopcommerce.com/marketplace.aspx?category=19&searchterm=code) too

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement it out of the box
