### ISSUE TITLE
Google Analytics. Send "cancel/refund" notifications only if an order was paid

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2974]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Place an order. But don't complete payment
2. Go to admin area and cancel  this order
3. Notification will be sent to Google. But it should be send only when an order was paid

P.S. Delete and refund events are not supported. We should support them like OrderCancelledEvent

**Comment by ivanslater** [comment]
@AndreiMaz that is right as it is. Once order is placed, GA plugin sends the order transaction to GA. It is not related if order is paid or not, it is always sent, so GA plugin need to cancel it everytime order is canceled, no matter if it is paid or not.

**Comment by AndreiMaz** [comment]
@ivanslater no, in 4.10 it sends only once it's paid (not placed)

**Comment by ivanslater** [comment]
@AndreiMaz so I believe you should change it to send them all... GA need to analyse conversion, and it means all orders placed, not only paid.

**Comment by ducduy181086** [comment]
Edit file Events.cs at Google.Analytics plugin, we will resolved this item.
