### ISSUE TITLE
Remove unused "Filter" and "Sort" methods from "QueryableExtensions".

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#2975]
And also check if there are any other methods related to server-side filtration used in Kendo grid before (for languages, settings).

**Comment by rreaddev** [comment]
We use the Filter method for filtering Kendo Grids in some of our current plugins.  The only issue we saw was that "public new object Value { get; set; }" needs to be changed to "public new string Value { get; set; }" in the Filter class.

**Comment by DmitriyKulagin** [comment]
Closed #2975
