### ISSUE TITLE
Upgrade to ASP.NET Core 2.1 

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#2976]
This is just enhancement, 
As nopCommerce is waiting for Entity framework core 2.1 to support Lazy loading feature, 

Same time upgrade nopCommerce to Asp.Net Core 2.1 and also target all project to .netcore2.1 instead of 4.6.1.

https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/

**Comment by a-patel** [comment]
Also use Microsoft.AspNetCore.App instead of Microsoft.AspNetCore.All

ref: https://github.com/nopSolutions/nopCommerce/issues/2958

**Comment by a-patel** [comment]
.Net Core 2.1 released now.

https://blogs.msdn.microsoft.com/webdev/2018/05/30/asp-net-core-2-1-0-now-available/
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by samdubey** [comment]
EFCore 2.1 has been available on Nuget
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/

**Comment by ghd258** [comment]
[https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1&from=groupmessage](url)
[https://docs.microsoft.com/en-us/aspnet/core/migration/20_21/_static/main20.png?view=aspnetcore-2.1](url)
[https://docs.microsoft.com/en-us/aspnet/core/migration/20_21/_static/main21.png?view=aspnetcore-2.1](url)

**Comment by ghd258** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1&from=groupmessage

**Comment by RodrigoFCampos** [comment]
I followed all the steps, but now I'm getting a really strange error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'XXXXXXXX' does not exist in the namespace 'XXXXXXX.Models' (are you missing an assembly reference?)	XPTO	c:\User\XPTO\Visual Studio 2017\Projects\XXXXX\XXXXX\obj\Debug\netcoreapp2.1\Razor\Views\ClientCredit\Create.g.cshtml.cs	38	Active

```

Where did this file came from? "Create.g.cshtml.cs" I never create it. I have more error like this in another Views that I never create them either, like:

Delete.g.cshtml.cs
Edit.g.cshtml.cs

Why are my views(at least a copy of them) inside a "obj"(obj\Debug\netcoreapp2.1\Razor\Views\) folder with this strange "g" making part of the extension? 

Are this new views created for some debug procedure?

Would you mind to help me?

**Comment by RodrigoFCampos** [comment]
After I upgrade from 2.0 to 2.1 I got the error: 

`Cannot consume scoped service 'XXXXX.Models.IAppDbContextRepository' from singleton 'Microsoft.AspNetCore.Authentication.IClaimsTransformation'.`

From this line on startup:

`services.AddSingleton<IClaimsTransformation, ClaimsTransformer>();`

I had to change it to:

`services.AddTransient<IClaimsTransformation, ClaimsTransformer>();`

Any ideas why did this happened?
