### ISSUE TITLE
LINQ to SQL & non-compiled queries 

### ISSUE THREAD

**Issue by ivanslater** [nopSolutions/nopCommerce#2979]
nopCommerce version:  all

Have you read this?

For web apps that use LINQ to SQL or Entity Framework as their data backend, compiling per-request LINQ queries often has the highest CPU overhead. Every time a LINQ query is executed, it is compiled into a SQL query by the LINQ to SQL provider. This is very CPU intensive, and gets progressively worse with more complicated LINQ expressions.

**Detect it**
While there is no easy way to monitor for this externally, you can assume you have this problem if your application uses LINQ to SQL or EF, and does not explicitly implement query compilation for per-request queries (ask your developer).

**Fix it**
To fix it, compile your LINQ to SQL queries:

// create compiled query
public static Func> CustomersByCity = CompiledQuery.Compile( (Northwnd db, string city) => from c in db.Customers where c.City == city select c);

// invoke compiled query
var myDb = GetNorthwind();
return Queries.CustomersByCity(myDb, city);

You can also compile your Entity Framework queries. Starting with Entity Framework 4.5, queries can be compiled automatically by the framework.

There has been a lot of discussion of negative performance benefits of compiled queries. The bottom line is if a query is going to be called in the context of a request, compiling it once and reusing it should always be a net win. Especially when you consider the overhead of per-request query compilation on application CPU usage, and not just the execution speed of the query itself.

**Comment by AndreiMaz** [comment]
After some investigation I can say that it won't significantly increase performance. But it'll make source code maintenance more complex and less developer-friendly. There are other more "friendly" way to improve performance (see issues with "performance" tag in this repository)
