### ISSUE TITLE
Duplicate order notification emails

### ISSUE THREAD

**Issue by jvukovich** [nopSolutions/nopCommerce#2981]
1. nopCommerce version: 3.90
2. Expected behavior: only send one order notification to the shop admin and customer.
3. Actual behavior: shop admin and customers are receiving two order notification emails at random.
4. Steps to reproduce the problem: we have two stores, one primary and another which is not in use (to be setup later). Initially, the duplicate notifications would occur on every single order placed. We disabled the second store, and the email notification duplicates reduced drastically (not every order). But, it still does occur (see screenshot). We suspect it is related to the number of stores setup in Nop. That was the only indicator we could find that may be related.
5. Any private modifications you made to your nopCommerce: only template (visual) changes and shipping plugins. No changes to core or notification system.

We are hosting with SmarterASP.net with their Premium plan. We tried turned on the web garden setting to see what would happen, but there was no difference. We set it back to disabled for now.

Screenshot of duplicate emails (subject lines):
![sa_email_duplicates](https://user-images.githubusercontent.com/6004664/39532522-3c5b79ea-4dea-11e8-81eb-cb901f635d65.png)

**Comment by AndreiMaz** [comment]
@jvukovich do you have only one instance of the application?

**Comment by jvukovich** [comment]
@AndreiMaz To my knowledge, yes, but I can't speak to how SmarterASP.net has their hosting configured. I think I'd have to do some digging on that side since it is shared hosting / black box. Thanks!

**Comment by AndreiMaz** [comment]
we cannot reproduce this issue.
