### ISSUE TITLE
News, blog available utc time

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#2982]
nopCommerce version:  4.0

Steps to reproduce the problem: 
News and blogs have available dates property (StartDateUtc, EndDateUtc) , when we edit in admin page, 
we didn't use the utc time, but with a local time , see in(~\Presentation\Nop.Web\Areas\Admin\Controllers\BlogController.cs)
`
                blogPost.StartDateUtc = model.StartDate;
                blogPost.EndDateUtc = model.EndDate;
`

 when search, we convert the time to user time , but the time is actually **user time**  
`
if (x.StartDateUtc.HasValue)
                        m.StartDate = _dateTimeHelper.ConvertToUserTime(x.StartDateUtc.Value, DateTimeKind.Utc);
                    if (x.EndDateUtc.HasValue)
                        m.EndDate = _dateTimeHelper.ConvertToUserTime(x.EndDateUtc.Value, DateTimeKind.Utc);
`

# So, should we save the StartDateUtc to utc time using _dateTimeHelper?

**Comment by AndreiMaz** [comment]
please see work item - https://github.com/nopSolutions/nopCommerce/issues/560 (not implemented yet)
