### ISSUE TITLE
Update product in cart bug

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#2985]
Steps: 
1. Navigate http://demo.nopcommerce.com/build-your-own-computer 
2. Select 320 GB HDD and click add to cart with 1 Qty 
3. On same product page, select 400 GB HDD and click add to cart. So now we should be having 2 product in cart. 
4. Navigate to cart page and we have 2 product with singel qty each 
5. Click the edit link for 400GB product and change the HDD to 320 GB. This will make both the product configuration same.

So what i found instead of Qty 2 in the cart for same product. I am left with only 1 Qty for 320 GB package instead of 2 Qty package.

**Comment by skoshelev** [comment]
Closed #2985
