### ISSUE TITLE
Switch Category DDLs in Admin to Combo Boxes

### ISSUE THREAD

**Issue by SuperArtie** [nopSolutions/nopCommerce#2986]
Currently developing a new TagHelper to use in lieu of NopSelectTagHelper for use in a catalog of 50,000+ categories. The select input is replaced with a Kendo Combo Box that dynamically fills in the options as the user types, searching all Categories by Name, through an AJAX call. Enabling or disabling of this could be configurable in Settings.

Does this sound like anything you would be interested in considering?

**Comment by AndreiMaz** [comment]
@SuperArtie sure, please share source code so we can check it

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/1892
