### ISSUE TITLE
Configure - Nivo Slider not display text localized 

### ISSUE THREAD

**Issue by justindongqiang** [nopSolutions/nopCommerce#2987]
nopCommerce version: 4.10
Admin -> Configuration -> Widgets
Configure Nivo Slider
Plugins.Widgets.NivoSlider.Text displays. Should it display English text if language  is English. 
I can fix it if you agree this is an issue.
![2018-05-08_16-00-51](https://user-images.githubusercontent.com/18490641/39786207-1e1c9a5e-52e5-11e8-8765-b8bd55cf671d.jpg)

Thanks,
Justin Dong

**Comment by AndreiMaz** [comment]
Justin,

It works fine. Locales are installed during the plugin installation

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Widgets.NivoSlider/NivoSliderPlugin.cs#L83
