### ISSUE TITLE
Widget.Review plugin not getting install 

### ISSUE THREAD

**Issue by Gaurav1330** [nopSolutions/nopCommerce#2989]
nopCommerce version: 4.10

Steps to reproduce the problem: 
After adding Widget.Review plugin folder under Nop.Web/Plugin/Widget.Review and running application locally shows following warnings and plugin is not able to install
![error](https://user-images.githubusercontent.com/38416260/39854158-eb69b0c8-5443-11e8-81dd-7c5b7c5ce00d.PNG)

**Comment by AndreiMaz** [comment]
Please contact the developer of this plugin. But actually the error is self-describing. It's for some other version

**Comment by Gaurav1330** [comment]
Plugin is supported for version  4.0

**Comment by AndreiMaz** [comment]
It should support 4.00
