### ISSUE TITLE
Google Analytics. UTM and other details are not passed to Google

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2993]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Place  an order
2. No UTM or other details (e.g. referrer, etc) are passed to GA. They are not available in IPN services because they are not requested by  a customer

The only way to support it is revert back to the previous implementation with JS that was used in bersion 3.90. But it in case case we'll have the same issue again as we had before (a customer must visit "order completed" page which is not always possible). The only way to go now is to support both ways (current one and 3.90 one). And let a store owner to choose.

TODO:
1. Under "Enable E-commerce" setting let's add a new setting - "Send ecommerce info using HTTP request" (enabled by default)
2. When enabled we'll use the current implementation (Nop.Plugin.Widgets.GoogleAnalytics\Events.cs)
3. When disabled, we'll have to use JS code like it was done in 3.90. But one important change. We'll have to do it using new gtag implenentation: https://developers.google.com/analytics/devguides/collection/gtagjs/enhanced-ecommerce?hl=ru (in 3.90 we used another implementation)
4. Add a new {ECOMMERCE} tag to "Tracking code" field (default value). We'll replace it with appropriate code on "Order completed" page when "Send ecommerce info using HTTP request" is disabled. Let's hard-code (no need for new inputs) information that will be generated in JS
5.  "Order completed" page should work fine even when it's opened multiple times - {ECOMMERCE} should not be generated twice (we had such validation in 3.90)
6. When "Send ecommerce info using HTTP request" is enabled, then "HandleEvent(OrderCancelledEvent eventMessage)" should check whether an order is paid (because with this setting enabled we notify Google Analytics only about already paid orders.) But when this setting is disabled, then we have to notify Google Analytics no matter of payment status because with this setting disabled  we notify Google Analytics even about unpaid orders, just placed). And for such cases also add support for "Order deleted" event

We need to support only "gtag('event', 'purchase'," command

Also see https://www.nopcommerce.com/boards/t/51595/nop-40-google-analytics-problem-with-conversions-analytics-widget-problemdelete-ecommerce.aspx

**Comment by awe-source** [comment]
Does this actually work at all unless using the JS method? There is a comment in 2992 that isn’t clear. But if it does only work with js then why keep the option. If it is usable please create some decent doco how to get it to work as we can’t figure it out and it appears to be broken either because the http doesn’t originate from the same client or because the  gtag code isn’t fully compatible with the http method perhaps?!

In out situation we can see the http requests going to google but data doesn’t change to reflect the inputs.

Google doco doesn’t seem to have any info if tracking code is compatible with gtag

**Comment by awe-source** [comment]
Tbh u should probably migrate this to Measurement protocol...  developers.google.com/analytics/dev guides/collection. And goto interconnected devices ...
