### ISSUE TITLE
Find a way  to ignore IDependencyRegistrar and INopStartup configurations of not installed plugins

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#2995]

**Comment by a-patel** [comment]
Then what does below code do during the startup?
NopEngine.ConfigureServices

`
//create and sort instances of startup configurations
            var instances = startupConfigurations
                **.Where(startup => PluginManager.FindPlugin(startup)?.Installed ?? true) //ignore not installed plugins**
                .Select(startup => (INopStartup)Activator.CreateInstance(startup))
                .OrderBy(startup => startup.Order);
`

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/471
