### ISSUE TITLE
shoule we force username/email case sensitive?

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#2996]
nopCommerce version: 4.0

Steps to reproduce the problem: 
When register new user we check the email/username repeat:
`
var query = from c in _customerRepository.Table
                        orderby c.Id
                        where c.Email == email
                        select c;
            var customer = query.FirstOrDefault();
`

if current database **collation is case insensitive**, users cannot register 'USER_1', if 'user_1' username exist, 
I think USER_1, user_1 should be different account.

**Comment by AndreiMaz** [comment]
Thanks! But it's by design.
