### ISSUE TITLE
Remove Service Locator Pattern from NOP extension methods.

### ISSUE THREAD

**Issue by DonaldRecord** [nopSolutions/nopCommerce#2997]
nopCommerce version: 4.00

Certain classes in NOP, such as ProductAttributeFormatter, make use of NOP extension methods that requires the EngineContext to be initialized. Such an example would be the `LocalizationExtensions.GetLocalized` method. On line 96, it calls `EngineContext.Current.Resolve<ILanguageService>();`

I am trying to include NOP dependencies in a unit test environment to assist myself in solving my customer's problems [without having to spin up a website], using my own IoC container, and this anti-pattern makes it very difficult to do so.

Other extension methods in NOP don't have this problem, such as `GenericAttributeExtensions.GetAttribute`, where the `IGenericAttributeService` is passed in.

Can I be approved to resolve this using optional parameters?
I would like to help with some NOP development going forward, is this the correct way to get approval?

**Comment by RomanovM** [comment]
Extension methods have been moved to services
