### ISSUE TITLE
Separate delivery addresses support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#3]
A store owner already can create several shipments per order. The next task is to allow customers to specify several shipping addresses during checkout. For example, product1 (qty 2) goes to address1 and product2 and product3 (qty 1 and qty3) goes to address2

Important notes:
1. But we'll create a new separate order for each specified address (like it's done in magento) because payment methods do not allow specifying several shipping addresses. It should also compute separate shipping totals or allow specifying distinct shipping methods for each delivery address! This option should be configurable (disabled by default).
2. We also should not store payment information in [Order] table/entity because in this case a payment could be "shared" between orders. For example, we could have 1 payment for several orders (as per point 1). First we should create a new [Payment] table/entity and move all information from [Order] table/entity there. Think about better way of managing it in admin area
3. Tax should be calculated separately for each address

**Comment by justinjstark** [comment]
My organization will need this feature but I understand it's a big change. Maybe a good first step is to move the ShippingAddressId from the Order table to the OrderItem table. That would give us a way to set different line-item shipping addresses with a custom plugin.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
