### ISSUE TITLE
Minor issue in language string resources 

### ISSUE THREAD

**Issue by ni-fara** [nopSolutions/nopCommerce#3001]
nopCommerce version: 4.0

In nopCommerce admin area > Configuration > Languages there is a resource name:
admin.catalog.products.productattributes.attributes.values.fields.imagesquarespicture
which has a related value of "Square picture". But the application is not using related "Square picture" value , instead the phrase "Image Squares" is used. Also any other translations of the value in other languages are not taken effect and still the phrase "Image Squares" is shown in non-English languages too.

Steps to reproduce the problem: 
Admin Area > Catalog>Products>"Choose a product">Product attributes  tab>Add a new attribute>
Info tab>Control type field. You can see "Image Squares" instead of "Square picture". Try it for other languages too.

**Comment by DmitriyKulagin** [comment]
Closed #3001 (https://github.com/nopSolutions/nopCommerce/commit/b76f3d2b82feee4fd39b594a575bf518007184d2)
