### ISSUE TITLE
Loading localizedProperty data on startup with dapper

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#3003]
Hi everyone,
I set the localizedproperty data to load at startup, but EntityFramework loads 120k rows long, so it takes a long time for application start. 
120k rows data loaded in 8 seconds with EntityFramework also loaded in 0.4 seconds with dapper. 
As a result, application startup and page loading have become faster than normal.
In addition redis works in windows environment really sucks. 
I don't know why this is the Stack.Exchange library or redis server for windows or configuration. 

I advise you to watch it.

**Comment by Xzelsius** [comment]
EF can load 120k rows in 0.4 seconds too. You just have to load them as "no tracking".

**Comment by fsefacan** [comment]
I tried, but it took 5 seconds on average.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/239
