### ISSUE TITLE
Combine some admin area pages into single ones

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3005]
To simplify management. Here is a list of suggested pages:
1. Reports (all reports will be there) - new menu item
2. Customer > Activity Log. Combine child pages to a single page with tabs
3. Content. News items + News comments
4.  Content. Blog posts  + Blog comments
5. Configuration > Tax. Tax providers + Tax categories 
6. Configuration > Plugins. Local plugins + all plugins and themes
7. System > Category templates, Manufacturer templates, Product templates + Topic templates
8.  Catalog > Bulk Edit. Just remove from menu, do not remove the page. Move to product list page as a "Bulk Edit" button (it will link to this page).

Still discussing final list of pages...

related to https://github.com/nopSolutions/nopCommerce/issues/1647

**Comment by fsefacan** [comment]
And you can get product discounts and categories in a separate tab.
Because the current state is not useful.

**Comment by sinaislam** [comment]
Checkout attributes should not go under catelog.

**Comment by DmitriyKulagin** [comment]
Closed #3005
