### ISSUE TITLE
Rewrite schedule task implementation (per HTTP request)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#301]
First please see http://www.hanselman.com/blog/HowToRunBackgroundTasksInASPNET.aspx 

Currently we run them on background when HttpContext is not available. It has several issues:
1. Caching does not work
2. Schedule tasks could be "buggy" because lifetime scope is not always passed
   Let's periodically invoke some "run schedule tasks" page (e.g. each 10-15 seconds). It'll have some kind of validation so other users cannot invoke it. Also we'll have special "schedule_task" user role. Also ensure that no "guest" record will be created. Then move this FakeHttpContext registration from Nop.Core to Nop.Tests 

This approach also will ensure that a schedule task is run once for the entire site (not for each instance) when running in web farm mode that we're going to support soon. 

If we implement by "requesting some internal URL to run certain task", then it could be work (HttpContext will be available) But such HTTP requests could be timeouted. Does the old 25 request pool rule still work in IIS? Not sure that it's really possible 

Also see how it's implemented in DNN, orchard, umbraco

**Comment by AndreiMaz** [comment]
done
