### ISSUE TITLE
"~/files/importexport"  looking for wrong folder?

### ISSUE THREAD

**Issue by clearbucketLabs** [nopSolutions/nopCommerce#3010]
nopCommerce version: 4

New install - Enable PDF attachment for email, place order.... gets error about can't find path files/importexport/order_xxxxx.pdf

This path is in the "root/wwwroot/" subfolder, but it's looking for it in the application's root path where the theme/view/dll's are located.     I just figure nop should make it in the right place so this isn't an issue.

**Comment by AndreiMaz** [comment]
already fixed https://github.com/nopSolutions/nopCommerce/commit/56677a22d426ab5bd0fe85f1c9b6f45b0b40db07
