### ISSUE TITLE
Permit the choice to use CSS style/link tags in admin

### ISSUE THREAD

**Issue by jimiayler** [nopSolutions/nopCommerce#3011]
nopCommerce version: 4.00

Steps to reproduce the problem: Try to add style or link tags to include CSS in Topics (pages) -- tags are eliminated and an empty <p> tag replaces it when page is saved.

TinyMCE is not configurable for me (and others) in the manner discussed in this otherwise unanswered forum question:

https://www.nopcommerce.com/boards/t/15797/tinymce-configuration.aspx

I want to add both style tags directly to pages in the Content Management section -- the only way, e.g., to add hover states without alot of inline/otherwise unnecessary code -- and the fix you recommend is, as noted, not working. There should be a choice in the admin to add not just CSS but Javascript tags and anything else HTML5 permits. If you're all in for tinyMCE, then you should make it configurable for your customers. Thank you for your attention.

**Comment by skoshelev** [comment]
Closed #3011
