### ISSUE TITLE
 Serious IIS Application Pool recycling bug/design flaw

### ISSUE THREAD

**Issue by kwerty** [nopSolutions/nopCommerce#3013]
This bug was reported not long after the release of NopCommerce 4.0, and since then many people have chimed in with the same problem. It's really strange that you guys haven't prioritized this and released a hotfix. Perhaps you guys need to look at having periodic minor version releases (4.0.1) for bugfixes.

https://www.nopcommerce.com/boards/t/49851/serious-iis-application-pool-recycling-bugdesign-flaw.aspx

**Comment by skoshelev** [comment]
Hello @kwerty , we don't make changes in previous versions, we will fix all issues only in the next version, you can have a look at these commits: [link 1](https://www.nopcommerce.com/boards/t/49851/serious-iis-application-pool-recycling-bugdesign-flaw.aspx?p=2#199340), [link 2](https://www.nopcommerce.com/boards/t/49851/serious-iis-application-pool-recycling-bugdesign-flaw.aspx?p=4#199793) and do the same in your version of nopCommerce.

Closed #3013

**Comment by kwerty** [comment]
This bug results in websites regularly going down until the IIS app pool is manually recycled. This is a serious problem, do you not think this warrants a hotfix or version 4.0.1 ? NopCommerce 4.0 was released over 7 months ago, and numerous people have come to your forums to complain about it. How can NopCommerce be considered production ready software with such a horrendous problem left unfixed for 7 months? This reflects very poorly on your team. Honestly it boggles the mind that you guys think this is acceptable.
