### ISSUE TITLE
Add support for Let's Encrypt certificates

### ISSUE THREAD

**Issue by rolek** [nopSolutions/nopCommerce#3014]
nopCommerce version: 4.0.0

Steps to reproduce the problem: 
Try setting up lets encrypt. It will not renew the certificates.

Proposed fix:
 [AllowAnonymous]
    public class LetsEncryptController : Controller
    {
        private readonly IHostingEnvironment environment;

public LetsEncryptController( IHostingEnvironment environment )
        {
            this.environment = environment;
        }

[HttpGet]
        [Route( ".well-known/acme-challenge/{id}" )]
        public ActionResult LetsEncrypt( string id )
        {
            string file = Path.Combine( environment.WebRootPath, ".well-known", "acme-challenge", id );
            return PhysicalFile( file, "text/plain" );
        }
    }

**Comment by AndreiMaz** [comment]
@rolek Could you please clarify what this code does? Some reference to documentation explaning it?

**Comment by rolek** [comment]
There is no documentation.
When you install nopCommerce and want let's encrypt free SSL certificate, the lets encrypt tool is not able to access through the web, the file it creates on the file system (the challenge file). It will return 404 error.

This controller adds a route that will enable the let's encrypt to access the challenge file through the web
be defining the route:
[Route( ".well-known/acme-challenge/{id}" )].

Now, in NopCommerce, if the route attributes are not supported, this would need to be mapped somewhere, where the routes are defined.
The full path to the file Let's Encrypt creates will be:
<application root>/.well-known/acme-challenge/<file-name>

The file names are cryptic like: aksdf83klsdfnsfdo2390fsadlmf, just FYI.

**Comment by AndreiMaz** [comment]
thanks a lot suggestion. but do not plan to implement it out of the box. @samdubey is right

**Comment by rolek** [comment]
Just FYI, if anyone is looking for this, I created a plugin.
https://github.com/rolek/NopLetsEncrypt
