### ISSUE TITLE
Ability to set home page SEO title and description

### ISSUE THREAD

**Issue by ni-fara** [nopSolutions/nopCommerce#3015]
Currently nopCommerce has the ability to set a page SEO title pattern in General settings->SEO section. Which can bee configured with three parameters of "Default page title", "Page title SEO adjustment" and "Page title separator". For example you can set a page SEO title to something like My Site | My Product.
But site owners usually set a different SEO title for their site's home page, which is longer and more descriptive than "Default page title" parameter. For example they set something like My Site | We sell all the good products you think. And also they set a SEO description for they site home page, which is not currently configurable in nopCommerce settings. So store owner may need to change theme code or write a plugin for it. But it would be so nice to have Home page SEO title and Home page SEO description in General settings->SEO section.

**Comment by DmitriyKulagin** [comment]
Closed #3015

**Comment by bo-bac** [comment]
Hello gentlemen,

not sure that proposed solution matches the requirements.

1 it is not localized
2 it is redundant cuz nop already has a half of implementation ("HomepageText" topic is tired up to Home page and has all necessary SEO properties)

what about this implementation #5331

**Comment by bo-bac** [comment]
@AndreiMaz please review
@DmitriyKulagin please look here again, I have a strong feeling that is 'поворот не туда')

**Comment by DmitriyKulagin** [comment]
@bo-bac To localize the values, we have planned this task - https://github.com/nopSolutions/nopCommerce/issues/43. This will give us the ability to localize the values in the multi-store, so we will go our chosen path, but thanks anyway for your suggestion.

**Comment by bo-bac** [comment]
@DmitriyKulagin  thank you for reply and in advance, text below might be considered like sharp a little but... 'nothing personal just business')  just going to use nop and would like it to be the best) so...

here is one comment from #43

> In my opinion very important. We have many multilanguage pages and when i look at google, it is a mixed language. Title English, Some description german and so on. Nearby the Homepage has SEO fields with no effects (from Topic). Also other SEO basics are missed.

let me point out **from Topic**
that is exactly what was implemented in my commit. 
We have Homepage topic and it has all SEO properties but they are not used on Home page. We use Body and Title but ignore all meta properties. It doesn't strange? Looks like someone forget to do this #5331

Feather more here 930861805ef794d5d95e00e75fd4cebf2fdc4a80 you add extra functionality for things that already exists and mixed them up with 'default' properties on Setting/GeneralCommon/SEO . Home Page props are not Default! They are two different stories.

@AndreiMaz please review. are you really would like to 'go that chosen path...' ?
настаиваю, закоммиченая имплементация - єто поворот не туда.

More over about Setting/GeneralCommon/SEO
- Default page title
- Default meta keywords
- Default meta description
єто все от лукавого!
It is catastrophe from SEO point of view if several pages on the site have the same title... Do you know? Please ask your SEO engineer or Google

and finally about mentioned #43 
agree multi-store it is separate case. will add some comments there

**Comment by AndreiMaz** [comment]
@bo-bac Thanks for your feedback. Here is some comments:
1. There is already an opportunity to set individual meta titles, keywords, and descriptions for most of the pages in any e-commerce store - products, categories, manufacturers, etc.
2. You can also specify default meta titles, keywords, and descriptions at Setting/GeneralCommon/SEO. It's used only on pages where other data is not specified. Duplicated data is better than empty data at all
3. Now you can also specify this data for the home page (previously it wasn't possible). And this specific work item is the home page only
4. There is a very small number of pages left where it's not possible now. For example, e.g. no meta keywords and description for the contacts page (but you can specify the "title" there). But you already can enter this individual data for 99% of pages (separately for each page). We'll find a good way to implement it (topics won't help in 100% of cases as well)

**Comment by bo-bac** [comment]
thank you for you time
