### ISSUE TITLE
Upgrade to ASP.NET Core 2.1 Program.cs and Startup.cs

### ISSUE THREAD

**Issue by ghd258** [nopSolutions/nopCommerce#3016]
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1&from=groupmessage
![main20](https://user-images.githubusercontent.com/4811375/40894108-c5b9565e-67d9-11e8-9ffe-9b6706109f56.jpg)
![main21](https://user-images.githubusercontent.com/4811375/40894110-ca3ed0aa-67d9-11e8-8d42-8f0c1b7f82d1.jpg)

namespace WebApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static # IWebHostBuilder  CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}

namespace WebApp1
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseMvc();
        }
    }
}

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/3155 and https://github.com/nopSolutions/nopCommerce/issues/3156
