### ISSUE TITLE
Discount with coupon code (Applied to Products): cannot add products

### ISSUE THREAD

**Issue by joecodino** [nopSolutions/nopCommerce#3017]
nopCommerce version: 4.10 (updated to commit 16f6dec)

Steps to reproduce the problem: nopCommerce with sample data, go to Promotions > Discounts and choose _Sample discount with coupon code_, then try to apply a product to the promotion. 
Take a look at the video in the attachment: [2018-06-03_15-40-08.zip](https://github.com/nopSolutions/nopCommerce/files/2066010/2018-06-03_15-40-08.zip)

**Comment by AndreiMaz** [comment]
@joecodino Thanks a lot! Fixed
