### ISSUE TITLE
Entity Framework. Performance optimization of many-to-many mapping entities

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3019]
nopCommerce version: 4.10

For example, "CustomerRoles" property of "Customer" entity. Now it loads all mapping records (CustomerCustomerRoleMapping). And then each customer role. Previously EF made only one SQL request

We can fix it by implementing a new method to load all customer roles, and injecting ICustomerService to all places where it's used. But it doesn't look good. Furthermore, mapping tables (CustomerCustomerRoleMapping) wil be loaded anyway because they are used in other places

So we just wait until EF team fixes it. See https://github.com/aspnet/EntityFrameworkCore/issues/10508 and https://github.com/aspnet/EntityFrameworkCore/issues/1368

There are also other properties. For example, discount mapping tables of Category, Product, Manufacturer

**Comment by AndreiMaz** [comment]
We just wait until EF team fixes it. See https://github.com/aspnet/EntityFrameworkCore/issues/10508 and https://github.com/aspnet/EntityFrameworkCore/issues/1368. EF team says "This means that it is not going to happen for the 3.0 release."

We we also postpone it

**Comment by sinaislam** [comment]
What if I take the changes from https://github.com/nopSolutions/nopCommerce/commit/57bb9a7994c10c9d6af856114cb19d6b64c9ebae
here. Will it increase the performance of the 4.2?

**Comment by a-patel** [comment]
@AndreiMaz 
Now What about EF Core?

As now Nop is using linq2db for ORM instead of EF Core.

https://github.com/nopSolutions/nopCommerce/issues/239

**Comment by skoshelev** [comment]
Hi @a-patel. As part of task #239, we abandon navigational properties as well as the use of EF Core. These changes open up great opportunities for developers, but unfortunately, we will not be able to abandon the use of mapping tables

**Comment by skoshelev** [comment]
hi @samhippie It makes no sense for you to implement these changes on nopCommerce 4.20 since the problem they solve has been fixed in the .Net Core 2.2 version

**Comment by skoshelev** [comment]
Closed #3019
