### ISSUE TITLE
Referral program

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#302]
It would be great to have a referral program. This is not the same as an affiliate program in the following ways:
- No need to create a unique affiliate for every single customer (since we would allow any customer to do a referral)
- Referrers would only be given credit (in the form of a gift card) for their referral's first purchase (affiliate program ties every subsequent purchase to the affiliate).
- The purpose is for everyone to spread the word, rather than having dedicated affiliates.
  Forum source: http://www.nopcommerce.com/boards/t/27518/nopcommerce-330-roadmap-and-estimated-release-date-lets-discuss.aspx#111710

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. Affiliates are what we should improve out of the box
