### ISSUE TITLE
Checkbox doesn't work on Safari or Firefox in macOS

### ISSUE THREAD

**Issue by softwarebybrent** [nopSolutions/nopCommerce#3020]
nopCommerce version: 3.9, 4.0

Steps to reproduce the problem: 
Use Mac OS, and safari.  Go to bulk edit products and attempt to modify a boolean field, (checkbox).  UI will not allow it.

How do we fix this?  We cannot update to latest version as company has decided against using .net core, so whatever modifications you make to fix this, it would be appreciated if it was shared here.  

Thanks!

**Comment by AndreiMaz** [comment]
@mariannk needs some investigation

**Comment by DmitriyKulagin** [comment]
@softwarebybrent 
Please specify the version macOS and safari that you are using.

**Comment by DmitriyKulagin** [comment]
Closed, because the issue not reproduce.
