### ISSUE TITLE
Removing product by setting shopping cart to 0 doesn't work

### ISSUE THREAD

**Issue by skarouw** [nopSolutions/nopCommerce#3022]
nopCommerce version: 3.90

Steps to reproduce the problem: 

- Make sure there is a product in your shopping cart
- Go to the shopping cart and try:
1. to set the number of products to 0 by entering a 0 
2. or by adjusting it downward to 0 by using the - button

**Comment by AndreiMaz** [comment]
It works fine out of the box. I presume you use some third-party plugin (we don't have - button)
