### ISSUE TITLE
我认为这里应该修改为： AllKeys.TryUpdate(key, false, true);

### ISSUE THREAD

**Issue by zhk0603** [nopSolutions/nopCommerce#3025]
https://github.com/nopSolutions/nopCommerce/blob/73b8a94c4902acd598dafae62caf5328078ef7e6/src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs#L105

**Comment by skoshelev** [comment]
@zhk0603 Thank you for your help

Closed #3025 (https://github.com/nopSolutions/nopCommerce/commit/d11a69fe12d3e0398a8841d4f9c68521e0480383)
