### ISSUE TITLE
Tests won't compile

### ISSUE THREAD

**Issue by pinkli** [nopSolutions/nopCommerce#3026]
nopCommerce version:  `4.1.0.0 develop branch`
Steps to reproduce the problem: 
1. clone the repo, and open the solution in Visual Studio 2017.
2. Build any one project in Tests folder.
3. It'll fail, specifying Rhino could not be found.

From commits I know the RhinoMocks dependency is removed, but what's the replacement? 
Currently we have to remove the Tests projects in order to build the solution successfully.

**Comment by AndreiMaz** [comment]
Thanks! We know about it. Just haven't finished the migration .net core yet
