### ISSUE TITLE
How to use EF migration in ASP.NET Core 2.1？

### ISSUE THREAD

**Issue by china-live** [nopSolutions/nopCommerce#3030]
nopCommerce version: develop  2018/06/10

Steps to reproduce the problem: 
![1111](https://user-images.githubusercontent.com/12002799/41202913-ca398338-6d02-11e8-80f5-2087c7c83cf7.png)
![2222](https://user-images.githubusercontent.com/12002799/41202916-d92a6ba0-6d02-11e8-8f5c-4bbc14b81357.png)

**Comment by AndreiMaz** [comment]
we don't use migrations out of the box. Could you please post this question on our forums? as github is used only for planned work items
