### ISSUE TITLE
Database back-up path problem

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#3037]
nopCommerce version: 3.90

I use separate servers for sql and web. When I want to back up the database, the SQL server fails to find the db_backup folder in itself.
I think the database back-up path should be configurable.

Cannot open backup device 'C:\inetpub\nopCommerce\Administration\db_backups\database_2018-06-14-09-02-06_9541455146.bak'. Operating system error 3(The system cannot find the path specified.). BACKUP DATABASE is terminating abnormally.

**Comment by skoshelev** [comment]
Database backup functionality works only when your nopCommerce application is deployed on the same server as the database.

Closed #3037

**Comment by fsefacan** [comment]
@skoshelev I think the database back-up path should be configurable so that everyone can keep it where they want.

**Comment by skoshelev** [comment]
@fsefacan 
Unfortunately, setting a directory on another server would cause much more problems, to resolve them you will have to write a lot of code. Much easier would be to organize a backup by the regular tools of the server
