### ISSUE TITLE
Move business logic from extension methods to services

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3038]
This will make it easy to override appropriate methods and then use them by DI container

**Comment by lintho** [comment]
This would be great!

**Comment by a-patel** [comment]
Agreed!

**Comment by lintho** [comment]
Great work RomanovM. 

Only one thing missing:                     


Error 'GdprConsent' does not contain a definition for 'GetLocalized' and no extension method 'GetLocalized' accepting a first argument of type 'GdprConsent' could be found (are you missing a using directive or an assembly reference?)
nopCommerce\src\Presentation\Nop.Web\Areas\Admin\Factories\SettingModelFactory.cs	1307	N/A

**Comment by skoshelev** [comment]
Closed #3038
