### ISSUE TITLE
Refactor "IsProxy" method of \Nop.Data\Extensions\EntityExtensions.cs

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3039]
nopCommerce version: 4.10

in EF 6 we could use ObjectContext.GetObjectType. Now it's not available. And we use a workaround

Let's find a built-in way to get it in EF Core

Our suggested way (https://github.com/nopSolutions/nopCommerce/commit/162bcb72fbcbcb462bf2e901b9c1a6ca37afc343) doesn't work well. Details at https://www.nopcommerce.com/boards/t/52224/nopcommerce-410-bug-fixes-and-improvements.aspx?p=3#206507

**Comment by skoshelev** [comment]
Closed #3039
