### ISSUE TITLE
Support SQL Server 2008

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3041]
nopCommerce version: 4.10

In doesn't work in SQL Server 2008 and 2008R2

In order to support it we have replace
.UseSqlServer(dataSettings.DataConnectionString);
with
.UseSqlServer(dataSettings.DataConnectionString, options => options.UseRowNumberForPaging());

But we should not use "UseRowNumberForPaging" for other databases. That's why let's make it configurable (appsetting.json) whether to support SQL Server 2008. Let's name this setting "UseRowNumberForPaging" but use descriptive comment such as "Enable for backwards compatibility with SQL Server 2008 and SQL Server 2008R2"

**Comment by skoshelev** [comment]
Closed #3041
