### ISSUE TITLE
Show whether IExchangeRateProvider is enabled on Local Plugins page

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3042]
Same like we do for other activated plugins (see the screenshot)
http://dl4.joxi.net/drive/2018/06/18/0017/3890/1122098/98/96490e4d8e.png

in this case we also have to support "Is enabled" checkbox of the "edit plugin" page save this setting)

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
