### ISSUE TITLE
Display a notification before primary store currency (etc) are changed

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3043]
For primary store currency, primary exchange rate currency, measures and dimensions (related work item https://github.com/nopSolutions/nopCommerce/issues/2422)

For example, for primary store currency we can write:
WARNING. It's not recommended to it on line sites because:
1. Product prices, order totals, shipping rates, etc are not automatically converted to the new currency
2. Currency exhange rates are not not automatically updated
3. what else??? .......

**Comment by DmitriyKulagin** [comment]
Closed #3043
