### ISSUE TITLE
CalculateTaxRequest in ITaxProvider.GetTaxRate() should contain StoreId

### ISSUE THREAD

**Issue by kwestground** [nopSolutions/nopCommerce#3046]
When using ITaxProvider.GetTaxRate() in an way where WebStoreContext is not representing the relevant Store, the TaxRate can be calculated wrong.

E.g. When exporting an Order to an external system that was created in 'Store 2' and you want to recalculate the Taxes, the schedule task instance of WebStoreContext is giving you 'Store 1'.
This can results in wrong tax calculation.

I suggest adding StoreId into the CalculateTaxRequest and at least move storeContext.CurrentStore.Id into the TaxService.GetProductPrice() method.

`var storeId = _storeContext.CurrentStore.Id;`

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Tax.FixedOrByCountryStateZip/FixedOrByCountryStateZipTaxProvider.cs#L94

**Comment by DmitriyKulagin** [comment]
Closed # 3046
