### ISSUE TITLE
No need to call AddAutoMapper()

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#3048]
nopCommerce version: 4.00

Steps to reproduce the problem: 
In NopEngine.cs,  **ConfigureServices** method, we use Automapper:
```C#
//register mapper configurations
AddAutoMapper(services, typeFinder);
```

in AddAutoMapper:
```C#
            //create AutoMapper configuration
            var config = new MapperConfiguration(cfg => {
                foreach (var instance in instances)
                {
                    cfg.AddProfile(instance.GetType());
                }
            });

            //register AutoMapper
            services.AddAutoMapper();

            //register
            AutoMapperConfiguration.Init(config);
```
After investigate AddAutoMapper() method, I think we don't need to call this, because we can use IMapperProfile interface implement this, we also can remove 

[AddAutoMapper extension method](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/blob/master/src/AutoMapper.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs)

This method just scan current domain's assemblies and find classes inherited from **Profile** and register the mapping config and mapper.
```c#
var profiles = allTypes
                .Where(t => typeof(Profile).GetTypeInfo().IsAssignableFrom(t) && !t.IsAbstract)
                .ToArray();

// omit some code



// create mapper configuration
            IConfigurationProvider config;
            if (UseStaticRegistration)
            {
                Mapper.Initialize(ConfigAction);
                config = Mapper.Configuration;
            }
            else
            {
                config = new MapperConfiguration(ConfigAction);
            }

// .. omit searching other types

// register mapper configuration, register IMapper
services.AddSingleton(config);
            
return services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService));

```

So, in AddAutoMapper() method, it already load mapping configuration file and Mapper, then registered.

In NopEngine.cs AddAutoMapper method, we create mapper config and mapper, it's duplicated.

Becase we're using IMapperProfile to search mapping config file, we don't need to scan assembly search Profile.

so it's safe to remove the services.AddAutoMapper(); line
```C#
            //create AutoMapper configuration
            var config = new MapperConfiguration(cfg => {
                foreach (var instance in instances)
                {
                    cfg.AddProfile(instance.GetType());
                }
            });

             // just remove this line
           // services.AddAutoMapper();

            //register
            AutoMapperConfiguration.Init(config);
```

**Comment by skoshelev** [comment]
@JohnsonYuan Thank you for your help, I investigated your proposition and implement it

Closed #3048

**Comment by JohnsonYuan** [comment]
@skoshelev 

AdminMapperConfiguration.cs 
```c#
AdminMapperConfiguration : Profile, IOrderedMapperProfile
```

since we use IOrderedMapperProfile to find mapping config, I think it's safe to remove base class Profile, it's used by AutoMapper to find mapping config files.

change to
```c#
AdminMapperConfiguration :  IOrderedMapperProfile
```

**Comment by JohnsonYuan** [comment]
I think we can also remove package AutoMapper.Extensions.Microsoft.DependencyInjection
