### ISSUE TITLE
Cleaning database of guest users should also delete associated generic attributess

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3051]
After cleaning database of guest users, GenericAttribute table is not cleaned. There are some records (like last visited page) associated to guests already deleted. 

Source: https://www.nopcommerce.com/boards/t/52429/genericattribute-do-not-remove-unassociated-records.aspx

**Comment by skoshelev** [comment]
Everything works well

Closed #3051
