### ISSUE TITLE
Tiered Discount on Subtotal

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#3059]
nopCommerce version: 3.9

Hello, I have a use case that looks like this:

$0-$99 spent would receive a 10% discount
$100-$199 spent would receive a 15% discount
$200 on up spent would receive a 20% discount

I have not found a way out of the box to do this, even with the customer had spent x.xx amount requirement. I have not found a third party plugin either. The closest one is this: https://www.nopcommerce.com/p/1593/aulveri-tiered-subtotal-discount-plugin-free.aspx but it appears that it's no longer supported. Does anyone have suggestions, or am I better off just implementing my own IDiscountRequirementRule plugin?

Thanks

**Comment by AndreiMaz** [comment]
it's not supported out of the box. but "spent" dixcount requirement plugins could be found on our marketplace
