### ISSUE TITLE
NopCommerce always showing standard value in admin

### ISSUE THREAD

**Issue by AxelAndersen** [nopSolutions/nopCommerce#3060]
nopCommerce version: 4.0

NopCommerce always showing standard value in admin

As an example I can take the Category, which can i be translated into any number of languages.
In the Admin area the menu item "Category", all labels and all headers will be translated, but the values of the categories are shown in Standard value. Why?

If I have an employee that dont know english, its just perfect that the Admin area can be visible in hes own language, so why not everything?

I think this is a bug, even if it is meant to be like that.

![image](https://user-images.githubusercontent.com/14222668/41959500-6c536b60-79ed-11e8-8b22-a9fef3922735.png)

**Comment by AndreiMaz** [comment]
Thanks a lot! It's by design now. But anyway we already have this work item - https://github.com/nopSolutions/nopCommerce/issues/2158
