### ISSUE TITLE
Allow to specify "description" for GDPR consent

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3062]
nopCommerce version: 4.10

For example, allow a store owner to specify a link (a topic, etc) with an explanation of that rule, so customer can click it, but can also read some more explaination to it. Like we have "policy" link for "Accept policy" setting

**Comment by cnEUL** [comment]
For the compliance of the GDPR it is important, among other things, that the user understands quickly what it is all about. A field description and a checkbox are usually not sufficient here. I put here a link or alternatively a kind of style which represents the additional information expanded in the page. 
This gives the customer an overview and if he already knows what it is all about, he can quickly decide whether or not to give his consent.
I would like to see this option in the final version 4.10.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
