### ISSUE TITLE
AdminTabStripCreated.BlocksToRender.Add should be able to render ViewComponent as a tab

### ISSUE THREAD

**Issue by wingback** [nopSolutions/nopCommerce#3063]
nopCommerce version: 

Steps to reproduce the problem: 
When you want to add new tab on edit pages for example product edit, vendor edit, etc. it would be nice to be able to pass ViewComponent as arg.

**Comment by LubovKhokhlova** [comment]
The task is irrelevant due to the redesign and abandonment of the tabs

**Comment by layinka** [comment]
Hi,
Please whats the replacemnt for this (AdminTabStripCreated), now that Tabs have been abandoned?
