### ISSUE TITLE
EfRepository Update performance problems.

### ISSUE THREAD

**Issue by JadynWong** [nopSolutions/nopCommerce#3064]
https://github.com/nopSolutions/nopCommerce/blob/4dbec629712e8133af49fe70bd17068144a23ea9/src/Libraries/Nop.Data/EfRepository.cs#L122

Every update operation will have all fields, which will have performance problems.
If the containing associated entity is all updated

This is my solution.
#3057 

Update()'s describtion in the note

https://github.com/aspnet/EntityFrameworkCore/blob/e300fdfe4ac314cc9e65520a15b9b7609a6c6a21/src/EFCore/DbSet%60.cs#L202

If it is a tracking entity, the update operation is no different from the Ef6

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement it
