### ISSUE TITLE
GDPR upgrade from T-Motions tables

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3068]
NopCommerce comes with a very good GDPR support in version 4.10. Since the new regulation is already since May 25, 2018 in force, some administrators have certainly fallen back on the plugin of the company T-Motion. 
It would certainly make sense to think about an SQL converter that converts the consents and the corresponding texts into the format of the GDPR standard version that is now included in NopCommerce.
Is there already a consideration in this respect?

**Comment by AndreiMaz** [comment]
We don't provide support for third-party plugin. We even don't source code of it. It's better to contact T-Motions
