### ISSUE TITLE
Allow customer to edit existing addresses during checkout

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#307]
Source with example: http://www.nopcommerce.com/boards/t/12461/checkout-progress-improvement-suggestions.aspx 

We can add "edit" link (for registered users) which will redirect to the address edit page. Let's make it configurable (whether to display it). And think what we should better do for guest accounts (how to implement that)

Also see https://github.com/nopSolutions/nopCommerce/issues/4849

**Comment by mingchar** [comment]
What's the differences between registered users and guest accounts on this function? 
I'm not so familiar with the business and needing more info to understand it.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
