### ISSUE TITLE
GDPR and Privacy policy headline in Registration process and Edit account page

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3070]
The new integration of GDPR approvals has been good, but a resource string for a heading like "Options" or the other areas would be good. The same applies to the distance between the checkbox and the consent text.

![registration](https://user-images.githubusercontent.com/37210350/42076644-46bef164-7b76-11e8-926f-3f2e7b033e6a.jpg)

**Comment by AndreiMaz** [comment]
please see the latest commit regarding the margin

**Comment by cnEUL** [comment]
Hello, Andrei,

yes, this is already the latest version. There wasn't a gray box before. But without a headline the box hangs a little in the air.

**Comment by cnEUL** [comment]
Hi Justin, Margin looks very good on your screen. I was using chrome and now i am downloading the newes nop snapsot to look on it in english. give me 30 minutes.
Another idea with the headline, i dont know if its good for you, but to see all GDPR questions inside the grey 'Options' box is also ok. Because Newsletter is just something with the GDPR. By the way, why is the Newsletter checkbox right and the GDPR Left?

**Comment by cnEUL** [comment]
I compiled with the nopCommerce version from today and under Chrome, Edge and IE the distance is ok now. Don’t know what it was.
The only thing is Header and the question if it’s not better to bring them all in the upper 'Options' box.

**Comment by justindongqiang** [comment]
@cnEUL Thanks for checking it again and I am glad the GDPR consents checkbox margin and distance are ok now. In term of if it is better to bring them together into one upper "Options" box, I wouldn't do so because GDPR could have multiple consents displaying in the box. 

@AndreiMaz I am going to work with this issue which is to add GDPR Headline into registration process. 

Thanks,
Justin

**Comment by cnEUL** [comment]
@justindongqiang  you are right

chris

**Comment by justindongqiang** [comment]
@AndreiMaz can you assign it to me? I am already  ready to check in this

**Comment by mariannk** [comment]
@cnEUL @justindongqiang hey there! Could you please clarify: the issue still exists?
Seems like everything is ok. Yes, it doesn't have any header. Is it the only issue for now?

**Comment by cnEUL** [comment]
yes, the headline is not resolved, the other point, with distance is ok now.
But all GDPR checkboxes dont have a headline. Like "GDPR - CONSENTS" or something else.

**Comment by justindongqiang** [comment]
@mariannk Yes the only issue here is no headline for GDBR Concerts. I am on it and I am going to check in the changes very soon.

**Comment by justindongqiang** [comment]
@mariannk I checked into my branch, and will create a pull request once my previous request is completed.
