### ISSUE TITLE
Bulk install / uninstall of plugins

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3079]
nopCommerce version: => 4.10 

During the initial installation all plugins are installed first. Many of them do not make sense in Germany, for example. So you have to uninstall a lot of them. But this also happens in ongoing operations.

Since the server restarts the website after each change, each process takes relatively long. So it would be nice to have either a kind of "bulk" mode with a checkbox for each plugin. So you can check the desired ones and then either uninstall or install them.

Certainly not an absolutely important thing, but it makes this area a bit more user-friendly again.

**Comment by AndreiMaz** [comment]
after some investigation we decide not to implement it
