### ISSUE TITLE
Allow store owner to configure URLs in admin area, rather than having to edit the RouteProvider.

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#308]
Allow store owner to configure URLs in admin area, rather than having to edit the RouteProvider. This allows none programmers to setup a nop website and have the freedom to use whatever URLs they want - good for SEO and good for other languages. 

There's already contributed fork here - http://nopcommerce.codeplex.com/SourceControl/network/Forks/makit/ConfigurableURLs

**Comment by kruijs** [comment]
Same here: Use-Case is Swiss target market allowing to change the shop language to de-CH, it-CH and fr-FR.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
