### ISSUE TITLE
[suggestion]build ClearPluginAssemblies.dll

### ISSUE THREAD

**Issue by JohnsonJohnsonYuan** [nopSolutions/nopCommerce#3080]
nopCommerce version: 4.10

Steps to reproduce the problem: 
I think we can remove  /src/Build/ClearPluginAssemblies.dll, and build it auto.

**Comment by skoshelev** [comment]
Hi @JohnsonJohnsonYuan 
It seems to me that this is an excessive solution, since at the moment the structure is such that you will need to build this library many times in the process of building the main project

Closed #3080
