### ISSUE TITLE
Bulk changes with customizable field list in grid.

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3082]
nopCommerce version: 4.10

In the Admincenter you can switch between Basic and extended by selecting the desired fields for the basic variant.
A similar function, i.e. the selection of fields that should be changeable (in bulk edit mode) would be helpful. 
In addition, the Warehouse Management field cannot be changed at all and is only a waste of space. 
I think everyone always has different fields that they want to change in bulk, so it should be customizable, maybe even through profiles not just a single set of fields.

![bulk](https://user-images.githubusercontent.com/37210350/42292808-7307ecf4-7fd5-11e8-965a-52b7cbd28b5b.jpg)

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement it out of the box. only these fields
