### ISSUE TITLE
Update Facebook plugin description

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3088]
I have translated the new facebook resources and tried also out to control that the field names are choosen right. But Facebook has changed completely the forms for developer.

 Here is a screenshot (german) but you see … its much different than in the description.

![unnamed](https://user-images.githubusercontent.com/5019111/42342747-aae715bc-809f-11e8-8d8a-8c428d3c27b7.jpg)

Perhaps someone controls the English page and made an update to your plugin.

**Comment by DmitriyKulagin** [comment]
Closed #3088
