### ISSUE TITLE
Cache Busting for JS and CSS files

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3092]
We had this pull request https://github.com/nopSolutions/nopCommerce/pull/3034 

but it's better to re-implement it:
1. Using built-n feature https://github.com/aspnet/Mvc/blob/release/2.1/src/Microsoft.AspNetCore.Mvc.TagHelpers/ScriptTagHelper.cs#L40
2. Do not use System.IO.Path.
3. Make it ocnfigurable in admin area so a store owner can disable it (there could be permission issues on some hosting)

**Comment by DmitriyKulagin** [comment]
After some discussion, it was decided not to implement it.

**Comment by RomanovM** [comment]
Moved to #4791
