### ISSUE TITLE
linux build error on project ClearPluginAssemblies

### ISSUE THREAD

**Issue by JohnsonJohnsonYuan** [nopSolutions/nopCommerce#3093]
nopCommerce version: 4.01

Steps to reproduce the problem: 
File: Build/ClearPluginAssemblies.proj
```xml
<Exec Command='dotnet "$(MSBuildProjectDirectory)\ClearPluginAssemblies.dll"
```

In windows the path seperator is \, but linux is / , when build the error message is like this:

> The command " dotnet "/Build\ClearPluginAssemblies.dll" exited with code 1.

because \ClearPluginAssemblies.dll is wrong on linux.

**Comment by JohnsonJohnsonYuan** [comment]
maybe this?
```xml
<Exec Command='cd $(MSBuildProjectDirectory); dotnet ClearPluginAssemblies.dll" />
```

**Comment by AndreiMaz** [comment]
thanks. but we don't support linux yet https://github.com/nopSolutions/nopCommerce/issues/3095

**Comment by entwicklerRepo** [comment]
Sorry I don't want to be rude, but to run dotnet core and does not support linux/macOS it's a bit weird.

**Comment by AndreiMaz** [comment]
I don't think it's weird. We just do it step by step. 
.net core is not introduced just for Linux support
.net core can be also run on windows and has its advandages on Windows as well

**Comment by entwicklerRepo** [comment]
All good just thought linux/macOS support will come with 4.1
