### ISSUE TITLE
Run nopCommerce on Linux

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3095]
Also see https://github.com/nopSolutions/nopCommerce/issues/415

**Comment by VR-Architect** [comment]
Hi, I see Issue# 3144 was closed and referenced to this issue. Just wondering, is this issue implying that support for Linux is not currently available and on the roadmap? I need to make production decisions for the servers to support the business timelines today. If Linux is not currently supported, does anyone know when they expect to support it? Thanks to anyone who may know.

**Comment by VR-Architect** [comment]
Received a [comment ](https://www.nopcommerce.com/boards/t/54054/nopcommerce-410-beta-released-please-share-your-impressions.aspx?p=6)stating Linux support is coming in v4.2

**Comment by skoshelev** [comment]
Closed #3095
