### ISSUE TITLE
linux path separator error

### ISSUE THREAD

**Issue by JohnsonJohnsonYuan** [nopSolutions/nopCommerce#3097]
nopCommerce version: 

Steps to reproduce the problem: 
In linux. the Install page will throw error like this:
DirectoryNotFoundException: Could not find a part of the path '[paths]/Presentation/Nop.Web/App_Data\Localization\Installation\'.

because when load language xml file, use the wrong separator:
```c#
_fileProvider.EnumerateFiles(_fileProvider.MapPath("~/App_Data/Localization/Installation/"), "*.xml")
```
```c#
public virtual string MapPath(string path)
        {
            path = path.Replace("~/", string.Empty).TrimStart('/').Replace('/', '\\');
            return Path.Combine(BaseDirectory ?? string.Empty, path);
        }
```

I think we can remove constant '\\', change to platform specific variable `Path.DirectorySeparatorChar`

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/3095
