### ISSUE TITLE
Allow affiliates to sign-up in public store (configurable) + interface for the affiliate for monitoring his account, customers etc

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#31]
Allow affiliates to sign-up in public store (configurable) similar to vednor registration (disabled by default). Have a look at open cart affiliate support (http://demo.opencart.com/index.php?route=affiliate/login). 

Logged-in affiliates can see order reports (order id, order date, order total)

Also see another suggestion - http://www.nopcommerce.com/boards/t/28309/feature-request-every-customer-should-have-an-affiliate-url.aspx 

also see http://www.nopcommerce.com/boards/t/43311/suggestion-affiliate-program-improvment.aspx#171774

also see the comment below

**Comment by viewtance** [comment]
When this feature will be implemented? look forward to this feature to release

**Comment by AndreiMaz** [comment]
The creation of a Reseller (or "Partner") Portal where resellers can register customers and order on a customers behalf.

The portal should allow the Partner to see only customers associated with them and orders only they have processed. A Partner Resources section where they can get logos, product descriptions etc would be helpful. Resellers are most useful for overseas and often foreign language sales.

Resellers purchase products at a discount and have the ability to turn off customer notifications about registration and also the option to hide order information (i.e,. the price paid) from the customer. Resellers whom separately bill the customer can then order products under their own pricing arrangements and can arrange for direct delivery either to the reseller or the customer.

In the case of downloadable products, the customer can login and download the product, but the reseller can't access the customer download, unless permitted by the store owner.

Ideally Partners would be organised in separate classes with different administration rights depending on classes. eg. A "Distributor" might have the ability to refund orders, a basic reseller may not.

This can actually be done using a mashup of the Administration Interface combined the "Affiliate" functionality ("Partner" is a much better term). We have done this by hacking the code a bit which means it is not appropriate to share - it needs to be done properly.

The result was support for both "Affiliate" and "Reseller" management in one place. Both can login and seeeither how their Affiliate program membership is going or in the case of resellers can administer most features of the affiliated customers (affiliates only see customer name) .

**Comment by sukeshak** [comment]
Is this pushed to 4.0 now?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
