### ISSUE TITLE
Actual developer branch did not compile

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3103]
nopCommerce version: 4.10

This is one of other similar error on compiling the developer branch from today. two days ago, it worked normal.

Anay Idea?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'GdprConsent' does not contain a definition for 'GetLocalized' and no extension method 'GetLocalized' accepting a first argument of type 'GdprConsent' could be found (are you missing a using directive or an assembly reference?)	Nop.Web	C:\Git\Csharp\Nop410\Source\Presentation\Nop.Web\Areas\Admin\Factories\SettingModelFactory.cs	1307	Active

**Comment by lintho** [comment]
All extension methods where removed. Maybe something wasnt updated

**Comment by lintho** [comment]
Seems to be fixed now @cnEUL

**Comment by cnEUL** [comment]
Yes, now i can compile again. Perfect!
