### ISSUE TITLE
SQL Compact is dropped, so Install view should be actualized

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3105]
nopCommerce version:  4.10

The SQL Compact is dropped, so drop also the radio box which has only one option (itself).
The headline then "Database Information" could stand for the rest oft the database parameters.
![install](https://user-images.githubusercontent.com/37210350/42461561-0cc6f8e8-83a1-11e8-9129-90fa84f10496.png)

**Comment by justindongqiang** [comment]
Good catch. The radio box should be dropped.

**Comment by AndreiMaz** [comment]
we've decided to leave it this way because of:
1. It's clear what type of database we support
2. we plan to add new database support in the next version

**Comment by cnEUL** [comment]
i understand.
