### ISSUE TITLE
EnumType for Combobox "Shopping cart & wishlist" not localizable

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3106]
nopCommerce version: 4.10

The new view "Sales\Shopping carts & wishlists" has a combobox. The EnumType of the Content is not in the resource table and therefore could not be translated.

![cart_wishlist](https://user-images.githubusercontent.com/37210350/42461789-a5a57d46-83a1-11e8-8b62-57d088674ff3.png)

We should make \Libraries\Nop.Core\Domain\Orders\ShoppingCartType.cs localizable like other enums

**Comment by RuS984** [comment]
Closed #3106
