### ISSUE TITLE
Date is only in us format

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3107]
nopCommerce version: all

Steps to reproduce the problem: 
All calender or date fields are using us date format insteed of the operating systems constants.

![date](https://user-images.githubusercontent.com/37210350/42469993-7e368df0-83b9-11e8-94d5-0c7b21875766.png)

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/30
