### ISSUE TITLE
Weigths (Configuration/Shipment/Measures)

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3109]
nopCommerce version: 4.10

Because of PAngV and the Base price takes the strings from that section, i prefer to change the headline in the section to "weidghs and other units".
So it is more clear that this part is the mixed section.

![weight](https://user-images.githubusercontent.com/37210350/42470870-1af5398c-83bc-11e8-9396-5e9b6cd0fad1.png)

**Comment by cnEUL** [comment]
![weight2](https://user-images.githubusercontent.com/37210350/42471008-8e5a01b4-83bc-11e8-81f5-ad55b332c788.png)
for clearification-

**Comment by AndreiMaz** [comment]
Right now we support only weights. So we'll leave it this way in 4.10. Anyway, you can edit a locale if you need it right now

**Comment by cnEUL** [comment]
I understand that. But at the moment the name of the unit stored there is used to calculate the base price in the product (PAngV). Conversely, this would mean that products with a base price would only be on a kilo basis. Just to mention it again :-)
