### ISSUE TITLE
Avatar in Customer - Clickbox did nothing - How did it Work?

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3110]
nopCommerce version: 4.10

I had activated in Configuration settings the customer avatar. One time also with "Defaults" another without.
In the list view of customers (without defaults), the checkbox is unclickable (and avatar) is the label.
How can i upload or select an Avatar?

![avatar](https://user-images.githubusercontent.com/37210350/42472250-f7d8f3f8-83c0-11e8-8e05-203f3fe1d3ed.png)

**Comment by skoshelev** [comment]
Hi @cnEUL. This is not checkbox, just empty image. Avatar can be uploaded by user on the "My Account" page.

Closed #3110

**Comment by skoshelev** [comment]
Closed #3110
