### ISSUE TITLE
Support schema other than DBO

### ISSUE THREAD

**Issue by KrzysztofPajak** [nopSolutions/nopCommerce#3114]
nopCommerce version:   4.10

Steps to reproduce the problem: 
When I install nopcommerce beta 4.10 on on my own sql user (not sa), created table contains schema of this user not dbo.
During instalation I get error: Cannot find the object "dbo.QueuedEmail" because it does not exist or you do not have permissions.
But this table exist, but with other schema
Regards
Krzysztof

**Comment by AndreiMaz** [comment]
@KrzysztofPajak thanks. but we haven't supported it before as well

**Comment by cnEUL** [comment]
@KrzysztofPajak 
For me i had a similar problem, i dont want the sa account on a webshop. So i created it with sa user, and then i chand the permissen by a powershell script. Perhaps it hels, so you not need to craete it by normal user. 
Also the Application pool has this sicurity like this:
    function Set-PermissionSspi()
    {
        Write-StackInfo

        $Hostname = $Script:ini["CUSTOMER"]["Hostname"]        

        $Sql =  "USE [Master]", `
                "CREATE LOGIN [IIS APPPOOL\$Hostname] FROM WINDOWS;", `
                "USE [$Hostname]", `
                "IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'$Hostname')", `
                "BEGIN", `
                "  CREATE USER [$Hostname] FOR LOGIN [IIS APPPOOL\$Hostname];", `
                "  EXEC sp_addrolemember N'db_owner', N'$Hostname'", `
                "END;"
        Send-SqlCommand $Sql
    }

**Comment by KrzysztofPajak** [comment]
In this case installation will not be possible on hosting server :(

**Comment by smyypkn** [comment]
I have same problem. Is there any solution for nop 4.1 installation on hosting server

**Comment by grzech1983** [comment]
Yep. This is IMHO huge issue. I'm wondering why you are using logged in user schema instead of dbo for creating tables using installer?

When it comes to dbo.QueuedEmail table is being created with USERNAMESCHENA.QueuedEmail but installer is looking for dbo.QueuedEmail so we have some inconsistency here when it comes to DB objects handling.

Another problem could be moving DB from one hosting provider to another. Previous username schema could cause issues after migration to new provider.

**Comment by AndreiMaz** [comment]
https://www.nopcommerce.com/boards/t/55402/installing-nopcommerce-on-host4aspnet.aspx

**Comment by skoshelev** [comment]
Closed #3114
