### ISSUE TITLE
Tipo Customer account

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3115]
nopCommerce version:  4.10

![tipo cstomer1](https://user-images.githubusercontent.com/37210350/42493644-1c58699a-841e-11e8-932b-61d5f2be4b87.png)

here in resource with target at the left side:
![tipocustomers1](https://user-images.githubusercontent.com/37210350/42493645-1f845926-841e-11e8-8552-5dc4e8c0487f.png)

**Comment by RuS984** [comment]
Closed #3115
