### ISSUE TITLE
Style problem on Warning if SKU exists

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3116]
nopCommerce version: 4.10 beta

On typing a duplicated SKU in product admincenter
1. A hint windows with just entred items hides the warning below after pressing Enter.
2. After pressing Enter on Chrome i cannot see the warning message.

![warning](https://user-images.githubusercontent.com/37210350/42496369-11a6782c-8426-11e8-9574-76510effdba6.png)

**Comment by AndreiMaz** [comment]
@mariannk please check

**Comment by DmitriyKulagin** [comment]
Closed #3116
