### ISSUE TITLE
Warning "Please provide a name" dont goes away after entering a name

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3117]
If you type in a product and dont type in the product name, a warnng is written under the field and on the top of the page.
If you resolve it by typing a name, the top warning is not going away.
![warningproductname](https://user-images.githubusercontent.com/37210350/42497157-aa0d2b40-8428-11e8-9f3b-a3c1568e2d28.png)

The same is about other edit pages

**Comment by AndreiMaz** [comment]
@DmitriyKulagin let's check whether it's an issue or by design by the validation script

**Comment by DmitriyKulagin** [comment]
@AndreiMaz 
In this case, "asp-validation-summary" validation is used. The error message will disappear after updating the model in case it has passed validation.

**Comment by DmitriyKulagin** [comment]
@cnEUL 
This is how built-in validation works in Net. core, we can not hide this message as it is done directly under the field itself, because in some cases we also use validation on the server, so we can not do without upgrading the model.
