### ISSUE TITLE
Limit customers per store

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#312]
could you advise if it is possible to restrict a customer to a specific Store? 

E.g. We have the scenario where we have common products across all stores which the multi store facility allows, but it we had the following: 

store1.ecommerce.com 
store2.ecommerce.com 

We would only want to allow 

customer1 to login to store1.ecommerce.com 

and 

customer2 to login to store2.ecommerce.com 

is this possible? 

Source: http://www.nopcommerce.com/boards/t/27981/multi-store-customer-restriction.aspx

**Comment by AndreiMaz** [comment]
duplicate

**Comment by johannwalder** [comment]
@AndreiMaz could you please point me to the duplicate as I couldn't find it.
Thanks!

Br,
Johann

**Comment by AndreiMaz** [comment]
@johannwalder https://github.com/nopSolutions/nopCommerce/issues/697

**Comment by johannwalder** [comment]
@AndreiMaz thanks again!
