### ISSUE TITLE
Error on new 4.1 solution with upgraded 3.8->3.9->4.0->4.1 database

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#3122]
nopCommerce version: 4.1 "beta"

Steps to reproduce the problem: 
Old db upgraded from 3.8 to 4.1 with every step.
New Dev solution. 

The solution works fine when im using another new installed 4.1 db, but the upgraded one does not work.

Error: 
Nop.Web> info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
Nop.Web>       Entity Framework Core 2.1.1-rtm-30846 initialized 'NopObjectContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using lazy-loading proxies 
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web>       Executed DbCommand (58ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web>       SELECT [t].[Id], [t].[Enabled], [t].[LastEndUtc], [t].[LastStartUtc], [t].[LastSuccessUtc], [t].[Name], [t].[Seconds], [t].[StopOnError], [t].[Type]
Nop.Web>       FROM [ScheduleTask] AS [t]
Nop.Web>       WHERE [t].[Enabled] = 1
Nop.Web>       ORDER BY [t].[Seconds] DESC
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web>       Executed DbCommand (39ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web>       SELECT [s].[Id], [s].[CompanyAddress], [s].[CompanyName], [s].[CompanyPhoneNumber], [s].[CompanyVat], [s].[DefaultLanguageId], [s].[DisplayOrder], [s].[Hosts], [s].[Name], [s].[SslEnabled], [s].[Url]
Nop.Web>       FROM [Store] AS [s]
Nop.Web>       ORDER BY [s].[DisplayOrder], [s].[Id]
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web>       Executed DbCommand (50ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web>       SELECT [s].[Id], [s].[Name], [s].[StoreId], [s].[Value]
Nop.Web>       FROM [Setting] AS [s]
Nop.Web>       ORDER BY [s].[Name], [s].[StoreId]
Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000]
Nop.Web>       An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
Nop.Web> 
Nop.Web> 
Nop.Web>       System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web> 
Nop.Web> Unhandled Exception: Unhandled Exception: Unhandled Exception: System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>          at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>          at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Nop.Data.EfRepository`1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>    at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000]
Nop.Web>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web>       An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web>       System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>          at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at System.Threading.TimerQueueTimer.CallCallback()
Nop.Web>          at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at System.Threading.TimerQueueTimer.Fire()
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at System.Threading.TimerQueue.FireNextTimers()
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000]
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>       An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
Nop.Web>    at Nop.Data.EfRepository`1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81
Nop.Web>       System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>          at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>          at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>    at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web>    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at System.Threading.TimerQueueTimer.CallCallback()
Nop.Web>    at System.Threading.TimerQueueTimer.Fire()
Nop.Web>    at System.Threading.TimerQueue.FireNextTimers()
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nop.Web>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web>    at Nop.Data.EfRepository`1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81
Nop.Web>    at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220
Nop.Web>    at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45
Nop.Web>    at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270
Nop.Web>    at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web>    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web>    at System.Threading.TimerQueueTimer.CallCallback()
Nop.Web>    at System.Threading.TimerQueueTimer.Fire()
Nop.Web>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web>       Executed DbCommand (84ms) [Parameters=[@p0='?' (DbType = DateTime2), @p1='?' (DbType = Int32), @p2='?' (Size = 4000), @p3='?' (Size = 200), @p4='?' (DbType = Int32), @p5='?' (Size = 4000), @p6='?' (Size = 4000), @p7='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
Nop.Web>       SET NOCOUNT ON;
Nop.Web>       INSERT INTO [Log] ([CreatedOnUtc], [CustomerId], [FullMessage], [IpAddress], [LogLevelId], [PageUrl], [ReferrerUrl], [ShortMessage])
Nop.Web>       VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);
Nop.Web>       SELECT [Id]
Nop.Web>       FROM [Log]
Nop.Web>       WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

**Comment by DmitriyKulagin** [comment]
@lintho 
I installed version 3.80 (with the "create sample data" checkbox set) and subsequently applied the scripts 3.90 - 4.0 - 4.10 to it. Half of this project 4.10 successfully launched on the final version of the database. Perhaps the problem is in your database. Can you send a dump of your base so that I can check the migration on it?

And what version of SQL Server are you using?

**Comment by lintho** [comment]
Hello. I will send it later this evening. Do you have a script to eliminate customer data. Its not that i don't trust you, but you know, policy etc.
________________________________

**Comment by DmitriyKulagin** [comment]
@lintho Just update the table Customer, all fields set "".

**Comment by lintho** [comment]
As far as i can see the problem was [Url] in [dbo].[Store] being set to an external url which didn't not exists anymore.

Could we have a separate url for development mode in admin?

**Comment by DmitriyKulagin** [comment]
@lintho 

> As far as i can see the problem was [Url] in [dbo].[Store] being set to an external url which didn't not exists anymore.

It seems that it is so. Because I tried to run the project as from the db-38 dump (full up to 4.1), and from the db-41 dump and all worked successfully.

> Could we have a separate url for development mode in admin?

Technically, this is possible. To do this, you must use the multistor mode in the admin panel for different URLs. And in the code forbid to show the administration area on one of them.
