### ISSUE TITLE
Indent missing under coupon code as URL

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3123]
nopCommerce version: 4.10

Steps to reproduce the problem: 
If you select "Requires coupon code" under "Promotions\Discounts\Discount Info" then the other fields open. The new "URL with coupon code" is not indent with the other upper fields.

![indent](https://user-images.githubusercontent.com/37210350/42508495-0293137c-8449-11e8-8b87-30c55c3b91ac.png)

**Comment by AndreiMaz** [comment]
why not? it is

**Comment by cnEUL** [comment]
I mean the third field, with the URL. It is an explanation, but has its own field name with hint. It should have moved in like this. If it is only a hint, the field name and hint would have to go away and then the explanatory text just below the field above, right?

**Comment by AndreiMaz** [comment]
No, it's by design
