### ISSUE TITLE
Notify customers when a store owner (or vendor) replies to their product reviews 

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3124]
nopCommerce version:  4.10

For me throup GDPR Policy it has to be accepted per customer in one if the consents. I have seen per default the corresponding messagetemplat eis not active. But this seems to be to be enhanced by individual consents,

**Comment by AndreiMaz** [comment]
after some discussion we've decided to leave it this way. not sure that each customer can choose whether to receive this email or not. You can write it in the policy that everyone will be notified about review replies
