### ISSUE TITLE
Hide My Account on Top Menu

### ISSUE THREAD

**Issue by josephhua** [nopSolutions/nopCommerce#3125]
nopCommerce version: 4.10b

Steps to reproduce the problem: Sign in as an administrator, and click Administration button on the to.
In the admin screen, click Configuration -> Settings -> General settings, the display "My Account" is not checked, but in public store, My Account is displayed. We really don't want it displayed at this point. So I check the checkbox, and save the page. Go to public store, and My account is still displayed.

**Comment by skoshelev** [comment]
Hi @josephhua. This is not bug, this settings for another place. Please see the image for more details

![img](http://dl3.joxi.net/drive/2018/07/12/0025/1250/1656034/34/c3653ae8e3.jpg)

Closed #3125

**Comment by josephhua** [comment]
Got it. Thanks -- Joseph
