### ISSUE TITLE
What is meant in Changelog with "Support filtering by product in summary reports on the order list page"

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3126]
nopCommerce version:  4.10

I checked Issues and also the version about that, but i could not find that filter. Where can i find that?

"Support filtering by product in summary reports on the order list page (admin area)"

**Comment by AndreiMaz** [comment]
Chris, Github is for issues. Could you please post questions on our forums? Thanks a lot!

**Comment by cnEUL** [comment]
Yes no problem, I thought forum is not for beta.

chris

Von: Andrei Mazulnitsyn [mailto:notifications@github.com]
Gesendet: Dienstag, 10. Juli 2018 16:39
An: nopSolutions/nopCommerce <nopCommerce@noreply.github.com>
Cc: Christian Niedergesäß <cn@eulanda.de>; Author <author@noreply.github.com>
Betreff: Re: [nopSolutions/nopCommerce] What is meant in Changelog with "Support filtering by product in summary reports on the order list page" (#3126)


Chris, Github is for issues. Could you please post questions on our forums? Thanks a lot!
