### ISSUE TITLE
Preview button dont show changes on news, topics etc. only after saving.

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3128]
nopCommerce version:  4.10

Steps to reproduce the problem: 
The news, topics etc. have a new preview button. Like the name says, it should be a preview, before it goes live. But it did not shows the changes. I have to save the changed content prior, i think it is not that what it should, or ?

**Comment by AndreiMaz** [comment]
It's by design. You save it withput publishing. Then you can preview it
