### ISSUE TITLE
Bundling not versioning when plugin javascript or css content modified.

### ISSUE THREAD

**Issue by Jerod5** [nopSolutions/nopCommerce#3130]
nopCommerce version: v4.0

Steps to reproduce the problem: 
1. Enabled bundling.
2. Modify Javascript or CSS content in a plugin (do not rename the file).

Result:
The bundled files are not versioned with the new Javascript or CSS changes

Request:
Add functionality that identifies a change has occurred and version the bundled files. This will guarantee that if a plugin does not or cannot version JS or CSS the bundles will be versioned.

By not versioning it produces risk of customers loading old content and worst case the entire site not loading until their browser cache is updated.

**Comment by AndreiMaz** [comment]
Bundled files are cached. You can reset cache in admin area
also see https://github.com/nopSolutions/nopCommerce/issues/3092

**Comment by Povilas-Jeremicius** [comment]
I believe admin area cache resetting does not help, as your browser caches bundles. A request to retrieve the new bundle never gets to server. Consider the following scenario:

- A user makes a request to the page that has 2 JS files linked in the page: Js1. js and Js2.js
- Server receives the request to the page and does bundling (creates bundle1.js). This bundle is cached.
- bundle1.js is added as a reference in the page.
- User receives the response for the page request and tries to render the HTML. User's browser notices a reference to bundle1.js and makes another request to retrieve this file.
- Server retrieves the cached version of bundle1.js and sends it back to the user. 
- User's browser caches bundle1.js (hooray, everything works as expected so far!)
- A change in Js2.js is introduced and a new version of application is deployed.
- Cache is cleared in admin area.
- A user makes a request to the page that has 2 JS files linked in the page: Js1. js and Js2.js
- Server receives the request to the page and does bundling (creates bundle1.js). This bundle is cached.
- bundle1.js is added as a reference in the page. (uh oh, I see what's going to happen *starts sweating*)
- User receives the response for the page request and tries to render the HTML. User's browser notices a reference to bundle1.js
- User's browsers pulls the cached version of bundle1.js *panic starts*
- A change that is introduced in Js2.js is not present.

Evidence of browser caching from a live page:

First load:
![image](https://user-images.githubusercontent.com/52908470/84862005-089a0900-b07b-11ea-8223-0c032f78590d.png)

Refresh:
![image](https://user-images.githubusercontent.com/52908470/84862682-464b6180-b07c-11ea-96bd-edd821a5b24f.png)

Notice **loaded from Disk cache** part
