### ISSUE TITLE
Search engine friendly page names: Column 'name' is empty in overview

### ISSUE THREAD

**Issue by lsx84** [nopSolutions/nopCommerce#3131]
nopCommerce version: 4.10 Beta

Steps to reproduce the problem: 
Go to 'Search engine friendly page names' from the 'System' menu.

Expected 'name' column to be filled, but is empty:

![capture](https://user-images.githubusercontent.com/1829944/42530411-6078b1ee-8481-11e8-9fdc-b5a1946e537c.PNG)

**Comment by RuS984** [comment]
Closed #3131
