### ISSUE TITLE
Tab 'Current Shopping cart' have now to be "Current shopping cart and wishlist"

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3132]
nopCommerce version: 4.10 beta

Steps to reproduce the problem: 
Go customer, then upper you see all tabs, also "Current shopping cart" which is now also a wishlist.
If you are in the first tab, you could not imagine, that behind this tab is a selectable value between shopping cart and wishlist. The tab name should be changed like the menu item to be consistent.

![cart_wishlist](https://user-images.githubusercontent.com/37210350/42532294-be1c65a2-8486-11e8-873e-0870d471e0d5.png)

Let's renamed it to "Current shopping cart and wishlist"

**Comment by DmitriyKulagin** [comment]
Closed #3132
