### ISSUE TITLE
Support "tax" name per country

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3133]
Nop 4.10 also before

We have a serious problem with the tax display. The problem is that there are different countries in Europe with different tax rates, but they speak the same language. Austria, Switzerland and Germany as examples.

In the Admincenter I can activate the "Display Tax Prefix", which has to be done according to the law "PAngV". But there is only one translation for the word "Tax" from the resource.

The problem is that shops sell across national borders. A customer from Austria must therefore see that the price displayed contains the "German tax rate". 

Amazon has already changed its pages and displays: "All prices include German VAT" and translates this text depending on the country setting.

We do not need a simple click field as it is now available, but also a multilingual text field that can be changed by the shop user. 

The problem is that we have to put the country in the text of the tax. And then the language package (ResourceStrings) is no longer usable for all countries that speak this language. Because an Austrian would have to stand: The price includes the Austrian tax...

For clarification I have added the setting in the admin center and two Amazon screens, which display this circumstance cleanly depending on the language.

![tax1](https://user-images.githubusercontent.com/37210350/42559771-64577934-84f5-11e8-8687-af30b6862cb6.png)

![tax2en](https://user-images.githubusercontent.com/37210350/42559782-6a88e2f2-84f5-11e8-8dab-e943915fa89b.png)

![tax2de](https://user-images.githubusercontent.com/37210350/42559790-6d160342-84f5-11e8-915e-d98a1faefb97.png)

**Comment by cnEUL** [comment]
The problem is that we have to put the country in the text of the tax. And then the language package (ResourceStrings) is no longer usable for all countries that speak this language. Because an Austrian would have to stand: The price includes the Austrian tax...

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
