### ISSUE TITLE
PublishModelEventsFilter - Model casted to BaseNopModel

### ISSUE THREAD

**Issue by alecrt** [nopSolutions/nopCommerce#3134]
Hi guys,

which is the reason of casting ViewData.Model to BaseNopModel?

```csharp
if (controller.ViewData.Model is BaseNopModel model)
{
//we publish the ModelPrepared event for all models as the BaseNopModel, 
//so you need to implement IConsumer<ModelPrepared<BaseNopModel>> interface to handle this event
 _eventPublisher.ModelPrepared(model);
}
```
If you skip the cast we could use something like IConsumer<ModelPrepared[ProductDetailsModel]> while now we need to have a single IConsumer and check the type inside there.

**Comment by AndreiMaz** [comment]
It's a ModelPrepared event. And it's only for nopCommerce models. It's by design
