### ISSUE TITLE
Cannot publish from VisualStudio 2017

### ISSUE THREAD

**Issue by alecrt** [nopSolutions/nopCommerce#3136]
4.10 BETA 

Visual studio v. 15.7.5 (very latest)
.NET SDK 2.1.1 (build 301)

I can't publish from Visual Studio and i get the following error.
dotnet publish works fine.

```
11/07/2018 12:37:15
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass41_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__116.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

===================
```

Output window, unfortunately, has no more details:
```
1>------ Build started: Project: Nop.Web, Configuration: Release Any CPU ------
1>Nop.Web -> D:\Lavori\Dumont\nopCommerce\src\Presentation\Nop.Web\bin\Release\netcoreapp2.1\Nop.Web.dll
2>------ Publish started: Project: Nop.Web, Configuration: Release Any CPU ------

2>Build failed. Check the Output window for more details.
========== Build: 1 succeeded, 0 failed, 4 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by AndreiMaz** [comment]
Cannot reproduce. Works fine.

Where do you publish it? File system?

**Comment by alecrt** [comment]
Nopre, to a remote IIS using webdeploy

**Comment by alecrt** [comment]
From diagnostic verbose level of the output window I get the following tip:
```
Using "GetReferenceNearestTargetFrameworkTask" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll".
        Task "GetReferenceNearestTargetFrameworkTask"
        Done executing task "GetReferenceNearestTargetFrameworkTask" -- FAILED.
```

I already opened a support post on asp.net forum:
https://forums.asp.net/post/6217383.aspx

**Comment by AndreiMaz** [comment]
Is it published withput errors when ypu try to deploy it to a file system (local)

**Comment by alecrt** [comment]
Yes, if I use dotnet publish from command line it works like a charm.

**Comment by DmitriyKulagin** [comment]
@alecrt 
I tried to reproduce your problem using the latest versions of the .NET Core packages:
 [Hosting Bundle Installer](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.2-windows-hosting-bundle-installer)
[.NET Core 2.1 SDK (v2.1.302)](https://www.microsoft.com/net/download/all)

and the following publishing options (local IIS using webdeploy):

![image](https://user-images.githubusercontent.com/27218280/42692453-74bdcd80-86b4-11e8-9c36-703edaadc5ea.png)

As a result, everything worked.
Try to update the library, perhaps the problem was in the version of the SDK that you used.

**Comment by alecrt** [comment]
Still fail.. same error. Very strange
```
Using "GetReferenceNearestTargetFrameworkTask" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll".
Done building project "Nop.Web.csproj" -- FAILED.
```

**Comment by alecrt** [comment]
Maybe it's not related with Nop, I'll investigate more when i have some time.
For the moment I happy with local publish and manual file transfer

**Comment by VR-Architect** [comment]
Is this related? There seems to be a solution at the bottom of the first link's page:

- `https://social.msdn.microsoft.com/Forums/windows/en-US/749a10e6-a5cf-4693-9b59-2ab0510279b0/the-nugetbuildtasksgetreferencenearesttargetframeworktask-task-could-not-be-loaded?forum=msbuild`

- [https://stackoverflow.com/questions/47863923/the-getreferencenearesttargetframeworktask-task-has-been-declared-or-used-inco](url)

**Comment by alecrt** [comment]
Unfortunately, already tried.

As I said, I think it’s something related with my env, so if you want close it and let see if someone else encounter the problem.

Inviato da iPhone

Il giorno 14 lug 2018, alle ore 16:29, Architect <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Is this related? There seems to be a solution at the bottom of the first link's page:

  *   https://social.msdn.microsoft.com/Forums/windows/en-US/749a10e6-a5cf-4693-9b59-2ab0510279b0/the-nugetbuildtasksgetreferencenearesttargetframeworktask-task-could-not-be-loaded?forum=msbuild

  *   https://stackoverflow.com/questions/47863923/the-getreferencenearesttargetframeworktask-task-has-been-declared-or-used-inco<url>

**Comment by DmitriyKulagin** [comment]
You tried update your MSBUILD Tools components?

Download the latest version of MSBUILD tools from https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017, run it, choose Modify and then select “Web development build tools” and “.NET Core build tools”.

Try the same method suggested [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c50943f0-7154-44ed-bc64-c144f12255b6/how-do-i-fix-the-quotgetreferencenearesttargetframeworktaskquot-error-in-visual-studio?forum=msbuild).

**Comment by alecrt** [comment]
Downloaded, installed, disabled Resharper and now i can publish.
Thx @DmitriyKulagin

**Comment by ocinbat** [comment]
I would like to re-open this issue.
I experience the same problem but it only occurs when I have ReSharper enabled on my VS 2017.

**Comment by gopaldahal** [comment]
I am facing the same issue. I am running vs 2017 and trying to deploy using File system. Project successfully build. However throws exception like this during Publish.


4/1/2019 10:46:19 AM
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

===================

**Comment by abhiquiet** [comment]
Hi, 

Even i get the same error, but have resolved the issue. 

I had updated my application from 2.2.1 to 2.2.2 and now i was trying to publish the application, and was facing the similar issue as reported above. 

I think the updation in nuget package must have left some issue of the publish properties. 

I closed the VS 2017, went to the properties folder and removed the PublishProfile folder. 

I again opened the solution, and created new publish profile. 

My project was published with charm. 

Regards. 

Abhinav Aggarwal

**Comment by hasibul2363** [comment]
Adding following to your csproj file might solve the issue
` <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />`

**Comment by khaidev** [comment]
In case some files included project, but do not exist on folder. The publish wizard will fail.
So please check all files included project correct.

**Comment by matthewpetch** [comment]
I'm having the same issue, only in VS2019

**Comment by asrinakbari** [comment]
Hi 
I am solve this error in your project with update MSBUILD Tools for Visual Studio 
 and get package System.Reflection.Emit from Nuget

**Comment by marcnoon** [comment]
Having same issue in lastest VS2019 as well.  Maybe someone that is an attack dog can fix this??????

**Comment by marcnoon** [comment]
I got a big error message in .tmp file: 

12/28/2019 9:53:48 PM
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.WebTools.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__213.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

System.Exception: Build failed. Check the Output window for more details.

===================

**Comment by marcnoon** [comment]
I got this working by switching from ftp publishing to Web Deploy using MSDeploy server.   Guess ftp doesn't want to always work .. or file publishing doesn't always work.  But it looks like in my case MS Deploy or WebDeploy ( or are they the same thing? ) did work.

**Comment by marcnoon** [comment]
Now when I switched back to file or ftp publish it magically works.?!?

**Comment by marcnoon** [comment]
I wanted to add one more thing... I think I switched to back to release environment and then when I switched to my production name environment again that started working.  Maybe switching the environment setting clears up the old settings somehow so I no longer see that error message.

**Comment by rameshkunwar** [comment]
I had similar error on Visual Studio 2019. Don't forget to check **Output** tab. The last line explains the error!

**Comment by DaveCousineau** [comment]
I'm getting this in VS2019. Good advice to check the build output window.

The issue, at least in my case, seems to have something to do with disagreement between projects over where build output ends up. The publishing project is appending `\<framework>\<runtime>\` directories to the path, whether or not the other projects specify them in their build path or not. This means that if the other projects build to `\bin\x86\debug\` then the publishing project looks for files in that project's `\bin\x86\debug\net40\win-x86\` folder, for example, which doesn't exist. If I change the output folder to `\bin\x86\debug\net40\win-x86\` then the publishing project actually looks for files in `\bin\x86\debug\net40\win-x86\net40\win-x86\` which is kind of ridiculous...

For class libraries, I only get this wrong path issue if I specify `<RuntimeIdentifiers>` in the `.csproj` file of the referenced class library. If I remove that tag, it seems to get the wrong path. (Though, with all these wrong paths who knows if it's even getting the version of the files that just built or not.)

And unfortunately in this case I am also referencing another executable project, and the wrong path issue happens whether or not I specify `<RuntimeIdentifiers>` in the executable project file.

**Comment by Naz786** [comment]
I have found the answer which works for me: Run Visual Studio as Administrator. It explains the Access denied errors in the output log. Let me know if this helps you. :)

**Comment by erasmosud** [comment]
Try Again with 3 solutions;

https://www.problemsolvedtoo.com/2019/08/03/how-to-solve-gatherallfilestopublish-error/

https://intellipaat.com/community/2459/why-do-i-get-the-error-the-target-gatherallfilestopublish-does-not-exist

https://dotnetthoughts.net/how-to-fix-error-the-target-gatherallfilestopublish-does-not-exist-in-the-project/

**Comment by boripatthongmaha** [comment]
Remove  file .log  from folder  App_data in your project , it work for me.

**Comment by AndreiMaz** [comment]
Please find our requirements [here](https://docs.nopcommerce.com/en/installation-and-upgrading/technology-and-system-requirements.html). For nopCommerce 4.70 or above you need MS Visual Studio 2022 (version 17.9 or above). And don't forget to install .NET 8 SDK ([download](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.204-windows-x64-installer)). Required for developers who want to edit the source code.
