### ISSUE TITLE
Error when using a URL (store) that does not exist. It should throw error with usable errormessage.

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#3139]
nopCommerce version: 
4.1

Steps to reproduce the problem: 
If you have a url in the store(settings) that does not exist, you get a 502 error with no real error message. In order to find the real error, you have to debug the solution and get "No such host".

Should there be a seperate URL for development?

**Comment by AndreiMaz** [comment]
So for example you entered "www.dfgdfgdfgdfgdfgdfg.com" URL. When exactly do you get this error?

**Comment by lintho** [comment]
Hello. As far as i can see this is whats going on:
The local webserver(asp.net core web server) says the following when NOT debugging:


Nop.Web> info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
Nop.Web> Entity Framework Core 2.1.1-rtm-30846 initialized 'NopObjectContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using lazy-loading proxies
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web> Executed DbCommand (58ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web> SELECT [t].[Id], [t].[Enabled], [t].[LastEndUtc], [t].[LastStartUtc], [t].[LastSuccessUtc], [t].[Name], [t].[Seconds], [t].[StopOnError], [t].[Type]
Nop.Web> FROM [ScheduleTask] AS [t]
Nop.Web> WHERE [t].[Enabled] = 1
Nop.Web> ORDER BY [t].[Seconds] DESC
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web> Executed DbCommand (39ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web> SELECT [s].[Id], [s].[CompanyAddress], [s].[CompanyName], [s].[CompanyPhoneNumber], [s].[CompanyVat], [s].[DefaultLanguageId], [s].[DisplayOrder], [s].[Hosts], [s].[Name], [s].[SslEnabled], [s].[Url]
Nop.Web> FROM [Store] AS [s]
Nop.Web> ORDER BY [s].[DisplayOrder], [s].[Id]
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web> Executed DbCommand (50ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
Nop.Web> SELECT [s].[Id], [s].[Name], [s].[StoreId], [s].[Value]
Nop.Web> FROM [Setting] AS [s]
Nop.Web> ORDER BY [s].[Name], [s].[StoreId]
Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000]
Nop.Web> An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
Nop.Web>
Nop.Web>
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web>
Nop.Web> Unhandled Exception: Unhandled Exception: Unhandled Exception: System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave) Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection() Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave)
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Nop.Data.EfRepository1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81 Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe. Nop.Web> at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220 Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection() Nop.Web> at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45 Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave)
Nop.Web> at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000]
Nop.Web> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web> An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave) Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at System.Threading.TimerQueueTimer.CallCallback() Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at System.Threading.TimerQueueTimer.Fire() Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe. Nop.Web> at System.Threading.TimerQueue.FireNextTimers() Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection() Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe. Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave)
Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave) Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> fail: Microsoft.EntityFrameworkCore.Update[10000] Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'. Nop.Web> at Nop.Data.EfRepository1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave) Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220 Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe. Nop.Web> at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45 Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection() Nop.Web> at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270 Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave)
Nop.Web> at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web> at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nop.Web> at System.Threading.TimerQueueTimer.CallCallback()
Nop.Web> at System.Threading.TimerQueueTimer.Fire()
Nop.Web> at System.Threading.TimerQueue.FireNextTimers()
Nop.Web> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
Nop.Web> at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList1 entriesToSave) Nop.Web> at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) Nop.Web> at Nop.Data.EfRepository1.Insert(TEntity entity) in F:\Repos\proj\src\Libraries\Nop.Data\EfRepository.cs:line 81
Nop.Web> at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 220
Nop.Web> at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in F:\Repos\proj\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 45
Nop.Web> at Nop.Services.Logging.DefaultLogger.Error(String message, Exception exception, Customer customer) in F:\Repos\proj\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 270
Nop.Web> at Nop.Services.Tasks.TaskThread.Run() in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 70
Nop.Web> at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in F:\Repos\proj\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
Nop.Web> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Nop.Web> --- End of stack trace from previous location where exception was thrown ---
Nop.Web> at System.Threading.TimerQueueTimer.CallCallback()
Nop.Web> at System.Threading.TimerQueueTimer.Fire()
Nop.Web> at System.Threading.ThreadPoolWorkQueue.Dispatch()
Nop.Web> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Nop.Web> Executed DbCommand (84ms) [Parameters=[@p0='?' (DbType = DateTime2), @p1='?' (DbType = Int32), @p2='?' (Size = 4000), @p3='?' (Size = 200), @P4='?' (DbType = Int32), @p5='?' (Size = 4000), @p6='?' (Size = 4000), @P7='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
Nop.Web> SET NOCOUNT ON;
Nop.Web> INSERT INTO [Log] ([CreatedOnUtc], [CustomerId], [FullMessage], [IpAddress], [LogLevelId], [PageUrl], [ReferrerUrl], [ShortMessage])
Nop.Web> VALUES (@p0, @p1, @p2, @p3, @P4, @p5, @p6, @P7);
Nop.Web> SELECT [Id]
Nop.Web> FROM [Log]
Nop.Web> WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

**However, while debugging you get the following error:**

"System.Net.WebException: No such host is known No such host is known ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\r\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   at System.Net.HttpWebRequest.SendRequest()\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request)\r\n   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\r\n   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)\r\n   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)\r\n   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)\r\n   at Nop.Services.Tasks.TaskThread.Run() in C:\\Users\\sindr\\Source\\Repos\\proj\\src\\Libraries\\Nop.Services\\Tasks\\TaskThread.cs:line 64"

**Comment by alecrt** [comment]
Same error as #3146

But i get this one even with Keep alive task disabled.
In my case any error that happens in a scheduled task generate this dbContext exception.

From I can see it's related with error logging on scheduled tasks.

**Comment by skoshelev** [comment]
Closed #3139
