### ISSUE TITLE
Redis cache services no inject in plugins controller but inject Per-Request Cache

### ISSUE THREAD

**Issue by DiogenesPolanco** [nopSolutions/nopCommerce#3141]
nopCommerce version: 3.90

I have created several plugins in this version of nopcomemrce but when I enable the use of redis cache, they do not inject themselves but inject me with the service per-request-cache

Steps to reproduce the problem: 
1-Create a plugin
2-Uses the cache service to cache a database query
3-Enable redis cache in the web.config

You can see that queries to the database continue to be made without using the cache. 

Any suggestions or alternatives to solve this problem?

**Comment by DmitriyKulagin** [comment]
@DiogenesPolanco 
In version 4.10 Redis cache services injected correctly. 
For version 3.90 use the following code in the plugin constructor:
`this._cacheManager = EngineContext.Current.ContainerManager.Resolve<ICacheManager>("nop_cache_static");`
