### ISSUE TITLE
Setup failed: Value cannot be null. Parameter name: hashAlgorithm

### ISSUE THREAD

**Issue by josephhua** [nopSolutions/nopCommerce#3142]
nopCommerce version: 4.10 beta

Steps to reproduce the problem: 
Trying to deploy NopCommerce 4.10 beta to Microsoft aZure. After deployed, go to the newly created aZure website, and setup page is loaded. After entering all the required data, got the error in red:
Setup failed: Value cannot be null. Parameter name: hashAlgorithm

The same error occurred in 4.0 beta also after searching the internet.

**Comment by skoshelev** [comment]
The same as #2970

**Comment by skoshelev** [comment]
@josephhua Sorry, I can't reproduce this issue. Can you enable the stdoutLogEnabled setting in the web.config file and give us more details about this error?

**Comment by VR-Architect** [comment]
I had this error too:
https://github.com/nopSolutions/nopCommerce/issues/3162

**Comment by ricard257** [comment]
have you clicked create sample data?

**Comment by skoshelev** [comment]
Can not reproduce

Closed #3142

**Comment by pantonis** [comment]
Have the same error when trying to install on a Windows Server 2012 R2 VPS

**Comment by sharpapp-mareklanduch** [comment]
I have the same thing... It's funny because I have installed previous version of nopcommerce and everything was working like a charm. I have this issue on webio.pl hosting. 
Additional info: I had problem with schema. There was something wrong with dbo.QueueEmail table or something like that so I decided to change default schema for this user to [dbo]. So now I'm struggling with this one. 
Is there any solution?

**Comment by cklenk** [comment]
This happened to me too. I got the same Setup failed: Value cannot be null. Parameter name: hashAlgorithm. I deleted the database and reinstalled it with no sample data and it worked the second time. I am doing a local IIS install on a win 10 box, not sure if that helps. I didn't have stdout logging on the first time, so I don't have the log when I received that error sorry. Just thought I would let you all know! Thanks.

**Comment by adrianiftode** [comment]
I have the same issue, I changed the code a bit so I can see the stack trace (btw, you should log these exceptions, not only show the error.Message).

```
System.ArgumentNullException: Value cannot be null.
Parameter name: hashAlgorithm
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in .Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 83
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by adrianiftode** [comment]
I checked the logging part, as the app thinks the database is not available, this error doesn't show in the Log table. Is there a way to enable a rolling file logger?

**Comment by spottedmahn** [comment]
Seems to be a [timeout issue as stated here](https://github.com/nopSolutions/nopCommerce/issues/2970#issuecomment-404492316)

- I deleted the DB
- I changed my raw connection string to have a much longer timeout value:
`Server=tcp:blah.database.windows.net,1433;Initial Catalog=blah;Persist Security Info=False;User ID=blah;Password=blah;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300000;`

worked this time 👍
