### ISSUE TITLE
Setup failed: An error occurred while creating the database

### ISSUE THREAD

**Issue by josephhua** [nopSolutions/nopCommerce#3143]
nopCommerce version: 4.10 beta

Steps to reproduce the problem: 
In Microsoft aZure, create a website without database. Open the website, the setup page will appear. After entering all the data needed, click start. After a while, got the following error:
Setup failed: An error occurred while creating the database: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. CREATE DATABASE operation failed. Internal service error.

When look at the database on the aZure, it has been created. So the time to wait the process of creating database should be longer.

**Comment by AndreiMaz** [comment]
it's just a timeout
