### ISSUE TITLE
Beta- 4.10 Minification is not working for min CSS file for new theme

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3148]
nopCommerce version: 4.10 Beta

Steps to reproduce the problem: 

1.  Add new theme with have .min css and js file
2.  Now enable bundling and minification from Admin > Configuration > Setting  > General Settings
3.  Save setting
4.  Now select new theme
5.  Save setting
After save setting new theme is applying and jquery min files are working fine. **But min css file is not working and design messed up**.

**Comment by AndreiMaz** [comment]
@rajupaladiya please share your theme with @mariannk

**Comment by rajupaladiya** [comment]
@mariannk - Click [here](http://xitstage2-001-site1.mysitepanel.net/RootTheme.zip) for download theme

**Comment by rajupaladiya** [comment]
@mariannk - Did you get theme folder?

**Comment by mariannk** [comment]
@rajupaladiya yes

**Comment by rajupaladiya** [comment]
@mariannk - Okay, Glad to hear 👍

**Comment by mariannk** [comment]
@rajupaladiya your ccs file root-theme-styles.css contains errors. That's why minification doesn't work and appropriate .min.css filw could not be found. Fix errors before enabling css bundling and minification.

**Comment by rajupaladiya** [comment]
@mariannk  - Okay thank you for update. Will check and update you on Monday.
