### ISSUE TITLE
SquareUp nonce

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3152]
Anyone seen this? Not sure what causes it

`Short message
Square payment error: Error calling Charge: {"errors":[{"category":"INVALID_REQUEST_ERROR","code":"CARD_TOKEN_USED","detail":"Card nonce already used; please request new nonce."}]}.

Full message
Square.Connect.Client.ApiException: Error calling Charge: {"errors":[{"category":"INVALID_REQUEST_ERROR","code":"CARD_TOKEN_USED","detail":"Card nonce already used; please request new nonce."}]}’

**Comment by Ochapparel** [comment]
Nop 4.00

**Comment by AndreiMaz** [comment]
please see https://www.sellercommunity.com/t5/Developer-Discussions/Creating-Customer-Card/td-p/27378

**Comment by Ochapparel** [comment]
I did read that. Just wasn't sure how it related to Nop. 

Thanks, keep up the good work

**Comment by softkey87** [comment]
Hi, I'm also having this error, which is related to the "save card for future use". I've read the post from Andrei, but I don't understand how to solve the problem. Ochapparel: Did you figure how to solve this problem? Thank you

**Comment by softkey87** [comment]
Thank you for your answer. Unfortunatly I'm already on 4.10 and still have the issue. I will let you know if I found something else. Thanks

**Comment by kylesullens** [comment]
I am having his issue using GrandNode 4.7.

I have purchased the Square plugin from the GrandNode team.  The plugin was functioning fine and then this error started occurring.  

If anyone has insight into the issue and how to resolve it, I would appreciate it.  Thanks
