### ISSUE TITLE
Move CommonSettings.UseResponseCompression setting to UI

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3153]
Let's decide where exactly

**Comment by demckee** [comment]
Yes, it was annoying to find it moved without notice in 4.10.

From what I've been able to understand, there are security issues when you use compression over https. The default in the Microsoft code is to disable compression when https is used. However, this is a poor solution as some things (bundled css/js) have no sensitive information, and can be safely compressed. The issue relates to a BREACH attack, and would apply to pages showing sensitive information only. So, it sounds like what we need is a way of selectively enabling/disabling compression, on a per-page basis. It should be disabled for the back-end, and enabled for most public pages.

**Comment by RuS984** [comment]
Closed #3153
