### ISSUE TITLE
Use CookiePolicy feature

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3156]
https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1

But we already have the [EuCookieLaw ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Shared/Components/EuCookieLaw/Default.cshtml)view component for such purposes

**Comment by a-patel** [comment]
In this case,
you should write the wrapper around existing GDPR middleware or something like that.
#suggestion

**Comment by AndreiMaz** [comment]
let's use our implementation
