### ISSUE TITLE
4.10 BETA - Feature Request - Security / Logs

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3160]
nopCommerce version: 4.10 BETA

Feature Request:
- If the user clears the log, create a new entry in the empty log showing the log was cleared and by whom.

**Comment by AndreiMaz** [comment]
@VR-Architect  I cannto reproduce it. It works fine. When you clear log, you can see it in the "activity log" (not the same as "system log")

**Comment by VR-Architect** [comment]
OK, if it is in system logs, all is good from a trace-ability perspective. Might be good to add to the system log too :)

**Comment by AndreiMaz** [comment]
Activity log enough. Thanks
