### ISSUE TITLE
4.10 BETA - Feature Request: Attached to existing nopCommerce database

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3162]
nopCommerce version: 4.10 BETA

Steps to reproduce the problem: 

1. Downloaded the 4.10 source code and deployed 5 days ago with sample data. It created the database and works great.
2. Deleted source code locally and downloaded source code from today and deployed. Install page appeared. 
3. There is no option on install page to re-attach to an existing nopCommerce database. So put in my connection string of existing database and existing nopCommerce admin user credentials without sample data. Received error on install page which doesn't really help the user to understand what to do:

`Setup failed: Sequence contains more than one element`

Could we get an attach to existing nopCommerce database option on this page as a feature request please?

Much appreciated.

**Comment by VR-Architect** [comment]
I deleted the existing database and ran the install again. Now I get this error message:

```
Setup failed: Value cannot be null.  Parameter name: hashAlgorithm
```

This is my connection string:
`Data Source=SQL5040.site4now.net;Initial Catalog=DB_A3E515_;User Id=DB_A3E515_userHere;Password=myPwHere;`

**Comment by VR-Architect** [comment]
A third try results in the same error as my first post.

**Comment by VR-Architect** [comment]
The errors seem related to 
https://github.com/nopSolutions/nopCommerce/issues/3142
https://github.com/nopSolutions/nopCommerce/issues/2970

However, my feature request is still requested please.

**Comment by AndreiMaz** [comment]
"Sequence contains more than one element" means that your database is not empty. You should delete all tables

**Comment by VR-Architect** [comment]
Then why not change the error message to be more user friendly? :)

**Comment by AndreiMaz** [comment]
This error is generated by Entity Frameworl. I think it should be better "fixed" by them

**Comment by Leftyx** [comment]
@AndreiMaz I don't think the problem is Entity Framework.
I've added Serilog to my implementation cause the errors/exceptions management is poor.
I've also added some traces and the problem sits in `CustomerRegistrationService.ChangePasswordResult`.

This bit of code:

```
case PasswordFormat.Hashed:
    var saltKey = _encryptionService.CreateSaltKey(NopCustomerServiceDefaults.PasswordSaltKeySize);
    customerPassword.PasswordSalt = saltKey;
    customerPassword.Password = _encryptionService.CreatePasswordHash(request.NewPassword, saltKey, _customerSettings.HashedPasswordFormat);
```

uses and injected setting: `_customerSettings.HashedPasswordFormat`

which is not resolved when pre-populating some data.

It happens randomly.
It's an issue.

**Comment by Leftyx** [comment]
One simple fix which seems to make things work is try to resolve `CustomerSettings `before changing password:

`var customerSettings = EngineContext.Current.Resolve<CustomerSettings>();`

at this line:

[CodeFirstInstallationService.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs#L4207)
