### ISSUE TITLE
4.10 BETA - Products not showing after install

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3163]
nopCommerce version: 4.10 BETA

Steps to reproduce the problem: 

1. Download source code as of July 14th version, build/release, and publish.
2. Create new database and configure on install page with sample data
3. Site comes up to http://www.voogu.net/login?ReturnUrl=%2F page asking user to login
     No products are showing
4. Login and still no products on public site. Enter 'book' in searchbox and no products show in search dropdown.
5. Go to admin, and can see all the products are there and published is true. Also the sample customers and vendors are also present.

Why are the products not showing on the public site after initial installation with sample data?
http://www.voogu.net/

**Comment by VR-Architect** [comment]
Also, after you log in, it stays on the log in page and shows that you are logged in.

**Comment by VR-Architect** [comment]
I just noticed that every link on the public site is going to this url http://www.voogu.net/login?ReturnUrl=%2F

**Comment by AndreiMaz** [comment]
your installation wasn't completed (timeouted). Please re-install the site
