### ISSUE TITLE
Low Stock Activity - feature not working

### ISSUE THREAD

**Issue by venta360** [nopSolutions/nopCommerce#3164]
nopCommerce version: 4.0

Steps to reproduce the problem: 
- select option to disable buy button and nothing happens see attached screenshot
- this is the product detail page http://nop40.odegiecommerce.com/nikon-d5500-dslr-red that still shows buy button.    Add to cart also shows up in grouped item http://nop40.odegiecommerce.com/nikon-d5500-dslr and category list page

![2018-07-16_1733](https://user-images.githubusercontent.com/16600505/42784859-76f6aefc-891e-11e8-9989-ec6ea98776a8.png)

**Comment by AndreiMaz** [comment]
It happens not after changes in admin area. But only after a purchase in public store (after an order is placed). It's by design
