### ISSUE TITLE
Double discount for associated items

### ISSUE THREAD

**Issue by kwerty** [nopSolutions/nopCommerce#3165]
nopCommerce version: 4.0

The problem happens when you have a product which has an associated product
For example "Computer motherboard" with associated product "Computer CPU"

Steps:

* Create two products with price $50
* Create a checkbox attribute on product 1 and associate it to product 2
* Go to product 1 page and tick the checkbox - price is $100 - so far so good
* Now create a 50% discount on product 1
* Go to product page and tick the checkbox - price is $50
* Now create a 50% discount on product 2
* Go to product page and tick the checkbox - price is $37.50

The customer has received a 50% discount on top of a 50% discount for the CPU.

I think it would be better if associated product prices were not subject to discounts on the main product. This way the store owner can separately create a discount on the associated product.

**Comment by DmitriyKulagin** [comment]
Hi, @kwerty 

After some discussion and analysis of the described situation, we came to the conclusion that this is not a bug. The discount is calculated according to the following principle: first, a discount is calculated for each attribute, the cost of all attributes (taking into account their discount) is added to the cost of the main product, and then the main product discount is applied to the entire product group.

To implement the model of calculation proposed by you, it is not necessary to resort to changing the source code. Other tools are provided for this - you just need to create a grouped product and apply the discount you need to it.

**Comment by kwerty** [comment]
Translation:
Hi @kwerty, we decided that this bug is a feature.
Totally normal to receive a double discount!

Let's go over this again..

Let's say I run an online electronics store
I have two separate listings for a motherboard and a CPU
To make it easier for the customer to bundle their purchase, I include a checkbox on the motherboard product listing, which is associated with the CPU
I'm running a promotion, which grants a 10% discount to all products in the "Computer parts" category
Customer goes to motherboard page, ticks CPU box, adds to cart
Customer has received a 20% discount on the CPU (when they should only receive a 10% discount)

Yeah, wonderful guys. Definitely a great feature.

**Comment by kwerty** [comment]
@DmitriyKulagin @AndreiMaz 
Please please please reconsider.
It's a super easy fix.
I'm not asking for this change for my benefit, because I already fixed it. I just want to help you guys make NopCommerce a better platform.
