### ISSUE TITLE
4.10 BETA - Feature Request

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3166]
nopCommerce version: 4.10 BETA

You may consider adding a comment to the web.config file above this line.
` <aspNetCore requestTimeout="23:00:00" processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%"  ....`

When deploying to Windows 2016 Server on Azure,  change the auto-generated processPath="dotnet" to 
processPath="C:\Program Files\dotnet\dotnet.exe" to make it work. 

If you don't do this, the user will get this message:

```
HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681
```
Note when running the app on the server directly from the command line, the cli doesn't use the web.config so the app will run. Driving you crazy to figure out. I went through 2 other hosting companies who didn't figure that out before I found the answer.

Hope this helps.

**Comment by DmitriyKulagin** [comment]
Closed #3166
