### ISSUE TITLE
Add "Select all" and "Delete all selected" in all grids

### ISSUE THREAD

**Issue by compito** [nopSolutions/nopCommerce#3169]
nopCommerce version: All?

Steps to reproduce the problem: Go to any grid/table page in admin where you want to delete all rows. Click on "Delete" once in every row and go mad after just one full page...

Seriously, shouldn't this be a part of all grid pages in admin? Possibly with a warning when "Delete all" button is clicked.

For example, I'd like to delete all language strings that were created by plugins, so I can export a clean language file before upgrade to 4.10. And there are 1561 rows to delete... There's an image attached, just in case I wasn't clear enough.
![screenshot-walfrid-001-site1 htempurl com-2018-07-18-15-35-02](https://user-images.githubusercontent.com/3284850/42886125-157e4140-8aa3-11e8-94f5-d4101a3c22b5.png)
.

**Comment by AndreiMaz** [comment]
after some investigation we decide not to implement it
