### ISSUE TITLE
4.10 BETA - "Add to cart" for variant seems confusing

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3170]
nopCommerce version: 4.10 BETA July 18th 1:00 PM EST

Steps to reproduce the problem: 

1. Install latest version to Windows Server 2016 / SQL Express 2017 on Azure VM
2. Register as a new customer. It then shows me as logged in as the customer.
3. Clicked the Electronics link above the photo
4. Clicked Camera & Photo link
5. Clicked blue "add to cart" button for the Nikon D5500 DSLR
     - Now it is showing the Nikon D5500 DSLR detail page (Nikon D5500 DSLR)
     - Shopping cart (0) is shown in top right corner 
     - Hover over the Shopping cart link in top right corner says no items in shopping cart

Most likely the issue is "Add to Cart" should say something else because there are variants of the camera colors to pick from. When I clicked on the Add to cart link for black color, it worked as expected.

**Comment by AndreiMaz** [comment]
It's by design. When you have two products (variants), then it redirects t o the product details page
