### ISSUE TITLE
Invalid column name 'PictureBinary' when importing from excel into Products

### ISSUE THREAD

**Issue by w-tbury** [nopSolutions/nopCommerce#3171]
nopCommerce version: 4.10 Beta 

Steps to reproduce the problem: 
Export a selection of products and make a few changes.
Import that excel back into Nop using the import feature.

Found issue in the PictureService class GetPictureHash(int[] pictureIds) method.  The SQL string references PictureBinary, but that looks like it was dropped and moved to it's own table.

**Comment by skoshelev** [comment]
@w-tbury Thank you for your help

Closed #3171
