### ISSUE TITLE
4.10 BETA - Feature Request

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3172]
nopCommerce version: 4.10 BETA

Please consider changing this method to return the inserted product's identity back to the caller in ProductService/IProductService. We need this for our API wrapper to return back the ID without a second call to the database to grab it.

void InsertProduct(Product product);

to 

int InsertProduct(Product product);

**Comment by AndreiMaz** [comment]
actually it's inside the "product" parameter

P.S. Please give descriptive issue names on github (not "feature request")

**Comment by VR-Architect** [comment]
Well I'll be, you are correct sir! 

BTW, love your product. And will drop the feature request label in the future.
