### ISSUE TITLE
Entity (Product, category, manufacturer, etc) seo name isn't changed based on language selection

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3174]
nopCommerce version:  beta 4.10

Steps to reproduce the problem: 

I added one language German.

After i edited Apple-Icam product name and seo name in German language

product name =  táo ICAM(German tab)
Seo name = vị-sôcôla-hiệu-new-york

Front side when i opened product detail  for English and German language .

Working fine for both  but **url seo** name is not changed based on language.

Also,i enabled seo friendly url.

**Comment by cnEUL** [comment]
Hello,
I tried to reproduce that with the current beta.
If I install German and save the descriptions in German, and change the SEO name to "Apfel", I get the correct translated link on the overview page and according to the language setting.

overview:
http://nop41.eulanda.eu/camera-photo

german: http://nop41.eulanda.eu/apfel-icam
english: http://nop41.eulanda.eu/apple-icam

**Comment by cnEUL** [comment]
oh, that's not funny. It looks like a bug :-)

**Comment by skoshelev** [comment]
Closed #3174
