### ISSUE TITLE
Cannot add "empty" order note (validation required)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3175]
nopCommerce version: beta 4.10

Steps to reproduce the problem: 

Edit order 3

Go through => order notes

click on **Add order note** without add  note.

It gives one alert like 'Failed to add order note.'

It throw exception like  **The property 'Id' on entity type 'OrderNote' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.**

After I checked at order note table.

I found that note field was not null.

To conclude,It should display message like **please enter note**.

**Comment by RuS984** [comment]
Closed #3175.
