### ISSUE TITLE
Category seo name isn't changed based on language selection

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3176]
nopCommerce version: beta 4.10

Steps to reproduce the problem: 

I added one language German.

After i edited computer category name and seo name in German language

category name = táo (German tab)
Seo name = vị-sôcôla

Front side when i opened category home page for English and German language .

Working fine for both but url seo name is not changed based on language.

Also,i enabled seo friendly url.

**Comment by AndreiMaz** [comment]
thanks. duplicated https://github.com/nopSolutions/nopCommerce/issues/3174
