### ISSUE TITLE
Manufacture seo name isn't changed based on language selection

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3177]
nopCommerce version:  beta 4.10

Steps to reproduce the problem: 

I added one language German.

After i edited Apple manufacture name and seo name in German language

manufacture name = táo (German tab)
Seo name = vị-hiệu-new-yor

Front side when i opened manufacture home page for English and German language .

Working fine for both but url seo name is not changed based on language.

Also,i enabled seo friendly url.

**Comment by AndreiMaz** [comment]
thanks. duplicated https://github.com/nopSolutions/nopCommerce/issues/3174
