### ISSUE TITLE
4.10 - displaydefaultfooteritemsettings.displayshippingandreturnsfooteritem

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3178]
nopCommerce version: 4.10 BETA

How do we hide the footer menu item called "Shipping & Returns"? I don't see a "displaydefaultfooteritemsettings.displayshippingandreturnsfooteritem" in the All Settings section.

Thanks for the help

**Comment by sk5202** [comment]
Hello,
This is topic page.

go  through http://admin-demo.nopcommerce.com/Admin/Topic/Edit/10

uncheck Include in footer (column 1)	or Include in footer (column 2)	

hope you will understand..!!

**Comment by VR-Architect** [comment]
Thanks sk5202. I see how it is set.

**Comment by AndreiMaz** [comment]
please also post all questions on our forums
