### ISSUE TITLE
Add ability to pay with Loyality Points

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3179]
nopCommerce version: 4.10 BETA

We are using nopCommerce for micro-transactions where the user pays with "credits". It looks like we can use the reward point system as our credit system. Could you please add the ability to pay for items in the shopping cart by using the reward points?

Additional related items:
- add ability to buy reward points via normal payment channels
- add ability to buy reward point gift cards via normal payment channels

We could build this as a module, but thought it would be a good add-on for the core solution.

**Comment by AndreiMaz** [comment]
duplicated work item
