### ISSUE TITLE
Message templates should use secured URL (if enabled)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3180]
See "RouteUrl" method of MessageTokenProvider. It always returns http (not https). We have to check "store.SecureUrl"  and use it

Source: https://www.nopcommerce.com/boards/t/54055/find-bugs-in-nopcommerce-410-beta-and-earn-10.aspx#209063

Please note that "SecureUrl" could be empty

**Comment by exileDev** [comment]
No longer relevant for 4.20 9af9056af80609d6b319718d9205ca84e9c00d80
