### ISSUE TITLE
Handle an exception on the plugin list page when no Internet access

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3182]
nopCommerce version: 4.10

 e.g. during development. or for example, when nopCommerce.com is not acessible

Forum source: https://www.nopcommerce.com/boards/t/54055/find-bugs-in-nopcommerce-410-beta-and-earn-10.aspx?p=2#209092

the same report https://github.com/nopSolutions/nopCommerce/issues/3252

**Comment by foxinstone** [comment]
But，Why  the problem(Can't open Plugins configuration page on admin area!) does not occur when debugging the source code by vs2017?  I mean, the two network connections on the situation is no different!
I've tested many times, When I run the project in vs2017, no error occurs on shows the list of plugins.

**Comment by foxinstone** [comment]
You are right, it's because network, My server access internet through VPN, My develop machine access internet directly, Even they use same router.
When I stop the VPN on server , everything is OK.

But believe me , When using VPN, I use a browser to test the Internet connection, it is good, Why nc4.1 feel bad network? Can use to configure the network connection method to avoid the problem? You know, this is a big problem...

**Comment by DmitriyKulagin** [comment]
Closed #3182

**Comment by NoFear23m** [comment]
Hello

I have a server on 1und1.de an it seems my provider is blocking the request to the marketplace.
In the 4.0 i have seen the local pluginlist but now in the 4.1 the local and the aviable plugins are on the same page and i get an error.
I have cloned the repository but if i copy the Nop.Web.dll after a releasebulid to the server the iis will not start. 
Has anyone a patched Nop.Web.dll for me or a description to fix this problem?

Thanks in advanced
Sascha

**Comment by Meberem** [comment]
Is there a hotfix or something we can use for 4.1? I am stuck using 1and1 as well and not being able to administer plugins is a bit of an issue to say the least

**Comment by sanju741** [comment]
I see NopCommerce has implemented DDOS protection and it is causing an issue on all of the application running with version 4.1
The request made to the feed manager is blocked by Cloudflare and neither of the store running with version 4.1 can access the plugin page.
