### ISSUE TITLE
Tax category cannot add or remove V.4.1

### ISSUE THREAD

**Issue by JonnyJST** [nopSolutions/nopCommerce#3184]
nopCommerce version: 4.1

Steps to reproduce the problem:
in version 4.0 you can add, remove or rename tax entries! that does not work anymore!

Menu->Configuration->Tax

**Comment by skoshelev** [comment]
@JonnyJST In my case all work fine, can you provide more details, which problem do you have, do you have any error in log?

**Comment by skoshelev** [comment]
Can not reproduce

Closed #3184
