### ISSUE TITLE
Add search by vendorId to SearchProducts & Product methods

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3185]
nopCommerce version: 4.10 BETA 

For security reasons, our API always searches for product by ProductID and VendorID. This is to ensure someone is not able to manipulate products for another vendor.

Please consider adding new method:
`_productService.GetProductByIdAndVendorId(int VendorId, int ProductId)`

And adding searchBy criteria to:
```
_productService.SearchProducts(
     vendorId: myVendorId,
);
```

**Comment by AndreiMaz** [comment]
Actually it exists in "SearchProducts" method

**Comment by AndreiMaz** [comment]
Furthermore, you can always load a product by ID and check its VendorId property

**Comment by VR-Architect** [comment]
Sorry Andrei,

I meant add ProductId to the SeachProducts method:

```
_productService.SearchProducts(
     vendorId: myVendorId,
     productId: myProductId
);
```

I a highly used site as we are expecting this to be, we would prefer not to have to make additional database calls. But for now, you are correct we can just check the vendorId.

Thanks again for consideration to add.
