### ISSUE TITLE
Store connection string in appsettings.json

### ISSUE THREAD

**Issue by rustybox** [nopSolutions/nopCommerce#3187]
Would it not be better to store connection string in appsettings.json to utilise the built in config transforming provided by IConfigurationBuilder and allow easy setup for multiple environments e.g. appsettings.QA.json, appsettings.UAT.json?

Alternatively perhaps DataSettingsManager -> DataSettingsFilePath could pulled out of appsettings.json so the datasettings.json could be swapped per environment.

**Comment by AndreiMaz** [comment]
we've thought about it. But as long as we know asp.net doesn't support editing (saving) of  appsettings.json now

**Comment by rustybox** [comment]
OK so installer has an impact gotya, how about the latter idea of pulling datasettings path from config file so the path could be switched per ENV?

**Comment by NathanNZ** [comment]
Only loading dataSettings.json as a fallback when not defined through the .NET Core settings loader would mean I could throw out some of my custom code to do this - has my vote 👍

**Comment by AndreiMaz** [comment]
after soem consideration we've decided to leave the current implementation

**Comment by NathanNZ** [comment]
Care to share your reasoning? I'm happy to implement the change if it's just low priority?

**Comment by lulzzz** [comment]
the way settings are done make it hard to do ci/cd and password rotation.
