### ISSUE TITLE
Plugin Loader Architecture

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#3189]
I suggest you review this technology for plugin loader architecture.
https://natemcmaster.com/blog/2018/07/25/netcore-plugins/
https://github.com/natemcmaster/DotNetCorePlugins

**Comment by AndreiMaz** [comment]
thanks. we'll check the links and decided whether it can be useful

**Comment by skoshelev** [comment]
We investigated this way to organize plugin system. In our case it not useful, when using it, we will have to load a large number of assemblies for each plug-in into memory. We also believe that our plugin system works well and also we are in the process of upgrading it.

Closed #3189
