### ISSUE TITLE
Cannot add (edit) a blog post

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3191]
nopCommerce version: 

Steps to reproduce the problem: 

Steps to Reproduce:

1. Create a new blog with only title and body 

2. Save and continue edit / create another new blog

Object reference not set to an instance of an object.Nop.Services.Blogs.BlogService.ParseTags

Source: https://www.nopcommerce.com/boards/t/54055/find-bugs-in-nopcommerce-410-beta-and-earn-10.aspx?p=3#209359

**Comment by RuS984** [comment]
Closed #3191
