### ISSUE TITLE
non-ASCII chars in URL don't work

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3192]
nopCommerce version: 4.10

the issue again was fixed recently (https://github.com/nopSolutions/nopCommerce/issues/2731). But it again appeared in 4.10  as per 
See  https://www.nopcommerce.com/boards/t/52224/nopcommerce-410-bug-fixes-and-improvements.aspx?p=5#209419

 For some reasons \Nop.Web.Framework\Mvc\Routing\NopRedirectResultExecutor.cs is not used

**Comment by tietaren** [comment]
Uri uri = new Uri("http://some-domain/façade-non-ASCII"); 
return Redirect(uri.AbsoluteUri);

**Comment by tietaren** [comment]
I just tested and it seems works well, what I did is modify the LocalizedRoute.cs in Localization directory under Nop.Web.Framework project:
add references for WebUtility.UrlEncode by adding: using System.Net;
then modify one line as below:

 public override VirtualPathData GetVirtualPath(VirtualPathContext context)
        {
            //get base virtual path
            var data = base.GetVirtualPath(context);
            if (data == null)
                return null;

            if (!DataSettingsManager.DatabaseIsInstalled || !SeoFriendlyUrlsForLanguagesEnabled)
                return data;

            //add language code to page URL in case if it's localized URL
            var path = context.HttpContext.Request.Path.Value;
            if (path.IsLocalizedUrl(context.HttpContext.Request.PathBase, false, out Language language))
                data.VirtualPath = WebUtility.UrlEncode("/{language.UniqueSeoCode}{data.VirtualPath}");
            //data.VirtualPath = $"/{language.UniqueSeoCode}{data.VirtualPath}";

            return data;
        }

**Comment by skoshelev** [comment]
Closed #3192

**Comment by DmitriyKulagin** [comment]
Closed #3192
