### ISSUE TITLE
Plugin "Warnings" won't go away

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3195]
nopCommerce version: 4.10

Steps to reproduce the problem: I upgraded to 4.10 from 4.00 and I had plugins like 'Shipping.FixedOrByWeight' and 'Payments.PayPalDirect', but they weren't in my "Plugin" list to remove them. So I removed them from the installedPlugins.json. I "cleared cache", "restarted application" and even rebooted my VPS. But yet the warning is still there. I can't get rid of them...thoughts?

![image](https://user-images.githubusercontent.com/20989983/43318955-e59e29b6-9170-11e8-8e47-2078b0d953cc.png)

**Comment by skoshelev** [comment]
@Ochapparel You should manually remove these plugins from Nop.Web/Plugins directory

Closed #3195

**Comment by Ochapparel** [comment]
Yep. That fixed it :)
