### ISSUE TITLE
Plugin Official Feed Default Search Filter Is Previous Version

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3197]
nopCommerce version: 4.10

Plugin official feed page should default search filter version to '4.10' - currently the default filter version is '4.00'

Steps to reproduce the problem: 
1. Navigate to /Admin/Plugin/OfficialFeed
2. Note default version search filter is 4.00 - expected current version: 4.10

**Comment by AndreiMaz** [comment]
It preselect the current version. It works fine. 4.10 is selected if you use 4.10

**Comment by toddca** [comment]
I deployed a clean/new 4.10 version and 4.00 was pre-selected NOT 4.10 as would be expected.
