### ISSUE TITLE
Move widget zones to PublicWidgetZones class

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3199]
web -> catalog -> serach.cshtml -> widgetZone = "productsearch_page_basic"
                            widgetZone = "productsearch_page_advanced"

admin -> VendorAttribute all createandupdate pages
etc

Source: https://www.nopcommerce.com/boards/t/54055/find-bugs-in-nopcommerce-410-beta-and-earn-10.aspx?p=3#209492

**Comment by RuS984** [comment]
Close #3199
