### ISSUE TITLE
Price range filter labels for category do not change to the respective valuation with change of currency 

### ISSUE THREAD

**Issue by biswarupkundu1990** [nopSolutions/nopCommerce#3200]
nopCommerce version: 4.10

Steps to reproduce the problem: 
step 1 - Go to currency and activate any currency other than US dollar and Euro(both of them comes activated out of the box). I have activated Indian Rupee  with exchange rate of 68.03 with respect to US dollar which is primary currency with exchange rate 1.

Now as per logic if Indian Rupee currency is selected then price range should also show in Indian Rupee standard. For example in category - http://yourstoreURL/camera-photo - we have "under $500, over $500" price raneg  in US currency .

Now if I select Indian currency , then it should show me "under 34015,over 34015" in indian rupee conversion. (currency rate 68.05 * 500). I could not place Indian currency notation before the values, but you can in understand what i want to say. I think this needs to be rectified.

**Comment by AndreiMaz** [comment]
we'll do it part of https://github.com/nopSolutions/nopCommerce/issues/276
