### ISSUE TITLE
Website down after editing the product Build your own computer NOP 4.1

### ISSUE THREAD

**Issue by petrjiricek** [nopSolutions/nopCommerce#3201]
nopCommerce version: 4.1

Steps to reproduce the problem: 
When I have editing sample product "Build your own computer" and at attribute I picked picture to each choice ... Processor (sample data) and saved this page then the website go down and log message is:

-- | -- | -- | --
◢ | $exception | {System.InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context.    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()    at System.Linq.Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)    at Nop.Services.Orders.CheckoutAttributeService.<>c__DisplayClass7_0.<GetAllCheckoutAttributes>b__0() in c:\NOP41\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 77    at Nop.Core.Caching.PerRequestCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in c:\NOP41\Libraries\Nop.Core\Caching\PerRequestCacheManager.cs:line 62    at Nop.Services.Orders.CheckoutAttributeService.GetAllCheckoutAttributes(Int32 storeId, Boolean excludeShippableAttributes) in c:\NOP41\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 75    at Nop.Web.Factories.ShoppingCartModelFactory.<>c__DisplayClass53_0.<PrepareMiniShoppingCartModel>b__2() in c:\NOP41\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 986    at Nop.Core.Caching.MemoryCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in c:\NOP41\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 152    at Nop.Web.Factories.ShoppingCartModelFactory.PrepareMiniShoppingCartModel() in c:\NOP41\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 983    at Nop.Web.Components.FlyoutShoppingCartViewComponent.Invoke() in c:\NOP41\Presentation\Nop.Web\Components\FlyoutShoppingCart.cs:line 32    at lambda_method(Closure , Object , Object[] )    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)    at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)} | System.InvalidOperationException

**Comment by AndreiMaz** [comment]
@petrjiricek can you reproduce it on our demo site?

**Comment by QuanNH88** [comment]
I also encounter the same error when building a new Plugin for Nopcommerce 4.1
How did you handle it?

Error: Cannot create a DbSet for 'GoogleAcceleratedMobileItem' because this type is not included in the model for the context.

**Comment by zwierzyna-prosystem** [comment]
I have similar problem, i have finished installation of nopCommerce 4.10., then created sample product which I put into my shopping cart → _"Failed to add the product. Please refresh the page and try one more time."_. Then after page refresh → _"InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context."_ on every page in public area. The error can be suppressed only manualy by deleting **shoping cart item** using SQL.
