### ISSUE TITLE
Missing translation - Shopping cart type

### ISSUE THREAD

**Issue by JonnyJST** [nopSolutions/nopCommerce#3202]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Edit customer details ->Current Shopping cart-> Shopping cart type / the translation of the combobox is missing

**Comment by cnEUL** [comment]
Hello,
i have looked under this, but the combobox is translateable. Or do you looked at another part?
![cart41](https://user-images.githubusercontent.com/37210350/43392933-894c62ea-93f5-11e8-9af7-0a276bf721cc.png)

**Comment by AndreiMaz** [comment]
I presume you're using BETA. It was fixed in 4.10 RTM
