### ISSUE TITLE
NUnit3 adding to source control issue

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3203]
nopCommerce version: 4.1
Visual Studio 15.7.5

Steps to reproduce the problem: 
-Create new project in Visual Studio Team Services 
-Set your Mappings
-Download Nopcommerce - Unblock - Extract Rar
-Open solution
-Add solution to source control

Errors in order
1- The item 'NUnit3.TestAdapter.pdb' cannot be added to source control because the item has no source control mapping.  If you choose one of the Ignore options the operation will continue without adding the file.

2- The item 'NUnit3.TestAdapter.dll' cannot be added to source control because the item has no source control mapping.  If you choose one of the Ignore options the operation will continue without adding the file.

3- The item 'nunit.engine.netstandard.dll' cannot be added to source control because the item has no source control mapping.  If you choose one of the Ignore options the operation will continue without adding the file.

4- The item 'Mono.Cecil.dll' cannot be added to source control because the item has no source control mapping.  If you choose one of the Ignore options the operation will continue without adding the file.

**Comment by AndreiMaz** [comment]
What source control do you use?

**Comment by bulutkartal** [comment]
Regular 4.10 source from NopCommerce website with VS 2017

**Comment by AndreiMaz** [comment]
What source control system? github? something else?

**Comment by bulutkartal** [comment]
Visual Studio Team Services, Online ;
Project with Team Foundation Version Control - Agile work item process.

and I add directly from vs to Tfs

**Comment by skoshelev** [comment]
Closed #3203
