### ISSUE TITLE
Popular tags font size: standard deviation won't be negative

### ISSUE THREAD

**Issue by JohnsonJohnsonYuan** [nopSolutions/nopCommerce#3204]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Is _columnsTwo.cshtml, the left side bar contains popular tags.
src/Presentation/Nop.Web/Models/Blogs/BlogPostTagListModel.cs

standard deviation  is always positive, I think it's not necessary to check standard deviation is negative:
In GetFontSize method:
```c#
return (factor > 2) ? 150 :
                (factor > 1) ? 120 :
                (factor > 0.5) ? 100 :
                (factor > -0.5) ? 90 :
                (factor > -1) ? 85 :
                (factor > -2) ? 80 :
                75;
```

**Comment by AndreiMaz** [comment]
@JohnsonJohnsonYuan why not? font size should be positive
