### ISSUE TITLE
PickupInStore Plugin Country area displayed twice

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3209]
nopCommerce version: 4.1

Steps to reproduce the problem: 
When you try to add a new pick up point, it provides a dropdown list and text field as well.

**Comment by DmitriyKulagin** [comment]
@bulutkartal Can you provide a screenshot of the problem? The error is not reproduced.

**Comment by bulutkartal** [comment]
There is no error. Country field is displayed twice.

**Comment by AndreiMaz** [comment]
The second one is not country. It's county

We'll display these fields according to address fields

**Comment by DmitriyKulagin** [comment]
Closed #3209
