### ISSUE TITLE
SEO Message is wrong in 4.10 "Entered page name already exist..."

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3210]
nopCommerce version: 4.10

Steps to reproduce the problem: 
Type on the SEO tab in porduct page some words. The resource "Language.Admin.System.Warnings.URL.Reserved.Value" with text "Entered page name already exists, so it will be replaced by '{0}'" is shown under the slug field.

In my opinion three solutions for that:
1. Change text like "The entred text exists or is not slug conform and changed in {0}"
or
2. Show the Message only if the SEO Title already exists
or
3. Make two Messages One for existing one, another for not conform slug.

I have seen, that the message is used in all SEO-Names, so the Text could be changed more general like:
"The name is not conform or double. It is corrected in '{0}'"
As a first fix, i changed it in the german translation like: "Der Name ist nicht konform oder doppelt. Er wird korrigiert in '{0}'"

Chris

**Comment by AndreiMaz** [comment]
Chris. could you please clarify. What exactly is wrong with this message? Not sure that I understand

**Comment by AndreiMaz** [comment]
Chris, please provide a list of steps to reproduce it at http://admin-demo.nopcommerce.com/admin/

When I type something unique, nothing appears

**Comment by cnEUL** [comment]
if i enter in the slug field something with blanks it tells the same warning, as if its a already existing slug.
But in this case, it is only a correction of the entered text. So we need a more general text for the warning, or otherwise no warning on only corrections (and warnung only if the slug value already exists). 
i prefer only a more general text, which tells that its something to correct (slug-conform) or is just existing. But also the text "Pagename " is for me not the best value, because its a slug (means in this case only the link). So for the user all is much clearer.

![slug](https://user-images.githubusercontent.com/37210350/43685781-a0ee3f68-98b9-11e8-993b-1a5a95206c31.jpg)
