### ISSUE TITLE
Shipping address if customer already exists

### ISSUE THREAD

**Issue by networkfusion** [nopSolutions/nopCommerce#3211]
nopCommerce version: 4.0

Steps to reproduce the problem: 

If you disable a country of state after a customer has already created an address they seem to be able to create an order based on that address even if it has been disabled. E.g. if an shop only accepts online orders for the mainland uk with all other parts of the world being telephone orders only so shipping is calculated correctly, they are still able to order if they created an account prior to disabling states (and possibly countries)

**Comment by AndreiMaz** [comment]
Please check out the latest version. We have appropriate validation in CheckoutModelFactory
