### ISSUE TITLE
UrlRecord not unique (sample data during installation)

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3212]
nopCommerce version: 4.10

Steps to reproduce the problem: 

There is a problem with UrlRecord. If I enter in sql management studio:

"select count(*), Slug from urlrecord group by Slug, LanguageId order by 1" 

for the demo database, I get a sorted list and at the end are a lot of duplicate entries.

Maybe I didn't understand everything very well, but overall only one identical slug-entry per language is allowed.
![urlrecord](https://user-images.githubusercontent.com/37210350/43687986-ea070492-98e0-11e8-950c-6096465f0892.jpg)

But there are 10x "apparel", where one EntityName='Category', the remaining 9 are from the category'ProductTag'.

There seems to be a problem here, on the one hand these ProductTag were created several times, on the other hand there is an overlap with Category.

**Comment by AndreiMaz** [comment]
@cnEUL Chris, thanks! You're right. It happens only during installation. We don't make appropriate validation in the https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs when invoking "urlRecordRepository.Insert". Introduced in the following commit - https://github.com/nopSolutions/nopCommerce/commit/c15db321ce3c37da93fd1079c07baf49ea5125a9#diff-79654c498769b4fd737ae0778c5d1b8b

**Comment by cnEUL** [comment]
ok. so in the table it should be:
9 Category apparel
10 ProductTag apparel-2

So apparel should only be in there one time, right?

**Comment by RuS984** [comment]
Closed #3212
