### ISSUE TITLE
Public area not working after inserting the product into the cart

### ISSUE THREAD

**Issue by zwierzyna-prosystem** [nopSolutions/nopCommerce#3213]
Hi everyone,
i wanted to start the transition to the new version of nopCommerce, but after creating sample product and inserting it into the cart an error occurs:

nopCommerce version: **4.10**
SQL Server: **2017 Express**

**Steps to reproduce the problem (after clean instalation):**

1. Create sample product (only name, price and picture)
2. Add this product to cart
3. Javascript message box will be displayed - _"Failed to add the product. Please refresh the page and try one more time."_
4. Every page refresh in public area returns exception - _"InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context."_
5. The only solution is to remove shopping cart item manualy using SQL query

**Call stack:**

`System.AggregateException: One or more errors occurred. (Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context.) ---> System.InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context.     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()     at System.Linq.Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)     at Nop.Services.Orders.CheckoutAttributeService.<>c__DisplayClass7_0.<GetAllCheckoutAttributes>b__0() in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 77     at Nop.Core.Caching.PerRequestCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Caching\PerRequestCacheManager.cs:line 62     at Nop.Services.Orders.CheckoutAttributeService.GetAllCheckoutAttributes(Int32 storeId, Boolean excludeShippableAttributes) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 75     at Nop.Web.Factories.ShoppingCartModelFactory.<>c__DisplayClass53_0.<PrepareMiniShoppingCartModel>b__2() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 986     at Nop.Core.Caching.MemoryCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 152     at Nop.Web.Factories.ShoppingCartModelFactory.PrepareMiniShoppingCartModel() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 983     at Nop.Web.Components.FlyoutShoppingCartViewComponent.Invoke() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Components\FlyoutShoppingCart.cs:line 32     at lambda_method(Closure , Object , Object[] )     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)     at StackExchange.Profiling.Internal.ProfilingViewComponentInvoker.InvokeAsync(ViewComponentContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore.Mvc\Internal\ProfilingViewComponentInvoker.cs:line 30     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)     --- End of inner exception stack trace ---     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)     at Nop.Web.Framework.Controllers.BaseController.RenderViewComponentToString(String componentName, Object arguments) in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web.Framework\Controllers\BaseController.cs:line 94     at Nop.Web.Controllers.ShoppingCartController.GetProductToCartDetails(List`1 addToCartWarnings, ShoppingCartType cartType, Product product) in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Controllers\ShoppingCartController.cs:line 610     at Nop.Web.Controllers.ShoppingCartController.AddProductToCart_Details(Int32 productId, Int32 shoppingCartTypeId, IFormCollection form) in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Controllers\ShoppingCartController.cs:line 936     at lambda_method(Closure , Object , Object[] )     at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)     at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()     at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()     at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)     at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()     at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()     at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)     at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()     at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()     at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)     at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94     at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 79     at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Nop.Core.Http.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Http\InstallUrlMiddleware.cs:line 51     at Nop.Core.Http.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Http\KeepAliveMiddleware.cs:line 50     at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)  ---> (Inner Exception #0) System.InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context.     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()     at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()     at System.Linq.Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)     at Nop.Services.Orders.CheckoutAttributeService.<>c__DisplayClass7_0.<GetAllCheckoutAttributes>b__0() in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 77     at Nop.Core.Caching.PerRequestCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Caching\PerRequestCacheManager.cs:line 62     at Nop.Services.Orders.CheckoutAttributeService.GetAllCheckoutAttributes(Int32 storeId, Boolean excludeShippableAttributes) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Services\Orders\CheckoutAttributeService.cs:line 75     at Nop.Web.Factories.ShoppingCartModelFactory.<>c__DisplayClass53_0.<PrepareMiniShoppingCartModel>b__2() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 986     at Nop.Core.Caching.MemoryCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in C:\NopCommerce\nopCommerce_4.10_Source\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 152     at Nop.Web.Factories.ShoppingCartModelFactory.PrepareMiniShoppingCartModel() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 983     at Nop.Web.Components.FlyoutShoppingCartViewComponent.Invoke() in C:\NopCommerce\nopCommerce_4.10_Source\Presentation\Nop.Web\Components\FlyoutShoppingCart.cs:line 32     at lambda_method(Closure , Object , Object[] )     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)     at StackExchange.Profiling.Internal.ProfilingViewComponentInvoker.InvokeAsync(ViewComponentContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore.Mvc\Internal\ProfilingViewComponentInvoker.cs:line 30     at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)<---  `

**Comment by AndreiMaz** [comment]
similar issue - https://github.com/nopSolutions/nopCommerce/issues/3201

**Comment by AndreiMaz** [comment]
we cannot reproduce it

**Comment by martinbacik** [comment]
Andrei. It is the same issue as in https://github.com/nopSolutions/nopCommerce/issues/3321
The problem was identified with entity framework and its culture-sensitive behavior.
https://github.com/aspnet/EntityFrameworkCore/issues/12617

Steps to reproduce:
1. Install nopcommerce
2. Add secondary language Slovakia for instance with /sk SEO suffix
3. Make sure you choose Language culture "sk-Sk"
4. Go to the frontend elglish version (http://localhost/en)
5. Put something to your basket
6. Switch the language to Slovak
7. Error "Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context"

Quick fix by @zwierzyna-prosystem 
1. Open ServiceCollectionExtensions.cs
2. add  System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");
before TaskManager.Instance.Initialize(); on line 66
