### ISSUE TITLE
Performance (memory) problems

### ISSUE THREAD

**Issue by sharpapp-mareklanduch** [nopSolutions/nopCommerce#3220]
nopCommerce version: 4.10 (.net core 2.1)

Steps to reproduce the problem: 
1. webio.pl - hosting on which my previous nopCommerce were working just fine
2. I have installedNoSource and later tried with NoSourceContained binaries
3. I have installed nopCommerce without sample data

NopCommerce is really slow, every page is loading for about 10-15 seconds. Webio.pl hosting has this site errors logs where there are such entries
"A worker process serving application pool 'store.sharpapp.net v4.0 (Integrated)' has requested a recycle because it reached its private bytes memory limit.
"The store.sharpapp.net application exceeded the limit of allowed volume in the server's memory and was restarted"

Like I said with previous versions of nopcommers everything was just great.

**Comment by KrzysztofPajak** [comment]
Hi,
Nopcommerce in version 4.1 need minimum 600-800MB RAM for application pool, it's caused by NET .CORE
Previous versions needed's 200-300MB RAM

**Comment by sharpapp-mareklanduch** [comment]
😢 I guess we can close this ticket.
