### ISSUE TITLE
CultureInfo for number is not working with nopCommerce for hi-IN culture

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3222]
nopCommerce version: 4.0 & 4.1

Steps to reproduce the problem: 
Use below code for get NativeDigits cultureInfo wise.

it's return English numbers instead of Hindi number.
check here: 

![cultureinfo](https://user-images.githubusercontent.com/13154058/43841889-c79b0d00-9b41-11e8-9daa-583d0923ffb8.png)

Here is code snippet:

```
var hindiCulture = new CultureInfo("hi-HI");          
            Console.WriteLine(string.Join("", hindiCulture.NumberFormat.NativeDigits));
```

and check output for numbers.

check [here on dotnetfiddler](https://dotnetfiddle.net/d5oSSa) it's working fine.

also review [this stackoverflow post](https://stackoverflow.com/questions/51745870/get-language-wise-numbers-using-culture-info-in-c-sharp/) for more detail

**Comment by AndreiMaz** [comment]
@rajupaladiya What does your code do? Please provide a list of steps to reproduce an issue in nopCommerce. What exactly is "functionality" problem?

**Comment by RuS984** [comment]
Displaying native digits is part of Windows functionality. To use native digits you need to install hindi language pack.
