### ISSUE TITLE
Official Feed Manager exception handling

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3223]
nopCommerce version: 4.1

Steps to reproduce the problem: 
`using (var response = request.GetResponse())
            {
                using (var dataStream = response.GetResponseStream())
                using (var reader = new StreamReader(dataStream))
                {
                    var responseFromServer = reader.ReadToEnd();

                    var xmlDoc = new XmlDocument();
                    xmlDoc.LoadXml(responseFromServer);
                    return xmlDoc;
                }
            }`

How abt using in try block? if it doesn't get response there is no option for handling exception

**Comment by bulutkartal** [comment]
The reason I opened this, we were using [bitdefender ](https://www.bitdefender.com/) on one of our servers and somehow it blocked nopcommerce response and cause break in the application.

**Comment by AndreiMaz** [comment]
duplicated.
