### ISSUE TITLE
Ordering with price ascending/descending

### ISSUE THREAD

**Issue by fsefacan** [nopSolutions/nopCommerce#3224]
nopCommerce version: 

Steps to reproduce the problem: 
1. Create a category
2. Create more than one product
3. Create discount applied to category(example 20% discount)
4. Go to catalog/category page and order by price asc or desc.

And you will see that prices are sorted according to fixed prices rather than discounted prices.

**Comment by fatiheker** [comment]
What is "catalogsettings.ignorediscounts" settings value?

**Comment by fsefacan** [comment]
Ofcourse in the case of false. because I am actively using category discounts.

**Comment by AndreiMaz** [comment]
thx. duplicated - https://github.com/nopSolutions/nopCommerce/issues/2078
