### ISSUE TITLE
Products cacheManager lifetime is per request

### ISSUE THREAD

**Issue by pantonis** [nopSolutions/nopCommerce#3225]
nopCommerce version: 4.1.0

Steps to reproduce the problem: 
I am debugging the code and I can see in ```ProductService``` method ```public virtual Product GetProductById(int productId)``` everytime I open detail view of a specific product this product is not in the cache but everytime it uses ```_productRepository.GetById(productId)``` to get it from database.

I don't understand the purpose of this cache. It should be a singleton there and cache should be shared across all requests.

**Comment by AndreiMaz** [comment]
it's a per HTTP request cache. EF doesn't support 2-level caching
