### ISSUE TITLE
Don't allow to save empty download object (product details page)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3226]
I think it shouldn't be possible to save empty url object. If somebody save changes, then change to "Upload a file" view and click the "Download uploaded file" button, he will get internal error. Maybe it will be better to validate if that field is empty or not?

Steps:
1. Open product
2. Go to Downloadable product
3. Change to "Use download URL"
4. Save empty record
5. Save changes in product
6. Go back to Downloadable product section, change back to "Upload file"
7. Click the "Download uploaded file" button

Source: https://www.nopcommerce.com/boards/t/54967/possibility-to-save-empty-download-object.aspx

**Comment by DmitriyKulagin** [comment]
Closed #3226
