### ISSUE TITLE
Default page title-Multilingual

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3229]
General settings>>SEO>>Default page title not support Multi Language

**Comment by cnEUL** [comment]
That's a very good thing. I look forward to it now, when it is approved. Overall, version 4.20 would look very good with more SEO options.

**Comment by AndreiMaz** [comment]
Thanks, Tigran. But duplicated - https://github.com/nopSolutions/nopCommerce/issues/43
