### ISSUE TITLE
Do not allow to assign "Vendor" and "Administrator" roles to a customer 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3232]
nopCommerce version: 4.10

Steps to reproduce the problem: We encountered a bug in nopCommerce 4.10. By default in nopCommerce you cannot assign Vendor and Administrator roles to a customer but in 4.10 when I edit admin user and assign vendor role to it and then save, it saves successfully. But after this, it does not let me go inside admin part in nopCommerce.. I had to go to database and remove vendor role association from admin user and then login again..

Source: https://www.nopcommerce.com/boards/t/52224/nopcommerce-410-bug-fixes-and-improvements.aspx?p=6#210410

The issue is that how we implemented new navigation properties in 4.10. We invoke "customer.IsVendor()" and "customer.IsAdmin()" methods but actually "CustomerCustomerRoleMappings" property is not syncronized with "CustomerRoles" ones (cached). We jsut have to reset "_customerRoles" variable when we update "CustomerCustomerRoleMappings" property

**Comment by RuS984** [comment]
Close #3232

**Comment by RuS984** [comment]
Close #3232
