### ISSUE TITLE
Memory usage and Garbage Collectors

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3233]
nopCommerce version: 4.10

All details at https://www.nopcommerce.com/boards/t/54986/nopcommerce-410-high-memory-usage-and-how-weve-handled-it.aspx

**Comment by skoshelev** [comment]
Closed #3233 (https://github.com/nopSolutions/nopCommerce/commit/1d58d0c6ebfc74fa87f37deab223d22fd6203f1f)
