### ISSUE TITLE
Do not store "clean" passwords for external authentication systems

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3235]
We've found a problem with Facebook External Authentication. If somebody use it to login in the store, nopCommerce will create explicit password, which is a combination of numbers. We think it should be done in a safer way. For example, encrypted like a normal password.

Source: https://www.nopcommerce.com/boards/t/55007/facebook-external-authentication-password-problem.aspx

**Comment by DmitriyKulagin** [comment]
Closed #3235
