### ISSUE TITLE
Proper sitemap.xml

### ISSUE THREAD

**Issue by demckee** [nopSolutions/nopCommerce#3236]
There seems to be some confusion as to what belongs in a sitemap.xml file, and how it relates to the sitemap page.

A url should be in the sitemap.xml file if is is a good page for a someone like google to return in response to a search. So, pages like blog posts, product pages and topic pages are high on this list. Index pages like a category page, product tag list etc are less useful here. Other pages like the contact us page shouldn't really be included in the sitemap.xml file, as they're not a good result for a search engine to return.

The sitemap page has no relationship to the sitemap.xml file. The sitemap page is for customers to find pages on your site. The sitemap.xml file is for search engines to know what pages are useful and which are not. Two different purposes.

So, two changes are needed and long overdue. First, which urls are included in the sitemap.xml file should not be controlled in any way by the same settings as the sitemap page. Most people don't want products on the sitemap page, but they should be included in the sitemap.xml. file.

Second change I've asked for multiple times: put the blog posts into the sitemap.xml file. I've been asking since 3.20 and it's still not done.

**Comment by cnEUL** [comment]
For multi language sites like ours also the hreflang tag is important and there is a spacial sitemap also for this. So for me also this woulb be good to be covered in a second xml sitemap. because it differs from the normal sitemap.xml.

  <url>
    <loc>https://www.eulanda.eu/en/packages-of-options-3</loc>
    <xhtml:link rel="alternate" hreflang="de" href="https://www.eulanda.eu/de/ausstattungspakete-3" />
    <xhtml:link rel="alternate" hreflang="en" href="https://www.eulanda.eu/en/packages-of-options-3" />
    <xhtml:link rel="alternate" hreflang="it" href="https://www.eulanda.eu/it/pacchetti-di-prodotti" />
  </url>

**Comment by DmitriyKulagin** [comment]
Closed #3236
