### ISSUE TITLE
Editing of attribute combinations doesn't properly pre-set values

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3237]
Steps to reproduce it, on your demo page:
1. Open product - "adidas Consortium Campus 80s Running Shoes"
2. Go to Product Attributes -> Attribute combinations 
3. Generate all possible combinations
4. Look at the, i.e - Size 9 / Color: Blue. Click the "Edit" button
5. You will see Size: 8 and Color Red. In the most cases, in nopCommerce after pressing the Edit button, you see the current values, not the default/first one.

Source: https://www.nopcommerce.com/boards/t/55020/attributes-combination-edit-window.aspx

**Comment by DmitriyKulagin** [comment]
Closed #3237
