### ISSUE TITLE
Www- and Https requirement functionality should not be active when running on localhost

### ISSUE THREAD

**Issue by kwestground** [nopSolutions/nopCommerce#3239]
If you are running against an production (or copy or production) database for debugging, Www and Https requirement functionality should not be active when running from and localhost site.

**Comment by cnEUL** [comment]
Good idea, when I forgot it, I have to disable it on sql level. And it occurs often...

**Comment by AndreiMaz** [comment]
Why https could not be enabled? IIS express supports it

**Comment by kwestground** [comment]
@AndreiMaz If you have an store url, the localhost site will redirect to the production site.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
