### ISSUE TITLE
MemoryCacheManager OutOfMemoryException

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#3242]
We are using MemoryCacheManager for  our own internal caching.

When approaching the maximum memory of the machine the cache manager throws an OutOfMemoryException.

Is there anyway to detect this and purge the oldest entries instead of throwing an exception?

We could keep track of memory usage ourselves, but I want to know if this is something that can be built in.

**Comment by Xzelsius** [comment]
See MemoryCacheOptions.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheoptions?view=aspnetcore-2.1

**Comment by rolandh** [comment]
It appears MemoryCache is broken according to this SO post
https://stackoverflow.com/questions/6895956/memorycache-does-not-obey-memory-limits-in-configuration

Someone has written a new cache here that won't crash the runtime when memory gets near the limit
https://github.com/haneytron/sharpmemorycache

Can I override the nop cache using this without changing the nop source code?

**Comment by Xzelsius** [comment]
Did you check how old your SO post is ?
You sure .net core is affected by the same?

@override: you can simply override the dependency and thus replace the default memory cache

**Comment by rolandh** [comment]
Perhaps not however I still get outofmemoryexception when filling this cache. What is the solution?

**Comment by Xzelsius** [comment]
Either I get you wrong or I cannot reproduce this.

Take a look at https://gist.github.com/Xzelsius/bb23217daa05eb9604a9f53705225aa2

That code creates around 10GB of cache entries. You can play around and go as high as you want.
I never got a OutOfMemory exception. My development machine has around 16GB of RAM and the MemoryCache managed to keep ~50GB of cache entries (according to Visual Studio).

![image](https://user-images.githubusercontent.com/17022099/45031392-02c26780-b04f-11e8-8ba1-203dd29841f3.png)

**Comment by AndreiMaz** [comment]
I also cannot reproduce it

**Comment by rolandh** [comment]
Thanks for taking the time to do this. I tried adding your code to our nopcommerce plugin and executing it on localhost. I also cannot reproduce it. I will test again on our azure server and see if I can get it to happen.

Thanks
