### ISSUE TITLE
Facebook login doen't work

### ISSUE THREAD

**Issue by zy-zero** [nopSolutions/nopCommerce#3243]
nopCommerce version: 4.1

Steps to reproduce the problem: 
I get a Facebook develop account, and then I setting the appid and appsecret.
I input them in the facebook login plugin, but I con't login with facebook.
I get a error message like this:
![image](https://user-images.githubusercontent.com/23359848/44334563-776ca200-a4a4-11e8-93da-53d0fb0ceb19.png)
It looks like I will request the facebook url with the code to get a access_token, yes or no?

**Comment by AndreiMaz** [comment]
I cannot reproduce it. It works fine

**Comment by jonquickqsense** [comment]
I've configured today for the first time on 4.1. Worked first time for me. I presume your oAuth callback url on FB app, is configured exactly to match https://<YourStoreUrl>/signin-facebook

J

**Comment by zy-zero** [comment]
So I should match the callback 'https://mystore/signin-facebook'  instead of 'https://mystore/FacebookAuthentication/LoginCallback/' ?
