### ISSUE TITLE
CSS issue with up/down buttons (IE Edge +Firefox)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3245]
Source: https://www.nopcommerce.com/boards/t/55132/updown-buttons.aspx

![screenshot-admin-demo nopcommerce com-2018-08-22-11-11-17](https://user-images.githubusercontent.com/5019111/44531173-c4e14d00-a6f8-11e8-94f0-89c058970fae.png)

**Comment by alessandromontividiu03** [comment]
fixed here (pull request)
https://github.com/nopSolutions/nopCommerce/pull/3322

**Comment by DmitriyKulagin** [comment]
Closed #3245
