### ISSUE TITLE
Import Product Picture URL Support- Not working

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3247]
picture with URL not importing.
Example file
[products.xlsx](https://github.com/nopSolutions/nopCommerce/files/2316215/products.xlsx)

**Comment by PatrykPorabik** [comment]
@tigran-avdalyan Did you mark the "Export/Import products. Allow download images" checkbox in Catalog Settings?

**Comment by tigran-avdalyan** [comment]
@PatrykPorabik Thanks
@AndreiMaz @skoshelev All works fine, i try on local version.
problem connected with CloudFlare.
