### ISSUE TITLE
Move "shoppingcartsettings.grouptierpricesfordistinctshoppingcartitems" to settings

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3249]
Source: https://www.nopcommerce.com/boards/t/55160/displaying-and-documenting-hidden-settings.aspx and https://www.nopcommerce.com/boards/t/55124/tiered-pricing-on-overall-quantity.aspx#210913

**Comment by LubovKhokhlova** [comment]
Resolved
