### ISSUE TITLE
Non English chars are not properly encoded after adding reward points in admin area

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3251]
1. Rename "admin.customers.customers.somecomment" to a new value (e.g. "ваш комментарий"
2. Go to a customer details page in admin area > reward points tab
3. Add a new record
4. See how "Comment" textbox is changed

![c0eff3c0b996](https://user-images.githubusercontent.com/5019111/44643387-044db900-a9d9-11e8-9713-7a3704f6bcb3.png)

**Comment by DmitriyKulagin** [comment]
Closed #3251

**Comment by AndreiMaz** [comment]
@DmitriyKulagin still exists. I can reproduce it
