### ISSUE TITLE
Can't open Plugins configuration page on admin area! (On NC 4.1)

### ISSUE THREAD

**Issue by foxinstone** [nopSolutions/nopCommerce#3252]
nopCommerce version: 4.10

I've been installed NC4.1 on my Windows Server 2012 server  ( Fresh install)
But after I login into the admin area, unable to open the plugins configuration page.
In addition, the function is normal.

If I use vs2017 to debug the source code, so everything is fine on the development machine.

Why is this?

![error](https://user-images.githubusercontent.com/35874666/44654974-1f92e580-aa26-11e8-87a9-d159a61997ec.JPG)
![log](https://user-images.githubusercontent.com/35874666/44655163-bf507380-aa26-11e8-8083-03682b027c64.JPG)

**Comment by foxinstone** [comment]
By the way:

(1)The screenshot above reflect is a situation when you use a browser on the server (NC4.1 server).
As with other browser on the other client (like 192.168.xx.xx/Admin/...), the result is the same.

(2)In order to solve the problem, I've been trying to install the core SDK (not just Run-Time) on NC4.1 Server, But the result is the same.

**Comment by AndreiMaz** [comment]
thanks. duplicated https://github.com/nopSolutions/nopCommerce/issues/3182
