### ISSUE TITLE
nopCommerce 4.1 Use of TableNoTracking 

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3253]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Use TableNoTracking table and do a query for Orders and then expand on OrderItems or Customer or other entities (BillingAddress, etc)

Result --> 
AutoMapper.AutoMapperMappingException: 'Error mapping types.'
Inner Exception
InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'Customer' on detached entity of type 'OrderProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.

So how do I do a read only query, without tracking, in a fast and performant way which will return entities that I can expand eg Orders, OrderItems, Customers, etc.

This same code use to work in 4.0 but the new EF seems to have changed some things and I am not super up on the EF changes, please advise.

**Comment by Xzelsius** [comment]
Since you are doing a readonly "TableNoTracking" query you'll have to `.Include()` every navigation property.

**Comment by AndreiMaz** [comment]
That's not an issue of nopCommerce. It;s rather EF question
