### ISSUE TITLE
Google structured data Breadcrumbs  - schema change August 2018

### ISSUE THREAD

**Issue by jonquickqsense** [nopSolutions/nopCommerce#3254]
Structured data tests on google report

BreadcrumbList problem: “The value provided for item.id must be a valid URL.”

https://webmasters.stackexchange.com/questions/117197/breadcrumblist-problem-the-value-provided-for-item-id-must-be-a-valid-url

the URL is now the id:

to fix edit _ProductBreadcrumb.cshtml

add id to span, with url as the value

 <span itemprop="item" itemscope itemtype="http://schema.org/Thing" id="@Url.RouteUrl("Product", new { SeName = Model.ProductSeName })">

.. and comment out the link item below...

                        @*<link itemprop="url" href="@Url.RouteUrl("Product", new { SeName = Model.ProductSeName })">*@

Jon

**Comment by PavelV95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Google structured data Breadcrumbs - schema change August 2018](https://trello.com/c/EMzZgNGd/1309-google-structured-data-breadcrumbs-schema-change-august-2018)
