### ISSUE TITLE
Redirect with 301 but ignores 'SEO  friendly Url' in Location of ResponseHeader

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3256]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Add a new language
2. Select 'Seo friendly url' in Configuration > Settings
3. Go to products of your choise and add "test" on the seo tab in 'Search engine friendly page name'
4. Save product record
5. Return to seo tab and change "test" in "testmetoo"
6. Search with curl for the deleted entry https://mydomain/de/test
7. The responseheader looks like:
_HTTP protocol error. 301 Moved Permanently.
Location: /testmetoo
Set-Cookie: .Nop.Customer=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
Set-Cookie: .Nop.Customer=6623a947-4477-495f-8e6d-3519860da8a9; expires=Sun, 01 Sep 2019 15:47:48 GMT; path=/; samesite=lax; httponly
Date: Sat, 01 Sep 2018 15:47:48 GMT
Content-Length: 0_

You see, the location does not contain '/de/testmetoo'. So what happs on searchcrwalers, they take the new url without /de/ in here index.
I have tried out this, because some of our pages in google did not contain the langauage inside the reruning url. In any case responseheaders ignores the language identifier.

The same behavior is under older nops like 3.90.

**Comment by AndreiMaz** [comment]
It's fine. Because then /testmetoo will be redirected to /de/testmetoo

**Comment by cnEUL** [comment]
I know that the browser follows, but Google not seems to follow. I have sawn this on a permission issue on site map. Also we have lot of results in Google and only used the language identifier, but in the results you see the URL without that. I was confused about that, so I tried out to find, why. It seems fur me it's the response header of inactive urlrecord entries.
