### ISSUE TITLE
4.10 performance issues

### ISSUE THREAD

**Issue by aquiladev** [nopSolutions/nopCommerce#3257]
I've tried to run load tests on 4.10 version and became sad:
<table>
<th></th>
<th>3.60 (Release - Any CPU)</th>
<th>4.10 (Release - Any CPU)</th>
<th>4.10 (Debug - Any CPU)</th>
<tr>
<td><b>Hardware</b></td>
<td colspan=3>Azure VM (B2ms)<br />vCPU - 2x (Xeon E5-2673 v4 2.30GHz)<br />RAM - 8GB<br /> Standard HDD</td>
</tr>
<tr>
<td><b>OS</b></td>
<td colspan=3>Windows Server 2016 Datacenter x64</td>
</tr>
<tr>
<td><b>MSSQL</b></td>
<td colspan=1>Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)</td>
<td colspan=2>Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)</td>
</tr>
<tr>
<td><b>Databese</b></td>
<td colspan=1>live db</td>
<td colspan=2>transformed live db via update scripts (3.60 -> 4.10)</td>
</tr>
<tr>
<td><b>Framework</b></td>
<td colspan=1>.NET Framework 4.5.1</td>
<td colspan=2>netcoreapp2.1</td>
</tr>
<tr>
<td><b>Runtime</b></td>
<td colspan=1>-</td>
<td colspan=2>dotnet core 2.0.9</td>
</tr>
<tr>
<td><b>Deployment mode</b></td>
<td colspan=1>-</td>
<td colspan=2>Self-contained</td>
</tr>
<tr>
<td><b>GC</b></td>
<td colspan=1>-</td>
<td colspan=2>
{ <br />
&emsp;ServerGarbageCollection: false,<br />
&emsp;ConcurrentGarbageCollection: false<br />
}
</td>
</tr>
<tr>
<td><b>Test scenario</b></td>
<td colspan=3> <ol><li>10 threads</li><li>request of 10 diff pages</li><li>10 loops</li></ol></td>
</tr>
<tr>
<td><b>Test results</b></td>
<td colspan=3><b>1000 requests</b></td>
</tr>
<tr>
<td><b>Time</b></td>
<td>4:58</td>
<td>10:13</td>
<td>11:05</td>
</tr>
<tr>
<td><b>Errors</b></td>
<td>39</td>
<td>48</td>
<td>0</td>
</tr>
<tr>
<td><b>Average</b></td>
<td>2 871 ms/page</td>
<td>5 760 ms/page</td>
<td>6 601 ms/page</td>
</tr>
<tr>
<td><b>Min</b></td>
<td>320 ms/page</td>
<td>217 ms/page</td>
<td>272 ms/page</td>
</tr>
<tr>
<td><b>Max</b></td>
<td>21 104 ms/page</td>
<td>100 422 ms/page</td>
<td>135 554 ms/page</td>
</tr>
<tr>
<td><b>CPU usage</b></td>
<td colspan=3>approximately 100%</td>
</tr>
<table>

Do you have any ideas why 4.10 performs worse than version 3.60?

**Comment by AndreiMaz** [comment]
We know about performance issues. But this task is too general. We have specific small task about performance improvements. If you have any other specific suggestions please let us know
