### ISSUE TITLE
Install Error: Cannot find the object "dbo.QueuedEmail" because it does not exist or you do not have permissions.

### ISSUE THREAD

**Issue by Papay** [nopSolutions/nopCommerce#3259]
nopCommerce version:  version 4.10
Steps to reproduce the problem: 
Hoster REG.RU
Copy archive with NO_SOURCE to server
Unpack archive to root
Goto site an starting installation
Fill all fields and click to install
After few seconds show error:
Cannot find the object "dbo.QueuedEmail" because it does not exist or you do not have permissions.

**Comment by AndreiMaz** [comment]
PLease check your database. Does this table exist? It works fine out of the box

**Comment by KrzysztofPajak** [comment]
Please check this issue:
[https://github.com/nopSolutions/nopCommerce/issues/3114](url)

**Comment by Papay** [comment]
Andrei,
Yes, table exists in the database. The installer creates this table. But further, when accessing this table from the installer, the DBO scheme is used.
The hoster creates the tables in a custom scheme (not DBO). 
And I can not change this on hosting.

**Comment by AndreiMaz** [comment]
duplicated
