### ISSUE TITLE
Price not updated when multiples rental products are linked to the same grouped product

### ISSUE THREAD

**Issue by vannicktrinquier** [nopSolutions/nopCommerce#3260]
nopCommerce version: 4.1 (not tested on previous version)

Steps to reproduce the problem: 
- Create a **grouped** product. Let's call it "Book"
- Create a simple product of type **rental**. Let's call it "Book Daily" and link it to the grouped product named Book
- Create a simple product of type **rental**. Let's call it "Book Monthly" and link it to the grouped product named Book
- On front end side, open the product page "Book", below are displayed all the products linked to this grouped product family "Book":. 
- When we update the starting and ending rental date of "Book Daily", the price is not updated at all

First investigation:
- Analysing the issue with Chrome console, it seems that the bug is linked to multiple definition of JS functions that should update the price. (they use the same name). 
Because of that, the wrong method is called and therefore wrong parameters are sent to the backend. After that on backend side, a null pointer exception happended and the price cannot be calculated again. 

Thanks

**Comment by RuS984** [comment]
Closed #3260
