### ISSUE TITLE
Contribution: Add open graph property "og:image:url" to display correct image when sharing on Facebook

### ISSUE THREAD

**Issue by wezzix** [nopSolutions/nopCommerce#3262]
Problem: When sharing a product on facebook, the product image is not shown as expected. Instead the logotype is shown. Using nopCommerce version: 4.10

Steps to fix the problem: 
Add meta property **og:image:url** with the same value as **og:image** in ProductTemplate.Simple.cshtml and ProductTemplate.Grouped.cshtml to resolve. This possibly applies to any other place where only og:image is used such as Blog.

**Comment by RuS984** [comment]
@wezzix 
We made changes in code. [commit](https://github.com/nopSolutions/nopCommerce/commit/f96c4b77b0b068d4f085c3a2da67cf7f98a6abd4)
Can you, please, check them on your FaceBook account?

**Comment by wezzix** [comment]
Yes that  is correct, I have tested that and the product image is displayed correctly in Facebook when sharing. Perhaps you would like to make the same edit on remaining occurrences of og:image, such as blog?

**Comment by RuS984** [comment]
@wezzix 
There are no more such places in "out of the box" code.
Closed #3262
