### ISSUE TITLE
VendorTermsOfService Topic Title Blank

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#3263]
nopCommerce version: 4.1

I just did a fresh install of 4.1 and noticed that in the footer the VendorTermsOfService topic name was blank. You can also see here below there is a space between sitemap and shipping and returns.

![image](https://user-images.githubusercontent.com/12185742/45054092-f4c61400-b059-11e8-84c6-6c41e36d0c5c.png)

I am just bringing it to attention, I am not sure if that was done intentionally or not.

Thanks

**Comment by RuS984** [comment]
Closed. (https://github.com/nopSolutions/nopCommerce/commit/cdf4175a9542155b4cfc1d5f4c277b7edc8af93c)
