### ISSUE TITLE
Checkout as Guest Or Register

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3266]
nopCommerce version: 4.1

Steps to reproduce the problem: 
1. I have enabled anonymous checkout and I have disabled registration.
2. When a user chooses to checkout they are redirected to /login/checkoutasguest.
3. The issue is the "Register" button and copy stating the advantages of registering are present even though the user will not be allowed to register.

IMO for this scenario it is best to not even show the checkoutasguest page and just redirect to the cart. 1. Typically if someone disables registration there are not returning users.
2. There is no point in asking them if they want to register because that will fail.
3. This leaves checkout as guest as the only option.

**Comment by AndreiMaz** [comment]
Thanks! We still should display the login page because although registration is disabled some users can login (accounts could be created manually). But of course, register button should not be displayed

**Comment by toddca** [comment]
yes for /login you should display and remove the register stuff, however for /login/checkoutasguest there is no point in displaying this page. My concern is that if you show both it could be confusing.
