### ISSUE TITLE
Hiding Price When Base is Zero (Configurable)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3268]
https://www.nopcommerce.com/boards/t/41290/hiding-price-when-base-is-zero.aspx

**Comment by tigran-avdalyan** [comment]
i think Hide price when "Base is zero" and "checked _Disable Add to Cart_ Button"

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
