### ISSUE TITLE
Nivo slider images url - HTTPS support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3269]
Mixed Content: The page at 'https://demo.nopcommerce.com/' was loaded over HTTPS, but requested an insecure image 'http://demo.nopcommerce.com/images/thumbs/0000079_banner_1.jpg'. This content should also be served over HTTPS.
(index):261 Mixed Content: The page at 'https://demo.nopcommerce.com/' was loaded over HTTPS, but requested an insecure image 'http://demo.nopcommerce.com/images/thumbs/0000080_banner_2.jpg'. This content should also be served over HTTPS.

**Comment by toddca** [comment]
@tigran-avdalyan please ensure your store is configured to use SSL. 

Admin: Configuration -> Stores - 'SSL enabled' == true.

**Comment by tigran-avdalyan** [comment]
@toddca
its not my store, its Nopcommerce demo site.
