### ISSUE TITLE
Performance. Store locale resources in files (not in database)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#327]
This way we won't even hit database.
1. We should think about support of web farms
2. Let's think how we should "highlight" new resources when a new version is released. Now we have "upgrade.sql script" and it's quite easy to create a new language pack (find new locales). What should we do now? We should help our community to easily upgrade existing language packs for new versions. Use WinMerge?
3. Drop LanguagePackImport stored procedure, drop LocaleStringResource entity, drop "localizationSettings.LoadAllLocaleRecordsOnStartup" setting
4. Drop "InstallLocaleResources" method from installation services
5. We should notify store owners in advance that during the upgrade "LocaleStringResource" table will be dropped. And they have to export and save existing locales on file system. We should also update our "upgrade instructions" and write that all "xml" files from \App_Data\Localization directory should be copied to a newer version
6. How will plugins be localized? Will their locales be stored in the same file as default ones?
7. Will custom resources be overridden when upgrading?

**Comment by esbee** [comment]
I agree this is a very important feature, furthermore, configuration/settings should also be stored in files

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
