### ISSUE TITLE
Using Azure CDN With Storage Origin With Path Fails

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3271]
nopCommerce version: 4.1

Steps to reproduce the problem: 
1. Create an Azure storage account and blob container name of "dev".
2. Setup Azure CDN and use the storage in 1. as your origin and set the path to /dev
3. Config nopCommerce to use Azure Storage by adding connection string, container name of "dev" and a storage endPoint of "https://endpoint.azureedge.net/"
4. Setup nopCommerce to store files on disk

Note when requesting images from azure the requested URL is:
https://endpoint.azureedge.net/dev/someimage.png
the correct URL is
https://endpoint.azureedge.net/someimage.png

When using a path in the origin config Azure CDN roots the URL to that path. So while the blob is at https://sample.blob.core.windows.net/dev/someimage.png when we config the CDN enpoint with a origin path the URL is https://endpoint.azureedge.net/someimage.png - note there is no "dev" part of the URI.

The issue is the AzurePictureService just blindly builds a URL from endpoint + containername + filename which is incorrect. It should be endpoint + filename as in this case the container name is not required in the URL.

Changing this would mean endpoint urls will need to be inclusive of the container name when not using a CDN and *may* be needed when using a CDN but only when an origin path is not specified. 

The fix is to add a 4th config variable: AzureBlobStorageAppendContainerName: true|false and then build the URL accordingly. Default to true so there are no regressions but in my case I would set to false.

**Comment by skoshelev** [comment]
Closed #3271
