### ISSUE TITLE
AzurePictureService Performance Issue

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3273]
nopCommerce version: 4.1

Steps to reproduce the problem: 
1. Configure for Azure Blob Storage.
2. Execute page requests

for each page request a new AzurePictureService instance is created. For each new instance an attempt is made to create the blob container and a call to set the permissions on the container is made. Although these are made in an async manner there is really only a need to do this once as the configuration is only read once per AddDomain start. 

Either do this initialization with a StartupTask() or set a static variable in the AzurePictureService that can be read to determine if the 1 time init has occurred, if not then init the container, set the flag, and put the correct locking around it.

**Comment by skoshelev** [comment]
Closed @3273
