### ISSUE TITLE
Support better DI implementation

### ISSUE THREAD

**Issue by iyilm4z** [nopSolutions/nopCommerce#3276]
I think it's so boring to register every new interface-implementation pair via IDependencyRegistrar implementations and i generally forget this part. Mostly we use `builder.RegisterType<Foo>().As<IFoo>()` and in my opinion it breaks [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). Why we don't have Conventional Registering by using some Reflection, Interception and [Marker Interface](https://en.wikipedia.org/wiki/Marker_interface_pattern) to register these pairs automatically? I can do it but what do you think about it?

**Comment by TomasHorvath** [comment]
https://dzone.com/articles/marker-interface-isnt-a-pattern-or-a-good-idea

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
