### ISSUE TITLE
Configuration Name problem

### ISSUE THREAD

**Issue by ayberkcal** [nopSolutions/nopCommerce#3277]
nopCommerce version: **4.1** (not tested another versions)

Steps to reproduce the problem: 

- Create new Solution Configuration "Develop Plugin" named (or anothername).
- Try debug project with new solution configuration.

Then problem will be occured.

**Exception:** 
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: 'One or more compilation failures occurred:
h0h0hvmq.2yl(1,1): error CS8301: Invalid name for a preprocessing symbol; 'DEVELOP PLUGIN' is not a valid identifier'

**Exception Detail:**
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException
  HResult=0x80131500
  Message=One or more compilation failures occurred:
h0h0hvmq.2yl(1,1): error CS8301: Invalid name for a preprocessing symbol; 'DEVELOP PLUGIN' is not a valid identifier
  Source=Nop.Web.Framework
  StackTrace:
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in C:\development\nopCommerce\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 81
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

Opinion:
I think some controls cannot handle configuration names different from "Debug" and "Release".

FYI

**Comment by skoshelev** [comment]
Hi @ayberkcal. This is not problem of nopCommerce, I'm not sure, but problem is on the space between two words, I added a new config without space and it work. Please try to add config with name DevelopPlugin.

**Comment by skoshelev** [comment]
Closed #3277
