### ISSUE TITLE
SelectBillingAddress method exception

### ISSUE THREAD

**Issue by resanehlab-admin** [nopSolutions/nopCommerce#3279]
nopCommerce version: 4.1

In SelectBillingAddress method of checkout controller we face with an exception if address.Country is null. The code which cause an exception is:

`if (_shippingSettings.ShipToSameAddress && shipToSameAddress && _shoppingCartService.ShoppingCartRequiresShipping(cart) && address.Country.AllowsShipping)`

We think that checking for address.Country != null is missing.

Source: https://www.nopcommerce.com/boards/t/55331/selectbillingaddress-method-exception.aspx

**Comment by AndreiMaz** [comment]
Thanks a lot! Actually it can be null in some cases. I think we should also check whether "Country" address field is enabled. And when enabled, we should make null validation

**Comment by DmitriyKulagin** [comment]
Closed #3279

**Comment by DmitriyKulagin** [comment]
Closed #3279
