### ISSUE TITLE
Blogpost edit not working ouside admin

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3283]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Login as Admin
2. write a blog
3. goto public store
4. on the to right of "Administration" click on "manage this page"
5. An error comes up "Page not found". Seems that there is used "../Admin/Blog/Edit/xxx" but inside the admin, the edit comes with: ".../Admin/Blog/BlogPostEdit/xxx9"

**Comment by cklenk** [comment]
I just noticed this too, thank you for reporting. Bummer it didn't make it into the 4.1 release. But looks easy enough to fix 👍
