### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by sreenisaseendran** [nopSolutions/nopCommerce#3286]
nopCommerce version: 4.10

Steps to reproduce the problem: 
Download the latest version
By running the application will get the following error
'Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

**Comment by RomanovM** [comment]
I just tried to reproduce the problem and launched a clean solution. It works like a charm without any errors.
