### ISSUE TITLE
Message Queue deleted when pressing [ENTER] in start date field

### ISSUE THREAD

**Issue by blades614** [nopSolutions/nopCommerce#3288]
nopCommerce version: 3.8

Steps to reproduce the problem: 
1. Backup your database first.
2. Log into the site as an admin and navigate to System | Message queue
3. Place your cursor in the start data field (make sure there's some messages queued to go out).
4. Press the [ENTER] key and notice a green banner is displayed that states, "All queued emails have been deleted successfully."

NOTE:  This might affect other areas and fields in the system as well.

![nop38-severebug](https://user-images.githubusercontent.com/11799219/45447655-d2557b80-b695-11e8-974c-1e77a18db070.png)

**Comment by RomanovM** [comment]
Ensure that pressing Enter causes to click Search button for all input fields in a search panel. We already did it for some of them (textboxes).

**Comment by RomanovM** [comment]
See https://www.nopcommerce.com/boards/t/63813/nop-42-string-resources-issues.aspx

**Comment by DmitriyKulagin** [comment]
Closed #3288
