### ISSUE TITLE
Marketplace Sorting - wrong results

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3291]
Please see
https://www.nopcommerce.com/boards/t/49512/in-marketplace-sort-by-filter-not-work-correctly.aspx

**Comment by tigran-avdalyan** [comment]
And please see
https://www.nopcommerce.com/boards/t/55395/nopcommerce-marketplace-clean-and-check.aspx

**Comment by RomanovM** [comment]
Thanks, we'll investigate it. Move discussion to the forum topic.
