### ISSUE TITLE
Discount configuration URL is not properly generated in virtual directories

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3292]
As per our premium support ticket number 14378

It appears to be a path issue when running nopCommerce as a sub-application under a parent domain.  Virtual path is generatead twice. For example. www.test.com/path/path/Admin/DiscountRulesCustomerRoles/Configure?discountId=18 instead of www.test.com/path/Admin/DiscountRulesCustomerRoles/Configure?discountId=18

I believe it's the "GetConfigurationUrl" method that has the issue in case of sub-applications.

var url = $"{_webHelper.GetStoreLocation()}{discountRequirementRule.GetConfigurationUrl(discount.Id, discountRequirementId)}";

**Comment by RomanovM** [comment]
See also: https://github.com/nopSolutions/nopCommerce/issues/2833

**Comment by DmitriyKulagin** [comment]
Closed #3292
