### ISSUE TITLE
Issue with dates in KendoUI (Telerik) grid

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#33]
Details: http://www.nopcommerce.com/boards/t/14024/issue-with-dates-in-teleriks-grid-admin.aspx 

nopCommerce store owners can have custom timezones. There two solution:

1 Using 'string' instead of 'DateTime' in admin area models (not a way to go!)
2. Convert dates in JsonResults on server (configurable - disabled by default). Let's make it configurable (can be disabled). 

Useful link  - http://stackoverflow.com/questions/726334/asp-net-mvc-jsonresult-date-format

**Comment by xitatulrungta** [comment]
https://www.nopcommerce.com/boards/t/49758/issue-with-datetime-difference-in-kendo-grid-in-almost-every-nopcommerce-version.aspx

Please check above link. This issue still persists.

**Comment by atulrungta** [comment]
https://www.nopcommerce.com/boards/t/49758/issue-with-datetime-difference-in-kendo-grid-in-almost-every-nopcommerce-version.aspx

Please check above link. This issue still persists.

**Comment by AndreiMaz** [comment]
@RomanovM Looks like Atul is right. Please check
