### ISSUE TITLE
Currency Symbol for EUR on fresh 4.10 is wrong

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3307]
nopCommerce version: 4.10

Steps to reproduce the problem: 
NopComemrce 4.10 newly installed
Go to "Configuration > Currency"
Click "Edit" in the EURO line
"Custom formatting" has a strange symbol like " Ђ 0.00 " instead of " € 0.00"
The installed binary file is the final 4.10 from github without source
Windows 2012 Datacenter US, SQL 2014 Webedition US, Core Hosting 2.1.4

![eur](https://user-images.githubusercontent.com/37210350/45782892-8477df00-bc64-11e8-98c3-6d17d202058d.png)

**Comment by AndreiMaz** [comment]
Thanks. The same ahppens on our demo site - http://demo.nopcommerce.com/

**Comment by PavelV95** [comment]
> NopComemrce 4.10 newly installed

Was the UseFastInstallationService option is enabled when installing shop? If this option is off the symbol displayed as it should

**Comment by cnEUL** [comment]
Where is that option to find, i have used the standard compiled version.

**Comment by PavelV95** [comment]
> Where is that option to find, i have used the standard compiled version

This option placed in Presentation/Nop.Web/appsettings.json
Please take a look at whether this parameter is set to true or false

**Comment by cnEUL** [comment]
Hi, but this is source code, i have used the binary - original.

**Comment by b-r-s** [comment]
Hi there - this issue is still present in v4.1 - the fix/commit mentioned above appears to not work
![image](https://user-images.githubusercontent.com/30550213/52540939-47200500-2d5d-11e9-81f9-cb7fc45ccf71.png)
