### ISSUE TITLE
"Visible individually" setting ignored when "Show on homepage" is marked

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3314]
Source: https://www.nopcommerce.com/boards/t/55460/visible-individually-setting-ignored-when-show-on-homepage-is-marked.aspx

**Comment by PavelV95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Visible individually" setting ignored when "Show on homepage" is marked](https://trello.com/c/SJqJ7ly6/1308-visible-individually-setting-ignored-when-show-on-homepage-is-marked)

**Comment by PavelV95** [comment]
Fix VisibleIndividually behavior
1. If a product is associated, then it is not displayed at all
2. If VisibleIndividually = true and ShowOnHomepage = true, a product is still not displayed in homepage

**Comment by PavelV95** [comment]
Closed #3314
