### ISSUE TITLE
Categories for specification attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#332]
When we have a lot of specifications, and a lot of products, its hard to find specifications in new product adding. 
also in product detail view, this specifications are not Categorized.. 

example for mobile : 
Appearance specifications such as : Dimensions, color , ... 
Technical specifications such as : CPU,RAM ,... 
Network specifications such as : 4G,3G,WiFi,... 

I think we need specifications in a structure such as hierarchy tables. and we need a relation between 
specifications and product categories.. 

in this structure, root nodes are only title for separate conceptual kind of specifications ( such as : Appearance specifications, Technical specifications, ..) 
and relation with product categories, help us to select, fast and right template to adding new product. 

Source: http://www.nopcommerce.com/boards/t/38537/feature-request-categorized-specification.aspx 

and 

http://www.nopcommerce.com/boards/t/19894/grouping-specification-attributes-specification-type.aspx

**Comment by AndreiMaz** [comment]
duplicated
