### ISSUE TITLE
Authentication error on requests in the Square payment plugin 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3320]
Source: https://www.nopcommerce.com/boards/t/54933/square-payment-not-working-with-410.aspx

**Comment by rajupaladiya** [comment]
Hi Romanov, 
I just work around on this and found miss send location parameter at payment request.
It shows below error message.
![square-error](https://user-images.githubusercontent.com/13154058/46921356-de778480-d017-11e8-8e92-551dd9b41ca1.png)

I added below code snippet  Plugins > Nop.Plugin.Payments.Square > SquarePaymentMethod.cs > GetPaymentInfo method and it worked fine.
 ```

  // Fixed Error with Live mode - Location is required parameter for payment request
            if(!_squarePaymentSettings.UseSandbox)
                paymentRequest.CustomValues.Add("Location", _squarePaymentSettings.LocationId);
```

**This is final code snippet** 
![nop-square](https://user-images.githubusercontent.com/13154058/46921379-28f90100-d018-11e8-9eca-041d599bc764.png)

Hope this is helpfully.

**Comment by RomanovM** [comment]
Check after https://github.com/nopSolutions/nopCommerce/commit/7cc092fa5383a421a7d5232620d0050472548fd4

**Comment by RomanovM** [comment]
Some more changes in https://github.com/nopSolutions/nopCommerce/commit/9178e7596a23f572e8bbd153b86ee7ee0e183e87

**Comment by garrie007** [comment]
is this cs file in nop 4.20, if so its not in mine...

**Comment by steve99** [comment]
I have upgraded to 4.2 and the Plugin still needs this workaround to include the location.  Also, the base URL will only work with production.  Discussing with Square, the sandbox has a different base URL.

**Comment by RomanovM** [comment]
@steve99 Thanks for the information. [Here](https://github.com/nopSolutions/nopCommerce/commit/623884dbf9c68a0f0e94248bc44bfde124f77ec2) is commit details.
