### ISSUE TITLE
OfficialFeedManager Proxy Settings.

### ISSUE THREAD

**Issue by JyeGoodlet** [nopSolutions/nopCommerce#3323]
nopCommerce version: 4.1.0

Steps to reproduce the problem: 
1. Go to /Admin/Plugin/List when hosting on server that only allows web requests via a proxy. 
2. Get error "The remote server returned an error: (407) Proxy Authentication Required."

Potential fix:
Either in web.config, appsettings.json or administration panel allow for section to configure proxy settings.

**Comment by RomanovM** [comment]
Thanks, moved to https://github.com/nopSolutions/nopCommerce/issues/3181
