### ISSUE TITLE
Newsletter Headline changes with inserting a test Email after reopening

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3325]
nopCommerce version:  4.10

Steps to reproduce the problem: 
Add Campagne, fill out all fields and reopen it.
Then go to the test eMail, insert one mail. In the same moment the Title of the newsletter is changed. If you save the campaign again, the wrong title is saved to the database.

![newsletter1](https://user-images.githubusercontent.com/37210350/45955001-07a38700-c00f-11e8-8067-78d26a9fd7df.png)

After reopening and inserting a test Email:
![newsletter2](https://user-images.githubusercontent.com/37210350/45955008-10945880-c00f-11e8-8a71-b3c98b604cdf.png)

**Comment by RomanovM** [comment]
It's not because of nop, it's the 'autofill forms' function of your browser. Text the email manually and the campaign name will not change.

**Comment by cnEUL** [comment]
;-) Thank you
