### ISSUE TITLE
The latest release version listed is wrong!

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3327]
What's the latest, current release of NopCommerce?  I suspect the release-4.10 branch, but there are two recent commits that show a version change to 4.2:

https://github.com/nopSolutions/nopCommerce/compare/release-4.10...develop

This means it's no longer a 4.1 release and no longer the latest release since it's not the same version as the official version for download.

I've been using the following 4.1 bug fix branch and it appears to be the latest release as it contains the latest bug fixes pertinent to 4.1.

https://github.com/nopSolutions/nopCommerce/tree/nopCommerce-4.10-bug-fixes

**Comment by AndreiMaz** [comment]
All is fine. Please see http://docs.nopcommerce.com/display/en/Working+with+source+code+and+contributions

"develop" is the latest development version (4.20 now).

So you should use "master" or "nopCommerce-4.10-bug-fixes". If you want to simply download any version, then find them at https://github.com/nopSolutions/nopCommerce/releases
