### ISSUE TITLE
Import/export specification attributes

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#3329]
Used functionality for any E-commerce product.

**Comment by AndreiMaz** [comment]
1. There's no need to import checkotu attributes. Why if usually store owners have 2-3 ones?
2. Product attributes can be imported for products (when importing products) excluding the parent one. We can consider importing it as well (but not exporting)
3. Specification attributes - maybe.

So I've renamed a work item to import/export specificationn attributes and remove product and specification ones

**Comment by ecommerce-tester** [comment]
You are right about Checkout attributes, in our project we have 6000 products and more then 100 type of products. Each type of product have more then 20 Specification. In a result we need to manually type 2000 specifications. I don't say about Specification Options. Each Spacification  have more then 5 Options.
Its very important  functionality

**Comment by ecommerce-tester** [comment]
For Product attributes
But for  Product attributes for first step we need to create Product attribute, then Map to Product.
Its also problem.
If we have many Product Attributes, for first step we need to import them , then we can Us it in IMPORT/EXPORT Product function.

**Comment by cnEUL** [comment]
But you can also access all tables very well via OData. Nop4You offers a plugin which allows access to almost all tables. In this way a special import or export can be realized.
OData is, if you look at it abstractly, a kind of ODBC over HTTP and you can control the protocol with Windows board tools also from scripting languages like simple VbScript.

**Comment by ecommerce-tester** [comment]
https://www.codeproject.com/Articles/1194712/Advanced-Excels-With-EPPlus

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
