### ISSUE TITLE
Products shared between vendors

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#333]
use nopcommerce to create some kind of "warehouse" - many vendors, many products etc. "MultiVendors" option is really great but also im little bit confused when i use it. For example when i have two vendors and they have same products with same name, same code and same or different price then i must add row for each product for each vendor in product table with the same name but different VendorId. 

My idea is create another table to store VendorID and ProductId, and also table to store price or other product attribute, and table to store PriceId and ProducutId. What do you think about this?:) 

Source: http://www.nopcommerce.com/boards/t/37978/suggestion-shred-product-between-vendors.aspx

also see http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=11#162935

**Comment by roger999** [comment]
This would be a very useful feature!

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
