### ISSUE TITLE
AdminAntiForgery token in partial view action causes 400 error for Vendors 

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3331]
nopCommerce version: 4.1

Steps to reproduce the problem: 
`[HttpPost]
        [AdminAntiForgery]
        public virtual IActionResult _ReportArea(int? testId, DateTime? startDate, DateTime? endDate, string destination)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageProducts))
                return AccessDeniedView();

            //prepare model
            var model = PrepareTestDataModel(testId, startDate, endDate, destination);

            return PartialView("~/Plugins/Misc.Test/Views/Admin/_ReportArea.cshtml", model);

        }`

`function Button1_Click() {
        $("#report-detail").html("");
        $.ajax({
            url: "@Html.Raw(Url.Action("_ReportArea", "TestAdmin"))",
            data: additionalData(),
            type: "POST",
            cache: false,
            success: function (data) {
                $("#report-detail").html(data);
            }
        });
    }
    function additionalData() {
            var data = {
                testId: $('#@Html.IdFor(model => model.TestSearchModel.TestId)').val(),
                startDate: $('#@Html.IdFor(model => model.TestSearchModel.SearchStartDate)').val(),
                endDate: $('#@Html.IdFor(model => model.TestSearchModel.SearchEndDate)').val(),
                destination: $('#@Html.IdFor(model => model.TestSearchModel.SearchDestination)').val()

            };
            addAntiForgeryToken(data);
            return data;
        }`

It works fine for admin but I get 400 error for vendors. if i remove antiforgery token it works fine. Idk if this is a bug or normal behavior.

**Comment by AndreiMaz** [comment]
Is it your custom code? There's no such methods in nopCommerce

**Comment by bulutkartal** [comment]
yes it is custom code from plugin.

**Comment by AndreiMaz** [comment]
if this case could you please post it on our forums? This issue tracker for issue in the core. For custom development question it's better to use our forums
