### ISSUE TITLE
Improve import/export products with specification attributes

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#3332]
1. Add possibility to fully match attributes when product importing(add, delete, and update)
2. Use name of "Specification Attribute Option" instead ID

What else??

**Comment by tigran-avdalyan** [comment]
@skoshelev 2.Can we use name of "Specification Attribute Option" Or ID (like we import product attributes)

**Comment by ecommerce-tester** [comment]
https://www.codeproject.com/Articles/1194712/Advanced-Excels-With-EPPlus

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
