### ISSUE TITLE
ECB Plugin not uninstalls itself in scheduler,  inside source is an invalid url

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3335]
nopCommerce version: 
4.10

Steps to reproduce the problem: 
If you uninstall the ECB Plugin it leaves the entry in task planner, so it generates exceptions in the eventlog.
"40          Error while running the 'Update currency exchange rates' schedule task. Active exchange rate provider cannot be loaded  "
So i have now disabled the task.

Second, i had done a look in the source and the url for the name space is not valid any more: "gesmes", "http://www.gesmes.org/xml/2002-08-01"

**Comment by cnEUL** [comment]
perhaps it is an idea to move the service task routine from install/uninstall the ECB plugin inside the plugin.

**Comment by PavelV95** [comment]
> If you uninstall the ECB Plugin it leaves the entry in task planner, so it generates exceptions in the eventlog.
> "40 Error while running the 'Update currency exchange rates' schedule task. Active exchange rate provider cannot be loaded "

I can't reproduce this bug, could you explain your steps in more detail and give links on the invalid source lines?

**Comment by cnEUL** [comment]
Hi,
if you uninstalls the ECB Plugin, and then also delete it. The Schedular has the ECB entry still there. It it is enabled and this give exception.

![ecb](https://user-images.githubusercontent.com/37210350/47020305-5dc0a180-d159-11e8-832e-dcefacf2b0f6.png)

**Comment by PavelV95** [comment]
We cannot delete this entry in the task scheduler, as all the others currency exchange plugins work with it. But if you do not need this task, then you can disable it or set the flag "Stop on error"

As for inaccessible url-addresses in the namespaces, they may not be necessarily working url addresses, their task is to ensure uniqueness, they are not intended to be passed on.

**Comment by cnEUL** [comment]
I can understand that it is not possible to delete the task because other plugins use it. But if you uninstall ECB and then press the Delete button, the task will run on the hammer, so to speak. There's nothing he can start.

We'd have to talk about a conceptual change here. At least you should prevent the delete button from being activated..
