### ISSUE TITLE
Widgets inside forms

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#3337]
I'm changing my CDEK plugin to show map during shipping method selection and it will use widget to show its map because as I see it's not possible otherwise.
But widgets are shown inside form. So every iteraction with widget causes POST and page reload.
Ofcourse I'v changed cshtml file. But I think its better to do it by default.

Should be:
```
        <div class="section shipping-method">
            @await Component.InvokeAsync("Widget", new { widgetZone = "checkout_shipping_method_top" })
            <form asp-route="CheckoutShippingMethod" method="post">
```

**Comment by ArturAlekseev** [comment]
You can see widget here: https://www.cdek.ru/clients/widget.html
When I press inside textbox where you need to select city - it causes page reload. If widget is moved outside of form it does not happen.

**Comment by DmitriyKulagin** [comment]
After some discussion, it was decided not to implement.

**Comment by ArturAlekseev** [comment]
Interesting to know the reason of such discussion.
Our plugins should be just plug & play. And you force us to make tell users to change/replace core nopcommerce files in order for plugins to work.
