### ISSUE TITLE
Checkout Attribute Textbox - Default value Multilingual

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3341]
nopCommerce version: 4.1

Steps to reproduce the problem: Create Checkout Attribute, Control Type - Textbox
And write Default Value, its not support Multilingual

P.S. i think same situation in Product Attribute Control Type - Textbox

**Comment by LubovKhokhlova** [comment]
Resolved #3341

**Comment by LubovKhokhlova** [comment]
Fixed bug with one language default value
