### ISSUE TITLE
Payment method Friendly Name Multilingual Support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3347]
nopCommerce version: 4.1

Steps to reproduce the problem: 
When checkout in Confirm Order step write "Payment Method: Cash On Delivery (COD)"
Payment Method: - String Resource and can be translated
but Cash On Delivery (COD) is plugin Friendly name , and can't be translated .

**Comment by RomanovM** [comment]
Thanks, it's already done. See https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs#L675
