### ISSUE TITLE
Not an issue [info]

### ISSUE THREAD

**Issue by iyilm4z** [nopSolutions/nopCommerce#3349]
Could you please tell me why we use *ForCaching classes for caching like [StoreForCaching](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Stores/StoreForCaching.cs) instead of classes itselfs like [Store](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Stores/Store.cs)?

**Comment by RomanovM** [comment]
You can use our [forums ](https://www.nopcommerce.com/boards)for such purposes

**Comment by iyilm4z** [comment]
Thanks @RomanovM
