### ISSUE TITLE
Product/checkout/customer/address attributes. Allow a store owner to specify regex rules for inputs textboxes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#335]
3 new types: "Email", "Integer", "Number" (with 2 decimals) that will be handled as the type Textbox but with a validation to assure that the right value is entered. A range could be also defined for Integer and Number types. 

Forum source: http://www.nopcommerce.com/boards/t/29083/suggestion-new-type-of-controls-for-product-attributes.aspx

let's discuss possible rules to support

**Comment by tigran-avdalyan** [comment]
We can use is.js (https://is.js.org)

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
