### ISSUE TITLE
Coupon validation. User won't be notified in some cases

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#3350]
Steps to reproduce the problem: 
1. create a coupon as you can see at the picture
![image](https://user-images.githubusercontent.com/27218280/46346829-12cf6600-c652-11e8-9182-66f677f153fe.png)
2. create an additional requirements for this
![image](https://user-images.githubusercontent.com/27218280/46346860-2da1da80-c652-11e8-8a21-88c7c32d61a1.png)

The problem is, if anyone else (not a „Forum moderator” member) want to use this coupon (checkout), will not be notified.
The page will be reloaded without any error message.

Source: Premium support (Ticket #14406)

**Comment by PavelV95** [comment]
Closed #3350
