### ISSUE TITLE
Copy-Paste problem of editor in firefox

### ISSUE THREAD

**Issue by ni-fara** [nopSolutions/nopCommerce#3352]
nopCommerce version: 4.0, 4.1

Steps to reproduce the problem: use an rtl language, edit a product, copy some text and paste it (ctrl+v) in editor. The screen goes dark. (It happens only with rtl languages)
![ezgif-1-562b6f373b39](https://user-images.githubusercontent.com/35923697/46478770-86ac7280-c7fa-11e8-8594-02eaebfa60fd.gif)

**Comment by RomanovM** [comment]
It's not because of nop, it's bug of your browser.
