### ISSUE TITLE
"Notify for qty below" setting in product details doesn't work

### ISSUE THREAD

**Issue by ni-fara** [nopSolutions/nopCommerce#3353]
nopCommerce version: 4.1, 4.0

Problem: The "Notify for qty below" setting in product details doesn't work. It doesn't notify the store owner for stock quantities below the specified value. It only notifies the store owner when the stock quantity reaches number zero.

What I've done to produce the problem:
1- Create a product of type simple.
2-In "Inventory method" setting choose "Track inventory".
3- Set "Stock quantity" to number 6
4- Set "Notify for qty below" to number 4
5- Then I reduce the quantity by buying the product (each time only one item is bought)
6- No notifications are displayed in dashboard in "Common statistics" section when the product quantity reaches number 4 or 3.
7- Continue buying the product, and you can see no notifications are displayed until product quantity is equal to zero.

Edit: I found that "Notify for qty below" setting was completely ignored for filtering the related result set in source code and other values were used instead of it. So i made pull request #3356  to fix the issue.

**Comment by ni-fara** [comment]
So "MinStockQuantity" propery is used for both "Low stock activity" and "Low stock report", but consider this situation that the store owner wants to see a product in low stock report  when the stock quantity reaches 5, and wants to disable the buy button when the stock quantity is zero. Currently it is impossible to do this. Two different needs are tight together.
 With changes of pull request #3356 both "low stock activity" and "Low stock report" work fine using the existing properties and codes for both simple products and combinations. Then we can add a new bool value to distinguish if the store owner want's to be notified with email too or not.

**Comment by holydk** [comment]
Closed #3353
