### ISSUE TITLE
[Suggestion] Support 3rd Party Fraud Screening

### ISSUE THREAD

**Issue by m-cameron** [nopSolutions/nopCommerce#3354]
nopCommerce should allows us to integrate 3rd party fraud screening service and alarm merchants on the high risk orders.

One example is FraudLabs Pro which is being used in 19 shopping carts https://www.fraudlabspro.com/supported-platforms

**Comment by RomanovM** [comment]
You can do such integrations as a Misc type plugins. It doesn't need a special infrastructure.
