### ISSUE TITLE
SEO urls with folder structure - could this be supported

### ISSUE THREAD

**Issue by sc0ttc0** [nopSolutions/nopCommerce#3362]
nopCommerce version: any
SEO urls with  folder structure.

I know this is a debated area in seo terms but some folks like to be able to add "depth" to the urls - something that nop does not support right now.
For example:
/blog/tools/latest-56v-power-drills-on-sale

As I understand it google would treat this the same as: blog-tools-latest-56v-power-drills-on-sale

But some prefer the folder structure .. I do from an organisation point of view anyway.

Not sure what is involved to support this ..

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/385
