### ISSUE TITLE
"GetListOfAllowedTokens" method should take MessageTemplate as parameter

### ISSUE THREAD

**Issue by brakim** [nopSolutions/nopCommerce#3364]
Hi, 

I have created a new custom Message Template and it don't seem possible to add Tokens to it.
The only Event that is published during edit of a Message Template is `AdditionTokensAddedEvent`.

So the only option we have right now is to consume that event and add all tokens, the only problem is that it's adding the tokens for all message templates. If the message template was passed into `GetListOfAllowedTokens` it could also be inserted into the Event `AdditionTokensAddedEvent`.

That way you can build logic for when you want to add Tokens or not per Message Template.

nopCommerce version: 4.10

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
