### ISSUE TITLE
OrderTotal Discount Tax is being calculated on pre-discount amount

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#337]
Forum source: http://www.nopcommerce.com/boards/t/26447/ordertotal-discount-tax-is-being-calculated-on-pre-discount-amount-nop-v-31.aspx

**Comment by alecrt** [comment]
Why it has been closed?
I still experience this behavior in 3.9

**Comment by andrenpt** [comment]
This is still an issue that can create massive accounting problems. Not sure why it's closed...
