### ISSUE TITLE
Checkout attribute conditions don't work

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3371]
nopCommerce version: 4.10

It's not possible to configure conditional attributes. The issue is in the "PrepareConditionAttributesModel" method of \Nop.Web\Areas\Admin\Factories\CheckoutAttributeModelFactory.cs:

if (!model.EnableCondition)
                return;

We should not return here.

More details (example) is available at our premium support portal (ticket 14427)

**Comment by DmitriyKulagin** [comment]
Closed #3371
