### ISSUE TITLE
Not a Code issue but Demo website is not working properly

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3374]
Receving following error when you try to open any categories.

An unhandled exception occurred while processing the request.
SqlException: The multi-part identifier "t.__RowNumber__" could not be bound.
The multi-part identifier "t.__RowNumber__" could not be bound.
The multi-part identifier "t.Id" could not be bound.
The multi-part identifier "t.AllowCustomersToSelectPageSize" could not be bound.
The multi-part identifier "t.CreatedOnUtc" could not be bound.
The multi-part identifier "t.Deleted" could not be bound.
The multi-part identifier "t.Description" could not be bound.
The multi-part identifier "t.DisplayOrder" could not be bound.
The multi-part identifier "t.LimitedToStores" could not be bound.
The multi-part identifier "t.ManufacturerTemplateId" could not be bound.
The multi-part identifier "t.MetaDescription" could not be bound.
The multi-part identifier "t.MetaKeywords" could not be bound.
The multi-part identifier "t.MetaTitle" could not be bound.
The multi-part identifier "t.Name" could not be bound.
The multi-part identifier "t.PageSize" could not be bound.
The multi-part identifier "t.PageSizeOptions" could not be bound.
The multi-part identifier "t.PictureId" could not be bound.
The multi-part identifier "t.PriceRanges" could not be bound.
The multi-part identifier "t.Published" could not be bound.
The multi-part identifier "t.SubjectToAcl" could not be bound.
The multi-part identifier "t.UpdatedOnUtc" could not be bound.
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs, line 85

Stack Query Cookies Headers
SqlException: The multi-part identifier "t.__RowNumber__" could not be bound.
 The multi-part identifier "t.__RowNumber__" could not be bound.
 The multi-part identifier "t.Id" could not be bound.
 The multi-part identifier "t.AllowCustomersToSelectPageSize" could not be bound.
 The multi-part identifier "t.CreatedOnUtc" could not be bound.
 The multi-part identifier "t.Deleted" could not be bound.
 The multi-part identifier "t.Description" could not be bound.
 The multi-part identifier "t.DisplayOrder" could not be bound.
 The multi-part identifier "t.LimitedToStores" could not be bound.
 The multi-part identifier "t.ManufacturerTemplateId" could not be bound.
 The multi-part identifier "t.MetaDescription" could not be bound.
 The multi-part identifier "t.MetaKeywords" could not be bound.
 The multi-part identifier "t.MetaTitle" could not be bound.
 The multi-part identifier "t.Name" could not be bound.
 The multi-part identifier "t.PageSize" could not be bound.
 The multi-part identifier "t.PageSizeOptions" could not be bound.
 The multi-part identifier "t.PictureId" could not be bound.
 The multi-part identifier "t.PriceRanges" could not be bound.
 The multi-part identifier "t.Published" could not be bound.
 The multi-part identifier "t.SubjectToAcl" could not be bound.
 The multi-part identifier "t.UpdatedOnUtc" could not be bound.
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by rajupaladiya** [comment]
Reported on Forum at https://www.nopcommerce.com/boards/t/55114/demo-site-down.aspx one and half month ago.

**Comment by bulutkartal** [comment]
I saw on forum as well, but seems like Nopcommerce Team cannot spare as much as time they used to on forum. That is why i put it here.

**Comment by RomanovM** [comment]
Thanks. We know about this problem and are trying to solve it.
