### ISSUE TITLE
Mobile View Admin Menu Panel Broken in Nop 4.1

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3385]
Source: https://www.nopcommerce.com/boards/t/54632/mobile-view-admin-menu-panel-broken-in-nop-41.aspx

**Comment by DmitriyKulagin** [comment]
Closed. See [commit](https://github.com/nopSolutions/nopCommerce/commit/cab5068388bcce96ee0f2ca327d15b6af8ee47e5)

**Comment by AndreiMaz** [comment]
There was other issue fixed at https://github.com/nopSolutions/nopCommerce/commit/aeabc20d80e0ad0b2fa861e7bb3738fca80846d6 (a value indicating whethrer the menu was expanded or collapses) wasn't properly saved. But after that fixed the original issue came back

**Comment by DmitriyKulagin** [comment]
Closed #3385

**Comment by AndreiMaz** [comment]
Disabled this functionality (cannot find other solution now). Anyway it's always expanded on desktop and collapsed on mobile devices
