### ISSUE TITLE
Missing updated stored procedure [dbo].ProductLoadAllPaged

### ISSUE THREAD

**Issue by MaximG1234** [nopSolutions/nopCommerce#3389]
nopCommerce version: Version 4.2

Problem: ProductLoadAllPaged Stored procedure has not been updated when checkin #3314 was performed as visible in this page: https://github.com/nopSolutions/nopCommerce/commit/c1e201cd138c705b9b7674feb376b5ed0f30d09c#diff-55813f80251e2b712a598e5a1c4fae8b

Steps to reproduce the problem: 

1. Run latest version of GitHub source code.
2. Open Products page. 

Receive error: Services.ProductService 'System.Data.SqlClient.SqlException: 'Procedure or function ProductLoadAllPaged has too many arguments specified.''

You can see the missing parameters in SqlServer.StoredProcedures.sql stored procedure [ProductLoadAllPaged]. 

The parameter missing is pParentGroupedProductId

**Comment by AndreiMaz** [comment]
Thanks. But we've decided to revert back that commit and re-do it more elegant way. Thanks again!
