### ISSUE TITLE
Price and OldPrice values in ProductOverviewModel

### ISSUE THREAD

**Issue by ayberkcal** [nopSolutions/nopCommerce#3393]
nopCommerce version: 4.10

Price and OldPrices decimal forms sometime need developing theme. May add this properties on ProductOverviewModel.

**Comment by RomanovM** [comment]
These properties are already in the [model](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Models/Catalog/ProductOverviewModel.cs#L31). Could you please clarify what you mean?
