### ISSUE TITLE
Registration of services

### ISSUE THREAD

**Issue by vlapenkov** [nopSolutions/nopCommerce#3394]
Good day!
I'm .NET core developer and your project is intresting to me in some approaches.
But I can't find source file of registration of dependencies in Startup.cs. 
After 'services.ConfigureStartupConfig<NopConfig>(configuration.GetSection("Nop"));'  i lost.
Please give me link to it.

**Comment by AndreiMaz** [comment]
Please post all questions on our forums. We use GitHub for work items only
