### ISSUE TITLE
Azure App Service multi instance - more than 50% requests (500) Internal Server Error

### ISSUE THREAD

**Issue by srrl** [nopSolutions/nopCommerce#3395]
nopCommerce version: 4.10

**Steps to reproduce the problem:** 
1) Install default NopCommerce instance on Azure App Service & Azure SQL (e.g. from Azure Marketplace)
![image](https://user-images.githubusercontent.com/16628480/47635565-4c947d80-dbba-11e8-8e74-c806063d61f9.png)
2) Scale out (App Service plan) to 2 instances or more
![image](https://user-images.githubusercontent.com/16628480/47635595-6cc43c80-dbba-11e8-887f-73998755f9dd.png)
3) Run simple load test in Azure DevOps (VSTS). e.g. HTTP method GET against store homepage, category page or/and product page 
![image](https://user-images.githubusercontent.com/16628480/47635636-92514600-dbba-11e8-8756-42d8f7704a51.png)

**Expected behavior:**
Application scales out according to Instance Count and will return 200 Response until it will reach CPU/Memory limit

**Actual behavior:**
Application returns 500 Internal Server Error for more than 50% of the requests regardless of load level.
![image](https://user-images.githubusercontent.com/16628480/47635866-49e65800-dbbb-11e8-9217-f4aa2671c01c.png)
![image](https://user-images.githubusercontent.com/16628480/47635897-5ff41880-dbbb-11e8-842d-4c5a1d28f81e.png)

> Log level - Error
Short message - The remote server returned an error: (500) Internal Server Error.
Full message - 
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at Nop.Services.Tasks.TaskThread.Run() in E:\nopCommerce\sources\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 65

**Comment by angeor2** [comment]
As posted to [this thread](https://www.nopcommerce.com/boards/t/49851/serious-iis-application-pool-recycling-bugdesign-flaw.aspx?p=9) I managed to consistently run multiple instances by setting Nop:UsePluginsShadowCopy  to false and deleting all the deps files for the plugins. 

Setting  CopyLockedPluginAssembilesToSubdirectoriesOnStartup to true did not work, as sometimes I got System.UnauthorizedAccessException and instances failed to start. Whenever some of the instances did not start I was getting the aforementioned System.Net.WebException at the same time the Send email task was triggered.

**Comment by ajhena** [comment]
Any updates on this? I am experiencing this issue just on deployment. I have 4.1 and the UsePluginsShadowCopy set to false and it isn't helping. Would it make sense to just turn off the tasks. This is causing me major problems with my site.

**Comment by skoshelev** [comment]
Hi @srrl. The 500 error from the screenshot is not related to shadow copying, the problem seems to be related to the incorrect setting of the store URL address and requests from the scheduled task cannot be executed. In version 4.20, we improved the informativeness of error messages in the system on a schedule tasks, and also solved the issue of disabling shadow copying. Pleace, try to reproduce this issue on the 4.20 beta version, and if the problem still exists, reopen this tiket with new ditails.
