### ISSUE TITLE
at checkout didn't show payment info

### ISSUE THREAD

**Issue by andysheu77** [nopSolutions/nopCommerce#3396]
1.nopCommerce version: 4.0
2. Expected behavior
show payment info
3. Actual behavior
didn't show
4. Steps to reproduce the problem
Disable "Billing address" step = true
ShippingRequired = false
BypassPaymentMethodSelectionIfOnlyOne = true
PaymentMethods.Count == 1
then payment info directly into first step.
5. Any private modifications you made to your nopCommerce
no

**Comment by DmitriyKulagin** [comment]
@andysheu77 
In the current version is not reproduced. But I checked how it works in version 4.0 and it turned out that the "Billing address" is in the first step. The decision was [here](https://github.com/nopSolutions/nopCommerce/issues/2823).
