### ISSUE TITLE
The datetime filter in the admin panel triggers the wrong button when pressing on enter

### ISSUE THREAD

**Issue by erikwuu** [nopSolutions/nopCommerce#3397]
nopCommerce version: tested with 4.1 and 4.0 on chrome.

When you press enter whilst having a datetime filter inputfield in the admin panel active, it triggers the wrong button in the form. This happens on all the admin list views.

Steps to reproduce the problem: 

Enter a random value in the datetime filter inputfield on the order list page or any other admin list page. When still active in the datetime input field (you can still type in the inputfield) press enter on the keyboard. It triggers the export button on the order page.

**Comment by RomanovM** [comment]
Thanks. Already [fixed](https://github.com/nopSolutions/nopCommerce/commit/2e97fb52999e2af33eb23e6cf319eb30b425c084)
