### ISSUE TITLE
Minor UI issue with delete feature of specification attributes options

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3398]
nopCommerce version: 4.10

Steps to reproduce the problem: 

1. Go to, Catalog -> Attributes -> Specification attributes in nopCommerce admin. For example, http://admin-demo.nopcommerce.com/Admin/SpecificationAttribute/Edit/5
2. Click on edit for any specification attribute that have option values
3. Go to options tab
4. Delete any option

You will see that option has been deleted but still an ajax loader shows in top right corner of your browser window. This issue is due to null value.

Source: https://www.nopcommerce.com/boards/t/55959/specification-attributes-option-delete-feature-have-bug.aspx

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/3c07d8945fafdbd7f48329022a267c58079b3a96
