### ISSUE TITLE
Re-design and simplify admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#34]
We also have to make the design responsive

More info at http://www.nopcommerce.com/boards/t/38847/re-design-and-simplify-admin-area-lets-discuss.aspx

**Comment by Helger53** [comment]
Allow for a page where the admin/webmaster can select which items / tabs to display to the day-to-day-admin and being able to pre-populate the various tickboxes and selection options for the day-to-day operator

**Comment by eadameg** [comment]
+1
You can simply add much more default values for admin like: 
adminareasettings.defaultgridpagesize
catalogsettings.defaultcategorypagesize
catalogsettings.defaultcategorypagesizeoptions
catalogsettings.defaultmanufacturerpagesize
catalogsettings.defaultmanufacturerpagesizeoptions
catalogsettings.defaultproductratingvalue
catalogsettings.defaultviewmode
customersettings.defaultavatarenabled
customersettings.defaultpasswordformat
customersettings.newslettertickedbydefault
datetimesettings.defaultstoretimezoneid
emailaccountsettings.defaultemailaccountid
frooglesettings.defaultgooglecategory
localizationsettings.defaultadminlanguageid
mediasettings.defaultimagequality
mediasettings.defaultpicturezoomenabled
seosettings.defaultmetadescription
seosettings.defaultmetakeywords
seosettings.defaulttitle
storeinformationsettings.defaultstoretheme
taxsettings.defaulttaxaddressid

**Comment by AndreiMaz** [comment]
oh, and since you're considering changing the admin UI/theme, I would like to suggest to right align all number/currency values in al table columns (for example reports etc). This design best practice improves readability and allows for easy comparison of values.

source: http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=9#161620

**Comment by mariannk** [comment]
Move setting "Ignore "limit per store" rules (sitewide):" to other place in UI, because it is used not only in catalog.

**Comment by mariannk** [comment]
Move Activity log (not Activity Types) from Configuration menu to Customers
