### ISSUE TITLE
Please make "Category" Auto Populate on Product Page

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3401]
nopCommerce version: 4.10

Steps to reproduce the problem: 
This is not a problem, just a suggestion. Could you make the "Catalog" populate on the "Product" List page like it does on the product detail page? I love it. I have tons of Categories and it would be nice to just TYPE and find it.

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.
