### ISSUE TITLE
IHttpClientFactory to create HttpClients

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3406]
nopCommerce version: 4.1

I've found in a bunch of places where `HttpClient` is initialized and immediately disposed:

```
using (var client = new HttpClient())
{
    ....
}
```

HttpClient should be [re-used throughout the life of an application](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1).

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly. 

A few articles have been written recently on the subject. [This](https://softwareengineering.stackexchange.com/a/330379/27318) StackOverflow answer give more details and the links to those articles and the reasons why it should be avoided.

Now we have a new interface `IHttpClientFactory `which can be registered and injected.

Some examples can be found [here](http://www.talkingdotnet.com/3-ways-to-use-httpclientfactory-in-asp-net-core-2-1/), [here](https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore) and [here](https://dotnetcoretutorials.com/2018/05/03/httpclient-factories-in-net-core-2-1/)

**Comment by dborovsky** [comment]
Guys I would like implement this.  Please select me as Assignee. Thank you

**Comment by AndreiMaz** [comment]
@dborovsky Thanks a lot. Please create a new pull request

**Comment by dborovsky** [comment]
@AndreiMaz  Strange, I have founded only two place where instance of HttpClient is created and disposed. This is:

1. `Nop.Web.Framework\Security\Captcha\GReCaptchaValidator.cs`
2. `Factories\CommonModelFactory.cs`

I have not seen anywhere.

**Comment by Leftyx** [comment]
@dborovsky: What I have done in my fork is to create in `NopEngine.ConfigureServices` a named `HttpClient`:

```
services.AddHttpClient("named-client", c =>
{
	c.BaseAddress = new Uri("client-base-address");
	// c.DefaultRequestHeaders.Add("User-Agent", "user-agent");
	c.Timeout = TimeSpan.FromSeconds(30);
});
```

so that we could have different specialized client for a different **url/service** and inject `IHttpClientFactory`.

The client can be resolved using its name:

`var httpClient = this.HttpClientFactory.CreateClient("named-client");`

and it does not need to be disposed. Another options is to create specialized clients but that would make things a bit more complicated.

**Comment by dborovsky** [comment]
@RomanovM i created PR. Check please. Thank you
