### ISSUE TITLE
Slow duplicate products

### ISSUE THREAD

**Issue by oswit** [nopSolutions/nopCommerce#3407]
nopCommerce version: 4.10

Steps to reproduce the problem: 
With a complex product (3 languages) 2 variants with 3-4 options each and around 10 product specifications, the copy product is very slow. Generally on the same website we experienced a 2-3 seconds copy with a 'light' one and >60 seconds with 'heavy' products. The issue seems to be in Entity Framework. Would be good to delegate the DB this action with a stored procedure.

**Comment by AndreiMaz** [comment]
@skoshelev let's test in the latest version after moving away from EF

**Comment by exileDev** [comment]
Working well now.
Closed #3407
