### ISSUE TITLE
Idea to improve GetFullErrorTextAndRollbackEntityChanges

### ISSUE THREAD

**Issue by tuanv2t** [nopSolutions/nopCommerce#3408]
Sometime I got error in _contex.SaveChanges:
Here's my idea to improve 

 protected string GetFullErrorTextAndRollbackEntityChanges(DbUpdateException exception)
        {
            //rollback entity changes
            if (_context is DbContext dbContext)
            {
                var entries = dbContext.ChangeTracker.Entries()
                    .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified).ToList();

                entries.ForEach(entry =>
                {
                    try
                    {
                        entry.State = EntityState.Unchanged;
                    }
                    catch (InvalidOperationException)
                    {
                        // ignored
                    }
                });
            }

            //_context.SaveChanges();
            //Sometime I got error in _contex.SaveChanges and the actually exception will not be catched , => try to try catch here again
            try
            {
                _context.SaveChanges();
                return exception.ToString();
            }
            catch(Exception ex)
            {
                return ex.ToString();//let outer caller throw inner exception along with this message ( the inner exception is sometime the actually exception )
            }
            
        }

**Comment by skoshelev** [comment]
@tuanv2t Thank you for your help

Closed #3408

**Comment by tuanv2t** [comment]
You're welcome. I love nopCommerce so much.
