### ISSUE TITLE
Preview in multistore show wrong result

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3409]
nopCommerce version: 4.1

Steps to reproduce the problem: create Multistore web site
in Store1 go to admin panel and create product, and set limitation to Store2 map to category in Store2
then press preview button, in result product show in Store 1

**Comment by RomanovM** [comment]
It's by design. Customers with permission to manage products may also see unpublished or somehow limited products in a public store (preview).

**Comment by tigran-avdalyan** [comment]
@RomanovM 
i don't talk about permission , is it right that product from Store1 in preview mode show in Store2?
