### ISSUE TITLE
Find more ways to improve performance

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3414]
We already have separate work items with "performance" label (https://github.com/nopSolutions/nopCommerce/issues?q=is%3Aopen+is%3Aissue+label%3Aperformance). We have to find more ways to improve performance

**Comment by AndreiMaz** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/12451

**Comment by rodolphito** [comment]
@AndreiMaz is it practical to do #3432 ? It will definitely improve performance a lot, and open the doors to many more optimizations (like using DLL postprocessing tools)

**Comment by RobinSCU** [comment]
@AndreiMaz is this Issue or #3432 implemented in some way or just closed with no fix?

**Comment by rafafontana** [comment]
Any news on this. Razor View compilation improves performance a lot. Regards

**Comment by alinmircea** [comment]
https://www.nopcommerce.com/en/boards/topic/98139/performance-improvement-plugins-w-precompiled-razor-views#315677
