### ISSUE TITLE
RWD layouts was broken

### ISSUE THREAD

**Issue by yuessir** [nopSolutions/nopCommerce#3415]
nopCommerce version: 
4.10 with merging bugs fix branch
Steps to reproduce the problem: 
Touching the menu multiple times will see the situation likes followings:
![screenshot_20181117-200431_chrome_mosaic_20_9_40](https://user-images.githubusercontent.com/8326310/48661039-e4450780-eaa6-11e8-859d-88e988eae19c.jpg)
![screenshot_20181117-200315_chrome_mosaic_20_10_11](https://user-images.githubusercontent.com/8326310/48661040-e4450780-eaa6-11e8-9984-c15cf97c10d4.jpg)

How can I fix the problem? :{

**Comment by RomanovM** [comment]
Already fixed, see https://github.com/nopSolutions/nopCommerce/issues/3385
