### ISSUE TITLE
Bug in checkout

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#3416]
nopCommerce version: 4.1

Steps to reproduce the problem: We have a one Payment Method(No need to choose in checkout )
We  check Ship to the same address in settings.
but when we start checkout process we have this points
1.Billing Address
1.Payment Method
2.Payment Information
3.Confirm Order

Bug. we have to 1. points

we click Continue and automatically go to  Payment Information

Then we click back button and BUG
all points inactive.(we haven't Back and continue buttons, we can't click to points)

**Comment by DmitriyKulagin** [comment]
@ecommerce-tester Hi, I was not able to reproduce the error on the latest version, perhaps it was already fixed. Try to check it now, and if the error remains - send a video with it.

**Comment by nickotech2000** [comment]
I use 4.20. This still a problem
Repro

I use NGINX as proxy reverse and connect to Windows that contains NopCommerce. the NGINX use SSL with letsencrypt.

Looks like http://youripaddress/onepagecheckout  --> this page
