### ISSUE TITLE
Filtering support for the "shopping carts and wishlist" page (admin area)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3417]
We already have "Shopping cart type" dropdownlist. Let's also add filters such as:
1. Start date (the start date for the search when a product was added to cart)
2. End date (the start date for the search when a product was added to cart)
3. Product (similar to the order list page)
4.  Billing address country
5. Store

Source: https://www.nopcommerce.com/boards/t/56139/dear-nc-devs-please-add-filters-in-admin-to-current-shopping-carts.aspx

Related task https://github.com/nopSolutions/nopCommerce/issues/3305

**Comment by LubovKhokhlova** [comment]
Done
