### ISSUE TITLE
Search isn't working in Iphone

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3418]
nopCommerce version: 3.90

Steps to reproduce the problem: Use any iphone try to search any item which contains single quote(') in name. You won't able to find that item in search result. We tested it in iPhone X and iPhone 6s both have latest version of iOS. Also we aren't using Auto Complete mode

Here some links to solve this issue but I am not sure about performance impact
https://apple.stackexchange.com/questions/299505/ios-11-default-quotation-mark-changed-to-and
https://stackoverflow.com/questions/47055726/is-single-quote-handled-differently-on-ios-and-sierra
https://stackoverflow.com/questions/9401312/how-to-replace-curly-quotation-marks-in-a-string-using-javascript

**Comment by AndreiMaz** [comment]
cannot reproduce
