### ISSUE TITLE
Avatars and Gravatar Integration

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#342]
Can we please add Gravatar integration, so that when a user makes a comment (review, blog, news articles and forum), his Gravatar is displayed. 

As a Designer, this is near essential, plus it enhances nopCommerce's look and feel. 

And if a user has not tied their email with Gravatar, can we have the option for users to upload their Avatars, in My Account Info. 

Also have a look at FrontEndContributions fork 

Forum source: http://www.nopcommerce.com/boards/t/15628/avatars-and-gravatar-integration.aspx

**Comment by AndreiMaz** [comment]
should be done as plugin
