### ISSUE TITLE
Create API and support it

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#3421]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Nopcommerce 4.1 Api **not working**, 
https://github.com/SevenSpikes/api-plugin-for-nopcommerce **community not responding** 
Can Nopcommerce TEAM create own API Plugin?

**Comment by RomanovM** [comment]
Thanks for the suggestion. But we don't plan to do it right now
