### ISSUE TITLE
Clean project runs slow during debug, not problem for production

### ISSUE THREAD

**Issue by glararan** [nopSolutions/nopCommerce#3422]
nopCommerce version: 4.1

Steps to reproduce the problem:

1. Download source code
2. Debug source code

Via following steps I get 1.2 min delay until I get response. Also I am getting so many exceptions for Autofac.dll

screenshot from chrome: https://ctrlv.cz/shots/2018/11/20/bpjY.png

Steps for production build with 1.2s delay:
1. Download source code
2. Build source code
3. Run via Nop.Web.exe
4. No problem

I need to write plugin for customer so I need debug. I am new to nopCommerce.

**Comment by AndreiMaz** [comment]
@glararan it's juts a first-time run. it's OK for any asp.net application

**Comment by glararan** [comment]
What? If I re-run app or re-load page I get again 1.2min delay.. problem is not fixed
