### ISSUE TITLE
Order GUID reset while editing

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3424]
Source: https://www.nopcommerce.com/boards/t/56162/order-guid-reset-while-editing.aspx

**Comment by MaxMommersteeg** [comment]
The same is happening when updating the OrderStatus from admin window (`_OrderDetails.Info.cshtml` & `OrderController.cs`).

**Comment by LubovKhokhlova** [comment]
#3424 Closed
