### ISSUE TITLE
PayPal Standard Options missing

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3426]
Source: https://www.nopcommerce.com/boards/t/56163/missing-paypal-standard-options-missing.aspx and https://www.nopcommerce.com/boards/t/46984/redirect-home-page-paypal-standard-plugin.aspx

**Comment by varunnaresh1992** [comment]
Any updates on this Romanov ?

**Comment by SteveEmbry** [comment]
Can we expect this to be resolved in version 4.20?

**Comment by skoshelev** [comment]
Closed #3426
