### ISSUE TITLE
State Abbreviation Conflict, shows wrong state in pickup location

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3427]
nopCommerce version: 3.90

Steps to reproduce the problem: Add 2 same state abbreviation for 2 different country.
For eg. we added many contries state from here [state package](https://www.nopcommerce.com/p/1622/all-states-provinces-package.aspx)

In this if you checked, Italy have state Bari as BA & Brazil have Bahia as BA. This shows wrong state in pickup location. Instead of Bari it shows Bahia in our store

An issue is under CheckoutModelFactory.cs file Method = PrepareShippingAddressModel  
` var state = _stateProvinceService.GetStateProvinceByAbbreviation(x.StateAbbreviation);`
pass country information to get correct details.

**Comment by RuS984** [comment]
This issue is fixed for version 4.10. Please see this commit 
 (https://github.com/nopSolutions/nopCommerce/commit/e62f001c4881315fc4d39587e78b38a01079cf5b)
Closed
