### ISSUE TITLE
Disable autocomplete for "Password" inputs in admin area

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#3429]
(from premium support 14517)
If you are defining a user management page where a user can specify a new password for another person, and therefore you want to prevent autofilling of password fields, you can use autocomplete="new-password"; however, support for this value has not been implemented on Firefox.

Now we can use the following one - autocomplete="off" (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)

Let's do it for all password fields

**Comment by rudgr** [comment]
please also add Edit Topic to the list tx
