### ISSUE TITLE
Mobile sitemap

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#343]
A mobile sitemap that can be submitted to Google or Bing. Here is more information about what is needed to submit a mobile sitemap: http://support.google.com/webmasters/bin/answer.py?hl=en&answer=34648. 

But as our desktop and mobile versions can be accessed using the same URL I don't think that it's required 

Forum source: http://www.nopcommerce.com/boards/t/15125/nc-24-mobile-access.aspx

**Comment by AndreiMaz** [comment]
our desktop and mobile versions can be accessed using the same URL I don't think that it's required
