### ISSUE TITLE
robots.txt cart disallow

### ISSUE THREAD

**Issue by turbochris** [nopSolutions/nopCommerce#3430]
nopCommerce version: 
3.9+
Steps to reproduce the problem: 
Have a product that starts with "cart". If you are selling "cartier" watches, you will be in trouble. Manufacturer "cartier" and products starting with "cart" will NOT get indexed in google.

Suggestion:
Google supports end of line: "$". So change it to Disallow: /cart$

Issue is explained here:
https://developers.google.com/search/reference/robots_txt

**Comment by DmitriyKulagin** [comment]
Closed #3430
