### ISSUE TITLE
Facebook Shop - Logo in Facebook iframe  Multistore support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3431]
nopCommerce version: 4.1

Steps to reproduce the problem: If we have Multistore and each store have own Logo, when we use Facebook shop, in facebook show only one logo for all stores.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/facebook-shop/issues/6
@tigran-avdalyan could you please create tasks in the appropriate repositories
