### ISSUE TITLE
Building for release doesn't utilize precompilation of Razor views

### ISSUE THREAD

**Issue by devharis** [nopSolutions/nopCommerce#3432]
nopCommerce version: 4.10

Steps to reproduce the problem: 

When building for release nopCommerce doesn't utilize precompiled razor-views, something that comes out of the box with `dotnet core ^2.0`

I wonder if this is intentional or something that has been missed? Right now a initial page load for each page takes 3-5 seconds instead of 0.1-1s when razor view is compiled.

**Comment by RomanovM** [comment]
We cannot use precompiled views, cuz in this case it will be impossible to use themes (that in fact are separate views replaced on runtime)

**Comment by rodolphito** [comment]
It is possible to do this. Please reopen: https://stackoverflow.com/a/53955626/3558373  This is relevant for #3414

**Comment by rafafontana** [comment]
I think this is already done. In .net core 3.1 and up it is enable by default. You can see a dll call xxx.Views.dll that is being generated also. A cool thing you could see in nopcommerce code is de addition of the statement mvcBuilder.AddRazorRuntimeCompilation(); so this let you modify the code of the views in production and recompile the Views.dll at runtime.

**Comment by exileDev** [comment]
As per .NET 6 changes, there is no way to implement this feature in our current code architecture. Closed #3432

**Comment by alinmircea** [comment]
https://www.nopcommerce.com/en/boards/topic/98139/performance-improvement-plugins-w-precompiled-razor-views#315677

**Comment by danFbach** [comment]
The other thing to consider is that the only _real_ performance gain is on cold start. Once a page has been built at runtime, it is cached, so all you're really getting is a faster start time, not an overall faster application. So, if it makes developing other parts of the application more difficult (i.e. themes and plugins) then even though i would also like to see faster start times, I would see this as a net negative outcome.
