### ISSUE TITLE
Attribute combination - selected value is missing or wrong

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3433]
nopCommerce version: 4.1(admin-demo.nopcommerce.com)

Steps to reproduce the problem: When editing attribute combination selected values is missing or wrong.
![ac](https://user-images.githubusercontent.com/17789934/48982547-88f5c380-f0fd-11e8-8687-2b8c6b442a2b.gif)

in example see HDD and Software

P.S.
Make this values not editable(this info only for read)

**Comment by skoshelev** [comment]
Closed #3433

Can't reproduce on 4.20
