### ISSUE TITLE
Product combinations with SKU

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3435]
nopCommerce version: 4.1

Steps to reproduce the problem: We have product with SKU="111"
product have a combination with SKUs ={"222","333","444"}
But when we in Store we select a combination the SKU not changing, and in order to.
Not show combination SKUs in order in admin area to.

**Comment by RomanovM** [comment]
@tigran-avdalyan Could you please clarify what do you mean
