### ISSUE TITLE
Add Product Cost to Attribute Combinations view

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3437]
nopCommerce version: 4.1

Steps to reproduce the problem: Add Product Cost to Attribute Combinations view for calculate wright Profit.
Please see
https://www.nopcommerce.com/boards/t/45817/add-product-cost-to-attribute-combinations-view.aspx

**Comment by tigran-avdalyan** [comment]
please see
#2030

**Comment by RomanovM** [comment]
Duplicated

**Comment by tigran-avdalyan** [comment]
@RomanovM  Where is Duplicate?????
