### ISSUE TITLE
JS exclude from bundle not working

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3439]
nopCommerce version: 4.1

Steps to reproduce the problem: 
`Html.AppendScriptParts(ResourceLocation.Head, "~/lib/test.js",true);`

not working, receiving Cannot convert from Nop.Web.Framework.UI.ResourceLocation to string error on VS

**Comment by RomanovM** [comment]
It works like a charm. Just specify a parameter name "excludeFromBundle: true"

**Comment by bulutkartal** [comment]
I guess [documentation ](http://docs.nopcommerce.com/display/en/Adding+CSS+and+JS+resource+files+into+nopCommerce+Plugin)should change

also how do we deal with external urls. Then throws "ArgumentException: The path in 'value' must start with '/'." exception.
