### ISSUE TITLE
Product Specifcation Attribute Values Not Localizable

### ISSUE THREAD

**Issue by PamperBoy** [nopSolutions/nopCommerce#3442]
nopCommerce version: 3.90

Product Specifcation Attribute Name Labels are localizable, but Product Specifcation Attribute Values are not. Especially the "Custom text" & "Custom html text" attribute types.

I'd like to see that the values are also localizable. Is this something that can be implemented?

**Comment by RomanovM** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/2417
