### ISSUE TITLE
Shipment List Page - have Duplicate default select option in Country drop-down

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3444]
nopCommerce version: 4.10

Steps to reproduce the problem: 
1. Go to Admin panel
2. Navigate to Shipments list page under Sales menu (http://admin-demo.nopcommerce.com/Admin/Order/ShipmentList)

**There duplicate default select option under country drop-down.**
[See here](https://i.ibb.co/LPw09k2/shipment-2.png)

**Comment by DmitriyKulagin** [comment]
Closed #3444
