### ISSUE TITLE
Javascript encoding when using "alert" or other javascript functions

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3447]
nopCommerce version: 4.10

Steps to reproduce the problem: 

I wanted to point out that if some text strings used as messages within the nopcommerce code are inserted with apostrophes (considered special characters) there may be problems with the operation of nopCommerce. Example:

admin.catalog.products.specificationattributes.selectoption | Select the option for the specification attribute | In Italian: Seleziona l'opzione per l'attributo di specificazione

The presence of apostrophes in the string "Seleziona l'opzione per l'attributo di specificazione  "

Causes the following error to make it impossible to enter product specification attributes:

"Uncaught SyntaxError: missing) after argument list"

Impact code:

  if (specificationAttributeOptionId === null) {
                                    //some validation
                                    if (attributeTypeId == 0) {
                                        //option
                                        alert('Seleziona l'opzione per l'attributo di specificazione');     <<<<<<<<<<<<<
                                } else {
                                    //other (text, hyperlink, etc)
                                    alert('Prima di tutto, crea almeno un'opzione per l'attributo di specificazione');
                                }
                            } else {
                                    $('#addProductSpec').attr('disabled', true);  

We should use "JavaScriptEncoder.Default.Encode"

**Comment by RomanovM** [comment]
Related with https://github.com/nopSolutions/nopCommerce/issues/3119

**Comment by DmitriyKulagin** [comment]
Resolved in #3119
