### ISSUE TITLE
Passwords in EmailAccount table are not encrypted

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#345]
We should use "encryption key". do not forget to update them when we change encryption key in admin area.The question is how we should upgrade (next version)?

In the [EmailAccount] table, the passwords for the email accounts is not being ecnrypted, its a very big vulnerability, since no one besides the owner of the account should have access to any password whatsoever, and now anyone with access to the db can lookup the password, which is extremely vulnerable issue.

Source: http://www.nopcommerce.com/boards/t/43865/email-accounts-not-hashing-password.aspx
See also: https://www.nopcommerce.com/boards/topic/70278/420-email-account-password-is-saved-in-plain-text-in-database#285290
Similar task - #451

**Comment by rudgr** [comment]
maybe should add this one as well to v3.90?

Encrypt some sensitive settings #451
https://github.com/nopSolutions/nopCommerce/issues/451

**Comment by AndreiMaz** [comment]
the same as https://github.com/nopSolutions/nopCommerce/issues/451

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
