### ISSUE TITLE
skipPaymentWorkflow

### ISSUE THREAD

**Issue by wooncherk** [nopSolutions/nopCommerce#3458]
nopCommerce version: 4.10

Steps to reproduce the problem: N/A

In OrderProcessingService, why aren't we using the method **IsPaymentWorkflowRequired()** to check if we need to skip payment workflow?

![image](https://user-images.githubusercontent.com/1028708/49931018-e614b600-ff00-11e8-822f-af12ccb8f884.png)

**Comment by skoshelev** [comment]
Closed #3458
