### ISSUE TITLE
Stripe payment processor

### ISSUE THREAD

**Issue by andrejpk** [nopSolutions/nopCommerce#3461]
nopCommerce version: 4.1

Before I create a pull request (I'm not quite ready), I wrote a Stripe plug-in for NopCommerce. Stripe is a great payment processor (at least in the US) but unfortunately I couldn't find a modern supported Stripe Plug-in I liked. I wrote one this weekend and it seems to be working well so far. It's on github here: https://github.com/andrejpk/nopCommerce/tree/develop/src/Plugins/Nop.Plugin.Payments.Stripe 

As much as possible, I modeled it on the Square plug-in. 

Is there interest in merging this into NopCommerce for it to be maintained in that tree going forward? Otherwise I can break it into its own project and repo.

**Comment by RomanovM** [comment]
@andrejpk Thanks for the suggestion. You can leave this project in your repository and also share plugin in our marketplace as well.
