### ISSUE TITLE
Encode grid column titles

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3464]
When you have ' char in the grid column title, then it won't rendered properly. For example, for Italian language pack it won't work - https://www.nopcommerce.com/boards/t/57409/gdpr-configuration-error.aspx

Let's fix it as part of the https://github.com/nopSolutions/nopCommerce/issues/75 task (not in KendoUI as it'll require a lot of changes)

![image](https://user-images.githubusercontent.com/5019111/50138890-271a1b00-02b1-11e9-98ef-f1eca6a4b7c1.png)

**Comment by DmitriyKulagin** [comment]
This is taken into account when developing a template for moving to DataTables.
