### ISSUE TITLE
Bottleneck for performance due to GenerateScripts call using a lock

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#3466]
nopCommerce version: 4.1

The message mentions the Theme "Motion", but this problem would occour without the motion theme as well.

I got the following info from Microsoft Azure. We have a premium support plan, and they offer their thoughts on things. There seems to be a problem (lock) with generatescripts. The method is called from layout view.

Active threads are showing a lock contention (waiting on a lock) - this takes place when calling Monitor.Enter :

6 threads [stats]: 22 29 30 32 35 39
    77cff29c ntdll!NtWaitForMultipleObjects+0xc

    74f22080 KERNELBASE!WaitForMultipleObjectsEx+0xf0

    (Inline) coreclr!WaitForMultipleObjectsEx_SO_TOLERANT+0x13

    6b26a8a6 coreclr!Thread::DoAppropriateAptStateWait+0x39

    6b26a5c8 coreclr!Thread::DoAppropriateWaitWorker+0x248

    6b26a327 coreclr!Thread::DoAppropriateWait+0x79

    6b26a29c coreclr!CLREventBase::WaitEx+0x39

    6b31ffe4 coreclr!CLREventBase::Wait+0x1a

    6b31fdff coreclr!AwareLock::EnterEpilogHelper+0x108

    6b31fcdc coreclr!AwareLock::EnterEpilog+0x51

    6b31fc82 coreclr!AwareLock::Enter+0x92

    (Inline) coreclr!SyncBlock::EnterMonitor+0x7

    (Inline) coreclr!ObjHeader::EnterObjMonitor+0xc

    (Inline) coreclr!Object::EnterObjMonitor+0x12

    6b31b0fd coreclr!JIT_MonEnter_Helper+0xd0

    6b31ade4 coreclr!JIT_MonReliableEnter_Portable+0x114

    205d8241 Nop_Web_Framework!Nop.Web.Framework.UI.PageHeadBuilder.GenerateScripts(Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x479

    205d72be Nop_Web_Framework!Nop.Web.Framework.UI.LayoutExtensions.NopScripts(Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper, Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x46

    209f13b4 31wn1hyg_u03!AspNetCore.Themes_Motion_Views_Shared__Root_Head+<>c__DisplayClass9_0+<<ExecuteAsync>b__1>d.MoveNext()+0x174

 

5 threads [stats]: 33 34 38 40 42

    77cff29c ntdll!NtWaitForMultipleObjects+0xc

    74f22080 KERNELBASE!WaitForMultipleObjectsEx+0xf0

    (Inline) coreclr!WaitForMultipleObjectsEx_SO_TOLERANT+0x13

    6b26a8a6 coreclr!Thread::DoAppropriateAptStateWait+0x39

    6b26a5c8 coreclr!Thread::DoAppropriateWaitWorker+0x248

    6b26a327 coreclr!Thread::DoAppropriateWait+0x79

    6b26a29c coreclr!CLREventBase::WaitEx+0x39

    6b31ffe4 coreclr!CLREventBase::Wait+0x1a

    6b31fdff coreclr!AwareLock::EnterEpilogHelper+0x108

    6b31fcdc coreclr!AwareLock::EnterEpilog+0x51

    6b31fc82 coreclr!AwareLock::Enter+0x92

    (Inline) coreclr!SyncBlock::EnterMonitor+0x7

    (Inline) coreclr!ObjHeader::EnterObjMonitor+0xc

    (Inline) coreclr!Object::EnterObjMonitor+0x12

    6b31b0fd coreclr!JIT_MonEnter_Helper+0xd0

    6b31ade4 coreclr!JIT_MonReliableEnter_Portable+0x114

    205d8241 Nop_Web_Framework!Nop.Web.Framework.UI.PageHeadBuilder.GenerateScripts(Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x479

    205d72be Nop_Web_Framework!Nop.Web.Framework.UI.LayoutExtensions.NopScripts(Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper, Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x46

    20257f87 31wn1hyg_u03!AspNetCore.Themes_Motion_Views_Shared__Root_Head+<>c__DisplayClass9_0+<<ExecuteAsync>b__0>d.MoveNext()+0x6d7

    2025680f System_Private_CoreLib!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.IO.Stream+<CopyToAsyncInternal>d__28, System.Private.CoreLib]](<CopyToAsyncInternal>d__28 ByRef)+0x933df07

    202566f0 31wn1hyg_u03!AspNetCore.Themes_Motion_Views_Shared__Root_Head+<>c__DisplayClass9_0.<ExecuteAsync>b__0()+0x30

 

4 threads [stats]: 15 18 25 27

    77cff29c ntdll!NtWaitForMultipleObjects+0xc

    74f22080 KERNELBASE!WaitForMultipleObjectsEx+0xf0

    (Inline) coreclr!WaitForMultipleObjectsEx_SO_TOLERANT+0x13

    6b26a8a6 coreclr!Thread::DoAppropriateAptStateWait+0x39

    6b26a5c8 coreclr!Thread::DoAppropriateWaitWorker+0x248

    6b26a327 coreclr!Thread::DoAppropriateWait+0x79

    6b26a29c coreclr!CLREventBase::WaitEx+0x39

    6b31ffe4 coreclr!CLREventBase::Wait+0x1a

    6b31fdff coreclr!AwareLock::EnterEpilogHelper+0x108

    6b31fcdc coreclr!AwareLock::EnterEpilog+0x51

    6b31fc82 coreclr!AwareLock::Enter+0x92

    (Inline) coreclr!SyncBlock::EnterMonitor+0x7

    (Inline) coreclr!ObjHeader::EnterObjMonitor+0xc

    (Inline) coreclr!Object::EnterObjMonitor+0x12

    6b31b0fd coreclr!JIT_MonEnter_Helper+0xd0

    6b31ade4 coreclr!JIT_MonReliableEnter_Portable+0x114

    205d8241 Nop_Web_Framework!Nop.Web.Framework.UI.PageHeadBuilder.GenerateScripts(Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x479

    205d72be Nop_Web_Framework!Nop.Web.Framework.UI.LayoutExtensions.NopScripts(Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper, Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x46

    209f13b4 31wn1hyg_u03!AspNetCore.Themes_Motion_Views_Shared__Root_Head+<>c__DisplayClass9_0+<<ExecuteAsync>b__1>d.MoveNext()+0x174

 

Note: there are many more threads just like this - above is just a part of total threads that are showing same behavior (waiting on a lock).

 

Owner of this lock is in the middle of processing and almost all other threads are waiting until this one finishes generating these scripts... *current* callstack looks like:

 

1 thread [stats]: 26

    (Inline) ntdll!RtlpEncodeDecodeOffsets+0x15

    (Inline) ntdll!RtlpSubSegmentAllocate+0x1a9

    (Inline) ntdll!RtlpLocalInfoAllocFromCache+0x1b3

    77cd43e9 ntdll!RtlpLowFragHeapAllocFromContext+0x219

    77cd40bc ntdll!RtlpAllocateHeapInternal+0xcc

    (Inline) ntdll!RtlpHpHeapAllocateRedirectLayer+0x17

    77cd3fe2 ntdll!RtlAllocateHeap+0x32

   5e57249a MicrosoftInstrumentationEngine_x86!_malloc_base+0x38

    5e564936 MicrosoftInstrumentationEngine_x86!operator new+0x1a

    (Inline) MicrosoftInstrumentationEngine_x86!std::_Default_allocate_traits::_Allocate+0x6

    (Inline) MicrosoftInstrumentationEngine_x86!std::_Allocate+0x37

    (Inline) MicrosoftInstrumentationEngine_x86!std::allocator<wchar_t>::allocate+0x39

    (Inline) MicrosoftInstrumentationEngine_x86!std::vector<wchar_t,std::allocator<wchar_t> >::_Buy+0x60

    5e53cdc0 MicrosoftInstrumentationEngine_x86!std::vector<wchar_t,std::allocator<wchar_t> >::vector<wchar_t,std::allocator<wchar_t> >+0x90

    5e55b22b MicrosoftInstrumentationEngine_x86!MicrosoftInstrumentationEngine::CTokenType::GetName+0x10b

    5e5383e2 MicrosoftInstrumentationEngine_x86!MicrosoftInstrumentationEngine::CMethodInfo::InitializeFullName+0x392

    5e53800b MicrosoftInstrumentationEngine_x86!MicrosoftInstrumentationEngine::CMethodInfo::GetFullName+0x3b

    5db01846 Microsoft_InstrumentationEngine_Extensions_Base_x86!Agent::Interop::CInteropInstrumentationHandler::ShouldInstrument+0x2d6

    5db01153 Microsoft_InstrumentationEngine_Extensions_Base_x86!Agent::Interop::CInteropInstrumentationHandler::AllowInline+0x43

    5daf426a Microsoft_InstrumentationEngine_Extensions_Base_x86!CHostExtensionBase::InternalAllowInlineSite+0x4a

    5dae9be3 Microsoft_InstrumentationEngine_Extensions_Base_x86!CInstrumentationMethodBase::AllowInlineSite+0xee3

    5e553dfd MicrosoftInstrumentationEngine_x86!MicrosoftInstrumentationEngine::CProfilerManager::CallAllowInlineOnInstrumentationMethods+0xad

    5e54b81e MicrosoftInstrumentationEngine_x86!MicrosoftInstrumentationEngine::CProfilerManager::JITInlining+0x36e

    6b4c8859 coreclr!EEToProfInterfaceImpl::JITInlining+0x6b

    6b3dcd2b coreclr!CEEInfo::canInline+0x1441ab

    6a7c19c5 clrjit!<lambda_646fd2c196a565593c9d037047c28595>::operator()+0xc5

    6b33c99b coreclr!CEEInfo::runWithErrorTrap+0x3b

    (Inline) clrjit!Compiler::eeRunWithErrorTrapImp+0x2f

    (Inline) clrjit!Compiler::eeRunWithErrorTrap+0x2f

    (Inline) clrjit!Compiler::impCheckCanInline+0x59

    6a74e027 clrjit!Compiler::impMarkInlineCandidate+0x2a7

    6a74f774 clrjit!Compiler::impImportCall+0x1574

    6a7b4c83 clrjit!Compiler::impImportBlockCode+0x8d3

    6a7b35fd clrjit!Compiler::impImportBlock+0x9d

    6a7b339e clrjit!Compiler::impImport+0x2de

    (Inline) clrjit!Compiler::fgImport+0x1e

    6a792a43 clrjit!Compiler::compCompile+0x93

    6a7bedfc clrjit!Compiler::compCompileHelper+0x28c

    6a7beaab clrjit!Compiler::compCompile+0x20b

    6a7be0af clrjit!jitNativeCode+0x18f

    6a7bdf06 clrjit!<lambda_f3433d8d13e7b67171705432d4f18ff9>::operator()+0xd8

    6b33c99b coreclr!CEEInfo::runWithErrorTrap+0x3b

    (Inline) clrjit!Compiler::eeRunWithErrorTrapImp+0x64

    (Inline) clrjit!Compiler::eeRunWithErrorTrap+0x64

    (Inline) clrjit!Compiler::fgInvokeInlineeCompiler+0x1b0

    (Inline) clrjit!Compiler::fgMorphCallInlineHelper+0x230

    (Inline) clrjit!Compiler::fgMorphCallInline+0x230

    6a7c297f clrjit!Compiler::fgInline+0x4ef

    6a7942dc clrjit!Compiler::fgMorph+0x70

    6a792bc6 clrjit!Compiler::compCompile+0x216

    6a7bedfc clrjit!Compiler::compCompileHelper+0x28c

    6a7beaab clrjit!Compiler::compCompile+0x20b

    6a7be0af clrjit!jitNativeCode+0x18f

    6a7bcd1b clrjit!CILJit::compileMethod+0x6b

    (Inline) coreclr!invokeCompileMethodHelper+0x4a

    6b277e5c coreclr!invokeCompileMethod+0xa7

    6b2772e9 coreclr!CallCompileMethodWithSEHWrapper+0x38

    6b27ae37 coreclr!UnsafeJitFunction+0x537

    6b276c1d coreclr!MethodDesc::JitCompileCodeLocked+0xd1

    6b276a94 coreclr!MethodDesc::JitCompileCodeLockedEventWrapper+0x92

    6b2765f9 coreclr!MethodDesc::JitCompileCode+0x379

    (Inline) coreclr!MethodDesc::PrepareILBasedCode+0x11d

    (Inline) coreclr!MethodDesc::PrepareCode+0x11d

    (Inline) coreclr!MethodDesc::PrepareInitialCode+0x13c

    6b2a7378 coreclr!MethodDesc::DoPrestub+0x508

    6b2a6d57 coreclr!PreStubWorker+0x207

    6b36b759 coreclr!ThePreStub+0x11

    20a8c085 NUglify!NUglify.JavaScript.Syntax.SwitchCase.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a8f842 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.SwitchStatement)+0x1da

    20a8bf3d NUglify!NUglify.JavaScript.Syntax.SwitchStatement.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7bbe3 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.IfStatement)+0x19b

    20acdfad NUglify!NUglify.JavaScript.Syntax.IfStatement.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a77e10 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.BlockStatement)+0x290

    20a7d7ea NUglify!NUglify.JavaScript.Visitors.OutputVisitor.OutputBlockWithBraces(NUglify.JavaScript.Syntax.BlockStatement)+0x4a

    20a7bce8 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.IfStatement)+0x2a0

    20acdfad NUglify!NUglify.JavaScript.Syntax.IfStatement.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a77e10 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.BlockStatement)+0x290

    20a7a35c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.OutputFunctionArgsAndBody(NUglify.JavaScript.Syntax.FunctionObject)+0x46c

    20a79d1c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.FunctionObject)+0x274

    20acd7ad NUglify!NUglify.JavaScript.Syntax.FunctionObject.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7970d NUglify!NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(NUglify.JavaScript.Syntax.AstNode, Boolean)+0x35

    20a7e2ba NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.ObjectLiteralProperty)+0x6a

    20ace77d NUglify!NUglify.JavaScript.Syntax.ObjectLiteralProperty.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7d260 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.AstNodeList)+0x1d0

    20a7cf68 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.ObjectLiteral)+0x128

    20ace6fd NUglify!NUglify.JavaScript.Syntax.ObjectLiteral.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7970d NUglify!NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(NUglify.JavaScript.Syntax.AstNode, Boolean)+0x35

    20a79a0c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.CallExpression)+0x2cc

    20acd715 NUglify!NUglify.JavaScript.Syntax.CallExpression.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a77e10 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.BlockStatement)+0x290

    20a7a35c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.OutputFunctionArgsAndBody(NUglify.JavaScript.Syntax.FunctionObject)+0x46c

    20a79d1c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.FunctionObject)+0x274

    20acd7ad NUglify!NUglify.JavaScript.Syntax.FunctionObject.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7970d NUglify!NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(NUglify.JavaScript.Syntax.AstNode, Boolean)+0x35

    20a79a0c NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.CallExpression)+0x2cc

    20acd715 NUglify!NUglify.JavaScript.Syntax.CallExpression.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a7970d NUglify!NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(NUglify.JavaScript.Syntax.AstNode, Boolean)+0x35

    20a79337 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.UnaryExpression)+0x287

    20acd695 NUglify!NUglify.JavaScript.Syntax.UnaryExpression.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a77e10 NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Visit(NUglify.JavaScript.Syntax.BlockStatement)+0x290

    20acf1fd NUglify!NUglify.JavaScript.Syntax.BlockStatement.Accept(NUglify.JavaScript.Visitors.IVisitor)+0x15

    20a779fd NUglify!NUglify.JavaScript.Visitors.OutputVisitor.Apply(System.IO.TextWriter, NUglify.JavaScript.Syntax.AstNode, NUglify.JavaScript.CodeSettings)+0x55

    20d5f5f4 NUglify!NUglify.Uglify.Js(System.String, System.String, NUglify.JavaScript.CodeSettings)+0x1fc

    20d5ef2f dotnet_bundle!BundlerMinifier.BundleMinifier.MinifyJavaScript(BundlerMinifier.Bundle, BundlerMinifier.MinificationResult)+0x3f

    20572c20 dotnet_bundle!BundlerMinifier.BundleMinifier.MinifyBundle(BundlerMinifier.Bundle)+0xd8

    204d5f5f dotnet_bundle!BundlerMinifier.BundleFileProcessor.ProcessBundle(System.String, BundlerMinifier.Bundle)+0x18f

    204d5082 dotnet_bundle!BundlerMinifier.BundleFileProcessor.Process(System.String, System.Collections.Generic.IEnumerable`1<BundlerMinifier.Bundle>)+0x92

    205d8359 Nop_Web_Framework!Nop.Web.Framework.UI.PageHeadBuilder.GenerateScripts(Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x591

    205d72be Nop_Web_Framework!Nop.Web.Framework.UI.LayoutExtensions.NopScripts(Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper, Microsoft.AspNetCore.Mvc.IUrlHelper, Nop.Web.Framework.UI.ResourceLocation, System.Nullable`1<Boolean>)+0x46

    209f13b4 31wn1hyg_u03!AspNetCore.Themes_Motion_Views_Shared__Root_Head+<>c__DisplayClass9_0+<<ExecuteAsync>b__1>d.MoveNext()+0x174

 

**So what we can see from above is that the component (the GenerateScripts) is calling this NUglify component which then processes some JavaScript and triggers JIT compilation and at this moment, the injected profiler is simply intercepting that call (seems normal).**

We hope that all this information helps you.  

SUMMARY:

**- There is definitely a bottleneck for performance due to GenerateScripts call using a lock.**
- This call may be taking a bit longer.
- It should be checked if this is a one-time operation - if so, this has minimal effect
- It should be cheked/confirmed that this only happens on or around process startup - again, if so, small impact overall unless process is restarting frequently
- It should be checked if this dynamic generation of scripts is even necessary?  Can this be just generated statically once and avoid this runtime generating of scripts? (suggestion: avoid unnecessary operations if possible)

**Comment by skoshelev** [comment]
Unfortunately, we can’t refuse to block in this place, but I was able to reduce the number of locks

Closed #3466
