### ISSUE TITLE
Add the ability, when updating nopcommerce, to perform the logic necessary for migrating from one version to another

### ISSUE THREAD

**Issue by LubovKhokhlova** [nopSolutions/nopCommerce#3472]

**Comment by miguelgimenez** [comment]
Hi,

For our own plugins we use DbUp http://dbup.github.io/ to run migrations both as we add new features in the same nop version or as we update from one nop version to the next.

We do it so each plugin that uses db tables can evolve independently and constantly.

This could also be used for Nop Core, we can share our code if this could benefit others.

Regards,

Miguel

**Comment by AndreiMaz** [comment]
done in 4.30

**Comment by ecommerce-tester** [comment]
@AndreiMaz How we can update from Nopcommerce 4.30 to 4.40 in admin area?
