### ISSUE TITLE
Setup Dependabot to keep nopCommerce's NuGet packages up-to-date.

### ISSUE THREAD

**Issue by MaxMommersteeg** [nopSolutions/nopCommerce#3474]
Keeping NuGet packages up-to-date is a task that is often forgotten. Dependabot is a service that automatically updates NuGet packages by opening up pull requests. This way nopCommerce's packages will always be up-to-date and this will save us some time doing it ourselves.

The service is free for open source projects.

Setup is really easy:
https://dependabot.com/

**Comment by RomanovM** [comment]
Thanks for the suggestion.
We always keep track of updates (not for only NuGet packages) and update as necessary. Details there https://github.com/nopSolutions/nopCommerce/issues/196.
No need to delegate it to the bot.
