### ISSUE TITLE
Customer Can Buy Selected Products

### ISSUE THREAD

**Issue by ayberkcal** [nopSolutions/nopCommerce#3476]
Currently customer must buy all products in shopping cart. But some customers would like buy selected products without remove any product from shopping cart. What do you think about nopcommerce team about this feature?

**Comment by RomanovM** [comment]
Thanks for the suggestion. We decide not to implement it and leave for the customization.

**Comment by ayberkcal** [comment]
I think you should reconsider your decision. Because NopCommerce provide B2B and/or B2C also multi store features. This means nopcommerce users could create different e-commerce websites for wide range customers. Buy selected products in cart feature Ican be very important to have this feature. And also this customization is very hard without touch nop core codes.

**Comment by MaxMommersteeg** [comment]
Would using the wish list functionality be an option for those customers?

**Comment by ayberkcal** [comment]
> Would using the wish list functionality be an option for those customers?

Yes it may solve problem but always i try to avoid workarounds.
