### ISSUE TITLE
TypeConverters for list are not registered if IgnoreStartupTasks is set to true.

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3479]
nopCommerce version: 4.10

Steps to reproduce the problem: Set `IgnoreStartupTasks` in `appsettings.json`.

Setting `IgnoreStartupTasks` to **false** in app settings does not trigger `RunStartupTasks` (**NopEngine**) which doesn't execute `TypeConverterRegistrationStartUpTask`.

Some of the settings of type List (IE: **SeoSettings.ReservedUrlRecordSlugs**) are not converted cause they don't pass this [validation](https://github.com/nopSolutions/nopCommerce/blob/c418122223ecd09c690cecaf120cda378bff202d/src/Libraries/Nop.Services/Configuration/SettingService.cs#L376):

```
if (!TypeDescriptor.GetConverter(prop.PropertyType).CanConvertFrom(typeof(string)))
        continue;
```

Is this an expected behavior ? Shouldn't type converters always be set ?

**Comment by AndreiMaz** [comment]
@Leftyx Could you please clarufy when you set **IgnoreStartupTasks** to **false**?

**Comment by Leftyx** [comment]
> 
> 
> @Leftyx Could you please clarufy when you set **IgnoreStartupTasks** to **false**?

@AndreiMaz: Removing **IIgnoreStartupTasks** fixes the problem. Thanks.
