### ISSUE TITLE
Item price increased by 1 when using rounding up with 1.00 intervals

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3480]
nopCommerce version: 3.90

Steps to reproduce the problem: The problem comes when you use rounding up with 1.00 intervals, On product page it shows price increase by 1 EUR. EUR is primary currency in our store.
For e.g if we have EUR 140 price on Catalog but it shows EUR 141 on product detail page. Create product with below conditions or consider it as Steps to reproduce issue.
1) Create Product with selling price 163.11 EUR without VAT. product must have attributes like "size" but price will remain same.
2) Add VAT 22% & show price including VAT in entire site so price is EUR 199 including VAT
3) Now create discount with 30% of price & Add this product
4) Now when you visit the catalog page it shows EUR 140 price incl. VAT & in product page first it shows EUR 140 but then there is call happen to get attribute price which increase product price with EUR 1

ShoppingCartController.cs
`public virtual ActionResult ProductDetails_AttributeChange(int productId, bool validateAttributeConditions, bool loadPicture, FormCollection form)`

in this function you execute this lines of code 
` decimal finalPrice = _priceCalculationService.GetUnitPrice(product,
                    _workContext.CurrentCustomer,
                    ShoppingCartType.ShoppingCart,
                    1, attributeXml, 0,
                    rentalStartDate, rentalEndDate,
                    true, out discountAmount, out scDiscounts);`
in this GetUnitPrice you guys round up price & its reason to increase EUR 1 in detail page. like above scenario it makes product price EUR 114.177 to EUR 115.

After 2-3 lines code you are calling `price = _priceFormatter.FormatPrice(finalPriceWithDiscount);`
which again round up price. consider with above eg.
115 * 1.22(VAT) = 140.3 incl. VAT makes price on product detail page = EUR 141
where as result must be like below
114.177 * 1.22(VAT) = 139.295 make price = EUR 140

In pricecalculationservice.cs ` public virtual decimal GetUnitPrice(Product product,
            Customer customer, 
            ShoppingCartType shoppingCartType,
            int quantity,
            string attributesXml,
            decimal customerEnteredPrice,
            DateTime? rentalStartDate, DateTime? rentalEndDate,
            bool includeDiscounts,
            out decimal discountAmount,
            out List<DiscountForCaching> appliedDiscounts)`

Please check following lines
` if (_shoppingCartSettings.RoundPricesDuringCalculation)
                finalPrice = RoundingHelper.RoundPrice(finalPrice);`

Making false this round price setting shows correct price. But there isn't point to keep this lines because at the end all price are pass through "RoundPrice" function & By default this setting is "True" so it takes more time to figure out the problem & it can be found only in All settings page only

**Comment by DmitriyKulagin** [comment]
Unable to reproduce on the latest version 4.20
