### ISSUE TITLE
Make admin area theme able

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#349]
Sometimes, we need to make a different layout in admin area, such as move the navigation menu as vertical in the left or make the admin area have a good look on mobile devices, or different role with different permission could get a different layout admin area. 

Is there a schedule to make admin area theme able? 

It would be great if NOP could implement this feature. 

Thanks in advance. 

Source: http://www.nopcommerce.com/boards/t/36896/feature-request-make-admin-area-theme-able.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
