### ISSUE TITLE
HadSpentAmount Plugin - has incorrect text in plugin.json (4.0 and 4.1)

### ISSUE THREAD

**Issue by IAmThatStrange** [nopSolutions/nopCommerce#3490]
nopCommerce version: 4.0 and 4.1 (the plugin.json below is from 4.0 but I verified it's the same in 4.1 - it is correct in 3.9)

Steps to reproduce the problem: 

Just open the plugin.json and you'll find this - The Friendly Name is incorrect "ustomer".   

The plugin.json 
{
  "Group": "Discount requirements",
  "FriendlyName": "ustomer had spent x.xx amount",
  "SystemName": "DiscountRequirement.HadSpentAmount",
  "Version": "1.20",
  "SupportedVersions": [ "4.00" ],
  "Author": "nopCommerce team",
  "DisplayOrder": 1,
  "FileName": "Nop.Plugin.DiscountRules.HadSpentAmount.dll",
  "Description": "This plugin allows you to configure discounts for customers who spent more than the certain amount"
}

**Comment by RomanovM** [comment]
Thanks. Already reported https://github.com/nopSolutions/HadSpentAmount-discount-requiremement-plugin-for-nopcommerce/issues/1

**Comment by IAmThatStrange** [comment]
Thanks!  I'm sorry I did search but oddly didn't find this!  Glad you know
