### ISSUE TITLE
Sending reviews for a product with an additional review type does not work.

### ISSUE THREAD

**Issue by LubovKhokhlova** [nopSolutions/nopCommerce#3492]
Without an additional review type, everything is sent without problems. When sending with an additional review type, an error occurs with the automapper.

**Comment by RomanovM** [comment]
Related to https://github.com/nopSolutions/nopCommerce/issues/3531

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/3531
