### ISSUE TITLE
Issue with State localization.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3493]
nopCommerce version: 4.10

Steps to reproduce the problem: 

**1 - Please add one language at admin side** 

in my case i add Arabic language.

Name = Arabic

Language Culture = Arabic (Egypt). ar-EG

Unique seo = ar

Righ to left = checked

Published = checked

Display order = 1

Now click on save button.

**2 - now open country USA go to state province tab.**

After that Please edit first state of USA country.

Add القوات المسلحة الأمريكتين in arabic language 

After click on save again open this in edit mode.

Value is not shown there.

After Carefully examine.

**I got one solution.**

here it is.

Go PrepareStateProvinceModel 

in which 

you can find below code 

localizedModelConfiguration = (locale, languageId) =>
{
    locale.Name = _localizationService.GetLocalized(**country**, entity => entity.Name, languageId, false, false);
};

here i change country to **state** in the first parameter of GetLocalized method and it is working fine with that.

**Comment by RuS984** [comment]
Closed #3493

**Comment by sk5202** [comment]
Thanks @RuS984
