### ISSUE TITLE
Use Azure Pipelines instead of Travis (or both)

### ISSUE THREAD

**Issue by MaxMommersteeg** [nopSolutions/nopCommerce#3495]
Proposal:
Azure Pipelines has as biggest advantage over Travis that builds can run parallel. Their own text:
>Starting today, Azure Pipelines provides unlimited CI/CD minutes and 10 parallel jobs to every open source project for free. All open source projects run on the same infrastructure that our paying customers use. That means you’ll have the same fast performance and high quality of service.

Maybe we can use both or just rely on Azure Pipelines solely.

**Comment by dorofeev-serdg** [comment]
@RomanovM is it ok, if I implement building all projects and running all tests in CI-CD without docker for all the branches as a first step.
As a second step (if a first step is Ok), I may launch building a docker image for predefined branches (for example master).
If the second step is Ok, should I publish a docker image somewhere?
Should any additional checks be implemented (coverage analisys, external component analisys and so on)?

**Comment by skoshelev** [comment]
also, see #4908
