### ISSUE TITLE
Bestsellers report invalid item count

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3498]
Source: https://www.nopcommerce.com/boards/t/57688/bestsellers-report-invalid-item-count.aspx

**Comment by MaxMommersteeg** [comment]
Strangely enough I could not reproduce this issue locally, but do see described behavior at the admin demo website.

**Comment by RuS984** [comment]
This issue is fixed in version 4.20
Closed #3498
