### ISSUE TITLE
Better "in-store pickup" support. Allow a store owner to configure (and a customer to choose) a pickup location (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#35]
Allow a store owner to configure (and a customer to choose) a pickup location (contribution)

A store owner should be able to configure a lot of pickup locations. Once done we can think about ability to limit them per city or country (e.g. there's no need to displayed pickup location in France if a customer if located in the USA)

Source: http://www.nopcommerce.com/boards/t/33202/shipping-via-collection-point-pickup-location.aspx 

Contribution - https://nopcommerce.codeplex.com/SourceControl/network/forks/tommy7m/PickUpPoints

let's discuss how it's better to implement (UI)

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/b644baddcb3bd2e98352e504b5bbec3f7ab7db86
