### ISSUE TITLE
Put logo and a note/message to customer on packaging slip (pdf)

### ISSUE THREAD

**Issue by compito** [nopSolutions/nopCommerce#3501]
nopCommerce version: all

Steps to reproduce the problem: Press "Print packaging slip" button on any shipment.

We already have logo on invoices, why not have it on packaging slip too? It should be the same function as for invoices?

Also, it would be good if we could write a note/massage to customer so it gets printed on packaging slip too. An additional text box on shipment page.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
