### ISSUE TITLE
"shoppingcartsettings.grouptierpricesfordistinctshoppingcartitems" variable name is confusing.

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3508]
nopCommerce version: 
All

Steps to reproduce the problem: 
Go to 
Admin > Configuration > Setting > All setting

And find setting name  "shoppingcartsettings.grouptierpricesfordistinctshoppingcartitems"

The setting name "shoppingcartsettings.grouptierpricesfordistinctshoppingcartitems" is confusing and unclear. Unless you go through the code, it would lead you to believe it affects the visual presentation of the shopping cart item, not how they are calculated. There's nothing about the name that implies that it changes how item prices are calculated, nor how they are calculated.

**Comment by RomanovM** [comment]
There is already an explanatory hint for this setting, so it's no need to rename it. See https://github.com/nopSolutions/nopCommerce/issues/3249
