### ISSUE TITLE
Why isn't the current product name saved in OrderItem? (Design flaw)

### ISSUE THREAD

**Issue by MaximG1234** [nopSolutions/nopCommerce#3510]
nopCommerce version: 4.2

This is a simple but extremely important issue:

The OrderItem table only contains a reference to ProductId and does not save the name of the product at the time of the transaction. 

Making the assumption that the product name for a given historical transaction is the same as the product name at some future point is a mistake and major design flaw in my opinion. 

My customers will often change the product name, even subsequent to when a transaction has already occurred for an item as I am sure many other users will. Obviously, regardless of any changes to the underlying product a user would expect that the product name would remain the same in the historical transaction.

Suggested solution:

1. I suggest that another column is added to the OrderItem table called 'ProductName' or 'Name' which contains the name of the product at the time of transaction.
2. I suggest the OrderView page is updated to show this new value.
3. For existing orders we would copy over the current product name into the 'ProductName' or 'Name' column.

I suppose what I haven't considered is that multiple parts of the application will obviously reference the product name.

I am happy to write this code if you're willing to commit it to the main branch, does anyone have any comments, issues or guidance with this suggested change?

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
