### ISSUE TITLE
Add pagination to the "new products" page

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3511]
Let's add paging support to the "new products" page (`/newproducts` URL). Add a paging support to category or manufacturer pages. Add paging only (no other filter blocks are required). 

So update appropriate logic in the "NewProducts" method of \Nop.Web\Controllers\ProductController.cs. And "GetProductsMarkedAsNewAsync" method of \Nop.Services\Catalog\IProductService.cs (add paging support)

Source: https://www.nopcommerce.com/boards/t/57526/new-features-sugestions.aspx

**Comment by dborovsky** [comment]
@RomanovM i would like to do this task. 
Must be added filter with select size unit per page like on another pages? Or do you want  set this feature by admin panel?

**Comment by AndreiMaz** [comment]
Pull request - https://github.com/nopSolutions/nopCommerce/pull/3571
