### ISSUE TITLE
Using PreRequestCacheManager in ManufacturerService 

### ISSUE THREAD

**Issue by ayberkcal** [nopSolutions/nopCommerce#3512]
I am extending ManufacturerService for our requirements and saw PreRequestCacheManager using in ManufacturerService. I have looked methods which use cacheManager and I think most of them need long term caching. 
For example:
GetManufacturerById
GetProductManufacturersByManufacturerId
GetProductManufacturersByProductIdand so on...
Is it bug or what is main reason for using short term caching in this service?
Thank you.

**Comment by AndreiMaz** [comment]
new caching approach is used in 4.30 (per HTTP requests) as we don't use EF anymore
