### ISSUE TITLE
Exported XML of language locales can no longer be opened in Excel due to UTF-16 encoding.

### ISSUE THREAD

**Issue by w-tbury** [nopSolutions/nopCommerce#3513]
nopCommerce version: Worked in 3.8.  Not working in 4.1

Steps to reproduce the problem: Export language locales from the admin area (Configuration -> Languages). 
Choose to edit a language.
Click to export.
Try to open XML file in Excel.
It errors because Excel can not handle UTF-16 encoding.

Could there be a way to have it where we can choose which encoding for XML we want when exporting any XML file?

**Comment by RomanovM** [comment]
It's not related with nop.
You can use any other tool for working with xml and convert the encoding yourself.

**Comment by awe-source** [comment]
It is actually related to how NOP code builds the XML via stringbuilder, so I disagree with the statement that its not NOP - but I guess you COULD argue its stringbuilder… regardless, you don't want to fix it that's fine, and the workaround does work... its just not "right" or very user friendly.
