### ISSUE TITLE
Initialize AutoMapper after registering services

### ISSUE THREAD

**Issue by dday4thedeceiver** [nopSolutions/nopCommerce#3524]
nopCommerce version: 4.10

Steps to reproduce the problem: Try to resolve anything from an AutoMapper configuration and it will fail, because nothing has been registered yet. Simply moving AutoMapper initialization in ConfigureServices() after service registrations fixes the issue.

**Comment by skoshelev** [comment]
Hi @dday4thedeceiver.
Please specify where you are trying to rezolvit something from AutoMapper and where we better configure it if not in ConfigureServices(https://github.com/nopSolutions/nopCommerce/blob/release-4.10/src/Libraries/Nop.Core/Infrastructure/NopEngine.cs#L194)?

**Comment by dday4thedeceiver** [comment]
Hi,

If the AddAutoMapper is called after RegisterDependencies, then everything is fine. Then one can call EngineContext.Current.Resolve from within an IOrderMapperProfile impl. to get instances of services.

**Comment by skoshelev** [comment]
We analyzed the code, and decided not to change the calls in places, since usually for configuring the AutoMapper there is no need to use the IEngine interface and there is also a high probability that the AutoMapper will be needed when working IDependencyRegistrar classes

Closed #3524
