### ISSUE TITLE
Allow User Secret Support in Development Environment

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3525]
nopCommerce version: 4.10

Steps to reproduce the problem: 
User Secrets is an aspnet feature that allows a developer to make changes to their configuration without having to change appSettings.json and at zero risk of checking in config changes which may break another developer or environment. You can read more about the feature [here](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows).

Just change the Startup constructor as so:
```

public Startup(IConfiguration configuration, IHostingEnvironment env)   
{
  //set configuration
  Configuration = configuration;
  
  if (env.IsDevelopment())
  {
    var builder = new ConfigurationBuilder()
                    .AddConfiguration(configuration)
                    .AddUserSecrets<Startup>();
   Configuration = builder.Build();
 }
}
```
On line 100 of rhte Nop.Web.csproj insert the following just before the closing </PropertyGroup> - you can choose any GUID you wish. 

`<UserSecretsId>8e91d132-9a5b-484b-8335-c787eb18f52e</UserSecretsId>`

**Comment by RomanovM** [comment]
After some investigation decided not to implement it now.
