### ISSUE TITLE
Refactoring and bug fixes for TaxService

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3527]
Nopcommerce uses the method GetProductPrice for calculation any prices.

1. IsEuConsumer (It's a big fix for store's from Europe)
This method GetProductPrice uses method IsEuConsumer for each checking prices (one time for each price)
It's better to save the result of first request in local cache (per request)

protected virtual bool IsEuConsumer(Customer customer)
{
//check the cached value 
....
}

But I think it's better to move this method to class IWorkContext and save the result of the first request for all next requests.

2. Method CreateCalculateTaxRequest
a) cosmetic fix, remove this old line. it's not reasonable to use it now.

            var overriddenBasedOn = _taxSettings.EuVatEnabled                                            //EU VAT enabled?
                && product != null && product.IsTelecommunicationsOrBroadcastingOrElectronicServices    //telecommunications, broadcasting and electronic services?
                && DateTime.UtcNow > new DateTime(2015, 1, 1, 0, 0, 0, DateTimeKind.Utc)                //January 1st 2015 passed?
                && IsEuConsumer(customer);                                                              //Europe Union consumer?

b) Big fix if we use pickup in store.

                var pickupPoint = _genericAttributeService.GetAttribute<PickupPoint>(customer,
                    NopCustomerDefaults.SelectedPickupPointAttribute, _storeContext.CurrentStore.Id);
                if (pickupPoint != null)
                {
                    var country = _countryService.GetCountryByTwoLetterIsoCode(pickupPoint.CountryCode);
                    var state = _stateProvinceService.GetStateProvinceByAbbreviation(pickupPoint.StateAbbreviation, country?.Id);

for each price calculation we check if customer selected PickupPoint and try to get country and state value from SQL for this PickupPoint.
It's many small SQL requests (two for each price, one for country and another for state).

Can we save address of each pickupPoint in static cache?

c) Big fix
                    calculateTaxRequest.Address = _addressService.GetAddressById(_taxSettings.DefaultTaxAddressId);

I agree the we saved to local cache the address after first request.
Can we store the result of this request in shared cache (static cache)?
If we have many requests from many customers we have three SQL requests to database.

d) big fix
ITaxProvider LoadActiveTaxProvider(Customer customer = null)
or 
ITaxProvider LoadTaxProviderBySystemName(string systemName)

For each price calculation we try to get default TAX provider

            var taxProvider = LoadTaxProviderBySystemName(_taxSettings.ActiveTaxProviderSystemName) ??
                              LoadAllTaxProviders(customer).FirstOrDefault();
            return taxProvider;

We need to save it in local value of TaxService class after first request
or share this local value between all customers. I think it's better.

Source: https://www.nopcommerce.com/boards/t/57914/performance-optimization-very-small-and-bix-fixes-for-taxservice.aspx

**Comment by AndreiMaz** [comment]
1. We cannot store entities in static cache because EF doesn't support 2-level caching
2. We also cannot cache IPlugin instanced between HTTP request but now cache them during the same HTTP request
3. Other changes are implemented. Thanks a lot!
4. One suggestion moved to a separate issue - https://github.com/nopSolutions/nopCommerce/issues/3649
