### ISSUE TITLE
Import theme archives

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#353]
If we add to import option for theme zip , rar file from admin then users/clients dont need to use ftp or 3rd party program for uploude and change design who not familiar ftp programs etc can use nop easyly .

Will be zip file import from admin and nopCommerce auto unzip it and creates folder to themes/ path . 

Hope you can think this functionality for default nopCommerce 

Forum source: http://www.nopcommerce.com/boards/t/31888/feature-request-import-theme-file.aspx 

also see https://www.nopcommerce.com/boards/t/48672/nopcommerce-40-bug-fixes-and-improvements.aspx?p=6#195342

**Comment by poyker** [comment]
This will make even more sense to be done for plugins. Furthermore some themes come with a lot of plugins and if you upload a theme from the admin then you should be able to upload the plugins for that theme again from the admin. In reality you usually have only a few themes but quite a lot of plugins in your store.

**Comment by AndreiMaz** [comment]
@poyker thanks. there's a separate task for plugins #78
