### ISSUE TITLE
Model binding issue

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3531]
nopCommerce version: develop

Steps to reproduce the problem: 
1. Go to Currency List page;
2. Click Get live rates button;
3. Click to Apply rate button for any currency;
4. Rate isn't applied and we get increasing memory consumption until crash;

5. The same happens when you try to update any checkout attribute
6. Also when you try to edit any product details on the order details page (admin area)
7. Also udpate of product reviews with an additional review types does not work

**Comment by charankasu** [comment]
Hi All - I've created a pull request https://github.com/nopSolutions/nopCommerce/pull/3583 that resolves this issue. I've provided the details of the actual problem and the corresponding fix in the pull request. Could someone please review?

**Comment by AndreiMaz** [comment]
Added two more scenarios to the issue description
