### ISSUE TITLE
Upgrade to reCAPTCHA v3

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3534]
Source: https://www.nopcommerce.com/boards/t/57991/recaptcha-v3-upgrade.aspx

Also see https://developers.google.com/recaptcha/docs/versions#checkbox

**Comment by varunnaresh1992** [comment]
Any Updates ? I think this is an important feature.

**Comment by MarthaDarumaTech** [comment]
Does anyone have any updates please!?

**Comment by holydk** [comment]
Closed #3534
