### ISSUE TITLE
Add recaptcha on Forgot password page

### ISSUE THREAD

**Issue by pantonis** [nopSolutions/nopCommerce#3536]
nopCommerce version:  4.10

Steps to reproduce the problem:  Recaptcha is not supported in Forgot password page

**Comment by dborovsky** [comment]
I can take on this task. If there are more priority tasks, I am also ready to help.

**Comment by RomanovM** [comment]
@dborovsky You are welcome, any help is appreciated. More information [here](http://docs.nopcommerce.com/display/en/Working+with+source+code+and+contributions)

**Comment by dborovsky** [comment]
@RomanovM I created PR. Check please. Thank you.

**Comment by dborovsky** [comment]
@RomanovM  Close this issue, because PR has been already merged with develop branch.

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/pull/3557
