### ISSUE TITLE
Allow to disable dashboard warning

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3538]
In the dashboard we have a nice warning about plugins that may be causing performance issues and recommend uninstalling them. Actually, this particular warning is displayed in the system > warnings area but then causes the dashboard warning to display.

My best guess is that this function is looking for plugins that are not enabled and reports them to the dashboard. This is very convenient except the condition when the Shipping Director plugin is installed and used.

Because shipping director requires every other shipping plugin to be disabled, this dashboard warning is permanently displayed. Even though clicking the X on the right corning causes the warning to go away. A browser refresh brings it right back.

So while it doesn't affect anything, its rather an ugly esthetic annoyance. Have to wonder, is there another variable that can be used in conjunction with "not enabled" to determine whether a plugin is actually used? Maybe "not installed" instead of "not enabled". But this does not seem like the right solution either.

Source: https://www.nopcommerce.com/boards/t/57967/persistent-dashboard-warning.aspx

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
