### ISSUE TITLE
Customer back in stock email subscription at Product Attribute Combination level

### ISSUE THREAD

**Issue by jonquickqsense** [nopSolutions/nopCommerce#3539]
Our store products have product attribute combinations for 'Size' and we track inventory by Product Attribute.  Customers are only interested in knowing when their size is back in stock.  We have no 'back in stock' notification for a particular combination (size) possible in 4.1

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/t/20226/back-in-stock-subscriptions-for-product-attributes.aspx
and: https://github.com/nopSolutions/nopCommerce/issues/1690

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
