### ISSUE TITLE
Sub Specification attribute (e.g. Vehicle filtering)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#354]
See http://www.nopcommerce.com/boards/t/31212/nopcommerce-350-roadmap-and-estimated-release-date-lets-discuss.aspx#127012 and http://www.nopcommerce.com/boards/t/31212/nopcommerce-350-roadmap-and-estimated-release-date-lets-discuss.aspx#127021 and https://www.google.com.mx/search?num=100&safe=off&q=auto+parts+eadameg+site%3Anopcommerce.com&oq=auto+parts+eadameg+site%3Anopcommerce.com

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
