### ISSUE TITLE
Could not load file or assembly  *.Views.dll 

### ISSUE THREAD

**Issue by yuessir** [nopSolutions/nopCommerce#3543]
nopCommerce version: 
DEV branch
Steps to reproduce the problem: 
Step1: Creating a new MVC (.net core 2.2) project
and ref essentials projects.
Step2: Run and error likes:
![sh](https://user-images.githubusercontent.com/8326310/52767561-d97a1e80-3065-11e9-9edc-07f1327e9285.PNG)

But I skip the *.Views.dll  file, it will show normal "welcome" screen like following: 
![s2h](https://user-images.githubusercontent.com/8326310/52767842-9f5d4c80-3066-11e9-9082-cf4f75bfb616.PNG)

**Comment by RomanovM** [comment]
It's not related with nop
