### ISSUE TITLE
Shipping rate computation method could not be loaded

### ISSUE THREAD

**Issue by Legends** [nopSolutions/nopCommerce#3545]
nopCommerce version: 4.10

Steps I have done before:
I have activated and configured the Paypal standard plugin.

Steps to reproduce the problem: 
Click on a product and add to cart.

![image](https://user-images.githubusercontent.com/966368/52850862-e1dd6280-3114-11e9-8de9-0ee668bc066d.png)

**Comment by RomanovM** [comment]
@Legends Could you please post such questions on our forums. This is an issue tracker.

**Comment by Legends** [comment]
I thought, an exception page is an issue ?!
There should be an action recommendation for the user displayed not an exception page, right?

**Comment by Legends** [comment]
Why is the site crashing on local plugin install? omg

**Comment by ym91** [comment]
Facing this too. Any solution about this?
