### ISSUE TITLE
NOP 4.1 - Plugin Must be assigned to customer role v1.25 ERROR 

### ISSUE THREAD

**Issue by alexmvubizname** [nopSolutions/nopCommerce#3546]
nopCommerce version: 4.1

Steps to reproduce the problem: steps and error described in forum:
https://www.nopcommerce.com/boards/t/57987/nop-41-plugin-must-be-assigned-to-customer-role-v125-error.aspx#221033

"Trying to add a new Discount using "Must be assigned to customer role" (in the requirements tab), a "Failed to load requirement content" appears and Customer Roles are not loaded."

**Comment by RomanovM** [comment]
@alexmvubizname  It works like a charm on our demo.

**Comment by alexmvubizname** [comment]
Yes, when I tried discount plugin from local PC with the same DB it works well.
I copied seven spikes plugins from our staging server, where we have issue, to my PC.
Tested discount plugin again and was able to replicate issue. Problem I don’t have any log indication where I can see it related to seven spikes, no stack trace, nothing. How we can find source of issue in this case?

**Comment by alexmvubizname** [comment]
I tried github version. Issue fixed here.
URL replaced to correct value:
            var url = discountRequirementRule.GetConfigurationUrl(discount.Id, discountRequirementId);
was:
            var url = $"{_webHelper.GetStoreLocation()}{discountRequirementRule.GetConfigurationUrl(discount.Id, discountRequirementId)}";

>>> It works like a charm on our demo.

It works in your demo because you don't use virtual folder for store.
