### ISSUE TITLE
Think out about moving interfaces to a separate library

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3548]
e.g. Nop.Abstractions

For example, see https://github.com/aspnet/AspNetCore/tree/master/src/Mvc/Mvc.Abstractions/src

**Comment by Lukejkw** [comment]
This would be a massive breaking change. Is the juice worth the squeeze?

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
