### ISSUE TITLE
HandleEvents<AdminTabStripCreated > is no longer called 

### ISSUE THREAD

**Issue by layinka** [nopSolutions/nopCommerce#3550]
nopCommerce version: 4.2(current develop branch)

Steps to reproduce the problem: 

Create a class that inherits from IConsumer<AdminTabStripCreated> and try to implement HandleEvents<AdminTabStripCreated > , the HandleEvents method is no longer called.

**Comment by AndreiMaz** [comment]
4.20 is not released yet (under development). We won't use tabs in 4.20. We replace them with blocks. So you'll have to us widgets to add custom blocks in 4.20

**Comment by layinka** [comment]
I have been checking out the blocks mode, i am not sure its the best approach, its not a very good UX approach as the user has to be scrolling up and down to navigate between different blocks, which used to be very easy to do with tabs.

I think you should consider allowing users to choose between tabs and blocks

See https://www.nopcommerce.com/boards/t/55550/nopcommerce-420.aspx?p=3
