### ISSUE TITLE
Error when disabling "billing address step"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3556]
Steps to reproduce the problem: 
1) do disable "billing address step" and disable "one page checkout".
2) delete all addresses from my account section.
3) now add any product to cart and do proceed to checkout , it is throwing error "value cannot be null".

We have apporpriate validate in multi-step checkout but not in one-page checkout

Source: https://www.nopcommerce.com/boards/t/58133/error-when-we-disable-billing-address-step-in-nopcommerce-41.aspx

**Comment by DmitriyKulagin** [comment]
Similar issue #3547

**Comment by DmitriyKulagin** [comment]
Closed, see [this commit](https://github.com/nopSolutions/nopCommerce/commit/15dc092f4f6d2b32becfabb3e21bc77343aca670)
