### ISSUE TITLE
Campaigns/newsletter filtering for customers that have purchased certain products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#356]
nopCommerce already has a great default feature to send email campaigns. I would recommend to add few more features using which admin can select customers to whom he need to send these campaigns. For example, we may have customer role, or all those customers who have registered, who have placed order, or may be not placed any order! Or may have placed order for certain products! 

Forum source: http://www.nopcommerce.com/boards/t/31609/campaigns-for-customers-that-are-assigned-to-certain-role-or-has-purchased-certain-products.aspx and http://www.nopcommerce.com/boards/t/28381/sugession-to-improve-newsletter-subscribers.aspx

**Comment by AndreiMaz** [comment]
duplicate
