### ISSUE TITLE
Tier prices with overlapping customer roles are incorrectly calculated

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3561]
Tier prices are incorrectly calculated when overlapping roles are applied to a tier price.  A "wholesaler" role customer, for instance, pays a flat rate of $3.00 per item when buying 10+ items.  A default "All customers" role customer , on the otherhand, pays $4.00 if they purchase 15+ items. Since "wholesaler" role customer is also in the "All customers" role, a "wholesaler" customer is charged $4 instead of $3 per item when buying 15+ items. 

Source: https://www.nopcommerce.com/boards/t/58221/tier-prices-with-overlapping-customer-roles-are-incorrectly-calculated.aspx

**Comment by DmitriyKulagin** [comment]
Tier prices functionality works correctly. The lowest price is chosen in the case of overlapping customer roles.
