### ISSUE TITLE
Preview button for message template editor

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3562]
I'd like to suggest the addition of a preview button on the message template editor. It would make it a lot easier and faster than having to email a copy to yourself each time you make an edit, and then want to review its changes to the template.

Source: https://www.nopcommerce.com/boards/t/58224/preview-button-for-message-template-editor.aspx

**Comment by cnEUL** [comment]
if you have several languages in templates (or other editors), open also one window for each language. This helps to control the translation also very easy.

**Comment by RomanovM** [comment]
After some discussion decided not to implement it now. Anyway we already have a "Test template" feature for it.
