### ISSUE TITLE
Почему продукт не поставляется в виде Nuget пакетов?

### ISSUE THREAD

**Issue by Sellec** [nopSolutions/nopCommerce#3565]
В конце концов, проект ведут русскоязычные разработчики, поэтому спрошу на родном, так проще. Начал изучать, как устанавливать nop, и вижу, что его нельзя подцепить в виде пакета с ресурсами к базовому проекту asp.net core. 
Хочу попробовать уйти от своей самописной cms на .net, изучаю nop на предмет того, насколько его легко дорабатывать. Столкнулся уже с кучей веселых классов типа FooterViewComponent для компонента футера...эм...на уровне кода...что это....почему дизайн связан с кодом напрямую...

**Comment by RomanovM** [comment]
@Sellec  nopCommerce is a self-contained project ready for deployment, there is no need to connect it by NuGet to a third-party projects.
Could you please post such questions on [our forums](https://www.nopcommerce.com/boards). This is an issue tracker.
