### ISSUE TITLE
ACL for checkout attributes

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3567]
We are working a lot with customer roles, it would be great if you could limit a checkout attribute to one or more customerroles. 

Source: https://www.nopcommerce.com/boards/t/58245/checkout-attributes.aspx

See also https://github.com/nopSolutions/nopCommerce/issues/703

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
