### ISSUE TITLE
User registration email not validated

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3570]
![2019-03-02 13_28_14-amazon registration](https://user-images.githubusercontent.com/31761152/53679298-f0b93d00-3cf0-11e9-9c0d-3ae0e994ff05.png)
![2019-03-02 13_27_33-please confirm your identity](https://user-images.githubusercontent.com/31761152/53679300-f3b42d80-3cf0-11e9-879b-7cfcf6c3b8d8.png)

nopCommerce version: 
Latest version as on 01-Mar-2019

Steps to reproduce the problem: 
User can enter any invalid email address and register them-self.
After registration we should send verification link to registered email address and after successfully verification only user get registered.
Also make mobile number as optional registration to email and send OTP to mobile to verify mobile number and avoid spamming.

It should be similar to Amazon.com

For me its highest priority issue.

**Comment by mrnams** [comment]
Guys i tried to implement it, but i could not, as i am novice to asp.net core.
Can anyone please take this on priority.
This issue is blocking me to deploy.

**Comment by RomanovM** [comment]
It's already implemented. Just set "Registration method" setting to EmailValidation http://admin-demo.nopcommerce.com/Admin/Setting/CustomerUser

**Comment by mrnams** [comment]
Thanks a lot for update,

I could not find option to Phone validation is required after registration,
I mean when user register using phone number instead of  email, then user should get opt to confirm he not using anybody else's phone to register.

Should i file seperate PR for this?
