### ISSUE TITLE
'Including VAT' shown while it shouldn't

### ISSUE THREAD

**Issue by Tychodewaard** [nopSolutions/nopCommerce#3572]
nopCommerce version: 3.9

Steps to reproduce the problem: 

Setup
- The shop is in the EU
- EU VAT Enabled
- The customer is logged in as company with valid tax number and in another country in the EU. 
- Prices are shown including VAT

What is wrong:
The prices in the product list and product detail (and preview shopping cart) say 'including tax' but have applied the 0% tax. This makes the visitors believe that the tax is applied and will be deducted during checkout.

FYI : If I switch the country to USA (but leave the test VAT number the same Belgium number) for instance, the same happens. 

Solution:
- If a logged in visitor has a valid VAT and is stated in another country than the shop, the prices should say  'excluding VAT', even if you have set 'including VAT' in the tax settings.

If there is a work around available without having to rebuild the solution in VS, that would be appreciated. Perhaps adding the applied taxrate, so it would say 'Incl 0% tax'?

**Comment by AndreiMaz** [comment]
A customer can always changes how to display tax (with or without taxes) in the appropriate dropdown list in the header
