### ISSUE TITLE
CustomerLoggedinEvent

### ISSUE THREAD

**Issue by Mahenbisht** [nopSolutions/nopCommerce#3574]
nopCommerce version: 

Steps to reproduce the problem:

**Comment by Mahenbisht** [comment]
How CustomerLoggedinEvent is handled from the Customer controller

_eventPublisher.Publish(new CustomerLoggedinEvent(customer));

**Comment by RomanovM** [comment]
@Mahenbisht Could you please post such questions on [our forums](https://www.nopcommerce.com/boards/). This is an issue tracker.
