### ISSUE TITLE
Insecure cookie attribute Nop.Customer

### ISSUE THREAD

**Issue by JamieSellars** [nopSolutions/nopCommerce#3575]
nopCommerce version: 
4.1
Steps to reproduce the problem: 

The application uses a number of cookies in order to maintain session state. One of these, the Nop.Customer cookie does not set the 'secure' attribute. This means that this cookie will be sent when the browser makes a request to the http:// (as opposed to https://).

*Not an issue if site is running HTTPS*

The expiration period is 1 year, which seems excessive.

Is there any particular reason why this cookie attribute is not set?

If there isn't I propose updating the SetCustomerCookie method to set secure attribute on creation.
WebWorkContext.cs [Line: 104]
```csharp
protected virtual void SetCustomerCookie(Guid customerGuid)
        {
            if (_httpContextAccessor.HttpContext?.Response == null)
                return;

            //delete current cookie value
            var cookieName = $"{NopCookieDefaults.Prefix}{NopCookieDefaults.CustomerCookie}";
            _httpContextAccessor.HttpContext.Response.Cookies.Delete(cookieName);

            //get date of cookie expiration
            var cookieExpires = 24 * 365; //TODO make configurable
            var cookieExpiresDate = DateTime.Now.AddHours(cookieExpires);

            //if passed guid is empty set cookie as expired
            if (customerGuid == Guid.Empty)
                cookieExpiresDate = DateTime.Now.AddMonths(-1);

            //set new cookie value
            var options = new CookieOptions
            {
                HttpOnly = true,
                Expires = cookieExpiresDate,
                Secure = true
            };
            _httpContextAccessor.HttpContext.Response.Cookies.Append(cookieName, customerGuid.ToString(), options);
        }
```

**Comment by DmitriyKulagin** [comment]
After some discussion, it was decided not to implement it now, because we can not leave without support sites working on http.
