### ISSUE TITLE
Nested Folder Views cannot be found

### ISSUE THREAD

**Issue by bulutkartal** [nopSolutions/nopCommerce#3586]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Create a view in plugin under Views/Admin/Product/test.cshtml

It works fine when the view is under Admin but when you create another folder(Product in my case) it cannot find the view.

**Comment by RomanovM** [comment]
Could you please post such questions on [our forums](https://www.nopcommerce.com/boards). This is an issue tracker of nopCommerce, it's not about custom plugin development

**Comment by bulutkartal** [comment]
@RomanovM Don't you create views when you develop a plugin? It cannot find the views if it is nested twice. I guess this is an issue and about Nopcommerce Plugin Development.
