### ISSUE TITLE
PickUp in Store treats an order as "shippable"

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3593]
nopCommerce version: 4.10

Steps to reproduce the problem: 

- Configure product "Shipping enabled"
- Install and configure "Pickup.PickupInStore"
- During check-out remove "Ship to the same address"
- Shipping address = Pickup in Store
- Payment = Pay in Store
- Complete

I can see my `ShippingStatusId` = **20** (Not Yet Shipped)
but the order is marked as `PickUpInStore`

I am forced to create a shipment to mark the order as **Completed**.

![Capture](https://user-images.githubusercontent.com/171024/54431740-1c8be800-471f-11e9-9d34-59a94eee0dbc.jpg)

I made some changes to this [line](https://github.com/nopSolutions/nopCommerce/blob/fbc494f1c8b5d9a5a87381dd1964afabc38c62d0/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L545) 

```
if (details.PickUpInStore)
{
    details.ShippingStatus = ShippingStatus.ShippingNotRequired;
}
else
{
    details.ShippingStatus = ShippingStatus.NotYetShipped;
}
```

I don't quite understand why PickUpInStore as a shipping option and a shipping address.

**Comment by DmitriyKulagin** [comment]
Works correctly by design. Maybe in the future we will add new Shipping Status
