### ISSUE TITLE
InvalidOperationException: No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by appsoln** [nopSolutions/nopCommerce#3594]
nopCommerce version: 3.0

Steps to reproduce the problem: Just cloned the repository, opened the SLN and RUN the project.,

I am trying to deploy nopcommerce using the source code. But whenever I try to run it, it is showing InvalidOperationException: No database provider has been configured for this DbContext. exception.

I researched on SO and found that this error comes when there is a parameterless constructor in the DbContext.

I searched all of the Nopcommerce source code but found no DBContext with a parameterless constructor.

**Comment by RomanovM** [comment]
>  I researched on SO and found that this error comes when there is a parameterless constructor in the DbContext.
> I searched all of the Nopcommerce source code but found no DBContext with a parameterless constructor.

..so, all is ok with nop. Try to start your SQL server
