### ISSUE TITLE
IsInCustomerRole bugged - Registered user can register again 

### ISSUE THREAD

**Issue by LighFusion** [nopSolutions/nopCommerce#3595]
nopCommerce version: 4.10
```
public static bool IsInCustomerRole(this Customer customer,
            string customerRoleSystemName, bool onlyActiveCustomerRoles = true)
        {
            var result = customer.CustomerRoles
                .FirstOrDefault(cr => (!onlyActiveCustomerRoles || cr.Active) && cr.SystemName == customerRoleSystemName) != null;
}

```
Steps to reproduce the problem: 
Register new user, don't logout go to url http://localhost:15536/register ,
write down correct data, and you would be registered again.

I don't know what the reason to make `!onlyActiveCustomerRoles `with or || operator, but if u want to ignore unactive users, its not the best option as it simply ignores whole logic 
P.S.
seems problem is not in `!onlyActiveCustomerRoles` || , but in  non updating customer.CustomerRoles array, or something different.
if i write this way in 
```
public virtual IActionResult Register(RegisterModel model, string returnUrl, bool captchaValid)
        {
var IsRegistered = _workContext.CurrentCustomer.CustomerRoles
                .FirstOrDefault(cr => cr.Active &&(cr.SystemName == NopCustomerDefaults.RegisteredRoleName) ) != null;
            Debug.WriteLine("model is registered role " + IsRegistered + "crActive "+ crActive);
}
```
And if i'm already registered, IsRegistered  returns true,

but original

```
public virtual IActionResult Register(RegisterModel model, string returnUrl, bool captchaValid)
        {
if (_workContext.CurrentCustomer.IsRegistered())
            {

}
         
```
returns false

**Comment by RomanovM** [comment]
This function works like a charm. And it's by design that you can register again, it will just be another new customer.

**Comment by LighFusion** [comment]
> This function works like a charm. And it's by design that you can register again, it will just be another new customer.

my bad ) i just thought its a vulnerability for auto-registering 1000 accounts even without exiting from old ones . its not a big deal if there is captcha but anyway ! sory
