### ISSUE TITLE
Remove filename after clicking "Remove picture" button when uploading images

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#3596]
In case you click the delete button, the thumbnail of selected image  reverts back to the default image, the delete button disappears, but the blue div with the name and size of the image selected before remains visible.

EditorTemplates\Picture.cshtml file

For more info see premium support ticket #14791

**Comment by skoshelev** [comment]
Also after adding the image to the product the image is saved and added to the table; but the form is not cleaned/reset.

For more info see premium support ticket #14792
