### ISSUE TITLE
Remove Clear from Default password format - Big security concern

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3598]
nopCommerce version: 
4.10
Steps to reproduce the problem: 
Go to 
Admin/Setting/CustomerUser -> Default password format
It has option for clear password,
Don't you this is big security concern, I personally feel we MUST remove this option.
Or please explain need for this option?

I surprise how no one raised this issue earlier?

**Comment by RomanovM** [comment]
You are not required to use this format if you do not want. By default, [hashed one](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Installation/CodeFirstInstallationService.cs#L6195) is used during installation, so everything is fine with security.

**Comment by mrnams** [comment]
Thanks for quick update
