### ISSUE TITLE
No margin for buttons in admin area

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3600]
nopCommerce version: 4.20

Steps to reproduce the problem: see the screenshot:

![image](https://user-images.githubusercontent.com/5019111/54489136-2f86ef80-48ba-11e9-869b-c3be68a1ea57.png)

**Comment by LubovKhokhlova** [comment]
Done in https://github.com/nopSolutions/nopCommerce/issues/1647

**Comment by AndreiMaz** [comment]
@LubovKhokhlova Still exists on the log list page

**Comment by LubovKhokhlova** [comment]
Done

**Comment by skoshelev** [comment]
![image](https://user-images.githubusercontent.com/16875599/55542066-f4185d80-56ce-11e9-82e6-bbc669612561.png)

**Comment by AndreiMaz** [comment]
cannot reproduce. already fixed
