### ISSUE TITLE
PayPal Standard Plugin - Add the ability to choose redirect landing page type

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#361]
The PayPal Standard plugin currently does not allow store owners to choose the type of landing page the customer is redirected to. 

The main benefit of this is that the store owner could designate the "Don't have a PayPal Account" as the default instead of "Have a PayPal account" without having to edit the source code. 

As pointed out by mauro.introzzi this can be hard coded by making the following changes: 

Standard Plugin on file 
"/Plugins/Nop.Plugin.Payments.PayPalStandard/PayPalStandardPaymentProcessor.cs" and recompiled it. 
I added the string "landing_page=billing&" to the method "public void PostProcessPayment(PostProcessPaymentRequest postProcessPaymentRequest)" 
changing the row "builder.AppendFormat("?cmd={0}&business={1}"...... 
with 
builder.AppendFormat("?landing_page=billing&cmd={0}&business={1}"..... 

We feel that the ability to edit this from the admin would be a great benefit for non technical users. 

Suggestion by: mauro.introzzi 

Work item source: http://www.nopcommerce.com/boards/t/22961/paypal-standard-payment-choose-redirect-landing-page.aspx 

also see contibution: https://nopcommerce.codeplex.com/SourceControl/network/forks/maurointrozzi/PaypalStandardChooseRedirLandingPage/contribution/4698

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
