### ISSUE TITLE
Pickup in store is not saved when it should

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3612]
nopCommerce version: 4.10

Steps to reproduce the problem: 

- Configure pickup in store ( Shipping settings)
- Configure pickup point
- Configure 1 product "Shipping enabled" = false
- Configure shipping method = Manual (Fixed or By Weight and By Total)
- Buy that product

Shipping status is set to ShippingNotRequired but PickUpInStore is set to false.

In OrderProcessingService.PreparePlaceOrderDetails there is a condition 

```
//shipping info
if (_shoppingCartService.ShoppingCartRequiresShipping(details.Cart))
{
....
}
```
which is not true as the cart contains just one product which is not enabled for shipping.
The process goes to `else` where the only statement is 

`details.ShippingStatus = ShippingStatus.ShippingNotRequired;
`

NopCommerce should set `PickUpInStore`  and `PickupAddress `also.

**Comment by RomanovM** [comment]
@Leftyx Delivery to pickup point is also considered as shipping, so if you disable shipping for product, pickup is disabled too.

**Comment by Leftyx** [comment]
> lso considered as shipping, so if you disable shipping for product, pickup is disabled too.

@RomanovM Thanks for the explanation.
