### ISSUE TITLE
Edit product combination should not check existing combination

### ISSUE THREAD

**Issue by spsinghats** [nopSolutions/nopCommerce#3613]
https://github.com/nopSolutions/nopCommerce/blob/6b475a656a14e429beb8003213dafcba3f00d8c4/src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs#L3301

Editing the Product combination does not work due to these lines, is this a side effect?

**Comment by tturner360** [comment]
I think this is my exact issue. Doesn't happen in the 4.10 demo on the site, but happens in my local 4.20 where I cannot update stock for combination.

**Comment by skoshelev** [comment]
Closed #3613
