### ISSUE TITLE
Model binding issues

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3615]
nopCommerce version: 4.20 ("develop" branch)

Steps to reproduce the problem: 
1. Try to update any checkout attribute. Or for example, try to edit any product details on the order details page (admin area)
2. There will be an infinite loop in the \Nop.Web.Framework\Mvc\ModelBinding\NopModelBinder.cs

**Comment by RomanovM** [comment]
Related to https://github.com/nopSolutions/nopCommerce/issues/3531

**Comment by AndreiMaz** [comment]
Or for example, try to edit any product details on the order details page (admin area). The same issue happens

**Comment by AndreiMaz** [comment]
moved https://github.com/nopSolutions/nopCommerce/issues/3531
