### ISSUE TITLE
Datetime picker not working in admin panel for some culture settings

### ISSUE THREAD

**Issue by mmakdessii** [nopSolutions/nopCommerce#3617]
Datetime picker not working in admin panel for customer

![Capture](https://user-images.githubusercontent.com/33662922/54759424-1bffbf80-4bff-11e9-93cb-39af929fd20c.PNG)

It considers days as months and vice versa, and then cannot correctly convert this data to a date

**Comment by mmakdessii** [comment]
How can I fix this???

**Comment by TsakiDev** [comment]
Can you specify the steps to reproduce this error?
Does the host has different configuration?

**Comment by DmitriyKulagin** [comment]
Depends on #30

**Comment by kiranbhadani** [comment]
@DmitriyKulagin Is this fixed? I am getting same issue in v4.5
