### ISSUE TITLE
Not able to install CCAvenue plugin

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3620]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
Download CCAvenue plugin from below location
http://downloads.nopcommerce.com/Extensions/UserContributions/58046_1030_CCAvenue.zip
Go to 
/Admin/Plugin/Plugins
and upload plugin
It says
" 0 plugins and 0 themes have been uploaded"

**Comment by AndreiMaz** [comment]
It doesn't support 4.20 because it's not released yet

**Comment by mrnams** [comment]
what's tentative plan for release of 4.20
