### ISSUE TITLE
IConsumer is called when plugin is disabled

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#3623]
nopCommerce version: 4.1

Steps to reproduce the problem: 
I have a shipment method that is not active. I receive the IConsumer when the event is fired!

**Comment by RomanovM** [comment]
It's by design. You should check a plugin for activity, as it is done for example [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Payments.Square/Services/EventConsumer.cs#L52)
