### ISSUE TITLE
Basic theme is not up to mark,safely we can say its weired

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3626]
nopCommerce version: 
Any version
Steps to reproduce the problem: 
Why Basic theme is not upto mark, can anyone make it good like SimplCommerce.
Though this is not showstopper,it has huge impact of visitor.

**Comment by RomanovM** [comment]
The default theme is intentionally made so simple and clean that it can be easily  customized.
But we think over to develop in addition one more theme with an impressive design. Thanks for the suggestion.
