### ISSUE TITLE
When you limit a topic page to a particular store you can still view it on other stores

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3627]
nopCommerce 4.10

I've noticed a bug when it comes to topic pages that are limited to store.  Essentially even if a topic page is limited to store you can still add it to the end of any of your store urls and view it.  This is problematic as a user could visit one of these pages on the wrong site and get incorrect information.

1. When you create a topic page and limit it to store you should not be able to access that page unless you are going to that store directly for example.  If I create a topic page named topic1 and limit it to store1.com I should only be able to do store1.com/topic1 to view that page and store2.com/topic1 should result in a page not found error.

2. However if I do store2.com/topic1 I am in fact able to view that topic page, this could be confusing as the information on this page could have nothing to do with store2.

3. Create an instance of nopCommerce with multiple stores, create a new topic page and limit it to store.  Go to any of your site URL's and see that topic page everywhere regardless if you are logged in or not.  Additionally if you are logged into store2.com and go to that topic page the url will reflect store2.com/topic1 even though in theory that should never be a valid link as it is limited to store.

4. We have not made any modifications to nopCommerce source code and do all of our enhancements in plugins.

Source: https://www.nopcommerce.com/boards/t/61595/bug-when-you-limit-a-topic-page-to-a-particular-store-you-can-still-view-it-on-other-stores.aspx

**Comment by RomanovM** [comment]
introduced on solving https://github.com/nopSolutions/nopCommerce/issues/2364
