### ISSUE TITLE
System.Data.SqlClient.SqlException: Too many arguments were specified for the ProductTagCountLoadAll procedure or function.

### ISSUE THREAD

**Issue by dborovsky** [nopSolutions/nopCommerce#3635]
nopCommerce version: 4.10

Steps to reproduce the problem: 
- I  updated branch develop with last changes.
- click any product or category
- method GetProductCount return error **System.Data.SqlClient.SqlException: 'Too many arguments were specified for the ProductTagCountLoadAll procedure or function.'**

**Comment by AndreiMaz** [comment]
It works fine by in the upcoming 4.20 so I presume you've forgot to apply all changes (e.g. in source code)

**Comment by dborovsky** [comment]
> It works fine by in the upcoming 4.20 so I presume you've forgot to apply all changes (e.g. in source code)

@AndreiMaz  What do you mean? 
I merged remote develop branch with my local develop branch.
How must I apply all changes?
