### ISSUE TITLE
Search products by SKU should be "contains" (not exact match)

### ISSUE THREAD

**Issue by RaoulSchabinger** [nopSolutions/nopCommerce#3638]
nopCommerce version: 4.1

We have a customer that want to search for partial SKUs. Could we change the storedProcedure to CONTAINS as it was in 3.6 and 3.7 version of nopcommerce?

We have lost this functionality with the update from nopCommerce 3.6 to 4.1.

Our customers need this functionality for their daily business.

**Comment by AndreiMaz** [comment]
It'll require customization from you. It should be exact match by default
