### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3639]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
Go to 
Administrator->Configuration->Local Plugins
and Hit Reload list of plugins
Application crashes.
Strange is it does not update log

**Comment by AndreiMaz** [comment]
What do you mean by crashes? Please clarify

Do you run it in VS?

**Comment by mrnams** [comment]
Yes i run in VS.
When we Hit Reload list of plugins, it closes browser

**Comment by mrnams** [comment]
Hello are you able to reproduce issue?

**Comment by mrnams** [comment]
@AndreiMaz
Are you working on this issue.

**Comment by AndreiMaz** [comment]
It's not the issue of nopCommerce. It happens in VS only (this is how VS works). And it'll work fine in a live hosted store. OR when you run the site without debugging

P.S. Please don't add "priority issue" or "serious issue" to work item titles.
P.P.S. I would also recommend to post it on our forums first (https://www.nopcommerce.com/boards/). This way we can discuss it first. And if an issue really existsm then we'll create a work item on GitHub

**Comment by mrnams** [comment]
@AndreiMaz,
No that's not case, we encounter same error on hosted site also
should i share video ?

**Comment by mrnams** [comment]
@AndreiMaz I am sharing logged message for application crash

nopCommerce needs to be restarted due to a configuration change, but was unable to do so.
To prevent this issue in the future, a change to the web server configuration is required:
- run the application in a full trust environment, or
- give the application write access to the 'web.config' file.

Please note I have already given write access to all folders mentioned in setup and  'web.config' file.
