### ISSUE TITLE
AspNetCoreModuleV2

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#3640]
nopCommerce version: 4.2

Steps to reproduce the problem: 

Are we going to use AspNetCoreModuleV2 instead of AspNetCoreModule? If not, why?

**Comment by RomanovM** [comment]
Do it after updating to net core 3 https://github.com/aspnet/Announcements/issues/339

**Comment by awe-source** [comment]
why? what was/is the thinking behind this change to/from V2...?!

**Comment by DmitriyKulagin** [comment]
Depends on #3652
