### ISSUE TITLE
Exception User-Unhandled

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3642]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
Logout from Administrator account,it will through Exception from "EuCookieLaw.cs" from below method

     public IViewComponentResult Invoke()

            //ignore notification?
            //right now it's used during logout so popup window is not displayed twice
            if (TempData[$"{NopCookieDefaults.Prefix}{NopCookieDefaults.IgnoreEuCookieLawWarning}"] != null && Convert.ToBoolean($"{NopCookieDefaults.Prefix}{NopCookieDefaults.IgnoreEuCookieLawWarning}"))

System.FormatException: 'String was not recognized as a valid Boolean.'

**Comment by skoshelev** [comment]
Closed #3642
