### ISSUE TITLE
Issue in reward point functionality

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3643]
nopCommerce version: 4.10

I registered in store and Enabled reward point functionality on store.
[Here ](https://i.ibb.co/mvzGtn1/1-Admin-Configuration.png)is Configuration of reward point

Here is My account - Reward point page (As fresh user, so not earned any reward point)
Check [here](https://i.ibb.co/x29BT5n/2-My-Account.png)

Now I'm place order of Product HTC One Mini Blue, Order total amount is 100$, So I'll earn 100 Reward point.
Check [order detail](https://i.ibb.co/DgBZ2gK/3-Place-Order.png).

I completed order and earn 100 reward point.  This is Perfect. Check [here](https://i.ibb.co/CPJcfzq/4-Earn-Rewardpoint-successfully.png). 
So now I've 100 reard points, which redeem amount is 50$.

Now I'm placing order of product - HTC One Mini Blue, Price is 100$.
Order total amount is 100$.

Now I'm using earned 100 reward point during checkout. 
So for this cart, below process should be process 
1. 100 Point should be redeem on order place.
2. 50 reward point awarded on order complete.
https://i.ibb.co/nbZBkKF/5-Cart-Will-Earn.png

I placed order and 100 Reward point successfully redeemed from my account. Check[ here my account](https://i.ibb.co/4K57TMZ/6-Redeemed-Success-Fully.png) page.

Now, I complete order from admin side. https://i.ibb.co/RTcSSkj/7-Order-Complete.png
On complete order event, I should earn 50 Reward point, but it awarded in my account.
https://i.ibb.co/Z85s5ML/8-not-earned-reward-point.png

Now, I'm going to cancel order from admin area.
So this cancel event, Only below process should be execute.
1. Return 100 reward point which I redeemed during checkout
2. Reduce 50 reward point which I earn on place order (Note: this should be done but I not earned in last order process)

I cancelled order - https://i.ibb.co/1QkQL73/9-order-cancelled.png
Now [check My account reward](https://i.ibb.co/PZ1DGJH/10-reward-point-history.png) point page:

Here you can see, there is two new logs,
1. 100 Reward point Returned back for order -1010 (**THIS IS FOR WHICH I REDEEMED DURING CHECKOUT AND THIS IS OKAY**)
2. 50 Reward point Reduced promotion for order -1010 (**THIS IS FOR WHICH Earn ON ORDER PLACE, BUT IN LAST ORDER I DIDN'T EARN ANY REWARD POINT ON PLACE ORDER AND IT REDUCED, SO THIS IS NOT OKAY**)

Now, 2 times I complete and cancel order and check reward point history page.
now [check my reward-point-history](https://i.ibb.co/ss8v1Nk/11-reward-history-page.png) page:

**This is happening due to single relation between order and reward point.**
_There should be multiple relation between Order and reward point history._

**Comment by rajupaladiya** [comment]
@AndreiMaz - Is this possibility to fix this in nopCommerce 4.20 ?

**Comment by dkmavai** [comment]
@rajupaladiya , @AndreiMaz  - Is there any update on it ?

**Comment by talha0324** [comment]
@AndreiMaz , any update or quick fix? I really need this or any heads up!

**Comment by holydk** [comment]
@rajupaladiya Hi. Are you completing an order through a change in status? 
There is a note that _"This option is only for advanced users (not recommended to change manually). All appropriate actions (such as inventory adjustment, sending notification emails, reward points, gift card activation/deactivation, etc) should be done manually in this case."_
To complete the order correctly, you need to create a shipment(s) with "delivered" status(es) and mark the order as paid.

Please let me know if the problem is relevant.

**Comment by DmitriyKulagin** [comment]
Not reproduced at 4.30 and up.
