### ISSUE TITLE
Price and short description load with Html.Raw

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3644]
Feature suggestion:

Many of store owners are using styled short description on product detail page on front-end side.
So it would be good if default nopCommerce display short description in @Html.Raw(Model.ShortDescription) in product detail template instead of @Model.ShortDescription.

Same as for display price, currently we already displaying label CALL FOR PRICE. 
So if we we inject it as Html.Raw(Price) then it would be good.

Many times need to override product templates and all view pages which are displaying price for just change @Model.Price to @Html.Raw(Model.Price).

So this is included in nopCommerce 4.10 and that would be good.

**Comment by AndreiMaz** [comment]
1. We'll think about short description 
2. But price shouldn't be in Html.Raw. If you want to apply some changes, then you'll have to customize CSS

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.
