### ISSUE TITLE
Cache result of "IsEuConsumer" method 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3649]
Moved from https://github.com/nopSolutions/nopCommerce/issues/3527 to a separate task

EuConsumer (It's a big fix for store's from Europe)
This method GetProductPrice uses method IsEuConsumer for each checking prices (one time for each price)
It's better to save the result of first request in local cache (per request)

protected virtual bool IsEuConsumer(Customer customer)
{
//check the cached value 
....
}

Also think about caching of this value in "Customer" entity

Original source: https://www.nopcommerce.com/boards/t/57914/performance-optimization-very-small-and-bix-fixes-for-taxservice.aspx

**Comment by RomanovM** [comment]
After some discussion decided not to implement it now.
