### ISSUE TITLE
Only Google maps API key available,cant we use Here MAP API 

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3650]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
Go to 
Administrator->Settings->Shipping settings->Advanced->Common
Only Google maps API key available,cant we use Here MAP API ??

**Comment by AndreiMaz** [comment]
@mrnams We don't use Google maps API as well. We don't use any maps API. I presume you've customized your solution

**Comment by mrnams** [comment]
@AndreiMaz No I have not customized, Go to
Administrator->Settings->Shipping settings->Advanced->Common
Only Google maps API

I have attached screenshot below

![2019-04-05 09_50_27-Shipping settings _ nopCommerce administration](https://user-images.githubusercontent.com/31761152/55603453-64cf8080-5788-11e9-8d41-54640fff7c63.png)

**Comment by AndreiMaz** [comment]
Ohh, I see now. You mean pickup addresse. We don't plan to support more API. We'll leave it for customization
