### ISSUE TITLE
Use single generic event for order status changes

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#3651]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Only OrderCancelledEvent is available, let us add Pending, Processing & Completed events.

Only when order is canceled or completed, email notification available, let us add when order is processing.

**Comment by astrumcs** [comment]
This idea has merit.  I believe that it would be a good idea to add a general event when there is any order status change.   Pass the old and new order status as an argument.
