### ISSUE TITLE
Cookies warning popup at centre of site

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3654]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
I understand we make default theme as simple,but we should display cookie warning dialog fixed to bottom as shown below
![Cookiefy](https://user-images.githubusercontent.com/31761152/55410228-1d2ad800-5581-11e9-82d2-e58366a40b18.png)

**Comment by RomanovM** [comment]
Thanks. We decided leave it for customization.
