### ISSUE TITLE
Pagination on Manufacturers page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3655]
Add a pager to "manufacturer/all" page

We had a feedback from a customer who sells products from over 300 manufacturers and he says browsing the manufacturer list page is difficult.

Source: https://www.nopcommerce.com/boards/t/61890/pagination-on-manufacturers-page.aspx

**Comment by DmitriyKulagin** [comment]
Done. See issue #75

**Comment by mssaluja78** [comment]
Hi, I have same requirement about pagination of manufacturer page. can you share your code for it.
