### ISSUE TITLE
Slug is not handled correctly

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3658]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
User delete part of slug and hit enter,then redirect to page not found.

FIX
While loading page we should check slug is matching with slug in database, if not then redirect to same page by appending slug from database.

refer https://stackoverflow.com, here try to edit slug and enter

![2019-04-03 23_01_03-nopCommerce demo store  Page not found](https://user-images.githubusercontent.com/31761152/55499810-82a3c500-5664-11e9-9434-684c983a168f.png)
![2019-04-03 23_01_25-nopCommerce demo store  Build your own computer](https://user-images.githubusercontent.com/31761152/55499812-82a3c500-5664-11e9-8775-989ba668bd04.png)

**Comment by AndreiMaz** [comment]
@mrnams Where exactly do you edit the slug? On the product details page in admin area? Or in admin area > system > Search engine friendly page names?

**Comment by mrnams** [comment]
in browser url,look both images url.
I agree this is not common practice that user edit slug.

but refer stackoverflow,

**Comment by AndreiMaz** [comment]
@mrnams you haven't answered my question. But if you edit the slug on the product details page at the "SEO" tab(in admin area), then it'll work as expected. The old URL will redirect to the new one. So you won't see the "page not found" error

**Comment by AndreiMaz** [comment]
@mrnams I also see that you play with our demo site - http://demo.nopcommerce.com/. So I presume you edited at http://admin-demo.nopcommerce.com/

Please see the warning displayed at https://www.nopcommerce.com/demo.aspx. It says "Please note that backend and frontend demo stores are not interconnected."

So it worls fine (redirects are made). Closing this issue

**Comment by mrnams** [comment]
@AndreiMaz I think we have communication gap, what i mean
"When user edit url in browser, then we should redirect to same page by correcting slug from database"

Example below is original url(correct slug)
https://stackoverflow.com/questions/14384007/how-to-update-github-forked-repository-using-tortoisegit

Now user modify url like this, user removed "tortoisegit" and trying to open below url
https://stackoverflow.com/questions/14384007/how-to-update-github-forked-repository-using-

Even though user modified slug value, system take slug from database and redirect to 
https://stackoverflow.com/questions/14384007/how-to-update-github-forked-repository-using-tortoisegit

**Comment by AndreiMaz** [comment]
Of course, it shouldn’t until this “slug” was previously used.

Stackoverflow is bad example because it has unique integer ID in URL. We don’t have it and it’s more SEO friendly

**Comment by mrnams** [comment]
@AndreiMaz Thanks a lot for update.
Yes I agree now.
