### ISSUE TITLE
Allow to delete previously entered addresses (during checkout)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3659]
Guests don't have an opportunity to delete previously entered billing addresses in front end (unilt they register and go to "My account" page). We should to edit/delete addresses during checkout

Source: https://www.nopcommerce.com/boards/t/61918/how-can-a-guest-delete-previously-entered-billing-addresses-in-front-end.aspx

**Comment by hfz-r** [comment]
Hi folks. Feel free to looks into my small PR https://github.com/nopSolutions/nopCommerce/pull/4289

**Comment by DmitriyKulagin** [comment]
Closed #3659
