### ISSUE TITLE
Performance issue when product has many discounts applied

### ISSUE THREAD

**Issue by cvalerio** [nopSolutions/nopCommerce#3663]
nopCommerce version: 4.10

When a product has a large number of Discount applied (of type Applied to SKUs), adding the product to the cart takes a long time.
Also loading the cart page is taking long time.

Steps to reproduce the problem: 
1) Create a large number of Discounts applied to SKUs and apply them to a single product (we tested with 500 discounts applied to a single product)
2) From store, add the product to the cart
3) Go to /cart page (it takes a long time to load)

Hints about the code causing the issue:
In PriceCalculationService.GetAllowedDiscountsAppliedToProduct you have this code:

```
            if (!product.HasDiscountsApplied) 
                return allowedDiscounts;

            //we use this property ("HasDiscountsApplied") for performance optimization to avoid unnecessary database calls
            foreach (var discount in product.AppliedDiscounts)
            {
                if (_discountService.ValidateDiscount(discount, customer).IsValid &&
                    discount.DiscountType == DiscountType.AssignedToSkus)
                    allowedDiscounts.Add(_discountService.MapDiscount(discount));
            }

```

Product.AppliedDiscounts is defined as follows:
```
   public IList<Discount> AppliedDiscounts => DiscountProductMappings.Select(mapping => mapping.Discount).ToList();
```

This is causing a single row select to the Discount table for each and every Discount applied to the product. When you have hundreds of discounts applied, this translates to poor performances.

We fixed this with:

```
      private readonly IRepository<Discount> _discountRepository;

       private readonly IRepository<DiscountProductMapping> _discountProductMappingRepository;
```
...

```
         var discounts = (from m in _discountProductMappingRepository.Table
            join d in _discountRepository.Table on m.DiscountId equals d.Id
            where m.ProductId == product.Id
            select d).ToList();
         foreach (var discount in discounts)
         {
            if (_discountService.ValidateDiscount(discount, customer).IsValid &&
                discount.DiscountType == DiscountType.AssignedToSkus)
               allowedDiscounts.Add(_discountService.MapDiscount(discount));
         }
```

**Comment by AndreiMaz** [comment]
already fixed in 4.30 after moving away from EF
