### ISSUE TITLE
Free shipping

### ISSUE THREAD

**Issue by MarshalOfficial** [nopSolutions/nopCommerce#3668]
Hi, I want to adjust shipping free for all orders (because of vendor policy, shipping expense will be discount for customers), now how and where can i adjust it ?
for default in checkout an order in shipping level there is nothing to choose and customer can not continue shipping and in administration page in configuration and shipping providers there is nothing and there is just address of marketplace to get a shipping provider plugin,
but in my case (free shipping) what is solution??
thanks,

**Comment by AndreiMaz** [comment]
Could you please this question on our forums? This GitHub tracker for issues and work items only

**Comment by MarshalOfficial** [comment]
> Could you please this question on our forums? This GitHub tracker for issues and work items only

Sure, Thanks
