### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by jmawebtech** [nopSolutions/nopCommerce#3670]
nopCommerce version: 4.1

Steps to reproduce the problem: 

Call this code:

public class MyController: BasePluginController

            IRepository<Order> orderRepository = EngineContext.Current.Resolve<IRepository<Order>>();
			IQueryable<Order> query = orderRepository.Table;
                DateTime beginTime = settings.LastDownloadUtc;
                DateTime endTime = settings.LastDownloadUtcEnd;

                query = query.Where(a => a.CreatedOnUtc >= beginTime);
                query = query.Where(a => a.CreatedOnUtc <= endTime);

                List<int> storeIds = GetStoreIds();

                if (storeIds.Count() > 0)
                    query = query.Where(a => storeIds.Contains(a.StoreId));

                var orders = new PagedList<Order>(query, 0, 1000).ToList();

				foreach(var order in orders){
				
				string state = order.BillingAddresss.Region.StateName;
				string country = order.BillingAddresss.Country.CountryName;
				
				}

Enumerate through the orders. It takes about two minutes to enumerate. How do I disable lazy loading in a custom plugin?

**Comment by AndreiMaz** [comment]
This is how EF works. You can use "Include" to load orders with addresses using one SQL command

Please use our forums for questrions. This tracker is for work items only
