### ISSUE TITLE
Make breadcrumb naming consistent

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3675]
See two screenshots. It's better to use the same separator (>)

![1](https://user-images.githubusercontent.com/5019111/55802615-44355c80-5ae1-11e9-8585-52f46b4b5386.png)

![2](https://user-images.githubusercontent.com/5019111/55802624-47304d00-5ae1-11e9-8d0f-10d08aa254ba.png)

**Comment by exileDev** [comment]
Closed #3675
