### ISSUE TITLE
Is it safe to store database user id and password  in "App_Data\dataSettings.json"?

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3676]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
Is it safe to store database user id and password  in "App_Data\dataSettings.json"?
We should use user secrets to store such sensitive information.

**Comment by AndreiMaz** [comment]
Yes. Please note that this file is downloadable from the Internet

**Comment by AndreiMaz** [comment]
Could you please post all further questions on our forums?

**Comment by mrnams** [comment]
sorry, shall use forum.

**Comment by mrnams** [comment]
@AndreiMaz  Sorry, but no one respond there.
