### ISSUE TITLE
Rename Homepage Poll Component view folder

### ISSUE THREAD

**Issue by razims** [nopSolutions/nopCommerce#3677]
nopCommerce version: 4.20
OS: Linux

To be on a safe side with a case-sensitive OS you should rename folder **HomePagePolls** https://github.com/nopSolutions/nopCommerce/tree/develop/src/Presentation/Nop.Web/Views/Shared/Components/HomePagePolls to **HomepagePolls**. Otherwise it may fail to find the view.

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Home/Index.cshtml line 20.

**Comment by RomanovM** [comment]
Thanks. Moved to https://github.com/nopSolutions/nopCommerce/issues/3609
