### ISSUE TITLE
SEO sitemap (sitemap.xml) doesn't add all links

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3678]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
SEO sitemap (yourdomain.com\sitemap.xml) not add all links.
sitemap.xml is missing news which admin added, they are listed on site but non added in sitemap.xml

**Comment by AndreiMaz** [comment]
It supports if you have "sitemapXmlSettings.SitemapXmlIncludeNews". So closing this "issue"

@mrnams Please let me ask you one more time. Please create a new topic on our forums first. We can discuss it. And if we confirm the issue, then we'll create a task on GitHub
