### ISSUE TITLE
CSS. Use Less or Sass or Stylus

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#368]
Use Less or Sass for CSS

**Comment by AndreiMaz** [comment]
after moving to asp.net core

**Comment by ngtrian** [comment]
Completed switching to asp.net core

**Comment by markadrake** [comment]
I don't begin to understand how to customize the current theme into something original given a 8,754 line CSS file compiled from what looks like many different sources. Why isn't this better organized? Why aren't the LESS/SASS files you are obviously building from included somewhere in the project? 

If I'm wrong, that would make me the happiest person in the world. Have I made a mistake? Missed something? 

I can of course roll my own, but I just want to customize what's there in a friendly manner.

**Comment by glhays** [comment]
Mark, I do not remember any Sass as part of the nop default css styling. You can add your own custom styling through your own custom theme based on the nop default theme. See the documentation. If you do not mind me asking why do you believe there are sass components. The styling for the default theme has not changed much over the years.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by markadrake** [comment]
@AndreiMaz I see from time to time you've updated this issue regarding SASS. Would you be open to sharing more detail about the status of this ticket and if the team would accept a PR? 

There are many ways to go about addressing a build system (to transpile the SASS). Does your team have a preference? This can be done in a way as not to inconvenience anyone - the resulting CSS file can still be included in the project. Perhaps it's best not to ship with any build system at all and allow the SASS to accompany the project for anyone who wants to make use of it.

All the best,

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
