### ISSUE TITLE
Microdata is missing important microdata attributes

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3682]
nopCommerce version: 4.1

Steps to reproduce the problem: 
The following link shows several errors and warning on NopCommerce's public demo page: 
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdemo.nopcommerce.com%2Fapple-macbook-pro-13-inch

**Comment by DmitriyKulagin** [comment]
Duplicate of this issue #4129
