### ISSUE TITLE
MemoryCacheManager.Get occurs System.StackOverflowException

### ISSUE THREAD

**Issue by yuessir** [nopSolutions/nopCommerce#3684]
nopCommerce version: 
latest dev branch
Steps to reproduce the problem: 
I installed a plugin with many settings.
Install was successful!
I traced the code to the class TaskManager.Initialize(), and can not go on debug.
Eventually I got the error like following:
![ovf](https://user-images.githubusercontent.com/8326310/56034091-ddba7380-5d58-11e9-97c7-651fa529df6e.png)

I have no ideas, please helping :{

**Comment by AndreiMaz** [comment]
@yuessir 
1. What exactly plugin do you mean? 
2. What do you mean by "Many settings"? How many? What settings?

**Comment by yuessir** [comment]
What exactly plugin do you mean?
 Customized **WidgetPlugin**
    What do you mean by "Many settings"? How many? What settings?
Sorry, no insert any setting to **Setting** Table 
I am not sure what happened. Maybe it is the  customized  widget plugin's problem. :{

**Comment by AndreiMaz** [comment]
We cannot find it without any details on how to reproduce it

**Comment by yuessir** [comment]
@AndreiMaz  I got it and will reopen the issue with sample later. Thanks
