### ISSUE TITLE
Paging not working in admin product tags and language string resources listing

### ISSUE THREAD

**Issue by spsinghats** [nopSolutions/nopCommerce#3686]
nopCommerce version: Latest code

Steps to reproduce the problem: 
1. Navigate to the language strings in admin
2. Select the langauge. Then search for resource string . e.g Home
3. The paging does not function in the search results.

Probable reason is the DataTables integration.

**Comment by AndreiMaz** [comment]
Thanks a lot! But it wasn't a bug. It was by design

**Comment by AndreiMaz** [comment]
Thanks. It's still being developed. These tables are not moved to DataTables yet
