### ISSUE TITLE
Make naming of params on the linq queries consistent

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#3692]
We must decide which approach to the names to choose and adhere to it in all requests, we use several approaches at once now:

`productVolume += _productAttributeParser.ParseProductAttributeValues(packageItem.ShoppingCartItem.AttributesXml)
	.Where(attributeValue => attributeValue.AttributeValueType == AttributeValueType.AssociatedToProduct)`

`var attributeValues = _productAttributeParser.ParseProductAttributeValues(shoppingCartItem.AttributesXml)
	.Where(x => x.AttributeValueType == AttributeValueType.AssociatedToProduct).ToList();`

`var query = _giftCardRepository.Table;
if (purchasedWithOrderId.HasValue)
	query = query.Where(gc => gc.PurchasedWithOrderItem != null && gc.PurchasedWithOrderItem.OrderId == purchasedWithOrderId.Value);`

**Comment by badijm** [comment]
Personally I'd prefer 2nd approach, which is the cleanest. (With **x** as lambda parameter)
Any other considerations?

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
