### ISSUE TITLE
SmtpClient is obsolete

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#3693]
nopCommerce version: 4.10

Steps to reproduce the problem: ...

Microsoft has marked `SmtpClient` as [obsolete](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-2.2) as it doesn't support many modern [protocols](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md).

They recommend using [MailKit](https://github.com/jstedfast/MailKit)

**Comment by exileDev** [comment]
#3693 Closed
