### ISSUE TITLE
Wrap info of "Loaded assemblies" (system information)

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3697]
nopCommerce version: 4.2

![Capture](https://user-images.githubusercontent.com/17789934/56284900-b7833380-60ca-11e9-9a73-92d793efd19a.PNG)

text is not WRAP, or cant scroll to right

**Comment by AndreiMaz** [comment]
@tigran-avdalyan Thanks a lot, Tigran! Fixed
