### ISSUE TITLE
Add "Image" specification attribute type

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#37]
We already have distinct attribute types supported for specification attributes. Let's add a new "Image" type 

Please note that we already support HTML input type. This way a store owner can manually specify an image URL. But it's better to make it more user-friendly

Forum source: https://www.nopcommerce.com/en/boards/topic/29080/suggestion-type-property-for-specification-attributes

Related work item: https://github.com/nopSolutions/nopCommerce/issues/7372

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/7372
