### ISSUE TITLE
Browser language isn't detected properly

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3701]
nopCommerce version: 4.10

Steps to reproduce the problem: Install 2 language EU and IT. Language display order doesn't matter here for me. Our website server is in Italy so they are using Italian culture on server. In previous version(nop 3.90) it was working fine. But in this version it works like below
- When I visited our site from Italy it shows me website in Italian language
- When I visited our site outside from Italy then also it shows site in Italian language.

_This issue only happen when customer open site & didn't login yet. After login it's showing site as per customer's choice language_

Under **GetLanguageFromRequest()**  method while debugging using logger
`var requestCulture = _httpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>()?.RequestCulture;` 

it gives culture = it-IT & UI culture = en-US which might be wrong for me if I m visiting site from India with en-US culture set in Browser(chrome).

so I follow up this link [https://stackoverflow.com/a/54877321](url)
& they suggested to use this & it works fine now with our site. customers form Italy can see site in Italian by default and customer outside Italy can see site in English

`var requestCulture = _httpContextAccessor.HttpContext.Request.GetTypedHeaders()
                       .AcceptLanguage
                       .OrderByDescending(x => x.Quality ?? 1) // Quality defines priority from 0 to 1, where 1 is the highest.
                       .Select(x => x.Value.ToString())
                       .FirstOrDefault();`

instead of this (your code)
`var requestCulture = _httpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>()?.RequestCulture;`

**Comment by RomanovM** [comment]
@jigarsangoi The code from SO answer is the same as in the default implementation of [AcceptLanguageHeaderRequestCultureProvider](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Middleware/Localization/src/AcceptLanguageHeaderRequestCultureProvider.cs#L26) that is used in RequestLocalizationMiddleware. 
It was necessary to simply add the supported culture values, since by default only the server one was used.
Thanks for the pointing out this bug.
