### ISSUE TITLE
Wrong profit in total of order when an orderitem prices are modified

### ISSUE THREAD

**Issue by pantonis** [nopSolutions/nopCommerce#3702]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Open an order from admin go to products edit a product and then add 0 to price inc VAT and price exc VAT and click update. profit in order totals is wrong (sometimes gives me negative) because in database Original Product price of that order item that was modified is not becoming zero.

**Comment by AndreiMaz** [comment]
@pantonis you should also update "order total" as well. Or go to admin area > configurtion > order settings > ensure that "Auto update order totals" is enabled

**Comment by pantonis** [comment]
@AndreiMaz  I am updating order total. Profit is not updated and is wrong. I have to go to the database and update the order item OriginalProductCost manually to make profit work.

"Auto update order totals" it says it is in beta mode. Is it still in beta mode or can I use it?

**Comment by AndreiMaz** [comment]
"OriginalProductCost" is not editable. It's saved when placing an order. It's by design

**Comment by pantonis** [comment]
yes but if you set the total values of the order item to 0 through the admin => Order => View=> Products tab the profit of the order is invalid
