### ISSUE TITLE
Error while installing on mac

### ISSUE THREAD

**Issue by cleopatra27** [nopSolutions/nopCommerce#3704]
nopCommerce version: 4.10

Steps to reproduce the problem: download files and build on VSCODE, run after changing the MapPath in NopFileProvider.  Receiving error after inputting details in the installation page:

An unhandled exception occurred while processing the request.

PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs, line 83

**Comment by ahmadkq** [comment]
4.1 version still not supporting Mac.

**Comment by skoshelev** [comment]
We fixed the problem with supporting UNIX compatible systems on #3095 ticket
