### ISSUE TITLE
RouteProvider improvements (suggestion)

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3709]
SUGGESTION 1:

The following 2 routes:

```
routeBuilder.MapLocalizedRoute("CustomerBackInStockSubscriptions", "backinstocksubscriptions/manage",
    new { controller = "BackInStockSubscription", action = "CustomerSubscriptions" });

routeBuilder.MapLocalizedRoute("CustomerBackInStockSubscriptionsPaged", "backinstocksubscriptions/manage/{pageNumber:regex(\\d*)}",
    new { controller = "BackInStockSubscription", action = "CustomerSubscriptions" });
```

I believe could be replaced with the following single route:

```
routeBuilder.MapLocalizedRoute("CustomerBackInStockSubscriptions", "backinstocksubscriptions/manage/{pageNumber:regex(\\d*)?}",
    new { controller = "BackInStockSubscription", action = "CustomerSubscriptions" });
```

where the {pagenumber} route segment has now been made optional to match both /backinstocksubscriptions/manage AND /backinstocksubscriptions/manage/1.

This would also require the route name in BackInStockSubscriptionController.CustomerSubscriptions to be changed from CustomerBackInStockSubscriptionsPaged to CustomerBackInStockSubscriptions.

SUGGESTION 2:

The following 2 routes (which map to the same controller and action) have different contraints for id:

```
routeBuilder.MapLocalizedRoute("CustomerProfile", "profile/{id:min(0)}",
    new { controller = "Profile", action = "Index" });

routeBuilder.MapLocalizedRoute("CustomerProfilePaged", "profile/{id}/page/{pageNumber:min(0)}",
    new { controller = "Profile", action = "Index" });
```

Should the second route be:

```
routeBuilder.MapLocalizedRoute("CustomerProfilePaged", "profile/{id:min(0)}/page/{pageNumber:min(0)}",
    new { controller = "Profile", action = "Index" });
```

SUGGESTION 3:

The following routes contain a regex(\\d*) constraint which I believe intends to restrict the route input to a number:

```
routeBuilder.MapLocalizedRoute("CheckoutCompleted", "checkout/completed/{orderId:regex(\\d*)}",
    new { controller = "Checkout", action = "Completed" });

routeBuilder.MapLocalizedRoute("CustomerBackInStockSubscriptionsPaged", "backinstocksubscriptions/manage/{pageNumber:regex(\\d*)}",
    new { controller = "BackInStockSubscription", action = "CustomerSubscriptions" });
```
NOTE: This route may potentially be altered in suggestion 1 above.

```
routeBuilder.MapLocalizedRoute("CustomerForumSubscriptionsPaged", "boards/forumsubscriptions/{pageNumber:regex(\\d*)}",
    new { controller = "Boards", action = "CustomerForumSubscriptions" });

routeBuilder.MapLocalizedRoute("ActiveDiscussionsPaged", "boards/activediscussions/page/{pageNumber:regex(\\d*)}",
    new { controller = "Boards", action = "ActiveDiscussions" });

routeBuilder.MapLocalizedRoute("TopicSlugPaged", "boards/topic/{id:min(0)}/{slug?}/page/{pageNumber:regex(\\d*)}",
    new { controller = "Boards", action = "Topic" });

routeBuilder.MapLocalizedRoute("ForumSlugPaged", "boards/forum/{id:min(0)}/{slug?}/page/{pageNumber:regex(\\d*)}",
    new { controller = "Boards", action = "Forum" });
```

Source: https://www.nopcommerce.com/boards/t/62243/potential-improvements-to-routeprovidercs.aspx

**Comment by davidandrewpowell** [comment]
_It does not appear that all of the original issue description from the nopcommerce forum has been copied here for suggestion 3.  The remaining text describes the issues with the 6 routes mentioned in suggestion 3.  For completeness, I have added this text below:_

It appears that there are a couple of potential issues with the regex constraint:

i) The regex may not be correct and may allow alphanumeric characters.  For example, if you take the second route and enter:

/backinstocksubscriptions/manage/a

Then the BackInStockSubscriptionController.CustomerSubscriptions action is executed but the pageNumber parameter is null.

I believe that the correct regex should be: regex(\\d+$)
_Note: That said, I believe a different constraint should be used (see below)._

And indeed, if you change the regex to this above then no more routes are matched for /backinstocksubscriptions/manage/a which is expected.

If you use http://regexstorm.net/tester you will see that the \d* pattern does match both numbers and letters.

ii) It is not always clear from a quick glance at regular expressions what is trying to be achieved or if it is correct (hence the potential issue above).

Each of these routes map to an action with an int or int? parameter type.

Therefore I would instead suggest an int route constraint.  For example, the first route above would become:

```
routeBuilder.MapLocalizedRoute("CheckoutCompleted", "checkout/completed/{orderId:int}",
    new { controller = "Checkout", action = "Completed" });
```

**Comment by davidandrewpowell** [comment]
SUGGESTION 4:

Additionally, the following 2 routes:

```
routeBuilder.MapLocalizedRoute("CustomerForumSubscriptions", "boards/forumsubscriptions",
    new { controller = "Boards", action = "CustomerForumSubscriptions" });

routeBuilder.MapLocalizedRoute("CustomerForumSubscriptionsPaged", "boards/forumsubscriptions/{pageNumber:int}",
    new { controller = "Boards", action = "CustomerForumSubscriptions" });
```


can also be replaced with the following single route:

```
routeBuilder.MapLocalizedRoute("CustomerForumSubscriptions", "boards/forumsubscriptions/{pageNumber:int?}",
    new { controller = "Boards", action = "CustomerForumSubscriptions" });
```
