### ISSUE TITLE
Custom search engine that should display search results with blog and forums entries too

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#371]
Custom search engine that should display search results with blog and forums entries too, currently search engine works only for product and forum search engine only works for forums, what about blog posts ? and company information pages like private policy, terms -conditions, shipping policy, about us pages etc ?

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
