### ISSUE TITLE
Pickup store id not saved in order

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#3710]
nopCommerce version: 4.1

Steps to reproduce the problem: 
When using the pickup in store, pickup id is not stored in the order, only the address id that is created on fly but not the one attached to the pickup point. I faced a situation that i need the pickup object so i have no idea how to get it.

**Comment by RomanovM** [comment]
@ahmadkq 
There is no need to store pickup point ids in orders in the basic functionality of the plugin.
But you can use generic attributes for this in your needs.
