### ISSUE TITLE
Nopcommerce slow on VS2019

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#3716]
nopCommerce version: 4.1

Steps to reproduce the problem: 
Use 4.1 in nopcommerce.

VS keeps hanging on small changes. Navigation, scrolling, name change, code change etc.
This is not an issue in other core projects.

**Comment by AndreiMaz** [comment]
Thanks for reporting. But I don't think that it's related to nopCommerce and we can do anything about that. It should be addresses to VS team
