### ISSUE TITLE
VAT number issues

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#372]
There are four problems with the current VAT Number implementation. 

1) VAT number can not be entered in the anonymous checkout 
http://www.nopcommerce.com/boards/t/6016/vat-number-bugs-and-one-enhancement.aspx
2) The web service which you use does not tell you if the VAT Number is valid it tells if the Company with the VAT number is registered as payer of VAT. There are companies which have VAT number but they are not VAT payers. VAT can be exempt to you if you are VAT payer from different EU country. Even if you are not VAT payer your VAT number should be included on invoice (at least according to Czech law). So, it means this needs to be changed: 
VatNumberStatus.Invalid -> VatNumberStatus.NotVatPayer 
VatNumberStatus.Valid -> VatNumberStatus.ValidVatPayer 

3) The country prefix should be shown on each place the VAT number is shown (at least to the customer) (invoice, order... ) 

It would be nice if entering a VAT number would fill company name, address and zip code. The web service returns this info. I would execute the web service right after entering the number. If it would be known VAT payer the details can be filled (but it should not overwrite details which are already filled). And the info about VAT Number status can be shown immediately too. Another possibility: add a button "Get company address from the VAT number"

**Comment by AndreiMaz** [comment]
split to multiple tasks
