### ISSUE TITLE
    Setup failed: Image cannot be loaded. Available decoders: - GIF : GifDecoder - PNG : PngDecoder - JPEG : JpegDecoder - BMP : BmpDecoder

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3720]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
While installing it throws following error

" Setup failed: Image cannot be loaded. Available decoders: - GIF : GifDecoder - PNG : PngDecoder - JPEG : JpegDecoder - BMP : BmpDecoder"

**Comment by AndreiMaz** [comment]
@mrnams It works fine. I cannot reproduce it
P.S. Could you please post all questions and suggestions https://www.nopcommerce.com/boards/ ?

**Comment by ChenZhaobin** [comment]
@AndreiMaz  I met with same problem when installing on centos server provided by bluehost

**Comment by ChenZhaobin** [comment]
@mrnams  hi,how do you do to solve this problem
