### ISSUE TITLE
Reward points not calculated because SelectedShippingOptionAttribute is always null

### ISSUE THREAD

**Issue by pantonis** [nopSolutions/nopCommerce#3722]
nopCommerce version: 4.1

Steps to reproduce the problem: 
When I place items into cart and then go to cart reward points are not shown. While debugging I discovered that in OrderTotalCalculationService.cs in GetShoppingCartShippingTotal method 
  ```
 if (customer != null)
                shippingOption = _genericAttributeService.GetAttribute<ShippingOption>(customer, NopCustomerDefaults.SelectedShippingOptionAttribute, _storeContext.CurrentStore.Id);
```

`shippingOption `is always null.

**Comment by DmitriyKulagin** [comment]
Hi, @pantonis 

Reward points are calculated at checkout. And this happens if the attribute useRewardPoints = true
