### ISSUE TITLE
"admin.dt.lengthmenu" override on "admin.paginate.next"

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3723]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
I am surprised instead of icons it is showing text that to overridden 
"admin.dt.lengthmenu" override on "admin.paginate.next"

Please refer image 
![2019-04-27 16_19_37-Registered customers _ nopCommerce administration](https://user-images.githubusercontent.com/31761152/56848624-d4a8d500-6908-11e9-8ef2-110add63d1e3.png)

**Comment by AndreiMaz** [comment]
Have you executed the upgrade script? It works fine

**Comment by mrnams** [comment]
@AndreiMaz Thanks for quick reply,
One query I have started fresh from 4.20, then why do we need to execute upgrade script 4.10 to 4.20
