### ISSUE TITLE
Setup failed: XML parsing

### ISSUE THREAD

**Issue by yuessir** [nopSolutions/nopCommerce#3724]
nopCommerce version: 
ab52ed768  Removed x-scrolling option
Steps to reproduce the problem: 
install failed

Same problem with the thread:
https://www.nopcommerce.com/boards/t/62434/nopcommerce-docker.aspx

Trying out to install nop on Docker, app is running but can't complete installation

error is
Setup failed: XML parsing: line 1, character 38, unable to switch the encoding

Any ideas what is causing it?

setting it up with
servername: nopcommerce_database
databasename: nopdb

sql user: sa
password: default from compose

Am i missing something?

**Comment by AndreiMaz** [comment]
Already fixed https://github.com/nopSolutions/nopCommerce/commit/a1d352c609ee027bab9d1533d7d07d4318a18a12
