### ISSUE TITLE
DataTables. ScrollX and pager issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3727]
I've described it at https://datatables.net/forums/discussion/56032/scrollx-and-pager-issue

it's similar to https://github.com/nopSolutions/nopCommerce/commit/3bb5fa5fd7b7808fff98ea19efdd0df07a0ec797

Also see a screenshot
![pager](https://user-images.githubusercontent.com/5019111/56891813-5eca7800-6a86-11e9-80ec-b5aa5599ea6e.png)

**Comment by ronenelahav** [comment]
I can't create the same issue... 
from my experience with datatables - you need to dd more parameters for everything to work well...
 I added those :
            colReorder = true;
            autowidth = false;
            responsive = true;
            lengthChange = true;
            pageResize = true;
            bScrollCollapse = true;
            sScrollX = "100%";
            sScrollXInner = "100%";
they solve the resizing issue of the window (scrumble the columns and headers alignment)
I think that also solve the scrolling issue..

**Comment by tigran-avdalyan** [comment]
Can you see that issue 
When Grid table is loading -- you can see grid style issue
![mmm](https://user-images.githubusercontent.com/17789934/58240903-c4fe8f80-7d00-11e9-86b8-a2b576f1ec8e.gif)

**Comment by DmitriyKulagin** [comment]
@tigran-avdalyan Hi, We redraw the table after the window has been resized and has completed the shift animation. So it was intended.
Initially this topic was created [here](https://github.com/nopSolutions/nopCommerce/issues/3730)

**Comment by tigran-avdalyan** [comment]
@DmitriyKulagin Please see this video to
![kkk2](https://user-images.githubusercontent.com/17789934/58248298-98eb0a80-7d10-11e9-9002-45956419916e.gif)

**Comment by DmitriyKulagin** [comment]
Closed #3727
