### ISSUE TITLE
Description for checkout/product/specification attribute values (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#373]
Description for checkout/product/specification attribute values: 

https://nopcommerce.codeplex.com/SourceControl/network/forks/rudgr/attributevaluedescription 

and submitted pull request: 

https://nopcommerce.codeplex.com/SourceControl/network/forks/rudgr/attributevaluedescription/contribution/8508

Let's decide whether we should support description for attributes or values

**Comment by rudgr** [comment]
This implementation allows store owners to add Description to checkout/product/specification attribute values.
For example this would allow you to show blue info marker icons that could show more info to customer about the attribute value option. (for example why customer should choose this option and pay more ;-)

[http://demo.nopcommerce.com/build-your-own-computer](http://demo.nopcommerce.com/build-your-own-computer)

**Comment by rudgr** [comment]
hi @mariannk 

was wondering if this nice feature will be included in nop3.80? ;-)

thanks!

**Comment by AndreiMaz** [comment]
![f020d45a-de7b-11e6-8c8b-ba525607db49](https://cloud.githubusercontent.com/assets/5019111/22120941/e793c164-de92-11e6-9429-67bd1d5b7bbe.png)

**Comment by rudgr** [comment]
sorry @AndreiMaz my russian is not so good... what does this screenshot mean? tx

**Comment by AndreiMaz** [comment]
@rudgr it's just an idea how it could be displayed (descriptions) - hints (popups)

**Comment by rudgr** [comment]
great!:)

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality.
