### ISSUE TITLE
DataTables. Column borders are not properly displayed in RTL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3730]
nopCommerce version: 4.20

1. In RTL:
See screenshot. There's no border between the last two columns:

![no_borders](https://user-images.githubusercontent.com/5019111/56894513-cd133880-6a8e-11e9-9922-7fa8c3852438.png)

2: When changing window size:
see comments below and https://github.com/nopSolutions/nopCommerce/issues/3770

**Comment by ronenelahav** [comment]
![image](https://user-images.githubusercontent.com/17380300/57034303-d4397280-6c57-11e9-87ab-0624eccf2324.png)
there seems to be another issue - when changing window size... it messes up all the columns

**Comment by mariannk** [comment]
> ![image](https://user-images.githubusercontent.com/17380300/57034303-d4397280-6c57-11e9-87ab-0624eccf2324.png)
> there seems to be another issue - when changing window size... it messes up all the columns

Hi. Are you expiriencing this issue on mobile devices?

**Comment by ronenelahav** [comment]
> > ![image](https://user-images.githubusercontent.com/17380300/57034303-d4397280-6c57-11e9-87ab-0624eccf2324.png)
> > there seems to be another issue - when changing window size... it messes up all the columns
> 
> Hi. Are you expiriencing this issue on mobile devices?
Haven't Checked yet...

**Comment by mariannk** [comment]
> > > ![image](https://user-images.githubusercontent.com/17380300/57034303-d4397280-6c57-11e9-87ab-0624eccf2324.png)
> > > there seems to be another issue - when changing window size... it messes up all the columns
> > 
> > 
> > Hi. Are you expiriencing this issue on mobile devices?
> > Haven't Checked yet...

Seems like it's just a browser resizing issue. It's ok on devices.

**Comment by tigran-avdalyan** [comment]
Not only in RTL.

**Comment by mariannk** [comment]
> Not only in RTL.

Could you please provide some screenshots?

**Comment by DmitriyKulagin** [comment]
Closed #3730
