### ISSUE TITLE
DataTables. Better footer styling

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3738]
nopCommerce version: 4.20

Right now we have as per the attached screenshot:
![pager](https://user-images.githubusercontent.com/5019111/56945178-d7850f00-6b2e-11e9-96a4-a277ca402f9b.png)

We did it because it wasn't displayed properly in some cases (e.g. on dashboard or small screen devices) when the dropdownlist was centered (it was displayed above the pager). Let's display them in the same row so widths are not fixed. 

It can be done at https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/_Table.Definition.cshtml#L149

**Comment by tigran-avdalyan** [comment]
![error3](https://user-images.githubusercontent.com/17789934/58239731-76e88c80-7cfe-11e9-8911-7e46ea2e40f5.PNG)

**Comment by ronenelahav** [comment]
Footer issues on RTL=> the direction of the buttons is wrong 
![image](https://user-images.githubusercontent.com/17380300/58418939-ec06e980-8091-11e9-8fb1-26bbeeefa2f2.png)

**Comment by DmitriyKulagin** [comment]
Closed #3738
