### ISSUE TITLE
Designing issue in child data-table on Shipment list page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3739]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
1. Go to Admin > Sales > Shipment
2. Open shipment items from shipment list table 
3. Check designs

Click [here](https://i.ibb.co/BZF8zdd/shipment-design.png) for see screen shot.

**Comment by RomanovM** [comment]
Thanks. Duplicate of https://github.com/nopSolutions/nopCommerce/issues/3728
