### ISSUE TITLE
Bulk Edit product is missing in nopCommerce 4.20 Beta

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3740]
nopCommerce version: 4.20

Steps to reproduce the problem: Go to Admin > Catalog > Product

There is Bulk Edit product option is missing.

**Comment by RomanovM** [comment]
Thanks. This is intentional, see details in https://github.com/nopSolutions/nopCommerce/commit/2f73ab4f45022c2ca8d7d931409a4ee67b298136
