### ISSUE TITLE
Configuration page of Manual (Fixed or By Weight and By Total) is throwing error 

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3741]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
**Checking with no source code in IIS**
1. Go to Admin > Configuration > Shipping > Shipping Providers
2. Click configure button of **Manual (Fixed or By Weight and By Total)**

It's show default error message.
Here is error log

**Page URL:** http://localhost:8066/Admin/FixedByWeightByTotal/Configure

**Short message**: 
`One or more compilation failures occurred:
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(143,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(149,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(154,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(159,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(164,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(169,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(174,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(181,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.FixedByWeightByTotal\Views\_ByWeightByTotal.cshtml(188,55): error CS0103: The name 'ShippingByWeightByTotalModel' does not exist in the current context`

**Comment by rajupaladiya** [comment]
Same issue in **UPS (United Parcel Service)** plugin configuration page.

Page URL: Admin/UPSShipping/Configure

Here is Error Message:
`One or more compilation failures occurred:
dpu0yu04.il2(1312,103): error CS1031: Type expected
dpu0yu04.il2(1312,269): error CS1031: Type expected
dpu0yu04.il2(1312,435): error CS1031: Type expected
dpu0yu04.il2(1312,601): error CS1031: Type expected
dpu0yu04.il2(1312,773): error CS1031: Type expected
dpu0yu04.il2(1312,945): error CS1031: Type expected
dpu0yu04.il2(1312,1117): error CS1031: Type expected
dpu0yu04.il2(1312,1281): error CS1031: Type expected
dpu0yu04.il2(1312,1445): error CS1031: Type expected
dpu0yu04.il2(1312,1609): error CS1031: Type expected
dpu0yu04.il2(1312,1771): error CS1031: Type expected
dpu0yu04.il2(1312,1933): error CS1031: Type expected
dpu0yu04.il2(1312,2095): error CS1031: Type expected
dpu0yu04.il2(1312,2285): error CS1031: Type expected
dpu0yu04.il2(1312,2475): error CS1031: Type expected
dpu0yu04.il2(1312,2665): error CS1031: Type expected
dpu0yu04.il2(1312,2831): error CS1031: Type expected
dpu0yu04.il2(1312,2997): error CS1031: Type expected
dpu0yu04.il2(1312,3163): error CS1031: Type expected
dpu0yu04.il2(1312,3335): error CS1031: Type expected
dpu0yu04.il2(1312,3507): error CS1031: Type expected
dpu0yu04.il2(1312,3679): error CS1031: Type expected
dpu0yu04.il2(1312,3851): error CS1031: Type expected
dpu0yu04.il2(1312,4023): error CS1031: Type expected
dpu0yu04.il2(1312,4195): error CS1031: Type expected
dpu0yu04.il2(1312,4389): error CS1031: Type expected
dpu0yu04.il2(1312,4583): error CS1031: Type expected
dpu0yu04.il2(1312,4777): error CS1031: Type expected
dpu0yu04.il2(1312,4971): error CS1031: Type expected
dpu0yu04.il2(1312,5163): error CS1031: Type expected
dpu0yu04.il2(1312,5355): error CS1031: Type expected
dpu0yu04.il2(1312,5547): error CS1031: Type expected
dpu0yu04.il2(1312,5715): error CS1031: Type expected
dpu0yu04.il2(1312,5883): error CS1031: Type expected
dpu0yu04.il2(1312,6051): error CS1031: Type expected
dpu0yu04.il2(1312,6225): error CS1031: Type expected
dpu0yu04.il2(1312,6399): error CS1031: Type expected
dpu0yu04.il2(1312,6573): error CS1031: Type expected
dpu0yu04.il2(1312,6759): error CS1031: Type expected
dpu0yu04.il2(1312,6945): error CS1031: Type expected
dpu0yu04.il2(1312,7131): error CS1031: Type expected
dpu0yu04.il2(1312,7291): error CS1031: Type expected
dpu0yu04.il2(1312,7451): error CS1031: Type expected
dpu0yu04.il2(37,98): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1311,71): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,85): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,251): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,417): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,583): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,755): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,927): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1099): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1263): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1427): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1591): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1753): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,1915): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2077): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2267): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2457): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2647): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2813): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,2979): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,3145): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,3317): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,3489): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,3661): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,3833): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4005): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4177): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4371): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4565): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4759): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,4953): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,5145): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,5337): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,5529): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,5697): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,5865): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6033): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6207): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6381): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6555): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6741): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,6927): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,7113): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,7273): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
dpu0yu04.il2(1312,7433): error CS0246: The type or namespace name 'UPSShippingModel' could not be found (are you missing a using directive or an assembly reference?)
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(16,49): error CS0103: The name 'PackingType' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(20,54): error CS0103: The name 'PackingType' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(24,54): error CS0103: The name 'PackingType' does not exist in the current context
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(72,86): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(75,87): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(76,96): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
H:\Raju Paladiya\nopCommerce-4.20-Beta\nopCommerce_4.20_Beta_NoSource\Plugins\Shipping.UPS\Views\Configure.cshtml(133,31): error CS1503: Argument 3: cannot convert from 'method group' to 'object'`

**Comment by RomanovM** [comment]
Thanks. Moved to https://github.com/nopSolutions/nopCommerce/issues/3761
