### ISSUE TITLE
Bad routing after install Api Plugin for Guest without permission in ACL

### ISSUE THREAD

**Issue by kingsimonever** [nopSolutions/nopCommerce#3742]
nopCommerce version: 4.10

Steps to reproduce the problem: 
Disable all checkbox for Guest ( disable allow navigation etc. )
Install Api plugin [https://github.com/SevenSpikes/api-plugin-for-nopcommerce](https://github.com/SevenSpikes/api-plugin-for-nopcommerce)
When you logged out go to main page which should redirect you to http://localhost:15536/login but you will be redirect to http://localhost:15536/account/login which means page not found.

I can't find a solution to this problem, but I want to use the API and have a store available only to registered user.
Someone has an idea?

**Comment by RomanovM** [comment]
You should contact with plugin developer [sales@nop-templates.com](mailto:sales@nop-templates.com)
