### ISSUE TITLE
Getting Error while click Payment(Check / Money Order) method configure button

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3746]
nopCommerce version: Beta 4.20

Steps to reproduce the problem: 

no source at local IIS

Admin/PaymentCheckMoneyOrder/Configure

getting below page

![paymennt](https://user-images.githubusercontent.com/41533502/56972205-34f97a00-6b88-11e9-9dd1-5f0c50ab35bd.PNG)

**Comment by RomanovM** [comment]
Thanks. Moved to #3761
