### ISSUE TITLE
Hint missing for Custom address attributes , Custom customer attributes and required mark

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3747]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

1) setup at local IIS

2) Add any Custom address attributes  and set as required

3) open this url Admin/Customer/AddressEdit?customerId=8&addressid=6

![customattribute](https://user-images.githubusercontent.com/41533502/56975216-eea71980-6b8d-11e9-8d72-12b7cf7b108e.PNG)

**Comment by AndreiMaz** [comment]
Custom attributes don't support description. So it's by design
