### ISSUE TITLE
Focus is not set when change Shipping method name from order Edit even url look like (Admin/Order/Edit/1#order-billing-shipping)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3749]
nopCommerce version: beta 4.20

Steps to reproduce the problem: 
1) setup at local IIS

2)  go Admin/Order/Edit/1

3) try to change shipping method name 

4) it's changed but it not focus there while i saw at url.

it look like Admin/Order/Edit/1#order-billing-shipping

so may be it should be focus at order-billing-shipping Collapsible

**Comment by RomanovM** [comment]
I can not reproduce this behavior. It works as expected, after loading page with that URL it displays "Billing & shipping" panel.

**Comment by sk5202** [comment]
Hello @RomanovM 

See here i've record video for this issue.

It is working but sometime it is not working too.

https://www.loom.com/share/701c10f700c347a59b96cfe1f320a773

**Comment by AndreiMaz** [comment]
It works fine. I also cannot reproduce it. 

P.S. Just don't move your mouse (scroll) after saving
