### ISSUE TITLE
Design issue with decimal and int fields at media,blog,news etc settings.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3750]
nopCommerce version: beta 4.20

Steps to reproduce the problem: 

1) setup at local IIS

2) go /Admin/Setting/Media

3) in my case i choose **Other pages** collapsible 

try expand and collapse (2 3 times)

4) design look strange. here is the picture

![collapse issue](https://user-images.githubusercontent.com/41533502/56978909-35990d00-6b96-11e9-882a-9d338b052964.PNG)

**Comment by mariannk** [comment]
Hi. Which browser do you use? Can you retrieve this in Chrome?

**Comment by sk5202** [comment]
Yes sure.

I used Chrome while testing.

I will prepare video and send you in 1 hour
