### ISSUE TITLE
Redis serialization self-referencing loop for SpecificationAttributes

### ISSUE THREAD

**Issue by rdantonio** [nopSolutions/nopCommerce#3751]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
1. Enable Redis caching
2. In admin panel, edit a product with specification attributes

An internal server error occurs:
`JsonSerializationException: Self referencing loop detected for property 'SpecificationAttribute' with type 'Castle.Proxies.SpecificationAttributeProxy'. Path '[0].SpecificationAttributeOptions[0]'.`

The Models for `SpecificationAttribute` and `SpecificationAttributeOption` refer to each other so when they get serialized it's causing this circular reference error. Locally I added a `[JsonIgnore]` attribute to the `SpecificationAttributeOption`'s `SpecificationAttribute` property, which seems to fix the issue.

**Comment by sk5202** [comment]
Can you please explain how to enable Redis caching ?

**Comment by rdantonio** [comment]
@sk5202 In `appsettings.json` (in the root of Nop.Web) set the following:

`"RedisEnabled": true`
`"RedisConnectionString": "<your connection string here>"`
`"UseRedisForCaching": true`

**Comment by sk5202** [comment]
@rdantonio  thanks
