### ISSUE TITLE
Nivo slider with Multi store- check box not selected but still able to update picture

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3752]
nopCommerce version: 4.20 Beta

Issue: With Multi-store, with select store and  able to upload picture even checkbox is not checked.

Steps to reproduce the problem: 
1. Configure store with Multiple store
2. Go to Nivo slider Configuration page
3. Select store 2 from store selection dropdown
4. Upload picture without select checkbox 

It allow to upload picture without check checkbox, but it should not allow.

See [here](https://i.ibb.co/HHLgWZ0/nivo-slider.gif) gif.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
