### ISSUE TITLE
Nivo slider - all Images are remove on change image with multi store

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3753]
nopCommerce version: 4.20 Beta

Description: When I set image for slider store wise and save, it's remove all images from configuration

Steps to reproduce the problem: 

1. Configure store with Multiple store
2. Go to Nivo slider Configuration page
3. Select store 2 from store selection drop-down
4. Change image and click on Save button
5. It's removing all images from configure page, but it should be available there

Click [here](https://i.ibb.co/y8kmt5p/nivo-slider-save-issue.gif) to see gif.

**Comment by szocco** [comment]
Not ideal, but here's how we make this work. In multi-store mode, you must check the boxes for all images, not just the one your are uploading before saving.   Leaving any unchecked signals to NIVO that you no longer want that image, and deletes it.

**Comment by sk5202** [comment]
yes you should select checkbox while you working with multi-store.

could you please check once?

**Comment by rajupaladiya** [comment]
> yes you should select checkbox while you working with multi-store.
> 
> could you please check once?

Please check other setting page, without select checkbox, you can't edit setting. That is disable until check store limited checkbox.
