### ISSUE TITLE
Something transacting against ScheduleTask causing the application to time out at startup

### ISSUE THREAD

**Issue by lukepothier** [nopSolutions/nopCommerce#3754]
nopCommerce version: 4.1

Steps to reproduce the problem:

- Install and set up nopCommerce 4.1 application with database on a network server
- Deploy nopCommerce application to another server and use the existing DB from step 1

I have a virtually unmodified nopCommerce 4.1 application which I've deployed to an IIS server on my network. I ran through the application setup, and connected to a database I'd created previously from my own PC. The deployment was successful, and initially the site connected to the DB without issue, but after a couple of hours everything stopped working with the following error:

```
An error occurred while starting the application.
Win32Exception: The wait operation timed out
Unknown location

SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

Win32Exception: The wait operation timed out
```

Running the application locally pointing to the same DB, I narrowed it down to a SQL command the application runs at startup:

```
SELECT [t].[Id], [t].[Enabled], [t].[LastEndUtc], [t].[LastStartUtc], [t].[LastSuccessUtc], [t].[Name], [t].[Seconds], [t].[StopOnError], [t].[Type]
FROM [ScheduleTask] AS [t]
WHERE [t].[Enabled] = 1
ORDER BY [t].[Seconds] DESC
```

which was timing out.

I ran the command manually in SSMS, and so far it's taken 35 minutes and has not returned. I separately ran the same query but with nolock, and it returns successfully immediately:

```
SELECT [t].[Id], [t].[Enabled], [t].[LastEndUtc], [t].[LastStartUtc], [t].[LastSuccessUtc], [t].[Name], [t].[Seconds], [t].[StopOnError], [t].[Type]
FROM [ScheduleTask] AS [t]
WITH (NOLOCK)
WHERE [t].[Enabled] = 1
ORDER BY [t].[Seconds] DESC
```

So it seems as though something is transacting against the ScheduleTask table indefinitely (or at least for a very long time) which seems like a bug to me.

I should also note that restarting the application doesn't help.

**Comment by Sizzler6610** [comment]
> So it seems as though something is transacting against the ScheduleTask table indefinitely (or at least for a very long time) which seems like a bug to me.

It appears that there is blocking or deadlocking in the database.  When this happens, if running your query in SSMS, right click on the server name in object explorer and select "Activity Monitor", this will show all the other processes going on during this time, including wait times, memory usage, expensive queries, etc.  This could lead to identifying the culprit causing the deadlocking.   
![activity_monitor](https://user-images.githubusercontent.com/37249950/57172247-6625b480-6deb-11e9-81cf-1cbea3e6ccb9.jpg)

**Comment by lukepothier** [comment]
I've been away from the PC since opening the issue, now everything is working as expected. I'm going to close it. If this happens again, I'll reopen and provide detail. Thanks @Sizzler6610 , I will diagnose with that method if this happens again.
