### ISSUE TITLE
Add notification after saving customer info (myaccount page) detail.

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3755]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: 
Did not get any notification if i save my customer info (myaccount page) detail.

**Comment by sangeetshah** [comment]
@AndreiMaz  is this not bug? because customer dont know form is saved or not. because customer cant get any notification whether data is saved or not.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
