### ISSUE TITLE
Desing issue on Apply for Vendor page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3758]
nopCommerce version: 4.20 Beta

Issue: Design issue on apply for vendor page

Steps to reproduce the problem: 
1. Login in Store
2. Scroll to bottom and click to Apply for Vendor link
3. See, there is design issue with title.

![Apply For Vendor](https://i.ibb.co/NjZ56mQ/vendor-apply.png)

**Comment by RomanovM** [comment]
It's by design. See details in https://github.com/nopSolutions/nopCommerce/issues/3717
