### ISSUE TITLE
bar-notification error append one by one. it not replace with existing on product detail page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3760]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: 
bar-notification error append one by one. it not replace with existing on product detail page
![Untitled](https://user-images.githubusercontent.com/10364140/57064156-21165b00-6ce3-11e9-8265-4de7aa24a59f.png)

**Comment by RomanovM** [comment]
This is by design. You can customize it if you want.

**Comment by rajupaladiya** [comment]
> This is by design. You can customize it if you want.

Sorry @RomanovM, but notification should be hide after some time or overlay with existing as it working fine in nopCommerce 4.10. I don't think it by design.

**Comment by sangeetshah** [comment]
@RomanovM error notification need to be replace as working into nop4.1.

**Comment by RomanovM** [comment]
Well, you are right. Possible broken in https://github.com/nopSolutions/nopCommerce/commit/8ecc69a702a91b3e37654aa7c523221cc8685d89

**Comment by DmitriyKulagin** [comment]
Closed #3760
