### ISSUE TITLE
Unnecessary popup while attached file save in order note , Product etc.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3764]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

1) setup local IIS

2) go Admin/Order/Edit/1 order note panel

3) check Attached file and Use download URL

4) directly click on save button without type 

anything in Download URL

it display unnecessary popup,It should be show object is saved as per 4.10.(considered you do not write anything in Download URL text box)

or it should save validation like please enter url.

same thing you can see at Admin/Product/Edit/10 here

![note](https://user-images.githubusercontent.com/41533502/57090104-a7eb2800-6d23-11e9-8060-00408abaed7e.PNG)

**Comment by DmitriyKulagin** [comment]
Closed #3764
