### ISSUE TITLE
RoxyFilemanController + Linux + DatabaseRoxyFilemanService

### ISSUE THREAD

**Issue by zzDave** [nopSolutions/nopCommerce#3766]
nopCommerce version:  4.2 Current Develop

Steps to reproduce the problem: 

"Store pictures in database" is set to true:
Go to content management, select topics, and edit the first topic. 
Insert a new image. 
The system saves the image in the database AND is storing it in the file system.  It is also checking the file system to verify the name is unique.   I did not check to see where the image comes from when displaying it on a content page. 

It should check the database for a unique file name.
It should not store the image on the file system.

If you are using the file system to save images and running on Linux:
The path is incorrect for the conf.json config file.    With the current path, it will try to create a file at the root called "wwwroot\lib\Roxy_Fileman\conf.json", rather than putting it in that directory.   The file upload paths need to be updated to work in Linux.

**Comment by zzDave** [comment]
A simple fix for the Linux path issue.   Just replace the slashes with the Path.DirectorySeperatorChar.

In the BaseRoxyFilemanService.cs

`  
        protected virtual string GetFullPath(string virtualPath) {
            virtualPath = virtualPath ?? string.Empty;
            if (!virtualPath.StartsWith("/"))
                virtualPath = "/" + virtualPath;
            virtualPath = virtualPath.TrimEnd('/');
            
            // Fix the path for the current environment.
            return _hostingEnvironment.WebRootPath + virtualPath.Replace('/', Path.DirectorySeparatorChar);            
        }
`

**Comment by skoshelev** [comment]
Closed #3766
