### ISSUE TITLE
Product reviews - Grid style issue

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3770]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: go to Product review in Admin panel
and see Grid Header and Column style.
![err12](https://user-images.githubusercontent.com/17789934/57130242-b9e1c080-6d4d-11e9-930d-a5977d8cdb2e.PNG)

**Comment by tigran-avdalyan** [comment]
its connected with admin menu sidebar position, when minimized style is incorrect.

**Comment by tigran-avdalyan** [comment]
this problem have all grids

**Comment by RomanovM** [comment]
Thanks. Moved to https://github.com/nopSolutions/nopCommerce/issues/3730
