### ISSUE TITLE
Move OrderStatus to the Database

### ISSUE THREAD

**Issue by astrumcs** [nopSolutions/nopCommerce#3772]
nopCommerce version: 4.1

Steps to reproduce the problem: 

I have done a quick search through the github issues and have not found the idea of moving the order status values into the database instead of an enum embedded into the nop.core project.

Having it in the database would allow the default install or plugins to add new status values that a general event could then respond to.   Of course, the existing default statuses of pending, processing, complete and cancelled would be protected from deletion so they could be relied upon. 

I know doing this is a bit of a can of worms and is not as simple as it sounds.   Worth a discussion though.

**Comment by AndreiMaz** [comment]
Thanks! But a lot of logic depends on it. So we'll have it in enum. If you have suggestions for any specific new enum values, please share

**Comment by astrumcs** [comment]
@AndreiMaz, That is kind of the rub, isn't it...   I would probably suggest 'InPick' and 'BackOrdered'.

We could discuss the merits of those two for a bit.  But, the deeper issue is that nop could be used by retailers selling digital content, items in a brick and mortar store, items via drop ship, items that do not exist and will be manufactured, combinations of any of these, waiting for inventory to be transferred from one store/warehouse to another, etc.  

With all the possible types for retailers out there, only a simple straight forward retailer fits well within the current model. 

The issue with order status is that I believe that nop might be enforcing too tight of a constraint on the the end user's business processes.  Having one status for 'processing' means that the more complex scenarios that a business _must_ deal with might drive them to another solution that does fit their processes better.
