### ISSUE TITLE
Newsletter subscribers >>Edit don't allow edit store

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3775]
![err13](https://user-images.githubusercontent.com/17789934/57134440-10093080-6d5b-11e9-8506-f97f7c548bea.PNG)
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
1.go to admin area>>Newsletter subscribers >>Edit
its don't allow edit store.
2.in search area why we need END DATE?
3.in search area needs to add filter by Store.

**Comment by AndreiMaz** [comment]
The same as https://github.com/nopSolutions/nopCommerce/issues/3769
