### ISSUE TITLE
Affiliate - Support Multistore

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3776]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
When We create affiliate user, system generate only one link fore default store, it's not support Multi-Store.
Need ability to generate links for checked Stores.

**Comment by AndreiMaz** [comment]
the same as https://github.com/nopSolutions/nopCommerce/issues/3778

**Comment by tigran-avdalyan** [comment]
@AndreiMaz 
![err](https://user-images.githubusercontent.com/17789934/57174641-e998d300-6df6-11e9-9b25-da76c527a7d0.PNG)

maybe change County to District
