### ISSUE TITLE
Discounts - Support Multistore

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3778]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: When generate "URL with coupon code", it's only generate for default Store, needs ability to generate for selected stores.

**Comment by AndreiMaz** [comment]
Thanks! It'll just add some extra inputs to the discount page and make it more complex. It's easier to replace URL manually

**Comment by tigran-avdalyan** [comment]
@AndreiMaz replace URL manually in NopCommerce? (HOW?)
