### ISSUE TITLE
Add an opportunity to using custom attributes in nop tag helpers

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3779]
For example in 3.x versions we can use 
`@Html.TextBoxFor(model => model.ExpireMonth, new { style = "Width: 30px;", autocomplete = "off", maxlength = 2, required = "required", @type = "number", @pattern = "\\d*", min = 1, max = 12 })`

Source: https://www.nopcommerce.com/boards/t/62903/setting-properties-in-form-controls-nopcommerce-390.aspx

**Comment by AndreiMaz** [comment]
Also see https://github.com/nopSolutions/nopCommerce/issues/5152

**Comment by DmitriyKulagin** [comment]
Closed #3779
