### ISSUE TITLE
4.20 Plugin Button Text Missing

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3780]
nopCommerce version: 4.20

Steps to reproduce the problem: 
"Install" a plugin

There are 2 new buttons "admin.configuration.plugins.applychanges" and "admin.configuration.plugins.discardchanges" and "admin.configuration.plugins.changesapplyafterreboot" they just have text. I searched the upgrade.sql and they are not in there to be added

![text](https://user-images.githubusercontent.com/20989983/57143178-4f03aa00-6d8c-11e9-813f-327950a641d0.PNG)

**Comment by sk5202** [comment]
Please install again once it is well with fresh installation.

You can find below file under appdata folder.

All resource string is there.

![resource](https://user-images.githubusercontent.com/41533502/57146516-2064ee00-6de3-11e9-941e-16f4d8f479f3.PNG)

**Comment by Ochapparel** [comment]
Ok, let me try.

**Comment by Ochapparel** [comment]
So I just deployed 4.20 into production and it is not a "fresh install" because I'm upgrading from 4.10. These are still not showing up in production. Any idea how to get them to? I know you said "Please install again once it is well with fresh installation." but this is not a fresh install. It is an upgrade

**Comment by Ochapparel** [comment]
Oh I found it. Had to go into the languages and upload the xml

Thanks! First time I had to do this
