### ISSUE TITLE
Database backups is not working in maintenance module

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3782]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

 i've setup project in my local environment.

here is video

https://www.loom.com/share/e90c2224921e4eb4b4135393cc4f7a0b

**Comment by skoshelev** [comment]
Hi @sk5202. From the text of the error, it is clear that the user on whose behalf Sql Server is working does not have permission to write to the specified directory, please provide the necessary rights and everything will work, this is not the nopCommerce bug.
