### ISSUE TITLE
Require Validation or Record should be saved at All setting page

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3783]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

1) go Admin/Setting/AllSettings.

2) go Add new record section.

3)  Write setting name and leave value field as it is 

4) click and save 

5) It should be display validation like value should not be empty or it should be save.

**Comment by AndreiMaz** [comment]
It shouldn't because it's not required
