### ISSUE TITLE
Reward point message text box must having place holder instead of value into product edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3790]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 
Reward point message text must having  place holder instead of value into product edit page.
![1](https://user-images.githubusercontent.com/10364140/57175000-572f1880-6e64-11e9-8176-1184305d87e2.PNG)

**Comment by DmitriyKulagin** [comment]
Closed #3790

**Comment by sangeetshah** [comment]
@DmitriyKulagin  is this not bug???

**Comment by sangeetshah** [comment]
@DmitriyKulagin  is this bug or not?
