### ISSUE TITLE
PostgreSQL database support

### ISSUE THREAD

**Issue by ghd258** [nopSolutions/nopCommerce#3794]
Similar to https://github.com/nopSolutions/nopCommerce/issues/3737 and https://github.com/nopSolutions/nopCommerce/issues/415

**Comment by rodolphito** [comment]
What would doing this entail? I'd like to see PostgreSQL support, maybe I can contribute it if it doesnt involve a full rewrite of anything.

**Comment by JTrotta** [comment]
I added support to Postgres into last 4.30 RC version. It works.
There is only a problem here:
```
        public TEntity InsertEntity<TEntity>(TEntity entity) where TEntity : BaseEntity
        {
            using var dataContext = CreateDataConnection();
            entity.Id = dataContext.InsertWithInt32Identity(entity);
            return entity;
        }
```
Npgsql cannot insert into mapping tables like StoreMapping, CustomerAddresses,PermissionRecord_Role_Mapping etc.
I modified it this way:

```
        public TEntity InsertEntity<TEntity>(TEntity entity, bool withIdentity = true) where TEntity : BaseEntity
        {            
            using var dataContext = CreateDataConnection();
            if (withIdentity)
                entity.Id = dataContext.InsertWithInt32Identity(entity);
            else
                dataContext.Insert(entity);

            return entity;
        }
```

**Comment by tplsoft** [comment]
@AndreiMaz no milestone assigned. is this going to be in v 4.30?

**Comment by AndreiMaz** [comment]
@tplsoft No, it's not assigned to 4.30. Most probably one of the next versions. First, we have to test the new approach  with MySQL

**Comment by JwanKhalaf** [comment]
@JTrotta I believe that nopCommerce does support MySQL now, am I right that the problem you highlighted is no longer an issue?

**Comment by exileDev** [comment]
Done!
Closed #3794

**Comment by JwanKhalaf** [comment]
@exileDev I think something is wrong.

![image](https://user-images.githubusercontent.com/42877376/103385789-c48cc400-4af3-11eb-8249-b1e6c9f46912.png)

I got latest from `develop` branch and tried Postgres (just to test things). But it thinks the username is the database!

**Comment by glhays** [comment]
It looks to me like the DB is looking for user that doesn't exist.
________________________________

**Comment by JwanKhalaf** [comment]
Perhaps, but I know that the database user exists.

![image](https://user-images.githubusercontent.com/42877376/103408928-6ea03680-4b5c-11eb-80fe-ad157cf0ce60.png)

Also, the message "Database 'nativeleaf_user' does not exist" makes me think it is looking for a database called 'nativeleaf_user'!

**Comment by exileDev** [comment]
@JwanKhalaf Thank you for your help. Fixed!
