### ISSUE TITLE
Admin "Add New" box is long (4.20)

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3795]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
http://localhost:15536/Admin/Tax/Categories

The "Name" box is so long. I know it isn't a bug, but just weird looking. Maybe shrink it to match the other fields lengths?

![image](https://user-images.githubusercontent.com/20989983/57221440-42ba5f80-6fcd-11e9-9d49-1b24f72a0a4c.png)

**Comment by AndreiMaz** [comment]
Thanks. It's by design
