### ISSUE TITLE
Scaling out and down on azure (with redis and blob) leads to "An error occurred while starting the application"

### ISSUE THREAD

**Issue by rudgr** [nopSolutions/nopCommerce#3797]
nopCommerce version: 

v4.20-beta

Steps to reproduce the problem: 

- v4.20-beta on azure
- enable redis cache
- enable blob storage
- scale-out to 2 instances
- scale down back to 1 instance

error:

`Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.DiscountRules.CustomerRoles.dll' is denied.`

Related issue: #2700 ?

**Comment by rudgr** [comment]
From premium support issue #14871:

Seems that disabling plugin shadow copy in app settings helps...
maybe update nopcommerce azure redis documentation?

stil getting exceptions like:

`the "Send emails" scheduled task failed with the "An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ProxySettings (DelegateActivator), Services = [Nop.Core.Domain.Security.ProxySettings], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Timeout performing EXISTS Nop.setting.all, inst: 5, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: RD0003FF5FBBDB, serverEndpoint: Unspecified/nopcommerce-test.redis.cache.windows.net:6380, keyHashSlot: 2077 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts) (See inner exception for details.)" error (Task type: "Nop.Services.Messages.QueuedMessagesSendTask, Nop.Services". Store name: "Your store name". Task run address: "http://nopcommerce-beta-test.azurewebsites.net/scheduletask/runtask").`

and

`Timeout performing EXISTS Nop.language.all-False, inst: 11, queue: 14, qu: 0, qs: 14, qc: 0, wr: 0, wq: 0, in: 765, ar: 0, clientName: RD0003FFDB6F28, serverEndpoint: Unspecified/nopcommerce-test.redis.cache.windows.net:6380, keyHashSlot: 3355 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)`

when running performance tests  on multiple webapp instances (with default redis confuguration)

**Comment by skoshelev** [comment]
We will make the necessary changes to the documentation after the official release. As for the problem with timeouts in Redis, the problem is solved by increasing the waiting time in the connection string, in the future we will rewrite everything to async calls (#2287), which will improve performance
