### ISSUE TITLE
How to add an Admin "TABS" 4.20?

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3798]
nopCommerce version: 
4.20
Steps to reproduce the problem: 

What are the steps to add a new collapsible admin tab? For example in the Customer Edit, how do I add one after Back in stock subscriptions?

**Comment by AndreiMaz** [comment]
Please post all development questions on our forums. We use GitHub only for development tasks

**Comment by Ochapparel** [comment]
Ok
