### ISSUE TITLE
Is NopFileProvider.Combine(string[]) causing further path issues and is it written correctly?

### ISSUE THREAD

**Issue by davidandrewpowell** [nopSolutions/nopCommerce#3799]
nopCommerce version: 4.20

This issue relates to issue [3733 ](https://github.com/nopSolutions/nopCommerce/issues/3733)(now resolved) where the nivo slider plugin was not installing correctly.

The original code that was causing that issue was:

```
var sampleImagesPath = _fileProvider.MapPath("~/Plugins/Widgets.NivoSlider/Content/nivoslider/sample-images/");
...
_fileProvider.ReadAllBytes(sampleImagesPath + "banner1.jpg")

```
The issue was caused due to `NopFileProvider.MapPath(string)` removing the trailing '/' character from the path.  When the paths were concatenated in the last line above it gave an invalid path:

`.../sample-imagesbanner1.jpg`

This has now been fixed by using `NopFileProvider.Combine(string[])` to join the paths.

So what changed in `MapPath`?  If we look at commit 234c85a4 we can see that the following version of `MapPath` (and its associated dependency on `Combine(string)`):

```
public virtual string MapPath(string path)
{
    path = path.Replace("~/", string.Empty).TrimStart('/');
    return Combine(BaseDirectory ?? string.Empty, path);
}

public virtual string Combine(params string[] paths)
{
    var path = Path.Combine(paths.SelectMany(p => p.Split('\\', '/')).ToArray());

    if (path.Contains('/'))
        path = "/" + path;

    return path;
}
```

Its seems that this commit introduced that bug.  The previous commit 5d2c95a6 shows `Combine(string[])` as follows:

```
public virtual string Combine(params string[] paths)
{
    return Path.Combine(paths);
}
```

I believe the first line of this new functionality is trying to strip out any path separators and replace them with new path separators (dependent on the current OS).  In doing so it is also removing the trailing '/' character.

**Questions:**

1. Although issue [3733](https://github.com/nopSolutions/nopCommerce/issues/3733) (described above) has now been resolved, is there anywhere else in the application where similar functionality exists (where `NopFileProvider.MapPath` has been called but the paths are not combined using `NopFileProvider.Combine` after the call) where we may have introduced further (yet to be detected) issues?

I would suggest that we either:

i) Add the trailing slash back if it was already present in `MapPath`.

or

ii) Examine all instances of where `Combine` is called to check that this issue will not occur.

2. Is the following code segment correct?:

```
if (path.Contains('/'))
    path = "/" + path;
```

It is not clear from reading the code (at least to me anyway) in what circumstance you would want to add a leading '/' character to the path. Where in the path are you looking for a '/' character which then means that you should add a further '/' to the beginning on the path?  If this is correct then maybe we should add a description to the code of why this additional '/' is being added.

**Comment by joekrauss** [comment]
David - The changes made to the NopFileProvider between 4.1 to 4.2 have caused another error condition when using UNC paths on IIS.

**Comment by skoshelev** [comment]
Closed #3799

**Comment by joekrauss** [comment]
Hello - I applied the changes, however when using an IIS setup with a UNC file path it fails.

**Comment by joekrauss** [comment]
Sergey - The UNC path issue fixed after making the change you requested, however there is still an issue with installing plugins. The plugins.json file never gets created or updated while using a UNC path on IIS.

Worked to load the site: return Path.Combine(paths); - Not working for installing or configuring plugins
