### ISSUE TITLE
Replace ImageResizer.NET With ImageProcessor

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#380]
You are currently using ImageResizer.NET in nopCommerce, but to benefit from DiskCaching you have to pay for a license. 

If you change to ImageProcessor then you get everything for free, it's completely open source and has DiskCaching OOTB. It's as good, if not better than ImageResizer.NET. 

http://imageprocessor.org 

https://github.com/JimBobSquarePants/ImageProcessor 

Just to assure you further, Umbraco have now moved to using ImageProcessor and its part of the Umbraco core now too. It should be a very easy change for you, and we get disk caching without any extra charges or licenses (By the way I am not the developer of ImageProcessor before you ask)

**Comment by tigran-avdalyan** [comment]
https://dotnet.libhunt.com/project/resizer/vs/imageprocessor?rel=cmp-cat

**Comment by tigran-avdalyan** [comment]
Can we open this issue???
