### ISSUE TITLE
Interface RouteProvider for non installed plugins

### ISSUE THREAD

**Issue by KrzysztofPajak** [nopSolutions/nopCommerce#3803]
Hi,
nopCommerce version: 4.20 beta
According to documentation nopCommerce 4.20 Beta changelog, plugins which is not installed do not load. Interface RouteProvider works for plugins not installed. I don't know is a bug or by design but it would be greate if routeprovider should not load for that plugins.

Regards
Krzysztof

**Comment by RomanovM** [comment]
@KrzysztofPajak Please clarify what you mean. Everything works as expected, if the plugin isn't installed, it won't be loaded and the routes of this plugin won't be available (RouteProvider won't be invoked).

**Comment by KrzysztofPajak** [comment]
Hi,
It was my mistake, sorry for that.
Regards
Krzysztof
