### ISSUE TITLE
State/Provice field doesn't refresh when country is changed

### ISSUE THREAD

**Issue by PatrykPorabik** [nopSolutions/nopCommerce#3804]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
1. Enable One page checkout
2. Add product to cart
3. Go to cart
4. Go to checkout
5. Confirm the billing address step, untick the Ship to the same address checkbox and go to shipping address step
6. Add new address
7. When you select Country, State/Provice should refresh, but it doesn't :) 

This behavior appears only on shipping address step.

[See screenshot](https://imgur.com/lk582NB)

**Comment by DmitriyKulagin** [comment]
Closed #3804
