### ISSUE TITLE
Visual Studio 2019 and Beta 4.20

### ISSUE THREAD

**Issue by vladoATL** [nopSolutions/nopCommerce#3805]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
Fresh install Visual Studio 2019 Enterprise (do not make any changes in setting)
Download and unzip 4.20 Beta source
Load the project 
This is the error when compiling:

Error | NETSDK1045 | The   current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or   use a version of the .NET SDK that supports .NET Core 2.2. | Nop.Core

**Comment by RomanovM** [comment]
Try to download the specified net core package. Anyway, this issue is not related to nop
