### ISSUE TITLE
Product Preview button not working properly into multi store

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3806]
nopCommerce version:  4.2beta

Steps to reproduce the problem: 

I have created two store into project. name is store1 and store2. when i create one product and try to use preview button then it show me store2 product detail page.(is this bug?).i didnt see any selection of preview button for stores. this preview button selection choose its own self store for preview.
second think if i have multiple store then i need to see multiple preview button for multiple store. because i need to see how my product display into particular store.
third think if i use this product for limited store then i need to check this store preview then how i check this with preview button.

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/7355
