### ISSUE TITLE
Still used kendo js and css into admin layout,admin popup layout,SetTelerikCulture in Common helper class,style.css(admin),styles.rtl.css(admin) and admin.common.js

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3807]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 
Still used kendo js and css into admin layout,admin popup layout,SetTelerikCulture in Common helper class,style.css(admin),styles.rtl.css(admin) and admin.common.js
![kendo](https://user-images.githubusercontent.com/10364140/57352920-83a8a480-7184-11e9-8b1d-c9e61b42fddc.png)

**Comment by RomanovM** [comment]
We gave up kendo grids, but we still use kendoui controls, see details https://github.com/nopSolutions/nopCommerce/issues/3665
