### ISSUE TITLE
Duplicate addresses display in billing address on one page checkout

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#3808]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
1. Enable One page checkout
2. Add product to cart
3. Go to cart
4. Click on checkout
5. Add new billing address and click on continue
6. Now when you click on back button from shipping method, new address does not create (Bug 1)
7. Again if you click on continue and click back from shipping method, you will find two address created with same details (Bug 2).

**Comment by DmitriyKulagin** [comment]
@sagarnop Hi, I can not reproduce the error, perhaps it was fixed earlier. Could you check again and if the error persists, send the video how to get it

**Comment by sagarnop** [comment]
@DmitriyKulagin  Hello, please check the video.
https://www.loom.com/share/50763df566ab4d418a3cebbe74aa1a1c

**Comment by sagarnop** [comment]
@DmitriyKulagin  Hello,
Have you seen this video?
Now what you think?

**Comment by DmitriyKulagin** [comment]
Closed #3808
