### ISSUE TITLE
Redis DB config 

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3809]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: 
In 4.1 we could configure Redis to use a specific DB, such as #1. In 4.2 we can no longer do this as cache uses DB #2, Plugin #3, and DataProtection keys #4. I am not clear on why we need to use 3 different Redis DBs vs just using 1, or why we can no longer configure what DB to use. So rather than being able to host multiple nopCommerce instances on 1 Redis instance we now must have a 1:1 NopCommerce to Redis cluster. This is extremely inefficient and very inflexible.

**Comment by toddca** [comment]
@RomanovM this should be marked as a bug - its a regression to what we had in 4.1 where you could edit the redis connection string and specify the DBID. Then with a single Redis server you could host a dozen+ nopCommerce deployments. Right now you need a 1:1 ration of Redis to NopCommerce which is expensive.

**Comment by skoshelev** [comment]
Closed #3809
