### ISSUE TITLE
Commented out and ignored tests which can easily be reapplied

### ISSUE THREAD

**Issue by davidandrewpowell** [nopSolutions/nopCommerce#3810]
nopCommerce version: 4.2 beta

The following **commented** tests exist in nopcommerce which can be uncommented:

**Nop.Web.MVC.Tests/Public/Validators/Blogs/BlogPostValidatorTests.cs:**
`Should_have_error_when_comment_is_null_or_empty()`
`Should_not_have_error_when_comment_is_specified()`

Both of these tests are commented out with the note "uncomment tests when the following FluentVlidation issue is fixed http://fluentvalidation.codeplex.com/workitem/7095"

The link does not work but if I uncomment the tests (and add appropriate using statements) they pass so these should be added back.

**Nop.Web.MVC.Tests/Public/Validators/Catalog/ProductReviewsValidatorTests.cs:**
`Should_have_error_when_title_is_null_or_empty()`
`Should_not_have_error_when_title_is_specified()`
`Should_have_error_when_reviewText_is_null_or_empty()`
`Should_not_have_error_when_reviewText_is_specified()`

Again, these have the same fluentvalidation comment as above and if I uncomment the tests (and add appropriate usings) they pass so these should be added back.

The following **ignored** tests exist in nopcommerce:

**Nop.Services.Tests/Messages/NewsLetterSubscriptionServiceTests.cs:**
`VerifyInsertEventIsFired()`

This test was commented out as you cannot test that `EventPublisherExtensions.EntityInserted` is called as this is an extension method.  However, this extension method is simply a wrapper around `EventPublish.Publish` which you can test is called.

I believe this test should be changed to test the `EventPublish.Publish` method is called instead.  Otherwise, the test should be removed.

**Comment by davidandrewpowell** [comment]
The above tests have been uncommented and unignored in pull request [3811](https://github.com/nopSolutions/nopCommerce/pull/3811).

**Comment by skoshelev** [comment]
Closed #3810
