### ISSUE TITLE
Tax issue in Pickup in Store

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3817]
nopCommerce version: 4.10

Steps to reproduce the problem: In Tax settings, set Tax based on "Shipping Address" & if you have pickup in store then TAX isn't applying.
In our case, store is located in Italy & if customer from Italy selected shipping option as "pickup in store" then 22% VAT isn't applying
When user selected pickup in store as shipping method, kindly apply tax based on billing address or Store address.

**Comment by RomanovM** [comment]
@jigarsangoi There is a setting "Tax based on pickup point address", did you try it?

**Comment by jigarsangoi** [comment]
@RomanovM Yes its working with that setting. Thanks for pointing me

**Comment by jigarsangoi** [comment]
@RomanovM Yes its working fine after changing that setting
