### ISSUE TITLE
Import of Categories failed

### ISSUE THREAD

**Issue by vladoATL** [nopSolutions/nopCommerce#3818]
nopCommerce version: 4.20 BETA

Steps to reproduce the problem: 
[Categories for Import.XLSX](https://github.com/nopSolutions/nopCommerce/files/3165656/Categories.for.Import.XLSX)
Import this Excel file and get error:
Categories with the following names aren't imported - DREVENÉ ŠPÁRADLÁ, ŠPAJDLE, MISKY A VANIČKY, MISKY S INTEGROVANÝM VIEČKOM (PP), POLIEVKOVÉ MISKY, PODLOŽNÉ MISKY (EPS), TERMO MISKY (EPS), MISKY HRANATÉ (PP), MISKY OKRÚHLE (PP), VANIČKY HRANATÉ (PP), MISKY S INTEGROVANÝM VIEČKOM (PET), ŠALÁTOVÉ MISKY (PET), DRESSINGOVÉ MISKY (PP), HLINÍKOVÉ MISKY, BOXY A KRABICE, BIO BOXY Z CUKROVEJ TRSTINY, TERMO BOXY (EPS), PAPIEROVÉ FOOD BOXY, TORTOVÉ KRABICE, KRABICE NA PIZZU Z VLNITEJ LEPENKY TYP 4, KRABICE NA PIZZU Z VLNITEJ LEPENKY TYP 6, ŠPECIÁLNE KRABICE NA PIZZU, PRÍSLUŠENSTVO PRE KRABICE NA PIZZU, POMÔCKY NA PEČENIE, PAPIER NA PEČENIE, CUKRÁRENSKÉ KOŠÍČKY NA PEČENIE, FÓLIE A ODVINOVAČE, HLINÍKOVÉ FÓLIE, ODVINOVAČE FÓLIÍ, POTRAVINOVÉ FÓLIE, POTRAVINOVÉ FÓLIE (PE), POTRAVINOVÉ FÓLIE PRIEMYSELNÉ (PVC), POTRAVINOVÉ FÓLIE (PVC), CHRÁNIČE ODEVOV, PRIEŤAŽNÉ FÓLIE NA PALETY, ZAKRÝVACIE FÓLIE, TAŠKY, SÁČKY A VRECIA, VRECIA NA ODPADKY - ROLOVANÉ, SYSTÉM NA ZATVÁRANIE VRECIEK, PRÍREZY, VRECKÁ, PAPIEROVÉ VRECKÁ PRE RÝCHLE OBČERSTVENIE, PAPIEROVÉ VRECKÁ LEKÁRENSKÉ, PAPIEROVÉ VRECKÁ DESIATOVÉ, VRECKÁ NA HYDINU, PAPIEROVÉ VRECKÁ S OKIENKOM, VRECKÁ DO KOŠA - ROLOVANÉ, VRECKÁ (LDPE), RÝCHLOUZATVÁRACIE VRECKÁ, RÝCHLOUZATVÁRACIE VRECKÁ S EURO-ZÁVESOM, VRECKÁ - ROLOVANÉ, VRECKÁ DO MRAZNIČKY, TAŠKY, TAŠKY KOŠIEĽKY, PAPIEROVÉ TAŠKY, PRIEMYSELNÉ OBALY, KANCELÁRSKE LEPIACE PÁSKY, GUMIČKY, LEPIACE PÁSKY, FAREBNÉ LEPIACE PÁSKY, ODVÍJAČE LAPIACICH PÁSOK, KREPOVÉ LEPIACE PÁSKY, OBOJSTRANNÉ LEPIACE PÁSKY, ŠPECIÁLNE LEPIACE PÁSKY, JEDNORAZOVÉ OBLEČENIE, JEDNORÁZOVÉ POKRÝVKY HLAVY, JEDNORÁZOVÉ RUKAVICE, JEDNORÁZOVÉ HYGIENICKÉ ODEVY, UTERÁKY A ZÁSOBNÍKY, PAPIEROVÉ SKLADANÉ UTERÁKY A ZÁSOBNÍKY, PAPIEROVÉ UTERÁKY V ROLI A ZÁSOBNÍKY, UTIERKY A ZÁSOBNÍKY, TOALETNÉ PAPIERE A ZÁSOBNÍKY, MYDLÁ, VÔŇE A DÁVKOVAČE, HYGIENICKÉ POTREBY, KRAJKY A ROZETKY, ROZETKY PREMIUM, PAPIEROVÉ DEKORAČNÉ KRAJKY, PAPIEROVÉ ROZETKY, OBRÚSKY, SVADOBNÉ DEKORÁCIE, OBRÚSKY 1-VRSTVOVÉ, OBRÚSKY DO ZÁSOBNÍKOV A ZÁSOBNÍKY, OBRÚSKY 2-VRSTVOVÉ, OBRÚSKY 3-VRSTVOVÉ, OBRÚSKY BIELE, OBRÚSKY DEKOSTAR, OBRÚSKY PREMIUM, OBRÚSKY S MOTÍVOM, STOLOVÉ PRESTIERANIE, PRESTIERANIE, NAPERONY, OBRUSY - SKLADANÉ, OBRUSY - ROLOVANÉ, RAUTOVÉ STOLOVÉ SUKIENKY, STREDOVÉ PÁSY - ROLOVANÉ, SVIEČKY, SVIEČKY KÓNICKÉ, SVIEČKY ROVNÉ, SVIEČKY VALCOVÉ, ČAJOVÉ SVIEČKY, SVIEČKY PRE VONKAJŠIE POUŽITIE, MIEŠAČKY A DEKORATIVNE BODCE, PLASTOVÁ MIEŠADLÁ, PLASTOVÉ NAPICHOVADLÁ, DEKORAČNÉ NAPICHOVADLÁ, ŠPAJDLE A ŠPÁRADLÁ, FINGERFOOD NAPICHOVADLÁ, PÁRTY SVIEČKY, PÁRTY DEKORÁCIE, SERPENTÍNY A KONFETY, GIRLANDY, LAMPIÓNY A PRÍSLUŠENSTVO, DEKORÁCIE SÁLY, NAFUKOVACIE BALÓNIKY A PRÍSLUŠENSTVO, PLESOVÉ A KARNEVALOVÉ DOPLNKY, PÁRTY SADY, VEĽKÁ NOC, VIANOCE

**Comment by vladoATL** [comment]
I forgot to say that some categories were imported.

**Comment by vladoATL** [comment]
I did it (without delete) again and "Categories have been imported successfully." It behaves like that - first time fail and second time not - every time I do it.

**Comment by skoshelev** [comment]
Hi @vladoATL This is not a mistake, this is by design. categories that are children may not load for the first time since their parent categories are not yet in the database
