### ISSUE TITLE
"Setup failed: Sequence contains more than one element " error come out when try to install project

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3823]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 
"Setup failed: Sequence contains more than one element " error come out when try to install project

Step to reproduce error
1) install nopcommerce 4.2beta
2) delete dataSettings.json and installedPlugins.json file from App_Data folder
2) now try to install project again. you got this error(set same database name as previous)

this second installation create another same  language into database.
this is bug because if some user accidentally delete  dataSettings file and need to install project on existing database then how can he do this?
or if some user having database of project and need to install project on same database then it not work.

![Capture](https://user-images.githubusercontent.com/10364140/57566570-a7215880-73eb-11e9-873f-c2e839e8b17c.PNG)
se table.

**Comment by mrnams** [comment]
This happens when there exists database and you try to create it again.
Please delete any pre exist Database and try to install again.

**Comment by sangeetshah** [comment]
but why it create multiple language into table? it must be validate before add

**Comment by mrnams** [comment]
Yes I agree that's bug

**Comment by AndreiMaz** [comment]
just empty yout database

**Comment by sangeetshah** [comment]
is this not bug? @AndreiMaz 

non technical person dont know to delete database or need to empty database. because this types of instruction not provided anywhere into project or forum. 

In first of time i also dont know what is issue or how to solve this? so my opinion  to resolve it or provide instruction over there.

**Comment by atulrungta** [comment]
@AndreiMaz 
This is a bug that even I wanted to report a lot of times. Please see details reported by @sangeetshah which tells what the problem exactly is. If you want, we can write you an another detailed description with proper steps and errors that we face and a step by step break.

**Comment by liqili** [comment]
I also got this issue. I'm using docker to run the application in production, but got this error when I change code and re-built the docker container. I just want to use the existing database without any data lost during installation. In my docker container, it will lose Settings.txt after re-built so the solutions in the community doesn't help. I think the script need check if the table is already there before inserting the data.
