### ISSUE TITLE
Roxy file man folder can not able to delete.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3825]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Edit any product.

Go Full description try  to open roxy fileman.

After upload test folder under root directory.

Upload pictures.

after delete, it says can't able delete folder it is not empty after i deleted each picture and i am able to delete that folder so till now it's working.

Now i try to upload pdf and pdf is not shown in the list because that is picture uploder.

It's perfect and working fine.

Now i tried to delete same folder but can't able to delete that folder.

It should be delete.

here is video to reproduce this issue.

https://www.loom.com/share/cd863ed92b4b4203a601bced96ace6d2

**Comment by RomanovM** [comment]
@sk5202  Well, just don't upload pdf files since it's a picture uploader and you can properly manage folders.
