### ISSUE TITLE
Can't able to open Hierarchical Grid (wishlist/Shopping cart) at CurrentCarts page

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3826]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Create one customer add one product in the cart.

login with admin and also add one product in wish list.

now go Admin/ShoppingCart/CurrentCarts.

select wishlist from shopping cart type.

try to open sub grid as per display in the video.

getting alert it shows some error like

DataTables warning: table id=childundefined - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

https://www.loom.com/share/8d93a92f2a91452f93de47e14fbe7014?focus_title=1&muted=1

**Comment by sk5202** [comment]
I am also facing same scenario with shopping cart type equals to shopping cart.

check with same as per display in video

**Comment by DmitriyKulagin** [comment]
Closed #3826
