### ISSUE TITLE
Consecutive logout when working with two store at same browser.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3827]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

I've deployed two different store at my IIS with two different db.

1) http://localhost:81/ 

2) http://localhost:82/

Now login with 81 and it's fine in second tab open with 82. Now login with 82.

81 is automatically logged off.

It should not be logged off both should be logged in.

here is the video for reproduce this issue.

https://www.loom.com/share/ee06d18b20df4b61bf9dcce53f97c02f

**Comment by RomanovM** [comment]
@sk5202  I assume that this is true only for localhost and there is nothing to worry about when using real server.
