### ISSUE TITLE
Wrong message when try to add empty vendor note.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3828]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Go => http://localhost:81/Admin/Vendor/Edit/1

After move to Vendor notes tab.

click on add vendor note button.

It displayed wrong validation message **Order note can not be empty.**

It should be display like **Vendor note can not be empty**

https://www.loom.com/share/174c9da87cbe4c14a0863e4c3e5c24bc?focus_title=1&muted=1

**Comment by DmitriyKulagin** [comment]
Closed #3828
