### ISSUE TITLE
Reserve product functionality

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#383]
Provide the ability for a customer to reserve a product that hasn't came out yet and make payments (at their own time) on it until it is paid off then the product will be shipped when it's available, like GameStop and other gaming stores allow their customers to do. 

It is different from the Pre-order functionality because it will allow the customer to make payments by logging in and seeing their balance. Once the product is completely paid for (and available), then it will be shipped. 

In order to Reserve a product, the customer would pay a deposit amount defined on the product then make payments (maybe the minimum payment could be set on the product also). The Pre-order functionality or any product would benefit from the "Allow Payments" feature and could increase sales of certain products, especially higher priced items. 

Allow Payments - check box (expands the following fields) 
Deposit - decimal input (leave 0 if no initial deposit is required) 
Minimum Payment - decimal input (least amount accepted towards the product; leave 0 if no minimum payment is required) 

Forum source: http://www.nopcommerce.com/boards/t/31823/feature-request-reserve-product-functionality.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
