### ISSUE TITLE
Aria-label attributes for language and tax select elements

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3830]
I was just wondering why you have added aria-label attribute to the "currency" select element, but not to the "language" and "tax" select elements. Perhaps you missed it? Or it's intentional?

Source: https://www.nopcommerce.com/boards/t/63606/aria-label-attributes-for-language-and-tax-select-elements.aspx

See related pr: https://github.com/nopSolutions/nopCommerce/pull/2990, https://github.com/nopSolutions/nopCommerce/pull/3607

**Comment by kem-storis** [comment]
We ran a scan using a tool which indicates the page elements that are missing some type of ADA attributes, however the language and tax select elements apparently were not indicated in our scan.

**Comment by poyker** [comment]
@kem-storis Did you have them enabled i.e more than one language?

**Comment by kem-storis** [comment]
@poyker, good point. That is probably exactly what happened and is a good reminder for future scans to enable setting for users to select their language.

**Comment by poyker** [comment]
@kem-storis @RomanovM  So in that case these changes need to be done in the tax and language select elements too

**Comment by DmitriyKulagin** [comment]
Closed #3830
