### ISSUE TITLE
Order Guid & Id is wrong after order status update

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#3834]
nopCommerce version: 4.10

Steps to reproduce the problem: In order details page, when you change status manually order guid, order # and Customer IP address become invisible or it's wrong
![Capture](https://user-images.githubusercontent.com/21276844/57630974-39785680-75bc-11e9-8c7d-6b9384befeb2.PNG)

**Comment by DmitriyKulagin** [comment]
@jigarsangoi It was fixed earlier. More details you can see [here](https://github.com/nopSolutions/nopCommerce/commit/a6ad8c35803cc338ba5c5b93ad6002764f337231)
