### ISSUE TITLE
Design issue on Billing address using multi page checkout

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#3835]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
1. Add multiple billing address on checkout page using multi page checkout.
![Billing address](https://user-images.githubusercontent.com/50259172/57674941-38880900-763e-11e9-9d37-cc882f028b6d.PNG)

**Comment by exileDev** [comment]
Closed #3835

**Comment by hsynlms** [comment]
The CSS file is invalid due to this fix.
The asterisk character should have been removed from that line: `*display: inline;`

**Suggestion:** remove that line completely.

**Comment by hsynlms** [comment]
This fix was not applied for the RTL style sheet as well.
