### ISSUE TITLE
Schedule tasks shows tags instead of seconds on edit first line

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3837]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
1. goto Schedule tasks
2. click on edit of first item (only this)
3. some like this:<tcxspan tcxhref=
1209600" class="userinput" type="number" min="0" max="100"/> is shown
![14-05-_2019_20-58-39](https://user-images.githubusercontent.com/37210350/57724567-60518e00-768b-11e9-8323-4eb6dabe6904.png)

**Comment by DmitriyKulagin** [comment]
@cnEUL The range of editing values is extended, but it is not clear where the strange "tcxspan" tag came from. We prescribe in the code what will be the contents of the cell at the time of editing, and there is nothing similar there. Please check back with the latest changes.

**Comment by cnEUL** [comment]
![14-05-_2019_20-58-39](https://user-images.githubusercontent.com/37210350/57828785-f8936400-77ac-11e9-860c-8e6d459c52b7.png)
@DmitriyKulagin 
Hi i checked it back with source of this morning, same result.

**Comment by DmitriyKulagin** [comment]
@cnEUL Hi, I was not able to reproduce such an error, I think it may be in your database once this happens only for this particular record. But in any case, we do not use the custom attribute "tcxspan", and managing the display of the cell at the time of editing is no different from other rows in the table.
As a result, according to the task - we expanded the range of the specified values for the column with the type "number".

**Comment by cnEUL** [comment]
@DmitriyKulagin 
it was done on a fresh installation, windows server, sql server and with the your demo data.

**Comment by cnEUL** [comment]
@DmitriyKulagin
Tryed out with another browser (Edge) and with this it worked as expected. So i was wondering about your response with "tcxspan", and... it was a chromeplugin that made that strange things. the plugin of a pbx telefon system of 3cx, which detects numbers out of a website to dial. It seems that they inserts that attributes in the code. (for information only)
