### ISSUE TITLE
System log doesn't show exception

### ISSUE THREAD

**Issue by demckee** [nopSolutions/nopCommerce#3838]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
Base 4.20 beta. If an exception occurs, the FullMessage is always empty.

The problem is in LogModelFactory, in the routine PrepareLogModel. This routine sets model.FullMessage to the text from the log record, then two lines later always sets model.FullMessage to null.

**Comment by DmitriyKulagin** [comment]
Closed #3838
