### ISSUE TITLE
Add a button to expand all blocks (nop-panel) in admin area

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3840]
nopCommerce version: 4.20

Steps to reproduce the problem: 
On Product, Customers etc. we habe no mor Tabs and now something like Dropdown areas. Is it possible to make a button to open all att the time?
If you are searching a string in the browser it is helpfull to expand all at the time. Also an option to tell the system if this should be the default.

Also would be nice if we can tell in the settings (where we can just select fields for basic mode) to tell which areas should be always expanded.

**Comment by exileDev** [comment]
After discussion, it was decided not to implement.
