### ISSUE TITLE
Customer link is not relevant ( id become 0 ) when Edit order total / change Order status / change Shipping method.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3841]
nopCommerce version: Beta 4.20

Steps to reproduce the problem: 

Go Admin/Order/Edit/3.

Click Edit order total and after click save order total.

Now click on customer link it is redirect to Admin/Customer/List instead of Admin/Customer/Edit/{id}

Same thing you happen with change order status and shipping method.

Here is the video.

https://www.loom.com/share/31595df8e62644d8bf228a089c2c9561

**Comment by DmitriyKulagin** [comment]
Closed #3841
