### ISSUE TITLE
Nopcommerce State & Province List

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3843]
nopCommerce version: 4.2 beta

This is States & Province list for all countries. 
Can Nopcommerce Team include this list of states & provinces in 4.2 release.

[Country.State.xlsx](https://github.com/nopSolutions/nopCommerce/files/3187829/Country.State.xlsx)

**Comment by RomanovM** [comment]
@tigran-avdalyan Thanks. What you mean by including it on the release? We already have the ["all states (provinces) package"](https://www.nopcommerce.com/p/1622/all-states-provinces-package.aspx) on our marketplace that you can download and import in the admin area if you need.

**Comment by tigran-avdalyan** [comment]
ok, can we include to  "all states (provinces) package" because in my file include all countries and states.

**Comment by RomanovM** [comment]
@tigran-avdalyan Sure, thanks again for your contribution

**Comment by AndreiMaz** [comment]
@tigran-avdalyan We'll do it. I've just create an internal task to update our package (convert from Excel to our TXT format). In the meantime I'm closing this task as it's not related to the core. Thanks again.
