### ISSUE TITLE
Terms of Service popup showing the wrong content

### ISSUE THREAD

**Issue by Pasyona** [nopSolutions/nopCommerce#3844]
nopCommerce version: 4.1.524.28656

Steps to reproduce the problem: We are finalizing our shop with the Brookling Theme. While we are testing some Bugs are coming up. Now we noticed in our cart page (when you press the popup link) the popup Window will open but the Content introduced in **Content Management -> Topics (page) -> Terms of Service** is not showing at all. Instead it shows a Mirror of the whole main page of our shop. I checked the whole admin Settings without any result.

Can someone tell me where can I Change the Content of the popup?

Cheers in Advance!
Ernesto

On forums: https://www.nopcommerce.com/boards/t/37227/terms-of-service-link-in-shopping-cart-not-working.aspx#231994

**Comment by RomanovM** [comment]
It works like a charm on the default configuration
