### ISSUE TITLE
AppSettings Reference to browscap.crawlersonly.xml But File Does Not Exist

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3845]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Open appSettings.json
2. Navigate to the following line: 
"CrawlerOnlyUserAgentStringsPath": "~/App_Data/browscap.crawlersonly.xml",
3. Notice there is no file by this name in the app_data folder or in the source.

**Comment by toddca** [comment]
ahh - I see we reference a file not in the app_data and then it gets created on first run -- I really hate this pattern. Why not just supply the file? Its not like if you update the browscap.xml file the crawlersonly file is going to be updated.

**Comment by RomanovM** [comment]
See details here https://github.com/nopSolutions/nopCommerce/issues/1964
