### ISSUE TITLE
Store InstalledPlugins.json in SQL DB vs Redis

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3847]
nopCommerce version: 4.2

Steps to reproduce the problem: 
In 4.2 a feature was introduced to will help those of us that run NopCommerce in a web farm of 2 or more web servers - the feature allows for storing the contents of InstalledPlugins.json in Redis instead on disk, that way when a plugin is modified on one server the other servers will pick up that change whenever they are restarted. 

This is a great idea however I don't really care for the implementation - we should be storing in the DB vs Redis. I cannot think of any reason why we cannot use the SQL DB just as we do Redis. In addition this would help reduce some of the issues with #3809 where for some reason the decision was made to use a number of hard coded DBIDs without making them configurable. This would at least reduce one such Redis DB. 

We do not require the perf of Redis here for the caching, the primary reason for this feature is to keep the web servers in sync as to what is going on which the DB does all the time.

**Comment by AndreiMaz** [comment]
thanks. but mostly duplicates https://github.com/nopSolutions/nopCommerce/issues/4113

**Comment by toddca** [comment]
@AndreiMaz How does this duplicate an issue which was opened 5 months after I created this one?
