### ISSUE TITLE
ResourceLocation.Footer for \Nop.Web\Views\Shared\_Root.Head.cshtml

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3848]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
Hi, I added this code to my Head.cshtml

`//scripts
    Html.AppendScriptParts("~/lib/datatables/moment-with-locales-2.22.2.min.js", excludeFromBundle: true);
    Html.AppendScriptParts("~/lib/datatables/datatables.min.js", excludeFromBundle: true);
    Html.AppendScriptParts("~/lib/datatables/js/dataTables.bootstrap.min.js", excludeFromBundle: true);
    Html.AppendScriptParts("~/lib/datatables/js/jquery.dataTables.min.js", excludeFromBundle: true);
    Html.AppendScriptParts($"~/lib/kendo/{kendoVersion}/kendo.web.min.js", excludeFromBundle: true);`

and I get 
`Uncaught ReferenceError: $ is not defined
    at 144:1`

I had to add ResourceLocation.Head to the the views/shared/_Root.Head.cshtml  to get it to work. i know i can have a custom _Root.Head.cshtml to move to the head. but just wanted to share.

`Html.AppendScriptParts(ResourceLocation.Head, "~/js/public.countryselect.js");
    Html.AppendScriptParts(ResourceLocation.Head, "~/js/public.ajaxcart.js");
    Html.AppendScriptParts(ResourceLocation.Head, "~/js/public.common.js");
    //when jQuery migrate script logging is active you will see the log in the browser console
    if (commonSettings.JqueryMigrateScriptLoggingActive)
    {
        Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery-migrate/jquery-migrate-3.0.1.js");
    }
    else
    {
        Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery-migrate/jquery-migrate-3.0.1.min.js");
    }
    Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery-ui/jquery-ui-1.12.1.custom/jquery-ui.min.js");
    Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery-validate/jquery.validate.unobtrusive-v3.2.10/jquery.validate.unobtrusive.min.js");
    Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery-validate/jquery.validate-v1.17.0/jquery.validate.min.js");
    Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery/jquery-3.3.1.min.js");`

**Comment by RomanovM** [comment]
@Ochapparel Please clarify what the issue with this?

**Comment by Ochapparel** [comment]
The issue is jquery-3.3.1.min.js is rendering at the footer and datatables.min.js is rendering at the top. I had to make Html.AppendScriptParts(ResourceLocation.Head, "~/lib/jquery/jquery-3.3.1.min.js"); in order to NOT get the javascript error TypeError: $(...).DataTable is not a function

**Comment by RomanovM** [comment]
@Ochapparel Well, but what is nopCommerce issue here? What do you suggest or what should we do?

**Comment by Ochapparel** [comment]
In `\Presentation\Nop.Web\Views\Shared\_Root.Head.cshtml` make all `ResourceLocation.Footer` references `ResourceLocation.Head`

This will allow it to render at the top in the header, not the footer, allowing any .js in a Theme's package to render.

The reason being, is if a person adds 

`//scripts
    Html.AppendScriptParts("~/lib/datatables/moment-with-locales-2.22.2.min.js", excludeFromBundle: true);

    Html.AppendScriptParts("~/lib/datatables/datatables.min.js", excludeFromBundle: true);

    Html.AppendScriptParts("~/lib/datatables/js/dataTables.bootstrap.min.js", excludeFromBundle: true);

    Html.AppendScriptParts("~/lib/datatables/js/jquery.dataTables.min.js", excludeFromBundle: true);

    Html.AppendScriptParts($"~/lib/kendo/{kendoVersion}/kendo.web.min.js", excludeFromBundle: true);`

to their "Themes" "Head.cshtml" they will get the error "TypeError: $(...).DataTable is not a function"

This is to render a DataTable on the front end, Not on the Admin area

**Comment by DmitriyKulagin** [comment]
@Ochapparel Hi,
And why don't you want to connect the libraries you use to the footer? 
Are there any limitations due to which we really have to do what you suggested?

**Comment by poyker** [comment]
I think this change will affect the page speed as these scripts will be loaded and executed in the Header rather than in the Footer. It will also encourage people to put more scripts in the Header. 
If someone wants to add any script that depends on jQuery they can always add this script in the Footer and thus ensure it is loaded after jQuery i.e:

Html.AppendScriptParts(ResourceLocation.Footer, "~/lib/datatables/datatables.min.js");

**Comment by DmitriyKulagin** [comment]
Hi, @poyker 
Perhaps I agree with you, we rolled back the changes and returned to using scripts in Footer
