### ISSUE TITLE
Textresource "Tax and Shipping" for law purposes

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3849]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
The testresource: 
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoProductBoxes.Hint.Value

has actual the content of:
Check to display tax and shipping info in product boxes (catalog pages). This option is used in Germany.

but it is not optional, it has to be absolut. So text is better:
Check to display tax and shipping information in product boxes (catalog pages). This option is required in Germany.

ALSO in the following resources:
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoFooter.Hint.Value
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoProductDetailsPage.Hint.Value
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoOrderDetailsPage.Hint.Value
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoShoppingCart.Hint.Value
Admin.Configuration.Settings.Catalog.DisplayTaxShippingInfoWishlist.Hint.Value

**Comment by DmitriyKulagin** [comment]
Closed #3849
