### ISSUE TITLE
Add support for product URLs with a category in path (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#385]
This way, product URLs could be `/category-slug-name/product-slug-name`. If a product has several categories in the breadcrumb, then use only the last one (the most nested). Also, note that sometimes a product could be with any categories (in this case always use `/product-slug-name`)

Let's make it configurable - the current way (e.g. `/product-slug-name`) or a new one (`/category-slug-name/product-slug-name`).  Add an appropriate setting to the admin area

Some notes (to be investigated):
1. The workaround for that is for `GenericPathRoute` to map to `{*generic_name}` rather than {generic_name} I believe.
2. Please note after addition of such custom route ALL controllers and routes should be also registered. For example, \somecontroller\somemethod. Otherwise, customers will be redirected to this new {*generic_name} route handler. Also, think about the processing of 404 errors for such cases. Some investigation is required.
3. Each missing static resource (like /content/files/missingfile.pdf) is also caught by `GenericPathRoute`, it's not a big problem, but I'm not sure of the consequences. 

Also see - http://www.nopcommerce.com/boards/t/29637/performance-optimization-needed-nopcommerce-is-too-slow-.aspx?p=7#123632

**Comment by rudgr** [comment]
vote++;

**Comment by MikeDub** [comment]
I initially thought I wanted a /category/product route too.
However I remember that NopCommerce supports multiple categories, 
so would /Brand/Product be a more reliable suggestion?

Maybe ideally if we had a route such as this: /Brand/Category?/Product, where it would only display the category if it was the only category the product was in.

Thoughts?
