### ISSUE TITLE
Remove Customer Required Data

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3850]
nopCommerce version: 4.2

Steps to reproduce the problem: 
When installing do we really need all the addresses and customer accounts that get installed automatically? IMO all of this should be removed and not automatically installed every time.

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/3603

**Comment by toddca** [comment]
@RomanovM - take a look at create_required_data.sql - there are a number of users, addresses, passwords, user role mappings created. The referenced issue does not address these.

**Comment by RomanovM** [comment]
@toddca Files "create_required_data.sql" and "create_sample_data.sql" are created just before the official release, so don't worry we will update them later for 4.20 version (not BETA).

**Comment by toddca** [comment]
@RomanovM but what about the fact I do not want any customer data, sample orders, products, etc? I get it, you want to show/demo what NopCommerce looks like however I end up having to go back and clean all this up. Maybe offer a way to clean up sample data?
