### ISSUE TITLE
User Agent Performance Issue

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3853]
nopCommerce version: 4.2

Steps to reproduce the problem: 
In UserAgentHelper.IsMobileDevice() for each call two complicated Regex objects created and then not used again. The Regex class is thread safe and we should be creating these as static objects and using the option RegexOptions.Compiled when creating these.

I do not have specific performance numbers.

**Comment by RomanovM** [comment]
See also https://github.com/nopSolutions/nopCommerce/issues/3608

**Comment by toddca** [comment]
@RomanovM I look a look at #3608 and it references Crawler Detection which is a totally different performance issue than what I am talking about here. But since you mentioned it, the only reference I could find to using the BrowserCap stuff is for IsCrawler() which basically is needed for the IsSearchEngine() which the only time that is used is to determine if we load a specially named guest account or create a new guest account for a crawler. IMO this is a total waist, you end up having to deploy 70MB+ of XML files and parsing/loading just so you can use a specially named guest account. I do not understand the logic here?

**Comment by skoshelev** [comment]
Hi @toddca, thank you for help

Closed #3853
