### ISSUE TITLE
Call For Price with a template

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3854]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Actually "Call for Price" is only a information. It would be good, if it is a button, to make a price request for that, similiar like "Email to a friend". 

The reason is, that in EU all customers can return the goods for 14 days without any reason. The return rate actually about 1-10%. But if the product is expensive and also complicated like espresso machines, that it is better to not allow selling with a hy button, but to accept a request. The "Call for price" is not very useful in this scenario. Better to take the product in a form ad send the request to the store owner.

**Comment by tigran-avdalyan** [comment]
https://github.com/nopSolutions/nopCommerce/issues/2191
similar offer

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality

it'll be implemented as part of https://github.com/nopSolutions/nopCommerce/issues/279
