### ISSUE TITLE
Tasks Not Running When Hosted in Azure

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3858]
nopCommerce version: 4.2

Steps to reproduce the problem: 
With default store configured as HTTP://[host]/ and the web server running in Azure and on HTTPS://[host] and Azure is configured to redirect HTTP->HTTPS the tasks fail to run since the HttpClient which is used is not setup to AllowAutoRedirect as it was when you used WebClient in 4.1. I would suggest you have a custom HttpClient for calling tasks.

I fixed this issue by changing my store url to HTTPS however that should not have to be the case.

**Comment by RomanovM** [comment]
@toddca  All is right, if you have a server hosted on HTTPS://[host] you need to configure your store URL as HTTPS://[host] as well, otherwise schedule tasks will not be executed
