### ISSUE TITLE
Add support for hidden checkout attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#386]
Forum source: https://www.nopcommerce.com/en/boards/topic/29547/nopcommerce-340-roadmap-and-estimated-release-date-lets-discuss/page/3#120472

Related work items - https://github.com/nopSolutions/nopCommerce/issues/315, https://github.com/nopSolutions/nopCommerce/issues/4307

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/315
