### ISSUE TITLE
Language Resource Import no longer supports UTF-8 

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3860]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 
Under Language, Resources the import did not accept anymore the utf-8 xml files. it gets a read error in the first line (by the way also utf-16 without bom is also not supported, only utf-16LE).

yes, we could convert the unicode resource file for 4.20, but we have also translated about 80 plugins which are all utf-8 to be read in all versions of nop commerce. At this momentm we have to offer two files, of all, only because 4.20 could not read utf-8.

Is there a chance to accept on import also utf-8 xml?

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce/commit/e91a44affc1b9b8780710aeb480e43702dcdbecd

**Comment by cnEUL** [comment]
@skoshelev 
The Import now accepts UTF-8, but if you now export a resource like US, then the file is coded in UTF-8, but the header info of th exml is still utf-16, so a browser cannot open this. You have to open it in a editor and you have to change it to utf-8 in the header.

**Comment by skoshelev** [comment]
Closed #3860
