### ISSUE TITLE
Picture not remove after insertions into product edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3861]
nopCommerce version: 4.2

Steps to reproduce the problem: 
Picture not remove after insertions into product edit page

> Goto product edit page
> upload image for product and press save button.
> now previous image need to remove as working into nopcommerce prevision version.

![Capture](https://user-images.githubusercontent.com/10364140/57965633-7057bf00-7964-11e9-88c6-d300ce8cb89d.PNG)

**Comment by RomanovM** [comment]
It works the same way as in the previous version. Anyway, you can't add the uploaded picture to the product twice, see details [here](https://github.com/nopSolutions/nopCommerce/commit/54948e0d15aff0ce84714bfb0d33806b8d09b322)

**Comment by sagarnop** [comment]
Hello @RomanovM ,
Inserted picture is accidentally remove in the product picture grid.
but user have seen this picture in upload control so he/she directly click on add button to add this picture record,but system give popup error message.
![product_picture_error](https://user-images.githubusercontent.com/50259172/58070748-db4d0400-7bb7-11e9-9294-33380d73e761.PNG)

**Comment by sangeetshah** [comment]
I know this working as previous version but this is bug did you don't think?


![chrome-capture](https://user-images.githubusercontent.com/10364140/58070699-a9d43880-7bb7-11e9-9fd1-3c0c556eb83c.gif)


when "Failed to add product picture." popup come at the time error log come into console as "http://nop42beta-001-site1.ftempurl.com/Admin/Product/ProductPictureAdd 500 (Internal Server Error)"

**Comment by RomanovM** [comment]
Decided not to implement it now.
