### ISSUE TITLE
German Language Resource for 4.20 Beta

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3865]
nopCommerce version: 4.20

We have finished the german translations for nopCommerce 4.20 (beta) in the last days and now offer them via our website www.eulanda.eu partnumber 5525. The language resource is updated in weekly rhythm during beta.

**Comment by RomanovM** [comment]
@cnEUL Thanks for your contribution, you can upload language pack on our [marketplace](https://www.nopcommerce.com/marketplace.aspx?category=1). But what is the reason to create this issue here?

**Comment by cnEUL** [comment]
@RomanovM
No during beta, also for testing new german resources, in this state in the marketplace there was no 4.20 entry. Now it could be closed.
