### ISSUE TITLE
Datagrid mastercheckbox need to uncheck after admin press delete selected button

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3866]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 

1st issue
1) Go to admin panel of nopcommerce.
2) Go to any grid that having master checkbox.(e.g. go to product list page)
3) now select mastercheckbox and press delete seleted.
4) now mastercheckbox need to unselect.

2nd issue
1) if i need to see latest record of datatable then i must need to refresh whole page. because i didnt see any refresh button of datatable. this button exist into kendo grid (4.1 or oldest nop version)
![chrome-capture (1)](https://user-images.githubusercontent.com/10364140/57981442-374b4780-7a55-11e9-9b36-fe17e72acd85.gif)

Datagrid mastercheckbox need to uncheck when user delete datatable row using this. need to refresh whole page if i need to show letest row into datatable.

**Comment by DmitriyKulagin** [comment]
Closed #3866
