### ISSUE TITLE
Customer,Order Export excel file display wrong CreatedOnUtc data or not display date.

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3867]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 

1) Goto customer list and select some of customer or one customer 
2) click on excel export selected button and check CreatedOnUtc  field data.
![customre sheet](https://user-images.githubusercontent.com/10364140/57981615-46cb9000-7a57-11e9-828f-378033ebebd4.png)

**Comment by skoshelev** [comment]
Hi @sangeetshah.  This isn't a bug, for import and export we us the "[OLE automation date](https://docs.microsoft.com/ru-ru/dotnet/api/system.datetime.tooadate?view=netcore-2.2)" to saving and loading the datetime fields

Closed #3867

**Comment by sangeetshah** [comment]
if i need date time for this field then how to get?

NonIT person dont know judge from this field data what date need to come here

**Comment by skoshelev** [comment]
This is due to compatibility issues with date and time formats, since we cannot control the type of fields in the Excel file, we cannot guarantee the correct handling of the date if it is in an incompatible format, so we use a secure format.

**Comment by sangeetshah** [comment]
@skoshelev 
can you convert this datetime to string to send ?
e.g.   new PropertyByName<ChildDiscount>("EndDateCT", p => p.EndDateCT.ToString()),


if you convert this datetime to string then it doesnt effect with any compatibility issue.

**Comment by skoshelev** [comment]
@sangeetshah 
I'm sorry, but this is only half the task, the date in text format will need to be imported later, and then compatibility problems begin.

**Comment by MSAInfotech** [comment]
how to

**Comment by MSAInfotech** [comment]
How to print order date in export to excel
