### ISSUE TITLE
Products never purchased grid filter might not be working properly

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3868]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 

1) Go to Admin/Report/NeverSold page
2) now only select Gift cart filter from category and hit enter. you get all over 2 product based on this filter
3) now also apply date filter 5/1/2019 to 5/19/2019 and hit enter. now you get 3 product into grid.

now this datetime filter might be work on 2record.

![chrome-capture (2)](https://user-images.githubusercontent.com/10364140/57982325-77b0c280-7a61-11e9-982f-69e9d8a7677f.gif)

**Comment by AndreiMaz** [comment]
@sangeetshah so what is the bug? what was the expected behavior?

**Comment by sangeetshah** [comment]
First i have applied category filter that give me 2record. now if i applied additional filter then filter might be based on two record. but result is differ.

Expected result is 2record.

**Comment by RomanovM** [comment]
All is ok here. You have never sold two of your gift cards (and sold one) at all times, but during the selected period you have not sold any of them. Filter works as expected.
