### ISSUE TITLE
WebP image support

### ISSUE THREAD

**Issue by stephenstroud** [nopSolutions/nopCommerce#3869]
WebP should be definitely added. 

Let's think and decide about JPEG 2000

**Comment by DmitriyKulagin** [comment]
Judging by the latest data, the jpeg 2000 format is not developing and its support by browsers leaves much to be desired (https://caniuse.com/#feat=jpeg2000).
I think it’s better to focus only on webp format support (https://caniuse.com/#feat=webp)

**Comment by AndreiMaz** [comment]
@DmitriyKulagin agree

**Comment by DmitriyKulagin** [comment]
Closed #3869
