### ISSUE TITLE
I unable to take database backup from Maintenance page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3870]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 
1) Go to Maintenance page in admin panel
2) now when i try to create backup for my database then i get error that attached with this message. 

I have hosted my website on smarter asp.net and provide full read/write permission to my directory. 

![screenshot-nop42beta-001-site1 ftempurl com-2019 05 19-18-31-22](https://user-images.githubusercontent.com/10364140/57982578-d1ff5280-7a64-11e9-9132-88a052f85dfb.png)

**Comment by AndreiMaz** [comment]
@sangeetshah please see the description of this block - "Database backup functionality works only when..." 
That's why it doen't work
