### ISSUE TITLE
Deplicate error message display (5times) on SendinBlue configuration page. error message not remove if i refresh page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3871]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 
 goto SendinBlue configuration page and try to save wrong API v3 key and click on save button. now you get success message with error message(duplicate 4times).error message not remove if i refresh page.

now refresh your page(try to refresh many times) but this error message not remove from this page.

![Untitled](https://user-images.githubusercontent.com/10364140/57982743-23a8dc80-7a67-11e9-8895-538c260a75f1.png)

deplicate error message display 5times on SendinBlue configuration page.

**Comment by RomanovM** [comment]
It's by design, you'll see see error messages according to the number of occurred errors. And if they are not disappeared, you are probably doing something wrong, in your case enter the wrong key

**Comment by sangeetshah** [comment]
by desing???

by desing need to show same error message multiple time? is this valid? and also if i try to refresh page then error message need to remove.(i had refresh this page n number of time but error message not gone)
