### ISSUE TITLE
 Pickup in store page, i didnt get any required field validation message for new pickup point form.

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3872]
nopCommerce version: 4.2beta

Steps to reproduce the problem:  Pickup in store page, i didnt get any required field for new pickup point form.

go to pickup in store page. now click on add new pickup point button and then without enter any detail press save button

![Untitled](https://user-images.githubusercontent.com/10364140/57982934-84391900-7a69-11e9-982c-1fe2c0700e97.png)

**Comment by RomanovM** [comment]
Yes, this is because the pickup point has no required fields.

We can though add mark some of them as required. But for what? If a user wants to add blank pickup point, let him do it

**Comment by sangeetshah** [comment]
but why user need to add blank pickup point?  and imgine blank pickup behavior into front side.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
