### ISSUE TITLE
Created multiple duplicate record when clicking multiple times on form save button.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#3873]
nopCommerce version: 4.20Beta

Steps to reproduce the problem: 
Created multiple duplicate record when clicking multiple times on form save button.
For e.g: 
Add new category,product,customer address, and clicking multiple times on form save button.

**Comment by RomanovM** [comment]
@sagarnop Yes, but what the issue here? If it was accidentally, you can always delete unnecessary entries

**Comment by sagarnop** [comment]
Hello @RomanovM ,
I totally agree with you but if hacker try to repeat this process n number of time then imagine how many record come into database and also size of database is increase. This display wrong impact.
Are agree with this point?

**Comment by RomanovM** [comment]
Well, then let's just not let hackers get on your site :) It's not the design issue.
