### ISSUE TITLE
Link product variants to parent grouped product by SKU in product import

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3874]
The issue is that it is not possible to import new grouped products and new product variants in the same import file because the product variants require the id of the parent grouped product and you do not currently have this information available.

The relevant import fields we have (in the xlsx file are):
ProductId
ProductType ('Grouped Product' or 'Simple Product')
ParentGroupedProductId

As the link suggests, the workaround is to import the grouped product first, followed by importing the product variants in a separate file (after you have established the parent product id).

And as the link suggests, one possible solution could be to look up products instead by 'ParentGroupedProductSku' instead of 'ParentGroupedProductId' as you will have the SKU available at the time of compiling the complete import.

Source: https://www.nopcommerce.com/boards/t/63779/suggestion-potentially-link-product-variants-to-parent-grouped-product-by-sku-in-product-import.aspx

**Comment by ecommerce-tester** [comment]
https://www.codeproject.com/Articles/1194712/Advanced-Excels-With-EPPlus

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
