### ISSUE TITLE
Unable To Scale Out NopCommerce 4.2 Running in Azure To More Than One Instance

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3876]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Deployed latest version of 4.2 to Windows web app running in Azure
2. Setup site to use Managed SQL instance running 8 proc, 32 GB RAM and install sample data.

Everything works great with 1 instance, I have done load testing where I have had 100,000+ requests handled in less than 5 min. However, once I scale the app out to two instances I start receiving HTTP 500 errors. I get errors like: Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.ExchangeRate.EcbExchange.dll' is denied.

After scaling out web application I have redeployed however that does not address the issue.

Note this is not specific to 4.2 as I can reproduce on 4.1 too with a totally separate app in a different Azure region/datacenter -- the only commonality is a HTTP 500 in both cases. Has anyone test this scenario -- I suspect its a supported one.

**Comment by skoshelev** [comment]
Duplicate #3797
