### ISSUE TITLE
Log is very slow to browse when there is a 17000+ entries

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#3877]
nopCommerce version:  4.0

Steps to reproduce the problem: 
Have a log of 17000+ entries

Browse the log 100 entries at a time via the admin portal. Takes 10-15 seconds to load each page.  

Why is browsing the log so slow? I can remotely login to the DB and pull all entries from SQL in a few seconds maximum.

**Comment by stephenstroud** [comment]
@rolandh I found the logger very limiting although helpful. In addition I plugged in a heavy weight logging solution https://datalust.co/seq - You can create a fairly lightweight NopReplacement plugin to support this.

**Comment by rolandh** [comment]
We also use our own logger (that uses sentry) but I liked having nop errors separated and in its own viewer. It would be nice to fix the speed as I can't see why it should be slow, maybe it is pulling back all log entries and filtering in memory instead of on the server.

**Comment by DmitriyKulagin** [comment]
I tried to reproduce this situation on the latest version of nopCommerce 4.30 (develop). The response time is about 0.96 ms per page loading of 100 entries. In the database with this order, 35000+ entries
