### ISSUE TITLE
Add "Refresh" button on all datatables grids

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3879]
Originally reported in https://github.com/nopSolutions/nopCommerce/issues/3866
"if i need to see latest record of datatable then i must need to refresh whole page. because i didnt see any refresh button of datatable. this button exist into kendo grid (4.1 or oldest nop version)"

**Comment by sk5202** [comment]
Yes that's right. Hope will fix to add refresh button at all data table.

**Comment by DmitriyKulagin** [comment]
Closed #3879
