### ISSUE TITLE
Admin Menu Minimize -- grid style issue

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3881]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: Go to Admin Panel>>Any Grid Table(Example Product list>>Minimize Admin menu )
![nnn](https://user-images.githubusercontent.com/17789934/58238319-e4df8480-7cfb-11e9-8137-d43f9d45f6e8.gif)

**Comment by RomanovM** [comment]
Already fixed. Please see https://github.com/nopSolutions/nopCommerce/commit/60e87a2000543f12dd15bbd806a4cfbb519162ec

**Comment by tigran-avdalyan** [comment]
When Grid table is loading -- you can see grid style issue
![mmm](https://user-images.githubusercontent.com/17789934/58240599-2e31d300-7d00-11e9-9465-6683ff593f01.gif)
