### ISSUE TITLE
Polls start date issue

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3886]
nopCommerce version: 4.2 beta

Steps to reproduce the problem: Go to admin panel>>Content Managment>>Polls 
Create new Poll and set Start Date
![zzz](https://user-images.githubusercontent.com/17789934/58307694-5e3aae00-7db4-11e9-82f5-bcf49953badf.gif)

**Comment by tigran-avdalyan** [comment]
Same issue in End Date

**Comment by tigran-avdalyan** [comment]
in Nopcommerce M/d/YYYY format, and in my system sets d/M/YYYY

**Comment by tigran-avdalyan** [comment]
On admin-demo.nopcommerce.com 4.10 works fine .

**Comment by RomanovM** [comment]
It's known issue. See https://github.com/nopSolutions/nopCommerce/issues/30
