### ISSUE TITLE
Allow Quantity

### ISSUE THREAD

**Issue by mehdinaz** [nopSolutions/nopCommerce#3888]
nopCommerce version: 4.2 beta

Steps to reproduce the problem:

Tick the **Allow Quantity** to the inventory count
for example
If there are 5 items in stock
Allow Quantity **don't exceed** 5
Allow Quantity **Automatically save** 1, 2, 3, 4, and 5

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.
