### ISSUE TITLE
Product History function

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3889]
Ability to save Product History (price history, quantity, ....., )
Please see:
https://www.nopcommerce.com/boards/t/37161/feature-product-history-enable.aspx
https://www.nopcommerce.com/boards/t/24669/product-pricecost-history.aspx

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
