### ISSUE TITLE
Azure Web App Deployment Slot Support WWW. issue

### ISSUE THREAD

**Issue by stephenstroud** [nopSolutions/nopCommerce#3890]
nopCommerce version: 3.90

Steps to reproduce the problem: 
HTTP 502 occurs using NopCommerce with Azure Webapp Deployments Slots.  Caused by Admin/Setting/GeneralCommon - Setting WWW prefix requirement to 'Pages should have WWW' prefix'. Azure Deployment slots URLs don't support WWW. under default DNS just non WWW. This is an issue with Production environments relying on the setting as it comes from the database and causes issues for production slot testing.

SOLUTION: 
Setting WWW Prefix requirement to 'Doesn't Matter' and adding a rewrite rule to  WebConfig resolves this issue.

![image](https://user-images.githubusercontent.com/7649287/58323792-ed7bac00-7e1c-11e9-95cf-dfc9c78cbe01.png)

Certainly a nice to have as I spent a while investigating why deployments slots suffered from HTTP 502.

**Comment by RomanovM** [comment]
@stephenstroud Thanks for your investigation and proposed solution. Could you please post also it on our [forums](https://www.nopcommerce.com/boards)?
