### ISSUE TITLE
product list page on category search filter can not work properly.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#3891]
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
Step 1: Create categories "A","B" and "C".
Step 2: Give Category "A" for parent of categories "B" and "C".
Step 3: Add two products ("$100 Physical Gift Card" and "$25 Virtual Gift Card") in category "B".
Step 4: Add one product ("$50 Physical Gift Card") in category "C".
Step 5: Product list page on select category filter in category "A" and without checked "Search subcategories" checkbox click on search button. then Categories "B" and "C" products will be display on product list.
Here  "Search subcategories" checkbox not checked.but still category filter searching in subcategories product. and category "A" have not any products.

https://www.loom.com/share/ecda390dbf70435fb066f5b5f95b2032

**Comment by sagarnop** [comment]
Hello @AndreiMaz  and @RomanovM ,
Is it not a bug?

**Comment by DmitriyKulagin** [comment]
@sagarnop Hi, I just tried to repeat the error on the latest version. Everything works correctly. Without the "Search subcategories" option activated, products from subcategories are not displayed. Try to repeat your test now.

**Comment by DmitriyKulagin** [comment]
@sagarnop  For details, please see [this](https://github.com/nopSolutions/nopCommerce/commit/1a003cc0) commit.
