### ISSUE TITLE
After the product is registered by the Vendor, the product will not be released

### ISSUE THREAD

**Issue by mehdinaz** [nopSolutions/nopCommerce#3893]
nopCommerce version: 
4.2 beta
Steps to reproduce the problem: 
After the product is registered **by the vendor**, the **product will not be released**
The product is approved by the manager or rejected and then published on the site
So that
Any Vendor can not directly publish the product on the site

**Comment by AndreiMaz** [comment]
thanks for suggestion. but we leave for customization now
