### ISSUE TITLE
Order edit page , missing State / province and country name.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3894]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Go => Admin/Order/Edit/5

go Billing & shipping collapsible.

See below picture to identify missing labels.

![image](https://user-images.githubusercontent.com/41533502/58384098-7cdeb600-7ffb-11e9-8be7-bea3be009f70.png)

**Comment by DmitriyKulagin** [comment]
Closed #3894
