### ISSUE TITLE
IP Address search is not working properly at customer listing page.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3895]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Go Admin/Customer/List

try to search with ip address.

It should not search null or empty ip address when search with different cases.

When i type 127.0.0.1 at that time it is displaying one record that's fine.

but when i type 127.0.0 that it display all record instead of 1 record.

Also, it is search with contain condition like other for an ex. Email , FN etc.

here is the video for better explanation.

https://www.loom.com/share/37c7d7a061dd49f79dd947179cf8f5e9

**Comment by DmitriyKulagin** [comment]
Hi, @sk5202 
Before searching by IP, it is checked whether the string is a valid IP address. If not, then the parameter value will not be taken into account during filtering. So, everything works correctly.
