### ISSUE TITLE
Store closed setting is not working properly

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#3896]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: 

Go general setting.

Enable store closed checkbox.

clear cache or restart application.

https://www.loom.com/share/f4c6a1b2e95c44179578b1b8db20fbc3

**Comment by RomanovM** [comment]
It works as expected. Store is closed for everyone except customers with permission "AccessClosedStore"
