### ISSUE TITLE
Add to cart button throw an error in IE browser

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3897]
nopCommerce version: 4.2beta

Steps to reproduce the problem: 

1) open IE browser 
2) opent his product detail link http://nop42beta-001-site1.ftempurl.com/build-your-own-computer
3) now select product attribute that is required
4) try to add to cart this product.
![Untitled](https://user-images.githubusercontent.com/10364140/58396729-8ef83d00-806b-11e9-8c03-855cc85d4853.png)

**Comment by sangeetshah** [comment]
is this bug or not?

**Comment by DmitriyKulagin** [comment]
Not reproduced for ver. 4.20
