### ISSUE TITLE
Avalara tax provider - plugin install issue

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3900]
nopCommerce version: 4.20 beta

Steps to reproduce the problem: Go to Admin Panel>>Local Plugins
and press install Avalara tax provider plugin
after that press "Restart application and apply changes"
Result - plugin not installed

**Comment by RomanovM** [comment]
@tigran-avdalyan I just checked it and it works like a charm. Do you see any errors in the log?

**Comment by tigran-avdalyan** [comment]
Please see
![plug](https://user-images.githubusercontent.com/17789934/58412808-4e5aec80-8088-11e9-920f-50146d69ebe1.gif)

**Comment by RomanovM** [comment]
@tigran-avdalyan Your application not really restarted, that's why plugins are not installed. I suppose you run it from vs, so you need manually restart solution to see changes.

**Comment by tigran-avdalyan** [comment]
@RomanovM You are right. Thank You
