### ISSUE TITLE
Product page -Full Description, Specification,Comments, Review show in tabs

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3901]
In StoreFront >>Product page  show Full Description, Specification,Comments, Review show in tabs.
And in admin area>>'Product detail' get ability to Enable-Disable tabs, and add custom tab.

For Example see https://demostore.x-cart.com/admin/admin.php?target=global_tabs

**Comment by RomanovM** [comment]
Thanks for the suggestion. This issue is better to contact the themes developers. There is no need a special infrastructure from nopcommerce to support it.

**Comment by tigran-avdalyan** [comment]
@RomanovM @AndreiMaz 
1.i mean needs ability to hide Full Description, Specification,Comments, Review  for product (needs setting in admin area).
2.Need ability to add Custom section in product page. for example Map section, or Additional info section.

P.S.

its not connected with tabs.

**Comment by tigran-avdalyan** [comment]
@RomanovM @AndreiMaz
in Product Page  by Default we have Product  Description, Product Specification, Product Tags sections.
Needs ability in admin area to Hide/Show sections for product.
Needs ability in admin area to add Custom section.
can we reopen this issue with this description?
