### ISSUE TITLE
Possible issue with "commonsettings.enablehtmlminification" setting

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3903]
nopCommerce version: 4.20 BETA

When enabled on a live server it could displayed the attached screenshot

It could be fixed by disabling this setting

![crazy_admin_login_page](https://user-images.githubusercontent.com/5019111/58427051-1f07a800-80a7-11e9-89e1-ad69df5e2064.png)

**Comment by DmitriyKulagin** [comment]
Closed #3903
