### ISSUE TITLE
Conflict Category and Product tag's SeName

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3905]
nopCommerce version: 4.20 on demo store

Steps to reproduce the problem: 
 Visit category and check url of below category and product tags
1. Category - apparel and Tag - apparel
2. Category - Shoes and Tag - shoes
3. Category - Jewelry and Tag - jewelry

All product tags are redirecting on category page instead of product tag page on latest demo store

Forum post Link - https://www.nopcommerce.com/boards/t/62757/nopcommerce-420-beta-released-please-share-your-impressions.aspx?p=9#234652

**Comment by AndreiMaz** [comment]
it's not reproduceable on 4.20. It was an issue on demo site only (caused by old versions of nopCommerce)
