### ISSUE TITLE
reviews.fields.rating.notgoodnotexcellent missing?

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3907]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
I get this in my logs:
Resource string (reviews.fields.rating.notgoodnotexcellent) is not found. Language ID = 1

I do not see it in defaultResources.nopres.xml or installation.en.xml

**Comment by Ochapparel** [comment]
Looks like it's in View/Products/ProductReviews.cshtml

**Comment by skoshelev** [comment]
Closed #3907
