### ISSUE TITLE
ITaxPluginManager.LoadPrimaryPlugin() Returns ITaxProvider For Plugin Which is Not Enabled

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3910]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Activate the Avalara Tax Plugin
2. Notice you will get a number of errors in your logs like: Avalara tax provider error. Tax provider is not configured

Expected: Being that the provider/plugin is not enabled I would not expect we would attempt to use it and we should fail gracefully without errors being written to the log and without calling into a provider which is not enabled.

**Comment by RomanovM** [comment]
All is ok here, plugin activated = plugin enabled in this case.
