### ISSUE TITLE
Can't upload ZIP file with plugin and subfolders

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3915]
Can't upload ZIP file with plugin and subfolders in nop 4.20.
Plugin in this ZIP file has subfolder **Resources**
ZIP has entry '4.20/FoxNetSoft.StripeDirect/Resources/'
Pay attention to "/" at the end of the file.
Nopcommerce creates empty file **Resources** instead of creating folder **Resources**
This line of code has error.
`var filePath = _fileProvider.Combine(pathToUpload, fileName.Replace("/", "\\"));`

Source: https://www.nopcommerce.com/boards/t/66148/cant-upload-zip-file-with-plugin-and-subfolders-in-nop-420.aspx

See also: https://www.nopcommerce.com/boards/t/67289/uploading-plugin-420-and-a-directory-is-exctract-as-a-file.aspx

**Comment by skoshelev** [comment]
Closed #3915
