### ISSUE TITLE
Full text enabling error

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3916]
'PK_LocalizedProperty' is not a valid index to enforce a full-text search key. A full-text search key must be a unique, non-nullable, single-column index which is not offline, is not defined on a non-deterministic or imprecise nonpersisted computed column, does not have a filter, and has maximum size of 900 bytes. Choose another index for the full-text key.
when want to enable Full text search.

Source: https://www.nopcommerce.com/boards/t/67170/full-text-enabling-error-nopcommerce-420.aspx

**Comment by skoshelev** [comment]
Closed #3916
