### ISSUE TITLE
Address hierarchy

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3917]
1.Rename "County" to "County / Region"
2.In Admin Area we have Country>>State / Provice and we can only add Country and State / Provice.
Need ability to have Country>>State / Provice >>County / Region>>City>>Districts

The Admin can create full address data, and customer can select from predefined data.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality (except point 1)
