### ISSUE TITLE
Add LastUpdateCustomerId to entities

### ISSUE THREAD

**Issue by samhippie** [nopSolutions/nopCommerce#3918]
nopCommerce version: 
4.2

When a user modifies an entity, the only place this action could be recorded is in the ActivityLog table. If we added a "LastUpdateCustomerId" column to an entity, then it would be possible to make a transaction log in the database to track any changes to an entity as well as which user made those changes.

**Comment by RomanovM** [comment]
Thanks for the suggestion. After discussion decided not to implement this feature and leave it for the customization.

**Comment by fpdavis** [comment]
I would like to see a little more discussion on this and possible ways it could be implemented. It seems like it would be a wide sweeping change (though minor) for a customization and could be done better in the core.

**Comment by AndreiMaz** [comment]
It'll require a lot of source code customization and duplication. ActivityLog is more than enough to get this information. Furthermore, it tracks datetime, history (if multiple actions are takes). It's much better
