### ISSUE TITLE
Performance issue on window Sever 2016 

### ISSUE THREAD

**Issue by HusseinElGanzory** [nopSolutions/nopCommerce#3923]
nopCommerce version: 
4.2
Steps to reproduce the problem: 
after publish nop files on windows server website very slow request take form 4 to 8 second to open page or request api data . despite hosting on ubuntu linux it very fast any recommendation please

**Comment by RomanovM** [comment]
You can post this question on our [forums](https://www.nopcommerce.com/boards) and the community will try to help you. 
There is no specific issue here, so I close it.
