### ISSUE TITLE
Square infinite loop on nonce request

### ISSUE THREAD

**Issue by cunnpole** [nopSolutions/nopCommerce#3924]
nopCommerce version: 4.20
Same in 4.10

Steps to reproduce the problem: 
1. Add item to basket and proceed to checkout
2. Supply billing address
3. Specify shipping method
4. Provide payment information
5. On Confirm Order screen go back to Specify Shipping method (doesn't matter if you select the same one or not)
6.  Continue back to Confirm Order and you'll see the nonce value changing about once a second

H.prototype.receiveMessageCallback receives calls until the end of time. It's like it knows there are 2 separate orders in progress

**Comment by DmitriyKulagin** [comment]
Hi, @cunnpole 
Cannot reproduce step by step. 
What do you mean by "nonce value"? Could you send a video on which we can understand what the problem is?

**Comment by DmitriyKulagin** [comment]
Closed #3924
