### ISSUE TITLE
Specification attributes missing in "Basic" view

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3927]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
1) Turn on "Specification attributes" in the product edit
2) Turn on "Basic" switch for a product
3) It is missing
4) Switch to "Advanced" and it shows up

Setting the flag
![specification](https://user-images.githubusercontent.com/20989983/58800114-0d595f80-85d5-11e9-9cd1-00b876cf832e.PNG)

Not there in Basic
![specificationNo](https://user-images.githubusercontent.com/20989983/58800119-10ece680-85d5-11e9-939f-0b0539aec6e6.PNG)

There in Advanced
![specificationAdvanced](https://user-images.githubusercontent.com/20989983/58800165-2a8e2e00-85d5-11e9-86f5-ddbb0f679c3e.PNG)

**Comment by DmitriyKulagin** [comment]
Closed #3927
