### ISSUE TITLE
Generic Conditions/Restrictions for store configuration and multi-store platform

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#393]
I don’t know whether this is programmaticaly feasible, but it would be very valuable for Nop (and a great advantage against its competitors) and and important step towards the highly demanded multi-store to have Generic Conditions with Boolean value (similar to the present discount restrictions) that could be used everywhere to control settings, behaviour and contents of the store:
- Configure Boolean settings (i.e.: Captcha, Show SKU/MPN/GTIN, Allow product sorting, Allow view mode changing, Allow customers to upload avatars, Show customers' location, Show customers' join date, Show discount box, Show gift card box, Enable Reward points, etc. etc.).
- Hide/display shipping/payment methods and Checkout Attributes
- Skip some step of the purchasing process like select shipping or billing address, confirmation, etc.
- Hide/display products/variants/categories/manufacturers; like a kind of high level ACL
- Publish/unpublish content elements: topics, news, polls, blogs, etc.
- Etc.

Condition will be configured in a special section (similar to, for instance, check out attributes) and will have a Name, maybe a description, and will take their value if [Not] All(And function)/Any(Or function) their requirements are met (true):
- Customer has [Not] assigned Any/All of these roles:...
- Store is [Not] Any/All of these:... This restriction will be very useful for a multi-store configuration
- Billing country is [Not] any of these:...
- Shipping country is [Not] any of these:...
- Customer registered country is [Not] any of these:...
- Customer had [Not] bought an amount equal or greater than $...
- Subtotal in cart is [Not] equal or greater than $...
- TodaysDate is [Not] within this range: Date1 and Date2
- Any/All of the following conditions are [Not] true: ConditionName1, ConditionName2, ... This will be like nesting some conditions within another one.
- Etc. etc.

There will be two system conditions: “False” and “True” with the same values. 
The configuration of the settings, publishing/unpublishing, enable/disable, display/hide, will be assigning a ConditionName for each case. 

Examples: 
North American VIP (Preferred and Platinum) customers have privileges: and exclusive category of products, coupon discounts, reward points. and paying with American Express card 
There is a sale season for NA VIPs between 15/01/2013 and 30/01/2013 and for others between 01/02/2013 and 15/02/2013 

ConditionName:North_american_VIPs 
Description: Special conditions for North Americans with the roles Preferred or Platinum between 15/01/2013 and 30/01/2013 
Restrictions: If All of the following restrictions are met:
- Customer registered country is Any of these: USA, Canada, Mexico
- Customer has assigned Any of these roles: Preferred, Platinum
- TodaysDate is within this range:15/01/2013 and 30/01/2013

ConditionName:Sale_for_NorthAmericans_VIPs 
Description: Special sale for North American VIPs between 15/01/2013 and 30/01/2013 
Restrictions: If All of the following restrictions are met:
- All of the following conditions are true: North_american_VIPs
- TodaysDate is within this range: 15/01/2013 and 30/01/2013

ConditionName:Sale_for_others 
Description: Special sale the rest between 01/02/2013 and 15/02/2013 
Restrictions: If All of the following restrictions are met:
- All of the following conditions are Not true: North_american_VIPs
- TodaysDate is within this range:01/02/2013 and 15/02/2013

ConditionName:Sale_Season 
Description: For NA VIPs between 15/01/2013 and 30/01/2013 and for others between 01/02/2013 and 15/02/2013 
Restrictions: If All of the following restrictions are met:
- All of the following conditions are true: Sale_for_NorthAmericans_VIPs, Sale_for_others

Configurations (for exclusive privileges for NorthAmerican VIPs):
- Show discount box: North_American_VIPs
- Enable Reward Points: North_American_VIPs
- Category ExclusiveProducts and its products: Published: North_American_VIPs
- American Express payment method enabled: North_American_VIPs

Configurations (for sale season):
- Topic Add_For_Sale Published: Sale_Season
- Category Special Sale and is products: Published: Sale_Season

I still have some more ideas to make this more efficient (performance-wise) which I can post later if the above suggestion makes sense 

Forum source: http://www.nopcommerce.com/boards/t/20912/suggestion-generic-conditionsrestrictions-for-store-configuration-and-multi-store-platform.aspx

**Comment by tigran-avdalyan** [comment]
Ability to set Registered User Administrator Permission in Store1 (Like we set User to Vendors Group)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
