### ISSUE TITLE
Accepted 13 digits in Mobile number set only accept 10 digit validation

### ISSUE THREAD

**Issue by skalpesh05** [nopSolutions/nopCommerce#3931]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Click on address
Click on add new 
Enter 13 digits in Mobile number
![Screenshot_20190604-100116](https://user-images.githubusercontent.com/51352887/58851435-63e79c00-86b0-11e9-996f-91ca29535a0a.png)

**Comment by RomanovM** [comment]
It's by design, you can customize any validation rules if you want.
