### ISSUE TITLE
When I am in clothing category then manufecturer should also change  

### ISSUE THREAD

**Issue by skalpesh05** [nopSolutions/nopCommerce#3932]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Select apperial from category
Select clothing's from category
Click on manufecturer filter 
Check there is displayed other manufecturer
![Screenshot_20190604-103533](https://user-images.githubusercontent.com/51352887/58852665-0efa5480-86b5-11e9-86b2-45590b7c1217.png)

**Comment by RomanovM** [comment]
These are not filters, but navigation blocks, so they should always be displayed here (in the default theme). You can use another public store theme or customize it to display these blocks as you want.
