### ISSUE TITLE
Update installation terms ("MSSQL" and "SQL Server")

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3937]
Right now we have the following text on the installation page: "Use SQL Server (or SQL Express) database".

But many hosting companies use the following terms - "MSSQL" or "Microsoft SQL Server". It can confusing some users. So let's rename it to "Use Microsoft SQL Server (or SQL Express) database". Do it for all languages in \App_Data\Localization\Installation\installation.en.xml (locale name is "SqlStandard")

P.S. This task will be helpful for non technical users

**Comment by alessandromontividiu03** [comment]
https://github.com/nopSolutions/nopCommerce/pull/3970
