### ISSUE TITLE
Add file upload control type for customer/vendor attributes

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3938]
when Customer want to register, he need to upload Passport or ID card during registration, then Admin can verify user, then activate account or add to special group.

Same function need when want to apply Vendor account, needs to upload Licence or other document, and admin verify the Vendor . 

for security needs parameter MAX Upload file Size in admin area.

p.s. 

Now for registration we can add customer attribute , but upload file Control type not supported.

**Comment by ivanlewis** [comment]
This feature is very useful for store owners to verify the end customer. At least vendor should have the option to upload by selecting id type (dynamic e.g. Passport, Driving License etc) and then the file. I request the team to include this as a feature in the next release.

**Comment by mohd-taheri** [comment]
is there any plan to develop this feature?

**Comment by AndreiMaz** [comment]
Also suggested at https://www.nopcommerce.com/en/boards/topic/81568/file-upload-control-type-for-custom-customer-attributes

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
