### ISSUE TITLE
Do not require options for all specification attributes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3940]
nopCommerce version: 4.20

Steps to reproduce the problem: 
1. Create a new specification attribute without any option
2. Try to add it to a product with "Custom text" type
3. You'll receive the following error - "First, please create at least one specification attribute option"

I know it's caused by a wrong design (mapping between tables). But let's think how we can fix it without so much changes in source code (table structure, etc)

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality.
