### ISSUE TITLE
More flexible way to choose a place where to render polls

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3942]
Right now we have "Show on home page" checkbox and "System name" string value. It's absolutely unclear for managers what value to enter into "System name". Furthermore it's quite limited (only the left column and the home page)

I suggest to remove both field. And then allow a store owner to specify any place where to render a poll block. For example, let's display a list of widget zones and allow to choose one.

We can also support friendly names of widgets zones. For example, add support for some attribute to each value of \Nop.Web.Framework\Infrastructure\PublicWidgetZones.cs. Demonstration:

[WidgetFriendlyName(Name="Account page. After nagivation")]
public static string AccountNavigationAfter => "account_navigation_after";

There's no need to support localization of such names now. It'll be enough

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
