### ISSUE TITLE
Product specification attributes. Give more details description

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3943]
Please see "Specification attributes" panel at the product details page. it has some description. But it's not clear for new store owners where you can add new attributes. We have more details description on the "Product attributes" block at the same page. Let's do the same on the "Specification attributes" panel.

Add the following statement: "You can add attribute for your product using existing list of attributes, or if you need to create a new one go to Catalog > Attributes > Specification attributes

**Comment by exileDev** [comment]
Closed #3943
