### ISSUE TITLE
Add shipment. Allow to mark as Shipped and Delivered

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3944]
When add a shipment in admin area (from the order details page) a new store owner doesn't always understand that later he has to mark it as "Shipped" and then as "Delivered". Specifially when he clicks "Save" button (and not "Save and contribute edit").

So let's add two new checkboxes to this page ("add new", not "edit") - "Set as shipped" and "Set as delivered". Hide the second one only when the first one is unchecked

**Comment by exileDev** [comment]
Closed #3944
