### ISSUE TITLE
BrowscapXmlHelper.cs read browscap.xml file error

### ISSUE THREAD

**Issue by JohnsonJohnsonYuan** [nopSolutions/nopCommerce#3945]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
if browscap.crawlersonly.xml not exist, we read browscap.xml, 
using (var sr = new StreamReader(userAgentStringsPath))
```
 {
                    crawlerItems = XDocument.Load(sr).Root?.Elements("browscapitem")
                        //only crawlers
                        .Where(IsBrowscapItemIsCrawler).ToList();
              
  }
```
this will cause crawlerItems.Count == 0, because 
 the "browscapitem" element is child node of "browsercapitems", but "browsercapitems" is not the root node.

it should be like this:
` crawlerItems = XDocument.Load(sr)?.Element("browsercapitems")?.Elements("browscapitem")`

**Comment by skoshelev** [comment]
Duplicates the #2780
