### ISSUE TITLE
Allowed to add attribute combination without selecting an attribute

### ISSUE THREAD

**Issue by dtaalbers** [nopSolutions/nopCommerce#3951]
nopCommerce version: 4.20

Steps to reproduce the problem: 

1) Add two product attributes
 ```
* Color with values: Yellow, Blue
* Ram with values: 1GB, 2GB
```

![Screen Shot 2019-06-13 at 13 26 45](https://user-images.githubusercontent.com/6512556/59429137-66986e80-8ddf-11e9-968d-7c53be58e843.png)

2) Add new attribute combination manually and save without selecting a product attribute value.

![Screen Shot 2019-06-13 at 13 36 26](https://user-images.githubusercontent.com/6512556/59429538-4917d480-8de0-11e9-906f-fc4be87085a7.png)

3) You're left with an empty attribute combination

![Screen Shot 2019-06-13 at 13 28 03](https://user-images.githubusercontent.com/6512556/59429567-5b920e00-8de0-11e9-8d12-b616d79a1156.png)

I am not sure if you classify this as a bug, but to me a attribute combination without selecting an attribute doesn't seem right!

**Comment by DmitriyKulagin** [comment]
Closed #3951
