### ISSUE TITLE
Do not use IApplicationLifetime (obsolete)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3954]
An instance of IApplicationLifetime is required in Nop.Core/WebHelper.cs - used in this class to stop the application in the RestartAppDomain() method.

This API is also now marked as obsolete - https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.iapplicationlifetime?view=aspnetcore-2.2

**Comment by skoshelev** [comment]
Fixed by this commit https://github.com/nopSolutions/nopCommerce/commit/6b4765855096e3518020a4925e550f5ebdf56a01

Closed #3954
