### ISSUE TITLE
Discounts not being applied in cart when product prices are cached

### ISSUE THREAD

**Issue by samhippie** [nopSolutions/nopCommerce#3955]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
 * Set catalogsettings.cacheproductprices to True
 * Add a discount with the following information:
Name: PROMO
Discount type: Assigned to products
Use percentage: no
Discount amount: 10 USD
Requires coupon code: yes
Coupon code: PROMO
Start date: blank
End date: blank
Cumulative with other discounts: no
Discount limitation: Unlimited
Maximum discounted quantity: blank
 * Save the discount
 * Add a product to the discount in the "Applied to products" section
 * Save the discount
 * Go to the shopping cart
 * Add discount code "PROMO" and apply it

The price does not update until the server cache is cleared and the page is refreshed.

**Comment by AndreiMaz** [comment]
Thanks! It's limitation of price caching. And it's already stated in the hint of setting (cache prices) in admin area
