### ISSUE TITLE
Renamed "Html minification" to "HTML minification"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3956]
Example: http://admin-demo.nopcommerce.com/Admin/Setting/GeneralCommon

**Comment by exileDev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Renamed "Html minification" to "HTML minification"](https://trello.com/c/zTkI6p4z/1579-renamed-html-minification-to-html-minification)

**Comment by exileDev** [comment]
Closed #3956
