### ISSUE TITLE
Find a way not to override core services in Avalara tax plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#3958]
nopCommerce version: 4.20

We should register and use \Nop.Plugin.Tax.Avalara\Infrastructure\DependencyRegistrar.cs only when the plugin is enabled. We should not override services when the plugin is disabled

Furthermore, it's better to implement all the logic even without override of the service (e.g. with events, etc)

**Comment by RomanovM** [comment]
Done in https://github.com/nopSolutions/nopCommerce/commit/7dddc66675800fd26496e35df6e6fc0cb208ca29
