### ISSUE TITLE
Fluent validation not registered for plugins where plugin name does not begin with Nop.

### ISSUE THREAD

**Issue by davidandrewpowell** [nopSolutions/nopCommerce#3960]
nopCommerce version: 4.20

NopCommerce 4.20 appears to allow plugins with any name to be installed.

In `InstallController.Index(InstallModel)` the application looks for plugins that implement the `IPlugin` interface:

```
var plugins = pluginService.GetPluginDescriptors<IPlugin>(LoadPluginsMode.All)
    ...
```

and then prepares these plugins for installation.

So, for example, this would allow me to register plugins with the following naming structure: "_CompanyName.Plugin.Group.Name_"

However, in the Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs `AddNopMvc()` method, there is the following code to register fluent validation:

```
//add fluent validation
mvcBuilder.AddFluentValidation(configuration =>
{
    //register all available validators from Nop assemblies
    var assemblies = mvcBuilder.PartManager.ApplicationParts
        .OfType<AssemblyPart>()
        .Where(part => part.Name.StartsWith("Nop", StringComparison.InvariantCultureIgnoreCase))
        .Select(part => part.Assembly);
    configuration.RegisterValidatorsFromAssemblies(assemblies);

    //implicit/automatic validation of child properties
    configuration.ImplicitlyValidateChildProperties = true;
});

```
Note the line:

`.Where(part => part.Name.StartsWith("Nop", StringComparison.InvariantCultureIgnoreCase))`

which only registers fluent validation from plugins with names starting with `Nop`.  So only plugins with the naming structure "_Nop.Plugin.Group.Name_" with have the fluent validation registered.

If I have understood this correctly then there appears to be a mistake here.

Either:

Plugins of any name should be allowed to be registered and therefore the the validation from those plugins should be registered also.

Or:

Only plugins starting with Nop. should be registered and therefore the current validation registration is correct.

My understanding is that plugins with any name should be registered and therefore the validation registration should be changed to match. 

See also: [https://www.nopcommerce.com/boards/t/67488/nopcommerce-42-validation-is-not-working-while-plugin-assembly-is-not-start-with-nop.aspx#238089](https://www.nopcommerce.com/boards/t/67488/nopcommerce-42-validation-is-not-working-while-plugin-assembly-is-not-start-with-nop.aspx#238089)

**Comment by alinmircea** [comment]
There is a simple workaround for this, to register validators in the Plugin startup

services.AddTransient<IValidator<Person>, PersonValidator>();

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality

**Comment by markusschnepf** [comment]
Found the solution:
For everyone else wondering:
you need to set the properties of your model (in my case: ConfigurationModel.cs) to a nullable data type.

"public string Description" was automatically validated by "jquery.validate.unobtrusive.js" which ALWAYS gives a text like "the field <property name> is required".

after changing it to "public string? Description" my custom fluentvalidator worked fine.

there is no documentation, no changelog that talks about this behavior, no help on github, no help in the forums,
just an old thread that validators will not be registered automatically. and the nopcommerce developers decided to leave this behavior so the "solution" was to register the validator manually in your "nopStartup" class.
