### ISSUE TITLE
WebHelper.cs IsCurrentConnectionSecured checking the wrong HTTP header for a proxy

### ISSUE THREAD

**Issue by zzDave** [nopSolutions/nopCommerce#3961]
nopCommerce version:  latest develop

In Libraries\Nop.Core\WebHelper.cs\IsCurrentConnectionSecured() is checking a non-existent header "HTTP_CLUSTER_HTTPS" to check for SSL.

Remove that check so the code will reach the UseHttpXForwardedProto check.

Steps to reproduce the problem: 
Run in kubernetes with an ingress controller that does the TLS termination.   
Then check the IsCurrentConnectionSecured function.   It will never get to the UseHttpXForwardedProto check, which is the actual header which holds the http/https details.

**Comment by DmitriyKulagin** [comment]
There is no need to remove this check. Balancers will use different settings. You just need to specify the following values in your _**_appsettings.json**_ settings file 

 "Hosting": {
    //Set to "true" the settings below if your hosting uses a load balancer. It'll be used to determine whether the current request is HTTPS
    "UseHttpClusterHttps": **false**,
    "UseHttpXForwardedProto": **true**,
...
}
