### ISSUE TITLE
OOB Email Templates Address Line 2 missing

### ISSUE THREAD

**Issue by jonquickqsense** [nopSolutions/nopCommerce#3962]
nopCommerce version: 4.1

Steps to reproduce the problem: 

Place an order, review emails sent to customer and store owner.

Address line 2 is missing in templates. This has caused unnecessary admin/customer enquiries "can I update the address on the order please?  etc."

I know it can easily be edited in template, but store owners may miss this on a new store, so would be better to correct out-of-the-box.

**Comment by exileDev** [comment]
Closed #3962
