### ISSUE TITLE
Do not allow to empty empty store name

### ISSUE THREAD

**Issue by brakim** [nopSolutions/nopCommerce#3963]
nopCommerce version: 
Atleast 4.10 and 4.20 
 
Steps to reproduce the problem: 

1. Have an empty store URL
2. Mark a shipment as sent.

I think its correct? to get this error probably but the error message "URL cannot be null" can be a bit confusing when you're trying to mark a shipment as sent.

And because SendShipmentSentCustomerNotification is pretty late inside the Ship method, pretty much all is already done except PublishShipmentSent.

So because of this emtpy store url the shipment is sent, but the notifications fails and the PublishShipmentSent is not published.

I think the PublishShipmentSent event should be fired even if the notification failed.
The error message should be clarified "Store URL cannot be null".

**Comment by AndreiMaz** [comment]
@brakim Where exactly do you have an empty store URL? On the store details page in admin area?

**Comment by brakim** [comment]
@AndreiMaz Yes, or the store URL is not NULL is actually string.Empty or '' in the database.
It's not really possible in production environment but in development its pretty common to null out the the store settings, at least for us.

The error is correctly thrown it's the error message itself that is a bit non descriptive. 

Have look at MessageTokenProvider.cs line 1038 and line 862

`
var shipmentUrl = RouteUrl(shipment.Order.StoreId, "ShipmentDetails", new { shipmentId = shipment.Id });

throw new Exception("URL cannot be null");
`

**Comment by AndreiMaz** [comment]
Thanks. In this case let's just ensure that store name is not empty. It's more logical

**Comment by AndreiMaz** [comment]
@brakim We don't allow nulls for store name even in database. So cannot reproduce

**Comment by brakim** [comment]
@AndreiMaz as i posted earlier the store url **is not null** its **empty**.
My suggestion is just to update the error message from "URL cannot be null" to "Store URL cannot be null"
