### ISSUE TITLE
Bundling exclude at admin site

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3965]
nopCommerce version: 4.2

Steps to reproduce the problem:  why bundling exclude for head and footer into admin area?
@Html.NopCssFiles(ResourceLocation.Head, false)
 @Html.NopScripts(this.Url, ResourceLocation.Head, false)

**Comment by DmitriyKulagin** [comment]
@samhippie Hi,
Because it is not required for the admin panel, there is no is no increase in performance, and the overhead of bundling in this case is not justified.
