### ISSUE TITLE
Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src *".

### ISSUE THREAD

**Issue by MDindar** [nopSolutions/nopCommerce#3966]
nopCommerce version: 4.20

Steps to reproduce the problem: 
01- going to the http://admin-demo.nopcommerce.com/admin/ 
02- Open chrome developer tools
03- you can see errors in the console. 

![image](https://user-images.githubusercontent.com/3940131/59907197-bb5f6900-941f-11e9-8fa3-9d94a1be6334.png)

**Comment by DmitriyKulagin** [comment]
Not reproduced

**Comment by nattrass** [comment]
I also see this at http://admin-demo.nopcommerce.com/admin/ using Chrome Version 79.0.3945.130 (Official Build) (64-bit)
