### ISSUE TITLE
Admin area. Reorderable grid columns

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#397]
When i do some editing using the admin sektion, i often miss the possibility of moving column so the ones i use for veification is closer to one another. Eg. the systemname and the edit button. As it is now i have to align my sight accros the screen to find the correct button to press.

Its not because im blind as a mole. But accaionally i hit the wrong one.

It would be great if the clomnus were floating layers that could be draged to the order you wish them to be at. and that order was put into a DB so it were so even after an update.

Forum source: http://www.nopcommerce.com/boards/t/18994/admin-column-order.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
