### ISSUE TITLE
Caching not worked when i go from one  page to another page of website

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3972]
nopCommerce version: 4.2

Steps to reproduce the problem: 
I have cached some of data from table. now caching working fine when rendering on same page but when i move to any other page then caching not work(caching automatic remove).

e.g. 

my first problem is this below method of plugin call 12-15 time when i refresh any of page of public site.
public IList<string> GetWidgetZones()
{
            return _widgetService.GetWidgetZoneNames();         
}

Now second problem is below service is for caching but it not working when i move from one page to another. i have set this caching for 1hour but nothing happen into caching. 

```
public IList<string> GetWidgetZoneNames()
{
     return _cacheManager.Get(WidgetZonesCacheKey, () =>
      {
            return _widgetRepository.Table.Select(x => x.WidgetName).Distinct().ToList();
       }, null);
 }
```

**Comment by AndreiMaz** [comment]
@sangeetshah 
2. Please provide a complete list of steps to reproduce the issue. Are you using a static cache manager?

**Comment by sangeetshah** [comment]
i am using private ICacheManager _cacheManager for caching

**Comment by AndreiMaz** [comment]
By default it's not static (do not cache between HTTP requests). You have to inject StaticCacheManager

I'm closing this ticket. As it's a custom development question. Please post it on our forums for more info
