### ISSUE TITLE
4.2 _httpContextAccessor.HttpContext Null Referance Exception when using PictureService in a Task

### ISSUE THREAD

**Issue by tommyangelo** [nopSolutions/nopCommerce#3975]
nopCommerce version: 4.2

Steps to reproduce the problem: Create a Task that uses the PictureService GetImagesPathUrl Method. _httpContextAccessor.HttpContext is NULL because its a Task.

We have a background task that depends on _pictureService.GetPictureUrl method. In the method GetImagesPathUrl (which is called by GetThumbUrl) the _httpContextAccessor.HttpContext is NULL and throws an error. In 4.10 this method didn't exist and the shop path was handled by webHelper.GetStoreLocation(); I guess the Task doesn't have a  context, hence the exception.

**Comment by AndreiMaz** [comment]
@tommyangelo please share source code of your task

**Comment by tommyangelo** [comment]
Sorry I forgot a crucial detail, the task creates a ConcurrentQueue of sub tasks, which then calls the picture service, therefore the httpContext of the Task is lost. This is done to not get a timeout exception when creating an azuse index with lots of products. In 4.1 it worked because pictureService used webHelper to get pathBase for images, which is protected against null reference. In 4.2 in PictureService.GetImagesPathUrl you straight call _httpContextAccessor.HttpContext.Request which throws an exception if httpContext is NULL.

Here is part of the code to give you an idea. Like I said the crucial part is the Queue which is later executed async to fill azure index in batch. 

`
        public void ProductAzureSearchIndexFullUpdate(bool recreateIndex = false)
        {
            _cacheManager.Clear();
            _backgroundTaskQueue.Clear();

            var pageCount = _productService.SearchProducts(0, MaxBatchSize).TotalPages;
            foreach (var language in _languageService.GetAllLanguages())
            {
                var indexName = language.ToProductSearchIndexName();

                if (recreateIndex)
                {
                    RecreateProductsSearchIndex(indexName);
                }

                FillBackgroundTaskQueue(pageCount, language);
            }

            _logger.Information($"AzureSetupService: Recreate Azure Search Index started with {pageCount} pages");
        }

        private void FillBackgroundTaskQueue(int pageCount, Language language)
        {
            Enumerable.Range(0, pageCount)
                .ForEach(pageIndex =>
                {
                    _backgroundTaskQueue.Enqueue((services, cancel) =>
                    {
                        var localLogger = EngineContext.Current.Resolve<ILogger>(); //need a Logger instance due to Task Context
                        try
                        {
                            var azureSetup = services.GetService(typeof(IAzureSetupService)) as IAzureSetupService;

                            azureSetup?.BatchUpload(pageIndex, MaxBatchSize, language.Id);

                            if (pageIndex == pageCount - 1)
                            {
                                localLogger.Information($"AzureSetupService: Recreate Azure Search Index completed");
                            }

                            return Task.CompletedTask;
                        }
                        catch (Exception e)
                        {
                            localLogger.Error("AzureSetupService: RecreateAzureSearchIndex error!", e);
                            throw;
                        }
                    });
                });
        }

        /// <summary>
        /// the method called by the batch upload task
        /// </summary>
        public void BatchUpload(int pageIndex, int pageSize, int languageId)
        {
            if (SearchServiceClient == null)
            {
                _logger.Warning("AzureSetupService: No search client active, cancelling upload");
                return;
            }

            var language = _languageService.GetLanguageById(languageId);
            var indexName = language.ToProductSearchIndexName();

            // divide products
            var products = _productService.SearchProducts(pageIndex, pageSize);
            var productsForSearch = PrepareAzureProductDocuments(products, languageId);

            try
            {
                var batch = IndexBatch.MergeOrUpload(productsForSearch);
                SearchServiceClient.Indexes.GetClient(indexName).Documents.Index(batch);
            }
            catch (IndexBatchException e)
            {
                _logger.Error("AzureSetupService: " + e.Message, e);
            }
            _cacheManager.Clear();
        }

        
        private IList<Document> PrepareAzureProductDocuments(IList<Product> products, int languageId)
        {
            var allCategories = _categoryService.GetAllCategories();
            var manufacturers = _manufacturerService.GetAllManufacturers();

            var productIds = products.Select(x => x.Id).ToList();
            var orderedProducts = _orderRepository.Table
                .Where(o => !o.Deleted)
                .Where(x => x.OrderStatus != OrderStatus.Cancelled)
                .Where(o => o.OrderItems.Any(orderItem => productIds.Contains(orderItem.ProductId)))
                .SelectMany(x => x.OrderItems.Select(i => i.ProductId))
                .ToList();

            var productsForSearch = new List<Document>();
            foreach (var product in products)
            {
                var searchModel = CreateProductSearchModel(product, languageId);
                searchModel["orderedAmount"] = orderedProducts.Count(x => x == product.Id);
                FillSearchModelWithCategoriesFacet(searchModel, product, allCategories);
                FillSearchModelWithAttributesFacet(searchModel, product, languageId);
                FillSearchModelWithManufacturersFacet(searchModel, product, manufacturers);
                productsForSearch.Add(searchModel);
            }

            return productsForSearch;
        }
        
        private Document CreateProductSearchModel(Product product, int languageId)
        {
            var pictureModel = PreparePictureModel(product);
            var priceModel = _advancedSearchProductModelFactory.GetMultiProductPriceModelCached(product);

            var newProduct = new Document
            {
                {"productId", product.Id.ToString()},
                {"id", product.Id}, // same as productID
                {"name", _localizationService.GetLocalized(product, x => x.Name, languageId)},
                {"seName", _urlRecordService.GetSeName(product)},
                {"shortDescription", _localizationService.GetLocalized(product, x => x.ShortDescription, languageId)},
                {"sku", product.Sku},
                {"mpn", product.ManufacturerPartNumber},
                {"freeShipping", product.IsFreeShipping},
                {"longDescription", _localizationService.GetLocalized(product, x => x.FullDescription, languageId)},
                {"markAsNew", product.MarkAsNew},
                {"markAsNewStartDateTimeUtc", product.MarkAsNewStartDateTimeUtc},
                {"markAsNewEndDateTimeUtc", product.MarkAsNewEndDateTimeUtc},
                {"modifiedDate", product.UpdatedOnUtc},
                {"createdDate", product.CreatedOnUtc},
                {"price", priceModel.PriceValue},
                {"oldPrice", 0}, // todo currently no OldPrice in MultiPriceProduct
                {"url", _urlRecordService.GetActiveSlug(product.Id, "Product", 0)},
                {"thumbnailUrl", new Uri(pictureModel.ThumbImageUrl)},
                {"imageUrl", new Uri(pictureModel.ImageUrl)},
                {"imageTitle", pictureModel.Title},
                {"imageAlternateText", pictureModel.AlternateText},
                {"fullSizeImageUrl", new Uri(pictureModel.FullSizeImageUrl)},
                {"vendor", _vendorService.GetVendorById(product.VendorId)?.Name},
                {"rating", product.ApprovedRatingSum / (product.ApprovedTotalReviews == 0 ? 1 : product.ApprovedTotalReviews)},
                {"tags", product.ProductProductTagMappings.Select(x => x.ProductTag.Name).Distinct()},
                {"orderedAmount", 0},
            };

            return newProduct;
        }

        private PictureModel PreparePictureModel(Product product)
        {
            var picture = _pictureService.GetPicturesByProductId(product.Id, 1).FirstOrDefault();
            var storeLocation = _storeContext.CurrentStore.Url ?? _storeContext.CurrentStore.Url;

            var pictureModel = new PictureModel
            {
                ImageUrl = _pictureService.GetPictureUrl(picture, _mediaSettings.ProductThumbPictureSize, storeLocation: storeLocation),
                FullSizeImageUrl = _pictureService.GetPictureUrl(picture, storeLocation: storeLocation),
                //"title" attribute
                Title = (picture != null && !string.IsNullOrEmpty(picture.TitleAttribute))
                    ? picture.TitleAttribute
                    : string.Format(_localizationService.GetResource("Media.Product.ImageLinkTitleFormat"),
                        product.Name),
                //"alt" attribute
                AlternateText = (picture != null && !string.IsNullOrEmpty(picture.AltAttribute))
                    ? picture.AltAttribute
                    : string.Format(_localizationService.GetResource("Media.Product.ImageAlternateTextFormat"),
                        product.Name),
                ThumbImageUrl = _pictureService.GetPictureUrl(picture, _mediaSettings.MiniCartThumbPictureSize, storeLocation: storeLocation)
            };

            return pictureModel;
        }`

**Comment by tommyangelo** [comment]
this is the error

![null-reference](https://user-images.githubusercontent.com/7500755/60161605-31851680-97f8-11e9-944f-f16ed7bf26f6.png)

here is my suggestion for fix:
![fix-suggestion](https://user-images.githubusercontent.com/7500755/60161715-5e392e00-97f8-11e9-87a7-60b1fadeb717.png)

**Comment by AndreiMaz** [comment]
HTTP context is used in many tasks in web applciation and not suited in many cases for background tasks. In this case we cannot refactor it. Please do it on your side

**Comment by landlogicit** [comment]
Solutions: 
Override PictureService into your custom plugin.

Override method GetImagesPathUrlAsync and insert this on first

protected override Task<string> GetImagesPathUrlAsync(string storeLocation = null)
        {
            if (_httpContextAccessor.HttpContext != null)
                return base.GetImagesPathUrlAsync(storeLocation);

            var pathBase = _httpContextAccessor.HttpContext?.Request?.PathBase.Value ?? string.Empty;
