### ISSUE TITLE
Inconsistent file lookup results in NopFileProvider

### ISSUE THREAD

**Issue by dealdiane** [nopSolutions/nopCommerce#3978]
nopCommerce version: 4.10-4.20

NopFileProvider acts on the content root directory while the inherited PhysicalFileProvider is using the web root directory.

https://github.com/nopSolutions/nopCommerce/issues/3069#issuecomment-401296496 is perfectly valid and by standard, nop plugin devs should use NopFileProvider's methods but it should at least provide a consistent behavior. 

As it currently is, assuming that I have a file called `SomeFile.txt` in the `App_Data` folder, calling
`NopFileProvider.FileExists("App_Data/SomeFile.txt")` returns **true** while calling `NopFileProvider.GetFileInfo("App_Data/SomeFile.txt")` returns a **file not found**. This is because the latter uses the inherited `PhysicalFileProvider` which looks for that file from a different directory, thus giving conflicting results.

**Comment by skoshelev** [comment]
Hi @dealdiane. Thank you for your help.

Closed #3978
