### ISSUE TITLE
Active link doesn't work on my account page.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#3979]
nopCommerce version:  4.20

Steps to reproduce the problem: 
When i clicked any one link on my account page.that time i can't see active that selected link.
```
<li class="customer-reviews">
<a href="/customer/productreviews" class="active">My product reviews</a>
</li>
```
active class applied in anchor tag, but it doesn't applied in li tag.

**Comment by sagarnop** [comment]
```
<li class="@item.ItemClass">
        <a href="@Url.RouteUrl(item.RouteName)" class="@(Model.SelectedTab == item.Tab ? "active" : "inactive")">@(item.Title)</a>
    </li>
```
please selected tab also check in li tag
`<li class="@item.ItemClass @(Model.SelectedTab == item.Tab ? "active" : "inactive")">`

**Comment by exileDev** [comment]
#3979 Closed
