### ISSUE TITLE
For one address there is unnecessary duplicate entry inserted into address table

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#3980]
nopCommerce version: 4.2

Steps to reproduce the problem: 

1. I am guest customer for website
2. Add product into cart page .
3. on one page check out, i have filled the billing address and checked the checkbox that is " Ship to the same address".
4. now place the this order.
5. when i check address table record at the time i find 3same address is inserted.

i know why three address is inserted. 2record is used for shipping and billing but now third record is not usable. it increase database size.

**Comment by fsefacan** [comment]
Hi @sangeetshah,
The reason for this is to prevent the order address from being deleted when the relevant address is deleted after the customer has placed an order.

**Comment by AndreiMaz** [comment]
fsefacan is right. closing this issue
