### ISSUE TITLE
nopCommerce 4.20 Restart Application Problem

### ISSUE THREAD

**Issue by Tech-Sohail** [nopSolutions/nopCommerce#3981]
nopCommerce version: 4.20

Steps to reproduce the problem: Uninstall any plugin then for apply changes need to Reboot application. Then again try to install that plugin. and Reboot application. It is giving some error.
I tried it in local and hosted server both. (Mostly I tried for 7Spikes plugins)

**Comment by RomanovM** [comment]
Install and uninstall functions work as expected for out of the box plugins. Try to contact the plugin developer for your issue.
