### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#3982]
nopCommerce version: 4.20

Steps to reproduce the problem: if we have many products on Home Page , the page loading time in to long.
Lazy loading not working on Home Page Featured Products.

**Comment by AndreiMaz** [comment]
@ecommerce-tester What exactly doesn't work? Please provide a lsit of steps to reproduce the issue?

**Comment by ecommerce-tester** [comment]
@AndreiMaz i have 1000 product on my Home Page, when i open my home page, all 1000 product boxes are loading, but i want to load 20 product, then if i scroll down loading next 20 , then.... next 20

**Comment by ecommerce-tester** [comment]
@AndreiMaz my steps, i create 1000 product, and check Show on Home Page in admin area.
and i have performance issue, because all product loading in same time , lazy loading not working.

**Comment by AndreiMaz** [comment]
@ecommerce-tester what exactly do you mean by "lazy loading not working"?

**Comment by AndreiMaz** [comment]
we don't plan to implement ajax loading for this functionality. you'll have to customize the solution
