### ISSUE TITLE
nopCommerce 4.10 save message template multilanguage

### ISSUE THREAD

**Issue by BorisKnez** [nopSolutions/nopCommerce#3985]
nopCommerce version: 4.10

Steps to reproduce the problem: 

Default 4.10 with multiple languages. When you change for example EmailAccount for language it does not select it after refresh. In the database its saved but not selected after it reloads with save and continue. If you then select it for another language it resets back to default.

Check attached video: 
[08.07.2019_08.37.07_REC.mp4.zip](https://github.com/nopSolutions/nopCommerce/files/3377136/08.07.2019_08.37.07_REC.mp4.zip)

**Comment by RomanovM** [comment]
Also check other dropdown lists in localized editors

**Comment by exileDev** [comment]
Closed #3985
