### ISSUE TITLE
Partial "_CreateOrUpdate.Seo.cshtml" Cannot be found

### ISSUE THREAD

**Issue by ThePheonixGuy** [nopSolutions/nopCommerce#3986]
nopCommerce version: 4.20

Error: Partial "_CreateOrUpdate.Seo.cshtml" Cannot be found

# Steps to reproduce the problem:

1. Install nopCommerce on a Linux machine
2. Go to Admin Portal
3. Select Catalog>Categories
4. Select Add New

# Investigation and Results:

Searching for occurences of this name in the Presentation folder, I found three files which are cased differently to the others.
The file it was looking for is referenced with ".Seo", but is named ".SEO". This is a bug on Linux as the file system is case sensitive, and won't occur on Windows because NTFS is not.

**Comment by RomanovM** [comment]
Check all such cases with "SEO" in a filename

**Comment by exileDev** [comment]
#3986 Closed
