### ISSUE TITLE
Add to cart issue in IE11. public.common.js ln: 142, htmlcode.append(content); 

### ISSUE THREAD

**Issue by anilgajeraxit** [nopSolutions/nopCommerce#3988]
nopCommerce version: 4.20

Steps to reproduce the problem: 
When you click on "ADD TO CART" button on IE11. It will not append notification message in notification tag.

error in public.common.js file. line number 142.

http://prntscr.com/ofmczq

**Comment by yb11206** [comment]
REPLACING 
htmlcode.append(content);
with 
htmlcode.appendChild(content)

Should fix this issue on IE 11

**Comment by DmitriyKulagin** [comment]
Not reproduced for EDGE
