### ISSUE TITLE
Exception thrown deleting last item from cart (when AutoUpdateOrderTotalsOnEditingOrder is enabled)

### ISSUE THREAD

**Issue by tonywiredin** [nopSolutions/nopCommerce#3989]
nopCommerce version:  4.2

Steps to reproduce the problem: 

Place an order with a single item
visit the admin order management page for that order.
Delete the single line item

An exception is thrown in OrderTotalCalculationService.UpdateOrderTotals because the customer is null. This is because in the OrderProcessingService.UpdateOrderTotals method, the restored cart has no items in it, so there is no way to get a customer record

**Comment by tonywiredin** [comment]
This can be simply fixed. Instead of trying to get the customer from restored cart, in OrderTotalCalculationService.UpdateOrderTotals, get it from the order:

customer = updateOrderParameters.UpdatedOrder.Customer;

**Comment by exileDev** [comment]
Closed #3989
