### ISSUE TITLE
Add bulk delete-function for categories and manufacturers

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3990]
nopCommerce version: 4.30

Steps to reproduce the problem: Delete function needs when we want Bulk delete Products or Categories.

**Comment by RomanovM** [comment]
@tigran-avdalyan  Please clarify what you mean by delete on importing? There is already a bulk delete function on the product list page.

**Comment by tigran-avdalyan** [comment]
But we haven't bulk delete function for Categories or Manufacturers, we can add bulk delete function as in products, or add new header in import file "Action" and when "Action" have parameter "Delete" , when importing Category or Manufacturer will be deleted

**Comment by noncenz** [comment]
I can pick this up. Is the intent to delete the products altogether or just remove the manufacturer or category assignment?

**Comment by joekrauss** [comment]
Any chance you can include discounts? We typically have 40 discounts per week. Real pain to delete each one at a time.

**Comment by noncenz** [comment]
Sure. I'm thinking this should use checkboxes and a Delete (selected) button to mirror Products.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/4112
