### ISSUE TITLE
Product Export - not export Limited to stores parameter

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3991]
nopCommerce version: 4.20

Steps to reproduce the problem: 
1.in Admin settings enable 'Catalog settings'>>Export/Import products with "limited to stores"
2.export product with active parameter  Limited to stores.
in excel file we cant find that parameter

**Comment by skoshelev** [comment]
Hi @tigran-avdalyan. Everything works as expected, this field participates in import/export only when the [Export / Import products with "limited to stores"] setting is turned on and the [Ignore "limit per store" rules (sitewide)] setting is turned off, you should also have more than one configured store

Closed #3991
