### ISSUE TITLE
Captcha timeout problem

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3992]
nopCommerce version: 4.20

I commented on the code in the file: `//client.Timeout = TimeSpan.FromMilliseconds(5000);`

\Presentation\Nop.Web.Framework\Security\Captcha\CaptchaHttpClient.cs

```
public CaptchaHttpClient(CaptchaSettings captchaSettings,HttpClient client, IWebHelper webHelper)
{
    //configure client
    client.BaseAddress = new Uri(NopSecurityDefaults.RecaptchaApiUrl);
    //client.Timeout = TimeSpan.FromMilliseconds(5000);
    client.DefaultRequestHeaders.Add(HeaderNames.UserAgent, $"nopCommerce-{NopVersion.CurrentVersion}");

    _captchaSettings = captchaSettings;
    _httpClient = client;
    _webHelper = webHelper;
}

```

Previously when submitting a form, it often takes a long time and often recaptcha errors.
Now, when submitting the form very quickly. I have tried 50 product review and there is no error.

Source: https://www.nopcommerce.com/boards/t/66093/nopcommerce-420-is-released.aspx?p=7#242668

**Comment by exileDev** [comment]
Closed #3992
