### ISSUE TITLE
Modified eventargs get saved to DB for MessageTokensAddedEvent

### ISSUE THREAD

**Issue by amunk** [nopSolutions/nopCommerce#3993]
nopCommerce version: 4.20

Steps to reproduce the problem: 
When implementing an EventConsumer : IConsumer<MessageTokensAddedEvent<Token>> to modify the Message.Body before the message is queued any changed to the eventMessage.Message.Body is persisted to the database messing up the original template.

Example:
public class WreakHavocEventConsumer : IConsumer<MessageTokensAddedEvent<Token>>
    {
        public void HandleEvent(MessageTokensAddedEvent<Token> eventMessage)
        {
            eventMessage.Message.Body = "Noooooo!";
        }
    }

While it might be intended for other events it does not make sense on this event type.

Or am I missing something here?

**Comment by AndreiMaz** [comment]
It's by design. You should not edit it this way
