### ISSUE TITLE
Cannot add to cart a product which has RequireOtherProducts

### ISSUE THREAD

**Issue by mitdacit** [nopSolutions/nopCommerce#3994]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Install Nopcommerce 4.2 with sample data
2. Go to admin page, edit product id=30
+ Required other products = checked
+ Required product IDs = 25
+ Automatically add these products to the cart = unchecked or checked (test both cases in step 4)
3. Go to public store, open details page product id = 30
4. Add to cart
+ Case 1: Automatically add these products to the cart = unchecked ==>  see error "This product requires the following product is added to the cart in the quantity of 1: adidas Consortium Campus 80s Running Shoes"	
+ Case 2: Automatically add these products to the cart = checked ==>  still see error "This product requires the following product is added to the cart in the quantity of 1: adidas Consortium Campus 80s Running Shoes"

Please correct me if I did any wrong. 

Thank you all for fantastic Ecommerce platform.

**Comment by Zambroff** [comment]
We do not believe this to be a bug with nopCommerce.

You can't automatically add products to the cart which have attributes, this is a limitation of the system. You can try setting the required product ID to 17 and you'll see it works just fine.

In your particular case how would you know what size and colour shoe the customer wants to order when adding it to the cart.

**Comment by holydk** [comment]
Yes, in case if the required product contains the attributes, the user should be select them and add the product to cart manually.

**Comment by holydk** [comment]
Closed #3994
