### ISSUE TITLE
Multipart body length limit 134217728 exceeded.	

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3996]
nopCommerce version: 4.20

Steps to reproduce the problem: when we want import products, and file is bigger.
Or when we want to upload downloadable file.

**Comment by Xzelsius** [comment]
134217728 = 128 MB if I am not wrong
Makes no sense to increase this by default for nopCommerce.

Just configure your application to allow greater request lengths.

**Comment by tigran-avdalyan** [comment]
maxAllowedContentLenght 2147483648 =2GB
maxRequestLength 1048576 = 1GB
Deskription see https://andyfeng.ga/2018/02/04/nopCommerce-tutorial-(2)-increase-file-upload-size/

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
