### ISSUE TITLE
Allow a store owner to decide which address fields are for billing or shipping address (separately)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#40]
For example, disable email for shipping address (http://www.nopcommerce.com/boards/t/33325/disable-email-field-in-shipping-address.aspx). Or email, zip, country, etc. The same is about custom address atributes. Other carts simply don't have "Email" in "Address" entity

Currently nopCommerce do not distinguish billing and shipping address when editing in public store > my account > addresses. We should think how to handle it. Most probably we'll have to separate addresses to billing and shipping (like it was done in versions 1.X). But it's a bit wrong

Maybe, we should simply allow a store owner disable "shipping email" now? Won't it be enough?

**Comment by ArturAlekseev** [comment]
I think this idea is wrong. How it is now is fine. All user addresses are of same type. If billing address is enabled then user can select during checkout which one to use as billing and which one as shipping.
As for address fields - I think that just common should be used:
name, email, phone, address, zip. No need for more like fax etc.
Shop owners or shipping companies need only user phone and name to contact him about delivery time (if courier). Email is needed for extra contact possibility. And address/zip for shipping method.
So no need to add such feature as to enable/disable these fields from admin area.

p.s. I think the most needed feature for 3.9 is navigation speed up considering a lot of categories/products.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
