### ISSUE TITLE
x-ua-compatability metatag "position" does nothing for many version of IE?

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4003]
https://github.com/nopSolutions/nopCommerce/blob/58a385d4b6219e9c6a1ce9d9c323d8a401438c3c/src/Presentation/Nop.Web/Views/Shared/_Root.Head.cshtml#L36

This is the same for "_adminLayout"

I'm not sure WHY (ie can't find doco) but the fact that this metatag gets rendered after a handful of others (including a script) tag, means that IE in many cases ignores this setting and will still cause the site to render in compatabilty mode in many situations...

The metatag should be moved up in the tree, or perhaps you should flip to a more "add.header" approach, rather than metatags... although I don't know if there are other reasons for using the metatag in this way over the header approach.

**Comment by DmitriyKulagin** [comment]
Related to #4618
