### ISSUE TITLE
Change the https redirect method using HttpsPolicyBuilderExtensions.UseHttpsRedirection(IApplicationBuilder) Method

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4005]
The useSSL option is now used to determine the request protocol - useSsl ? Uri.UriSchemeHttps : Uri.UriSchemeHttp. But there is a more advanced way to implement this - [link](https://docs.microsoft.com/ru-ru/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#https-redirection-middleware-alternative-approach). It became available with ASP.NET Core 2.1

**Comment by RomanovM** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/3155
