### ISSUE TITLE
ADA items to assist users with screen readers

### ISSUE THREAD

**Issue by kem-storis** [nopSolutions/nopCommerce#4006]
nopCommerce version: 
4.2
Steps to reproduce the problem: 
We use a tool to scan a clean site to determine any issues that users with screen readers might encounter. I will use this issue to submit any changes requested to the Nop codebase to correct these issues.

**Comment by AndreiMaz** [comment]
already done. thanks - https://github.com/nopSolutions/nopCommerce/pulls?q=is%3Apr+ADA+is%3Aclosed
