### ISSUE TITLE
Option to assign a warehouse to a vendor

### ISSUE THREAD

**Issue by levioza** [nopSolutions/nopCommerce#4007]
Feature Request: NopCommerce Warehouse Enhancement

Actually, it would be great if there's an option to be able to assign a warehouse to a vendor. Currently, the vendor can associate a product with any warehouse in the system. So, he might add his product to a warehouse that he doesn't own. I believe that this not properly designed. This is important as the shipping is calculated based on the warehouse's address Thank you.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
