### ISSUE TITLE
Feature Request - NopCommerce Exchange Rate based on Fixer.IO

### ISSUE THREAD

**Issue by levioza** [nopSolutions/nopCommerce#4008]
Feature Request - NopCommerce Exchange Rate based on Fixer.IO

It would be great if there's a plugin integrated that supports most of the currencies. I want to use NopCommerce in the middle east and I can't find proper NopCommerce Exchange Rate plugins. Fixer.IO is good as it supports more currencies.

**Comment by RomanovM** [comment]
Thanks for the suggestion. But we don't plan to develop new exchange rate providers at this moment. You can ask about it on [our forums](https://www.nopcommerce.com/boards/).
