### ISSUE TITLE
Products in Product List would better to have links.

### ISSUE THREAD

**Issue by zandiarash** [nopSolutions/nopCommerce#4009]
nopCommerce version :
 4.20  

Steps to reproduce the problem: 
I believe that nopCommerce is perfect.
But this missing feature is annoying when products does not have a link to their actual page in Product list of admin area.
Actually other E_Commerce CMS's have a direct link when showing products in admin panel.

[Here](https://github.com/nopSolutions/nopCommerce/pull/4010) I want to add this feature 👍 
![Link](https://user-images.githubusercontent.com/10775073/62387254-53985400-b56f-11e9-94f9-df4fe17b472e.png)

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
