### ISSUE TITLE
"Old Price" for Tier Pricing

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#401]
"Old Price" for Tier Pricing would allow showing the obvious discount even when using tier pricing (which is also used to provide a different qty 1 price for a single customer) 

Forum source: http://www.nopcommerce.com/boards/t/17472/suggestion-old-price-for-tier-pricing.aspx

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/topic/91235/old-tier-price

**Comment by waelarbi** [comment]
We are using Tier Prices For different purpose wich is showing different prices for different users types per dates not as promotion but this is our business model, if user reach a certain level than he will see a different prices from users that are in other levels and for this also the old price should be updated cause it will not be the same for every level.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
