### ISSUE TITLE
Product Attributes Per Category

### ISSUE THREAD

**Issue by levioza** [nopSolutions/nopCommerce#4011]
It would be great if it's possible to specify the product attributes and specification attributes per category. Let's suppose that we sell Shoes and T-Shirts in the same store. The size attribute for shoes might be 11, 12, 13 etc... However, for T-Shirts... It would be X, M, L, XL... The size attribute will conflict... It's more logical to be able to specify the attributes per Category.

**Comment by RomanovM** [comment]
See also https://github.com/nopSolutions/nopCommerce/issues/3902

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
