### ISSUE TITLE
Feature Request - Multi Sellers Who Sell the Same Product

### ISSUE THREAD

**Issue by levioza** [nopSolutions/nopCommerce#4012]
It would be great to allow a product to be sold by multiple sellers... If a vendor A sells an Ibanez Guitar... and a Vendor B sells the same guitar... It would be great if the product could be assigned automatically to a grouped product. I'm not sure if this is the best way to implement this feature. But, it's a great feature to have :)

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/3892
