### ISSUE TITLE
Wrong product search for multi-language shop

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#4013]
nopCommerce version: 4.10 - 4.20

Steps to reproduce the problem: 

In Admin Panel

Create a second language, I.E.: **French**  
Create a product with a "Product Name" (standard) I.E. **NopCommerce**   
Add a "Product Name" for French, I.E.: **PopCommerce**  

In Public Store

Change language to **French**  
Search for **NopCommerce** 

You will see your **PopCommerce** product in the auto-complete list.
Select the product **PopCommerce** from the list
Go to the product details page; **NopCommerce** does not appear anywhere cause in French there's no reference to that word.

We have tons of product which have totally different names, short descriptions and long descriptions for different languages.
Our stores have 4 main language: French, German, Italian and English.
Some of our customers notices some products which have nothing to do with the product(s) they're searching.

I can give you an example:

**BLANCOL All Purpose Adhesive** (EN) [==>ref](https://www.blancol.swiss/product/all-purpose-adhesive/?lang=en)

is called 

**Colle de bricolage BLANCOL** in French [==>ref] (https://www.blancol.swiss/produit/colle-de-bricolage/?lang=fr)

and 

**BLANCOL Bastelleim** in German [==>ref] (https://www.blancol.swiss/produkt/bastelleim/)

All our standard names are save in **French** so the main description for that product would be:

_Colle de b**ricola**ge BLANCOL_

If someone chose the **German** Language and would want to find the famous Swiss herbal sweets using the name: **ricola** they would see in the list **BLANCOL Bastelleim** which is an adhesive.

The problem is the store procedure `ProductLoadAllPaged` cause the search on the main/standard description is UNIONed with the `LocalizedProperty` and it makes sense if you only have one language and no extra languages but in our case it is not really fit for purposes.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/2158
