### ISSUE TITLE
no dirty flag for customer changes

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4014]
nopCommerce version: all

Steps to reproduce the problem: 
change attribute in admin
no "activity log" is entered
change attribute in "customer/info"
no "activity log" is entered

I get why this isn't done, perhaps, for performance reasons, however (as far as I can tell) there is not even a "dirty/last modified" date on a customer where you can even see when a customer record was last changed, regardless of by whom.

The only way to know if a customer is changed is to implement your own logic on something like perhaps all the "save points" for a customer (customer/info and admin customer save, and anywhere else (plugins?) that a customer is changed (maybe actionfilters on all the actions.... register/info/admin customer save/create and so on...) OR IConsumer<EntityInserted/ModifiedEvent<Customer/customerattributes>> or something like this, which is all good and well, but very clunky/messy for something as simple as "is a customer changed"

if there is a simple way to do this, can someone point it at me?

**Comment by RomanovM** [comment]
Such events as `EntityUpdated<Customer>` already exist.
Could you please ask all similar questions on [our forums](https://www.nopcommerce.com/boards/). This is an issue tracker.

**Comment by awe-source** [comment]
Apologies if this wasn't clear but this IS an issue/suggestion... not a question.

The LastActiveDayeUTC and CreatedOnUtc both are part of the CUSTOMER and either deliberately or not, aren't consistent with activity log entries. It is clear to me that "activity logs" are to track a users activity, however it appears to me that its inconsistency is a flaw in this system.
I know the existing EVENT IN CODE is there for the purpose/reason u suggest, however there is no DATA equivalent... Or if there is, then it's not consistent... 
My suggestion is for the system to address this... In some way... this bit I guess is up for discussion.

My thoughts:
Add BASIC tracking - customer/info -> CUSTOMER record has activity entry "customer changed own info" - customer/address -> "customer changed an address"
Add SIMPLY "ModifiedOnUtc" fields to most of the entity tables (eg: customer, address, order... MAYBE genericattributes and so on).

There is also a case to be made to expand the functionality of the activity log refernce "entityid" which isnt' used much as far as I can tell....
This is what I was trying to highlight, and the reason I think this is "broken" is that there appears to be partial "tracking" but more from the "admin" side:
eg: if you login as admin, and open customer and impersonate, then change something it tracks that you modified an entity "backwards" (eg: the admin account records "Edited customer (ID=1234)") but there is no similar note in the customer record to indicate the reciprocal (although the data to support this is mostly there)…

Does that make more sense?

**Comment by awe-source** [comment]
(This is related, but COULD be considered a separate issue)
As additional to this, why I think this is "broken" - the events that are raised by various "actions" around the system are not very smart - as example: update of a customer is literally just the customer "base record" (kind of) has changed.
additionally, UPDATE is ALWAYS called regardless of the "to/from" state (eg: the object WAS updated, but the value was not changed.

I understand this might be for performance reasons, to not used EF or other tracking techniques by default, however, from what I can tell the events:
a) don't have access to the "old" value, only the "event entity" in its new/current state.
b) the events are only ever called "after the fact" (ie there is no "EventChanging/EventChanged" pattern here)

**Comment by samhippie** [comment]
This could be implemented on the database side if there were "CreatedOnUtc", "CreateCustomerId", "UpdatedOnUtc", and "UpdateCustomerId" fields on whatever entities you wanted to track. The difficult part about this would updating the existing code to use the new fields. You can get around this by adding these fields to the BaseEntity class and adding logic to the EfRepository class to automatically update these fields. I've experimented some with this, and I could put together a pull request if needed.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement. We have activity log for customer edit but it's only about admin area. There's no log event for editing in public store
