### ISSUE TITLE
Rework Logging to Use a Logging Framework Like NLog

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#4017]
nopCommerce version: 4.2

Steps to reproduce the problem: 
NLog has a ton of advantages over the current logging infrastructure.

**Comment by RomanovM** [comment]
See also https://github.com/nopSolutions/nopCommerce/issues/358

**Comment by RomanovM** [comment]
Thanks for the suggestion. But we don't plan to implement it right now. We leave it for customization.

**Comment by toddca** [comment]
@RomanovM yea I did see $358 however it was closed without any reason given so I thought I would open this one.
