### ISSUE TITLE
Should Nop.Core and Nop.Services have knowledge of the presentation layer

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4020]
nopCommerce version: 4.20

Main questions:
1. An instance of IHostingEnvironment is required in Nop.Core/Infrastructure/NopFileProvider.cs and Nop.Services/Media/BaseRoxyFileman/BaseRoxyFilemanService.cs, DatabaseRoxyFilemanService.cs and FileRoxyFilemanService.cs.

2. An instance of IApplicationLifetime is required in Nop.Core/WebHelper.cs.

Start of the discussion is here https://www.nopcommerce.com/boards/t/67784/should-nopcore-and-nopservices-have-knowledge-of-the-presentation-layer.aspx

See also: https://github.com/nopSolutions/nopCommerce/issues/3954

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
