### ISSUE TITLE
Second product attribute IsRequired not working

### ISSUE THREAD

**Issue by subburaja** [nopSolutions/nopCommerce#4022]
nopCommerce version: 4.20 and 4.10

Steps to reproduce the problem: Visit product detail page of any product which has more than one attribute(variant options) as required and the second attribute should be dropdownlist type. 

Issue: The first option of the second attribute will be automatically selected. But it should not be auto-selected as it is needed to be selected by user as it is "IsRequired" for users selection. 

More Info: I think source code of following file needs to be changed at line 38 into @if (attribute.IsRequired)  //remove ! 
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Product/_ProductAttributes.cshtml
![image](https://user-images.githubusercontent.com/22806694/62865863-2bf27a00-bd2d-11e9-8609-492ab7fe74a7.png)

**Comment by szocco** [comment]
Any product attribute that is type drop down list does not work as expected if set to 'is required'. These attributes should not default/preselect value based on 'is required'. https://www.nopcommerce.com/boards/t/49813/product-attribute-control-drop-down-list.aspx

**Comment by holydk** [comment]
Closed #4022 (see also #16 #2909)
