### ISSUE TITLE
Can't check if a plugin is installed in the current theme context in 4.20

### ISSUE THREAD

**Issue by koenverburg** [nopSolutions/nopCommerce#4023]
nopCommerce Version: 
NopCommerce 4.20

He Guys, what is the new implementation of `_pluginFinder.AuthenticateStore(pluginDescriptor, store.Id))`

I can't find a method to check if the plugin is installed in the current theme context in the `IPluginService`.

Am I overlooking something?

Hope to hear from you!

**Comment by skoshelev** [comment]
Please use the IPluginManager<T>.IsPluginActive method instead the AuthenticateStore method. Also please asking all your question on the our forum
