### ISSUE TITLE
No multi product catalog available.

### ISSUE THREAD

**Issue by csilk** [nopSolutions/nopCommerce#4025]
nopCommerce version: All

There is no option to create multiple product catalogs.

Ideally, you could create multiple products catalogs.

Use case: One master catalog could sync product attributes to multiple product catalogs where each catalog could have localised product information. This would suit a deployment with multiple storefronts in multiple coutries.
![Annotation 2019-08-18 015621](https://user-images.githubusercontent.com/1517793/63214428-69a33880-c15b-11e9-8d25-7e648768b121.png)

**Comment by csilk** [comment]
It looks like a workaround is to use pricing tiers with a multi store confiuration but admins will have access to ALL stores rather than just their local store. Are there any plans to move towards a better way to handle multi-country and multi-catalog use cases?

**Comment by RomanovM** [comment]
Thanks for the suggestion, but we don't plan to do it right now.
