### ISSUE TITLE
Responsive home page will output all categories in the menu

### ISSUE THREAD

**Issue by china520999** [nopSolutions/nopCommerce#4026]
Responsive home page will output all categories in the menu

nopCommerce/src/Presentation/Nop.Web/Views/Shared/Components/TopMenu/Default.cshtml 
    53 row
`    var rootCategoriesResponsive = Model.Categories.ToList();
    //name it "Categories" if we have only categories. Otherwise, "Menu"
    var responsiveMenuTitle = Model.HasOnlyCategories ? T("Categories") : T("Menu");`

`    var rootCategoriesResponsive = Model.Categories.Where(x => x.IncludeInTopMenu).ToList();
    //name it "Categories" if we have only categories. Otherwise, "Menu"
    var responsiveMenuTitle = Model.HasOnlyCategories ? T("Categories") : T("Menu");`

**Comment by RomanovM** [comment]
Thanks, we leave it for customization.
