### ISSUE TITLE
Recursive redirect to /Install after application first use

### ISSUE THREAD

**Issue by Roliari** [nopSolutions/nopCommerce#4027]
![Capture](https://user-images.githubusercontent.com/49748094/63301552-2374e300-c2db-11e9-977b-b888df102c67.PNG)

nopCommerce version:  4.30

Steps to reproduce the problem: 
1. Copy published files to the server
2. Add page to the IIS
3. Open page in any browser

**Comment by RomanovM** [comment]
It works. Try to ask on [our forums](https://www.nopcommerce.com/boards).
