### ISSUE TITLE
Per store topic page for PageNotFound

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4028]
We just encountered an issue when we were trying to achieve something using a plugin. We wanted to setup different content for PageNotFound topic page per store.

It has a limited to store functionality but we need our page not found URL to be same for both stores.

Source: https://www.nopcommerce.com/boards/t/71171/per-store-topic-page-for-pagenotfound.aspx

**Comment by nopadvance** [comment]
@DmitriyKulagin to reproduce this issue, simply make two stores in your nopCommerce installation and try to display PageNotFound topic with different contents for both store while keeping same URL for both stores.
This seems to be a major issue. We were doing work around from a long time but now it looks like this has stopped us at a place and there is no other way to achieve this without customizing nopCommerce code.

**Comment by DmitriyKulagin** [comment]
@nopadvance I tried to reproduce the situation according to your description. Now it works correctly. Each store has its own PageNotFound page with its own content, and when switching between stores, the PageNotFound page linked to the store is displayed.

**Comment by atulrungta** [comment]
@DmitriyKulagin can you please confirm if each store for PageNotFound have same URLs?
If not, then this was the issue originally reported. I don't know if it's been solved in recent development.

**Comment by atulrungta** [comment]
Actually, topic page and such other things with content must have a multi store configuration instead of Limited to store.

**Comment by DmitriyKulagin** [comment]
@atulrungta 
Yes, the URL is the same for both stores ("/page-not-found")

> @DmitriyKulagin can you please confirm if each store for PageNotFound have same URLs?
> If not, then this was the issue originally reported. I don't know if it's been solved in recent development.

**Comment by atulrungta** [comment]
Hello @DmitriyKulagin ,

Apologize for late reply but this whole feature has not been touched. It was my fault that I didn't explained properly.
Should I make a document and attach it here to explain?
Before that, can you please try to produce this scenario so you could understand my concern better:

1. I need two stores store1.com and store2.com with about us page on this Url "/about-us".
2. Both store about us pages must have store specific content. Let's say, Store 1 should say "Welcome to store 1" and Store 2 should say "Welcome to store 2" on about us pages.

This is required on all topic pages. The "/page-not-found" example provided earlier work in same way. We wanted store specific content while keeping same Url for all stores.
This is needed for all such as "LoginRegistrationInfo", "PageNotFound", "ConditionsOfuse", etc.

I hope now it must be clear :) Please let me know if still you have questions. I will be happy to help and see this in current release.

@AndreiMaz @RomanovM
