### ISSUE TITLE
Client validation is not working for nop-editor

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4029]
1. Version: 4.2
2. Expected: When Title input is empty I expect to see 'Title Required' message without full page reload using jquery validate
3. Actual: Page refreshes without triggering jquery validation
4. Steps: go to Admin -> Content -> New Blog Post -> Leave Title empty -> Save

When replacing <nop-editor... with <input asp-for="Title" the validation is working as expected then.

It seems to be something is wrong with nop-editor tag helper. Also the issue can be reproduced for Title property only. For other properties validation is triggered OK.

The issue is that data-val-required="" attribute is not in the result markup when using <nop-editor> for some reason

Source: https://www.nopcommerce.com/boards/t/71115/client-validation-is-not-working-for-title-property-of-blogpost-and-other-models-but-ok-for-other-properties-including-other-models.aspx

**Comment by DmitriyKulagin** [comment]
Closed #4029
