### ISSUE TITLE
Added to cart message not visible for IE

### ISSUE THREAD

**Issue by TTomu** [nopSolutions/nopCommerce#4033]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Customer report us with possible solution. 
Open demo.nopCommerce.com at IE11, click add to cart. No message is display. 
Possible solution:
Function displayBarNotification at public.common.js using append, which is not supported by IE. IE support appendChild.
Code below should fix issue:
`htmlcode.appendChild(content);`

**Comment by AndreiMaz** [comment]
duplicated work item
