### ISSUE TITLE
The images are generated larger than the original in the thumbs folder

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4034]
When an image is uploaded no matter where the nopCommerce Picture controller generates the picture in the \wwwroot\images\thumbs folder, the image, however, is most times larger in size than the original image which was uploaded from the Administration. For example, our client uploaded a picture which was 600kb and the one generated in the thumbs folder is 1.5Mb. I'm referring to the image that is not resized with the sizes set by the Media Settings and it is not larger than the maximum image size setting.

Source: https://www.nopcommerce.com/boards/t/71252/the-images-are-generated-larger-than-the-original-in-the-thumbs-folder.aspx

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/2073
