### ISSUE TITLE
App dies on plugin refresh

### ISSUE THREAD

**Issue by sohailqureshi** [nopSolutions/nopCommerce#4036]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1) Download source code
2) Compile and run on Localhost with VS2019 
3) Install new version of app with sample data.
4) Then Administration >> Configuration >> Local Plugins (see image Nop-01)
5) Click "Reload list of Plugins" 
6) "Reloading Plugins" screen is displayed
7) ReloadList() method is invoked (see Image Nop-02)
8) Application simply ends after :return RedirectToAction("List"); (see image Nop-03)

![Nop-01](https://user-images.githubusercontent.com/483526/63671928-a8c72e80-c7d8-11e9-8504-36d62445bfcc.PNG)
![Nop-02](https://user-images.githubusercontent.com/483526/63671929-a95fc500-c7d8-11e9-9dde-21f576546b21.PNG)
![Nop-03](https://user-images.githubusercontent.com/483526/63671930-a95fc500-c7d8-11e9-8a82-e388465f65d5.PNG)

**Comment by RomanovM** [comment]
This is a specificity of VS, see tons of similar questions (and answers) on [our forums](https://www.nopcommerce.com/boards).
