### ISSUE TITLE
.UseKestrel is limiting and not aligned with aspnetcore22+

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4037]
nopCommerce version: 4.2

Steps to reproduce the problem: 
This (I believe) forces the application to use Kestrel (or at least Break ANCM startup in some scenarios, such as inprocess operation) 

            var host = WebHost.CreateDefaultBuilder(args)
                **.UseKestrel(options => options.AddServerHeader = false)**
                .UseStartup<Startup>()

According to the doco - the "Kestrel vs IIS" setup is "intelligently" already done in  .CreateDefaultBuilder() and the "addserverheader = false should be done in ".ConfigureKestrel()"

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/index?view=aspnetcore-2.2&tabs=windows#in-process-hosting-model
https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio

The current setup appears to be against the 2.2 migration advice
and limits the application to ONLY outofprocess operation.

There may be reasons that you have done this, but if not then this appears to me/my reading to be unnecessarily restrictive (eg: prohibiting performance gains from using IIS directly on windows).

Additionally I note that there is a note on the web.config element to delay "AspNetCoreModeuleV2" until moving to 3.0, and I don't know if the decision to roll this back has anything to do with this, but its worth noting here, in case there is some insider knowledge that has an impact here.

**Comment by DmitriyKulagin** [comment]
Implemented in #3653
