### ISSUE TITLE
IPN handlers of PayPal Direct plugins. Better recurring payments support.

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#404]
1. Change new order status according to newPaymentStatus.
 2. Add 'refund' and 'void' support

But which order should be process (refund, void)? How can we know which exactly payment history record (and order) was refunded/voided? 

Regarding PayPal Standard. It doesn't support recurring payments, but it has the same implementation of IPN handler as PayPal Direct. So it's just a note to also update the source code once it's done in PayPal Direct (but not required) 

PayPal Direct. IPN doesn't mark orders as paid. We just invoke the following code in the "IPNHandler" method: _orderProcessingService.ProcessNextRecurringPayment(rp); But there's no way to mark as it paid or authorized. It's left as pending. The issue is in the implementation of recurring payment. Let's think about it

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/58253ec477e26a1db35650a4a65d9d467b203227
