### ISSUE TITLE
External authentication doesn't work properly on checkout

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4045]
What i am getting is External Authentication works fine if it comes to just login functionality but when user add something in cart and we ask him/her to login first while providing him/her functionality to login from social media accounts, h/s does it and go ahead for "proceed to checkout" here issue appears because when we hit "proceed to checkout" button it looks for next page which is billing address or simply address, so customers logged in using external authentication obviously have no address in account and got the error " we're sorry an internal error occurred ". 

Source: https://www.nopcommerce.com/boards/t/71342/login-through-external-authentication-doesnt-work-when-we-go-for-proceed-to-checkout-due-to-no-addresses-in-account-.aspx

**Comment by skoshelev** [comment]
Can't reproduce on 4.30

Closed #4045
