### ISSUE TITLE
ModelPrepared event for actions with Json result

### ISSUE THREAD

**Issue by arieldeil** [nopSolutions/nopCommerce#4048]
nopCommerce version: 4.20

Steps to reproduce the problem: 
1. Inherit a class from IConsumer<ModelPreparedEvent<BaseNopModel>> interface and implement it with some dummy code.
2. In the browser go to /Admin/Order/List
3. Add a break point on HandleEvent(ModelPreparedEvent<BaseNopModel> eventMessage) of class in step 1
4. Click search

The consumer will not get hit when OrderListModel is returned by the action. The reason is because 'PublishModelEventsFilter' is not considering JsonResult when checking 'context'.

I tried to implement a filter in my own plugin and catch 'OrderListModel' when it is executed but the problem is that the model is transformed to Anonymous type by 'BaseController.Json<T>()' method before it is processed by the filter so the original type (OrderListModel) is no longer available.

Is it possible to remove the Anonymous usage in  'BaseController.Json' method? It would be preferred to use a generic type of original model.

Of course, the better solution would be to add support for 'ModelPreparedEvent' on actions using Json results also..

**Comment by skoshelev** [comment]
Closed #4048
