### ISSUE TITLE
Add ability to copy settings/data from one store to other

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4054]
This could save most of store setup time and setting everything individually.

Source: https://www.nopcommerce.com/boards/t/71191/adding-some-b2b-and-b2c-features-to-nopcommerce-to-make-it-more-comprehensive.aspx#244918

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
