### ISSUE TITLE
Retargeting.biz Plugin [Save Order Event is not triggered] nopCommerce 3.90

### ISSUE THREAD

**Issue by adiprisacariu** [nopSolutions/nopCommerce#4060]
nopCommerce version: 3.90

Steps to reproduce the problem: 
Retargeting team: "all functions are implmeneted on every page , the save order event is not triggered. ask them to talk to nopcommerce , they made the plugin and the implementation”

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/retargeting-plugin-for-nopcommerce/issues/1
