### ISSUE TITLE
Datatable - Read doesn't work, if no form is present on the page

### ISSUE THREAD

**Issue by LucStr** [nopSolutions/nopCommerce#4062]
nopCommerce version: 4.20

Description: When no form is present on a page the datatable is unable to send any ajax calls. 

Explanation:
The JavaScript function addAntiForgeryToken: 
```
function addAntiForgeryToken(data) {
    //if the object is undefined, create a new one.
    if (!data) {
        data = {};
    }
    //add token
    var tokenInput = $('input[name=__RequestVerificationToken]');
    if (tokenInput.length) {
        data.__RequestVerificationToken = tokenInput.val();
    }
    return data;
}
```

It will check for an input with name __RequestVerificationToken. 

I couldn't find the place where this input should be generated. Therefore I checked on other pages, where they were implemented. The forms, that are containing such an input field also don't have anything specified. 

So I tried to put an anti forgery token on my page next to the grid:

```
<nop-antiforgery-token/>
```
And it worked. I think the input field should also be generated within the Table.cshtml or just in general on every page, or even better, if it were within the global Javascript scope, where it could be accessed by the addAntiForgeryToken function.

**Comment by DmitriyKulagin** [comment]
Closed #4062
