### ISSUE TITLE
Make Firstname and Lastname toggleable like all other customer fields

### ISSUE THREAD

**Issue by rodolphito** [nopSolutions/nopCommerce#4064]
Having Firstname and Lastname fields is currently forced onto all nopCommerce users. I would like to disable them and use the user's Username instead. I can already tell nopCommerce to use the Username only, but I can't stop collecting the Firstname and Lastname.

Collecting these is a hassle, and involves more legalese due to GDPR. It would be easier to just turn them off.

I can PR this, guidelines say to discuss in issue first though.

**Comment by rodolphito** [comment]
I have implemented this on my site and it is in testing.

**Comment by RomanovM** [comment]
@rodolphito 
> I can PR this, guidelines say to discuss in issue first though.

We will be grateful. Thanks.
