### ISSUE TITLE
Provide filter option for shipment is not delivered

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#4065]
nopCommerce version: 4.10

Steps to reproduce the problem: Go to this page Admin/Order/ShipmentList
There is option given to mark selected shipment as delivered but there is no option available to filter shipments which aren't delivered.

Can you please check and add this option ?

**Comment by jigarsangoi** [comment]
If you guys want, I can contribute this change

**Comment by RomanovM** [comment]
@jigarsangoi You are more than welcome to contribute, thanks.

**Comment by jigarsangoi** [comment]
@RomanovM I generated pull request

**Comment by DmitriyKulagin** [comment]
Closed #4065
