### ISSUE TITLE
Add a message token for discounted amount

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4068]
The discount is already displayed in the product table on using `%Order.Product(s)%` message token. 
It can also be added as a separate token to use in email templates.

Source: https://www.nopcommerce.com/boards/t/71540/show-discount-code-or-discount-amount-in-email.aspx

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box (leaving for custozamition)
