### ISSUE TITLE
Amazon Product Importer (available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#407]
I was asked by one of the community members here about the code I used to query Amazon's product base for product information. I finally got around to creating it in a Web Control. It is really easy to install and use. I have zipped up the source code and made it available for download. 

The control works with keywords, ISBN's, and other product numbering schemes. 

The information retrieved from an Amazon query are: 
Name of the item. 
Picture of the item. 
Short and long descriptions. 
Price information such as list price, lowest used price, and lowest new price. 
Dimensions of the item such as height, length, weight, and width. 

To download and try the "Amazon Product Importer", go to http://www.deccks.net/nopcommerce/amazon-product-importer.html 

Information on how to install the Web Control can be found at the above link. 

If anyone decides to try it, let me know what you think and what could make it better. Thanks. 

Source: http://www.nopcommerce.com/boards/t/6846/amazon-product-importer.aspx 

also a third-party plugin is availabe

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
