### ISSUE TITLE
sitemap.xml not working correctly

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4072]
nopCommerce version: 
developper branch
https://github.com/nopSolutions/nopCommerce/commit/fb5f1576e5f9addd315cfaaa3799a4b4780e71c0

Steps to reproduce the problem: 
https://hoodarcheryshop.com/sitemap.xml
My sitemap seem like text not xml format, its not work.

**Comment by RomanovM** [comment]
There are no issues with your sitemap, you can test it with any sitemap checker.
