### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by talha0324** [nopSolutions/nopCommerce#4077]
**nopCommerce version:**  
           
Release 4.20

**Steps to reproduce the problem:** 

Just download the release source code (version 4.20) and run it in debug mode or publish it on IIS.

**Details:**

I have downloaded Release 4.20 source. After running it in debug mode or even release mode, the loading time of each new page takes from 30 secs to 1 and a half minute roughly. Simply each navigation is slow. I have even deployed it to IIS locally. Things are more slower on IIS.
After first loading, the website goes on quick loading with each load is very quick **but if you let the IIS go idle and don't open website for like 5mins or so, it again takes a minute to get intial loadings.**
I'm concerned if this will keep happening in production. So if there's no traffic on my website. the initial customer will have to face these delayed loadings.

**Comment by korifeich** [comment]
@talha0324 HI!

You can try to use Application Initialization module for IIS to keep your website up even if no requests are present:

https://docs.microsoft.com/en-us/iis/configuration/system.webserver/applicationinitialization/

**Comment by talha0324** [comment]
So I now published the code using `dotnet` and also ran it using `dotnet nop.web.dll` but It's still the same. I'm attaching a file of a profiler output just so you can let me know where things are going wrong. I see major time consumption on opening/closing database connection and major time in request,. otherwise the sql queries are very fast.
[Catalog_Category (642.7 ms) - Profiling Results.pdf](https://github.com/nopSolutions/nopCommerce/files/3747714/Catalog_Category.642.7.ms.-.Profiling.Results.pdf)
Profiler details: (This page is a category page with 3 sub categories)

If anyone can please give me some heads up so I can release this, as I'm already very late for production release

**Comment by AndreiMaz** [comment]
It works fine by default . Please test it at https://demo.nopcommerce.com/

Also try the upcoming version 4.30 where we moved away from EF
