### ISSUE TITLE
CSS problem appears for RTL languages

### ISSUE THREAD

**Issue by Arashz22** [nopSolutions/nopCommerce#4081]
nopCommerce version: 4.20

Steps to reproduce the problem: 
As you know these languages are right to left :

- Arabic
- Aramaic
- Azeri
- Dhivehi/Maldivian
- Hebrew
- Kurdish (Sorani)
- Persian/Farsi
- Urdu

After Updating chrome to 76 or maybe 77 the admin page became messy for RTL languages.
Thus for opera browser and other Chromium based browsers it has happened.
Fortunately Firefox and Edge show correct.
please look at this image (chrome 77.x) :
![persian](https://user-images.githubusercontent.com/10775073/64710974-258f2380-d4ce-11e9-95d6-52077f82f238.jpg)

Or if you are not familiar with RTL languages and it is not visually comprehensive for you, I've added English as a RTL language, lets see:
![English](https://user-images.githubusercontent.com/10775073/64711175-74d55400-d4ce-11e9-979d-9015308e6a75.jpg)

The correct should be something like this, like which is showing in Firefox:
![fire](https://user-images.githubusercontent.com/10775073/64711345-af3ef100-d4ce-11e9-9ee0-37d119ff6608.jpg)

Or in chrome 75.x or below:
![chrome 75](https://user-images.githubusercontent.com/10775073/64711417-cbdb2900-d4ce-11e9-836b-7625f85a86a4.jpg)

**Comment by ertebatgharineh** [comment]
Hi Arash,
as i checked the latest versions and i already have this problem, i find that this is a problem with some changes in latest chrome update which is about to blocking something in jquery ui, by the way i changed the jquery ui version and it resolved in one of my projects but i didn't get the same value in other project.

**Comment by DmitriyKulagin** [comment]
Closed #4081
