### ISSUE TITLE
The discount requirements entity deleted event doesn't fire when the discount is deleted

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4083]
As a continuation of the https://github.com/nopSolutions/nopCommerce/issues/1859.
See comment https://github.com/nopSolutions/nopCommerce/commit/fdafb77ab4e5b41fe5689223a4fdc6e8c0415b94#commitcomment-35014637

**Comment by skoshelev** [comment]
Closed #4083
