### ISSUE TITLE
[SUGGESTION] Releases in .zip or tar.gz

### ISSUE THREAD

**Issue by mmgil** [nopSolutions/nopCommerce#4084]
Hi All,

In releases the download is on .RAR and this is very bad for implementations and Automations, because we need a third party software to unpack.

I am suggesting to keep the releases in .ZIP, because in this way it would be possible to unpack using native Windows tools (Expand-Archive).

Or tar.gz, because tar.gz is possible to unpack both on Linux and Windows 2019 native.

**Comment by RomanovM** [comment]
@mmgil Thanks for this suggestion, we will consider it. I close this issue, since it's not related with the source code.

**Comment by jonnyaeast** [comment]
I would like to second this, I think gz or zip would make a lot more sense as they are well supported in CI & build tools such as Gulp.

I am trying to do the same thing as @mmgil and have found that RAR has very little support outside of using winrar on windows.
