### ISSUE TITLE
attributes (such as asp-disabled) does not work in NopEditorTagHelper  (Nop.Web.framework)

### ISSUE THREAD

**Issue by Reza-Piri** [nopSolutions/nopCommerce#4085]
nopCommerce version: 4.20

Steps to reproduce the problem: 

attributes (such as asp-disabled) does not work in NopEditorTagHelper  (Nop.Web.framework)
for example you can check "AccessToken" field in Configure.cshtml belong to Nop.Plugin.Payments.Square

thanks

**Comment by RomanovM** [comment]
@Reza-Piri Please clarify what do you mean. 
All default `asp-` attributes work in the nop-editor, including for "AccessToken" on the Square plugin configuration page. You can see it on the [demo](https://admin-demo.nopcommerce.com/Admin/PaymentSquare/Configure).
