### ISSUE TITLE
Uploading and setting nopadvance Emporio- v4.0 theme results in error

### ISSUE THREAD

**Issue by Workaholic01** [nopSolutions/nopCommerce#4088]
![nop-issue](https://user-images.githubusercontent.com/29353695/65023360-171c8e00-d94c-11e9-9576-a3c5b97e626b.PNG)
nopCommerce version:  Latest

Steps to reproduce the problem: 
Download theme  from L 
1- https://nopadvance.com/emporio-free-nopcommerce-theme?utm_source=marketplace&utm_medium=product&utm_campaign=theme
2- Upload it in Configurations  -> Local Themes -> Upload
3- Set newly added theme as default theme in configuration-> settings -> Generalsettings

--Error :

[Generated Code
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

The type or namespace name 'HomePageNewsItemsModel' could not be found (are you missing a using directive or an assembly reference?)
+
    public class Themes_Emporio_Views_Shared_Components_HomepageNews_Default : Nop.Web.Framework.Mvc.Razor.NopRazorPage<HomePageNewsItemsModel>
The type or namespace name 'HomePageNewsItemsModel' could not be found (are you missing a using directive or an assembly reference?)
+
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<HomePageNewsItemsModel> Html { get; private set; }](url)

**Comment by rajupaladiya** [comment]
@Workaholic01 - You can ask to nopAdvance team via them support email, they can help you on this.
This is a theme related issue, so you have to contact vendor.
