### ISSUE TITLE
Digital products. Licensing (license key generation)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#409]
See http://www.nopcommerce.com/boards/t/35855/feature-request-natively-support-license-key-generator.aspx

related work item - https://github.com/nopSolutions/nopCommerce/issues/2020

**Comment by iammourya** [comment]
This should also have a way to upload license key files which are generated outside nopcommerce. Once the purchase is made, store owner or vendor can upload the license key. A mail alert with license key attached should be sent too. 

These features would make this unbeatable.

**Comment by AndreiMaz** [comment]
split to two work items - https://github.com/nopSolutions/nopCommerce/issues/2020

**Comment by AndrewBragdon** [comment]
Any update on this one?  Would be really valuable

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
