### ISSUE TITLE
Incorrect map placement for pickup point during checkout when store language is set to German

### ISSUE THREAD

**Issue by NormanMann** [nopSolutions/nopCommerce#4091]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
-Switch store language to German
-Add item to cart
-Goto Checkout

On pickup address the map will be displayed with incorrect coordinates. This might be caused due to the formatting the values with , (comma) instead of . (point)

As a quick fix to illustrate the problem the followings lines can be inserted in OpcShippingAddress.cshtml in line 106 

              var latitude = point.Latitude.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);
                                            var longitude = point.Longitude.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

then use the newly created variables when calling the google maps api:

var marker = new google.maps.Marker({
	map: googleMap,
	title: "@point.Name",
	//position: new google.maps.LatLng(@point.Latitude, @point.Longitude),
	position: new google.maps.LatLng(@latitude, @longitude),
	icon: "https://maps.google.com/mapfiles/ms/icons/blue-dot.png"
});

**Comment by DmitriyKulagin** [comment]
Closed #4091
