### ISSUE TITLE
Affiliate tracking panel for affiliates

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4093]
Needs ability to check affiliate link statistic. Now Webmasters cant see their affiliate  link tracking info.

source: https://www.nopcommerce.com/boards/t/24320/nopcommerce-affiliate-tracking-panel-for-affiliates.aspx

**Comment by tigran-avdalyan** [comment]
Maybe add ability to register  as Partner(like register as Vendor).

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/31
