### ISSUE TITLE
SQL query inside Nopcommerce Admin Area

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4097]
Ability to write SQL query inside Nopcommerce Admin Area.

For example integrate https://github.com/sqlkata/querybuilder

**Comment by RomanovM** [comment]
Thanks. We don't plan to implement it. There is no reason to add this feature in nopCommerce.

**Comment by karanvirdi95** [comment]
hi, can somebody tell me i checkout the Nopcommerece from git but i didnt get the Nop.Admin project i have checkout the latest version, can somebody help in this

**Comment by glhays** [comment]
Just to help you here, but your question is not an issue for using the git repository. Use the Forum on the nop website.
The admin is located in the Nop.Web folder in the Areas folder.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
