### ISSUE TITLE
Make the creation of "DataTablesModel" available for Override or Manipulating

### ISSUE THREAD

**Issue by brakim** [nopSolutions/nopCommerce#4102]
For example, to override the admin order list we now have to create a custom view engine and duplicate the views on order to add a custom column to the table.

Creating the DataTablesModel inside the view feels like the wrong approach. The logic should maybe be moved to a Factory instead and also publish the ModelPreparedEvent.

Or is there another way of extending the DataTable that i have not thought about?

**Comment by brakim** [comment]
The easy way, if you add this line after the model is created

![image](https://user-images.githubusercontent.com/894222/65917659-2bdf3400-e3d8-11e9-90b4-a80f0a1ff381.png)

You can create a override on OrderModelFactory

![image](https://user-images.githubusercontent.com/894222/65917790-7a8cce00-e3d8-11e9-87f8-3bf91b1c13e1.png)

And then consume the event

![image](https://user-images.githubusercontent.com/894222/65917816-8d9f9e00-e3d8-11e9-9482-783ebbeff7ac.png)

and voila 

![image](https://user-images.githubusercontent.com/894222/65917847-a27c3180-e3d8-11e9-9e8c-3757c6f39db4.png)

**Comment by brakim** [comment]
@DmitriyKulagin i created a PR #4107

**Comment by AndreiMaz** [comment]
thanks. but after some consideration we've decided not to implement this functionality
