### ISSUE TITLE
Support Afterpay (With Afterpay's blessing)

### ISSUE THREAD

**Issue by goldfish1974** [nopSolutions/nopCommerce#4103]
nopCommerce version:  ALL
Steps to reproduce the problem:  N/A

Afterpay flat our refuse to support the 3rd Party AfterPay plugin for NopCommerce.

Please work with AfterPay directly to get supported. This is a show stopper for those who wish to implement AfterPay. Yes, there is an API, but they won't grant a merchant account to get setup unless it's one of their supported platforms (e.g. Shopify, etc.)

We've been trying for 2 years with no result and I don't need their technical support at all.

Please look into this urgently as the spread of AfterPay is going to make NopCommerce less attractive than other eCommerce platforms.

**Comment by RomanovM** [comment]
@goldfish1974  Thanks for the information. We'll consider the potential development of this plugin.
For now we are closing this issue, if there are any further activities, we'll reopen it.

**Comment by jonquickqsense** [comment]
I was just starting on feasibility of developing my own plugin for UK Afterpay.  Just this minute, I receive an email saying they can't help me at this time. I wonder if its because I selected 'Other' > 'nopcommerce' for my platform.  

I am in agreement with Goldfish1974   -- 2 of our uk competitors already have afterpay as a funding option on their stores and many uk retailers are adopting.  

Could someone on the Nop Team start some  dialog with AfterPay/Clearpay to open some doors?

**Comment by goldfish1974** [comment]
> I was just starting on feasibility of developing my own plugin for UK Afterpay. Just this minute, I receive an email saying they can't help me at this time. I wonder if its because I selected 'Other' > 'nopcommerce' for my platform.
> 
> I am in agreement with Goldfish1974 -- 2 of our uk competitors already have afterpay as a funding option on their stores and many uk retailers are adopting.
> 
> Could someone on the Nop Team start some dialog with AfterPay/Clearpay to open some doors?

Here in Australia, AfterPay is rapidly converting Lay-By/Lay-Away into Buy-Now-Pay-Later on a grand scale. It is gobbling up other payment methods (including taking market share from Credit Cards).

In Australia, yes, we are very quick with the uptake in technology but the growth of AfterPay is truly amazing. It has reached the point where there are huge chunks of customers that only buy produces using AfterPay/ZipPay/etc.) type purchasing.

From the correspondence via email with AfterPay, over nearly 2 years and who are litterally 3 blocks away my work address, I get the impression that if it isn't an approved Shopping Cart, then they don't have time for it.

One of my customers is clearly loosing business becuase of not supporting AfterPay and I am now looking at migrating their cart to wooCommerce. wooCommerce is also stand alone unlike Shopify which is hosted.

Very Very soon, AfterPay will be so mainstream (as in, same as Credit Cards level mainstream) that not supporting it will mean death to the platform. I'd say, in the last year looking at shopping centers, last year only a few had AfterPay, now only 1 year later there are only a few that don't seem to have AfterPay. The rest of the world will no doubt follow this growth.

I think the above response is "park it". It's possibly already too late for nopCommerce, which is a shame becuase it's a great platform that you can customise.

My advice, if it doesn't currently support AfterPay, then skip over it and choose something else. Your customers will be thankful for it.

NOP: Just go and google the relevant info on the growth of AfterPay in the last 2 years. NOP can either be part of it or go by the way side. Give it the priority that it needs because it's a deal breaker here in Australia and it will be a Deal Breaker in the US, EU and UK very soon too.
