### ISSUE TITLE
Using AssemblyLoadContext (.NET Core 3.0) to Implement  plugin hot loading

### ISSUE THREAD

**Issue by ghd258** [nopSolutions/nopCommerce#4111]
Using core 3.0 AssemblyLoadContext to Implement Plug-in Hot Loading

**Comment by tanyo520** [comment]
Is this function supported?

**Comment by skoshelev** [comment]
Hi @tanyo520. Not yet. We decided to put this issue on hold because we need to load all plugins on startup, it is related to the configuration of DI and possibility replace all our services from the plugins.
