### ISSUE TITLE
NopEditorTagHelper and problem with not required int type fields 

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#4114]
nopCommerce version: 4.20

NopEditorTagHelper do not create a not required int type fields, them always mark as required 

Details in the PS tiket #15077

**Comment by rupe120** [comment]
As a work around the zero value can be used as a null value in the view model field, and the following `ForMember()` call can be added to the AutoMapper configuration for the effected model

    CreateMap<OrderLimitRuleModel, OrderLimitRule>()
        .IgnoreAllPropertiesWithAnInaccessibleSetter()
        .IgnoreAllSourcePropertiesWithAnInaccessibleSetter()
        .ForMember(domainModel => domainModel.PlanId, config => config.MapFrom(viewModel => viewModel.PlanId == 0 ? (int?)null : viewModel.PlanId));

**Comment by DmitriyKulagin** [comment]
There is an alternative way that is more suitable in this situation. Just add the `[UIHint("Int32Nullable")]` attribute to the desired property of the view model.
