### ISSUE TITLE
Title and Encoding for umlaut

### ISSUE THREAD

**Issue by Leftyx** [nopSolutions/nopCommerce#4115]
nopCommerce version: 4.10 - 4.20

Steps to reproduce the problem: 

Change the **Default page title** in SEO section for General Settings using umlaut
IE: 

> Füße

Page title is rendered like this:

`<title>F&#xFC;&#xDF;e</title>`

Same goes for all the META tags.
I think this could cause problems with search engines.

Shouldn't we strip HTML/Javascript from these fields and render as it is ?

**Comment by RomanovM** [comment]
See also Premium Support Ticket #13961

**Comment by Leftyx** [comment]
Hi @RomanovM,
 
we are the premium support ticket ? could you please include a link?
Thank

**Comment by RomanovM** [comment]
Hi @Leftyx 
This information (about ticket number) is for someone from our team assigned this issue. A similar question has already been described in our premium support service and ways to resolve it have been proposed.

**Comment by Leftyx** [comment]
Thanks @RomanovM

**Comment by AndreiMaz** [comment]
@Leftyx It's encoded according to HTML specification.  Just test it at https://seositecheckup.com/tools/meta-title-test - you'll see - it works fine
