### ISSUE TITLE
Show date for pre-order availability

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#412]
I would like to use the function pre-order, not just to let the customer order something beforehand, but also let the customer know when the product is available for shipping. 

I would like to show the date from the product (when the button is being changed from pre-order to order) on the website and possibly also at the order notification (my account, emails). 

Source: http://www.nopcommerce.com/boards/t/38212/feature-request-show-date-for-pre-order-availability.aspx

Make it configurable (move to catalog settings). Whether to display this date in public store

**Comment by skoshelev** [comment]
Closed #412
