### ISSUE TITLE
"Compare Products" bug in IE11

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4124]
nopCommerce version: 4.20

The "compare products" functionality is currently malfunctioning in Internet Explorer 11 (and perhaps in other IE versions too).

There is a bug in the public.common.js file that is triggered when any "compare products" button is pressed.
It seems the problem is related to the notification message that the browser is appending to the page after a product is added to the compare list. The result is that the message is never added and the page is left in a perpetual loading state.

Source: https://www.nopcommerce.com/boards/t/73311/compare-products-bug-in-ie11.aspx

Also see https://www.nopcommerce.com/boards/topic/74728/nopcommerce-42-does-not-display-the-product-has-been-added-to-your-shopping-cart-in-ie-110 

And pull request: https://github.com/nopSolutions/nopCommerce/pull/4163

**Comment by DmitriyKulagin** [comment]
Not reproduced for EDGE

**Comment by DmitriyKulagin** [comment]
Duplicate #3988
