### ISSUE TITLE
Pre order, pay later (a store owner has to approve an order before payment by a customer)

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4126]
Ability to pre order, when store admin confirm the order, customer can pay.

**Comment by TheFirstWhiteDream** [comment]
Call For Price？

**Comment by compito** [comment]
I'd need a version of this when selling stuff where we don't know the final price yet. For example customer want to buy 500 grams of something, so customer preorders that, but final weight of product is s480g, or 520g. So I would finalize order with exact weight before delivery...
Is it doable in same way?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement
