### ISSUE TITLE
errors either "offers", "review", or "aggregateRating" should be specified from google console search 

### ISSUE THREAD

**Issue by xcellenceit** [nopSolutions/nopCommerce#4129]
nopCommerce version:  4.2

Steps to reproduce the problem: Google Webmaster / Search Console Error

errors reporting that either "offers", "review", or "aggregateRating" should be specified from google console search. 

May be we need to fix this in schema markup of view pages

**Comment by DmitriyKulagin** [comment]
Closed #4129
