### ISSUE TITLE
Facebook Oauth not working

### ISSUE THREAD

**Issue by kamblerupesh9** [nopSolutions/nopCommerce#4130]
Hello,
I am using nopcommerce 3.9

I am facing below issue in Facebook oauth 

1.	I have setup fb APP
2.	On click ( sign in with Facebook) , it ask me to login to facebook
3.	Respond to this (after successful login) :  got URL similar to : https://localhost:15536/plugins/externalauthFacebook/logincallback/?code=AQAO81pLQceu6PZst79-n1_x8NytsJo9Zah8Vz498SE0giKsiE331ChY9ODVVA1sJ6ZU1j0iKqWBYYBZ_vpZtxhfk0zN273X4ZWUwnJZuMtECsxY6J649r1m9cuR-q_ujfvr3n4IWYcO9Bi9RfNAoFH6C-Q-D_yrI4_QpndkxsGqZvgovTLaYaB2f3bd7y-TELfg-7l0tpKSKOu8_vlpHMADWMjDygYGi5m452eLzNoplNrvJRlbWbMQRNDKg2VL_xjVCf_0nXAsSqqiMj2x96yAeK9iys0em-m8eK97pLOmBsUq2Jp25Vw9vZa1xk5IYVaBLlDJq_6A9HzHtwjJLpbR#_=_

**After this nothing happen .**

My **code never reach** :  function **_LoginCallback_** from ExternalAuthFacebookController.cs

Can you please guide me , why **_LoginCallback_** is not reached even after successful login from Facebook.
Thanks.

**Comment by AHComp** [comment]
What's the result in the browser ? ErrorMassage ?

**Comment by skoshelev** [comment]
Can't reproduce on 4.30

Closed #4130
