### ISSUE TITLE
Phone number verification during registration

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#4131]
nopCommerce version: 
4.2
Steps to reproduce the problem: 
God knows why do nopCommerce Ignores very basic and MUST feature of 
Phone number verification during registration (configurable) #2228
Only reason for many like me to move to other e-commerce.
Can nopCommerce mention/list reasons not to include this feature/plugin

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/2228
