### ISSUE TITLE
Top menu navigation doesn't respect the DisplayOrder property

### ISSUE THREAD

**Issue by bentolila** [nopSolutions/nopCommerce#4134]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Create a set of sub categories with unique 'DisplayOrder' values.
2. When displaying the top level category, all sub categories are display properly with the correct order ( respecting the 'DisplayOrder' property )
3. However, in the top menu navigation, this order is not respected and not ordered by the 'DisplayOrder'

Proposed Fix:
CatalogModelFactory.cs - Line :681
var categories = allCategories.Where(c => c.ParentCategoryId == rootCategoryId)**.OrderBy(c => c.DisplayOrder)**.ToList();

By adding the OrderBy in the above line will correct the top menu navigation.

Please let me know if you would like me to create a pull request :)
Thanks!

**Comment by RomanovM** [comment]
@bentolila 
> Please let me know if you would like me to create a pull request :)
You are more than welcome. Thanks.
