### ISSUE TITLE
Bundling minification on linux

### ISSUE THREAD

**Issue by JadynWong** [nopSolutions/nopCommerce#4135]
nopCommerce version: nopcommerceteam/nopcommerce:4.2

Steps to reproduce the problem: 
Enable docker 'JavaScript bundling and minification' and 'CSS bundling and minification'.

The Bundling minification feature not support linux.
![image](https://user-images.githubusercontent.com/13699353/67917673-b16f2300-fbd4-11e9-880e-4354bfba4460.png)
The bundles file not create at '/app/wwwroot/bundles', create at root directory.The bundle file is empty.
![image](https://user-images.githubusercontent.com/13699353/67917805-26daf380-fbd5-11e9-9ad4-f639f142e56d.png)

**Comment by skoshelev** [comment]
Hi @JadynWong. Thank you for your help.

Closed #4135
