### ISSUE TITLE
Suggestion: Save Transaction Fees

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4140]
nopCommerce version:  4.20

Steps to reproduce the problem: 
Store the "Processing Fee" of a transaction in the Orders Table.

**Comment by RomanovM** [comment]
@Ochapparel Could you please clarify what is "Processing Fee"? There are already `PaymentMethodAdditionalFee` [fields ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Orders/Order.cs#L133)in the order entity.

**Comment by Ochapparel** [comment]
I’m saying store the fees that payment methods charge. Example

PayPal’s fees: 2.9% plus $0.30 per transaction
Square’s fees: 2.9% + 30¢ per transaction

This info is passed back from the api so it’s easily captured and storable.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
