### ISSUE TITLE
Suggestion: Update PayPal Plugin Text

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4141]
nopCommerce version: 4.20

Steps to reproduce the problem: 
I was trying to figure out how to tie a Manual Invoice I created on PayPal to an Order that wasn't fully paid. After digging through the Code I noticed the value "Custom" is used to check if there is an order number related to the IPN call from paypal.

Suggestion: In the PayPal plug in, state that "Adding the open Order Number from NopCommerce to the Invoice "Memo" field at PayPal will link the payment". Something along those lines.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
