### ISSUE TITLE
Improper encoding on password reset approval email links 

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4142]
nopCommerce version: 4.2

Steps to reproduce the problem: 
Create an account with valid email but special chars eg + or / (according to many sources these are valid emails) a feature of gmail to label things I think... anyway the account is created correctly. But the user cannot click the link in the email correctly because the plus becomes a space...

The customer must replace these characters with the encoded versions manually to get the links to work eg %2b for plus

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/3946
