### ISSUE TITLE
Should allow customizable fields in exports

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4143]
nopCommerce version: 4.2 

Steps to reproduce the problem: 
Export to excel doesn’t include several key fields that xml does and I understand xml has more control over structured satay than the flat(ish) format of excel it’s unreasonable not to include txnID and several other fields directly from the order table that would not impact performance... 

It should at least be somewhat able to provide a bunch of checkboxes for order data to include fields... like products export.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
