### ISSUE TITLE
Xml output is bad because of stringbuilder

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4144]
nopCommerce version: 4.2

Steps to reproduce the problem: 
Export to xml requests UTF8 but encoding is always 16 this will not be able to be parsed by ‘stupid’ programs like msexcel. 

Should either use stream or maybe use writestartdocument with standalone option?

You can easily open the xml file on not pad and remove the offending tag but for non techs this is bewildering

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/3513
