### ISSUE TITLE
no retry on timeout of most "httpclient" operations

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4145]
nopCommerce version: 4.2

Steps to reproduce the problem: 
I'm not so sure about this and if its (a) reproduceable that easily and (b) a problem that can be fixed "globally" or if it needs to be developed on a case/by case thing where httpclient is being used...

a) there are known issues with httpclient being used directly rather than httpclienthandlers
b) for example in the PayPalStandard plugin in places like "IPN verification" and "getting PDT detail" the code will do something like this:

            var response = await _httpClient.PostAsync(url, requestContent);

if this times out, either beucase the other service is slow, OR (more common) the httpclient has exhausted its resources  then there is no way to retry  this operation, or recover from this situation.

This leaves you (especially the way payment plugins are built) often in the situation where your "process is broken" and you cannot recover from this through any system provided mechanism and must restort (in most cases, and depending on your needs) to a direct to DB fix - eg: insert the "AuthorizationTransactionId" (which really should be editable (and auditable) via the AdminUI in my opinion.

**Comment by awe-source** [comment]
Failing this kind of thing which may be too close to the metal  then you need to adopt a better pattern for remote requests because there is a lot of code that assumes no failures with these requests and just have if response is success then ok else response is fail , but if the REQUEST fails then it dies completely leaving payments or operation s in limbo states

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
