### ISSUE TITLE
Plugins: add/delete locale resources

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#4149]
nopCommerce version: 4.20

Hello, finaly i'v started to update to 4.20.
The question regarding install/uninstall methods in plugins:
Why we add localization strings to db using _localizationService.AddOrUpdatePluginLocaleResource one by one (It's used for each string).
I think its better to implement a methods to add them in one request and also delete them in one request.
For deleting its better to also have function to delete all localization strings that "StartsWith".

**Comment by RomanovM** [comment]
Thanks. Moved to https://github.com/nopSolutions/nopCommerce/issues/3528
