### ISSUE TITLE
Referenced project files are copied to plugin folder

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#4150]
nopCommerce version: 4.20

In all csproj files of plugins there should be:
```
    <ProjectReference Include="..\..\Presentation\...REFERENCED.csproj">
      <Private>false</Private>
    </ProjectReference>
```

It is "Copy Local" set to false for referenced project.

Now it is not set to false everywhere. This causes plugins, that reference Nop.Web to get a copy of "Plugins" folder inside plugin folder and as result - exception about trying to load plugins with same names (because many copies exist).

**Comment by TheFirstWhiteDream** [comment]
Please use vs2017,because vs2019 has this problem.

**Comment by ArturAlekseev** [comment]
It's easier to change project files than to reinstall to older VS version.

**Comment by DmitriyKulagin** [comment]
This issue has already been fixed. You can see the details in task #4079.
