### ISSUE TITLE
PayPal IPN Order not Updating

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4152]
nopCommerce version: 4.20

Steps to reproduce the problem: 
1) Have a person check out with paypal but not complete the order on PayPal side. The order will be in Pending status on NopCommerce.
2) Create an invoice on PayPal 
3) Put the NopCommerce invoice number in the Memo section of the invoice: This field comes across in the IPN as custom
4) Customer pays the invoice
5) Error in Logs:
    `PayPal IPN. Order is not found`
6) In the Error details it has the order number in the custom field:
    `custom: 2009`

When I look at the PayPal plugin in Nop Commerce it uses this field to find the order, but it appears to not work:

File = namespace Nop.Plugin.Payments.PayPalStandard.Controllers - PaymentPayPalStandardController.cs
Line = 561

values.TryGetValue("custom", out var orderNumber);
ProcessPayment(orderNumber, ipnInfo, newPaymentStatus, mcGross, txnId);
                    break;

Let me know if you need any screenshots.

**Comment by Ochapparel** [comment]
Just wondering if instead of getOrderByGuid should you just do getOrderById?

**Comment by Ochapparel** [comment]
I just made it 

var order = _orderService.GetOrderById(intOrderNumber);

and converted the parameter "string orderNumber" into an it. Worked perfectly.

**Comment by RomanovM** [comment]
@Ochapparel But why should we change the method of getting an order to by `Id`, we pass exactly the order `Guid` in [requests](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Payments.PayPalStandard/PayPalStandardPaymentProcessor.cs#L166).

**Comment by Ochapparel** [comment]
From what I see in the code you use the “Custom” field to get the guid. The custom field is supposed to be the order id. When I put the order id of 2009 in the Memo Field it does not update the “order” to paid because it doesn’t find the order. So I changed the code to getOrderByID and it found the order. I am not sure why converting the orderId to a guid then using that guid to get the order does not work. Can you test?

**Comment by RomanovM** [comment]
@Ochapparel Well, so just use the order `Guid` instead of the `Id` for your manual orders and the plugin will work correctly.

**Comment by Ochapparel** [comment]
I would, however the code

 `protected virtual void ProcessPayment(string orderNumber, string ipnInfo, PaymentStatus newPaymentStatus, decimal mcGross, string transactionId)` 

in PaymentPayPalStandardController.cs has an argument of "orderNumber" and it does a "try" to `orderNumberGuid = new Guid(orderNumber);` then it uses that orderNumberGuid for the GetOrderByGuid. So if I pass through the GUID instead of the ORDERNUMBER it definitely won't work.
