### ISSUE TITLE
First giftcard has Id 0 and cannot be edited

### ISSUE THREAD

**Issue by jonquickqsense** [nopSolutions/nopCommerce#4153]
nopCommerce version: 4.2 

Steps to reproduce the problem:  Customer placed order for Gift Card on production store. It was the first gift card record. Could not edit gift card record in Admin area. Noted Gift Card record had been assigned Id 0

Workaround: Manually created a new Gift Card record in Db, auto assigned Id 1. Coped values from first record. Deleted record with Id 0. Can now edit (and activate) record in Admin area.

**Comment by holydk** [comment]
@jonquickqsense I could not reproduce your problem. I deployed the solution of version 4.2 with an empty database, added the product as a gift card and placed an order. The first gift card had id 1. Let me know, if you can tell more about your production environment and whether there was a modification of the core solution.

**Comment by jonquickqsense** [comment]
@holydk many thanks for investigating.
My environment is a source code build of 4.2, with database upgraded from 4.1.  WIndows Server 2016. SQL Express 2017

I do have a custom plugin which, for example,  has a personalised ProductModelFactory,  and overrides the default PrepareProductDetailsModel

I will try myself to recreate the problem on a dev environment and debug. It could well be something in our custom code tripping it up.

**Comment by AndreiMaz** [comment]
@jonquickqsense Have you had a chance to check it? Any news about the issue?

**Comment by holydk** [comment]
You can open new issue if you can reproduce the problem on the core solution.
Closed #4153
