### ISSUE TITLE
StateProvinces Caching Issue

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#4154]
nopCommerce version: 4.2

Steps to reproduce the problem: 

In StateProvinceService the method GetStateProvinceByAbbreviation() attempts to cache a state by abbreviation and country id however the format key NopDirectoryDefaults.StateProvincesByAbbreviationCacheKey only takes one formatted parameter although we pass 2 to string.Format() and the comment for StateProvincesByAbbreviationCacheKey would indicate we should be passing 2 parameters as well.

**Comment by holydk** [comment]
Closed #4154
