### ISSUE TITLE
default value of form in customer/order page should NOT be most expensive operation

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4155]
nopCommerce version: 4.20

Steps to reproduce the problem: 
submit the form with NO parameters on the \Admin\Customer\List or \Admin\Order\List page.
the default functionality for a POST to the list page is to include the "exportxml-all" value (probably because its top of the list of options?) which is LITTERALLY the most expensive operation that could possibly be triggered from this page(s).

Aside: While we're on the topic really should look at reviving the "i'll do this an let you know when I'm done" process rather than the wait for this (and in large datasets, this will timeout) to generate a dynamic xml(or excel) file.

**Comment by DmitriyKulagin** [comment]
Closed #4155
