### ISSUE TITLE
IE11 admin bug attribute OPTION dropdown empty

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#4156]
nopCommerce version: 4.2

Steps to reproduce the problem: 

 
1. Go to site and login as Admin

2. Open Catalog > Products and edit a product (any product)

3. Scroll down to the 'Specification attributes' section and select Add Attribute

4. Select any attribute that has an OPTION list loaded (or create one)

5. Select the Attribute Option drop-down

6. No values are shown...

**Comment by DmitriyKulagin** [comment]
Method Object.values() not support Internet Explorer

**Comment by DmitriyKulagin** [comment]
Not reproduced for EDGE

**Comment by DmitriyKulagin** [comment]
Related to #4618
