### ISSUE TITLE
Creating a TagHelper to embed Markdown into a View

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4157]
We could use the Markdown format in topics, or for example use some parts of the documentation to display them on the administration panel as help.

**Comment by AndreiMaz** [comment]
The second customer won't be able to complete the order concurrently with the first customer. He'll get a warning that

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality
