### ISSUE TITLE
RemotePost doesn't work properly

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4158]
nopCommerce version: 4.20
Source: https://www.nopcommerce.com/boards/t/73997/remotepost-doesnt-work-properly-42.aspx

Perhaps we should just remove this functionality.

**Comment by erkantdemir** [comment]
@RomanovM  @AndreiMaz 
Hi,

Do you have any suggestion?

**Comment by holydk** [comment]
Closed #4158
