### ISSUE TITLE
Allow Vendors to Setup their own Discounts

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#416]
It would be great when using the multi-vendor feature in nopCommerce if a store owner could set whether or not Vendors could create their own discounts. The discounts should only be applied to the creating vendors products thoug 

Source: http://www.nopcommerce.com/boards/t/35617/feature-request-allow-vendors-to-setup-their-own-discounts.aspx

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/107
