### ISSUE TITLE
Add more widgets to order summary

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#4162]
nopCommerce version: 4.2

Steps to reproduce the problem: 
I wanted to show how much money remaining for free shipment. I couldn't find a widget inside the OrderSummary/default.cshtml before the 
@await Component.InvokeAsync("OrderTotals", new { isEditable = Model.IsEditable }) line

It is good to have a widget there so we can add any warning message there

**Comment by VeronicaIsHere** [comment]
Closed #4162
