### ISSUE TITLE
Allow datasettings.json to be placed outside App_Data

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#4164]
nopCommerce version: 
Latest

Steps to reproduce the problem: 
dataSettings.json is stored in App_Data. I am using Octopus Deploy and want Octopus Deploy to set the connection string on deployment (deploy dataSettings.json and do variable substitution). But Octopus Deploy should not deploy the contents of App_Data.

Being able to move dataSettings.json into the Nop.Web root would resolve this problem. (We are using Azure AppAuthentication and Managed Identities for integrated security with Azure AD.)

I can issue a pull request to allow for configuration of the dataSettings.json location. What do you think of this?

* Add a DataSettingsLocation setting to appsettings.json
* Add DataSettingsLocation to NopConfig
* Delete NopDataSettingsDefaults which provides the static location of the dataSettings.json file.
* Change DataSettingsManager to be non-static and inject NopConfig
* Inject NopConfig into the consumers of DataSettingsManager (There are 5 consumers. 1 has nopConfig already. 2 are middleware that support DI. The remaining 2 also support DI.)

Any thoughts before I start work on this? Are there portential backward compatibility or plugin issues with removing NopDataSettingsDefaults? I'd also be interested in implementing a broader solution that supports other storage options like #4113 environment variables.

**Comment by justinjstark** [comment]
As a workaround, I've moved datasettings.json into the root and then added a deployment step to copy it into App_Data. This way I can not deploy App_Data and still deploy datasettings.json into App_Data after Octopus Deploy updates the variables in datasettings.json.

**Comment by sanju741** [comment]
I don't think it will be safe from the security perspective. Won't placing the dataSettings.json file on the root directory allow it to be downloaded directly through the HTTP request? Allowing the file with a connection string to be downloaded can be a major threat to the security of the web application.
The placement of dataSettings.json in the App_Data directory means it can't be downloaded directly through the browser and  HTTP requests which makes it a much safer option.

**Comment by justinjstark** [comment]
It is safe. In .NET Core MVC, files outside of wwwroot (a subdir of root) are not accessible by browser.

**Comment by hsb0307** [comment]
in  asp.net core,  can app restart  when you change appsettings.json?

**Comment by justinjstark** [comment]
Out of the box, the app does not restart when appsettings.json is changed. You have options for how appsettings.json changes propagate using `IOptions`, `IOptionsSnapshot`, and `IOptionsMonitor`.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/4113
