### ISSUE TITLE
Allow use of AppAuthentication with Azure SQL

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#4165]
nopCommerce version: 
Latest

Steps to reproduce the problem: 
To prevent storing passwords in the SQL connection string, we'd like to use AppAuthentication which provides integrated token-based security using Azure AD.
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi

I can implement this by doing the following:
* Add Microsoft.Azure.Services.AppAuthentication NuGet package to Nop.Data
* Add a flag to dataSettings.json: UseAzureAppAuthentication
* Run the following code to the NopObjectContext constructor if the flag is set

```c#
var conn = (System.Data.SqlClient.SqlConnection)Database.GetDbConnection();
 conn.AccessToken = (new AzureServiceTokenProvider()).GetAccessTokenAsync("https://database.windows.net/").GetAwaiter().GetResult();
```

Let me know your thoughts. If this is acceptable I will issue a pull request.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
