### ISSUE TITLE
Allow storing DataProtectionKeys in an Azure blob storage container

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#4166]
nopCommerce version: 
latest

Steps to reproduce the problem: 
Currently, data protection keys can only be stored on disk in App_Data or using Redis. .NET Core provides Microsoft.AspNetCore.DataProtection.AzureStorage which stores the key in Azure.
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.0&tabs=visual-studio#azure-storage

It can connect using a connection string or AppAuthentication. We should provide support for both. The data protection key should live in a private container separate from the media container.

I can work on implementing this if given the OK.

**Comment by skoshelev** [comment]
Hi @justinjstark. Thank you for your contribution.

Closed #4166.
