### ISSUE TITLE
编译时发现以下问题

### ISSUE THREAD

**Issue by xhp681** [nopSolutions/nopCommerce#4167]
Hello:
我下载最新版本后，在编调的过程中发现这个问题：
InvalidOperationException: Unable to resolve service for type 'Nop.Web.Infrastructure.Installation.IInstallationLocalizationService' while attempting to activate 'Nop.Web.Validators.Install.InstallValidator'.
=======================================
麻烦请指教应该如何解决这个问题呢？

**Comment by TheFirstWhiteDream** [comment]
把nop.web设为启动项
采用vs2017

**Comment by xhp681** [comment]
我用的是VS2019，还是不行呢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XuZhiYong"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 上午9:18
收件人: "nopSolutions/nopCommerce"<nopCommerce@noreply.github.com&gt;; 
抄送: "&amp;#8238;靓&amp;#8237;Rince"<527883283@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nopSolutions/nopCommerce] 编译时发现以下问题 (#4167)




把nop.web设为启动项
 采用vs2017

**Comment by xhp681** [comment]
现在又发现了新的问题
![image](https://user-images.githubusercontent.com/22016050/69704766-13b53800-112f-11ea-99f7-6cdbf73514d5.png)  这个到底是什么原因造成的呢，老是出现这种问题。

**Comment by RomanovM** [comment]
Could you please post such questions on [our forums](https://www.nopcommerce.com/boards)?
