### ISSUE TITLE
Vendor Attributes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#417]
It would be nice if a store owner was able to create attributes for a vendor much like they can for a product or customers. The vendor attributes would then be displayed on the vendor detail page in the public store (apply for vendor and edit vendor details, vendor details page) and admin area (add/edit a vendor page). 

This would allow for Multi-Vendor stores to be able to collect and display to the customers more information about the vendor without having to try and format it in the Description field that is currently available. 

Some different attributes that could be created would be Street, City, State, Zip, Country, Contact Number, Email Address, etc. 

Source: http://www.nopcommerce.com/boards/t/35062/feature-request-vendor-attributes.aspx

also see plugin - http://www.nopcommerce.com/p/1827/vendor-attributes-silhouettewebcom.aspx

---------------

Vendor already have address (https://github.com/nopSolutions/nopCommerce/issues/468). Let's allow a store owner to configure any custom attribute (similar to customer attributes)

Website, etc

Good example: http://www.notonthehighstreet.com/mariaallenjewellery

Source: http://www.nopcommerce.com/boards/t/28316/vendor-page.aspx#117992

**Comment by RomanovM** [comment]
Done https://github.com/nopSolutions/nopCommerce/commit/23df8f921d30735231d981e5f04de46030099838
