### ISSUE TITLE
SUGGESTION: Add Product Card to Campaign

### ISSUE THREAD

**Issue by mobsoftware** [nopSolutions/nopCommerce#4171]
Add the ability to insert product cards into a campaign. These product cards would consist of the product image, title, and price with a Buy Now button which could be edited. To add a product card, there would be a button that would allow a store owner to search for a product to add to the campaign.

Thanks!
Bruce

**Comment by RomanovM** [comment]
Thanks for the suggestion. We don't plan to implement it. We leave it for customization.
