### ISSUE TITLE
Plugin filter not working

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4172]
nopCommerce version: https://admin-demo.nopcommerce.com/

Steps to reproduce the problem: go to Configurations>>All plugins and themes
and filter by version, version filter not working.

**Comment by erjys** [comment]
Hello @RomanovM , I am new contributor so Please guide me to proceed further as i have already raised the PR "https://github.com/nopSolutions/nopCommerce/pull/4250". 

Please review or suggest me to add someone to review it.

@tigran-avdalyan

**Comment by DmitriyKulagin** [comment]
No changes required. Fixed.

**Comment by erjys** [comment]
> No changes required. Fixed.

You must have changed the service from where plugin list is being populated.
