### ISSUE TITLE
Customer enters price. Ensure that only numbers, comma and dot (no letters) can be entered

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4175]
nopCommerce version: 4.2

Steps to reproduce the problem: Activate "Customer enters price" function, go to product page and type in price Textbox letters , and add to cart.
but when you write digits, range validation is working.

**Comment by RomanovM** [comment]
@tigran-avdalyan I cannot reproduce this on our 4.20 [demo site](https://demo.nopcommerce.com/if-you-wait-donation).
Please clarify what you mean.

**Comment by tigran-avdalyan** [comment]
@RomanovM Set minimal price to "0", and then enter your price, but write letters, and add to cart.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
