### ISSUE TITLE
Error redirection Login - Register

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4181]
Nop Version: 4.30

Expected Behavior: From the homepage, if i click on 'Log In' on the top right, and i click on 'Register' on the top right, i should see the register page.

Actual behavior: From the homepage, if i click on 'Log In' on the top right, and i click on 'Register' on the top right, i see the error page.

Steps to reproduce the problem: On the homepage, click 'Login' on the top right, then click on 'Register' on the top right.

**Comment by bustiloo** [comment]
If a user is logged out of the site and click on 'Apply for vendor account', then click on either 'Register' of 'Log in', error/error

**Comment by alessandromontividiu03** [comment]
@DmitriyKulagin https://github.com/nopSolutions/nopCommerce/pull/4186
