### ISSUE TITLE
pay failed orders Can not delete

### ISSUE THREAD

**Issue by xxl-cc** [nopSolutions/nopCommerce#4182]
nopCommerce version: 
dev
Steps to reproduce the problem: 
when pay failed,the orders can not delete , add cancel pay button  on  orders page  suggest .

**Comment by RomanovM** [comment]
@xxl-cc Please clarify what is the issue with this and what is your suggestion? Also specify the steps to reproduce the problem, at now they look not clear.

**Comment by xxl-cc** [comment]
when i pay failed ，i can not delete this order .

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality
