### ISSUE TITLE
Order List - vendor(s) column

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#419]
can u please add a vendor column to the order list page 
each month we need to calculate vendors earnings, it will be very helpful to see the vendor name on the main table. 

the only other option is to search by vendor, however when there are many vendor it's impossible. 

the best thing will be running a report order by vendor 

Source: http://www.nopcommerce.com/boards/t/33428/order-list-vendor-column.aspx

**Comment by AndreiMaz** [comment]
already added filerting support
