### ISSUE TITLE
Add clean Topic page without Nopcommerce Template

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4192]
Now when we add Topic Page, by default page have header and footer.
Needs ability to add clean Topic Page with Custom HTML,CSS,JS Code.

**Comment by RomanovM** [comment]
You can add a topic with any content by using your own [topic template](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Topics/TopicTemplate.cs) for this.
