### ISSUE TITLE
Upgrade to AdminLTE 3

### ISSUE THREAD

**Issue by iyilm4z** [nopSolutions/nopCommerce#4193]
Based on bs4

[Here](https://github.com/ColorlibHQ/AdminLTE/releases) is the release and [here](https://adminlte.io/themes/dev/AdminLTE/index.html) is the demo.

**Comment by Lymperis79** [comment]
I did some work for the refactoring..... if you interested let me know how to share it

**Comment by DmitriyKulagin** [comment]
@iyilm4z You can share this via pull request.

**Comment by iyilm4z** [comment]
@DmitriyKulagin this issue was just a notification, i have no pr, i wish i would have one:)

**Comment by a-patel** [comment]
Just release new version [AdminLTE 3.0.2](https://github.com/ColorlibHQ/AdminLTE/releases)

**Comment by iyilm4z** [comment]
The repo [admin-lte-dotnet](https://github.com/iyilm4z/admin-lte-dotnet) made by me shows how to implement Admin LTE 3 with  dotnet core.

**Comment by DmitriyKulagin** [comment]
Closed #4193

**Comment by Lymperis79** [comment]
Dear Dimitri,
I am glad even for this small help in such nice project!

Best Regards
Antonis
