### ISSUE TITLE
Hide Payment and/or Shipping on checkout

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4194]
nopCommerce version: 4.2

Steps to reproduce the problem: 
Ability to Hide Payment and/or Shipping steps on checkout, and create order.
We have Products that don't need to online Payment or Shipping.
For example Real Estate for Sale.
Customer can create order, and reserve product.

**Comment by RomanovM** [comment]
@tigran-avdalyan You can use something like "Pay in store" payment plugin and free shipping for these purposes.

**Comment by tigran-avdalyan** [comment]
@RomanovM I disable all Payment methods, all shipping methods, and in checkout process i have 3 steps, 1 and 2 auto selected, and 3-rd step is confirm order.
![image](https://user-images.githubusercontent.com/17789934/70086731-62316d80-162c-11ea-9c59-429fba911c33.png)
but i need checkout in 1 step if i haven't payment and shipping, only show confirm step.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
