### ISSUE TITLE
Use ASP.NET Core internal dependency injection instead of Autofac

### ISSUE THREAD

**Issue by ni-fara** [nopSolutions/nopCommerce#4196]
As you know ASP.NET Core has an internal dependency injection ([Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection)). If there isn't any technical benefits in using Autofact, why not use ASP.NET Core built in dependency injection?

Also see performance comparison - https://github.com/danielpalme/IocPerformance

**Comment by thangtq1009** [comment]
Yes, I think so

**Comment by Xzelsius** [comment]
ASP.NET Core built in dependency injection does not cover all aspects of Autofac.

Things like `class SettingSource` or dependency overrides (plugin DbContext) or named dependencies at all.

Personally I like the built in framework... but if you used said Autofac features you probably can't switch to built in without refactoring huge parts of your code.

**Comment by uttamughareja** [comment]
@Xzelsius I'm agree with you. I have been using most of features you mentioned from autofac and this isn't possible with built in container without neasty hack.

**Comment by sefacan** [comment]
I upgraded to 3.1 version with built-in dependency injection. You can see last pull request.

**Comment by a-patel** [comment]
Autofac is best IoC/DI solution for nopCommerce. ASP.NET Core DI provide basic features only.

**Comment by sefacan** [comment]
I replaced nopcommerce DI with built-in DI and working nice.

**Comment by ugharejauday** [comment]
> I replaced nopcommerce DI with built-in DI and working nice.

It will work In ideal case but when you have customisation it won't for example when Service1 and Service2 implements IService and you want to resolve either of one based on scenario.

**Comment by a-patel** [comment]
> 
> 
> > I replaced nopcommerce DI with built-in DI and working nice.
> 
> It will work In ideal case but when you have customisation it won't for example when Service1 and Service2 implements IService and you want to resolve either of one based on scenario.

e.g. `IDependencyRegistrar`, `INopStartup`, `IOrderedMapperProfile`

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box

**Comment by RomanovM** [comment]
Let's rethink the possibility to implement this feature after upgrading to [.net 5](https://github.com/nopSolutions/nopCommerce/issues/4268).

**Comment by uttamughareja** [comment]
If anyone interested to look [Scrutor](https://github.com/khellang/Scrutor) is build around **Microsoft.Extensions.DependencyInjection** and perhaps can be used as a reference

**Comment by DmitriyKulagin** [comment]
Done #4196
