### ISSUE TITLE
PO (purchase order) and vendor enhancements

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#42]
NC has a great start for Vendor support, but I was wondering if we could enhance it even more. Volusion has a great implementation for Vendors. It allows the admin to setup vendors with lots of information about the Vendor to be used when drop shipping and creating POs that are automatically sent to the Vendor when an order is made. You can see details (along with some screenshots) of what it all entails here http://support.volusion.com/article/vendors. The Purchase Order features would be a huge addition to NC for those of us that use Vendors with Drop Shipping. Thanks for your consideration. 

Forum source: http://www.nopcommerce.com/boards/t/27963/enhancement-add-more-features-for-vendor-support.aspx and http://www.nopcommerce.com/boards/t/29853/additional-vendor-features.aspx

SilhouetteBS is going to implement it as a plugin (said on 2016/02/02). So let's leave it for customization

**Comment by AndreiMaz** [comment]
SilhouetteBS is going to implement it as a plugin (said on 2016/02/02)
