### ISSUE TITLE
Add a settings allowing to hide "out of the stock" products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#420]
Source: http://www.nopcommerce.com/boards/t/32411/productload-or-product-search-based-on-stock-availability.aspx 

It would be hard to implement it for "manage inventory method" set to "Track inventory by product attributes". The same is about multiple warehouses. So we can ignore it for them.

**Comment by AndreiMaz** [comment]
We already have "low stock activity" for such purposes
