### ISSUE TITLE
Customers can register without ticking the GDPR consents

### ISSUE THREAD

**Issue by rodolphito** [nopSolutions/nopCommerce#4200]
This seems to be a foresight/bug, right now customers can register without giving consent. This has bad legal implications. I have implemented a fix and am using it on my website. https://github.com/rodolphito/nopCommerce/commit/0190e4899f929d914f93d0fdb1350f063cc1917e

I can PR this, but I wanted to check if it was a bug or intentional first.

**Comment by holydk** [comment]
@rodolphito Hi. Your changes are incorrect. You missed the check in case if the GDPR consent is not required.

**Comment by rodolphito** [comment]
@holydk Thanks, yes I'm aware. That's a fix I'm using on my website. They are correct in my use case. I made an issue here to ask if this was a problem worth PR'ing, the code on my repo is definitely not final.

**Comment by holydk** [comment]
@rodolphito Ok, then you can PR. Thanks.

**Comment by holydk** [comment]
@rodolphito By the way, any estimate on turnaround time?

**Comment by holydk** [comment]
Closed #4200
