### ISSUE TITLE
Create & Use ProductPrice Table For Multi Currency Product Price

### ISSUE THREAD

**Issue by dogo-mehmetcantas** [nopSolutions/nopCommerce#4201]
For 4.30 version it's good to use the ProductPrice table. For example, if we have 3 different currencies (USD, EUR, TRY, etc.) we can use different currencies for different countries.  When we get the product price we can use the last added price for the selected currency. Also, you can add a currency restriction option. In this scenario, we can choose the default currency for each country.

**Comment by fatiheker** [comment]
I needed multiple prices in two different project. One of them dealer prices. Another one different installment has different priceses. There wasn't percent releation.

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/1
