### ISSUE TITLE
Add Ticket booking feature - Seat Reservation

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4203]
nopCommerce version: 4.3

Ticket Booking System
https://techbrij.com/online-ticket-booking-system-asp-net-sql-server

**Comment by ecommerce-tester** [comment]
https://www.jqueryscript.net/chart-graph/Full-featured-Seating-Chart-Plugin-With-jQuery-Seat-Charts.html

**Comment by compito** [comment]
Nice idea, it should be developed as a plugin tho, not everyone needs a booking functionality in their shops.

**Comment by RomanovM** [comment]
Thanks.
Moved to https://github.com/nopSolutions/nopCommerce/issues/36.
Also look at our [marketplace](https://www.nopcommerce.com/marketplace), there are already some similar plugins from third-party developers.
