### ISSUE TITLE
Product Full Description js and css support

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4205]
nopCommerce version: 4.2

in Product Full Description i add css and js (code or file path) and TinyMce put my code inside 
Paragraph "< p >< /p>"  tags, and for result js and css not working.
adminareasettings.richeditorallowjavascript = True
adminareasettings.richeditorallowstyletag = True

**Comment by ecommerce-tester** [comment]
i write style code 
**_<style>
.item-box .details { position: absolute; margin-top: -50px; }
</style>_**
and save
then when i open source code i see
**_<style></style>_**

**Comment by ecommerce-tester** [comment]
After save auto added comment tags

**Comment by AndreiMaz** [comment]
Just set "adminareasettings.richeditorallowstyletag" to "true"

P.S. Could you please post all suggestions on our forums?
