### ISSUE TITLE
Different Product Sorting Order not possible in Multi-Store mode

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4210]
nopCommerce version: 4.10

>Example in one store i want sort 'A-Z' first and the other store i want 'Newest' first.
Unfortunately this is not working from the backend despite it having the multi-store mode checkbox feature on the side of it.

Source: https://www.nopcommerce.com/boards/topic/74447/bug-different-product-sorting-order-not-possible-in-multi-store-mode

**Comment by holydk** [comment]
Closed #4210
