### ISSUE TITLE
Order Item Bulk Insert at Order Place time 

### ISSUE THREAD

**Issue by sinaislam** [nopSolutions/nopCommerce#4213]
nopCommerce version: 
All version of nopCommerce
Steps to reproduce the problem:
Add 100 individual products for 5 customers. When these 5 customers will going to place their order at the same time, it will take10-20 minutes(dependent on the server configuration and database) to complete their orders. For moving 500 products from the shopping cart to the orderitems the system will go to database 500 times.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/3410
