### ISSUE TITLE
Checkout Attribute amount not removed

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4217]
nopCommerce version: 4.20

>In the demo, the "Gift wrapping" checkout attribute has "Shippable product required" selected.  If you add a shippable product to the cart and select the gift wrapping, then the additional fee appears.  If you then remove the shippable item from the cart, and add a non-shippable item to the cart (e.g. a downloadable product), then the fee still appears (and yet the checkout attribute dropdown no longer appears).

Source: https://www.nopcommerce.com/boards/topic/74479/checkout-attribute-amount-not-removed

**Comment by holydk** [comment]
Closed #4217
