### ISSUE TITLE
Security warning by  security-code-scan

### ISSUE THREAD

**Issue by springmin** [nopSolutions/nopCommerce#4227]
nopCommerce version: 4.2
Steps to reproduce the problem: 
Security Code Scan - static code analyzer for .NET（ https://security-code-scan.github.io/ ）
find 682 Security warning：
1、SCS0005 - Weak Random Number Generator  4
2、SCS0005 - Weak Random Number Generator  4
3、SCS0016 - Cross-Site Request Forgery (CSRF)  660
4、SCS0018 - Path Traversal                                  5
5、SCS0027 - Open Redirect                                 9

**Comment by DmitriyKulagin** [comment]
Closed #4227
