### ISSUE TITLE
Avalara: Incorrect tax calculations: Need to pass entire cart to tax provider

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#4230]
nopCommerce version: 
4.2

nopCommerce does not calculate tax correctly. When viewing the cart, instead of passing the entire cart to the tax provider (ex: Avalara), it sends each line to GetTaxRate individually. This will result in incorrect taxes on shipping in some cases.

Example:
In Nebraska, the tax liability on shipping is, by law, calculated proportionally as follows:
`(total cart amount taxable / total cart amount) * tax rate`
The best way for a tax plugin to calculate the proper tax is to pass the entirety of the cart to the tax service and have it apply the rules (which vary state by state) to the whole order.

The plugin API needs changed. nopCommerce needs to pass the entire cart to the tax plugin for this to work. State tax rules vary greatly from state to state and sometimes change. Let Avalara handle the tax rules.

This is a big deal. US users of nopCommerce will be in violation of state laws, especially due to a recent court case that says companies must pay taxes to most states they ship to, not just the ones in which they have nexus.

**Comment by justinjstark** [comment]
We will be customizing nopCommerce to fix this integration with one of your Gold Partners. They may reach out to you. If you would like to work on this together, we have a good knowledge of the Avalara API and how the integration needs to function. We have built custom Avalara integrations for other shopping carts in the past.

**Comment by RomanovM** [comment]
@justinjstark Thanks for your investigation and contribution. We have added a [new method](https://github.com/nopSolutions/nopCommerce/commit/427d45066e4668b1372806bbfe70e55beb301343) in ITaxProvider to calculate tax total for the entire shopping cart, and implemented this method for the Avalara plugin. Details [here](https://github.com/nopSolutions/nopCommerce/commit/7dddc66675800fd26496e35df6e6fc0cb208ca29).
