### ISSUE TITLE
TaxService.cs CalculatePrice calculate original price when price already include tax

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#4236]
Steps to reproduce the problem: 
 `
protected virtual decimal CalculatePrice(decimal price, decimal percent, bool increase)
        {
            if (percent == decimal.Zero)
                return price;

            decimal result;
            if (increase)
            {
                result = price * (1 + percent / 100);
            }
            else
            {
                result = price - price / (100 + percent) * percent;
            }

            return result;
        }

`

when the price is already, the original price can be calculated by `result = price / (1 + percent / 100);,` and it's equal to `result = price - price / (100 + percent) * percent;`, but more easy.

**Comment by RomanovM** [comment]
After some consideration we've decided to leave current approach.
