### ISSUE TITLE
Remove discount coupon and gift card code save to database many times

### ISSUE THREAD

**Issue by JohnsonYuan** [nopSolutions/nopCommerce#4238]
nopCommerce version: 
4.2

Steps to reproduce the problem: 

In CustomerService.cs method RemoveDiscountCouponCode, RemoveGiftCardCouponCode 
when remove discount coupon and gift card code, why write to database once?

For example, in RemoveGiftCardCouponCode method, if the original giftcard count is 5, and remove one, then the database need to be write 5 times (1 for 'null' value, 4 for remaining codes), why just calculate the remaning code and write to database once?
`
            //clear them
            _genericAttributeService.SaveAttribute<string>(customer, NopCustomerDefaults.GiftCardCouponCodesAttribute, null);

            //save again except removed one
            foreach (var existingCouponCode in existingCouponCodes)
                if (!existingCouponCode.Equals(couponCode, StringComparison.InvariantCultureIgnoreCase))
                    ApplyGiftCardCouponCode(customer, existingCouponCode);
`

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality. too minor and rare affect to performance
