### ISSUE TITLE
Show only existing product attribute values in ProductAttributeCombination table

### ISSUE THREAD

**Issue by dogo-mehmetcantas** [nopSolutions/nopCommerce#4245]
nopCommerce version: 

Steps to reproduce the problem: 

Hi, when a customer entering the product detail page, we showing a lot of attributes of products. Some attribute not exist in the product combination list but still, customers see these combinations. So  if we show them just exist product attribute values at combination list in product detail page, it's will be so good for customers and store owners

**Comment by AndreiMaz** [comment]
Thanks. But it duplicates https://github.com/nopSolutions/nopCommerce/issues/16
