### ISSUE TITLE
docker, linux "The type initializer for 'Gdip' threw an exception"

### ISSUE THREAD

**Issue by andreydruz** [nopSolutions/nopCommerce#4248]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Install 4.2 in docker https://hub.docker.com/r/nopcommerceteam/nopcommerce on linux
2. Try to upload image in editor
3. After upload get error: "The type initializer for 'Gdip' threw an exception"
![Alt Text](https://drive.google.com/uc?id=1BpHJur8A5WYbweVd2ixFiHmUWTiak8ko)

**Comment by andreydruz** [comment]
Partial fix: 
`apk add libgdiplus --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted`
And change Presentation/Nop.Web/wwwroot/lib/Roxy_Fileman/index.html
`<input type="file" name="files[]" id="fileUploads" accept=".jpg,.png" onchange="listUploadFiles(this.files)" multiple="multiple" />`

**Comment by skoshelev** [comment]
Closed #4248
