### ISSUE TITLE
docker, linux - css and js bundles not working

### ISSUE THREAD

**Issue by andreydruz** [nopSolutions/nopCommerce#4249]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Install 4.2 in docker https://hub.docker.com/r/nopcommerceteam/nopcommerce on linux
2. Activate bundles in shop settings "MinificationSettings.EnableJsBundling" and "MinificationSettings.EnableCssBundling"
3. Check shop front and you will get 404 on bundle urls

**Comment by andreydruz** [comment]
Bundles created in wrong folder `/wwwroot/bundles`
https://drive.google.com/uc?id=1L_uEVRXFjD5WofLrXQHJLt5AoiUPInaj
And not in `/app/wwwroot/bundles`

**Comment by skoshelev** [comment]
Duplicate the #4135
