### ISSUE TITLE
"Search page" and "page size options" not saved in multi store

### ISSUE THREAD

**Issue by pddeveloper12** [nopSolutions/nopCommerce#4253]
nopCommerce Version: 4.00, 4.10, 4.20

Steps to reproduce the problem: 
Setup a multi-store
Go to Admin > Configuration > Setting > Catalog setting >  on the "Search" section "Search page. Page size options" value is not saved in another store.

I have checked there is a very small change in the view page.

**Comment by holydk** [comment]
Closed #4253
