### ISSUE TITLE
Code re-factoring: Inherit plugin DbContext from new base abstact class BaseDbContext

### ISSUE THREAD

**Issue by a-patel** [nopSolutions/nopCommerce#4254]
Need improvement:
As per existing code for all plugin `DbContext` few methods are the same for all plugins and some of them implementation is not required at all (throw NotImplementedException).
This code id repetitive. It is against the DRY principle.

Possible Solution:
Create new abstract base class (e.g. `BaseDbContext : DbContext, IDbContext`).
All new `PLUGINNAMEObjectContext` and `NopObjectContext` will use `BaseDbContext` as a base class.

**Comment by a-patel** [comment]
Logically, `BaseDbContext` should have the same purpose as the `BasePlugin` class.

**Comment by skoshelev** [comment]
Hi @a-patel. Thank you for suggesting, but we work on the rejection of EF (#239 ), there we won't use the IDbContext interface, that is why these changes won't be relevant
