### ISSUE TITLE
Unit price is incorrect for discount with maximum discounted quantity

### ISSUE THREAD

**Issue by beko1997** [nopSolutions/nopCommerce#4258]
While testing a payment provider which sends the order to an external administration I came across the following situation. This occurs when there is a discount applied to a assigned product which is limited with a maximum discounted quantity.

**nopCommerce version:** 
4.20

**Steps to reproduce the problem:** 
 1. Add a new discount
    - Discount type: Assigned to products
    - Discount amount: 5
    - Maximum discounted quantity: 48
    - Assign to product
 2. Add assigned product to cart with an amount above 48. For example 72. 
 3. Place order
 4. Open PDF invoice of product.

The unit price is displayed like this:
![image](https://user-images.githubusercontent.com/3949189/72260295-d3dcde00-3612-11ea-8b98-38a5e09f8ebe.png)
When calculating the price manually: € 10.29 * 72 = € 740,88‬. While the displayed price of € 860.88 is in fact correct, the unit price is different for the first 48 and the other 24 items and is not displayed within the order. 
The order/order item entity should contain the unit price for each item based on the different discounts. For example you would be able to add another discount for the first 10 items. 

Maybe these should be extracted to 3 different order lines. So you would get:
10x €5.29
38x €10.29
24x €15.29

**Places where this is happening:**
 - PDF invoice
 - Order history > details
 - Admin > orders
 - Payment providers
 - Maybe more

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/1233
