### ISSUE TITLE
in my home page category.NumberOfProducts return null

### ISSUE THREAD

**Issue by MRSheikh** [nopSolutions/nopCommerce#4262]
nopCommerce version: 4.30

i used this code to retrieve number of products for each category in homepage but always `category.NumberOfProducts` return null:

>@model TopMenuModel
 var rootCategories = Model.Categories.Where(x => x.IncludeInTopMenu).ToList();
 foreach (var category in rootCategories)
{
                    var categoryLineModel = new TopMenuModel.CategoryLineModel
                    {
                        Category = category
                    };
                 var temp = category.NumberOfProducts;
  }

i checked  assigning some products to category .
why `category.NumberOfProducts` return null?

**Comment by RomanovM** [comment]
@MRSheikh  There is no nopCommerce 4.30 yet.
Check `CatalogSettings.ShowCategoryProductNumber` setting for your problem.
Next time please post all your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker only.

**Comment by MRSheikh** [comment]
thanks.
