### ISSUE TITLE
Editing Order Items Quantity Not increasing Total Price

### ISSUE THREAD

**Issue by mkibaly** [nopSolutions/nopCommerce#4264]
nopCommerce version: 4.2

Steps to reproduce the problem: 
Open admin panel
Open pending order details
In products section,
Change product price and quantity
Save changes
Total not re-calculated

**Comment by beko1997** [comment]
Automatically updating the order total might override a earlier manual change of the total price. Although I personally agree that the price should always match the totals of orderitems, discounts and extra costs (like shipping/handling fee).

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/2090
