### ISSUE TITLE
Add CreatedOrUpdatedDateUtc to GenericAttribute entity

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4267]
nopCommerce version: 4.20

>I have a notion of introducing CreatedOrUpdatedDateUtc column in GenericAttribute table. This is a good addition as GenericAttribute table lets you store a key value pair in relation to (in case you're customizing as well) nopCommerce operation.

Source: https://www.nopcommerce.com/boards/topic/74726/genericattribute-table-should-have-a-createdorupdateddateutc

**Comment by DmitriyKulagin** [comment]
Closed #4267
