### ISSUE TITLE
Upgrade to .NET 5

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4268]
Let's do once released. But don't start the upgrade until it's officially released and all third-party libraries support .NET 5

**Comment by dizx** [comment]
Good idea

**Comment by Daniel-Guenter** [comment]
This would be really useful for us.  We have existing libraries that we need to link for a plugin that are not compatible with .net Core.  I am hoping that this would allow us to reference them, or at least reduce the number of projects that we have to change in order to reference them.

**Comment by MafdyAzer** [comment]
@AndreiMaz  👍 
There is no longer a need for ".NET Standard" after" .Net 5" release, It'll be removed, only "net5.0"

![image](https://user-images.githubusercontent.com/57217759/83885557-cdc4d680-a746-11ea-8cb6-47865d0ddd9e.png)

https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/

**Comment by AndreiMaz** [comment]
@MafdyAzer You're absolutely right. Now there's no need to consider ".NET Standard"

**Comment by ryanbarlow1** [comment]
.NET 5 is currently scheduled to release in November 2020. Will version 4.40 move to .NET 5 or stay on .NET Core 3.1 (LTS)?

**Comment by ghd258** [comment]
.NET 5 is release

**Comment by ryanbarlow1** [comment]
I should clarify. Back when nopCommerce 4.2 was released, .NET Core 2.2 reached End of Support before nopCommerce 4.3 was released (.NET Core 2.2 lost support December 2019 and nopCommerce 4.3 wasn't released until May 2020). Those five months people were using nopCommerce 4.2 in Production with the .NET Core version not receiving security updates. To remediate this, should nopCommerce only upgrade to LTS versions of .NET, which have a much longer support lifespan? If not, how can this be prevented from happening in the future?

**Comment by ghd258** [comment]
Upgrade to. Net 5 is very simple

**Comment by DmitriyKulagin** [comment]
Closed #4268

**Comment by RobinSCU** [comment]
@DmitriyKulagin did you experience any Performance improvments when you updated to .net core 5.0?

**Comment by DmitriyKulagin** [comment]
@RobinSCU Yes, we have seen some performance improvements over the previous version. But since there were several more significant changes that affect performance, it is difficult to say how much the increase was in terms of migration to .NET 5.

**Comment by SpeakOutLoud** [comment]
Hi @DmitriyKulagin, do we have an expected data for nopCommerce on .Net 5 release?

**Comment by DmitriyKulagin** [comment]
@SpeakOutLoud, estimated end of Q1 2021.

**Comment by SpeakOutLoud** [comment]
@DmitriyKulagin I wanted to ask you, if I currently use the development branch of nopCommerce as it is NET 5 and many other improvements, is it stable version to be used on production?
