### ISSUE TITLE
DeleteExpiredShoppingCartItems method doesn't publish delete event

### ISSUE THREAD

**Issue by AliDehghani** [nopSolutions/nopCommerce#4271]
The DeleteExpiredShoppingCartItems method in ShoppingCartService deletes some shopping cart items but, doesn't publish any event for deleted ones. It happens because this method uses the shopping cart item repository directly for deleting and doesn't use the DeleteShoppingCartItem method.

**Comment by holydk** [comment]
Closed #4271
