### ISSUE TITLE
Cannot connect to mail server that does not support authentication

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4273]
nopCommerce version: develop

The 4.3 development version based on mailkit has an issue sending mails when the SMTP server does not have authentication enabled.
I am using Office 365 to send mails, it is configure to authenticate based on source IP address and does not accept authentication. In 4.2 this works fine but the mailkit implementation always tries to authenticate even if no username/password is configured.

To get it working I made the following change in SmtpBuilder:

```
                if (emailAccount.UseDefaultCredentials || !string.IsNullOrWhiteSpace(emailAccount.Username))
                {
                    client.Authenticate(emailAccount.UseDefaultCredentials ?
                            CredentialCache.DefaultNetworkCredentials :
                            new NetworkCredential(emailAccount.Username, emailAccount.Password));
                } 
```

Source: https://www.nopcommerce.com/boards/topic/74983/cannot-connect-to-mailserver-that-does-not-support-authentication

Related with #3693

**Comment by exileDev** [comment]
Closed #4273
