### ISSUE TITLE
Web Page Load Slowly

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4274]
nopCommerce version: 4.30-developper branch

Steps to reproduce the problem: 
I have low speed page. It's jpg files problem. How to add WebP format?
Or any tips for performance? I have request waiting time problem actually. Download is good. 
My server is i7 8700 cpu,64gb ram,nvme ssd and windows server 2019 and sql server 2019 I use iis and dotnet.exe(64bit). I think i have good system for nopCommerce.

https://hoodarcheryshop.com/
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fhoodarcheryshop.com%2F
![2](https://user-images.githubusercontent.com/7630189/73225451-c92b5880-417d-11ea-9636-0f45101ea820.png)
![1](https://user-images.githubusercontent.com/7630189/73225276-283c9d80-417d-11ea-9da3-16526015ef07.jpg)

**Comment by RomanovM** [comment]
@mk148a Hi. Try to look at https://www.nopcommerce.com/nopcommerce-performance-guide.
Could you please post such questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker only.
