### ISSUE TITLE
Bug in PayPalSmartPaymentButtons plugin

### ISSUE THREAD

**Issue by tarnegur** [nopSolutions/nopCommerce#4275]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
I have an error trying to use this plugin - Error: Expected an order id to be passed.

I have checked the logs and there are many errors from PayPal API of this type:
{
            "field": "/purchase_units/@reference_id=='c319a32c-32f6-4b40-8d30-73faeec2beb1'/items/0/unit_amount/value",
            "value": "652,94",
            "location": "body",
            "issue": "INVALID_PARAMETER_SYNTAX",
            "description": "The value of a field does not conform to the expected format."
        }

My project has german localization, so I would say the problem is the decimal formatting of sent values - comma instead of point.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce/issues/4
