### ISSUE TITLE
Square Payment Plugin 3DS does not work

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4276]
nopCommerce version: develop

>Enabling 3DS on the Square Payment Plugin makes it refuse to authorize all payments. I have tested on 4.20 and 4.30 beta. Any idea what could be causing this, or how I could debug it? There aren't any error messages.

Source: https://www.nopcommerce.com/boards/topic/75287/square-payment-plugin-3ds-does-not-work

**Comment by holydk** [comment]
Closed #4276
