### ISSUE TITLE
Created  a guest customer after  the keep alive task completed

### ISSUE THREAD

**Issue by Farb** [nopSolutions/nopCommerce#4278]
nopCommerce version: 4.3 dev

Steps to reproduce the problem: 
1.My keepalive will run every 300 seconds（5 mins）;
2.I will log  a infomation after  the first step,that is '[KeepAliveAsync]: I'm Api,and I'm alive!'
3.When I  check Customer table,I found new guest customer was created.The  time is the same.

**Comment by Farb** [comment]
guest customer in database 
![](https://i.bmp.ovh/imgs/2020/01/4fc20da03a09fc51.png)
-------------------
task run log
![](https://i.bmp.ovh/imgs/2020/01/630927910b88c647.png)

**Comment by AndreiMaz** [comment]
Cannot reproduce in the latest version. Furthermore, we can simple ignore that because guests are periodically deleted in schedule tasks
