### ISSUE TITLE
Product Price Dynamics

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4281]
Show on Public Store , on Product Page "Product Price Dynamics" graphic with Chart.js

Example: 
![demo_834_none-1](https://user-images.githubusercontent.com/43282933/73750619-ec09ce00-4776-11ea-827d-c18b26f38a4b.png)

**Comment by RomanovM** [comment]
Thanks. We don't plan to implement it now, we leave it for customization.
