### ISSUE TITLE
Zero based orders to not be set as Paid

### ISSUE THREAD

**Issue by janeel** [nopSolutions/nopCommerce#4285]
If an order has a zero total, the payment status is set as paid instead of invoking the payment plugins. 

It would be preferred to make this configurable to allow the payment plugins to handle this.

nopCommerce version: 4.20

Steps to reproduce the problem: 
Purchase a product with Zero price
Payment status is set to Paid and payment plugins are never invoked

**Comment by AndreiMaz** [comment]
It's by design. We'll leave it for customization?
