### ISSUE TITLE
Administration Products List Search Dropdowns Localization

### ISSUE THREAD

**Issue by genireodan** [nopSolutions/nopCommerce#4286]
nopCommerce version: 4.2

Steps to reproduce the problem: 
- Add a new language to the system
- Add or update a category and add a localized value for the Name
- Go to Catalog -> Products
- Open the dropdown for Category, and you will find that it always shows the default value, and not the one within the chosen language

(The same thing happens with the manufacturer dropdown)

I already updated the methods, so it can support that for my case, so I wanted to share that with you, to check if it's the best way to make the change, and also to share it so you can update it for next versions.

Check the attached file:
[changesNopCommerce.txt](https://github.com/nopSolutions/nopCommerce/files/4188167/changesNopCommerce.txt)

If you need more details about the issue, I would be glad to give more information

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/2158
