### ISSUE TITLE
Apply Discounts to OldPrice (for DiscountType "AssignedToSKUs")

### ISSUE THREAD

**Issue by SuperArtie** [nopSolutions/nopCommerce#4287]
I'm loading the MSRP of my products into the 'OldPrice' column on the Product table, and I need to assign a percentage to discount off of the MSRP. Currently the PriceCalculationService & DiscountService use the 'Price' column of the Product table. So I'll need to write something that'll allow for Discounts (where DiscountType == 'AssignedToSKUs') to specify which column ('Product.Price' or 'Product.OldPrice') the discount should be applied. 

If you were interested in having this functionality be a part of the project, how could it best be implemented? Add a new type ('AssignedToSKUsOldPrice') to the DiscountType enum? Or perhaps add a column to the 'Discount_AppliedToProducts' table?

Even if you're not too keen on this, any feedback/advice/input is appreciated. Thanks!

**Comment by AndreiMaz** [comment]
We leave it for customization. But if you need more information on how it could be implemented, please ask on our forums
