### ISSUE TITLE
PostgreSQL Support for nopCommerce

### ISSUE THREAD

**Issue by karaagacylmaz** [nopSolutions/nopCommerce#4288]
nopCommerce version: 
4.20
Steps to reproduce the problem: 
license fees are too expensive in my country. 
I would love to be able to use postgresql

**Comment by AndreiMaz** [comment]
thanks. but duplicates https://github.com/nopSolutions/nopCommerce/issues/3794

**Comment by RynDaniel** [comment]
> nopCommerce version: 4.20 Steps to reproduce the problem: license fees are too expensive in my country. I would love to be able to use postgresql

Did you achieve passing mssql to postgresql? Thanks
