### ISSUE TITLE
Tawk.to integration error

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4290]
nopCommerce version: 4.30(developer brach always last commit)
Steps to reproduce the problem: I was use nopcommerce 4.20 with  tawk.to chat, it was work perfectly, but when I use 4.30 developer version scripts not work with my website its not load(its work with another website without nopcommerce 4.30). ı am share my chrome browser console debug

![1](https://user-images.githubusercontent.com/7630189/74365742-b9e41600-4ddf-11ea-9960-3c4c97e24b4c.JPG)

**Comment by RomanovM** [comment]
Could you please post your questions on [our forums](https://www.nopcommerce.com/boards)? We use GitHub as an issue tracker only.
