### ISSUE TITLE
The database does not exist

### ISSUE THREAD

**Issue by DTHerrera** [nopSolutions/nopCommerce#4292]
nopCommerce version: 4.2.0.0

Steps to reproduce the problem: The database was mistakenly lost (deleted from the server).

The first nopCommerce installation was successful and I generated the Database correctly.

How can I re-generate the installation?

This is the error:
System.Data.SqlClient.SqlException: 'Cannot open database "DBCiperty" requested by the login. The login failed.
Login failed for user 'MACDTH\DTapia'.'

Thanks a lot

**Comment by skoshelev** [comment]
You may delete dataSettings.json and plugins.json files on the App_Data folder. Please post all questions on our forums

**Comment by DTHerrera** [comment]
Ok, Thanks..
