### ISSUE TITLE
Ask country detail in newsletter subscription

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#4301]
nopCommerce version: 4.10+

Steps to reproduce the problem: Currently nopCommerce dont ask country information from customer while subscribing for newsletter.
Its helpful to store owner for sorting customer from different countries/region & send newsletter according to timezones.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we leave it for customiztion
