### ISSUE TITLE
Display customer currency on orders in admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4303]
nopCommerce version: 4.20

>In a multi-currency setup, it would be great to see the purchase amounts in the customer currency that was selected during checkout in addition to the purchase amount that's converted to the base store currency.
It would also be great if we could display the currency code for the purchase, the base currency code, and the exchange rate used at the time of purchase. All of the info is already stored in the DB it's just not available in the admin.

![ACbRd0k](https://user-images.githubusercontent.com/5019111/102578977-87482f80-410c-11eb-9112-369dd62242dc.png)

Source: https://www.nopcommerce.com/boards/topic/78257/display-customer-currency-as-well-as-base-currency-on-orders-in-admin

**Comment by skoshelev** [comment]
Closed #4303
