### ISSUE TITLE
Instant search. Allow to filter by category name

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4306]
Let's make it configurable (disabled by default)

Add a category dropdownlist to the top search box (between the input and the button). The root item name will be "All categories". So it'll be used for the AJAX search and when clicking the "Search" button.

Displat top categories only + "All categories" default value (search in all categories)

Also add a catalog setting indicating whether this feature is enabled or disabled (the dropdownlist is hidden in this case)

**Comment by dorofeev-serdg** [comment]
I'll take care about this issue.

**Comment by dorofeev-serdg** [comment]
https://github.com/nopSolutions/nopCommerce/pull/4339

**Comment by AndreiMaz** [comment]
After some consideration we've decide not to implement this functionality and leave it for customization.

**Comment by exileDev** [comment]
Closed #4306
