### ISSUE TITLE
Add support for hidden product attributes

### ISSUE THREAD

**Issue by ianpowell2017** [nopSolutions/nopCommerce#4307]
I would like to create a product attribute that a customer cannot see or select.

Source: https://www.nopcommerce.com/boards/topic/37850/feature-request-hide-address-or-customer-attributes-from-customer

Related work items - https://github.com/nopSolutions/nopCommerce/issues/315, https://github.com/nopSolutions/nopCommerce/issues/386

**Comment by RajeshRajendiran** [comment]
@ianpowell2017 You can ask this question dev forms

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality

**Comment by NealWebb** [comment]
My I ask the rationale behind not implementing this feature?  My company also has a scenario where that would benefit from this feature (as well as hidden attributes on the customer).  We want to keep any additional functionality relegated to plugins, and while this might be possible by creating a custom entity, it's certainly more difficult and being able to register new attributes as part of the plugin install method.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/315
