### ISSUE TITLE
Retry payment leads to connection reset in custom payment plugin

### ISSUE THREAD

**Issue by spsof** [nopSolutions/nopCommerce#4308]
nopCommerce version: 4.20

I'm developing a payment plugin using redirection, which works fine when just paying for an order after a normal checkout, but fails when I press the "Retry payment" button under the order details (for example after a cancelled payment attempt), showing the following error in console window:
"System.InvalidOperationException: Headers are read-only, response has already started."
and a connection reset error in the browser.

The only thing I have inside my PostProcessPayment method is a RemotePost.Post() call towards the payment gateway. It seems that the order details page already expects a response and it gets aborted with my Post() call. Again, the exact same code works fine when coming from the checkout page.
Any ideas? 
Thanks in advance!

**Comment by AndreiMaz** [comment]
Considering that it's about a third-party plugin and cannot reproduced for the plugins available out of the box, could you please post it on our forums?
