### ISSUE TITLE
Compile fresh clone of nopCommerce

### ISSUE THREAD

**Issue by iwhp** [nopSolutions/nopCommerce#4309]
nopCommerce version: **branch develop**

Steps to reproduce the problem: 
- git clone repository
- build solution

Build message:
**error MSB3073: The command "dotnet "ClearPluginAssemblies.dll" "OutputPath=....
...|SaveLocalesFolders="" exited with code 255.**

One has to remove **|SaveLocalesFolders=** to compile without issues.

**Comment by DmitriyKulagin** [comment]
Not reproduced for latest version (develop)
