### ISSUE TITLE
Azure CDN bundles minify .css and .js

### ISSUE THREAD

**Issue by patsadow2** [nopSolutions/nopCommerce#4313]
nopCommerce version: 4.2

Hello, I am wondering why there is no implementation for azure blob storage cdn for bundle for .css and .js. 
I am not sure it's time consuming since we have similar implementation for pictures ?

Is there any obstacle to do that ?

**Comment by dorofeev-serdg** [comment]
@patsadow2 thanks for this issue.
Could you please describe with more details, what exactly should be implemented?
I tried to configure Azure CDN endpoint before the Azure app service and it seems, that all resources are being cached in CDN.
Azure Web App: 
https://nopsd.azurewebsites.net
Azure CDN Endpoint:
https://nopcdn.azureedge.net
Take a look please at DevTools -> Network for the Azure CDN endpoint page (screenshot is attached). 
Almost all the files (except several banner pictures) are being loaded from CDN.
I mean I reached this state only by configuration, nothing was changed in the code.
So what exactly should be implemented under this issue?
![DevTools-CDN](https://user-images.githubusercontent.com/8334539/75521294-b4a1e080-5a07-11ea-9623-1d4f1184833e.png)

**Comment by patsadow2** [comment]
Where i can find code according to that .ja .css bundle cdn cache ?

**Comment by dorofeev-serdg** [comment]
patsadow2 
Do you mean where to find such files in nopCommerce? Or how to access them in Azure CDN?

**Comment by DmitriyKulagin** [comment]
Duplicate #1299
