### ISSUE TITLE
Docker linux SmtpClient - failing

### ISSUE THREAD

**Issue by patsadow2** [nopSolutions/nopCommerce#4314]
nopCommerce version: 4.2

Steps to reproduce the problem: Sending emails fails on docker

Error sending e-mail. The operation has timed out

**Comment by patsadow2** [comment]
I see bug here: https://github.com/dotnet/runtime/issues/28333

**Comment by skoshelev** [comment]
Can't reproduce on 4.30, sending email function work without problems

Closed #4314
