### ISSUE TITLE
ScheduleTask 524 protection

### ISSUE THREAD

**Issue by mehmetcantas** [nopSolutions/nopCommerce#4317]
nopCommerce version: 
4.20
Steps to reproduce the problem: 

Hello, background tasks working great but not in long processes. If you using Cloudflare for DNS management you facing 524 issues in some tasks

**Comment by AndreiMaz** [comment]
There's no any way to fix it other than to increase timeout in Cloudflare

**Comment by mehmetcantas** [comment]
Even if we use websockets? @AndreiMaz

**Comment by mk148a** [comment]
Me to have same problem
https://github.com/nopSolutions/nopCommerce/issues/4613
Some tasks and automated mails not send(order mails)

**Comment by mehmetcantas** [comment]
Maybe SignalR can be use for this.

**Comment by mk148a** [comment]
Whats a SingalR?
