### ISSUE TITLE
QualPay add to Vault

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4318]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
1) Open current customer
  -- Customer Country is United States
2) Click "Add to Vault"
3) Get below errors:

> Short message	
> Qualpay Customer Vault error: Failed to create customer. Error details in the log
> Full message	
> Nop.Core.NopException: Qualpay Customer Vault error: Failed to create customer. Error details in the log
>    at Nop.Plugin.Payments.Qualpay.Controllers.CustomerController.CreateQualpayCustomer(Int32 customerId)
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at WebMarkupMin.AspNetCore2.WebMarkupMinMiddleware.Invoke(HttpContext context)
>    at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94
>    at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 79
>    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
>    at Nop.Services.Installation.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52
>    at Nop.Services.Common.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

> Log level	
> Error
> Short message	
> Qualpay error: Error calling AddCustomer: {
>   "code" : 2,
>   "message" : "Request validation failed",
>   "data" : {
>     "shipping_country_code" : "Country code is invalid"
>   }
> }
> Full message	
> qpPlatform.Client.ApiException: Error calling AddCustomer: {
>   "code" : 2,
>   "message" : "Request validation failed",
>   "data" : {
>     "shipping_country_code" : "Country code is invalid"
>   }
> }
>    at qpPlatform.Api.CustomerVaultApi.AddCustomerWithHttpInfo(AddCustomerRequest body)
>    at qpPlatform.Api.CustomerVaultApi.AddCustomer(AddCustomerRequest body)
>    at Nop.Plugin.Payments.Qualpay.Services.QualpayManager.<>c__DisplayClass42_0.<CreateCustomer>b__0()
>    at Nop.Plugin.Payments.Qualpay.Services.QualpayManager.InvokeFunction[TResult](Func`1 function)

**Comment by RomanovM** [comment]
@holydk  The shipping country code should be - ISO numeric country code for the shipping address. 
For example for United States it should be “840” instead of “USA”

**Comment by qualpay** [comment]
Thank you for taking a look.  We have subscribed to updates so we can follow progress.

**Comment by holydk** [comment]
Closed #4318
