### ISSUE TITLE
Drop "securitysettings.forcesslforallpages" setting

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4322]
Nowadays if some store owner has SSL vertificate, then he/she enables it for the entire website. So we can think about it like it's always set to "true"

Let's remove this setting with all appropriate source code along with \Nop.Web.Framework\Security\SslRequirement.cs

Let's use "SslEnabled" property of the "Store" entity only

**Comment by holydk** [comment]
Closed #4322
