### ISSUE TITLE
Data table error when searching by name with full-text enabled

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4326]
nopCommerce version: 4.30(developer branch)

Steps to reproduce the problem: 
hi there, when i trying searching some keyword in product page, thats have this error:

![datatables](https://user-images.githubusercontent.com/7630189/76007349-f60e2080-5f1e-11ea-8bea-001f5bfbd76f.jpg)

**Comment by mk148a** [comment]
IT's also when i use it website search, i was open full text search
error detail:
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ')'.

**Comment by holydk** [comment]
Closed #4326
