### ISSUE TITLE
Improvement of the checkout process

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#4327]
nopCommerce version: 4.30

How about moving the “Billing address” tab in front of the “Payment type” tab and starting the checkout from the “Shipping address” tab ?
It seems to me that it’s a bad form to start right away with a payment / payment address, you can start with delivery to show the store’s “service” first.
Billing address will be automatically filled in from shipping address, it can be changed if desired.

In addition, it is worth combining the tabs “Shipping address” and “Shipping methods”, for example, in “Shipping type / method”.
How will it look like ?
1. Delivery types will be arranged in the form of tabs or a list, for example, “delivery to address”, “pick up at the store”, “pick up at the pick-up point”, etc.
1. When choosing a tab, the corresponding content should be dynamically loaded.
1. If the user selects “delivery to the address”, then he needs to fill in the address (manually or from the address book) and choose a delivery method.
1. If the user selects “pick up in the store” or “pick up at the pick-up point”, then he will be able to select the desired point from the list or on the map.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box. leaving it to customization. Now most shopping cart works this way
