### ISSUE TITLE
Registration Failure - Duplicate key violation. 

### ISSUE THREAD

**Issue by mfusiki** [nopSolutions/nopCommerce#4328]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
We currently have an issue, where registering a new user results in a primary key violation, because the guest role is already assigned to the user. I can not at this time provide steps to reproduce, however:

Please have a look at the following:
**Location:** ..\src\Libraries\Nop.Services\Customers\CustomerRegistrationService.cs
**Method:** RegisterCustomer(CustomerRegistrationRequest request)

`//remove from 'Guests' role `

`                       
            if (_customerService.IsGuest(request.Customer))
            {                
                var guestRole = _customerService.GetCustomerRoleBySystemName(NopCustomerDefaults.GuestsRoleName);
                _customerService.AddCustomerRoleMapping(new CustomerCustomerRoleMapping { CustomerId = request.Customer.Id, CustomerRoleId = guestRole.Id });
            }`

The comments suggest we should  remove the guest role which makes sense considering how nopCommerce handles guest, however the code attempts to add the guest role, instead of remove it.

**Comment by mfusiki** [comment]
If we have a look at the following commit, it seems to have changed from remove to add:

342f5b8b6d0ebda4e7b6092255856ee79ba4ef8a

**Comment by AndreiMaz** [comment]
@mfusiki Do you experience this issue each time? Can you reproduce it on the clean installation?

**Comment by AndreiMaz** [comment]
We cannot reproduce the issue. Everything works fine
