### ISSUE TITLE
Bundles of downloadable products don't work

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#433]
Right now we simply disabled this option (display a warning)

Forum source: https://www.nopcommerce.com/en/boards/topic/27409/downloadable-product-associated-with-other-downloadable-products

1. Note that we should also allow a store owner to activate/deactivate downloads in admin area > order details pag for such orders. How can we do it easily for bundled products?
2. We should also include "download" link into message templates. How can we do easily it for bundled products?

maybe, it's just better it's simply ignore such downloadable products. Just add an appropriate note to the "Associate product to product attribute" page

also see https://www.nopcommerce.com/en/boards/topic/44494/suggestion-option-to-upload-file-to-each-product-attribute

also see https://github.com/nopSolutions/nopCommerce/issues/2564

**Comment by petrsoudek** [comment]
Hi, is this bug already solved?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
