### ISSUE TITLE
an infinite loop in a stored procedure when using full-text search

### ISSUE THREAD

**Issue by edsdck** [nopSolutions/nopCommerce#4331]
nopCommerce version: 4.20

Steps to reproduce the problem:
Firstly, full-text search should be enabled from the **General settings** page or by executing the **FullText_Enable** stored procedure.

Next step would be to make sure that the following configuration settings are: 
- UseFullTextSearch = `True` (Database table `Setting`, row `Name = commonsettings.usefulltextsearch`)
- FullTextMode = `And` (Database table `Setting`, row `Name = commonsettings.fulltextmode`)

In a website search enter the following text: `product "` and hit an enter.

The most important part here is that the search term must end with a whitespace and a quotation mark to reproduce the problem.

In a stored procedure `ProductLoadAllPaged` the quotation mark gets removed and the search is being performed with a keyword `product` and a trailing whitespace  which results in an infinite loop inside the stored procedure and crazy large log message which fails to load in an administration page.

**Comment by skoshelev** [comment]
Details in premium support ticket 15320

**Comment by skoshelev** [comment]
Closed #4331
