### ISSUE TITLE
why does it so fuck slowly

### ISSUE THREAD

**Issue by angel6708** [nopSolutions/nopCommerce#4332]
I JUST CLICKED ON THE LINK [LOGIN IN] ,SPENT 1692.8028ms+21305.385ms +21320.1016ms+21320.4194ms +10164.2675ms+23643.7672ms+43784.1547ms +1777.4689ms+.....fuck more.

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost/login  
info: System.Net.Http.HttpClient.default.LogicalHandler[100]
      Start processing HTTP request POST http://localhost/scheduletask/runtask
info: System.Net.Http.HttpClient.default.ClientHandler[100]
      Sending HTTP request POST http://localhost/scheduletask/runtask
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost/scheduletask/runtask application/x-www-form-urlencoded 69
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Login", controller = "Customer", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Login(System.Nullable`1[System.Boolean]) on controller Nop.Web.Controllers.CustomerController (Nop.Web).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "RunTask", controller = "ScheduleTask", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult RunTask(System.String) on controller Nop.Web.Controllers.ScheduleTaskController (Nop.Web).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 204
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.ScheduleTaskController.RunTask (Nop.Web) in 1692.8028ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 21305.385ms 204 
info: System.Net.Http.HttpClient.default.ClientHandler[101]
      Received HTTP response after 21320.1016ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[101]
      End processing HTTP request after 21320.4194ms - NoContent
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Login.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Login executed in 10164.2675ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.CustomerController.Login (Nop.Web) in 23643.7672ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 43784.1547ms 200 text/html; charset=utf-8
info: System.Net.Http.HttpClient.default.LogicalHandler[100]
      Start processing HTTP request POST http://localhost/scheduletask/runtask
info: System.Net.Http.HttpClient.default.ClientHandler[100]
      Sending HTTP request POST http://localhost/scheduletask/runtask
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost/scheduletask/runtask application/x-www-form-urlencoded 69
info: System.Net.Http.HttpClient.default.LogicalHandler[100]
      Start processing HTTP request POST http://localhost/scheduletask/runtask
info: System.Net.Http.HttpClient.default.ClientHandler[100]
      Sending HTTP request POST http://localhost/scheduletask/runtask
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost/scheduletask/runtask application/x-www-form-urlencoded 64
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "RunTask", controller = "ScheduleTask", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult RunTask(System.String) on controller Nop.Web.Controllers.ScheduleTaskController (Nop.Web).
info: System.Net.Http.HttpClient.default.LogicalHandler[100]
      Start processing HTTP request POST http://localhost/scheduletask/runtask
info: System.Net.Http.HttpClient.default.ClientHandler[100]
      Sending HTTP request POST http://localhost/scheduletask/runtask
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost/scheduletask/runtask application/x-www-form-urlencoded 58
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 204
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.ScheduleTaskController.RunTask (Nop.Web) in 1777.4689ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 17160.2158ms 204 
info: System.Net.Http.HttpClient.default.ClientHandler[101]
      Received HTTP response after 17167.9886ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[101]
      End processing HTTP request after 17168.2892ms - NoContent
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "RunTask", controller = "ScheduleTask", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult RunTask(System.String) on controller Nop.Web.Controllers.ScheduleTaskController (Nop.Web).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 204
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.ScheduleTaskController.RunTask (Nop.Web) in 570.1504ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 17367.555ms 204 
info: System.Net.Http.HttpClient.default.ClientHandler[101]
      Received HTTP response after 17385.3285ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[101]
      End processing HTTP request after 17385.6292ms - NoContent
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "RunTask", controller = "ScheduleTask", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult RunTask(System.String) on controller Nop.Web.Controllers.ScheduleTaskController (Nop.Web).
info: System.Net.Http.HttpClient.StoreHttpClient.LogicalHandler[100]
      Start processing HTTP request GET http://localhost/keepalive/index
info: System.Net.Http.HttpClient.StoreHttpClient.ClientHandler[100]
      Sending HTTP request GET http://localhost/keepalive/index
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost/keepalive/index  
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.7893ms 200 
info: System.Net.Http.HttpClient.StoreHttpClient.ClientHandler[101]
      Received HTTP response after 12.7572ms - OK
info: System.Net.Http.HttpClient.StoreHttpClient.LogicalHandler[101]
      End processing HTTP request after 13.0401ms - OK
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 204
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.ScheduleTaskController.RunTask (Nop.Web) in 116.7277ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 13856.3925ms 204 
info: System.Net.Http.HttpClient.default.ClientHandler[101]
      Received HTTP response after 13899.7005ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[101]
      End processing HTTP request after 13899.8494ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[100]
      Start processing HTTP request POST http://localhost/scheduletask/runtask
info: System.Net.Http.HttpClient.default.ClientHandler[100]
      Sending HTTP request POST http://localhost/scheduletask/runtask
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost/scheduletask/runtask application/x-www-form-urlencoded 69
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "RunTask", controller = "ScheduleTask", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult RunTask(System.String) on controller Nop.Web.Controllers.ScheduleTaskController (Nop.Web).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 204
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.ScheduleTaskController.RunTask (Nop.Web) in 1221.7095ms
info: System.Net.Http.HttpClient.default.ClientHandler[101]
      Received HTTP response after 13077.3994ms - NoContent
info: System.Net.Http.HttpClient.default.LogicalHandler[101]
      End processing HTTP request after 13077.6735ms - NoContent
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 13075.1521ms 204

**Comment by AndreiMaz** [comment]
fuck closing

P.S. please be more polite
