### ISSUE TITLE
Display both "title" and "system name" for topics (admin area)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4334]
Currently we display only system name in admin area > content management > topics. It could be confusing for some store owners because system name is not so friendly as "title". Furthermore, it could be empty

On the other hands we also cannot display only "title" because it's also empty in case cases. For example, for topics such as "ApplyVendor", "CheckoutAsGuestOrRegister", "ContactUs", etc.

It does make sense to add the second column for "title" because it'll take a lot of space in the grid. 

The suggestion is to do the following:
1. Rename the column to "Name" (not "title" or " system name")
2. If title is not empty, then display it
3. If title is empty, then display the "system name"

**Comment by VeronicaIsHere** [comment]
Closed #4334
