### ISSUE TITLE
Unable to login from fresh install

### ISSUE THREAD

**Issue by tony09uk** [nopSolutions/nopCommerce#4340]
nopCommerce version: 4.2
sql server version: 15.0.2000

Steps to reproduce the problem: 

- Download package from nopcommerce.com
- unzip in to [folder of your choice]
- open solution in visual studio
- select Nop.Web as start up project
- press F5 to run the project
- follow install wizard (check create new database, select window authentication mode)
- once installed restart the application
- try to log in using the username: (admin@yourStore.com) and password: (password), you set up

Result:
redirected to home page
no errors shown (even when stepping through the code)

Steps taken to resolve the problem:
I downloaded the package again from nopcommerce.com (in case I had a corrupted download).
Checked the user has the correct privileges

Found during debugging:
CustomerController/Login() calls _customerRegistrationService.ValidateCustomer (line 400). 
This returns CustomerLoginResults.Successful. 
On line 413 _authenticationService.SignIn() is called, this method successfully assigns _cachedCustomer. 
When CustomerController/Login() completes, AdminHeaderLinksViewComponent.Invoke() is called. The invoke method calls _commonModelFactory.PrepareAdminHeaderLinksModel().
PrepareAdminHeaderLinksModel() calls _workContext.CurrentCustomer but the guest customer is returned, not the customer that has been signed in

EDIT:

I have resolved the issue by editing nop.web properties and enabling SSL, so my question is now, why?

**Comment by AndreiMaz** [comment]
We cannot reproduce the issue. It works fine

Try to clear your browser cookies or use some anonymous mode in your browser to test it out

**Comment by tony09uk** [comment]
I tried that before posting this. The problem is related to not having SSL enabled.
