### ISSUE TITLE
Barcode generator

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4344]
Barcode generator for products in Admin Area

**Comment by compito** [comment]
If you just need a barcode generated for your GTIN/EAN-13 numbers it could just be a matter of using a dedicated font for it besides the GTIN field, something like https://www.fontpalace.com/font-download/EAN-13/

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box

**Comment by AndreiMaz** [comment]
See https://www.nopcommerce.com/en/barcode-scanner
