### ISSUE TITLE
Support 100% for webfarm (Load balancing)

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#4352]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Still the nopcommerce is not supporting 100% load balancing. For example, when uploading new image for a product, it saved in one server not the 2 servers. Even when using Azure blob, it saves only the thumbs there.

Currently, i suggest to support saving the uploaded images to the blob beside the thumbs, in this case, it will support 100% the load balancing when using the Azure blob.

I am not sure about the generated files and invoices if this should be handled or not.

**Comment by AndreiMaz** [comment]
Thanks. But duplicates https://github.com/nopSolutions/nopCommerce/issues/2494
