### ISSUE TITLE
Adding validation for customer phone number

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#4356]
nopCommerce version: Development branch

Steps to reproduce the problem: Currently there is no validation for customer phone number. It will be very useful to have regularexpression validating the phone number similar to what is being done for the Customer Username.

**Comment by AndreiMaz** [comment]
Also see https://github.com/nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce/issues/3

**Comment by DmitriyKulagin** [comment]
Closed #4356
