### ISSUE TITLE
Adding Google External Authentication Plugin

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#4358]
nopCommerce version: 4.2

Steps to reproduce the problem: I have created the Google external authentication plugin. I think it will be very useful to share with everyone. Let me know if you guys would like me to create a pull request.

**Comment by AndreiMaz** [comment]
We don't plan to add out of the box. Please find this plugin available at https://www.nopcommerce.com/extensions?searchterm=Google+&category=authentication
