### ISSUE TITLE
Decimal quantity in shopping cart item and order item

### ISSUE THREAD

**Issue by PanagLtd** [nopSolutions/nopCommerce#4359]
There are many situations where decimal quantity is needed. for example for grocery stores, many products are picked by weight.

It would be nice to be able to use a decimal value in Quantity in OrderItem and ShoppingCartItem tables.

Regarding the UI, to be backward compatible with INT values, UI can allow decimal values only when enabling this feature with a setting.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But duplicates - https://github.com/nopSolutions/nopCommerce/issues/232
