### ISSUE TITLE
Affiliate support. Commisions. Allow store owner to specify fixed or percentage of commission 

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#436]
Commisions. Allow store owner to specify fixed or percentage of commision. Or don't specify any value. In this case allow store owner to specify affiliate commision on order details page. We also need to add an option to control on which order status a commision is applied and what value on (order subtotal, total) 

At the same moment there are really a lot of much more complex scenarios how commission is calculated. Maybe, in this we should just allow a store owner to enter any custom values of commission? Other ideas?

It will also affect profit reports 

also see http://www.nopcommerce.com/boards/t/77/relevance-of-an-affiliate.aspx?p=3#141626

Some more great suggestions: http://www.nopcommerce.com/boards/t/41042/suggestion-improving-the-affiliate-program-module.aspx

let's discuss

Related work item - https://github.com/nopSolutions/nopCommerce/issues/554

**Comment by eadameg** [comment]
How is the comisión going to be paid?
It could be done as reward points

**Comment by AndreiMaz** [comment]
@eadameg thank! haven't thought much about this task yet.

**Comment by eadameg** [comment]
Welcome.
P.S. I have seen Reward points used to pay affiliates in sites like Groupon, Uber, etc. and I feel it will be simple to implement

**Comment by mjacoup** [comment]
what is the status of this feature since it is blocking become basic  feature ???

**Comment by amirkhanlari** [comment]
Why is there no this basic possibility for vendor commission? There is no plan for it?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box because it's a too specific requirement

**Comment by mjacoup** [comment]
after 5 years u decide it is specific requirements ? oh my GOD i see no future

**Comment by AndreiMaz** [comment]
@mjacoup it's Over exaggeration. We've decided to focus on the core functionality, polishing, refactoring and highly demanded features. This one is not a highly demanded feature. You can always implement it or hire a third-party develop to finish it
