### ISSUE TITLE
Build fails after updating the Nop.Plugin.Payments.PayPalSmartPaymentButtons

### ISSUE THREAD

**Issue by Monchkrit** [nopSolutions/nopCommerce#4360]
nopCommerce version: current

Steps to reproduce the problem: 
1. Clone the repository
2. Build with current code
3. Update NuGet packages
4. Build fails

**Comment by Monchkrit** [comment]
I copied out the errors after build. I hope this helps.

Severity | Code | Description | Project | Line | Suppression State
-- | -- | -- | -- | -- | --
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 412 | Active
Error | CS0117 | 'OrdersCreateRequest' does not contain a definition for 'Body' | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 412 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 423 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 424 | Active
Error | CS0311 | The type 'PayPalCheckoutSdk.Orders.OrdersAuthorizeRequest' cannot be used   as type parameter 'TRequest' in the generic type or method   'ServiceManager.HandleRequest<TClient, TRequest,   TResponseData>(TClient, TRequest, PayPalSmartPaymentButtonsSettings)'.   There is no implicit reference conversion from   'PayPalCheckoutSdk.Orders.OrdersAuthorizeRequest' to   'BraintreeHttp.HttpRequest'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 424 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 435 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 436 | Active
Error | CS0311 | The type 'PayPalCheckoutSdk.Orders.OrdersCaptureRequest' cannot be used   as type parameter 'TRequest' in the generic type or method   'ServiceManager.HandleRequest<TClient, TRequest,   TResponseData>(TClient, TRequest, PayPalSmartPaymentButtonsSettings)'.   There is no implicit reference conversion from   'PayPalCheckoutSdk.Orders.OrdersCaptureRequest' to   'BraintreeHttp.HttpRequest'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 436 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 447 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 448 | Active
Error | CS0311 | The type 'PayPalCheckoutSdk.Payments.AuthorizationsCaptureRequest' cannot   be used as type parameter 'TRequest' in the generic type or method   'ServiceManager.HandleRequest<TClient, TRequest,   TResponseData>(TClient, TRequest, PayPalSmartPaymentButtonsSettings)'.   There is no implicit reference conversion from   'PayPalCheckoutSdk.Payments.AuthorizationsCaptureRequest' to   'BraintreeHttp.HttpRequest'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 448 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 459 | Active
Error | CS0311 | The type 'PayPalCheckoutSdk.Payments.AuthorizationsVoidRequest' cannot be   used as type parameter 'TRequest' in the generic type or method   'ServiceManager.HandleRequest<TClient, TRequest,   TResponseData>(TClient, TRequest, PayPalSmartPaymentButtonsSettings)'.   There is no implicit reference conversion from   'PayPalCheckoutSdk.Payments.AuthorizationsVoidRequest' to   'BraintreeHttp.HttpRequest'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 459 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 476 | Active
Error | CS0012 | The type 'HttpRequest' is defined in an assembly that is not referenced.   You must add a reference to assembly 'PayPalHttp-Dotnet, Version=1.0.0.0,   Culture=neutral, PublicKeyToken=null'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 477 | Active
Error | CS0311 | The type 'PayPalCheckoutSdk.Payments.CapturesRefundRequest' cannot be   used as type parameter 'TRequest' in the generic type or method   'ServiceManager.HandleRequest<TClient, TRequest,   TResponseData>(TClient, TRequest, PayPalSmartPaymentButtonsSettings)'.   There is no implicit reference conversion from   'PayPalCheckoutSdk.Payments.CapturesRefundRequest' to   'BraintreeHttp.HttpRequest'. | Nop.Plugin.Payments.PayPalSmartPaymentButtons | 477 | Active

**Comment by DmitriyKulagin** [comment]
You are trying to use PayPalCheckoutSdk ver. 1.0.3 in which BraintreeHttp is replaced by PayPalHttp
If you are updating NuGet packages, you should take care of their compatibility with the code. We use PayPalCheckoutSdk ver. 1.0.2 together with BraintreeHttp without any build problems
