### ISSUE TITLE
Use serilog with thread-safe ILogger for system logging

### ISSUE THREAD

**Issue by sefacan** [nopSolutions/nopCommerce#4361]
Hi,
Now that we are working with .net core 3.1, why don't we use the built-in logging structure.
Sinks providers are also available so that we can save the log to the same database or to a different location.

https://github.com/serilog/serilog-aspnetcore
All Sinks -> https://github.com/serilog/serilog/wiki/Provided-Sinks
MSSQL Sinks -> https://github.com/serilog/serilog-sinks-mssqlserver
PostgreSQL Sinks -> https://github.com/b00ted/serilog-sinks-postgresql
MySQL/MariaDB Sinks -> https://github.com/TeleSoftas/serilog-sinks-mariadb

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
