### ISSUE TITLE
Feature request: more flexible report generation module

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#4364]
nopCommerce version: 4.2

Steps to reproduce the problem: if we can have support for RDLC rendering with core product it will make reporting alot more flexible. For example invoice plugin and admin dashboard page can use such functionality and you can even schedule reports to be sent out via email.

**Comment by AndreiMaz** [comment]
Thanks. But we don't plan to implement any kind of RDLC.
