### ISSUE TITLE
ShipStation plugin typo

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4367]
nopCommerce version: the upcoming 4.30 ("develop" branch)

Steps to reproduce the problem: 
1. Go to the configuration page
2. "Send dimensio" input should be named "Send dimensions". Or it's even better to name it "Pass dimensions" (for consistency) like it's done for other shipping plugins such as "UPS"

**Comment by skoshelev** [comment]
Closed #4367
