### ISSUE TITLE
Filtering products associated to a parent "grouped" product

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#437]
The problem is that currently when you map a grouped product to a category its child products are not necessarily mapped to the category. This makes the filters in nopCommerce miss these products. In other words if I have a grouped products Cannon EOS 400D and two child products Cannon EOS 400D Black $400 and Cannon EOS 400D Black $500, the price range filter will not take into account neither the $400 price nor the $500 one. This is also true for the specification filter. 
So we were wondering whether it would be better when a grouped products is mapped to a category that its child products are automatically mapped too to that category, because essentially they belong to this category. We can of course implement a twisted query which in addition to the products mapped to the category also traces all these products via their ParenteGroupProductId (which is for a product also mapped to the category) but it would be quite ugly and I am not sure how it is going to perform. 

[AM] Maybe, ask a store owner about it (confirmation window) whether he want to map a child product to the same categories/manufacturers as the parent one 

[AM] in most cases these child products will have “visible individually” disabled and even mapping a child associated product to the same category won’t resolve the issue with “price range” or “filter by specs”. I understand it but still have some doubts about how it’s better to implement/resolve. 

also see forum topic about filtering by prices - http://www.nopcommerce.com/boards/t/25269/price-filter-for-grouped-products-is-not-working-correctly.aspx

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
