### ISSUE TITLE
Getting Error in install page on linux 'Setup failed: An error occurred while creating the database: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.'

### ISSUE THREAD

**Issue by ravikumarmistry** [nopSolutions/nopCommerce#4376]
nopCommerce version: 4.2, Dotnet runtime 2.2

Steps to reproduce the problem: 
Follow the steps to install linux from [link](https://docs.nopcommerce.com/en/user-guide/installing/linux.html) 

![image](https://user-images.githubusercontent.com/5242351/77830166-a8b35680-714c-11ea-9e7d-a24a9f145ff9.png)

When I try to run locally from windows and connect to same database on server it works.

What could be the reason of the issue.

**Comment by dustinmoorman** [comment]
I'm experiencing the same thing during my fresh install using the RAR from the releases page, found here:
https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.20

Environment details:
- Ubuntu 18.04 on AWS EC2.
- nopCommerce 4.2, .NET 2.2

Followed the same link, but unable to proceed with actual install. Subscribing to this issue. Thanks for the help!

**Comment by maplewang** [comment]
the download version not working for linux, you have to compile it under Visual studio or under linux platform.

**Comment by skoshelev** [comment]
Hi all. @maplewang is right. Please see this ticket in the official nopCommerce documentation page on GitHub https://github.com/nopSolutions/nopCommerce-Docs/issues/63
