### ISSUE TITLE
Allow developers to name primary keys and indexes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4378]
One thing that I noticed is that the new interface is not used when creating the names of the primary keys and indexes for the tables.
For example if your entity is Slider and you specify the table name to be SS_Slider.
Then the primary key will be "PK_Slider" instead of "PK_SS_Slider" and the same for the Index.
I am not sure if this is really needed but for the sake of consistency I think it should also use the specified table names in INameCompatibility instead of the type of the entity.

p.s: Foreign keys are working fine and they use the TableNames properly.

Source: https://www.nopcommerce.com/boards/topic/80047/nopcommerce-430-bug-fixes-and-improvements/page/2#260163

**Comment by skoshelev** [comment]
Closed #4378
