### ISSUE TITLE
Discount is applied but discount is not working

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4385]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Make one discount set Discount Type as **Assign to Subtotal**

2) Use percentage	= true
Discount percentage = 20%

3) Code - 456 and save 

4)  Check at front end discount is applied but discount amount is not appear.

**Comment by sk5202** [comment]
Also got same issue for **Assign to OrderTotal**

**Comment by sk5202** [comment]
![6](https://user-images.githubusercontent.com/41533502/77996029-7c652900-734a-11ea-969a-7457d962b0a8.png)

**Comment by skoshelev** [comment]
Closed #4385
