### ISSUE TITLE
Product can't able to add while Applied to product Discount type

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4386]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Make one discount set Discount Type as **Assign to Product** save and continue

2) Go Applied to Product panel and try to add any product not working as expected

**Comment by sk5202** [comment]
![7](https://user-images.githubusercontent.com/41533502/77996181-c6e6a580-734a-11ea-99be-6b8d2aa7871c.png)

**Comment by skoshelev** [comment]
Closed #4386

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@skoshelev @AndreiMaz
