### ISSUE TITLE
Discount switch from assign to categories to assign to product and getting error

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4387]
nopCommerce version:  beta 4.30

Steps to reproduce the problem: 

1) add new discount set assign to categories

2) Add 1 categories at category panel 

3) Click save continue

4) change discount type assign to category to assign to product 

5) getting error see attached screenshot
![1](https://user-images.githubusercontent.com/41533502/77994113-1aef8b00-7347-11ea-9906-f9c0cac5dc06.png)

**Comment by skoshelev** [comment]
Hi, @sk5202. Thank you for your help.

Closed #4387.
