### ISSUE TITLE
Order status change and display unexpected output at order detail and order list page

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4388]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 

1) open order Admin/Order/Edit/2

2) change status from processing to cancel.

3) save

4) it will display 0 

Expected result is cancel 
![2](https://user-images.githubusercontent.com/41533502/77994777-3c9d4200-7348-11ea-9e03-e046f964654c.png)
![3](https://user-images.githubusercontent.com/41533502/77994783-3dce6f00-7348-11ea-821b-c9a3d2f15277.png)

**Comment by sk5202** [comment]
Please change status from drop down from any to cancel 
![5](https://user-images.githubusercontent.com/41533502/77995892-34de9d00-734a-11ea-916c-645165c14009.png)

**Comment by exileDev** [comment]
Fixed by this commit f960488

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@exileDev @AndreiMaz
