### ISSUE TITLE
ShippingbyWeight: improvement to zip code logic

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#439]
Shipping by Weight module could be made much more useful if more than one zip code per price record would be allowed. 

Option 1: would be to allow multiple zip codes (eg. commna separated) per record eg. "1234, 1235". This should be simple be changing the equals to Contains below. 

Option 2: Much more diffiult however even more usefull option would be to also allow zip code to be specified as ranges eg. "BT1-82, BT92-94". 

ShippingByWeightService.cs line 97

```
//filter by zip
        var matchedByZip = new List<ShippingByWeightRecord>();
        foreach (var sbw in matchedByStateProvince)
            if ((String.IsNullOrEmpty(zip) && String.IsNullOrEmpty(sbw.Zip)) ||
                (zip.Equals(sbw.Zip, StringComparison.InvariantCultureIgnoreCase)))
                matchedByZip.Add(sbw);
```

Just to illustrate the need for the feature here is a list of special delivery zones for one of the german courier companies for delivery to Nederlanden 

1156AA-1156ZZ, 1791AA-1797ZZ, 
8881AA-8884ZZ, 8891AA-8897ZZ, 
8899AA-8899ZZ, 9161AA-9164ZZ, 
9166AA-9166ZZ 

Wildcards would be nice too :-)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
