### ISSUE TITLE
Nivo slider can't able to change picture it should be up loader instead of text box

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4390]
nopCommerce version:  4.20 beta

Steps to reproduce the problem: 
Go Admin/WidgetsNivoSlider/Configure

**Comment by sk5202** [comment]
![8](https://user-images.githubusercontent.com/41533502/77996637-9e12e000-734b-11ea-9845-38a3c4fd99f1.png)

**Comment by sk5202** [comment]
**I think every where up loader replace with text box (number)**

**Comment by DmitriyKulagin** [comment]
Closed #4390
