### ISSUE TITLE
Product SEO - Search engine friendly page name is not updated

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4391]
nopCommerce version:  beta 4.30

Steps to reproduce the problem: 
1) GO Admin/Product/Edit/38

2) Go SEO panel try to change **Search engine friendly page name**

3) Click save continue

4) it should be change

**Comment by sk5202** [comment]
![9](https://user-images.githubusercontent.com/41533502/77997948-eaf7b600-734d-11ea-89da-7bf176270a48.png)

**Comment by sk5202** [comment]
Even Same thing is not working with category , manufacture SEO

**Comment by sk5202** [comment]
Actually it is updated but model is not updating when you save

**Comment by skoshelev** [comment]
Closed #4391

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@skoshelev  @AndreiMaz
