### ISSUE TITLE
Forgot to Refresh grid - Product tag Edit 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4392]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 

1) Go  Admin/Product/ProductTags

2) try to edit any tag

3) you guys forgot to call refresh grid 

Expected- Grid should be refresh after edit pop up close

![10](https://user-images.githubusercontent.com/41533502/77999270-0794ed80-7350-11ea-8460-3d1bf0d5f954.png)

**Comment by DmitriyKulagin** [comment]
Closed #4392
