### ISSUE TITLE
SKU Search not working on product list

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4393]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Product/List

2) try to search any sku and click go 

3) Expected - It should be go relevant
![11](https://user-images.githubusercontent.com/41533502/78000039-41b2bf00-7351-11ea-8301-2ac22c654be7.png)
 product Edit if exist

**Comment by exileDev** [comment]
Fixed by this commit f960488

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@exileDev @AndreiMaz
