### ISSUE TITLE
MySQL 5.7 issue with SQL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4394]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
With MySQL 5.7 we were getting the following error message upon clean installation:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive CategoryTree AS ( SELECT id, cast(concat(LPAD(DisplayOrder, @lengt' at line 1

Source: https://www.nopcommerce.com/boards/topic/80144/find-bugs-in-nopcommerce-430-beta-and-earn-10#260234

**Comment by MaceWindu** [comment]
Looks like CTE query, which requires MySql 8+

**Comment by AE10EFCB** [comment]
I also don't know is this important, but if log_bin_trust_function_creators = 0, MySQL 8.0.19 also has an error in installation.

MySQL 8.0.19 by default log_bin_trust_function_creators = 0 
I solved the problem by changing log_bin_trust_function_creators = 1 from my.ini .

**Comment by exileDev** [comment]
We removed the CategoryLoadAllPaged stored procedure that used the CTE statement. Now SQL in nopCommerce complies with MySQL 5.7.

**Comment by exileDev** [comment]
Closed #4394

**Comment by DavidMills02** [comment]
nopCommerce version: 4.30 Beta

I downloaded nopCommerce version: 4.30 Beta today 05/04/2020
Installed nopCommerce version: 4.30 Beta on Visual Studio 2019 16.5.2
NET.Core 3.1.3 is installed
MySQL version 5.7.29.0 installed

Steps to reproduce the problem: 
I started the Installation of nopCommerce version: 4.30 using the Create Database option
Set Database to MySQL and set the MySQL Host details

That creates the error
Setup failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive CategoryTree AS ( SELECT id, cast(concat(LPAD(DisplayOrder, @lengt' at line 1

Database is created when I check with MySQL Workbench
I clicked on Restart the Installation and set the connection string to the database
This creates the error 
Setup failed: FUNCTION Check_Exists_FullText_Index already exists

When I re-do the Installation with or without using the connection string the same error is shown
Setup failed: FUNCTION Check_Exists_FullText_Index already exists

Detailed Error Information:
Module | AspNetCoreModuleV2
ExecuteRequestHandler
aspNetCore
0x8007045b


Regards

**Comment by DavidMills02** [comment]
True -  Delete the Check_Exists_FullText_Index Function and retry.
The problem is solved.
