### ISSUE TITLE
Shipment Date delivered can't able to change

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4395]
nopCommerce version: beta 4.30

Steps to reproduce the problem: 
1) Go Admin/Order/ShipmentDetails/2

2) Try to change **Date delivered** and click save 

3) it will display message like **Enter delivery date**

4) same thing i tried here and it's working https://admin-demo.nopcommerce.com/Admin/Order/ShipmentDetails/2

Expected result - It should be change 
![12](https://user-images.githubusercontent.com/41533502/78001714-bd157000-7353-11ea-9bc8-f6ef1682a33d.png)

**Comment by exileDev** [comment]
Fixed by this commit f960488

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@exileDev @AndreiMaz
