### ISSUE TITLE
Edit order Total not working all value become zero

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4396]
nopCommerce version:  beta 4.30

Steps to reproduce the problem: 

1) Go Admin/Order/Edit/2

2) Click Edit **order total button** 

3) Click Save order totals
![13](https://user-images.githubusercontent.com/41533502/78002518-fdc1b900-7354-11ea-964d-e174429f5305.png)
 button

All value became zero

**Comment by skoshelev** [comment]
Can't reproduce on last source code

Closed #4396

**Comment by sk5202** [comment]
Hello,

Thank you for your comment.

@skoshelev could you please explain me didn't get you.

On this point -  **on last source code**

Is it working at yours?

**Comment by skoshelev** [comment]
Hi, @sk5202. Yes, now everything works. I meant that it was a problem with beta source code, but at the moment the problem has been fixed, in all likelihood, other corrections have affected this task. Thank you again for your active participation in the testing.

**Comment by sk5202** [comment]
@skoshelev ohk that's also good.
