### ISSUE TITLE
Order Shipping method text update is not working 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4397]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go Admin/Order/Edit/4

2) Go Billing and shipping panel

3) Try to change Shipping method text

4) click save 

5) all value cleared

 expected result - It should be update
![14](https://user-images.githubusercontent.com/41533502/78003133-d7e8e400-7355-11ea-973d-115df0efa051.png)

**Comment by exileDev** [comment]
Fixed by this commit f960488

**Comment by sk5202** [comment]
Hello,
Thanks very much for your quick fix
I think you guys forgot to put Bug label still this task have discussion and investigation label.
@exileDev @AndreiMaz
