### ISSUE TITLE
Product Info (price incl and excl ) is not updating on Order Edit 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4398]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Order/Edit/1

2) Go product panel

3) try to change second product price(click edit)

4) instead of 530 add 630 

It is roll back to original one instead of new

See the scrrenshot
![15](https://user-images.githubusercontent.com/41533502/78004074-40849080-7357-11ea-8e17-3a7d038992a1.png)
![16](https://user-images.githubusercontent.com/41533502/78004084-42e6ea80-7357-11ea-9834-b6c3027ecd87.png)

**Comment by sk5202** [comment]
here same thing is working https://admin-demo.nopcommerce.com/Admin/Order/Edit/1

**Comment by skoshelev** [comment]
Can't reproduce on last source code

Closed #4398
