### ISSUE TITLE
News Comment and Blog Comment Edit is not working 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4399]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 

1) Go to Admin/News/NewsComments

2) Edit any  news comment

3) set Is approved uncheck

4) it is not updating 

Expected - It should be update from check to uncheck
![17](https://user-images.githubusercontent.com/41533502/78005179-d0770a00-7358-11ea-896b-8b96a5f2e817.png)

**Comment by sk5202** [comment]
this button also not working



![18](https://user-images.githubusercontent.com/41533502/78005450-35326480-7359-11ea-977d-f17b145b77da.png)

**Comment by AndreiMaz** [comment]
Also added - https://github.com/nopSolutions/nopCommerce/issues/4400 (duplicates)

**Comment by skoshelev** [comment]
Closed #4399

**Comment by sk5202** [comment]
Hello, 
Thanks very much for your quick fix
I think you guys forgot to put **Bug label** still this task have discussion and investigation label.
@skoshelev  @AndreiMaz
