### ISSUE TITLE
Simplify product export/mport from Excel

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#440]
hi , when we want to import price list from excel file , need to prepare many things in excel file to import and some supplier send file with 20.000 pcs product in side and very difficult to prepare product excel import file , can we make some changes there ? maybe we can make price import table and we can map only which colums we need to use because customer send us usually only product name , sku , price and stock , just 4 column in excel and it is all and we can show all our categorys in drop down menu and we can choice category and manufacturer from drop down menus which products will be mapped for it.

We should implement it after #1464 (configurable properties)

**Comment by skoshelev** [comment]
Closed #440
