### ISSUE TITLE
Blog Comment Edit is not working

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4400]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Blog/BlogComments

2) Edit any blog comment

3) set Is approved uncheck

4) it is not updating

Expected - It should be update from check to uncheck

![19](https://user-images.githubusercontent.com/41533502/78005820-bf7ac880-7359-11ea-9f9f-2ed2dcf1edf0.png)
![20](https://user-images.githubusercontent.com/41533502/78005827-c1448c00-7359-11ea-841e-7e4c03bac2a8.png)

**Comment by AndreiMaz** [comment]
duplicates - https://github.com/nopSolutions/nopCommerce/issues/4399
