### ISSUE TITLE
Message template edit is not working

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4401]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Admin/MessageTemplate/Edit/6

2) Click s**ave and  continue**

3) It will display message like 
**Subject is required.
Body is required.
**

**once you click save and continue subject and body cleared**

4) before you can see both are already there
Expected result - It should be update

![21](https://user-images.githubusercontent.com/41533502/78006452-a9213c80-735a-11ea-80e8-d6b680d2555f.png)

**Comment by skoshelev** [comment]
Can't reproduce on the last source codes

Closed #4401
