### ISSUE TITLE
Admin - Logo uploader does not show fine uploader

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4402]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
1. Go Admin > Configuration > General Setting
2. Check upload logo section, 
![logo_uploader](https://user-images.githubusercontent.com/13154058/78010448-010e7200-7360-11ea-90ca-85c2b4025383.png)

Here should be file uploader with fine upload but it shows logo picture Id.

[AM] duplicates already reported - https://github.com/nopSolutions/nopCommerce/issues/4390

**Comment by rajupaladiya** [comment]
Also it not working on the 
![category_editpage](https://user-images.githubusercontent.com/13154058/78010758-5ea2be80-7360-11ea-96e6-d085a9144a2a.png)
![Product_Editpage](https://user-images.githubusercontent.com/13154058/78010766-606c8200-7360-11ea-98ec-550bf577c1e4.png)

category edit page, product edit page

**Comment by AndreiMaz** [comment]
Thanks. But duplicates already reported - https://github.com/nopSolutions/nopCommerce/issues/4390
