### ISSUE TITLE
Order total is not updating with Pickup Fee

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4403]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
1. Go to Pickup point edit page, here pickup fee is 1.99$ 
![4_PickupFee](https://user-images.githubusercontent.com/13154058/78011753-a2e28e80-7361-11ea-96a1-33242b1a320a.png)

2. Now on checkout step, select Pickup point option from shipping method
![5_pickupoPoint](https://user-images.githubusercontent.com/13154058/78011843-c6a5d480-7361-11ea-99d8-b562e63fa13e.png)

3. Click to next and reach at confirm order section and see Shipping price. 
It still zero instead of pickup fee-1.99$
and order total should be with this amount

![6_order_total](https://user-images.githubusercontent.com/13154058/78012168-36b45a80-7362-11ea-8659-515057e8ef69.png)

**Comment by skoshelev** [comment]
Hi @rajupaladiya.

Everything works well, the product you have chosen is simply marked as for free shipping

Closed #4403

**Comment by rajupaladiya** [comment]
@skoshelev - If it free shipping product then pickup amount should be zero in shipping address section in checkout page.

**Comment by rajupaladiya** [comment]
This makes confusion to user

![13-shipping](https://user-images.githubusercontent.com/13154058/78038627-a9d1c700-738a-11ea-826f-7e779621cd07.png)

**Comment by rajupaladiya** [comment]
Checked with the latest source code and it still a same issue there.
In the shipping address section, it still shows pickup point amount 1.99$

**Comment by skoshelev** [comment]
Closed #4403
