### ISSUE TITLE
_columnTwo - widget before and after in left section should be different

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4404]
nopCommerce version: 4.0 Beta

Steps to reproduce the problem: 
Go to Presentation > Nop.Web > Views > Shared > _ColumnsTwo.cshtml
Here newly added widget in the left section should be different to current left side navigation because left section most of the use for my account pages while the left side is used for catalog pages, especially for the filter.

![7_leftside_widget](https://user-images.githubusercontent.com/13154058/78013116-9f500700-7363-11ea-9666-1895fb0ff5ad.png)

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
 (you can determine a current page in the widget)
