### ISSUE TITLE
Application crash in IIS on restart application from Admin

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4405]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
- Go to Admin
- Restart Application from top right button
- Here site is crashing and shows error message 
`HTTP Error 503.0 - Server has been shutdown
The service is unavailable.`

![8_restart_application](https://user-images.githubusercontent.com/13154058/78014034-f73b3d80-7364-11ea-93f9-06191f58530b.gif)

**Comment by AndreiMaz** [comment]
This is restart works in the development mode. It works fine on the live deployed website

**Comment by mk148a** [comment]
> start works in the development mode. It works fine on the live deployed web

How does it know that the site is live?

**Comment by joekrauss** [comment]
This error occurs on my live IIS server as well. I’m using a build from April 21. My environment is based on an upgrade from version 4.2.

**Comment by kevlingo** [comment]
I just dowloaded the source and am using the 4.3.0 release tag. I am getting this error as well. This is my local dev machine. No third-party plugins are being used. Everything seems to be working fine, but as soon as I do a manual restart or delete/uninstall plugins then I get this same error.
