### ISSUE TITLE
Application crash on reload list of plugin click

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4406]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 
1) go plugin list

2) click reload list plugin button
![22](https://user-images.githubusercontent.com/41533502/78014660-e3440b80-7365-11ea-9020-af66390f4f26.png)
![23](https://user-images.githubusercontent.com/41533502/78014670-e50dcf00-7365-11ea-9aa8-b7d831324fd5.png)

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4405
