### ISSUE TITLE
Category is not respect to Limited to store functionality

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4407]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Configure nopCommerce with multiple stores then set any category to limited store 1 but this category still displays in-store two. I cleared cache but it still displays in store 2

Setting - **Ignore "limit per store" rules (sitewide)**  is disabled

**Comment by rajupaladiya** [comment]
Same as for Topic, I set a topic welcome to your store to store 1 and also set display in top menu and footer column one and save.
Clear cache and also restart the application from admin and still this topic displaying in store 2 top menu, in the footer , homepage and also able to access individually

**Comment by skoshelev** [comment]
Closed #4407
