### ISSUE TITLE
Maintenance page - Database backups section is hidden after perform any action

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4408]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to Admin  > System > Maintainance

Perform any option like delete gust user or cart item, it will hide **Database backups ** section

![9_maintanace](https://user-images.githubusercontent.com/13154058/78016782-e7bdf380-7368-11ea-9088-2497d6c12aa2.gif)

**Comment by AndreiMaz** [comment]
@skoshelev related to https://github.com/nopSolutions/nopCommerce/issues/4368

**Comment by skoshelev** [comment]
Closed #4408
