### ISSUE TITLE
Community pole vote is not counted

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4409]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) install beta 4.30

2) Go home page scroll and find community poll.

3)  give vote in my case i gave excellent but it is not counted.

![24](https://user-images.githubusercontent.com/41533502/78018674-f0fc8f80-736b-11ea-92c6-660966730bb9.png)
![25](https://user-images.githubusercontent.com/41533502/78018678-f22dbc80-736b-11ea-99d4-bf8f399a3f72.png)

**Comment by skoshelev** [comment]
Closed #4409
