### ISSUE TITLE
The discount is not been applied

### ISSUE THREAD

**Issue by vitorelli** [nopSolutions/nopCommerce#4410]
nopCommerce version: release-4.30-beta

Steps to reproduce the problem: 
1) Add Manufacturer Discount
2) Add Order Total Discount
3) Try to buy some products and try to apply the discounts
4) The discounts will not be applied

PR to solve this issue: https://github.com/nopSolutions/nopCommerce/pull/4375

**Comment by sk5202** [comment]
Thanks for your solution 

#4385 already reported here

**Comment by skoshelev** [comment]
Hi @vitorelli. Many thank you for your investigation and help. Your changes weren't full, we made our on changes, but they include and your changes too.
