### ISSUE TITLE
Getting Error - Setup failed: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4413]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

Getting error where try to install with **my sql**  at smarter asp.net.

Once installation screen is display after select **my sql** and fill relative value.

Note - If you working with smarter asp you should change at web config file as reported @rajupaladiya #4412 

Here is error screen shot

![29](https://user-images.githubusercontent.com/41533502/78026525-67ec5500-7379-11ea-8c1a-ced396f3fd0c.png)

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/4394
