### ISSUE TITLE
Paypal smart button - configuration missing for payment images and logo

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4414]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to Payment methods and active **PayPal Smart Payment Buttons** payment method.

This plugins shows paypal logo and images on configured widgets but there is no configuration for upload/change images.

![11_header_logo](https://user-images.githubusercontent.com/13154058/78026547-6d499f80-7379-11ea-9f21-05824098058b.png)

![12_foooter](https://user-images.githubusercontent.com/13154058/78026555-70dd2680-7379-11ea-82ec-3d3db479363d.png)

**Comment by rajupaladiya** [comment]
Alos UI is not proper in header with default theme.
I don't think header widget need in the configuration.

**Comment by RomanovM** [comment]
It's PayPal recommendation to use their logos on sites as Prominently Feature. We have added additional settings to configure these logo and banners.
See details in https://github.com/nopSolutions/nopCommerce/commit/cd132abb2d26628595df36a7af3f80b52b10a58d

**Comment by rajupaladiya** [comment]
What about it messed default nop design?
At least it should proper display with default nopCommerce. Isn't it?

**Comment by RomanovM** [comment]
@rajupaladiya You can modify the source code of these logos to fit correctly into your theme and site style. Or just hide them.
