### ISSUE TITLE
If product shipping is free then shipping amount should not display on product detail page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4416]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Mark product as free shipping from admin area and check detail page of that product

Here still shipping calculation section displaying. If product is free shipping then it should not be there. It makes confusion to user.

![14-free-shgipping-on-productdetailpage](https://user-images.githubusercontent.com/13154058/78040166-b3f4c500-738c-11ea-98b4-045e1e8caa8f.png)

**Comment by holydk** [comment]
Closed #4416

**Comment by rajupaladiya** [comment]
@holydk, @AndreiMaz - Bug label is missing.
