### ISSUE TITLE
Unable to update return request (staff note) and disappear record once return request created from front end.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4417]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Login with 
victoria_victoria@nopCommerce.com 
123456

2) Go /order/history

3) click return request After select qty and add relevant reason.

4) login with Admin and go Admin/ReturnRequest/List

5) Edit same request you just created and add staff note click on save 

6) You will redirect to list page and same return request will disapear

7) when you go  victoria_victoria@nopCommerce.com my account page return request link (side menu) will also disappear

see the video 

 https://www.loom.com/share/2b7c213840fb4321b91bdc8c8c09f226

**Comment by holydk** [comment]
Closed #4417
