### ISSUE TITLE
Queued Email [Go directly to email] (button) is not working

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4418]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) go /Admin/QueuedEmail/List

2) Add and int at [Go directly to email] (button) this input

3) Click go nothing is happened.

It should be redirect relevant  Queued Email detail page

![30](https://user-images.githubusercontent.com/41533502/78056943-8a936380-73a3-11ea-817e-6246f188308a.png)

**Comment by skoshelev** [comment]
Can't reproduce the problem on the last source codes. All work as expected

Closed #4418
