### ISSUE TITLE
SeNames search is not working.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4419]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Common/SeNames

2) try to search 100-physical-gift-card

3) not able to search 

Expected it should be work as here  https://admin-demo.nopcommerce.com//Admin/Common/SeNames

https://www.loom.com/share/700b19f383c145a59e5a8d2e56b5855b

**Comment by skoshelev** [comment]
Closed #4419
