### ISSUE TITLE
Customer activated event code is missing

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4420]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
There is item in release note : **#4179 Add customer activated event** there is no code exist for rise event on activate customer from admin area,

**Comment by skoshelev** [comment]
Hi @rajupaladiya. Yes, that's right, the original task did not imply such behavior

> Please add event consumer for On Customer Activation.
> 
> When User registration type is not Standard, then there is no way to identify from a plugin when customer is activated.

**Comment by rajupaladiya** [comment]
@skoshelev - Then you have to remove this item from the release note list.
