### ISSUE TITLE
Delete SEO Friendly name is not working

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4421]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to Admin > System > Search engine friendly page names

Select record and click on delete button.

![15_seoname](https://user-images.githubusercontent.com/13154058/78058082-633d9600-73a5-11ea-89f1-2429d44e0b77.gif)

**Comment by skoshelev** [comment]
Can't reproduce the problem on the last source codes. All work as expected.

Closed #4421

**Comment by rajupaladiya** [comment]
@skoshelev - can you update the download folder with the latest files, so we can test with latest files.

I tested 3-4 times and it's same.

**Comment by rajupaladiya** [comment]
After investigating, it seems it is caching related issue.

**Comment by kava81** [comment]
hi, please look here
https://www.nopcommerce.com/boards/topic/52859/locale-cached-problem
it seems the same problem

**Comment by rajupaladiya** [comment]
@skoshelev - with the latest source code, it seems working fine.
