### ISSUE TITLE
Checkout button in hidden after enable PayPalSmartPaymentButtons payment method

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4424]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to admin > Configuration > Payment Methods >
Enable **Payments.PayPalSmartPaymentButtons** payment method.

now I've three active payment methods.
![20-payment-method](https://user-images.githubusercontent.com/13154058/78065345-c7b22280-73b0-11ea-8577-adcdf8895bf3.png)

Now redirect to cart page.
Here now display paypla buttons but no Checkout button available even I've enabled checkmoney order and manual payment methods are active.

![21-paypal-button](https://user-images.githubusercontent.com/13154058/78065682-41e2a700-73b1-11ea-8a6f-7d88e5e1f282.png)

Here Paypal buttons are making confusion.
Also, click on these buttons, it redirects to the checkout page instead of a direct redirect payment page as it Button payment method.

**Comment by RomanovM** [comment]
We have added the setting whether to display these buttons instead of the default one. See details in https://github.com/nopSolutions/nopCommerce/commit/cd132abb2d26628595df36a7af3f80b52b10a58d

**Comment by rajupaladiya** [comment]
@RomanovM - So this is not bug?

**Comment by rajupaladiya** [comment]
@RomanovM & @AndreiMaz,
I take pull with current source code and tested, it seems still there is no checkout button with wrong paypal credentials.
Don't know why @RomanovM  closed this.

https://www.loom.com/share/20e8f5e395fc4a9b96514f5db5a78076

**Comment by RomanovM** [comment]
@rajupaladiya We hid these buttons on the shopping cart page by default, so now after installing the plugin, a default 'Checkout' button will be displayed. And then merchant needs to configure the plugin correctly so that everything displays correctly. See details in https://github.com/nopSolutions/nopCommerce/commit/52a4f18583f8d7e4bf1fc2812ae2d9afafc9bff7
