### ISSUE TITLE
Error on customer edit page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4426]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to customer edit page and click on save and continue option, it removing all customer data and display error `Add the customer to 'Guests' or 'Registered' customer role`

![22_customer_edit](https://user-images.githubusercontent.com/13154058/78069874-7148e200-73b8-11ea-93ec-d5ee17289b4e.png)

Here is Video, please look 
https://www.loom.com/share/2e633d5101c04d8cb5324b8ef028e5b2

**Comment by rajupaladiya** [comment]
This happens only when **Registration method** type is **A customer should be approved by administrator**

![23-customer-registeration-type](https://user-images.githubusercontent.com/13154058/78070580-aace1d00-73b9-11ea-8063-69ca7c30cc52.png)


With the rest of settings, it's working fine.

**Comment by DmitriyKulagin** [comment]
@rajupaladiya I can not reproduce this. Works good. Perhaps this problem has been fixed along with other improvements. Please update the code and try again

**Comment by rajupaladiya** [comment]
@DmitriyKulagin - I just checked with latest source code and it seems working fine now.

For verifying bug you can check [here](http://430.nopcypher.com/Admin/Customer/Edit/12)
login with admin@yourstore.com / admin@123
Here no-source uploaded which is available on release page when beta version released.
