### ISSUE TITLE
 PayPal Smart Payment Buttons payment method is working only for admin

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4427]
nopCommerce version: 4.30

Steps to reproduce the problem: Configure  PayPal Smart Payment Buttons payment method.
**Login with admin**
Add a few items in the cart and proceed checkout with  PayPal Smart Payment Buttons method, it works fine.

Now login with a registered user and proceed checkout process with **PayPal Smart Payment Buttons** payment method. It throws an error and not allow user to proceed next step.

Error Message: **Error: Expected an order id to be passed**
Here is video: https://www.loom.com/share/e25ace062ee94f0ab689ac9a3e669504

**Comment by rajupaladiya** [comment]
I noticed this issue due to the invalid address of the customer. After adding a proper address, it working fine.

But in this case error message should be display proper instead of **Expected an order id to be passed** message.

**Comment by AndreiMaz** [comment]
@rajupaladiya What exactly invalid address have you entered? 

Could it be related to https://github.com/nopSolutions/nopCommerce/commit/ae741a9e11205a4fefc05fe786a8c47197efac15 and https://github.com/nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce/issues/3

**Comment by rajupaladiya** [comment]
@AndreiMaz & @DmitriyKulagin - here is address
test
test,Alabama,test
United States

You can see [here](http://430.nopcypher.com/Admin/Customer/Edit/12)
login with admin@yourstore.com/ admin@123

![00_address](https://user-images.githubusercontent.com/13154058/78403356-d9e2c980-7619-11ea-853b-5212865471fc.png)

**Comment by RomanovM** [comment]
We have added an additional error notification for such cases. See details in https://github.com/nopSolutions/nopCommerce/commit/cd132abb2d26628595df36a7af3f80b52b10a58d

**Comment by rajupaladiya** [comment]
@RomanovM - So are you not considering this as bug?

**Comment by RomanovM** [comment]
@rajupaladiya Nope. There was already an error notification, just with different message.

**Comment by rajupaladiya** [comment]
But it was not related to the actual issue...
Error message was: **Error: Expected an order id to be passed** which is already mentioned in description.

**Comment by rajupaladiya** [comment]
@RomanovM - is this fixed? we still getting same issue in latest version of plugin in nopCommerce version 4.50.2
Paypal commerce plugin : Version: 1.10.6
https://prnt.sc/T1_PVcnnwya7

![Image](https://github.com/user-attachments/assets/5a09fd89-403b-46ee-a850-687d36292796)

**Comment by RomanovM** [comment]
@rajupaladiya Check the log for error details. "Expected an order id to be passed" is the common error text returned by PayPal
