### ISSUE TITLE
No payment detail display with wrong client secret and id in paypal smart button plugin

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4428]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Go to  PayPal Smart Payment Buttons's configuration page.
Configure here wrong credentials.

Now go to checkout page, this will allow user to select  PayPal Smart Payment Buttons payment method from paymet method list section.

Select  PayPal Smart Payment Buttons method and click on the next button.
Now, the Payment information section is totally blank.

![26-payment-method-list](https://user-images.githubusercontent.com/13154058/78072829-68a6da80-73bd-11ea-9ff5-597ed235ce87.png)

![27-payment-information-page](https://user-images.githubusercontent.com/13154058/78072832-693f7100-73bd-11ea-9499-d24c843cf3b3.png)

It also not display checkout button on cart page
![25-order-summary](https://user-images.githubusercontent.com/13154058/78072821-62186300-73bd-11ea-8cd4-d21207095b92.png)

So in this case,  PayPal Smart Payment Buttons method should not display in payment method list in the checkout process

Look at this video - https://www.loom.com/share/5fe4ca87223e4a7d83c973d9a68ddc4d

**Comment by RomanovM** [comment]
If a merchant wants to use a plugin with incorrect credentials, this is his right, but it's obviously that the plugin won't work.

**Comment by rajupaladiya** [comment]
@RomanovM - Are you sure merchant will use plugin without credentials? if yes then why?
Whatever you saying that need during development time and here plugin is already developed.
I don't think this make any sense.

Also what about below screen. Is that not an issue?
![paypal](https://user-images.githubusercontent.com/13154058/79078049-426d2d00-7d23-11ea-8382-894b3cca7aa3.png)

**Comment by RomanovM** [comment]
@rajupaladiya Well, I agree along with #4424 this can be considered as a bug. Moved to #4424.
