### ISSUE TITLE
Gift card initial amount is zero

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4431]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Place order or virtual gift cart 25$ product and make it paid.

After order paid, gift card amount should be 25$ but it is zero.

See this video - https://www.loom.com/share/dd86c5d549d247a7bfb988dd3a1ae8c6

**Comment by mariannk** [comment]
Hi! Unfortunately I can't reproduce this issue. Please make sure you use a clean installation with default product and don't use any third party plugins. And also please check that you connected to right database. Let me know if you checked all my suggestions and you still have this issue.

**Comment by rajupaladiya** [comment]
@mariannk - I download code from GH and tested, it seems now it working fine.
Before it was not working. you can check at video or test at http://430.nopcypher.com/.

It might be fixed with some other changes.

**Comment by cklenk** [comment]
Oops ignore that. The issue was $0.00 was entered for the overridden gift card amount 🤦🏼‍♂️ haha

Thanks 
-Cameron
