### ISSUE TITLE
Shipping pop up Validation missing and it's show undefined when i click on Apply button

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4433]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /fahrenheit-451-by-ray-bradbury

2) Click on shipping And ii will display popup

3) there are 2 drop down and one text field all are require but validation is not set when you leave zip code blank it will allow and close pop up

4) If you not select any country and state it will display undefined message once pop up close.

see the video https://www.loom.com/share/a4c8b4992a434a60abe49a8a7d326c58

**Comment by holydk** [comment]
Closed #4433
