### ISSUE TITLE
Cannot save ACL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4434]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1. Open ACL page in administration
2. Check "Admin area. Manage plugins" for the Vendors role.
3. Click "Save"
4. After the page is saved, click "Save" again or enable another permission per role and click "Save"

Source: https://www.nopcommerce.com/boards/topic/80047/nopcommerce-430-bug-fixes-and-improvements/page/2#260282

**Comment by skoshelev** [comment]
Closed #4434
