### ISSUE TITLE
MySQL install failed.

### ISSUE THREAD

**Issue by neoayi** [nopSolutions/nopCommerce#4435]
nopCommerce version: 
4.3.0
Steps to reproduce the problem: 
install with MySQL version.

MySQL version : 5.7.25

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive CategoryTree AS
	(
	  SELECT id, cast(concat(LPAD(DisplayOrder, @len' at line 21

**Comment by sk5202** [comment]
thanks but
It is already reported. #4394

**Comment by neoayi** [comment]
> thanks but
> It is already reported. #4394

ok.
