### ISSUE TITLE
Picture Upload Problem

### ISSUE THREAD

**Issue by AE10EFCB** [nopSolutions/nopCommerce#4436]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. Edit product page in administration
2. In the Add a new picture section picture upload input is shown as integer value.

and
Open "General Settings" page in administration
Try to upload logo

![picture_upload](https://user-images.githubusercontent.com/11808950/78140283-6f236980-7432-11ea-9e04-ff7fa43472fd.png)
![logo_upload](https://user-images.githubusercontent.com/11808950/78140381-99752700-7432-11ea-967f-ffd47d49b0d2.png)

**Comment by sk5202** [comment]
thanks,
but already reported #4402
