### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by vitorelli** [nopSolutions/nopCommerce#4437]
nopCommerce version: release-4.30-beta

Steps to reproduce the problem: 

**Fail to import language resource file:**
1. Create a second language
2. Import a language file
3. It will broke the primary web site language (and possible duplicate some items in LocaleStringResource table)

**Performance issue:**
1. Create a second language
2. Import a language file
3. Reimport the same language file
4. For each resource item, the code will run GetLocaleStringResourceByName method, it will go to database to obtain a instance of LocaleStringResource
5. It should avoid those round-trips in database

PR to solve those issues: https://github.com/nopSolutions/nopCommerce/pull/4373

**Comment by skoshelev** [comment]
Hi @vitorelli. Thanks a lot for your optimization suggestion, I looked at it and agree to accept your changes. Please make a separate PR without changes to NopEditorTagHelper and, if possible, with one commit.

**Comment by vitorelli** [comment]
Hi @skoshelev per your request, I create a new PR: https://github.com/nopSolutions/nopCommerce/pull/4448

**Comment by skoshelev** [comment]
Hi @vitorelli. Thank you for your help.

Closed #4437
