### ISSUE TITLE
Order status change value showing wrong value on order edit page or order list page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4439]
nopCommerce version: 4.3beta

Steps to reproduce the problem:
Order status change value showing wrong value on order edit page or order list page

Go to Order edit page > change status
now look the value of order status on order edit page as well as order list page

![Orders _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/78212667-07226100-74ce-11ea-962d-a83b6f207763.gif)

**Comment by sk5202** [comment]
Hello @sangeetshah 

Thanks but already reported #4388

**Comment by sangeetshah** [comment]
ok then i am going to close this bug
