### ISSUE TITLE
Order Shipments is not working on order edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4440]
nopCommerce version: 4.3beta

Steps to reproduce the problem: 

Go to order edit page - shipment section
Do add to shipment 

add Tracking number,
Admin comment	,
select Shipped,
select Delivered

now proceed for save or save and continue	

![Edit order details _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/78213214-9f6d1580-74cf-11ea-94cd-9107116458e3.gif)

**Comment by sk5202** [comment]
Hello,

thanks @sangeetshah  but this person @tigran-avdalyan  already reported #4383
