### ISSUE TITLE
Export order to excel not working on order list page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4441]
nopCommerce version: 4.3beta

Steps to reproduce the problem: 
Export order to excel not working on order list page

error name is:"lease set the ExcelPackage.LicenseContext property. See https://epplussoftware.com/developers/licenseexception
![Orders _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/78214545-27085380-74d3-11ea-8582-f4025a673890.gif)

**Comment by skoshelev** [comment]
This exception is called only in debug mode to draw attention to the changed license. We have added the necessary configuration section to the appsettings.json file 

Closed #4441

**Comment by noptools** [comment]
It's still not clear to me whether this "changed license" impacts us.   Adding "necessary configuration section" just masks the message, but are 'developers' allowed to compile nopCommerce when it includes EPPlus without a license?

**Comment by skoshelev** [comment]
We analyzed the current situation with the new license and decided to return to using the previous version of the library.

See [this commit](https://github.com/nopSolutions/nopCommerce/commit/7d9e89b63c06a912c83d75b4adb80250534b345d)

**Comment by sangeetshah** [comment]
can you please add bug tag with this task.

**Comment by sangeetshah** [comment]
@AndreiMaz 

sir is this bug or not? if this one is bug then can you please add bug tag with this issue. bcz i can see commit for this issue.
