### ISSUE TITLE
Getting error -  Invalid non-ASCII or control character

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4443]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

**I am Facing this issue only at shared hosting (smarter Asp)
If same thing i tested at local IIS it is working.** 

1) Add one language 

Name- Arabic
Language culture - Arabic (Egypt)
Unique SEO code - AR

2) Now Go general setting and enable **SEO friendly URLs with multiple languages enabled**	

3) Clear cache and restart application.

2) Go topic page /Admin/Topic/Create

Add value like i added
Title of topic page
Standard - test topic
English - bã-yến-mạch
Arabic -   bã-yến

![31](https://user-images.githubusercontent.com/41533502/78223559-b833f600-74e4-11ea-8b81-509dc90d1e37.png)

3) click on **save and continue** 

4)  Click on preview

     now you will get error 

![32](https://user-images.githubusercontent.com/41533502/78231404-5da09700-74f0-11ea-86e8-813c51252d0d.png)

**Here i reproduced full error see the full video** 

https://www.loom.com/share/288b1fe985244af1970ef1fc94fa211b

**Comment by RomanovM** [comment]
Possibly related to #2731

**Comment by RomanovM** [comment]
@sk5202 Ensure that your setting ["AllowNonAsciiCharactersInHeaders"](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Security/SecuritySettings.cs#L39) is enabled.

**Comment by sk5202** [comment]
@RomanovM  it is already enabled AllowNonAsciiCharactersInHeaders

Default nop set as enabled during the installation time.

I am also surprised this issue happened with smarter asp.net

**Comment by skoshelev** [comment]
I could not repeat the problem for 4.30 even with the AllowNonAsciiCharactersInHeaders setting turned off, since the .net Core team seems to have fixed the problem

![Your store  bã-yến - Google Chrome](https://user-images.githubusercontent.com/16875599/78291399-fdc8e100-752d-11ea-8bc8-85dc3c173826.jpg)

Closed #4443

**Comment by skoshelev** [comment]
I reproduced the problem in the docker container

![docker](https://user-images.githubusercontent.com/16875599/78332951-a52b2f80-7591-11ea-8a57-3cfb25652841.jpg)

**Comment by mk148a** [comment]
That issue still in nopcommerce 4.50 version
![resim](https://github.com/nopSolutions/nopCommerce/assets/7630189/1163a83d-a5df-4e3d-af0e-229a0ff0d987)

**Comment by AndreiMaz** [comment]
@mk148a Could you please copy the specified URL here?

**Comment by jimmyrn** [comment]
Hi @mk148a, I can still reproduce this issue in version 4.70.5
On the url https://mettehvitved.dk/bjørks-trøje (localized, working url: https://mettehvitved.dk/da/bjørks-trøje)
`securitysettings.allownonasciicharactersinheaders` is set to True:
![image](https://github.com/user-attachments/assets/a0460ca3-9e47-47af-aa37-36952fd55c3f)

The error:
![image](https://github.com/user-attachments/assets/30b6b556-249f-42af-90bb-321b421a86c4)
