### ISSUE TITLE
Cannot delete all tables in database

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4444]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1. Install nopCommerce
2. Go to the database with SSMS
3. Try to delete all tables (you could need it sometimes). Previously you can delete all of them (with several interations)
4. Now there are several tables 9Address, Country, Customer, Order, RewardPointsHistory, StateProvince) that cannot be deleted until you manually remove some foreign keys

I presume it's related to wrong creation of foreign keys (references) between these tables

**Comment by skoshelev** [comment]
Closed #4444

**Comment by skoshelev** [comment]
Closed #4444
