### ISSUE TITLE
Product Detail shipping ajax loader is constantly moving while create copy product and go (Product detail front end)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4445]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Product/Edit/10

2) Click copy product from header it will allow as to some value in pop up

3) just **uncheck published and copy product check box** leave other as it is

![33](https://user-images.githubusercontent.com/41533502/78234388-b83bf200-74f4-11ea-8bd6-1dd5421aa725.png)

4) It will redirect to product edit page of your new product.

Now click on preview button you will redirect front end product detail page.

and see there is ajax loader moving 

It should not moving.

![34](https://user-images.githubusercontent.com/41533502/78234371-b07c4d80-74f4-11ea-81d0-0f4b8ead6f45.png)

**Comment by sk5202** [comment]
Reproduce this issue see the video

https://www.loom.com/share/5176066c49984d289a623beb67bf0688

**Comment by holydk** [comment]
Closed #4445
