### ISSUE TITLE
Email doesn't work with SSL

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4447]
nopCommerce version: 4.30 beta

Source: https://www.nopcommerce.com/boards/topic/80146/nopcommerce-430-beta-released-please-share-your-impressions/page/2#260287

Also see: https://www.nopcommerce.com/boards/topic/80146/nopcommerce-430-beta-released-please-share-your-impressions/page/3#261336

Getting the following error when sending emails (gmail account): "An error occurred while attempting to establish an SSL or TLS connection. This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons: 1. The server is using a self-signed certificate which cannot be verified. 2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate. 3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable. 4. The certificate presented by the server is expired or invalid. Another possibility is that you are trying to connect to a port which does not support SSL/TLS. It is also possible that the set of SSL/TLS protocols supported by the client and server do not match. See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions"

[Andrei Mazulnitsyn] We also experience the same on our demo website

**Comment by RomanovM** [comment]
Related to https://github.com/nopSolutions/nopCommerce/issues/3693
See also https://github.com/nopSolutions/nopCommerce/issues/4273

**Comment by exileDev** [comment]
Closed #4447. Also make sure that you are using correct protocol ports: 465 with SSL security or 587 with TLS
