### ISSUE TITLE
Can't able to add product on category Edit 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4449]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go Admin/Category/Edit/13 and chose advance mode.

2) Go Products panel and try to add any product 

Not working.

<img width="943" alt="36" src="https://user-images.githubusercontent.com/41533502/78253507-1deaa700-7512-11ea-8eb6-28413eb31f11.png">

**Comment by skoshelev** [comment]
The same problem as in #4450

Closed #4449
