### ISSUE TITLE
Can't able to Edit display order and delete product from category edit product panel

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4450]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go Admin/Category/Edit/13 and chose advance mode.

2) Go Products panel and Edit and change display order and save 

not working edit functionality

3) And try to delete any record from grid also not working

<img width="943" alt="36" src="https://user-images.githubusercontent.com/41533502/78254409-7cfceb80-7513-11ea-8223-dd9e61929dbf.png">
<img width="949" alt="37" src="https://user-images.githubusercontent.com/41533502/78254410-7e2e1880-7513-11ea-8290-1587ed4be247.png">

**Comment by skoshelev** [comment]
Closed #4450
