### ISSUE TITLE
Can't able to save store at [limited to store multi select] checkout attribute edit page

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4451]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/CheckoutAttribute/Edit/1

2) Limited to store - select store from multi select and click save and continue

values should be save but not working. 

https://www.loom.com/share/5f565a846de54981a4ca98c17197655d

here is another video i am trying remove store from same field and i can't able to remove even i cleared cache.

https://www.loom.com/share/5336dd2b4c36486593ccd4a3df802536

**Comment by skoshelev** [comment]
On the latest version of the source code, everything works without problems.

Closed #4451
