### ISSUE TITLE
Cannot install Nop.Plugin.Shipping.FixedByWeightByTotal after uninstall

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4459]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1. delete table from sqlserver database,
2. delete entry in App_Data/plugins.json (Shipping.FixedByWeightByTotal)
3. restart Nop.Web, login as admin
4. Install Shipping.FixedByWeightByTotal
5. Configure (fails)
6. Crash message: System.Data.SqlClient.SqlException: 'Invalid object name 'ShippingByWeightByTotalRecord'.'
7. At: public PagedList(IQueryable<T> source, int pageIndex, int pageSize, bool getOnlyTotalCount = false)
8. Cause: Table not created during plugin installation.

Source: https://www.nopcommerce.com/boards/topic/80144/find-bugs-in-nopcommerce-430-beta-and-earn-10/page/3#261392

**Comment by skoshelev** [comment]
When manually interfering with the database structure, you also need to delete entries from the MigrationVersionInfo table related to the plugin, in particular for the Shipping.FixedByWeightByTotal plugin, you must delete the entry with the description = "Shipping.FixedByWeightByTotal base schema"

Closed #4459
