### ISSUE TITLE
ProductLoadAllPaged SP Returning First Mapping Display Order

### ISSUE THREAD

**Issue by ash-grennan** [nopSolutions/nopCommerce#4460]
nopCommerce version: 
4.1

Steps to reproduce the problem: 
- Catalog > enable Position to be the default for sorting
- Create several categories
- Create several products
- Assign a chosen product to more than one category
- Change the Display Order for each product category mapping for chosen product
- Load the category with the smallest display order value for chosen product
- The position will appear wrong (providing there's already ordered products in said category)

The issue is the SP is selecting the first product category mapping records display value, not the one tied to the actual category id we're trying to load, therefore serving the wrong display order.

The display order for Position is LN 581 in the SP

Thanks
![sp-ss](https://user-images.githubusercontent.com/8833566/78351487-c6464d00-759e-11ea-8069-7fae65c1c7d3.PNG)

**Comment by AndreiMaz** [comment]
we don't use stored procedures anymore
