### ISSUE TITLE
4.30 Image Upload Button and Image?

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4461]
nopCommerce version: 
4.30 

Steps to reproduce the problem: 
1) Edit a Category
2) For the Picture box I just have a number and no Upload button
3) Not sure if this is just my screen, but wanted to point it out

![image](https://user-images.githubusercontent.com/20989983/78360219-73f83280-7584-11ea-8ff3-536732d0ec7d.png)

**Comment by AndreiMaz** [comment]
Thanks. already reported - https://github.com/nopSolutions/nopCommerce/issues/4402
