### ISSUE TITLE
Cant edit Pixel Id and store

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4463]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
add Facebook Pixel id, then try edit pixel id or Store

**Comment by RomanovM** [comment]
@ecommerce-tester It's by design. After the initial configuration, it's not allowed to change the Pixel Id and the store for integrity purposes. If you need to change these settings, just delete the current one and create a new configuration.
