### ISSUE TITLE
SQL Server password should be hidden during installation

### ISSUE THREAD

**Issue by ilyaspatel92** [nopSolutions/nopCommerce#4464]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
Try to install the nopcommerce 4.30 beta , 
At installation page in SQL Password, text box type is change password to text
Here is the screenshot: https://prnt.sc/rsjawo

**Comment by jeeckeman** [comment]
Hello, 
The fix i purpose is in the file : 
/src/Libraries/Nop.Data/INopConnectionStringInfo.cs

Add the first line : 
+using System.ComponentModel.DataAnnotations;

and before the line 33 : 
+DataType(DataType.Password)]
string Password { get; set; }

Please be indulgent, it is my first fix :)

**Comment by holydk** [comment]
Closed #4464
