### ISSUE TITLE
4.30 Remove Address when checking out "Sequence contains no elements"

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4465]
nopCommerce version: 
4.30

Steps to reproduce the problem: 

1. Have 2 addresses in your address book
2. Start to check out
3. Delete one of the addresses from your book
4. Continue to try and check out
5. I get the error when trying to finish paying OR when I leave the page and try to go back into my cart

I keep getting System.InvalidOperationException: 'Sequence contains no elements'

I cleared my cache in my browser and through NopAdmin

**CustomerService.cs**
![image](https://user-images.githubusercontent.com/20989983/78414667-41cdeb80-75eb-11ea-8599-a871de8c0c65.png)

The address ID being passed in is 4206
![image](https://user-images.githubusercontent.com/20989983/78414738-8bb6d180-75eb-11ea-82da-eba0ec9f07c2.png)

But I think that address is the one I deleted
![image](https://user-images.githubusercontent.com/20989983/78414751-a0936500-75eb-11ea-8161-3d8f7cd9cf40.png)

**Comment by holydk** [comment]
Closed #4465
