### ISSUE TITLE
Getting error while update message template (Email account dropdown value set to all)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4466]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1)  pull latest changes.

2) Go /Admin/MessageTemplate/Edit/2

3) Find Email account -> set Value to **ALL**	

Click save and continue

You will get error.

<img width="936" alt="40" src="https://user-images.githubusercontent.com/41533502/78422653-70e16d00-767e-11ea-958a-cb31bcb1507f.png">

**Comment by skoshelev** [comment]
Closed #4466
