### ISSUE TITLE
Email friend Wishlist page - Personal message should be textarea

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4468]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Add any item to wishlist
Go to wishlist page
Click on Email a friend button
See here, personal message input is a textbox. it would be good it have textarea

![03_emailafriend](https://user-images.githubusercontent.com/13154058/78423497-4db9bc00-7684-11ea-9de8-62d81116874b.png)

**Comment by badijm** [comment]
@rajupaladiya Hi, I've just checked and it already **<textarea>**. 
So no issue here.
But we can improve it in another way - restrict resizing.

![image](https://user-images.githubusercontent.com/22330489/89993758-cd682080-dc4c-11ea-985e-ebd48dd000e7.png)


![image](https://user-images.githubusercontent.com/22330489/89993553-7eba8680-dc4c-11ea-8ff0-71a76b31f13e.png)
