### ISSUE TITLE
Provide ability to crop Avatar using jCrop

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#447]
Currently, nopCommerce resizes image based on the longest side, however if the width is longer it will get squished to the maximum width. To have nicer avatar images, it would be best to allow the user to select which portion of the image they want and save the dimensions along with the cropped image in the database. This can be accomplished pretty easy using a jquery plugin called jCrop. 

http://deepliquid.com/projects/Jcrop/demos.php 

Forum source: http://www.nopcommerce.com/boards/t/16542/feature-request-provide-ability-to-crop-avatar-using-jcrop.aspx

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/240
