### ISSUE TITLE
nopCommerce version: 4.30 Beta Install Error using MySQL 5.7 

### ISSUE THREAD

**Issue by DavidMills02** [nopSolutions/nopCommerce#4476]
nopCommerce version: 4.30 Beta

I downloaded nopCommerce version: 4.30 Beta today 05/04/2020
Installed nopCommerce version: 4.30 Beta on Visual Studio 2019 16.5.2
NET.Core 3.1.3 is installed
MySQL version 5.7.29.0 installed

Steps to reproduce the problem: 
I started the Installation of nopCommerce version: 4.30 using the Create Database option
Set Database to MySQL and set the MySQL Host details

That creates the error
Setup failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'recursive CategoryTree AS ( SELECT id, cast(concat(LPAD(DisplayOrder, @lengt' at line 1

Database is created when I check with MySQL Workbench
I clicked on Restart the Installation and set the connection string to the database
This creates the error 
Setup failed: FUNCTION Check_Exists_FullText_Index already exists

When I re-do the Installation with or without using the connection string the same error is shown
Setup failed: FUNCTION Check_Exists_FullText_Index already exists

Detailed Error Information:
Module | AspNetCoreModuleV2
ExecuteRequestHandler
aspNetCore
0x8007045b

Regards

**Comment by ChrisJollyAU** [comment]
Isn't this fixed from #4394 ?

**Comment by iori-xia** [comment]
> Isn't this fixed from #4394 ?

No,I think.

**Comment by iori-xia** [comment]
> Isn't this fixed from #4394 ?

I have the same problem today.
I Deleted the Check_Exists_FullText_Index Function and retry.
The problem was solved.

**Comment by ChrisJollyAU** [comment]
@iori-xia Are you running the beta or the latest source code? You need the latest code for that fix

**Comment by iori-xia** [comment]
@ChrisJollyAU 
About 8 hours ago, the develop branch.

**Comment by DavidMills02** [comment]
Thank you - True -  Delete the Check_Exists_FullText_Index Function and retry.
The problem is solved.

**Comment by DavidMills02** [comment]
> @iori-xia Are you running the beta or the latest source code? You need the latest code for that fix

Yes - the download of the source code was done today 05/04/2020

The solution to make it work as suggested above -  Delete the Check_Exists_FullText_Index Function and retry.
The problem is solved.

**Comment by wangweinjcn** [comment]
> > Isn't this fixed from #4394 ?
> 
> I have the same problem today.
> I Deleted the Check_Exists_FullText_Index Function and retry.
> The problem was solved.
how to soved? delete the function, then reinstall?

**Comment by jkeating11** [comment]
`src/Presentation/Nop.Web/App_Data/Install/MySQL.StoredProcedures.sql`

There are three Check_Exists+FullText+Index here which one do I delete?

I'm using 4.4
