### ISSUE TITLE
Fix some Simplified Chinese localization texts.

### ISSUE THREAD

**Issue by byteflying** [nopSolutions/nopCommerce#4477]
nopCommerce version: 
4.30 (develop branch)

Steps to reproduce the problem: 
1.I need to fix some Simplified Chinese localization texts.
2.I will carefully compared each line to make sure there was no mistake.
3.Thx 4 ur reading.

**Comment by JadynWong** [comment]
All installation translation `installation. *. xml` should be changed.

The historical version of nop only supports 4.2. Version 4.3 added MySQL support, but the name of the translation key was tightly modified.
https://github.com/nopSolutions/nopCommerce/commit/0968d6cac4351b4f9a6f41b7c108996f199456d5#diff-3ba7e2ba30aad08aa89ad7b2b27bae72

**Comment by byteflying** [comment]
already done

**Comment by AndreiMaz** [comment]
Merged 
@byteflying @JadynWong Thanks a lot!
