### ISSUE TITLE
Reward points don't reduce total Actually Paid with PayPal Smart Payment Buttons

### ISSUE THREAD

**Issue by neo302** [nopSolutions/nopCommerce#4481]
nopCommerce version: 
4.3 
Steps to reproduce the problem: 
Go to cart.
Agree to terms
Click PayPal button
When you get to Payment Method, it has box to use reward points to reduce the price, click it. 
Radio button has "PayPal Smart Payment Buttons" selected.
Click continue.
Click PayPal again.
PayPal pop-up loads with total **without** points included - shows original, not discounted price. 
Upon returning to NopCommerce, the confirm order shows discounted total. 
Confirm payment.
Log into PayPal account and see the **full** amount was paid, not the discounted amount.
Order in NopCommerce shows the discounted amount was charged when that is not the case.

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/cd132abb2d26628595df36a7af3f80b52b10a58d
