### ISSUE TITLE
Search engine friendly names doesn't get updated when edited from the edit product page 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4483]
Search engine friendly names doesn't get updated when edited from the edit product page and also it doesn't create new ones when adding a new product. I tried on localhost and also on azure web host.

Source: https://www.nopcommerce.com/boards/topic/80144/find-bugs-in-nopcommerce-430-beta-and-earn-10/page/5#261483

**Comment by sk5202** [comment]
i think duplicate #4391

**Comment by AndreiMaz** [comment]
@sk5202 Right. Thanks, Smiten!

**Comment by sk5202** [comment]
@AndreiMaz  your welcome
