### ISSUE TITLE
Product edit page on category selecting category cache issue

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#4484]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
Go => to => Admin => Product edit page
1. Select category 
2. Click on save to continue button
3. Admin user can not show selected category in multi-select dropdown box.
4. Clear cache 
5. After clear cache aAdmin user can show selected category in multi-select dropdown box.
Please verify it.

https://www.loom.com/share/4881dad97904436d8091890d2392c68b

**Comment by skoshelev** [comment]
Hi @sagarnop. Thank you for your help. But I can't reproduce this problem on the last source code.

Closed #4484
