### ISSUE TITLE
Product detail page on category breadcrumb not display with current category.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#4486]
nopCommerce Version: 4.30

Steps to reproduce the problem: 
# Admin side: 
        1. Go to => Admin => Product edit page (product name: Build your own computer)
        2. Add two categories : 1) computer =>  Desktop 2) Electronics => Camera & photo
# Front side:  
        1. Click on Computer menu.
        2.  Computer category in click on Desktop category.
        3.  Click on Build your computer product and user will show a breadcrumb like  "Home /Computers /Desktops /Build your own computer "

        4. Click on Electronics menu.
        5.  Electronics category in click on Camera & photo category.
        6.  Click on Build your computer product and user will show a breadcrumb like  "Home /Computers /Desktops /Build your own computer "   
Here, the user goes through with Electronics => Camera & photo category, So why here the user sees the wrong breadcrumb.

"Home /Electronics / Camera & photo/Build your own computer "  this is the actual breadcrumb when the user goes through with Electronics => Camera & photo category.

Please verify it.

https://www.loom.com/share/95e9a6d6086846eda7ae3559e39154b2

**Comment by AndreiMaz** [comment]
Thanks. We know about that but don't consider that as a bug.
