### ISSUE TITLE
Wish-list page - When clicking on add to cart button it is not showing any message that select checkbox first.

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#4487]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1. Add item in wish-list.
2. Go to wish-list page.
3. When clicking on add to cart button it is not showing any message that i have to select checkbox first.

https://www.loom.com/share/cb739e438ff74c95a714242220cb8f08

**Comment by DmitriyKulagin** [comment]
Closed #4487
