### ISSUE TITLE
Message is missing - Customer info save button my account page

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#4489]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1. Login to your nopcommerce 4.3 beta
2. Go to my account
3. Go to customer info and click save button. nothing is showing that data saved or not. message should be display
https://www.loom.com/share/f1c3a9712ec24118a32339f85730a315

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/3755
