### ISSUE TITLE
Plugin disappears from local plugins list when uninstalled

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4490]

**Comment by AndreiMaz** [comment]
All by design

**Comment by mariannk** [comment]
@AndreiMaz we need to remove "Load mode" filter from this page and change the Manual plugin installation instructions then. Agree?

**Comment by AndreiMaz** [comment]
@mariannk 
1. "Load more" filter is still required
2. Instructions - agree - https://github.com/nopSolutions/nopCommerce/issues/4496
