### ISSUE TITLE
While order list empty Click on **Print PDF Invoices (All Found)**. Error thrown

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#4493]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1) Go to order list page admin side.
2) While order list is empty after search something wrong. Click on **Print PDF Invoices (All Found)**. Error thrown
https://ibb.co/b1867tq

https://www.loom.com/share/8b166f0bf9fd43a88d61e13b371c70a7

**Comment by skoshelev** [comment]
Closed #4493

**Comment by forefrontinfotech** [comment]
@skoshelev thank you the fixing :)
