### ISSUE TITLE
Required Validation. Customer birth date should not be future date while creating customer from admin side

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#4497]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1) Go customer list admin side
2) Try to create new customer
3) Add future date in birth date field. Then also customer is creating successfully. Require validation

https://www.loom.com/share/56d68ecf512848d0838c006c7826812a

**Comment by AndreiMaz** [comment]
Thanks. But we don't consider that as real bug. Especially when a store owner enters this date
