### ISSUE TITLE
Model should be fill out once perform any post action at order listing page 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4498]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Place one order and Go /Admin/Order/List

2) Search same order with by filling start date and end date 

Ex - If you place order today than today is 04(MM)/06(DD)/2020(YYYY) 
Start date - 04/06/2020
End date - 05/06/2020

3) Now fill the product text box with same product name which you placed recently 

4) Now click on **Print PDF invoice (selected)**

**And see all search value disappeared it should be filled** 

https://www.loom.com/share/9043f9ddc2344fcf98739cb7c863921d

**Comment by sk5202** [comment]
same should be here Admin/Order/ShipmentList

**Comment by sk5202** [comment]
Hello,  This task i was created 8 day ago but still no progress @AndreiMaz

**Comment by DmitriyKulagin** [comment]
Closed #4498
