### ISSUE TITLE
reCAPTCHA v3 a problem with the value of the "score threshold" field when changing culture

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4499]
nopCommerce version: 4.30 (beta)

> Using fr-BE as Language culture. if you change reCAPTCHA v3 score threshold to any number you get a validation error. (The field must be a number.)

![image](https://user-images.githubusercontent.com/27218280/78567244-0caedc80-7829-11ea-99d9-952047591b61.png)

Source: https://www.nopcommerce.com/boards/topic/80144/find-bugs-in-nopcommerce-430-beta-and-earn-10/page/4#261436

**Comment by holydk** [comment]
Closed #4499
