### ISSUE TITLE
Buy 2 get 1 free discounts. Notify about free products. Option to add them automatically to the cart

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#45]
Notifications about discounted products and automatical way to add "free" products. One more issue is that you have to manually add "free" product to the cart. So we need to find a way to notify a customer about this free product. We should show a message on the product page i.e. "Buy one more and get a free gift" or "Buy product Y for a discount" etc. We only way to implement it is the following. Load ALL products on the shopping cart page. Calculate price for EACH of them considering discounts and all possible discount requirements. If price is 0 and some discount is applied, then add this product to the cart. But it'll simply kill the performance. Of course, we can implement kind of rules (e.g. "if product 1 with qty 2 is in the cart, then add qty 3") but this way we'll lose all advantages of "Discount" entity (e.g. start/end dates. discount requirements, etc). Of course, we can also use tier prices to apply such discounts. It's the easiest way to go if you're talking about the same products. 

Forums source: http://www.nopcommerce.com/boards/t/14298/buy-2-get-the-3rd-one-free.aspx

Let's see whether it's available as a plugin (http://www.nopcommerce.com/p/2589/bundled-discounts-buy-together-plugin.aspx). If yes, we can postpone it

**Comment by AndreiMaz** [comment]
duplicates #1927
