### ISSUE TITLE
Quantity field on category page (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#450]
Also add this field on all product boxes (manufacturer details page, products by tag), etc. Make this option configurable. 

Forum source (contribution): http://www.nopcommerce.com/boards/t/14394/quantity-field-on-category-page.aspx

**Comment by johannwalder** [comment]
If not mistaken this link points to a newer implementation of the same requirement: http://www.nopcommerce.com/boards/t/24852/add-the-quantity-textbox-next-to-addtocart-button-when-you-are-exploring-the-products.aspx

Just in case someone is looking for it.
