### ISSUE TITLE
SendinBlue Configuration - Tracker Id is not updated, multiple warning and error message displayed

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4500]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/SendinBlue/Configure

2) Add dummy value at step 2 - Connect your store to SendinBlue 

3) Go Marketing Automation panel

4) Use Marketing Automation  set to enable
    Add some value at **tracking Id** text box
   Click Save

5) **Value is not updated.**

Click on **Sync Now** button from Manual synchronization You will get same warning multiple time Which is not relevant

<img width="942" alt="41" src="https://user-images.githubusercontent.com/41533502/78578645-6cb77a00-784d-11ea-80cd-96705f4d4bda.png">

https://www.loom.com/share/6fcb7e46b6824c578b199dab10621d53

**Comment by DmitriyKulagin** [comment]
@sk5202 In step 2, you enter "dummy value" for the API v3 key location. Configure the plugin as instructed, the plugin does not have access to your SendinBlue account.
