### ISSUE TITLE
Creating a Customer Role does not require a "System Name", then errors on role to customer assignment.

### ISSUE THREAD

**Issue by neo302** [nopSolutions/nopCommerce#4502]
nopCommerce version: 
4.3
Steps to reproduce the problem: 
Create a new Customer Role, which doesn't require a "System Name".
When you try to assign the new role to a customer, NopCommerce errors with:
Value cannot be null. (Parameter 'customerRoleSystemName')

**Comment by skoshelev** [comment]
Closed #4502
