### ISSUE TITLE
HOST values field should be display with basic mode under store edit page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4504]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to store edit page and change mode to basic.

Here in basic mode, store URL field is display but Host value field displays only with advance mode.
If we change store url then we must need to change host values also, so this should be visible with basic mode.

SSL enable - we can move this in advance setting

**Comment by AndreiMaz** [comment]
It's also by design
