### ISSUE TITLE
Square payment : Use sandbox checkbox is not working properly 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4505]
nopCommerce version:  4.30 beta

Steps to reproduce the problem: 

1) Go Admin/PaymentSquare/Configure

2) Click on **Obtain Access token**

3) It will redirect to new domain for getting access token.

4) Go back to Configuration page 

5) check Use sandbox checkbox 

6) It is roll back to uncheck even i cleared cache

not working

https://www.loom.com/share/a1c0a29cd5434e27ace3e75c2a38d226

**Comment by holydk** [comment]
It will be fixed in #4133 . Closed #4505

**Comment by sk5202** [comment]
That's also good but i see that #4133 issue posted  on 2019. Now again appear this bug so you should mark as bug label #4505 
And remove from  discussion and investigation.

What you think am i right ?

@holydk  @AndreiMaz

**Comment by sk5202** [comment]
@AndreiMaz ??

**Comment by sk5202** [comment]
Hello,

Could you please ans on this @holydk @AndreiMaz ?

**Comment by AndreiMaz** [comment]
@sk5202 This bug was already reported at https://github.com/nopSolutions/nopCommerce/issues/4133 (more general issue)
