### ISSUE TITLE
Delete confirmation popup is missing on Activity log page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4506]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to admin  > Customers > Activity Log page

Click on Clear button which is at top right corner.

Text should be **Clear All** or **Clear Activity Log ** instead of only **Clear**

It should display confirmation popup like the below image.

![__1_clear](https://user-images.githubusercontent.com/13154058/78584009-367df880-7855-11ea-888c-0a007bdce832.png)

**Comment by exileDev** [comment]
Closed #4506
