### ISSUE TITLE
Registration success message contained "Membership" word

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4507]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to customer setting
Select **Email validation is required after registration** method as **Registration method**

Go to registration page, fill form and submit it.
After submit form, it displays below message:

**Your registration has been successfully completed. You have just been sent an email containing membership activation instructions.**

![__register](https://user-images.githubusercontent.com/13154058/78584840-798c9b80-7856-11ea-9724-358ea98f9018.png)

Here used membership words instead of registration. Normally membership word uses when registration type paid and it for specific time like 1-month subscription, quarterly or yearly subscription.
--------------

[A.M.] Let's update it to "Your registration has been successfully completed. You have just been sent an email containing activation instructions."

**Comment by holydk** [comment]
Closed #4507
