### ISSUE TITLE
Shipping method Add and Edit are not working - Getting AutoMapperMappingException Error

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4508]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1)  /Admin/Shipping/EditMethod/1

2) Click save and continue

getting below error

<img width="883" alt="43" src="https://user-images.githubusercontent.com/41533502/78585912-45b27580-7858-11ea-8bb4-dfbb37a02b86.png">

**Comment by skoshelev** [comment]
Closed #4508
