### ISSUE TITLE
Not able to add any item to cart as guest user

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4509]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Add any product to cart as a guest customer.
You can see success notification and item in flyout cart but when you visit to cart page, it shows empty.

**Note: I'm using the latest source code, pulled just before an hour from develop branch.**

Also, it creates a new guest user on every page refresh.

See this video - https://www.loom.com/share/3de21545a0ef4a5eb6ed9d8495bc4b7c

**Comment by skoshelev** [comment]
Closed #4509
