### ISSUE TITLE
Encrypt some sensitive settings

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#451]
You're not alone in understanding the risk of storing sensitive information in plain text. Such as some settings, EmailAccount, etc

Source: http://www.nopcommerce.com/boards/t/12711/encryption-and-merchant-login.aspx

P.S. ensure that it'll work fine when changing "Encryption key" in admin area. it should also work fine after upgrade from previous version (when settings were not encrypted). Although we can add a new column in this case indicating whether it's encrypted. It'll allow us to easily upgrade (do not use [SettingStorageFormat(Format.Encrypted)] )

**Comment by rudgr** [comment]
Considering this is a security risk, can this be placed on v3.90 roadmap/milestone? tx

**Comment by pmccloghrylaing** [comment]
Seems like it would need to do the following:
- When storing, check for the attribute, if it exists encrypt and mark the value as encrypted (in a separate column).
- When retrieving, check if it's encrypted, then decrypt if necessary.
- When the encryption key changes, decrypt and re-encrypt all the encrypted settings.

Does there need to be a step for upgrading? And is there anything we can do to prevent it showing in plain text on admin pages?

**Comment by pmccloghrylaing** [comment]
Managed to get most of this working relatively well, then I discovered that the encryption key is stored in the Settings table as well. Considering the plan was to encrypt and decrypt values when they're stored and retrieved from the DB, this seems to add no real security. Has there been any thought into providing alternative options for encryption key storage? I know SQL injection isn't something to worry about, but still: http://security.stackexchange.com/a/12334

**Comment by AndreiMaz** [comment]
actually with this logic we should encrypt all information in database. customer info, order info, etc, etc

decided not to implement

**Comment by pantonis** [comment]
@AndreiMaz encrypting password is rule **number one** in Digital security.  Customer info, order info etc are critical but not critical enough as an email password. Consider that an attacker that gets access to an email address. Especially when it has to do with an enterprise that sells data online. It would be disastrous.

**Comment by ivanslater** [comment]
Once the encryption key is also stores in the same DB and the e-commerce source code is available online for free, there is increase of security by encrypting all those data. Someone who with full/partial access to the database either by legal/hacking methods will find no problem in decrypting those data. We should think on a better security system for that.

**Comment by AndreiMaz** [comment]
after some consideration we've decided not to implement this functionality out of the box
