### ISSUE TITLE
GDPR - Admin notification and customer edit page link is missing on GDPR request page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4510]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to admin and enable GDPR from Configuration > Settings > GDPR Setting

Now login with any existing user and go to my account.
From left side navigation, go to GDPR Tools page

Here click on **Delete Account** button

It'll show message: **We'll process your request as soon as possible**
Note: Here account is not deleting, it just log entry in GDPR request table.
![__gdpr_!](https://user-images.githubusercontent.com/13154058/78590837-1a338900-7860-11ea-8e5a-1d79b6f9918b.png)

Now login with admin and go to Customers > GDPR requests (log) page. (yourstore.com//Admin/Customer/GdprLog)

In the request log grid, the customer edit page link is missing in the customer info column. Admin should redirect to the customer edit page for the delete account.
![__gdpr_2](https://user-images.githubusercontent.com/13154058/78591184-a776dd80-7860-11ea-9690-ed0caecc477c.png)

Also, the admin should receive an email on the request of delete account from GDPR tools page. Without this admin can't know there is new notification arrives or not.

**Comment by AndreiMaz** [comment]
Thanks. But everything is by design
