### ISSUE TITLE
New widget zone in AdminHeaderLinks

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4511]
nopCommerce version: 
4.30

This isn't an issue, but a suggestion. 

Could you add a Widget area in the AdminHeaderLinks? I have a few plugins I'd like to link directly to them. Right now I just edit the file, but maybe other people may like to add links there with their plugins.

**Comment by AndreiMaz** [comment]
@DmitriyKulagin Let's add a new one before the closing <div> tag - https://github.com/nopSolutions/nopCommerce/blob/95fe797ea67f8a1147398e50143d54861b80210d/src/Presentation/Nop.Web/Views/Shared/Components/AdminHeaderLinks/Default.cshtml#L20

**Comment by Ochapparel** [comment]
Awesome!

**Comment by DmitriyKulagin** [comment]
Closed #4511

**Comment by Ochapparel** [comment]
You guys really do rock!
