### ISSUE TITLE
New Widget in Shipping Address Pickup Point Section

### ISSUE THREAD

**Issue by stntz** [nopSolutions/nopCommerce#4512]
nopCommerce version: 4.20 - 4.30

Steps to reproduce the problem: I am building a plugin that requires delivery slot selector for pick up. Would be nice to have a widget within (at the end of the address/pickup fee) the pickup section of the OpcShippingAddress and ShippingAddress to insert the table for time selector.

I was able to achieve the same delivery slots in Shipping Methods view like attached

<img width="1002" alt="Screenshot 2020-04-07 at 17 21 16" src="https://user-images.githubusercontent.com/12134684/78694219-400a6d80-78f4-11ea-91b9-f5994216109c.png">

**Comment by holydk** [comment]
Closed #4512
