### ISSUE TITLE
Unable to update stock quantities when trying to update the qty in the edit form of the attribute combination.

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#4513]
nopCommerce version: 4.30 beta

Error: Unable to update stock quantities when trying to update the qty in the edit form of the attribute combination.

The error message says "The same combination already exists" even though I was just trying to update the stock quantities in the combination attributes, not adding new combination.

Source: https://www.nopcommerce.com/boards/topic/80144/find-bugs-in-nopcommerce-430-beta-and-earn-10/page/7#261597

**Comment by DmitriyKulagin** [comment]
Closed #4513
