### ISSUE TITLE
Order>>Shipping method>> Edit 

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4516]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: in Order>>Shipping method
when we want to Edit Shipping method, opens TextArea.
Needs to change TextArea to Selector.

**Comment by AndreiMaz** [comment]
It's by design

**Comment by ecommerce-tester** [comment]
![text](https://user-images.githubusercontent.com/43282933/78784467-6f81ae80-79b6-11ea-90e3-efaa4417bbbb.png)
