### ISSUE TITLE
Pickup.PickupInStore Plugin

### ISSUE THREAD

**Issue by kwiksys** [nopSolutions/nopCommerce#4518]
nopCommerce version:  beta 4.3

Admin/Shipping/CreateMethod

Mapping types:
ShippingMethodModel -> ShippingMethod
Nop.Web.Areas.Admin.Models.Shipping.ShippingMethodModel -> Nop.Core.Domain.Shipping.ShippingMethod

Error

AutoMapperMappingException: Missing type map configuration or unsupported mapping. Mapping types: ShippingMethodModel -> ShippingMethod Nop.Web.Areas.Admin.Models.Shipping.ShippingMethodModel -> Nop.Core.Domain.Shipping.ShippingMethod

    lambda_method(Closure , ShippingMethodModel , ShippingMethod , ResolutionContext )
    AutoMapper.Mapper.Map<TSource, TDestination>(TSource source, TDestination destination)
    Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions.MappingExtensions.MapTo<TSource, TDestination>(TSource source, TDestination destination) in MappingExtensions.cs
    Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions.MappingExtensions.ToEntity<TEntity, TModel>(TModel model, TEntity entity) in MappingExtensions.cs
    Nop.Web.Areas.Admin.Controllers.ShippingController.EditMethod(ShippingMethodModel model, bool continueEditing) in ShippingController.cs
    lambda_method(Closure , object , object[] )

Steps to reproduce the problem: 

Configuration -> Shipping -> Shipping Providers

Add a new shipping method  -> then Save  -> result in the above 
[error.txt](https://github.com/nopSolutions/nopCommerce/files/4450258/error.txt)
 error

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4508
