### ISSUE TITLE
Plugin disappear after installed

### ISSUE THREAD

**Issue by tejasmistry19** [nopSolutions/nopCommerce#4519]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1. Go to <storeurl>/Admin/Plugin/List
2. Install any plugin.
3. After installation completed, click on "Restart application to apply changes" button.
4. Check the plugin list after restart, last installed plugin is disappeared.
5. Try clean and build project, execute the project and refresh the step 1. Now can find the plugin in list.

**Comment by skoshelev** [comment]
Can't reproduce this problem, plugins installation function works as expected

Closed  #4519
