### ISSUE TITLE
Performance. Cache Settings objects in ConfigurationProvider

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#452]
The various system settings in nopCommerce are used in pretty much every controller, so Dependency Resolution is constantly going to ConfigurationProvider to create instances of the various settings objects 

The ConfigurationProvider class is using _settingService which itself is using the static cache to access the various stored property values in BuildConfiguration - however, this routine is currently being called many many times per controller access. With the various PartialView methods making up the Views, each call to a method is causing settings objects to be recreated 

Suggestion: How about caching the Settings objects themselves, rather than the various strings in _settingService? Add an ICacheManager to the ConfigurationProvider ctor and cache there? 

e.g. something like...

```
public class ConfigurationProvider<TSettings> : IConfigurationProvider<TSettings> where TSettings : ISettings, new()
{
    readonly ISettingService _settingService;
    private readonly ICacheManager _cacheManager;

    public ConfigurationProvider(ISettingService settingService, ICacheManager cacheManager) 
    {
        this._cacheManager = cacheManager;
        this._settingService = settingService;

        // However you want to do this cache key, comething like this? 
        string cacheKey = string.Format("nop.core.configuration.settings.{0}", typeof(TSettings).ToString());
        if (_cacheManager.IsSet(cacheKey))
            this.Settings = _cacheManager.Get<TSettings>(cacheKey);
        else
        {
            this.BuildConfiguration();
            this._cacheManager.Set(cacheKey, this.Settings, 60);
        }
    }

    // etc etc
```

And in DependencyRegistar, make sure it's a static cache

```
builder.RegisterGeneric(typeof(ConfigurationProvider<>)).As(typeof(IConfigurationProvider<>))
               .WithParameter(ResolvedParameter.ForNamed<ICacheManager>("nop_cache_static"));
```

There is quite high CPU usage at the moment when navigating around nopCommerce, the ConfigurationProvider is one of the most used objects - this would take a bit of load off (at the cost of some memory). Could probably make some changes to SettingService as well, so that the settings values + the setting objects aren't both cached.

Any thoughts? 

Source: http://www.nopcommerce.com/boards/t/12600/suggestion-cache-settings-objects-in-configurationprovider.aspx

**Comment by AndreiMaz** [comment]
decided to stay with the current approach
