### ISSUE TITLE
When enable Ship to the same address (Billing Address) - Pick up point charge unable to apply 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4521]
nopCommerce version: beta 4.30

Steps to reproduce the problem:  

1) So just add one item which have no shipping. Go cart page click on **estimate shipping** 
2) Choose pick up from pop up 
3) click on checkout and enable - Ship to the same address
4) It will directly move to shipping method and after continue you will find in order summary **pick up charge is not display.**

Solution - If i select **same as shipping one checkbox** than pick up check box should be populate there because at this time pick up selection at only shipping address step that's why charge is not applied when i select Ship to the same address.

**See the video.**

https://www.loom.com/share/976d67e0f7c64dfc833670af6ea57b42

**Comment by stntz** [comment]
@sk5202 that makes sense though, if you select ship to same address, then you don't want to pick up the item. 
if you want to pick up the items, you won't select ship to your billing address.

Estimate shipping is just a calculator not your shipping method

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
