### ISSUE TITLE
The Value "" is invalid 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4522]
nopCommerce version: 4.30 beta

Steps to reproduce the problem:  

1) Go /Admin/Tax/Categories

2) Add one tax category and **click save**

3) After **again click save**(Leave text boxes as it is after above click(step2) ) it will display **The Value "" is invalid** because of Display order Value become null or Empty after add record.

It should be 0 or validation message should be changed.

Changable location

1)  Admin/Measure/List 
2)  /Admin/Product/Edit/25  - picture panel
3) /Admin/Template/List
4) /Admin/Poll/Edit/1

here i reproduced this issue check this video

https://www.loom.com/share/c149f26a73c94e41a385d84b925a8404

**Comment by skoshelev** [comment]
Closed #4522
