### ISSUE TITLE
Do not cache "heavy" entities per HTTP requests

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4524]
Download - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Media/DownloadService.cs#L46

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce/commit/640214041ad8a3a89ae730c6554664ef9d305944

Closed #4524
