### ISSUE TITLE
News detail page is not validate with Start date and End date 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4525]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) /Admin/News/NewsItemEdit/1

2) add some past date at start and end date datepicker

3) Click on preview.

It should be redirect to home page based on start and end date validation even i perform action like news comment at news detail page.So better to redirect home page at that case.

But when you go home page validation worked you can not see there news.

See the video 

https://www.loom.com/share/db3162a8763c4857991647ee1b0a21e8

**Comment by sk5202** [comment]
Event, i did publish false than i allowed to add comment on news it should be validate based on dates and publish fields.

**Comment by sk5202** [comment]
Even, Blog have same issue 
/Admin/Blog/BlogPostEdit/2

**Comment by AndreiMaz** [comment]
Thanks. But we don't consider it as a bug. You're in admin mode. 

It'll just require too much extra logic just to validate "admin preview" mode actions in stores

**Comment by sk5202** [comment]
@AndreiMaz  yaa that's right but what happened when some  customer(non admin role) knows news detail url at that time they easily comment news by fill up 2 fields.

Than customer should be prevent to fill news comment as well as blog commerce while both are out of date.

What you say  at that case ? 

:-)

**Comment by AndreiMaz** [comment]
@sk5202 it's not possible to visit it for non-admin users - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/NewsController.cs#L135 and https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/NewsController.cs#L141

**Comment by sk5202** [comment]
yaa i forgot to check that condition anyway thanks. @AndreiMaz
