### ISSUE TITLE
Topics with same url per store still not working

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#4528]
nopCommerce version: 4.30
Related issues: #4028 and #4057 
Steps to reproduce the problem: 

We need an ability to have same SE names or URL per store with different content. This is an important feature in eCommerce and an important part of CMS.

Above related issues were closed because I think that time, no one understood actual issue that we wanted to describe.
I have described it again here https://github.com/nopSolutions/nopCommerce/issues/4028#issuecomment-611368376

I am sorry that this is a duplicate of above two but it would be better if we could get this feature in current version itself without waiting more.
https://www.nopcommerce.com/boards/topic/71171/per-store-topic-page-for-pagenotfound

@AndreiMaz please see this.

**Comment by AndreiMaz** [comment]
@atulrungta Thanks for suggestion. But unfortunately, we don't plan to implement that. Topic configuration per store will make management just much more complex. Furthermore, if we would decide to implement, then why only topics? Why not other entities

There are only two ways to go:
1. Use different topics with different URLs for each store
2.  Create a new page (with a controller, routing, a view). Its URL will be the same for all stores. Then reference your topic by systemname in your view. So you can create multiple topics (limited by a store) with the same systemname
