### ISSUE TITLE
Reduce number of created guest customers when a user logout

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#453]
I think I found a problem in the default implementation of Nop.Core.IWorkContext (Nop.Services.WorkContext): the customer cookie is always set, even when the customer is authenticated. Moreover, when no user is authenticated, the customer cookie is read and if the corresponding is registered, a new guest customer is created. So imagine the following sequence:
1. A customer is logged in and therefore the customer cookie has its guid;
2. The customer logs out: the WorkContext tries to create a guest from the guid but since it corresponds to a registered user, a new guest is created;
3. The customer logs in again: the customer cookie now contains the guid of the registered customer account;

If you repeat steps 2 and 3, a new guest user will be created each time. I think that can be avoided by only storing guests account guids in the customer cookie. 

Is that a desired behavior? Since the primary key is an int, a (very) successful store could run out of ids (and forced to switch to bigint) earlier than necessary. 

Source: http://www.nopcommerce.com/boards/t/11088/20-maintenance.aspx#45755

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. Anyway, they will deleted later
