### ISSUE TITLE
PayFast plugin gives error when installing on server with Nopcommerce 4.30

### ISSUE THREAD

**Issue by anmolrathod** [nopSolutions/nopCommerce#4532]
nopCommerce version:  4.30

Steps to reproduce the problem: 
The plugin works perfectly but as soon as i try to install it on the server it crashes the whole site and the plugin doesn't get installed. Following steps are to reproduce the exception that i am facing.
1) Upload the plugin from admin panel (The plugin gets uploaded and also get displayed in plugin list)
2) Install the plugin from plugin list.
[Payments.PayFast.zip](https://github.com/nopSolutions/nopCommerce/files/4458152/Payments.PayFast.zip)
![error](https://user-images.githubusercontent.com/25930402/78932545-56b3ee80-7ac5-11ea-8d65-24bf17b10560.png)

**Comment by AndreiMaz** [comment]
1. 4.30 is not released yet.
2. This plugin i not available out of the box - https://www.nopcommerce.com/payfast-payment-module
3. This plugin doesn't support 4.30 - "nopCommerce team doesn't plan to upgrade this plugin to the latest version. Our community is more than welcome to continue development of the plugin. Please feel free to use our source code."

**Comment by anmolrathod** [comment]
@AndreiMaz sir, i upgraded this PayFast plugin for both the Nopcommerce versions 4.20 and 4.30 as well. As i mentioned earlier that, after the upgrade the plugin is working normally but as soon as i upload and install it on the server its gives the an strange error which is crashing the whole site.
