### ISSUE TITLE
Decimals inputs are not properly edited

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4533]
nopCommerce version: 4.30 beta

Some of the inputs should have 4 digits. For example,

1. Currencies  (see "Rate" digits count) - 
![euro](https://user-images.githubusercontent.com/17789934/78935345-a0004000-7abd-11ea-9275-5c51729063c8.gif)
2. Product inputs - e.g. price, measures
3. Etc

All of them are displayed only with 2 digits now. It worked fine in 4.20

**Comment by DmitriyKulagin** [comment]
Closed #4533
