### ISSUE TITLE
Vendor attributes not working

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4534]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: Create Vendor attribute(i create DropDown List )
Go to vendor page and you can see that Vendor Attribute is Pre-Selected. I think its wrong.
When you select Vendor Attribute and save, its not show in Vendor Page.

**Comment by DmitriyKulagin** [comment]
@ecommerce-tester 
I tried to reproduce the situation you described, but everything works correctly. On the page "My account - Customer info" all values specified in Admin-> Vendor_Detail are saved. Please describe in more detail how to reproduce the error indicating the pages on which you are looking at the result. Or record a video.

**Comment by ecommerce-tester** [comment]
Sorry my mistake.
But when we create new Vendor Attributes, on old Vendor page Vendor Attribute is preselected.

**Comment by ecommerce-tester** [comment]
By default we have Vendor1 and Vendor2
We create New Vendor Attribute with name Test and options 1,2 and 3(Dropdown list)
We go to Vendor1 or Vendor2 page and see that Vendor Attribute with name Test and option 1.
But we Don't select Option 1 for that Vendors.

**Comment by ecommerce-tester** [comment]
Issue connected with Dropdown list only, other control types works fine.

**Comment by DmitriyKulagin** [comment]
@ecommerce-tester It works correctly by design
