### ISSUE TITLE
newsletter textbox in footer

### ISSUE THREAD

**Issue by Faarhad** [nopSolutions/nopCommerce#4536]
nopCommerce version: 
4.3
Steps to reproduce the problem: 
newsletter textbox in the footer in Firefox browser has a problem and it will solve with css

**Comment by AndreiMaz** [comment]
@Faarhad Could you please share a screenshot? It looks fine

**Comment by Faarhad** [comment]
sorry about that , I checked it again and, rebuild solution it solved.

**Comment by Faarhad** [comment]
sorry about that , I checked it again and, rebuild solution it solved.
