### ISSUE TITLE
Blank Categories Image

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4537]
nopCommerce version: 4.30 developer branch(about 2 month old)

Steps to reproduce the problem: 
Blank Categories Image
when i load my website(its randomly) i see some categories and listing photos gone. When i look that source i see that source address :127.0.0.1:29090 whats that?
I think that site attacked via remote. When i restart iis its fixed.

Here photo:
![Adsız](https://user-images.githubusercontent.com/7630189/78946280-fcb62780-7aca-11ea-9fd2-ee88cd1734cc.jpg)
And video of error:
https://youtu.be/kNsqf7-9pSw

**Comment by AndreiMaz** [comment]
Could you please test it on the latest "develop" branch? Two months ago it was too unstable

**Comment by AndreiMaz** [comment]
@mk148a Could you please test it on the latest "develop" branch? Two months ago it was too unstable

**Comment by mk148a** [comment]
> 
> 
> @mk148a Could you please test it on the latest "develop" branch? Two months ago it was too unstable

I want it but my plugins not compatible with netcore 3.1(i dont have source code).
It's Advanced Product Reviews Plugin for Nopcommerce. 
https://nopplugin.com/show-reviews-on-product-detail-page-plugin-for-nopcommerce

**Comment by AndreiMaz** [comment]
Unfortunately, we cannot reproduce the issue.

Maybe, it's caused by a wrong URL in admin area > configuration > stores. Maybe, wrong web farm configuration (if you use that)

**Comment by mk148a** [comment]
> 
> 
> Unfortunately, we cannot reproduce the issue.
> 
> Maybe, it's caused by a wrong URL in admin area > configuration > stores. Maybe, wrong web farm configuration (if you use that)

No its true configured, configure stores store url is my domain name. I dont use web farm, i think that have security issue and someones attack website from outside.
