### ISSUE TITLE
PayPal Smart Payment Buttons. Unable to modify Widget Zones in the Configure

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4538]
I removed "header_links_before" option or any other options but the all options are automatically back to the list when I clicked the save button.

**Comment by RomanovM** [comment]
We have replaced this setting with several separate checkboxes. See details in https://github.com/nopSolutions/nopCommerce/commit/cd132abb2d26628595df36a7af3f80b52b10a58d
