### ISSUE TITLE
Integration between nopCommerce and MS Dynamics AX (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#454]
It took a bit longer than expected but the integration between nopCommerce (1.90) and MS Dynamics AX is now ready. The solution is of 2 parts – add-on for nopCommerce and connector for Dynamics AX. They are available from www.geterp.net – I wasn’t very sure what is the format for publishing nopCommerce add-ons and because there were quite a few things changed I posted the entire source code in both source and compiled version. 
nopCommerce add-on is free of charge. It will be great if you review the add-on and advice if it can become part of the standard nopCommerce package. 

http://www.nopcommerce.com/p/180/nopcommerce-190-ms-dynamics-ax-add-on.aspx

**Comment by AndreiMaz** [comment]
should be done as plugin
