### ISSUE TITLE
Hide the "register" link in the header when registration is disabled

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#4540]
nopCommerce version: 4.30

Steps to reproduce the problem: 
It is not a bug but a small suggestion. When the registration is disabled the registration link in the HeaderLinks page can be headen completely because there is no fuction of the link button!  
One way to do that is by creating a bool in the HeaderLinksModel and change the value by checking the _customerSettings.UserRegistrationType in the commonmodelfactory. From there the value will pass it to the HeaderLinks\default page file and hide the button link.

**Comment by badijm** [comment]
Hi, I can pick this one too.

**Comment by badijm** [comment]
@AndreiMaz I've sent the pull request. Can u take a look? Also, I have bunch others open PRs to @nopCommerce

**Comment by holydk** [comment]
Closed #4540
