### ISSUE TITLE
Subdomain Cookie Support

### ISSUE THREAD

**Issue by stntz** [nopSolutions/nopCommerce#4541]
nopCommerce version: 4.20 - 4.30

Steps to reproduce the problem: Setting up a store with subdomains and would prefer the cookies can be setup to support subdomain so that user can be signed in once across stores.
It's an easy change in the Nop core code but would prefer to not touch the core code.
Is there a way to set the domain properties on cookies?

**Comment by AndreiMaz** [comment]
Cookies are already supported for any URL (including subdomains).

I presume you've meant SSO support. There's a separate work item for this task
