### ISSUE TITLE
Error when trying to remove deleted product from cart.

### ISSUE THREAD

**Issue by neo302** [nopSolutions/nopCommerce#4542]
nopCommerce version: 
4.3
Steps to reproduce the problem: 
Log in
Add existing item to cart.
Delete item from store as Admin
Item will still show in cart but say product is deleted. 
When you try and remove the item from cart or set the qty to 0, you will encounter an error:
System.Collections.Generic.KeyNotFoundException: 'The given key '1' was not present in the dictionary.'

**Comment by DmitriyKulagin** [comment]
Closed #4542
