### ISSUE TITLE
Validation of the "Maximum shopping cart items" setting on existing cart 	

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4543]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1) Add more than one item in cart 
2) Go to  /Admin/Setting/ShoppingCart. And change the "Maximum shopping cart items" value to 1
3) System doesn't allow to add new items to the cart. But it allows to checkout and place the order

It should not allow me to to do check out and place order respect with this setting. So we should validate the shopping cart setting on the existing shopping cart as well

**Comment by sk5202** [comment]
Hello, @AndreiMaz  I've reported this issue 9 days ago still no action.

Could you please verify?

**Comment by AndreiMaz** [comment]
@sk5202 thanks. it's already assigned to 4.30. So we'll check it before its release

**Comment by sk5202** [comment]
@AndreiMaz ??

**Comment by holydk** [comment]
Closed #4543
