### ISSUE TITLE
Avalara tax provider Configuration - Company dropdown value vanished after perform post operation

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4544]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1) go /Admin/AvalaraTax/Configure

2) select any country 

3) Click on test tax calculation

4) After you can see the **company dropdown** options vanished. 

https://www.loom.com/share/75a2d1780aba466aba62325b70cc2bac

**Comment by sk5202** [comment]
Hello @AndreiMaz  @RomanovM this issue created it almost completed 8 days.
Could you guys verify ?

**Comment by AndreiMaz** [comment]
@sk5202 thanks. it's already assigned to 4.30. So we'll check it before its release

**Comment by RomanovM** [comment]
Done in https://github.com/nopSolutions/nopCommerce/commit/7dddc66675800fd26496e35df6e6fc0cb208ca29
