### ISSUE TITLE
PayPal Smart Payment Buttons. Fix wrong decimal precision

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4545]
nopCommerce version: 4.30 beta

Originally described at https://github.com/nopSolutions/PayPal-SmartButtons-plugin-for-nopcommerce/pull/7 (waiting for the update of the PR) - later moved to https://github.com/nopSolutions/nopCommerce/pull/4547

But it's better to have this implementation consistent with other similar places in source code. For example, https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Payments.PayPalStandard/PayPalStandardPaymentProcessor.cs#L283 

Also see issue https://github.com/nopSolutions/nopCommerce/issues/4275

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/pull/4547
