### ISSUE TITLE
Activity Types data table  - Invalid JSON response when refresh grid

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4548]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/ActivityLog/ActivityTypes

2) scroll down and refresh table 

You will get this error

**DataTables warning: table id=activityLogType-grid - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1**

**Comment by sk5202** [comment]
![image](https://user-images.githubusercontent.com/41533502/79067791-96562280-7cdf-11ea-8d26-07d95b7e473e.png)

**Comment by DmitriyKulagin** [comment]
Closed #4548
