### ISSUE TITLE
Return Request - Id is not display for new return request for order

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4550]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Pull latest changes

2) Place one order => Paid order => add shipment => set as delivered =>  set as shipped 

3) Go front side order listing page

4) Click on return request and create new request don't forget to select qty 

5) Now go Admin/ReturnRequest/List

**You can see at grid Id  should be display.**

![image](https://user-images.githubusercontent.com/41533502/79068634-08316a80-7ce6-11ea-9041-70b55371fc7c.png)

**Now you can edit same request at the Id should be display**

![image](https://user-images.githubusercontent.com/41533502/79068657-4038ad80-7ce6-11ea-8a6b-2b20482d582c.png)

**but at both listing page and return request detail page id is not there.**

**Comment by DmitriyKulagin** [comment]
Closed #4550
