### ISSUE TITLE
Continue button is missing in payment information section 

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4553]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Configured Paypal smart button plugin with working credentials
Add product to cart
Redirect to the checkout page
Select/fill billing and shipping address
Select **PayPal Smart Payment Button method** from Payment method list section
Now click on back button and select **Check/Money Order payment** method and click continue
Now see, there is continue button missing in payment information section.
Click back and select Manual Credit card method and click on continue
Same here on payment information page - **continue button** is missing

**_Note_: Using latest source code** 

See this video for re-produce step:
https://www.loom.com/share/d2bd8a8667b449eda5659641df673462

**Comment by rajupaladiya** [comment]
![01_contnue](https://user-images.githubusercontent.com/13154058/79081699-6b022080-7d3d-11ea-9b07-d500384568bd.png)

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/52a4f18583f8d7e4bf1fc2812ae2d9afafc9bff7
