### ISSUE TITLE
PayPal Smart Payment Buttons redirect to cart page without add to cart

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4554]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to configure page of PayPal Smart Payment Buttons payment method
Mark true as setting **Display buttons on product details** and save

![02_conf](https://user-images.githubusercontent.com/13154058/79081859-c41e8400-7d3e-11ea-810b-a48f39667deb.png)

Now go public area and open Build your own computer's product detail page, t**his have required product attribute**

Now you can see there paypal payment buttons available.
Now click on any paypal button
This will redirect user to cart page/checkout page without add to cart.

https://www.loom.com/share/411cc85b67bd4a0b95c15a2f61b6ba46

**Comment by RomanovM** [comment]
Now the behavior of these buttons on the product details page is exactly the same as the default 'Add to cart' button behavior. See details in https://github.com/nopSolutions/nopCommerce/commit/52a4f18583f8d7e4bf1fc2812ae2d9afafc9bff7
