### ISSUE TITLE
Warning message of required checkout attribute not display on checkout page with PayPal smart button on cart page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4555]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to configuration page of  **PayPal Smart Payment Buttons** (Admin/PayPalSmartPaymentButtons/Configure)

Check **Display buttons on shopping cart**	and save setting.

![03_conf](https://user-images.githubusercontent.com/13154058/79082169-4a3bca00-7d41-11ea-94be-1a4aadf4de7b.png)

Now go to Catalog > Attributes > Checkout attributes
Add here one attribute with required and without any preselected value.
You can use attribute type checkboxes

Now go to cart page.
Click on PayPal smart button without select checkout attribute value

This will refresh cart page without any error message.

There should be display proper warning message regarding select checkout attribute.

See this video 
https://www.loom.com/share/8a0033ab4e7e4ea1be49013ef4f5031a

**Comment by RomanovM** [comment]
Now the behavior of these buttons on the shopping cart page is exactly the same as the default 'Checkout' button behavior. See details in https://github.com/nopSolutions/nopCommerce/commit/52a4f18583f8d7e4bf1fc2812ae2d9afafc9bff7
