### ISSUE TITLE
Discount update -  There is already an open DataReader associated with this Command which must be closed first.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4557]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 
1) Add one discount with assign to product discount type click save and continue.

2)Add product at applied to product grid in my case i added **Apple iCam**

3) Now Switch discount type from assign to product **to** **Assign to categories**

4) Click save and continue

You will get this error.

**There is already an open DataReader associated with this Command which must be closed first.**

https://www.loom.com/share/9cdb1c6573c24e9089413767495e53ed

**Comment by skoshelev** [comment]
Closed #4557
