### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by schalkvanwyk** [nopSolutions/nopCommerce#4558]
nopCommerce version: 4.2

Steps to reproduce the problem: 
docker build

Results in failure, the plugin source "/src/Plugins/Nop.Plugin.Payments.Qualpay" does not exists.

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce/commit/d8f9a869b7784bdae19f1bc9c37da37921be422c

Closed #4558
