### ISSUE TITLE
Payment by credit/debit is not working in PayPal Smart button

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4560]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Configured PayPal smart button and go to checkout page.
Select PayPal smart button payment method from payment list method.
Select Credit/Debit card option from payment information section.
It will load credit card form.
Fill here testing card details (4111 1111 1111 1111 or 5105 1051 0510 5100) and click on continue.
It'll show below message.

**Something went wrong. We'll take you back to checkout so you can try again.**

![09](https://user-images.githubusercontent.com/13154058/79142688-802c8d00-7dd9-11ea-84b0-be8aefec02a4.png)

The same card is working fine with first PayPal button and popup.

Here is video - 
https://www.loom.com/share/696c9b5f26be406ba83be09affe625fc

**Comment by RomanovM** [comment]
@rajupaladiya This issue isn't related to nopcommerce. Try to contact PayPal support.
