### ISSUE TITLE
New Topic Page Create :  Exeption occured SqlException The INSERT statement Topic page  

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4561]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go Admin/Template/List

2) Go topic template panel

**note :
delete all template by default there is only one but if you created more than one than delete all topic template**

3) Go /Admin/Topic/Create

4) add name and click on **save and continue** 

you will get below error.

The INSERT statement Topic page  : conflicted with the FOREIGN KEY constraint "FK_Topic_TopicTemplateId_TopicTemplate_Id"

https://www.loom.com/share/c57c311ee5864e31a47f46669054e630

**Comment by AndreiMaz** [comment]
@exileDev There was no need to add this foreign key as it never existed before in previous versions. It's wrong because it also could cause cascade delete during the delete of a template. The foreign key should be removed

**Comment by exileDev** [comment]
Closed #4561
