### ISSUE TITLE
Currency not updating after set to 0

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4562]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to currency list page
Redirect to edit page of any currency
Set currency rate to 0 and click on save and continue button
Now you see here an exception
**Exchange rate must be greater than 0.**

![10](https://user-images.githubusercontent.com/13154058/79144097-0053f200-7ddc-11ea-9bce-215d552485a8.png)

Now change rate to 5 or 10, any number above 0 and click on save and continue,
you will see some error message. This is not allowing to update currency.

See this video.
https://www.loom.com/share/9f25565806f44aae88ba526fadd8c55f

**Comment by DmitriyKulagin** [comment]
Closed #4562
