### ISSUE TITLE
Validation message for int/decimal is not valid

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4564]
nopCommerce version: 4.30 beta

Steps to reproduce the problem:
1. Go to Tax categories page
2. Add category with null display order
3. It will display **The Value "" is invalid** because of Display order value is null

The same happens for other fields (e.g. "Price" on a product details page)

Note: **Using latest source code, you can see in video.** (after fixed and close task #4522)

https://www.loom.com/share/ed244c6df3874847b72589ab5487cfd5

[A.M.] UPDATE: Please see the details at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute. Especially the following text: _However, model binding for a non-nullable property may fail, resulting in an error message such as The value '' is invalid. To specify a custom error message for server-side validation of non-nullable types, you have the following options..._

**Comment by AndreiMaz** [comment]
@DmitriyKulagin Also in the previous versions when you go to any other page (e.g. Category details page), and clear an integer input (e.g. DisplayOrder), click "Save", you would get a user-friendly error: "The Display order field is required". 

But now it displays "The Int32 field is required"

We should display it the same way like it was before

**Comment by AndreiMaz** [comment]
@skoshelev As a continuation of the https://github.com/nopSolutions/nopCommerce/issues/4563 and https://github.com/nopSolutions/nopCommerce/issues/4522 work items

Also in the previous versions when you go to any other page (e.g. Category details page), and clear an integer input (e.g. DisplayOrder), click "Save", you would get a user-friendly error: "The Display order field is required".

But now it displays "The Int32 field is required"

We should display it the same way like it was before

**Comment by skoshelev** [comment]
Closed #4564

**Comment by AndreiMaz** [comment]
Please see the details at https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute

Especially the following text: _However, model binding for a non-nullable property may fail, resulting in an error message such as The value '' is invalid. To specify a custom error message for server-side validation of non-nullable types, you have the following options..._

So we should avoid specifying "required" messages for non-nullable int/decimal fields and find some other solution.

**Comment by skoshelev** [comment]
Closed #4564
