### ISSUE TITLE
Maintenance - Database backups panel is not appear with shared hosting (Used My SQL Database))

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4565]
nopCommerce version: 4.30 beta

Steps to reproduce the problem:  

1) Pull latest changes

2) I deployed at **smrter asp.net** shared hosting

3) Create database using **MySql**  

4) Go =>  Admin/Common/Maintenance

Database backups panel   database panel missing

**note -   issue with shared hosting and my sql db i don't know it is appear with MS SQL so test with MySQL**

![image](https://user-images.githubusercontent.com/41533502/79207682-a3e5e680-7e5e-11ea-9358-7cd31fb8ea53.png)

**Comment by sk5202** [comment]
https://www.loom.com/share/c61ef7c038c54462a6e8ad818fa20ae4

**Comment by skoshelev** [comment]
Hi, @sk5202. Thank you for your active participation in the testing. In this case, it should be so, we decided to hide the backup panel for providers that do not support it. Please see [this ticket](https://github.com/nopSolutions/nopCommerce/issues/4368#event-3167865508) for more details.
