### ISSUE TITLE
Purchase/Supplier Order

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#457]
Hi.

It could be very cool to have purchase orders like ERP system. I do not require balance like ERP system. But merely a way to control inventory better.

It would open up for the following options:
 * Tell customers when we expect stuff back on stock
 * Better possibility for revenue statistics (we now have cost-prices over time - we can compare that to our orders)
 * Forecasting possibilities

Hope that it gets votes. I think it's really important.

Of course it should also work with product attributes (size, color etc.)

**Comment by Joebeazelman** [comment]
Wow!  She was shutdown without a response.  Not a good way to foster community engagement.
