### ISSUE TITLE
Docker configuration persistence

### ISSUE THREAD

**Issue by Craumix** [nopSolutions/nopCommerce#4572]
nopCommerce version: 4.20

Steps to reproduce the problem: 
When using the nopCommerce Docker image, configurations like, for example the Database name and credentials are not persistent.
Is there a directory in the Container, that can be backed up to retain this information?

**Comment by AndreiMaz** [comment]
Thanks. Duplicates https://github.com/nopSolutions/nopCommerce/issues/4113
