### ISSUE TITLE
Cart Error - NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4573]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Customer/Create

2) Add Email and Password only. **I repeat Add only email and password**

3) Click save and continue.

4)  Go to /Admin/Tax/Providers and set avalara **mark as primary provider**  (You should change this setting otherwise issue is not happened)

4) Go Public store login with that customer which you created.

5) Add any product to cart.

Go to cart you will get below screen

![image](https://user-images.githubusercontent.com/41533502/79262379-d5869e00-7eae-11ea-8eaf-e30ee69653d1.png)

here is the full video 

https://www.loom.com/share/0378b9351fa94234889af75d8385953f

**Comment by sk5202** [comment]
Actually this error is coming from avalara plugin. You guys forgot to handle null there

**Comment by AndreiMaz** [comment]
Thanks. It's a known issue - https://github.com/nopSolutions/nopCommerce/issues/3958

**Comment by sk5202** [comment]
@AndreiMaz   ya i reviewed #3958 
There is two way 

1) We should register and use \Nop.Plugin.Tax.Avalara\Infrastructure\DependencyRegistrar.cs only when the plugin is enabled. We should not override services when the plugin is disabled

2) Furthermore, it's better to implement all the logic even without override of the service (e.g. with events, etc)

An of you choose 1) than it will not impact on #4573.  still error will occur at that time this issue should be relevant.

If you choose 2) than also you have to applied inside code at that time you have to fix that null error. that is additional.

So, #3958  this issue is the way change and #4573 populate null error.

What you think ?

@AndreiMaz

**Comment by AndreiMaz** [comment]
@sk5202 we'll avoid the override of the core service in the Avalara plugin. So it'll be point 2 in https://github.com/nopSolutions/nopCommerce/issues/3958

But most probably you're right about the rest part that the originally described issue will still exist. We'll check it. Thanks

**Comment by sk5202** [comment]
@AndreiMaz yaa thank you

**Comment by RomanovM** [comment]
Not reproduced after commit https://github.com/nopSolutions/nopCommerce/commit/7dddc66675800fd26496e35df6e6fc0cb208ca29. 
Try again with the last code changes.
