### ISSUE TITLE
Plugin dll files is deleted ignoring version 

### ISSUE THREAD

**Issue by sencagri** [nopSolutions/nopCommerce#4574]
nopCommerce version: 4.20

I wanted to use AutoMapper v7 for my plugin but it is deleted without checking the version of the nuget package. How can I handle this ?

**Comment by skoshelev** [comment]
Hi @sencagri. I am very sorry, but you will not be able to use the libraries that are in the core of nopCommerce, but with a different version. Even if you find such a method, the site won't work with such a plugin.

Please, ask your questions on our [forum](https://www.nopcommerce.com/boards), we use GitHub only for bug reports and suggestions.
