### ISSUE TITLE
Radio-button - Pre-selected is not working respectively for Checkout attributes

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4577]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Admin/GiftCard/List  

2) Remove All attributes

3) Add new attribute /Admin/CheckoutAttribute/Create

4) Control type should be radio button list click save and continue

5) Add some attribute values (only 3). make sure as now don't enable any pres select checkbox

now go cart page you can see there are no any preselect radio on page load

that's fine

Now enable middle preselect checkbox i presume you added 3 attribute values.

Now again go cart page and middle is selected which is also fine.

**go back and disable pre select option which you enable just.**

**So we don't have any pre select option enabled.**

**Now go cart page you can see middle is selected.**

**At this stage no one is selected.**

here i reproduce full issue by made this video.

https://www.loom.com/share/eec06674266c4c60997e9218209b305b

**Comment by AndreiMaz** [comment]
@sk5202 Once the shopping cart page is visited, it saves a previously selected values. So it was saved right after your first visit to the shopping cart. There are many ways to invoke this method - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/ShoppingCartController.cs#L153

**Comment by sk5202** [comment]
@AndreiMaz  yes i am agree with you.

i am thinking about different case.

If store owner created attribute like(Radio button list)

- Additional amount for 2 day (+ 50$)
- Additional amount for 5 day (+ 150$)
- Additional amount for 7 day (+ 250$)

Above is radio button list and store owner now pre-select checkbox disable from admin side.

now think if customer select any of this previous so now customer have to pay either $50 , $150, $250 to place their order because of store owner enable pre select previous.

So if we think about customer point of view at that time that is wrong.

We have to check condition while you guys get that attributes.

Hope you understand this case.

Thanks,


@AndreiMaz

**Comment by sk5202** [comment]
Hello @AndreiMaz  could you please see once above scenario?

Hope you will check.

**Comment by sk5202** [comment]
@AndreiMaz ?
