### ISSUE TITLE
VS 2019 Copy References to Output Directory in PlugIns with Nuget Packages

### ISSUE THREAD

**Issue by Shane32** [nopSolutions/nopCommerce#4580]
In issue #3208 there was a recommendation how to compile a plugin when it depends on a nuget package that is not part of the base nop library, and have the plugin output only save the DLLs for the plugin and added nuget reference -- but not all of .Net Core.  This works fine in VS 2017.  However, as much as I try, I cannot produce the same result in VS 2019.  Can you provide a sample csproj for VS 2019 which will copy only the plugin dll and the additional nuget references necessary to the output folder?

Steps to reproduce the problem: 
1. Create a plugin that depends on a nuget resource not already referenced within Nop.Web or the other core Nop projects
2. Follow the steps in #3208 to update the csproj so that the dependency will get copied to the proper plugin output folder (but not all referenced .Net Core assemblies)
3. Clean the solution and empty the Nop.Web\Plugins folder
4. Compile in VS 2017, and notice that only the necessary DLLs are copied to the plugin's output folder
5. Clean the solution and empty the Nop.Web\Plugins folder
6. Open the solution in VS 2019 and compile the plugin
7. Notice that the DLLs are not filtered appropriately based on the csproj settings.

I'm using nopCommerce version 4.1

**Comment by skoshelev** [comment]
Hi @Shane32.
I tried to repeat the problem on version 4.30 and VS 2019(16.4.5) everything works as expected.
In your case, it may not work the ClearPluginAssemblies, or it might work out with the wrong data since it is this task that is responsible for cleaning the plugin output folder against libraries that are in the main project.

Closed #4580
