### ISSUE TITLE
Include aria-label attributes for cart and wishlist remove checkbox and quantity display

### ISSUE THREAD

**Issue by kem-storis** [nopSolutions/nopCommerce#4581]
nopCommerce version: 
All versions
Steps to reproduce the problem: 
For ADA compliance purposes, an aria-label attribute needs to be added to the remove checkbox for cart and wishlist items so that vision impaired persons using screen readers will know what the purpose of the control is. Additionally, the quantity input field on both pages also needs an aria-label. I have created a PR already for this item.

**Comment by AndreiMaz** [comment]
@DmitriyKulagin Also see PR - https://github.com/nopSolutions/nopCommerce/pull/4582

**Comment by DmitriyKulagin** [comment]
Closed #4581
