### ISSUE TITLE
Duplicate specification attribute option at product edit page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4584]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Note: Using the latest source code and fresh installation

Go to any product edit page
Scroll down till specification attribute section and click on **add attribute** button

Now check value of Attribute	dropdown list.
It shows duplicate entry with same number of it's value

![00001](https://user-images.githubusercontent.com/13154058/79496636-0946fc80-8044-11ea-9026-f39ce320bd69.png)

See this video.
https://www.loom.com/share/e2662d7001284e858bec95416f754bb4

**Comment by MatDm** [comment]
Hi,

Somebody can simply add "Distinct()" to Nop.Services/Catalog/SpecificationAttributeService.cs, in the GetSpecificationAttributesWithOptions() method so the returned query will contain distinct elements (without repetition).

**Comment by AndreiMaz** [comment]
See PR - https://github.com/nopSolutions/nopCommerce/pull/4594

**Comment by holydk** [comment]
Closed #4584
