### ISSUE TITLE
Login links not working and sidemenu active menu issue with Avalara tax plugin

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4585]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to Avalara tax configuration page.
There are links of **production service** and **development service** login  are broken.
It redirects to 404 page.
![00002](https://user-images.githubusercontent.com/13154058/79499363-72c90a00-8048-11ea-90e6-552b9d25ca2c.png)

1. left side menu active issue
Click on view button of any log item under Avalara configuration page
Now check left side menu item, no one menu item is selected on this page

it should selected Configuration  > Tax Providers

**Comment by AndreiMaz** [comment]
Thanks, Raju! Already reported - https://github.com/nopSolutions/nopCommerce/issues/4296
