### ISSUE TITLE
Payment method: Friendly Name and Display Order -> translate | store location

### ISSUE THREAD

**Issue by iwhp** [nopSolutions/nopCommerce#4586]
nopCommerce version: **4.20**

Steps to reproduce the problem: 
- Navigate to: **http://your-nop-url/Admin/Payment/Methods**
- A list of all available payment methods is shown, with columns **friendly name** and **display order**
- Changes friendly name and/or display order
- This change is stored on the file system at **.\Nop.Web\Plugins\Payments.XXX\plugin.json**

Issues:
- It is not possible to properly **translate** friendly name to multiple languages
- There may be issues if multiple **areas are deployed** (test, prod). One has to manage these plugin.json files to make sure, the environments are consistent

Consider storing those values in the database.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box

**Comment by syky27** [comment]
@AndreiMaz 
You guys seriously decided not to have that Friendly Name that gets showed in the list of available payments localized?

So the whole ecommerce will be in 2 languages but the type of payment will be only in one? This makes sense to you?
