### ISSUE TITLE
BaseDataProvider - Methods don't expose command timeout

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4587]
nopCommerce version: 4.30

Steps to reproduce the problem: 

Previously IDbCnontext.ExecuteSqlCommand(...); used to accept a timeout parameter. 
In the new 4.30 version there doesn't seem to be a way to set the timeout on a command.

BaseDataProvider.ExecuteNonQuery() and other methods that use a CommandInfo.

Not sure if I might have missed how to set the timeout on a CommandInfo so let me know if there is actually a way.

**Comment by alinmircea** [comment]
One simple, more straight forward option that could be implemented as a first step for a faster release, would be to move the checks from the extension function on a virtual property/method on ProductAttributeMapping so we could override it.

**Comment by exileDev** [comment]
Closed #4587
