### ISSUE TITLE
Order total not updating properly from admin area with multiple quantity

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4588]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Place any order 
Now go to admin area > Configuration > Setting > Order setting
Make sure setting **Auto update order totals**is enable
![Screenshot_1](https://user-images.githubusercontent.com/13154058/79670327-aee2a300-81df-11ea-8104-a842a3340e46.png)

Now go to recently placed order detail page.
Navigate to product section and add any product with more than 1 quantity

Now see order total - it's added only 1 quantity's amount
Also product section display single quantity's amount in Total column, it should be (item price x quantity)

![Untitled](https://user-images.githubusercontent.com/13154058/79670456-d8e89500-81e0-11ea-9b97-d9a2c215f9d6.png)

See here video
https://www.loom.com/share/10e79b46d54b42309c9f84f1480361f4

**Comment by RomanovM** [comment]
@rajupaladiya When adding a product to an existing order, you need to manually correctly fill in all the fields - price, quantity and total, in this case the order amount will be recalculated correctly.
There is also an [issue](https://github.com/nopSolutions/nopCommerce/issues/2090) to automatically update these fields.

**Comment by martinschoenwandt** [comment]
I see that this issue is closed - but the error is still there; when changing quantity Total with and without TAX is not updated. Will this be fixed (Version 4.20)??
