### ISSUE TITLE
Issue with checkbox in country list page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4589]
nopCommerce version: 4.30 Beta

Steps to reproduce the problem: 
Go to the country list page
select any 1 or two countries and click on **unpublish selected** button
This will mark unpublish to selected countries and refresh grid

Now select other two countries and click on **publish selected** button
See now, it will publish those countries which unpublished in last action.

**Note: Using latest source code**

See here video - https://www.loom.com/share/babc31345eb343d995457c2b0e0a913e

**Comment by sk5202** [comment]
same issue i found here /Admin/ProductReview/List

**Comment by sk5202** [comment]
So i think all the places you have to check and fix accordingly @rajupaladiya  explain

**Comment by DmitriyKulagin** [comment]
This has been fixed in this commit - https://github.com/nopSolutions/nopCommerce/commit/afd9460b22daba988711baeb72dd732aa825e73b
