### ISSUE TITLE
Need to change Other (Non US) to Other in state/province drop-down list 

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4590]
### Suggestion
We need to change pre-selected state/province label to **Other** when a country is not selected United State and it doesn't have any state.

This required because there are many store owners are available from other countries, not US.
In this case they are not doing business in US.
So it would be good if we change lable to Other from Other (Non US).
Other (Non US) sounds force to think store limited to US.

Hope I make me clear.

**Comment by holydk** [comment]
Closed #4590
