### ISSUE TITLE
Transform ProductAttributeExtensions.IsNonCombinable into configurable Attribute or AttributeMapping Property

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4595]
The idea is to allow user configuration of which attributes should be ignored when working with attribute combinations.

I believe the logic is already there with the extension method (ProductAttributeExtensions.IsNonCombinable). I haven't done a thorough investigation but you will know better anyway if this can be easily achieved or not.

We have situations where a specific attribute with 20+ values should not be added to the combination pool as it will create too many duplicate results.

One simple, more straight forward option that could be implemented as a first step for a faster release, would be to move the checks from the extension function on a virtual property/method on ProductAttributeMapping so we could override it.

**Comment by alinmircea** [comment]
One simple, more straight forward option that could be implemented as a first step for a faster release, would be to move the checks from the extension function on a virtual property/method on ProductAttributeMapping so we could override it.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
