### ISSUE TITLE
Force entering email twice during registration (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#46]
Next to customer forgetting their house number in the address, we have a lot of users not entering their email address right. This leads to email delivery failures. Is it possible to add an email confirmation option? (Not by email, but by entering the email twice?) 

Make it configurable (disabled by default). Put "Force entering email twice" setting into "customer settings". Hint: Force entering email twice during registration

Source: http://www.nopcommerce.com/boards/t/32286/force-entering-email-address-twice.aspx

**Comment by skoshelev** [comment]
Closed #46
