### ISSUE TITLE
Replace a SendInBlue logo with a new one

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4600]
Two pages:

1. /Admin/Plugin/List
2. /Admin/SendinBlue/Configure

The new one is attached
![Master-Horizontal-notagline@2x (1)](https://user-images.githubusercontent.com/5019111/79729208-cf9e1c00-82f7-11ea-9900-57dacf156578.png)

**Comment by holydk** [comment]
Closed #4600
