### ISSUE TITLE
Move customer related fields from the "GenericAttribute" table to the "Customer" table

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4601]
Currently some customer properties (e.g. First Name, Last Name, etc) are stored in the [GenericAttribute] table. These records are stored separately (one value - one record in the table). Assume if a store has 10.000 customers, then it will create minimum 100.000 rows. So GenericAttribute table will be increasing continuously. And this will definitely increase database size and impact the performance. 

Let's move these records to the [Customer] table.

You can find all of them at C:\andrei\nop_sources\src\Libraries\Nop.Core\Domain\Customers\NopCustomerDefaults.cs. But here is a list of properties to be moved (not all should be moved):

1. FirstName
2. LastName
3. Gender
4. DateOfBirth
5. Company
6. StreetAddress
7. StreetAddress2
8. ZipPostalCode
9. City
10. County
11. CountryId
12. StateProvinceId
13. Phone
14. Fax
15. VatNumber
16. VatNumberStatusId
17. TimeZoneId
18. CustomCustomerAttributes
19. CurrencyId
20. LanguageId
21. TaxDisplayTypeId

**Comment by sateeshmunagala** [comment]
AvatarPictureId property is missing. 
Is it done intentionally ?
