### ISSUE TITLE
Searching a product by category (parent - children relation) issue

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#4602]
nopCommerce version: 4.30

Steps to reproduce the problem: 
If you want to search by category and the category has more subcategories (children) it give no results! For example if you select computers the search result is none if you select the category Computers>>Desktops you have 3 results! 
Normaly the parent category should include all the children categories.... and give the results of all the subcategories!

**Comment by AndreiMaz** [comment]
@Lymperis79  What page are you talking about? Where are you trying to search? Please clarify

**Comment by Lymperis79** [comment]
If you are in the product list page in admin view. In the top panel you can select and filter the results with categories... if you change the categories and press search you can see the issue.

**Comment by AndreiMaz** [comment]
Have you ticked the "Search subcategories" checkbox? It's under "Category" dropdownlist

**Comment by Lymperis79** [comment]
Ok if you select the checkbox it works! Sorry for that!
