### ISSUE TITLE
If you enable the customer avantar the table header is not resized-aligned correctly

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#4603]
nopCommerce version: 4.30

Steps to reproduce the problem: If in the customer settings the user enables the avantar and enables the username options in the list of the customers the header of the table is not aligned - resized corectly.

**Comment by AndreiMaz** [comment]
@DmitriyKulagin The same happens in for datatable heading in OfficialFeed admin page (https://github.com/nopSolutions/nopCommerce/issues/4604)

**Comment by DmitriyKulagin** [comment]
Closed #4603
