### ISSUE TITLE
ReturnRequest is deleted when you edit it

### ISSUE THREAD

**Issue by mdhcindioglu** [nopSolutions/nopCommerce#4605]
nopCommerce version: 4.3

Steps to reproduce the problem: 
When I tried to update state of ReturnRequest, it DELETED.

There are missing code in IReturnRequestService:
        /// <summary>
        /// Updates the  return request 
        /// </summary>
        /// <param name="returnRequest">return request </param>
        void UpdateReturnRequest(ReturnRequest returnRequest); 

and you have to change this line of code in ReturnRequestController in method:
        
public virtual IActionResult Edit(ReturnRequestModel model, bool continueEditing)

from:

_returnRequestService.DeleteReturnRequest(returnRequest);

To:

_returnRequestService.UpdateReturnRequest(returnRequest);

**Comment by sk5202** [comment]
may be related to #4417

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4417
