### ISSUE TITLE
4.30 Facebook Share "Invalid HREF"

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4607]
nopCommerce version: 
4.30

Steps to reproduce the problem: 
1) Go into a product
2) Click the Facebook Share button
3) I get `Parameter 'href' should represent a valid URL`

![image](https://user-images.githubusercontent.com/20989983/79988247-672c7780-847c-11ea-819c-2fb48be6ee49.png)

**Comment by DmitriyKulagin** [comment]
I just checked this and everything works well. 

![image](https://user-images.githubusercontent.com/27218280/80204624-e2835a00-8631-11ea-85ba-f1fa662b5e73.png)


Check your `catalogsettings.pagesharecode` setting value. By default, the store is set with this value -

`<!-- AddThis Button BEGIN --><div class="addthis_toolbox addthis_default_style "><a class="addthis_button_preferred_1"></a><a class="addthis_button_preferred_2"></a><a class="addthis_button_preferred_3"></a><a class="addthis_button_preferred_4"></a><a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a></div><script src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=nopsolutions"></script><!-- AddThis Button END -->`

**Comment by Ochapparel** [comment]
I wonder if it's because I'm testing on localhost.

I checked my setting and its the same except for the bold part below. I removed the bold part and still the same results, so that wasn't it.

`<!-- AddThis Button BEGIN --><div class="addthis_toolbox addthis_default_style "><a class="addthis_button_preferred_1"></a><a class="addthis_button_preferred_2"></a><a class="addthis_button_preferred_3"></a><a class="addthis_button_preferred_4"></a><a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a></div><script **type="text/javascript"** src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=nopsolutions"></script><!-- AddThis Button END -->`

Thanks for checking.
