### ISSUE TITLE
Issue with header width for tables Official Feed and Customers when ScrollX bar is visuable

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#4609]
nopCommerce version: 4.30

Steps to reproduce the problem: 
You enable Avantar and username from customer settings. Then if you go to in Customer list page or in Official Feed page and you reduce the size of the page so the scroll bar down (scrollX ) appears the header of the table is not alligned properly .

**Comment by AndreiMaz** [comment]
already reported at https://github.com/nopSolutions/nopCommerce/issues/4609 and https://github.com/nopSolutions/nopCommerce/issues/4603
