### ISSUE TITLE
Orders bulk update / Do with selected

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#461]
Do with selected: When processing orders it would greatly speed up administration when in the list of orders you have selection boxes at the front of the row and a “limited” number of options that you could do. For example: search on all orders that need to be shipped. I print the packaging slips, post them and then I need to set the status to “shipped”. If I can multi select the orders and have a drop down task list that has an option “set status to shipped” and a button “update” -> done. (instead of opening the 100 orders of the day, click on shipping info, click on shipped, save, go back to list (new search) and so on…)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box
