### ISSUE TITLE
Search in topic should not case sensitive

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4612]
Steps to reproduce the problem: 
Go Admin > Content Management > Topic (Pages)

Here is search box for search topic by topic contents and it is case sensitive.

So it would be if this is not case sensitive.

![01](https://user-images.githubusercontent.com/13154058/80272799-3c475b00-86ea-11ea-9566-8272718d1c34.png)
![02](https://user-images.githubusercontent.com/13154058/80272800-3c475b00-86ea-11ea-9eac-c744e6d85764.png)

**Comment by holydk** [comment]
Closed #4612
