### ISSUE TITLE
CloudFlare SSL problem with mail server

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#4613]
nopCommerce version: 4.30 develop branch(3-4 months ago)

Steps to reproduce the problem: 
My website mails dont send, because ssl problem here.
I was use cloudflare and cloudflare ssl, my mail server is work with my e-mail application(outlook).But its not work with website. 
Whats your soluiton for nopcommerce with cloudflare?

![1](https://user-images.githubusercontent.com/7630189/80278722-49237900-8701-11ea-9096-8c6da02e1464.JPG)
![2](https://user-images.githubusercontent.com/7630189/80278727-4d4f9680-8701-11ea-90c3-8941d1188af9.JPG)

**Comment by AndreiMaz** [comment]
Could you please post all questions on our forums?
