### ISSUE TITLE
Discount Requirement - Group name should not be empty - It fills blank value to DD due to empty

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4614]
nopCommerce version: 4.30 beta

Steps to reproduce the problem: 

1) Go /Admin/Discount/Edit/2

2) Discount requirement type	 - Add requirement group 
 
3) Group name leave as black and click save 4 to 5 times

3) And see the **Add to group dropdown** is empty due to lots of empty record.

**So It should not be empty validation should be there Group name should not be empty.**

https://www.loom.com/share/63fdb8f5042f471a8a6c34cc0e493f6a

**Comment by exileDev** [comment]
Closed #4614
