### ISSUE TITLE
Date format in NopMigrationAttribute should allow 24 hour format

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4615]
nopCommerce version: 4.30

Steps to reproduce the problem: 
All date formats of NopMigrationAttribute are using 12 hour format without any  "t" 

private static readonly string[] _dateFormats = { "yyyy-MM-dd hh:mm:ss", "yyyy.MM.dd hh:mm:ss", "yyyy/MM/dd hh:mm:ss", "yyyy-MM-dd hh:mm:ss:fffffff", "yyyy.MM.dd hh:mm:ss:fffffff", "yyyy/MM/dd hh:mm:ss:fffffff" };

Please consider using HH or t to avoid any confusion

**Comment by skoshelev** [comment]
Hi, @alinmircea. 
Thank you for your suggests


Closed #4615
