### ISSUE TITLE
Customer/address/product/vendor attributes. Hide "Values" section for "TextBox", "MultilineTextbox", "Datepicker", "FileUpload" attributes types 

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#4625]
nopCommerce version: 4.20

Steps to reproduce the problem: 
Please see attached image.

![Capture](https://user-images.githubusercontent.com/7768934/80638313-dfe39300-8a7d-11ea-96b1-866d69027bad.PNG)

I don't see a need for Values section when we have date picker as product attribute control type. This is confusing as well.

**Comment by exileDev** [comment]
@atulrungta I can't reproduce this problem. It works fine on a clean installation

**Comment by atulrungta** [comment]
@exileDev the previous screenshot was made on our hosted nopCommerce 4.20 website. You can see the front-end here https://nopcommerce420.nopadvance.com/100-physical-gift-card
You already have the back-end screenshot.

Today I did same thing on https://admin-demo.nopcommerce.com/ and it's the same as what I did on our hosted site. Both are almost same. See below:
![pic1](https://user-images.githubusercontent.com/7768934/80755656-daa24900-8b4e-11ea-8489-7d9bed24bc53.png)

The Date picker control does not need "Default value" textbox and Values section.

**Comment by AndreiMaz** [comment]
@atulrungta Thanks a lot for reporting, Atul! Fixed
