### ISSUE TITLE
PayPal Smart Payments doesn't work in Firefox

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4626]
nopCommerce version: 4.20

More info at https://www.nopcommerce.com/en/boards/topic/81509/paypal-smart-payments-no-checkout-possible-wrong-xml-due-to-wrong-conversion-of-decimal-numbers#262595

let's check

**Comment by RomanovM** [comment]
All is OK in the latest plugin version.
