### ISSUE TITLE
System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4629]
Measurements of performance show that this library is faster, but its functionality is still inferior to "Newtonsoft.Json". We will need to solve a number of problems to start using "System.Text.Json"

See [more](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview)

[How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)

**Comment by sefacan** [comment]
System.Text.Json still has a lots of issue. https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Text.Json.

I'm not sure it works properly yet.

**Comment by AndreiMaz** [comment]
Decided to postpone until System.Text.Json is implement a good way. Most probably the next version of .NET

**Comment by RomanovM** [comment]
After some consideration we've decided to leave Newtonsoft.Json.
