### ISSUE TITLE
Add multi-store support for Customer Settings

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#463]
I have multiple stores, but in only one of them do I need to add the minimum age (3.70). Therefore I would like customer settings to be multi-store enabled. 

Source: http://www.nopcommerce.com/boards/t/38080/add-multi-store-support-for-customer-settings.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. It can cause conflict when saving
