### ISSUE TITLE
Refactoring of RenderViewComponentToString method

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4630]
nopCommerce version: 4.20
[RenderViewComponentToString](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Controllers/BaseController.cs#L40)
Initially we customized the original internal [ViewComponentResultExecutor](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ViewComponentResultExecutor.cs) implementation. We need to improve and simplify this customization.

**Comment by sefacan** [comment]
You can try that.
https://gist.github.com/pauldotknopf/b424e9b8b03d31d67f3cce59f09ab17f

**Comment by DmitriyKulagin** [comment]
Closed #4630
