### ISSUE TITLE
Move away from using 0 as enum value in ReturnRequestStatus

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4634]
nopCommerce version: 4.20

Also let's check all other enums.

**Comment by badijm** [comment]
@RomanovM Hi, can you provide more details? Or it just - replace **0** to any other **non-zero** value. (E.g. -1).

**Comment by RomanovM** [comment]
After some discussion we've decided not to implement this. The current enum values ​​are already used in db, so let's not change them.
@badijm Anyway, thanks for your help.
