### ISSUE TITLE
Ability to add multiple product attribute conditions

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#4639]
nopCommerce version: 4.20

Steps to reproduce the problem: 

Right now only one condition can be added to a product attribute in nopCommerce. This limits user's whenever there is a need to have conditions based on multiple values. For example, Please see below:

1. Let us assume we have a product attribute Color with control type drop-down and have four values Red, Blue, Green and Yellow.
2. We have another product attribute Description with control type textbox that I want to show only when Blue or Yellow is selected from Color drop-down on front-end.

This is not possible right now. Even, there is one more requirement which I am writing below:

3. Apart from 1 and 2 mentioned above, let us assume that there is an another product attribute Size with control type drop-down and have values Small, Medium, Large, Extra Lagre.
4. We have an another product attribute Picture with control type File upload. This should be only visible when Color = Red OR Color = Green AND Size = Large OR Size = Small.

Hope this makes sense.

**Comment by AndreiMaz** [comment]
Thanks. But after some consideration we've decided not to implement this functionality out of the box
