### ISSUE TITLE
Can't login or register (ERR_TOO_MANY_REDIRECTS)

### ISSUE THREAD

**Issue by mdhcindioglu** [nopSolutions/nopCommerce#4641]
nopCommerce version: 4.3

Steps to reproduce the problem: 
- Download NopCommerce 4.3 with code.
- UnZip code to HD
- Run in VS Version 16.6.0 Preview 2.1
- Install database in SQL Server V18.5
- After NopCommerce started I can't login or Register
Error Message: Redirected many times! ERR_TOO_MANY_REDIRECTS
- I tried http and https.

**Comment by mdhcindioglu** [comment]
I tried to remove this line:
[HttpsRequirement]
From:
Presentation/Nop.Web/Controllers/CustomerController line: 384

and it worked!

**Comment by Svmurvj** [comment]
I have same problem. What is best solution for that to handle on localhost ?

**Comment by SelectSystemsInternational** [comment]
I have it setup in both Visual Studio and on IIS and I could not login in either. When I ran the setup on IIS the default settings are not created for SSL (See Image 1). 
![StoreSetup1](https://user-images.githubusercontent.com/34350154/80892069-af188d80-8d0b-11ea-919f-1a1a073c9137.png)
I had to manually set the values then restart the webserver. Then I can login (See Image 2)
![StoreSetup2](https://user-images.githubusercontent.com/34350154/80892075-b8a1f580-8d0b-11ea-8b76-9a7802e0dc95.png)

**Comment by maplewang** [comment]
I am using Cloudflare SSL, you need add online in  web.config  <httpProtocol> <customHeaders> section to set Use_HTTP_X_FORWARDED_PROTO to true.
<add key="Use_HTTP_X_FORWARDED_PROTO" value="true" />

**Comment by mdhcindioglu** [comment]
Problem here:
RedirectRequest(filterContext, _storeContext.CurrentStore.SslEnabled);
If we change this line to:
RedirectRequest(filterContext, !_storeContext.CurrentStore.SslEnabled);
It worked!

Nop.Web.Framework.Mvc.Filters.HttpsRequirementAttribute.HttpsRequirementFilter.OnAuthorization(AuthorizationFilterContext filterContext)

**Comment by zerokewl88** [comment]
I also had this problem, and was able to resolve this via updating the database and set the following:

Url -> https://www.mysite.com
Hosts -> [changed this to my site host]
SslEnabled -> 1

**Comment by mdhcindioglu** [comment]
The question is: How the normal user can update the store data if he can't login.

**Comment by skoshelev** [comment]
Closed #4641

**Comment by skoshelev** [comment]
> The question is: How the normal user can update the store data if he can't login.

Unfortunately, the only way to make corrections to the configuration when there is no access to the administration area is to directly edit the database.

**Comment by chu3kit0** [comment]
> I have it setup in both Visual Studio and on IIS and I could not login in either. When I ran the setup on IIS the default settings are not created for SSL (See Image 1).
> ![StoreSetup1](https://user-images.githubusercontent.com/34350154/80892069-af188d80-8d0b-11ea-919f-1a1a073c9137.png)
> I had to manually set the values then restart the webserver. Then I can login (See Image 2)
> ![StoreSetup2](https://user-images.githubusercontent.com/34350154/80892075-b8a1f580-8d0b-11ea-8b76-9a7802e0dc95.png)
> I also note the securitysettings.forcesslforallpages Setting is no longer used ?

it worked for me
