### ISSUE TITLE
Nop 4.2 Source Build Issues With Avalara Tax Plugin

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#4642]
nopCommerce version: 4.2

Steps to reproduce the problem: 

Building the source version of nop 4.2. I notice that in the Nop.Web/Plugins/Tax.Avalara it seems to build the entire web project in that folder. It does remove some files but some are left behind. I'll attach a screenshot of what the folder looks like. Has anyone else run into this? I pulled the source version right from github and did a rebuild.

Thanks

![image](https://user-images.githubusercontent.com/12185742/80814587-24fce780-8b9a-11ea-8389-a2fb7a6cb257.png)

**Comment by AndreiMaz** [comment]
It works fine in the latest version
