### ISSUE TITLE
ProductTemplate.Simple	file is missing

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4644]
nopCommerce version: 4.30 RC

Views folder is missing. We should not pre-compile view when publishing

**Comment by ecommerce-tester** [comment]
if i right all Views goes to Nop.Web.Views.dll
And how we can add new Product Template or Catalog Template?
in Themes folder?

**Comment by skoshelev** [comment]
Closed #4644
