### ISSUE TITLE
Got the blank page after fresh nopCommerce installation

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4645]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Upload no source code of 4.3 to hosting panel
2. Start installation of nopCommerce setup. When you press submit button then it redirect me to blank page.
3. When i refresh the page again then its show me nopCommerce public website.

**Comment by atulrungta** [comment]
I also got the same issue but I captured the screenshot. Please look at the image.
![Untitled](https://user-images.githubusercontent.com/7768934/80829740-54950980-8c05-11ea-816b-db6c6b5ef312.png)

I got this page right after installation was finished and the website tried to redirect to homepage. I am using no-source version from 4.30 release candidate on a VPS where all other nopCommerce versions are hosted and .net core 3.1.3 hosting bundle is installed.

**Comment by AndreiMaz** [comment]
@sangeetshah @atulrungta Could you please re-download the latest version from https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.30-release-candicate and try one more time?

**Comment by AndreiMaz** [comment]
@skoshelev Any application restart caused the following error to be displayed (not just in VS but even on a hosting) - "The service is unavailable". For example, after installation, after application restart in admin area, plugin reload, etc

I've just re-uploaded the latest version to our internal website for testing ("ef430"). And it works fine now (no such error anymore). There were two changes that could be related to it. Please check them and let me know which one caused the issue. The first one is ithttps://github.com/nopSolutions/nopCommerce/commit/cc8f7146a4ca1b90327d6227335b1c9f502eb2e5. The second one is that the solution previously was deployed in "debug" mode and now I've re-uploaded it built in "release" mode

**Comment by poyker** [comment]
I can also confirm that this happens using the RC no source code version in IIS

**Comment by AndreiMaz** [comment]
@poyker Could you please re-download the package and try to install it one more time

**Comment by atulrungta** [comment]
> I also got the same issue but I captured the screenshot. Please look at the image.
> 
> ![Untitled](https://user-images.githubusercontent.com/7768934/80829740-54950980-8c05-11ea-816b-db6c6b5ef312.png)
> 
> I got this page right after installation was finished and the website tried to redirect to homepage. I am using no-source version from 4.30 release candidate on a VPS where all other nopCommerce versions are hosted and .net core 3.1.3 hosting bundle is installed.

@AndreiMaz this issue still exists. I did what you said but I got same screen again on my VPS. After refresh, site started working like before.
There is nothing in Log too. How should we trace this problem?

**Comment by skoshelev** [comment]
@AndreiMaz Everything works locally on the last build of the RC from the site, but from the local repository not, so I don’t think that this is because of https://github.com/nopSolutions/nopCommerce/commit/cc8f7146a4ca1b90327d6227335b1c9f502eb2e5 changes

**Comment by AndreiMaz** [comment]
fixed in the updated package
