### ISSUE TITLE
Configure - Manual (Fixed or By Weight and By Total) - cant add 'Next Day Air'  new record

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4647]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: Go to Configure - Manual (Fixed or By Weight and By Total) 
select By Weight
add record
select Next Day Air, and save.
System not save record.
Only when selecting Ground, record saved

**Comment by skoshelev** [comment]
hi @ecommerce-tester. This isn't a bug, just filter, please see the screenshot below

![image](https://user-images.githubusercontent.com/16875599/80862179-92347980-8c7b-11ea-8ddd-b65c71f25067.png)

**Comment by ecommerce-tester** [comment]
@AndreiMaz @skoshelev can we add '*' value by default for Shipping method in search area?
