### ISSUE TITLE
Sort by low to high filter not working with discounted price

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4649]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 
1) I have applied the 10usd discount to "Levi's 511 Jeans" product(without coupon code-sidewide discount) now i have set filter of sort by price but this product not come into sort by price.

url: http://sangeet4-001-site1.etempurl.com/apparel-2?pagesize=18&orderby=10
![screenshot-sangeet4-001-site1 etempurl com-2020 05 02-10_55_01](https://user-images.githubusercontent.com/10364140/80855999-d3209400-8c63-11ea-8f21-0f17c7eed83c.png)

**Comment by AndreiMaz** [comment]
Thanks. But already reported https://github.com/nopSolutions/nopCommerce/issues/2078
