### ISSUE TITLE
Getting error message "Server has been shutdown" in some times

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4650]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 
1) I have deploy my side over shared hosting server.(128mb ram)  
2) Now website not working and send the multiple error pages. old version working fine on the same server configuration. 
I am getting error message that server getting shut down in some time when using website.

![server shutdown](https://user-images.githubusercontent.com/10364140/80856786-999f5700-8c6a-11ea-88c8-475d7323e31b.png)
![aa](https://user-images.githubusercontent.com/10364140/80856787-9ad08400-8c6a-11ea-8553-8aae794031c4.jpg)

**Comment by AndreiMaz** [comment]
According to your screenshot the access to path is denied (some blocking issue).

Also not possible to reproduce without any exact list of steps

**Comment by sangeetshah** [comment]
![support](https://user-images.githubusercontent.com/10364140/80856886-7032fb00-8c6b-11ea-9efe-623ccef04192.png)


My hosting provided telling me that ram is not enought to run site
