### ISSUE TITLE
Estimated Shipping pop up missing (button) - shopping cart 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4652]
nopCommerce version: RC 4.30

Steps to reproduce the problem: 

deployed RC 4.30 

1) add any product in the cart

2) Estimation shipping button missing beside continue shipping also at product detail page even though shipping is enable and product  doesn't have free shi[ping
<img width="914" alt="44" src="https://user-images.githubusercontent.com/41533502/80864801-9aec7600-8ca2-11ea-95c0-44a0f9324591.png">

**Comment by skoshelev** [comment]
Hi @sk5202 
It looks like your browser cached the old version of the stylesheet,
please reset your browser’s cache

Closed #4652

**Comment by noptools** [comment]
This is going to impact customers when a site is upgraded.    Please consider some kind of [Cache Busting](https://www.c-sharpcorner.com/article/how-to-force-the-browser-to-reload-cached-js-css-files-to-reflect-latest-chan/)
