### ISSUE TITLE
Plugin Resource string is missing after install RC 4.30

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4653]
nopCommerce version: RC 4.30

Steps to reproduce the problem: 
1) Get RC 4.30 deployable code from here https://www.nopcommerce.com/en/boards/topic/81557/nopcommerce-430-rc-is-available-please-share-your-impressions

2) Install in local IIS 

All plugin resource string is not imported.

<img width="832" alt="45" src="https://user-images.githubusercontent.com/41533502/80864853-177f5480-8ca3-11ea-9a42-839095b7fba5.png">

**Comment by rajupaladiya** [comment]
Same issue on FaceBook Authentication plugin's configuration page.
![res](https://user-images.githubusercontent.com/13154058/80894291-5808bd80-8cf7-11ea-87b9-76cb6af07284.png)

**Comment by skoshelev** [comment]
Closed #4653
