### ISSUE TITLE
Do not allow to delete the only template (product, category, manufacturer, vendor)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4654]
nopCommerce version: RC 4.30 

Steps to reproduce the problem: 
1) /Admin/Template/List go here
2) Delete Topic template
3) Open any template at front end

/privacy-notice i opened this.

You will get exception. An unhandled exception occurred while processing the request. - Exception: No default template could be loaded

We should not allow to delete the only template

**Comment by sk5202** [comment]
<img width="871" alt="46" src="https://user-images.githubusercontent.com/41533502/80867133-10ab0e80-8cb0-11ea-8d72-15261a836353.png">

**Comment by sk5202** [comment]
same this i found with category , product and manufacture template

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4644

Please re-download and re-install the package

**Comment by sk5202** [comment]
@AndreiMaz  hello this issue happened when topic template deleted. otherwise it is working fine.

Can you please re-read this issue ?

**Comment by AndreiMaz** [comment]
@sk5202 Thanks again! I've just updated the issue description

**Comment by tigran-avdalyan** [comment]
@AndreiMaz @sk5202 @exileDev I think we don't need this changes.
Because if we add limitation to  delete the only template.
We can Rename or Change Path of Template, and get same issue.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan you're right. it's up to a store administrator to manage that
