### ISSUE TITLE
Not able to update Gift Card detail of product from wish list

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4656]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) I have added Virtual Gift Card product into wish list
now i can see edit button to edit gift card detail of product  but i cant update this from wishlist.

![wish list](https://user-images.githubusercontent.com/10364140/80869700-8f5b7800-8cbf-11ea-82cb-722f3339cf8f.png)
![wish list2](https://user-images.githubusercontent.com/10364140/80869702-92566880-8cbf-11ea-8f49-451465defcba.png)

**Comment by AndreiMaz** [comment]
Cannot reproduce. It works fine. The "update" button is displayed (below the "add to cart")

**Comment by sangeetshah** [comment]
![Untitled](https://user-images.githubusercontent.com/10364140/81210509-96e88d00-8fef-11ea-9e7c-2de035adfc59.png)


now looked good
