### ISSUE TITLE
Add a setting to allow/disable multiple reviews for single product 

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4658]
Currently a customer can write multiple reviews for a single product. 

Let's add a new catalog setting that will I think its allow/disable this functionality

![3](https://user-images.githubusercontent.com/10364140/80871350-ad2dda80-8cc9-11ea-9fb3-21ef30725b0c.png)

PR - https://github.com/nopSolutions/nopCommerce/pull/4860

**Comment by denisburlacu** [comment]
#4860

**Comment by DmitriyKulagin** [comment]
See commits https://github.com/nopSolutions/nopCommerce/commit/6a2e2616e3683aeb851636eeb8c080ff462b00b4 and https://github.com/nopSolutions/nopCommerce/commit/ba608f15287a542ef14c7635641d6e445bfdd901
