### ISSUE TITLE
Ability to Delete "Previously Names" from SEO Tab

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#466]
Right now, for I guess redundancy reasons, Nopcommerce keeps an archive of the key entries placed in the 'Search engine friendly page name' field under the SEO Tab of products. 

...there needs to be an easy way to delete those. 

I've lost count as to how many times a product has had a "-2" or "-3" appended to the SEO friendly name because that name (in my case a SKU) is already used by another product; erroneously I might add. 

Why can't there be another subsection under Manage Products -> Attributes? Call it like "SEO Attributes". And in there is a list of all your products with the SEO Tab information displayed (Meta Title, Keyword, Description, SEO Friendly Name). With the ability, like the 'Bulk Edit Products', to just click on the cell you want to edit and only in this area would you be able to override the values and force them to be what ever you like; hey, if it messes up the public side's page (product) links, who cares. -- That's what people like me are paid to fix. ;P 

Right now there's apparently a table with all the values entered into 'SEO Friendly Name' and I'd have to clear that out to drop the value reservation.....I really don't like using dynamite to sweep the floor with. -- If you catch my drift. 

source: http://www.nopcommerce.com/boards/t/37375/suggestion-ability-to-delete-previously-names-from-seo-tab.aspx

**Comment by AndreiMaz** [comment]
it's possible in admin area > system >seo names
