### ISSUE TITLE
Issue with Paypal smart plugin on checkout confirm order section

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4661]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: 
Configure Paypal smart button with valid credentials
Go to checkout page, select Paypal Smart Payment button and make payment via Paypal
Click on continue and reach at confirm order section.
Click on confirm button, here you will get error:
`Payment Error: Plugin not configured`

![Screenshot_1](https://user-images.githubusercontent.com/13154058/80894730-432e2900-8cfb-11ea-88fe-93049aea3272.png)

See this video - https://www.loom.com/share/ba4335dac69a471c94005c28014a2e88

**Comment by rajupaladiya** [comment]
Also I need to one more point regarding PayPal button on cart page.
If cart/order total is zero confirm button should be display instead of PayPal buttons as no need to make any payment here.

![paypalwithfreeorder](https://user-images.githubusercontent.com/13154058/80907089-37f5f000-8d31-11ea-9d30-610fd5d9341a.png)

**Comment by rajupaladiya** [comment]
Regarding Error
> Payment Error: Plugin not configured
This error log I found in log list
Payments.PayPalSmartPaymentButtons error:
One or more errors occurred. ({"name":"VALIDATION_ERROR","message":"Invalid data provided","debug_id":"3503cc93e22fc","information_link":"https://developer.paypal.com/docs/api/webhooks/#errors","details":[{"field":"url","location":"body","issue":"Not a valid webhook URL"}],"links":[]})

**I logged out in PayPal and login again and it seems working and Order placed successfully.**

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/5b57eb8842bbf9a455b1cce206b80e4091870614
