### ISSUE TITLE
Changing from Database to File System for media, breaks Product Page

### ISSUE THREAD

**Issue by zerokewl88** [nopSolutions/nopCommerce#4663]
nopCommerce version:  4.30

Steps to reproduce the problem: 
1. Import products and categories into the system
2. Change from the media storage from database to file system.
3. Open the products page. 

Results : Can't open the products page, datatables error. 

![image](https://user-images.githubusercontent.com/5489947/80898404-35919700-8d2d-11ea-9352-e0ad830cc5b0.png)

**Comment by zerokewl88** [comment]
This could possible be also due to that i was inserting using my own API, and just had to make a change to escape quotes, or else the picture retrieval would break, as i found on a category product listing page.

**Comment by skoshelev** [comment]
Can't reproduce on the clear source code

Closed #4663
