### ISSUE TITLE
Password recovery url contains amp; in url which not working in browser

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4664]
Here is password recovery email content:
`<p><a href="http://localhost:15431/">Your store name</a> 
<br /> <br /> To change your password 
<a href="http://localhost:15431/passwordrecovery/confirm?token=1804dfec-607a-4de4-9903-790a47adda50&amp;guid=518c7c83-717f-4f0c-8868-b2125865289a">click here</a>. 
<br /> <br />
 Your store name</p>`

Here in recovery contains `"&amp;"`, when copy this link and paste address bar in the browser, it redirects to homepage.

![Screenshot_2](https://user-images.githubusercontent.com/13154058/80899353-e0558580-8d2c-11ea-910e-cd1b60907b5a.png)

**Comment by AndreiMaz** [comment]
But you copy it from HTML source code according to your screenshot
. 
When you get this email, you don't read it in HTML in gmail. So it's displayed and copied fine
