### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by mdhcindioglu** [nopSolutions/nopCommerce#4667]
nopCommerce version: 4.3

This is some suggestions:

1. Adding the instagram link to sosyal media links in Admin/Settings and Footer
2. Adding ReSent to customer to return request states

**Comment by AndreiMaz** [comment]
1. duplicates - https://github.com/nopSolutions/nopCommerce/issues/3997 (also by you at https://github.com/nopSolutions/nopCommerce/issues/4666)
2. You can resend any request email in the message queue list

P.S. Please do not make multiple suggestions in one "issue". Also each title should be self-descriptive
