### ISSUE TITLE
When I deleted a category, search engine friendly page name of this category not deleted

### ISSUE THREAD

**Issue by mdhcindioglu** [nopSolutions/nopCommerce#4668]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1- add new category, new Search engine friendly page name will be add.
2- when I delete this new category the search engine friendly page name of this category will not delete.
3- If I added another category and save it a new search engine friendly page name will be added.
4- If I change search engine friendly page name to new name, new search engine friendly page name will be added.
5- when I delete the new category the 2 search engine friendly page names of this category will not delete.
6- in database there are three unusable search engine friendly page names.

**Comment by AndreiMaz** [comment]
It's by design. You can always manually delete a reserved URL in admin area > system > Search engine friendly page names
