### ISSUE TITLE
Same products adding into order instead of increase qty at order edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4669]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) Go to order edit page
2) Add same product into products grid 

![screenshot-nopcommerce430rc nopadvance com-2020 05 03-22_18_29](https://user-images.githubusercontent.com/10364140/80920261-4de4ce80-8d8c-11ea-9919-11e3263cf813.png)

Also a little bit related work item - https://github.com/nopSolutions/nopCommerce/issues/1920 (could be implemented together, with one workflow)

**Comment by RomanovM** [comment]
It's by design. Perhaps we should reconsider this behavior.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
