### ISSUE TITLE
Ability to Change 'Week Start' Day

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#467]
As pointed out here: http://www.nopcommerce.com/boards/t/36690/issue-with-weekly-order-totals-when-first-day-of-the-week-is-different-than-sunday.aspx 

Stuff doesn't work quite right if you want to change the default of 'Sunday' being the start of a new week (truthfully, I don't even understand this..Sunday is part of the week END; as in the end of the week. But whatever.). 

Now, if there is a place to change this then I haven't found it...nor has Google (lol). So it should be there. It's rather annoying to have to keep adding the total sales of 'Sunday' to the weekly sales every single week. 

Source: http://www.nopcommerce.com/boards/t/37280/suggestion-ability-to-change-week-start-day.aspx

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave the current implementation
