### ISSUE TITLE
Limited to customer role not working with category

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4670]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) I have set the limited to customer role guest to gift-cards category
2) Now gift-cards menu hide from public site but i can open this with seoName link

bug : If i have link of this category then i can access this category page from public side without any problem

![2](https://user-images.githubusercontent.com/10364140/80921412-e894db80-8d93-11ea-9b98-c4c9387c34a2.png)
![3](https://user-images.githubusercontent.com/10364140/80921485-53dead80-8d94-11ea-913f-a1c56d25418f.PNG)

**Comment by RomanovM** [comment]
@sangeetshah Not reproduced in latest version. 
I suppose, that you checked this with admin account (AccessAdminPanel permission), in this case you can see category page without any limitation.
Please check this again and provide more details if the error reoccurs.

**Comment by sangeetshah** [comment]
The problem is that if you have the category url and you have set this category only for guest user but if you enter this category url with login customer then you can able to use this category. i am its not allow me to use this category url

**Comment by RomanovM** [comment]
There is no such a problem as you describe. If you set the category as limited only to guests, then registered customers (except admin users, but it's by design) will not be able to see it even at the direct URL.

**Comment by sangeetshah** [comment]
if admin can access this url then one bug is that you have to display this url into top menu as well as left panel of category navigation when role is admin.

**Comment by AndreiMaz** [comment]
@sangeetshah Administrators can preview any hidden category/product/etc, it's by design.
