### ISSUE TITLE
Topic page - Password fields should be mandatory when Password protected is check to true

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4673]
nopCommerce version: RC 4.30 

Steps to reproduce the problem: 

1) Edit any topic page 

2) check Password protected set to true

4) Password fields leave blank 

5) Click on preview System allow you to add password which is not right bcz still you didn't add password.

6) So Password is mandatory when Password protected is enable.

**Comment by exileDev** [comment]
Closed #4673
