### ISSUE TITLE
Cannot restart the application

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4675]
nopCommerce version: 4.30 RC

Any application restart causes the following error to be displayed (not just in VS but even on hosting) - "The service is unavailable"

For example, after installation, after application restart in admin area, plugin reload, etc

**Comment by sangeetshah** [comment]
#4645 might be same issue that i am facing

**Comment by AndreiMaz** [comment]
@sangeetshah You're absolutely right. Thanks! Duplicates https://github.com/nopSolutions/nopCommerce/issues/4645
