### ISSUE TITLE
Warehouse delete exception - SqlException: The DELETE statement conflicted with the REFERENCE constraint

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4677]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: 

1) Edit any product and Go shipping panel and map one ware house. /Admin/Product/Edit/21

2) Edit same ware house from here  from here /Admin/Shipping/Warehouses

3) and press delete button you will get error. 
<img width="925" alt="49" src="https://user-images.githubusercontent.com/41533502/80945005-701c3200-8e08-11ea-997b-4b159c05776e.png">

**Comment by exileDev** [comment]
Closed #4677
