### ISSUE TITLE
Shipping popup apply button does not work properly in the product details page

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4679]
nopCommerce Version: 4.3rc

Steps to reproduce the problem: 
1. Go to any one product details page
2. Refer to this video:- https://www.loom.com/share/ba4bb28eee474de0b50c8fb9dc9e09b3

**Comment by holydk** [comment]
@Kalpeshsali Hello. I fix 'apply button', also you must make sure that you clear the browser cache so that there are no errors in the address fields.

**Comment by Kalpeshsali** [comment]
@AndreiMaz sir

is this bug or not? if this is bug then can you please add bug tag with this issue.

**Comment by holydk** [comment]
Closed #4679
