### ISSUE TITLE
More options on vendor details page. Vendor address

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#468]
storefront - link to the vendors main informaton page 
products - link to all the specific vendors products 
customer comments - usefull way of highlighting this (without the complexity of ebay or amazon style feedback) 
terms & conditions - vendor conditions 
returns - vendors returns policy 
delivery - vendors delivery policy 
Contact and Address details 

Good example: http://www.notonthehighstreet.com/mariaallenjewellery 

I think Vendor contact details should be taken in a controlled way (like customer registration) so that it can be displayed uniformly in the public store (which i think is best practice) - otherwise, every vendor could have their contact details displayed differently and a customer has to search for the the details 

vendor business name : 
vendor name : 

vendor description : ( text editor ) 

vendor street address 1 : 
vendor street address 2 : 
vendor town : 
vendor country : 
vendor postcode : ( maybe as a link to google maps target="_blank" ) 
vendor telephone number : 
vendor mobile telephone number : 
vendor email address : ( :mailto ) 
vendor website : ( target="_blank" ) 

Storeowner should be able to decide whether the 'vendor website' should be displayed - storeowner might not want outgoing links 

---

Regarding address. Allow vendors to have address details. It would be editable in admin area (vendor details page) and public store (my account > vendor info). It could be also entered when applying to vendor account (public store).

We'll store it into "Address" entity. "Vendor" account will have "AddressId" property (without navigation property). Let's just discuss which exactly values will vendors be allowed to enter and which ones will be required

Let's also add a vendor setting indicating whether this data should be displayed in public store on a vendor details page - "Display vendor address"
Source: http://www.nopcommerce.com/boards/t/28316/vendor-page.aspx#117992

**Comment by AndreiMaz** [comment]
Added support for address. Other subtasks moved to https://github.com/nopSolutions/nopCommerce/issues/2001 and https://github.com/nopSolutions/nopCommerce/issues/2002
