### ISSUE TITLE
Images cannot be seen just after the installation

### ISSUE THREAD

**Issue by SohamJadiya** [nopSolutions/nopCommerce#4680]
nopCommerce version: 4.20

I have just finished the installation of my nopcommerce site, but when I visited the site.
The site was working fine, but the problem was with images, the site cannot load any images.

I've looked in the image url it's pointing at localhost, that's wrong I don't know how to point that url to real url.

so is there any solution available?

**Comment by AndreiMaz** [comment]
The error is too general (we cannot reproduce it). What is your website URL?

**Comment by SohamJadiya** [comment]
hospitalyours.com

**Comment by SohamJadiya** [comment]
> The error is too general (we cannot reproduce it). What is your website URL?

Have you considered to test the nopcommerce on centos distribution with cpanel configuration?

**Comment by SohamJadiya** [comment]
> The error is too general (we cannot reproduce it). What is your website URL?
Will you please provide me any solution or full documentation regarding installation and troubleshooting in Centos or RHEL.
