### ISSUE TITLE
Admin dashboard grid collapse design issue 

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4682]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) Go to admin dashboard
2) Hide all the div box and refresh the page
3) open all grid box you can see the grid desing issue
![Dashboard _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/80997814-85707b00-8e5f-11ea-8cf8-c82b030d9f0e.gif)

[A.M.] Just add the appropriate logic to https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/wwwroot/js/admin.common.js#L296

**Comment by AndreiMaz** [comment]
Add the appropriate logic to https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/wwwroot/js/admin.common.js#L296

**Comment by holydk** [comment]
Closed #4682
