### ISSUE TITLE
Validate rental period (ensure not 0)

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4685]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1) set the Rental configuration
enable rental checkbox
2) now open this product at add the required detail and click on rent button
3) now open any page of website you getting error

![1](https://user-images.githubusercontent.com/10364140/81035112-250d2800-8eb7-11ea-9ede-31459369f31a.png)
![3](https://user-images.githubusercontent.com/10364140/81035113-26d6eb80-8eb7-11ea-8d4f-cfbe7d286b7a.png)

Let's add a validation that "Rental period length" > 0 when "Is rental" is ticked

**Comment by AndreiMaz** [comment]
@sangeetshah Thanks. Updated the title and description (not related to gift cards).

**Comment by sangeetshah** [comment]
@AndreiMaz 

but its throw error page so its bug or feature sir?

**Comment by holydk** [comment]
Closed #4685
