### ISSUE TITLE
State list not populated for the india country

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4688]
nopCommerce Version: 4.3rc

Steps to reproduce the problem: 
1. Open anyone product (http://sangeet4-001-site1.etempurl.com/adidas-consortium-campus-80s-running-shoes)
2. Open shipping option
3. Select India in-country
4. Check state not populated in the for India there is displayed only one option (Other) what is the meaning to display

=> https://prnt.sc/sap07f

**Comment by AndreiMaz** [comment]
Please see https://www.nopcommerce.com/en/all-states-provinces-package
