### ISSUE TITLE
As per the user perspective pagination displayed in right side and 'no records' displayed in center

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4689]
nopCommerce Version: 4.3rc

Steps to reproduce the problem: 
1. Go to admin panel
2. Open catalog and click on products
3. Set search option as same as displayed in the screenshot

=> https://prnt.sc/sarxnt

**Comment by AndreiMaz** [comment]
Thanks for suggestion! But it's by design. Furthermore, the place (where "no records" is displayed) usually displays number of records
