### ISSUE TITLE
Option to Exclude Certain IPs / Customers from 'Online Customers'

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#469]
Cause...you know it's rather silly to have 47 online customers....7 of which are in the work place and 10 that don't have any (search bots). 

Why is there no option to, at the very least, exclude Search Bots. And at best, exclude IPs from an 'ignore list'. So you can can an accurate view of how many are on your site. 

Source: http://www.nopcommerce.com/boards/t/37025/suggestion-option-to-exclude-certain-ips-customers-from-online-customers.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
