### ISSUE TITLE
Setup failed: Fatal error encountered during command execution. [Mysql]

### ISSUE THREAD

**Issue by kingsjakal** [nopSolutions/nopCommerce#4691]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Fresh installation 
-> Added mysql connection string "Server=localhost;Port=3308;Database=nopcommerce;Uid=xxxxx;Pwd=xxxxxx;"
-> It says intalling
-> I able to see the tables that are created in mysql server
![image](https://user-images.githubusercontent.com/834427/81080621-92987300-8f0e-11ea-96e3-d93b496a79e0.png)

In console
![image](https://user-images.githubusercontent.com/834427/81080774-c378a800-8f0e-11ea-8468-2bc946a0ddc6.png)

-> After the above log i am getting the following fatal error, it is happening only for mysql based installation, for mssql it is working fine
![image](https://user-images.githubusercontent.com/834427/81080072-f79f9900-8f0d-11ea-86a6-73f67bc01469.png)

**Comment by kingsjakal** [comment]
HI Found the root cause of the issue,

From the following `path`
nopcommerce\src\Libraries\Nop.Data\MySqlDataProvider.cs  
attached snippet line number trying to create the store procedure in MySql 

![image](https://user-images.githubusercontent.com/834427/81103637-f6329880-8f2e-11ea-85ec-c72dfa9fbf5a.png)

from the list of stored procedure, the below is the one of the store procedure throwing the error in mysql 8.0

` CREATE PROCEDURE `Create_FullText_Index`(   `TableName`  varchar(200),   `ColumnNames`  varchar(600),   `IndexName`  varchar(200),     out `Result`   bool ) MODIFIES SQL DATA  sql security invoker BEGIN  set `Result` = true;  select if (   `Check_Exists_FullText_Index`(`TableName`, `IndexName`)   ,'select false into @stmt_result'   , concat('CREATE FULLTEXT INDEX ', `IndexName`, ' ON ', `TableName`, '(', `ColumnNames`, ');')) into @a;     PREPARE stmt1 FROM @a;  EXECUTE stmt1;  DEALLOCATE PREPARE stmt1;          Set `Result` = @stmt_result; END`



I have manually installed the script from
nopcommerce\src\Presentation\Nop.Web\App_Data\Install\MySQL.StoredProcedures.sql 
after the table creation and it started to work.

If the person is not a developer who is installing the nopcommerce using mysql then he cant use the application, it is bug please review the code

**Comment by exileDev** [comment]
@kingsjakal The fact is that you did not specify the `Allow User Variables = True` parameter in your RAW connection string. These stored procedures use User Defined Variables in SQL statements.

**Comment by exileDev** [comment]
Closed #4691
