### ISSUE TITLE
Master checkbox checkbox not unchecked on grid row change of category > add product grid

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4693]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) Edit any category page at admin side
2) now click on add new product and select master checkbox and press delete or next page of grid
![Add a new product _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/81213176-a538a800-8ff3-11ea-804c-3be921b02a16.gif)

**Comment by AndreiMaz** [comment]
@mariannk The same issue is about the "page size" dropdownlist - http://dl3.joxi.net/drive/2020/05/11/0039/0260/2580740/40/111a40cccd.png

**Comment by AndreiMaz** [comment]
@mariannk https://github.com/nopSolutions/nopCommerce/issues/4715
