### ISSUE TITLE
TaxRate Table not found  in  Nop.Plugin.Tax.FixedOrByCountryStateZip

### ISSUE THREAD

**Issue by kwiksys** [nopSolutions/nopCommerce#4694]
nopCommerce version:  4.3 

Steps to reproduce the problem: 
Admin -> Tax Providers -> Configure -> Error Popup

Should have a create table script  for this.

![Nop Plugin Tax FixedOrByCountryStateZip_7May2020](https://user-images.githubusercontent.com/31030124/81262257-1322b500-9070-11ea-9582-f96a4b71973a.jpg)

**Comment by AndreiMaz** [comment]
It works fine when installed from scratch. Try to re-install the plugin

**Comment by kwiksys** [comment]
Thanks
