### ISSUE TITLE
Object reference error when remove specification attribute option

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4695]
nopCommerce version: RC 4.30

Steps to reproduce the problem in frontend: 
1) /Admin/SpecificationAttribute/Edit/1
2) Delete All the option from option tab
3) See at used by product tab on same page
4) View that product and click on preview (means you have to go front side product detail page)

You will get object reference error. https://www.loom.com/share/6afd13fc8a1d4104865a6fbf15ac6e17

<img width="844" alt="50" src="https://user-images.githubusercontent.com/41533502/81273857-21230680-906d-11ea-8fb9-6dc6ffc65207.png">

And the same error in admin area:
1) /Admin/SpecificationAttribute/Edit/1
2) Delete All the option from option tab
3) See at used by product tab on same page
4) Click on View button you will redirect to /Admin/Product/Edit/4 
You will get below error from specification attribute grid
<img width="933" alt="51" src="https://user-images.githubusercontent.com/41533502/81274385-d8b81880-906d-11ea-8a12-5b7dc4b53278.png">

**Comment by skoshelev** [comment]
Closed #4695

**Comment by glhays** [comment]
Has this been resolved?
I am still getting the DataTables warning on my site as the image shows that Andrei added from issue 5202.
Using version 4.3 downloaded from nop downloads in the admin area.
