### ISSUE TITLE
Product Edit (Admin) - DataTables warning: table id=specificationattributes-grid - Ajax error.

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#4696]
nopCommerce version: RC 4.30

Steps to reproduce the problem: 

1) /Admin/SpecificationAttribute/Edit/1

2) Delete All the option from option tab

3) See at used by product tab on same page

4) Click on View button you will redirect to /Admin/Product/Edit/4 

You will get below error from specification attribute grid

<img width="933" alt="51" src="https://user-images.githubusercontent.com/41533502/81274385-d8b81880-906d-11ea-8a12-5b7dc4b53278.png">

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/4695 (actually one issue with caching)
