### ISSUE TITLE
Admin notifications email address

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#470]
At the moment the e-mail account used for "Notify admin for quantity below" is whichever email account is set as Default. I propose this is changed to be able to select the email account that is used. 

Source: http://www.nopcommerce.com/boards/t/36827/notify-admin-for-quantity-below-email-address.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
