### ISSUE TITLE
Add Icons to Product Attributes and specification Attributes

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4700]
Also see https://github.com/nopSolutions/nopCommerce/issues/517
We can use Font Awesome or other Library .

**Comment by ecommerce-tester** [comment]
also see https://github.com/nopSolutions/nopCommerce/issues/249

**Comment by AndreiMaz** [comment]
thanks for suggestion. but we do not plan to implement it
