### ISSUE TITLE
change "Free Shipping " icon

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4703]
Examples https://www.freepik.com/search?dates=any&format=search&page=1&query=free%20shipping&sort=popular
![44279 1](https://user-images.githubusercontent.com/43282933/81315731-ba691180-909b-11ea-99ad-0204ea188cb8.png)

**Comment by AndreiMaz** [comment]
Thanks. But we'll leave it for customization
