### ISSUE TITLE
TinyMCE Bug

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4704]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: Set adminareasettings.richeditoradditionalsettings=True
and edit any Product.

**Comment by ecommerce-tester** [comment]
![image](https://user-images.githubusercontent.com/43282933/81318923-03bb6000-90a0-11ea-97ad-25a1cc1a5d51.png)
![image](https://user-images.githubusercontent.com/43282933/81319034-23eb1f00-90a0-11ea-8b07-0bb485d7de4c.png)
![image](https://user-images.githubusercontent.com/43282933/81319100-382f1c00-90a0-11ea-9c54-6c6dca7ada05.png)

**Comment by AndreiMaz** [comment]
you cannot set it to "true". It should contain additional js values for the editor
