### ISSUE TITLE
Error message should be come instead of success message

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4706]
nopCommerce version: 4.30rc

Steps to reproduce the problem: 
1. Open admin panel
2. Add new product
3. Fill all the required details
4. Click on save and continue 
5. See error message should be come instead of success message

=> https://prnt.sc/sczbty

**Comment by AndreiMaz** [comment]
@Kalpeshsali It's just a warning. It's not prohibited to have the same SKU
