### ISSUE TITLE
Do not load uninstalled plugins in memory

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#471]
Source: http://www.nopcommerce.com/boards/t/36558/uninstalled-plugins-are-loaded-and-run.aspx - this way we also won't register dependencies of uninstalled plugins (IDependencyRegistrar), etc

But we have to properly handle installation/uninstallation of plugins. Currently I see only one way to do it - store a list of plugins to install after application restart in some external text file. Let's discuss other possible ways before implementation

In this case we can ignore IDependencyRegistrar and INopStartup configurations of not installed plugins

**Comment by AndreiMaz** [comment]
currently decided to stay with the current approach

**Comment by RomanovM** [comment]
See also: https://github.com/nopSolutions/nopCommerce/issues/3189

**Comment by sc0ttc0** [comment]
I've not reviewed the latest plugin load code so sorry if this is way off .. but an simple idea I've seen in php environments is to prefix folders with "_"   e.g. plugins prefixed like "_Shipping.UPS" would simply be ignored completely, this is also useful in terms of quickly removing plugins without having to move the whole folder.

**Comment by skoshelev** [comment]
Closed #471
