### ISSUE TITLE
Displayed required attributes error when user open generate several combinations

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4712]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Go to admin panel
2. Open catalog and click on the product
3. Edit any product
4. Move to Product attributes
5. Click on attribute combinations tab
6. Click on generate several combinations

=> https://prnt.sc/sd255n

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4713
