### ISSUE TITLE
Displayed error while save attribute combinations

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4713]
nopCommerce version: 

Steps to reproduce the problem: 
1. Go to admin panel
2. Open catalog and click on the product
3. Edit any product
4. Move to Product attributes
5. Click on attribute combinations tab
6. Click on generate several combinations
7. Close popup
8. Click on Add combination

=>https://prnt.sc/sd1w0j

**Comment by skoshelev** [comment]
Closed #4713
