### ISSUE TITLE
Check out attribute grid master check box not unchecked after grid row change

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4715]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 
1) Go to check out attribute
2) Checked the master check box and perform any action like delete/page size changes
3) master checkbox not unchecked after grid refresh

![Checkout attributes _ nopCommerce administration](https://user-images.githubusercontent.com/10364140/81433846-d85d7180-9182-11ea-81e5-8e587159b2c5.gif)

**Comment by AndreiMaz** [comment]
related to https://github.com/nopSolutions/nopCommerce/issues/4693
