### ISSUE TITLE
Check out attribute dropdown showing me on cart page without values

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4716]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 
1) I have add one check out attribute but i didnt enter values into this attribute
2) open cart page. now you can see this new added checkout attribute without values

![3](https://user-images.githubusercontent.com/10364140/81434435-bfa18b80-9183-11ea-94e6-9c5bced52a95.PNG)

**Comment by AndreiMaz** [comment]
Just enter values and they will be displayed
