### ISSUE TITLE
Will get an error on the first time run with web server.

### ISSUE THREAD

**Issue by cnxinan** [nopSolutions/nopCommerce#4719]
nopCommerce version: 
4.3
Steps to reproduce the problem: 
1 host with web server 
![image](https://user-images.githubusercontent.com/4035333/81473283-e4ebd380-922f-11ea-8acf-470f92651441.png)
2 ctrl+f5 to run. 

Will get the an error "Unable to connect to web server  'Nop.Web' " when the first time to run.

And found an error via console:
![image](https://user-images.githubusercontent.com/4035333/81473326-4449e380-9230-11ea-97c2-5e60109be9f7.png)

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue
