### ISSUE TITLE
Edit tier price for one role deletes same quantity tier price for different role

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#4720]
nopCommerce version: 4.20

Steps to reproduce the problem: 
1) Edit Product - 
2) create tier price with quantity 1, for Registered role
3) create tier price with quantity 1, for Guest role
(both save fine)
4) Edit one of the tiers - e.g. change price, but leave quantity and role the same 
--> the updated tier will be deleted on save action

See forum post
[https://www.nopcommerce.com/en/boards/topic/79516/price-adjustments-per-customer-role#263169]

**Comment by skoshelev** [comment]
Can't reproduce on 4.30

Closed #4720
