### ISSUE TITLE
Master checkbox not unchecked when change pagination and all data exports on export to excel(selected)

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4721]
nopCommerce version: 4.30rc

Steps to reproduce the problem: 
1. Open admin panel
2. Open catalog and click on products 
3. Select master checkbox
4. Go to next page from pagination
5. Return back on 1st page
6. See master checkbox still checked
7. Open export and click on Export to excel (selected)

=> https://www.loom.com/share/d2f1dbf3d2014080b562418c1e3d07dd

**Comment by AndreiMaz** [comment]
Continuation of https://github.com/nopSolutions/nopCommerce/issues/4715 and https://github.com/nopSolutions/nopCommerce/issues/4693

**Comment by mariannk** [comment]
Fixed here: https://github.com/nopSolutions/nopCommerce/commit/3642694493f7f4d210dd90ea8c6cdafe4e9093bb
