### ISSUE TITLE
Design issue when expand collapse search in orders

### ISSUE THREAD

**Issue by Kalpeshsali** [nopSolutions/nopCommerce#4722]
nopCommerce version: 4.30rc

Steps to reproduce the problem: 
1. Go to admin panel
2.Open sales menu and select orders

=>https://www.loom.com/share/5968b408437245e5954a5c4e9dd9d8e0

**Comment by AndreiMaz** [comment]
What exactly is wrong? Please clarify

**Comment by AndreiMaz** [comment]
moved to similar issue https://github.com/nopSolutions/nopCommerce/issues/4723
