### ISSUE TITLE
Display friendly enum names when exporting orders

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4726]
1) Go to order page, export order into excel 
2) Check order status, PaymentStatus, ShippingStatus its showing me id instead of name. its diffucult to find the name based on value.

this issue also exist into oldest version. 

![1](https://user-images.githubusercontent.com/10364140/81504650-18019600-9308-11ea-93ce-db4077f6a326.png)

**Comment by badijm** [comment]
Hi, I can work on that.

**Comment by badijm** [comment]
Added PR.

Upd: It strange that my previous commit somehow appear here.

**Comment by badijm** [comment]
Hi, @skoshelev @AndreiMaz did you have chance to review my PR ?

https://github.com/nopSolutions/nopCommerce/pull/4837

**Comment by skoshelev** [comment]
Hi @badijm. 

I looked at the code you suggested, and I have a couple of comments:
1. Please do not mix refactoring of old code and task execution, it is better to make it a separate PR
2. Your code does not take into account the CatalogSettings.ExportImportRelatedEntitiesByName setting
3. It is better to use a ready-made mechanism using the PropertyByName<T>.DropDownElements properties as it is done in the import / export of products (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/ExportImport /ExportManager.cs#L1194)

**Comment by badijm** [comment]
Okay, I will take a look on the example & update my branch.

**Comment by badijm** [comment]
@skoshelev Ok, I've just pushed some code changes to my branch.

**Comment by skoshelev** [comment]
Hi @badijm. Thank you very much for your contribution, unfortunately, your changes for some reason are not collected in our CI system, in any case, it is better to do everything in one commit since it is very difficult to check a whole series of changes, please make a new PR with a single commit

**Comment by badijm** [comment]
Ok, sure.

**Comment by badijm** [comment]
@skoshelev 

I was almost done with this "migration to single commit", but in the end I struggled with strange issue of **OpenXml**. 

It throws an error only when you export Orders together with Products (`ExportOrderToXlsxWithProducts` method.),
when `_orderSettings.ExportWithProducts` is true. (It is true by default ) 

I'm not sure how proceed with it. 

_Message: 
    System.InvalidOperationException : Validation of E2 failed: Formula1 cannot be empty
  Stack Trace: 
    ExcelDataValidation.Validate()
    ExcelDataValidationWithFormula`1.Validate()
    ExcelDataValidationCollection.ValidateAll()
    ExcelWorkbook.ValidateDataValidations()
    ExcelWorkbook.Save()
    ExcelPackage.Save()
    ExportManager.ExportOrderToXlsxWithProducts(PropertyByName`1[] properties, IEnumerable`1 itemsToExport) line 685
    ExportManager.ExportOrdersToXlsx(IList`1 orders) line 1581
    ExportManagerTests.CanExportOrdersXlsx() line 186_


![success](https://user-images.githubusercontent.com/22330489/95318478-4d061a80-089f-11eb-8bf7-3607b103f6a4.PNG)
![error](https://user-images.githubusercontent.com/22330489/95318480-4d9eb100-089f-11eb-8fbf-84b7563f9e24.PNG)

**Comment by skoshelev** [comment]
Closed #4726
