### ISSUE TITLE
wrong button name of order grid in customer edit page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4727]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 

1) Go to customer edit page at admin side
2) Now check the button name of order grid to view the order

![3](https://user-images.githubusercontent.com/10364140/81505612-31a5dc00-930e-11ea-8995-b025fd540957.PNG)

**Comment by AndreiMaz** [comment]
Continuation of https://github.com/nopSolutions/nopCommerce/issues/4335

**Comment by skoshelev** [comment]
Closed #4727
