### ISSUE TITLE
product stock does not decrease where order status change from cancel to others state

### ISSUE THREAD

**Issue by blue-boy** [nopSolutions/nopCommerce#4728]
nopCommerce version:  all version

Steps to reproduce the problem:  

product stock does not decrease where order status change from cancel to others state

**Comment by AndreiMaz** [comment]
When you change it manually on the order details page it states:

This option is only for advanced users (not recommended to change manually). All appropriate actions (such as inventory adjustment, sending notification emails, reward points, gift card activation/deactivation, etc) should be done manually in this case.
