### ISSUE TITLE
Separate "Estimate shipping" settings for a product details and cart pages

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4729]
Currently, we have one single "Estimate shipping enabled" setting for both pages.It can be very "expensive" to get shipping rates on a product details page.  Consider example where the store uses both FedEx and USPS;  both APIs need to be called, and that takes time.  Even if the calls are asynchronous, it's just a waste.

So let's have two separate settings for that

1. "Estimate shipping (cart page)". Hint: "Check to allow customers to estimate shipping on the shopping cart page.". Setting name "ShippingSettings.EstimateShippingCartPageEnabled"

2. "Estimate shipping (product page)". Hint: "Check to allow customers to estimate shipping on the product details pages. Please note that all the shipping provider APIs will be called on the product details page. Also the final shipping rate in the cart may not be exactly equal to the sum of all the individual estimates.". Setting name "ShippingSettings.EstimateShippingProductPageEnabled"

Source: https://www.nopcommerce.com/en/boards/topic/81681/product-estimate-shipping-rc-430 (point 1)

**Comment by holydk** [comment]
Closed #4729
