### ISSUE TITLE
Product Estimate Shipping doesn't properly sort shipping options

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4731]
The shipping methods displayed are ordered (sorted) by rate (amount). That's not how it shows in the checkout, and it may not be desired when, as in example above, store uses both FedEx and USPS.

We should implement it the same way as during checkout "shipping" step

Source: https://www.nopcommerce.com/en/boards/topic/81681/product-estimate-shipping-rc-430 (point 3)

**Comment by holydk** [comment]
Closed #4731
