### ISSUE TITLE
UPS shipping plugin. Remove Access Point Economy Service and add settings to choose dimension and weight

### ISSUE THREAD

**Issue by Phoetrix** [nopSolutions/nopCommerce#4733]
nopCommerce version: 4.30

Plugin: Nop.Plugin.Shipping.UPS

Steps to reproduce the problem: 

Hi!

When I use UPS shipping plugin I get two errors when I proceed to checkout:

UPS Access Point Economy Service shipments must have a Hold for Pickup at UPS Access Point or UPS Access Point Delivery Shipment Indication Type or must be a Return shipment.
Error code : 111526

This measurement system is not valid for the selected country or territory.
Error code: 111057

I have one product in my shopping cart with dimensions in CM and weight in KGS.
But UPS plugin use "LBS" as default weight unit and "inches" as default dimensions for a product. (See UPSService.cs constants between lines 52 to 62)

When I replace this defaults units values by CM and KGS I don't get any errors and plugin works fine.
So I don't know if I miss something in NopCommerce configuration otherwise I think that the possibility to choose the default dimension and the default weight should be added in the UPS Shipping plugin configuration. 😄

**Comment by AndreiMaz** [comment]
@Phoetrix Do you experience this issue in 4.20 or previous versions?

P.S. 4.30 is not released yet

**Comment by Phoetrix** [comment]
No I use your NopCommerce 4.30 Beta version here => https://www.nopcommerce.com/en/boards/topic/80146/nopcommerce-430-beta-released-please-share-your-impressions

**Comment by RomanovM** [comment]
@Phoetrix Thanks for the info.

>UPS Access Point Economy Service shipments must have a Hold for Pickup at UPS Access Point or UPS Access Point Delivery Shipment Indication Type or must be a Return shipment.
Error code : 111526

We have removed this delivery service from the list. Actually this is a pickup point service, so we need implement IPickupPointProvider to use this feature.

>This measurement system is not valid for the selected country or territory.
Error code: 111057

This plugin always uses lbs and inches, but your store can have any measures in any case values are converted (see [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Shipping.UPS/Services/UPSService.cs#L747) and [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Shipping.UPS/Services/UPSService.cs#L708)) before sending a request. Just ensure that you have properly set measures ratio on the [Measures page](https://admin-demo.nopcommerce.com/Admin/Measure/List).

**Comment by RomanovM** [comment]
@Phoetrix I also implemented your suggestion about new settings for this plugin. Thanks again.
