### ISSUE TITLE
Issue in Order and reward point mapping 

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4734]
Currently, Reward point and order's mapping available in order table by RewardPointsHistoryEntryId with Foreign key.

And when reward point functionality is enable then customer two things can be done,
- Customer earn reward point based on order total
- Customer can use his awarded reward point for payment from payment method in checkout process

So currently, when customer earning xx reward point by place order and spend his/her yy reward point, then yy reward point deduct from customer's account and that reward point history map in order table in RewardPointsHistoryEntryId column.

Now on order is complete, customer should receive his/her xx reward point, but he/she not receiving this reward point due to there is already entry exist in RewardPointsHistoryEntryId column with that order.

So here should be multiple mapping with Order and Reward Point history instead of a single relation.

I hope I made it clear.

**Comment by skoshelev** [comment]
Hi, @rajupaladiya.

This is not entirely so. The fact is that the RewardPointsHistoryEntryId field is used only to store a record of how many bonuses are accrued for placing an order so that later it would be possible to cancel the accrual if the order is canceled. In the case when bonuses are spent on paying for the order, this field is not used.

Closed #4734

**Comment by rajupaladiya** [comment]
@skoshelev - So you mean if I'm placing order of 1000$, and I'm spending 100 reward point of worth 100$ and pay 900$ by payment method during checkout, so I'm not able to earn reward point on pay of 900$?
Is that you mean?

Did you checked this by place order and complete it? If not then please check.

**Comment by rajupaladiya** [comment]
Check line number 909 and 953 in OrderProcessingService, might be you get an idea.

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L909

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L953

**Comment by rajupaladiya** [comment]
@skoshelev - as per your comment, line number 908 to 910 should not in OrderProcessingService.

![reward](https://user-images.githubusercontent.com/13154058/81671020-19e16b80-9466-11ea-8b97-6f9a9a79ad50.png)

**Comment by AndreiMaz** [comment]
@rajupaladiya We cannot reproduce this issue. Everything works fine as expected (tested in 4.30 RC). Could you please provide a complete and detailed list of steps to reproduce it?

**Comment by rajupaladiya** [comment]
Hi @AndreiMaz, 
This is working, I didn't noticed the new added column. Apology for that.
But I found another issue regarding the reward point. 
Posting here soon. Thanks

**Comment by rajupaladiya** [comment]
@AndreiMaz -
New issues are:
1. On redeeming reward point during order place - there is no entry on column RedeemedRewardPointsEntryId in order table
2. If I placed order with redeemed reward point, then on cancel order it reducing awarded reward point but not awarding redeemed reward point during checkout.

Check this video 
https://www.loom.com/share/269226311d324436aa7aaa21f91b453a

**Comment by skoshelev** [comment]
Closed #4734
