### ISSUE TITLE
Shipping method restriction - Checkbox position issue

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4739]
nopCommerce version: 4.3 RC

![image](https://user-images.githubusercontent.com/43282933/81693826-8ada5080-9471-11ea-9d98-b3ba6adc3d0a.png)

**Comment by AndreiMaz** [comment]
The master checkbox at /Admin/Shipping/Restrictions should be at the same location as at /Admin/Payment/MethodRestrictions

**Comment by exileDev** [comment]
Closed #4739
