### ISSUE TITLE
B2B and B2C support/ price list

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#474]
I need to compare Nop versus other shops like shopify and Magento. I know one of the requirements is B2B and B2C pricing with potential different price roles. Also different products per customer group (so distributors get to see other products than consumers). Pricing and incl./ excl. tax also differs. And per country a shop or globally (one shop for certain countries). 

A second requirement is co-creation in a community. Customer 1 creates a product and uploads it online. Other B2C customers are interested in it and purchase it. After purchase this can be either a product which must be created or a digital download of the drawing. 

Forum source: http://www.nopcommerce.com/boards/t/34076/b2b-and-b2c-support-price-lists.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
