### ISSUE TITLE
Facebook Pixel - Multistore Support

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4740]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: Facebook Pixel don't support  Multistore configuration

**Comment by RomanovM** [comment]
It's already supported.

**Comment by ecommerce-tester** [comment]
@AndreiMaz @RomanovM Where is multistore setting?

![image](https://user-images.githubusercontent.com/43282933/81735147-a95a3f00-94a5-11ea-9874-7804fd6b351e.png)

**Comment by RomanovM** [comment]
@ecommerce-tester Here. Ensure that you have properly added multiple stores.
![39dd034067](https://user-images.githubusercontent.com/16698464/81739707-18329a80-949c-11ea-85b4-5980bc75fdb5.png)
