### ISSUE TITLE
Header not coming in export excel file of Newsletter subscribers

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#4743]
nopCommerce version: 4.3rc

Steps to reproduce the problem: 
1) Go to admin side and open Newsletter subscribers section
2) Click on export section and check the file. header is missing into this file

![2](https://user-images.githubusercontent.com/10364140/81720148-9e9aac80-949b-11ea-813f-4dac03566a34.png)

**Comment by skoshelev** [comment]
Closed #4743
