### ISSUE TITLE
Facebook pixel plugin. Ignore CatalogSettings.IgnoreStoreLimitations setting to properly configure plugin for multistore

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4745]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: In admin area go to Widgets>>Facebook Pixel>>Configuration 
Try add Configuration  {Missing Store Select configuration}
When we add configuration, we can see System select Store with minimal value of Store>>Display Order

**Comment by RomanovM** [comment]
@tigran-avdalyan Ensure that you have properly added multiple stores and try again to configure the plugin.

**Comment by tigran-avdalyan** [comment]
![pixel](https://user-images.githubusercontent.com/17789934/81742061-8bdea280-94b0-11ea-90ff-0da2fd592735.gif)

**Comment by RomanovM** [comment]
@tigran-avdalyan Well, I see. What is your `CatalogSettings.IgnoreStoreLimitations` setting value?

**Comment by tigran-avdalyan** [comment]
![image](https://user-images.githubusercontent.com/17789934/81744116-d877ad00-94b3-11ea-9f19-68b3f68b1e77.png)

**Comment by tigran-avdalyan** [comment]
@RomanovM Sorry my mistake
But how i understand  Limitation By Store and Multi Store Support is different  functions. I right?

**Comment by RomanovM** [comment]
@tigran-avdalyan Partially. Usually we consider this settings in plugin multistore configurations, but for this plugin it's not needed. We fix it. Thanks for investigation.
