### ISSUE TITLE
Store name in which order is was placed - is wrong

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4746]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: Create Multi store, place order in Store which display order is not have minimal value, and see Store name in order.
![store](https://user-images.githubusercontent.com/17789934/81746983-66ee2d80-94b8-11ea-9ae7-a59a11e0e954.gif)

**Comment by tigran-avdalyan** [comment]
when i go to Store(bing.com) i don't get errors
![image](https://user-images.githubusercontent.com/17789934/81758785-dd4c5900-94d3-11ea-8d27-dc15844d7348.png)

**Comment by tigran-avdalyan** [comment]
But when i go to Store(Localhost)
i got warning
![image](https://user-images.githubusercontent.com/17789934/81758858-12f14200-94d4-11ea-97f3-b5d4f87286be.png)

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue. Try to debug how the store is detected in WebStoreContext
