### ISSUE TITLE
Product Combination SKU is not working

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#4747]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: Generate Product Combinations by Attributes, set for every combinatin SKU's. And add any Combination to cart, and create order. In order we can't see Combination SKU, we only see product SKU.
![sku](https://user-images.githubusercontent.com/17789934/81748003-27284580-94ba-11ea-9b92-d41214e70acf.gif)

**Comment by skoshelev** [comment]
Hi, @tigran-avdalyan. Everything works as expected. If you need to use the SKU of the attribute combination you need to change the Inventory method to "Track inventory by product attributes"

Closed #4747
