### ISSUE TITLE
Vendor Page form is not showing 

### ISSUE THREAD

**Issue by cxtan8906** [nopSolutions/nopCommerce#4748]
nopCommerce version: 4.20

Steps to reproduce the problem: 
checked **Allow customers to apply for vendor account**	
the apply as vendor form is not shown in public store page

![1](https://user-images.githubusercontent.com/51307924/81787413-97bf7880-9533-11ea-9698-3b75ecdd6707.png)
![2](https://user-images.githubusercontent.com/51307924/81787416-98f0a580-9533-11ea-989d-56b9f206a7dc.png)

**Comment by AndreiMaz** [comment]
Everything works fine as expected
