### ISSUE TITLE
Adding a shared theme folder

### ISSUE THREAD

**Issue by samhippie** [nopSolutions/nopCommerce#4749]
nopCommerce version: 
4.30
Steps to reproduce the problem: 
N/A

We recently created a second theme for our store, and we found that we had to copy and paste a lot of our custom views from one theme to the other, which is difficult to maintain. We want to avoid modifying the base nop /Presentation/Nop.Web/Views folder to make upgrades easier. 

We added a Shared folder to the /Presentation/Nop.Web/Themes folder for views that are used by all of our themes, and we modified Nop.Web.Framework.Themes.ThemeableViewLocationExpander to look in this Shared folder if the view was not found the the current theme's folder. This way any theme can override a shared view, but all themes have the shared view by default. I'll put together a pull request with our implementation.

**Comment by AndreiMaz** [comment]
@samhippie Thanks a lot. But after some consideration we've decided not to implement this functionality and leave it for customization
