### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#475]
Hi guys. 

I want to talk about administration access security. 

A lot of sites started to add another authentication method to increase security. So, I think Nop should follow them. 

Google Authenticator is a good choice and easy to use. 

http://www.codeproject.com/Articles/403355/Implementing-Two-Factor-Authentication-in-ASP-NET 

https://googleauthcsharp.codeplex.com/ 

The admin area is very critical to all stores. Any unauthorized access could make big losses, hacking or taking some self-advantage changing/reading informations. 

What do you think? 
I think to use it only for admin access, not for all customer, but in this case, more development will be required. 

Thanks! 

Source: http://www.nopcommerce.com/boards/t/34056/two-factor-authentication-google-authenticator.aspx

**Comment by DmitriyKulagin** [comment]
Closed #475
