### ISSUE TITLE
"main-header" on admin area, color black in LTR but blue in RTL version

### ISSUE THREAD

**Issue by MafdyAzer** [nopSolutions/nopCommerce#4752]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: 
- Install a new version 4.30 RC with source
- Add Arabic language as RTL version.
- Change admin area language from English to Arabic.
- When language is English, main-header background color are black
- But, when language is Arabic, main-header are blue "the old css"

- Another issue, logo in RTL not display correct.

Screenshots:
 
- English:
![image](https://user-images.githubusercontent.com/57217759/81921628-32bf5d80-95db-11ea-9af6-9c531dede611.png)

- Arabic:
![image](https://user-images.githubusercontent.com/57217759/81921687-479bf100-95db-11ea-8531-48f45a51bb1b.png)

**Comment by MafdyAzer** [comment]
Logo Issue fixed by:

.main-header .logo-lg {
-- add:
    background-size: contain;
    background-origin: content-box;
    padding: 0 10px;
}
at styles.rtl.css

**Comment by exileDev** [comment]
Thank you! Closed #4752
