### ISSUE TITLE
Performance optimization when you have a lot of specification attributes and product tags

### ISSUE THREAD

**Issue by okarpov** [nopSolutions/nopCommerce#4753]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1) add +40K products 
2) Add specification attributes and specification attribute options - 10 per product minimum
3) Add +70K Product Tags
4) Upgrade from 4.1 to 4.2

Website becames almost unsusable - a lot of SQL Timeout exceptions

Also this was a big mistake changing from Home**P**age to Home**p**age - a lot of headace with it!

Thank you

**Comment by AndreiMaz** [comment]
@okarpov Is it possible to share your database backup?

**Comment by okarpov** [comment]
only 4.1 version
but need to remove sensitive data

**Comment by AndreiMaz** [comment]
it works quite fast on our test websites. I presume something were done wrong way (e.g. upgrade, etc). I would recommend to post it on our forums to find out what exactly

**Comment by okarpov** [comment]
so you don't need our DB anymore?

**Comment by AndreiMaz** [comment]
@okarpov Sure, please send a download link to [info][at][nopcommerce]dot[com] with a reference to this work item 

But I can say that we'll test it on the latest 4.30 version (will run the upgrade script to 4.30 and test it on 4.30).

**Comment by okarpov** [comment]
sent email, thx
4.3 is fine - whatever version is fine if it is stable and really much faster than 4.1

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/4980
