### ISSUE TITLE
Dashboard CSS small Issue, RTL Version (affects: Arabic, Hebrews, Farsi, ...etc)

### ISSUE THREAD

**Issue by MafdyAzer** [nopSolutions/nopCommerce#4754]
nopCommerce version: 4.30 RC

Steps to reproduce the problem: 
- Fork latest develop branch

Issue:
- Admin dashboard > Latest orders report >  order status badge css in RTL need padding right 0.6em;

- Correct CSS at LTR version:
![image](https://user-images.githubusercontent.com/57217759/81946589-d7539680-95ff-11ea-90ff-59e27d620f90.png)

- Incorrect CSS at RTL version:
![image](https://user-images.githubusercontent.com/57217759/81946949-4204d200-9600-11ea-85f9-252b4005be00.png)

- Fixed by edit styles.rtl.css Line 1212:

/*grid color statuses*/
.span.grid-report-item {
    padding: .2em .6em .3em .6em;
    ----
}

**Comment by AndreiMaz** [comment]
@exileDev see https://github.com/nopSolutions/nopCommerce/pull/4755

**Comment by ronenelahav** [comment]
another minor bug... 
![image](https://user-images.githubusercontent.com/17380300/82335532-24fe4380-99f2-11ea-92a7-128433563acf.png)
the cursor class for the sidebar menu should be left instead of to right: 
"fa-angle-right"=> "fa-angle-left"
