### ISSUE TITLE
Problem in moving child category from one category to onther

### ISSUE THREAD

**Issue by mdhcindioglu** [nopSolutions/nopCommerce#4758]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1- Go to admin/categories
2- Search for Shoes category
3- Change Parent category from Apparel to Books
4- In main menu Apparel, Shoes directory will disappear and you can show it in Book menu (That's OK)
5- If you clicked on Apparel category in main web site you still see Shoes (That's wrong because we moved it)
6- If you clicked on Book category in main web site you will see Shoes (That's OK).
7- If I clear cache from admin page then every thing will be fine.

I thing problem is not deleting Shoes from Apparel in cache

![01](https://user-images.githubusercontent.com/49324748/82028230-0587b380-969e-11ea-991c-5fc6383ddafd.jpg)

![02](https://user-images.githubusercontent.com/49324748/82028264-0fa9b200-969e-11ea-8544-07dad79f3399.jpg)

**Comment by skoshelev** [comment]
Can't reproduce on the latest source code

Closed #4758

**Comment by skoshelev** [comment]
Closed #4758
