### ISSUE TITLE
Free shipping block doesn't properly work on the details page of the grouped product

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#4759]
nopCommerce version: 4.30RC

Steps to reproduce the problem: 
1. We have the grouped product that have 2 simple products.
1. First simple product have some attribute.
1. Second simple product have the free shipping.
1. Free shipping disappears for the second simple product (when page is loaded or attribute is changed).
It's related with one [event handler](https://github.com/nopSolutions/nopCommerce/blob/90e5eb132ef13d62036ba53aad1cf1fdcc7c0586/src/Presentation/Nop.Web/Views/Product/_DeliveryInfo.cshtml#L6) on page.
https://www.loom.com/share/ee5931b8888e41d9a1795ee514b6cc92

**Comment by skoshelev** [comment]
Closed #4759
