### ISSUE TITLE
Rental products better funcionality

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#476]
We were very happy to see that rental product support now has been added. It is very welcome! 

...but we think that the current rental products need to have better functionality and more possibilities in the admin area: 
 * A better overview of rental products. 
You can't see when a product is rented and you can rent a product that has already been rented. IE double booking. 
We would like to see which dates are occupied in the calender on the outside as well as the administration.
 * A good idea might be to have a dashboard panel that shows an overview of the current rented products.
 * Rent a product by the hour 
   Now you can rent a product in days as minimum period.
 * Different prices for different periods 
   For example an hotel may want to charge more in the weekends. No matter which kind of period you use (hours, days, weeks etc)

**Comment by AndreiMaz** [comment]
duplicated
