### ISSUE TITLE
Nop.Plugin.Shipping.UPS - How to allow NegotiatedRatesIndicator?

### ISSUE THREAD

**Issue by Phoetrix** [nopSolutions/nopCommerce#4760]
nopCommerce version: 4.30 (Last version of the develop branch)

Steps to reproduce the problem: 
Before begin thanks to @RomanovM for the support in my last issues. :)

Everything works fine with the plugin but I have a last question.
My client said that shipping prices is too expensive so I discussed with the UPS Staff and they say me that the request to UPS service miss "/NegotiatedRatesIndicator".
I searched in the plugin code and I found in "Connected Services => UPSRate => Reference.cs" that the value "NegotiatedRatesIndicator" is present. But I don't know how to use it and I don't find any parameter for that in the config.

My client is supposed to have -60% for all shippings. Do you have an idea?

**Comment by RomanovM** [comment]
@Phoetrix Negotiated rates can be obtained if you specify AccountNumber in your configuration, there is even the hint for this field: "Specify UPS account number (required to get negotiated rates)."
Could you please post all your questions on [our forums](https://www.nopcommerce.com/en/boards). We use GitHub as an issue tracker only.
