### ISSUE TITLE
Request duration is too long up to several minutes

### ISSUE THREAD

**Issue by Farb** [nopSolutions/nopCommerce#4761]
nopCommerce version: 4.3

Steps to reproduce the problem: 

Note:(My original nopCommerce version is 4.2 develop)
1.I downloaded the latest zip package,upzip it.
2.I replaced many files with same file name,but not all,because some files has different business logic.
3.After replaced,I fixed all the errors.
4.Build successfully.Then Publish to IIS.
5.I run the application,and find it is very slow,even for several minutes.And basicly,every request is quite slow.

The following is the result of Mini-profiler:
![YRC60I.png](https://s1.ax1x.com/2020/05/17/YRC60I.png)

![](https://s1.ax1x.com/2020/05/17/YRCtTx.png)

**Comment by AndreiMaz** [comment]
@Farb it works quite fast on our test websites. It's not possible to investigate it without your database backup. But I presume something were done wrong way (e.g. upgrade, etc). I would recommend to post it on our forums to find out what exactly

**Comment by Farb** [comment]
@AndreiMaz Thanks a lot! 
I have found the answer. Because I did not execute the update sql script.
And the default cache time is 0 minutes, so every request that needs to transform local source string ,it will get all the data in the localestringresouce table every time.
So if not execute the update script or set default cache time (because of forget or typo),it will be terrible.

Finally,I sugget that we had better give the default cache time value, like the flowing code:

```
namespace Nop.Core.Caching
{
    /// <summary>
    /// Caching settings
    /// </summary>
    public class CachingSettings : ISettings
    {
        /// <summary>
        /// Gets or sets the default cache time in minutes
        /// </summary>
        public int DefaultCacheTime { get; set; } = 60;

        /// <summary>
        /// Gets or sets the short term cache time in minutes
        /// </summary>
        public int ShortTermCacheTime { get; set; } = 5;

        /// <summary>
        /// Gets or sets the bundled files cache time in minutes
        /// </summary>
        public int BundledFilesCacheTime { get; set; } = 120;
    }
}
```

**Comment by Farb** [comment]
@AndreiMaz Thanks a lot! 
I have found the answer. Because I did not execute the update sql script.
And the default cache time is 0 minutes, so every request that needs to transform local source string ,it will get all the data in the localestringresouce table every time.
So if not execute the update script or set default cache time (because of forget or typo),it will be terrible.

Finally,I sugget that we had better give the default cache time value, like the following code:

```
namespace Nop.Core.Caching
{
    /// <summary>
    /// Caching settings
    /// </summary>
    public class CachingSettings : ISettings
    {
        /// <summary>
        /// Gets or sets the default cache time in minutes
        /// </summary>
        public int DefaultCacheTime { get; set; } = 60;

        /// <summary>
        /// Gets or sets the short term cache time in minutes
        /// </summary>
        public int ShortTermCacheTime { get; set; } = 5;

        /// <summary>
        /// Gets or sets the bundled files cache time in minutes
        /// </summary>
        public int BundledFilesCacheTime { get; set; } = 120;
    }
}
```
