### ISSUE TITLE
RoxyFileman thumbnails on rollover don't show up

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4762]
nopCommerce version: 4.30

Upload an image in a topic page using Roxy Fileman.
Roll over that image in the Roxy Fileman file browser.

Error: System.NotSupportedException: 'Stream does not support reading.'

The error happens in Nop.Services.Media.RoxyFileman.FileRoxyFilemanService, at this point:

`cropImg.GetThumbnailImage(width, height, () => false, IntPtr.Zero).Save(GetHttpContext().Response.Body, ImageFormat.Png);`

Changing it to something along the lines of this, will work:

```
using (MemoryStream ms = new MemoryStream())
{
        cropImg.GetThumbnailImage(width, height, () => false, IntPtr.Zero).Save(ms, ImageFormat.Png);
        byte[] msa = ms.ToArray();
        GetHttpContext().Response.Body.WriteAsync(msa, 0, msa.Length);
}
```

**Comment by skoshelev** [comment]
Hi, @alinmircea. Thank you for your help.

Closed #4762
