### ISSUE TITLE
Performance optimization for multiple requests during the application restart

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4763]
One of the scenario's in which we were able to easily reproduce performance issues before was by running a load test during application restart (so to simulate a disaster recovery situation for one of our stores). With those tests we were always able to stop the application from starting up for an extended time while being able to see threadcount rising out of control in the Azure Monitor logs.

We can consider some kind of "blocking" (queuing) simultaneous requests during the application startup. Although not sure whether it's possible 

Here is a more specific requirement from one of our Gold partners (Andrei has more details - email from June 19th 2020):

> The application is able to start up after an application restart or application pool crash under heavy traffic load, without exhausting the number of available threads on the thread pool. In a reasonably performant environment (4 cores, 7GB RAM, Azure SQL 200DTU database), the application should start up and begin handling meaningful web requests within 5 minutes under normal production traffic (2.5k req./min.).

Also related: https://github.com/nopSolutions/nopCommerce/issues/2494 (suggested in one of the comments below)

**Comment by dhruvpiesoftware** [comment]
Hello @AndreiMaz ,

We have deployed **nopCommerce 4.3 RC** version on **Azure Linux App Service**. We are also facing the performance issue. Even basic page like login, register, home page is also taking time like 12-15 seconds minimum. 

Regards,
Dhruv Pandya

**Comment by AndreiMaz** [comment]
@dhruvpiesoftware It works fine on our test website. I presume you upgraded without running the upgrade script. What is the value of your "CachingSettings.ShortTermCacheTime" setting?

**Comment by dhruvpiesoftware** [comment]
Hi @AndreiMaz ,

Running upgrade script worked for us. Now we are not facing any performance issue.

Thank you.

Regards,
Dhruv Pandya

**Comment by clearbucketLabs** [comment]
This is definitely dev ops related.  load balancer needs to check the health and block requests until the server is ready. same for auto-scaling.

**Comment by exileDev** [comment]
We don't plan to do this. The problem isn't reproduced in a case with a single instance now. Otherwise, you can perform the health check on any page by ARR or Azure tools for the web farm.

Closed #4763
