### ISSUE TITLE
Datatable design issue at the dashboard (admin area)

### ISSUE THREAD

**Issue by Farb** [nopSolutions/nopCommerce#4764]
nopCommerce version: 4.3RC
Steps to reproduce the problem: 
After install mssql  database,restart the application.show this style.
I run the app in vs debug mode.

![YhmqHK.png](https://s1.ax1x.com/2020/05/18/YhmqHK.png)

**Comment by AndreiMaz** [comment]
@farb Here is it - https://admin-demo.nopcommerce.com/admin. No issues. Do you expreicne the same issue on our demo website?

**Comment by Farb** [comment]
@AndreiMaz  Yep,your demo website has the same style problem.
What's wrong? I used the Chrome browser and microsoft priview edge browser.They are the same behavior. 


[![YhuXSH.png](https://s1.ax1x.com/2020/05/18/YhuXSH.png)](https://imgchr.com/i/YhuXSH)

**Comment by AndreiMaz** [comment]
1. What is your browser resolution?
2. have you reset your browser cache (CTRL+F5)?

**Comment by Farb** [comment]
1.I have tried (CTRL+F5) and clear the cache in the past 24 hours.Then it did not work.
2.When I set the page to zoom 90%, it's ok to look. But this problem occurs when the scaling is 100%.

**Comment by Farb** [comment]
My screen resolution is 1366*768.

**Comment by mariannk** [comment]
Fixed when working on [this issue](https://github.com/nopSolutions/nopCommerce/issues/4193)
