### ISSUE TITLE
503 error during the application restart

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4765]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Try to restart an already deploy application
2. You'll get the 503 error (service is not available)
3. When i refresh the page again then it reloads fine

The same happens when you install nopCommerce

But sometimes it works fine, sometimes - not

Related: https://github.com/nopSolutions/nopCommerce/issues/4770, https://github.com/nopSolutions/nopCommerce/issues/4645, https://github.com/nopSolutions/nopCommerce/issues/4405

Also see https://www.nopcommerce.com/en/boards/topic/81873/43-release-http-error-5030-server-has-been-shutdown

**Comment by AndreiMaz** [comment]
The fix - https://github.com/nopSolutions/nopCommerce/commit/65b738824e42c39daae91ef9f3c7c23195f85a26

**Comment by FerNet23** [comment]
Hi,
Unfortunately, the problem still exists .
After install fresh copy of nopcommerce 4.30, i got the following error:
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Nop.Web.Controllers.InstallController.RestartApplication (Nop.Web) in 3.9461ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Nop.Web.Controllers.InstallController.RestartApplication (Nop.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 17.1782ms 200

C:\Users\FerNet\Documents\Visual Studio 2019\Projects\sharamStore\Presentation\Nop.Web\bin\Debug\netcoreapp3.1\Nop.Web.exe (process 21604) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

Please help me to resolve the problem .

**Comment by untiedshoes** [comment]
Just to add, I'm having the same issue too. Fresh installation of 'no source' nop4.30, running on my local IIS.

Uninstall a plugin, then click 'Restart application to apply changes' - results in 'service is not available'.

I have to refresh to load the site again, but it takes forever.

Also, it doesn't happen every time. Sometimes, the restart goes as planned, other times, I get the service is not available.

**Comment by mitcht** [comment]
In \NopCommerce\Libraries\Nop.Services\Media\PictureService.cs , change `mutex.WaitOne()` to `mutex.WaitOne(500)`
