### ISSUE TITLE
kendo.messages.zh-CN.min.js has bug

### ISSUE THREAD

**Issue by Farb** [nopSolutions/nopCommerce#4768]
nopCommerce version: 4.3 release

Steps to reproduce the problem: 
Login the Admin home page,browser console throw this js exception.
Uncaught TypeError: Cannot read property 'ChatView' of undefined.

I've compared the two files，kendo.messages.zh-CN.min.js and kendo.messages.en-US.min.js
kendo.messages.zh-CN.min.js has the property 'ChatView' ,but kendo.messages.en-US.min.js not.

**Comment by AndreiMaz** [comment]
@Farb So you see the error in the browser console. But does the website (admin area) work fine?

**Comment by Farb** [comment]
@AndreiMaz It's like going to slow down a little bit.

**Comment by AndreiMaz** [comment]
it's a third-party library (KendoUI). They should fix it, not our team. Once it's done, we'll update the package
