### ISSUE TITLE
Setup failed: An error occurred while creating the database: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.

### ISSUE THREAD

**Issue by mane06** [nopSolutions/nopCommerce#4769]
nopCommerce version:  
4.20
Steps to reproduce the problem: 

Hello, I appreciate in advance the support provided.

I have followed to the letter the instructions given in this link: https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html

and everything works fine until I get to this point I have an error with SQL:

Setup failed: An error occurred while creating the database: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.

What could it be ?

![image](https://user-images.githubusercontent.com/50756282/82368813-a4cce380-99db-11ea-98e6-b98f64163ced.png)

![image](https://user-images.githubusercontent.com/50756282/82368827-ab5b5b00-99db-11ea-9d76-fb867a40d970.png)

**Comment by AndreiMaz** [comment]
@mane06 we'll update this article in the near time for version 4.30. Please try it one more time once it's done
