### ISSUE TITLE
Impersonate (place order). Allow a store owner to purchase products with "call for price"

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#477]
I have a vendor that has requested that I not show the price of their product on my site. They sell both wholesale and retail, and have their own retail e-commerce site. I made the changes for their products by selecting the "call for price" checkbox . When I go to Place Order (Impersonate), the products cannot be purchased

I would like a feature that would allow the Administrator to see the "price" button when in the impersonate mode. This would allow for the Administrator to complete the purchase via phone or secure chat on the back-end without changing what the customer sees on the front-end. 

Let's make it configurable. "Allow a store buy products with "call for price" enabled" (enabled by default). 

Source: http://www.nopcommerce.com/boards/t/33419/a-new-feature-for-place-order-impersonate.aspx 

also see comment by New Yrok at http://www.nopcommerce.com/boards/t/33419/a-new-feature-for-place-order-impersonate.aspx#136388

**Comment by AndreiMaz** [comment]
related work item https://github.com/nopSolutions/nopCommerce/issues/2510
