### ISSUE TITLE
HTTP Error 503.0 - Server has been shutdown

### ISSUE THREAD

**Issue by breaup** [nopSolutions/nopCommerce#4770]
nopCommerce version: 4.3

Steps to reproduce the problem: 

I run Visual Studio 2019, when I open without debugging, go to the plugin list and click reload plugin list it crash IIS Express. I went and installed it on IIS and tried the same thing and same problem happen.

When I check in the log it says Application Shutdown 
`
info: Microsoft.Hosting.Lifetime[0]

      Application is shutting down...

info: Microsoft.AspNetCore.Mvc.RedirectToActionResult[1]

      Executing RedirectResult, redirecting to /Admin/Plugin/List.

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]

      Executed action Nop.Web.Areas.Admin.Controllers.PluginController.ReloadList (Nop.Web) in 5.5722ms

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

      Executed endpoint 'Nop.Web.Areas.Admin.Controllers.PluginController.ReloadList (Nop.Web)'

info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

      Request finished in 71.1427ms 302 
`
Anyone else encountered this ? Except that it installed properly running fine.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/4645

**Comment by alextretij** [comment]
I have the same error message on fresh nop 4.30 instance.
