### ISSUE TITLE
Missing locales for the Avalara plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4774]
nopCommerce version: 4.30

On the Avalara configuration page. Missing locales after upgrade from 4.20:
1. Plugins.Tax.Avalara.Fields.EnableLogging
2. plugins.tax.avalara.fields.taxoriginaddresstype.shippingorigin.warning

**Comment by mariannk** [comment]
plugins.tax.avalara.fields.taxoriginaddresstype.shippingorigin.warning is missed as well
