### ISSUE TITLE
Plugins page. Rename "Is enabled" to "Enabled"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4775]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Go to the "Local plugins" page
2. It has two locales - "Installed" and "Is enabled".

Let's make them consistent

**Comment by badijm** [comment]
I can grab this one. Looks easy enough

**Comment by AndreiMaz** [comment]
@badijm sure, please contribute

**Comment by holydk** [comment]
Closed #4775
