### ISSUE TITLE
Product Attribute Combination Price Override Not Working

### ISSUE THREAD

**Issue by joekrauss** [nopSolutions/nopCommerce#4776]
nopCommerce version: 4.3

Steps to reproduce the problem: 
Configure a product with tier pricing (e.g. $20 for retail, $20 for vendor, etc.). Configure multiple product attribute combinations (color and sizes). Set a price override value for one of the product attribute combinations (e.g. $2.00). The product price and cart price never get overridden by the attribute combination override value.

![ProductAttributeCombinations_CombinationsList](https://user-images.githubusercontent.com/41585973/82576850-d070da80-9b4f-11ea-9964-94fcecfbd70d.PNG)
![ProductAttributeCombinations_EditField](https://user-images.githubusercontent.com/41585973/82576853-d1097100-9b4f-11ea-8847-f4510475872c.PNG)
![ProductFrontEnd_CombinationSelected](https://user-images.githubusercontent.com/41585973/82576855-d1097100-9b4f-11ea-9a8c-0c959291b10f.PNG)

**Comment by AndreiMaz** [comment]
@joekrauss Please go to your product details page, open the "Inventory" tab. What is the value of the "Inventory method" dropdownlist?

**Comment by joekrauss** [comment]
@AndreiMaz  Its set to track inventory by product attributes. This issue started on version 4.2 we just worked around not using attributes to avoid the price issue.

![image](https://user-images.githubusercontent.com/41585973/82587612-1da87880-9b5f-11ea-8426-f9e79343e8fd.png)

**Comment by skoshelev** [comment]
Hi @joekrauss. This is not a mistake, it is by design. The logic of this behavior is as follows: the tier prices always overlap the price of the product, it does not matter how the price of the product is calculated by attributes or by a set value

Closed #4776

**Comment by joekrauss** [comment]
Hello @skoshelev, I'm not sure I understand the purpose of the product attribute combination price override if it doesn't actually override the tier or product price. If you don't mind can you explain when the override price option works if not against the tier or product price? Thanks

**Comment by skoshelev** [comment]
I will try to explain to you in detail:
For a product, you can indicate its current "Price" value (and "Old price") - we will consider this the basic price of the product. If a product has combinations of attributes, and for some of them defined the “Overridden price” value, then this price will be considered the base price, that is, it will replace “Price”. And the tier pricing mechanism is designed to redefine the price of the product depending on the number of products in the cart, and it redefines the cost of the product, no matter how it was calculated.
