### ISSUE TITLE
Consider enabling test code coverage

### ISSUE THREAD

**Issue by networkfusion** [nopSolutions/nopCommerce#4778]
Test Code coverage is an important part of unit testing, please consider enabling it.

https://networkfusion.wordpress.com/2020/05/19/nopcommerce-4-3-build-pipeline-on-visualstudio-online-azure-devops-with-code-coverage/

As you are an open source project, https://sonarcloud.io/ (which is free for open source projects) would help you with code smells etc, would also be worth considering (since it has full GitHub integration).

**Comment by AndreiMaz** [comment]
thanks. moved to https://github.com/nopSolutions/nopCommerce/issues/405
