### ISSUE TITLE
Customer address fields issue

### ISSUE THREAD

**Issue by networkfusion** [nopSolutions/nopCommerce#4779]
nopCommerce version: 4.3

Steps to reproduce the problem: Something looks wrong here:

![image](https://user-images.githubusercontent.com/11439699/82602111-7c461480-9ba8-11ea-99da-33f43404d550.png)

**Comment by AndreiMaz** [comment]
@networkfusion "Something looks wrong here"

What exactly?

**Comment by networkfusion** [comment]
@AndreiMaz If you look at the picture's highlighted fields you will see that they do not conform to all of the other fields, for example all of the fields conform to:
`'x' is enabled` -`'x' is required`

where as the highlighted shows:
`'Country' is enabled` - `'State/Province' is enabled`

Perhaps this is by design??

**Comment by AndreiMaz** [comment]
It's by design. states cannot be enabled without countries
