### ISSUE TITLE
Ensure no exception is thrown when we have duplicated locale names

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4782]
If you have a language resource with the same key (there is no constraint in the database to ensure unique keys) then nopCommerce 4.30 will throw an exception because of this code assuming the resource name is unique:

```
var lsNamesList = _lsrRepository.Table
                .Where(lsr => lsr.LanguageId == language.Id)
                .ToDictionary(lsr => lsr.ResourceName, lsr => lsr);

```
Source: https://www.nopcommerce.com/en/boards/topic/80047/nopcommerce-430-bug-fixes-and-improvements/page/6#264900

**Comment by roman-gherman** [comment]
fixed in https://github.com/nopSolutions/nopCommerce/pull/4816

**Comment by skoshelev** [comment]
Closed #4782

**Comment by sorenaxla** [comment]
We had to revert this commit in our solutions as the orderBy part didn't complete. As an result the solution did not proceed from the method and the solution could not start up when run localhost. We have a single language (updated from the Danish 4.20 version) in the solution that we first encountered this issue.

**Comment by roman-gherman** [comment]
@sorenaxla what do you mean with: "orderBy part didn't complete"? 
did it hang there? where there any errors?

**Comment by sorenaxla** [comment]
Yes, it hangs. I have tried in two different 4.30 solutions with two different languages in each and the issue occurs only with the new commit:

                  .GroupBy(lsr => lsr.ResourceName, (key, groupedLsr) => 
                      groupedLsr.OrderBy(lsr => lsr.Id).Last())

Note, that both sites are using the NopThemes Prisma theme (latest 4.30 version) which adds some strings, which might/could be the issues... just a note.

I have attached the xml for the english language extracted from one of the solutions.
[language_pack (1).txt](https://github.com/nopSolutions/nopCommerce/files/4735815/language_pack.1.txt)

**Comment by joekrauss** [comment]
We are currently testing 4.3 with Nop-Templates and I see a 2 to 4 minute delay starting the website after applying the code changes to correct the duplication exception error. 

I verified the NopCommerce settings to load locals, SEO, etc. are not checked during startup. Removing Nop-Templates plug-ins & themes allows the site to quickly startup within 30 seconds. I have my own custom plugins enabled, so either the change impacted performance on NopCommerce startup or something is wrong with Nop-Templates plugins / theme.

**Comment by roman-gherman** [comment]
@skoshelev I have reproduced the issue guys are talking about, the STARTUP is really slow when having a lot of language resources.

I have fixed it with https://github.com/nopSolutions/nopCommerce/pull/4892
