### ISSUE TITLE
4.2 to 4.3 upgrade script - remove dbo. prefix 

### ISSUE THREAD

**Issue by jonquickqsense** [nopSolutions/nopCommerce#4785]
this action fails if existing database is not installed under dbo schema, and UsedWithOrder column is not created, leading to runtime errors using Reward Point History

--new column
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=object_id('[RewardPointsHistory]') and NAME='UsedWithOrder')
BEGIN
	ALTER TABLE dbo.RewardPointsHistory ADD UsedWithOrder uniqueidentifier NULL
END
GO

**Comment by skoshelev** [comment]
Closed #4785 by [this commit](https://github.com/nopSolutions/nopCommerce/commit/7b1bdf8ff306dd250e53fc5cce784b31e6285c7f)
