### ISSUE TITLE
Problematic numbers

### ISSUE THREAD

**Issue by arshyuo2** [nopSolutions/nopCommerce#4786]
nopCommerce version:  4.3

when update nopcommerce 4.2 to 4.3 all numbers on the admin page have a problem.
But when I click on the text box to edit the numbers, they are displayed correctly without any changes!
![number broken](https://user-images.githubusercontent.com/65789306/82709488-f30d0b80-9c95-11ea-8ea1-cbaab915f102.jpg)

**Comment by AndreiMaz** [comment]
@arshyuo2 What is the culture of language? Please go to admin area > configuration > languages > details page and check. 

I presume it's related to the following forum post - https://www.nopcommerce.com/en/boards/topic/81817/nopcommerce-430-is-released/page/4#265652

**Comment by DmitriyKulagin** [comment]
Since we want to stop using the kendo library, this problem should be solved in issue #5016
