### ISSUE TITLE
Paypal Standard plugin. Redirection to Home instead of CheckoutCompleted

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4789]
nopCommerce version: 4.30

>I have a problem of redirection when the payment is completed.
I use a business account on Paypal. I follow all steps correctly and I use sandbox for tests.
When I valid the checkout I'm redirected to Paypal to pay and when I click on the return to website button I'm redirected to the PDTHandler action of my website. It works correctly but the PDTHandler action proceed to a redirection to the Home of my shop instead of redirect me to the "CheckoutCompleted" action.

Source: https://www.nopcommerce.com/en/boards/topic/81973/plugin-paypal-standard-redirection-to-home-instead-of-checkoutcompleted

**Comment by Phoetrix** [comment]
Maybe this could help with the null tx value when I use sandbox with the plugin:
[https://stackoverflow.com/questions/59003163/paypal-not-sending-the-transaction-information-on-return](url)

And in the Paypal docs:
[https://developer.paypal.com/docs/api-basics/notifications/ipn/IPNPDTAnAlternativetoIPN/#when-to-use-pdt](url)

**Comment by RomanovM** [comment]
All is correct here, if the PDT request details is enough to process the order, the customer will be redirected to the order details page, if the order cannot be received by these details, customer will be redirected to the home page.
