### ISSUE TITLE
Versioning of JavaScript and CSS bundles

### ISSUE THREAD

**Issue by edsdck** [nopSolutions/nopCommerce#4791]
_Disclaimer: I may be absolutely wrong about how the issue appeared._
nopCommerce version: 4.20
Steps to reproduce the problem: 
`commonsettings.enablejsbundling` set to `True`

When the bundle is generated the name is formatted from the JavaScript file names and when requested it's cached for a week (see screenshot below). For bundle's name generating see `PageHeadBuilder.GetBundleFileName`.
![Annotation 2020-05-26 120038](https://user-images.githubusercontent.com/43700864/82881594-8f5e3900-9f48-11ea-9bf1-169dc33f4b93.png)

And if there aren't any new JavaScript files added the name will always stay the same which basically means the cached bundle will be used until expired or the page will be hard refreshed.

As this isn't a problem in the Development environment, but is in the Production, shouldn't some more dynamic approach be provided for the latter scenario?

I understand the benefits of caching the bundle, but the problem I've faced is after the release the users with a cached bundle couldn't pass one of the steps in a checkout. To overcome this problem I'm planning to provide a unique identifier for every release to production and when generating a bundle add that identifier to a string to be hashed.

**Comment by Povilas-Jeremicius** [comment]
See my comment on https://github.com/nopSolutions/nopCommerce/issues/3130 for  a step by step guide on how to reproduce this issue.

**Comment by exileDev** [comment]
Closed by #5834
