### ISSUE TITLE
Dynamic url value "products" redirects to page not found

### ISSUE THREAD

**Issue by vadhersmit** [nopSolutions/nopCommerce#4793]
nopCommerce version: 4.30

Steps to reproduce the problem: 
- Create any record with name = **products** for the product, category, or any entity which generates slug.
- It will generate **products** slug properly but when we open the URL it redirects to page not found.

Let's reserve it. See the "seosettings.reservedurlrecordslugs" setting

**Comment by vadhersmit** [comment]
It seems route is confilicting with `BackwardCompatibility1XRouteProvider` for "products/{id}.aspx" route. As it gets registered before generic routes.

**Comment by exileDev** [comment]
Thanks!
Closed #4793

**Comment by skoshelev** [comment]
Need to add fix by migration

**Comment by exileDev** [comment]
Added in commit: https://github.com/nopSolutions/nopCommerce/commit/eac97a1f8902aa8adfe3ba7671e3d6552cfd5cbe
Closed #4793
