### ISSUE TITLE
[Admin Panel]The selected plugin is't displayed after a search by full Name.

### ISSUE THREAD

**Issue by IzabelaJanota** [nopSolutions/nopCommerce#4796]
nopCommerce version: 
4.30

Pre-Conditions:
Login to admin panel as admin

Steps to reproduce the problem: 

1. Go to: _Configuration_ -> _All plugins and themes tab_
2. Search plugin by Name:  “Adyen Redirect Payment Module” 
3. Search plugin by Name:  “WorldPay Redirect Payment Module”

Actual result:
App doesn’t shows result after entering the full name of plugins. For example:
![image](https://user-images.githubusercontent.com/63049254/83110163-ef78ea80-a0c2-11ea-86a2-eb3c64c95ec4.png)

Expected result:
The actions should shows the  plugins searched after entering the full name.

Test Environment:
Browser: Chrome
Version: 81.0.4044.138 (64-bit)
Device: Notebook - Lenovo ThinkPad T480

**Comment by AndreiMaz** [comment]
There is no such plugin - https://www.nopcommerce.com/en/extensions?searchterm=Adyen+Redirect+Payment+Module 

or a wrong name (it's the exact match)

**Comment by IzabelaJanota** [comment]
![image](https://user-images.githubusercontent.com/63049254/83146148-274d5580-a0f6-11ea-93d0-b3c5abca1cd6.png)

**Comment by AndreiMaz** [comment]
@IzabelaJanota Thanks a lot! We'll check and fix it in the near time

P.S. It's related not to nopCommerce itself but to our official website https://www.nopcommerce.com/
