### ISSUE TITLE
Cannot add a gift cart to an existing order in admin area

### ISSUE THREAD

**Issue by IzabelaJanota** [nopSolutions/nopCommerce#4797]
nopCommerce version: 
4.30
Steps to reproduce the problem:
Pre-Conditions:
Login to admin panel as admin

Steps to reproduce the problem: 
1. Go to Sales -> Orders
2. View an existing order with status “Pending” -> Click [View]
3. Add to new product -> Click button [Add product]
4. Select one of Gift Card ($100, 50$ or 25$)
5. Complete the indicated fields.

Actual result:
App doesn’t added product '$100 Physical Gift Card' to order.  There is an error and there is no detailed information on problem.
![image](https://user-images.githubusercontent.com/63049254/83111288-ab86e500-a0c4-11ea-8307-ed138b5428d8.png)
![image](https://user-images.githubusercontent.com/63049254/83111307-afb30280-a0c4-11ea-98c3-3ad56e78bbfc.png)

Expected result:
The actions should added new product.

In addition, from Public Store, Gift Card added correctly. For example:
![image](https://user-images.githubusercontent.com/63049254/83111508-fd2f6f80-a0c4-11ea-8830-727e00931fc5.png)

Test Environment:
Browser: Chrome
Version: 81.0.4044.138 (64-bit)
Device: Notebook - Lenovo ThinkPad T480

**Comment by IzabelaJanota** [comment]
And what do You think?

**Comment by holydk** [comment]
Closed #4797
