### ISSUE TITLE
[Admin Panel] Ability to create discount with a negative value

### ISSUE THREAD

**Issue by IzabelaJanota** [nopSolutions/nopCommerce#4798]
nopCommerce version:
4.30

Pre-Conditions:
Login to admin panel as admin

Steps to reproduce the problem:
1. Go to: _Promotions -> Discounts_
2. Add new discount, in field **Discount amout**  write negative amout for example " -100USD" and complete the rest of the required fields.

Actual result:
![image](https://user-images.githubusercontent.com/63049254/83112541-9743e780-a0c6-11ea-819a-0f7a6ce0537f.png)

In public store you can enter the wrong code and there is no information from the system that the code is a negative value and something is wrong.
![image](https://user-images.githubusercontent.com/63049254/83112641-c35f6880-a0c6-11ea-92cf-9c4568a1d900.png)

Expected result:
No negative value codes can be created.

Test Environment:
Browser: Chrome
Version: 81.0.4044.138 (64-bit)
Device: Notebook - Lenovo ThinkPad T480

**Comment by AndreiMaz** [comment]
Thanks. But It's by design
