### ISSUE TITLE
Support conditions in message templates

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#48]
1. Some message templates contain shipping method. It should be hidden for non-shippable orders (without shipping address)
2. Message templates for anonymous customers (e.g. Service.EmailAFriend)
We need to be able to use expressions such as "<if ()></>" 

also see http://www.nopcommerce.com/boards/t/32276/feature-request-message-template-expressions.aspx and http://www.nopcommerce.com/boards/t/38322/email-templates-for-downloadable-products.aspx

also see https://github.com/nopSolutions/nopCommerce/issues/1801

**Comment by suddenelfilio** [comment]
We changed this using a separate service which is using the mvcmailer. We abuse the messagetokens to update the message templates making them render a json which then gets posted to the other mailer service. The payload gets merged with the json data using MvcMailer and the mail is send. We created a custom Task to replace the original mail task which would differentiate using the internal system or the new one by looking at the emailaccount that should be used for the message template. I have to admit a dirty hack of the current system, but works perfectly.

**Comment by rchamorro** [comment]
There is already a plugin by @BeniGemperle that works with Razor:

https://github.com/BeniGemperle/nopCommerce-RazorMessageService

I think it's a good start

**Comment by m1dst** [comment]
I expected a simple condition like the one below should have worked.  The condition matches True in a repl so I would have expected the same to be the case here.  Did I miss something?

%if (DateTime.Now.DayOfWeek == DayOfWeek.Wednesday) Today is Wednesday endif%

However, the following does work.  Weird.

%if (DateTime.Now.DayOfWeek == "Wednesday") Today is Wednesday endif%

Do you know any other oddities like this?
