### ISSUE TITLE
Visual issues - In some cases incorrect rendering of table columns  

### ISSUE THREAD

**Issue by IzabelaJanota** [nopSolutions/nopCommerce#4801]
nopCommerce version:
4.30
Steps to reproduce the problem:
Pre-Conditions:
Login to admin panel as admin
Reproduction steps:
1.	Go to Configuration -> All plugins and themes tab
2.	Go to Reports -> Low stock
Actual result:
In some cases incorrect rendering of table columns  

First case
![image](https://user-images.githubusercontent.com/63049254/83124268-450ac280-a0d6-11ea-8edb-e0324b9746c0.png)

Second case
![image](https://user-images.githubusercontent.com/63049254/83124292-4f2cc100-a0d6-11ea-93ff-9b7120c259b3.png)

Expected result:
Correct rendering of table columns 

Test Environment:
Browser: Chrome
Version: 81.0.4044.138 (64-bit)
Device: Notebook - Lenovo ThinkPad T480

**Comment by AndreiMaz** [comment]
already reported. thanks
