### ISSUE TITLE
[Public store] Unable to add discount coupon code for a gift Virtual Gift Card

### ISSUE THREAD

**Issue by IzabelaJanota** [nopSolutions/nopCommerce#4803]
nopCommerce version:
4.30

Pre-Conditions:
Login to public store as user
Login to admin panel as admin

Steps to reproduce the problem:
1.  Purchase the gift card.
2. Adding a discount coupon code 

Actual result:
"Sorry, this discount cannot be used with gift card in the cart."
![image](https://user-images.githubusercontent.com/63049254/83125479-df1f3a80-a0d7-11ea-8574-fac5a80d231b.png)

Setting discount coupon code:
![image](https://user-images.githubusercontent.com/63049254/83125464-da5a8680-a0d7-11ea-9b45-b99981f5b71d.png)

Test Environment:
Browser: Chrome
Version: 81.0.4044.138 (64-bit)
Device: Notebook - Lenovo ThinkPad T480

**Comment by AndreiMaz** [comment]
Sorry, this discount cannot be used with gift card in the cart. - it's by design
