### ISSUE TITLE
Enabling HSTS breaks NopCommerce 4.1

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#4804]
I am setting up a stock version 4.1 site with HSTS set in IIS  and "force ssl for all pages" set in the site settings. When I navigate to the site, the css and javascript doesn't load and breaks the all the pages. The same thing happens when I enable ModSecurity, except the pages show a 500 error message before loading the rest of the page's content.  I noticed the links are relative and I wonder if this is related to NopCommerce's bundling?

nopCommerce version: 4.1

Steps to reproduce the problem: 
Deploy a stock NopCommerce 4.1 site
Enable HSTS in IIS or Plesk
Navigate to the page
Enable ModSecurity Firewall (detection only) in plesk

**Comment by AndreiMaz** [comment]
Let's check. If the issue really exists, then let's fix it

**Comment by exileDev** [comment]
We checked this on the 4.30 version and it works fine. Tests were with the clean installation nopCommerce and active `SSL enabled` store setting, also hosted by IIS with enabling `HSTS`.  You may try to reproduce this issue on 4.30, and if the problem still exists, we'll reopen it.
