### ISSUE TITLE
Estimate shipping not showing in IE11

### ISSUE THREAD

**Issue by bjorndep** [nopSolutions/nopCommerce#4808]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. Go to the demo site, using IE11
2. Add product to cart, go to cart
3. Press "Estimate shipping"

In Chrome and Firefox, popup appears (OK).
In IE11 nothing happens. No console errors neither.

https://demo.nopcommerce.com/cart#estimate-shipping-popup

**Comment by RomanovM** [comment]
Please see https://github.com/nopSolutions/nopCommerce/issues/4618
