### ISSUE TITLE
Allow skipping migrations outside of plugin upgrading process

### ISSUE THREAD

**Issue by nguyenhthai** [nopSolutions/nopCommerce#4809]
nopCommerce version: 4.30

The current implementation of the migration manager automatically scans for all the assemblies, including plugin assemblies, and try to run any migration that it could find. This poses a problem if a plugin wants to have a custom migration process using FluentMigrator instead of relying on the default Nop migrator.

For example, during the plugin startup (**INopStartup**), one can build a custom FluentMigrator service with custom runner settings (custom version table for migration tracking instead of using the default one, etc...) and try to apply any migrations from that service instead.

However, because of the automatically scan-in that Nop performs during plugin initialization, those migrations are automatically loaded and Nop would try to apply them again despite they have been successfully applied before.

At the moment, Nop only skips the migrations if it has **[SkipMigrationOnUpdate]** and that is only applied for plugin upgrading process. So a quick solution to this problem would be adding another attribute that would allow the migration to be skipped directly. The skipping should be applied for both up and down migration process.

Furthermore, it would be better if Nop allows specifying custom migration tracking table within the plugin configuration process and only use the default tracking if that version table is not found, or somehow allows plugin to specify custom migrator runner settings instead.

**Comment by skoshelev** [comment]
Closed #4809
