### ISSUE TITLE
Use authorization in ASP.NET CORE 3.1

### ISSUE THREAD

**Issue by KrzysztofPajak** [nopSolutions/nopCommerce#4811]
nopCommerce version: 4.30

Steps to reproduce the problem: 
During the migration to ASP.NET Core 3.1, the option of using Authorization was not properly implemented. 
More info you ca find here:
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#startup-changes
Currently, you cannot implement your own authorization without changing the source code.
Methods UseRouting and UseEndpoints they follow each other without the possibility of injecting the code in between.

**Comment by maxpowernz** [comment]
Hi KrzysztofPajak, how did you get around the problem for now?

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/en/boards/topic/83354/how-to-use-authorize-attribue

**Comment by unfailing** [comment]
[https://www.nopcommerce.com/en/boards/topic/30917/how-to-enable-cors-cross-origin-requests#279501](https://www.nopcommerce.com/en/boards/topic/30917/how-to-enable-cors-cross-origin-requests#279501)

**Comment by DmitriyKulagin** [comment]
Closed #4811
