### ISSUE TITLE
Mixed Content Issue with Promotion Discount Rule Requirement and Checkout

### ISSUE THREAD

**Issue by tc74** [nopSolutions/nopCommerce#4814]
nopCommerce version: 4.3

Steps to reproduce the problem: 
**Configuration to note**
Store URL have been set to **https**://<domain>/
SSL cert have not been checked. (we wanted to check, but checking it will result in endless redirection); by today standard, all website especial ecommerce should be with SSL

Backend
1. Login as Admin
2. Got To Promotions
3. Discount Type: Assign to Product
4. Discount requirement type: Must be assigned to customer role

Resulted in 
Error message - Failed to load content

Using Plugin - Discount requirements: Must be assigned to customer role
Version: 1.34
Author: nopCommerce team
System name: DiscountRequirement.MustBeAssignedToCustomerRole

When reload with browser F12 developer mode, the following line have error

http://<domain>/Admin/DiscountRulesCustomerRoles/Configure?discountId=1&_=1591023672591

It seem to be due to mixed content http/https.

Similar issues was faced during checkout where in onepagecheckout.cshtml when we tried to enter billing address and next, it redirect back to cart.

It seems that to be related to storelocation -> getstorelocation() method issue. Noticed the page / code which breaks on url checkout/opcsavebilling where this storelocation is used on getstorelocation method which checks if currentconnectionsecured

if we use http, we can proceed past billing

**Comment by AndreiMaz** [comment]
1. Store URL have been set to https://
2. SSL cert have not been checked

It should be configured this way. 

As already stated on the forums we cannot reproduce this issue

**Comment by tc74** [comment]
Thanks Andrei. We found out it was a configuration issue related to HAProxy and SSL termination and forwarding to the bad end.

**Comment by russlank** [comment]
Hi tc74, Could you please explain more what was the problem with the reverse proxy? I am asking because I am facing exactly the same issue with my Nginx proxy with nopCommerse....
