### ISSUE TITLE
Addresses are not displayed during checkout when "Country" is disabled

### ISSUE THREAD

**Issue by gmandl** [nopSolutions/nopCommerce#4819]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Create a user
2. Create address at "my addresses" page
3. Ensure that "Country" address field is disabled in admin area
4. Go to checkout. The new address will be missing

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue. Everything works fine

**Comment by gmandl** [comment]
@AndreiMaz Thanks for your quick answer. Let me ask have you tried with or without onepagecheckout? :)

**Comment by AndreiMaz** [comment]
One-page checkout (no third-party plugins). But it doesn't matter. The same method is used in both cases

**Comment by gmandl** [comment]
@AndreiMaz - Thanks for your help and patience. :) We used the previous versions and it worked fine. 

I started to dig in and I found my problem. We have a special client where we turned off the country field for the customer's address. So as we create addresses it won't save country for the customer address .

The problem is here the country is null for the address and the 4.30 has a new filter on CheckoutModelFactory.PrepareBillingAddressModel() - so it filter out all of the addresses.

**Comment by AndreiMaz** [comment]
@gmandl You're absolutely right. Thanks for reporting

**Comment by gmandl** [comment]
@AndreiMaz Thank you. :)

**Comment by holydk** [comment]
Closed #4819
