### ISSUE TITLE
Option for "Administrator enters price" when impersonating

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#482]
Forum source: http://www.nopcommerce.com/boards/t/31894/feature-request-option-for-administrator-enters-price-when-impersonating.aspx

**Comment by AndreiMaz** [comment]
After some consideration we've decided to leave it for customization

**Comment by samhippie** [comment]
We have implemented a version of this for our site. Is there any interest in us making a pull request?
