### ISSUE TITLE
Change the plugin name in the description on the Shipping methods page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4822]
nopCommerce version: 4.30

Steps to reproduce the problem: 
go to https://admin-demo.nopcommerce.com/Admin/Shipping/Methods
The description says "Manual (Fixed or By Weight)" but it should be "Manual (fixed or by weight and by total)"

**Comment by AndreiMaz** [comment]
It's by design. just a little bit shorten
