### ISSUE TITLE
Scrolling doesn't work properly after product editing

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4823]
nopCommerce version: 
4.30

Steps to reproduce the problem: 
1) Edit a Product
2) Edit Specification attributes
3) Save
4) The page will go down to Specification attributes but then jumps back to the top when it's done loading. I've attached a video:

https://ochapparel.com/Edit%20product%20details%20_%20nopCommerce%20administration%20-%20Google%20Chrome%202020-06-04%2009-23-43.mp4

Also let's check all other editing functionality with the scroll support (anchor # in URL)

**Comment by glhays** [comment]
I do not get this behavior using edge browser. What I do get is a new page for editing then once saved returns back to product page with saved values at the Specification section where it started. Version 4.2 used a dialog box popup for add, edit of attributes. Wished it still did to be honest, not so clunky.

**Comment by glhays** [comment]
I do not get this behavior using edge browser. What I do get is a new page for editing then once saved returns back to product page with saved values at the Specification section where it started. Version 4.2 used a dialog box popup for add, edit of attributes. Wished it still did to be honest, not so clunky.

**Comment by mariannk** [comment]
Fixed when working on [this issue](https://github.com/nopSolutions/nopCommerce/issues/4193)
