### ISSUE TITLE
Fix typo on the SendinBlue configuration page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4825]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Go to [https://admin-demo.nopcommerce.com/Admin/SendinBlue/Configure](https://admin-demo.nopcommerce.com/Admin/SendinBlue/Configure)
Buid and target your audience > seems like it should be "Build and target your audience"

**Comment by badijm** [comment]
Hi, I could try this out. I'm looking for my first open-source project to contribute.

**Comment by badijm** [comment]
We can closed this for now, or keep just to track all typo-issue for the future.

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/c191824920a8d67fcf7544414b7602683e9fc8bd
