### ISSUE TITLE
Allow option to define if Action can be AccessibleWhenStoreClosed (not only topics)

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4827]
For instance, CheckAccessClosedStoreAttribute can be refactored to check if the MethodInfo on ControllerActionDescriptor has a [AccessibleWhenStoreClosedAttribute]  defined.

Additionally, password reset page should be accessible when Store is Closed.
Administrators are allowed to access pages when the store is closed but not if they have forgotten their password.

**Comment by AndreiMaz** [comment]
@alinmircea Thanks
1. Its construction already has a boolean "ignore" parameter that allows that
2. moved to a separate work item - https://github.com/nopSolutions/nopCommerce/issues/4828

**Comment by alinmircea** [comment]
Oh I missed that on CheckAccessClosedStoreAttribute.
@AndreiMaz  Thank you for pointing it out.
