### ISSUE TITLE
Problem with using different versions of libraries

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#4834]
There's a problem when different versions of one library are used by other different plugins

![image (2)](https://user-images.githubusercontent.com/16875599/84145806-3a9be180-aa63-11ea-8bfe-26ac930f150b.png)

see details [here](https://www.nopcommerce.com/en/boards/topic/81849/43-couple-of-issues-when-building-source-code-on-azure-devops-build-pipeline). Also see https://github.com/nopSolutions/nopCommerce/issues/4877

Good suggestion is [here](https://www.nopcommerce.com/en/boards/topic/95753/bug-in-nop-460-beta-two-external-different-dll-files#301994) (let's display a warning to do not load one of the plugins with a different version)

**Comment by RomanovM** [comment]
Look at https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by skoshelev** [comment]
Also see [this comment](https://www.nopcommerce.com/en/boards/topic/95753/bug-in-nop-460-beta-two-external-different-dll-files#301994)

**Comment by skoshelev** [comment]
see also [this one](https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support)

**Comment by skoshelev** [comment]
Closed #4834
