### ISSUE TITLE
Why is the method 'ClearCache' of  class CacheEventConsumer  empty?

### ISSUE THREAD

**Issue by Farb** [nopSolutions/nopCommerce#4835]
nopCommerce version: 
4.3
Steps to reproduce the problem: 

I found a problem:when I add a new customer role,then the action is successful.but when I refresh the /Admin/CustomerRole/List,the new added customer role was not shown.
Finally,I found the Insert Event and found the following code.Is it right?

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Caching/CacheEventConsumer.cs

![image](https://user-images.githubusercontent.com/7587900/84172568-bf601d00-aaae-11ea-816a-f5f15004f283.png)

**Comment by skoshelev** [comment]
Hi @Farb. The CacheEventConsumer class is an abstract class, so an empty method is normal for it since derived classes are responsible for the specific implementation of this method

**Comment by Farb** [comment]
@skoshelev  Ok,I got it.Thanks a billion.
