### ISSUE TITLE
Stock management issue for products with non-combinable attributes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4840]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Open our "Custom T-Shirt" sample product. It has a text attribute
2. In admin area the quantity is set to a "9985" and "Track Inventory" dropdownlist value selected
3. Enter your text as 1 and quantity as 9985 (the current max value allowed ) then Add to cart
4. Enter your text as 2 and quantity as 9985 (the current max value allowed ) then Add to cart
5. Now the customer can order more stock than stock quantity

Source: https://www.nopcommerce.com/en/boards/topic/82380/create-negative-stock-quantity-adding-items-to-cart-with-different-attributes

Let's decide how we should better manage stock for products with non-combinable attributes (no way to create combinations)

**Comment by holydk** [comment]
Closed #4840
