### ISSUE TITLE
Shipping option conflicting with pickup address

### ISSUE THREAD

**Issue by vadhersmit** [nopSolutions/nopCommerce#4841]
nopCommerce version: 4.30

Steps to reproduce the problem: 
- Enable ShippingSettings.AllowPickupInStore and disable OrderSettings.DisplayPickupInStoreOnShippingMethodPage
- Add pickup address
- Add item to cart
- Select billing address
- Now select pick up from store option from the shipping address list (user will be redirected to payment options as it should)
- Now go to checkout/shippingmethod, select any method and proceed to confirm the order

It will show the pickup address and selected shipping method with the shipping charge in order total box.
Also, the order can be placed successfully with shipping charge of the selected method and pickup address.

**Comment by holydk** [comment]
Closed #4841
