### ISSUE TITLE
Checkout attribute issue when the condition attribute is checkbox

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4844]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Create a checkout attribute with "checkxboxes" attribute type
2. Create one more checkout attribute.
3. Click "Enable condition"
4.  the values are not displayed as checkbox and it just like textbox.
![image](https://user-images.githubusercontent.com/5019111/84585498-0c2e5580-ae19-11ea-90b1-ef4f20d44203.png)

Source: https://www.nopcommerce.com/en/boards/topic/82132/43-checkout-attribute-when-the-condition-attribute-is-checkbox

**Comment by holydk** [comment]
Dublicate #4858
