### ISSUE TITLE
Plugins list, not load on when language set to other than English

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#4847]
nopCommerce version: 4:30

Steps to reproduce the problem: 
Configure for example French language, and try to go on Plugins page

![image](https://user-images.githubusercontent.com/16875599/84624022-3a7b6600-aee9-11ea-89d9-1d318b878fe8.png)

Details on premium support item 15460

**Comment by DmitriyKulagin** [comment]
Closed #4847
