### ISSUE TITLE
Improve performance with Redis

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4848]
We have to investigate and check how we can increase performance when using Redis. It can work faster

Most probably the good way to fix them will be to first implement https://github.com/nopSolutions/nopCommerce/issues/2287

Also check the slowness reasons after upgrading to async methods

**Comment by lintho** [comment]
Will this be done for 4.4?

**Comment by exileDev** [comment]
@lintho Yes, it is. 👀

**Comment by AndreiMaz** [comment]
done everything possible while working on https://github.com/nopSolutions/nopCommerce/issues/2494
