### ISSUE TITLE
Inheritance not able to be used in plugins given BuildTable implementation

### ISSUE THREAD

**Issue by matthewha** [nopSolutions/nopCommerce#4850]
nopCommerce version: 4.30

Steps to reproduce the problem: 
MigrationManager.cs BuildTable only takes the Type passed to it and does not incorporate any of the parent classes/attributes.
As a result, when using inheritance in a plugin, the BuildTable function does not include any of the columns that should be there due to inheritance from parent class/es. Unless there is a workaround that I'm not aware of, this means that each database table object will need to have lots of replicated code by not using a decent inheritance software architecture within a plugin.
What would be great is if the MigrationManager.cs incorporated a recursive search up the inheritance hierarchy until reaching BaseEntity, similar to that shown in https://docs.microsoft.com/en-us/dotnet/api/system.type.basetype?view=netcore-3.1

PR - https://github.com/nopSolutions/nopCommerce/pull/4857

**Comment by denisburlacu** [comment]
#4857

**Comment by matthewha** [comment]
Thanks Denis for doing this and nopcommerce team for including in next version

**Comment by exileDev** [comment]
After some consideration, we've decided not to implement this functionality.
