### ISSUE TITLE
Category / Product Breadcrumb

### ISSUE THREAD

**Issue by joekrauss** [nopSolutions/nopCommerce#4854]
nopCommerce version: 4.3

We use a category on our website for promotions (weekly deals) something similar to the new products category. This means a product could be associated with multiple categories at different times during its lifecycle. 
![image](https://user-images.githubusercontent.com/41585973/84806404-3de71e00-afcb-11ea-8763-3537c81af73a.png)
The issue here is when I click on the item which category for the item should be presented to the user on the public site? The temporary category such as deals and weekly specials or its more permanent category packs and pouches? I believe the result should be its permanent category. We discovered that Google draws attention to our products while they are present in the temporary category "Deals" making the Google search results show the product exists under "Weekly Deals" breadcrumb.

We have our categories configured with a display order sequence so that the permanent category should be first however, nopCommerce appears to be using alphanumeric order to get the first category for the breadcrumb. Shouldn't the breadcrumb logic be designed to follow the display order value over alphanumeric sorting?
![image](https://user-images.githubusercontent.com/41585973/84807006-307e6380-afcc-11ea-9656-d6de315dfb3a.png)
![image](https://user-images.githubusercontent.com/41585973/84807461-e649b200-afcc-11ea-9a52-aaf069859ea0.png)

We see the same issue on the Admin side where the categories are sorted in some manner we can't explain. What does make sense is having the Admin product display assigned categories in alphanumeric sorted order.

@AndreiMaz 
Thanks for answering the other questions today. Much appreciated!

**Comment by joekrauss** [comment]
The issue is tied to the GetProductCategoriesByProductId Method in CategoryService. The order is based on the product category association and it should be based on the category display order.

Here is what I changed to fix the issue. Hope it helps anyone experiencing the same issue.
var query = from pc in _productCategoryRepository.Table
                        join c in _categoryRepository.Table on pc.CategoryId equals c.Id
                        where pc.ProductId == productId &&
                              !c.Deleted &&
                              (showHidden || c.Published)
                        **orderby c.DisplayOrder, c.Id**
                        select pc;

**Comment by AndreiMaz** [comment]
You can manage the display order on the category details. We sort them using "Display order" property of the mapping table (not of the category table)
