### ISSUE TITLE
Cannot edit a checkout attribute when there's some other attribute with "checkboxes" type

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4858]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1) Create new checkout attribute with 'checkboxes' control type and add some attribute values
2) Go to the sample 'Gift wrapping' checkout attribute
3) Click 'save' button

The following error is displayed - ![error](https://user-images.githubusercontent.com/5019111/84861907-cf619900-b07a-11ea-887f-c881f8d5967d.png)

See PR https://github.com/nopSolutions/nopCommerce/pull/4896

**Comment by denisburlacu** [comment]
#4896

**Comment by holydk** [comment]
Closed #4858
