### ISSUE TITLE
Date format issue with non English culture when saving product

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#4859]
nopCommerce version: **4.3**

Steps to reproduce the problem: 

1. Add language 'Norwegian' with culture 'nb-No'
2. Edit product
3. Set availability date
4. Save product

![image](https://user-images.githubusercontent.com/14998556/84884881-e373bd80-b0af-11ea-9156-9f383b5fcf94.png)

**Comment by kiranbhadani** [comment]
@AndreiMaz, @DmitriyKulagin Any update on this? is there any fix or workaround available?

**Comment by DmitriyKulagin** [comment]
@kiranbhadani You need to download a localization template for Norwegian culture
![image](https://user-images.githubusercontent.com/27218280/85289374-059a8080-b4a0-11ea-9a01-1f22d36a920a.png)

**Comment by kiranbhadani** [comment]
@DmitriyKulagin I did try above, but didn't help, same errors. Problem is not client side validation, it's failing on server side

**Comment by kiranbhadani** [comment]
Ah! actually it's client side issue, problem is with kendo UI culture script ('nb-No') it defines time format as 'HH.mm' but dotnet accepts 'HH:mm'

**Comment by DmitriyKulagin** [comment]
@kiranbhadani Indeed, in kendo scripts, the time format is specified in HH.mm. The format that dotnet uses is the same as cldr (HH: mm). Unfortunately this does not depend on our code. But you can copy yourself this fixed script with which it will work.
Into `wwwroot\lib\kendo\2020.1.406\js\cultures` [kendo.culture.nb-NO.min.zip](https://github.com/nopSolutions/nopCommerce/files/4864898/kendo.culture.nb-NO.min.zip)
