### ISSUE TITLE
pagination tagging to prevent duplication

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#486]
google is finding duplicate titles and tags on pages that are multiple pages in length. 

the solution to this should be to use the pagination markup with the canonical tag- more info here https://support.google.com/webmasters/answer/1663744?hl=en 

example of how to implement: 

```
<link rel="canonical" href="http://www.example.com/article?story=abc&page=2"/> 
<link rel="prev" href="http://www.example.com/article?story=abc&page=1&sessionid=123" /> 
<link rel="next" href="http://www.example.com/article?story=abc&page=3&sessionid=123" />
```

**Comment by AndreiMaz** [comment]
duplciated https://github.com/nopSolutions/nopCommerce/issues/84
