### ISSUE TITLE
Products from subcategories are not loaded

### ISSUE THREAD

**Issue by AE10EFCB** [nopSolutions/nopCommerce#4862]
nopCommerce version:  4.3

Steps to reproduce the problem: 
Products are not listed, if there are 2 depth categories in the main category.

**Comment by AndreiMaz** [comment]
@AE10EFCB Everything works fine. Please provide a detailed list  of steps to reproduce the issue

**Comment by AE10EFCB** [comment]
I have this problem in 4.3 but it has been upgraded from version 4.2.
category structure
Root
|-----ABC
|-----|----DEF
|----------|----GHE

1. Add the product to the GHE Category
2. Select ABC category

There is no product listed.

**Comment by AndreiMaz** [comment]
Please go to catalog setting  and enable "Include products from subcategories"

**Comment by AE10EFCB** [comment]
"Include products from subcategorie" is already active.

**Comment by holydk** [comment]
Closed #4862
