### ISSUE TITLE
Overriding nopcommerce controllers routes

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#4863]
nopCommerce version:  4

We have a fairly comprehensive plugin that overrides a lot of nopcommerce functionality. To ensure we don't modify any original source code we override and reinject a lot of major classes and routes.

Doing this is fairly difficult. For example we need to override the main TopicController, TopicModelFactory, WebWorkContext

Overriding the factories and contexts etc isn't too difficult as we simply extend the base classes and re-register our new classes (that only override the functionality we need). The issue is with controllers, you can't simply override them without also including all the views and other material in the plugin, otherwise once you replace the controller with the same name, it cannot find all the views.

As we don't want to include all the views we also have to replace the routes. This is where it gets hacky. Eg the following code below to replace the TopicController with our own (that overrides a single function).

```
RouteProvider.cs

//Find the topic route
for (var index = 0; index < routeBuilder.Routes.Count; index++)
{
	var item = routeBuilder.Routes[index];
	var route = item as Route;
	if (route == null) continue;

	if (route.Name.Equals("Topic"))
	{
		topic = route;
		break;
	}
}

routeBuilder.Routes.Remove(topic);

//Register the new route replacing the one above
routeBuilder.MapLocalizedRoute(
	name: "Topic",
	template: "{SeName}",
	defaults: new { controller = "OverrideTopic", action = "TopicDetails" });
		
DependencyRegistrar.cs
builder.RegisterType<OverrideTopicModelFactory>().As<ITopicModelFactory>().InstancePerLifetimeScope();
```

Is there any easier way to do this?`

**Comment by AndreiMaz** [comment]
@rolandh You can also try to customize the logic using filters (e.g. add new data to models, etc). It's not actually the override but perhaps you can uses it (depends on your tasks)

In the meantime I'm closing this topic because it's better to open some discussion topics on our forums. GitHub is only for work items. Thanks for understanding

**Comment by mk148a** [comment]
do you know solutions for nopcommerce 4.70? Maybe i can open topic for that
