### ISSUE TITLE
Apply AutoValidateAntiforgeryToken filter globally

### ISSUE THREAD

**Issue by exileDev** [nopSolutions/nopCommerce#4864]
nopCommerce version: 4.30

Steps to reproduce the problem: 

We always apply `AutoValidateAntiforgeryToken` to individual action methods for defending against CSRF attacks. It's more likely in this scenario for a POST action method to be left unprotected by mistake.

Let's specify a filter at a higher level:

```
/// <summary>
/// Add and configure MVC for the application
/// </summary>
/// <param name="services">Collection of service descriptors</param>
/// <returns>A builder for configuring MVC services</returns>
public static IMvcBuilder AddNopMvc(this IServiceCollection services)
{
	//add basic MVC feature
	var mvcBuilder = services.AddControllersWithViews(options =>
		options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute()));
	
	...
}
```

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
