### ISSUE TITLE
GetVendorByProductId does not use the parameter productId

### ISSUE THREAD

**Issue by vadhersmit** [nopSolutions/nopCommerce#4865]
nopCommerce version: 4.30

Parameter productId of the method `GetVendorByProductId(int productId)` is never used inside method.
https://github.com/nopSolutions/nopCommerce/blob/725200f95d5cf85f867f887c531edb4d0d481073/src/Libraries/Nop.Services/Vendors/VendorService.cs#L63

Also above method is used while preparing the shopping cart item model to have vendor name in the cart items list. And `GetVendorById(int vendorId)` can be used here, as we already have `VendorId `in the product obj.
https://github.com/nopSolutions/nopCommerce/blob/725200f95d5cf85f867f887c531edb4d0d481073/src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs#L383

**Comment by AndreiMaz** [comment]
Thanks. Fixed at https://github.com/nopSolutions/nopCommerce/issues/4867
