### ISSUE TITLE
Don't show "The coupon code was applied" text when a coupon code is not applied

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4868]
nopCommerce version: 4.30

Steps to reproduce the problem: using sample data
1. Add any product which don't have any discounts (for example HTC One M8 Android L 5.0 Lollipop) to cart
2. Go to shopping cart
3. Enter the **123** coupon code
4. See the "The coupon code was applied" but actually it wasn't

**Comment by AndreiMaz** [comment]
It's been applied (
