### ISSUE TITLE
TimyMCE should not generate empty paragraphs 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4872]
nopCommerce version: 4.30

Steps to reproduce the problem: 
The TimyMCE editor generates empty <p> tags. They are not valid and remove when the "HTML minification" setting is enabled. Please see https://www.nopcommerce.com/en/boards/topic/82470/nop-42-html-minify-issue

So we should ensure that the editor adds  `&nbsp;` if they are empty. For example, see a related discussion - https://community.tiny.cloud/communityQuestion?id=90661000000IfOcAAK

**Comment by exileDev** [comment]
Closed #4872
