### ISSUE TITLE
Fix sidebar in Admin area

### ISSUE THREAD

**Issue by FabioV79** [nopSolutions/nopCommerce#4874]
**nopCommerce version: from 4.00 to latest**

I've found a solution to fix the sidebar in Admin area:
on file _\Areas\Admin\Views\Shared\_Admin\Layout.cshtml_ I've added a library _**jquery.slimscroll**_ with this line (before bootstrap library): 
`Html.AppendScriptParts("https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js");`

Then in the tag body, I've added a class _fixed_.
In this way, the vertical scroll of the sidebar and the body of the page are independent.

That's all.
If good, can you add it in the next release?

**Comment by AndreiMaz** [comment]
Thanks. But we don't plan to implement it
