### ISSUE TITLE
Bugfix for plugin loading

### ISSUE THREAD

**Issue by sidatacom** [nopSolutions/nopCommerce#4877]
If a plugin have different nuget package references you got an error that the asselbly is not found.

The problem is explaint here:

https://devnet.kentico.com/articles/referencing-multiple-versions-of-the-same-assembly-in-a-single-application

A good plugin wrapper i found here:

https://natemcmaster.com/blog/2018/07/25/netcore-plugins/

I fixed the problems first but the acutall implementation is horrible.
So please refactor and implement also a isolation feature.
Actually all mvc controllers from all plugins will be loaded without control.

I fixed the problem already and send you a pull request againe for testing #4876

**Comment by sidatacom** [comment]
Realy no response ?

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/4834
