### ISSUE TITLE
Add note to the "Limited to customer roles" field from the "Edit plugin details" page as it's done for the "Limited to stores" field

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4878]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Go to https://admin-demo.nopcommerce.com/Admin/Plugin/EditPopup?systemName=Payments.CheckMoneyOrder&btnId=btnRefreshList&formId=plugins-form-local page
2. See that there is no any note beside the "Limited to customer roles" field saying that in order to use this functionality, you have to disable the following setting: **Catalog settings → Ignore "limit per store" rules (sitewide)**.

**Comment by skoshelev** [comment]
Closed #4878
