### ISSUE TITLE
Add support for minor versions of nopCommerce

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4879]
Sometimes we release minor versions of nopCommerce with some bug fixes. For example, right after release of 4.30 we updated our packages several times. But the version number stayed the same - 4.30. That's wrong because users don't understand that some changes have been done. At the same time right now we cannot update the version number because in this case all plugins will be marked as not compatible.

We have to introduce support for minor versions. Let's add one more "MinorVersion" property to https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/NopVersion.cs. It'll be incremental - e.g. "0", "1", "2", etc.

We'll use it only to render the version number in the footer of admin area right after the major version (http://dl4.joxi.net/drive/2020/06/23/0039/0260/2580740/40/a1cafe5cd4.png) and at the system information page (https://admin-demo.nopcommerce.com/Admin/Common/SystemInfo)

It won't be used in any other places to keep the things simple. For example, at the plugin list at https://admin-demo.nopcommerce.com/Admin/Plugin/OfficialFeed, validation of plugin compatibility, etc.

See PR https://github.com/nopSolutions/nopCommerce/pull/4895

**Comment by denisburlacu** [comment]
#4895

**Comment by skoshelev** [comment]
Hi @denisburlacu! Thank you for your contribution

Closed #4879

**Comment by lintho** [comment]
Fantastic!

**Comment by pranaykothari** [comment]
Much needed, thanks!
