### ISSUE TITLE
Allow developers to add new tabs to admin area details pages without tabstrip

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#488]
Currently we can add new tabs to some admin area details pages (e.g. Category details page) from plugins because they have tabstrip. More info at http://www.nopcommerce.com/boards/t/43569/how-can-my-plugin-add-a-tab-into-product-or-category-admin-view.aspx#172964

But we cannot add new tabs for pages without tabstrip (one single column). Just because we cannot have a tabstrip with just one tab. 

Need to find a way to allow developers to add new tabs to admin area details pages without tabstrip. Is it possible? The only I see now is to generate a tabstrip with only one tab (and hide its title). If some new tab is added (from a plugin), then display all tabs

**Comment by RomanovM** [comment]
Closed, cuz we have no tabs in admin area anymore.
