### ISSUE TITLE
Product Cost support multi currency 

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4882]
nopCommerce version: All

Steps to reproduce the problem: Because Product Cost used only for  information , and don't used in calculation formulas, we can write product cost Digits and select Currency.

P.S.
Product Cost is a static value(Digit and Currency)
But now its connected with currency rate, and its wrong.
Example. You buy Apple by 2 Euro and sale by 5 USD
2 Euro=2.5 USD 
but in store you sale by USD, and your Product Cost write in USD, and USD ~~Euro exchange rate is Dynamic, BUT PRODUCT COST is Static ))

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/1
