### ISSUE TITLE
Cannot initialise new mysql database: An exception was thrown while activating Nop.Data.Migrations.MigrationManager -> λ:FluentMigrator.Runner.IVersionLoader

### ISSUE THREAD

**Issue by sami016** [nopSolutions/nopCommerce#4888]
nopCommerce version: 

4.30

Steps to reproduce the problem: 

 - Go to install page for fresh install
 - Enter in a valid connection string to an empty database
 - Click install

The following error prevents the installation from succeeding:

Setup failed: An exception was thrown while activating Nop.Data.Migrations.MigrationManager -> λ:FluentMigrator.Runner.IVersionLoader.

MySqlException: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

**Comment by AndreiMaz** [comment]
@sami016 We cannot reproduce the issue. The installation works fine.

Please provide more information on how we can reproduce the issue

**Comment by exileDev** [comment]
Error description speaks for itself. When the system variable 'sql_require_primary_key' is set to `ON` MySQL requires tables to contain a primary key, but nopCommerce has some tables without PK. Please set the system variable '[sql_require_primary_key](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key)' to `OFF` and try to install again

**Comment by StephenGilboy** [comment]
@exileDev can I ask why some tables don't have a PK? I'm trying to use DigitalOcean's managed MySQL but without all tables having a PK the ability to run read-only databases and automated backup/recovery is unavailable.

**Comment by tcorps** [comment]
hello I have exactly the same problem as described below despite having set the primary sql key off the problem is always done I have configured my sql table like this
sudo mysql_secure_installation
sudo mysql
mysql> CREATE USER 'sammy' @ 'localhost' IDENTIFIED BY 'password';
mysql> GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *. * TO 'sammy' @ 'localhost' WITH GRANT OPTION;
mysql> FLUSH PRIVILEGES;
mysql> exit

mysqladmin Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
Copyright (c) 2000, 2021, Oracle and / or its affiliates.

Oracle is a registered trademark of Oracle Corporation and / or its
affiliates. Other names may be trademarks of their respective
owners.

Server version 8.0.25-0ubuntu0.20.04.1
Protocol version 10
Localhost connection via UNIX socket
UNIX socket /var/run/mysqld/mysqld.sock
Uptime: 1 day 7 hours 51 min 47 sec

Threads: 2 Questions: 146 Slow queries: 0 Opens: 234 Flush tables: 3 Open tables: 153 Queries per second avg: 0.001

**Comment by PeterZhukov** [comment]
2021-09-02 21:04:32.130 MSK [8576] ERROR:  type "citext" does not exist at character 63
2021-09-02 21:04:32.130 MSK [8576] STATEMENT:  ALTER TABLE "public"."MigrationVersionInfo" ADD "Description" citext NULL

**Comment by exileDev** [comment]
@PeterZhukov `CREATE EXTENSION citext;` then try again. This extension is required because the nopCommerce is case insensitive when working with a database.

**Comment by trofunenko** [comment]
I have the same error during installation process with empty database. 

Server: Ubuntu 18.04.6 LTS
PostgreSQL 10.18 (Ubuntu 10.18-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu. 


Build and deploy follows way : 
Commit: b81e3554
Branch: develop 
dotnet restore ./src/NopCommerce.sln
dotnet build ./src/Nop.Web.csproj -c Release -o /app
dotnet publish ./src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o ./app/published

Database and user have been created : 
postgres=# CREATE USER user WITH ENCRYPTED PASSWORD 'userpass';
postgres=# create database XXX;
postgres=# grant all privileges on database XXX to user;

**Comment by ozgurerdogan** [comment]
I had to install mysql 5.7 and error gone.

**Comment by trofunenko** [comment]
I'm trying investigate root of issue. I've changed web.config, stdoutLogEnable = "true" and restart application but can't find full description of the exception. Looks like the one related with permission [https://github.com/nopSolutions/nopCommerce/issues/5304](https://github.com/nopSolutions/nopCommerce/issues/5304)

**Comment by sandeep18051989** [comment]
Hi,
I am also trying to install fresh nopcommerce 4.4 on a azure hosted MySql instance, but getting the same issue. In first run, app generated tables but while inserting default/required data throwed exception "Transaction" related exception. 
Then I removed the schema and creatred a new database to try again, then it is not going to the installation loading screen, after I click Install button, it starts throwing this exception we are talking about.
It is veri wiered, we have tried MySQL, PostGreSQL database on 2 different hosting servers AWS and Azure, but not getting any luck.

**Comment by schakarian** [comment]
Same here. 
`Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.`
I am getting this issue on 4.50.3 Mysql 8, Ubuntu 22.04.
```
/Logs# cat stdout/readme.txt
This folder is used only for system logging by ASP.NET (could be enabled in web.config file)
```
There is not web.config anywhere here in the non-source version. I think you guys can streamline the installation process better for the linux people.

Nevertheless, I ensured that sql_require_primary_key is off in mysql. And the extension installation command for citext has failed.

**Comment by kevingermain** [comment]
@ryanlee714 I got the same trouble today

**Comment by digitalray** [comment]
@ryanlee714 The issue is with the version of MySQL. You need to change it in code to 8.0.29 and recompile the app. Please see: https://github.com/nopSolutions/nopCommerce/issues/6284

**Comment by ryanlee714** [comment]
@digitalray I had the same issue while I was installing nopCommerce 4.50.2. I knew it must be related to MySQL 8.0.29. But I couldn't fix it. I was waiting for 4.50.3 to be released. Hopefully nop developers could fix the problem. Same issue happened with nopCommerce 4.50.3. I'm not an expert with Visual Studio. I can change the code to 8.0.29, but I can't publish it to server correctly. I need someone who can help me. My email is ryanlee714@gmail.com, please email me, so we can get in touch.
Thank you in advance

**Comment by pranjalSL** [comment]
Getting the same issue 'Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.' on Configuration screen of Nop Commerce after building and running the web app via VS.

**Comment by glhays** [comment]
Have you tried the suggested fix of updating to 8.0.29?


________________________________

**Comment by ryanlee714** [comment]
@glhays I tried solution suggested by @digitalray, this issue didn't pop up again. But installation process crashed and timed out.
They updated Linux installation guide to 4.50.3.  They haven't done enough tests on 4.50.3 with MySQL 8.0.29 on Ubuntu. A lot of people, myself included, can't install it correctly. I'm not happy with nopCommerce team.

**Comment by glhays** [comment]
Understood but issue 4888 is closed. Is there another issue open relating to your issues or are you implying it is the same issue? I offered a suggestion based on the issue of 4888.


________________________________

**Comment by pranjalSL** [comment]
I am also getting the same exception. I tried to debug and found out that error is happening at line no. 226 inside the InstallController.cs class (Nop.web -> Controllers -> InstallController.cs). Also attaching a snapshot for reference
<img width="1086" alt="Screenshot 2022-07-15 at 5 03 01 PM" src="https://user-images.githubusercontent.com/104342240/179215552-df609657-38b0-4111-bf0b-b88dc2c5bdab.png">
.
<img width="1369" alt="Screenshot 2022-07-15 at 5 06 04 PM" src="https://user-images.githubusercontent.com/104342240/179215799-dff51596-78db-4684-b95c-d11f84ea092f.png">

**Comment by zzt0341011** [comment]
这么多相同的问题，官方为啥不给解决办法？

**Comment by neominky** [comment]
The same error occurs in MS SQL Server as well.

Devlop branch, August 7, 2026, version 5.0.  #[Merge branch '4.90-bug-fixes' into develop](https://github.com/nopSolutions/nopCommerce/commit/5e3b7cc319a136bde2129bf471dc741184c561e9)

An error occurs after creating an empty "MigrationVersionInfo" table.
