### ISSUE TITLE
USPS Plugin is not checking response for errors

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#4889]
nopCommerce version: 4.30

Steps to reproduce the problem:  Enter invalid username/password in USPS plugin configuration

See this forum post
[https://www.nopcommerce.com/en/boards/topic/82816/shipping-options-could-not-be-loaded-v430#267153](https://www.nopcommerce.com/en/boards/topic/82816/shipping-options-could-not-be-loaded-v430#267153)

**Comment by DmitriyKulagin** [comment]
See this commit https://github.com/nopSolutions/USPS-plugin-for-nopcommerce/commit/585d024ca9493311cf78ed06c22f29bd58f39c63
