### ISSUE TITLE
New activity types

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#489]
Add missing activity types

CampaignController - insert,edit, delete
CustomerAttributeController- insert,edit, delete
CurrencyController- insert,edit, delete
CountryController - тут страны и штаты
BlogController- insert,edit, delete
StoreController- insert,edit, delete
AffiliateController- insert, edit, delete
AddressAttributeController - insert, edit, delete
ShippingController - Warehouses only
VendorController - insert, edit, delete
ScheduleTaskController - edit
ProductReviewController - edit, delete
NewsController - insert, edit, delete
MessageTemplateController - edit, delete
MeasureController - insert, edit, delete (two entities)
LanguageController - insert, edit, delete (locale editing is not required)
EmailAccountController - insert, edit, delete

PluginController - Install/uninstall/edit

**Comment by skoshelev** [comment]
Closed #489
