### ISSUE TITLE
Add database type mapping for int64/long

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4891]
There is no type mapping in MigrationManager.cs for long type.

A line should be added to _typeMapping :
[typeof(long)] = c => c.AsInt64(),

Source: https://www.nopcommerce.com/en/boards/topic/82849/43-missing-database-type-mapping-for-int64long

See PR https://github.com/nopSolutions/nopCommerce/pull/4894

**Comment by denisburlacu** [comment]
#4894
