### ISSUE TITLE
Performance optimization of some services

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4897]
nopCommerce version: 4.30

Steps to reproduce the problem: 
The performance of our services, such as `GetProductsByIds`, `GetCustomersByIds`, `BulkDeleteEntities`, is currently implemented based on the functions `Contains()` or a similar `In()`. This negatively affects performance when we want to request a really large amount of data.
```
WHERE
	[c_1].[Id] IN (55730, 55729, 55728, 55727, 55726, 55725, 55724, 55723, 55722, 55721, 55720, 55719, 55718,...and so on infinitely many)
```

**Comment by sdanyliv** [comment]
if Ids come from LINQ queries, they should be passed to methods and linq2db will generate appropriate SQL.
If not, I know only one solution for that: create temporary table, BulkCopy into it, then join to that table. linq2db provides such functionality.
It should be fast.
