### ISSUE TITLE
4.30 Nopcommerce restart - server shutdown 

### ISSUE THREAD

**Issue by PODHUPU** [nopSolutions/nopCommerce#4898]
nopCommerce Version: Latest version 4.3

Steps to reproduce the problem: 
On restart server shutdown

**Comment by TheFirstWhiteDream** [comment]
yes , I also has this problem;

**Comment by AndreiMaz** [comment]
Is it a  live server?
1. If yes, then already fixed at https://github.com/nopSolutions/nopCommerce/issues/4765
2. If in VS, then it's by design.

**Comment by jeromeferber** [comment]
> Is it a live server?
> 
> 1. If yes, then already fixed at #4765
> 2. If in VS, then it's by design.


what do you mean it's by design?? pls help me

**Comment by skoshelev** [comment]
Hi @jeromeferber. This is how the launch of the site from the VS works: after the command to restart the server, the server simply stops and does not restart itself, but waits for a command from the developer. On the live server, the site restarts without problems.

**Comment by raminfosystems** [comment]
>This is how the launch of the site from the VS works: after the command to restart the server, the server simply stops and does not restart itself, but waits for a command from the developer.

Hi Skoshelev, I think restart application is a vital part of configuring plugin and to test that on the visual studio we need to have the complete cycle of restart application thus it assures that plugin installs successfully. Now I am not sure how to tackle the issue with VS but there should be simple configuration about the behaviour and we should able to configure correctly. 

Any thoughts?

RL
