### ISSUE TITLE
"BalanceInventory" doesn't work properly when shipment is created

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#4903]
nopCommerce version: 4.30+

Steps to reproduce the problem: 
1. I have the product that have stock in warehouse1 (Q=10, R=0, P=0) and warehouse2 (Q=25, R=7, P=0)
2. In admin area, go to any placed order with related product(p. 1) without shipments.
3. Add shipment to order from warehouse2 (i created one shipment with quantity 5)
4. warehouse2 have Q=25, R=12(wrong, should be 7), P=5

This problem should be resolved after #4901

**Comment by dborovsky** [comment]
I can check this bug and fix.

**Comment by holydk** [comment]
see [commit](https://github.com/nopSolutions/nopCommerce/commit/a6f315e4def08135890d2358f11f5f74e1a2a611)
