### ISSUE TITLE
Support logging of the external authentication errors

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4904]
nopCommerce version: 4.30

Currently [when processing the External Authentication plugins](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Authentication/AuthenticationMiddleware.cs#L56), it has a try catch block around the operation. The catch block is empty.

I think it would be a great feature to add a flag on the External Authentication configuration screen to enable additional logging or reporting of errors when executing the middleware.

Source: https://www.nopcommerce.com/en/boards/topic/82914/external-authentication-debug-flag-feature

**Comment by skoshelev** [comment]
Closed #4904
