### ISSUE TITLE
Add ViewBag.RefreshPage for view ProductSpecAttributeAddOrEdit

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#4906]
nopCommerce version: 4.3

**Comment by AndreiMaz** [comment]
@ngtrian Why?

**Comment by ngtrian** [comment]
> @ngtrian Why?

I am creating a new ProductSpecAttribute by opening a popup window, after saving it can close the popup window and refresh the ProductSpecAttribute table list.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But if you're talking about customization, then you'll have to add to your custom solution. It's not required in the default solution (there's no a popup window on this page)
