### ISSUE TITLE
.NET Core Denial of Service Vulnerability

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#4907]
Found a security bulletin from Microsoft. I didn't see anyone talk about it on here yet. The link is https://github.com/dotnet/announcements/issues/157. Can we just update the runtime/sdk or does nopCommerce need to be recompiled against the new version?

Thanks 
-Cameron

**Comment by DmitriyKulagin** [comment]
@cklenk After installing the new version of the SDK, you need to recompile the project.
