### ISSUE TITLE
Error NETSDK1004 'C:\MyCodeRepo\nopCommerce\src\Libraries\Nop.Core\obj\project.assets.json' could not found

### ISSUE THREAD

**Issue by talatkuyuk** [nopSolutions/nopCommerce#4909]
nopCommerce version: 4.3.0
dotnet version 3.1.300
Windows 10
Microsoft Visual Studio Community 2019
Version: 16.6.3

Steps to reproduce the problem: 
I have downloaded the nopcommerce with source.  I did not change even any chracter. 
When I build the Nop.Web, I receive this error:

Error NETSDK1004	'C:\MyCodeRepo\nopCommerce\src\Libraries\Nop.Core\obj\project.assets.json' could not found. 

Even I cloned the NopCommerce from github today, the problem continues.
I could not figure out the problem?

**Comment by AndreiMaz** [comment]
Please manually delete all /obj/ directories and rebuild the solution.

**Comment by mouadking** [comment]
realyy !!!
