### ISSUE TITLE
Use unique Id when creating child Datatable

### ISSUE THREAD

**Issue by nguyenhthai** [nopSolutions/nopCommerce#4911]
nopCommerce version: 4.30

Problem:
When a child datatable is created, the Id of that child table has the pattern of "child(Model.PrimaryKeyColumn)" (i.e: if PrimaryKeyColumn value is 12, the id would be child12). Problem can occur when in a view, there are multiple child tables and the PrimaryKeyColumn for each table could be the same.

The table creation code from **Table.cshtml** currently looks like this:
```javascript
function getchild_@(modelName)(d) {
   return '<table id="child' + d.@(curModel.PrimaryKeyColumn) + '" class="table table-bordered table-hover dataTable" width="100%" style="padding-left:2%;"></table>';
}

///
$(document).ready(function () {
....
   row.child(getchild_@(modelName)(row.data())).show();
   var classid = '#child' + row.data().@(curModel.PrimaryKeyColumn);
   $(classid).DataTable({
       @await Html.PartialAsync("_Table.Definition", curModel.ChildTable)
   }).draw;
.....
}
```
The Id need to be something unique, maybe a combination of model name and the primary key column value instead of just that column alone. That way developers can access those tables by query the correct Id pattern.

**Comment by DmitriyKulagin** [comment]
Closed #4911.  See [this commit](https://github.com/nopSolutions/nopCommerce/commit/4de48951e224c1c203568d5f77dca86c016d2707)
