### ISSUE TITLE
LocalizationService.ImportResourcesFromXml creates duplicate LocaleStringResource

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#4916]
nopCommerce version: 
4.3

Steps to reproduce the problem: 
After upgrading to 4.3 in my test environment I realized that the application creates some duplicate entry in LocaleStringResource. After debugging I found that inside ImportResourcesFromXml the comparison is done with case sensitivity and hence it was adding duplicate entry. 

When adding a LocalStringResouce from the admin interface it add the resource name as all lowercase. When running the application it will compare the camel case ResourceName with all lowercase ResouceName and creates duplicate entry. 

            var lsNamesList = _lsrRepository.Table
                .Where(lsr => lsr.LanguageId == language.Id)
                .ToDictionary(lsr => lsr.ResourceName, lsr => lsr, **StringComparer.InvariantCultureIgnoreCase**);

            var lrsToUpdateList = new List<LocaleStringResource>();
            var lrsToInsertList = new Dictionary<string, LocaleStringResource>(**StringComparer.InvariantCultureIgnoreCase**);

**Comment by skoshelev** [comment]
Closed #4916
