### ISSUE TITLE
Cannot set initial Order ID using MySQL

### ISSUE THREAD

**Issue by connde** [nopSolutions/nopCommerce#4917]
nopCommerce version: 4.30

Steps to reproduce the problem: Set Order ID field with number higher than 1 and save.

Hi, I'm using MySQL 8.0 and I'm doing basic setup of the store, I wanted my order ID identifier to start with a higher number instead of 1 as proposed. After saving I got an error

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Order' AUTO_INCREMENT = 2201' at line 1

![image](https://user-images.githubusercontent.com/1514559/86867071-8e243e00-c0a8-11ea-9361-2d16b65eafa2.png)

**Comment by AndreiMaz** [comment]
Thanks. But already reported - https://github.com/nopSolutions/nopCommerce/issues/4866
