### ISSUE TITLE
Display more user-friendly error when uploading non-picture file as a picture

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4919]
Steps to reproduce the problem: 
1. Upload any non-picture file (e.g. XML or .cs) as a picture. For example, on a product details page 
2. It gives a correct message that uploading failed. But also, 'Object reference not set to an instance of an object.' throwing error on picture controller side.

Let's handle the exception so it's not thrown. There should be just an error text without an unhandled exception 
![download](https://user-images.githubusercontent.com/5019111/86886520-c440dc80-c0ff-11ea-9869-c83c6e70e069.png)

Source: https://www.nopcommerce.com/en/boards/topic/84221/picture-controller-in-get-error-object-reference-not-set-to-an-instance-of-an-object

**Comment by badijm** [comment]
Hi, I can grab this item if available.

**Comment by badijm** [comment]
@AndreiMaz  Hi, I've send the PR. Lemme know if it works for ya.

**Comment by AndreiMaz** [comment]
@badijm Please create the PR at https://github.com/nopSolutions/nopCommerce/pulls and share the link here

**Comment by badijm** [comment]
> @badijm Please create the PR at https://github.com/nopSolutions/nopCommerce/pulls and share the link here

https://github.com/nopSolutions/nopCommerce/pull/4963

**Comment by badijm** [comment]
@AndreiMaz  https://github.com/nopSolutions/nopCommerce/pull/4963

**Comment by holydk** [comment]
Closed #4919
