### ISSUE TITLE
Multiple tax rates per product. Associated product attributes and bundles (tax rate of a parent product only is used)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#492]
when we associate a product as a product attribute, the tax is calculated on the base product, eg:
1. a book has 5% vat
2. a cd has 19% vat

If I choose to buy the book with the cd, the total price is incorrect! Taxes are calculated with a vat of 5%!!! The same can be told about bundles. Currently only tax rate of the parent product is used. child or attribute associated products are ignored 

Maybe, we should make it configurable (whether to use only a parent product tax rate or consider child products also) 

Forum source: http://www.nopcommerce.com/boards/t/27452/bug-in-tax-calculation-with-associated-products-attributes.aspx and http://www.nopcommerce.com/boards/t/27452/bug-in-tax-calculation-with-associated-products-attributes.aspx#176962

---

Imagine the following scenario:
1. We have one main product. Its price is $100. Tax rate is 5%
2. It has two different attributes ("attribute1" and "attribute2"). In order to keep it simple let's imagine that each attribute has only one value ("attribute1" has "value1" and "attribute2" has "value2"). And each value is associated to some other product
3. "attribute1" has "value1" which is associated to a product with price $50 and tax rate 10%
4. "attribute2" has "value2" which is associated to a product with price $30 and tax rate 15%

Right now each product can have only one tax rate. How should we display it to a customer?

---

I see now only one solution is to create a new service which will include all logic (price calculation, tax services, currency conversation). It'll receive all details as parameters and use. Because right now it could quite to implement it (separate tax calculation for attributes). Furthermore, anyway we have related work item which will require similar refactoring - https://github.com/nopSolutions/nopCommerce/issues/1

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.

**Comment by i7phillip** [comment]
Let's be honest, most of the feature requests I've seen lately have the same response from the developers:

`After some consideration we've decided not to implement this functionality out of the box.`
