### ISSUE TITLE
Increase the width of the "Review text" column on the product reviews page in the admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4920]
Go to https://admin-demo.nopcommerce.com/Admin/ProductReview/List and that the space for the review text is not enough 
![698572f01f](https://user-images.githubusercontent.com/16681184/86888830-83e35d80-c103-11ea-8320-cad0890a7bf0.jpg)

Not sure what we can here because all columns are important. But at least we should remove the "Store" column that is not much useful

**Comment by AndreiMaz** [comment]
@mariannk  Not sure what we can here because all columns are important. But at least we should remove the "Store" column which is not much useful
