### ISSUE TITLE
User that haven't validated email are unable to get a new email and cannot reset password

### ISSUE THREAD

**Issue by DavidML3** [nopSolutions/nopCommerce#4921]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1. Register as a new user
2. Use Case - Activation email is sent then lost or deleted. Never got to user
3. User goes to your site and tries to login. There is no way to get an activation email re-sent at the press of a button
4. User forgot password and tries to reset
5. User gets a message that the account is not found because the validation email was never sent, lost or accidentally deleted.

User leaves your site because what should be a simple reset process, is too complicated and drawn out.
Money is lost

1. Users should be able to get an activation email resent on their own
2. Users should be able to reset their password even without clicking the activation email
3. Users should not have to send the admin an email to reset their password
4. Users should not have to create a new account if they never activated their original account

**Comment by AndreiMaz** [comment]
There's "Re-send activation message" button  on the customer details page in admin area

**Comment by DavidML3** [comment]
Why was this closed? A user should never have to wait on an admin to send a password reset. This should be user controlled always.

I would like to request a very needed feature of having users have the ability to resend a password request to their email much like the 1000s of other ecommerce websites that allow this basic feature

**Comment by iammourya** [comment]
DavidML3,

That's one way to look at it but it may be misused to flood emails to a targeted email address. Moreover, all hosting environments have a limit on how many emails can be sent per day. Giving an option to trigger emails as per the customer's wish may not be wise.

If someone is genuinely willing to have their account activated with a specific email address they could always use contact us form and admins can always trigger it.

**Comment by DavidML3** [comment]
Again that is a bad solution and not good for usability. If you go to any site there is an option to reset your password. There is no option to email an admin to reset the password and for good reason. You never want your customers to jump through hoops to do something simple.

**Comment by iammourya** [comment]
That's a different case.

An email address that has not been activated - for whatever reason, in your example, the email got deleted - doesn't require password resets before even activating it first.

Once it is activated, the user can reset the password at any time as per his convenience. This option is available.

If the account hasn't been activated but wants to reset the password, it won't work anyway as the account is not active. It's better to contact support and get things sorted out - starting from requesting resending the activation email, followed by self-resetting the password.
