### ISSUE TITLE
Multi Store - Wrong store detected

### ISSUE THREAD

**Issue by layinka** [nopSolutions/nopCommerce#4923]
nopCommerce version: 4.20

Steps to reproduce the problem: 

I have a multi store setup in place for a website i migrated from version 3.9 to 4.2, 3 different stores are setup and i have pointed the domains to the ip address.

For one of the stores though, there is an issue. Anytime i go to that domain(only that domain/store, the other two works perfectly), nopcommerce doesn't recognise the store configured for it, it recognises the main store instead. This only happens for that particular store.

i.e
I have store A, domain.com
Store B , domain.com.ng
Store C domain.com.gh

Everytime i go to the domain.com.ng, nopcommerce detects it as store A, and consequently all the "Limit to store" set on store B do not work.
I checked and some of the images on the site(Store B), are even loading from store A, the main/default store or Store c sometimes.

I am using nopcommerce 4.2 running on Linux with nginx set as reverse proxy.

Please help

**Comment by AndreiMaz** [comment]
Could you please it on our forums? Most probably something is not properly configured
