### ISSUE TITLE
Enable / Disable Feature for Store

### ISSUE THREAD

**Issue by pandyadhruv** [nopSolutions/nopCommerce#4926]
nopCommerce version: 4.3

Store should have enable / disable feature.

**Comment by AndreiMaz** [comment]
What exactly feature?

**Comment by pandyadhruv** [comment]
I want to disable store for time being, so that no one can access store related pages like categories, products and all. When I enable it back, the same will be available to public. Whatever records are limited to specific store should not be available to public when the same store is disabled.

**Comment by AndreiMaz** [comment]
You already can override "storeInformationSettings.StoreClosed" setting per store
