### ISSUE TITLE
Public plugin url not redirecting to include language code when SeoFriendlyUrlsForLanguagesEnabled

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4934]
**Setup:**

Define RouteProvider in plugin, to include the language pattern for SeoFriendlyUrls:

```
            var pattern = string.Empty;
            if (DataSettingsManager.DatabaseIsInstalled)
            {
                var localizationSettings = endpointRouteBuilder.ServiceProvider.GetRequiredService<LocalizationSettings>();
                if (localizationSettings.SeoFriendlyUrlsForLanguagesEnabled)
                {
                    var langservice = endpointRouteBuilder.ServiceProvider.GetRequiredService<ILanguageService>();
                    var languages = langservice.GetAllLanguages().ToList();
                    pattern = "{language:lang=" + languages.FirstOrDefault().UniqueSeoCode + "}/";
                }
            }
```

Define a route to use the pattern

```
endpointRouteBuilder.MapControllerRoute("RouteName", $"{pattern}PluginUrl",
                new { controller = "PluginController", action = "Index" });

```

**Expected behavior:**

When navigating to http:// website/PluginUrl , the browser should be redirected to  http:// website/**en**/PluginUrl

**Investigation:**

Removing lines 82-84 from https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Mvc/Filters/CheckLanguageSeoCodeAttribute.cs resolves the issue.

```
//ensure that this route is registered and localizable (LocalizedRoute in RouteProvider)
if (context.RouteData.Values["language"] == null)
        return;
```

**Conclusion:**

I might be missing something, specifically where in the plugin to configure the language as RouteData. On the other hand, is that check really needed ? Based on the comment, it looks like remnant of older versions

**Comment by DmitriyKulagin** [comment]
Closed #4934
