### ISSUE TITLE
Add support for "mastercheckbox" for multiple tables on the same page (admin area)

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#4938]
nopCommerce version: 4.30+

Steps to reproduce the problem: 
1. click on "mastercheckbox" of the first table 
![image](https://user-images.githubusercontent.com/37818094/88155673-0e05e880-cc11-11ea-9236-d9f32dfedbbc.png)
1. click on "mastercheckbox" of the second table 
![image](https://user-images.githubusercontent.com/37818094/88155705-1a8a4100-cc11-11ea-93b3-7e6fc76e9c36.png)

**Comment by DmitriyKulagin** [comment]
Closed #4938
