### ISSUE TITLE
Lost custom order Redeemed RewardPoints History RedeemedRewardPointsEntryId

### ISSUE THREAD

**Issue by chuanrou** [nopSolutions/nopCommerce#4942]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Libraries\Nop.Services\Orders\OrderProcessingService.cs  line:841 add "order.RedeemedRewardPointsEntryId ="

            _rewardPointService.AddRewardPointsHistoryEntry(details.Customer, -details.RedeemedRewardPoints, order.StoreId,
                string.Format(_localizationService.GetResource("RewardPoints.Message.RedeemedForOrder", order.CustomerLanguageId), order.CustomOrderNumber),
                order, details.RedeemedRewardPointsAmount); -->

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L841

```
//generate and set custom order Redeemed RewardPoints History
order.RedeemedRewardPointsEntryId = _rewardPointService.AddRewardPointsHistoryEntry(details.Customer, -details.RedeemedRewardPoints, order.StoreId,
                string.Format(_localizationService.GetResource("RewardPoints.Message.RedeemedForOrder", order.CustomerLanguageId), order.CustomOrderNumber),
                order, details.RedeemedRewardPointsAmount);
            _orderService.UpdateOrder(order);
```

See also: https://www.nopcommerce.com/en/boards/topic/89634/43-redeemed-reward-points-entry-id-not-being-added-to-order-table

**Comment by holydk** [comment]
Closed #4942
