### ISSUE TITLE
Estimate Shipping - reduce requests to 3rd-party shipping providers

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#4944]
see details: https://www.nopcommerce.com/en/boards/topic/82736/estimate-shipping-on-cart-page-for-430-every-keypress-in-zippostal-field-gets-rates

Way to solve the problem:
1. Init [requestDelay](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/wwwroot/js/public.estimateshipping.popup.js#L5) parameter from `ShippingSettings.RequestDelay`. Defaults 300.

**Comment by holydk** [comment]
Closed #4944

**Comment by noptools** [comment]
I see that this issue was implemented for 4.40, but it does not seem to be working.  (I think 300 ms  default is too short, but)  Even when I change the setting (shippingsettings.requestdelay) to 2000, I see no delay.
