### ISSUE TITLE
AbandonedMutexException in PictureService

### ISSUE THREAD

**Issue by TrymBeast** [nopSolutions/nopCommerce#4946]
nopCommerce version: 4.2.0

While developing a plugin for Nop that uses the PictureService I discovered in my local environment that the GetPictureUrl in concurrency can throw an AbandonedMutexException because of returning from the method without releasing the mutex.

When using mutexes the release should always be done in a finally block, which is not the case and it actually returns without releasing the mutex, and don't forget that if any exception happens the mutex is not released as well.

The DatabaseRoxyFilemanService usage of a mutex should also use a finally block for this.

**Comment by skoshelev** [comment]
As part of #2287 ticket, we switched to using a semaphore instead of a mutex and fixed a possible problem with locks

Closed #4946
