### ISSUE TITLE
Product reviews. Allow to remove the pre-selected rating value

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4948]
Originally described at https://www.nopcommerce.com/en/boards/topic/85015/google-product-reviews-program-5-default-rating-stars-bad-practice

We already have the "catalogSettings.DefaultProductRatingValue" setting. Let's ensure that it works properly when we set it to 0. Currently the validation doesn't work when set to 0 (on the "write review" page)

**Comment by edsdck** [comment]
Could I implement this one?

**Comment by skoshelev** [comment]
Closed #4948
