### ISSUE TITLE
virtual keyword missing in ReturnRequestService

### ISSUE THREAD

**Issue by stntz** [nopSolutions/nopCommerce#4951]
nopCommerce version: 4.30

Steps to reproduce the problem: The virtual keyword is missing in a Nop.Services.Orders.ReturnRequestService method

```
public IPagedList<ReturnRequest> SearchReturnRequests(int storeId = 0, int customerId = 0,
            int orderItemId = 0, string customNumber = "", ReturnRequestStatus? rs = null, DateTime? createdFromUtc = null,
            DateTime? createdToUtc = null, int pageIndex = 0, int pageSize = int.MaxValue, bool getOnlyTotalCount = false)
{

/// rest of code removed

}
```

**Comment by badijm** [comment]
Hey, I can grab this one too.

**Comment by badijm** [comment]
I can grab this one. So is there a plan to override this method sooner?

**Comment by stntz** [comment]
i have had to change the core code to add virtual as i did an override.
I would send a pull request but don't have the code packed for it.

**Comment by AndreiMaz** [comment]
@badijm Sure, please create a pull request. Thanks a lot

**Comment by badijm** [comment]
@AndreiMaz @stntz I've sent PR with fix, can u take a look?
