### ISSUE TITLE
A cookie associated with a cross-site resource at “URL” was set without the `SameSite` attribute

### ISSUE THREAD

**Issue by aghili371** [nopSolutions/nopCommerce#4953]
nopCommerce version: 4.30

Steps to reproduce the problem: 
I should add one link to my website. but it can not handle the cookies. 
i asked in nopcommerce from but it hasn't answered yet. please if you have a solution informs me to solve it.

the link which i need to add:
`<a target="_blank" href="https://trustseal.enamad.ir/?id=163012&Code=TK0kzMINU8wONMdCf89Z"> <img src = "https: // Trustseal .eNamad.ir / logo.aspx? id = 163012 & amp; Code = TK0kzMINU8wONMdCf89Z "alt =" "style =" cursor: pointer "id =" TK0kzMINU8wONMdCf89Z "> </a>`

the error:

`(index): 1 A cookie associated with a cross-site resource at http://trustseal.enamad.ir/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite = None` and` Secure`. You can review cookies in developer tools under Application> Storage> Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by AndreiMaz** [comment]
Please post all technical questions on our forums (http://nopcommerce.com/boards/). This issue tracker only for work items

**Comment by aghili371** [comment]
@AndreiMaz it is already there. check it, please.
https://www.nopcommerce.com/en/boards/topic/85155/a-cookie-associated-with-a-cross-site-resource-samesitenone
