### ISSUE TITLE
Allow back in stock subscriptions also for ManageStockByAttributes inventory method

### ISSUE THREAD

**Issue by GidanMX2** [nopSolutions/nopCommerce#4955]
nopCommerce version:  4.30

Steps to reproduce the problem: 

If you have a product with inventory method set on "ManageStockByAttributes" there isn't the option to allow back in stock subscriptions. Reading the code I think that this is due to how attribute selection is handled by nopCommerce, now the selection of the attribute is handled client side by js code causing a whole series of problems (es. missing of the ability to link to a specific product/attribute selection, and so the very first price rendered by the server is always that of preselected attribute) while in my opinion it would be better capturing the change event of the select (for attributes with drop down list selection) and then make an ajax call to the same method of ProductController (ProductDetails method) passing an extra argument that specify which attributes are selected, then it could be possible to edit the PrepareProductDetailsModel to support AllowBackInStockSubscriptions even with ManageStockByAttributes inventory type. 
Someone is already working on this thing, is it a change that could be of interest?

**Comment by ipetk0v** [comment]
Many of our customers want this functionality. It makes sense that when we have a clothing store and a certain size is over, I want to subscribe to a specific size, not the whole product. I hope this will be introduced in a new version soon.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
