### ISSUE TITLE
Bestsellers report counts sales incorrectly

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#4956]
nopCommerce version: 4.30

> I started to debug the code, at some point in the past someone added in the Category to the query for the best seller report and [because of that left join](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderReportService.cs#L368) it will count your sales 1 time for each category that product is in.  in my case i had a few of my best sellers in two categories and there for my sales were doubled for them.
I would assume that sales for an order item should be counted only once, no matter how many categories that product is in.
While I just mention this bug for the best sellers report, it might be a good idea to make sure other reports do not have the same issue.

Steps to reproduce the problem: map a product to multiple categories, makes some sales and view the best sellers report.

Source: https://www.nopcommerce.com/en/boards/topic/85001/best-selling-report-counts-sales-incorrectly

**Comment by YetAnotherDev** [comment]
I submitted this bug on the forum, please let me know if you have any issues reproducing it or if i can provide more information on this issue.

**Comment by holydk** [comment]
Closed #4956
