### ISSUE TITLE
This SqlTransaction has completed; it is no longer usable.

### ISSUE THREAD

**Issue by mmokhtari** [nopSolutions/nopCommerce#4958]
nopCommerce version:  4.3

Steps to reproduce the problem: 
in facing this error so many times

InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
System.Data.SqlClient.SqlTransaction.ZombieCheck()

DependencyResolutionException: An exception was thrown while activating Nop.Web.Framework.WebWorkContext -> Nop.Services.Directory.CurrencyService -> Nop.Services.Directory.ExchangeRatePluginManager -> Nop.Services.Plugins.PluginService -> Nop.Data.Migrations.MigrationManager -> λ:FluentMigrator.Runner.IVersionLoader.

**Comment by AndreiMaz** [comment]
Please provide a complete list of steps to reproduce the issue?

**Comment by AndreiMaz** [comment]
no reply, closing the issue

**Comment by govi2010** [comment]
@AndreiMaz  This when you uncheck `Create sample data` and install Nopcommerce.
