### ISSUE TITLE
Unsafe Cross-Origin Links

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4961]
nopCommerce version: 4.30+

Steps to reproduce the problem: 

> The social icons/links  here cause a cross-origin link issue:
> Admin/Setting/GeneralCommon
> 
> This shows any pages that link to external websites using the target=”_blank” attribute (to open in a new tab), without using rel=”noopener” (or rel=”noreferrer”) at the same time. Using target=”_blank” alone leaves those pages exposed to both security and performance issues. Ideally rel=”noopener” would be used on any links that contain the target=”_blank” attribute to avoid them. The external links that contain the target=”_blank” attribute by itself can be viewed in the ‘outlinks’ tab and ‘target’ column.
> 
> This seems like a very simple fix.

Source: https://www.nopcommerce.com/en/boards/topic/85247/unsafe-cross-origin-links

**Comment by badijm** [comment]
hi, i can pick this one

**Comment by DmitriyKulagin** [comment]
@badijm Hi, You can take this into development. Lighthouse auditing tool is fine for testing.

**Comment by DmitriyKulagin** [comment]
Closed #4961
