### ISSUE TITLE
Paid amount for order item with discount should calc by order total

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#4962]
nopCommerce version: 4.30+

Steps to reproduce the problem: 

> We have a discount:
> 
> - apply to product variants 
> - applied to a single product 
> - requires coupon code: true 
> - discount value: 10 euro 
> - maximum discounted quantity: 2
> 
> The discount apply on product: 
> - Price: 25 euro 
> - Minimum cart quantity: 2
> 
> How to reproduce: 
> - Customer add to cart 3 quantity of the discounted product. 
> - Go into the cart 
> - Apply the discount inserting the promo code. 
> - Cart refresh and calculate the discount: 25 euro * 4 qty - (10 euro * 2 qty) = 80 euro 
> - Cart show 15 euro per quantity (IMHO wrong, should show the real price and a discount information) 
> - The customer inserts the order and proceed to the payment with Paypal Standard plugin with "Send detailed product information" checked - we have another plugin for Unicredit Payment Gateway and the bug is reproducible as well also in that plugin 
> - Customer pay 
> - Returned information from PayPal evidence that paid amount is lower than the total amount, in the Order Notes we can found this:
> 
> PayPal IPN. Returned order total 74,89 doesn't equal order total 94,8900. Order# 100547.
> 
> In the OrderItem when the order is created, NOP store 15 euro in UnitPriceExclTax instead of 25, saving correctly 20 euro in DiscountAmountExclTax and 80 euro in PriceExclTax, while the OrderTotal is correct.

Source: PS #15576

**Comment by AndreiMaz** [comment]
Just set "PassProductNamesAndTotals" setting to "false" (a default value)
