### ISSUE TITLE
App Crashes when adding Attribute

### ISSUE THREAD

**Issue by t-surendra** [nopSolutions/nopCommerce#4968]
nopCommerce version: 

Steps to reproduce the problem: 
-> Add Product
     -> Add Attribute
      -> Save
![Screenshot (55)](https://user-images.githubusercontent.com/61778653/89380986-3107c080-d718-11ea-9026-bd0c4915e546.png)

**Comment by M-Sampson** [comment]
On develop branch I am unable to recreate this crash adding attributes to a new product.

**Comment by holydk** [comment]
I could not reproduce the issue. Closed #4968
