### ISSUE TITLE
Fix the field alignment on the vendor details page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#4970]
nopCommerce version: 4.30
 
![4e60cc07ba](https://user-images.githubusercontent.com/16681184/89403333-cc9d2f00-d720-11ea-9439-f7ebd3eba8f4.jpg)

**Comment by M-Sampson** [comment]
I just looked into this issue, it is caused by the 'Customers' label having a class of '.control-label' which gives it a padding of 7px. Can be solved by creating a custom css class for the 'No customer account associated to this vendor.' also giving it a padding of 7px.
