### ISSUE TITLE
Sorting is wrong at the shopping carts and wishlists pages (admin area)

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#4971]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1. for example Shoppingcarts with several entries 

> customer 1 => id =1

- cart item1 = CreatedOnUtc = 07/30/2019 09:51:37
- cart item2 = CreatedOnUtc = 07/30/2019 09:55:37

> customer 2 => id =2
- cart item1 = CreatedOnUtc = 01/12/2019 09:51:37
- cart item2 = CreatedOnUtc = 01/12/2019 09:55:37

> customer 3 => id =3
- cart item1 = CreatedOnUtc = 06/30/2020 09:51:37
- cart item2 = CreatedOnUtc = 06/30/2020 09:55:37

> customer 4 => id =4
- cart item1 = CreatedOnUtc = 07/30/2020 09:51:37
- cart item2 = CreatedOnUtc = 07/30/2020 09:55:37

in the version 4.3 will be sorted like

1. customer 1
2. customer 2
3. customer 3
4. customer 4

in the version 4.2 was sorted correct like

1. customer 4
2. customer 3
3. customer 2
4. customer 1

**Comment by mardev-code** [comment]
we currently use the version 4.3 in the PROD envirement and should find that
In release 4.3 the sorting of the shoppingcarts list is not correct.
in the old 4.2 version it is sorted by CreatedOnUtc now by customerId.
which leads to great effort.

**Comment by mardev-code** [comment]
the problem exists in Shopping carts and wishlists

**Comment by DmitriyKulagin** [comment]
Closed #4971
