### ISSUE TITLE
Store encryption key in datasettings

### ISSUE THREAD

**Issue by nicklundin08** [nopSolutions/nopCommerce#4972]
As per this issue (https://github.com/nopSolutions/nopCommerce/issues/451) , any data that is encrypted in the db is not actually reducing the vulnerability vs just having the data stored in cleartext. Moving the encryption key to data settings would allow encrypting sensitive data to be more meaningful from a security standpoint

**Comment by nicklundin08** [comment]
@AndreiMaz whats the reasoning for this being on hold?

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box
