### ISSUE TITLE
Specification Attribute Filter Not Working

### ISSUE THREAD

**Issue by sinaislam** [nopSolutions/nopCommerce#4973]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. Install default nopCommerce for mysql( 8.0.18 - MySQL) or any.
2. Go to the "Shoes" category then select any specification attributes and it will show no Products.

**Comment by exileDev** [comment]
@sinaislam Are you sure that your `ProductLoadAllPaged` procedure has changed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/062abe6e7f72fa3ea11d6e9957670f98e1879249)?

**Comment by exileDev** [comment]
Not reproduced #4973
