### ISSUE TITLE
duplicate product_manufacture_mapping record with service

### ISSUE THREAD

**Issue by ertebatgharineh** [nopSolutions/nopCommerce#4974]
nopCommerce version: 4.3

Steps to reproduce the problem: 
create new product_manfucture_mapping service from service for multiple time and it will save to database as much as you do it
for example for product id 1234 and manufactureid 4321 if try to insert new record which is in service layer of nopcommerce for multiple times, it will create the record multiple time and show manufacture name of product 1234 everywhere

**Comment by AndreiMaz** [comment]
@ertebatgharineh So you can reproduce it programmatically only? Can you reproduce it on the clean default installation with UI?
