### ISSUE TITLE
Add UTM links to the Sendinblue plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4975]
Go to the plugin configuration page (/Admin/SendinBlue/Configure).

It has two links to the official nopCommerce website at the footer (forums and premium support). Let's add the following UTM parameters to both of them

?utm_source=admin-panel&utm_medium=sendinblue&utm_campaign=admin-panel

PR: https://github.com/nopSolutions/nopCommerce/pull/4977

**Comment by badijm** [comment]
Hi, I can add this if available.

**Comment by AndreiMaz** [comment]
@badijm Thanks! Sure, please create a PR

**Comment by badijm** [comment]
@AndreiMaz I've created PR.
