### ISSUE TITLE
Performance optimization for many products tags

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4980]
nopCommerce version: 4.30

When you have a lot of products tags (e.g. 23K records), then the category details page could load up to 5 seconds and the product details page around 3 seconds. If you disable product tags (e.g. do not invoke the "ProductTagCountLoadAll"), then everything works fast

Tested with catalog of around 3K products and 23K product tags

Also see: https://github.com/nopSolutions/nopCommerce/issues/5117 (possible solution), https://github.com/nopSolutions/nopCommerce/issues/4753 (then test with a lot of specification attributes, but I don't think it really matters)

**Comment by exileDev** [comment]
Closed #4980
@okarpov Thanks for your DB. Now, in your case, a performance drop isn't seen.
