### ISSUE TITLE
Allow searching Products by ProductTemplateId

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#4985]
Consider adding ProductTemplateId in ProductSearchModel and use it in ProductModelFactory.PrepareProductListModel and  ProductService.SearchProducts

Creating a CRUD plugin section to handle only a specific "type" of products can't be easily done.
Could use Product Categories, but it doesn't really fit. 
Also, can't use ProductType because that requires changes to the nop commerce source code.

**Comment by AndreiMaz** [comment]
Thanks! But we don't plan to implement it out of the box
