### ISSUE TITLE
Azure Web Apps - 500 - Reqeust Timeout

### ISSUE THREAD

**Issue by victorlpb92** [nopSolutions/nopCommerce#4986]
nopCommerce version:. 4.3

Steps to reproduce the problem: 

Azure Web Apps - Plan P2V2
Azure Sql: Gen5, 4vCores
Cache Azure Redis: C1 Badic

Algumas vezes ao atualizar configurações gerais retornar erro 500 - The request timed out.
O mesmo acontece com tarefas longas como Excel de produtos ou gerar Google Shopping Feed.

Sometimes when updating general settings return error 500 - The request timed out.
The same is true with long tasks like product Excel or generating Google Shopping Feed.

**Comment by victorlpb92** [comment]
![image](https://user-images.githubusercontent.com/56916573/90303736-89f4f880-de7e-11ea-8835-dc04ffe34faf.png)

**Comment by AndreiMaz** [comment]
@victorlpb92 do you experience it only for the "general settings" page? or for other pages as well?

**Comment by victorlpb92** [comment]
@AndreiMaz another pages of settings have the same problem.

**Comment by AndreiMaz** [comment]
We cannot reproduce the issue on the default installation. Most probably, it's related to the server configuration (e.g. SQL server is located far away from application server). Anyway, no specific details are provided
