### ISSUE TITLE
Search order with vendor filter show multiple order with the same order id

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#4989]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. Store with one or more vendors
2. Order with ID = 2144 that contain 6 products from vendor X
3. in Order search UI select vendor X and seach all Order

result: 
it will show 6 orders (= orderItem.count) in the result
![Unbenannt](https://user-images.githubusercontent.com/59456113/90898193-97523b80-e3c6-11ea-824a-55485c64e2a5.PNG)

**Comment by exileDev** [comment]
Closed #4989
