### ISSUE TITLE
HTML minification	- strips closing body & html tags

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#4990]
nopCommerce version: 4.30

Steps to reproduce the problem: Enable HTML minification, results in the closing body & html tags to be stripped.

Regards,
Craig

**Comment by joekrauss** [comment]
According to W3C you can omit certain tags. Most current browsers handle the omitted tags properly.

 

https://www.w3.org/TR/2014/REC-html5-20141028/syntax.html#optional-tags


Joseph Krauss

**Comment by untiedshoes** [comment]
Hi Joseph,

That's very true, but GTmetrix, and pagespeed tools complain about render blocking scripts when the closing body / html tags are missing.

Regards,
Craig

**Comment by joekrauss** [comment]
I’m now on 4.3 of NopCommerce and the render blocking script issues are not an issue. I believe the blocking script issue has been resolved. The only low score I get below a B rating is leveraging the browser caching. Everything else is either a B or A.

 

If I run the test again the fully loaded time drops below 4 to 3 seconds. Hope this helps. 

 




Joseph Krauss

**Comment by untiedshoes** [comment]
Yeah, our 4.30 (just moved the clubs from 4.00 to 4.30) gets A / A, although enabling html minification drops that due to the render-blocking (as enabling this, removes the closing body / html tags). I've looked in the issues, but haven't been able to find a fix?

Development site:
https://gtmetrix.com/reports/www.clubs20.socksandboots.com/KeqIPtqY

We're just putting the final finishing touches together, then we'll run some load tests once complete.

**Comment by DmitriyKulagin** [comment]
See also: [https://github.com/Taritsyn/WebMarkupMin/issues/109](https://github.com/Taritsyn/WebMarkupMin/issues/109)

It looks like we should make this parameter configurable from the admin area.

The quick solution would be like this.
```
services.AddHtmlMinification(options =>
{
    options.MinificationSettings.RemoveOptionalEndTags = false;
});
```
