### ISSUE TITLE
"SSL enabled" doesn't work properly

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#4991]
nopCommerce version: 4.30

It's still allowed to visit a non-secure page even if "SSL enabled" setting is ticked

The bug is introduced in https://github.com/nopSolutions/nopCommerce/commit/fbb534d372968ecb2a7d541971c93632766e1295

We have to simplify the implementation by moving the attribute to https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Controllers/BaseController.cs#L29 and removing it from all other places

**Comment by holydk** [comment]
Closed #4991
