### ISSUE TITLE
Email "OrderPlaced.VendorNotification" will be send several times

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#4993]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. Store with one or more vendors
2. Order that contain for example 6 products from vendor X
3. OrderPlaced.VendorNotification is active
4. After Complete Order the backend send 6 times (= products.count) the same notification to the Vendor x

**Comment by exileDev** [comment]
Closed #4993
