### ISSUE TITLE
Suggestion: DataTables Pop up Add New/Edit

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4994]
nopCommerce version: 
4.30

Steps to reproduce the problem: 
Just a suggestion to make a simple popup add/edit for datatables so you don't have to go to a new page every time. Example on their website:

https://editor.datatables.net/examples/inline-editing/simple.html

**Comment by AndreiMaz** [comment]
Thanks. We already use inline editing where it's possible. For example, https://admin-demo.nopcommerce.com/Admin/Language/Edit/1

**Comment by Ochapparel** [comment]
@AndreiMaz sorry I meant inline "add new" if you click the "New" button on the example, it pops up a little window, instead of loading a whole new page. Just a thought.

**Comment by glhays** [comment]
I second this suggestion to make the functionality more like it was in 4.2. Andrei, in ver4.2 when adding a new attribute to a product from the product page a dialog popped up to do so. Now in version 4.3 you are essentially directed to a page with a postback to the product. The editing of the attributes worked the same, now also in a in-line postback scenario.

This new functionality makes it very time consuming to enter/edit attributes for a product when numerous attributes exist.
The product page is quite time consuming in loading on first load as it is. Yes the product page does load faster when returning from the in-line attribute functionality but still not all that fast.

**Comment by Ochapparel** [comment]
I agree. I don't want to harp on this too much b/c I'm sure A LOT of time was put into making all these changes...but from a community perspective it is really clunky and a slow process...It was to "modernize" the admin pages, but I think this is a step backwards....

Nop team, please consider some sort of add new on the same page or popup or something that doesnt require going to another page to perform....
