### ISSUE TITLE
Unpublished products are visible on front-end category page (possible pagination issue)

### ISSUE THREAD

**Issue by pranaykothari** [nopSolutions/nopCommerce#4995]
nopCommerce version: 4.30

Steps to reproduce the problem: 

1. Create a category of products with more that 10 products. 
2. Set category page size to be 10 products per page (or less).
3. Go to the category page on front-end. We will see unpublished products in the list of products in that category.

Note 1 - The same problem occurs for page sizes other than 10 too. 
Note 2 - temporary fix:  the page size must be less than the number of products for that category, so that all the products appear in the same page (no pagination occurs). In this case, the unpublished products do not show up.

**Comment by holydk** [comment]
@pranaykothari I can't reproduce the problem. Close #4995
