### ISSUE TITLE
Installation Error:  λ:FluentMigrator.Runner.IVersionLoader.

### ISSUE THREAD

**Issue by koenigstein0808** [nopSolutions/nopCommerce#4996]
nopCommerce version: 4.30

Installation on fresh OVH cloud server, database is MS SQL Express.

Tried with already created database and with the installation db creation.
Permissions are all set for IIS APPPOOL\Nop.

I always get the error:
Installation schlug fehl: An exception was thrown while activating Nop.Data.Migrations.MigrationManager -> λ:FluentMigrator.Runner.IVersionLoader.

**Comment by koenigstein0808** [comment]
After trying with MariaDB and MySQL too:

Installation schlug fehl: Identifier name 'FK_CustomerAttributeValue_CustomerAttributeId_CustomerAttribute_Id' is too long

**Comment by exileDev** [comment]
All works fine. Ensure what your created database compatible with the current version nopCommerce or please provide more information on how we can reproduce the issue.

**Comment by exileDev** [comment]
Can't reproduce

Closed #4996
