### ISSUE TITLE
Disable shipping setting in "Shipping settings" Admin section

### ISSUE THREAD

**Issue by ryanbarlow1** [nopSolutions/nopCommerce#4997]
nopCommerce version: 
4.2 / 4.3

Steps to reproduce the problem: 
Some eCommerce sites sell completely digital products and do not use the shipping functionality at all. Currently if you want to disable shipping site-wide you need to go through each individual product and disable shipping for that product. It would be very useful in this case to have a master "Disable shipping" (or "Enable shipping") setting that controls the shipping functionality. There is already the master enable/disable functionality for the settings in the Rewards points, GDPR settings, Vendor settings, Blog settings, News settings, and Forum settings sections. Could this be extended to Shipping as well?

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But it's by design. You can easily disable shipping for all your products by executing an appropriate SQl command over your database (UPDATE [Product] ...)
