### ISSUE TITLE
Simplify entity caching

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5000]
nopCommerce version: 4.30

Need a simplification of new way for caching entities previously introduced in https://github.com/nopSolutions/nopCommerce/issues/239. Let's make it more unified.

**Comment by untiedshoes** [comment]
@RomanovM Quick question - can we make these changes to 4.30? I've implemented 'Removed IQueryableExtensions', without any adverse effects to 4.30.

Regards,
Craig
