### ISSUE TITLE
Simplify CRUD methods in services

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5001]
nopCommerce version: develop

As a continuation of https://github.com/nopSolutions/nopCommerce/issues/4881.
We need to find a way to make the default implementation of CRUD methods in services to simplify the interfaces. For example, the generic `GetById` method instead of `GetBlogPostById`, `GetBlogCommentById`, etc.
Is it possible to use C# 8.0 "default interface methods" for this?

**Comment by AndreiMaz** [comment]
No simple way to implement now
