### ISSUE TITLE
Edit app settings in admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5002]
nopCommerce version: 4.30

**Comment by tekguy** [comment]
I noticed the move to store appsettings.json in the App_Data folder instead of root, just curious what was the reason for doing this?

**Comment by RomanovM** [comment]
@tekguy We decided to keep all external rewritable on runtime files (e.g. plugins.json, datasettings.json, appsettings.json) in one place. Further we are going to [add support](https://github.com/nopSolutions/nopCommerce/issues/5025) for storing such settings not only in files.

**Comment by tekguy** [comment]
@RomanovM thank you
