### ISSUE TITLE
Duplicated order in /Admin/Order/List after filer is applied

### ISSUE THREAD

**Issue by oswit** [nopSolutions/nopCommerce#5003]
nopCommerce version: 4.30

Steps to reproduce the problem: 

When in /Admin/Order/List is applied a filter (Vendor) /OrderList is returning multiple orders with the same number.
Below an example of retuned Json data

72: {IsLoggedInAsVendor: false, Id: 202755, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
73: {IsLoggedInAsVendor: false, Id: 202755, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
74: {IsLoggedInAsVendor: false, Id: 202753, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
75: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
76: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
77: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
78: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
79: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
80: {IsLoggedInAsVendor: false, Id: 202752, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
81: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
82: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
83: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
84: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
85: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
86: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
87: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
88: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
89: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
90: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
91: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}
92: {IsLoggedInAsVendor: false, Id: 202751, OrderGuid: "00000000-0000-0000-0000-000000000000",…}

**Comment by exileDev** [comment]
duplicates - #4989
