### ISSUE TITLE
Docker Compose File Error On Ubuntu Machine

### ISSUE THREAD

**Issue by tanviraminbappy** [nopSolutions/nopCommerce#5005]
nopCommerce version: 4.30

Steps to reproduce the problem: 
run docker-compose up  from root directory of the source code then get

 Step 4/52 : RUN dotnet restore NopCommerce.sln
 ---> Running in 80c41fbe7bd1
  Determining projects to restore...
/usr/share/dotnet/sdk/3.1.401/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/NopCommerce.sln]
/usr/share/dotnet/sdk/3.1.401/NuGet.targets(128,5): error :   Resource temporarily unavailable [/src/NopCommerce.sln]
ERROR: Service 'nopcommerce_web' failed to build: The command '/bin/sh -c dotnet restore NopCommerce.sln' returned a non-zero code: 1

![npo](https://user-images.githubusercontent.com/12523268/91637997-23e7a400-ea2e-11ea-9eac-91d71833bc7e.png)

**Comment by tanviraminbappy** [comment]
For your information, I am using Ubuntu 20.04 LTS for building those images.

**Comment by skoshelev** [comment]
Hi @tanviraminbappy. Judging by the log of your error, there was a problem with the availability of the site with NuGet manager packages. Please make sure that your server has access to the Internet and the api.nuget.org site is not blocked.

Closed #5005
