### ISSUE TITLE
Issue with ShipStation Plugin

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#5006]
nopCommerce version: 4.3
There is a problem with the logic in CreateOrUpadeteShipping in
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Shipping.ShipStation/Services/ShipStationService.cs
The routine CreateOrUpadeteShipping trys to write a shipmentItem before writing the shipment to get and use the Id
See issue and quick fix here
https://www.nopcommerce.com/en/boards/topic/85274/430-how-to-get-shipments-in-order-from-plugin

**Comment by skoshelev** [comment]
Closed #5006

**Comment by glhays** [comment]
Did anyone take notice of the misspelling of the method name "CreateOrUpadeteShipping" should it be  CreateOrUpdateShipping?

**develop branch:**
src/Plugins/Nop.Plugin.Shipping.ShipStation/Services/ShipStationService.cs
Line: 427
/src/Plugins/Nop.Plugin.Shipping.ShipStation/Controllers/ShipStationController.cs
Line: 140
Someone should be able to quickly fix.

**Comment by AndreiMaz** [comment]
@glhays Thanks a lot! We'll fix it soon - https://github.com/nopSolutions/nopCommerce/issues/5036
