### ISSUE TITLE
GetBestCustomersReport wrong parameters in order by

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#5007]
nopCommerce version: 4.30

Steps to reproduce the problem: Please check code for `GetBestCustomersReport` method in `CustomerReportService.cs` file.

The order by clause is not properly written, please check below code 
`query2 = orderBy switch
            {
                OrderByEnum.OrderByQuantity => query2.OrderByDescending(x => x.OrderTotal),
                OrderByEnum.OrderByTotalAmount => query2.OrderByDescending(x => x.OrderCount),
                _ => throw new ArgumentException("Wrong orderBy parameter", nameof(orderBy)),
            };`

Here if we order by quantity then query2 must be ordered by OrderCount in DESC order. Same way for Order Total Amount.

Currently results on views are correct because from view also you passed wrong parameter for eg. `BestCustomersByOrderTotal.cshtml`
in this view please check filters parameter in datatable.

`Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(Model.BestCustomersByOrderTotal.OrderBy), (int)OrderByEnum.OrderByQuantity),
}`

only thing is, condition is not matching with `enum` properties.

**Comment by holydk** [comment]
Closed #5007
