### ISSUE TITLE
Plugin list in admin panel not showing if language is set to french

### ISSUE THREAD

**Issue by PascalThome** [nopSolutions/nopCommerce#5011]
nopCommerce version: 4.30 (sources)

Steps to reproduce the problem: 
1. Add new language french
2. Go to Admin panel -> Configuration -> Plugins locaux 
3. Plugins not showing (empty list)

Probable cause:
Uncaught ReferenceError: renderColumnDescription is not defined
    at render (List:1257)
Uncaught SyntaxError in renderColumnDescription : Unexpected identifier line 1358 : 
`  '<li>Ordre d'affichage: ' + row.DisplayOrder + '</li>' +`
Quote is not escaped in script.

Temporary resolution : 
Remove quote in localestringresource = Admin.Configuration.Plugins.Fields.DisplayOrder

**Comment by DmitriyKulagin** [comment]
Already fixed in [this commit](https://github.com/nopSolutions/nopCommerce/commit/06411aa161757ee9d357eca1d74ed42c925801b1)
