### ISSUE TITLE
Can't Build NopCommerce 4.3 on MacOS

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#5012]
nopCommerce version: 4.3 (all commits including develop branch)

Steps to reproduce the problem: 

 .NET Core SDK 3.1.301 (I've tried 2.2, etc.)
Perform a build using on MacOS Catalina from the command line using dotnet build.

I am unable to build NopCommerce 4.3 on MacOS Catalina.  When I build the application I get the following error:

_The command "dotnet "ClearPluginAssemblies.dll" "OutputPath/Documents/Projects/...." exited with code 126._

Note how the OutputPath variable is inside the double quotes and there's no "=" after it.  When I do I full binary log, msbuild gives a more specific error  that the arguments are too long. It appears the ClearPluginsAssemblies.proj has an issue generating the arguments correctly.

There's also several areas about where msbuild warns:

_It was already imported at "/Users/joe/Documents/Projects/site/src/Tests/Nop.Services.Tests/obj/Nop.Services.Tests.csproj.nuget.g 2.props (19,5)".  This is most likely a build authoring error. This subsequent import will be ignored. This warning may or may not be related to the build issue._

I am unable to perform a build using VS 2019 for Mac. It gets stuck in the "Loading..."  On the PC opening the full solution is extremely slow.

**Comment by Joebeazelman** [comment]
Is there any additional information you might need to investigate this issue?  I suspect this is entirely related to MSBuild. I'm running Microsoft Build Engine version 16.6.0 for Mono.

**Comment by AndreiMaz** [comment]
@Joebeazelman Please sorry for delay. We'll reply as soon as we check it

**Comment by skoshelev** [comment]
Hi @Joebeazelman.

I'm sorry, we have not tested the build functionality under mono and it is very difficult to say what exactly does not work in your environment, especially since you have problems launching through VS 2019. You can try to install the Visual Studio Сode editor and install plugins for working with .net core and c#. You can also try deleting all bin and obj directories. As a temporary solution, you can try to remove the plugin cleanup code, you can do this in the Nop.Web.csproj file, just remove the following code:

```
<!-- This target execute after "Build" target.
We use it to clean up folder with plugins from unnecessary and obsolete libraries. -->
<Target Name="NopTarget" AfterTargets="Build">
<ItemGroup>
  <!-- Get plugin description files to get plugin paths -->
  <PluginsDescription Include="$(MSBuildProjectDirectory)\Plugins\**\plugin.json;" />
  <!-- Get paths for all plugins -->
  <PluginsFolders Include="@(PluginsDescription->'%(relativedir)')" />

  <!-- Get all the libraries from the shadow copy folder to remove them,
	because depending on the settings, this may not happen when the application is starting,
	but this can lead to unpredictable results during debugging of the project. -->
  <ShadowCopiesLibraries Include="$(MSBuildProjectDirectory)\Plugins\bin\*.*" Exclude="$(MSBuildProjectDirectory)\Plugins\bin\placeholder.txt" />

  <!-- Get paths for ClearPluginAssemblies project -->
  <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />

</ItemGroup>
<PropertyGroup>
  <PluginsFolders>@(PluginsFolders)</PluginsFolders>
</PropertyGroup>
<!-- Delete libraries from the shadow copy folder -->
<Delete Files="@(ShadowCopiesLibraries)" />
<!-- When .NET Core builds a project, it copies all referenced libraries to the output folder.
  For plugins it creates too many unnecessary files that just take up space.
  At the moment you can't disable this behavior. That's why we have to manually delete all unnecessary libraries from plugin output directories. -->
<MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(PluginsFolders)" Targets="NopClear" />

</Target>
```

**Comment by Joebeazelman** [comment]
Sorry for the delayed response. The same issue happens under VS Studio Code running dotnet msbuild. I believe the problem may be related to path separators which are different between UNIX and Windows. Do you have a test script I can run to see if it is indeed the issue?


> Hi @Joebeazelman.
> 
> 
> 
> I'm sorry, we have not tested the build functionality under mono and it is very difficult to say what exactly does not work in your environment, especially since you have problems launching through VS 2019. You can try to install the Visual Studio Сode editor and install plugins for working with .net core and c#. You can also try deleting all bin and obj directories. As a temporary solution, you can try to remove the plugin cleanup code, you can do this in the Nop.Web.csproj file, just remove the following code:
> 
> 
> 
> ```
> 
> 
> 
> <Target Name="NopTarget" AfterTargets="Build">
> 
> <ItemGroup>
> 
>   
> 
>   <PluginsDescription Include="$(MSBuildProjectDirectory)\Plugins\**\plugin.json;" />
> 
>   
> 
>   <PluginsFolders Include="@(PluginsDescription->'%(relativedir)')" />
> 
> 
> 
>   
> 
>   <ShadowCopiesLibraries Include="$(MSBuildProjectDirectory)\Plugins\bin\*.*" Exclude="$(MSBuildProjectDirectory)\Plugins\bin\placeholder.txt" />
> 
> 
> 
>   
> 
>   <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
> 
> 
> 
> </ItemGroup>
> 
> <PropertyGroup>
> 
>   <PluginsFolders>@(PluginsFolders)</PluginsFolders>
> 
> </PropertyGroup>
> 
> 
> 
> <Delete Files="@(ShadowCopiesLibraries)" />
> 
> 
> 
> <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(PluginsFolders)" Targets="NopClear" />
> 
> 
> 
> </Target>
> 
> ```

**Comment by skoshelev** [comment]
Can't reproduce

Closed #5012

**Comment by Joebeazelman** [comment]
> Can't reproduce
> 
> Closed #5012

Did you try this on MacOS? What release are you using?

**Comment by itto** [comment]
I had the same issue. When commenting out the msbuild instruction, I could build the solution.
However, as this wasn't a good solution I looked into it further and found out that Dotnet was not available in eg Terminal.

`zsh: command not found: dotnet`

Installing the Dotnet 5 sdk solved the issue.

**Comment by Joebeazelman** [comment]
I have MsBuild and dotnet on my path and can build the entire solution from the CLI.  Are you using VS2019 for the Mac?

**Comment by itto** [comment]
I use Rider from JetBrains.
