### ISSUE TITLE
Agree to terms: Cart Page

### ISSUE THREAD

**Issue by brandon71** [nopSolutions/nopCommerce#5014]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Admin>Settings>Order 

Terms of service (shopping cart page) 
When enabled the agreement appears however it is not required to click before continuing. You can continue to checkout without agreeing.

Terms of service (confirm order page)
Works as expected.

![terms](https://user-images.githubusercontent.com/4977768/92313289-6279e300-ef87-11ea-81b0-c758e3461a51.PNG)

**Comment by AndreiMaz** [comment]
@brandon71 We cannot reproduce the issue. Can you reproduce it on our demo website?  https://demo.nopcommerce.com/

**Comment by exileDev** [comment]
Can't reproduce

Closed #5014
