### ISSUE TITLE
Connect all client libraries via npm or find a replacement for them

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5016]
We have already done (#4240) most of the work on connecting js libraries via npm. Now in the lib folder there are either obsolete libraries (jquery-ui) or those that we decided to abandon and find a replacement for them (kendo). It is necessary to completely abandon the use of libraries through the lib folder.

**Comment by RomanovM** [comment]
Almost done here, the remaining items have been moved to separate tasks #3665 #5295 #5296.
