### ISSUE TITLE
Azure blob storage NuGet package deprecated

### ISSUE THREAD

**Issue by wforney** [nopSolutions/nopCommerce#5018]
nopCommerce version: 4.4/source code from develop

Steps to reproduce the problem: The NuGet package for Azure blob storage is deprecated. There is a new one. I have created an update for this and adding the root files to the solution under a Solution Items folder. I will create a PR for it in a moment.

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce/commit/4c562b00d56a32767ffdf6028761d9998a9da731 commit

Closed #5018
