### ISSUE TITLE
Import Customers (Excel)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#502]
I'm in the process of migrating from an old shopping cart system where I have nearly 1,700 loyal customers and I would like to find an easier way to import them (other than manually adding each one) so the transition to the new website is seamless and transparent to them. I am also applying Rewards Points to their accounts based on how much they have spent on the old site. 

Can a "Customer Import from Excel" option be made allowing us to carry over their basic information, e-mail address, billing & shipping address, Newsletter signup as well as a Rewards Points column that I can calculate on the spreadsheet before importing them to NopCommerce?

also see http://www.nopcommerce.com/boards/t/43312/no-way-to-import-customers-in-37.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
