### ISSUE TITLE
Send a test email (message template) immediately even if "Send immediately" is not enabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5020]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Open any message template in admin area
2. Untick "Send immediately" checkbox and set some "Delay send"
3. Save the template
4. Send a test email by clicking the "Test template" button
5. It'll be properly queued but not sent because the "Delay send" value will be used

We should ignore if when testing message templates

**Comment by holydk** [comment]
Closed #5020
