### ISSUE TITLE
Random 400 Bad Requests, and 'The client has disconnected' errors.

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5029]
nopCommerce version: 4.30

Steps to reproduce the problem: After upgrading from 4.00, to 4.30, we're getting multiple, and completely random 400 Bad Requests, and 'The client has disconnected' errors. We didn't get any such errors with 4.00.

Error 400. Bad request:
Getting these on various pages, and completely random. Contact, login, password recovery, cart.

e.g.
Page URL:	/login?returnurl=%2Fcart
Referrer URL:	/login?returnurl=%2Fcart

The client has disconnected:
Again, completely random! 

`Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
---> System.Runtime.InteropServices.COMException (0x80070040): The specified network name is no longer available. (0x80070040)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebMarkupMin.AspNetCore3.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 125
   at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at FoxNetSoft.Plugin.Misc.CDNConnector.Infrastructure.CDNConnectorMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper)
   at Nop.Services.Common.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

Page Url: /register?returnurl=%2Fcart
Referrer URL:  /register?returnurl=%2Fcart

Both errors are coming from either guest accounts, or users logged in (shows the email address in the log).

The site works perfectly fine, and we're taking orders as normal?

Any ideas anyone?

Regards,
Craig

**Comment by joekrauss** [comment]
Hey buddy, I’m having the exact same issue in my environment. I opened a premium support case concerning the issue. The Nop team suggested the following changes below. It helped but I still see the errors.

Here’s the reality, if you happen to encounter the error yourself you’ll get an endless hourglass during the login process. You can hit refresh and you’re suddenly your logged into the site. For this to be occurring to customers without our knowledge is not acceptable. I’m going to copy your request to my premium case to hopefully get more attention to this issue as it’s not isolated to just me.

P.S. make sure you are compiled under 3.1.8 of net core. There is security concerns around cookies. https://dotnet.microsoft.com/download/dotnet-core/3.1

NopCommerce response:
Most likely your issue is related to the issue https://github.com/nopSolutions/nopCommerce/issues/4991. It looks like you go to the main page of the site bypassing https and then try to log in, and the login page is already working on top of https, try to make changes linked to the ticket, this should help.

Also please check appsettings.json for this setting. 
"UseHttpXForwardedProto": true
If false, change to true.


Thank you,
nopCommerce team


> On Sep 12, 2020, at 9:32 AM, untiedshoes <notifications@github.com> wrote:
> 
> ﻿
> nopCommerce version: 4.30
> 
> Steps to reproduce the problem: After upgrading from 4.00, to 4.30, we're getting multiple, and completely random 400 Bad Requests, and 'The client has disconnected' errors. We didn't get any such errors with 4.00.
> 
> Error 400. Bad request:
> Getting these on various pages, and completely random. Contact, login, password recovery, cart.
> 
> e.g.
> Page URL: /login?returnurl=%2Fcart
> Referrer URL: /login?returnurl=%2Fcart
> 
> The client has disconnected:
> Again, completely random!
> 
> Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected ---> System.Runtime.InteropServices.COMException (0x80070040): The specified network name is no longer available. (0x80070040) --- End of inner exception stack trace --- at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody() at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token) at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory1 memory, CancellationToken cancellationToken)
> at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory1 buffer, CancellationToken cancellationToken) at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken) at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext) at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext) at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at WebMarkupMin.AspNetCore3.WebMarkupMinMiddlewareBase.Invoke(HttpContext context) at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 125 at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at FoxNetSoft.Plugin.Misc.CDNConnector.Infrastructure.CDNConnectorMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Nop.Services.Installation.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) at Nop.Services.Common.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
> 
> Page Url: /register?returnurl=%2Fcart
> Referrer URL: /register?returnurl=%2Fcart
> 
> Both errors are coming from either guest accounts, or users logged in (shows the email address in the log).
> 
> The site works perfectly fine, and we're taking orders as normal?
> 
> Any ideas anyone?
> 
> Regards,
> Craig
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



Defense Solution Group, Inc. / DSG Arms
Office: 817-806-9242
Fax: 817-615-8820
Email: 
6100 Conveyor Drive
Cleburne, TX 76031-0998
CAGE: 1L0J5
GSA: GS-07F-6007R 
https://dsgarms.com
https://www.dsgholsters.com
http://www.dsginc.com
The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by untiedshoes** [comment]
Hey Joe!

Yeah, I had looked at that a few days ago, but we force SSL.. you physically can’t access the site via none https.

The team at the moment are getting very good at not responding to anyone, and they are virtually none existent on the forums.

Did you see my comment on the Async issue (git hub). Our upgraded 4.30 can’t handle 25 clients a second, which is worse than the 4.00 it’s replaced, and way way worse than the 50 that the dev site can handle.,  

Regards,
Craig Richards

mail: craig@untiedshoes.co.uk
web: www.untiedshoes.co.uk

**Comment by joekrauss** [comment]
Our site is setup the same with no access to HTTP communications to protect all parties. Given I don’t clear my cookies I question if this issue impacts new customers or those who clear cookies regularly.

 

I am following your async issue and your test results. With the holidays coming having a fix for 4.3 would be nice before sites that hit high client numbers start failing. ☹


Joseph Krauss

**Comment by untiedshoes** [comment]
You may be onto something!!

I’ve just done the following:

Added a product to the cart
Click proceed, and logged in
On the cart, I cleared my cache, and then clicked proceed / checkout button.

Got the following pop up (on my phone at the moment).

![80830A66-B1A8-41A4-A8DA-53DD2CFD6269](https://user-images.githubusercontent.com/12123259/93003153-3dabdf80-f534-11ea-8cfd-8776410d810d.png)

Tried the same on one of our other sites (3.90), and got redirected to the login page after clicking the checkout button (after clearing the cache).

**Comment by untiedshoes** [comment]
Tested on desktop:

1. Add product to cart
2. Checkout
3. Sign in
4. Back to cart
5. Clear browser cache
6. Click Checkout button

This results in a 400 error - this page isn't working. Refreshing the page doesn't work and just asks if you wish to 'Confirm Form Submission'. The only way to fix this is to go to the top of the browser, and manually return the url.

In 3.90, this doesn't happen, and you get redirected back to the login page.

**Comment by untiedshoes** [comment]
Any movement on this guys? We’re getting a tonne of 400 bad requests per day.

The issue can be replicated on the demo site too.

**Comment by exileDev** [comment]
@untiedshoes By your steps, all work fine on the clean installation, and the demo site too.
PS: AntiforgeryValidationException (400 error in WinLog) can happen on lost the key ring from `~/App_Data/DataProtectionKeys` directory. After logging, an error ASP.Net creates a new valid Data Protection key and generates antiforgery token with continues working in normal mode. A customer doesn't have any problems at this moment. These log errors create only for customers who were logged on store previous to lost a data protection key.

**Comment by jigarsangoi** [comment]
@exileDev @DmitriyKulagin Isn't there possibility to adding setting to avoid this exception from log like we have it for 404.
Because of this logs sometimes developers won't able to check real problems

@untiedshoes it really depends on your server configuration and your customization 

> Did you see my comment on the Async issue (git hub). Our upgraded 4.30 can’t handle 25 clients a second, which is worse than the 4.00 it’s replaced, and way way worse than the 50 that the dev site can handle.,

**Comment by DmitriyKulagin** [comment]
@jigarsangoi I think this is not the best practice if we add settings to the kernel that will hide certain errors. Developers can take care of filtering/clearing the logs through the SQL script themselves.

**Comment by sereoja** [comment]
if you are using [AutoValidateAntiforgeryToken] at controller level add [IgnoreAntiforgeryToken] at Action/Method level:
   ` [AutoValidateAntiforgeryToken]
    public partial class CustomerController : BasePublicController
    {
        [HttpPost]
        **[IgnoreAntiforgeryToken]**
        [Route("login")]
        //available even when a store is closed
        [CheckAccessClosedStore(true)]
        //available even when navigation is not allowed
        [CheckAccessPublicStore(true)]
        public async Task<IActionResult> Login(LoginModel model, string returnUrl)
        {...}
    }`
hope it helps
