### ISSUE TITLE
"Product review possible only after product purchasing" setting doesn't properly properly work for grouped products

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5032]
nopCommerce version: 4.30

I notcied some behavior with regards to product variants (not shown individually) and reviews with the following setting.

Product review possible only after product purchasing

When turnd on, users who have purchased a variant , its not possible to submit a review for the variant for obvious reasons. It is not possible to review the grouped parent either since it cannot be purchased. So with this setting on, it is impossible to review any grouped product or its variants.

Related work item: https://github.com/nopSolutions/nopCommerce/issues/5033

Source: https://www.nopcommerce.com/en/boards/topic/87568/product-reviews-logic

**Comment by holydk** [comment]
Closed #5032
