### ISSUE TITLE
Setup failed: An error occured executing the following sql: 

### ISSUE THREAD

**Issue by Richking4life** [nopSolutions/nopCommerce#5038]
Everytime i try to install nopCommerce using VS2019 i get these sort of error. Been on this for days now and it's fraustrating. Please help.

nopCommerce version: Latest version

Steps to reproduce the problem: 

Setup failed: An error occured executing the following sql: ALTER TABLE [dbo].[Product_SpecificationAttribute_Mapping] ADD CONSTRAINT [FK_Product_SpecificationAttribute_Mapping_SpecificationAttributeGroupId_SpecificationAttributeGroup_Id] FOREIGN KEY ([SpecificationAttributeGroupId]) REFERENCES [dbo].[SpecificationAttributeGroup] ([Id]) ON DELETE CASCADE The error was Foreign key 'FK_Product_SpecificationAttribute_Mapping_SpecificationAttributeGroupId_SpecificationAttributeGroup_Id' references invalid table 'dbo.SpecificationAttributeGroup'. Could not create constraint or index. See previous errors.

**Comment by exileDev** [comment]
Thanks. Fixed in [this commit](https://github.com/nopSolutions/nopCommerce/commit/d88e0bd13a4c16274a0f71553a35a342ec06d470)

Closed #5038
