### ISSUE TITLE
WindowsAzure.Storage NuGet package is deprecated in Nop.Services

### ISSUE THREAD

**Issue by ryanbarlow1** [nopSolutions/nopCommerce#5039]
nopCommerce version: 
4.3

Steps to reproduce the problem: 
When you browse NuGet in Visual Studio, you can see that WindowsAzure.Storage v 9.3.3 that is currently used has been deprecated. Instead there is a recommendation to use the Azure.Storage.Blobs package.

**Comment by DmitriyKulagin** [comment]
Duplicated #5018
