### ISSUE TITLE
Use "tel" and "email" types for inputs

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5041]
Let's use "type= tel" for all telephone inputs. And use "type= email" for all email inputs

Source: https://www.nopcommerce.com/en/boards/topic/87731/feature-more-mobile-friendly-address-form

**Comment by MarkTallentire** [comment]
I went ahead and submitted a PR for this, as far as I can see there were only two fields across the whole app missing these attributes.

**Comment by purehaTime** [comment]
Done with version 4.50
