### ISSUE TITLE
Update the "Help" menu in admin area

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5042]
1. Rename "Help topics" to documentation

2. Add a new menu items to the end - "Solution partners" pointing to the https://www.nopcommerce.com/solution-partners?utm_source=admin-panel&utm_medium=menu&utm_campaign=solution_partners&utm_content=help

3. Update all UTM links as per the latest changes (actually it's required to update on all pages of admin area that have links to the official website). Ivan has more info

**Comment by skoshelev** [comment]
Closed #5042
