### ISSUE TITLE
Filtering by customer roles in tier prices should not depend on the "Ignore ACL" setting

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5047]
Filtering by customer roles in tier prices should not depend on the "Ignore ACL" setting

Source: https://www.nopcommerce.com/en/boards/topic/87812/is-this-bug-

Introduced at https://github.com/nopSolutions/nopCommerce/issues/3515

**Comment by skoshelev** [comment]
Closed #5047
