### ISSUE TITLE
NameCompatibilityManager.AdditionalNameCompatibilities 

### ISSUE THREAD

**Issue by albNik** [nopSolutions/nopCommerce#5054]
Not sure how it's used but it returns always an empty list
` public static List<Type> AdditionalNameCompatibilities => new List<Type>();`

There is a reference in Initialize method Nop.Data.Mapping.NameCompatibilityManager  
`compatibilities.AddRange(AdditionalNameCompatibilities.Select(type => EngineContext.Current.ResolveUnregistered(type) as INameCompatibility));`
and another in InitializePlugins method of Nop.Web.Framework.Infrastructure.Extensions
 `NameCompatibilityManager.AdditionalNameCompatibilities.AddRange(nameCompatibilityList);`

**Comment by skoshelev** [comment]
Closed #5054
