### ISSUE TITLE
Edit Products-Admin Spec Attributes Add/Remove Reverts Previously changed settings if not saved prior to

### ISSUE THREAD

**Issue by glhays** [nopSolutions/nopCommerce#5055]
nopCommerce version: 4.3

Steps to reproduce the problem:
1. Edit product
2. Expand Price section and Edit Price
3. Collapse Price
4. Expand Specification Attribute
5. Add/Edit attribute, leaves the page, save returns to editing product
6. Expand Price, previous edits have been reverted as it appears the product needs to be saved prior to Add/Editing of Specification Attributes.

Same issue happens in the Product Attributes.

**Comment by RomanovM** [comment]
@glhays Yep, that's by design, you need to save the changes before leaving the product details page. 
What you propose to change in this process?

**Comment by glhays** [comment]
Hey Romano, 
No disrespect but I feel it is an effect of the design not the design of the product add/edit page. Only ProductAttributes and ProductSpecifications have under gone a change in 4.3 to leave the page and return back. The popup dialog of the past and still being used in a lot of other places works just fine.
What by design now makes it have to leave the page directly and return and essentially reload the product. I may be missing something?

**Comment by AndreiMaz** [comment]
As Maxim mentioned it's by design
