### ISSUE TITLE
Move UseRouting to own startup file

### ISSUE THREAD

**Issue by JadynWong** [nopSolutions/nopCommerce#5056]
https://github.com/nopSolutions/nopCommerce/blob/49da7cefa8716028de3bf71ffa6ab5c5bed14386/src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs#L388-L397

It is proposed to moveUseEndpoint to a separate INopStartup.

Some middleware must be between Routing and Endpoint.
See `https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#order`

This will be more user-friendly for plug-in development.

**Comment by zandiarash** [comment]
Would you please see [this page](https://www.nopcommerce.com/en/boards/topic/88910/nopcommerce-430-change-default-route) ? 
Is it related with this issue ?

**Comment by DmitriyKulagin** [comment]
@zandiarash I don't think these are related topics

**Comment by DmitriyKulagin** [comment]
Closed #5056
