### ISSUE TITLE
Check the icons functionality in virtual directories

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#5059]
nopCommerce version: 4.0-4.2+

Steps to reproduce the problem: 
Likely most people fix this manually or don't use the site as a subsite much, but appears to be an ongoing issue...

Create new site: put site as subsite "mysite/nop"

images will render correctly "http://mysite/nop/images..."
icons will not "http://mysite/icons...."
No icons will manifest in any (that we've tested) device icon placement (widgets, tabs, pins, homescreens, etc...)

(from the code this issue appears to be still present in 4.3 but we havne't tried it out yet)

**Comment by mariannk** [comment]
@awe-source hi. To fix this you need to override the "commonsettings.faviconandappiconsheadcode" setting. Just change the icon paths considering your virtual repository name, such as href="/virtual_repository_name/icons/icons_0/apple-touch-icon.png
