### ISSUE TITLE
Force activation of multi-factor authentication for all users

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5060]
Perhaps we should provide for the expansion of the multifactor authorization functionality by additional setting the forced activation of the MFA for each user.

**Comment by iammourya** [comment]
This would either have to be via on Google or Microsoft Authenticator or using Text Message to the registered mobile phone number.

**Comment by DmitriyKulagin** [comment]
Closed #5060
