### ISSUE TITLE
Separate wishlist from ShoppingCartItem

### ISSUE THREAD

**Issue by alperalpdogan** [nopSolutions/nopCommerce#5061]
Adding products to wishlist should not redirect to the product page and it should not make it mandatory to select a variant to add it to the wishlist. I understand that since the basket items and the wishlist comes from the same table so users need to choose an attribute. It would be a better direction if wishlist is seperated from the basket items to it's own table so users could add products to their wishlist witout redirection and choosing an attribute.

**Comment by RomanovM** [comment]
Thanks for the suggestion. But after some consideration decided not to implement it out of the box and leave it for customization.
