### ISSUE TITLE
is it has video learn ?

### ISSUE THREAD

**Issue by mahdisky** [nopSolutions/nopCommerce#5062]
sorry,
is it has video learn?

**Comment by goransipic** [comment]
Hi mahdisky. For video learning you can subscribe on youtube channel [https://www.youtube.com/user/nopCommerce](https://www.youtube.com/user/nopCommerce) there is enough tutorials for getting started.

**Comment by RomanovM** [comment]
@goransipic You are right, thanks.
@mahdisky Please post all your questions on [our forums](https://www.nopcommerce.com/boards), we use GitHub as an issue tracker.
