### ISSUE TITLE
Move loading SpecificationAttributeOptionIds to a separate method from product search

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5065]
nopCommerce version: develop

Currently we load them in [Search](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Catalog/ProductService.cs#L548) method, this makes the query very complicated, let's move it to a separate method.

**Comment by badijm** [comment]
We could change signature of `SearchProducts` method to return (Value)Tuple ( `filterableSpecificationAttributeOptionIds`, `IPagedList<Product>`.)
instead of `out` parameter.

**Comment by RomanovM** [comment]
@badijm Yep, but we are thinking of completely moving the getting of this ids into a separate method, so there will be no need to return them from this one at all.

**Comment by badijm** [comment]
Got it. I would like to implement this, if available.

**Comment by RomanovM** [comment]
@badijm Thanks as always, but we are still thinking out how exactly implement this.

**Comment by exileDev** [comment]
Closed #5065 (see also #276)
