### ISSUE TITLE
Replace EPPlus

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5066]
[EPPlus](https://github.com/JanKallman/EPPlus) will from version 5 switch license from LGPL to Polyform Noncommercial 1.0.0 license. We need to replace it as its further update is not possible due to its commercial license.

Let's think about what alternatives we can use:
- [NPOI](https://github.com/dotnetcore/NPOI)
- [ExcelDataReader](https://github.com/ExcelDataReader/ExcelDataReader)
- [Open XML SDK](https://github.com/officedev/open-xml-sdk)

What else?

**Comment by JadynWong** [comment]
ClosedXml[ClosedXML](https://github.com/ClosedXML/ClosedXML)

It is very easy for operating excel.
ClosedXml is base on OpenXml.
The original OpenXml is very powerful, but not easy to operate.

**Comment by DmitriyKulagin** [comment]
Closed with commit https://github.com/nopSolutions/nopCommerce/commit/fbc65ba7df47e99ef58f01bf2a8519924297683c
