### ISSUE TITLE
Caching issue with absolute paths

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#5070]
nopCommerce version: 3.9, 4.0, 4.1, 4.2

Steps to reproduce the problem: 

binding with port 80 and 443 and SSL setup correctly and enabled in NOP store config, but NO hostname specified in IIS for the certificate.

recyle the app pool, restart the server, or clear the cache - make the FIRST request to the server (it MUST be the first request that causes caching to occur for the application).

the request should be of the following format:
"localhost"
a request by IP
a request with no "hostname" (we have even seen this with HEAD requests by server monitoring services -which you wouldn't think would cause the home page, or whatever, to load and cache image address paths but stepping through the code in test seems to show that "something" is causing the home page to load - perhaps IIS/aspdotnet doesn't 'do' HEAD requests properly!?)

eg: (this is a request that we've stepped through from the IIS logs that triggers this)
2020-10-02 02:14:58 W3SVC1 testserver1 192.168.1.1 HEAD / - 80 - 192.168.11.100 HTTP/1.0 WhatsUp/1.0 - - - 200 0 0 1004 57 140 192.168.11.100

these requests will cause the "hostname" to be dropped/lost/not provided and the "IP/localhost/dotNET process and port number (only in 4.0+)" to be cached for product images (usually the N images displayed on the homepage)

eg: 
https://127.0.0.1:12445 (dotnet process and port)
https://127.0.0.1 or https://localhost (accessing from server via locahost binding)
https://123.213.32.123 (access by IP)

these "broken URLs" are then cached for the duration of the cache lifecycle (eg: if your cache refresh is 1 hour - these broken image links will last for 1 hour) or if you manually "clear cache".

If you have a low volume website AND a integration/monitoring/malware/scanning/other service that references to SERVER/IP rather than the domain name, and its more likely to hit the server "first" after a refresh you will see this more often, if not then its likely you will only see these occasionally, for us we first noticed it with the appPool recycle times were in "non busy" times.

This has been reported several times eg: is highlighted in this topic... https://www.nopcommerce.com/en/boards/topic/52431/images-problem-40-version

no_jedi and  beefydogs "solution" (2 different ones) are both options:
"fix hostname in SSL cert binding" - in that it will fix the "app" but other aspects are problematic when using monitoring and you can no longer reference "localhost" on the server, however we've seen no huge side effects to keep alive or scheduled tasks from this configuration (yet).
"fix absolute paths" - in that it doesn't cache the "silly" values, however we have seen "theme" based things getting cached (logo, headings, can't pin these down to a coded source however... so this may be less than 100% solution. (perhaps related to HttpContext.Request.PathBase/_webHelper.GetStoreLocation() in some utility/models/factories)

Not sure if there is a "more correct" one...

Perhaps a better solution would be to fix/improve the caching so that it ONLY cached these if they were correct and not obviously "stupid" (eg: if url liek "locahost/127.0.0.1/127.0.0.1:12345/*.*.*.*/etc...", or if URL is NOT one of the hostname values in the "Store Configuration") values which don't really make sense in any senario - however this may slow down caching... so may not be a viable option.

Alternatively this is unlikely to be a problem with "relative" paths (and so, as others have suggested) - setting "use absolute path for media" to "FALSE" will also solve this issue - and with modern browsers and search engines and other tools, I am struggling to think of valid reasons why this isn't the default for NOPCOMMERCE in the first place, (and why there doesn't seem to be any Admin UI way to toggle this value (other than "all settings" obviously - I would think it should be on the "media settings" page...)
However perhaps we need to broaden this to the theme/webui utils, because we THINK there's something in there that is still getting the "absolute" path... but becasue this a tricky issue to "catch" in production its very difficult to prove/reproduce reliably across all aspects.

Thanks

**Comment by skoshelev** [comment]
Hi @awe-source. We made a setting to disable using full path for images (MediaSettings.UseAbsoluteImagePath), to solve such problems but did not implement it in the UI, as the need for it very rarely arises.

**Comment by awe-source** [comment]
If most of your implementations are cloud based and no one ever touches it locally (including monitoring systems) then it may never happen, however if you are self hosting or in any way controlling the server at a more structured setup, then it will arise.
Perhaps just documenting the existence of this feature is to solve this issue would be enough? (implementing a feature without reasoning information is next to useless - especially when it produces such random and hard to reproduce results)

**Comment by skoshelev** [comment]
We have created a task for documentation, you can find it [here](https://github.com/nopSolutions/nopCommerce-Docs/issues/216)

Closed #5070
