### ISSUE TITLE
Shopping cart item is cleared after placing order

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5072]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1- To have a credit card payment method.
2- The customer select a payment method with redirect mode.
3- Once the customer place an order, the shopping cart is cleared.
4- The customer will be redirect to the payment method page to insert the credit card information.
5- If something went wrong, the customer will find that his order is placed! This makes him confused.

Suggestion:
If the payment is redirect mode, then it is the plugin responsibility to clear the shopping cart after the payment is succeeded.

**Comment by AndreiMaz** [comment]
It's by design. An order is placed before the redirection. A customer can retry the payment on the order details page later

**Comment by ahmadkq** [comment]
> It's by design. An order is placed before the redirection. A customer can retry the payment on the order details page later

I know it is by design. What i am saying that you may think to change this process. I know the customer can do a retry payment but from his point of view and when the payment is failed, the customer thinks that the order is not placed and it is not logic to be placed. What do you think?
