### ISSUE TITLE
Assembly 'Nop.Web.Framework' with identity 'Nop.Web.Framework, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.AspNetCore.Mvc.Razor, Version=3.1.6.0, Culture=neutral,

### ISSUE THREAD

**Issue by aslamusa** [nopSolutions/nopCommerce#5079]
nopCommerce version: 4.3
Database : MSSQL

Steps to reproduce the problem: 

Getting erros when publishing site. When I run the website locally, it works fine. But it is as soon as it is published, that it starts complaining.
Errors occur when open installation page.
I haven't updated any nuget packages. As far as I understand the error may be caused by NuGet packages.

Have you encountered this problem?

![nopommerce](https://user-images.githubusercontent.com/20440971/95423782-56988c80-094a-11eb-951d-ec6554f590c4.png)

**Comment by AndreiMaz** [comment]
We cannot reproduce the described issue
