### ISSUE TITLE
SVG image support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#508]
Forum source: https://www.nopcommerce.com/en/boards/topic/18871/svg-support

Just check whether SkiaSharp supports it. If yes, then enable it. Otherwise, just close this task

**Comment by AndreiMaz** [comment]
isn't it supported?

**Comment by Etabat** [comment]
Just to confirm, is svg supported in nopCommerce? If not, what are the alternatives? I'm a bit confused as to whether it is or not based on the information available, and this post from four years ago: http://www.nopcommerce.com/boards/t/18871/svg-support.aspx

**Comment by AndreiMaz** [comment]
@Etabat  not supported out of the box. http://imageresizing.net/ doesn't support it. although there are some third-party plugins for imageresizing that support it

**Comment by Etabat** [comment]
@AndreiMaz, thank you for the suggestion. Unfortunately I had no luck finding any. Do you know of which third-party plugins specifically? A link would be highly appreciated, thanks!

**Comment by AndreiMaz** [comment]
@Etabat It requires some investigation. But I've seen several such posts on stackoverflow.

**Comment by VladislavSrd** [comment]
@AndreiMaz SVG ведь векторный формат причем тут imageresizing? Обычно размер задается в css, но в нашем случае можно в атрибут style задать размер.

**Comment by USvER** [comment]
I'm migrating website from woocommerce wich has category icons as SVG...
I was really surprized that SVG does not supported out of the box =\

**Comment by tigran-avdalyan** [comment]
its need

**Comment by tigran-avdalyan** [comment]
we can enable Supporting SVG only for Manufacturers, Catalogs, 
And don't support for Products.
In Manufacturers and Catalogs we don't need to resize function.

**Comment by jhaydens** [comment]
maybe we should support for all images (including slider). it will mean faster loading of nopcommerce especially  on mobile devices and this has become really important in terms of goole rankings ( i attended a google seminar in january where we were told load speed on mobile devices would determine overall rankings)
lets get ahead of the curve

see also:
[http://www.nopcommerce.com/boards/t/46398/optimisation-send-smaller-images-or-avoid-sending-some-images-to-mobile-devices.aspx](url)

**Comment by tigran-avdalyan** [comment]
https://dotnet.libhunt.com/project/resizer/vs/imageprocessor?rel=cmp-cat

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization

**Comment by RomanovM** [comment]
Now we are using SkiaSharp as an image processor, so we should think about SVG image support again.

**Comment by DmitriyKulagin** [comment]
Closed #508
