### ISSUE TITLE
Performance optimization of rendering of the top menu

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5081]
nopCommerce version: develop

It takes 30-40% of the request time.
We already added `UseAjaxLoadMenu` setting (disabled by default), let's think what else we can do.
See also: https://github.com/nopSolutions/nopCommerce/issues/2094

**Comment by iammourya** [comment]
Excellent consideration.

**Comment by exileDev** [comment]
Closed #5081
