### ISSUE TITLE
Add the "back to" link to the "Shipping method restrictions" page from the "Shipping restrictions" page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5083]
nopCommerce version: 4.30

Steps to reproduce the problem:

Go to https://admin-demo.nopcommerce.com/Admin/Shipping/Restrictions
There is no any "back to" link.
Add one to the "Shipping rate computation methods (providers)" page (not to the default shipping plugin)

**Comment by holydk** [comment]
Closed #5083
