### ISSUE TITLE
Feature-Policy superceeded

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5084]
nopCommerce version: 4.30

The feature policy has now been renamed to Permissions-Policy
in [web.config](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/web.config):
`<add name="Feature-Policy" value="accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment *; usb 'none'" />`
Should now be:
`<add name="Permissions-Policy" value="accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment *; usb 'none'" />`
Source: https://www.nopcommerce.com/en/boards/topic/88132/feature-policy-superceeded

**Comment by DmitriyKulagin** [comment]
Closed #5084
