### ISSUE TITLE
Handling locale formatting errors

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5085]
nopCommerce version: develop

We should find a way to handle errors in case of incorrect formatting locales using `string.Format()` (e.g. `Index (zero based) must be greater than or equal to zero and less than the size of the argument list.`) and just return incomplete text instead of throwing an exception.

For example see https://www.nopcommerce.com/en/boards/topic/88112/index-zero-based-must-be-greater-than-or-equal-to-zero-and-less-than-the-size-of-the-argument-list
Also see https://github.com/nopSolutions/nopCommerce/issues/4146

**Comment by AndreiMaz** [comment]
These are errors that actually should not be handled so a store owner knows about that and can fix it
