### ISSUE TITLE
Allow settings to be used as message template tokens

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5086]
nopCommerce version: develop

Source: https://www.nopcommerce.com/en/boards/topic/88148/referencing-a-setting-in-a-string-resources
See also: https://github.com/nopSolutions/nopCommerce/issues/125

**Comment by AndreiMaz** [comment]
We should not allow it. 

1. An administrator can use this functionality to get access to any setting (values) that it not acceptable
2. Settings are hard-coded and aren't changed (in 99% cases). So it almost doesn't make any sense to support them. Just use its value in message templates
