### ISSUE TITLE
Add 'List<string>' support to 'nop-select' tag helper with asp-multiple="true"

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5090]
nopCommerce version: 4.30+

Steps to reproduce the problem: `nop-select` tag helper with `asp-multiple="true"` throw exception if `asp-for` parameter contains `List<string>`. We may need to add a new editor template for `List<string>`.
AggregateException: One or more errors occurred. (The model item passed into the ViewDataDictionary is of type 'System.Collections.Generic.List`1[System.String]', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.List`1[System.Int32]'.)

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/4725
