### ISSUE TITLE
Decimal serialization error for inline table editing

### ISSUE THREAD

**Issue by landlogicit** [nopSolutions/nopCommerce#5091]
nopCommerce version: 4.3

Steps to reproduce the problem: 
bug version 4.3. if I am in the admin area and for example I go to the management of measures on dimensions and I modify a value on ratio it is converted badly. if I pass 0,2 it puts 2, if I put 0.2 it always puts 2. this problem does not happen with the English language.

**Comment by DmitriyKulagin** [comment]
Closed #5091

**Comment by landlogicit** [comment]
Good Job

**Comment by dimiszk** [comment]
NopCommerce version 4.30 (branch 4.30-bug-fixes)
I am trying to modify the seconds value on Scedule taks. On update i am gettting the error The value 'x' is not valid for Seconds (run period). Seconds should be positive

**Comment by DmitriyKulagin** [comment]
@dimiszk Thanks a lot! I added commit https://github.com/nopSolutions/nopCommerce/commit/789774491d6cf876dd1bda934c024b22555b9a0d in the 4.30-bug-fixes branch
