### ISSUE TITLE
Activate newsletter subscription only after email validation (if enabled)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5092]
1. Set the "Registration method" setting  to "Email validation is required after registration"
2. Register a new account and check "Subscribe to newsletter"
3. The "newsletter" record will be marked as active. But we should not mark the "newsletter" record as active until the email is validated. But let's validate it only if the "Registration method" setting is set to "Email validation is required after registration"

**Comment by skoshelev** [comment]
Closed #5092
