### ISSUE TITLE
Images Squares on a mobile device

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#5093]
nopCommerce version: v4.3
It is only a little problem - not ever sure it is a problem to be fixed - just something I noticed : 
On a small mobile device go to https://demo.nopcommerce.com/nike-floral-roshe-customized-running-shoes
Select the right Image Square for Print - Because on a mobile device the Print image stays in focus
The pop-up image covers the add to cart button
And if you click the poped up image it does not go away 
You need to click off the Image to reveal the Add to cart button
But then you have not selected the Image Square - You need to select it again to register the selection
Im a bit stupid as it took me a liitle while to work out to click off the image 
and click the image again to get the correct selection
Maybe thats just how stuff works on a mobile  ?
See 
![Error Images Squares on Mobile](https://user-images.githubusercontent.com/34350154/95958594-19059900-0e4d-11eb-8393-fbd7bc48a853.png)

**Comment by mariannk** [comment]
@SelectSystemsInternational hi. I can't reproduce this issue. When I click off the image to reveal the Add to cart button, the image square stays selected. Could you please share more details, record a video, or somehow explain how to reproduce this?

**Comment by SelectSystemsInternational** [comment]
Hi Mariann 

 

Here is a video using the phone6 plus simulator in Chrome

 

If you use the actual iPhone 6 plus then an extra click is required when the pop-up image is displayed to select the option as discussed in the post 

 

Also tried in Firefox – sems the pop image is not displayed so there is no issue as such

 

Thanks

Andrew

**Comment by mariannk** [comment]
Seems like this is a default iOS behaviour: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW4
