### ISSUE TITLE
Whether to return soft deleted entities from services methods

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5094]
nopCommerce version: develop

Whether we should return mark as deleted entities (implemented [ISoftDeletedEntity](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Common/ISoftDeletedEntity.cs) interface) from services methods?
We can consider such entries as completely deleted and not return them at all, as for example was done for all [GetByIds()](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/EntityRepository.cs#L86) methods, [SearchOrders](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderService.cs#L258), etc.
Or we can return such entries from methods and filter deleted by place of use.
What about `GetById` method?

**Comment by sdanyliv** [comment]
Just don’t forget that linq2db has QueryFilters
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/QueryFilterTests.cs#L111
Which can be ignored by `IgnoreFilters`. It will help to do not forget filtering associations.

**Comment by RomanovM** [comment]
So, we decided not to complicate the current implementation for now (including using QueryFilters, as @sdanyliv suggested) and let the developers decide for themselves whether to filter such soft deleted entries.
We'll just add a common parameter to the repository methods for more convenient use. As for our services, the approach is as follows: `GetById()` always returns soft deleted entries (this is necessary for some features to work correctly), `GetByIds()` gets entries already filtered at the repository level and returns them as-is, `GetAll()` and  `GetAllPaged()` filter entries at the service level. In all other cases the need for a filter is considered separately.

**Comment by skoshelev** [comment]
Closed #5094
