### ISSUE TITLE
Make a [store] as a soft deleted entity 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5096]
nopCommerce version: develop

Store must implement the `ISoftDeletedEntity` and just be marked as Deleted when deleted to avoid losing of the related mapping data.

See also: https://github.com/nopSolutions/nopCommerce/issues/5035

**Comment by badijm** [comment]
Hi, I can work on that, looks somple enough.

**Comment by exileDev** [comment]
Closed #5096
