### ISSUE TITLE
Don't use linq2db outside of Nop.Data

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5097]
nopCommerce version: develop

Remove direct access to LinqToDB namespace in all projects except Nop.Data, we should encapsulate all appropriate methods and properties in Nop.Data and use them in other projects. 
At the moment such usings remain in [PictureService](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Media/PictureService.cs#L6) and [BaseNopValidator](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Validators/BaseNopValidator.cs#L5).

**Comment by exileDev** [comment]
Closed #5097
