### ISSUE TITLE
Remove some unused methods

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5098]
nopCommerce version: develop

Remove some unused methods from services and appropriate interfaces (marked with 
`//TODO: Delete unused method` and 
`//TODO: may be deleted`).
 But be sure that they are not actually used anywhere (including in plugins, tests, views, etc).

**Comment by skoshelev** [comment]
Also, see the https://github.com/nopSolutions/nopCommerce/commit/3148040cbb2344091572b1758b454338fd075fa2 commit

Closed #5098
