### ISSUE TITLE
Move some public methods to protected utilities

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5099]
nopCommerce version: develop

Move some public methods to protected utilities and remove from appropriate interfaces (marked with
`//TODO: may be deleted from interface`).
But be sure that they are not actually used anywhere except owning class (including in plugins, tests, views, etc).

**Comment by skoshelev** [comment]
Implemented by https://github.com/nopSolutions/nopCommerce/commit/ccfde281cd7409a0207b7969c47ae343fc6b9f33 commit

Closed #5099

**Comment by skoshelev** [comment]
We need to roll back changes in the factory interfaces because it produces problems for plugin developers ([see details here](https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/5#281596))

**Comment by skoshelev** [comment]
Closed #5099
