### ISSUE TITLE
Form Field Tooltips

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#51]
I would like to see the ability to add custom form field tooltips throughout NC. This is a great way to give a little help to our customers. This site has a great example of how to apply it with minimal code: http://jqueryui.com/tooltip/#forms 

Forum source: http://www.nopcommerce.com/boards/t/20067/feature-request-custom-form-field-tooltips.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
