### ISSUE TITLE
Simplify interfaces by moving some methods to extensions

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5100]
nopCommerce version: develop

We have a number of methods in services that don't use class fields and dependencies, but only execute common actions or calculations (marked with 
`//TODO: migrate to an extension method`).
We could port these methods to extensions and thus simplify interfaces, but such extensions are more difficult to override in plugins or in customization (see related issue #3038).
Let's think out how best to do here.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
