### ISSUE TITLE
Save option not working

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5106]
nopCommerce version: v4.40

![Screenshot 2020-10-21 at 11 51 39](https://user-images.githubusercontent.com/6122624/96704018-d6374a00-1393-11eb-9185-93a6fbb1019c.png)

**Current behaviour:**

Steps to reproduce the problem: 

1.) Step
![Screenshot 2020-10-21 at 11 20 47](https://user-images.githubusercontent.com/6122624/96701661-22cd5600-1391-11eb-8f72-963ebfbaf0cd.png)

2.) Step
![Screenshot 2020-10-21 at 11 30 04](https://user-images.githubusercontent.com/6122624/96703287-f74b6b00-1392-11eb-9aa0-a3919b274838.png)

Why is there save button. If you click the button nothing is happening. There is nothing to save on this screen. Only option to filter products.

**Expected behaviour:**

Remove the save button

**Comment by holydk** [comment]
It's by design. Closed #5106
