### ISSUE TITLE
Upgradation of version 4.1

### ISSUE THREAD

**Issue by AbhishekRobosol** [nopSolutions/nopCommerce#5109]
nopCommerce version 4.1: 

I am currently working on version 4.1 application. I just want to add/merge upgradated version file int omy current version (4.1) application without upgrading to newer version whole application.

I there any way to do changes in code/file? How to add that code/file in my existing applcation(version 4.1).

All help is appreciated!

Thanks

**Comment by AndreiMaz** [comment]
Could you please post all technical questions on our forums?
