### ISSUE TITLE
CustomerService.GetCustomerByGuid() is not cached

### ISSUE THREAD

**Issue by KostaVlev** [nopSolutions/nopCommerce#5111]
Seems like it is worth it to cache since is executed on each request for guest customers

```
public virtual Customer GetCustomerByGuid(Guid customerGuid)
{
        if (customerGuid == Guid.Empty)
            return null;

        var query = from c in _customerRepository.Table
                    where c.CustomerGuid == customerGuid
                    orderby c.Id
                    select c;
         var customer = query.FirstOrDefault();

         return customer;
}
```

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Customers/CustomerService.cs#L398

in similar way like 

```
public virtual Customer GetCustomerById(int customerId)
{
        return _customerRepository.GetById(customerId,
            cache => cache.PrepareKeyForShortTermCache(NopEntityCacheDefaults<Customer>.ByIdCacheKey, customerId));
}
```

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Customers/CustomerService.cs#L377

**Comment by AndreiMaz** [comment]
There is no any need to cache it because it's already cache (later) in the "SetCurrentCustomer" method of "WebWorkContext" (in a local variable).
