### ISSUE TITLE
Update/Insert/Delete Customer clears entire customers related cache

### ISSUE THREAD

**Issue by KostaVlev** [nopSolutions/nopCommerce#5112]
When Update/Insert/Delete Customer the `CacheEventConsumer` 

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Caching/CacheEventConsumer.cs#L63

calls 

```
protected override void ClearCache(Customer entity)
{
        RemoveByPrefix(NopCustomerServicesDefaults.CustomerCustomerRolesPrefix);
        RemoveByPrefix(NopCustomerServicesDefaults.CustomerAddressesPrefix);
        RemoveByPrefix(NopEntityCacheDefaults<ShoppingCartItem>.AllPrefix);

        if (string.IsNullOrEmpty(entity.SystemName))
            return;

        Remove(NopCustomerServicesDefaults.CustomerBySystemNameCacheKey, entity.SystemName);
}        
```

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Customers/Caching/CustomerCacheEventConsumer.cs#L29

which would clear entire customers related cache and because there is almost all the time one of the CRUDs executed for Customer, example is guest visits the site we Insert the guest customer and the cache will be cleared, so there is never anything cached for Customers.

Probably is a good idea to narrow the clearing the cache to the current customer?

**Comment by skoshelev** [comment]
Closed #5112
