### ISSUE TITLE
Add soft delete to product attributes / combinations

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#5114]
nopCommerce version: 
4.2

We have a plugin which allows customer service representatives to edit orders after they have been placed. After an order is placed, when an admin deletes product attributes which are associated to a product, the link between an order item with that product+attribute and the product is lost because the product attribute records are hard deleted. We lose the order item product SKU and other product information on historical orders when the attribute is deleted.

To fix: When an attribute is deleted, the product attribute and product attribute mapping should not be deleted from the database. Instead, it should set an IsDeleted flag to true, similar to deleting a product.

Better fix: IMO, a better fix is to copy down all of the product information onto the order item when an order is placed. That way, even if products change, the line item has an accurate historical record of the order's products and attributes. We should never have to navigate from an order item to a product to determine information about the product that was ordered since the product may have changed since the order was placed.

Steps to reproduce the problem: 
1) Set up a product with an attribute associated to a product:
2) Place an order using the product with the associated-to-product attribute
3) Delete the product attribute from the product
Now the link between the order line item and the product is lost.

**Comment by AndreiMaz** [comment]
Thank a lot for suggestion. Considering the this information now is stored as text as well (duplicated), then it's not actually deleted. But you're right that it's not possible to work with this data programmatically.

We'll consider this implementation a little bit later (after other work items)

**Comment by AndreiMaz** [comment]
Consider it only after https://github.com/nopSolutions/nopCommerce/issues/2830 and https://github.com/nopSolutions/nopCommerce/issues/2564

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box
