### ISSUE TITLE
Microdata is incorrectly set to OutOfStock

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5116]
nopCommerce version: 4.30

Product is available and has Track Inventory and could be purchased but Display availability is not checked.
The microdata for the product is incorrectly set to OutofStock:
`<meta itemprop="availability" content="http://schema.org/OutOfStock"/>`
Simply uncheck "Display availability" for any product that is available and you will replicate the issue.

Source: https://www.nopcommerce.com/en/boards/topic/88443/nopcommerce-430-microdata-is-incorrectly-set-to-outofstock
See also: https://github.com/nopSolutions/nopCommerce/issues/4616

**Comment by holydk** [comment]
Closed #5116
