### ISSUE TITLE
PopularProductTagsViewComponent causes performance issue when there are 4000+ product tags

### ISSUE THREAD

**Issue by KostaVlev** [nopSolutions/nopCommerce#5117]
`PopularProductTagsViewComponent` calls `_catalogModelFactory.PreparePopularProductTagsModel();`

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs#L1114

even that all database calls are cached the sroting logic is still very expensive and causes performance issues when there are lots of product tags.

In order to reproduce the issue, create database with 4000+ product tags then run any load test tools, I used [artillery](https://artillery.io/) and hit any category page. With the current implementation the application will become not responsive.

I was able to solve the problem by caching the entire `PopularProductTagsModel` model

Would be good if we can change the current `PreparePopularProductTagsModel()` logic to cache the entire `PopularProductTagsModel` model?

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/4980

**Comment by landlogicit** [comment]
Solutions for 4.3: 
public class PopularProductTagsViewComponent : NopViewComponent
    {
        private readonly ICatalogModelFactory _catalogModelFactory;
        
        private readonly ICacheKeyService _cacheKeyService; //nuovo
        private readonly CacheKey _chiaveCacheTags = new CacheKey("Nop.logic.chiavecachetags");
        private readonly IStaticCacheManager _staticCacheManager;

        public PopularProductTagsViewComponent(ICatalogModelFactory catalogModelFactory,
            ICacheKeyService cacheKeyService,IStaticCacheManager staticCacheManager)
        {
            _catalogModelFactory = catalogModelFactory;
            _cacheKeyService = cacheKeyService;
            _staticCacheManager = staticCacheManager;
        }

        public IViewComponentResult Invoke()
        {
            var chiaveCache = _cacheKeyService.PrepareKeyForDefaultCache(_chiaveCacheTags);

            //var model = _catalogModelFactory.PreparePopularProductTagsModel();

            var model = _staticCacheManager.Get(chiaveCache, () => _catalogModelFactory.PreparePopularProductTagsModel());

            if (!model.Tags.Any())
                return Content("");

            return View(model);
        }
    }
