### ISSUE TITLE
MemoryCacheManager.RemoveByPrefix() removes recent short term cache not related to the prefix when calls tokenSource?.Cancel()

### ISSUE THREAD

**Issue by KostaVlev** [nopSolutions/nopCommerce#5118]
`MemoryCacheManager.RemoveByPrefix()` removes recent cache not related to the prefix when calls `tokenSource?.Cancel()`.

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs#L202

The issue with calling `tokenSource?.Cancel()` is that particulary when `RemoveByPrefix(NopCustomerServicesDefaults.CustomerCustomerRolesPrefixCacheKey);` is called from `CustomerCacheEventConsumer` wipes out the recet cached item that are not related to `CustomerCustomerRolesPrefixCacheKey`.

The issue can be reproduced by adding some new item to the short term cache then check if the cache is set for it before and after `RemoveByPrefix(NopCustomerServicesDefaults.CustomerCustomerRolesPrefixCacheKey);`

![screen shot](https://user-images.githubusercontent.com/10883826/97192268-22143580-177e-11eb-9a36-e9f01f54c49a.PNG)

**Comment by KostaVlev** [comment]
If I replace `services.AddDistributedMemoryCache();` with `services.AddMemoryCache();` it wokrs as expected.

https://github.com/nopSolutions/nopCommerce/blob/ed3d75b1bec0b7b474e5d8f41cdd077f44538cc6/src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs#L29

The `MemoryCacheManager` is actually using `IMemoryCache` and `IDistributedCache` is never used.

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs#L22

Is any specific reason for using `services.AddDistributedMemoryCache();` ?

**Comment by skoshelev** [comment]
Hi, @KostaVlev.

We were unable to replicate your problem, but for [this ticket](https://github.com/nopSolutions/nopCommerce/issues/4699), we removed the call of `services.AddDistributedMemoryCache() `method when using the in-memory cache

Closed #5118
