### ISSUE TITLE
hello，I have a question about lists

### ISSUE THREAD

**Issue by Xiaobaiaixiaobai** [nopSolutions/nopCommerce#5122]
nopCommerce version: 4.30

Steps to reproduce the problem: 
For example, my current list is the second page. I select a column of data from the list and click the details page. When I return to the list, it can still be the second page. The current return is the default first page. How should I modify the code? Which master has achieved it? Want to ask the next train of thought, thank you!!!

**Comment by AndreiMaz** [comment]
Please post all technical questions on our forums http://nopcommerce.com/boards/
