### ISSUE TITLE
Customer activitylog list can not paging

### ISSUE THREAD

**Issue by JadynWong** [nopSolutions/nopCommerce#5124]
https://github.com/nopSolutions/nopCommerce/blob/3783fdb26bb02e44788ae2182bd68ea1651f331d/src/Presentation/Nop.Web/Areas/Admin/Factories/CustomerModelFactory.cs#L1045-L1075

It is should be `new CustomerActivityLogListModel().PrepareToGrid(searchModel, activityLog, () => pageList); `

I can't understand. It this is by design?

**Comment by RomanovM** [comment]
@JadynWong You are right. We've already fixed this in one of the issue branches, but not yet in the develop.

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/nopCommerce/commit/2158845eb40297dfb07475ffa257883d2e064f8e.
