### ISSUE TITLE
After checkout step 1 (Billing Address) always return to cart page

### ISSUE THREAD

**Issue by amrnoor** [nopSolutions/nopCommerce#5126]
nopCommerce version: 4.3

Steps to reproduce the problem: 
1- Select product
2- Go to shopping cart page
3- Sign on terms checkbox and click checkout button
4- Fill the billing address page
5- Click continue
6- It is return again to the cart page and do not going to step 2 (Shipping address)

**Comment by ekartsearch** [comment]
I'm also getting same issue, please resolve this, our store is not working and unable to proceed

**Comment by AndreiMaz** [comment]
We cannot reproduce it. It works fine out of the box. You can check it on our demo website - https://demo.nopcommerce.com/

**Comment by mursoftmx** [comment]
I have the same problem, on my development computer it works fine but on my website it has the same behavior pointed out in the post.

**Comment by prodigy** [comment]
I just created a fresh install using the docker container and the sample data and have the exact same issue.
