### ISSUE TITLE
Why multiple calls to database in order to persist one entity ?

### ISSUE THREAD

**Issue by ProNoob702** [nopSolutions/nopCommerce#5127]
Hi,
Didn't understand why there is multiple calls to the database in order to persist one entity 
as I see in customer creation :

![image](https://user-images.githubusercontent.com/16271638/97927069-95144200-1d64-11eb-9877-f4c245d2d7e7.png)

I think persiting all in one call could be better isn't it ?

nopCommerce version: Latest

**Comment by skoshelev** [comment]
Hi @ProNoob702. The screenshot shows that the customer is saved only once, and after that optional parameters are saved, which are stored as separate entities in the attribute table. If you can suggest a good optimization solution, we would be very grateful for your PR.

Please ask your questions on our forum: https://www.nopcommerce.com/boards
