### ISSUE TITLE
V4.3 Duplicate orders issue, orders are paid by Paypal express

### ISSUE THREAD

**Issue by zw896** [nopSolutions/nopCommerce#5131]
nopCommerce version: 4.3

Steps to reproduce the problem: 
Hi,
I found an issue related to checkout. For example, if customers open two tabs of same checkout page, and click confirm order in both tabs (btw, orders are paid by PayPal express plugin) almost at the same time, Nopcommerce will create two orders which are duplicated, and both two orders would be marked as Paid in Nopcommerce, but actually based on the response message received from Paypal, first order will receive both success and error responses, the second order does not have any Paypal message.

The success message is understandable, and the error message shows
..."Errors":[{"ShortMessage":"Duplicate Request","LongMessage":"A successful transaction has already been completed for this token.","ErrorCode":"11607"...

I know the possibility of this case maybe very small, but it has happened several times on our store. I dont know how the customer caused this problem exactly, but in the way I described above, I can reproduce this issue.

My question is how to prevent this issue? Is this a case would be improved in the future?

Thanks.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/paypalexpress-plugin-for-nopcommerce/issues/23
