### ISSUE TITLE
Improve PagedList performance

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5132]
nopCommerce version: develop

At now [this code](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/PagedList.cs#L35) `AddRange(source.Skip(pageIndex * pageSize).Take(pageSize).ToList());` produces the SQL with `ROW_NUMBER() OVER ..`. This approach can be very slow on large data. 
Let's think out what we can do. Try to use `OFFSET`, something else?

**Comment by exileDev** [comment]
There is currently no way to improve this approach.

Closed #5132
