### ISSUE TITLE
Check availability of all parent entities when get mappings

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5136]
nopCommerce version: develop

For example, in the method `GetProductManufacturersByManufacturerId()` we [check availability](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Catalog/ManufacturerService.cs#L286) of manufacturers but not products, although the mapping has references to both entities and actually cannot be returned if at least one of the parent objects is not available.
We should check all such places.

**Comment by exileDev** [comment]
Closed #5136
