### ISSUE TITLE
Caching by a single customer role

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5137]
nopCommerce version: develop

Whether we should cache objects by a single customer role or by all customer's roles (current approach, for example [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Catalog/CategoryService.cs#L158))? 
Let's discuss.

**Comment by AndreiMaz** [comment]
I don't think it's possible to cache separately for each customer role. Otherwise, we'll have to execute such SQL queries separately for each customer role to get appropriate results
