### ISSUE TITLE
Customize attachment name of Invoice

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#5138]
nopCommerce version: 4.3

**Steps to reproduce the problem:** 
Set `ordersettings.attachpdfinvoicetoorderplacedemail` to `true`
Enable Email sending
Create an Order

You will receive an Email with the Order placed notification.
You will have attached a document called `order.pdf`

**The problem:**
The name is not customizable and cannot be translated into other languages.

**What I would expect:**
I would expect a similar field to `OrderNumberMask` where we can customize the attachment name

**Comment by noncenz** [comment]
I can take this one. I'll assume we want to use the same base name for order paid and order completed as well.

**Comment by manuel3108** [comment]
Hey NopCommerce Team, can we expect this to be merged into the current version? This is such a small but important feature? There is even already a PR for that

**Comment by skoshelev** [comment]
Closed #5138
