### ISSUE TITLE
SEO support for product tags

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5146]
nopCommerce version: develop

Add to 'ProductTag' ability modify the metadata (meta-title, meta-description etc). So you can promote the site for narrow queries and get a more audience coverage.
Example
https://www.svyaznoy.ru/catalog/phone/224/tag/knopochnie
https://www.eldorado.ru/c/smartfony/tag/dlya-selfi/

**Comment by RomanovM** [comment]
See also: https://github.com/nopSolutions/nopCommerce/issues/873
