### ISSUE TITLE
The order is completed before the customer picks it up from the store

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5151]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Customer place order
1. Customer chose the pick-up option from the store
1. Customer paid the order
1. Store owner creates the shipment with delivered status (the shipment is waiting for the customer in the store)
1. Order is completed automatically, but the customer has not received it yet

**Comment by AndreiMaz** [comment]
@holydk It's by design. "delivered" means that a customer received products. You don't have to mark a shipment as delivered in such case (until a customer gets it)
