### ISSUE TITLE
asp-disabled tag is inconvenient to use

### ISSUE THREAD

**Issue by dmitrydulkevich** [nopSolutions/nopCommerce#5152]
nopCommerce version: 4.30

Why asp-disabled tag implemented in Custom Input and TextArea tag helper classes?
And why asp-disabled expected string value instead boolean?
I can't use asp-disabled without asp-for tag.

I guess, that realization is better: 
`
[HtmlTargetElement("input", Attributes = DisabledAttrName)]
[HtmlTargetElement("textarea", Attributes = DisabledAttrName)]
[HtmlTargetElement("select", Attributes = DisabledAttrName)]
 public class DisabledTagHelper : TagHelper
 {
private const string DisabledAttrName = "asp-disabled";
...
}
`

Can some one explain this moment?
Thanks.

**Comment by RomanovM** [comment]
See also https://github.com/nopSolutions/nopCommerce/issues/3779

**Comment by DmitriyKulagin** [comment]
Closed #5152
