### ISSUE TITLE
Display a warning about uploaded but uninstalled plugins (admin area dashboard)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5155]
Currently if there are some uploaded but still uninstalled plugins, then a store owner could miss information that they are available.

We already display some warnings related to plugins in admin area dashboard. Let's display information about uninstalled plugins with "SystemWarningLevel.Warning" type. Let's recommend to delete or install them. There's no any sense to keep them uninstalled

**Comment by skoshelev** [comment]
Closed #5155
