### ISSUE TITLE
Customer Table...

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#5158]
nopCommerce version: 4.30 

Steps to reproduce the problem:  Call API 100 times  every 10 minutes

---------------------------------------------------------------------------
Hi,
       in many forum posts it has been reiterated several times
that by Design has been chosen to maintain
session information in the Customer table.

All third-party plugins with sncronization capabilities, and even SevenSpikes APIs generate a huge amount
GUIDs without e-mails and without usernames in the Customer table.

This is unprofessional, and it is becoming difficult to explain to END USERS why the ID goes on by steps of 1,000 if I don't enter new customers.

The best solution would be to trace sessions in a table different Table. And nevermore  in Customer Table.

A new customer should be inserted only after a Shopping Cart Items confirmation .

By design at the time of Nop 2.65 The product table has been redesigned. It was a bold choice. It's time to do the same for the Customer table too.

Redesign the customer table, please !

The fact that the IDs are moving forward exponentially does not leave calm our customers.

I tried to explain  that it takes 50 years to reach the last Id of an integre,
but this thing continues to worry customers! And penalize sales of NopCommerce and its Templates !!
 
thanks

Luca

**Comment by AndreiMaz** [comment]
We store customer information in cookies, so they are not created for each page open. Furthermore, guests are periodically deleted by a schedule task

Regarding the API. What exactly API do you mean? If you're talking about a third-party provider, then it should be implemented this developer (create one system customer account and use it for each request)
