### ISSUE TITLE
Allow to mark shipments as ready for pick-up (for "pick-up in store" orders)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5162]
When a store owner has pickup in store enabled, then there's no user-friendly way to notify a customer when a shipment is ready for pick-up. We also have to add a way to mark such shipments as ready for pick-up

In such cases a store owner create a new shipment but doesn't mark it as shipped or delivered. So there's no need to add a new shipping status. We just have to allow a store to mark such "Shipment" records as "ready for pick-up" (add a new boolean property to the "Shipment" entity). This option should be available only for orders with "PickupInStore" set to "true", there's no need to display it for other orders.

When a shipment is marked as ready for shipping, then we have to send a new message template ("ShipmentReadyForPickup.CustomerNotification") to a customer

**Comment by untiedshoes** [comment]
Awesome, and much needed! This is something that I've already implemented for a client on 3.90 :)

**Comment by holydk** [comment]
@untiedshoes Hi. Could you tell us a little more about your implementation approach? Does your approach differ in any way from the suggested solution?

**Comment by untiedshoes** [comment]
> @untiedshoes Hi. Could you tell us a little more about your implementation approach? Does your approach differ in any way from the suggested solution?

Give me a little time, and I'll dig through the code - it's a 3.90 site, and I did it a little while ago now.

**Comment by untiedshoes** [comment]
Here's a link to my solution. It's a 'quick' hack, that requires a shipment to be added first, then you can set it to 'ready for collection, which in turn uses its own message template.

The ready for collection button only shows for those orders using store pick up - so yes, my solution works more or less as @AndreiMaz has suggested.

[https://streamable.com/xwp0oz](url)

**Comment by holydk** [comment]
@untiedshoes Thanks for your solution.

**Comment by DmitriyKulagin** [comment]
Closed #5162
