### ISSUE TITLE
Плагин подписки...

### ISSUE THREAD

**Issue by ARMAN-8** [nopSolutions/nopCommerce#5165]
Добрый день! Хотел узнать, имеется ли у вас плагин "подписки" ? Как на "Netflix, Яндекс Музыка, ivi". Создали интернет магазин через NopCommerce, теперь нам нужен плагин подписки.  Что бы у нас клиенты покупали товары необходимо приобрести нашу подписку. Есть ли такая возможность, если нет то можете ли нам разработать это, и озвучить цену?

**Comment by RomanovM** [comment]
Please post your questions on [our forums](https://www.nopcommerce.com/boards), we use GitHub only as an issue tracker.
