### ISSUE TITLE
Добрый день! Хотел узнать, имеется ли у вас плагин "подписки" ? Как на "Netflix, Яндекс Музыка, ivi". Создали интернет магазин через NopCommerce, теперь нам нужен плагин подписки.  Что бы у нас клиенты покупали товары необходимо приобрести нашу подписку. Есть ли такая возможность, если нет то можете ли нам разработать это, и озвучить цену?

### ISSUE THREAD

**Issue by ARMAN-8** [nopSolutions/nopCommerce#5167]
Добрый день! Хотел узнать, имеется ли у вас плагин "подписки" ? Как на "Netflix, Яндекс Музыка, ivi". Создали интернет магазин через NopCommerce, теперь нам нужен плагин подписки.  Что бы у нас клиенты покупали товары необходимо приобрести нашу подписку. Есть ли такая возможность, если нет то можете ли нам разработать это, и озвучить цену?

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/5165
