### ISSUE TITLE
Selected page number shown incorrectly on product/catalog page

### ISSUE THREAD

**Issue by mehmetcantas** [nopSolutions/nopCommerce#5169]
nopCommerce version: 
4.20
Steps to reproduce the problem: 

Open 2 different browser and try to navigate different pages (different page number) of any categories. Try to do this at the same time or in a very short period of time.

**Comment by AndreiMaz** [comment]
We cannot reproduce the issue on our demo website - https://demo.nopcommerce.com/

Please try to do it and share screenshots
