### ISSUE TITLE
Datatables inline edit issue "The value is not valid for seconds"

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5171]
nopCommerce version: 4.30

Steps to reproduce the problem: 

> While updating schedule task in nopcommerce 4.30 we are getting this problem "The value 86,400 is not valid for seconds. Seconds should be positive"
> 
> This error comes from Table.cshtml(Datatable) where team generate object for update row. Our server is with Italian culture but in my localhost with "en-US" culture
> new Intl.NumberFormat('@currentCulture').format(value)
> this line convert 86400 to 86,400

Source: https://www.nopcommerce.com/en/boards/topic/89138/schedule-task-update-the-value-is-not-valid-for-seconds

**Comment by DmitriyKulagin** [comment]
Closed #5171

**Comment by exileDev** [comment]
Closed #5171
