### ISSUE TITLE
Adding DeleteResourcesFromXml to allow for removing of localized sources from xml

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#5175]
nopCommerce version: 4.3

Steps to reproduce the problem: 

Will be very useful to have a function similar to ImportResourcesFromXml in LocalisationService in order to be able to **delete resources** based on the input xml files. This will very much simplify the handling of the resource inside the plugins. Then it will be possible to add default behavior in order to add and remove resources when the plugin get installed and uninstalled.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
