### ISSUE TITLE
Create discount rules based on the product attributes combinations

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#5176]
nopCommerce version: 4.3

Steps to reproduce the problem: Currently there is no way to have discount for specific product attribute combinations. For example if you want to only discount a red TShirt it is not possible.

**Comment by AndreiMaz** [comment]
@Farshidgolkarihagh Thanks for suggestion. But we'll leave it for customization or plugin development (it can be implemented as a discount requirement plugin)
