### ISSUE TITLE
Editing order to add a product doesn't work correctly for product attribute combination

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#5177]
nopCommerce version: 4.3

Steps to reproduce the problem: 
For a given order, if you want to add a product which is defined by a product attribute combination, there are a number of problems: 

1) It doesn't evaluate the correct price for the selected product attribute combination. 
2) If the order already have a discount, it doesn't apply the discount for the added product

**Comment by RomanovM** [comment]
At the moment, we don't plan to complicate the process of adding products to an existing order. You need to manually specify the product price (qty, total) according to all your requirements and conditions. 
Or use feature 'Impersonate customer' and place an order at the public store.

Later, these problems may be solved in https://github.com/nopSolutions/nopCommerce/issues/8 or https://github.com/nopSolutions/nopCommerce/issues/1920.
