### ISSUE TITLE
Incorrect formatting for strings in NopCommonDefaults.cs

### ISSUE THREAD

**Issue by HaykoAper** [nopSolutions/nopCommerce#5178]
nopCommerce version: 4.3
Incorrect formatting for SingleFaviconHeadLink, FaviconAndAppIconsPath and LocalePatternPath.
May result failing HTML verification if single favicon.ico is uploaded. 
The path is formatted with backslashes (\\) instead of common slash (/)

Steps to reproduce the problem: 
In file "Nop.Services/Common/NopCommonDefaults.cs"

In current version:
```
public static string SingleFaviconHeadLink => "<link rel=\"shortcut icon\" href=\"\\icons\\icons_{0}\\{1}\">";
public static string FaviconAndAppIconsPath => "icons\\icons_{0}";
public static string LocalePatternPath => "lib\\cldr-data\\main\\{0}";
```

Should be:
```
public static string SingleFaviconHeadLink => "<link rel=\"shortcut icon\" href=\"/icons/icons_{0}/{1}\">";
public static string FaviconAndAppIconsPath => "icons/icons_{0}";
public static string LocalePatternPath => "lib/cldr-data/main/{0}";
```

**Comment by badijm** [comment]
Hi, if this item available I can grab.

**Comment by RomanovM** [comment]
@badijm Sure. You are welcome.
