### ISSUE TITLE
BillMeLater support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#518]
Provide BillMeLater support. By providng BillMeLater support, customers can make larger purchases and not have to worry about paying for them upfront. This feature will increase sells of larger ticket items and is an extremely valuable feature for any e-commerce storefront. It will also increase sells for customers who don't have the money to make the purchase, but will have the money later (deferred billing). 

There should be a BillMeLater button under the Add to Cart button. This is for making the customer aware of the BillMeLater feature and providing more information and how to use it. 

Example of BillMeLater button - http://www.flickr.com/photos/11900110@N08/7044918025/ 

BillMeLater website - https://www.billmelater.com/index.xhtml 

Forum source: http://www.nopcommerce.com/boards/t/16173/bill-me-later.aspx

**Comment by AndreiMaz** [comment]
should done as plugin
