### ISSUE TITLE
Order edit page on showing error page when product is deleted.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5184]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Step 1: Place 1 Order (3 Product) 
Step 2: Login with admin 
Step 3: Go to Admin => Sales => Order
Step 4: Click on View button of placed order 
Step 5: Go to Products panel on order edit page.
Step 6: Delete 1 product from product list 
Step 7: Click on refresh browser
Step 8: Click on Continue button 
![order edit on producterr](https://user-images.githubusercontent.com/50259172/100186732-93294300-2f0c-11eb-9d38-5eb04ddc6b68.png)

Actual Result : showing error page

Expected Result : should not show error page

**Comment by glhays** [comment]
Why are you refreshing page at step 7?
________________________________

**Comment by AndreiMaz** [comment]
Looks like you don't refresh the page. It works fine if you refresh it (do not re-post)
