### ISSUE TITLE
does not implement interface member 'IOpenIddictApplicationManager.CreateAsync(OpenIddictApplicationDescriptor, CancellationToken)'

### ISSUE THREAD

**Issue by SharadKamate** [nopSolutions/nopCommerce#5185]
nopCommerce version: 

Steps to reproduce the problem:

**Comment by SharadKamate** [comment]
what I am missing, i downloaded the project and rebuild it, and it is not working

**Comment by RomanovM** [comment]
@SharadKamate There is no such interface in the project, try to check third-party plugins, themes, customization, etc. 
Anyway, post your questions on [our forums](https://www.nopcommerce.com/boards), we use GitHub as an issue tracker only.
