### ISSUE TITLE
Update old price on product details page for discounted products on product attribute change

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#5186]
On a product details page, when the product has a discount, selecting a product attribute with +additional price will change the product price but will not reflect it in the old product price (strikethrough price)

Please consider making changes so it also updates the old price.

Potentially:

Can  include a price without discount calculation in ShoppingCartController.ProductDetails_AttributeChange to be returned in the resulting json so it can be used in javascript to update the price ?

Probably duplicating the price calculation like this with includeDiscounts set to false ?

```
var priceWithoutDiscount = string.Empty;
if (_permissionService.Authorize(StandardPermissionProvider.DisplayPrices) && !product.CustomerEntersPrice)
{
    var finalPrice = _shoppingCartService.GetUnitPrice(product,
        _workContext.CurrentCustomer,
        ShoppingCartType.ShoppingCart,
        1, attributeXml, 0,
        rentalStartDate, rentalEndDate,
        false, out var _, out _);
    var finalPriceWithoutDiscountBase = _taxService.GetProductPrice(product, finalPrice, out var _);
    var finalPriceWithoutDiscount = _currencyService.ConvertFromPrimaryStoreCurrency(finalPriceWithoutDiscountBase, _workContext.WorkingCurrency);
    priceWithoutDiscount = _priceFormatter.FormatPrice(finalPriceWithoutDiscount);
}
```

Then in _ProductAttributes.cshtml for function @(attributeChangeHandlerFuncName)()
```
if (data.priceNoDiscount) {
    $('.discounted-price-value-@productId').text(data.priceNoDiscount);
}
```

**Comment by AndreiMaz** [comment]
After some consideration we've decide not to implement this functionality and leave it for customization.
