### ISSUE TITLE
Please change URL Structure

### ISSUE THREAD

**Issue by hossein2408** [nopSolutions/nopCommerce#5187]
nopCommerce version: 4.3

Steps to reproduce the problem: 

please change URL structure to http://sitename.com/PoductId/SeoName
and seo name only display for seo and routing by productId or newsId ,...

**Comment by hossein2408** [comment]
it can implement like wordpress and website owner can change it in web site settings by tokens
%product_id%
%post_id%
%postname%
%category%
%author%
 http://sitename.com/%product_id%/%postname%/
old version users can use google change of address and 301 redirect

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But it's better to remove the "productid" part from the URL (currently it's better optimized for SEO)
