### ISSUE TITLE
UpdateShipping function with multiple store don´t return the expected result

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#5188]
nopCommerce version: 4.30

Steps to reproduce the problem: 

1. have more than one store
2. each store has the same shipment method but with diferent shipment fee 

- stroe A (www.storeA.com) has shipmentoption x with additional cost for example 10€

- store B (www.storeB.com) has the same shipmentoption x with diferent additional cost for example 20€
3. store manager is logged in the background with (www.storeA.com) domain
4. the store manager change an order ( with 20€ shipment fee) from store B
5. the store manager save that changes
6. the order shippingTotalExclTax will be 10€ 

```
protected virtual decimal UpdateShipping(UpdateOrderParameters updateOrderParameters, IList<ShoppingCartItem> restoredCart,
            decimal subTotalInclTax, decimal subTotalExclTax, out decimal shippingTotalInclTax, out decimal shippingTaxRate)
        {

            var updatedOrder = updateOrderParameters.UpdatedOrder;
            var customer = _customerService.GetCustomerById(updatedOrder.CustomerId);


// hier is the bug
 var shippingOptionsResponse = _shippingService.GetShippingOptions(restoredCart, shippingAddress, customer, updatedOrder.ShippingRateComputationMethodSystemName, _storeContext.CurrentStore.Id);
}
```

the fix for this issue is take the store Id from the updatedOrder instead _storeContext.CurrentStore.Id
`var shippingOptionsResponse = _shippingService.GetShippingOptions(restoredCart, shippingAddress, customer, updatedOrder.ShippingRateComputationMethodSystemName, updatedOrder.StoreId);`

**Comment by RomanovM** [comment]
Thanks. Moved to #8
