### ISSUE TITLE
Cannot open the "page not found" when a store is multilingual and closed

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5190]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Enable "SEO friendly URLs with multiple languages enabled" (general settings). And the restart a website
2. Close the store (general settings)
3, Try to open some non-existing page (e.g. /sdfsdfsdfsdfsdf)
4. You should be redirected to the /page-not-found page or /storeclosed page. But you're redirected to the /page-not-found/storeclosed that even cannot be open

Source: https://www.nopcommerce.com/en/boards/topic/89365/nopcommerce-makes-wrong-urls-when-store-is-closed

**Comment by DmitriyKulagin** [comment]
Closed #5190
