### ISSUE TITLE
Generate javascript for nested settings in admin area automatically (in tag helper)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5191]
nopCommerce version: 4.30

This way we will get rid of manually writing such scripts as [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Shipping.cshtml#L2)

**Comment by AndreiMaz** [comment]
The logic could be more complex and it won't be possible to automatically generate it in many cases
