### ISSUE TITLE
An "Edit" button doesn't work on the specification attributes page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5195]
nopCommerce version: 4.40 develop

Steps to reproduce the problem: 
1. Go to the specification attributes page
2. See the "Edit" button beside the Default group
3. Click this button
4. See that nothing happens
![cfa06c08f8](https://user-images.githubusercontent.com/16681184/100599861-9b6cee00-3311-11eb-8a70-98349f0a16ce.jpg)

**Comment by holydk** [comment]
Closed #5195
