### ISSUE TITLE
Don't use microdata for associated products that are not visible individually

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5197]
nopCommerce version: develop

Should we [create microdata](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Product/_Microdata.cshtml#L44) for all associated products or only for those that are `VisibleIndividually`?

Source: https://www.nopcommerce.com/en/boards/topic/89212/nullreferenceexception-reported-when-trying-to-view-a-product-manually-set-in-the-dbourlrecord-table#277872

**Comment by AndreiMaz** [comment]
@DmitriyKulagin We can use "itemref" for such purposes (but for grouped products only). Example: https://stackoverflow.com/questions/16903781/marking-up-html-code-with-microdata-when-there-are-multiple-products-on-a-page
