### ISSUE TITLE
Custom order number

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#52]
the order is now the ID a number itself can be better. for example, "year - prefix - sequential number" = "2015 - RE-30001". You should reset the serial number. So in the new year the number again 

Of course, standard ID will be also left. But need the ability to have custom order numbers as well

Forum source: http://www.nopcommerce.com/boards/t/33848/invoice-number.aspx

similar to RMA custom numbers implemented in 3.80)

**Comment by viewtance** [comment]
When will implement this feature?

**Comment by AndreiMaz** [comment]
Most probably in the next vesion

**Comment by viewtance** [comment]
Look forward to do it earlier, really need this feature.

**Comment by skoshelev** [comment]
Closed #52
