### ISSUE TITLE
Admin Panel Kendo UI culture not working

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#5200]
nopCommerce version: 4.30

Steps to reproduce the problem:  
Kendo UI language not set. Because after uploading the document should be set. 

Solved : 

`   <script type="text/javascript">
        $(document).ready(function () {
            var culture = "@GetDefaultLocale()";

            //load cldr for current culture
            $.when(
                $.get("/lib/cldr-data/supplemental/likelySubtags.json"),
                $.get("/lib/cldr-data/main/" + culture + "/numbers.json"),
                $.get("/lib/cldr-data/main/" + culture + "/currencies.json"),
                $.get("/lib/cldr-data/supplemental/numberingSystems.json"),
                $.get("/lib/cldr-data/main/" + culture + "/ca-gregorian.json"),
                $.get("/lib/cldr-data/main/" + culture + "/timeZoneNames.json"),
                $.get("/lib/cldr-data/supplemental/timeData.json"),
                $.get("/lib/cldr-data/supplemental/weekData.json"),
            ).then(function () {
                // Normalize $.get results, we only need the JSON, not the request statuses.
                return [].slice.apply(arguments, [0]).map(function (result) {
                    return result[0];
                });
            }).then(Globalize.load).then(function () {
                Globalize.locale(culture);
            });

                kendo.culture("@(currentKendoCulture)");
            });
    </script>`

**Comment by DmitriyKulagin** [comment]
@mehmetkurt You just need to install the CLDR package for your culture (General settings-> Localization), in which case it will work.

**Comment by mehmetkurt** [comment]
> @mehmetkurt You just need to install the CLDR package for your culture (General settings-> Localization), in which case it will work.

Hi,

I installed CLDR but not working. I changed the that code block, after the work!

**Comment by DmitriyKulagin** [comment]
@mehmetkurt Hi, I made a [video](https://www.loom.com/share/8782ece7418343ac89224e7a5f4e8c10) so you can see if we are trying to reproduce the error correctly. If these steps differ from yours, please let me know.

**Comment by networkfusion** [comment]
Perhaps related to https://github.com/nopSolutions/nopCommerce/issues/4777 fixed in next release?

**Comment by DmitriyKulagin** [comment]
@networkfusion I don't think it has anything to do with this task.
