### ISSUE TITLE
The "subscribe" button design issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5201]
nopCommerce version: 4.30

1. Text on the "subscribe" button doesn't fit the page when the text is too long
![33333e48b4ff](https://user-images.githubusercontent.com/5019111/101246447-6ce17f80-3724-11eb-9f32-573027e858a9.png)

2. We also have to check other buttons as well.

So it should have the standard minimum width but ensure that fits the long text

**Comment by DmitriyKulagin** [comment]
Closed #5201
