### ISSUE TITLE
Discounts. Add "basic" and "advanced" modes

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5208]
The following fields will be displayed for the "Advanced" mode only:

- Maximum discount amount
- Start date	
- End date
- Cumulative with other discounts	
- Discount limitation	
- Admin comment
- "Requirements" block

**Comment by ivan23gor** [comment]
Work Completed.


пт, 29 окт. 2021 г. в 17:47, Andrei Mazulnitsyn ***@***.***>:
