### ISSUE TITLE
Exception when executing PlaceOrder method caused missing OrderItem records.

### ISSUE THREAD

**Issue by sencagri** [nopSolutions/nopCommerce#5211]
Hello, 
We are using nopCommerce 4.30 and today my client told me that we have a Order that a missing OrderItem lines. I checked the log entries. 

And saw the exception below
![image](https://user-images.githubusercontent.com/7950917/101377946-8a008480-38c3-11eb-9171-1e9883b29eab.png)

In the **_localizationService.GetResource("Admin.StockQuantityHistory.Messages.PlaceOrder")** method application tried to get a value from database and eventually an exception occured. Because we are lacking of transactional architecture **Order** and one of the **OrderItem** inserted then that exception occured and **MoveShoppingCartItemsToOrderItems** method couldn't finished it's work. Also, the records has been saved to the database remained. This is a big inconsistency problem. Is there any way to convert PlaceOrder method to a fully transaction based architecture. It seems it is very critical. 

Cheers

**Comment by AndreiMaz** [comment]
According to the stack this error is not related to nopCommerce. It's somehow related to the SQL server - "an error occured during the login process" (SQL Server, not nopCommerce)
