### ISSUE TITLE
Add a reference to our premium support services to the system log pages

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5213]
Let's add the following information (hint) to the top of these two pages:
1. Admin area > system > Log
2. Admin area > system > View log entry details

"Have questions or need help? Get dedicated support from the nopCommerce team with a guaranteed response within 24 hours. Please find more about our premium support services here."

And "here" will point to:
1. The log list page - https://www.nopcommerce.com/nopcommerce-premium-support-services?utm_source=admin-panel&utm_medium=menu&utm_campaign=premium_support&utm_content=log-list
2. 1. The log ddetails page - https://www.nopcommerce.com/nopcommerce-premium-support-services?utm_source=admin-panel&utm_medium=menu&utm_campaign=premium_support&utm_content=log-details

**Comment by badijm** [comment]
Hi, I can work on that

**Comment by AndreiMaz** [comment]
@badijm Thanks a lot! Sure, please submit a pull request
