### ISSUE TITLE
Update sample data in  the default theme

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5214]
Currently some sample data is outdated. The use of way outdated items in the demo products & categories give the impression that the product is outdated

We update have to it, make it more modern

**Comment by iammourya** [comment]
I think the nop-template pavilion theme should be the one that should be adopted by the nopcommerce team as the default theme. Enough refinements are done on nop-template team that it would take many years to reach to the same level of "WOW" factor. I'm sure nopcommerce team can work out a deal with nop-template team.

**Comment by sajasbana** [comment]
Hi 
It will be also great if admin template can be customizable like public store so will can be admin themes in market also

**Comment by goransipic** [comment]
Will new theme have support for Bootstrap. Or it will be vanilla CSS. @AndreiMaz

**Comment by cabbage89** [comment]
I think this is an option  ,  https://github.com/cabbage89/Nop.Plugin.Administration.ProAdminUI.Doc

**Comment by glhays** [comment]
Is this available on the official nopcommerce marketplace?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HarunKilic** [comment]
It would be awesome with more modern frontend like Blazor or React/Vue/Angular.

**Comment by nathanfranke** [comment]
Dark theme when the browser requests it?

**Comment by MeysamNaderi** [comment]
The base theme of NopCommerce should prioritize clean design, simple and easily editable code, an enjoyable user experience and SEO optimization. Hence, there's no need for the WOW theme. My recommendation is to create a new theme using a framework like Bootstrap, which will feature a clean and adaptable UI, and utilize AJAX for all functionalities, adaptive (& responsive) design with lower JS/CSS/HTML code.
