### ISSUE TITLE
More user-friendly CMS capabilities

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5215]
Allow it edit the content without knowledge of HTML. It's not just about topics. It's about blocks of some entire pages such as the home page or catalog pages.

**Comment by untiedshoes** [comment]
How about integrating something similar to GrapesJS, or something along the lines of Umbraco's grid editor or the new block editor?

I managed to get an api working with Umbraco8, which passed back the full JSON for the grid editor, which I then deserialized, and used that as the layout for topics.

**Comment by compito** [comment]
Hi, if you are looking for a better CMS functionality, check the Piranha, it could be a good solution. 
https://github.com/PiranhaCMS/piranha.core 
It can be used both as an integrated CMS or as a headless API.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/6876
