### ISSUE TITLE
New "Sales summary" report

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5216]
Let's add a new report to admin area > reports. It'll be the first report in this menu list. So it'll display total orders summary the following way:

Available filters:

The first column:
1. Start date	
2. End date	
3. Order status
4. Payment status	

The second column:
5. Category
6. Manufacturer	
7. Billing country
All of them will be the same as currently available at /Admin/Report/Bestsellers
8. Product. The same one as currently available at /Admin/Order/List

One more field below will be the "Group by" dropdownlist. This one is actually not a filter. It'll have three options. "Day" (the default one), "Week", "Month".

When the "Search" button is clicked, then we'll display the following results in the grid (columns):

1. Summary. When the "Group by" is set to "Day" it'll display a list of dates for a selected period (start/end date). For example, "Nov 8th, 2020", "Nov 7th, 2020", etc. When the "Group by" is set to "Week",  it'll display a list of weeks (e.g. "December 7th, 2020 - December 12th, 2020", etc). . When the "Group by" is set to "Month",  it'll display a list of months (e.g. "December 2020", "November 2020, etc). 
2. Number of orders. For example, 5
3. Profit - similar to the "Summary" block at the orders page. For example, $1444.00
4. Shipping - similar to the "Summary" block at the orders page 
5. Tax - similar to the "Summary" block at the orders page 
6. Order total - similar to the "Summary" block at the orders page

**Comment by DmitriyKulagin** [comment]
Closed #5216
