### ISSUE TITLE
sitemap.xml file should not be a localizable URL (do not include a language code to URL when you have multiple languages)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5217]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Create two languages (e.g. /en/ and /ru/)
2. Open www.store.com/sitemap.xml. It'll redirect to www.store.com/en/sitemap.xml
3. Actually www.store.com/en/sitemap.xml and www.store.com/ru/sitemap.xml will be the same
4. There is no need to localize this URL. We can have only the default one - www.store.com/sitemap.xml because it already includes all alternative (localized) URLs of all web pages of website

**Comment by exileDev** [comment]
Closed #5217
