### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Avalara.AvaTax.netstandard11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by hassantarique** [nopSolutions/nopCommerce#5220]
nopCommerce version: 4.3.0

Steps to reproduce the problem: 
1-> Downloaded the source code from nopcommerce site
2-> added to GITHUB repo
3-> Created a new APP Service in Azure
4-> Configured CI/CD from Azure->deployment center to point to GITHUB Repo.. choosed .NET CORE 3.1 as technology stack
5-> Pushed the code to GITHUB Repo from my local GIT
6-> Deployment workflow initiated at GITHUB
7-> Deployment successful
8-> and we get this error .....

any help is appreciated.

Many Thanks

**Comment by hassantarique** [comment]
May be, It is related to this issue.. somehow..not sure..

https://github.com/avadev/AvaTax-REST-V2-DotNet-SDK/issues/133

**Comment by RomanovM** [comment]
There is nothing to do on our side
