### ISSUE TITLE
Cache issues with pickup points

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5222]
Trying to add, edit or delete the pickup points. It is reflecting in database table but not in grid of pickup points.

Getting the changed data once I clear the cache.

Source: https://www.nopcommerce.com/en/boards/topic/89565/cache-issues-in-pickup-points

**Comment by RomanovM** [comment]
Duplicate https://github.com/nopSolutions/nopCommerce/issues/5156
