### ISSUE TITLE
Redirect customer to homepage once store is opened again

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5227]
nopCommerce version: 4.30

> Can we add setting which redirect customer to home page once store is opened again ? because if customer try to refresh same page then he/she will remain stuck on same page.
> 
> But while reloading store closed page if we check if store is open now then we redirect customer to homepage. From developer point of view is not required that much but store owner would like if this feature implemented in future versions.
> 
> I might affect website reputation.

Source: https://www.nopcommerce.com/boards/topic/89615/redirect-customer-to-homepage-once-store-is-opened-again

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
