### ISSUE TITLE
Ensure page size is greater 0 when creating PagedList

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5228]
nopCommerce version: 4.30

> Running 4.3 I am still getting this same error :
> DivideByZeroException: Attempted to divide by zero.
> Nop.Core.PagedList<T>..ctor(IEnumerable<T> source, int pageIndex, int pageSize, int totalCount) in PagedList.cs, line 66

We already added this check for 3.80, but then removed it in [this commit](https://github.com/nopSolutions/nopCommerce/commit/9ae006ce#diff-aa955c1214e5bbbc43341c86561caa3108bbc51ffb930467405771de9b8adc2bL48).
Perhaps we should force use 1 as the page size in such cases, or still throw exception?

Source: https://www.nopcommerce.com/boards/topic/40451/pagedlistcs-division-by-zero#278669

**Comment by s3500659** [comment]
Hi,

I'm a university student from Australia studying a Bachelor of IT and would like to contribute to my first opensource project. I have found this issue and would like to work on it, do you think this is easy for me to do? How can I recreate this problem so I can fix it?
