### ISSUE TITLE
Issue in Admin-->Setting--> CustomerUser page

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#5229]
nopCommerce version: 4.40

Steps to reproduce the problem:If you navigate in Admin-->Setting--> CustomerUser page and you enable the usernames you get an misaligned form-group as you can see in the picture.
![image](https://user-images.githubusercontent.com/58636259/102352659-147a6f80-3fb9-11eb-83f5-c6d5c8ef966b.png)

the div is missing the class="form-group row advanced-setting"

**Comment by RomanovM** [comment]
@Lymperis79  I cannot reproduce this problem on the last develop, seems all is ok with alignment. Try to clear browser cache and check it again.

**Comment by Lymperis79** [comment]
I did already but i checked again! I checked in both edge and chrome. 
I have the same effect! and it extents when i tick to extent more as you can see in the picture!

![image](https://user-images.githubusercontent.com/58636259/102380517-10f6e080-3fd9-11eb-887d-9edd7ee5b1cc.png)

 i noticed also an other effect! If you make the window smaller i am losing complete the lines between the boxes as you can see in the picture bellow
class="form-group row advanced-setting"

**Comment by Lymperis79** [comment]
Sorry the second screen is not showing
![image](https://user-images.githubusercontent.com/58636259/102380800-6cc16980-3fd9-11eb-9cc0-f42ca4b94b76.png)

**Comment by DmitriyKulagin** [comment]
Closed #5229
