### ISSUE TITLE
Main-sidebar covering content in small browser window and no access of main-sidebar in mobile views

### ISSUE THREAD

**Issue by Lymperis79** [nopSolutions/nopCommerce#5230]
nopCommerce version:  v4.40

Steps to reproduce the problem: If you open the main-sidebar is not hiding when the size of the browser is small and it is covering the content of the page and in the mobile view or really small window when it disappears you have no access in the main-sidebar as you can see in the picture.

![image](https://user-images.githubusercontent.com/58636259/102353880-c5353e80-3fba-11eb-8202-eb8f3b81037b.png)

**Comment by RomanovM** [comment]
@Lymperis79 You are right, thanks. We have already noticed of this, as well as a group more minor design bugs of the updated admin area, we will fix them closer to the release.
