### ISSUE TITLE
CMYK color mode images color is getting changing after upload.

### ISSUE THREAD

**Issue by princeprasad90** [nopSolutions/nopCommerce#5231]
nopCommerce Version: 4.30

CMYK color mode images color is getting changing after upload. I have tried setting the Default image quality to 100, but still, the same issue persists.

Steps to reproduce the problem: 

Upload the attached image as the product image.

[https://ibb.co/wWRhLM4](https://ibb.co/wWRhLM4)

![image](https://user-images.githubusercontent.com/18004095/102358237-b6558880-3fc8-11eb-8f58-68360f99ac16.png)

**Comment by RomanovM** [comment]
Yep, CMYK mode [is not supported](https://github.com/SixLabors/ImageSharp/issues/1238) by the ImageSharp library which we use for image processing. 
We don't plan to implement it and leave it for customization.
