### ISSUE TITLE
Order Details page (admin area). Display prices in customer currency

### ISSUE THREAD

**Issue by iwhp** [nopSolutions/nopCommerce#5233]
nopCommerce version: 4.30

Proposal: 

I was in need to show on the **Order Details** page, in the **Info** section, beside the prices in the site currency, also the prices in the customer currency. I came up with this (it is not yet complete):

![Screenshot 2020-12-17 194008](https://user-images.githubusercontent.com/1591872/102529065-b1173d00-409f-11eb-8876-1a9db15da7ab.jpg)

Is this something for a pull requests?

Thankx, Harry

**Comment by AndreiMaz** [comment]
@iwhp Thanks a lot! Here is the existing work item - https://github.com/nopSolutions/nopCommerce/issues/4303

Please feel free to create a PR. Thanks again!
