### ISSUE TITLE
Shipping & Returns cannot be turned off in footer

### ISSUE THREAD

**Issue by V4A001** [nopSolutions/nopCommerce#5234]
nopCommerce version: 4.4

Steps to reproduce the problem: 
Shipping & Returns cannot be turned off in footer

Or I do not see where to turn it off.

**Comment by RomanovM** [comment]
@V4A001 Check topics with this name, they have property "Include in footer", just disable it.
Please post such questions on [our forums](https://www.nopcommerce.com/boards), we use GitHub only as an issue tracker.
