### ISSUE TITLE
Enhance Admin Order List, do not include cancelled orders

### ISSUE THREAD

**Issue by iwhp** [nopSolutions/nopCommerce#5237]
nopCommerce version: v4.30

Feature request: 

I'd like to have a search criteria on Admin/Order/List to **include cancelled** orders or **not**.
All other criteria would still work, but if the cancelled order criteria is set to **not show**, cancelled orders would not be shown.
Otherwise cancelled orders would be shown, as we know it today.

UI:

**Include cancelled orders:** **true** vs. **false**

I could implement this feature.

Thankx, Harry

**Comment by AndreiMaz** [comment]
You can already filter by "cancelled" order status on the order list page

**Comment by iwhp** [comment]
Thankx I know that. But what I cannot do is, give all records which are delivered, but not the cancelled one.
Or is that possible?
