### ISSUE TITLE
Nop 4.30 have too many Redis Scan Command.

### ISSUE THREAD

**Issue by fehmianac** [nopSolutions/nopCommerce#5238]
nopCommerce version:
4.30
Steps to reproduce the problem: 
When some settings changed, Nop Commerce have Too many requested Redis scan command.  Some themes are updating settings while all home page request. It's effected web site performance. I think cache clean strategy should be refactor.  Specifically while using redis.

![Screenshot at Dec 20 13-08-53](https://user-images.githubusercontent.com/9279620/102710701-32034e00-42c5-11eb-8a20-d5046a6803bd.png)

**Comment by skoshelev** [comment]
Closed #5238 (by [this ticket](https://github.com/nopSolutions/nopCommerce/issues/4699))
