### ISSUE TITLE
Export/Import with localized content

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#524]
When we have two or more languages, we should support multilanguage data (export/import to Excel/XML).
 
Examples: SEO for product is exported only for standart variation - not for localized content... And other localized field of database too... (Product description ..., Category localized columns...) ... ... ... 

See also: https://www.nopcommerce.com/boards/t/55469/when-we-have-two-or-more-languages-we-should-support-multilanguage-data-exportimport-to-excelxml.aspx

**Comment by tigran-avdalyan** [comment]
its very important function

**Comment by AhmedVolcano** [comment]
This feature won't be in near future?

**Comment by AmerBakeer** [comment]
I wish this could be done in the near future.

**Comment by ecommerce-tester** [comment]
https://www.codeproject.com/Articles/1194712/Advanced-Excels-With-EPPlus

**Comment by jac69** [comment]
How do you have a multilingual platform and no multilingual import? A language code column in the import excel will be enough to make it work.
Best
Jose

**Comment by BlagoCuljak** [comment]
Hello, I was using ImportManager.GetPropertiesByExcelCells in my plugin, and on upgrade to 4.6 I see it's missing. 

What can I use instead of GetPropertiesByExcelCells to get my plugin working?

**Comment by skoshelev** [comment]
Hi, @BlagoCuljak. Please ask all your question on the our [forum](https://www.nopcommerce.com/boards). I do not quite understand why you have this question since you found this ticket. The logic you are looking for is now in the ImportManager.GetWorkbookMetadata method
