### ISSUE TITLE
Add more widget zones in public store (e.g. for Shopping Cart, Wishlist, etc)

### ISSUE THREAD

**Issue by LucStr** [nopSolutions/nopCommerce#5241]
nopCommerce version: 4.3

Steps to reproduce the problem: 
On the shopping cart view, there are no widgetzones. Specifically I am talking about this View:

https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/ShoppingCart/Cart.cshtml

I would like to inject some scripts on this site. I can do this with my own theme, but I think it would be beneficial, if it were added to nopCommerce itself.

best regards Luca

**Comment by LucStr** [comment]
Same goes for the wishlist https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/ShoppingCart/Cart.cshtml

**Comment by LucStr** [comment]
Same would be for login and register page

**Comment by LucStr** [comment]
As well as the Not Found Page. Is it intended, that every page contains widgetzones or what is the philosophy behind it? Are they gradually added, as they are needed?

**Comment by RomanovM** [comment]
Hi @LucStr 

> Is it intended, that every page contains widgetzones or what is the philosophy behind it? Are they gradually added, as they are needed?

Second one. See for example #787 or #3577. 
Just suggest the widget zones you are missing, we'll consider adding them.

**Comment by RomanovM** [comment]
Add widget zones in _OrderReviewData

**Comment by DmitriyKulagin** [comment]
Closed #5241

**Comment by SelectSystemsInternational** [comment]
I added some widget Zones for Topic - I reused the ContactUs ones so I did not need to change code to add new ones - but it would be good if there was some new Zones specific for TopicDetails.cshtml

<div class="page topic-page" id="ph-topic">
    @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.ContactUsTop, additionalData = Model })
    <div class="page-title" id="ph-title">
        <h1>@Model.Title</h1>
    </div>
    <div class="page-body">
        @Html.Raw(Model.Body)
    </div>
    @await Component.InvokeAsync("Widget", new { widgetZone = PublicWidgetZones.ContactUsBottom, additionalData = Model })
</div>
<script>

**Comment by SelectSystemsInternational** [comment]
I produce an Afterpay.com Payment Plugin and recently Afterpay have been requested that their **Product Page Widget** be placed straight underneath the Price. Currently there is no widget in that location which means Clients who want to use the plugin have to manual adjust ProductTemplate.Simple.cshtml and relocate the PublicWidgetZones.ProductDetailsOverviewBottom up to this location to get the website approved by Afterpay

To same a lot of hastle It would be great if you can an a new Widget Zone PublicWidgetZones.ProductDetailsUnderPrice 

See the Image showing where the “afterpay-product-widget-container” is inserted when he PublicWidgetZones.ProductDetailsOverviewBottom is relocated 
![Afterpay](https://user-images.githubusercontent.com/34350154/202633997-467186fe-0d3f-4467-92d3-07d2203233a8.png)

**Comment by skoshelev** [comment]
Closed #5241
