### ISSUE TITLE
Culture does not change according to the chosen language

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5242]
nopCommerce version: 4.40 develop

Steps to reproduce the problem: 
![image](https://user-images.githubusercontent.com/27218280/102992459-4a28d680-452c-11eb-89c6-63aa89c3631e.png)

Start your investigation here to understand the problem:
https://github.com/nopSolutions/nopCommerce/blob/c7d7193b4bf0c0150d2535ad21c35923e74290f8/src/Presentation/Nop.Web.Framework/Globalization/CultureMiddleware.cs#L56-L59

**Comment by sefacan** [comment]
IRequestCultureProvider can solve this problem.

**Comment by DmitriyKulagin** [comment]
Closed #5242
