### ISSUE TITLE
Discount doesn't work properly in shopping cart

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5246]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Add some product to the cart
2. Go to the cart
![image](https://user-images.githubusercontent.com/37818094/103097276-d7952500-4617-11eb-8937-7f97c5d3adf8.png)

**Comment by RomanovM** [comment]
Actually discounts are not applied, the problem is only in the display them incorrectly.

**Comment by holydk** [comment]
#5246 Closed
