### ISSUE TITLE
Inventory Transactions

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#525]
I would like to adjust inventory with transactions. The only way to currently adjust inventory is to just change the quantity being tracked. It would be useful to have a form for adjusting inventory so that things can be tracked. I envision this form having a positive or negative adjustment field as well as a reason field (reasons would be managed similar to product specifications) and a notes field. It would also be great for ACL to be set on this. 

For example, if I have a product and it's being adjusted a lot because of it's damaged, that would be a good indicator I need to discontinue the product.

**Comment by AndreiMaz** [comment]
duplicated
