### ISSUE TITLE
Order CustomValuesXml

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#5250]
nopCommerce version: All

Regards the attribute order.CustomValuesXml
On the Customer Order Details page, the decoded values are associated with and displayed under the Billing Address heading
In the Order PDF the values are displayed separately under the Payment Method Details 
In Admin Order Details the Custom Values are displayed separately under the Payment Method details 

I use order.CustomValuesXml for storing details about the payment either:
The Payment Method type (in the case where there are multiple payment types for the one payment method)
For other payment methods order.CustomValuesXml is used to store a Payment Receipt number 
I dont know how others may use it ?

I also do not know if there is a reason why order.CustomValuesXml are associated with the Billing Address on the Customer Order Details page ?
This attribute is more likely to be used to store information about the order rather than details related to the billing address.

I would like to recommend that the display of the order.CustomValuesXml be moved on the Customer Order Details page to under the Payment Details so that it is standardised in all three locations.

**Comment by SelectSystemsInternational** [comment]
Any more thoughts on this change ?

**Comment by RomanovM** [comment]
See also #3304

**Comment by SelectSystemsInternational** [comment]
Suggestion that there is now a case to add a Type or DIsplay Location field and make it a Tuple <DisplayLocation, Key, Value>
So that the values can be linked to and displayed in the most approporaite location under either:
1. BillingAddress - Billing Address related customer values
2. ShippingAddress - Shipping Address related customer values
3. Payment - For values associated with Payment i.e. Receipt number of Invoice Number
4. Shipping - For values associated with Shipping i.e. Pickup Point

In a new Shipping plugin the Service Location for pickup of the order package with associated details as well as a customer Reciept Number - The details are now displayed under Payment but would be better if displayed under shipping
![image](https://github.com/nopSolutions/nopCommerce/assets/34350154/20b6c5ae-867b-442d-b076-d3146d7301da)
