### ISSUE TITLE
Object reference not set error in dependency registration method for data settings

### ISSUE THREAD

**Issue by bijeshbala** [nopSolutions/nopCommerce#5252]
nopCommerce version: 4.3

Steps to reproduce the problem: 
Error come up while running nop.web the development branch

Parent call stack is dependency registration in nop.web.framework. The call goes to data provider manager in nop.data and the method is get data provider

**Comment by RomanovM** [comment]
The last develop branch works like a charm. Check your data settings.

**Comment by mi-sohel** [comment]
@RomanovM  when I am trying to do a fresh install then it got the following error  ==>
https://localhost:44333/install

An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Nop.Data.DataProviderManager.get_DataProvider() in DataProviderManager.cs, line 41

DependencyResolutionException: An exception was thrown while activating Nop.Web.Framework.Mvc.Routing.SlugRouteTransformer -> Nop.Services.Localization.LanguageService -> Nop.Data.EntityRepository`1[[Nop.Core.Domain.Localization.Language, Nop.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null]] -> λ:Nop.Data.INopDataProvider.
Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action<ResolveRequestContext> next)

Stack Query Cookies Headers Routing

**Comment by mi-sohel** [comment]
![image](https://user-images.githubusercontent.com/18647404/103288231-a39e7300-4a0e-11eb-9a2b-69c660c0c251.png)
@RomanovM  added an image it might help.

**Comment by RomanovM** [comment]
@mi-sohel Well, I see now. Thanks for the details.

**Comment by mi-sohel** [comment]
@RomanovM  you are most welcome.
