### ISSUE TITLE
Trim values of some inputs when binding model

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5253]
nopCommerce version: develop

This can be useful for example on search, when extra spaces are removed from the search term, etc.

Previously, we forcedly used `.Trim()` in our [custom model binder](https://github.com/nopSolutions/nopCommerce/commit/59c7fc04958f52cebda0be1b0b4870c7f6eb0505#diff-c61493506ddee573adb6fdefd895cf3c5223eea7c199dce53832a4362def1617L72), with the [updating to .NET 5](https://github.com/nopSolutions/nopCommerce/issues/4268) this approach no longer works. 
Should we look for another way do it or just leave the model values as they come?

[UPDATE] Decided to trim it only when searching in public store. In all other places let's have the default behavior of ASP.NET Core 5 (no trim)

**Comment by DmitriyKulagin** [comment]
Closed #5253
