### ISSUE TITLE
Rethink the need to use a lock in schedule tasks or change it to semaphore

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5256]
nopCommerce version: develop

In continuation of #2287

Or vice-versa think about overall using ILocker instead of mutex and semaphore constructions.

**Comment by skoshelev** [comment]
See also https://github.com/nopSolutions/nopCommerce/issues/3859

**Comment by skoshelev** [comment]
for 4.40 the task is not relevant, now the ILocker interface is used

Closed #5256
