### ISSUE TITLE
The value is out of range. Maximum value is 99999999999999.99 in Product Edit Page

### ISSUE THREAD

**Issue by roboter** [nopSolutions/nopCommerce#5258]
nopCommerce version: github master

Steps to reproduce the problem: 
after editing product (change name for example) 
product cannot be saved
price was 1 euro

![image](https://user-images.githubusercontent.com/386485/103373754-75886400-4ade-11eb-92dd-b879a5e19086.png)

**Comment by roboter** [comment]
Issue is in `KendoCulture`

**Comment by DmitriyKulagin** [comment]
Depends on #5242

**Comment by RinkuChoudhary226** [comment]
I also having the same issue like  "The value is out of range. Maximum value is 0.99" in nopcommerce in decimal field
Please help

**Comment by RinkuChoudhary226** [comment]
> Issue is in `KendoCulture`

then what we can do  for that?

**Comment by wangyiwu** [comment]
Pls Im facing this issue on 4.60
