### ISSUE TITLE
Design issue on admin __ConfigurePlugin layout

### ISSUE THREAD

**Issue by shivaaysoft** [nopSolutions/nopCommerce#5263]
nopCommerce Version: 4.30

Steps to reproduce the problem: 
https://admin-demo.nopcommerce.com/Admin/WidgetsNivoSlider/Configure
open url > select any store > but not all store
![image](https://user-images.githubusercontent.com/69075835/103618015-3b431a80-4f55-11eb-9971-ed03be903e0b.png)

**Comment by RomanovM** [comment]
@shivaaysoft  Thanks. Already reported #4871. We just forgot to update this on our demo, we'll fix it soon.
