### ISSUE TITLE
A way to set currency for a first time visitor

### ISSUE THREAD

**Issue by iwhp** [nopSolutions/nopCommerce#5267]
**Business Case**

A store owner may have the following setup:

Languages: English, Deutsch
Currency: US$, BRITISH POUND, EURO

As one can see, we only have one language English, but two "corresponding" currencies US$ or BRITISH POUND.
For a language we can define a default currency, either we use US$ or BRITISH POUND for the English language, and EURO for the German language.

When a visitor with a German browser visits our web site, NopCommerce is capable to set the language to German and the currency to EURO.

If a visitor with a US-English browser visits our web site, NopCommerce uses the default currency defined in the English language, this maybe either US$ or BRITISH POUND. 

So there may be a issue for certain visitors.
NopCommerce at the moment may not handle this situation as expected.
We could define a second language for either British English or US English, but the we have to duplicate the translations.

**Suggested Solution:**

Define a new language and set its default currency, do not publish the language, so no translations are needed.

Change the code in Nop.Web.Framework.WebWorkContext.cs as follow:

````
public virtual Currency WorkingCurrency
{
   // ...
   //check customer currency availability
   var customerCurrency = allStoreCurrencies.FirstOrDefault(currency => currency.Id == customerCurrencyId);

   //it not found, then try to get the default currency for the current language (if specified)
    if (customerCurrency == null)
    {
      // First try to get with languages from the HTTP request
      var requestLanguages = _httpContextAccessor.HttpContext.Request.GetTypedHeaders().AcceptLanguage?.OrderByDescending(x => x.Quality ?? 1).Select(x => x.Value.ToString()).ToArray() ?? Array.Empty<string>();

      foreach (var requestLanguageCd in requestLanguages)
      {
         // Also check languages which are not published, but have a default currency defined
         var requestLanguage = _languageService.GetAllLanguages(true).FirstOrDefault(language =>
         language.LanguageCulture.Equals(requestLanguageCd, StringComparison.InvariantCultureIgnoreCase));

         if (requestLanguage != null)
         {
            customerCurrency = allStoreCurrencies.FirstOrDefault(currency => currency.Id == requestLanguage.DefaultCurrencyId);
            if (customerCurrency != null)
            {
               break;
            }
         }
      }

      // If not assigned, try to get it with the working language
      if (customerCurrency == null)
         customerCurrency = allStoreCurrencies.FirstOrDefault(currency => currency.Id == WorkingLanguage.DefaultCurrencyId);
   }
   // ...
}
````

Instead of using the the HTTP request culture (_httpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>()?.RequestCulture), I suggest to use **_httpContextAccessor.HttpContext.Request.GetTypedHeaders().AcceptLanguage**, so the languages defined in the browser are used (this could also considered for **WorkingLanguage.Get**)

The above code is working on our side and I am happy to provide a pull request if this "solution" is accepted by the community.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But this code with two English languages (a published one and unpublished) looks like a workaround. That's why we'll leave it for customization
