### ISSUE TITLE
Plugin Ressources not loaded, backend and frontend

### ISSUE THREAD

**Issue by maerlynflagg** [nopSolutions/nopCommerce#5271]
nopCommerce version: 

Steps to reproduce the problem: 

- install nopcommerce 4.3
- install german language pack

now, there are two "issues"...

first, in the backend, an all places , where plugin.XXXXX ressources is used, is the ressource key as value, so a normal user like the shop owner hasn't fun. looks like:

```
Plugins.Payment.CheckMoneyOrder.ShippableProductRequired
Plugins.Payment.CheckMoneyOrder.AdditionalFeePercentag
Plugins.Payments.PayPalSmartPaymentButtons.Fields.LogoInFooter

```
additionally some keys are so long, they go out of visibility.

the second think i found in the frontend and i'm not found a configuration way for normal user to customize it.
so in frontend are the keys under the payment buttons displayed:

```
plugins.payment.checkmoneyorder.paymentmethoddescription
plugins.payments.paypalsmartpaymentbuttons.paymentmethoddescription
```

**Comment by AndreiMaz** [comment]
It means that you actually haven't install the language pack

**Comment by maerlynflagg** [comment]
the backend says, the german translation pack, is installed. 
Translation pack is downloaded from there: https://www.nopcommerce.com/de/translations

alle text is translated except all thinks, which begins with "plugins.".

so, it looks like a bug, not like there is nothing installed.

**Comment by AndreiMaz** [comment]
Language packs don't include resources for plugins. What I can suggest is to:
1. Import the English language pack first
2. Import the German language pack after it

It should work fine
