### ISSUE TITLE
Duplicate Orders for Vendors in the Order search

### ISSUE THREAD

**Issue by DennisVerhoevenDC** [nopSolutions/nopCommerce#5274]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Create a vendor in nopCommerce 4.30
2. Create an order containing 2 seperate products from this vendor
3. Go to the Order overview section in the nopCommerce backoffice
4. Witness the order occuring twice in the Order overview

This issue relates to the query where the orderitem/vendor table join not being distinct and thus returning multiple instances of the same order on the query. Found in OrderService on line 220 to 225 in the statement that left joins the OrderItem table and the Vendor table on the query.

**Comment by mardev-code** [comment]
this Bug is already fixed look this link
https://github.com/nopSolutions/nopCommerce/issues/4989

Commit: https://github.com/nopSolutions/nopCommerce/commit/e402482ac6b8fca0ccdeddba8d7dc5235b526f8a
