### ISSUE TITLE
Configurable defaults

### ISSUE THREAD

**Issue by gkennedy1** [nopSolutions/nopCommerce#5277]
nopCommerce version: 4.3

Steps to reproduce the problem: 

- Add a new product
- Some product settings default to hardcoded values

For background see [https://www.nopcommerce.com/en/boards/topic/89872/configurable-defaults](https://www.nopcommerce.com/en/boards/topic/89872/configurable-defaults)

**Comment by RomanovM** [comment]
@gkennedy1 You can use "Copy product" feature for this, for example create a dummy product with common set properties and then copy it for real products.  
BTW, how do you suggest to implement configurable defaults from a UI perspective?

**Comment by gkennedy1** [comment]
@RomanovM "Copy product" is not a bad workaround but still requires us to train the admin users not to use the "Add New" button.
I think the UI would make sense to be a section in the Catalog Settings.

**Comment by RomanovM** [comment]
@gkennedy1 But the product entity includes about 100 properties, if default values will become editable for all of them, this section in the catalog settings will greatly bloat and become inconvenient to use, don't you think so?

**Comment by gkennedy1** [comment]
hmm... maybe. Another thought I had was a popup like the Settings dialog for showing/hiding fields on the basic mode window but I think it is more intuitive in the settings.

**Comment by RomanovM** [comment]
@gkennedy1 Thanks for your suggestion.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
