### ISSUE TITLE
Checkout Attribute by Percent

### ISSUE THREAD

**Issue by LuvForAirplanes** [nopSolutions/nopCommerce#5280]
For example, we offer software. We also offer Software as a Service. After they've purchased the keys for the software, at checkout we need to give them the option to host the software with us on our servers. This will add 40% to the cost of the software. How is this achieved?

**Comment by LuvForAirplanes** [comment]
@AndreiMaz Like when do you expect this to get done if it does? Are there other community members that could help me through doing this correctly in nopCommerce? (I'm kinda new to open-source contributing)

**Comment by AndreiMaz** [comment]
@LuvForAirplanes Thanks for suggestion. But currently we don't plan to implement that (at least in the near 12 months).

If you're interest in custom development, then please feel free to contact one of our solution partners - https://www.nopcommerce.com/partners or ask our community at https://www.nopcommerce.com/boards/forum/21/commercial-help-wanted

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
