### ISSUE TITLE
[FEATURE REQUEST] CSS minification for virtual folders

### ISSUE THREAD

**Issue by vubiz-am** [nopSolutions/nopCommerce#5281]
nopCommerce version: ALL

Steps to reproduce the problem: 
![image](https://user-images.githubusercontent.com/54327114/104932361-89a0e200-5975-11eb-842c-5dceea8e13f5.png)

Is it possible to make virtual folder support for CSS minification?

**Comment by AndreiMaz** [comment]
Thanks. But it duplicates https://github.com/nopSolutions/nopCommerce/issues/2674
