### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5282]
nopCommerce version: develop

At now TLS 1.2 support is enabled on [entire application](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs#L56). 
Some third-party services are step by step moving to TLS 1.3. Some difficulties with SMTP clients are also possible.
Is it time time to upgrade to TLS 1.3?

See also: #1871
https://www.nopcommerce.com/en/boards/topic/89848/email-account-tls-connection-problem

**Comment by DmitriyKulagin** [comment]
Closed #5282
