### ISSUE TITLE
Add more order tokens for message templates

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5283]
nopCommerce version: 4.30

> it would be possible to add new tokens to the template for complete the order with information about the total price of the order, something like %Order.Total% and %Order.Currency%? This data is missing between the tokens, it could be used, for example, to generate a QR code for a bank transfer via an external API.

Source: https://www.nopcommerce.com/boards/topic/89996/order-total-token-in-the-order-confirmation-template
See also: https://github.com/nopSolutions/nopCommerce/issues/2161

**Comment by davemacblack** [comment]
More tokens to personalize the template for complete the order would be very beneficial.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
