### ISSUE TITLE
Check using of IgnoreAntiforgeryToken and AutoValidateAntiforgeryToken attributes

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5288]
nopCommerce version: develop

> I'm aware what the [IgnoreAntiforgeryToken] attribute does but I'm little confused of its usage in the NopCommerce source code:
> 
> 1. There are controllers which are decorated with the [AutoValidateAntiforgeryToken] attribute but their GET methods (not decorated with the [HttpPost] attribute) are marked with the [IgnoreAntiforgeryToken]. Such an example is the CheckoutController.cs. As the documentation stated the [AutoValidateAntiforgeryToken] does skip GET methods and it is not checking the antiforgery token, so then why using the [IgnoreAntiforgeryToken] on such methods?
> 
> 2. There are controllers decorated with the [AutoValidateAntiforgeryToken] and some of their methods are decorated with  the [IgnoreAntiforgeryToken]. Maybe to allow accessing this methods without an active login session or something else?
> 
> 3. There are controllers not decorated with the [AutoValidateAntiforgeryToken] but only single methods in those controllers are decorated with this attribute. Such an example is PrivateMessagesController.cs

Let's check using of out anti-forgery attributes, whether they correctly set everywhere.

Source: https://www.nopcommerce.com/en/boards/topic/89920/whats-the-point-of-ignoreantiforgerytoken-attribute

**Comment by DmitriyKulagin** [comment]
We cannot completely opt-out of using the `[IgnoreAntiforgeryToken]` attribute. Methods calling _fineUploader_ cannot be without this attribute, because the call takes place in a third-party library.
