### ISSUE TITLE
Don't immediately hide the text of admin hints after moving the cursor

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5289]
nopCommerce version: develop

At now we display hints on hovering over the tooltip icon and hide it after moving the cursor, so it's impossible to copy the hint text or follow the link inside. 
We could keep the hint while the cursor is over the text, and not just over the icon or display and leave the hint on click on the icon.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
