### ISSUE TITLE
Remove duplicate of ISO 3166 file

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5293]
nopCommerce version: develop

Currently we have ISO3166 class with countries info [in the plugin](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Misc.SendinBlue/Domain/ISO3166.cs) and it doubles the [file in the core](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Installation/ISO3166.cs).
Let's check other plugins as well.

**Comment by DmitriyKulagin** [comment]
Plugin [FraudLabs Pro](https://github.com/nopSolutions/fraudlabs-pro-plugin-for-nopcommerce/blob/8835294e68c61b1106b290dce08d9f90a39c84fd/Nop.Plugin.Misc.FraudLabsPro/Services/ISO3166.cs)

**Comment by DmitriyKulagin** [comment]
See #5121
