### ISSUE TITLE
Use await using for IAsyncDisposable objects (streams, connections, etc)

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5294]
nopCommerce version: develop

For example [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/DataProviders/MsSqlDataProvider.cs#L119) we could use
`await using var connection = GetInternalDbConnection(await GetCurrentConnectionStringAsync());`
since the `DbConnection` implements the `IAsyncDisposable`.
Let's check through the whole project.

**Comment by skoshelev** [comment]
Closed #5294
