### ISSUE TITLE
Find an alternative for Roxy fileman 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5295]
nopCommerce version: develop

Since it's impossible to connect Roxy_fileman by npm, we could find another third-party library (connected by npm) for it's functions.

See also: https://github.com/nopSolutions/nopCommerce/issues/5016

**Comment by hailua8xpro** [comment]
![Capture](https://user-images.githubusercontent.com/11335372/118921232-006cdc80-b962-11eb-89b2-1c9a04ee9dde.PNG)

I have two issues with Roxy fileman
The fist is it frequently crash or loadding very slow (i have > 100 images)
Second is it cannot display the thumbnail 
Please consider fix it on the next version of NopCommerce
Thanks team

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality

**Comment by AndreiMaz** [comment]
Also check https://github.com/Studio-42/elFinder
