### ISSUE TITLE
RTL version of AdminLte

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5296]
nopCommerce version: develop

At now we must manually add [RTL css styles](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/wwwroot/lib/adminLTE/css/adminlte-rtl.min.css) for AdminLte, while the library itself is connected via npm.
 What we can do with this?

See also: #5016

**Comment by MafdyAzer** [comment]
Till this moment there's no official RTL release from Bootstrap, As a result, there is no official AdminLTE RTL version.
But they -AdminLTE- scheduled adding RTL support to AdminLTE v4 as Bootstrap v5 comes with an official RTL support. 

Ref.:
-AdminLTE: https://github.com/ColorlibHQ/AdminLTE/issues/2236#issuecomment-698162674
-Bootstrap: https://github.com/twbs/bootstrap/issues/30918
-Bootstrap: https://github.com/twbs/bootstrap/pull/30980

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality. Works fine now
