### ISSUE TITLE
system role names should be singular

### ISSUE THREAD

**Issue by bo-bac** [nopSolutions/nopCommerce#5297]
nopCommerce version: 4.3 current

Steps to reproduce the problem: 
1 go to the Admin/CustomerRole/List
2 Names should be singular
![image](https://user-images.githubusercontent.com/4517566/105630751-9df04d80-5e53-11eb-89eb-b0d69d47a861.png)

**Comment by glhays** [comment]
Yes, I would agree only if there is only going to be one. I would be one of possibly many administrators, guests, or and moderators. Apples and oranges.
________________________________

**Comment by bo-bac** [comment]
role imho more likely about who you are but not from which group you are. so if you are a fruit, you must be an apple or an orange but definitely not the apples.
and of course it is not must to have but a kind of about good taste)

**Comment by glhays** [comment]
You make an excellent point! With good tastes. :)
________________________________

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
