### ISSUE TITLE
Ignore language code for some routes that should not be localizable 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5298]
nopCommerce version: develop

Just as it was done for the sitemap #5217. The list of such routes can be taken from the 4.20 (where they were registered as `MapRoute()` and not as `MapLocalizedRoute()`).

**Comment by exileDev** [comment]
Closed #5298 (by commit e0dcba5587a91ffdeb2d5f6dd78e4d922e76bae1)
