### ISSUE TITLE
Ability to add reward points when purchasing a certain product (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#53]
Major supermarkets used BONUS reward points to heavily promote particular products. I suggest introducing this feature into nop by enhancing the current reward point system 

PROPOSAL:  Allow admin to apply bonus reward points for specific items purchased 

BUT (and this is important because giving reward points can equal giving substantial discounts): for clarity, we would need to create a specific way to track this : it would be easy to lose track of the products for which we offered bonus points, so on this new reward point system page, I think it would be very useful to have a gridview listing all the products which have a 'bonus points' field with a value >0 

as a minimum, the grid view would need to list the following 

product VARIANT name : amount of bonus points : edit/view (link taking admin to product variant page) 

I envisage the new admin page to have two tabs - 

```
 1st tab - all the current reward point information
 2nd tab - the above gridview
```

you could implement this new system in various ways 

e.g. 

add new input field in product variant : 'bonus reward points' 
and manage in the same way as 'bulk edit products' with a built in search function, checkboxes etc - just replace 'price column' with a 'bonus points' column 

alternatively, a completely different approch would be to implement it like the current discount system is applied 
ie create a 'bonus points' sytem where admin would create a 'bonus point promotion type' and designate it either 'assigned to category' or 'assigned to product variant (sku)' and provide the amount of points to be added per item 
(personally, I think we would still need the above described gridview to view the items / categories which the bonus ponts were applied to) 

further, 
I think if we implemented this system then it would make sense to have an atomatic 'flag' appear on both the category listing + product page, highlighting the fact that x number of bonus points are associated with the product 

check the post for further comments: 
http://www.nopcommerce.com/boards/t/6943/move-reward-points-from-global-settings-into-promotions-and-make-following-enhancement.aspx

also see https://github.com/nopSolutions/nopCommerce/issues/1917

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
