### ISSUE TITLE
Review the use of events in the NewsLetterSubscription service

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5300]
nopCommerce version: develop

We moved the generic events publishing from services to the [repository](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/EntityRepository.cs), but for some reason left for the above [service](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Messages/NewsLetterSubscriptionService.cs).
We also have a separate [EmailSubscribedEvent](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Messages/EmailSubscribedEvent.cs) and [EmailUnsubscribedEvent](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Domain/Messages/EmailUnsubscribedEvent.cs) events for this.
This all leads to duplicate events and the impossibility of using them correctly in plugins. So, let's check and review using all of these events in the service.

Source: https://www.nopcommerce.com/en/boards/topic/90037/handleevententityinsertedeventnewslettersubscription-eventmessage-gets-called-twice

**Comment by skoshelev** [comment]
Closed #5300
