### ISSUE TITLE
current active item highlight in admin sidebar looks weak

### ISSUE THREAD

**Issue by bo-bac** [nopSolutions/nopCommerce#5303]
nopCommerce version: 4.3 current

Steps to reproduce the problem: 
1 go to admin area
2 select some settings page for instance  Configuration -> Settings -> Order settings

current active item highlight look weak
![image](https://user-images.githubusercontent.com/4517566/105747138-108f2500-5f49-11eb-9cfb-28848d311d26.png)

what about
![image](https://user-images.githubusercontent.com/4517566/105747209-2d2b5d00-5f49-11eb-8f36-2a7f1e0b0ebd.png)

PR #5302

**Comment by AndreiMaz** [comment]
Thanks. But we prefer our design

**Comment by bo-bac** [comment]
no probs. just would like to point out that it was not about 'design'. it's small UX improvement but you decide)
