### ISSUE TITLE
cant install with _Create sample data_ with Postgresql

### ISSUE THREAD

**Issue by codecubix** [nopSolutions/nopCommerce#5304]
nopCommerce version: 
4.30 (forked, develop branch)

Steps to reproduce the problem: 
TRIAL 1)

1. clone, restore and build and run develop branch
2. run install  with _Create sample data_ checkbox checked in installation page

WARNING MESSAGE:
Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader

**Postgres Logs:**
2021-01-26 05:12:59.159 PST [51806] admin@db3 ERROR:  type "citext" does not exist at character 63
2021-01-26 05:12:59.159 PST [51806] admin@db3 STATEMENT:  ALTER TABLE "public"."MigrationVersionInfo" ADD "Description" citext NULL

TRIAL 2 AFTER FIXING CITEXT with **CREATE EXTENSION citext;**)
run install again with _Create sample data_ checkbox checked in installation page:

WARNING MESSAGE:
Setup failed: The field 'Description' has a type currently unknown to Npgsql (OID 28619). You can retrieve it as a string by marking it as unknown, please see the FAQ.

**Postgres Logs:**
_no added logs_

**Machine:**
Ubuntu 20.04 LTS
dotnet --version 
5.0.102

Note: Installation succeeded after clicking button _Restart Installation_ but the installed app is without sample data

**Comment by exileDev** [comment]
I can't reproduce it. On Ubuntu Server (20.04 LTS) works well.
Closed #5304

**Comment by taymfriz** [comment]
after fixing citext, must delete/drop the MigrationVersionInfo table in the DB and reset up again.

**Comment by msavara** [comment]
I have same issue. Ubuntu 20.04, nginx 1.18, postgresql 12. .NET 5 and nothing else. Just this clean install 

https://i.imgur.com/Q4PowLT.png

**Comment by exileDev** [comment]
> I have same issue. Ubuntu 20.04, nginx 1.18, postgresql 12. .NET 5 and nothing else. Just this clean install
> ps : @exileDev i saw here couple of this same issues and you closed every opened issue.
> if you want. i can give you access into my server where it's happening.
> 
> https://i.imgur.com/Q4PowLT.png

@msavara Please try to delete the previously created database and start the installation process again. 
PS: Or you can drop the MigrationVersionInfo table as was suggested [here](https://github.com/nopSolutions/nopCommerce/issues/5588#issuecomment-815380915)

**Comment by ngtrian** [comment]
I checked that this error occurs when create the database manually before installation.

The installation is successful when pick option "Create database if it doesn't exist" to create the database automatically
