### ISSUE TITLE
NopEditorTagHelper not working with LocalizedEditor and HtmlPrefix

### ISSUE THREAD

**Issue by lukasoberhaensli** [nopSolutions/nopCommerce#5308]
nopCommerce version: 4.3

Steps to reproduce the problem: 
- Create a Localized Editor in a Partial View
- Pass the model with a Prefix in "ViewData.TemplateInfo.HtmlFieldPrefix"
- Prefix is ignored and Model can not be bound to controls of type NopEditorTagHelper 

The reason is because they are bound over ViewData Attributes in nop-editor. By the time the ViewData Entries are created, the prefix ist not there.
**Example:** 
ViewData Key = "Locales[0].DefaultTitle"
HtmlFieldPrefix = "SeoSettings"
Added ViewData = "Locales[0].DefaultTitle" but should be => "SeoSettings.Locales[0].DefaultTitle"

To fix this issue we added the prefix in the NopEditorTagHelper.
```
//generate editor
var pattern = $"{nameof(ILocalizedModel<object>.Locales)}" + @"(?=\[\w+\]\.)";

if (!_htmlHelper.ViewData.ContainsKey(For.Name) && Regex.IsMatch(For.Name, pattern))
{
    var prefix = _htmlHelper.ViewData.TemplateInfo.HtmlFieldPrefix;
    _htmlHelper.ViewData.Add(string.IsNullOrEmpty(prefix) ? For.Name : $"{prefix}.{For.Name}", For.Model);
}
```

**Comment by DmitriyKulagin** [comment]
Closed #5308
