### ISSUE TITLE
Update int quantity to decimal....

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#5314]
Hi,
       most of the customers we contact have a wordpress site.

When we try to offer Nop Commerce + NOP-TEMPLTES the first thing a customer tells us is that quantity is not decimal, while in wordress it is!

To sell some more Nop4.20 we had to modify the schema DB, Access Layer, Service layer, etc ...

The work itself is fast. Three days of work.

Unfortunately, after the change, many NopTemplates Plugins throw exceptions.

In Nop 4.40 Could you make the Quantity decimal?
The Nopsolutions team would do it in a minute!

Although units of measure are managed, our customers would prefer to write quantities with commas ...

We did it! These are tables and fields to edit,...

Please update int quantity to decimal.... we don't want to do it every release ... but above all we want to use NOP-TEMPLATES:

Table: [OrderItem] 
 	- [Quantity] 

Table: [Product]:   
	-	[StockQuantity] 
	-	MinStockQuantity
	-	NotifyAdminForQuantityBelow 
	-	OrderMinimumQuantity 
	-	OrderMaximumQuantity
 	  
Table:  [StockQuantity]  
	-	NotifyAdminForQuantityBelow
	   
	   
Table:  [ProductAttributeValue]:  
	-	[Quantity]  
	
Table:  [ProductWarehouseInventory]:   	
	-	[StockQuantity] 
	-	[ReservedQuantity]

Table:  [TierPrice]:  
	-	[Quantity]  
			
Table:  [ShipmentItem]:  
	-	[Quantity]  

Table:  [ShoppingCartItem]:  
	-	[Quantity]  

Table:  [StockQuantityHistory]: 
	-	[QuantityAdjustment]
	-	[StockQuantity]  

Table:  [Discount]:  
	-	[MaximumDiscountedQuantity]

Table:  [ReturnRequest]:  
	-	[Quantity]  

best regards

Luca

**Comment by brucedelponte** [comment]
That would be useful for me too.
Please consider it.

Bruno

**Comment by FabioV79** [comment]
Bad English, but a clear problem! :-)
Indeed it would be appropriate to resolve it.
Regards

**Comment by Horus76** [comment]
I confirm !!! many customers ask us the same thing.
We want to grow nopCommerce more and more!
Help us

**Comment by Horus76** [comment]
I confirm !!! many customers ask us the same thing.
We want to grow nopCommerce more and more!
Help us

**Comment by kiara9588** [comment]
Hi, yesterday I had a meeting with a client and he had the same problem.

**Comment by RomanovM** [comment]
Previously we decided not to implement this functionality out of the box and left it for customization (see #232). Perhaps it's worth discussing the implementing this feature again.

**Comment by vincent87-bernal** [comment]
Hi, I'm a food marketplace owner, my units of measure are kg and grams. It would be perfect!

**Comment by luc-cap** [comment]
Thanks Maksim,
         I am very happy that you are re-considering the thing.

I Now you have so many things to do, 
in particular I am impatiently waiting for your Google Authenticator plugin.

But I would like to say one thing:

70% of Italian users made of Sevenspikes plugins their first choice.
I don't know, in the world, what the percentage is.

At the same time in Italy there are many types of shops
suitable for a NopCommece version with decimal quantity:
        - SUPER MARKET
        - Industrial bakeries
        - Gourmet shops
        - Vegan outlets 
        - etc...

Decimal quntity should be a feature Out of the BOX .

This Because from the moment that the Customization
forbid the utilization o NOP-TEMPLATES Plugins , the deal is gone!.

I'd like to know sevenspikes' opinion ... regarding the feasibility of the changes.

Maybe someone of the team will write 

Thank you

have a nice day

**Comment by noptemplates** [comment]
@luc-cap 

If the nopCommerce team adds support for decimal quantity then of course we will also add it in our plugins.

**Comment by luc-cap** [comment]
Simply fantastic ! 
I hope that the status of this issue will be set soon to "functionality / feature".

Nop-templates ... you are great !

**Comment by viktoraskas** [comment]
I vote for decimal quantity too. For now using Prestashop but I wonder to migrate to Nop. One of problem is quantity.
May be it could be not decimal but  have fraction.
If we want decimals then field quantity (integer) have field fraction (integer) with value 1000.
Example : field Quantity value is 1000. Field Fraction have value 1000. we divide 1000/1000=1 so real quantity is 1.
But we can put tu car quantity 500/1000=0.5
Sorry for my English but I hope You understood me :)

**Comment by AndreiMaz** [comment]
Closing it and re-opening https://github.com/nopSolutions/nopCommerce/issues/232
