### ISSUE TITLE
Add a message that the user is already logged in when he opens the login page again

### ISSUE THREAD

**Issue by MafdyAzer** [nopSolutions/nopCommerce#5316]
nopCommerce version: 4.20, 4.30

Steps to reproduce the problem: 
- Log in to store, 
- Open the login url again in the same store.
- It will ask you to log in again.

If you open the store at login url, even if you logged in it will ask you to logged in, 
In version 4.2 it keeps refresh the login page without any error message but makes you believe that you cannot login, while the truth is that you already logged in.
In version 4.3 will ask you to logged in again, and then sometimes it's stuck in login page and sometimes redirect you to home.
 
Conclusion: 
What I believe is that if user logged in and he opens login url next time by mistakes, it should be redirect to Home or perhaps account page, to avoid such misunderstanding. 

![image](https://user-images.githubusercontent.com/57217759/106896118-d3215900-66f9-11eb-9f1e-99b011b4f1c8.png)

**Comment by RomanovM** [comment]
It's by design to allow user to login for another account without an intermediate logout, and also to link external authentication to the current account. 
Perhaps we should add some kind of message that the user is already logged in, if he visited the login page by mistake.

**Comment by MafdyAzer** [comment]
@RomanovM   You're right, I got it now,
I completely agree with your suggestion for a message to inform user if he already logged in, as it will avoid such misunderstanding, and I think highlighting such a great feature (login by another account without the need to logout) will be a huge add.

**Comment by purehaTime** [comment]
Done with 4.5 version
