### ISSUE TITLE
Homepage Categories not cached by store

### ISSUE THREAD

**Issue by severindheureuse** [nopSolutions/nopCommerce#5317]
nopCommerce version: 4.30

Steps to reproduce the problem: 
- Create 2 stores with a category which is restricted to a single store
- Set "Show on home page" on a category to true
- When viewing the different store home pages, eighter the category is showed on both stores or in none of them.

It looks like the home page categories are not separately cached for the stores in the `PrepareHomepageCategoryModels `method in the `CatalogModelFactory`. 
Adding the `_storeContext.CurrentStore.Id` to the cache key should fix this issue.

**Comment by skoshelev** [comment]
Closed #5317
