### ISSUE TITLE
If there are no tax categories created, the configuration page of the "Manual (Fixed or By Country/State/Zip)" method is not displayed

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5319]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Delete all tax categories
2. Go to the "Manual (Fixed or By Country/State/Zip)" configuration page
3. The page is not displayed, even the layout. It just shows "No tax categories can be loaded" on the white screen

It should display the layout and the plugin name at least

**Comment by skoshelev** [comment]
Closed #5319
