### ISSUE TITLE
Get  final price with and without discount in one pass

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5323]
nopCommerce version: develop

So, instead of 
```
var (minPossiblePriceWithoutDiscount, _, _) = await _priceCalculationService.GetFinalPriceAsync(product, await _workContext.GetCurrentCustomerAsync(), includeDiscounts: false);
var (minPossiblePriceWithDiscount, _, _) = await _priceCalculationService.GetFinalPriceAsync(product, await _workContext.GetCurrentCustomerAsync());
```
we could get something like 
`var (minPossiblePriceWithoutDiscount, minPossiblePriceWithDiscount, _, _) = await _priceCalculationService.GetFinalPriceAsync(product, await _workContext.GetCurrentCustomerAsync(), includeDiscounts: true);`

**Comment by skoshelev** [comment]
Closed #5323
