### ISSUE TITLE
NopTabsTagHelper  - You can no longer add a class attribute to a tab

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5325]
nopCommerce version: 4.40 develop

Found an issue in the NopTabsTagHelper class. You can no longer add a class attribute to a tab. The application returns an error InvalidOperationException: The collection already contains an entry with key 'class'.
That's due to the fact that you've added the followin line in the NopTabsTagHelper.cs line 263:
tabTitle.AddCssClass("nav-item");

and after that on line 284 you do this:
            if (context.AllAttributes.ContainsName("class"))
                tabTitle.Attributes.Add("class", context.AllAttributes["class"].Value.ToString());

However, there is already a class key in the dictionary which results in the error mentioned above.

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/2#280810

**Comment by DmitriyKulagin** [comment]
Closed #5325
