### ISSUE TITLE
Typo in src/Presentation/Nop.Web.Framework/Infrastructure/AuthorizationSatrtup.cs

### ISSUE THREAD

**Issue by celer1tas** [nopSolutions/nopCommerce#5327]
nopCommerce version: 4.4.0 - develop

Steps to reproduce the problem: 
Typo in src/Presentation/Nop.Web.Framework/Infrastructure/AuthorizationSatrtup.cs

I assume that AuthorizationSatrtup.cs should be AuthorizationStartup.cs

**Comment by DmitriyKulagin** [comment]
Closed #5327
