### ISSUE TITLE
Plugins not shown in local plugins list due to JS error if the language is not English

### ISSUE THREAD

**Issue by deckbsd** [nopSolutions/nopCommerce#5328]
nopCommerce version: 4.30

Steps to reproduce the problem: 
In the admin panel
- Change the language to French
- Go to Configuration / Local plugins
- The list wont be displayed
- If you change the language to English, it works.

Here is the javascript error :

`Uncaught ReferenceError: renderColumnDescription is not defined`

**Comment by RomanovM** [comment]
Duplicate #4847
