### ISSUE TITLE
Setup failed: Cannot access a disposed object. Object name: 'IServiceProvider'.

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5332]
nopCommerce version: 4.40 Development Branch

https://prnt.sc/z202su

Having error `Setup failed: Cannot access a disposed object. Object name: 'IServiceProvider'.` at installation time with current development branc. This was working fine with a day before code

**Comment by rajupaladiya** [comment]
![installation-error 1](https://user-images.githubusercontent.com/13154058/107611717-a1b10c00-6c6a-11eb-8c53-73a55a9a4be5.png)

**Comment by DmitriyKulagin** [comment]
@rajupaladiya I just tried the install on the current develop branch and everything worked without error. Try to clear the `bin` and `obj` folders in the solution and repeat the installation process
