### ISSUE TITLE
Stop using nvarchar(max) on indexable fields

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#5334]
nopCommerce version: 
4.20

There are a lot of fields in the database (we use SQL Server) that are nvarchar(max). Some of these fields we would benefit from putting an index over them. But the largest non-full-text-indexable nvarchar is 900.

One example of this is Order.CustomOrderNumber. My organization would benefit from an index on this field as customers, CSRs, admins, and our automated processes often search the Order table by CustomOrderNumber. But, since it is an nvarchar(max), we cannot create an index on it without altering the size of this column.

Here are some other columns on Order, for example, that could benefit from an index but are nvarchar(max):
PaymentMethodSystemName
CustomerIp
ShippingMethod

Not being able to index these columns limits the performance we can squeak out of the database. It also means Azure auto-tuning will not recommend/add indexes on these columns when it thinks it will help.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
