### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5336]
1. Change the string resource value from "Activity Types" to "Activity types" and check if other string resources from admin area have the same issue with capitalization
2. Don't capitalize names of shipping methods. Go to Shipping methods page. Do not capitalize names of shipping methods. There's no need to update existing stores, only the installation data

See the comment below

**Comment by bo-bac** [comment]
just 5¢ if you allow)
it is not an easy question about Capitalization in English. I know cases when there were two controversial directions 'what and how to capitalize' ordered by native speakers)

so IMHO the right solution for the mentioned problem do NOT try to fix place-to-place but to find out some kind of guideline written by reliable authority and agree to follow.

here is an example of such a guideline
https://docs.microsoft.com/en-us/style-guide/capitalization

**Comment by RomanovM** [comment]
We'll leave it for customization.
