### ISSUE TITLE
'Search' function is available even if turn it off in Catalog settings

### ISSUE THREAD

**Issue by bo-bac** [nopSolutions/nopCommerce#5337]
nopCommerce version: 4.3 and current

Steps to reproduce the problem: 

1. go to /Admin/Setting/Catalog
2. turn off 'Search enabled'
3. go to Home page
        act: 'Search' is visible in the Footer navigation
        exp: no 'Search' link in the Footer  navigation
4. follow the link /search 
        act: page is opened, function is available
        exp: 404 Page not found

**Comment by DmitriyKulagin** [comment]
@bo-bac Search link in footer is disabled by another setting: `Settings->General settings->Footer items`. I was unable to reproduce the 404 error on the latest version, it works correctly.

**Comment by bo-bac** [comment]
ok.
you are right 'Search' link in the footer can be hidden by Settings->General settings->Footer items

but lets think about 'Search' function.
if Site owner would like to remove this function from the site...
it must be she
1 go to /Admin/Setting/Catalog
2 turn off 'Search enabled' 

are you agree with she?
if yes. please go to http://nop here/search
do you see something like
![image](https://user-images.githubusercontent.com/4517566/109346382-468e3480-787a-11eb-86d2-572d30d7296e.png)

but it must be 404 cuz 'Search' function is disabled right?


more over. please look at https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Shared/Components/Footer/Default.cshtml

line 15 for example it id Sitemap
`@if (Model.SitemapEnabled && Model.DisplaySitemapFooterItem)`

there are two conditions: one for function another one for footer item

it seems the same should be for Search

what do you think?

**Comment by DmitriyKulagin** [comment]
@bo-bac Yes, it makes sense. If search is disabled, then the link for it should not be in the footer.

**Comment by DmitriyKulagin** [comment]
Closed #5337

**Comment by bo-bac** [comment]
thank you @DmitriyKulagin
