### ISSUE TITLE
Filter by specs doesn't work properly

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5341]
nopCommerce version: 4.40

See also #85
Expected (4.30 version):
![image](https://user-images.githubusercontent.com/37818094/108071202-8123f000-7076-11eb-8392-aefb57de3721.png)

Actual (4.40 verison):
![image](https://user-images.githubusercontent.com/37818094/108071346-ae709e00-7076-11eb-9b2e-5ca4d8dcbb81.png)

**Comment by exileDev** [comment]
Closed #5341
