### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#5342]
nopCommerce version:
    develop

Steps to reproduce the problem: 
    1. run on linux docker
    2. complete installaction with sample data
    3. click 'personalize your store' on panel 'Welcome to your store!'
    
Exception:

`Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.

 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory

   at SkiaSharp.SkiaApi.sk_version_get_milestone()

   at SkiaSharp.SkiaSharpVersion.get_Native()

   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)

   at SkiaSharp.SKObject..cctor()

   --- End of inner exception stack trace ---

   at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)

   at SkiaSharp.SKObject.set_Handle(IntPtr value)

   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)

   at SkiaSharp.SKObject.Dispose(Boolean disposing)

   at SkiaSharp.SKFileStream.Dispose(Boolean disposing)

   at SkiaSharp.SKNativeObject.Finalize()`

**Comment by chensiel** [comment]
I have tried this [https://github.com/mono/SkiaSharp/issues/1341#issuecomment-660584994](url)

Still has the some exception

**Comment by chensiel** [comment]
Works on ubuntu based docker container.
I changed the Dockerfile:

FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS runtime 
RUN apt-get update
RUN apt-get install -y libicu-dev fontconfig-config
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN apt-get install -y libgdiplus linux-libc-dev

**Comment by exileDev** [comment]
@chensiel Thanks! We didn't change the Dockerfile yet. Since in the project, too many commits every day. 
We'll check it before the 4.40 release.

**Comment by last-Programmer** [comment]
When will be the official docker hub image updated with this fix?.

Unable to use the docker hub image in linux docker.

Please update the docker hub image.

thanks

**Comment by petrsoudek** [comment]
> When will be the official docker hub image updated with this fix?.
> 
> Unable to use the docker hub image in linux docker.
> 
> Please update the docker hub image.
> 
> thanks

I am waiting too

**Comment by skoshelev** [comment]
Hi @last-Programmer and @petrsoudek We fixed the docker hub image you may try it now
