### ISSUE TITLE
Test case fail when have multiple theme in store

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5343]
nopCommerce version: 4.40

Steps to reproduce the problem: 
Add new theme in store 
Run test case
it'll fail test case  `CanPrepareStoreThemeSelectorModel` because it checking theme should be 1
it must be    `model.AvailableStoreThemes.Count.Should().BeGreaterThan(1);`

https://github.com/nopSolutions/nopCommerce/blob/5f022f5570d4c8f7f268a5c0f34b6cd4f3a4d889/src/Tests/Nop.Tests/Nop.Web.Tests/Public/Factories/CommonModelFactoryTests.cs#L274

![image](https://user-images.githubusercontent.com/13154058/108333486-ffa79b80-71f6-11eb-8b7e-28d824ef62e2.png)

**Comment by skoshelev** [comment]
Closed #5343
