### ISSUE TITLE
hostingModel="InProcess" in web.config

### ISSUE THREAD

**Issue by YipingRuan** [nopSolutions/nopCommerce#5346]
nopCommerce version: 
develop

Steps to reproduce the problem: 
A tiny issue.
Clone the repo and open solution in Visual Studio 2019

![image](https://user-images.githubusercontent.com/5492274/108352971-8aea5680-7222-11eb-998b-7fcc849bc4cf.png)
![image](https://user-images.githubusercontent.com/5492274/108353047-a2c1da80-7222-11eb-9d29-ea0ed76eeb39.png)

**Comment by RomanovM** [comment]
@YipingRuan Do you mean just a capitalization of this string?

**Comment by YipingRuan** [comment]
@RomanovM  From the intellisense and warning, it should be "inprocess" ?

**Comment by RomanovM** [comment]
@YipingRuan We don't edit this value manually, it's auto inserted from the [project properties](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Nop.Web.csproj#L16), and the value exactly with such capitalization (see [docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0#enable-in-process-hosting)). I don't think there is an actual problem with this other than a warning in the VS. We can just ignore it.
