### ISSUE TITLE
Consider a possibility to generate "toggle" js-functions for nested settings in the appropriate tag helper instead of doing this manually

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5347]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Now we do this manually on each page 
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Recurring.cshtml#L10

**Comment by DmitriyKulagin** [comment]
Closed #5347
