### ISSUE TITLE
SalesSummaryList "year" column doesn't exist postgresql

### ISSUE THREAD

**Issue by sefacan** [nopSolutions/nopCommerce#5348]
nopCommerce version: 4.40(develop branch)

Steps to reproduce the problem: 
Install nopCommerce with PostgreSQL Provider
Go to Admin Area > Reports > SalesSummaryList

You will see "year" column doesn't exist error.

**Comment by exileDev** [comment]
Closed #5348

**Comment by skoshelev** [comment]
Closed #5348
