### ISSUE TITLE
Extend EstimateShippingModel

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5349]
nopCommerce version: develop

Add the new parameter in the model EstimateShippingModel

```public string City{ get; set; }```

DHL and other parcel services doesn't use ZipPostalCode for many countries (only City)
and It's better to add parameters "Hide City", "Hide ZipPostalCode " for EstimateShipping widget

Source: https://www.nopcommerce.com/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/3#281153

**Comment by holydk** [comment]
Closed #5349
