### ISSUE TITLE
Add a CSS Editor Section to Nop

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#535]
Just like how Nop Templates' themes all come with a Custom CSS entry area. It'd be nice, especially now that Nop Templates made the new default them (and hopefully continues to! :D), to just modify the 'vanilla Nop' without the need to go into the /Themes/DefaultClean/Content/CSS folder and modify the CSS file directly. 

...it's really a pain to have to edit, upload, refresh, edit again, upload, refresh, 'repeat till happy'. 

((I've made a bunch of CSS entries into Nop Templates theme and I'm pretty sure I'll have to go and incorporate those changes into each individual plugin.)) 

So, ya, however Nop Templates does it...can we get that in the stock version of Nop 

Source: http://www.nopcommerce.com/boards/t/39318/suggestion-add-a-css-editor-section-to-nop.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
