### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by loverdeveloper** [nopSolutions/nopCommerce#5350]
Hi, I can't build my project with docker, I getting this error
OS: Linux Arch
Steps to reproduce the problem: 
``
docker-compose up
``
Then:
```
nopcommerce             | It was not possible to find any compatible framework version
nopcommerce             | The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
nopcommerce             |   - The following frameworks were found:
nopcommerce             |       5.0.3 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
nopcommerce             | 
nopcommerce             | You can resolve the problem by installing the specified framework and/or SDK.
nopcommerce             | 
nopcommerce             | The specified framework can be found at:
nopcommerce             |   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=alpine.3.13-x64
```

Plus I try this:
`
docker pull mcr.microsoft.com/dotnet/core/sdk:3.1
`

I think the problem is related to versions because when I try to get 3.1.0 by this `docker pull mcr.microsoft.com/dotnet/core/sdk:3.1.0` it doesn't working. I guess it's related to `.0`, it shouldn't be there

**Comment by skoshelev** [comment]
Can't reproduce on the latest source codes

Closed #5350
