### ISSUE TITLE
Rename the AddLocaleResourceAsync method from LocalizationMigration to AddOrUpdateLocaleResourceAsync as it updates resources as well

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5351]
nopCommerce version: 4.30

**Comment by skoshelev** [comment]
Closed #5351

**Comment by untiedshoes** [comment]
@skoshelev 

You have some extra spacing in many places in this fix:

e.g.
await _localizationService.AddOrUpdateLocaleResourceAsync (new Dictionary<string, string>

should be

await _localizationService.AddOrUpdateLocaleResourceAsync(new Dictionary<string, string>

**Comment by skoshelev** [comment]
Closed #5351
