### ISSUE TITLE
4.40 Product - Estimate shipping pop up

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5352]
nopCommerce version: 4.40

Steps to reproduce the problem: On a product page, when you click the 'estimate shipping' popup, trying to close it with the x in the corner does not close the modal. All it does is shift the X to the bottom left, which if you click that, does close the modal.

Clicking the 'body' closes the modal as expected.

Also - download 4.40 zip, build and publish does not build and publish plugins.

**Comment by RomanovM** [comment]
Duplicate #5244

As of the publishing, I just tested it and all is fine here, plugins are in.

**Comment by untiedshoes** [comment]
Sorry, but for me, they don't build. Using VisualStudio 16.8.4
![Screen Shot 2021-02-21 at 11 28 41](https://user-images.githubusercontent.com/12123259/108623672-1ab51e00-7438-11eb-81c1-5c24b450c709.png)
![Screen Shot 2021-02-21 at 11 30 23](https://user-images.githubusercontent.com/12123259/108623691-37e9ec80-7438-11eb-97da-4a14ab917c20.png)
