### ISSUE TITLE
Error on Install Docker Latest Version with MySql

### ISSUE THREAD

**Issue by trindium** [nopSolutions/nopCommerce#5354]
nopCommerce version: latest

Steps to reproduce the problem: 

In a new install in docker with nopCommerce latest and mysql.

During the install when the Database is being created. Get an error on screen:

Setup failed: Table 'AddressAttribute' already exists
This is the log on the container:

>  FluentMigrator.Runner.Processors.MySql.MySql5Processor[1003]
> 2/20/2021 1:11:18 PM      ALTER TABLE `Discount_AppliedToProducts` ADD CONSTRAINT `FK_93CBDED2C39FEA8DC8E0DDD9F6CDA0BB3009BBE2` FOREIGN KEY (`Product_Id`) REFERENCES `Product` (`Id`) ON DELETE CASCADE
> 2/20/2021 1:11:19 PMinfo: FluentMigrator.Runner.MigrationRunner[1004]
> 2/20/2021 1:11:19 PM      CreateTable AddressAttribute
> 2/20/2021 1:11:19 PMinfo: FluentMigrator.Runner.Processors.MySql.MySql5Processor[1003]
> 2/20/2021 1:11:19 PM      CREATE TABLE `AddressAttribute` (`Id` INTEGER NOT NULL AUTO_INCREMENT, `Name` NVARCHAR(400) NOT NULL, `IsRequired` TINYINT(1) NOT NULL, `AttributeControlTypeId` INTEGER NOT NULL, `DisplayOrder` INTEGER NOT NULL, CONSTRAINT `PK_AddressAttribute` PRIMARY KEY (`Id`)) ENGINE = INNODB
> 2/20/2021 1:11:19 PMfail: FluentMigrator.Runner.MigrationRunner[0]
> 2/20/2021 1:11:19 PM      Table 'AddressAttribute' already exists
> 2/20/2021 1:11:19 PMMySql.Data.MySqlClient.MySqlException (0x80004005): Table 'AddressAttribute' already exists
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
> 2/20/2021 1:11:19 PM   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
> 2/20/2021 1:11:19 PM   at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Process(String sql)
> 2/20/2021 1:11:19 PM   at FluentMigrator.Runner.StopWatch.Time(Action action)
> 2/20/2021 1:11:19 PM   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
> 2/20/2021 1:11:19 PMinfo: FluentMigrator.Runner.Processors.MySql.MySql5Processor[1004]
> 2/20/2021 1:11:19 PM      Rolling back transaction
> 2/20/2021 1:11:19 PMinfo: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
> 2/20/2021 1:11:19 PM      Executing ViewResult, running view Index.
> 2/20/2021 1:11:19 PMinfo: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
> 2/20/2021 1:11:19 PM      Executed ViewResult - view Index executed in 34.013ms.

The Install DB scripts continues, but the UI gives that error.

![image](https://user-images.githubusercontent.com/165527/108602010-7f13a700-737e-11eb-9097-3eb66fe11fa7.png)

**Comment by trindium** [comment]
This does not happen using mssql

**Comment by exileDev** [comment]
Can't reproduce. 
Ubuntu 20.04 LTS, Docker 20.10, Mysql 8.0.23
