### ISSUE TITLE
Cannot remove a product from wishlist

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5356]
nopCommerce version: 4.40 beta

Continuation of https://github.com/nopSolutions/nopCommerce/issues/4343. There's no way to remove products from wishlist. It should work the same way as for the cart

![image](https://user-images.githubusercontent.com/5019111/108670944-c7eb6d00-74f0-11eb-9f97-bed42f11416a.png)

**Comment by holydk** [comment]
Closed #5356
