### ISSUE TITLE
Categories with the following names and/or IDs don't exist: Desktops etc while import product

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5357]
nopCommerce version: beta 4.40

Steps to reproduce the problem: 

1) Go /Admin/Product/List

2) Export to excel (All Found)

3) Import same file 

Following error occurred.

![image](https://user-images.githubusercontent.com/41533502/108673941-810a7100-750a-11eb-8aef-6aebc64d876d.png)

**Comment by skoshelev** [comment]
Closed #5357
