### ISSUE TITLE
Abnormal messages appeared - after order status update

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5358]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 

1) Go to /Admin/Order/Edit/1

2) Change Order status Processing to Completed and click save button order status is updated but it redirected same page with below messages

Also getting same issue when i update Order Totals

![image](https://user-images.githubusercontent.com/41533502/108674795-d6934d80-750b-11eb-9a0d-790738d0eea0.png)

**Comment by skoshelev** [comment]
Closed #5358
