### ISSUE TITLE
Country State Ajax loader is not stopped 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5359]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 

1) Register new customer

2) Add any product to cart

3) Do checkout while filling the billing address click on country dropdown and select country ajax loader is continues loading.

If state is filling based on country than also it is loading continuously.

![image](https://user-images.githubusercontent.com/41533502/108676031-9cc34680-750d-11eb-93b4-02288076bf31.png)

**Comment by holydk** [comment]
Closed #5359
