### ISSUE TITLE
Ensure products have unique SKU

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#536]
Some time ago I contributed by creating unique SKU plugin which would prevent from adding 2 same SKUs to your webshop. As I believe that by sharing we will get the most out of it I hereby give you the code to first plugin from upcoming series of plugins. 

source code is on github under link https://github.com/RafPe/nopcommerce-plugin-uniqueSku 

Source: http://www.nopcommerce.com/boards/t/39322/unique-sku-plugin-on-github.aspx and http://www.nopcommerce.com/p/1845/unique-sku.aspx

**Comment by AndreiMaz** [comment]
duplicated
