### ISSUE TITLE
Can't able to edit Product Attribute Predefine Value 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5360]
nopCommerce version: 4.40 beta 

Steps to reproduce the problem: 

1) Create new **master product attribute** from here : /Admin/ProductAttribute/Create

2)  Once it created open with Edit mode. and add any predefine attribute value.

3) One done , Edit same predefine value. 

pop up will appeared with different information. see the screenshot.

![image](https://user-images.githubusercontent.com/41533502/108677255-6d153e00-750f-11eb-9ae9-7f533d8fbbd5.png)

**Comment by skoshelev** [comment]
Closed #5360
