### ISSUE TITLE
License key is not with Avalara tax provider plugin configuration

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5361]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 

1) Go Plugins/Avalara/Configure

2) save required value , License key is not saved 

3) Every time when i save it will ask about license key require

**Comment by RomanovM** [comment]
Actually this is a bug with the address validation. Fixed in https://github.com/nopSolutions/nopCommerce/commit/0457aa8b09d3523b9fda6911882865df8f845b5a
