### ISSUE TITLE
Checkout page new Address State loader are not hide after select the country and getting console error

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5362]
nopCommerce version: 4.4 Beta

Steps to reproduce the problem: 
GO to Checkout page 
- Add new Address 
- select country and in state it getting issue loader are not hide and console getting issue 
as I have share screen shot 
https://prnt.sc/103jsgr

**Comment by RomanovM** [comment]
Thanks. Duplicate #5359
