### ISSUE TITLE
Trim code is missing at search by product tags / Product

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5363]
nopCommerce version: 4.40

Steps to reproduce the problem: 

1) /Admin/Product/ProductTags

2) on search panel search with below keyword.

**keyword 1** : awe
**keyword 2**:  awe[put 3 to 4 space after awe]  

Both should give same result.

same thing happened at /Admin/Product/List when I search by product name

**Comment by AndreiMaz** [comment]
Thanks. But we don't consider this as a bug. This is new default behaviour of .NET 5. We've implemented it for public store search only
