### ISSUE TITLE
Select country label are display twice in order edit address admin side 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5366]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Admin > Edit Order 
2. Click on Edit address 
3. Select country , in that it display 2 times select country

https://prnt.sc/103mwre

**Comment by RomanovM** [comment]
See also: #3444

**Comment by skoshelev** [comment]
Closed #5366
