### ISSUE TITLE
Select State label are display twice in order edit address admin side 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5367]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1. Admin > Edit Order 
2. Click on Edit address 
3. Select State , in that it display 2 times select country

NOTE : if not reproduce then just select United state and select any state and save 
and try again it will show twice

https://prnt.sc/103n5vi

**Comment by RomanovM** [comment]
See also: #3444

**Comment by skoshelev** [comment]
Closed #5367
