### ISSUE TITLE
Selected Other State on admin edit address click on save it will success but  it is not updated in DB 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5368]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Admin > Edit Order 
2. Click on Edit address 
3. Select in State  as "other", and click on save but it not reflected or updated 

https://prnt.sc/103n9t7

**Comment by skoshelev** [comment]
In this context, "Other" and "Select state" have the same meaning and should not save any values in the database. 

But we decided to leave only the "Other" value in this case.

Closed #5368
