### ISSUE TITLE
Manually Order status change from admin edit order getting issue as given in screen shoot 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5369]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Admin > Edit Order 
2. Click on Change Order status pending to processing
3. After changing getting issue of validation 
![screenshot-localhost_44388-2021 02 22-16_27_54](https://user-images.githubusercontent.com/27865278/108699770-b1163c00-752b-11eb-8eb6-20b76839d3f2.png)

**Comment by RomanovM** [comment]
Thanks. Duplicate #5358
