### ISSUE TITLE
Minor UI issue in admin area > Catalog setting

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5370]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
Go to admin > catalog setting and check '**Products by tag' page. Calculate price range automatically'**

**Comment by rajupaladiya** [comment]
![image](https://user-images.githubusercontent.com/13154058/108706077-1b32df00-7534-11eb-83da-19d12f59e82a.png)

same as for search setting

**Comment by mariannk** [comment]
Fixed in [this commit ](https://github.com/nopSolutions/nopCommerce/commit/5f59f24ec9bbc676c0a744fa78aa0df46b161ed6)
