### ISSUE TITLE
Add order note Attach file UI is not correct 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5375]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Admin > Edit Order 
2. Click on Add notes 
 
https://prnt.sc/103rf4x

**Comment by kalpeshboghara** [comment]
![image](https://user-images.githubusercontent.com/27865278/108956982-a330fa00-7696-11eb-9cc9-ecc142eb4a05.png)


Please check this as well

**Comment by kalpeshboghara** [comment]
Upload section width issue while check and uncheck upload download url checkbox in order details page Admin Section

**Comment by mariannk** [comment]
Fixed in [this](https://github.com/nopSolutions/nopCommerce/commit/e7351feffecce009c76ecd4fa565557d658ed40e) commit
