### ISSUE TITLE
Add order note Attach file UI click on Check box and save and download button is not properly UI Design 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5376]
nopCommerce version: 4.40 beta

Steps to reproduce the problem:
1. Admin > Edit Order 
2. Click on Add notes 
3. click on check box upload file button UI is not properly 
 
https://prnt.sc/103rg4b

**Comment by mariannk** [comment]
Fixed in [this](https://github.com/nopSolutions/nopCommerce/commit/e7351feffecce009c76ecd4fa565557d658ed40e) commit
