### ISSUE TITLE
Topic page form validation not working

### ISSUE THREAD

**Issue by sangeet-shah** [nopSolutions/nopCommerce#5377]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 

Go to Admin side > Topic > Add new topic

**Comment by RomanovM** [comment]
All is ok here, validation properly works.

**Comment by sangeetshah** [comment]
@RomanovM Can you please see my attachment? I have record the video that show validation not working.

![aa](https://user-images.githubusercontent.com/10364140/109009542-a8ad3500-76d4-11eb-80eb-997a065697c0.gif)

**Comment by RomanovM** [comment]
@sangeetshah I see, thanks. But what do you mean by "validation not working", what is expected?

**Comment by sangeetshah** [comment]
@RomanovM Alteast body is required to save the topic page. Without any detail what is meaning to create topic page.

**Comment by RomanovM** [comment]
@sangeetshah We have not foolproof, if admin wants to create a topic without a body just let him do it. The current behavior is exactly the same as in previous versions.

**Comment by sangeetshah** [comment]
@RomanovM I agree with you but no one can create topic page without title and body because its useless. Their is meaning less to create blank page. no one store owner want to create only blank page on their website.

Thanks for your reply.
