### ISSUE TITLE
Go directly to product SKU not working when Avlara tax provider enable as primary provider

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5378]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 

1) /Admin/Tax/Providers

2) Click on Mark as primary provider for this Avalara tax provider.

3) GO to /Admin/Product/List and check **Go directly to product SKU**

**Comment by RomanovM** [comment]
Same as #5373
