### ISSUE TITLE
UI is not properly Display on new vendor create screen / Admin side

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5379]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 

1) Go /Admin/Vendor/List

2) Click on Add new button

3) Check Current screen is basic mode or advance mode 

**If Basic Mode :** 

  A.  Click on it so it will display Advance Mode

than you will get below UI

![image](https://user-images.githubusercontent.com/41533502/108715911-7919f380-7541-11eb-9807-177cb78b964e.png)

**If Advance mode :-**

 enable Basic mode 

repeat steps 1 , 2, 3

Again that UI will appear.

**Note**  make sure when you open vendor create screen initially it will be open with basic mode

**Comment by RomanovM** [comment]
Thanks, actually it's the same error as in #5370
