### ISSUE TITLE
Add order note Attach file UI click on Check box and save and click download button show page not found error while in previous nopcommorce version its redirect to home page 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5380]
nopCommerce version: 4.40 beta

Steps to reproduce the problem:
1. Admin > Edit Order -> Add order note 
2. Click on Order notes  
3. click on Download show page not found error

https://prnt.sc/103rsht
https://prnt.sc/103rsuv

**Comment by RomanovM** [comment]
@kalpeshboghara  I cannot reproduce this. Please provide more detailed list of steps or record a small video with this problem.
