### ISSUE TITLE
UI is not properly Display on Edit Product Downloadable product tab / Admin side

### ISSUE THREAD

**Issue by Ilyaspatel91-del** [nopSolutions/nopCommerce#5383]
nopCommerce version: 

Steps to reproduce the problem: 
1. Go /Admin/Product/Edit
2. Go to Downloadable product click on Downloadable product
3. click on check box upload file button UI is not properly

https://prnt.sc/103y8cs

**Comment by RomanovM** [comment]
Thanks. Same as #5376
