### ISSUE TITLE
Admin Panel all the sub menu alignments are not proper

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5385]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Go to /Admin/Catalog/Attributes
2. Go to /Admin/Configuration/Settings
3. Go to /Admin/Configuration/Shipping
4. Go to /Admin/Configuration/Authentication
5. Go to /Admin/Reports/Customer reports

![Sub Menu Allignment](https://user-images.githubusercontent.com/75514919/108739312-88f20180-755a-11eb-92f0-a7a779f0fb58.png)

**Comment by HarshBhesawala** [comment]
@RomanovM  Should we consider this as bug?

**Comment by AndreiMaz** [comment]
@HarshBhesawala No, it's definitely not a bug. Just a minor improvement

**Comment by AndreiMaz** [comment]
Decided not to implemented as it's the default behavior of AdminLTE
