### ISSUE TITLE
In Category list page tooltip text is missing for compare and wishlist button

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5387]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Computers/Notebooks  =>  on compare & wishlist button there should be tooltip text like Add to compare list & Add to wishlist.

![Category List](https://user-images.githubusercontent.com/75514919/108742813-26026980-755e-11eb-8c6d-e259e25a4371.png)

**Comment by holydk** [comment]
Closed #5387

**Comment by HarshBhesawala** [comment]
Yes, I confirm.
you can pay amount to my email id harshbhensawala@gmail.com
