### ISSUE TITLE
Not receiving an email regarding link to reset password after password recovery

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5388]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Login => Forgot password
2. Enter email address & press recovery button.
3. Message will appear that  "Email with instructions has been sent to you."

Link for password recovery not sent.

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue. An email is queued at /Admin/QueuedEmail/List
