### ISSUE TITLE
Resource string value is missing at Google Authenticator page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5390]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
Goto https://localhost:44355/Admin/GoogleAuthenticator/Configure
Press save button without any data into both textbox and you get this resource string 

![image](https://user-images.githubusercontent.com/10364140/108798857-ce431d00-75b4-11eb-958b-02d3ac5f3027.png)

**Comment by skoshelev** [comment]
Closed #5390
