### ISSUE TITLE
Cant able to remove accessiBe Installation script textbox value

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5391]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 

Goto > /Plugins/AccessiBe/Configure
Enter the Installation script textbox value and now you can't remove this textbox value except plugin need to be set inactive.

I have added some value into this textbox
![image](https://user-images.githubusercontent.com/10364140/108799319-0565fe00-75b6-11eb-90fa-ca3ebec23527.png)

This textbox value shown at home page top side
![image](https://user-images.githubusercontent.com/10364140/108799328-0f87fc80-75b6-11eb-94bf-2ce11c3c8912.png)

Now i have to remove this dummy value but i cant do this except plugin need to be set inactive
![image](https://user-images.githubusercontent.com/10364140/108799340-16af0a80-75b6-11eb-9ca3-9481f0a1c96e.png)

**Comment by AndreiMaz** [comment]
@RomanovM Let's allow entering of empty values
