### ISSUE TITLE
Ajax loading not stopped after changes country on billing address of check out page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5392]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1) Go to onepage checkout page
2) In the billing address section and add new address then press submit button and  select country and then state and check ajax loader

![image](https://user-images.githubusercontent.com/10364140/108805208-8ed0fc80-75c5-11eb-86fe-beb40608561c.png)

**Comment by sangeetshah** [comment]
![image](https://user-images.githubusercontent.com/10364140/108958522-1dfb1480-7699-11eb-986d-0c8ff0195971.png)

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5359
