### ISSUE TITLE
Billing new address form value getting reset after going to next and come to this section again on one page check out page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5393]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 

1) Go to check out page and in the billing address section select new address and filled the detail 
2) Go to next section and come on billing address section again then you can see all form value getting blank or reset 

![image](https://user-images.githubusercontent.com/10364140/108958771-729e8f80-7699-11eb-9298-ef6e8d639d19.png)
![image](https://user-images.githubusercontent.com/10364140/108958788-7df1bb00-7699-11eb-890d-b724c3c91025.png)

**Comment by sangeetshah** [comment]
@RomanovM is this bug or not?

**Comment by exileDev** [comment]
Closed #5393
