### ISSUE TITLE
Name validation required for pickup point

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5394]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Shipping/Pickup points

Null values getting saved in the "name" field. Form validation required.

![Pickup Point](https://user-images.githubusercontent.com/75514919/108807201-c6da3e80-75c9-11eb-8c0e-a6ec62a7d700.png)

**Comment by RomanovM** [comment]
@DmitriyKulagin See also #5377, possible it's a generic error.

**Comment by DmitriyKulagin** [comment]
It's by design.

**Comment by HarshBhesawala** [comment]
@RomanovM @DmitriyKulagin  I agree with you but no one can create Pickup points without name because its useless.
 Their is meaning less to create pickup point without name. no one store owner want to create only blank named pickup point 
 on their website.

 Thanks for your reply.

**Comment by DmitriyKulagin** [comment]
@HarshBhesawala Since the absence of a name only affects the display at checkout, we will add the appropriate functionality so that the collection point is displayed without extra commas. Here is a [related work item](https://github.com/nopSolutions/nopCommerce/issues/5455).

**Comment by HarshBhesawala** [comment]
@DmitriyKulagin  Due to this bug you have find another bug on front side, i think that on admin side name should be required.

so can we count this as bug?
