### ISSUE TITLE
In Dashboard Start accepting orders Tab does not appear in mobile view

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5395]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Dashboard

Start accepting orders Tab does not appear in mobile view.

![Start accepting orders](https://user-images.githubusercontent.com/75514919/108815330-4839cd00-75da-11eb-8a7d-3a6835b0dd3a.png)

![Start accepting orders mobile view](https://user-images.githubusercontent.com/75514919/108815339-4cfe8100-75da-11eb-9ad7-9cd0ca7c980a.png)

**Comment by AndreiMaz** [comment]
It's by design (not required in mobile view)
