### ISSUE TITLE
UI Grid is not properly Display on ReturnRequest/List while click on Search collapse / Admin side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5396]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1. Admin > ReturnRequest -> List
2. Click on search collapse 
3. After click on collapse Return Request feature (RMA) design grid are changes 

https://prnt.sc/104kt2x

**Comment by AndreiMaz** [comment]
cannot reproduce the issue
