### ISSUE TITLE
All front side pages on focus button outline issues

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5397]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 

1) Open Inspect Element
2) Select button and add focus event

https://prnt.sc/104n8ho
https://prnt.sc/104nfsz
https://prnt.sc/104nh5l
https://prnt.sc/104nhs1

**Comment by RomanovM** [comment]
Thanks. It's by design, see #5022
