### ISSUE TITLE
specification Attribute group title should be align center below 1000px media screen

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5398]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 

Specification attribute group title is not aligned center below 1000px media screen. so we can do it using colspan as shown in second screenshot. 

https://prnt.sc/104o708
https://prnt.sc/104o7oj

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
