### ISSUE TITLE
Vendor Reviews (contribution and available as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#54]
Add Vendor Reviews (written for a vendor).

Or maybe have aggregated reviews, which will calculate the vendor review based on the reviews of its products. Also, in the vendor page, the list of reviews will be displayed, which will be created by aggregating the reviews from all the vendor products sorted by date.  

Contribution: http://nopcommerce.codeplex.com/SourceControl/network/forks/BinaryBrains/VendorReviews/contribution/8116

contribution (plugin): http://www.nopcommerce.com/p/2071/extended-vendor-ratings-source-code-included-roastedbytescom.aspx  and http://www.nopcommerce.com/boards/t/38639/vendor-reviews.aspx

plugins: http://www.nopcommerce.com/p/2358/vendor-rating.aspx

let's discuss it first

**Comment by sumit7034** [comment]
With reference to point no 5 in https://github.com/nopSolutions/nopCommerce/issues/101
I want to know 
How the feature for "Ability to display Vendors and Products based on the clients location" 
will be implemented?

Will it be based on google map longitute, Latitute?

**Comment by ayberkcal** [comment]
I think this will be very very good feature for competition with other projects. I suggest, reconsider this issue.
