### ISSUE TITLE
Newsletter subscription design issue in mobile screen

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5402]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 

Newsletter subscription input and button design is not properly in mobile screen below 375px media screen.

https://prnt.sc/104p5a2

**Comment by AndreiMaz** [comment]
it's by design. there's no way to fix (enhance) it for so small screens. 
P.S. It works fine on standard mobile devices (displayed in one single line)
