### ISSUE TITLE
No layout in product download page when user downloaded maximum time

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5403]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: Set maximum allow to download 0 or in downloadable product
try to download after reach it maximum time

it will display a message in the entire white screen  (Layout = null)
https://screencast-o-matic.com/watch/crn06dWQsN

![image](https://user-images.githubusercontent.com/13154058/108833800-5811db00-75f3-11eb-8eee-6d4046f0db84.png)

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
