### ISSUE TITLE
Video downloadable product

### ISSUE THREAD

**Issue by faransi10** [nopSolutions/nopCommerce#5404]
nopCommerce version: 4.4

Steps to reproduce the problem: 

Please add the feature to store video downloadable produce locally 
( the only option is to store in DataBase)
And you know when storing large video file in DataBase as blobs the loading time will be very big and you cant seek until the file fully loaded from DataBase)

**Comment by AndreiMaz** [comment]
Thanks for the suggestion. But we're leaving it for customization
