### ISSUE TITLE
Admin panel Products page grid design issue

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5405]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1.  Go to Admin/Products => Enter Product name and press search button
     -> Enter "comp" in Product name and select Category Electronics then press search button
          again select Category Computers then press search button
          now select Category Computers => Desktops result will show in improper design grid.
 
    Grid view design is not proper.

![Product List page](https://user-images.githubusercontent.com/75514919/108835598-b6d85400-75f5-11eb-9f15-51156da0ab86.png)

**Comment by DmitriyKulagin** [comment]
I could not reproduce according to the specified scenario, this behavior of the grid is possible only if the window size was changed through the developer tools in the browser, for example.

**Comment by HarshBhesawala** [comment]
I have reproduce this problem again and take vedio of this problem, please review the attached file.

![Admin product list](https://user-images.githubusercontent.com/75514919/109163160-0908a900-779f-11eb-9723-31b6edf3fc5a.gif)
