### ISSUE TITLE
Blog Comment is required , but it missing to display asterisk / Front side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5408]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 

1. Blogs > click on Blogs 
2. Click on new Blogs , it display error message , but it missing asterisk sign 
 ![image](https://user-images.githubusercontent.com/27865278/108837543-631b3a00-75f8-11eb-9ffd-fa8d628d9295.png)

**Comment by AndreiMaz** [comment]
it's by design. obviously, it's required
