### ISSUE TITLE
Admin dashboard top menu not display properly(Design issue)

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5409]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 

Go to admin side and open this dashboard page into mobile 

![image](https://user-images.githubusercontent.com/10364140/108837591-76c6a080-75f8-11eb-8981-6db9dcec4d73.png)

![image](https://user-images.githubusercontent.com/10364140/108983852-514b9c80-76b5-11eb-9243-43ddfdd81f71.png)

**Comment by AndreiMaz** [comment]
@DmitriyKulagin Also see https://github.com/nopSolutions/nopCommerce/issues/5417

**Comment by DmitriyKulagin** [comment]
Closed #5409
