### ISSUE TITLE
select input focus outline issue

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5411]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
In all page's inputs there are outline on focus, if its functionality. so, it should be also work for select. it working when double click on select.

https://prnt.sc/104q344

**Comment by mariannk** [comment]
@kalpeshboghara hi which browser do you use?

**Comment by AndreiMaz** [comment]
Works fine
