### ISSUE TITLE
Search panel textbox label coming right side instead of left into mobile view

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5413]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1. Go to admin side
2. Open product list page into mobile view and check the label of this filter search textbox

![image](https://user-images.githubusercontent.com/10364140/108838407-9b6f4800-75f9-11eb-8ed5-943827b3b3d3.png)

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5372
