### ISSUE TITLE
Sales summary report design issue in mobile view

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5414]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Report/Sales summary

Start date & end date allignment issue.

![Sales summary report](https://user-images.githubusercontent.com/75514919/108838862-3b2cd600-75fa-11eb-81e1-65f795880176.png)

**Comment by mariannk** [comment]
Fixed in [this commit](https://github.com/nopSolutions/nopCommerce/commit/254cbafbc7b0e8500d2b674c1f5297f509bb519c)
