### ISSUE TITLE
Add new address form country/state dropdown selection getting reset when press submit button into Billing address page at check out page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5415]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1) Go to one page check out
2) Select new address form from billing section
3) Select country and state only from this form
4) Press submit button. now you can see the country and state dropdown selection getting reset

Add new address form country/state dropdown selection getting reset when press submit button into Billing address page at check out page

![image](https://user-images.githubusercontent.com/10364140/108838994-75967300-75fa-11eb-85bf-255fb1fda650.png)

**Comment by RomanovM** [comment]
Same as #5393
