### ISSUE TITLE
UI Mobile Language wise responsive design issue into mobile view / Admin side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5417]
nopCommerce version: 

Steps to reproduce the problem: 
1. Go to Admin 
2. Dashboard make a responsive
3. Add multi language , Language are not display selected
![image](https://user-images.githubusercontent.com/27865278/108841321-944a3900-75fd-11eb-9e97-9357bc41f3d7.png)

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5409
