### ISSUE TITLE
My Account change password success notification not display  / Front side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5418]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1. Go to My Account  > Change Password 
2. Change password as per needed , but after success it should need to display proper success notification 
![image](https://user-images.githubusercontent.com/27865278/108841660-1e929d00-75fe-11eb-961f-62e9c9211602.png)

**Comment by holydk** [comment]
Closed #5418
