### ISSUE TITLE
Refactoring of some controller action methods

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#542]
In many cases it's possible and easy to extend standard functionality by implementing custom service but sometimes more flexibility is needed than that. 

For example extend viewmodel with additional properties (add some elements on the view) so it is needed to override controller action and i'd like you to take in considerations the following code issues:
avoid long methods such as PrepareShoppingCartModel in ShoppingCartController, could you try to split such methods on several protected virtual methods, instead of a long one method?
add empty protected virtual methods before returning a View for example:

```
public ActionResult Product(int productId, int updatecartitemid = 0) 
{ 
//.... 
var model = PrepareProductDetailsPageModel(product, updatecartitem, false);    

ProductDetailsModelPrepared(model,product, updatecartitem, false); 
//...
return View(model.ProductTemplateViewPath, model);
} 
```

ProductDetailsModelPrepared could be an empty protected virtual it will allow easier replace view model 
by inherited view model which is extended with additional properties.
1. sometimes you just forget to mark methods as virtual (PrepareProductDetailsPageModel is not marked as virtual)
2. I would prefer to see action methods like this:

```
public ActionResult Product(int productId, int updatecartitemid = 0) 
{
  return ProductAction(productId, )
} 

protected virtual ProductAction(int productId, int updatecartitemid = 0) 
{ 
//... 
} 
```

b/c sometimes you 've put in Views the following things: 

@Html.Action("FlyoutShoppingCart","ShoppingCartController",...) thus it requires override not only controller but also Views. 

Suggestions: http://www.nopcommerce.com/boards/t/37320/more-flexibility-and-extend-ability-for-nopcommerce.aspx

**Comment by AndreiMaz** [comment]
done with factories
