### ISSUE TITLE
UPS configure getting issue of Object reference not set to an instance of an object  / Admin side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5420]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1. Go to My Account  >Admin > Shipping >Providers
2. select UPS (United Parcel Service) and click on configure 
3. After click on configure it getting exception issue 

![image](https://user-images.githubusercontent.com/27865278/108844954-d033cd00-7602-11eb-914f-9acd5a80138d.png)

**Comment by RomanovM** [comment]
Not reproduced on a clean installation. 
@kalpeshboghara Please check it again and provide more details if this problem still exists.
