### ISSUE TITLE
ShipStation configure getting issue of resource string missing / Admin side

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#5421]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1. Go to My Account  >Admin > Shipping >Providers
2. select ShipStation and click on configure 
3. Resource string is missing

**Comment by kalpeshboghara** [comment]
it's work after reinstall,

**Comment by skoshelev** [comment]
Hi @kalpeshboghara, Did you use fresh install or upgrade from 4.30?

**Comment by skoshelev** [comment]
Moreover, these methods used to be public in the previous versions of nopCommerce so probably many nopCommerce developers are already using them in their custom plugins.
I will appreciate it if you reconsider this!

Closed #5421

**Comment by skoshelev** [comment]
I tried to reproduce the problem in both scenarios, when upgrading from 4.30 and when installing 4.40 cleanly. Everything works as expected, all locales are in place

Closed #5421
