### ISSUE TITLE
On checkout page billing address dropdawn design issue in mobile view

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5422]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
Go to Checkout/Billing Address  =>  Address dropdawn design issue in mobile view.

![Checkout page](https://user-images.githubusercontent.com/75514919/108846717-e5116000-7604-11eb-9f2a-de3de92151bc.png)

**Comment by AndreiMaz** [comment]
It works fine on real mobile devices (multiple lines)
