### ISSUE TITLE
mysql unicode issue

### ISSUE THREAD

**Issue by MRSheikh** [nopSolutions/nopCommerce#5423]
nopCommerce Version:  4.30

Steps to reproduce the problem: 
I installed nopcommerce on my host:
windows server 2016
mariadb : 10.5.8
MySQL collation : utf8

when I save some Unicode characters on the site content page, only ???? characters save into the MySQL table.

**Comment by exileDev** [comment]
I can't reproduce. It works fine. (MySQL defaults: Charset utf-8, utf8_general_ci)

Closed #5423

**Comment by MRSheikh** [comment]
I set `CharSet=utf8;` at end of the connection string and then that works fine !!!

`"DataConnectionString": "server=localhost;database=nop;allowuservariables=True;user id=****;password=****;CharSet=utf8;",`
