### ISSUE TITLE
MySqlException in catalog view

### ISSUE THREAD

**Issue by codegolem** [nopSolutions/nopCommerce#5425]
nopCommerce version: latest

Steps to reproduce the problem: 

install nopCommerce 4.4 beta using MySQL server (docker image: 8.0.21-1debian10), creating sample data.

Wait for installation to complete and restart.

Navigate to any product category.

The following error is shown:

MySqlException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'nop44.sa.DisplayOrder' which is not in SELECT list; this is incompatible with DISTINCT

(full error message in attachment)
[Internal Server Error.pdf](https://github.com/nopSolutions/nopCommerce/files/6030400/Internal.Server.Error.pdf)

**Comment by holydk** [comment]
Closed #5425

**Comment by codegolem** [comment]
Thank you for fixing! :)
