### ISSUE TITLE
Delete or rename specification attribute group option is missing

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5426]
nopCommerce version: Beta 4.40

Steps to reproduce the problem: 
There is no option for rename or delete specification attribute group (/Admin/SpecificationAttribute/List)
![image](https://user-images.githubusercontent.com/13154058/108883430-6da2f700-762b-11eb-966c-2a0f0fefd39f.png)

**Comment by AndreiMaz** [comment]
Actually, you can. 
P.S. "Default group (non-grouped specification attributes)" is not editable

**Comment by rajupaladiya** [comment]
Yeah got it.
Sorry, my bad :(
