### ISSUE TITLE
No icon for the "Plugins" menu item in the admin area

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5428]
nopCommerce version: 4.40 beta

On the admin menu, put an icon for "plugins". The other headers have a little icon, but not plugins
![image](https://user-images.githubusercontent.com/5019111/108951013-46bee200-7678-11eb-93a6-082146262b60.png)

Source: https://www.nopcommerce.com/en/boards/topic/90309/find-bugs-in-nopcommerce-440-beta-and-earn-10/page/2#281369

**Comment by DmitriyKulagin** [comment]
This functionality is not out of the box.

**Comment by Ochapparel** [comment]
Sorry, it's been driving me nuts. Just change the sitemap.config under admin area from:

`<siteMapNode SystemName="Third party plugins" nopResource="Admin.Plugins" IconClass="**far** fa-bars" />`

to

`<siteMapNode SystemName="Third party plugins" nopResource="Admin.Plugins" IconClass="**fas** fa-bars" />`

**Comment by RomanovM** [comment]
@Ochapparel Thanks.
