### ISSUE TITLE
Catalog pages. Display a user-friendly message when no products founds

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5429]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
Step 1: Click Computer/Desktop category.
Step 2: Select price range 0-10.
Products are not displayed.

I suggest you please give a message here "No products found" something like that.
![image](https://user-images.githubusercontent.com/50259172/108955859-d8d4e380-7694-11eb-950d-d9c06b3dbecb.png)

**Comment by holydk** [comment]
Closed #5429
