### ISSUE TITLE
Product basic mode setting not working properly.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5430]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Go to => Admin => Catalog => Product
Step 2: Click on Add/Edit a product.
Step 3: Click on Settings button.
Step 4: Click on Product info group checkbox to select all checkbox.
Step 5: In Product info group **Manufacturers** option checkbox uncheck manually.
Step 6: Click on Product info group and uncheck and then check group checkbox.
**Manufacturers** checkbox on doesn't see any effect of group checkbox. When i manually checked/unchecked it.
![image](https://user-images.githubusercontent.com/50259172/108957514-995bc680-7697-11eb-8c83-35dfb74092e3.png)

**Comment by sagarnop** [comment]
Are you reproduce this?

**Comment by skoshelev** [comment]
Closed #5430
