### ISSUE TITLE
Add new shipping address in country and state is reset and added new address not display in shipping address drop down list

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5431]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Enable One page checkout
Step 2: Add product to cart
Step 3: Go to cart
Step 4: Click on checkout
Step 5: Select billing address and uncheck  **Ship to the same address** (click on continue button)
Step 6: Add new shipping address and click on continue
Step 7: Back button on click and back to the shipping address.
In drop down list added shipping address not showing in the list.
![image](https://user-images.githubusercontent.com/50259172/108960082-5bf93800-769b-11eb-8fd2-8d1502e82af9.png)

**Comment by arty1901** [comment]
Can I inspect this bug?

**Comment by exileDev** [comment]
Duplicated #5393
