### ISSUE TITLE
Website performance getting slow down with multi store and in 1500products. 

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5433]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1) I have added 1500 products into website.
2) I have added one more store so now i have total two store.
3) if you save any setting(for now try to save GeneralCommon setting ) from admin side then its take too much time to save or public store takes too much time to open the page.

**Comment by sangeetshah** [comment]
@AndreiMaz @RomanovM is this bug or not?

**Comment by AndreiMaz** [comment]
it's a possibile performance issue, and we'll check it. but it's not a bug

**Comment by exileDev** [comment]
Can't reproduce. Closed #5433
