### ISSUE TITLE
Allow nesting settings when the appropriate checkbox is unticked

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5435]
nopCommerce version: 4.40 BETA

1. For example, go to the manufacturer edit page in admin area
2. Proceed to the Display panel
3. Untick the "Allow customers to select page size" checkbox and see that the "Page size" field is not nested

And few more fields in admin area with the same issue

Related: https://github.com/nopSolutions/nopCommerce/issues/5494

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this.
