### ISSUE TITLE
Nivo slider plugin. Use picture element instead of img

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5436]
nopCommerce version: 4.30

> My nivo slider now have 10 images and i need 10 for desktop and 10 for mobile(because of resolution).I want when width is lower then 769 to change images for desktop with images for mobile. I saw that nivo slider can only put images on img element so i can't use picture and source element to fix my problem.

Source: https://www.nopcommerce.com/boards/topic/90324/nivo-slider-problem-with-source-element

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
