### ISSUE TITLE
Pdf invoice direct link throw the null error on admin side

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5438]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
1) Open this link "https://localhost:44308/Admin/Order/PdfInvoice"

**Comment by rajupaladiya** [comment]
@sangeetshah - You must have to pass order id, you're trying to access invalid link

**Comment by sangeetshah** [comment]
@rajupaladiya but null handling is necessary for any code i think.

**Comment by AndreiMaz** [comment]
There's no need to handle such situations when a store owner "manually" plays with or generates some unexisting URLs
