### ISSUE TITLE
Add new address in getting error on my account page.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5439]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Go to My account page.
Step 2: Click on address
Step 3: Click on add new button
Step 4: Fill data in fields.
Step 5: Select country 
Step 6: Select state (Display wait text with loader)
error display in console.
![image](https://user-images.githubusercontent.com/50259172/108989774-fb2e2780-76bb-11eb-8451-5419651b53ef.png)

**Comment by RomanovM** [comment]
Duplicates #5359
