### ISSUE TITLE
Dynamic Tier Pricing (on attribute change, not qty)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#544]
So first of all, I'm not talking about updating the tier pricing table when the qty is changed, there's plenty of other requests for that. 

I'm talking about when attributes are changed and the ajax dynamic price update is called, also update the tiered pricing table. 

Example: 
My base price = $2 
Price with 25+ = $1.50 
I have an attribute value where, if selected, adds $3. If that value is selected, the table will update to show 25+ = $4.50 instead of $1.50. Same idea for OverriddenPrice in combinations. 

Source: http://www.nopcommerce.com/boards/t/37071/feature-request-dynamic-tier-pricing-on-attribute-change-not-qty.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
