### ISSUE TITLE
Save Download button design is not proper.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5441]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Catalog => Product
Step 2: Go to product Create/Edit page
Step 3: Go to **Downloadable product** panel.
Step 4: Click on Downloadable product checkbox
Step 5: Check Use download URL.
Button design is not proper.
![image](https://user-images.githubusercontent.com/50259172/108999771-cbd1e780-76c8-11eb-87a3-8d20257f98e0.png)

Same UI issue is in "Sample download file".
![image](https://user-images.githubusercontent.com/50259172/109000140-4ef33d80-76c9-11eb-9a9e-0a87e1beace3.png)

**Comment by RomanovM** [comment]
Duplicates #5376
