### ISSUE TITLE
Admin panel design issue in Downloadable product tab in edit product page

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5443]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Product/Edit
    In Downloadable product tab  design issue in download url & save download button.

![Downlodable product](https://user-images.githubusercontent.com/75514919/109002858-c4acd880-76cc-11eb-932f-2aa0cc95eee9.png)

**Comment by RomanovM** [comment]
Duplicates #5376
