### ISSUE TITLE
Rental product start and end date does not have any date selected.

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5445]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Select Jwelley -> Elegant Gemstone Necklace (rental) ->  Start date & end date does not have any date selected.
    I suggest you that both start and end date should be selected with current date.

![rent product](https://user-images.githubusercontent.com/75514919/109008852-d0e86400-76d3-11eb-82cd-0fa942405605.png)

**Comment by RomanovM** [comment]
@HarshBhesawala 
>I suggest you that both start and end date should be selected with current date.

But why? I think customer should choose the dates he wants without any preselection.

**Comment by HarshBhesawala** [comment]
@RomanovM  on Admin side all calendar in current date display.

![109009065-1311a580-76d4-11eb-9302-5efebeff4eeb](https://user-images.githubusercontent.com/75514919/109106063-126d2380-7755-11eb-9f82-d6d4760fd07a.png)

what about this??  here customer should also choose the dates he wants without any preselection.

**Comment by AndreiMaz** [comment]
this is how calendar works. everything is by design
