### ISSUE TITLE
Not showing focus on current date in calendar

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5446]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
Step 1: Create a new rental product. Product Name is A.
Step 2: Go to  public store
Step 3: Open Product A details page.
Step 4: Select start date to open calendar
open calendar in not showing current date.
![image](https://user-images.githubusercontent.com/50259172/109008941-ee1d3280-76d3-11eb-9805-196ebf176325.png)

on Admin side all calendar in current date display.
![image](https://user-images.githubusercontent.com/50259172/109009065-1311a580-76d4-11eb-9302-5efebeff4eeb.png)

**Comment by sagarnop** [comment]
This is bug or not?

**Comment by RomanovM** [comment]
@sagarnop See conversation [here](https://github.com/nopSolutions/nopCommerce/issues/5445).
