### ISSUE TITLE
Filter by attributes not working properly

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5447]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Go to Apparel => Shoes
Step 2: Select Red color
![image](https://user-images.githubusercontent.com/50259172/109010473-cfb83680-76d5-11eb-86e8-4d12f203b4ba.png)

Step 3: Select Gray color
Red color product not display.
![image](https://user-images.githubusercontent.com/50259172/109010515-dba3f880-76d5-11eb-9dc0-7657bc9ab009.png)

Step 4: Unchecked Red color
Red color product display in Gray color.
![image](https://user-images.githubusercontent.com/50259172/109010537-e3639d00-76d5-11eb-8fc8-0dfabacf4eee.png)

**Comment by holydk** [comment]
See also #5341

**Comment by sagarnop** [comment]
Thank you

**Comment by exileDev** [comment]
Closed #5447

**Comment by sagarnop** [comment]
sagarkayasth@gmail.com
This is my email id, that I verifying as per your email.
