### ISSUE TITLE
News item in not showing full description error message properly

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5448]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
Step 1: Go to admin => Content management => News items
Step 2: Click on Add new  button on news item list.
Step 3: Click on save button without filling data.
Name and short description required message display but full description message not display.

When i add space in Name and short description both fields then i'll get required message in full description, but here when i add space in full description then i get Name and short description required message but not full description required message get.

![image](https://user-images.githubusercontent.com/50259172/109017522-4442a380-76dd-11eb-8319-2cafbff8d119.png)

![image](https://user-images.githubusercontent.com/50259172/109017603-57ee0a00-76dd-11eb-98cf-c0044538937f.png)

**Comment by RomanovM** [comment]
@sagarnop Full description is checked by server validation. Like in a previous version.
