### ISSUE TITLE
In Admin panel multiple duplicate records getting saved when clicking multiple times on form save button.

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5450]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Product, Categories, Manufacturers
    For Example
    Add new category & when i click save button mutliple times, multiple duplicate records getting saved.
    Notification also shown multiple times.

   
![Add](https://user-images.githubusercontent.com/75514919/109034018-339a2980-76ed-11eb-9bbc-aea891639f27.png)
![List](https://user-images.githubusercontent.com/75514919/109034022-34cb5680-76ed-11eb-8396-c10447d51c51.png)

**Comment by AndreiMaz** [comment]
You clicked it multiple times, you got multiple records. as expected

**Comment by HarshBhesawala** [comment]
@AndreiMaz  What about the success notification?
 It shown twice.
