### ISSUE TITLE
When clicked on "Remove download" button,file related entry does not removed from database table (download).

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5451]
nopCommerce version:  4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Product/Edit
    Go to Downloadable product section, enable "Downloadable product".
    Upload file then we can see two buttons display after uploaded file,
    "Download uploaded file" and "Remove download"
    Click on "Remove download" button, it will remove file but it will not remove that file entry in database table (download).

    
![downloadable product](https://user-images.githubusercontent.com/75514919/109036368-883ea400-76ef-11eb-9a71-31e87c4c2aee.png)

**Comment by RomanovM** [comment]
Duplicates #3878
