### ISSUE TITLE
Product detail page on category breadcrumb does not display current category.

### ISSUE THREAD

**Issue by HarshBhesawala** [nopSolutions/nopCommerce#5452]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Go to Admin/Product/Edit
    Product name : HTC One M8 Android L 5.0 Lollipop
    Categories :  Electronics >> Cell phones && Digital downloads
    selected two categories and saved product.

2. Go to front side
    Select menu Electornics/Cell phones,
    Click on "HTC One M8 Android L 5.0 Lollipop" product,
    breadcrumb shown : "Home /  Electronics /  Cell phones /  HTC One M8 Android L 5.0 Lollipop"

    Select menu Digital downloads
    Click on "HTC One M8 Android L 5.0 Lollipop" product,
    breadcrumb shown : "Home /  Electronics /  Cell phones /  HTC One M8 Android L 5.0 Lollipop"
    breadcrumb should be :  "Home /  Digital downloads /  HTC One M8 Android L 5.0 Lollipop"

![Multiple Categories](https://user-images.githubusercontent.com/75514919/109039151-790d2580-76f2-11eb-9c0b-4dd125c18329.png)

![breadcrumb](https://user-images.githubusercontent.com/75514919/109039387-be315780-76f2-11eb-83e3-2ab7855dd9d7.png)

**Comment by AndreiMaz** [comment]
it's by design (duplicated work item)
