### ISSUE TITLE
Roxyfileman highly compress large image

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5453]
nopCommerce version: 4.40 Beta even in 4.30

Steps to reproduce the problem: 
Go to wwwroot > wwwroot > lib > Roxy_Fileman > conf.json

Update MAX_IMAGE_WIDTH and MAX_IMAGE_HEIGT to maximum values, suppose - 100000 x 100000
Restart application 
Now go to product edit page in admin
Upload large image from roxyfileman
and see uploaded image, it highly compresses the image and reduces 50% image quality

see with this video
https://screencast-o-matic.com/watch/crnZqNWFGr

I've used this image for test
![R_WWEN_iPhone_SE_Q220_Large_1-File 1](https://user-images.githubusercontent.com/13154058/109058690-51758780-7709-11eb-8d56-87f06c9747c5.jpg)

**Comment by AndreiMaz** [comment]
@rajupaladiya So why do you need to upload 100000 x 100000 pictures? Or change these settings to these values?

**Comment by rajupaladiya** [comment]
Regarding change setting, default it is 1000 x 1000, so on uploading image, it resize width to 1000 px if original image have wide (width > 1000px), so I changed it to 100000 x 100000 for upload image with original quality

you can check [here ](https://github.com/nopSolutions/nopCommerce/blob/87c3eeb614922979f64f53caa65bf33fcbf6e7a6/src/Libraries/Nop.Services/Media/RoxyFileman/FileRoxyFilemanService.cs#L637)

I'm uploading image with 13000px+ width, there are promotion images with high clearity.
![image](https://user-images.githubusercontent.com/13154058/109145578-aa383500-7788-11eb-99d5-c0e64f0e9ba6.png)

**Comment by DmitriyKulagin** [comment]
@rajupaladiya The size of the uploaded image is cut off due to the "_mediaSettings.MaximumImageSize" (default is 1980px).
