### ISSUE TITLE
Catalogs switching between multiple stores

### ISSUE THREAD

**Issue by alexmvubizname** [nopSolutions/nopCommerce#5454]
nopCommerce version: 4.3.0 release

Steps to reproduce the problem: 
Open two stores in the same browser, two tabs
https://csc.vubiz.com/
https://tta.vubiz.com/
Start checking catalog products on first and second store. Return to home page for both stores.
 
Result should be:
![image](https://user-images.githubusercontent.com/47668528/109073617-a04cfe00-76c4-11eb-8af1-aa30f9b0af5f.png)
![image](https://user-images.githubusercontent.com/47668528/109073631-a5aa4880-76c4-11eb-98ee-4489eb1cfd83.png)

But some times catalog switching:
![image](https://user-images.githubusercontent.com/47668528/109073679-ba86dc00-76c4-11eb-918a-360f8c625067.png)

**Comment by AndreiMaz** [comment]
I presume it's the same as https://github.com/nopSolutions/nopCommerce/issues/5317 (already fixed)
