### ISSUE TITLE
Change behavior of master checkbox with pagination

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5456]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Catalog =>Product
Step 2: Product list page on select master checkbox
Step 3: Go to next page
Master checkbox is checked but items checkbox doesn't check.
When I'll come on my previous page there is same problem show on page.

![image](https://user-images.githubusercontent.com/50259172/109127518-8965e480-7774-11eb-980e-efe60191f659.png)

![image](https://user-images.githubusercontent.com/50259172/109127567-94b91000-7774-11eb-8201-37fd84543829.png)

**Comment by DmitriyKulagin** [comment]
@sagarnop I tried to reproduce your scenario on the current development branch and everything works well.

![masterCheckBox gif](https://user-images.githubusercontent.com/27218280/134301030-9bc32c95-6e8c-466f-b95a-8beccde37b4e.gif)
