### ISSUE TITLE
Add a new product specification attribute title missing

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5457]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Catalog => Product.
Step 2: Edit **Build your own computer** product.
Step 3: Go to **Specification attributes** panel
Step 3: Click on Add attribute button.
![image](https://user-images.githubusercontent.com/50259172/109129659-e5316d00-7776-11eb-878e-eb17685e8fdd.png)
Step 4: Open new page for add a new product specification attribute.
but here page title is missing.
![image](https://user-images.githubusercontent.com/50259172/109129938-304b8000-7777-11eb-968b-34224ccb34ee.png)

Product attribute page title is display but specification attribute not display.

**Comment by ngtrian** [comment]
Can open in the popup window instead?
Similar to Product attribute
