### ISSUE TITLE
Cannot enter decimals

### ISSUE THREAD

**Issue by qcjxberin** [nopSolutions/nopCommerce#5458]
nopCommerce version: 4.40Beta

Steps to reproduce the problem: 
When I added product data in the background, I found that I could only enter whole numbers, not decimal places

**Comment by AndreiMaz** [comment]
@qcjxberin 
1. What exactly fields are you trying to enter data in?
2. What page?

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/109139471-85e35500-7796-11eb-99a0-4fea6845ce3e.png)
@AndreiMaz  eg: 1.90

**Comment by AndreiMaz** [comment]
@qcjxberin It works fine. 
1. What are your language and culture are you using in nopCommerce (admin area > configuration > languages)?
2. What is your Window culture and language?

**Comment by qcjxberin** [comment]
It is a problem with the current language setting. After I modify it, it is OK.
