### ISSUE TITLE
Uploaded file not showing but in database Download table its showing.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5459]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Catalog => Product
Step 2: Edit **Build your own computer** product.
Step 3: Add new product attribute with file upload.
Step 4: Go to Public store and open **Build your own computer** product.
Step 5: Upload file successfully.
Step 6: Refresh the page.
Step 7: Uploaded file not showing but in database **Download** table its showing.

![image](https://user-images.githubusercontent.com/50259172/109130765-19595d80-7778-11eb-841c-11d3d49668ef.png)

![image](https://user-images.githubusercontent.com/50259172/109130814-29713d00-7778-11eb-8827-3db1e66d821f.png)

![image](https://user-images.githubusercontent.com/50259172/109130901-43128480-7778-11eb-8cca-1e17926618d9.png)

**Comment by AndreiMaz** [comment]
it's a default behavior because we cannot track page reloads
