### ISSUE TITLE
Uploaded file can't download on cart page.

### ISSUE THREAD

**Issue by sagarnop** [nopSolutions/nopCommerce#5460]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Catalog => Product
Step 2: Edit Build your own computer product.
Step 3: Add new product attribute with file upload.
Step 4: Go to Public store and open Build your own computer product.
Step 5: Upload file successfully.
Here i can download my uploaded file.
![image](https://user-images.githubusercontent.com/50259172/109132206-95a07080-7779-11eb-9897-69cbff23666f.png)
Step 6: Add to this product in cart.
Step 7: Click on uploaded file for download.
Here i can't download my uploaded file.
![image](https://user-images.githubusercontent.com/50259172/109132324-b963b680-7779-11eb-8e68-f0da9a870199.png)

**Comment by skoshelev** [comment]
Can't reproduced on the latest source code

**Comment by format-17** [comment]
I have the same problem.
ChromeDevTools console say:
> Mixed Content: The site at 'https://shop.xy.com/' was loaded over a secure connection, but the file at 'https://shop.xy.com/download/getfileupload/?downloadId=bb0d2df0-d059-4ce5-9c23-ddac8a4512f8' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

I guess there is a problem with the proxy or something.

I run NopC 4.40.3 in a docker env. Behind pomerium proxy.

**Comment by RomanovM** [comment]
@format-17 See [this comment](https://github.com/nopSolutions/nopCommerce/issues/5748#issuecomment-877129833).
