### ISSUE TITLE
4.4 NOTIFCATION IN TOP BAR

### ISSUE THREAD

**Issue by smss123** [nopSolutions/nopCommerce#5466]
nopCommerce Version: 4.4 beta

Steps to reproduce the problem: 
NEED AREA IN TOP BAR IN NOTIFICATION TO ADD NOTIFICATION FROM PLUGIN OR FROM NOPCOMMERCE ENGIN

**Comment by AndreiMaz** [comment]
the notification system is already available for developers. please see how it's used in other places
