### ISSUE TITLE
Redundant "Help <" suggestion  in search autocomplete (admin area)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5467]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. Go to admin area
2. Try typing "hel" or "la"
3. You'll see a redundant "Help <" suggestion

![image](https://user-images.githubusercontent.com/5019111/109257949-553d0300-780a-11eb-8dc9-2eb7a7dce28b.png)

**Comment by skoshelev** [comment]
Closed #5467
