### ISSUE TITLE
Localization of months for datepicker

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5468]
1. Go to the "my account", "registration" page. Or other pages where "nop-date-picker" is used
2. "Month" localization should depend on the current language. But it's not localizable

Source: https://www.nopcommerce.com/en/boards/topic/90309/find-bugs-in-nopcommerce-440-beta-and-earn-10/page/2#281461

**Comment by OKANIL** [comment]
"Month" should be "Ay"

Month : English 
Ay : Turkish

**Comment by exileDev** [comment]
Closed #5468 For more details see #3773
