### ISSUE TITLE
Required field condition is not checked at Shipping origin tab

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5469]
nopCommerce version :  4.40 beta
Steps to reproduce the problem: 

1) /Admin/Setting/Shipping

2) GO Shipping origin

3) Some of the field screen shot attached here 
Required field condition is not checked. **It will save with blank value.**

![image](https://user-images.githubusercontent.com/41533502/109268087-98aa6800-7830-11eb-84e3-4d12361556c7.png)

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/5470

**Comment by skoshelev** [comment]
Closed #5469
