### ISSUE TITLE
Required validation is not working on Add Product Review 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5471]
nopCommerce version: 4.40 Beta

Steps to reproduce the problem: 
1) Create one Product

2) Go front end (preview product)

3) Click Be the first to review this product

4) Click on submit button. **Required validation is not working** 

https://www.loom.com/share/3d855b3c5eb6421ebb804a1523e6a9ec

**Comment by skoshelev** [comment]
Closed #5471
