### ISSUE TITLE
Upgrading to NopCommerce 4.3 - unable to login or register due to too many redirects

### ISSUE THREAD

**Issue by j2bmw** [nopSolutions/nopCommerce#5474]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Upgrade to nopCommerce 4.30 from 4.20 following the upgrade instruction.
2. Publish to an Azure App service through Visual Studio Web Deploy via the existing publish profile for 4.20.
3. Start the website. Some pages ceased working because of "too many redirects", including login, register and wish list.

Settings:
1. Table Store SslEnabled: False; URL: https://bebooks.com.au/; Host: bebooks.com.au
2. domain bebooks.com.au is a secured connection, forced to ssl.

Tried the following methods, I still has no success.
1. Enable SSL in Store table.
2. clear site cookies and browser caches.
3. "Empty Cache and Hard Reload" through Chrome developer tools.
4.  Although it's not related to Azure app service hosting, I tried "UseHttpXForwardedProto": true. There is no luck.

Please note that https://bebooks.com.au works fine with nopCommerce 4.20.

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue but it's definitely related to a wrongly configured SSL. Please post all technical questions on our forums

**Comment by j2bmw** [comment]
I have posted the issue at https://www.nopcommerce.com/en/boards/topic/90354/upgrading-to-nopcommerce-430-from-420-unable-to-login-or-register-due-to-too-many-redirects#281511. Please note after upgrading database, I skipped installation. May be there is a permission issue in this way.

**Comment by j2bmw** [comment]
Now I can answer my question above. That's not an issue.

I redeployed the website. Then I enabled SSL for my store. It's fine now. I did the same thing last time. It didn't work. I did restart the app service after enabling SSL previously. This is some thing I cannot explain. But I am happy to leave it because it's been working since two days ago.
