### ISSUE TITLE
Default plug-in detection is not supported

### ISSUE THREAD

**Issue by qcjxberin** [nopSolutions/nopCommerce#5477]
nopCommerce version: 
4.40BETA

Steps to reproduce the problem: 
Default plug-in detection is not supported
![image](https://user-images.githubusercontent.com/5792218/109447280-4c546780-7a7e-11eb-9b55-206f1b257775.png)

**Comment by AndreiMaz** [comment]
Everything works fine by default (clean installation). Cannot reproduce the issue

**Comment by qcjxberin** [comment]
We also installed it cleanly, and there is no adjustment in the background, and there is a problem with the prompt field

**Comment by AndreiMaz** [comment]
"no adjustment in the background" and "there is a problem with the prompt field"

what exactly problem?

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/109457976-e2948780-7a96-11eb-967a-a2747a7ed293.png)

**Comment by AndreiMaz** [comment]
It doesn't look like a clean installation of 4.40 beta. Try reinstalling
