### ISSUE TITLE
Email id into billing and shipping going out of div at order edit page (UI issue)

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5479]
nopCommerce version: 4.4beta

Steps to reproduce the problem: 
Email id into billing and shipping going out of div at order edit page 

![image](https://user-images.githubusercontent.com/10364140/109455440-a3593d00-7a7c-11eb-9932-1f4d995f8fa8.png)

**Comment by AndreiMaz** [comment]
There's no way to "fix" it because emails cannot be displayed on separate lines
