### ISSUE TITLE
Add type for 'Related Products' (ie. Accessories, Alternatives etc.)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#548]
Related products is a great feature to help customers find related products. However, often it could be useful for the customer to know what kind of relation the products have. 

If the relation is "Accessory" the customer knows that the related product fits to the first product and can safely add it to the basket and buy it without asking the store owner if it fits (for example if the product the customer bought months ago has been broken and needs to be repaired). Example: A tire could be an accessory to a bicycle.

If it instead is an  "Alternative" the customer knows that the product replaces the first one and that they don't necessarily match each other. Example: A red bicycle could be an alternative to a blue bicycle.

I suggest that it should be possible in admin to choose what kind of relation a "Related product" has.

Forum ource: http://www.nopcommerce.com/boards/t/40021/suggestion-add-type-for-related-products-ie-accessories-alternatives-etc.aspx

**Comment by tigran-avdalyan** [comment]
add Accessories ability is very important 
Example: https://comfy.ua/noutbuk-acer-aspire-es1-533-c7n4-nx-gfteu-042-acsessuary.html
we can Add this function  to Grouped products
