### ISSUE TITLE
Gets an error when adding a new discount requirement type with not selected customer role

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5481]
nopCommerce version: 4.40 BETA

Steps to reproduce the problem: 
1. Go to the discount edit page
2. Add a new requirement with the "Must be assigned to customer role" type
3. Click Save when customer role is not selected
![179884352c](https://user-images.githubusercontent.com/16681184/109557849-adfdeb80-7ae9-11eb-93a5-08000da243f1.jpg)

**Comment by skoshelev** [comment]
Closed #5481
