### ISSUE TITLE
Avalara tax plugin. Too many GetTax API Calls

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5482]
nopCommerce version: 4.30

Source: https://www.nopcommerce.com/boards/topic/90367/avalara-plugin-making-too-many-gettax-api-calls

We should use the [DownloadTaxRatesByZipCode](https://developer.avalara.com/api-reference/avatax/rest/v2/methods/TaxContent/DownloadTaxRatesByZipCode/) endpoint and update the tax rates monthly. This would allow us to provide a tax estimate without pinging AvaTax for a tax calculation and will reduce calls to AvaTax.

**Comment by justinjstark** [comment]
@RomanovM  You all can design your tax calculations better. Tax only needs to be calculated once per order. You don't need to calculate tax until shipping address is entered during checkout (tax rate in the US is determined by nexus and shipping address). Once per order/checkout is all you need. Caching tax results is a terrible strategy as you noted in the help-text that it is inaccurate. Tax accuracy is not something to shortcut as it can lead to incorrect filings and legal problems here in the US. If you need help better designing tax calculations, let me know and I can help guide you. I have built custom integrations with Avalara for other platforms.
