### ISSUE TITLE
Azure FrontDoor Health Check creates new Guest Customer

### ISSUE THREAD

**Issue by severindheureuse** [nopSolutions/nopCommerce#5486]
nopCommerce version: 4.30

Steps to reproduce the problem: 
Im currently running a nopCommerce installation on an Azure App Service behind Azure Front Door and noticed that many Guest Customers are getting created. 
Azure FrontDoor has an integrated healt Check which Pings a Custom Path (default is /) every X Seconds. On each Ping, a different Guest Customer gets created by nopCommerce.

The solution would be to add the User Agent "Edge Health Probe" to the browscap.crawlersonly.xml.
I tested the solution in my installation and it works fine.

**Comment by AndreiMaz** [comment]
It's a third-party library that we prefer not to edit manually (https://github.com/browscap/browscap and http://browscap.org). We'll include it if they add it as well.

Anyway, it's not a problem because all such guest records are deleted automatically later
