### ISSUE TITLE
ShipStation configuration page. Hide "Package volume" if "Pass dimensions" checkbox is unticked; use nested settings there

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5488]
nopCommerce version: 4.40 BETA

Steps to reproduce the problem: 

1. go to ShipStation configuration page
2. tick "Pass dimensions"
3. select "Pass dimensions" in the "Packing type" field
4. untick "Pass dimensions"
5. see that the "Package volume" field is still here

There is also no nested settings design

**Comment by skoshelev** [comment]
Closed #5488
