### ISSUE TITLE
Html Helper ConvertHtmlToPlainText is not working proper

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#5489]
nopCommerce version: 4.4 Beta

Steps to reproduce the problem: 
Method  HtmlHelper.ConvertHtmlToPlainText(text, true, true) is not removing html tags proper
After convert html to plain text, I can see still `<p>, <h3>, <img>, <code> `tags are there
What I get that it just remove anchor tag and replacing br tag `&nbsp;&nbsp `word

Kindly see this video - https://screencast-o-matic.com/watch/creejJWK1A

**Comment by rajupaladiya** [comment]
This is helped for me - https://gist.github.com/ArtemAvramenko/e9a2ae1c814450c701b1fc270caf37fd


`private static readonly Regex[] _htmlReplaces = new[] {
    new Regex(@"<script\b[^<]*(?:(?!</script>)<[^<]*)*</script>", RegexOptions.Compiled | RegexOptions.Singleline, TimeSpan.FromSeconds(1)),
    new Regex(@"<style\b[^<]*(?:(?!</style>)<[^<]*)*</style>", RegexOptions.Compiled | RegexOptions.Singleline, TimeSpan.FromSeconds(1)),
    new Regex(@"<[^>]*>", RegexOptions.Compiled),
    new Regex(@" +", RegexOptions.Compiled)
};

private string HtmlToPlainText(string html)
{
    foreach (var r in _htmlReplaces)
    {
        html = r.Replace(html, " ");
    }
    var lines = html
        .Split(new[] { '\r', '\n' })
        .Select(_ => WebUtility.HtmlDecode(_.Trim()))
        .Where(_ => _.Length > 0)
        .ToArray();
    return string.Join("\n", lines);
}`

**Comment by AndreiMaz** [comment]
Why should it remove HTML tags? It's not by design (especially in a blog post). If a store owner entered a blog oist with HTML tags, it means he wants to display them

WebUtility.HtmlDecode does not remove HTMl tags, it decodes it

**Comment by rajupaladiya** [comment]
I just show example for BlogPost but consider it for any html text.
But if any html text pass in method HtmlHelper.ConvertHtmlToPlainText(text, true, true) then it must remove html tags as per method name - Convert Html To **Plain Text** but here output text is **not actually Plain Text**

Kindly check @AndreiMaz
