### ISSUE TITLE
Allow a store owner to download/upgrade current plugins in admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#55]
We already allow a store owner to see a list of all plugins from official site (with a official site extension page).

1. Allow him to download free plugins. Note that there are a lot of commercial plugins which not be installed this way. They should be purchased and installed manually

2. Also let's automatically check whether some of already downloaded plugin has been updated and allow a store owner to automatically download and update it.
Source: http://www.nopcommerce.com/boards/t/31888/feature-request-import-theme-file.aspx#137533. Also we need a notify store owners when an upgrade is available

3. Offer them during installation? As part of https://github.com/nopSolutions/nopCommerce/issues/1730

We can do that it's already done in orchard, perhaps it's possible to use their code and architecture?

We should wait until we have our own marketplace where all plugins are stores in our database

See related work item #78

**Comment by cybernexus** [comment]
I am in the process of testing and finalizing a plugin that provides not only this functionality but automatic license key download / installation for purchased products.

There are two components...

1. A store side plugin that provides the custom setup and WebAPI (data feeds)
2. A client side plugin that provides core functions to other plugins and consumes number the above WebAPI. This plugin also installs / uninstalls / upgrades plugins with code that supports executing sql upgrade scripts and adding language resource strings that may be included in the downloaded package.

I found quite a few issues that needed to be explored while writing the code. The big one was versioning and the limit of having only one download option for a product. What I ended up doing involved creating a new table that stores a one to many relationship of product to downloads with additional data stored in the mapping table such as plugin version, nop version etc. 

All in all the functionality is rather robust and so far I have been fairly happy with the results but... I would rather have this functionality built into the default plugin management and would be more than willing to contribute / integrate any code I have written to serve the entire community.

**Comment by compito** [comment]
Any news on this one? It would definitely be of huge help for people who can't be bothered with manual updates...

**Comment by mobsoftware** [comment]
I really hope we can get this added to the next version of nopCommerce 4.30!

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
