### ISSUE TITLE
product detail page: image gallery won't popup

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5500]
nopCommerce version: 4.40-beta with default clean theme

Steps to reproduce the problem: just open a product detail page with images, and click any.

I saw there is a poppup in the demo site, but in our fresh installation, there is only a plain image gallery, when you click the thumb under the big image, there is no popup, only the big image switched.

**Comment by AndreiMaz** [comment]
just set mediasettings.defaultpicturezoomenabled to true
