### ISSUE TITLE
Do not hard-code styles

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5503]
nopCommerce version: 4.40 beta

There are some hard-coded styles at https://github.com/nopSolutions/nopCommerce/blob/9e9795d91c884a4d2edbc778169e29f819914bdb/src/Presentation/Nop.Web/Views/Checkout/BillingAddress.cshtml#L58
Could you please move them to the css files so that we can style them in the themes without overriding these views?

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/5#281739

**Comment by exileDev** [comment]
Closed #5503
