### ISSUE TITLE
Add an event to the " UpdateAsync" method

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5504]
The UpdateAsync method does not take into account the publishEvent parameter and no event is being published - https://github.com/nopSolutions/nopCommerce/blob/9e9795d91c884a4d2edbc778169e29f819914bdb/src/Libraries/Nop.Data/EntityRepository.cs#L377

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/5#281747

See PR: https://github.com/nopSolutions/nopCommerce/pull/5506

**Comment by badijm** [comment]
Hi, I can pick this item.

**Comment by AndreiMaz** [comment]
@skoshelev see https://github.com/nopSolutions/nopCommerce/pull/5506

**Comment by skoshelev** [comment]
Thank you @badijm 

Closed #5504
