### ISSUE TITLE
40 times slower request in nopCommerce 4.30 vs 4.20

### ISSUE THREAD

**Issue by j2bmw** [nopSolutions/nopCommerce#5505]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Run nopCommerce 4.30 and 4.20 websites with two identical databases (copy) side by side on local server through Visual Studio debugger.
2. Turn on mini profilers on each.
3. The result for reloading home page: 4.30 spends 56s in request while 4.20 1.5s. 4.30 is 40 times slower in reloading the home page than 4.20. Please the mini profiler screenshots below.

The same issue occurs on production server https://bebooks.com.au. The slow request seems across many pages. The whole site becomes slow and unusable.

We believe 4.30 should be faster. But why there is such an unreasonable long request in 4.30? Did I miss something? How to investigate it further?

Mini profiler results of 4.20
![nopCommerce mini profiler Reload home page 4 20](https://user-images.githubusercontent.com/30361626/110222123-228abd00-7f24-11eb-942f-023e88ebeadb.PNG)

Mini profiler results of 4.30
![nopCommerce mini profiler Reload home page 4 30](https://user-images.githubusercontent.com/30361626/110222125-23bbea00-7f24-11eb-8e10-4cfed599117c.PNG)

**Comment by AndreiMaz** [comment]
Definitely not true. Here is 4.30 and it works very fast (not 56 seconds) - https://demo.nopcommerce.com/
