### ISSUE TITLE
Catalog pages without products should not display "No products were found that matched your criteria"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5507]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
When you visit a category without direct products i.e Computers. This message is shown under the images of the subcategories: "No products were found that matched your criteria."

I believe this is needed only after filtration.

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/5#281814

**Comment by DmitriyKulagin** [comment]
Closed #5507
