### ISSUE TITLE
Do not show "out of stock" by default for combinations without selected values

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5510]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 

Just tested the new functionality for disabling the out-of-stock combinations (Very nice!!!) and noticed that the product availability is shown as "Out of stock" by default (even though the first attribute is not even selected i.e Please select) and the product has several attribute combinations that are in stock (Track inventory by attributes is selected for the product).
This may confuse the customers and they may decide the product is out of stock and not even select any attributes. Maybe show the availability once a given combination is selected.

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/6#281833

**Comment by skoshelev** [comment]
Closed #5510
