### ISSUE TITLE
Fix a checkbox behavior for the accessiBe plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5513]
nopCommerce version: 4.40 beta

Steps to reproduce the problem: 
1. go to the plugin configuration page
2. tick the "Enable" checkbox
3. It should display a new input

**Comment by skoshelev** [comment]
Closed by https://github.com/nopSolutions/nopCommerce/commit/4340b160eba3fd89d188e01065ff13593c6ebead
