### ISSUE TITLE
Default schema collation not respected

### ISSUE THREAD

**Issue by SzmergieL** [nopSolutions/nopCommerce#5519]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. `CREATE SCHEMA new_schema DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs ;`
2. Install NopCommerce by pointing to created database.
3. `SHOW TABLE STATUS where name like 'Product';`
![3](https://user-images.githubusercontent.com/5410643/110859662-0c7e5300-82bc-11eb-898a-bed56042d71c.PNG)
4. `SHOW FULL COLUMNS FROM Product;`
![4](https://user-images.githubusercontent.com/5410643/110859691-17d17e80-82bc-11eb-9eb8-f2f0a97e633b.PNG)

I've created new schema with `utf8mb4_0900_as_cs` collation. During nopCommerce installation I'm passing appropriate connection string. Installation completes successfully.

But, when I check the collation of the `Product.Sku` column it is different than the default. I've scanned the source code, but beside initial installation code, I couldn't find any other places where collation would be specified.

Does anyone know how to enforce default collation?

**Comment by AndreiMaz** [comment]
it's by cesign. please see https://github.com/nopSolutions/nopCommerce/issues/5423
