### ISSUE TITLE
Better PostgreSQL support, standard compliance column and table naming conventions

### ISSUE THREAD

**Issue by neaplus** [nopSolutions/nopCommerce#5521]
nopCommerce version: 
4.40
Steps to reproduce the problem: 

PostgreSQL's table and column names are case-sensitive. If we created object's names with uppercase letters in it, than you should use double-quoted name, every time you try to access them.

Best practice is to use legal, lower-case names exclusively so double-quoting is not needed.

Currently generated table and column names in select query like this:
`
SELECT "Id", "Name", "MetaKeywords", "MetaTitle", "Sku", "ManufacturerPartNumber", "Gtin", "AllowedQuantities"
FROM public."Product";
`
If we move db generation format to snake_case, it will be like bellow which is more user friendly and familiar. (especially for database guys)
`
SELECT id, name, meta_keywords, meta_title, sku, manufacturer_part_number, gtin, allowed_quantities
FROM product;
`

for example: https://www.npgsql.org/efcore/modeling/table-column-naming.html

That would be perfect if we can implement it, Just a friendly advice..

**Comment by exileDev** [comment]
We don't plan to implement this feature OTB and will leave it for customization. You can find a way to solve this here: https://github.com/linq2db/linq2db/issues/2501#issuecomment-831285987.

Closed #5521
