### ISSUE TITLE
Remove redundant  summary comments of controllers actions

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5523]
nopCommerce version: 4.40

Previously we have updated summary comments for methods that return a Task object (details here https://github.com/nopSolutions/nopCommerce/commit/b2a51612bdf7efd0e5023db3dfd80ea2afb79d66). 
But it's redundant for controller actions, see for example [CommonController](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/CommonController.cs#L109)

**Comment by skoshelev** [comment]
Closed #5523

**Comment by RomanovM** [comment]
Same for view components, see [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Components/AdminHeaderLinks.cs#L17)

**Comment by skoshelev** [comment]
Closed #5523
