### ISSUE TITLE
[Code Analysis] V3093 The '&' operator evaluates both operands. Perhaps a short-circuit '&&' operator should be used instead.

### ISSUE THREAD

**Issue by badijm** [nopSolutions/nopCommerce#5525]
Hi, this is the minor code issue revealed by static code analysis: 

`V3093 The '&' operator evaluates both operands. Perhaps a short-circuit '&&' operator should be used instead. FilePermissionHelper.cs 32`

**Update**: Created PR to fix it.

**Comment by bigboybamo** [comment]
Is this issue still open because it looks like it has been corrected in FilePermissionHelper.cs

**Comment by badijm** [comment]
Currently in `develop` still using '&' operator, not '&&' [CheckUserFilePermissions method]
