### ISSUE TITLE
error Rate in get live rates

### ISSUE THREAD

**Issue by sergeor** [nopSolutions/nopCommerce#5527]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1) From the admin panel, remove any language - regions and leave only one language that has comma for decimal separator (el-GR)
2) In the Currencies make euro rate 1
3)Click Get Live Rate
The rate that returned is without decimal separator for example 1222 but the correct value must be 1,222

**Comment by AndreiMaz** [comment]
@sergeor What exchange rate provider are you using?

**Comment by sergeor** [comment]
i checked in fresh installation. i use the default provider - ECB exchange rate provider

**Comment by sergeor** [comment]
The problem is biggest from the currency rate. Seems the admin area suffer from correct globalization implementation.

From some small investigation I have the following results.

Select a region which use comma separator for decimals.

1) At the shipping  / measures , when change the value with comma, for example 1,32 after save the value becomes to 132. No mater if you use 1,32 or 1.32

2) At the catalog / product (edit or new) the price work well. But in the list show as 1.32 (with dot not with comma)

**Comment by AndreiMaz** [comment]
@sergeor Have you updated the CLDR at the general settings page?

**Comment by DmitriyKulagin** [comment]
I have not been able to reproduce this, the currencies are set correctly.

**Comment by sergeor** [comment]
> 
> 
> @sergeor Have you updated the CLDR at the general settings page?

Yes i have click the CLDR at the general settings page. that put in mail folder the dir el with all necessarily files.
I have installed version 4.3 from the source on 3 PCs. 2 windows and 1 Linux. I have same result every time.
I want to note that this happens in the admin area and only for decimals. That is, in the statistics where the currency symbol exists (probably it is currency format and not decimal), I see the comma as symbol divisor, which is also right . in the list of products where the price does not have a currency symbol, instead of a comma display a dot. 

I will try to find time to download the latest version and try there. 

In the meantime if anyone is interested in this problem and wants to investigate it, I can provide access to an online running nopCommerce and you can experiment.
