### ISSUE TITLE
No descriptor file is found. It should be in the root of the archive.

### ISSUE THREAD

**Issue by alexcibridge** [nopSolutions/nopCommerce#5530]
nopCommerce version: 4.3

Steps to reproduce the problem: I have tried to setup everything however it seems that this error doesn't solve despite the plugins.json file being correct.

**Comment by AndreiMaz** [comment]
please contact an author of your plugin (you're trying to upload)

**Comment by alexcibridge** [comment]
Believe it or not... Nopcommerce is the plugin developer?? 

`  "SystemName": "Payments.PurchaseOrder",
  "Version": "1.34",
  "SupportedVersions": [ "4.20" ],
  "Author": "nopCommerce team",
  "DisplayOrder": 1,
  "FileName": "Nop.Plugin.Payments.PurchaseOrder.dll",
  "Description": "This plugin allows paying with Purchase Orders"
}`

**Comment by glhays** [comment]
Your plugin is supported version 4.2, and your posted error issue states your version as 4.3. is that the possible reason?
________________________________
