### ISSUE TITLE
Add security and versioning dependency alerts with Dependabot

### ISSUE THREAD

**Issue by aleks-ivanov** [nopSolutions/nopCommerce#5534]
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality

**Comment by aleks-ivanov** [comment]
Alright Andrei, have a good one! 🙂 

If you ever need anything DevSecOps for NopCommerce, just drop us a line at info@pipeline.foundation. We'd be happy to contribute!
