### ISSUE TITLE
Migration from Travis CI pipeline to GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [nopSolutions/nopCommerce#5538]
Migrate the Travis CI pipeline to a GitHub Actions pipeline for all the required automated processes with the addition of some other automation ideas, written as pseudo code in the pipeline in the connected PR.

We can start working on this promptly, just please let us know if you are interested in the implementation of the idea 🙂

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
