### ISSUE TITLE
Vendor commission system

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#554]
I think for multi vendor there should have a commissioning system. Site owner will get a percentage for every vendor product sell. At the creation time of the vendor site owner will be able to set commission rate as percentage. Like 5% or 10%. Then transaction report for both site owner (commission wise income) and vendor ( income without commission ). Then vendor fund transfer system or withdraw system. 

Related work item - https://github.com/nopSolutions/nopCommerce/issues/436 (the same issues and questions)

**Comment by patelsagu** [comment]
Vendor Payment option
vendor can request for money and admin approve it's requests
e.g Amazon

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/1928
