### ISSUE TITLE
Search order function in admin area error when pass parameter "phone" or "name"

### ISSUE THREAD

**Issue by hailua8xpro** [nopSolutions/nopCommerce#5544]
nopCommerce version: 

Steps to reproduce the problem: System.Data.SqlClient.SqlException (0x80131904): 'Length' is not a recognized built-in function name.     at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)     at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)  --- End of stack trace from previous location ---     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)  --- End of stack trace from previous location ---     at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)     at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)     at LinqToDB.Linq.QueryRunner.ExecuteElementAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)     at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)     at System.Linq.AsyncIQueryableExtensions.ToPagedListAsync[T](IQueryable`1 source, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in D:\work\web\NopCoreV1\Libraries\Nop.Data\Extensions\AsyncIQueryableExtensions.cs:line 649     at Nop.Services.Orders.OrderService.SearchOrdersAsync(Int32 storeId, Int32 vendorId, Int32 customerId, Int32 productId, Int32 affiliateId, Int32 warehouseId, Int32 billingCountryId, String paymentMethodSystemName, Nullable`1 createdFromUtc, Nullable`1 createdToUtc, List`1 osIds, List`1 psIds, List`1 ssIds, String billingPhone, String billingEmail, String billingLastName, String orderNotes, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in D:\work\web\NopCoreV1\Libraries\Nop.Services\Orders\OrderService.cs:line 389     at Nop.Web.Areas.Admin.Factories.OrderModelFactory.PrepareOrderListModelAsync(OrderSearchModel searchModel) in D:\work\web\NopCoreV1\Presentation\Nop.Web\Areas\Admin\Factories\OrderModelFactory.cs:line 972     at Nop.Web.Areas.Admin.Controllers.OrderController.OrderList(OrderSearchModel searchModel) in D:\work\web\NopCoreV1\Presentation\Nop.Web\Areas\Admin\Controllers\OrderController.cs:line 225     at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)     at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)     at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)     at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)     at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)     at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 104     at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)     at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in D:\work\web\NopCoreV1\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 94     at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in D:\work\web\NopCoreV1\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52     at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in D:\work\web\NopCoreV1\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49     at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)  ClientConnectionId:97433837-62ba-452c-a252-395d1259833f  Error Number:195,State:10,Class:15

**Comment by RomanovM** [comment]
Actually the same as #5545
