### ISSUE TITLE
Incorrect search of orders in the admin area when filter by a warehouse

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5545]
nopCommerce version: 4.30

> When doing a search on the Order screen, and only selecting a particular warehouse (leaving all other options as blank or ALL), the correct orders are not displayed. In most cases, a negative dollar amount is shown in the total, and no orders are in the grid.

Introduced in [this commit](https://github.com/nopSolutions/nopCommerce/commit/f021d40d4f8fe2a08e53e00beadfb67f17feb000#diff-841ecc872010bdbfcac101a62fb8025b9f4ae9f2dbf814a50c350ac60cf346c4L192), we shouldn't use the `inner join` to `_productWarehouseInventoryRepository` here, since it leads to incorrect results.

Source: https://www.nopcommerce.com/boards/topic/90501/order-search-bug-on-warehouse-only-search-nop43

**Comment by justinhof** [comment]
Thank you. Is there not a quick change to the code that I can update to get this to work? Waiting a couple months for 4.5 to be released will not be very good for business. I tried using the code that was checked in, but obviously that did not work. Any help on this would be greatly appreciated!!

Thanks!

**Comment by skoshelev** [comment]
Closed #5545
