### ISSUE TITLE
Disallow links with returnUrl parameter in robots.txt

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5546]
nopCommerce version: 4.40

> I had similar errors where google bot tries to index pages which have URL content as "returnUrl". It just mess with google search console coverage, since returnUrl pages usually have duplicated results.
> Better add the robots.additions file with the below content.
> 
> User-agent: *
> Disallow: */login?returnUrl=*
> Disallow: */register?returnUrl=*
> Disallow: */login?returnurl=*
> Disallow: */register?returnurl=*
> 
> My search console coverage results jumped from 26000 to 42000 in a month after I updated the robot.txt with the additional file.
> 

Source: https://www.nopcommerce.com/boards/topic/82070/se-ranking-reported-errors-and-fixes#281771

**Comment by exileDev** [comment]
Closed #5546

**Comment by arieldeil** [comment]
I got the same issue when google multiplied website page count  because every page had a different login URL. 
I added cannonical tag to login and register pages and page count went back to normal.
I think that this is a better approach in terms of SEO.
