### ISSUE TITLE
Using placeholders in product description

### ISSUE THREAD

**Issue by jakubmaguza** [nopSolutions/nopCommerce#5548]
nopCommerce version: 4.4

Hi,
I'm trying to use placeholders in product messages. Is this possible with current version of nopcommerce?

I know I can use that with messages, but I couldn't find any way to do that with product description.

I was also thinking of having description template with placeholders. All of our products are using exactly the same description template, only some variables are changed. Are you planning to introduce something like that, or I need to write my own plugin?

**Comment by AndreiMaz** [comment]
@jakubmaguza No, we're leaving it for customization
