### ISSUE TITLE
Attribute naming discrepancy in nopSelect tag helper

### ISSUE THREAD

**Issue by mark-at-tusksoft** [nopSolutions/nopCommerce#5549]
nopCommerce version: 4.30

In `Presentation\Nop.Web.Framework\TagHelpers\Admin\NopSelectTagHelper.cs`:

`private const string DisabledAttributeName = "asp-multiple";`

**Comment by jlechem** [comment]
I don't see that name in the code (DisabledAttributeName), I do see DISABLED_ATTRIBUTE_NAME. In fact I don't see the camel case reference anywhere in the code.
