### ISSUE TITLE
Localized plugin friendly-names in the admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5552]
nopCommerce version: 4.40

Now it used in a public store, pdf invoices, message templates. Whether we should also support localized plugin friendly-names in the admin area, e.g. on the plugin list page, etc?

Source: https://www.nopcommerce.com/boards/topic/90506/discount-plugin-missing-localized-resource-and-friendly-name-not-loaded

**Comment by AndreiMaz** [comment]
dualities https://github.com/nopSolutions/nopCommerce/issues/2158

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
