### ISSUE TITLE
VisibleIndividually option ignored

### ISSUE THREAD

**Issue by steph-ultima** [nopSolutions/nopCommerce#5553]
nopCommerce version: 4.40

Steps to reproduce the problem: 
- Set a product in the catalog so 'Visible individually' option is not selected.
- Start the store where this product is available
- In the search box or in the item by category list, the product appears when it should not

Fix:
- In Nop.Services\Catalog\ProductServices.cs, 
- In public virtual async Task<IPagedList<Product>> SearchProductsAsync
- Check the value (after line 815) with the below code
       `if (visibleIndividuallyOnly)
                productsQuery = productsQuery.Where(p => p.VisibleIndividually);`

**Comment by LindenSims** [comment]
I consider this a breaking bug in 4.4. Thanks for the fix.

**Comment by brakim** [comment]
I agree that this is a breaking bug. It totally changes the behavior of the catalog view when you are using grouped products and both the parent and the child have the same category assigned.

**Comment by exileDev** [comment]
Closed #5553
