### ISSUE TITLE
Temp tables connection leak

### ISSUE THREAD

**Issue by nduc** [nopSolutions/nopCommerce#5556]
nopCommerce version: 4.40

Steps to reproduce the problem: I'm running the linux build on Digitalocean with Ubuntu 20.04(LTS)x64 Basic instance with 2G of RAM, Postgres, nginx, and Let's Encrypt SSL.  When I go to Administration and restart the application the deamon gets killed with a status=6/ABRT.
Digging through the log I find this in /var/log/syslog

Mar 20 04:18:17 bottles systemd[1]: nopCommerce440.service: Main process exited, code=killed, status=6/ABRT
Mar 20 04:18:17 bottles systemd[1]: nopCommerce440.service: Failed with result 'signal'.
Mar 20 04:18:27 bottles systemd[1]: nopCommerce440.service: Scheduled restart job, restart counter is at 91.
Mar 20 04:18:27 bottles systemd[1]: Stopped Example nopCommerce app running on XUbuntu.
Mar 20 04:18:27 bottles systemd[1]: Started Example nopCommerce app running on XUbuntu.
Mar 20 04:18:34 bottles nopCommerce440-example[20927]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 121
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 20 04:18:34 bottles nopCommerce440-example[20927]: --- End of stack trace from previous location ---
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.TimerQueue.FireNextTimers()
Mar 20 04:18:34 bottles nopCommerce440-example[20927]:    at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Mar 20 04:18:35 bottles systemd[1]: nopCommerce440.service: Main process exited, code=killed, status=6/ABRT
Mar 20 04:18:35 bottles systemd[1]: nopCommerce440.service: Failed with result 'signal'.
Mar 20 04:18:38 bottles kernel: [ 8327.985499] [UFW BLOCK] IN=eth0 OUT= MAC=3e:60:4c:f4:6e:2c:fe:00:00:00:01:01:08:00 SRC=89.248.165.204 DST=161.35.238.204 LEN=40 TOS=0x00 PREC=0x00 TTL=243 ID=27564 PROTO=TCP SPT=59976 DPT=17191 WINDOW=>
Mar 20 04:18:45 bottles systemd[1]: nopCommerce440.service: Scheduled restart job, restart counter is at 92.
Mar 20 04:18:45 bottles systemd[1]: Stopped Example nopCommerce app running on XUbuntu.
Mar 20 04:18:45 bottles systemd[1]: Started Example nopCommerce app running on XUbuntu.
Mar 20 04:18:52 bottles nopCommerce440-example[20968]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 121
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 20 04:18:52 bottles nopCommerce440-example[20968]: --- End of stack trace from previous location ---
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.TimerQueue.FireNextTimers()
Mar 20 04:18:52 bottles nopCommerce440-example[20968]:    at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)

Looking at the code in TasksThread.cs looks like it has something to do with the timer.

Thank you for looking into this.

**Comment by nduc** [comment]
After trying to figure out why I kept getting error scheduled task cannot run in the log.  It turned out that whatever the value in StoreUrl is when the server first boot, that is the URL used to call the schedule tasks, even after Restart Application.  In my case I was switching between http -> https and non-www -> www URL.  Even after issuing Reboot Application, the value originally stored in StoreUrl is retained.
Once I changed the StoreUrl I have to reboot the server, and this also make the deamon to start properly.
One thing to note is that when I issue the Restart Application, the web page didn't refresh automatically.  I had to manually refresh the page.  This is jarring for the end users.

**Comment by nduc** [comment]
I was able to restart the application but leaving it running for about half a day I would get this error
Mar 31 00:00:34 bottles nopCommerce440-example[1039]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:       An exception was thrown attempting to execute the error handler.
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:       Npgsql.PostgresException (0x80004005): 53300: remaining connection slots are reserved for non-replication superuser connections
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications>
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.ConnectorPool.<>c__DisplayClass38_0.<<Rent>g__RentAsync|0>d.MoveNext()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:       --- End of stack trace from previous location ---
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:       --- End of stack trace from previous location ---
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Npgsql.NpgsqlConnection.Open()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Data.DataConnection.EnsureConnection()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Data.DataConnection.CreateCommand()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Data.DataConnection.get_Command()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters, Boolean withPar>
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints, Boolean withParameters)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumbe>
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Core.Caching.MemoryCacheManager.Get[T](CacheKey key, Func`1 acquire)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Web.Framework.WebStoreContext.GetCurrentStore()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Web.Framework.Infrastructure.DependencyRegistrar.<>c__DisplayClass0_0.<Register>b__2(IServiceProvider serviceProvider)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Core.Infrastructure.NopEngine.Resolve[T](IServiceScope scope)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Web.Framework.Globalization.NopRequestCultureProvider.DetermineProviderCultureResult(HttpContext httpContext)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<<UseNopExceptionHandler>b__2_1>d.MoveNext()
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:       --- End of stack trace from previous location ---
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:         Exception data:
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           Severity: FATAL
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           SqlState: 53300
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           MessageText: remaining connection slots are reserved for non-replication superuser connections
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           File: postinit.c
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           Line: 815
Mar 31 00:00:34 bottles nopCommerce440-example[1039]:           Routine: InitPostgres

After trying to restart nginx and nopCommerce services a few times I would get this error and cannot recover

Mar 30 23:27:52 bottles systemd[1]: nopCommerce440.service: Scheduled restart job, restart counter is at 235.
Mar 30 23:27:52 bottles systemd[1]: Stopped Example nopCommerce app running on XUbuntu.
Mar 30 23:27:52 bottles systemd[1]: Started Example nopCommerce app running on XUbuntu.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: --- End of stack trace from previous location ---
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueue.FireNextTimers()
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)System.NullReferenceException: Object reference not set to an instance of an object.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: --- End of stack trace from previous location ---
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueue.FireNextTimers()
Mar 30 23:27:58 bottles nopCommerce440-example[8433]:    at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Mar 30 23:27:58 bottles systemd[1]: nopCommerce440.service: Main process exited, code=killed, status=6/ABRT
Mar 30 23:27:58 bottles systemd[1]: nopCommerce440.service: Failed with result 'signal'.

I'm going to try to install pgbouncer to see if it helps with the Postgres connections.

**Comment by nduc** [comment]
Going to move the connection to a new issue.  I don't believe it's related to to the original issue.

**Comment by AndreiMaz** [comment]
also posted at https://github.com/nopSolutions/nopCommerce/issues/5582

**Comment by nduc** [comment]
I believe I tracked down the issue, but I don't know how to fix it.
When DeleteGuestCustomersAsync is executed and my store is newly setup there's no guest to delete, this function doesn't release the connections and creates new ones every time.  From monitoring the Postgres connections I see connections being created and remains in idle state until it reaches the max connection pool of 100 and then the application can't execute anymore query and I get remaining connection slots are reserved for non-replication superuser connections error above.

```
 46473 | commerce |                  | 127.0.0.1   | 2021-04-14 05:50:49.253914+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 46712 | commerce |                  | 127.0.0.1   | 2021-04-14 06:00:49.494995+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 46715 | commerce |                  | 127.0.0.1   | 2021-04-14 06:00:49.489656+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 46973 | commerce |                  | 127.0.0.1   | 2021-04-14 06:10:50.639725+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 46974 | commerce |                  | 127.0.0.1   | 2021-04-14 06:10:50.634614+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 47221 | commerce |                  | 127.0.0.1   | 2021-04-14 06:20:50.846333+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 47225 | commerce |                  | 127.0.0.1   | 2021-04-14 06:20:50.825771+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 47478 | commerce |                  | 127.0.0.1   | 2021-04-14 06:30:51.017865+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 47482 | commerce |                  | 127.0.0.1   | 2021-04-14 06:30:51.00948+00  | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 47740 | commerce |                  | 127.0.0.1   | 2021-04-14 06:40:51.317837+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 47747 | commerce |                  | 127.0.0.1   | 2021-04-14 06:40:51.314924+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 48001 | commerce |                  | 127.0.0.1   | 2021-04-14 06:50:51.529573+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 48003 | commerce |                  | 127.0.0.1   | 2021-04-14 06:50:51.526315+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 48381 | commerce |                  | 127.0.0.1   | 2021-04-14 07:00:52.414851+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 48382 | commerce |                  | 127.0.0.1   | 2021-04-14 07:00:52.411313+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 48565 | commerce |                  | 127.0.0.1   | 2021-04-14 07:10:52.622317+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 48573 | commerce |                  | 127.0.0.1   | 2021-04-14 07:10:52.615531+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 48834 | commerce |                  | 127.0.0.1   | 2021-04-14 07:20:52.83056+00  | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 48839 | commerce |                  | 127.0.0.1   | 2021-04-14 07:20:52.823927+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 49534 | commerce |                  | 127.0.0.1   | 2021-04-14 07:50:55.662494+00 | idle   | DROP TABLE "tmp_guestsToDelete"                                                                     +
       |          |                  |             |                               |        |
 49537 | commerce |                  | 127.0.0.1   | 2021-04-14 07:50:54.719634+00 | idle   | DROP TABLE "tmp_guestsAddressesToDelete"                                                            +
       |          |                  |             |                               |        |
 49974 | commerce |                  | 127.0.0.1   | 2021-04-14 08:10:55.720852+00 | idle   | CREATE TABLE "tmp_guestsToDelete"                                                                   +
       |          |                  |             |                               |        | (                                                                                                   +
       |          |                  |             |                               |        |         "CustomerId" Int NOT NULL                                                                   +
       |          |                  |             |                               |        | )                                                                                                   +
       |          |                  |             |                               |        |
 49311 | commerce |                  | 127.0.0.1   | 2021-04-14 07:40:53.667873+00 | idle   | CREATE TABLE "tmp_guestsToDelete"                                                                   +
       |          |                  |             |                               |        | (                                                                                                   +
       |          |                  |             |                               |        |         "CustomerId" Int NOT NULL                                                                   +
       |          |                  |             |                               |        | )                                                                                                   +
       |          |                  |             |                               |        |
 50065 | commerce |                  | 127.0.0.1   | 2021-04-14 08:17:08.040552+00 | idle   | UPDATE                                                                                              +
       |          |                  |             |                               |        |         "ScheduleTask"                                                                              +
       |          |                  |             |                               |        | SET                                                                                                 +
       |          |                  |             |                               |        |         "LastSuccessUtc" = $1,                                                                      +
       |          |                  |             |                               |        |         "LastEndUtc" = $2,                                                                          +
       |          |                  |             |                               |        |         "LastStartUtc" = $3,                                                                        +
       |          |                  |             |                               |        |         "StopOnError" = $4,                                                                         +
       |          |                  |             |                               |        |         "Enabled" = $5,                                                                             +
       |          |                  |             |                               |        |         "Type" = $6,                                                                                +
       |          |                  |             |                               |        |         "Seconds" = $7,                                                                             +
       |          |                  |             |                               |        |         "Name" = $8                                                                                 +
       |          |                  |             |                               |        | WHERE                                                                                               +
       |          |                  |             |                               |        |         "ScheduleTask"."Id" = $9                                                                    +
       |          |                  |             |                               |        |
   851 |          |                  |             |                               |        |
   850 |          |                  |             |                               |        |
   852 |          |                  |             |                               |        |
(56 rows)

```

**Comment by exileDev** [comment]
Closed #5556

**Comment by nduc** [comment]
I made a new build and been running this for 5 hr and don't see the issue anymore.
Thanks for the fix!

**Comment by rachaH** [comment]
> I made a new build and been running this for 5 hr and don't see the issue anymore.
> Thanks for the fix!

How can I fix it for the current moment before the new version release ? I'm in production environment and can't wait for the new version

**Comment by exileDev** [comment]
@rachaH You can build the 4.40-bug-fixes branch that already has the fix. Btw, we're going to release the next minor version soon.
