### ISSUE TITLE
Navigation is not working in Angular when Seizure Safe profile option is enabled

### ISSUE THREAD

**Issue by PiyushTiwari248** [nopSolutions/nopCommerce#5557]
![image-2021-03-12-09-47-44-588](https://user-images.githubusercontent.com/38920486/111861641-f8022080-8975-11eb-8192-6cc9bf40809e.png)

I am integrating accessibe in my Angular application. 
The problem is when I enable  Seizure Safe profile and other options  in my application all the navigations that I have created in left side bar ( you can see in the image) are not working anymore. It seems like they are freeze. I have used simple router Link to navigate withinin the application. Before enabling, it is  working completely fine.. I am not getting this issue in Chrome or edge.. I am only getting this problem in Mozilla Firefox. 

I have spent many days in figuring out the problem but it seems I am not even close to solving it.

**Comment by AndreiMaz** [comment]
@PiyushTiwari248 What is Seizure Safe? What is an application on your screenshot? How is it related to nopCommerce?
