### ISSUE TITLE
Rename GetProductsByProductAtributeIdAsync to GetProductsByProductAttributeIdAsync

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#5560]
nopCommerce version: 4.4

Steps to reproduce the problem: (no)

Wrong method name in ProductService

Atribute==>Attribute

[IProductService.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Catalog/IProductService.cs#L189)

**Comment by skoshelev** [comment]
Closed #5560

**Comment by skoshelev** [comment]
Closed #5560
