### ISSUE TITLE
Throw error when search billing email address  into order list page

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5561]
nopCommerce version: 4.4.2

Steps to reproduce the problem: 
1. Open admin side and go to order list page
2. Search billing email address 

![image](https://user-images.githubusercontent.com/10364140/112097424-fd55aa00-8bc5-11eb-828e-063cdae86791.png)

**Comment by RomanovM** [comment]
@exileDev  If there is `string.IsNullOrEmpty()` inside the query (for example [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderService.cs#L380)), linq2db generates an incorrect sql in output. See also mthods in [OrderReportService](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderReportService.cs)

**Comment by skoshelev** [comment]
Closed #5561
