### ISSUE TITLE
SkiaSharp - Images don't resize when using the supplied Dockerfile

### ISSUE THREAD

**Issue by purplepiranha** [nopSolutions/nopCommerce#5563]
nopCommerce version: 4.40.1

Steps to reproduce the problem: 
Create a Docker image using the Dockerfile supplied with NopCommerce 4.40 / 4.40.1
An Alpine runtime image is produced.
Images do not resize when uploaded as SkiaSharp requires library ld-linux-x86-64.so.2 which is not present.

See [https://www.nopcommerce.com/en/boards/topic/90532/image-resize-not-working-on-alpine-since-upgrade-to-nopcommerce-44#283404](https://www.nopcommerce.com/en/boards/topic/90532/image-resize-not-working-on-alpine-since-upgrade-to-nopcommerce-44#283404) for solution/workaround.

There may be a better way to do this - I'm surprised that there is nothing in the SkiaSharp documentation that I can find as the latest preview release states that is supports Alpine x64 (I tried the preview before using the workaround and had the same problem).

**Comment by skoshelev** [comment]
Closed #5563

**Comment by killerwife** [comment]
Using commit cabffa399e getting same error as in https://github.com/nopSolutions/nopCommerce/issues/5639

Running a clean configuration with just a theme installed.

https://gist.github.com/killerwife/e20b6285be242704eba26e455e690589 - error from console shown here.

Commit https://github.com/nopSolutions/nopCommerce/commit/12dd4825dfb56bbc64e192cd35d25e3205427646 is in the build (doublechecked to make sure)

Is it possible it is specifically only because of the theme? Is there a nuget package the theme might be missing?

**Comment by purplepiranha** [comment]
I can't see any reason why this doesn't work and having merged the latest release into the solution that I'm currently working on don't experience this problem.

Try looking at the Nop.Services project file and verifying that the following are both present and have the correct version:

```
<PackageReference Include="SkiaSharp" Version="2.80.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />
```

Also check to ensure that the following are correct on your DockerFile in case an old version has been left during a merge:

```
# create the build instance 
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
```

```
# create the runtime instance 
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runtime 
```

Note - this will only work if you are using Alpine as your runtime. If you are using a different Linux OS then you may need to install extra packages while creating the image instead.

I don't think that the theme would cause this kind of problem, but just to be sure you could switch to DefaultClean and then try performing an image resize to test it.

I also had an issue with file encoding on the entrypoint.sh script which meant that some parts of the script didn't run properly. That may be worth checking...
My working entrypoint.sh has the encoding set to 'Unicode - Codepage 1200', whereas the nopCommerce repo one appears to be 'Western European (Windows) - Codepage 1252'.

**Comment by killerwife** [comment]
The encoding was indeed the issue. Fixed it by setting to UTF-8 without Signature. Hopefully anyone else will also notice this.
