### ISSUE TITLE
Re-add UninstallPermissionsAsync

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#5565]
nopCommerce version: 4.4

Steps to reproduce the problem: Method UninstallPermissionsAsync was been deleted. (Commit 'Deleted unused methods')

@skoshelev Hello, can you re-add UninstallPermissionsAsync? Will the permissions not be automatically removed when a plugin is uninstalled? it's right?

**Comment by RomanovM** [comment]
See also https://www.nopcommerce.com/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/9#283300

**Comment by RomanovM** [comment]
Moved to #5717
