### ISSUE TITLE
CustomCustomerAttribute - Preselected value not working correct

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5568]
nopCommerce version: 4.40

> If a customer has a custom attribute and in the table "GenericAttribute" there is an entry "CustomCustomerAttributes" with information about these attributes and then I add a new custom attribute with a pre-selected value it is not selected (e.g. customer/info). When there is no entry in "GenericAttribute" the mechanism works correctly and pre-selects.

[Here](https://github.com/nopSolutions/nopCommerce/blob/4.40-bug-fixes/src/Presentation/Nop.Web/Factories/CustomerModelFactory.cs#L1000) we should first check whether there is a stored value for the appropriate attribute and then reset 'IsPreSelected' if a value exists.

Source: https://www.nopcommerce.com/boards/topic/90563/customcustomerattribute-preselected-value-not-working-correct

**Comment by skoshelev** [comment]
Closed #5568
