### ISSUE TITLE
Rename method AddLocaleResourceAsync

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5569]
nopCommerce version: 4.40

Actually, [this method](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L718) not only adds new locales but also updates existing ones. This can confuse users.
Initially, it was used only in plugins, so it wasn't so serious, but now it is used all over the solution and it might make sense.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5351
