### ISSUE TITLE
Store sitemap.xml as a file

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5570]
nopCommerce version: develop

At now XML sitemap generated in memory upon request, placed in the cache and then returned. This can be expensive in terms of performance if the store has many products, categories, etc., and the cache will not help here, since usually search engine robots request a map less often than it's stored in the cache. We could store the sitemap in a file and just return it when requested. But then this file will need to be periodically updated somehow (including from plugins), also it will need to be replicated in case of web farms, etc.
Perhaps we should make this behavior configurable? Let's discuss.

Add a new setting "Do not update Sitemap.xml before UTC" (choose a better name). Re-generate XML file (or files) only after this date. Then update the setting for the next period. For example, 7 days (make it configurable)

**Comment by untiedshoes** [comment]
Why not have an extra cache setting, other than default or short-term, for items that very rarely (if ever) change? 

i.e. PrepareKeyForLongTermCache and cache for much longer periods (months?)

**Comment by AndreiMaz** [comment]
@exileDev 
Add a new setting "Do not update Sitemap.xml before UTC" (choose a better name). Re-generate XML file (or files) only after this date. Then update the setting for the next period. For example, 7 days (make it configurable)

**Comment by exileDev** [comment]
Closed #5570
