### ISSUE TITLE
Combine usage IDependencyRegistrar and INopStartup

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5571]
nopCommerce version: 4.40

As a continuation of #4196
We moved to the internal DI, but still using our custom mechanism with `IDependencyRegistrar` to register dependencies, and also we have added `INopStartup` when updated to .net core, since this was the only way to connect some services and features in .net core. So, now it's all meshed up, some services are registered in one place, some in another, but the internal mechanism is the same. 
We have to think it out.

**Comment by DmitriyKulagin** [comment]
Done. #5571
