### ISSUE TITLE
Overridden editor templates (kendo) don't use attributes

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5577]
nopCommerce version: 4.40+

Steps to reproduce the problem: 
Use **nop-editor** tag helper in view with _asp-disabled="true"_. The attribute will be ignored. Also we should check other attributes.
```
<nop-editor asp-for="MinOrderTotal" asp-disabled="true" />
```

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
