### ISSUE TITLE
signin-facebook route not found after facebook login redirected

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5578]
nopCommerce version: 4.40.2

Steps to reproduce the problem: 
config everything for facebook authenticate, and then click the facebook login button.
After facebook login, I was redirected to "mysite.com/signin-facebook", which is not found in my site! I can see the error log, and I set an breakpoint at "LoginCallback" action of "FacebookAuthenticationController" and its never fired. Besides, I searched the whole source repo and did not find any route releated to "signin-facebook". Seesm there is no such a route in Nop.

One more thing astonishes me is that this issues seems to be around since 2017, and never a solution is found by the people who reported the issue.

**Comment by nextfool** [comment]
In fact if you just visit the "mysite.com/signin-facebook", it says page not found. So it's totally a configuration of route here.

**Comment by glhays** [comment]
I use 4.3 and have Facebook login setup on our site with no custom modifications and it works fine, so I do not believe that it's been an issue since 2017. Just saying... That's all.
________________________________
