### ISSUE TITLE
While uploading/reloading plugin, site goes down

### ISSUE THREAD

**Issue by balajivelu147** [nopSolutions/nopCommerce#5579]
nopCommerce version: 4.4 and latest 

Steps to reproduce the problem:  
1> https://localhost:44351/Admin
2> navigate to local plugins
3> click on reload list of plugins

while uploading plugin, while searching for local plugin... getting this error

![image](https://user-images.githubusercontent.com/34922609/112976370-68792080-9172-11eb-8adc-de6feb545960.png)

**Comment by RomanovM** [comment]
This is how VS works in debug, after app restart you need to manually start IIS or your web server.
