### ISSUE TITLE
Migration runner MigrateUp can execute unapplied older and skipped migrations

### ISSUE THREAD

**Issue by smitvadher** [nopSolutions/nopCommerce#5580]
nopCommerce version: 4.40

https://github.com/nopSolutions/nopCommerce/blob/ecb1bb8eed4d07018d268060a7cbfaea880b2140/src/Libraries/Nop.Data/Migrations/MigrationManager.cs#L193

This line applies all found (and unapplied) migrations up to the given version.
If I have any unapplied migration with a lower version, the "Up" method is going to be executed for that migration too. Even if it is marked with a skip attribute.

So if I have unapplied lower version migration with the SkipMigrationOnUpdate attribute, the up method is being called on app start.

**Comment by skoshelev** [comment]
Closed #5580

**Comment by lintho** [comment]
Is this an issue on 4.40.3? Im trying to upgrade nopcommerce from 3.8 til 4.40.3 and all migrations are throwing errors cause the tables already exists. ive ran all the upgrade scripts. I only have one table with migrationhistory, and thats empty.
