### ISSUE TITLE
Database connections not close

### ISSUE THREAD

**Issue by nduc** [nopSolutions/nopCommerce#5582]
nopCommerce version: 4.40

Steps to reproduce the problem: 
I'm running a Linux version on Digitalocean with Ubuntu 20.04(LTS)x64 Basic instance with 2G of RAM, Postgres, nginx, and Let's Encrypt SSL.  Leaving the app running for about 8 hours I start to get the following exception in /var/log/syslog

Mar 30 23:27:52 bottles systemd[1]: nopCommerce440.service: Scheduled restart job, restart counter is at 235.
Mar 30 23:27:52 bottles systemd[1]: Stopped Example nopCommerce app running on XUbuntu.
Mar 30 23:27:52 bottles systemd[1]: Started Example nopCommerce app running on XUbuntu.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: --- End of stack trace from previous location ---
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueue.FireNextTimers()
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)System.NullReferenceException: Object reference not set to an instance of an object.
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: --- End of stack trace from previous location ---
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueue.FireNextTimers()
Mar 30 23:27:58 bottles nopCommerce440-example[8433]: at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Mar 30 23:27:58 bottles systemd[1]: nopCommerce440.service: Main process exited, code=killed, status=6/ABRT
Mar 30 23:27:58 bottles systemd[1]: nopCommerce440.service: Failed with result 'signal'.

Looking at the full log I noticed that there's a schedule task ran about once a minute.  Checking Schedule Tasks I see that Send email task is scheduled to run once a minute.  It seems like the async task is not closing out the database connection properly.  From the log it looks like the send email task takes a bit longer than one minute to run.  So what happens when the previous instance is not finished yet and a new instance is created?  Does nopCommerce use database connection pool?
By default, Postgres is configured with max_client_conn = 100.  I don't think it's a memory issue as I resized my droplet to 8G of ram and the issue still persists.

Thanks again for the great work on nopCommerce!

**Comment by AndreiMaz** [comment]
already posted at https://github.com/nopSolutions/nopCommerce/issues/5556
