### ISSUE TITLE
Free shipping should NOT be "free" for all shipping methods.

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5583]
nopCommerce version: all

Steps to reproduce the problem: 

As we know that, air shipping is far more expensive than other shipping, e.g. land or  ocean shipping. 

We defined both  land shipping and  air shipping in the system, and we want to offer the "free shipping" to customers only by "land shipping". But if the customer wants a faster way, they should pay the extra cost for air shipping.

The current problem is that, we have some products marked as "free shipping", and also have the "free shipping over X" feature enabled, but if any of the free shipping conditions are met, all shipping methods are free to the customer, but what we really offered is just free land shipping.  

Can this kinda problem be solved in next release?

**Comment by AndreiMaz** [comment]
It's by design (if mark a product as free for shipping, then it'll be free)

You can configure it manually some other way (separate for each shipping method)
