### ISSUE TITLE
Add caching to the "GetAppliedDiscounts" method

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#5587]
nopCommerce version: 4.30 and above

The method DiscountService.GetAppliedDiscounts execute multiple times and need have a caching

**Comment by AndreiMaz** [comment]
Please note that we cannot cache it between HTTP requests because any discount can have discount requirements. And you never know what rule each discount requirement has. Hence you don't know the cache key parameters

**Comment by skoshelev** [comment]
Closed #5587
