### ISSUE TITLE
Setup failed: The field 'Description' has a type currently unknown to Npgsql (OID 16401). You can retrieve it as a string by marking it as unknown, please see the FAQ.

### ISSUE THREAD

**Issue by Hoangnhvt** [nopSolutions/nopCommerce#5588]
nopCommerce version: 4.40.2 

Steps to reproduce the problem: 
I install nop w postgres 13. After press install  button , i receive error [#5304] https://github.com/nopSolutions/nopCommerce/issues/5304) 

Then i execute 'CREATE EXTENSION citext' into DB  and  do reinstalation process . 

Finnaly  'Setup failed: The field 'Description' has a type currently unknown to Npgsql (OID 16401). You can retrieve it as a string by marking it as unknown, please see the FAQ.' appear on the sreen.

How can i do to fix the issue.

Stack trace https://github.com/nopSolutions/nopCommerce/issues/5617

**Comment by nduc** [comment]
I had this same issue before.  You must delete/drop the MigrationVersionInfo table in there and run set up again.

**Comment by AndreiMaz** [comment]
stack trace at https://github.com/nopSolutions/nopCommerce/issues/5617

**Comment by exileDev** [comment]
Closed #5588
