### ISSUE TITLE
Null validation when searching

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5590]
nopCommerce version: 4.40

We should validate for "null" at https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/CatalogController.cs#L321 before the invocation of the "Trim" method.

            if (string.IsNullOrWhiteSpace(term))
                return Content("");
            term = term.Trim();
            if (term.Length < _catalogSettings.ProductSearchTermMinimumLength)
                return Content("");

**Comment by skoshelev** [comment]
Closed #5590
