### ISSUE TITLE
Keep filter and page parameters when returning to any list in the admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5598]
nopCommerce version: 4.40

> When saving a changed Category, or when clicking on the "Return To Categories Page" (if no changes have been made), return to, and highlight, the Category that was just closed.

Source: https://www.nopcommerce.com/boards/topic/90647/admin-section-suggestions
See also: https://www.nopcommerce.com/boards/topic/81622/returning-to-any-list-after-searching-and-editing-1-item-search-information-lost
and https://www.nopcommerce.com/boards/topic/88634/i-have-a-question-about-lists

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
