### ISSUE TITLE
Different 'from' and 'to' fields for store owner notifications

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5599]
Add a way to send store owner notifications to an email different from the one specified in the EmailAccount.

After some discussion decided to add a setting (just an advanced setting without UI) indicating whether such emails should be sent to the same email or to the default one

Source: https://www.nopcommerce.com/boards/topic/14536/store-owner-email and https://www.nopcommerce.com/en/boards/topic/95293/messagetemplate-newcustomernotification-sending-email-to-itself/

**Comment by noptools** [comment]
[https://www.nopcommerce.com/en/boards/topic/95293/messagetemplate-newcustomernotification-sending-email-to-itself#300772](https://www.nopcommerce.com/en/boards/topic/95293/messagetemplate-newcustomernotification-sending-email-to-itself#300772)

it seems odd that this is "on hold / maybe wont".  Team, why?  This seems like a 'bug' to to me...

The email account that "Is default email account", should always be considered the "store owner".
It should be the email address used as the TO email for templates named "... StoreOwnerNotification".
And also for other templates that will be sent TO the store owner, which is indicated at the top of the message template page - for example, NewCustomer.Notification, says:
[b] The message is received by a store owner. [/b]

The hint for "Email account" on the message template says "The email account that will be used to send this message template".  I.e. the 'sender' email account of that template. Nothing more ;)

**Comment by xmenxwk** [comment]
A quick temp fix for one method, since most of OwnerNofication methods are same, they should be moved to a separate method and call it from every other OwnerNotication method. Also since 'NewCustomer.Notification' is a store owner notification, the method name should include 'Owner' and 'NewCustomer.Notification' renamed to 'NewCustomer.OwnerNotification' to make it easily understandable. Same goes for other notifications (if any).


`        public virtual async Task<IList<int>> SendCustomerRegisteredNotificationMessageAsync(Customer customer, int languageId)
        {
            if (customer == null)
                throw new ArgumentNullException(nameof(customer));

            var store = await _storeContext.GetCurrentStoreAsync();
            languageId = await EnsureLanguageIsActiveAsync(languageId, store.Id);

            var messageTemplates = await GetActiveMessageTemplatesAsync(MessageTemplateSystemNames.CustomerRegisteredNotification, store.Id);
            if (!messageTemplates.Any())
                return new List<int>();

            //tokens
            var commonTokens = new List<Token>();
            await _messageTokenProvider.AddCustomerTokensAsync(commonTokens, customer);

            return await messageTemplates.SelectAwait(async messageTemplate =>
            {
                //email account
                var emailAccount = await GetEmailAccountOfMessageTemplateAsync(messageTemplate, languageId);

                var tokens = new List<Token>(commonTokens);
                await _messageTokenProvider.AddStoreTokensAsync(tokens, store, emailAccount);

                //event notification
                await _eventPublisher.MessageTokensAddedAsync(messageTemplate, tokens);

                var defaultEmail = await _emailAccountService.GetEmailAccountByIdAsync(_emailAccountSettings.DefaultEmailAccountId);
                
                var toEmail = defaultEmail is not null ? defaultEmail.Email : emailAccount.Email;
                var toName = defaultEmail is not null ? defaultEmail.DisplayName : emailAccount.DisplayName;

                return await SendNotificationAsync(messageTemplate, emailAccount, languageId, tokens, toEmail, toName);
            }).ToListAsync();
        }`

**Comment by skoshelev** [comment]
Closed #5599
