### ISSUE TITLE
Method VendorService.GetVendorByProductId is not filtering by productId

### ISSUE THREAD

**Issue by epabon** [nopSolutions/nopCommerce#5600]
nopCommerce version: 4.3

Steps to reproduce the problem: Assign a vendor to a product, add that product to the shopping cart and it is going to show the first Vendor that is associated to any product (not necessarily the product that is in the shopping cart)

**Comment by AndreiMaz** [comment]
Thanks. But already fixed at https://github.com/nopSolutions/nopCommerce/issues/4867
