### ISSUE TITLE
Support for latest ES (JavaScript) syntax or Typescript

### ISSUE THREAD

**Issue by uttamughareja** [nopSolutions/nopCommerce#5601]
nopCommerce version: 4.40 +
Since the latest version is using gulp now, It could be used for transpilaton of latest EcmaScript to es5.

This will help us developers writing all latest features, syntax, better cleaner and less code.

I'm not sure if TypeScript is right thing as it has learning curve. 

However, TS doesn't restrict from writing regular javascript (valid js is valid TS) and there're folks knows it and can use it. remaining can still fallback to es5

I request community to share their opinion

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
