### ISSUE TITLE
Wrong data in Bestsellers's Statistic (duplicate product)

### ISSUE THREAD

**Issue by guidosette** [nopSolutions/nopCommerce#5602]
nopCommerce version: 4.3

Steps to reproduce the problem: 
Hi in Admin/Report/Bestsellers, the table has TotalQuantity and TotalAmount wrong.
I see that the products is duplicated.

Change This code:
`var query2 =
                //group by products
                from orderItem in query1
                group orderItem by orderItem.ProductId into g
                select new BestsellersReportLine
                {
                    ProductId = g.Key,
                    TotalAmount = g.Sum(x => x.PriceExclTax),
                    TotalQuantity = g.Sum(x => x.Quantity)
                };`

in 
`var query2 =
                //group by products
                from orderItem in query1**.Distinct()**
                group orderItem by orderItem.ProductId into g
                select new BestsellersReportLine
                {
                    ProductId = g.Key,
                    TotalAmount = g.Sum(x => x.PriceExclTax),
                    TotalQuantity = g.Sum(x => x.Quantity)
                };`

**Comment by exileDev** [comment]
Couldn't reproduce it on the 4.50 version

Closed #5602
