### ISSUE TITLE
Allow sorting in admin list pages(products, categories... etc.)

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5603]
nopCommerce version: all

Hi,
Currently we have many searching criteria in the admin data list page which is good, but the only thing is that sorting is not available. For example, if we create a product, we would like to see it on the top of the list. So it would be really nice to be able to sort all the fields in the list page, we can make the "th" in the table clickable, and pass the sorting field and sorting direction to the controller. 

I saw this kinda issue in the forum for years, I would ask is there any thing block this from fixing?

Thanks.

**Comment by JimGeersinga** [comment]
Would love for this to be added.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization

**Comment by sunil200680** [comment]
this is very important feature, without sorting its useless the grid list

**Comment by brandon7171** [comment]
We have had a few clients complain about this recently.  It looks like the SearchProducts function takes a sort id. Wouldn't this be fairly simple to add another admin setting "Admin Catalog Sort Order" that would at least allow an Admin to select a default sort order with one of the enum values? I think this would be a good add if sorting is not going to be supported.

**Comment by veomex** [comment]
It's really disappointing, all these advanced features and yet many simple and basic things are still missing and need custom work.
