### ISSUE TITLE
Allow sitemap access even when the public store navigation is closed

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5606]
nopCommerce version: 4.40

> We setup nopcommerce to generate sitemap.xml, which is working fine.
> Our problem is, we removed guest navigation so that viewing every pages requires a login (publicstore - allow navigation).
> This has caused nopcommerce to also block sitemap.xml behind login screen, which we don't want.

Source: https://www.nopcommerce.com/boards/topic/90744/sitemapxml-access

We already [ignore](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/CommonController.cs#L285) some action filters when generating a sitemap, let's do it also for the `[CheckAccessPublicStore]`.

**Comment by DmitriyKulagin** [comment]
Closed #5606
