### ISSUE TITLE
Crimea is Ukraine

### ISSUE THREAD

**Issue by bo-bac** [nopSolutions/nopCommerce#5608]
nopCommerce version: 4.4, current

Steps to reproduce the problem: 
1 open App_Data/Localization/states.txt
2 as well in DB

Actual:
RU,Крым,82,True,1  
UA,Донецька область,Дон. обл.,False,5
UA,Луганская область,Луганська область,False,12

Expected:
~RU,Крым,82,True,1~  
UA,Автономна Республіка Крим,АР Крим,True,1
UA,Донецька область,Дон. обл.,True,5
UA,Луганская область,Луганська область,True,12

**Comment by Lsmith998** [comment]
@AndreiMaz How can you discuss this!!! 
Crimea is belong to Ukraine without any discussion.

**Comment by noploser** [comment]
It seems that nopcommerce thinking Crimea is Russia since 2019.

**Comment by badijm** [comment]
Crimea is Ukraine.

**Comment by stopnopcommerce** [comment]
We should stop using this software and continue to develop with it!!! 
Such behavior and companies should be condemned by the community.
**Crimea is Russia this is not by mistake!**
Another evidence we can find here: [https://www.nopcommerce.com/en/all-states-provinces-package](https://www.nopcommerce.com/en/all-states-provinces-package)

**Comment by AndreiMaz** [comment]
We're out of politics. So let's make it easy. Now anyone can include it to any country he/she wants - https://github.com/nopSolutions/nopCommerce/commit/7918322d1914e01680078b1eaba61b46ba409b55

**Comment by stopnopcommerce** [comment]
@AndreiMaz You are very clever, Crimea was removed from Russia, but now where should you put it?

**Comment by bo-bac** [comment]
what about
UA,Донецька область,Дон. обл.,**True**,5
UA,Луганская область,Луганська область,**True**,12

**Comment by skoshelev** [comment]
Hi @bo-bac. Of course, I have corrected this information, thanks for your help.
