### ISSUE TITLE
Showing Wrong Vendor in cart details page

### ISSUE THREAD

**Issue by manwarhossen** [nopSolutions/nopCommerce#5610]
**nopCommerce version: 4,30**

I have 3 vendors. In the products details page showing correct vendor name but in the cart details page showing wrong vendor name. I have created the first Vendor MYSHOP. always Myshop name showing for single or multiples products. 

**Example:** 
1. I have added ABC Shop  Vendor products but in the cart but showing MYSHOP.
2. I have added ABC & XYZ vendors products but in the cart but showing MYSHOP.

**Comment by AndreiMaz** [comment]
Thanks. already fixed at #4867

**Comment by manwarhossen** [comment]
**AndreiMaz** Thanks for the update. seems bug has been fixed on 4.4 version. 
There is any possibility to fixed on 4.3 version?

**Comment by AndreiMaz** [comment]
@manwarhossen You can apply the fix manually. Or upgrade to the latest version

**Comment by manwarhossen** [comment]
@AndreiMaz  I have installed 4.30 without source code. **src** folder is not showing or available.
>>  src/Libraries/Nop.Services/Vendors/VendorService.cs

Would you please explain the file path and exactly which file needs to edit.

**Comment by glhays** [comment]
Without source code, you will not be able to manually fix. You would need a developer to apply the fix. Or upgrade to 4.4.
________________________________
