### ISSUE TITLE
Flyout-cart not updating on back button click

### ISSUE THREAD

**Issue by steinarthrdn** [nopSolutions/nopCommerce#5611]
nopCommerce version:  4.3,4.4

Steps to reproduce the problem: 
- Open Nopcommerce store ( https://frontend.nopcommerce.com/ )
- Press any product (product detail) for example the HTC One M8 Android L 5.0 Lollipop
- Add that product to cart
- Press back on chrome or mouse button
- See that flyout shopping cart does not have the correct quantity of the previously added product.

By flyout shopping cart I am talking about the mini shopping cart in the upper right corner.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
