### ISSUE TITLE
Pagination for product reviews on a product page

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5613]
Currently there is NO paging for product review page. This is bad when you have hundreds or even thousands of reviews for a product.

Let's make it configurable (has paging or nor, page size)

**Comment by loid345** [comment]
It is rather strange that product reviews are on a separate page.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
