### ISSUE TITLE
js minification not working in version 4.40.3

### ISSUE THREAD

**Issue by vubiz-am** [nopSolutions/nopCommerce#5615]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. In admin section enable javascript bundle and minification
2. Try open checkout page

Error: Javascript not loading

![image](https://user-images.githubusercontent.com/54327114/114916004-4dedab00-9df2-11eb-869b-8c97f249e9ef.png)

**Comment by AndreiMaz** [comment]
@vubiz-am It works fine out of the box, we cannot reproduce it.

Furthermore, it checkout URL looks weird (non standard). Are you using a third-party or custom checkout plugin?

**Comment by vubiz-am** [comment]
I am using default PayPal plugin, checkout looks strange because JavaScript didn’t load to this page. Maybe this relates to sevenspike theme. This custom here. Issue only on 4.40. 4.30 has no problems with compressing JS into one bundle.

**Comment by AndreiMaz** [comment]
@vubiz-am 
1. Which exactly default PayPal plugin? Standard or Smart Buttons?
2. One page checkout or multi-step?

**Comment by vubiz-am** [comment]
Its PayPal standard plugin with one page checkout. Maybe sevenspike plugin some how affecting NOP JS bundle functionality. I'll try enable log file for checking any additional errors.

**Comment by AndreiMaz** [comment]
It works fine out of the box

**Comment by vubiz-am** [comment]
Yes, can be result of using sevenspike plugin. I directly tried to open this minified js file 
https://mydomain.com/home/bundles/-eerxu6pghxocnp8rmfuhzkgprhazj-d0rnagj9qdge.min.js
Network status 404, but page looks blank. Usually I can see default 404 IIS page, not in this case. I think JS minification fail on checkout page. Reason unknown. I will check log ...

**Comment by vubiz-am** [comment]
No errors in log file, only log for request:
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://mydomain.com/home/bundles/-eerxu6pghxocnp8rmfuhzkgprhazj-d0rnagj9qdge.min.js 
File itself blank, 404 error.

Would be great if NOP can provide more info here in case of any errors. I can't go to plugin provider and ask to fix it without any related prove.

**Comment by vubiz-am** [comment]
Its interesting file exist: https://mydomain.com/home/bundles/-eerxu6pghxocnp8rmfuhzkgprhazj-d0rnagj9qdge.js
Only difference web page expecting file name with "min":  -eerxu6pghxocnp8rmfuhzkgprhazj-d0rnagj9qdge.min.js

All files here wwwroot\bundles, but some files has "min" some dont

**Comment by RomanovM** [comment]
@vubiz-am I think this is how the BundlerMinifier works, if there are errors in the original files (css or js), it cannot create a minified one, but a name has already been generated. See related issue #3148

**Comment by vubiz-am** [comment]
Issue in "Nop One Page Checkout" plugin. When I uninstall it, all works fine. It would be great if NOP throw any errors in case if file not available. This can save time for us, looking for source of problem.
