### ISSUE TITLE
List Featured Products on home page instead using "show on homepage" of Product

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#5616]
I want the featured product list on the homepage to be grouped by category, or the option to show products that have selected "Shown on homepage" according to the category that contains it. 

I think the website homepage should show more products that will be more intuitive for customers. I hope this issue is done

**Comment by AndreiMaz** [comment]
Thanks for the suggestion. But we would prefer the current way to manage home page products
