### ISSUE TITLE
 An exception was thrown attempting to execute the error handler. Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds)

### ISSUE THREAD

**Issue by Hoangnhvt** [nopSolutions/nopCommerce#5617]
After run deploy nop 1 received exeption: 

Apr 11 03:51:20 vps nopCommerce440-example: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
Apr 11 03:51:20 vps nopCommerce440-example: An exception was thrown attempting to execute the error handler.
Apr 11 03:51:20 vps nopCommerce440-example: Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds)
Apr 11 03:51:20 vps nopCommerce440-example: ---> System.TimeoutException: The operation has timed out.
Apr 11 03:51:20 vps nopCommerce440-example: at Npgsql.ConnectorPool.<>c__DisplayClass38_0.<<Rent>g__RentAsync|0>d.MoveNext()
Apr 11 03:51:20 vps nopCommerce440-example: --- End of stack trace from previous location ---
Apr 11 03:51:20 vps nopCommerce440-example: at Npgsql.NpgsqlConnection.<>c__DisplayClass41_0.<<Open>g__OpenAsync|0>d.MoveNext()
Apr 11 03:51:20 vps nopCommerce440-example: --- End of stack trace from previous location ---
Apr 11 03:51:20 vps nopCommerce440-example: at LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)

I have to restart nopservices everyday to resolve this problem.
Nop 4.4.02 + centos + postgres
You can see full log here
http://upfile.vn/7QBC7aBmNqGg/messages1-txt.html

Can nop team help me to resolve this issue. Many thank

**Comment by AndreiMaz** [comment]
please do not duplicate issues - https://github.com/nopSolutions/nopCommerce/issues/5588
