### ISSUE TITLE
Invoice button in "sales" isn't working

### ISSUE THREAD

**Issue by landgea2016** [nopSolutions/nopCommerce#5622]
nopCommerce version: 3.90

Steps to reproduce the problem: Go into sales, orders, pick an order, try to view the invoice for the order.this is the "invoice" that pops up.
![image](https://user-images.githubusercontent.com/71133640/115126716-46b7d000-9f9f-11eb-8228-7ff085b175b1.png)

**Comment by AndreiMaz** [comment]
I cannot reproduce the issue. It works fine

P.S. Please share the entire stack trace (admin area > system > log)

**Comment by landgea2016** [comment]
Log level
Error
Short message
An unexpected network error occurred.
Full message
System.IO.IOException: An unexpected network error occurred. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count) at System.IO.FileStream.ReadByte() at iTextSharp.text.io.RAFRandomAccessSource.Get(Int64 position) at iTextSharp.text.io.IndependentRandomAccessSource.Get(Int64 position) at iTextSharp.text.pdf.RandomAccessFileOrArray.Read() at iTextSharp.text.pdf.RandomAccessFileOrArray.ReadInt() at iTextSharp.text.pdf.TrueTypeFontSubSet.CreateTableDirectory() at iTextSharp.text.pdf.TrueTypeFontSubSet.Process() at iTextSharp.text.pdf.TtfUnicodeWriter.WriteFont(TrueTypeFontUnicode font, PdfIndirectReference refer, Object[] parms, Byte[] rotbits) at iTextSharp.text.pdf.TrueTypeFontUnicode.WriteFont(PdfWriter writer, PdfIndirectReference piref, Object[] parms) at iTextSharp.text.pdf.FontDetails.WriteFont(PdfWriter writer) at iTextSharp.text.pdf.PdfWriter.AddSharedObjectsToBody() at iTextSharp.text.pdf.PdfWriter.Close() at iTextSharp.text.pdf.PdfDocument.Close() at iTextSharp.text.Document.Close() at Nop.Services.Common.PdfService.PrintOrdersToPdf(Stream stream, IList`1 orders, Int32 languageId, Int32 vendorId) in C:\inetpub\wwwroot\Landgea-v2\Libraries\Nop.Services\Common\PdfService.cs:line 980 at Nop.Admin.Controllers.OrderController.PdfInvoice(Int32 orderId) in C:\inetpub\wwwroot\Landgea-v2\Presentation\Nop.Web\Administration\Controllers\OrderController.cs:line 1868 at lambda_method(Closure , ControllerBase , Object[] ) at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) at System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
IP address
174.233.4.137
Customer
***@***.***<https://www.landgea.com/Admin/Customer/Edit/1467>
Page URL
https://www.landgea.com/admin/order/pdfinvoice?orderid=52778
Referrer URL
/Admin/Order/Edit/52778
Created on
4/18/2021 7:14:39 AM

Matt Hiatt
Chief Engagement Officer
Direct (937)416-3769
Matt@Landgea.com
www.LANDGEA.com



CONFIDENTIALITY NOTICE: This electronic mail transmission and any accompanying documents contain information belonging to the sender which may be confidential and legally privileged. This information is only for the use of the individual or entity to whom this electronic mail transmission was intended. If you are not the intended recipient, any disclosure, copying, distribution, or action taken in reliance on the contents of the information contained in this transmission is strictly prohibited. If you have received this transmission in error, please immediately contact the sender and delete the message.


________________________________

**Comment by landgea2016** [comment]
> I cannot reproduce the issue. It works fine
> 
> P.S. Please share the entire stack trace (admin area > system > log)

We shared the log over the weekend but the issue still continues today.
