### ISSUE TITLE
Adding asp-readonly to input fields

### ISSUE THREAD

**Issue by lyleRpalagar** [nopSolutions/nopCommerce#5623]
nopCommerce version: 
4.40

 Problem:
When creating an input field using <nop-editor> tag helper if you want an input field to not be editable you would use `asp-disabled` 

```
<div class="form-group">
        <div class="col-md-3">
          <nop-label asp-for="Something" />
        </div>
        <div class="col-md-9">
          <nop-editor asp-for="Something" asp-disabled="true"/>
          <span asp-validation-for="Something"></span>
        </div>
      </div>
 ```
![image](https://user-images.githubusercontent.com/4369797/115131210-943e3800-9fb3-11eb-9b1f-2feaea457436.png)

however, there are some use cases for the input field to not be edited but also be able to submit the value of the field as well. `asp-disabled` does not do that because [it adds the attribute `disabled` to the input field](https://www.w3.org/TR/html401/interact/forms.html#disabled), to get the desired functionality, if the nop commerce team deems this to be a worthy addition to the tag helpers, create a `asp-readonly="true" attribute.

workaround that I found was to do attribute `readonly` in a  javascript script after dom has been rendered 
ex:
```
 $(document).ready(function () {
    // note - using asp-disable will not work for IdChart because it will not submit the value.
    $("#@Html.IdFor(model => model.Something)").prop('readonly', true);
````

**Comment by RomanovM** [comment]
See also: #3779

**Comment by DmitriyKulagin** [comment]
After we have implemented the ability to add any attributes to the Html markup([commit](https://github.com/nopSolutions/nopCommerce/commit/aefce288b8622b910365bca2d472ff02b32b91dd)), you can take advantage of this mechanism without using any workarounds. Here is an example of how it will look in the code:

`<nop-editor asp-for="Test" html-attributes="@(new { @readonly = "readonly" })" />`
