### ISSUE TITLE
Option to not copy database ProductWarehouseInventory values when creating new product by copy method

### ISSUE THREAD

**Issue by DB-TORGA** [nopSolutions/nopCommerce#5628]
nopCommerce version: 4.4.0.3

For my shop we often create new products in our catalogue by using the feature to copy from existing product.

We have a multi store, multi vendor environment and multiple product warehouses.

When we create a new product by copy method, the values in ProductWarehouseInventory table are also copied. This causes problems with our inventory management. 

We would like an option to not copy the ProductWarehouseInventory values.  I made a screenshot of what I think the UI should be.

![2021-04-20_17-08-22](https://user-images.githubusercontent.com/67700893/115420148-2e43f180-a1fb-11eb-8e61-94eec2d50af9.jpg)

Steps to reproduce the problem:

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
