### ISSUE TITLE
Shipping Charge Rebate (reward points)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#563]
We would like to offer our customers "Shipping Charge Rebate" i.e. essentially free shipping however first they have to pay for the shipping charge and system should add reward point equal to the shipping charge amount (fixed charges $15) to their account so that they can use it in their next order. 

This creates really good incentive for customer to come back again and again, as they will pay shipping charge on 1st order, we offer those charges back to them in terms of equal reward value for next, during next order they again pay shipping charges which gets rewarded back on next order..etc and cycle keeps continue,. 

However, currently reward does not allow to set a fix reward points per order hence it is not possible to implement for us. 

Source: http://www.nopcommerce.com/boards/t/33396/fixed-reward-point-per-order.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
