### ISSUE TITLE
honeypot enhancement

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5630]
Hi,
Can we add more feature to the honeypot technique to better get rid of some really "smart" bots?
1. able to use a custom name of the honeypot input.
2. able to use custom css styles to hide the honeypot input.
3. able to add honeypot input to pages other then registration page, just like the reCaptcha.
Thank you.

**Comment by AndreiMaz** [comment]
@nextfool Thanks
1. You already can set it by updating the "securitysettings.honeypotinputname" setting
2. It'll require customization like for any other input in nopCommerce
3. Currently we don't plan to add to other pages, the registration only
