### ISSUE TITLE
Contact us - changing url slug doesn't work as expected

### ISSUE THREAD

**Issue by purplepiranha** [nopSolutions/nopCommerce#5633]
nopCommerce version: 4.4

Steps to reproduce the problem: 

Change the url slug for the ContactUs topic to something other than contactus.

The contact form is still displayed at url slug 'contactus'
The topic text is displayed without the contact form at the new url.

**Comment by AndreiMaz** [comment]
It doesn't work this way for this form (it's not a topic but a page). You have to edit https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Infrastructure/RouteProvider.cs#L85
