### ISSUE TITLE
PDF Invoice file name should be the same as order number

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5634]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. Added custom order number format, e.g. {YYYY}-{MM}-{DD}-{ID}
2. click the " PDF Invoice" link to download the pdf file.
3. as you can see, the pdf file name is still order_{ID}.pdf, instead of order_{YYYY}-{MM}-{DD}-{ID}.pdf

**Comment by nextfool** [comment]
or can we make it configurable, just like the order id.

**Comment by RomanovM** [comment]
Duplicate #5138
