### ISSUE TITLE
RoxyFilemanProvider has hard dependencies on NopFileProvider

### ISSUE THREAD

**Issue by mark-at-tusksoft** [nopSolutions/nopCommerce#5635]
nopCommerce version: 4.3

We are currently working on implementing Azure Storage as the underlying provider for INopFileProvider; however, I have concerns about how this will affect RoxyFilemanProvider (and potentially other services) as it makes strong assumptions about the INopFileProvider provided by the IoC container. For example, here is GetFileInfo():

```
/// <summary>Locate a file at the given path.</summary>
/// <param name="subpath">Relative path that identifies the file.</param>
/// <returns>The file information. Caller must check Exists property.</returns>
public IFileInfo GetFileInfo(string subpath)
{
    var pictureService = EngineContext.Current.Resolve<IPictureService>();

    if (_physicalFileProvider.GetFileInfo(subpath).Exists || !pictureService.StoreInDb)
        return _physicalFileProvider.GetFileInfo(subpath);

    var fileProvider = EngineContext.Current.Resolve<INopFileProvider>() as NopFileProvider;
    var roxyFilemanService = EngineContext.Current.Resolve<IRoxyFilemanService>();
    var virtualPath = fileProvider?.GetVirtualPath(fileProvider.GetDirectoryName(_physicalFileProvider.GetFileInfo(subpath).PhysicalPath));
    roxyFilemanService.FlushImagesOnDisk(virtualPath);

    return _physicalFileProvider.GetFileInfo(subpath);
}
```

This method gets an INopFileProvider from the EngineContext but just assumes it is the NopFileProvider and that the provider is using the physical filesystem. From the little bit that I have read, this is primarily used with ckEditor, so if we aren't using ckEditor to upload files I am hoping this won't be an issue for our use-case but I am curious if this is the right approach for implementing Azure Storage as the underlying file provider and if there are any other concerns taking this approach.

**Comment by skoshelev** [comment]
Closed #5635

**Comment by daerogami** [comment]
@skoshelev #5629 does not fully address this issue. That PR only focused on the improper cast. RoxyFilemanProvider still assumes physical filesystem and there are values from _physicalFileProvider being fed into the INopFileProvider as if it is being assumed as a physical filesystem implementation.
I'm honestly not sure why RoxyFilemanProvider is directly using a physicalFileManager and not solely depending on the INopFileProvider from the IoC container. Also, why isn't INopFileProvider injected? There is a great deal of context I don't have around this simply because I'm not that familiar with Roxy nor nopCommerce, yet.

**Comment by skoshelev** [comment]
Hi @daerogami. For RoxyFileman to work, we use the standard approach of registering a static content directory (IApplicationBuilder.UseStaticFiles) like also with Themes, Plugins and Icons. Therefore, we are forced to implement the IFileProvider. In general, if the storage of images in the database is enabled, RoxyFileman uses the file system in the same way as the thumbs mechanism, that is, where the originals of the images are, IPictureService decides
