### ISSUE TITLE
Topics in popups ignore a password

### ISSUE THREAD

**Issue by espiro16** [nopSolutions/nopCommerce#5636]
nopCommerce version: 

Steps to reproduce the problem: 
Enter the administration
Go to Contents-> topics
Edit ConditionsOfUse
select "Password Protected"
put a password and save
Go to general settings
Check "Pop-ups for" terms of service "
save
Go to the store and buy a product
In the terms and conditions click on read 

I resolve change TopicDetail.cshtml
`@if (Model.IsPasswordProtected)
{
    if (isPopup == null || isPopup == false)
    {
        <script type="text/javascript" asp-location="Footer">

        $(document).ready(function () {
            $('#button-password').click(function () {
                var postData = {
                    id: $("#topic-@Model.Id").val(),
                    password: $('#password').val()
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.RouteUrl("TopicAuthenticate")',
                    data: postData,
                    dataType: 'json',
                    success: function (data) {
                        if (data.Authenticated) {
                            $('#ph-topic #ph-title h1').html(data.Title);
                            if ($('#ph-topic #ph-title h1').text().length == 0) {
                                $('#ph-title').hide();
                            }
                            $('#ph-topic .page-body').html(data.Body);
                            $('#ph-password').hide();
                            $('#ph-topic').show();
                            //we need to re-run the validation plugin after the content is loaded after successful authentication
                            $.validator.unobtrusive.parse('#ph-topic');
                        }
                        else {
                            $('#password-error').text(data.Error).fadeIn("slow");
                            $('#ph-password #password').select().focus();
                        }
                    }
                });
                return false;
            });
        });

        $(document).ready(function () {
            $('#ph-topic').hide();
            $('#ph-password #password').select().focus();
        });
        </script>
    }
    else
    {
        //Script for modal mode

        <script type="text/javascript">

        $(document).ready(function () {
            $('#button-password').click(function () {
                var postData = {
                    id: $("#topic-@Model.Id").val(),
                    password: $('#password').val()
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.RouteUrl("TopicAuthenticate")',
                    data: postData,
                    dataType: 'json',
                    success: function (data) {
                        if (data.Authenticated) {
                            $('#ph-topic #ph-title h1').html(data.Title);
                            if ($('#ph-topic #ph-title h1').text().length == 0) {
                                $('#ph-title').hide();
                            }
                            $('#ph-topic .page-body').html(data.Body);
                            $('#ph-password').hide();
                            $('#ph-topic').show();
                            //we need to re-run the validation plugin after the content is loaded after successful authentication
                            $.validator.unobtrusive.parse('#ph-topic');
                        }
                        else {
                            $('#password-error').text(data.Error).fadeIn("slow");
                            $('#ph-password #password').select().focus();
                        }
                    }
                });
                return false;
            });
        });

        $(document).ready(function () {
            $('#ph-topic').hide();
            $('#ph-password #password').select().focus();
        });
        </script>
    }

    <div class="topic-password" id="ph-password">
        <form asp-route="TopicAuthenticate" method="post">
            <input asp-for="Id" id="topic-@Model.Id" type="hidden" />
            <div class="enter-password-title">
                @T("Topic.EnterPassword")
            </div>
            <div class="enter-password-form">
                <input name="password" id="password" type="password" />
                <input type="submit" id="button-password" value="@T("Topic.Button")" class="button-1 topic-password-button" />
            </div>
            <div class="password-error" id="password-error" style="display: none;"></div>
        </form>
    </div>

}`

**Comment by exileDev** [comment]
Closed #5636
