### ISSUE TITLE
Order status with custom icons and colors (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#564]
I didn't liked the look of the customers orders overview. Especially when it comes to the order-status: it's not intuitive. Customers should recognize the status of their order at one glance. 
Is my order still in process? Completed? So I decided to put in some icons and custom colors for better user experience and I wanted to share it with you, maybe someone else is also interested in modifying their templates with that piece of code. 

I'm not an experienced asp/razor coder, so if someone had a better way to solve the issue just post the code. 
The code just compares the order status with the specific language ressource and echoes a css class for the custom icon + color. 

Source: http://www.nopcommerce.com/boards/t/33387/order-status-with-custom-icons-and-colors.aspx 

[AM] Add the following code to appropriate CSS file 
.order-list-page .order-list .order-item .info .order-status.pending{color:orange;font-weight:bold;padding:2px 5px 0 18px;background:url(images/order-status-pending.png) no-repeat left;} 
.order-list-page .order-list .order-item .info .order-status.processing{color:blue;font-weight:bold;padding:2px 5px 0 18px;background:url(images/order-status-processing.png) no-repeat left;} 
.order-list-page .order-list .order-item .info .order-status.complete{color:green;font-weight:bold;padding:2px 5px 0 18px;background:url(images/order-status-complete.png) no-repeat left;} 
.order-list-page .order-list .order-item .info .order-status.cancelled{color:red;font-weight:bold;padding:2px 5px 0 18px;background:url(images/order-status-cancelled.png) no-repeat left;} 

icon files are attached 

also see suggestion for icons here http://www.nopcommerce.com/boards/t/33387/order-status-with-custom-icons-and-colors.aspx#138021

[order-status-icons.zip](https://github.com/nopSolutions/nopCommerce/files/94193/order-status-icons.zip)
![2jabzva](https://cloud.githubusercontent.com/assets/16681184/12390563/3149762c-bdf2-11e5-86b9-8b55a238c2f1.jpg)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
