### ISSUE TITLE
Single page architecture 

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#5640]
nopCommerce version: 4.3

Steps to reproduce the problem: single page application (Spa) is a lot more user friendly and responsive in terms of user experience. I understand it will be quite difficult to be search engine optimised when going down this path but I think it definitely worth the effort and will significantly separate this platform from other. SPA could also help with the scalability of the applications. SPA technology stack might be more complex and tricky from development perspective. 

What are your thoughts?

**Comment by AndreiMaz** [comment]
Thanks for the suggestion. But SPA is not for ecommerce websites. We're leaving it for customization
