### ISSUE TITLE
Docker ALB

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#5643]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
When using aws ALB(application load balance) with ECS docker, I get too many redirects when store SSL is enabled.

I  have seen that X_FORWARDED_PROTO is set by ALB. But also seen some articles that  with docker it does not work, since it also adds the last protocol as http.

I have updated the WelHelper class to get X_FORWARDED_PROTO header with firstordefault but it didnt work.

I think there is a bug with Docker and Loadbalancer configuration

**Comment by streamzyuk** [comment]
I have found that when you set X_Forward_Proto with X_HTTPS_CLUSTER (Which only works on IIS) then it doesnt work. Disable HttpsCluster and select X_Forward_Proto then it works.
Web helper does not check all of them but only one of them.

**Comment by exileDev** [comment]
Closed #5643

It should be solved in #5584. You can reopen this issue if the problem persists.
