### ISSUE TITLE
Incorrect product sorting when default 'ProductSortingEnum' value is used

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5650]
nopCommerce version: 4.40

> The Product_Category_Mapping table has a DisplayOrder column that should be used when selecting sort by 'Position' within a category.  Instead, the Product's DisplayOrder value is being used (default behaviour) within the ProductExtensions static class.

Source: https://www.nopcommerce.com/boards/topic/90845/nop-4403-product-category-mapping-display-order-unexpected-behaviour

Introduced in https://github.com/nopSolutions/nopCommerce/commit/ffa7355ce10f1e0c3daa19f0bea4aa195686efee

**Comment by skoshelev** [comment]
See also premium support ticket [#16065](https://nopcommerce.zendesk.com/agent/tickets/16065)

**Comment by DmitriyKulagin** [comment]
See also premium support ticket [#16083](https://nopcommerce.zendesk.com/agent/tickets/16083)

**Comment by exileDev** [comment]
Closed #5650
