### ISSUE TITLE
More user-friendly way to change quantity of items in the shopping cart

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5653]
In #4343 we've added a more user-friendly way to remove items in the shopping cart, now let's add a user-friendly way to change items quantity:

1. And "+/-" buttons beside each input. Similar to aliexpress.com website or the screenshot below
![example](https://user-images.githubusercontent.com/5019111/214570526-19b3ef90-ce9f-4950-91c9-7f9fef025897.png)
Once clicked an AJAX request will be sent to the server. All shopping cart sub-total and order totals should be re-calculated in this case.

2. Also allow to enter new qty in the input without "-/+" buttons. So a customer will be able to update qty manually. In this case an AJAX request will be sent to a server when input focus is removed from the input

3. So no more need for the 'Update shopping cart' button. It should be removed

4. Ensure that it works fine with the "Allowed quantities" specified as well. No need for "+/-" buttons in this case, just render the dropdownlist as before

**Comment by mike-warren-dev** [comment]
What are your thoughts on using a dropdown menu? I did a quick survey of cart screens on big eCommerce sites, and most of them (Amazon, Ebay, Apple & Target) use dropdowns. Here's Amazon's, for example. You can select any quantity up to 9 with two clicks, and if you want more then you can manually key it in:

![image](https://user-images.githubusercontent.com/90517350/214093629-21f24a25-11b8-4448-8b06-00f675ddaae4.png)

A couple of big sites like Walmart and Shopify (via AllBirds.com) used +/- buttons, but both seemed clunky to me--neither allowed for keyed-in values (potentially requiring a lot of clicks) and both sites did a data refresh every time the user clicked a + or - button.

**Comment by DmitriyKulagin** [comment]
Closed #5653
