### ISSUE TITLE
Portuguese translation amendments

### ISSUE THREAD

**Issue by mateusbellozupko** [nopSolutions/nopCommerce#5657]
nopCommerce version: 
4.3

Steps to reproduce the problem: 

Portuguese translation have a few issues. I have fixed it on my store, but I'm unsure how to export the changes and create a pull request. Could someone help?

**Comment by AndreiMaz** [comment]
Please submit your suggestions at https://crowdin.com/project/nopcommerce (as per https://www.nopcommerce.com/translations)
