### ISSUE TITLE
Do not allow guests to enter news/blog comments if comments are disabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5659]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Disable "Allow guests to leave comments"
2. Go to a news page in public store as a guest
3. Enter a comment and click the "new comment" button
4. Now a guest will see a warning "Only registered users can leave comments"

We should disable inputs and display "Only registered users can leave comments" on a page load in such cases (before POST, not only after submitting)

The same is about blog comments

![image](https://user-images.githubusercontent.com/5019111/116525048-cbc8b080-a8e0-11eb-8ea6-5ee37e89837b.png)

**Comment by skoshelev** [comment]
Closed #5659
