### ISSUE TITLE
Use state id instead of abbreviation and country id instead of code in pickup points 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5660]
nopCommerce version: 4.40

See example [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Pickup.PickupInStore/PickupInStoreProvider.cs#L92) and [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L519)
We should use ids instead of codes, since not all entries may have abbreviations (see the [file](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/App_Data/Localization/states.txt) with states) and codes.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
