### ISSUE TITLE
When you update "Requires coupon code" field of a discount you have to manually clear cache to see the changes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5662]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Apply a pre-created discount "Sample discount with coupon code" to some product on the product edit page
2. Click the "Preview" button on the product edit page
3. Make sure there are no changes in the product price (since the discount has the "Requires coupon code" filed checked)
4. On the "Sample discount with coupon code" discount edit page untick the "Requires coupon code" checkbox and save changes
5. Refresh the product page in the public store
6. See that the price is not updated, the discount is not applied
7. Click the "Clear cache" button in the admin area
8. Refresh the product page in the public store
9. Make sure that the price is updated

**Comment by skoshelev** [comment]
Closed #5662
