### ISSUE TITLE
The "Delete guests" scheduled task failed with the "One or more errors occurred. (Table 'tmp_guestsAddressesToDelete' already exists)"

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5668]
nopCommerce version: 4.40.3
env: ubuntu 20.04 + mysql 8

There is a [bug](https://github.com/nopSolutions/nopCommerce/issues/5625), which is fixed by https://github.com/nopSolutions/nopCommerce/issues/5556 
I think this new exception also has something to do with it.

**Comment by RomanovM** [comment]
@nextfool It's the same exception. Fix from #5556 are not yet in 4.40, it's only in the develop branch, most likely it will be included in the next minor release (e.g. 4.40.4).
