### ISSUE TITLE
Laybuy Plugin

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#5671]
nopCommerce version: AlI versions I assume 

Steps to reproduce the problem: 
I have a client that wanted the pluign for verion 4.2 so I have converted the plugin and it works
But there are a couple of problems I wanted to make you aware with the Price Breakdown Widgets 

**1. Using the plugin with a nop-Templates theme issue in the Product Box - Price Breakdown Widget** 
Using the PublicWidgetZones.ProductBoxAddinfoMiddle causes a display issue 
**DeafultClean Theme**
![Product Box - With Default Theme](https://user-images.githubusercontent.com/34350154/116949561-f1c9c880-acc5-11eb-87c0-9df0c3447f95.png)
**nop-Templates Motion Theme**
![Product Box - With Theme](https://user-images.githubusercontent.com/34350154/116949565-f3938c00-acc5-11eb-98a9-20fb9c2ec10a.png)
I attached the Code to the **PublicWidgetZones.ProductBoxAddinfoAfter** instead
![Product Box - With Theme - Widget Changed to After](https://user-images.githubusercontent.com/34350154/116949717-6997f300-acc6-11eb-87cb-f50b5240ebe6.png)

**2. When using the plugin with a nop-Templates theme - Product Page - Price Breakdown Widget**
Because the CSS is changed and structured differently to the DefaultClean theme the Product Widget Does not display.
**DeafultClean Theme**
![Product Page - No Theme](https://user-images.githubusercontent.com/34350154/116949751-76b4e200-acc6-11eb-9122-31a42b24de98.png)
**nop-Templates Motion Theme**
![Product Page - With Theme](https://user-images.githubusercontent.com/34350154/116949756-77e60f00-acc6-11eb-9c67-988bb950e3d2.png)

Ideally if there was a widget located after the prices box the Price Breakdown could be attached to that widget rather than attaching to the CSS via the PublicWidgetZones.ProductDetailsBottom. 
I used PublicWidgetZones.ProductDetailsOverviewBottom instead and did not use the CSS injection.

**3. Shoping Cart  - Price Breakdown Widget**
If an item has shipping then the widget does not display
**Product shipping required**
![Shopping Cart - With Shipping](https://user-images.githubusercontent.com/34350154/116949882-d01d1100-acc6-11eb-8f4c-5ff1e3db2a9d.png) 
**Product shipping not required**
![Shopping Cart - No Shipping](https://user-images.githubusercontent.com/34350154/116949886-d1e6d480-acc6-11eb-94cf-e8f72cb597f3.png)

I created a new field in the PublicInfoModel 

```
namespace Nop.Plugin.Payments.Afterpay.Models
{
    public class PublicInfoModel : BaseNopModel
    {
        public string PriceValue { get; set; }
    }
}
```

Then stored the Price (less shipping - to be added later) in the model when it is created 
Then used @Model.PriceValue in the script file to get the Price Breakdown

**Comment by RomanovM** [comment]
@SelectSystemsInternational Thanks for the info. Moved to https://github.com/nopSolutions/laybuy-plugin-for-nopcommerce/issues/1.  BTW, the widget on a cart with shipping items is already displayed in 4.40.

**Comment by SelectSystemsInternational** [comment]
There is another question - Is there a reason why you call 
public (Order order, string ErrorMessage) CheckRefunds(int orderId)
everytime you view an order ?

In the case where you use multiple payment methods then of course if you try to check the Refund on an order which is paid via another payment method then it creates an error that is logged. This is because Laybuy does not know about that order number.

![Order not found error](https://user-images.githubusercontent.com/34350154/118236145-12213080-b4d9-11eb-9a14-9437119d095f.png)

Given that in the normal course of events when an Order refund is carried out the Payment Status is set to Refunded.
I assume the above is just a double check that the refund return was captured which is done if the order is ever viewed again
