### ISSUE TITLE
Base64 image Refused to load by CSP in Tinymce

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#5672]
nopCommerce version: 4.4+

Tinymce has the feature is set to convert local image to base64 in Tinymce

An error occurs when copying content containing images in Word into the Tinymce editor. 

"Refused to load the image 'blob:myurl' because it violates the following Content Security Policy directive: "img-src * data:"."

I tried fixing by editing the **web.config** file
`img-src * data:` to `img-src * data: blob:`

And it worked properly.

**Comment by RomanovM** [comment]
@ngtrian Thanks, we leave the config as it is. But it looks like useful information to share on [our forums](https://www.nopcommerce.com/boards).
