### ISSUE TITLE
DataExtensions.RetrieveIdentity() returns wrong Identity values

### ISSUE THREAD

**Issue by KostaVlev** [nopSolutions/nopCommerce#5676]
> DataExtensions.RetrieveIdentity() build internally query to retrieve the last identity column value calling GetMaxValueSql().
> 
> This returns wrong value because the query that is used is "SELECT Max({columnName}) FROM {tableName}" which is not the last identity value. SQL would return the last identity value calling IDENT_CURRENT('Table_Name')
> 
> The steps to reproduce the issue are:
> 
> Insert records
> Go to SQL and delete the records
> Insert again
> The returned IDs will not match the IDs in SQL
> 
> Note: Turning off the SQL Identity cache does not solve the issue

[Issue 2983 - DataExtensions.RetrieveIdentity() returns wrong Identity values](https://github.com/linq2db/linq2db/issues/2983)

Possible solution would be to introduce new extension method similar to [DataExtensions.RetrieveIdentity() ](https://github.com/linq2db/linq2db/blob/5dec345f6d597310c808d369f68fb88322c80f92/Source/LinqToDB/Tools/DataExtensions.cs#L23) which will use `IDENT_CURRENT('Table_Name')` insted of `SELECT Max({columnName}) FROM {tableName}` ?

**Comment by exileDev** [comment]
This API method doesn't work as expected for bulk operations.
Closed #5676
