### ISSUE TITLE
Add  markup to "specification group" names 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5679]
nopCommerce version: 4.40

It seems we missed to notify you about a bug with the markup of the new "Specification Group" names inside the product specification table that we found upon the version 4.40 release.

The html markup for specification group names is currently invalid.
Group names are currently rendered as a single table cell, while the number of the table cells for each specification is 2 - name and value.
The W3C standard is not allowing different number of table cells per row within the same table, this is invalid markup. If one needs different number of cells, they need to use the colspan attribute on the cell that doesn't match the rest of the table. In this case colspan="2" is needed, as long as the rest of the table is always having 2 cells per row. That should be a very simple fix. No css changes are required.

By the way, it's a good idea to add a class name on the <tr> element that contains the group name, so we can differentiate it from other table rows within the same table.

Source: https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/9#285122

**Comment by purehaTime** [comment]
Done with 4.5 version
