### ISSUE TITLE
Pass HtmlHelper to IPageHeadBuilder

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#568]
Would it be possible to pass the htmlHelper to the Generate Scripts function? 

This is a very minor change but it would allow for the customization of script generation to 3rd party plug in with limited change needed for views. 

Source: http://www.nopcommerce.com/boards/t/32524/minor-change-to-ipagdheadbuilder-and-pageheadbuilder.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
