### ISSUE TITLE
customer avatar thumbnail is not updated after new avatar uploaded

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5680]
nopCommerce version: 4.40.3

media setting: save image in file system (instead of database)

Steps to reproduce the problem: 
upload an avatar image first, and then try to update a new one.
Expected behavior: avatar should be updated imminently.
Actual behavior: avatar is NOT updated.

This is caused by the fact that Nop did not delete the generated thumbnail  for new uploaded avatar image. alghou in systems, you can see the original avatar is updated correctly.
To fix this, we need to regenerate the avatar thumb or just delete the old one.

**Comment by skoshelev** [comment]
Closed #5680

**Comment by chensiel** [comment]
@skoshelev Hi, The seoname passed null to update avatar in the method Customer>UploadAvatar, so I think this commit will't fix this issue.
I tried to update avatar at 4.60.3, it doesn't work.

customerAvatar = await _pictureService.UpdatePictureAsync(customerAvatar.Id, customerPictureBinary, contentType, null);
