### ISSUE TITLE
Security / Data Protection Issue - Invoice generation

### ISSUE THREAD

**Issue by purplepiranha** [nopSolutions/nopCommerce#5682]
nopCommerce version: 4.4

Steps to reproduce the problem: 
Set the invoice to be sent out by email when order paid.
Create and order and pay for it.
Email is sent to the customer.

There appear to be 2 issues here:
a) The invoice is saved to wwwroot/files/exportimport/order_<order_guid>_<random_4_digit_code>.pdf which means that the invoice is publicly available.
b) I'm not getting the attachment (I'll investigate further, but it's somewhat less important)

If the invoice is publicly available, so is the customer's name, address, telephone number etc. Whilst it's unlikely that someone will guess that rather long filename with the random code (that may have been acceptable in the 1990s), it's definitely possible for an attacker to script an attack to collect the data. It's also possible that there are sites out there where browsing is enabled for that folder as it will depend on how the web server has been set up.

The problem is with the PrintOrderToPdfAsync method on Nop.Services.Common.PdfService. This saves the file to the mentioned location and then returns it's path. It would be better if it just returned a stream and then the attachment could be created from the stream.

I've tested the invoice generation from a customer's account page and that doesn't have the same issue as the controller action simply returns the file (from a stream) to the customer's browser without saving it anywhere.

**Comment by AndreiMaz** [comment]
It's by design

a) this URL has a random and long URL. No one will find it out until a customer shares it
b) you can enable it in the admin area

**Comment by glhays** [comment]
Any e-commerce site allowing browsing of these folders are ripe for attack in any case, I agree with Andrei. Some relatively easy mods by the site dev can customize the location it is stored and alter the security levels for access.
________________________________
