### ISSUE TITLE
ShipStation Invalid XML

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5684]
nopCommerce version: 4.40+

Steps to reproduce the problem: 

> When we click "Test Connection" in ShipStation, we receive this error message:
>We received an error testing the Custom store: Invalid XML. Error: 'Root element is missing.' We received: ''

Source: Premium support [#16094](https://nopcommerce.zendesk.com/agent/tickets/16094)

**Comment by DmitriyKulagin** [comment]
Closed #5684

**Comment by ushahx** [comment]
Hello I am still receiving the same "Invalid XML. Error: 'Root element is missing.' We received: ''" error on 4.40.4.
What is the user/pwd I am supposed to use? I tried just some generic user/pwd that is not either my store or shipstation user/pwd and also nop and SS specific user/pwd. None of them work.

![image](https://user-images.githubusercontent.com/13063345/162533277-f4a03342-b25f-48b4-ab6a-44aa33849704.png)

**Comment by ushahx** [comment]
I was able to solve this error by getting this fix. https://tedsolves.com/Shipping.ShipStation.zip
