### ISSUE TITLE
Significant deterioration in performance with multiple themes

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5688]
nopCommerce version: 4.40.3

Steps to reproduce the problem: One of our clients runs a large, multi-store, each with a separate theme (5 in total, with a new store being added this summer to take the number to 6).

I've been doing some load testing as we've just recently ported their 4.30 over to 4.40.3. We immediately saw a huge difference in performance over a standard install of 4.40.3, which lead me to start investigating.

After rather a lot of work, I decided to remove all of the themes, apart from one, and performance skyrocketed, in fact surpassing the base install of 4.40.3.

Each theme is identical, apart from colour changes in the css, and each has its own logo.cshtml components file.

Here are some load tests illustrating what's happening (These tests have been carried out on a development version, running two stores in total - exactly the same files as the live site though and running on the same server / sql server).

Also, all tests are just hitting the homepage - I know from experience that once you start hitting category / product pages, performance drops, so I've not tested those.

**1st test (100 clients per second, 1 minute) - 1 theme:**
<table role="table">
<thead>
<tr>
<th>avg(ms)</th>
<th>min(ms)</th>
<th>max(ms)</th>
<th>success</th>
</tr>
</thead>
<tbody>
<tr>
<td>151</td>
<td>115</td>
<td>1265</td>
<td>6000</td>
</tr>
<tr>
<td>152</td>
<td>112</td>
<td>950</td>
<td>6000</td>
</tr>
<tr>
<td>158</td>
<td>110</td>
<td>1137</td>
<td>6000</td>
</tr>
<tr>
<td>156</td>
<td>110</td>
<td>1190</td>
<td>6000</td>
</tr>
</tbody>
</table>

**2nd test (100 clients per second, 1 minute) - 3 themes:**
<table role="table">
<thead>
<tr>
<th>avg(ms)</th>
<th>min(ms)</th>
<th>max(ms)</th>
<th>success</th>
</tr>
</thead>
<tbody>
<tr>
<td>175</td>
<td>116</td>
<td>1221</td>
<td>6000</td>
</tr>
<tr>
<td>158</td>
<td>118</td>
<td>884</td>
<td>6000</td>
</tr>
<tr>
<td>155</td>
<td>113</td>
<td>11279</td>
<td>6000</td>
</tr>
<tr>
<td>171</td>
<td>114</td>
<td>1133</td>
<td>6000</td>
</tr>
</tbody>
</table>

**3rd test (100 clients per second, 1 minute) - 4 themes:**
<table role="table">
<thead>
<tr>
<th>avg(ms)</th>
<th>min(ms)</th>
<th>max(ms)</th>
<th>success</th>
</tr>
</thead>
<tbody>
<tr>
<td>1447</td>
<td>120</td>
<td>6862</td>
<td>4210</td>
</tr>
<tr>
<td>2021</td>
<td>116</td>
<td>11097</td>
<td>3705</td>
</tr>
<tr>
<td>230</td>
<td>118</td>
<td>1992</td>
<td>5511</td>
</tr>
<tr>
<td>780</td>
<td>114</td>
<td>12258</td>
<td>4646</td>
</tr>
<tr>
<td>967</td>
<td>115</td>
<td>9015</td>
<td>4639</td>
</tr>
</tbody>
</table>

Here's the graph for the last test above:
![Screen Shot 2021-05-14 at 16 46 53](https://user-images.githubusercontent.com/12123259/118295688-126afd00-b4d4-11eb-834c-cd7b8fff15d3.png)

**4th test (100 clients per second, 1 minute) - 6 themes:**
<table role="table">
<thead>
<tr>
<th>avg(ms)</th>
<th>min(ms)</th>
<th>max(ms)</th>
<th>success</th>
</tr>
</thead>
<tbody>
<tr>
<td>3383</td>
<td>213</td>
<td>10292</td>
<td>2835</td>
</tr>
<tr>
<td>3005</td>
<td>142</td>
<td>9551</td>
<td>3151</td>
</tr>
<tr>
<td>2224</td>
<td>125</td>
<td>7994</td>
<td>3576</td>
</tr>
<tr>
<td>2487</td>
<td>219</td>
<td>10464</td>
<td>3235</td>
</tr>
<tr>
<td>2799</td>
<td>168</td>
<td>7451</td>
<td>3243</td>
</tr>
</tbody>
</table>

Here's the graph for the last test above:
![Screen Shot 2021-05-14 at 16 53 15](https://user-images.githubusercontent.com/12123259/118296450-e734dd80-b4d4-11eb-9ca9-d8fb2e3b30f5.png)

As you can see, there is a very sharp drop in performance above 3 themes.

I'm dreading telling the client, as we've spent years with performance issues under load - Last year, they were extremely close to moving to another platform, but I told them to hang on for the new 4.40 release.

Also, at 50 clients per second, the response times with 6 themes, is slightly slower than 3. The real issue is once you get above 50 clients per second, and a steady load i.e. 0-500 over 1 minute.

I've had a quick look, and it seems that the working theme name is never cached per store?

Any ideas??

**Comment by untiedshoes** [comment]
So I've spent quite some time on this over the past two days. I was up at 3:30am (couldn't sleep)!

Anyway, I think I've got somewhere with it.

4.40.x now uses a lock, Dictionary, and Initialize for the ThemeProvider - I've now changed it to use a ConcurrentDictionary and removed the lock as the Concurrent is thread-safe anyway (correct me if I'm wrong please?).

`protected ConcurrentDictionary<string, ThemeDescriptor> _themeDescriptors;`
`protected virtual void Initialize()
        {
            //data can be loaded while we waited
            if (_themeDescriptors != null)
                return;

            //load all theme descriptors
            _themeDescriptors =
                new ConcurrentDictionary<string, ThemeDescriptor>(StringComparer.InvariantCultureIgnoreCase);

            var themeDirectoryPath = _fileProvider.MapPath(NopPluginDefaults.ThemesPath);
            foreach (var descriptionFile in _fileProvider.GetFiles(themeDirectoryPath,
                NopPluginDefaults.ThemeDescriptionFileName, false))
            {
                var text = _fileProvider.ReadAllText(descriptionFile, Encoding.UTF8);
                if (string.IsNullOrEmpty(text))
                    continue;

                //get theme descriptor
                var themeDescriptor = GetThemeDescriptorFromText(text);

                //some validation
                if (string.IsNullOrEmpty(themeDescriptor?.SystemName))
                    throw new Exception($"A theme descriptor '{descriptionFile}' has no system name");

                _themeDescriptors.TryAdd(themeDescriptor.SystemName, themeDescriptor);
            }
        }`

Results are as follows (100 clients per second, 1 minute) - 5 themes (compare to the above using 4 themes!):
<table role="table">
<thead>
<tr>
<th>avg(ms)</th>
<th>min(ms)</th>
<th>max(ms)</th>
<th>success</th>
</tr>
</thead>
<tbody>
<tr>
<td>162</td>
<td>1113</td>
<td>956</td>
<td>6000</td>
</tr>
<tr>
<td>177</td>
<td>117</td>
<td>1325</td>
<td>6000</td>
</tr>
<tr>
<td>168</td>
<td>114</td>
<td>119</td>
<td>6000</td>
</tr>
<tr>
<td>164</td>
<td>113</td>
<td>1297</td>
<td>6000</td>
</tr>
</tbody>
</table>

I'll have a look at making 'var text = _fileProvider.ReadAllText(descriptionFile, Encoding.UTF8);' async and also 'var themeDescriptor = GetThemeDescriptorFromText(text);'

**Comment by untiedshoes** [comment]
Making those two methods async, pushes the response times through the roof, and locks the site up!

So, above is the best I can make it at the moment.

**Comment by untiedshoes** [comment]
Some more tests this morning - the above 'fix' limits us to 100 clients per second. 150 clients per second we're looking at average response times of around 2.5 / 3s, using 5 themes, compared to an average of 200ms using one theme and the lock.

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/topic/90943/extremely-slow-response-after-upgrade-from-440-to-4403

**Comment by untiedshoes** [comment]
Changing both IThemeProvider & IThemeContext to Singleton helps with loads of up to 100 clients (leaving the lock in place), but above that, we're seeing slow response times still with 5 themes.

Every so often, we get the dreaded 'Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.' running 150 clients.

**Comment by untiedshoes** [comment]
For now, this can be closed as I've resolved 'our' particular issue. This is still going to be an issue for others, using multiple themes (stores with different themes) until resolved by the team.

Now using Singleton for ThemeProvider:
`services.AddSingleton<IThemeProvider, ThemeProvider>();` 

Also, as we don't allow theme swapping by customers, and once a theme is uploaded for a store, it is not removed, unless a store is deleted, which is very rare, and at most, maybe once a season (football clubs).

Because of this, I don't need to check if a theme exists, or if a customer is allowed to select a theme, which in turn means, I can now cache the Working theme per store.

`public virtual async Task<string> GetWorkingThemeNameAsync()
        {
            if (!string.IsNullOrEmpty(_cachedThemeName))
                return _cachedThemeName;

            var themeName = string.Empty;

            var defaultStoreThemeNameCacheKey = _staticCacheManager.PrepareKeyForDefaultCache(_DefaultStoreThemeCacheKey, await _storeContext.GetCurrentStoreAsync());
            var defaultStoreThemeNameCache = await _staticCacheManager.GetAsync(defaultStoreThemeNameCacheKey, async () => {
                if (string.IsNullOrEmpty(themeName))
                    themeName = _storeInformationSettings.DefaultStoreTheme;
                return themeName;
            });

            _cachedThemeName = defaultStoreThemeNameCache;

            return defaultStoreThemeNameCache;
        }`

Performance, for 6 themes - 150 clients per second, 1 minute.

![6 themes](https://user-images.githubusercontent.com/12123259/118966140-4e351500-b961-11eb-8ba8-7741d0988609.png)

Just a quick note, this is using 4.4.3 without AutoFac.

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/5701
