### ISSUE TITLE
Bug: Latest products never show up on page "newproducts" when setting is lower than "new" products

### ISSUE THREAD

**Issue by mogica** [nopSolutions/nopCommerce#5689]
nopCommerce version: 
4.40.x

Issue: Order by Product.CreatedOn not working when result set is bigger than setting.

Steps to reproduce the problem: 
- Mark x products as New
- set _catalogSettings.NewProductsNumber lower than x
- go to page: "newproducts"
- Latest products are not visible op page

Solution:
Add an extra "orderby p.CreatedOnUtc descending" to the query in "GetProductsMarkedAsNewAsync" in ProductService.cs line 694

Greetings,
Mo

**Comment by exileDev** [comment]
Closed #5689 (by 397e0fde0503094dd80c5fb4072207f9fdce1a2c)
