### ISSUE TITLE
Add a setting to enable/disable the product reviews

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5692]
nopCommerce version: 4.40

Steps to reproduce the problem: 
Let's add setting that will disable the reviews on product page (no matter whether reviews are configured with "allow reviews" or not). By default the reviews should be enabled.

Helps to quickly turn off product reviews without a hassle.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
