### ISSUE TITLE
ARM template azure marketplace does not deploy

### ISSUE THREAD

**Issue by blueflightx7** [nopSolutions/nopCommerce#5694]
#5596

**Comment by skoshelev** [comment]
We are sorry, but the package on the Azure marketplace is assembled only for win-x64 systems, we do not support or plan to support other architectures. For all other architectures, you need to follow the instructions from the [documentation](https://docs.nopcommerce.com/en/developer/tutorials/azure-publish.html). For Azure app service configuration questions, you need to refer to the Azure documentation or write to Azure technical support.

Closed #5694

**Comment by AsafJosefMor** [comment]
Hi @blueflightx7 @skoshelev,

but what about the "HTTP Error 500.31 - ANCM Failed to Find Native Dependencies" which is not related and reproduces even with x64?

**Comment by hubby2004** [comment]
@skoshelev Even with x64, we still have error HTTP Error 500.31 - ANCM Failed to Find Native Dependencies. This is still an issue using the Azure marketplace nopcommerce

**Comment by AsafJosefMor** [comment]
![image](https://user-images.githubusercontent.com/20573715/129714883-22f1c8c2-9008-4bff-9557-84754943354d.png)
