### ISSUE TITLE
Searching product by recent added (Orderby Created on) in Admin Product List 

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#5697]
Searching product by recent added (Orderby Created on) in Admin Product List.

My store, I add a lot of products every day, and I think this search feature will help everyone

**Comment by AndreiMaz** [comment]
Thanks. But we sort them by name by default (more demanded). You can customize the solution to sort by date

**Comment by ngtrian** [comment]
I think the essential basic options should be built-in rather than customized.
Because it can be troublesome every nopCommerce upgrade for normal users

**Comment by AndreiMaz** [comment]
We think the by default products should be sorted by name

**Comment by ngtrian** [comment]
Of course, the default should be sorted by name, but there is an additional order by form as shown below.

![image](https://user-images.githubusercontent.com/4327817/118698195-4f1f5700-b83a-11eb-8ae2-079b26451e90.png)

**Comment by ngtrian** [comment]
Currently, the way to manage my newly added products is to go to the public store > select category, then select **Sort by Created on**
