### ISSUE TITLE
Add setting to turn off order summarization on the admin order list page 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5698]
nopCommerce version: 4.40

> We have a really large number of orders stored in our database 1.5M+. We've noticed a significant delay on the Order List page and tracked it down to the summarization of order totals in the footer. 

Source: https://www.nopcommerce.com/boards/topic/90988/add-setting-to-turn-off-order-summarization-in-admin

We could add that setting in advanced mode (without UI). 

But first of all, we have to check why it's so slow and how we could improve performance.

**Comment by exileDev** [comment]
We haven't found any critical lags for this section. 2 SQL commands run per web request. And with 220k+ orders, the execution time of the SQL command is 140-150ms which I think is normal. But for so large a dataset, we're going to add the setting to disable this section.

**Comment by skoshelev** [comment]
Closed #5698
