### ISSUE TITLE
Remove Autofac, or allow a setting for it not to be used.

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5701]
nopCommerce version: 4.40.x

Steps to reproduce the problem: 

Please remove Autofac from future releases, or allow a setting for it not to be used by those that can afford the extra memory usage that resulted in reverting back to AutoFac.

I'm using 4.40.1, with everything from 4.40.3 (apart from autofac  #5586 & 'Changed sql data provider') applied, and the difference in performance under load is enormous.

I'm not going to post any load tests, as I'm sure you're fed up with me doing that ;)'

-----------------

See https://github.com/nopSolutions/nopCommerce/issues/5688 for the initial discussion

**Comment by AndreiMaz** [comment]
See #5688 for the initial discussion

**Comment by untiedshoes** [comment]
@AndreiMaz can this be looked at please? I'm struggling to get the performance of 4.50 @150 clients / second to match that of my 4.40.4 (using the internal DI, not autofac).

Performance of 4.50 at 50 clients, 100, 150, 0-500 & 0-1000 is down quite a lot based on my own 4.4.4.

**Comment by lintho** [comment]
**If** this is sorted out, could it be a minor release for 4.50?

**Comment by skoshelev** [comment]
Closed #5701

**Comment by skoshelev** [comment]
We have implemented the ability to select an IoC container so that everyone can choose what suits them best. In our tests, both containers showed good results. However, we don't recommend switching from AutoFac as it's slightly faster and more stable in our tests.
