### ISSUE TITLE
arm template does not deploy x86 does not apply here

### ISSUE THREAD

**Issue by blueflightx7** [nopSolutions/nopCommerce#5703]
HI team, this is for deployment directly from the marketplace and not for deployment from a custom arm template. Deployments from the marketplace do not provide the option for some to choose the type of architecture to deploy on. Only App service, database, and monitoring enablement are the choices. Again the template does not work/deploy AS-IS without any intervention, changes, customizations or adjustments from the user and does not provide an option for anyone to able to specify an x86 architecture. This problem still exists, if the team wants to continue ignore it, please close this issue and I will no longer pursue this as this is my 3rd time opening an issue to help resolve this.

**Comment by AndreiMaz** [comment]
@blueflightx7 I've just re-opened a previously closed ticket - https://github.com/nopSolutions/nopCommerce/issues/5596 (closing this one to avoid duplication).
