### ISSUE TITLE
Can't get past this issue

### ISSUE THREAD

**Issue by ancosam** [nopSolutions/nopCommerce#5704]
nopCommerce version: 4.4

Steps to reproduce the problem: I am able to run the setup and I can see the database is created, but the program hangs on line:
private static readonly Lazy<IDataProvider> _dataProvider = new(() => new SqlServerDataProvider(ProviderName.SqlServer, SqlServerVersion.v2012, SqlServerProvider.SystemDataSqlClient), true);
with the error: System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.SqlServer.Types, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

Can somebody steer me in the right direction?

**Comment by AndreiMaz** [comment]
cannot reproduce the issue. it works fine
