### ISSUE TITLE
plugins not valid after clean installation

### ISSUE THREAD

**Issue by chrkorn** [nopSolutions/nopCommerce#5706]
nopCommerce version: main / head as of May 20 2021

Steps to reproduce the problem: 
Clone the sources, open the solution in VS, build the solution, run, install and configure a Postgres DB. Installation will run and then "restart", i.e. shut down the app. After restart, all included plugins show up in the list of warnings as "plugin is not compatible or cannot be loaded". var plugins in InstallController line 270 is empty. The build had produced artifacts for all plugins and placed  them in Plugins/<PluginName>/.

**Comment by AndreiMaz** [comment]
We don't recommend using the "develop" branch. The development version (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/NopVersion.cs) is not updated for plugins yet (4.40). 

Please use sources from https://www.nopcommerce.com/download-nopcommerce
