### ISSUE TITLE
Payment plugin form needs additional labels to be ADA compliant for disabled persons

### ISSUE THREAD

**Issue by kem-storis** [nopSolutions/nopCommerce#5707]
nopCommerce version: 4.3

Steps to reproduce the problem: 
The Nop.Plugin.Payments.Manual plugin includes a credit card entry form which contains an expiration date section. Within that section there are two dropdowns: one for month and one for year. In order for disabled persons who use screen readers or other tools to assist with accessing the site, it would be helpful for both dropdown fields to contain a label as opposed to one label for both dropdowns. This way they are able to determine the purpose of each dropdown individually as it pertains to the expiration date.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
