### ISSUE TITLE
GetProductAttributeCombinationBySku method shouldn't return combination for deleted product

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5711]
nopCommerce version: 4.40+

Steps to reproduce the problem: 
1. I have two ProductAttributeCombinations with the same SKU. First combination for a deleted product
2. Try to get combination by SKU, you will get combination for deleted product.

We must exclude getting the ProductAttributeCombinations for deleted products. Just like we do it in the _GetProductBySkuAsync_.
https://github.com/nopSolutions/nopCommerce/blob/d2859f8ee907514ba04109b2ce5f1c32d92c6dc2/src/Libraries/Nop.Services/Catalog/ProductService.cs#L1201-L1216

**Comment by fizmhd** [comment]
ProductAttributeCombination does not have any propery Deleted

**Comment by holydk** [comment]
@fizmhd We can check to product was deleted via **inner join**

**Comment by fizmhd** [comment]
Ok, now the description makes it more clear
Thanks for the reply.

**Comment by patel-hitesh** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Data;

namespace Nop.Services.Catalog
{
    /// <summary>
    /// Product attribute service
    /// </summary>
    public partial class ProductAttributeService : IProductAttributeService
    {
        #region Fields

        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<PredefinedProductAttributeValue> _predefinedProductAttributeValueRepository;
        private readonly IRepository<ProductAttribute> _productAttributeRepository;
        private readonly IRepository<ProductAttributeCombination> _productAttributeCombinationRepository;
        private readonly IRepository<ProductAttributeMapping> _productAttributeMappingRepository;
        private readonly IRepository<ProductAttributeValue> _productAttributeValueRepository;
        private readonly IStaticCacheManager _staticCacheManager;

        #endregion

        #region Ctor

        public ProductAttributeService(IRepository<Product> productRepository,
            IRepository<PredefinedProductAttributeValue> predefinedProductAttributeValueRepository,
            IRepository<ProductAttribute> productAttributeRepository,
            IRepository<ProductAttributeCombination> productAttributeCombinationRepository,
            IRepository<ProductAttributeMapping> productAttributeMappingRepository,
            IRepository<ProductAttributeValue> productAttributeValueRepository,
            IStaticCacheManager staticCacheManager)
        {
            _productRepository = productRepository;
            _predefinedProductAttributeValueRepository = predefinedProductAttributeValueRepository;
            _productAttributeRepository = productAttributeRepository;
            _productAttributeCombinationRepository = productAttributeCombinationRepository;
            _productAttributeMappingRepository = productAttributeMappingRepository;
            _productAttributeValueRepository = productAttributeValueRepository;
            _staticCacheManager = staticCacheManager;
        }

        #endregion

        #region Methods

        #region Product attributes

        /// <summary>
        /// Deletes a product attribute
        /// </summary>
        /// <param name="productAttribute">Product attribute</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeleteProductAttributeAsync(ProductAttribute productAttribute)
        {
            await _productAttributeRepository.DeleteAsync(productAttribute);
        }

        /// <summary>
        /// Deletes product attributes
        /// </summary>
        /// <param name="productAttributes">Product attributes</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeleteProductAttributesAsync(IList<ProductAttribute> productAttributes)
        {
            if (productAttributes == null)
                throw new ArgumentNullException(nameof(productAttributes));

            foreach (var productAttribute in productAttributes) 
                await DeleteProductAttributeAsync(productAttribute);
        }

        /// <summary>
        /// Gets all product attributes
        /// </summary>
        /// <param name="pageIndex">Page index</param>
        /// <param name="pageSize">Page size</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attributes
        /// </returns>
        public virtual async Task<IPagedList<ProductAttribute>> GetAllProductAttributesAsync(int pageIndex = 0,
            int pageSize = int.MaxValue)
        {
            var productAttributes = await _productAttributeRepository.GetAllPagedAsync(query =>
            {
                return from pa in query
                    orderby pa.Name
                    select pa;
            }, pageIndex, pageSize);

            return productAttributes;
        }

        /// <summary>
        /// Gets a product attribute 
        /// </summary>
        /// <param name="productAttributeId">Product attribute identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute 
        /// </returns>
        public virtual async Task<ProductAttribute> GetProductAttributeByIdAsync(int productAttributeId)
        {
            return await _productAttributeRepository.GetByIdAsync(productAttributeId, cache => default);
        }

        /// <summary>
        /// Gets product attributes 
        /// </summary>
        /// <param name="productAttributeIds">Product attribute identifiers</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attributes 
        /// </returns>
        public virtual async Task<IList<ProductAttribute>> GetProductAttributeByIdsAsync(int[] productAttributeIds)
        {
            return await _productAttributeRepository.GetByIdsAsync(productAttributeIds);
        }

        /// <summary>
        /// Inserts a product attribute
        /// </summary>
        /// <param name="productAttribute">Product attribute</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task InsertProductAttributeAsync(ProductAttribute productAttribute)
        {
            await _productAttributeRepository.InsertAsync(productAttribute);
        }

        /// <summary>
        /// Updates the product attribute
        /// </summary>
        /// <param name="productAttribute">Product attribute</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task UpdateProductAttributeAsync(ProductAttribute productAttribute)
        {
            await _productAttributeRepository.UpdateAsync(productAttribute);
        }

        /// <summary>
        /// Returns a list of IDs of not existing attributes
        /// </summary>
        /// <param name="attributeId">The IDs of the attributes to check</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the list of IDs not existing attributes
        /// </returns>
        public virtual async Task<int[]> GetNotExistingAttributesAsync(int[] attributeId)
        {
            if (attributeId == null)
                throw new ArgumentNullException(nameof(attributeId));

            var query = _productAttributeRepository.Table;
            var queryFilter = attributeId.Distinct().ToArray();
            var filter = await query.Select(a => a.Id)
                .Where(m => queryFilter.Contains(m))
                .ToListAsync();
            
            return queryFilter.Except(filter).ToArray();
        }

        #endregion

        #region Product attributes mappings

        /// <summary>
        /// Deletes a product attribute mapping
        /// </summary>
        /// <param name="productAttributeMapping">Product attribute mapping</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeleteProductAttributeMappingAsync(ProductAttributeMapping productAttributeMapping)
        {
            await _productAttributeMappingRepository.DeleteAsync(productAttributeMapping);
        }

        /// <summary>
        /// Gets product attribute mappings by product identifier
        /// </summary>
        /// <param name="productId">The product identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute mapping collection
        /// </returns>
        public virtual async Task<IList<ProductAttributeMapping>> GetProductAttributeMappingsByProductIdAsync(int productId)
        {
            var allCacheKey = _staticCacheManager.PrepareKeyForDefaultCache(NopCatalogDefaults.ProductAttributeMappingsByProductCacheKey, productId);

            var query = from pam in _productAttributeMappingRepository.Table
                orderby pam.DisplayOrder, pam.Id
                where pam.ProductId == productId
                select pam;

            var attributes = await _staticCacheManager.GetAsync(allCacheKey, async () => await query.ToListAsync()) ?? new List<ProductAttributeMapping>();

            return attributes;
        }

        /// <summary>
        /// Gets a product attribute mapping
        /// </summary>
        /// <param name="productAttributeMappingId">Product attribute mapping identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute mapping
        /// </returns>
        public virtual async Task<ProductAttributeMapping> GetProductAttributeMappingByIdAsync(int productAttributeMappingId)
        {
            return await _productAttributeMappingRepository.GetByIdAsync(productAttributeMappingId, cache => default);
        }

        /// <summary>
        /// Inserts a product attribute mapping
        /// </summary>
        /// <param name="productAttributeMapping">The product attribute mapping</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task InsertProductAttributeMappingAsync(ProductAttributeMapping productAttributeMapping)
        {
            await _productAttributeMappingRepository.InsertAsync(productAttributeMapping);
        }

        /// <summary>
        /// Updates the product attribute mapping
        /// </summary>
        /// <param name="productAttributeMapping">The product attribute mapping</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task UpdateProductAttributeMappingAsync(ProductAttributeMapping productAttributeMapping)
        {
            await _productAttributeMappingRepository.UpdateAsync(productAttributeMapping);
        }

        #endregion

        #region Product attribute values

        /// <summary>
        /// Deletes a product attribute value
        /// </summary>
        /// <param name="productAttributeValue">Product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeleteProductAttributeValueAsync(ProductAttributeValue productAttributeValue)
        {
            await _productAttributeValueRepository.DeleteAsync(productAttributeValue);
        }

        /// <summary>
        /// Gets product attribute values by product attribute mapping identifier
        /// </summary>
        /// <param name="productAttributeMappingId">The product attribute mapping identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute mapping collection
        /// </returns>
        public virtual async Task<IList<ProductAttributeValue>> GetProductAttributeValuesAsync(int productAttributeMappingId)
        {
            var key = _staticCacheManager.PrepareKeyForDefaultCache(NopCatalogDefaults.ProductAttributeValuesByAttributeCacheKey, productAttributeMappingId);

            var query = from pav in _productAttributeValueRepository.Table
                orderby pav.DisplayOrder, pav.Id
                where pav.ProductAttributeMappingId == productAttributeMappingId
                select pav;
            var productAttributeValues = await _staticCacheManager.GetAsync(key, async () => await query.ToListAsync());

            return productAttributeValues;
        }

        /// <summary>
        /// Gets a product attribute value
        /// </summary>
        /// <param name="productAttributeValueId">Product attribute value identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute value
        /// </returns>
        public virtual async Task<ProductAttributeValue> GetProductAttributeValueByIdAsync(int productAttributeValueId)
        {
            return await _productAttributeValueRepository.GetByIdAsync(productAttributeValueId, cache => default);
        }

        /// <summary>
        /// Inserts a product attribute value
        /// </summary>
        /// <param name="productAttributeValue">The product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task InsertProductAttributeValueAsync(ProductAttributeValue productAttributeValue)
        {
            await _productAttributeValueRepository.InsertAsync(productAttributeValue);
        }

        /// <summary>
        /// Updates the product attribute value
        /// </summary>
        /// <param name="productAttributeValue">The product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task UpdateProductAttributeValueAsync(ProductAttributeValue productAttributeValue)
        {
            await _productAttributeValueRepository.UpdateAsync(productAttributeValue);
        }

        #endregion

        #region Predefined product attribute values

        /// <summary>
        /// Deletes a predefined product attribute value
        /// </summary>
        /// <param name="ppav">Predefined product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeletePredefinedProductAttributeValueAsync(PredefinedProductAttributeValue ppav)
        {
            await _predefinedProductAttributeValueRepository.DeleteAsync(ppav);
        }

        /// <summary>
        /// Gets predefined product attribute values by product attribute identifier
        /// </summary>
        /// <param name="productAttributeId">The product attribute identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute mapping collection
        /// </returns>
        public virtual async Task<IList<PredefinedProductAttributeValue>> GetPredefinedProductAttributeValuesAsync(int productAttributeId)
        {
            var key = _staticCacheManager.PrepareKeyForDefaultCache(NopCatalogDefaults.PredefinedProductAttributeValuesByAttributeCacheKey, productAttributeId);

            var query = from ppav in _predefinedProductAttributeValueRepository.Table
                        orderby ppav.DisplayOrder, ppav.Id
                        where ppav.ProductAttributeId == productAttributeId
                        select ppav;

            var values = await _staticCacheManager.GetAsync(key, async () => await query.ToListAsync());

            return values;
        }

        /// <summary>
        /// Gets a predefined product attribute value
        /// </summary>
        /// <param name="id">Predefined product attribute value identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the predefined product attribute value
        /// </returns>
        public virtual async Task<PredefinedProductAttributeValue> GetPredefinedProductAttributeValueByIdAsync(int id)
        {
            return await _predefinedProductAttributeValueRepository.GetByIdAsync(id, cache => default);
        }

        /// <summary>
        /// Inserts a predefined product attribute value
        /// </summary>
        /// <param name="ppav">The predefined product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task InsertPredefinedProductAttributeValueAsync(PredefinedProductAttributeValue ppav)
        {
            await _predefinedProductAttributeValueRepository.InsertAsync(ppav);
        }

        /// <summary>
        /// Updates the predefined product attribute value
        /// </summary>
        /// <param name="ppav">The predefined product attribute value</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task UpdatePredefinedProductAttributeValueAsync(PredefinedProductAttributeValue ppav)
        {
            await _predefinedProductAttributeValueRepository.UpdateAsync(ppav);
        }

        #endregion

        #region Product attribute combinations

        /// <summary>
        /// Deletes a product attribute combination
        /// </summary>
        /// <param name="combination">Product attribute combination</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task DeleteProductAttributeCombinationAsync(ProductAttributeCombination combination)
        {
            await _productAttributeCombinationRepository.DeleteAsync(combination);
        }

        /// <summary>
        /// Gets all product attribute combinations
        /// </summary>
        /// <param name="productId">Product identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute combinations
        /// </returns>
        public virtual async Task<IList<ProductAttributeCombination>> GetAllProductAttributeCombinationsAsync(int productId)
        {
            if (productId == 0)
                return new List<ProductAttributeCombination>();

            var combinations = await _productAttributeCombinationRepository.GetAllAsync(query =>
            {
                return from c in query
                       orderby c.Id
                    where c.ProductId == productId
                    select c;
            }, cache => cache.PrepareKeyForDefaultCache(NopCatalogDefaults.ProductAttributeCombinationsByProductCacheKey, productId));

            return combinations;
        }

        /// <summary>
        /// Gets a product attribute combination
        /// </summary>
        /// <param name="productAttributeCombinationId">Product attribute combination identifier</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute combination
        /// </returns>
        public virtual async Task<ProductAttributeCombination> GetProductAttributeCombinationByIdAsync(int productAttributeCombinationId)
        {
            return await _productAttributeCombinationRepository.GetByIdAsync(productAttributeCombinationId, cache => default);
        }

        /// <summary>
        /// Gets a product attribute combination by SKU
        /// </summary>
        /// <param name="sku">SKU</param>
        /// <returns>
        /// A task that represents the asynchronous operation
        /// The task result contains the product attribute combination
        /// </returns>
        public virtual async Task<ProductAttributeCombination> GetProductAttributeCombinationBySkuAsync(string sku)
        {
            if (string.IsNullOrEmpty(sku))
                return null;

            sku = sku.Trim();

            var query = from pac in _productAttributeCombinationRepository.Table
                        join p in _productRepository.Table on pac.ProductId equals p.Id
                        orderby pac.Id
                        where pac.Sku == sku && !p.Deleted
                        select pac;
            var combination = await query.FirstOrDefaultAsync();

            return combination;
        }

        /// <summary>
        /// Inserts a product attribute combination
        /// </summary>
        /// <param name="combination">Product attribute combination</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task InsertProductAttributeCombinationAsync(ProductAttributeCombination combination)
        {
            await _productAttributeCombinationRepository.InsertAsync(combination);
        }

        /// <summary>
        /// Updates a product attribute combination
        /// </summary>
        /// <param name="combination">Product attribute combination</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task UpdateProductAttributeCombinationAsync(ProductAttributeCombination combination)
        {
            await _productAttributeCombinationRepository.UpdateAsync(combination);
        }

        #endregion

        #endregion
    }
}`

**Comment by Navidliverpool** [comment]
@holydk  I hope I'm getting the issue right.
I have just interchanged a product's SKU with another one and then deleted the first product.
However when I search for the existing product it perfectly work. No attribute combination of the deleted product comes up.
Could I ask you holydk to explain the issue a bit more please ?

**Comment by holydk** [comment]
@Navidliverpool 
1. Create the first product, add a combination to the product with "abc" sku. Then remove it.
2. Create a second product, add a combination to the product with "abc" sku.
3. In _Admin -> Catalog -> Product_, enter "abc" in the "Go directly to product SKU" field and try to navigate to the product.
4. Also you can directly call the _GetProductAttributeCombinationBySkuAsync_ method, you will get the combination for the remote product

**Comment by Navidliverpool** [comment]
@Holydk
Thanks very much for the information. I understand the issue now.

**Comment by holydk** [comment]
Closed #5711
