### ISSUE TITLE
For 5,100+ Products, The Export (All) to Excel does not end.

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#5714]
nopCommerce version:  4.40.3

Hello,
              The Export (All) to Excel of a catalog with 5,100 products does not end.

Could  you introduce a settings, which indicates the threshold,
beyond which the export is split into multiple excell files, downloaded as a single zip file?

You could use a library like: ICSharpCode.SharpZipLib

thank you

**Comment by skoshelev** [comment]
Many thanks for the offer, but most likely, the process of exporting all of your products lasts more than the HTTP query lifetime. We checked the performance of the export of products and have not found explicit problems. In any case, the division into several files and their further archiving will not solve the issue with the waiting time, but only aggravate it. And in addition to this, work with data in the archive will be less convenient.

Closed #5714
