### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by CalebZim** [nopSolutions/nopCommerce#5716]
I am trying to set up nopCommerce, but I keep getting an error message:
![image](https://user-images.githubusercontent.com/54634315/119850979-06bc0500-bedc-11eb-9dc8-9ec1c33e4306.png)
I am using postgreSQl 12. Please help.

**Comment by AndreiMaz** [comment]
"No such host is known" - It should be addressed to your network administrator. DNS is not resolved properly
