### ISSUE TITLE
HTTP Error 500.32 - Failed to load .NET Core host 

### ISSUE THREAD

**Issue by raminfosystems** [nopSolutions/nopCommerce#5718]
nopCommerce Version: 4.40.3_NoSource_Win_x64.zip

Steps to reproduce the problem: Download Package without source code

Make sure you have .Net Runtime 5.0. installed correctly. (True)
Make sure you have SDK installed correctly (True)
Database configured (True)

Download package and unzipped in the folder.
(i.e. htdocs on the Plesk server - VPN SERVER) 
Try to install it but failed to run and throw 500.32 failed to load asp.net core host error. 

A possible solution for this is https://www.nopcommerce.com/en/boards/topic/84750/version-430-32-bit-iis#279787

I am not sure why it causes a problem and not able to run correctly. I think it is carry on as the web. Config file has not correctly configured values as mentioned in the solution.

**Comment by RomanovM** [comment]
It perfectly works on almost all hosting providers, if not in your case you can change the configuration. 
We are not planning to change the web.config file.

**Comment by raminfosystems** [comment]
HI Thank you for the prompt reply. However, I am not sure whether it is related to the new installation or it affected due to previously installed instances. For example, in my case, I have the 4.30 version installed and running for a good few months.  

I think it should be easily replicate on any given environment with windows server 2019 R2 and x64 architecture, with a previously installed version and test with a new version. The behaviour should be replicated in both conditions (such as SDK not installed and SDK and runtimes installed correctly). I am happy to share more if you would like to test it thoroughly.

**Comment by RomanovM** [comment]
@raminfosystems There were no web config changes between 4.30 and 4.40, so I don't think it's a hosting model issue. Most likely the server just doesn't have some .net core (5.0) components.

**Comment by raminfosystems** [comment]
@RomanovM I think 4.30 was depending on .net core 3 and 4.40 runtime is .net 5.0, which I think is a major change. Of course, I could be completely wrong about this. Please guide me.

**Comment by AdrianPT** [comment]
In this kind of situation. If you are using plesk in the hosting service verify if the **ISS Pool user** (IWPG for example) have **permissions** to modify and execute in the root folder of the app.

In the **publish** options try **"SELF CONTAINED"** mode, the only difference between this and "framework dependent" is a few files in .dll format at the moment of the publish, the performance is the same and is a really great solution that allow to have the last version of nopcommerce in every type of environment.

If another error happens, to see the logs you must search the stdoutLogEnabled variable in the web.config file and set to true:
`stdoutLogEnabled="false" -> stdoutLogEnabled="true"`

Later you can consult the logs in the LOGS folder:
`(myhostingfolderoot)\Presentation\Nop.Web\logs`

Good luck in the solution.

**Comment by glhays** [comment]
Anyone who passes by looking at a similar error on their setup, check that you unblocked the zip file after download and before extraction of files.


________________________________
