### ISSUE TITLE
Emails in queue Without registered user

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#5722]
nopCommerce version: 4.3

Steps to reproduce the problem: 

Some person or machine has tried to send email.
as you can see in my email queue several emails were created.

The user with the email "sample@email.tst" is not registered.

Is this problem known? 
![grafik](https://user-images.githubusercontent.com/59456113/120321865-15435b80-c2e4-11eb-9c74-4ca6d01b70e1.png)

**Comment by RomanovM** [comment]
There is no problem. Someone was just trying to subscribe to your store's notifications, no need to register for that. You can disable this feature, see for '[Hide newsletter box](https://admin-demo.nopcommerce.com/Admin/Setting/CustomerUser)' setting.
