### ISSUE TITLE
Add the ability to search for products without a categories in the admin

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5724]
Just add a new item "None" to "Category" dropdown list.

**Comment by Navidliverpool** [comment]
//By adding this bit of code to   Nop.Web/Admin/Areas/Views/Category/List.cshtml    the item "None" will appear in "Category" //as a dropdown list

 <div class="card card-default card-search">
                    <div class="card-body">
                        <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                            <div class="search-text">@T("Admin.Common.None")</div>
                            <div class="icon-collapse"><i class="far fa-angle-@(!hideSearchBlock ? "up" : "down")" aria-hidden="true"></i></div>
                        </div>
                    </div>
                </div>

**Comment by Navidliverpool** [comment]
Could you explain the issue a bit more, please ?

**Comment by glhays** [comment]
What will the option none return from the search of no categories? Items not assigned?
________________________________

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
