### ISSUE TITLE
App Crash Plugin

### ISSUE THREAD

**Issue by hexroot007** [nopSolutions/nopCommerce#5725]
nopCommerce version: 4.4.0.0

Steps to reproduce the problem: I am just adding a free plugin in the application when i add zip file its goes for application restart and does not come live. also if I press reload list of plugin it happens too. 
 _hostApplicationLifetime.StopApplication(); after this method the debugger stops nothing happens and appcrashes.

**Comment by RomanovM** [comment]
You say debugger, I guess it's VS, so it is how VS is working, you need to manually restart the application.

**Comment by hexroot007** [comment]
i have to manually restart the application?. i can not add a plugin too its not added let me try again
