### ISSUE TITLE
Ignore unrenderd section "CatalogFilters" in CategoryTemplate.ProductsInGridOrLines when using ColumnsOne layout

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#5726]
nopCommerce version: 4.40

An message error: "The following sections have been defined but have not been rendered by the page at '/Views/Shared/_ColumnsOne.cshtml': 'CatalogFilters'. To ignore an unrendered section call IgnoreSection("sectionName")."

When I change CategoryTemplate.ProductsInGridOrLines layout to "ColumnsOne"

I think I have to add this line of code: `@await RenderSectionAsync("CatalogFilters", false)`

**Comment by RomanovM** [comment]
Yep, if you want to display this section in the one-column layout you need to render it. 
Please post all your questions on [our forums](https://www.nopcommerce.com/boards).
