### ISSUE TITLE
Upgrade to .NET 6

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5727]
Let's do it as soon as the official release is available.

- https://docs.microsoft.com/aspnet/core/migration/50-to-60
- https://docs.microsoft.com/dotnet/core/compatibility/6.0

**Comment by DmitriyKulagin** [comment]
Done #5727

**Comment by lintho** [comment]
Hello. Is this something one could merge into a 4.40.4 project "easily"?
