### ISSUE TITLE
Filtering products by infinite number of values

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5732]
nopCommerce version: any

There is only filtering products by finite number of choices(checkboxes)

![Screenshot 2021-06-08 at 15 37 39](https://user-images.githubusercontent.com/6122624/121194975-800a0f00-c86f-11eb-93c2-f22c40d1c4d4.png)

There will be nice to add filtering by infinite number of values, currently only price has option for filtering infinite number of values

![Screenshot 2021-06-08 at 15 38 52](https://user-images.githubusercontent.com/6122624/121195200-af208080-c86f-11eb-8b11-34db7266c405.png)

**Comment by RomanovM** [comment]
Thanks for the suggestion. There are many options to display filtering options, e.g. slider (as you propose) or dropdown list (see #459), but it's just a design issue, we don't plan to change the current one and will leave that for customization.

**Comment by goransipic** [comment]
Okay i understand that is design issue how present option type. But on admin part there is only supported filtering by option which only doing filtering by finite numbers of values. There is not any way to define on admin side filtering by infinite numbers only option type is supported.

![Screenshot 2021-06-09 at 14 24 11](https://user-images.githubusercontent.com/6122624/121353956-b3f83980-c92e-11eb-9cf4-7cc8910497ca.png)

**Comment by RomanovM** [comment]
Well, I got it now. It looks like a good idea for a third-party plugin to implement such a feature.
