### ISSUE TITLE
Inject product repository via ctor instead EngineContext in ProductAttributeService

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#5733]
nopCommerce version: 4.40+

#5711 
see commit https://github.com/nopSolutions/nopCommerce/commit/1e15d82eae4ae18e4085ca068bd3a03aceb2fb2b

**Comment by Navidliverpool** [comment]
Can I ask you are product repository and product.cs class the same thing, please ?

**Comment by glhays** [comment]
Navid, research the repository design pattern. Also just FYI the nopCommerce GitHub is for tracking bugs.
________________________________

**Comment by Zalhera** [comment]
Pull request #5745 solves this issue.

**Comment by Navidliverpool** [comment]
@glhays Sorry for late reply and thank you for your comment.

**Comment by skoshelev** [comment]
Closed by https://github.com/nopSolutions/nopCommerce/pull/5745
