### ISSUE TITLE
Fix name of the "back to" button for IWidgetPlugin

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5735]
nopCommerce version: 4.40

> Plugin inherits from `IWidgetPlugin` too (e.g.) `public class SendinbluePlugin : BasePlugin, IMiscPlugin, IWidgetPlugin`
> however, it's being hidden from the widget list `public bool HideInWidgetList => true;`
> so on the plugin configuration page, the breadcrumb should not say  "back to widget list", it should say "back to plugin list" (like it did in 4.30).
> 
> 1. nopCommerce version:  4.40.3
> 2. Expected behavior -
>   Go to the Sendinblue plugin configuration page.
>   The breadcrumb should say "back to plugin list"  (like it did in 4.30)
> 3. Actual behavior - breadcrumb says "back to widget list"
> 4. Steps to reproduce the problem - [look at SendInBlue configuration page](https://admin-demo.nopcommerce.com/Admin/Sendinblue/Configure)

Source: https://www.nopcommerce.com/boards/topic/91220/iwidgetplugin-with-hideinwidgetlist-true-should-show-back-to-plugin-list

**Comment by exileDev** [comment]
Closed #5735
