### ISSUE TITLE
Web Store Context is sometimes caches wrong store

### ISSUE THREAD

**Issue by ArturSprinter** [nopSolutions/nopCommerce#5737]
nopCommerce version: 4.40.3

Steps to reproduce the problem: Create multi-store, setup all hostnames (or at least for store which has higher `DisplayOrder`).

Sometimes when you try to get store context using `GetCurrentStore()` or `GetCurrentStoreAsync()` you will get first store from your stores (one with lowest `DisplayOrder`).
This is probably caused when during first (pre-cached) active store resolution, method is called, but `HttpContext` is inaccessible (so `Host` header is missing) nopCommerce will return and cache first available store.

**Comment by AndreiMaz** [comment]
@ArturSprinter Do you experience this issue only during the application start? Or do you also experience it later (during further HTTP requests)?

**Comment by untiedshoes** [comment]
@AndreiMaz 

Could this be looked at as a matter of urgency please?

Our football club multi-store is showing the same contact us page (info) for all clubs.

As you can imagine, having the same contact info for different clubs is a huge no no!!

FYI, Portsmouth is display order zero (the first).

Worked perfectly fine on 4.30.

[](https://pompey.clubstore.co.uk/contactus)

[](https://blues.clubstore.co.uk/contactus) 

Thanks,
Craig

**Comment by untiedshoes** [comment]
@AndreiMaz 

FYI - We have a dev version of the site, with two stores, and it works as expected. I have restarted the application and still works. 

I don't have access to the server at the moment to recycle the app pool, to see if that is the cause though, but I'll let you know as soon as I can.

**Comment by untiedshoes** [comment]
@AndreiMaz

I know why our issue is related, as we cache the topic blocks, per store.

`var cacheKey = _staticCacheManager.PrepareKeyForDefaultCache(NopModelCacheDefaults.TopicBlockModelCacheKey, systemName, await _storeContext.GetCurrentStoreAsync());`

**Comment by untiedshoes** [comment]
Found 'our' bug - I wasn't passing the current store Id.

`var cacheKey = _staticCacheManager.PrepareKeyForDefaultCache(NopModelCacheDefaults.TopicBlockModelCacheKey, systemName, await _storeContext.GetCurrentStoreAsync());`

`var cacheKey = _staticCacheManager.PrepareKeyForDefaultCache(NopModelCacheDefaults.TopicBlockModelCacheKey, systemName, (await _storeContext.GetCurrentStoreAsync()).Id);`

**Comment by ArturSprinter** [comment]
@AndreiMaz no. I experience this bug when application is started and is working properly.
This is quite weird case, because during single request I receive different values (which should be the same, because it's cached in service which has request scope).

To describe it a bit more precise:
1.  I call `(await _storeContext.GetCurrentStoreAsync()).Id` at a start of component `InvokeAsync` method
2. Later in code I call my service which has injected `IStoreContext` in it's constructor, and in it's method body it calls `GetCurrentStore()` (method is not `async` method)
3. In both places returned `Store` entity is different (in first case it's valid (depending on host)), but in second case it's first store from store list (the value is returned from cache in `WebStoreContext`)

I would like to notice I do not call `GetCurrentStore` method in any class constructor.
.NET often do not has access to `HttpContext` in constructors, so headers will be missing in this scenario.

I only experience this problem in Azure WebApp.
Everything works perfectly on my local machine.

**Comment by skoshelev** [comment]
Hi @ArturSprinter. There may be a problem in registering your service in DI, if you register it not as Scoped then caching may not work correctly
