### ISSUE TITLE
The product picture was uploaded successfully, but the picture disappeared after clicking Save button.

### ISSUE THREAD

**Issue by AlienYMin** [nopSolutions/nopCommerce#5738]
nopCommerce version: 4.40.3

Steps to reproduce the problem: The product picture was uploaded successfully, but the picture disappeared after clicking Save button.
![QQ截图20210617182804](https://user-images.githubusercontent.com/32658641/122380068-1211c600-cf9a-11eb-9e39-7d51525dd2c7.png)
![QQ截图20210617182850](https://user-images.githubusercontent.com/32658641/122380067-1211c600-cf9a-11eb-8460-b2cb83cfab0d.png)

**Comment by untiedshoes** [comment]
Did you click the ‘add product picture’ button?

**Comment by AndreiMaz** [comment]
It works fine on our demo website - https://admin-demo.nopcommerce.com/admin/
