### ISSUE TITLE
Highlight required fields and attributes after click

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#574]
I was playing around with the demo site and went to add a gift certificate to my cart. It popped up an error message at the top of the screen saying "Enter valid recipient name. Enter valid sender name." It would be nice if along with the message it also highlighted the required fields that the message references and places the cursor in the first field. 

Forum source: http://www.nopcommerce.com/boards/t/31139/enhancement-highlight-required-fields-after-click.aspx

P.S. Actually the same should be done for product attributes

**Comment by RomanovM** [comment]
After some investigation decided not to implement this feature and leave it for customization.
