### ISSUE TITLE
Datetime properties aren't accurately mapped on db columns

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5741]
nopCommerce version: 4.40

See an example of this problem in #5595

**Comment by hcholm** [comment]
This is due to a bug introduced in linq2db 3.2.3, see https://github.com/linq2db/linq2db/issues/2811

A workaround in `FluentMigratorMetadataReader.cs:`



                var dataType = SqlDataType.GetDataType(columnSystemType).Type.DataType;
                return new ColumnAttribute
                {
                    Name = column.Name,
                    IsPrimaryKey = column.IsPrimaryKey,
                    IsColumn = true,
                    CanBeNull = column.IsNullable ?? false,
                    Length = column.Size ?? 0,
                    Precision = column.Precision ?? (dataType==LinqToDB.DataType.DateTime2 ? 7 : 0), //workaround linq2b bug in 3.2.3 missing precision
                    IsIdentity = column.IsIdentity,
                    DataType = dataType
                };

**Comment by exileDev** [comment]
Closed #5741
