### ISSUE TITLE
Topic only available to certain roles

### ISSUE THREAD

**Issue by ianpowell2017** [nopSolutions/nopCommerce#5742]
nopCommerce version: latest, however, it has been there for many previous versions

Steps to reproduce the problem: 
Create a topic page and make it available to registered users only.
View topic page whilst NOT logged in -> Page not found error 404.

This suggests that the page link does not work when in fact it is a protected page and only viewable by registered users.  In my mind, it should return a 401 and thus a login page, which would then suggest to the user that the page is protected and not a broken page link.

Additionally when the site is indexed by Google etc then this page is not listed as an error

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
