### ISSUE TITLE
Updating and removing existing themes from the admin area

### ISSUE THREAD

**Issue by ghost** [nopSolutions/nopCommerce#5744]
nopCommerce version: 4.40

Steps to reproduce the problem: 
* Try to update an exists Theme.
* Raise: "A theme with '{themeDescriptor.SystemName}' system name is already defined" exception (_GetThemeDescriptorFromText() method in Libraries\Nop.Services\Themes\ThemeProvider.cs_).

Quick workaround:
In _UploadSingleItem() method in Libraries\Nop.Services\Plugins\UploadService.cs_, replace line:
  descriptor = _themeProvider.GetThemeDescriptorFromText(reader.ReadToEnd());
with:
  descriptor = JsonConvert.DeserializeObject<ThemeDescriptor>(reader.ReadToEnd());

**Comment by RomanovM** [comment]
@jot4p3 Yep, this is how theme uploading currently works, you can only add a new one, not update existing themes.
The suggested workaround is not the best way here, as the theme may already be in use in the runtime, unlike plugins, themes don't have an intermediate installation before use.

So, we should think about how to implement it.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality. Themes rarely change.
