### ISSUE TITLE
DB download button is non http

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#5748]
nopCommerce version: 
4.40.3

Steps to reproduce the problem: 
1) go to Maintenance Page
2) Click Backup Now
3) Click "download" (it doesnt do anything)
4) Inspect the page I see this:

Mixed Content: The site at 'https://ochapparel.com/' was loaded over a secure connection, but the file at 'https://ochapparel.com/db_backups/DBFILE.bak' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

And this is the HTML (which isnt secure)
<a class="btn btn-default" href="**http**://ochapparel.com/db_backups/DBFILE.bak">Download</a>

My store settings

![image](https://user-images.githubusercontent.com/20989983/123528532-fd2de480-d6b5-11eb-9839-ad9f0034a017.png)

**Comment by RomanovM** [comment]
So, we should reconsider the use of `IWebHelper.GetStoreLocation(false)` throughout the solution, since it leads to the "Mixed Content" error.

**Comment by exileDev** [comment]
Closed #5748 by 7d83105f43390d6ecbfa9bdca202c618916216b6. This problem may still happen in the 4.40.x with proxies, but for the 4.50 version, we refactor it.
