### ISSUE TITLE
CSS Bundling with Base64 (issue in ASP.NET library)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#575]
Forum source: http://www.nopcommerce.com/boards/t/31053/suggestions-for-nopcommerce-34.aspx#126532

Contribution: https://github.com/nopSolutions/nopCommerce/pull/1671

**Comment by shoecake** [comment]
I've created a plugin for this issue at https://github.com/shoecake/SPC.Nop.Plugin.VirtualDirectoryFix (entry in marketplace coming soon).

Perhaps this is the best solution if you don't wish to incorporate into the core. That way if anything changes it will be easy to remove or fix this.
I've created a plugin for this issue at https://github.com/shoecake/SPC.Nop.Plugin.VirtualDirectoryFix (entry in marketplace coming soon).

Perhaps this is the best solution if you don't wish to incorporate into the core. That way if anything changes it will be easy to remove or fix this.
