### ISSUE TITLE
Sendinblue error: Plugin not configured - when 'disabled'.

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#5751]
nopCommerce version: 4.40.x

Steps to reproduce the problem: Install Sendinblue plugin, but don't configure it, then disable the plugin.

Full Error:
`Nop.Core.NopException: Plugin not configured
   at Nop.Plugin.Misc.Sendinblue.Services.SendinblueManager.CreateApiClientAsync[TClient](Func`2 clientCtor)
   at Nop.Plugin.Misc.Sendinblue.Services.SendinblueManager.UpdateContactAfterCompletingOrderAsync(Order order)`

Error relates to One Page Checkout > checkout/OpcConfirmOrder/

**Comment by RomanovM** [comment]
What do you mean by `"disable the plugin"`? There is no way to deactivate this plugin like a payment method or a tax provider, you can just uninstall it, and in this case, such errors should not occur.

**Comment by untiedshoes** [comment]
@RomanovM From the plugins list, click edit, then enabled 'false' :)

**Comment by RomanovM** [comment]
Well, I got it. As I mentioned above, this way of deactivation doesn't work for this plugin. In the next versions, we should remove the ability to disable `IMisc` plugins (e.g. SendinBlue), as this doesn't work correctly for them. 
Now you can just uninstall the plugin if you don't need it.
