### ISSUE TITLE
Excuse me, how is the value of Customerguid generated in the customer table in the database?

### ISSUE THREAD

**Issue by AlienYMin** [nopSolutions/nopCommerce#5752]
nopCommerce version: 4.40.3

Steps to reproduce the problem: In the database ->Customer table
![QQ截图20210628183917](https://user-images.githubusercontent.com/32658641/123623615-3e520000-d840-11eb-92cb-2ffb48f403b5.png)

**Comment by AlienYMin** [comment]
I need to manually generate a batch of users into the database, but in the process of creating, I know all the table relationships, but the generated users still have problems in the foreground display. Is this related to the generation rule of CustomerGuid? Please help me to answer it. Thank you!

**Comment by kava81** [comment]
I think it's a dotnet standard guid function

https://docs.microsoft.com/it-it/dotnet/api/system.guid.newguid?view=net-5.0

Guid g = Guid.NewGuid();

**Comment by RomanovM** [comment]
Please post your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker only.
