### ISSUE TITLE
Uploading the default image from the admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5753]
nopCommerce version: 4.40

> In the following
> `Configuration > Settings > Media Settings`
> Add photo upload to set your default image for products.
> Note: I know you can change it in code, or rename your default photo to match Nop and upload it to respective directories, Just thought this would be a nice feature to add.

Source: https://www.nopcommerce.com/boards/topic/91322/default-product-image

We already have `Media.DefaultImageName`, but the user must still manually put the image to the server. Let's add a way to upload it from the admin area.

**Comment by KotLikeCat** [comment]
Working on it
