### ISSUE TITLE
Google Analytics plugin. Possible wrong conversions value

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5755]
nopCommerce version: 4.40

> Steps to reproduce the problem: 
> 1. Instal Nop 4.4
> 2. Install Google Analytics plugin (add your GA ID in settings)
> 3. Open yourstore.com
> 4. Make order with cart value 1000 or greater $ to see where it is included.
> 5. Check your google analytics statistic (only today results).
> 6. In our case direct source  conversion value is "negative". -1000.

Source: https://www.nopcommerce.com/boards/topic/91318/nop-4403-google-analytics-wrong-conversions-value
and https://www.nopcommerce.com/boards/topic/75296/google-analytics-plugin-negative-conversions-and-channelling
and https://www.nopcommerce.com/boards/topic/95645/google-analytics-conversions-bug

**Comment by DmitriyKulagin** [comment]
Depends on https://github.com/nopSolutions/nopCommerce/issues/6553
