### ISSUE TITLE
Reward points not awarded for orders where points are redeemed

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5764]
This affects many versions of nopCommerce, up to and including 4.4

If a customer places an order and redeems reward points, no new reward points are added for that order.

This is because there is a test in the OrderProcessingService.AwardRewardPointsAsync to see if the order's RewardPointsHistoryEntryId has a value. If it does, no points are awarded.

BUT if the customer redeemed points, then RewardPointsHistoryEntryId will have a value.

Source: https://www.nopcommerce.com/en/boards/topic/91440/reward-points-not-awarded-for-orders-where-points-are-redeemed

**Comment by holydk** [comment]
I can't reproduce issue. The new reward points are added to order after completing.

Closed #5764
