### ISSUE TITLE
NotMapped attribute not working into nop4.3 and nop4.4

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#5766]
nopCommerce version: 4.3 and 4.4

Steps to reproduce the problem: 

1. Add new property into domain class that not exist into table into plugin source code

Example
1. Select "GoogleAuthenticator" plugin 
2. Add any custom property into GoogleAuthenticatorRecord.cs and set this property as NotMapped attribute. but we dont want to add this property into this table. 
3. Now run the project you got error message for this additional property.

![image](https://user-images.githubusercontent.com/10364140/126874513-c28dbcd7-f236-451b-a17f-34728dea31a2.png)

I think one condition is missing into FluentMigratorMetadataReader.cs class
![image](https://user-images.githubusercontent.com/10364140/126032458-ec19d7f0-11e4-4164-8626-19cf13b36c4c.png)

**Comment by exileDev** [comment]
I can't reproduce this issue. Closed #5766

[Here](https://docs.nopcommerce.com/en/developer/tutorials/update-existing-entity.html) is a small guide.

**Comment by sangeetshah** [comment]
@exileDev  I have edited my description with proper example

**Comment by exileDev** [comment]
We'll investigate it one more time. This should be implemented via NopEntityBuilder, for example.

**Comment by exileDev** [comment]
Closed #5766
