### ISSUE TITLE
Error with Linq2DB .any function

### ISSUE THREAD

**Issue by fejango** [nopSolutions/nopCommerce#5767]
nopCommerce version: 4.4

**Steps to reproduce the problem:**  Download developer sourcecode from GitHub. Configure IISExpress for SSL. Start Nop.Web. Fill Form and enter connectionstring to MS SqlServer  (Version 10.0.5500.0).After the installation routine is restarting the app, an error occurs : Microsoft.Data.SqlClient.SqlException: Wrong syntax near 'EXISTS'-Keyword. in class DataMigrations in Method Up Line 29.
_if (!_dataProvider.GetTable<PermissionRecord>().Any(pr => string.Compare(pr.SystemName, "AccessProfiling", true) == 0))._

**Comment by exileDev** [comment]
According to the minimum [system requirements](https://docs.nopcommerce.com/en/installation-and-upgrading/technology-and-system-requirements.html#supported-databases), we support SQL Server since the 11.0 version. On later versions, everything works fine.
Closed #5767
