### ISSUE TITLE
Nesting Datatables implementation

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#5769]
nopCommerce version: 4.40+

Steps to reproduce the problem: 

> I am trying to add couple of nesting DataTable like
> Table1
>   > Table2
>     > Table3
> 
> Everything working fine till Table2 but if I try to expand for Table2 error occurs in console "Cannot read property 'Id' of undefined"  

Source: https://www.nopcommerce.com/en/boards/topic/91445/nesting-datatable-implementation-issue

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
