### ISSUE TITLE
Container ignores datasettings environment variables if datasettings.json does not exist

### ISSUE THREAD

**Issue by mrmarino** [nopSolutions/nopCommerce#5772]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
Run the latest docker container (which does not ship a datasettings.json) and try to set the ConnectionString via environment variables

I believe this check is stopping the section that reads environment variables: 

![image](https://user-images.githubusercontent.com/1873061/126581499-f4f499e6-fda0-44a7-b7a7-db420f41a579.png)

**Comment by DmitriyKulagin** [comment]
This is by design. Environment variables can only override settings when the datasettings.json file exists. Therefore, first, create a file with default settings.

**Comment by mrmarino** [comment]
Hi @DmitriyKulagin! Since this is the docker image provided by nopCommerce, there's no way to create the file without building a new image. Maybe this default should be provided in the container?

This is specially problematic when using services (app services for containers) that do a fresh pull every time the container is started, so a "datasettings.json" never exists. As soon the install process finishes, it restarts the container and every file is reset.

**Comment by DmitriyKulagin** [comment]
Hi @mrmarino! After some discussion, we decided to add the datasettings.json file to the container, although we understand that in some cases it is still impossible to avoid creating our own image based on the official one. Until now, use a new image based on ours.

**Comment by skoshelev** [comment]
Hi @mrmarino We've updated the official image, the environment variables should now work fine.
