### ISSUE TITLE
Incorrect order search in the admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5774]
nopCommerce version: 4.40.3

> Bug in order grid after search apply.
> If you place two order for same product different attribute. then only this issue coming.
> Showing more then one order after search in 4.4.3
> 
> https://www.loom.com/share/a09bc254d0ed42119e45f09a6881e864

Source: https://www.nopcommerce.com/boards/topic/91516/showing-more-then-one-order-after-search-in-443

**Comment by exileDev** [comment]
Closed #5774
