### ISSUE TITLE
Order of category mapping on Edit Product Details page and current Breadcrumb show on the Product Details page

### ISSUE THREAD

**Issue by ngtrian** [nopSolutions/nopCommerce#5776]
nopCommerce version: 4.40

Steps to reproduce the problem: 

I use the sample data available when installing nopCommerce on localhost (Windows)

### When creating a new product: (using SQL Server)
1. Set Category mapping to `Computers >> Desktops`, `Computers >> Notebooks`, `Computers >> Software`
2. On the product detail page, the current breadcrumb is `Computers/Software` 
   =>Means nopCommerce takes the newer category (last) as the main breadcrumb

   ![image](https://user-images.githubusercontent.com/4327817/126891130-6980ca7f-bedf-4bfe-9c14-c74da797c3ed.png)
   (_Screenshot category mapping on the Edit product details_)

3. Sau đó tôi xóa Category mapping `Computers >> Notebooks` và thêm `Electronics` and **Save**
   => Check on the product detail page, the current breadcrumb is `Electronics`
4. Then I added again `Computers >> Notebooks` and **Save**
5. Result on the product detail page, the current breadcrumb is `Computers/Software` still is `Electronics`
   
   ![image](https://user-images.githubusercontent.com/4327817/126887025-c25928d8-1be0-41c7-b85f-19218e7b2d59.png)
   (_Screenshot category mapping on the Edit product details_)

6. I keep adding `Apparel` and `Apparel >> Shoes` => Result current breadcrumb is `Apparel`

![image](https://user-images.githubusercontent.com/4327817/126887188-fac2a1f2-9624-4470-91a6-4420ffa5894d.png)

7. **Create a new product** and and set Category mapping to `Computers`, `Computers >> Desktops`, `Computers >> Notebooks`
=> The current breadcrumb is `Computers`. Means nopCommerce takes the older category (first) as the main breadcrumb

   ![image](https://user-images.githubusercontent.com/4327817/126890855-3d491572-be1d-4120-9c67-3454cc1ac681.png)
(_Screenshot category mapping on the Edit product details_)

8. Continue to add category mapping is `Computers >> Software`
 => The current Breadcrumb is `Computers`. 

9. Delete category mapping `Computers` => current Breadcrumb is `Computers/Software`

### A Question:
- Current Breadcrumb in step 2 is `Computers/Software`, but why in step 5 the Breadcrumb is not `Computer >> Notebooks`, why in step 6 is `Apparel`. And why in step 7 is `Computers`. 
- Exactly which category mapping should be chosen for the product Breadcrumb
- The results do not reflect the correct Category mapping on the Edit product details page (screenshot above)

### Other situation
Repeat the above steps but use **nopCommerce + PostgreSQL**, current BreadCrumb in
Step 1: `Computers >> Notebooks`
Step 2: `Electronics`
Step 5: `Electronics`
Step 6: `Electronics`
Step 7: `Computers`
Step 8: `Computers`
Step 9: `Computers >> Notebooks`

Finally, I don't know exactly which category mapping to get for the current BreadCrumb. I don't know if this is a bug or by design, or where am I doing it wrong

**Comment by AndreiMaz** [comment]
Thanks for suggestion. Duplicated - https://github.com/nopSolutions/nopCommerce/issues/5452 and https://github.com/nopSolutions/nopCommerce/issues/4854 and https://github.com/nopSolutions/nopCommerce/issues/4486 (we don't plan to implement it)

**Comment by ngtrian** [comment]
I think the sorting of categories on the Edit product detail page should be based on "Display order" property of the mapping table. That helps reflect what I see, the first category will have a display order of 1

Ví dụ: Nếu category trên Edit product detail có thứ tự là Category A, Category B thì thuộc tính Display order (mapping table) nên là 1, 2

Currently can only enter tab Product on the Edit category details page to edit Display Order. If there are multiple category mappings to a product, this editing becomes complicated
