### ISSUE TITLE
Reference constraint error with sub category images

### ISSUE THREAD

**Issue by fejango** [nopSolutions/nopCommerce#5778]
**nopCommerce version:** 4.50, MS SQL Server 2016

**Steps to reproduce the problem:** Add Image to Category and save it.  Remove image and save again. -> SqlException: conflict with reference constraint 'FK_PictureBinary_PictureId_Picture_Id'  (see attachment)
![2021-07-27 11_03_56-Window](https://user-images.githubusercontent.com/51709126/127131278-43e184f8-cc6f-4af0-bc08-b62e1b03e4a9.png)

Hint: if you go back to categories overview, the error won't occur any longer.

**Comment by exileDev** [comment]
I couldn't reproduce it. Any details?

**Comment by exileDev** [comment]
Closed #5778
