### ISSUE TITLE
Installation failed when trying to install nopCommerce on macOS Big Sur or may be Linux.

### ISSUE THREAD

**Issue by ampadashi** [nopSolutions/nopCommerce#5782]
nopCommerce version: 4.4

Steps to reproduce the problem: I am trying to run and install nopCommerce 4.4 in macOS Big Sur. The folder of nopCommerce application is located in a folder named "My Projects" which contain space character between My and Projects. In this situation, every time i try to install, i faced with bunch of errors related to some folders permissions (as shown in picture below).

![image](https://user-images.githubusercontent.com/32009041/127819512-7f90d802-fcd6-4483-af8d-7ea00935982e.png)

If I rename the folder and remove space character from folder name, It will be installed without any error.
In order to fix this issue, we have to modify CheckPermissionsInUnix method (line no.184 and 185) in FilePermissionhelper.cs located in Nop.Web.Framework\Security folder. We must place {path} variable in both lines to double or single quote.

**Comment by skoshelev** [comment]
Closed #5782
