### ISSUE TITLE
Bug in NopEditorTagHelper

### ISSUE THREAD

**Issue by ampadashi** [nopSolutions/nopCommerce#5783]
nopCommerce version: 4.4

Steps to reproduce the problem: NopEditorTagHelper has different editor templates. In almost all templates, some javascript code for Kendo will be generated depending on the type of the editor. The generated javascript code can raise an error in some languages and cultures like Persian (Iran), specially when the type of input is Int32 or Decimal. You can find the body of error in the picture below:

![image](https://user-images.githubusercontent.com/32009041/128026359-e01e0f52-0496-42b4-b0cc-93bf3fd4a885.png)

The generated script works fine in English language but, when we set Persian as default language of the site, In some part of Admin panel we face with some validation errors. As an example, Configuration > Settings > General Settings.
So, in order to investigate on this issue, add Persian (Iran) language in admin panel and download its language pack. Then go to the Configuration > Settings > General Settings and set the language to FA from language switcher in header of the page. Try to save the current setting. You will be faced with validation error as below:

![image](https://user-images.githubusercontent.com/32009041/128028511-287d5689-1e18-44a6-bec2-ad7f3f55e414.png)

I think the cause of the error is the old bug of ASP.NET Core Razor engine when try to set a value to any javascript variable using @Html.Raw() razor helper. I have already fix this problem from the EditorTemplates views for Int32.cshtml, Int32Nullable.cshtml, Double.cshtml, Decimal.cshtml and DecimalNullable.cshtml. In the code block below, you can see the changes that I have made in Int32.cshtml view:

     $(document).ready(function() {    
        $("#@Html.IdForModel()").kendoNumericTextBox({
            min: parseInt('@Html.Raw(int.MinValue)'),
            max: parseInt('@Html.Raw(int.MaxValue)'),
            decimals: 0,
            restrictDecimals: true,
            format: "# @postfix"
        });
     });

I have wrapped @Html.Raw(int.MinValue) in quotes then try to parse it to Int. After this modification, everything is working fine. Please let me know if you have any idea about this issue.

**Comment by ampadashi** [comment]
There's something wrong with the culture. The minus character is not really -. It's Left-to-right mark which cannot be accepted as numeric value in javascript. It's even the same for plus character.

**Comment by DmitriyKulagin** [comment]
The problem arises because the kendo culture settings are different from the CLDR (fa-IR Arabic culture) settings, so an error occurs when validating the model on the client. Since we cannot influence this problem on our part, we plan to stop using kendo components in the future.

Further discussion is moved to this issue - https://github.com/nopSolutions/nopCommerce/issues/5756

**Comment by ampadashi** [comment]
> The problem arises because the kendo culture settings are different from the CLDR (fa-IR Arabic culture) settings, so an error occurs when validating the model on the client. Since we cannot influence this problem on our part, we plan to stop using kendo components in the future.
> 
> Further discussion is moved to this issue - #5756

Dear, I think stop using kendo component will not solve the problem completely. In client side validation, it will help. But, there are a few things should be considered.
Last night, I installed a plugin developed by Seven Spikes (nopTemplate). The culture of my website is fa-IR. One of the viewmodel properties, has been hard coded in the view and the value was -1. Minus character (-) in fa-IR is not the exact minus that is used in en-US culture. It's actually Left-to-Right Mark (LTM) which its charset is different. So, every time I tries to save the form, because of that value (-1), it failed. As the culture of my website is fa-IR, It only accept LTM minus when we send the form to the controller. About the other characters like decimals, data, plus and etc. , it's the same. So, if you stop using kendo component, only client side validation problem will be fixed.
I'm working on finding the best solution but, honestly, i couldn't find it yet. All the solutions has their cons and pros. I hope i could find the best one.

**Comment by moonch22** [comment]
Hello , I am facing similar issues with validating datatype double with kendo numeric text box when the culture is not "en" specifically with RTL cultures such as Arabic.
Is there any update on this forum.
your help is appreciated.
Thanks
