### ISSUE TITLE
In which directory can i find the Assembly (.dll) that contains the interfaces for design-by-contract plugin development?

### ISSUE THREAD

**Issue by jayjupdhig** [nopSolutions/nopCommerce#5785]
As title says: https://www.nopcommerce.com/de/boards/topic/91578/in-which-directory-can-i-find-the-assembly-dll-that-contains-the-interfaces-for-design-by-contract-p#287275

Thank you very much for your feedbacks.

**Comment by AndreiMaz** [comment]
PLease do not duplicate questions on our forum. GitHub is for work items only

**Comment by jayjupdhig** [comment]
ok...

**Comment by jayjupdhig** [comment]
-> https://github.com/nopSolutions/nopCommerce/issues/5946

**Comment by jayjupdhig** [comment]
-> https://www.nopcommerce.com/en/boards/topic/92458/an-exception-was-thrown-while-activating-%CE%BBfluentmigratorrunneriversionloader-on-debian-11-bullseye/page/2#290093
