### ISSUE TITLE
Fix the namespace of the AddOrderRewardPointsHistoryFK class

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5786]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. Open the AddOrderRewardPointsHistoryFK file
2. See that it has "Nop.Data.Migrations.Indexes" namespace which should actually be "Nop.Data.Migrations.ForeignKeys"

**Comment by skoshelev** [comment]
Closed #5786
