### ISSUE TITLE
robots.txt pointing to wrong sitemap in multi-language store

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5791]
nopCommerce version: 4.40

> Example of what is being displayed at the top of the auto-generated robots.txt file for my multi-store/multi-language nop:
> ```
> User-agent: *
> Sitemap: https://domain.com/en/sitemap.xml
> Sitemap: https://domain.com/fr/sitemap.xml
> Sitemap: https://domain.com/de/sitemap.xml
> Host: https://domain.com/
> ```
> 
> The 3 Sitemaps listed above come back as HTTP ERROR 404.
> 
> Shouldn't the correct sitemap be the following, which works as a combined sitemap for all languages?
> ```
> Sitemap: https://domain.com/sitemap.xml
> ```
> 
> This one works and Google seems happy with it.

Source: https://www.nopcommerce.com/boards/topic/91616/nop4404-robotstxt-pointing-to-wrong-sitemap-in-multi-language-store

Introduced in #5217

**Comment by exileDev** [comment]
Closed #5791
