### ISSUE TITLE
Decimal quantity feature

### ISSUE THREAD

**Issue by sencagri** [nopSolutions/nopCommerce#5794]
Hi,

We have been in retail sector and developing accounting and POS systems since 1996. We generally work with markets, greengrocers etc. In the last 6 months, our customers demanded e commerce application. We have found and liked nopCommerce. We have active 6k customers and planning to install e commerce application %10 of them. 

Everything was almost fine until we see there is no decimal quantity. I have downloaded the source code and changed all fields with decimal and did the required work and it worked.

Now, this version works in 10 different customer check the sample pages below;

[Decimal quantity sample page](https://bizimpaket.com/domates-kg-S4719B4719)
[Interger quantity sample page](https://bizimpaket.com/aly-baklavalik-boreklik-yufka-800-gr-adet-S6089B6089)

But this approach comes with big problems:

1. Some of external plugins created by noptemplates etc. becomes not installable. (Which creates a huge problem)
2. When I pull bug-fix branch into my local it conflicts all the time which is expected but it is not sustainable
3. We have using noptemplates themes in these stores when I change from int to decimal. I needed to format all the fields based on its unit type (piece or weight), but noptemplates javascript files all minified and obfuscated so I hardly find these files and changed it. Every time I try to setup a new app this drives me crazy.

So at that point I offer you I can create a PR for 4.4 and later. But you guys should give me a promise :) I can do the big work and you won't ignore or refuse it. At this stage this becomes huge problem for me.

Cheers.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. Please see https://github.com/nopSolutions/nopCommerce/issues/232
