### ISSUE TITLE
Database connection information not correct at Install wizard

### ISSUE THREAD

**Issue by chendelin1982** [nopSolutions/nopCommerce#5795]
nopCommerce version:  docker:latest

![image](https://user-images.githubusercontent.com/16741975/129671284-fa1a130d-8aaa-4e83-8157-addcf905cf12.png)

Steps to reproduce the problem: 

Install wizard, database settings. If select the Chinese language, and MySQL database, the username and password is still display
**SQLServer**

**Comment by skoshelev** [comment]
Hi, @chendelin1982. This is not a mistake, this is done by design. The inscription is standard for any of the selected database providers, since they are all SQL servers, we decided not to complicate the language packs.

Closed #5795
