### ISSUE TITLE
Some problems using webusb api

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#5798]
nopCommerce version: develop

Steps to reproduce the problem: publish and deploy to iis 10.0

In web.config

`<add name="Permissions-Policy" value="accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=*, usb=()" />`

No permission when open usb port [(instructions)](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API)

It works when I changed to 

` <add name="Permissions-Policy" value="*" />`

Maybe  someone know how to fix it by only change usb permission config.

I use webusb api to connect printers, print shipping labels

**Comment by AndreiMaz** [comment]
If the following code works:
`<add name="Permissions-Policy" value="*" />`

Then you can change it in your installation. By default we would prefer to leave the current settings
