### ISSUE TITLE
docker image tagged as version 4.40 is showing version 4.50

### ISSUE THREAD

**Issue by nishant-newton** [nopSolutions/nopCommerce#5799]
nopCommerce version: 4.40

Steps to reproduce the problem: 
docker run --name nopcommerce -d nopcommerceteam/nopcommerce:4.40

Once docker image is pulled and container is up. Install the nopcommerce and login as Administrator and check the version

![image](https://user-images.githubusercontent.com/5425634/130356961-0114242b-adbb-4585-bd25-a389891ad776.png)

In the source code also  version is mentioned as 4.5

**Comment by nishant-newton** [comment]
One of the major issue with this is plugins and widgets are not loading. If i go into a particular plugin and change the version in the plugins plugin.json then the plugin starts appearing

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/topic/91886/how-to-configure-ssl-in-v4404-using-a-proxy

**Comment by skoshelev** [comment]
We've fixed the issue with the image on the DockerHub, the new one contains exactly 4.40.4 code

Closed #5799
