### ISSUE TITLE
Price adjustment for product/checkout attributes with textbox attribute type

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#580]
Allo a store owner to specify price adjustment for textboxes. But how can we do it? Textbox attributes do not have values. Hence charge cannot be specified 

also see work item 11865 (https://nopcommerce.codeplex.com/workitem/11865 - http://www.nopcommerce.com/boards/t/27525/suggestion-combinablenon-combinable-product-attributes.aspx)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
