### ISSUE TITLE
Checkbox doesn't remember selections unlike previous versions

### ISSUE THREAD

**Issue by Nemes1sX** [nopSolutions/nopCommerce#5800]
nopCommerce version: 
4.40.0
Steps to reproduce the problem: 
1. Check somebody in first page
2. Go to next page and select sonething.
3. Go back previous page and prievious selections isn't checked despite checked earlier
In prievious versions checkbox selections are remembered.

**Comment by Nemes1sX** [comment]
I only I have clue that DataTables GridView model cause issue, because correspending JS file admin.table.js is the same as previous working version

**Comment by mbangali** [comment]
On which screen you are checking?

**Comment by Nemes1sX** [comment]
On orders list table.
