### ISSUE TITLE
IOSS (Import One-Stop Shop)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5801]
Ensure that nopCommerce is fully compatible with IOSS. And apply appropriate changes (if required). And describe it in our documentation

Also note that our Avalara plugin already supports it - https://www.avalara.com/us/en/products/ioss.html?utm_source=nopCommerce-admin-panel&utm_medium=Referral&utm_campaign=nopCommerce-Avalara

**Comment by RomanovM** [comment]
So, it's all just about tax settings configuration. No required changes.
We could add an additional field (IOSS Number) for Order and Shipment entities to enable it to be passed to third-party services, and perhaps fill in this field automatically for appropriate orders. Consider this as a feature later.

**Comment by AndreiMaz** [comment]
After furter inviestigation we think that the best way to go will be using our built-in Avalara plugin. It already supports it - https://www.avalara.com/us/en/products/ioss.html?utm_source=nopCommerce-admin-panel&utm_medium=Referral&utm_campaign=nopCommerce-Avalara
