### ISSUE TITLE
Minor design bug with required editor

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5803]
nopCommerce version: 4.40

> `<nop-editor asp-for="Description" asp-template="RichEditor" asp-required="true"  />`
>As can be seen, * is in the wrong place.

![juiJV3XkRGS0aZjgnH341g](https://user-images.githubusercontent.com/16698464/130751039-638f0ba6-ceba-4dd8-be09-b702f558f6c0.png)

Source: https://www.nopcommerce.com/boards/topic/91728/asp-required-and-asp-template-mismatch

**Comment by exileDev** [comment]
Closed #5803
