### ISSUE TITLE
Pagination dont work on search item list

### ISSUE THREAD

**Issue by gotees** [nopSolutions/nopCommerce#5804]
nopCommerce version: 4.20

Steps to reproduce the problem: On the search bar write an item and press enter. On the product list found, the pagination isn't working. It only displays page "1", if you click on page "2" or any other, it keeps showing page "1".
![search](https://user-images.githubusercontent.com/89529871/130805405-ab64b54b-bd50-46fe-94aa-0b16add28b7b.jpg)
![page](https://user-images.githubusercontent.com/89529871/130805431-7bb1070d-0a8e-47b4-8d56-dcf015eaf422.jpg)

**Comment by RomanovM** [comment]
It works fine on the default theme. I guess the causer is a third-party theme or plugin, contact its developer.
