### ISSUE TITLE
Adding new migration in Nop-Data makes most tests fail

### ISSUE THREAD

**Issue by AndreCarvalho** [nopSolutions/nopCommerce#5805]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
Add a dummy migration to Nop.Data.Migrations namespace, such as

```    
    [NopMigration("2021-08-26 00:00:00")]
    public class DummyMigration : AutoReversingMigration
    {
        public override void Up()
        {
            
        }
    }
```
build and run tests

error root cause is `Microsoft.Data.Sqlite.SqliteException : SQLite Error 6: 'database table is locked'`

This is preventing us from creating any migration in Nop.Data

**Comment by skoshelev** [comment]
This problem is related to #5580.

If you want to add migration directly into Nop.Data library before applying this bugfix, you may use [SkipMigrationOnInstall] attribute to prevent this problem.

Closed #5805
