### ISSUE TITLE
502 - Web server received an invalid response while acting as a gateway or proxy server

### ISSUE THREAD

**Issue by HazimTafour** [nopSolutions/nopCommerce#5808]
nopCommerce Version: 4.3

Misc.Watermark,4.3

Steps to reproduce the problem: 
01-downloaded, upload document with the same error.
"Hello @jkergosi. We know about this issue and we'll fix it in near future. You can fix it yourself, just to rename the file uploadedPlugins.json to uploadedItems.json."

02-trying to copy "Misc.Watermark" folder to the plugin folder into the release.
After install loading will have the following dead page error.

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by AndreiMaz** [comment]
It's a third-party plugin. Please contact its developer
