### ISSUE TITLE
Social media posts when products are added to certain categories

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#581]
We need the ability to mark a category (also at the product level) to create social media posts (e.g. Twitter, Facebook, Google+, etc) upon adding a product. If it is at the category level, then all products added to the category create a social media post defined in the category (unless overridden in the product). If it is at the product level, then only that product creates the specified social media posts. 

Forum source: http://www.nopcommerce.com/boards/t/29045/feature-request-social-media-posts-when-products-are-added-to-certain-categories.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
