### ISSUE TITLE
GDPR compliance. Improve cookie notice (allow visitors to allow or disallow cookies)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5810]
In terms of a cookie notice; simply displaying a consent popup stating that you use cookies isn't enough. The website visitor should have the option to allow or disallow different categories of cookies based upon their preferences, such as functional cookies, marketing cookies, analytical cookies etc.

This is such a basic functional requirement in the UK/EU it would be really good to see nopCommerce pay a bit more attention to it.

Here's an example of the above requirement https://www.akikodesign.com/

Allow a store owner to configure this option (enable or disable) in admin area > configuration > settings > GDRP settings

Source: https://www.nopcommerce.com/en/boards/topic/86984/nopcommerce-not-in-compliance-with-eu-gdpr-cookie-law#287948

Also see https://www.nopcommerce.com/en/boards/topic/86984/nopcommerce-not-in-compliance-with-eu-gdpr-cookie-law/page/2#290943

**Comment by purplepiranha** [comment]
It would be worth looking at https://www.legalmonster.com/blog/accept-all-reject-all/.

I don't think you'll find that the https://www.akikodesign.com/ example is actually fully compliant. There has been a lot said recently about the need to ensure that the opt-in/opt-out buttons being the same size, not links etc., which this article talks about. I realise that they are trying to promote their own product but I think it's one of the best examples that I've seen so far.

It's also really important that there is an easy way for someone to opt out if they have already opted in, which this showcases.

There could also be an option to control the cookie expiry by number of days or to expire all existing cookies from admin - prompting the user to re-accept if you've changed the cookie/privacy policies.

**Comment by purplepiranha** [comment]
Another thought...

Should there be a way for a plugin to register the types of cookies that it uses?
- Necessary
- Analytical
- Marketing

Along with the provider's name, description of what the cookie does and link to providers privacy policy (and cookie name(s), expiry, domain, type) so that it can be displayed?
e.g. (from the LegalMonster link)
![image](https://user-images.githubusercontent.com/15064668/132240875-58cf5b08-66a3-4bcc-abf9-16e1c3cd6145.png)

This would allow all of the information to be automatically generated based on the installed plugins.

**Comment by BaloghDavid90** [comment]
@AndreiMaz: Do you have any news regarding this task? Thank you!

**Comment by AxelAndersen** [comment]
We have a lot of customers complaining about this, very nice to have this implemented

**Comment by exileDev** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
Closed #5810

**Comment by peysche** [comment]
hi,

https://www.nopcommerce.com/de/boards/topic/98245/nopcommerce-not-in-compliance-with-eu-gdpr-cookie-law-v2

mybe you can also comment here or reffer here to the entry ?

THX

**Comment by AndreiMaz** [comment]
Good suggestions at https://www.nopcommerce.com/en/boards/topic/98245/nopcommerce-not-in-compliance-with-eu-gdpr-cookie-law-v2#309421 (especially about https://github.com/osano/cookieconsent)
