### ISSUE TITLE
Possible problem with GenerateOrderGuid method

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5813]
nopCommerce version: 4.40

> For the one page checkout, when I reviewed how the order guid is generated, its saved just after the payment method is selected and also when the opc order is confirmed. There is some logic in the code to keep the same order guid as long as the interval is between the SETTING `paymentsettings.regenerateorderguidinterval`. This value is defaulted to 180 seconds.
> 
> Now the timing of how the order guid is determined whether to use the existing guid or generate a brand new one makes me nervous. I've set the `regenerateorderguidinterval` value very high and will keep an eye out on any further issues.
> 
> You might also want to review the code in [PaymentService.cs](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Payments/PaymentService.cs#L462)
> 
> The line here I believe causes race conditions.
> ```
> DateTime.UtcNow - previousPaymentRequest.OrderGuidGeneratedOnUtc.Value;
> ```
> 
> `DateTime.UtcNow` relies on the webserver time, what about `previousPaymentRequest.OrderGuidGeneratedOnUtc.Value`? There would be more a concern if the deployment is running under a web farm.

Source: https://www.nopcommerce.com/boards/topic/91664/paypal-smart-buttons-plugin-not-working-in-nopcommerce-44#287950

**Comment by skoshelev** [comment]
I checked the logic of the GenerateOrderGuid method again, I did not find any problems in it. Even if the code will work on a server farm, in the worst case, the identifier will be regenerated earlier or later, but this will not affect the logic and functionality of the payment process.

Closed #5813
