### ISSUE TITLE
Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader

### ISSUE THREAD

**Issue by zapp-bit** [nopSolutions/nopCommerce#5814]
nopCommerce version: 4.40.4

Steps to reproduce the problem: Followed step steps to install on ubuntu found here: https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html

small changes when installing included specifying the correct dotnet folder for ubuntu's current version. this was required in the "/etc/systemd/system/nopCommerce440.service" file.

In my case, the current folder for ubuntu version 20.04.3 is "/usr/share/dotnet"

Set up mySQL db as per instructions.

Create root account and an account for nopCommerce to use, enabled mysql_native_password authentication for both users and set passwords. no other action taken to mysql.

website is running on localhost, when going through the "install" process on the first page, I enter the creds to setup for the admin account, followed by my country, I ask it to create sample data, advise to use mysql and to create the database for me. i then enter the connection string because it was insisting I use this or it would throw another error

Data Source=localhost; User ID=[OMITTED FOR PRIVACY]; Password=[OMITTED FOR PRIVACY];

I then click install and receive the following error:

Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.

Please help! Thanks in advance!

**Comment by AndreiMaz** [comment]
Please also see https://github.com/nopSolutions/nopCommerce/issues/4996

**Comment by zapp-bit** [comment]
> Please also see #4996

Thanks for getting back to me, unfortunately, there does not really seem to be a solution on that issue either.

Could you please explain how I can confirm the database created is compatible with the current version nopCommerce. I have followed the instructions posted in the linux section as stated, and i have used the latest available version of Mysql.

Thank you

**Comment by exileDev** [comment]
@zapp-bit We'll try to reproduce, but can you provide information from ~\Log directory with enabled stdout in the web.config file

**Comment by zapp-bit** [comment]
> @zapp-bit We'll try to reproduce, but can you provide information from ~\Logs directory with enabled stdout in the web.config file

Thanks for the prompt reply! Please excuse my lack of knowledge, I am trying to locate the web.config file inside the www folder I created for my site (I named it nopCommerce440) so I can enable stdout but I cannot seem to locate the file. Could you please guide me in the correct direction?

Thanks

**Comment by exileDev** [comment]
The web.config file is located in the root application directory. Also, I noticed an invalid sample of the connection string you provided:
> Data Source=localhost; User ID=[OMITTED FOR PRIVACY]; Password=[OMITTED FOR PRIVACY];

It should be like
> Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;

I couldn't reproduce it. You can post your questions on [our forums](https://www.nopcommerce.com/boards/active-discussions), we use GitHub only as an issue tracker. 

If there is confirmation of the issue, we'll reopen this one.
Closed #5814

**Comment by ximenchuifeng** [comment]
I  reproduce it, 
nopcommerce  source from office website , version 4.50.2 
mysql  version:  Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64

i only upgrade  MySql.Data verion to the latest: 8.0.29  in Nop.Data project。 then fix the problem

**Comment by ryanlee714** [comment]
> I reproduce it, nopcommerce source from office website , version 4.50.2 mysql version: Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64
> 
> i only upgrade MySql.Data verion to the latest: 8.0.29 in Nop.Data project。 then fix the problem

How to upgrade MySql.Data verion to the latest: 8.0.29 in Nop.Data project?
My environment:
OS: Ubuntu 20.04
NopCommerce: 4.50.2
Database: MySQL 8.0.29

Thank you in advance

**Comment by ximenchuifeng** [comment]
> How to upgrade MySql.Data verion to the latest: 8.0.29 in Nop.Data project? My environment: OS: Ubuntu 20.04 NopCommerce: 4.50.2 Database: MySQL 8.0.29

just use vs studio  or nuget  to upgrade the mysql.data to 8.0.29 in Nop.Data, then republish it    :)

**Comment by ryanlee714** [comment]
NopCommerce 4.50.2 was released on Apr 14. MySQL 8.0.29 was released on Apr
26.

NopCommerce might has some compatibility issues with MySQL.

Thank you

**Comment by akertech** [comment]
I have the same issue ( Setup failed: An Exception was thrown while activating:fluentMigrator.Runner.IVersionLoader). 
Is there any fix for this problem? I have been trying to install the latest version of Nopcommerce (4.50) no-source on ubuntu with MySQL .
Each time I get the same error.
any solution to this problem yet or can we say Nop on linux has come to an end

**Comment by ryanlee714** [comment]
> I have the same issue ( Setup failed: An Exception was thrown while activating:fluentMigrator.Runner.IVersionLoader). Is there any fix for this problem? I have been trying to install the latest version of Nopcommerce (4.50) no-source on ubuntu with MySQL . Each time I get the same error. any solution to this problem yet or can we say Nop on linux has come to an end

I have some difficulty to setup NopCommerce on Ubuntu 20.04. It might be that Nop 4.50.2 has compatibility issue with MySQL 8.0.29. The installation page is successfully loaded. After I clicked Install, it failed to create database tables and crashed. I'm waiting for NopCommerce 4.50.3. Hopefully it will solve the problem.

**Comment by ryanlee714** [comment]
We can help each other. My name is Ryan. My email is ***@***.***
Can I have your email?

**Comment by ximenchuifeng** [comment]
i'm sorry, i reply so so so slow, because this mail is not my primary
email, you can just upgrade latest mysql.data  in the Nop.Data project, can
fix this problem[image: 1663336595466.png]
