### ISSUE TITLE
The product list is not displayed in the admin/products section

### ISSUE THREAD

**Issue by reza-azarmi** [nopSolutions/nopCommerce#5816]
nopCommerce version: 4.3

Steps to reproduce the problem: 
The product list is not displayed in the admin/products section
There is no data and this is while in the orders section you can go to the product page and see the product, I will even add a new product, it will not be seen in the list

**Comment by AndreiMaz** [comment]
We cannot reproduce the issue. It works fine. 

Please provide a list of steps to reproduce it

**Comment by reza-azarmi** [comment]
Hi
I was looking forward to receiving an answer and thank you for answering. This has happened to my site since yesterday morning and I am still working on fixing this problem.
The product page of the site is a blank page. The product list is not displayed, but in the product orders section, I can enter the product page and apply the changes.
    Even when I add a new product, it does not appear in the list below.
Does not show any errors. Product information is available in the database because in all parts of the site, product-related locations are visible, and even on the main site, there is no problem in displaying products. This problem only exists in the site administrator.
I copied it from the database and uploaded it to another website that had nopcommerce installed, and the same problem occurred.
    In my opinion, the problem could be from the database. I do not know what happened that caused this problem. I need your help, professors
ncommerce v 4.30
I will send you the error in Chrome in the console section, maybe it will help to solve this problem

Thank you very much for taking the time to pay attention to my question
Thanks a lot

Error:
content.js:319 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at new ExternalResourceKeeper (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/content.js:319:20)
    at HTMLDocument.<anonymous> (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/content.js:428:26)
    at u (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/lib.min.js:2:3532)
    at Object.fireWith [as resolveWith] (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/lib.min.js:2:4344)
    at Function.ready (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/lib.min.js:2:6140)
    at r (chrome-extension://ndbhnmhkplkehbnjckcdlmcicflinjnl/dest/lib.min.js:1:962)
ExternalResourceKeeper @ content.js:319
(anonymous) @ content.js:428
u @ lib.min.js:2
fireWith @ lib.min.js:2
ready @ lib.min.js:2
r @ lib.min.js:1
load (async)
Z.ready.promise @ lib.min.js:2
(anonymous) @ lib.min.js:2
(anonymous) @ lib.min.js:1
(anonymous) @ lib.min.js:1
List:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
