### ISSUE TITLE
Migrations don't update locale resources properly

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5820]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Create your custom localization migration
2. Add locale resources using the AddLocaleResourceAsync method
3. Run the solution - resources will be added
4. Run the solution the second time - resources will be removed
5. On the third run they will be added again an so on

**Comment by AndreiMaz** [comment]
@skoshelev Also check https://github.com/nopSolutions/nopCommerce/issues/5784

**Comment by skoshelev** [comment]
Closed #5820
