### ISSUE TITLE
RUN dotnet restore NopCommerce.sln failed on docker image

### ISSUE THREAD

**Issue by podupu** [nopSolutions/nopCommerce#5825]
nopCommerce Version: 
Latest version 
Steps to reproduce the problem: 
Fresh start

docker-compose -f .\postgresql-docker-compose.yml build

> [build  4/44] RUN dotnet restore NopCommerce.sln:
#22 1.185 /usr/share/dotnet/sdk/5.0.401/NuGet.targets(290,5): error MSB3202: The project file "/src/Plugins/Nop.Plugin.Misc.Sendinblue/Nop.Plugin.Misc.Sendinblue.csproj" was not found. [/src/NopCommerce.sln]
------
executor failed running [/bin/sh -c dotnet restore NopCommerce.sln]: exit code: 1
ERROR: Service 'nopcommerce_web' failed to build : Build failed

**Comment by AndreiMaz** [comment]
Please also see https://github.com/nopSolutions/nopCommerce/issues/5542

**Comment by podupu** [comment]
Fixed the issue by changing from SendinBlue to Sendinblue. Please manually rename /src/Plugins/Nop.Plugin.Misc.SendinBlue to /src/Plugins/Nop.Plugin.Misc.Sendinblue.

**Comment by AndreiMaz** [comment]
@podupu What version of nopCommerce are you using?
