### ISSUE TITLE
not all "NopException" are translatable

### ISSUE THREAD

**Issue by reader-man** [nopSolutions/nopCommerce#5829]
nopCommerce version: 
4.40.3
Steps to reproduce the problem: 
as you can see this line:
                throw new NopException(string.Format(await _localizationService.GetResourceAsync("Checkout.MinOrderTotalAmount"),
                    await _priceFormatter.FormatPriceAsync(minOrderTotalAmount, true, false)));
which is great.

but there are 49 lines that are like this:

NopException("Not   supported rental period"),
NopException("Backup   directory not exists");
NopException("'Registered'   role could not be loaded");
NopException("Email   cannot be null");
NopException("Usernames   are disabled");
NopException("'Guests'   role could not be loaded");
NopException("System role   could not be deleted");
NopException("Primary   exchange rate currency is not set");
NopException("No   worksheet found");
NopException("Wrong file   format");
NopException("Recipient   could not be loaded");
NopException("You cannot   delete this email account. At least one account is required.");
NopException("Email   account could not be loaded");
NopException("Anonymous   checkout is not allowed");
NopException("Billing   address is not provided");
NopException("Email is   not valid");
NopException("Cart is   empty");
NopException("Shipping   address is not provided");
NopException("Shipping   total couldn't be calculated");
NopException("Order total   couldn't be calculated");
NopException("Billing   address is not available");
NopException("Shipping   address is not available");
NopException("Payment   method couldn't be loaded");
NopException("Payment   method is not active");
NopException("Recurring   payments are not supported by selected payment method"),
NopException("Not   supported recurring payment type"),
NopException("processPaymentResult   is not available");
NopException("Recurring   payment is not active");
NopException("Initial   order could not be loaded");
NopException("Customer   could not be loaded");
NopException("Next   payment date could not be calculated");
NopException("Cannot do   cancel for order.");
NopException("Cannot do   capture for order.");
NopException("You can't   mark this order as paid");
NopException("Cannot do   refund for order.");
NopException("You can't   refund this order");
NopException("Cannot do   partial refund for order.");
NopException("You can't   partially refund (offline) this order");
NopException("Cannot do   async Task for order.");
NopException("You can't   async Task this order");
NopException("Not   supported cycle period"),
NopException("Shipping   rate computation method could not be loaded");

so, maybe if they are done like the first example, it would be better.

**Comment by AndreiMaz** [comment]
Thanks a lot for the suggestion. But these exception are system ones, anyway you cannot reproduce them because the presentation layer has appropriate validation as well. We don't translate them in order to keep the size of language pack smaller
