### ISSUE TITLE
Default styles.rtl.css file should contain only overriden styles for RTL (similar to Telerik or KenodUI)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#583]
Forum source: http://www.nopcommerce.com/boards/t/27518/nopcommerce-330-roadmap-and-estimated-release-date-lets-discuss.aspx?p=14#117210 

and http://www.nopcommerce.com/boards/t/28833/new-responsive-design-for-upcoming-version-330-beta-testers-needed.aspx?p=2#117461 

also note that it can override some default styles (order will be changed)

**Comment by AndreiMaz** [comment]
moved to 1585
