### ISSUE TITLE
GUID as BaseEntity

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#5830]
Hello,
       I have been synchronizing nop with our ERP from some years.
When data to be updated increases , it is more efficient, use libraries that provide an Orchestrator, such as:
          - Sync Framework (for .NET... No more supported )
          - Dotmim.Sync (for .NET Core)

ES: With Dotmim.Sync I syncronize a NopDb on a VM with one on-premise, under Distributed transaction, in less then 5 miutes.

The only side effect that occurs is an Unjustified Increase .. of the progression of fictitious (unregistered) Customer Ids.

In particular, if by mistake we call the wrong url of the controllers,
calls are no longer considered to be of users:

       - builtin@search_engine_record.com
       - builtin@background-task-record.com

Furthermore, "the Guest-Customer delete task"  fails and slowdowns occur.

The fact that Guest-Customer and Customers are in the same table is a problem.

You should add Records in Customer table only after ShoppingCartItems order confirmation.

Many other systems have a more articulated customer management:

ASP.NET project standards start from tables:
     - AspNetUser
     - AspNetUserLogin
     - AspNetUserClaims

Upon this -> After order confirmation is added a record in:
      - Customer or
      - Contact

Remember the Einstein quote:

"Everything should be made as simple as possible, but no simpler."

By design, the choice to use only the customer table to manage orders is too simple.

In case of a configuration error if the Id of a session table reaches Max INT ... that's not a problem!
We reset everything and do a RESEED.

In case of a configuration error if the "Id of the Customer table" reaches Max INT ... The site is to be thrown away.

the best solution would be to Use GUIDs for all Entities.

If you want to schedule the activity for the next releases.... thanks in advance .

If you wanna open a crowdfunding project for my proposal ...
... from me  --> +100.00 $

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
