### ISSUE TITLE
Another way to detect search engines and mobile devices

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5831]
nopCommerce version: develop

Now we are using browscap package and [complex regex](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Helpers/UserAgentHelper.cs#L32) for this, it's a very inflexible solution. Moreover, browscap.xml is very heavy and bulky.

We could use something more modern and in sort of asp .net core process (e.g. https://github.com/wangkanai/Detection). This will allow more flexible configuring of the necessary detection settings, and easily make view markup for different devices using tag-helpers.

So, we should think about it.

See also #5822

**Comment by skoshelev** [comment]
Unfortunately, we haven't found a way to solve our problems in another way. 
We should leave the current implementation as the most appropriate

Closed #5831
