### ISSUE TITLE
Properly manage plugins with HideInWidgetList property

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5832]
nopCommerce version: develop

We should properly manage cases when a plugin inherits from `IWidgetPlugin`, but it's being hidden from the widget list (`public bool HideInWidgetList => true;`), so this is not the main plugin type. 
1. On the plugin configuration page, the breadcrumb should not say "back to widget list", it should say "back to [plugin type] list". Already fixed in #5735
2. Properly handling od `Enable` property on the CreateOrUpdatePlugin view, so that the main plugin type is enabled/disabled, and not the widget. See #5751 
3. Something else? Let's check all possible problems with such a situation.

**Comment by DmitriyKulagin** [comment]
Closed with commit https://github.com/nopSolutions/nopCommerce/commit/f0e39cc0f0e267b0aef7f94233ac5db928871aaf
