### ISSUE TITLE
Replace BundlerMinifier 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5834]
nopCommerce version: develop

The current way to create bundles and minifications of css and js using BundlerMinifier becomes inappropriate, more and more errors and problems appear (see #2674, #4791, #5627, #5817). 
We should find a new method or third-party library for this. For example, look at https://github.com/ligershark/WebOptimizer or something else.
After migrating to a new service, need to ensure that all of the above problems are fixed.

**Comment by exileDev** [comment]
Closed #5834
