### ISSUE TITLE
Find a way to ignore script tag location

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5835]
nopCommerce version: develop

Sometimes we need to ignore `asp-location` parameter of the `<script>` tag helper, for example, when a request is made using AJAX and is rendered without head and footer. 
At now we use `nop.IgnoreScriptTagLocation` value [saved in context](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/TagHelpers/Public/ScriptTagHelper.cs#L79), it's not the best way for this. Perhaps we could add a new parameter (e.g. `asp-ignore-location`) in the tag helper? 
Also need to remember that scripts can be added not from the view, but from the code by `IHtmlHelper.AddScriptParts()`.

**Comment by exileDev** [comment]
Closed in #5834. Introduced a new field for the ResourceLocation class: `None`
