### ISSUE TITLE
Move IStoreContext and IWorkContext from Nop.Core

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5836]
nopCommerce version: develop

Actually, the core is not a place for web contexts, the best place would be Nop.Web.Framework, but probably we cannot isolate all contexts dependencies only there, so Nop.Services is also suitable.
Let's think about it.

**Comment by kwerty** [comment]
Core is the perfect place for them. They're not Web Contexts, they're interfaces for accessing the current customer or store.

This could be useful for example if you were creating a NopCommerce Console App or WebForms app, where there is a different mechanism for determining the currently logged in user.

**Comment by RomanovM** [comment]
After some consideration we've decided not to move these classes.
