### ISSUE TITLE
Performance optimization to load category left block and top menu

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#584]
Currently we request child categories for each category in the block or menu. See "PrepareCategorySimpleModels" method of "CatalogController" and "MiscFacebookShopController". 

But we can simply load all categories before invocation of this method and pass them to this method. This way only one SQL request is made. Similar approach is used in the "GetFormattedBreadCrumb" method of the \Libraries\Nop.Services\Catalog\CategoryExtensions.cs file. 

But the issue is that it can slow down the system (maybe) if we have several thousands of categories (quite rare scenario but possible) 

Should we do it?

**Comment by Andrey-Pavlov** [comment]
I dont know relative my issue to this or not but I have performance issue with get slugs for categories and products. I have 4000 nested sub-categories and my main page crashes on timeout each time on clean start (cache cleared). Also I have the same issue when page has more than 100 products. (for example on search page)

I profile database and detect "select SlugName query" for each category/product.

Probably need to select all slug names with one query and use like a dictionary or select categories/products from db already with slug names.

**Comment by Andrey-Pavlov** [comment]
Also I have performance issue with 
- Show the number of distinct products besides each category and sub-categories

I guess it same issue type - select products count for each category in loop. Its ok with a few cats but on 4000 it timing out on each "clear cache".

**Comment by AndreiMaz** [comment]
@Andrey-Pavlov you can enable it in admin area > configuration > general and misc settings > localization settings > Load all search engine friendly names on startup
