### ISSUE TITLE
Change Url property to Host for the Store entity

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5840]
nopCommerce version: develop

Wouldn't it be enough to store only the host, without the scheme and path? That is, there will be `Host` and `AdditionalHosts` (for multi-store configuration) properties for the Store.

**Comment by AndreiMaz** [comment]
@exileDev Please clarify details about this suggestion. Why is it required?

**Comment by AndreiMaz** [comment]
@exileDev Please clarify details about this suggestion. Why is it required?

**Comment by exileDev** [comment]
After some discus, we've decided not to implement it. Closed #5840
