### ISSUE TITLE
Remove LayoutExtensions

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5845]
nopCommerce version: develop

We have a number of [extensions](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/UI/LayoutExtensions.cs) that internally just resolve `IPageHeadBuilder` and use the appropriate methods of that service. Do we really need them, because now we can inject the service right into the views and use its methods directly? This will allow to avoid using `IEngine.Resolve()` (see #3101) and reduce the call stack.

See also: #568, #5624

**Comment by exileDev** [comment]
Closed #5845
