### ISSUE TITLE
different measures for different quantities

### ISSUE THREAD

**Issue by gotees** [nopSolutions/nopCommerce#5847]
nopCommerce version: 4.40.3

Steps to reproduce the problem: I need to have the same product with diferent measures, wich each measure will be availabe on different quantities. Example: **Item1** 30x30; 20units. **Item1** 40x40; 50Units. **Item1** 80x80; 60Units If the customer clicks on option **Item1** 30x30, the quantity box only available will be 20Units.

**Comment by RomanovM** [comment]
@gotees Try to use product attributes and track inventory control by attributes for this.
Anyway, ask for advice on how to achieve this on [our forums](https://www.nopcommerce.com/boards).
