### ISSUE TITLE
Ability to Undo the shipped/Delivered status

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5850]
nopCommerce version: 4.40

Steps to reproduce the problem: 
If the shipment status is Shipped or Delivered, there should be a way for the admin to undo the status and clear the date. For example, if the status is "Delivered", admin can undo this and the status becomes Shipped.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality

Just delete such a shipment and create a new one
