### ISSUE TITLE
CLDR files are not loaded in virtual directories

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5852]
nopCommerce version: 4.40

> We are currently setting up NopCommerce in IIS Virtual directories. i.e. domain.com/US/ or domain.com/IN/. When looking at the browser console  we see the following errors:
> 
> ```
> Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/main/en/timeZoneNames.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/main/en/ca-gregorian.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/supplemental/numberingSystems.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/supplemental/weekData.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/main/en/numbers.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/supplemental/timeData.json:1 Failed to load resource: the server responded with a status of 404 ()
> /lib_npm/cldr-data/main/en/currencies.json:1
> ```
> 
> It appears that the virtual path is not being applied when an IIS virtual directory is used.
> i.e.
> `/lib_npm/cldr-data/main/en/currencies.json`
> should be:
> `/US/lib_npm/cldr-data/main/en/currencies.json`
> for a virtual directory /US

Source: https://www.nopcommerce.com/boards/topic/91905/iis-virtual-directory

**Comment by DmitriyKulagin** [comment]
Closed #5852
