### ISSUE TITLE
Track inventory by products attribute stock quantity condition rule not working 

### ISSUE THREAD

**Issue by manwarhossen** [nopSolutions/nopCommerce#5864]
nopCommerce version: 4.3 and 4.40.4

Steps to reproduce the problem: 
1.  Track inventory by products attribute for variant products. 
2. At front end / public store  stock quantity showing perfectly.
3. But if I add more then stock quantity it's adding to cart though add more then stock. Example : Stock quantity 4pcs , so we will not able to add more then 4 into cart. But system allowing more then 8pcs and not showing any warning.

**Comment by AndreiMaz** [comment]
Go to your product details page in admin area > attributes > combinations > your combination. Ensure that "Allow out of stock" is not ticked
