### ISSUE TITLE
How to change NuGet URL?

### ISSUE THREAD

**Issue by li5908** [nopSolutions/nopCommerce#5865]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
We have encountered NuGet download issue in Taiwan. You may check that here https://status.nuget.org/?q=1.
The NuGet team provides us an alternative CDN infrastructure to work around temporarily.
However, we couldn't find the NuGet.Config file or other config files state NuGet URL https://api.nuget.org/v3/index.json.
Please advise how can we change the NuGet URL to an alternative URL. Thanks!

**Comment by AndreiMaz** [comment]
Sorry for inconvenience. But I believe you should wait until the NuGet team fixes it
