### ISSUE TITLE
Line 836 of ProductService.cs

### ISSUE THREAD

**Issue by leeeuvern** [nopSolutions/nopCommerce#5866]
nopCommerce version: 4.4

Steps to reproduce the problem: 
for querying products by warehouse, there might be a mistake in the query at line  836. 

**Current code**: pwi => pwi.Id == warehouseId && pwi.ProductId == p.Id

**Correction:**:  pwi => pwi.WarehouseId == warehouseId && pwi.ProductId == p.Id

**Comment by RomanovM** [comment]
See also: #5760
