### ISSUE TITLE
Change quantity to decimal

### ISSUE THREAD

**Issue by AddeCrona** [nopSolutions/nopCommerce#5867]
nopCommerce version: all

Steps to reproduce the problem: 
I have come across some sites that need the ability to use decimal as quantity. Such as food gross companies that have a sales unit of kg and hence want to be able to add decimal value (or have AllowedQuantities) of 1.5kg or 2.4kg etc to cart. Many other e-commerce platforms I have worked with already support decimal as quantity.

I have done this on a nopCommerce website with some stuff around not working fully as they should. For example, cart totals or allowed quantites (since it uses a comma-seperated list and some cultures use comma as decimal-separator for example Sweden). Here I had to make a workaround for the AllowedQuantities and build some more custom functionality.

If more people than me have come across this and want this as a new feature it would be awesome if we could vote for this and come to a solution on how to take this home.

If this is not something that you think are ever gonna happen even if ppl want it then please remove this issue. @AndreiMaz

**Comment by AndreiMaz** [comment]
Thanks a lot for the suggestion. But it already exists - https://github.com/nopSolutions/nopCommerce/issues/232
