### ISSUE TITLE
A product attribute value can be removed even if it participates in a product attribute combination

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5872]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1. Add a product attribute with a value to any product
2. Create a product attribute combination using this value
3. Remove the value: the product attribute combination lose its name and the "combinations" tab is hidden if it was the only combination

Conclusion: a customer should not be able to delete a product attribute value if it participates in a product attribute combination as it's already done for the product attribute itself. Why can't we delete a product attribute because it is used in the combination but we can delete the appropriate value? Looks like a bug.

**Comment by DmitriyKulagin** [comment]
Closed #5872
