### ISSUE TITLE
Facebook Pixel plugin. Use Facebook Conversions API

### ISSUE THREAD

**Issue by li5908** [nopSolutions/nopCommerce#5874]
The Facebook Pixel plugin (available out of the box). Let's use Facebook Conversions API

Also see here https://www.nopcommerce.com/boards/topic/92576/api-conversions-facebook-plugin

**Comment by RomanovM** [comment]
See also here https://www.nopcommerce.com/boards/topic/92576/api-conversions-facebook-plugin
