### ISSUE TITLE
Order status is processing when order marked as paid

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5876]
nopCommerce version: 4.40

Steps to reproduce the problem: 
Once the payment status is marked as paid, the order status changed to processing! I believe this should be controlled by the payment plugin or manually by the admin.
The issue here is changing it to processing doesn't reflect the real world situation as for example, the shipment needs to be created first, then change the order to processing to indicate it is under processing.

**Comment by AndreiMaz** [comment]
It's by design. An order completed when it's paid and delivered
