### ISSUE TITLE
Wrong discount math being applied

### ISSUE THREAD

**Issue by leoChronos** [nopSolutions/nopCommerce#5881]
nopCommerce version: 4.30

Steps to reproduce the problem: 

**Display Prices with tax enabled**

**Create a discount rule that applies to PRODUCT**
- Use percentage: NO
- Coupon code: ANY
- Discount amount: Equals or Bigger than product value
- Maximum discounted quantity: 1 or higher

**Add this discount rule to a PRODUCT**

**Creates an order adding a quantity of this product bigger than "Maximum discounted quantity"**

**Result**
While subtotal looks fine, the product unit price became ZERO and the discount amount is higher than it is supposed to be.

**Comment by RomanovM** [comment]
Duplicate of #1233
