### ISSUE TITLE
Move back to EntityFramework when .Net 6 comes out

### ISSUE THREAD

**Issue by fendric** [nopSolutions/nopCommerce#5884]
nopCommerce version: 4.50

Steps to reproduce the problem: Move back to EntityFramework when .Net 6 comes out in order to take advantage of the speed enhancements in EF Core that .Net 6 will bring.

**Comment by AndreiMaz** [comment]
Let's consider it when .NET 6 is released. But anyway we'll consider EF only if it supports 2-layer caching
