### ISSUE TITLE
Computing final price based on Price/TierPrice - bug or breaking change?

### ISSUE THREAD

**Issue by geoionescu** [nopSolutions/nopCommerce#5888]
Hello all.

We've been using nop 3.7 and considering upgrading to latest version.
We've noticed a breaking change/bug in the way nop handles final Product pricing calculation taking into account Product's Price and TierPrice.

**Example**:
Let's say we define a product having a **Price of $10**, and a TierPrice for that Product having (for simplicity, e.g. not taking into account Customer Roles and/or Date ranges for TierPrice availability):
- **Quantity 1**
- **Price $15**

**The final price in nop 3.7 is $10**, since it was a minimum between the Price and TierPrice:

```
public virtual decimal GetFinalPrice(Product product, ...

...
//tier prices
if (product.HasTierPrices)
{
    decimal? tierPrice = GetMinimumTierPrice(product, customer, quantity);
    if (tierPrice.HasValue)
        price = Math.Min(price, tierPrice.Value);
}
```

However, **the final price in latest nop is $15**, and the code is something like this:

```
public virtual async Task<(decimal priceWithoutDiscounts, decimal finalPrice, decimal appliedDiscountAmount, List<Discount> appliedDiscounts)> GetFinalPriceAsync(Product product...

...
//tier prices
var tierPrice = await _productService.GetPreferredTierPriceAsync(product, customer, (await _storeContext.GetCurrentStoreAsync()).Id, quantity);
if (tierPrice != null)
    price = tierPrice.Price;
```

Please notice that while in 3.7 `Math.Min` was used in order to determine the price, this is no longer the case in latest version.

Q1: Is this a bug, or a feature/breaking change?
Q2: If we have $10 price for a product and a single TierPrice with $15, which price is right? I know this is more a philosophical question, but what bugs me a lot is the different way nop handles this between versions...
Q3: If we should always prefer the minimum price, is it enough to change the code to be `Math.Min` in `GetFinalPriceAsync`, or are there any other places to change?

nopCommerce version: [latest](https://github.com/nopSolutions/nopCommerce/commit/d87e107b7b9cf8b680efa8cc701af25a1acb4a4d) as of this writing

Thank you,
George.

**Comment by RomanovM** [comment]
@geoionescu 
This is by design now.  You can customize the latest version to keep the old price calculation.
1. This was introduced in 3.90, see #365 for details.
2. If there is a tier price for a specific quantity, it's a priority (kind of special price), so in your example, the price will be $15.
3. The tier price (if it exists) is used by default, but in the catalog, the min price is always displayed.
