### ISSUE TITLE
GA ecommerce doesn't work for products without categories

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5889]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
1. Enable "Enable eCommerce" and disable "Use JS to send eCommerce info"
2.  Create a product without a category
3. Purchase this product
4. It won't appear in GA e-commerce

P.S. It was reproducible on our official website (fixed on October 8th 2021)

**Comment by DmitriyKulagin** [comment]
Closed #5889
