### ISSUE TITLE
EncryptionService uses deprecated 3DES encryption

### ISSUE THREAD

**Issue by jaymckinney** [nopSolutions/nopCommerce#5896]
nopCommerce version: 4.40

NIST urges all users of 3DES to migrate to AES as soon as possible. This recommendation was made in 2017.

Resources
- https://csrc.nist.gov/news/2017/update-to-current-use-and-deprecation-of-tdea
- https://www.cryptomathic.com/news-events/blog/3des-is-officially-being-retired
- https://www.linkedin.com/pulse/3des-deprecated-offically-being-retired-benjamin-budts/

P.S. We should ensure that all already encrypted resources will work fine after the change

**Comment by exileDev** [comment]
Closed #5896
