### ISSUE TITLE
Guest Checkout issue with bundling and minification

### ISSUE THREAD

**Issue by jigarsangoi** [nopSolutions/nopCommerce#5899]
nopCommerce version: 4.40

Steps to reproduce the problem: Guest checkout won't allow to add new address when JS bundling and minification is enabled.
I attached screenshot of this error & I'm facing this error with "Emporium" Theme.

Solution: We need to add semicolon(;) at the end of [public.billingaddress.js](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/wwwroot/js/public.billingaddress.js)

![Error](https://user-images.githubusercontent.com/21276844/137107516-3ddc2033-3d55-4e76-99e3-e3d4ae5aaa87.PNG)

**Comment by exileDev** [comment]
I couldn't reproduce it. Closed #5899

Please, get in touch with theme developers.
