### ISSUE TITLE
why can't we merge dataSettings.json and appsettings.json?

### ISSUE THREAD

**Issue by mamoorkhan** [nopSolutions/nopCommerce#5900]
why can't we just have our settings in one standard appsettings.json and have to access them using AppSettings.cs class?

**Comment by AndreiMaz** [comment]
Please post all questions on our forums (do not duplicate here please) - https://www.nopcommerce.com/en/boards/topic/92197/why-cant-we-merge-datasettingsjson-and-appsettingsjson
