### ISSUE TITLE
Redundant picture  when "Pictures are stored into file system" was setted

### ISSUE THREAD

**Issue by hailua8xpro** [nopSolutions/nopCommerce#5903]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
- When "Pictures are stored into file system" config was setted, then you upload a picture by "Upload" button (UIHint("Picture")) Nopcommrece save picture in two folder "wwwroot\images" and "wwwroot\images\thumbs" but picture in "wwwroot\images" was not deleted and also its never were used somewhere
-  When "Pictures are stored into file system" button was hit: "all" picture were generated in "wwwroot\images". I am not sure why but i think it make redundant resources.

**Comment by skoshelev** [comment]
Hi, @hailua8xpro.

Despite the fact that it seems that this is a useless use of resources and the files in the wwwroot\images directory are not used in any way, this is done for a reason.

Indeed, the pages themselves display images only from the wwwroot\images\thumbs directory, but this folder contains already prepared files (the size has been reduced, the compression procedure has been carried out, etc.). Now, let's imagine that you wanted to change the design a little, and now you need to display images of a larger size than you have displayed before. What shall you do if you only have compressed files with a lower resolution from the wwwroot\images\thumbs directory? The only option is to store the originals of the images somewhere, these are the originals that are in the wwwroot\images folder. 

If it seems to you that you will never need the originals - you can delete them, however, it seems to us that the disk space occupied by the original images will be covered with peace of mind in case of unforeseen changes. 

You can analyze the [GetPictureUrlAsync](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Media/PictureService.cs#L557) method to better understand the purpose of the files in the wwwroot\images directory
