### ISSUE TITLE
https/SSL doesn't works in Linux with nginx when ssl is enabled in store setting

### ISSUE THREAD

**Issue by abdullah-bin-hasan** [nopSolutions/nopCommerce#5904]
nopCommerce version: 4.40

Steps to reproduce the problem: 

1. Enable SSL/HTTPS with nginx reverse proxy 
2.  UseHttpXForwardedProto enabled 
3. Tick the SSL enabled checkbox.
4. Enter your Store URL with the 'https://' prefix
5. Save and reload

Result: Too Many Redirect error

Also tried, clearing cache and cookies.
Normally https works with nginx when ssl is not enabled in the store setting. Cloudflare Full ssl mode also works fine.
using https with a proxy without enabling SSL in the store leads to another problem: external authentication plugins doesn't work when SSL is not enabled internally.

I think Kestrel Redirecting to https://localhost:5000/ might be the problem:

```
curl -v localhost:5000
* Rebuilt URL to: localhost:5000/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 16 Oct 2021 14:38:21 GMT
< Server: Kestrel
< Content-Length: 0
< Location: https://localhost:5000/
< Set-Cookie: .Nop.Customer=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/
< Set-Cookie: .Nop.Customer=b50d6f-5858-42e0-93b1-04d771d16; expires=Sun, 16 Oct 2022 14:38:21 GMT; path=/; httponly
< X-MiniProfiler-Ids: ["b4373e-800d-4b19-9dbb-e440f5770c"]
< 
* Connection #0 to host localhost left intact
```
``

**Comment by exileDev** [comment]
The 4.40 doesn't have the `UseHttpXForwardedProto` setting. This setting has been moved to `appsetting.json` (Admin/Setting/AppSettings) and is now called the `Use proxy servers option`. Also, the app should be hosted via Kestrel under HTTP protocol. I'll leave some examples here:

```
"HostingConfig": {
    "UseProxy": true,
    "ForwardedProtoHeaderName": null,
    "ForwardedForHeaderName": null,
    "KnownProxies": null
  }
```

```
upstream nopcommerce {
	server 127.0.0.1:5000;
}

server {

	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;


	ssl_certificate           /usr/local/share/ca-certificates/aspnet/localhost.crt;
	ssl_certificate_key	  	  /usr/local/share/ca-certificates/aspnet/localhost.key;

    ssl_session_timeout       1d;
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers               ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_tickets       off;
    ssl_stapling              off;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;	

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		proxy_pass http://nopcommerce;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection keep-alive;
		proxy_set_header Host $host;
		proxy_cache_bypass $http_upgrade;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}
```
Works as expected. Closed #5904

**Comment by abdullah-bin-hasan** [comment]
Hi @exileDev , please see the image below that I am having the `UseHttpXForwardedProto` setting in my nop 4.40.4 instance.
also the HostingConfig is different in my appsettings.json.

i am using nopcommerce downloaded without source code package for linux.
![image](https://user-images.githubusercontent.com/46241390/146042839-2f693231-e0f0-4089-ae2b-3300274504c9.png)
![image](https://user-images.githubusercontent.com/46241390/146044194-11a82bb9-e2ef-4a54-b760-37f901f19978.png)

**Comment by abdullah-bin-hasan** [comment]
Update: 
Unfortunately, the `UseHttpClusterHttps` was the problem in my case.
I am sorry.  I should have recognized and mentioned this before.
