### ISSUE TITLE
DropDown List selection strange behavior in Firefox

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5908]
nopCommerce version: 4.40

> I noticed a strange behaviour of the UI. When trying so select an item from a DropDownList (e.g. Selection of Shipping Address) the control does not respond in the first place. Only the second click opens the lists. That behaviour is only in FireFox (newest version 93), in Edge it works.
> 
> What I found out so far:
> - The error is specific to nopCommerce, because other sites work well
> - I disabled all CSS for the html 'selection' and 'option' tags, but the error still shows up
> - it seems that the first click activates the drop down list, and the second expands it eventually
> - my guess is, that some of the javascript code is responsible for this behaviour

Source: https://www.nopcommerce.com/boards/topic/92174/dropdown-list-selection-firefox-bug

Perhaps it is somehow related to[ accessibility issues](https://github.com/nopSolutions/nopCommerce/issues?q=is%3Aissue+accessibility+).
But even so, should we do something if the problem only occurs in FireFox?

**Comment by exileDev** [comment]
Couldn't reproduce (Firefox 101.0.1). Closed #5908
