### ISSUE TITLE
Google Analytics. Support UTM when "Use JS to send eCommerce info" is disabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5915]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
1. Enable "Enable eCommerce" in Google Analytics
2. Disable "Use JS to send eCommerce info"
3. No UTM details will be sent to Google Servers. "Source / Medium" will always be  "(direct) / (none)" - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Api/GoogleRequest.cs#L131 (hard-coded)
P.S. It's related to https://github.com/nopSolutions/nopCommerce/issues/2993 

It's supported in the new [Measurement Protocol Overview](https://developers.google.com/analytics/devguides/collection/protocol/ga4). We should use it instead of the current implementation as https://github.com/nopSolutions/nopCommerce/tree/develop/src/Plugins/Nop.Plugin.Widgets.GoogleAnalytics/Api

So we should ensure that UTM parameters of customer who placed an order are sent. The question is where do we get these parameters? Because in many cases this request is not sent by a customer. It could sent by a server after some PDT notification from a payment system. So there are no such parameters knowed. Can we get it from Google servers somehow? Or should we store them locally for each customer? Let's investigate. Perhaps, client_id or user_id or "Non-Interaction Hit" could help.
P.S. Google by "google measurement protocol get UTM details". There are a lot of related topics

**Comment by RomanovM** [comment]
Yep, we should use Measurement Protocol for this plugin. But it still is an alpha stage, so just waiting for a full release of this feature.

**Comment by DmitriyKulagin** [comment]
Solved in #6553
