### ISSUE TITLE
Sendinblue plugin. Incorrect token replacement

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5920]
nopCommerce version: develop

> In detail:
> If sendinblue template I write "Dear {{ params.billing.firstname }}," in the mail I receive I do not find written the value of the variables and therefore "Dear Michela" but "Dear% billing.firstname%".
> 
> So the variable is replaced with another variable, not with the value of the same, where am I wrong?
> 
> Here is a piece of code from the Sendinblue template:
> 
>   
> ```
> ­Dear {{ params.billing.firstname }},
> 
> Numero Ordine:
> {{ params.id }}
> ­
> Data ordine:
> {{ params.date }}
> ```

Source: https://www.nopcommerce.com/boards/topic/92297/sendinblue-integration

Perhaps due to an extra space here `% billing.firstname%`, let's check.

**Comment by DmitriyKulagin** [comment]
It is necessary to specify the parameters according to the allowed message tokens from the message template of nopCommerce.
