### ISSUE TITLE
Schedule tasks not working in Centos.

### ISSUE THREAD

**Issue by abdullah-bin-hasan** [nopSolutions/nopCommerce#5926]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
Install NopCommerce in Centos by following the official installation guide.
check the scheduled tasks after giving them some time to run or,
changing the "seconds run period" and restart the application.

Run now button only works for the first time only.
there is no error log found.
the log record is increasing and the emails are not sent.

**Comment by exileDev** [comment]
It works fine. I couldn't reproduce.

Closed #5926

**Comment by abdullah-bin-hasan** [comment]
Hello @exileDev , i am still trying to find the problem i am facing which even doesn't have any error or log to work upon.
I am using the NopCommerce without source code package in RHEL with SELinux enabled. could you please suggest any debugging scope?

**Comment by abdullah-bin-hasan** [comment]
Update: just checked a clean new installation in Ubuntu and everything works fine as expected. but in centos, it is not working whether SElinux is enabled or not. should I create a new issue?

**Comment by abdullah-bin-hasan** [comment]
> 

@exileDev

**Comment by exileDev** [comment]
@abdullah-bin-hasan I'll try to reproduce it, let you know.

**Comment by skoshelev** [comment]
Hi @abdullah-bin-hasan. I've tried to reproduce your problem on the fresh install of CentOS 8.5.2111 and nopCommerce 4.50 beta and I do not have any problem with scheduled tasks, all work as expected.

It looks like a local problem on your server config. You may try to use the version with source code and debug the TaskThread.TimerHandler and TaskThread.RunAsync methods to find out the problem reason

Closed #5926

**Comment by abdullah-bin-hasan** [comment]
Hello there, @skoshelev and @exileDev
i am really sorry for not checking the problem thoroughly before creating this issue.
i used Cloudflare every time I tried to solve the issue in a different distribution. therefore the problem is with using nopcommerce with Cloudflare. the same site works fine in localhost and with remote IP address, but when the request is going through Cloudflare Schedule task is not working in centos and its derivatives distros, not even the run now button. 
however, in Ubuntu the run now button works every time but not the background scheduled ones.
please try once again to reproduce the problem or suggest any solution if any.
thank you.

**Comment by D3bo** [comment]
I had the same problem with Ubuntu / traefik / docker: direct emails worked but queued emails didn't start. By chance I have enabled port 443 of the firewall and now they exit the queue correctly. @abdullah-bin-hasan

**Comment by abdullah-bin-hasan** [comment]
Hi, @D3bo Thanks for the info. btw, I am having this problem while using Cloudflare only. without Cloudflare proxying the host IP, everything works as expected for me.
