### ISSUE TITLE
Country 'Croatia (HR)' should be 'Subject to VAT'

### ISSUE THREAD

**Issue by kwestground** [nopSolutions/nopCommerce#5927]
Croatia does not install with Subject to VAT Flag.

https://github.com/nopSolutions/nopCommerce/blob/c8dff865418b9e9c6b21db69ab61d58161a74308/src/Libraries/Nop.Services/Installation/ISO3166.cs#L106

https://en.wikipedia.org/wiki/European_Union_value_added_tax

**Comment by kwestground** [comment]
@RomanovM Look like United Kingdom also have wrong setting (should be false)

**Comment by skoshelev** [comment]
Closed #5927
