### ISSUE TITLE
Discount amount in Ordersummary

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5930]
nopCommerce version: 4.40

Steps to reproduce the problem: 
When the discount type is on product base, the OrderTotal component doesn't show the discount amount. It seem it is like this by design, but it will be good to show the discount amount in the order summary in all cases.

**Comment by RomanovM** [comment]
Correct. Such discounts are displayed on item level and sub-total already calculated with these discounts. So it will be incorrect and confusing to add such a discount amount in the order summary. 
We'll keep the current design, but you can customize it.
![discount-item-level](https://user-images.githubusercontent.com/16698464/139709128-0c34d3ef-4797-4bda-8af0-1a31b4f4cc22.png)
