### ISSUE TITLE
Basic/advanced mode doesn't work on the message template page 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5934]
nopCommerce version: 4.40.4

"Basic/Advanced" mode on the message template page worked fine in previous versions. All "advanced-setting" classes have been accidentally deleted on this page

We have to revert them back like it's been done in version 4.30

**Comment by RomanovM** [comment]
Same for the category page

**Comment by DmitriyKulagin** [comment]
Closed #5934
