### ISSUE TITLE
Plugins Not Installed on Live server

### ISSUE THREAD

**Issue by UAsoftwaredeveloper** [nopSolutions/nopCommerce#5935]
nopCommerce version: 4.40

Steps to reproduce the problem: 
I have developed a plugin and tested on test environment it'is not upload on live system
Error is: No descriptor file is found. It should be in the root of the archive
plugin file attached:
[MySmsPlugin 4.40.zip](https://github.com/nopSolutions/nopCommerce/files/7496144/MySmsPlugin.4.40.zip)
.

**Comment by AndreiMaz** [comment]
It should be in the root of the archive. 

P.S. Please post all further technical questions on our forums

**Comment by UAsoftwaredeveloper** [comment]
> It should be in the root of the archive.
> 
> P.S. Please post all further technical questions on our forums

thank you it's done
