### ISSUE TITLE
.net 6 css & javascript isolation (MVC views and components)

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5938]
Hi,

There is new feature in .net 6 for css and javascript isolation (MVC views and components)

Css Isolation
[https://docs.microsoft.com/hr-hr/aspnet/core/mvc/views/overview?view=aspnetcore-6.0#css-isolation](https://docs.microsoft.com/hr-hr/aspnet/core/mvc/views/overview?view=aspnetcore-6.0#css-isolation)

Javascript isolation
[https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component)

This feature can make making themes and plugins much more robust and less bug-prone.

**Comment by exileDev** [comment]
Closed #5938

It's not suitable for our current policy of working with static resources.
