### ISSUE TITLE
Hide "Sales summary" report from vendors

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5939]
nopCommerce version: 4.40

It's a continuation of a previously implemented task - https://github.com/nopSolutions/nopCommerce/issues/5216. The issue is described at https://www.nopcommerce.com/en/boards/topic/92428/vendor-sales-email-report-incorrect

We hide all order totals for vendors (e.g. pdf reports, order list page in admin area > summary block, etc). So this report (/Admin/Report/SalesSummary) should NOT be available to vendors as well. Let's implement a new permission for this page (enable it for admins only). By the way, we can use the same permission for the order list page in admin area > summary block (displayed below the order table).

**Comment by skoshelev** [comment]
As for using the new permission for the order list page in admin area > summary block, it is not necessary because this block displays for vendors but contains only information about their products

Closed #5939

**Comment by exileDev** [comment]
Closed https://github.com/nopSolutions/nopCommerce/issues/5939
