### ISSUE TITLE
"An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader." on Debian 11 "Bullseye"

### ISSUE THREAD

**Issue by jayjupdhig** [nopSolutions/nopCommerce#5946]
**nopCommerce version:** 4.40

**Steps to reproduce the problem:** 

Hi there

Today, i installed NOP commerce as described on https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html - the only one difference is that i didn't use MySQL / MariaDB - that was replaced by PostgreSQL...

After doing all steps on https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html and set all 3 services (nginx, postgres, nopcommerce) to service autostart (on OS start), i get the install page on http://IP_ADDRESS...

AND: The database called "nopcommerce" was created manuelly by me with Windows tool "HeidiSQL"

I don't know where the problem is and think i've done all required steps correctly...

- Maybe the problem is that ASP.NET is installed in BOTH version 5.0 and 3.1.x ? Maybe they can't coexist together...?

- Maybe the problem is that i've created the database called "nopcommerce" by myself instead of using the NopCommerce installing process...?

Hmmm...? ;-)

Thank you very much for your feedbacks.

**Comment by jayjupdhig** [comment]
Screenshot here:

![image](https://user-images.githubusercontent.com/42765391/141491726-90477db2-4a74-420d-b53b-9f77bcfd627d.png)


...maybe the problem is because i have a ´$´ in my passwords??

**Comment by jayjupdhig** [comment]
DB exists, and as far i known, i don't need to add some specific permissions to the "postgres" user - because that user is the "root" user on postgresql DBMS?

![image](https://user-images.githubusercontent.com/42765391/141492338-1fd97c16-a973-4195-895b-12cff1a9f6a6.png)

**Comment by jayjupdhig** [comment]
Or is NopCommerce [still?] NOT supported on Debian 11 "Bullseye" yet...?

**Comment by AndreiMaz** [comment]
Duplicated at https://www.nopcommerce.com/en/boards/topic/92458/an-exception-was-thrown-while-activating-%CE%BBfluentmigratorrunneriversionloader-on-debian-11-bullseye

**Comment by exileDev** [comment]
Did you use the network instance of PostgreSQL (Windows)? By default, PostgreSQL accepts connections only from the localhost.

Please, enable stdlog and share the full stack trace on our forum. It doesn't seem there's any bug in the source code. I'll close this issue and reopen it if necessary.

**Comment by jayjupdhig** [comment]
HERE...

`-- Journal begins at Thu 2021-11-11 17:28:12 CET. --
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]:       Executing ViewResult, running view Index.
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]:       Executed ViewResult - view Index executed in 14.3369ms.
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]:       Executed action Nop.Web.Controllers.InstallController.Index (Nop.Web) in 642.2189ms
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]:       Executed endpoint 'Nop.Web.Controllers.InstallController.Index (Nop.Web)'
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Nov 16 10:42:17 debian-ll nopCommerce440-example[32026]:       Request finished HTTP/1.1 POST http://192.168.80.242/install application/x-www-form-urlencoded 534 - 200 - text/html;+charset=utf-8 699.1157ms
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]:       Request starting HTTP/1.1 POST http://192.168.80.242/install application/x-www-form-urlencoded 536
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]:       Executing endpoint 'Nop.Web.Controllers.InstallController.Index (Nop.Web)'
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
Nov 16 10:43:20 debian-ll nopCommerce440-example[32026]:       Route matched with {action = "Index", controller = "Install", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index(Nop.Web.Models.Install.InstallModel) on controller Nop.Web.Controllers.InstallController (Nop.Web).
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.MigrationRunner[1000]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       VersionDescriptionMigration migrating
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.Processors.Postgres.PostgresProcessor[1004]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Beginning Transaction
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.MigrationRunner[1004]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       AlterTable MigrationVersionInfo
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.Processors.Postgres.PostgresProcessor[1003]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.MigrationRunner[1002]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       => 0.0011705s
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.MigrationRunner[1004]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       CreateColumn MigrationVersionInfo Description citext
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.Processors.Postgres.PostgresProcessor[1003]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       ALTER TABLE "public"."MigrationVersionInfo" ADD "Description" citext NULL;
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: fail: FluentMigrator.Runner.MigrationRunner[0]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       An error occured executing the following sql:
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       ALTER TABLE "public"."MigrationVersionInfo" ADD "Description" citext NULL;
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       The error was 42704: Typ »citext« existiert nicht
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       System.Exception: An error occured executing the following sql:
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       ALTER TABLE "public"."MigrationVersionInfo" ADD "Description" citext NULL;
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       The error was 42704: Typ »citext« existiert nicht
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:        ---> Npgsql.PostgresException (0x80004005): 42704: Typ »citext« existiert nicht
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlDataReader.NextResult()
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at Npgsql.NpgsqlCommand.ExecuteNonQuery()
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.Processors.Postgres.PostgresProcessor.Process(String sql)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:         Exception data:
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           Severity: FEHLER
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           SqlState: 42704
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           MessageText: Typ »citext« existiert nicht
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           Position: 63
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           File: parse_type.c
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           Line: 270
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:           Routine: typenameType
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          --- End of inner exception stack trace ---
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.Processors.ProcessorBase.ReThrowWithSql(Exception ex, String sql)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.Processors.Postgres.PostgresProcessor.Process(String sql)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateColumnExpression expression)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Expressions.CreateColumnExpression.ExecuteWith(IMigrationProcessor processor)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.StopWatch.Time(Action action)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:          at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: FluentMigrator.Runner.Processors.Postgres.PostgresProcessor[1004]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Rolling back transaction
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Executing ViewResult, running view Index.
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Executed ViewResult - view Index executed in 7.4811ms.
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Executed action Nop.Web.Controllers.InstallController.Index (Nop.Web) in 1050.0954ms
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Executed endpoint 'Nop.Web.Controllers.InstallController.Index (Nop.Web)'
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Nov 16 10:43:21 debian-ll nopCommerce440-example[32026]:       Request finished HTTP/1.1 POST http://192.168.80.242/install application/x-www-form-urlencoded 536 - 200 - text/html;+charset=utf-8 1060.2604ms`

**Comment by jayjupdhig** [comment]
-> https://www.nopcommerce.com/en/boards/topic/92458/an-exception-was-thrown-while-activating-%CE%BBfluentmigratorrunneriversionloader-on-debian-11-bullseye/page/2#290092

**Comment by jayjupdhig** [comment]
@exileDev : Please re-open, there is a bug. Described here: https://www.nopcommerce.com/en/boards/topic/92458/an-exception-was-thrown-while-activating-%CE%BBfluentmigratorrunneriversionloader-on-debian-11-bullseye/page/2#290096

Thanks in advance!!

**Comment by jayjupdhig** [comment]
-> Not interested for that issues? Not interested to improve your product?? If yes: Why?

**Comment by jayjupdhig** [comment]
-> https://www.nopcommerce.com/de/boards/topic/92458/an-exception-was-thrown-while-activating-%CE%BBfluentmigratorrunneriversionloader-on-debian-11-bullseye/page/3#290198

**Comment by blaine614** [comment]
I'm also getting the same error for postgres. Apparently they didn't bother to fix it.

**Comment by msavara** [comment]
I have exact same issue 
Ubuntu 22.04 kernel 6.0
aspnet core runtime 6.0.9
MariaDB (ver. 10.6.10

If you want. i can provide login info for that server

**Comment by PTMAndrey** [comment]
> I'm also getting the same error for postgres. Apparently they didn't bother to fix it.

![image](https://github.com/nopSolutions/nopCommerce/assets/30751450/50c6fca6-79dc-4ff3-b3e6-5becd34f8b2a)

Still got an error while trying to connect with postgres...

**Comment by daneov** [comment]
Still relevant today.

Adding an init script with

```SQL
CREATE EXTENSION IF NOT EXISTS citext;
```

got me further, though I then ran into:

```text
2026-04-14 09:45:38.766 UTC [71] ERROR: function nextval(character) does not exist at character 194 [db] | 2026-04-14 09:45:38.766 UTC [71] HINT: No function matches the given name and argument types. You might need to add explicit type casts. [db] | 2026-04-14 09:45:38.766 UTC [71] STATEMENT: INSERT INTO "Language"
```

This can be hotfixed, by running the following statement in a `psql` shell:

```SQL
CREATE OR REPLACE FUNCTION nextval(character)
RETURNS bigint AS $$
BEGIN
  RETURN nextval($1::regclass);
END;
$$ LANGUAGE plpgsql;
```

The one after that is `datetime2fromparts`, which seems to be a Microsoft SQL thingie?

```text
2026-04-14 09:48:27.786 UTC [69] ERROR:  function datetime2fromparts(integer, integer, integer, integer, integer, integer, integer, integer) does not exist at character 270
2026-04-14 09:48:27.786 UTC [69] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2026-04-14 09:48:27.786 UTC [69] STATEMENT:  INSERT INTO "Currency"
```

Could be related to #8146, but I don't know.
