### ISSUE TITLE
Update the "powered by nopCommerce" hyperlink

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5951]
The first change is to add `target="_blank"` to the "powered by nopCommerce" hyperlink displayed in the footer

The second change is `rel="nofollow"` in order to improve our main website SEO. But let's display this `rel="nofollow" ` on all public store pages except the homepage. The main page won't have this attribute

**Comment by skoshelev** [comment]
Closed #5951
