### ISSUE TITLE
Cannot delete attributes from copied product

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#5953]
If I copy a product which has product attributes, I am not able to delete these attributes from the copied product, even once I have deleted all the attributes' values.
![nopcommerce error deleting attributes](https://user-images.githubusercontent.com/16698464/141784490-b4848923-3fd4-4348-91a4-324c24dd5f18.png)
 
Source: https://www.nopcommerce.com/boards/topic/92457/cannot-delete-attributes-from-copied-product

**Comment by skoshelev** [comment]
Can't reproduce

Closed #5953
