### ISSUE TITLE
OrderItem AttributeDescription saved with html encoded string

### ISSUE THREAD

**Issue by Zalhera** [nopSolutions/nopCommerce#5954]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 

- Create a product attribute with non standard characters: Größe
- Make an order including a product with this attribute

The value of the column _AttributeDescription_ in the _OrderItem_ table now contains a html encoded string of the attribute (`Gr&#246;&#223;e: 9`). The value should be Größe: 9

**Comment by kwerty** [comment]
AttributeDescription is HTML. If you have multiple attributes, they will be separated by <br />

**Comment by AndreiMaz** [comment]
"kwerty" is right. It's by design. They store attributes in HTML format
