### ISSUE TITLE
Change Log Search Order By

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#5956]
nopCommerce version: 
V4.40.4
Steps to reproduce the problem: 
Search the log - currently items are sorted by time 

                query = query.OrderByDescending(l => l.CreatedOnUtc);

When you are fault finding then log items may not be in sequece when the time vales are the same 
Suggest to change to order by Id

                query = query.OrderByDescending(l => l.Id);

For example in my log I see 
528496 5:41:17 AM	eWay Rapid Process Payment Gateway Transaction For Order: d46694f6-33b4-4c84-879e-7d2556b74ef2
528495 5:41:17 AM	eWay Rapid Process Payment Gateway Order Status set to : Authorized	
528497 5:41:17 AM	eWay Rapid **Post Process** Transaction For Order: 2021083 for Amount: 60.24
528494 5:41:16 AM	eWay Rapid Process Payment Gateway Transaction For Order: d46694f6-33b4-4c84-879e-7d2556b74ef2

As we know **Post Process Payment** happens after **Process Payment** 
This is a simple example - in more complex situations its confusing to see things out of order

This would help for fault finding and live debugging

**Comment by gkennedy1** [comment]
There's a precision bug in Linq2db that drops the milliseconds, previously reported [here](https://github.com/nopSolutions/nopCommerce/issues/5741) 
If that bug is fixed then this wouldn't be an issue.

**Comment by RomanovM** [comment]
@DmitriyKulagin Let's do it only if the solution of #5741 doesn't help here.

**Comment by exileDev** [comment]
Closed #5956. Solved with #5741
