### ISSUE TITLE
Support for Level 3 Credit Card transactions

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#596]
Defined: 
http://en.wikipedia.org/wiki/Merchant_account#Level_2_or_Level_3_Processing_-_Purchasing_Cards 

For level 3 cc data, line item data needs to be sent along with the CC auth/capture: 
Product codes, Product descriptions, price, quantites, units of measure, etc 

Issue:
 * Level 3 compliant transactions can sometimes reduce costs with certain payment gateways.
 * Some B2B transactions require Level 3 data to be passed to payment gateways. 

This data (for the most part) is already supplied within NOP using the Order object, but the data is only gathered within NOP only after the payment is processed. 

In order to attempt to get this data, some payment plugin authors try to recreate the NOP shopping cart/order data within their plugin. See the large commented out section in: 

https://nopcommerce.codeplex.com/SourceControl/latest#src/Plugins/Nop.Plugin.Payments.PayPalDirect/PayPalDirectPaymentProcessor.cs 

Proposed: 
 * Modifying the ProcessPaymentRequest to include an Order object. (ProposedOrder)
 * Updating the PlaceOrder method in the OrderProcessngService to partially assign values to the Order object before the Payment processor is called. 
*This "uninserted" Order object is then assigned to the ProcessPaymentRequest and the PlaceOrder method is called.
 * After the Payment is successful, will the rest of the Order object values be assigned and only then is the Order.Add method called.
 * This will allow the payment processors to access more detailed order info without recreating code from within the OrderProcessingService.

**Comment by 3dmerchant** [comment]
I want this for a client too. 
All I need to make it happen is to **add RETURN URL to the authorize.net set up configuration.** Then with emulator my gateway will handle the rest automatically (and include 3D secure that another user wants too.)
