### ISSUE TITLE
Change Image Folder's Location

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5964]
nopCommerce version: 
4.40.4

Hi, it is possible for me to change the location of image folder (content/images..) to another drive because my current is nearly full.

Link to original question:
[https://www.nopcommerce.com/en/boards/topic/55218/change-image-folders-location](https://www.nopcommerce.com/en/boards/topic/55218/change-image-folders-location)

**Comment by AndreiMaz** [comment]
Please do not post questions here. Use our forums for it. This repository is work items only
