### ISSUE TITLE
export orders with products

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5966]
nopCommerce version: 4.40

Steps to reproduce the problem: 
If the products has attribute combination with (SKU, Price, ....). The exported excel doesn't support this. It should handle the attribute combination

**Comment by AndreiMaz** [comment]
@ahmadkq Please describe the scenario and expected behavior. Currently, it's not clear what exactly doesn't work

**Comment by ahmadkq** [comment]
@AndreiMaz 
1- Create a product
2- Add 2 product attributes and their combinations. Each combination has its own SKU.
3- Make sure to have "Export orders with products" option is enabled in Order settings.
4- Place and order with this product.
5- Export to excel this order

Excpect:
To have the SKU for that product combination in the order

**Comment by skoshelev** [comment]
Closed #5966
