### ISSUE TITLE
Revise the Gulp tasks implementation

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#5967]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. Open the package.json file
2. Add a new library there
3. Then you need to add this library to lib_npm folder of wwwroot. How would you do this?
4. You will run the tasks from gulpfile.js file that first clears the whole lib_npm folder and then adds all the libraries again one by one
5. Some of them can be updated, some files can be deleted from the newly added libraries, etc.
6. This way, we get LOTS of added, updated and deleted files in the version control system. Even if you added the library with only ONE js file, for example
7. So to not mess up in your commit history you must delete and revert the files MANUALLY excluding the file of the library that you really added to the package.json file
8. This way gulp doesn't automate the work files but adds you a lot of manual work instead

**Comment by exileDev** [comment]
Closed #5967 by d4b18d527815f3b62842b41685dd678046e08b85
