### ISSUE TITLE
Cannot write DateTime with Kind=Unspecified to PostgreSQL

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#5968]
nopCommerce version: 
4.50 develop

Steps to reproduce the problem: 
when intallation for postgresql, 
Setup failed: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

**Comment by exileDev** [comment]
It's a known issue. Please refer to the [3.6.0 release](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#release-360) note of l2db.
> If you want to adopt npgsql 6 changes and map DateTime to timestamptz by default, you need to specify new defaults for it in mapping schema (don't forget that your database also should use timestamptz type for affected columns):
```csharp
mappingSchema.AddScalarType(typeof(DateTime), DataType.DateTimeOffset);
mappingSchema.AddScalarType(typeof(DateTime?), DataType.DateTimeOffset);
```

Closed #5968

**Comment by mehmetkurt** [comment]
I understand you, but this is not a special solution. We are getting this error while installing nopCommerce core. That's why it needs to be fixed.

**Comment by mehmetkurt** [comment]
passed. thanks a lot.
