### ISSUE TITLE
Wrong price in instance search box

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5971]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1- Create a product with at least 1 product attribute, for example color
2- Set the product price to 10
3- Generate a combination attributes
4- set a price for each combination (override price) that is different than 10, for example 20.
5- In public store, do a search for this product, you will see it in the instance search with price 10

The instance search doesn't check if the product has combination with override price. So, the customer will see a price in the instance search and will see different price when go the product details.

**Comment by glhays** [comment]
To understand this better and to check my store. Should the instance search show all possible combinations of prices, or which should it expose to the public. If I have 10 different colors all set to individual prices what should the system select for this product, all of them?
Only asking as I am soon to be upgrading from 4.30.


________________________________
From: ahmadkq ***@***.***>
Sent: Thursday, November 25, 2021 11:26:31 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Wrong price in instance search box (Issue #5971)


nopCommerce version: 4.40

Steps to reproduce the problem:
1- Create a product with at least 1 product attribute, for example color
2- Set the product price to 10
3- Generate a combination attributes
4- set a price for each combination (override price) that is different than 10, for example 20.
5- In public store, do a search for this product, you will see it in the instance search with price 10

The instance search doesn't check if the product has combination with override price. So, the customer will see a price in the instance search and will see different price when go the product details.

**Comment by AndreiMaz** [comment]
Duplicated https://github.com/nopSolutions/nopCommerce/issues/29

P.S. @ahmadkq Could you please our forums to report or suggest new issues?
