### ISSUE TITLE
How to install NopCommerce440 on Debian 11.x with PostgreSQL 13.x?

### ISSUE THREAD

**Issue by jayjupdhig** [nopSolutions/nopCommerce#5973]
Hello

How to install NopCommerce440 on Debian 11.x with PostgreSQL 13.x?

I get that error with PostgreSQL 13.x *

[img]https://i.ibb.co/MCsXFqS/postgres.jpg[/img]

* installed as described on https://computingforgeeks.com/install-postgresql-on-debian-linux/

Thank you very much for your feedbacks.

Kind regards, Jan

**Comment by jayjupdhig** [comment]
-> https://www.nopcommerce.com/de/boards/topic/92578/how-to-install-nopcommerce440-on-debian-11x-with-postgresql-13x

**Comment by jayjupdhig** [comment]
After manually cleaning (delete nopcommerce DB from previous PostgresQL version), nothing happens anymore... a DB will not be created and the "sequence" error is also gone. After the [failed] installation process i'm still on /install path... no DB in pgadmin...

**Comment by RomanovM** [comment]
Follow forum topic. 
If someone from the community confirms the problem, we'll open this issue.
