### ISSUE TITLE
PayPal Commerce TAX issue

### ISSUE THREAD

**Issue by fencer** [nopSolutions/nopCommerce#5974]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
Store has items with different tax percentages, in my case, 0% and 18%. In the scenario where shopping cart has different tax categories and qty the `UnitAmount.Value` sent to PayPal is wrong.

### Cart Example:
1 x Item A (0% Tax) @ € 1
2 x Item B (0% Tax) @ € 1
1 x Item C (18% Tax) @ €1
4 x Item D (18% Tax) @ €1

### Values Sent to Paypal:
`AmountWithBreakdown.Value`: 8.00
`AmountBreakdown.ItemTotal.Value`: 7.25
`AmountWithBreakdown.AmountBreakdown.TaxTotal.Value`: 0.75
`PurchaseUnits.Items.Item.Tax`: null (for all items)
`PurchaseUnits.Items.Item.UnitAmount.Value`: € 1 for items with QTY 1, 0.85 for items with QTY 4.

This is causing an `UNPROCESSABLE_ENTITY` error when trying to process the payment.

**Full message:**
```
PayPalHttp.HttpException: {"name":"UNPROCESSABLE_ENTITY","details":[{"field":"/purchase_units/@reference_id=='4d5c7aab-54dc-4f3c-b2a1-6da0c7016ec8'/amount/breakdown/item_total/value","value":"27.98","issue":"ITEM_TOTAL_MISMATCH","description":"Should equal sum of (unit_amount * quantity) across all items for a given purchase_unit"}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"9a1ca202185c0","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-ITEM_TOTAL_MISMATCH","rel":"information_link","method":"GET"}]}
   at PayPalHttp.HttpClient.Execute[T](T req)
   at Nop.Plugin.Payments.PayPalCommerce.Services.ServiceManager.HandleCheckoutRequestAsync[TRequest,TResult](PayPalCommerceSettings settings, TRequest request)
   at Nop.Plugin.Payments.PayPalCommerce.Services.ServiceManager.<>c__DisplayClass28_0.<<CreateOrderAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Nop.Plugin.Payments.PayPalCommerce.Services.ServiceManager.HandleFunctionAsync[TResult](Func`1 function)
```

**Comment by RomanovM** [comment]
Well, this is a continuation of #5517, the reason for all these problems is that PayPal forcibly rounds all amounts to two decimal, as a result, they don't match with calculated on our side. 
We'll add some workaround for this.

**Comment by RomanovM** [comment]
See also: https://www.nopcommerce.com/boards/topic/95488/paypal-commerce-code
