### ISSUE TITLE
External authentication with Google account

### ISSUE THREAD

**Issue by acnhia** [nopSolutions/nopCommerce#5975]
nopCommerce version: latest

Steps to reproduce the problem: 
Looking for integrating new user and logins using gmail logins

**Comment by AndreiMaz** [comment]
There are third-party plugins for that - https://www.nopcommerce.com/en/social-login-via-facebook-google-etc-foxnetsoftcom or https://www.nopcommerce.com/en/external-authfacebooktwittergooglemicrosoftlinkedin
