### ISSUE TITLE
Scroll page up when using paging on catalog pages

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5979]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
1. Enable "Use AJAX products loading" (admin area > configuration > settings > catalog settings)
2. Open some catalog page with paging (e.g. https://demo.nopcommerce.com/awesome)
3. Click page 2 at the bottom

It should smoothly scroll up to the top of the products block. A customer should not do it manually

**Comment by RogerSmithR** [comment]
Hi!

I would love to help with this task. Could you assign it to me?

**Comment by AndreiMaz** [comment]
@RogerSmithR Thanks a lot for your interest in contribution. You're more than welcome to make a pull request
