### ISSUE TITLE
Upgrading Visual Studio 2019 to 2022

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#5981]
nopCommerce version: 
4.40

Steps to reproduce the problem: 
Install Visual Studio 2022 Community
Open Nop Solution
Debug

Get this error:
https://www.nopcommerce.com/en/boards/topic/92619/error-method-clone-in-type-on-start-when-loading-some-plugins

**Comment by oyhan** [comment]
Seems there is a problem with the build operation.

**Comment by skoshelev** [comment]
I checked to build 4.40.4 on visual studio 2022, everything works without issue. Perhaps the problem is in local settings or temporary files. Try to close the studio and manually delete all bin and obj directories

![image](https://user-images.githubusercontent.com/16875599/144800577-81fd9a09-0f9a-4827-b3ba-3ca3144a852e.png)

Closed #5981

**Comment by oyhan** [comment]
@skoshelev Hi
BTW it's not a compile error it's a runtime error.
Continue to run the project with some plugins installed.

**Comment by skoshelev** [comment]
Sorry for misunderstanding, but I may run nopCommerce 4.40.4 from the visual studio 2020 without problem too

![image](https://user-images.githubusercontent.com/16875599/144807297-e4fac4b4-4920-4ccb-8704-c63fa87a0eeb.png)

**Comment by oyhan** [comment]
Unfortunately it's not happening all the time. For me after couple of stop/starting project during the development showed up and I had to switch to vs2019 and rebuild **solution** and run again.
Can you just rebuild a existing plugin in the project and then again start the web project? because it's just my routine

**Comment by skoshelev** [comment]
You know, it looks like there really is some kind of problem in visual studio 2022, I once managed to reproduce the problem, but after repeating the same actions, the problem is just gone. Anyway, a complete rebuild of the solution works well, so it looks like there is a problem not with our code.

**Comment by oyhan** [comment]
Absolutely it's not from the code. As I mentions before there is something wrong with build operation in vs22 and just revealed in the Nop project in some circumstances. And I must add it may be something related to ```record``` types.

**Comment by Ochapparel** [comment]
I deleted the Bin and the Obj folder. Did a whole rebuild and still same error when "debugging"

<img width="574" alt="image" src="https://user-images.githubusercontent.com/20989983/144852019-69b218e8-50d7-42d2-ada0-e674a06d6341.png">

@skoshelev  anyone else on the nop team able to try 2022? Not a big issue to use 2019, it's just a very strange error

**Comment by joekrauss** [comment]
NopCommerce works fine with VS2022 however, all assemblies including 3rd party plugins have to be compiled under VS2022 to work properly. If one plugin or assembly is not compiled with VS2022 you will get errors like "not compatible with base type method 'Nop.Web.Framework.Models.BaseNopEntityModel.<Clone>$()'.". I wish I had more time to investigate the cause, but from what I see the VS2022 compiled version is different in size than when compiled under VS2019.

**Comment by eplsoftware** [comment]
will the new version 4.50 now be compiled with Visual Studio 2022 or with version 2019? It should be version 2022 so there is no mess.

**Comment by Ochapparel** [comment]
Agreed. And maybe a communication to the 3rd party plugins to compile in 2022

**Comment by Ochapparel** [comment]
How is the new bath compiled? 2019?

**Comment by eplsoftware** [comment]
Version 4.40 and all plug-ins with Visual Studio 2019 and version 4.50 and all plug-ins with Visual Studio 2022.

**Comment by Ochapparel** [comment]
Great. Maybe make that communication make to everyone. Especially 3rd party plugins.

**Comment by oyhan** [comment]
For all people like me still has the problem try to install the [latest dotnet 5 sdk](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.403-windows-x64-installer) 
My problem went out.

**Comment by yashobanta999** [comment]
hii! Can i upgrade from 2019 to 2022 studio directly from 2019 version or i have to download the 2022 version separately

**Comment by glhays** [comment]
Download VS2022 and install it. If your 2019 is a licensed version check your account for upgrade options. 
NopCommerce website provides the requirements needed for versions of its software. 4.40 and earlier VS2022 or earlier, 4.50 requires VS2022.

**Comment by serkandede** [comment]
Hi, i have same issue with a little bit different environment.
We are running Nop 4.40 in VS Code on mac computer.  Everything is perfect without third party libraries. 


But when we added third party plugins (Nop-Templates Plugins, we dont have source code to rebuild) :

- project build succesfully.
- it is runtime error
- third party dlls caused the same issue (Nop-Templates's plugin dlls)

**Comment by glhays** [comment]
Your nop template plug-in folders are not source code they are compiled by nop templates. They should only be placed in the plug-ins folder of the Nop.web project not in the nopcommerce plug-ins folder that gets compiled with the nop source code. Check your nop template account for updated theme files for the version of nopcommerce your running and add them.
VS2019 and 2022 are standalone, so you do have to install separately. You can run them side by side and the visual studio installer manages the versions on your machine.


________________________________
