### ISSUE TITLE
First letter a and First letter A problem for admin url

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#5982]
nopCommerce version: 4.50

Steps to reproduce the problem: 
/admin working but /Admin not working. If clicked another link in the admin panel working.  It doesn't matter Admin or admin.

This page isn’t working right now
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by AndreiMaz** [comment]
It works fine (cannot reproduce the issue)
