### ISSUE TITLE
AddRouting Move to NopRoutingStartup

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#5983]
nopCommerce version: 4.50

Steps to reproduce the problem: 
   //add routing
   services.AddRouting(options =>
   {
       //add constraint key for language
       options.ConstraintMap[NopPathRouteDefaults.LanguageParameterTransformer] = typeof(LanguageParameterTransformer);
   });

**Comment by AndreiMaz** [comment]
@mehmetkurt Why should it be done?
