### ISSUE TITLE
Migrate from Connector/NET (MySql.Data) to MySqlConnector(mysql-net)

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5985]
Hi,

Maybe its time to migrate from MySQl.Data to MySqlConnector. 

MySqlConnector is a more robust solution for dotnet core + mysql. There are many Bug Fixes resolved with MySqlConnector and its more performance suitable for project like Nop.

**Comment by exileDev** [comment]
Closed #5985
