### ISSUE TITLE
Change Image Folder's Location

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#5986]
nopCommerce version:
4.40.4

Hi,

Currently you can choose between disk or database for image storage. When disk is used for storage its using hard coded location(content/images) there is not any option available to choose **custom** disk path. 

![Screen Shot 2021-12-07 at 09 23 03](https://user-images.githubusercontent.com/6122624/144992993-c89f2bb4-f462-4015-af6c-ddd6175e471c.png)

**Comment by AndreiMaz** [comment]
THanks a lot. But after some consideration we've decided not to implement this functionality out of the box and leave it for customization

**Comment by skoshelev** [comment]
Closed #5986
