### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#5987]
nopCommerce version: 4.50

Steps to reproduce the problem: 
When first run, before installation : InvalidOperationException: The ConnectionString property has not been initialized.

**Comment by AndreiMaz** [comment]
@mehmetkurt 
1. Have you upgraded or installed nopCommerce from scratch?
2. What database are you using? 
3. What version of the database?

**Comment by skoshelev** [comment]
Fixed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/d59a0157132e10fc2c6e54671f0cde43fd235a25)
