### ISSUE TITLE
Estimate Shipping not applying

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#5988]
nopCommerce version: 4.40.4 and 4.50

Steps to reproduce the problem: 
1. Enable estimate shipping
2. Go to the cart page
3. Check estimate shipping
4. Apply some shipping option
![image](https://user-images.githubusercontent.com/5019111/145148119-ca6b4299-7aeb-460f-ab09-4e37906453e5.png)

Expected behavior: should apply shipping cost with the order total.

Actual behavior: applying estimate shipping showing this error (this error for name property got null at controller while applying estimate shipping))

**Comment by Koushiq** [comment]
I think this issue was already reported 
Issue URL : https://github.com/nopSolutions/nopCommerce/issues/5907

**Comment by DmitriyKulagin** [comment]
@Koushiq Yes, you pointed out correctly, this problem was already fixed earlier in this ticket - #5907
