### ISSUE TITLE
Estimate shipping button is not working on cart page.

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#5991]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Go to Cart Page
2. Click on estimate shipping button and nothing happening.
3. https://www.loom.com/share/64246b39393a4f30a35592b8879ff988

**Comment by DmitriyKulagin** [comment]
@forefrontinfotech This is not reproducible on the current version. Refresh your page in the browser with Ctrl + F5, the estimated shipping should pop up when you click on the button in a separate window, and not be displayed directly on the cart page. Or, for some reason, js resources are not loaded, check the console for errors.

**Comment by forefrontinfotech** [comment]
http://nop450beta.forefrontinfotech.com/cart

Here is the URL you can try.

**Comment by DmitriyKulagin** [comment]
@forefrontinfotech  Works correctly on this test bench.

**Comment by forefrontinfotech** [comment]
I have downloaded no source from forum post. and hosted same on server and not working.

**Comment by DmitriyKulagin** [comment]
@forefrontinfotech I just deployed an application to IIS on a local machine ([no source version](https://github.com/nopSolutions/nopCommerce/releases/tag/release-4.50.0-beta)) and was unable to reproduce the problem. I also tried to publish the application from VS2022, and I also don't get the error. For the purity of the experiment, every time I installed the application on a new database and a new directory on the hard drive. Please provide clear steps to reproduce the problem.
