### ISSUE TITLE
Required Validation is not working on estimate shipping box in cart page

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#5992]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Go to Cart page
2. Remove selected value from Country dropdown and remove zipcode from text box and click on apply button. nothing happened.
3. https://www.loom.com/share/9164e6394faa4bffb071bd4b0d2ee458

**Comment by DmitriyKulagin** [comment]
duplicates #5991
