### ISSUE TITLE
Estimate Shipping Rate are not coming in cart page

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#5993]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Go to cart page
2. Enter the country, state and zipcode. then click on apply button. nothing happened. no message
3. https://www.loom.com/share/bfe23798324041f0880c38a8847ef168

**Comment by untiedshoes** [comment]
#5990 This fix hasn't been included in the download via the forum

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5990
