### ISSUE TITLE
Order search default [ALL] in multi selected missing 

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#5995]
nopCommerce version: 4.50

Steps to reproduce the problem: 
1. Orders >Filters search area  ( by default ALL in multi selected missing )
2. Select any thing from payment statuses filter  
ex: default display nothing , select Pending ( searching properly) 
3. Remove that filter now in the text box default selected ALL is coming 
 https://prnt.sc/22b90b1
 
https://www.loom.com/share/f3f690fce7a54c4d81947b877175479b

**Comment by AndreiMaz** [comment]
The searching works fine in this case (just "All" value is not displayed)

**Comment by DmitriyKulagin** [comment]
Closed #5995
