### ISSUE TITLE
Master checkbox is not working on Shipping Restriction, Payment Method Restriction, Access control list pages

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#5996]
nopCommerce version: 4.50 beta

Steps to reproduce the problem: 

step 1 : login with admin and go /Admin/Shipping/Restrictions

step 2 : play with master checkbox. it is not working as expected

https://www.loom.com/share/b093599767314c7f84c7232fd226c531

**Comment by DmitriyKulagin** [comment]
Closed #5996
