### ISSUE TITLE
Allow to search message templates by system names (currently we search in content only)

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#5997]
nopCommerce version: 4.50 beta

Steps to reproduce the problem: 
1. Message template List  > 
2. Search keyword with "Service"  
3. As with the service there is 3 record , but while we doing search with this keyword we found only 1 record with another system name attach screen shot and video 

For your reference attach the screen shot [Screen shot 1](https://prnt.sc/22bbgl0) [screen shot 2](https://prnt.sc/22bbl6u)

https://www.loom.com/share/796f49d4265d443ab8a4a7588c3c2284

[A.M.] Allow to search message templates by system names (currently we search in content only)

**Comment by AndreiMaz** [comment]
@ilyaspatel91 It's by design. It searches in content only. But I think it's a good suggestion to search in system names as well

**Comment by exileDev** [comment]
Closed #5997
