### ISSUE TITLE
Master checkbox not working on payment method restriction page

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#5998]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Login using admin and go Admin/Payment/MethodRestrictions
2. Try to select individual checkbox and then try with master checkbox.
https://www.loom.com/share/0e84e7a3557f4fdeb2788a2bd942a8f5

**Comment by AndreiMaz** [comment]
Duplicates https://github.com/nopSolutions/nopCommerce/issues/5996
