### ISSUE TITLE
Required Validation is missing while adding new pickup point

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#5999]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Login as a admin and go to /Admin/PickupInStore/Configure
2. Click add new button pickup point and then click save. there is should be required validation on some fields.
3. https://www.loom.com/share/cc5dcbae20394f5fa9556dbf5d231749

**Comment by AndreiMaz** [comment]
There are no any required fields
