### ISSUE TITLE
Increased Blog functionality

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#6]
1. There is no way to preview a blog post.
2. The blog is not included in the sitemap.xml.
3. The blog is not included in a site search.
4. There should be an option to show blog summaries on the home page (like the news).
5. Blog images are not handled the same way other images are.
   Source: http://www.nopcommerce.com/boards/t/36820/blog-is-lacking.aspx 

Metablog support - http://outcoldman.ru/ru/blog/show/229 
Pingback, trackback support 
etc

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development. Furthermore,  we plan to move blog to a plugin
