### ISSUE TITLE
Allow a store owner to search/filter orders by multiple statuses

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#60]
Source: http://www.nopcommerce.com/boards/t/34536/enhancement-interactive-dashboard-not-shipped-should-exclude-cancelled-orders.aspx#140698 

do not forget to update reports (summary) in the order list grid as well

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/24117262240e94d6312ee2df46c51c61336f3593
