### ISSUE TITLE
Enter State/Province in textbox when no states configures in admin area

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#600]
Please, include a field to allow the saving of State/County/Province (whatever you call it locally) as free text. 

It might work well in the US and Canada to have a drop down list and just save the ID of the state, but the rest of the world is not so simple and even it it was, it's going to be a huge list to cover every state/county/province in the world, if you sell internationally. 

Ideally, the _CreateOrUpdateAddress.cshtml view would show a drop list for countries with defined states, and a plain text field for those that don't 

Forum source: http://www.nopcommerce.com/boards/t/26501/save-statecountyprovince-as-free-text.aspx

**Comment by shoecake** [comment]
+1 to this, I am quite surprised it is not available already or that more people are not asking for this.
