### ISSUE TITLE
Product search is not working with white space Trim is missing 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#6000]
nopCommerce version: 4.50 beta 

Steps to reproduce the problem: 

step 1 :  Go to /Admin/Product/List

step 2 : search **build  your** this term.

build your own computer item should be search as extected

https://www.loom.com/share/80d631ba54a04d7289d1b415848e6f0f

**Comment by AndreiMaz** [comment]
you've entered two spaces. enter a single one as the product name has

**Comment by prasantakumarpradhangalaxy** [comment]
@AndreiMaz  when you type **build** and put two to three space after **build** keyword than also i can't able to search

**Comment by sk5202** [comment]
@AndreiMaz  when you type build and put two to three space after build keyword than also i can't able to search
