### ISSUE TITLE
Unable to save other Tax setting because of Postal Required 

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#6001]
nopCommerce version: 4.50

Steps to reproduce the problem: 

1. Login as a admin and go to Admin/Setting/Tax
2. Try to change common tab value like default tax category and other field 
3. It will display validation message "Zip / postal code is required." and unable to save other things also 

please review the video for reference 
https://www.loom.com/share/baaa858626e74fb4a18c68479f78c922

**Comment by AndreiMaz** [comment]
Just enter  "Zip / postal code" (it's required)
