### ISSUE TITLE
Master checkbox not working on Access control list page

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#6002]
nopCommerce version: 

Steps to reproduce the problem: 
1. Login using admin and go /Admin/Security/Permissions
2. Try to select individual checkbox and then try with master checkbox.

https://www.loom.com/share/431457a23abd40f3b3a45dc7244df617

**Comment by AndreiMaz** [comment]
Duplicates https://github.com/nopSolutions/nopCommerce/issues/5996
