### ISSUE TITLE
Prevent to select pre selected value multiple  in custom attribute dropdown values 

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#6003]
nopCommerce version: 4.50

Steps to reproduce the problem: 

1. Admin Login > Admin/Setting/CustomerUser > Add new **Custom customer attributes**
2. Add new Attribute info with required and dropdown as per screen shot [Screenshot](https://prnt.sc/22bfg29)
3. It should not allow to select multiple as pre selected in dropdown you can see from the video 
https://www.loom.com/share/e1475e3cb6fe474eb1fae09af593aef5

**Comment by AndreiMaz** [comment]
@ilyaspatel91 Specify "pre-selected" for one option only. It's obvious. We don't plan to implement all possible ways for foolproof
