### ISSUE TITLE
Admin menu search not working properly

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#6005]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Go to admin side
2. Search "Web" and you will see two result. "Web Api" & "Web Api Frontend". 
3. In menu it is showing only one called "Web API" So why showing two result in search with different name and while clicking it is going on same page.
https://www.loom.com/share/984be8edef8344e88346d0709527e70c

**Comment by AndreiMaz** [comment]
These are two different links. That's why they are displayed

**Comment by forefrontinfotech** [comment]
But same page is opening on both link. What is the purpose of it ?

**Comment by AndreiMaz** [comment]
Sales & marketing
