### ISSUE TITLE
Do not allow to delete the only one template (category, manufacturer, product, topic)

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#6007]
nopCommerce version: 4.5 beta 

Steps to reproduce the problem: 

step 1 : Go Admin/Template/List

step 2: delete manufacture and category template 

step 3 : open detail page of both template at front end you will get internal server error.

**Note** : validation is there at least one template is there.

https://www.loom.com/share/5c691d9e162f4feba4a902e57442ebd3

**Comment by DmitriyKulagin** [comment]
Closed #6007
