### ISSUE TITLE
Web API menu should be highlighted when some one open Web Api Fronted plugin configuration page

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#6008]
nopCommerce version: 4.5 beta

Steps to reproduce the problem:

step 1: go to /admin 

step 2: click on web api from site map it will come up with new page but when you see at site map than same menu is not highlighted

![image](https://user-images.githubusercontent.com/41533502/145235595-008187db-27ae-4a8c-b93f-2d317aaafef9.png)

https://www.loom.com/share/b2c230baf4d74fa78da2bcda7ea324d2?focus_title=1&muted=1&from_recorder=1

**Comment by AndreiMaz** [comment]
It's by design
