### ISSUE TITLE
Multiple address generated when i edit check out process 

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#6009]
nopCommerce version: 4.50 beta

Steps to reproduce the problem: 

step1 :  Add any product in cart

step2 :  click checkout and at billing add new address and go to next step 

step3 : when you reach shipping method step than go back and edit same address it will generate new entry in address instead of edit existing one.

https://www.loom.com/share/fd502bcf01e44120af17baa2cb38fec5

**Comment by AndreiMaz** [comment]
It's by design
