### ISSUE TITLE
Add an option to subscribe to nopCommerce newsletters during installation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#601]
We can do it similar to umbraco. Very good idea -  "Keep me updated on Umbraco Versions, Security Bulletins and Community News"

Do not throw an exception if subscription cannot be submitted (e.g. limited Internet connection, etc). Furthermore, let's make it async (and set timeout to 3s).
1. In this case we should implement some protection (against spam attacks creatign multiple emails not really subscribed). We should validate the email for such emails (but not like registration validation - just newsletter email validation)?
2. How should we localize installation packages? Leave it as it is? Ask community to localize this locale - http://www.nopcommerce.com/boards/t/17641/help-nopcommerce-team-to-localize-the-installation-page-46-resources.aspx

But we should add email validation in this case

**Comment by Samkituka** [comment]
Hello,
Is that issue still relevant and open to work on it ?

**Comment by DmitriyKulagin** [comment]
Closed #601

**Comment by DmitriyKulagin** [comment]
Closed #601
