### ISSUE TITLE
Avalara tax provider configuration validation not working

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#6010]
nopCommerce version: 4.5

Steps to reproduce the problem: 

1. Admin > open tax provider >open configuration of Avalara or  Admin/Avalara/Configure
2. Without any changes just click on save it display required but no validation worked click here for [screenshot](https://prnt.sc/22cb7hd)

https://www.loom.com/share/3957208f56f44e6c95f11f51444c7063

**Comment by AndreiMaz** [comment]
The same can be told for any plugin (e.g. PayPal, UPS, etc). We don't consider this as a bug because we allow a store administrator to enter them later. 

This asterisk is just for informational purposes only

**Comment by ilyaspatel91** [comment]
Yes you are right , but as we can see that plugin( e.g. PayPal, UPS, etc) they have not provided information like **asterisk** and all they have simply display the text box [screenshot](https://prnt.sc/22fggab)
