### ISSUE TITLE
Accordion ( collapse) not working in avalara tax Configuration page

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#6011]
nopCommerce Version: 4.50

Steps to reproduce the problem: 

1. Login admin > Configuration > tax provider > configure the avalara tax configuration 
2. try to collapse the accordion for the configuration section it will not work attach video for reference 
https://www.loom.com/share/95cfe13f69464efd9082d1cc41cd8148

**Comment by exileDev** [comment]
Closed #6011
