### ISSUE TITLE
PayPal Commerce Payment Configuration issue

### ISSUE THREAD

**Issue by ilyaspatel91** [nopSolutions/nopCommerce#6012]
nopCommerce version: 4.50

Steps to reproduce the problem: 

1. Admin Login > Configuration Payment Methods 
2. **select** PayPal Commerce Plugin > click on configure 
3. play around with the configuration of email and other. it is not working as expected validation also missing 
4. email field required but missing astrik symbol (*) [click here ](https://prnt.sc/22cf1du)

https://www.loom.com/share/2a6bce4b56d6427d91cfaed772371297

**Comment by AndreiMaz** [comment]
The same can be told for any plugin (e.g. PayPal, UPS, etc). We don't consider this as a bug

**Comment by ilyaspatel91** [comment]
Yes you are right , but as we can see that plugin( e.g. PayPal, UPS, etc) they have not provided information like **asterisk** and all they have simply display the text box [screenshot](https://prnt.sc/22fggab)
