### ISSUE TITLE
Better distributed lock implementation

### ISSUE THREAD

**Issue by JadynWong** [nopSolutions/nopCommerce#6016]
[DistributedLock](https://github.com/madelson/DistributedLock)

This library supports a very large number of distributed lock implementations, such as `redis`, `zookeeper`, `sqlserver`, `pgsql`, `mysql`, `azure blob` , `file system`, etc.

**Comment by AndreiMaz** [comment]
@skoshelev Let's just check the library

**Comment by skoshelev** [comment]
I studied the library and came to the conclusion that its functionality is redundant for solving our problems.

Closed #6016
