### ISSUE TITLE
Checkboxes are not working properly even refresh the grid or browser - Activity types page admin side

### ISSUE THREAD

**Issue by forefrontinfotech** [nopSolutions/nopCommerce#6018]
nopCommerce version: 4.50 Beta

Steps to reproduce the problem: 
1. Login as a admin go to /Admin/ActivityLog/ActivityTypes
2. Select master checkbox and then refresh grid or browser. still many checkboxes are selected as it is.
https://www.loom.com/share/0d3d0810c2a74d8197c52f9f3f11367d

**Comment by DmitriyKulagin** [comment]
@forefrontinfotech When you first load the page, you have not selected some of the rows. Then you just play with the master checkbox and don't save the state of the table. Thus, when the table is updated, it is restored to its original state (all lines that are not marked fully correspond to what was at the beginning of the video).

**Comment by forefrontinfotech** [comment]
on page refresh things should clear isn't ?
