### ISSUE TITLE
"Manage Customers" permission does not work properly

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6020]
nopCommerce version: 4.40 and 4.50

Steps to reproduce the problem: 
1. Created a new customer role 
2. Assign only the "Admin area. Manage Customers" permission in the Access control list to the role. 
3. While the new role can see all customers and enter the customer editing page (without changing of the role), it cannot save any changes. When I clicked the Save button I got an error message saying "Not enough rights to manage customer roles."

Roles are not validated properly in the `ValidateCustomerRolesAsync` method of \Nop.Web\Areas\Admin\Controllers\CustomerController.cs. We should not require "Manage ACL" permission if roles are NOT changed. The `Except` method doesn't work as expected

Source: https://www.nopcommerce.com/en/boards/topic/92687/manage-customers-permission-does-not-work-properly

This is a continuation of https://github.com/nopSolutions/nopCommerce/issues/3592

**Comment by DmitriyKulagin** [comment]
Closed #6020
