### ISSUE TITLE
Could not serialize access due to read/write dependencies among transactions

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#6022]
nopCommerce version: 4.50

Steps to reproduce the problem: 
When use crud operations for Localization in Plugin some times.

40001: could not serialize access due to read/write dependencies among transactions
DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.

**Comment by AndreiMaz** [comment]
@mehmetkurt Please share the plugin so we can reproduce the issue

**Comment by mehmetkurt** [comment]
> @mehmetkurt Please share the plugin so we can reproduce the issue

@AndreiMaz Nothing new. I am getting an error in nopCommerce core. The picture is attached. There is an interesting situation. Sometimes it's okay. I think we have a problem with connection. It's like deadlocking.

![localization_problem](https://user-images.githubusercontent.com/9388243/146096212-79b4f0e1-a6ce-4560-8f61-2e79710a2552.png)

**Comment by exileDev** [comment]
I couldn't reproduce it. Closed #6022

**Comment by mehmetkurt** [comment]
at System.Transactions.TransactionStateAborted.EndCommit(InternalTransaction tx)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at Nop.Data.EntityRepository`1.<InsertAsync>d__17.MoveNext() in C:\projects\elastic\src\Libraries\Nop.Data\EntityRepository.cs:line 371
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nop.Services.Localization.LocalizationService.<AddOrUpdateLocaleResourceAsync>d__31.MoveNext() in C:\projects\elastic\src\Libraries\Nop.Services\Localization\LocalizationService.cs:line 752

**Comment by mehmetkurt** [comment]
this error only comes with postgresql. I guess the connection stays open and cannot operate.

@AndreiMaz important!

**Comment by mehmetkurt** [comment]
@exileDev 

        <deadlock>
 <victim-list>
  <victimProcess id="process26b74755088" />
 </victim-list>
 <process-list>
  <process id="process26b74755088" taskpriority="0" logused="144" waitresource="KEY: 5:72057594049134592 (ffffffffffff)" waittime="356" ownerId="29391" transactionname="user_transaction" lasttranstarted="2021-12-17T22:54:47.137" XDES="0x26b6f698428" lockMode="RangeI-N" schedulerid="8" kpid="38296" status="suspended" spid="54" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2021-12-17T22:54:47.210" lastbatchcompleted="2021-12-17T22:54:47.197" lastattention="1900-01-01T00:00:00.197" clientapp="Core Microsoft SqlClient Data Provider" hostname="ELASTIC" hostpid="39016" loginname="ELASTIC\Mehmet KURT" isolationlevel="serializable (4)" xactid="29391" currentdb="5" currentdbname="elastic_dev" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
   <executionStack>
    <frame procname="adhoc" line="1" stmtend="374" sqlhandle="0x02000000a471e21ee9ccb85b76d4f7f1cde46c82c730bc120000000000000000000000000000000000000000">
unknown    </frame>
   </executionStack>
   <inputbuf>
insert bulk [LocaleStringResource] ([ResourceName] NVarChar(200) COLLATE SQL_Latin1_General_CP1_CI_AS, [ResourceValue] NVarChar(max) COLLATE SQL_Latin1_General_CP1_CI_AS, [LanguageId] Int)   </inputbuf>
  </process>
  <process id="process26b733f8108" taskpriority="0" logused="144" waitresource="KEY: 5:72057594049134592 (ffffffffffff)" waittime="356" ownerId="29435" transactionname="user_transaction" lasttranstarted="2021-12-17T22:54:47.203" XDES="0x26b6f60c428" lockMode="RangeI-N" schedulerid="2" kpid="1744" status="suspended" spid="56" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2021-12-17T22:54:47.210" lastbatchcompleted="2021-12-17T22:54:47.207" lastattention="1900-01-01T00:00:00.207" clientapp="Core Microsoft SqlClient Data Provider" hostname="ELASTIC" hostpid="39016" loginname="ELASTIC\Mehmet KURT" isolationlevel="serializable (4)" xactid="29435" currentdb="5" currentdbname="elastic_dev" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
   <executionStack>
    <frame procname="adhoc" line="1" stmtend="374" sqlhandle="0x02000000a471e21ee9ccb85b76d4f7f1cde46c82c730bc120000000000000000000000000000000000000000">
unknown    </frame>
   </executionStack>
   <inputbuf>
insert bulk [LocaleStringResource] ([ResourceName] NVarChar(200) COLLATE SQL_Latin1_General_CP1_CI_AS, [ResourceValue] NVarChar(max) COLLATE SQL_Latin1_General_CP1_CI_AS, [LanguageId] Int)   </inputbuf>
  </process>
 </process-list>
 <resource-list>
  <keylock hobtid="72057594049134592" dbid="5" objectname="elastic_dev.dbo.LocaleStringResource" indexname="PK_LocaleStringResource" id="lock26b71460080" mode="RangeS-S" associatedObjectId="72057594049134592">
   <owner-list>
    <owner id="process26b733f8108" mode="RangeS-S" />
    <owner id="process26b733f8108" mode="RangeI-N" requestType="convert" />
   </owner-list>
   <waiter-list>
    <waiter id="process26b74755088" mode="RangeI-N" requestType="convert" />
   </waiter-list>
  </keylock>
  <keylock hobtid="72057594049134592" dbid="5" objectname="elastic_dev.dbo.LocaleStringResource" indexname="PK_LocaleStringResource" id="lock26b71460080" mode="RangeS-S" associatedObjectId="72057594049134592">
   <owner-list>
    <owner id="process26b74755088" mode="RangeS-S" />
    <owner id="process26b74755088" mode="RangeI-N" requestType="convert" />
   </owner-list>
   <waiter-list>
    <waiter id="process26b733f8108" mode="RangeI-N" requestType="convert" />
   </waiter-list>
  </keylock>
 </resource-list>
</deadlock>
