### ISSUE TITLE
Title is Messed up with unicode languages

### ISSUE THREAD

**Issue by zandiarash** [nopSolutions/nopCommerce#6023]
nopCommerce version: 4.50.0

Steps to reproduce the problem: 

Title is Messed up with Unicode languages
![1](https://user-images.githubusercontent.com/10775073/145664883-cbc0ba27-26b6-4968-99be-9449d36a5dc6.png)
![2](https://user-images.githubusercontent.com/10775073/145664888-750083ab-f7ee-45f5-bbf6-3f0e00f4c29e.png)

I made a pull request [here in https://github.com/nopSolutions/nopCommerce/pull/6024](https://github.com/nopSolutions/nopCommerce/pull/6024)

**Comment by exileDev** [comment]
Thanks! Closed #6023
