### ISSUE TITLE
System.ArgumentException: 'The route "/css/ShoppingCartCart.styles.css" was already specified (Parameter 'route')'

### ISSUE THREAD

**Issue by mattcarlucci** [nopSolutions/nopCommerce#6025]
nopCommerce version:  4.50 Beta

Steps to reproduce the problem: 
As an Admin, Goto Customers, Edit customer, Create an order via  Impersonate

System.ArgumentException: 'The route "/css/ShoppingCartCart.styles.css" was already specified (Parameter 'route')'

**Comment by AndreiMaz** [comment]
Duplicated https://github.com/nopSolutions/nopCommerce/issues/5994
