### ISSUE TITLE
Cookie window appears even if not necessary

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#6026]
nopCommerce version: 4.50 beta

Steps to reproduce the problem: 

            1.  Cookie popup  windows functionality must be enabled.
            
            2.  Go to the home page
            3. Popup  is shown. 
            4. Click  OK
            4. Then log-in as Admin
            5. Do nothing, ...simply  log-out
            
            6. If you press F5,
                the cookie pop-up  appears even though, previously, 
                we had confirmed the ok button

This because, after log-out,
a dummy customer has been created with no e-mail, username, etc ...

The log-out action, before creating a new dummy customer, should do a few more checks

The cookie window appears even if not necessary

It's annoying

**Comment by AndreiMaz** [comment]
"a dummy customer" (guest) is created by design.

**Comment by luc-cap** [comment]
ok, 
 create the guest.

but do not ask me to confirm  cookie  for the second time
