### ISSUE TITLE
HTML code is showing in wishlist when main product is added in wishlist and then add related product

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6029]
nopCommerce version:  4.40 - 4.50 beta

Steps to reproduce the problem: 
1 add any product to wishlist
2 assign related product to that product
3 open wishlist

**Comment by skoshelev** [comment]
Hi @JayPatel7348. I cannot reproduce the problem, please send screenshots or videos showing the problem

**Comment by JayPatel7348** [comment]
![1 HTML code is showing when main product is added in wishlist and then add related product](https://user-images.githubusercontent.com/96106946/146173424-2e0dc97e-cc39-4192-83d4-49ecc09eb353.jpg)

**Comment by skoshelev** [comment]
Closed #6029
