### ISSUE TITLE
Use slider for price range support (this way the filter can handle multi-currency correctly)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#603]
Price ranges (display in the "filter" block) are not converted into selected currency when selected currency is changed. For example if I have defined $0-$20; $21-$40, when I change currency to yen it is still 0-20; 21-40 except it is now yen; it should be converted and not only currency changed as the buying power of yen and dollar is much much different.

On the other hand (due to currency conversion) prices will bebecome not so friendly as entered by a store owner (not 0-20, but 0-24.34).

Possible solution. Now most stores support sliders with price ranges (or input textboxes with preset "min" and"max" possible prices). Maybe we should also re-think it

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/issues/276
