### ISSUE TITLE
Buy button is disappear after using Low stock activity

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6030]
nopCommerce version: 4.5 beta

Steps to reproduce the problem: 
1 Set Minimum stock quantity in any product
2 Set Low stock activity to Disable buy button for that product
3 Place order for that product until quantity reached to the Minimum stock quantity
4 Buy button will be disappeared
5 Enter more quantity in Stock quantity
6 Buy button should appear

**Comment by AndreiMaz** [comment]
It's by design. Once it's unpublished you have to enable it manually
