### ISSUE TITLE
Nop.Core.Infrastructure.Singleton<T>.Instance.get returned null.

### ISSUE THREAD

**Issue by mehmetkurt** [nopSolutions/nopCommerce#6031]
nopCommerce version: 4.50

Steps to reproduce the problem: 

when installing, DataProviderManager, Intance is null!

var dataProviderType = Singleton<DataConfig>.Instance.DataProvider;

![abc](https://user-images.githubusercontent.com/9388243/146049416-154b0ef9-e478-422f-89b2-8b355e13286d.png)

**Comment by AndreiMaz** [comment]
@mehmetkurt It works fine. Please provide more details on how to reproduce the issue (e.g. database, connection values, etc)

**Comment by exileDev** [comment]
@mehmetkurt Can you provide an exception stack trace and information about DBMS?

**Comment by AndreiMaz** [comment]
@exileDev Also see https://www.nopcommerce.com/en/boards/topic/92676/find-bugs-in-nopcommerce-4500-beta-and-earn-10#290939

**Comment by mehmetkurt** [comment]
Thanks @AndreiMaz

**Comment by exileDev** [comment]
It was happening when during low-level client operations, something configured wrong (e.g., incorrect connection string, failed login, permission denied). Closed #6031
