### ISSUE TITLE
Reset password does not work when an email contains a +

### ISSUE THREAD

**Issue by justinjstark** [nopSolutions/nopCommerce#6033]
nopCommerce version: 
Latest

Steps to reproduce the problem: 
- Create an account with an email like "test+test@gmail.com"
- Send the password reset link
- The URL in the email will contain "email=test+test@gmail.com" which model binds in MVC to email="test test@gmail.com".
- Clicking the reset link sends you to the homepage and does not allow you to reset your password

The URL parameters should be escaped as "email=test%2Btest@gmail.com". In a URL, the + acts as a space.

It appears this is caused in MessageTokenProvider.cs.
![image](https://user-images.githubusercontent.com/214307/146073863-d955273f-67b0-4019-b362-0557a4609845.png)

`urlHelper.RouteUrl(routeName, routeValues))` results in a properly escaped URL. But when you pass this into the PathString constructor, it escapes everything. You then UrlDecode it later resulting in an unecoded + in the email value. Microsoft's documentation specifically says not to use PathString with an encoded URL.

I don't have time to issue a pull request now but we fixed it by doing this:
![image](https://user-images.githubusercontent.com/214307/146074406-95ef1780-b03d-48df-9644-91511893969e.png)

**Comment by RomanovM** [comment]
See also #3946

**Comment by DmitriyKulagin** [comment]
@justinjstark Since version 4.30, [we pass the user's Guid](https://github.com/nopSolutions/nopCommerce/blob/d9c79c6b61ad9c5cdfc544f2b8bec16c3ceb13f3/src/Libraries/Nop.Services/Messages/MessageTokenProvider.cs#L1218-L1218) to the RouteUrlAsync method. How do you pass the Email parameter to the method?

**Comment by justinjstark** [comment]
@DmitriyKulagin The user GUID is just a RouteValue? It gets appended and escaped correctly by UrlHelper.RouteUrl just like all other RouteValues. What am I missing?

**Comment by DmitriyKulagin** [comment]
Closed #6033
