### ISSUE TITLE
Static text "Edit address" in JS Code (ignoring user language)

### ISSUE THREAD

**Issue by manuel3108** [nopSolutions/nopCommerce#6034]
nopCommerce version: 4.40.x

Steps to reproduce the problem: 
On the billingaddress page in multi page checkout, select an address and edit it.
It will always have the text "Edit address" ignoring the language of the user:
![grafik](https://user-images.githubusercontent.com/30698007/146150374-4ff346b2-ba0d-429a-b9a0-8c608e3396ae.png)

https://github.com/nopSolutions/nopCommerce/blob/14b519f74562bf51b54f70a66efb0635b05b8638/src/Presentation/Nop.Web/wwwroot/js/public.billingaddress.js#L35-L41

**Comment by DmitriyKulagin** [comment]
Closed #6034
