### ISSUE TITLE
Issue In MacOS - Cannot Launch application in Chrome after installation

### ISSUE THREAD

**Issue by alex-dhanasekar-tw** [nopSolutions/nopCommerce#6043]
nopCommerce version: 4.40+ (latest as of today's date)

Steps to reproduce the problem:
1. On a macbook pro laptop 2019 edition, install vs code
2. Clone repo
3. Use dotnet build command to restore and build the whole solution.
4. Use dotnet run command to run the application.
5. The installation page appears, follow steps and install application
6. Restart application and try browsing the application in Google Chrome, you will get the 403 unauthorized error.
7. Try browsing the application in Safari browser, you are able to launch the application successfully.

**Comment by skoshelev** [comment]
Hi, @alex-dhanasekar-tw. Could you please check the Chrome console to give us more details about the problem? Possible some error we on the nopCommerce logs?

**Comment by skoshelev** [comment]
We checked nopCommerce on MacOs + Chrome and found no issues. Perhaps your browser has cached something and it interferes with its normal operation, try clearing the cache and browser data.

Closed #6043
