### ISSUE TITLE
 null object reference when install nop 4.5

### ISSUE THREAD

**Issue by ahmedzakaria432** [nopSolutions/nopCommerce#6048]
nopCommerce version: 4.5

Steps to reproduce the problem: 
![image](https://user-images.githubusercontent.com/51932179/146980718-717352fe-acbc-4322-9711-93cae4da8f55.png)
getting this when trying to install nopcommerce 4.5 locally
create sample data : true
create database if not exist :true
enter raw connection checked 
connection string: data source=.;initial catalog=nop;integrated security=true
data provider :sqlServer

**Comment by glhays** [comment]
The period represents the local server in the connection string? Try inserting the sqlserver instance installed on the machine or server.
Not an issue for the git repo, post it in the forum.



________________________________
From: Ahmed zakaria ***@***.***>
Sent: Tuesday, December 21, 2021 11:14:00 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Nop.Core.Infrastructure.Singleton<T>.Instance.get returned null. (Issue #6048)


nopCommerce version: 4.5

Steps to reproduce the problem:
[image]<https://user-images.githubusercontent.com/51932179/146980718-717352fe-acbc-4322-9711-93cae4da8f55.png>
getting this when trying to install nopcommerce 4.5 locally
create sample data : true
create database if not exist :true
enter raw connection checked
connection string: data source=.;initial catalog=nop;integrated security=true
data provider :sqlServer

**Comment by ahmedzakaria432** [comment]
ok will post in forum

**Comment by RomanovM** [comment]
Duplicate of #6031
