### ISSUE TITLE
How to change source code and still get main source code changes

### ISSUE THREAD

**Issue by rezathecoder** [nopSolutions/nopCommerce#6051]
nopCommerce version: 
4.40.4

Hi. I need some development guid. I need to be able to change source code and add features to my shop and still be able to keep up with updated main source code. I don't want updating source code rollback my custom code but i still want to get bug fixes and ... .
I know i can develop plugins for most of the needs but there are sometimes that i need to change the core of nopCommerce.
Please suggest me a workflow that i can achieve my goal. Thanks!

**Comment by AndreiMaz** [comment]
Please post all questions on our forums. We use GitHub repository for issues only
