### ISSUE TITLE
Add a new "Manage connection string" permission

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6053]
nopCommerce version: 4.50

We should add a new separate permission to manage the connection string. This way all managers won't be able to manage connection string in admin area

![image](https://user-images.githubusercontent.com/5019111/147191700-7ae35156-4dbd-4551-ba30-444af4c53f53.png)

**Comment by DmitriyKulagin** [comment]
After some discussion, we decided to add a new permission to manage all application settings, as this solution covers a wider range of applications. Closed #6053
