### ISSUE TITLE
Followup on Products that are still in stock are incorrectly unpublished

### ISSUE THREAD

**Issue by serialseb** [nopSolutions/nopCommerce#6054]
The issue is closed, but i've added some comments. I apologise if this issue is not necessary, but it is sometimes the case that closed issues do not trigger notifications anymore in some repository (for example the Microsoft ones), and I'd like to understand what behaviour I'm seeing, as I'm very confused by it.

The original issue is #6040 

If this is not necessary because you get the notifications, I shall know in the future for this repo and close this issue immediately and apologise for the extra noise.

Thanks to the team.

**Comment by AndreiMaz** [comment]
Please do not duplicate issues. We'll check #6040 again
