### ISSUE TITLE
Replace sample pictures 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6056]
Let's upgrade the slider graphics on the home page (Nivo Silder). I don’t care about the internal products so much, but the first thing you see are five year old phones.

 It has iPhone 6 and Nokia Lumia 1020!  Makes people wonder if the store is behind the times.

**Comment by michalwitek1232** [comment]
@AndreiMaz is this thing getting deployed right now?
It might be reason for my issue https://github.com/nopSolutions/nopCommerce/issues/6286

**Comment by DmitriyKulagin** [comment]
Closed #6056
