### ISSUE TITLE
Check Cumulative Layout Shift (CLS)

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6057]
nopCommerce version: 4.40.4

> On my store and also the nopcommerce demo store the cumulative layout shift (CLS) on mobile is high at 0.183. This is screwing with the core web vitals in the google search console. Desktop rendering is unaffected.
> 
> I am aware there are ways to correct CLS but not an advanced user of css. The issue is coming from the main div wrapper. Since this is a core theme issue is why I am attempting to get some guidance on a possible solution here instead of the theme author. Any insight is appreciated.
> 
> It is conceivable that every nopcommerce 4.40.4 store is affected unless the store owner has addressed this issue themselves. This is the only issue keeping core web vitals from having "Good" urls.
> 
> `<div class="master-column-wrapper">`

Source: https://www.nopcommerce.com/boards/topic/92796/excessive-cls-on-demo-store-0183

Let's check it.

**Comment by joekrauss** [comment]
I confirm this issue exists on my site and I've paid multiple SEO experts to analyze the CLS issue. Most of the recommendations require removing elements like product sliders or pushing the text way below the screen to prevent the shift. Google is measuring our site negatively as the algorithm detects these overlapping images, buttons, and text.

**Comment by exileDev** [comment]
I have checked it and in Lighthouse CLS metric is 0.035. This may be because of the NivoSlider or other third-party plugins.

Closed #6057
