### ISSUE TITLE
Issue with cultures that use a comma as decimal separator

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6060]
nopCommerce version: 4.50 RC

something happened with the regional settings. Danish language uses ,(comma) as decimal seperator and if I select danish language and enters the products in admin i see wrong prices, weight and measures. They are multiplied with 10000. That has never been an issue before.

Example price with Danish 12000000,00 DKK but with UK it´s correct 1200.00DKK. Only in admin the display is wrong in storefront it always shows 1200 DKK no matter DA/UK.

If i change my regional setting on computer from , to . then it works fine. But somehow there is a problem as this is not right.

Source: https://www.nopcommerce.com/en/boards/topic/92834/nopcommerce-4500-rc-is-available#291427

Maybe, it's related to https://github.com/nopSolutions/nopCommerce/issues/6046 and https://github.com/nopSolutions/nopCommerce/issues/5756

**Comment by AndreiMaz** [comment]
@exileDev Also see https://www.nopcommerce.com/en/boards/topic/92834/nopcommerce-4500-rc-is-available/page/2#291583

**Comment by exileDev** [comment]
Closed #6060
