### ISSUE TITLE
Inventory : Reserve qty should not increase in warehouse 2 when configure multiple warehouse but actual stock qty reducing from warehouse 1

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6061]
![Reserve qty should not increase in warehouse 2 when configure multiple warehouse instead actual qty reducing from warehouse 1](https://user-images.githubusercontent.com/96106946/147671665-0496a51b-6949-4835-bf5d-f296c50a6a31.jpg)
nopCommerce version: 

Steps to reproduce the problem:

**Comment by AndreiMaz** [comment]
@JayPatel7348 Please provide a complete list of steps to reproduce the issue

**Comment by JayPatel7348** [comment]
please refer image trail to reproduce the problem:
![1](https://user-images.githubusercontent.com/96106946/147688281-86b80776-b21e-4ea2-9e59-1a586be6282a.PNG)
![2](https://user-images.githubusercontent.com/96106946/147688314-6234c511-bc4c-495f-82ce-771cd78652b0.PNG)
![3](https://user-images.githubusercontent.com/96106946/147688333-9266b102-2900-47d4-9f05-e62c8e25fcda.PNG)
![4](https://user-images.githubusercontent.com/96106946/147688349-9a10eb69-2e25-49b0-9506-08e142ed725b.PNG)
![5](https://user-images.githubusercontent.com/96106946/147688373-9ec2c0e6-cfce-4710-844c-47d2ce255d27.PNG)
![6](https://user-images.githubusercontent.com/96106946/147688384-96228189-3913-4711-b2fe-114f68eedddb.PNG)
![7](https://user-images.githubusercontent.com/96106946/147688392-29611628-5aef-400e-81f1-45de56bb678b.PNG)
![8](https://user-images.githubusercontent.com/96106946/147688399-e9d87b5f-ced9-4fa7-bb8f-9ebf996ceaa8.PNG)
![9](https://user-images.githubusercontent.com/96106946/147688407-4a8cfff5-c777-46c8-b067-cb9ca401f4d3.PNG)
![10](https://user-images.githubusercontent.com/96106946/147688419-cc615fb9-e79c-465e-b55b-d9ecedb5a7b7.PNG)
![11](https://user-images.githubusercontent.com/96106946/147688428-f7b6d64e-9a2c-4e40-8df8-f473d0fe2d01.PNG)
![12](https://user-images.githubusercontent.com/96106946/147688436-dcf6692b-c2fa-4284-8913-480d1434f6c9.PNG)
![13](https://user-images.githubusercontent.com/96106946/147688451-7ef09a78-cd2f-4c47-823e-48d5b963f9c9.PNG)

**Comment by JayPatel7348** [comment]
@AndreiMaz please review this issue again otherwise let me know if it's not an issue

**Comment by JayPatel7348** [comment]
> @JayPatel7348 Please provide a complete list of steps to reproduce the issue

**Comment by skoshelev** [comment]
Hi @JayPatel7348. This is not an issue. Most likely you miss warehouse choosing during creating the shipment:
![image](https://user-images.githubusercontent.com/16875599/148777568-f567f4d0-8c80-4125-8151-30837b21042f.png)

Closed #6061
