### ISSUE TITLE
Don't encode external authentication info at customer edit page

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6063]
nopCommerce version: 4.40.4

Steps to reproduce the problem: use an external authentication to login in any user, and edit this customer

In page '/Admin/Customer/Edit/{id}' will show like '\u5FAE\u4FE1\u767B\u5F55'

It's ok at front store page '/customer/info'

[see line 449](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Views/Customer/_CreateOrUpdate.Info.cshtml)

The system name of my external authenticaion provider is in Chinese.

Browser is Microsoft Edge beta 97.0.1072.41 64 bit.

**Comment by AndreiMaz** [comment]
@chensiel What exactly "an external authentication" are you using?

**Comment by chensiel** [comment]
> @chensiel What exactly "an external authentication" are you using?

Hello @AndreiMaz ExternalAuth.Wechat

Code the same like ExternalAuth.Facebook

`//create external authentication parameters
            var authenticationParameters = new ExternalAuthenticationParameters
            {
                ProviderSystemName = FacebookAuthenticationDefaults.SystemName,
                AccessToken = await HttpContext.GetTokenAsync(FacebookDefaults.AuthenticationScheme, "access_token"),
                Email = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.Email)?.Value,
                ExternalIdentifier = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.NameIdentifier)?.Value,
                ExternalDisplayIdentifier = authenticateResult.Principal.FindFirst(claim => claim.Type == ClaimTypes.Name)?.Value,
                Claims = authenticateResult.Principal.Claims.Select(claim => new ExternalAuthenticationClaim(claim.Type, claim.Value)).ToList()
            };

            //authenticate Nop user
            return await _externalAuthenticationService.AuthenticateAsync(authenticationParameters, returnUrl);`

**Comment by DmitriyKulagin** [comment]
Closed #6063

**Comment by chensiel** [comment]
@DmitriyKulagin  Hello, WebUtility.HtmlEncode tests ok. Email address maybe null, but this is not a issue, we can set it to stirng.Empty when it's null.
