### ISSUE TITLE
Consider migrate from linq2db to EF Core 6

### ISSUE THREAD

**Issue by goransipic** [nopSolutions/nopCommerce#6067]
There are significant improvements to query performance for EF Core 6.0.

> After these improvements, the gap between the popular "micro-ORM" Dapper and EF Core in the TechEmpower Fortunes benchmark narrowed from 55% to around a little under 5%.

 
Its this good argument for you to make consideration for migration to EF Core 6 from linq2db or you will continue using linq2db because other reasons? 

[EF Core 6 Improved performance on TechEmpower Fortunes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#improved-performance-on-techempower-fortunes)

**Comment by AndreiMaz** [comment]
No, we don't consider it because it still doesn't support 2-layer caching

**Comment by LuckyEvent** [comment]
[VahidN/EFCoreSecondLevelCacheInterceptor: EF Core Second Level Cache Interceptor](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor)
