### ISSUE TITLE
How to install a Let's Encrypt Certificate on a nopCommerce440 on Debian 11 installation?

### ISSUE THREAD

**Issue by jayjupdhig** [nopSolutions/nopCommerce#6068]
nopCommerce version: 440

Steps to reproduce the problem: Enter "sudo certbot --nginx --agree-tos --redirect --hsts --staple-ocsp --email dev@yourdomain.live -d test.yourdomain.live"

_________________________________________________________________________________________________________

Hi there

I used the command "sudo certbot --nginx --agree-tos --redirect --hsts --staple-ocsp --email dev@ourdomain.live -d test.ourdomain.live" , but the web browser tells me that it is invalid:

Issued by: localhost

Issued for: localhost

But the console output tolds me that the certificate generation was successful - with the original domain name in its text "test.ourdomain.live"...

Maybe somebody knows how to do that correctly?

Thank you very much for your feedbacks... :-) 

Best regards,
Jan

**Comment by jayjupdhig** [comment]
-> https://www.nopcommerce.com/en/boards/post-create/92912

**Comment by glhays** [comment]
Is this an issue of the software or an issue of the server being used?


________________________________

**Comment by AndreiMaz** [comment]
Please post all questions on our forums. GitHub is for work items only

**Comment by jayjupdhig** [comment]
ok thx
