### ISSUE TITLE
Discount Requirements Save Button Not Working

### ISSUE THREAD

**Issue by joekrauss** [nopSolutions/nopCommerce#6069]
nopCommerce version: 4.50.0

Steps to reproduce the problem: Try creating a discount using the discount plugin "customer role" with a condition for guest or admin. The save button does not trigger the save event.

**Comment by RomanovM** [comment]
@exileDev Yep, when js bundling is enabled, the save button does not work.

**Comment by exileDev** [comment]
@joekrauss Thank you! Closed #6069
