### ISSUE TITLE
Add published/Active to product attribute combination

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6071]
nopCommerce version: 4.40

Steps to reproduce the problem: 
If you have some combination inside a product, and you want to hide this combination without effecting the old orders or even the current pending orders for that combination

**Comment by RomanovM** [comment]
Perhaps we could mark combinations as `ISoftDeletedEntity `and just delete them.

**Comment by ahmadkq** [comment]
> Perhaps we could mark combinations as `ISoftDeletedEntity` and just delete them.

I believe make Active option is also good, as I want to hide a combination from the website for a period of time, then i want to active it later

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality. We'll consider the following one - https://github.com/nopSolutions/nopCommerce/issues/5114
