### ISSUE TITLE
Unknown TAX rates appearing

### ISSUE THREAD

**Issue by fencer** [nopSolutions/nopCommerce#6072]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
When editing an order from the admin, these mysterious TAX rates appear. We only have 3 tax rates setup (0%, 5% and 18%) yet these rates are appearing which would confuse the customer on the receipt.
![image](https://user-images.githubusercontent.com/620966/148927819-03aaccab-3329-432a-8a5b-a50ba4b49a3a.png)
![image](https://user-images.githubusercontent.com/620966/148928045-18891ac0-14cf-4b5b-aeed-8cff5ea2c6d1.png)

**Comment by RomanovM** [comment]
@fencer Is setting `AutoUpdateOrderTotalsOnEditingOrder` enabled?

**Comment by fencer** [comment]
Yes `AutoUpdateOrderTotalsOnEditingOrder` is enabled

**Comment by RomanovM** [comment]
@fencer Well, this feature is still in beta and may be unstable (see #8). For now, we recommend disabling this setting and manually editing the order details.

**Comment by glhays** [comment]
Can the version this issue relates to be established? 4.0.4?


________________________________

**Comment by fencer** [comment]
Just realised the version number is incorrect. Should have been 4.40.4

**Comment by RomanovM** [comment]
So, I close this issue for now, follow #8
