### ISSUE TITLE
Total amount mismatch in bestseller report

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6073]
nopCommerce version: 4.40

> In Admin > Report > Bestsellers, the total amount of all products is wrong
> The total now is calculated as Qty*Product total amount, which made the total amount of all products much bigger than it should be. The total should be sum of all products total, do not times the qty

Source: https://www.nopcommerce.com/boards/topic/92965/admin-report-calculation-error

See also: https://github.com/nopSolutions/nopCommerce/commit/a3199c357695f4fd29796af2ee62039fec47f56b

**Comment by exileDev** [comment]
Closed #6073
