### ISSUE TITLE
Is __RequestVerificationToken for ajax call missing?

### ISSUE THREAD

**Issue by scorpion86** [nopSolutions/nopCommerce#6074]
Hi! 
I have upgraded my code from 4.4 to 4.5 beta. I'm having problems with antyforgery tokens. 
For example in home page polls when i try to vote it returns "Failed to vote." response. When i look at it from console there is a "Error 400. Bad request".

In "public.common.js" there is a function which tries to add antiforgerytoken "addAntiForgeryToken(postData);" But when i look at the elements of the page from console there is no input with name "__RequestVerificationToken" because there is no form tag for poll.

By the way when i add [IgnoreAntiforgeryToken] to Vote method of PollController then it works fine.

Am i missing something?

**Comment by DmitriyKulagin** [comment]
Closed #6074
