### ISSUE TITLE
Wrong email validation

### ISSUE THREAD

**Issue by PiotrMarczuk** [nopSolutions/nopCommerce#6077]
nopCommerce version: 4.50-RC

Steps to reproduce the problem: 

**Initial conditions:**
Not logged in user is on login page.

**Steps:**
1. In field "E-mail" write "admin..admin@example.com"
2. In field "Password" write "password".
3. Click the "Log in" button

**Expected result:**
Under the field "E-mail" validation error is shown. "Log in" button is not sending request to log in. 

---

## Defect
System is allowing user to register / log in with wrong e-mail address.

## Screenshots
![image](https://user-images.githubusercontent.com/43501065/149470099-c0dfb468-c850-4881-bdeb-dab7c0860634.png)

## Expected result
System should not allow to register / login for e-mails having two dots in middle of it.

**Comment by RomanovM** [comment]
You cannot register with such an email. 
By default, server validation from FluentValidation is used, but you can customize it and add your own validation if needed.
