### ISSUE TITLE
Add decimal values to OrderDetailsModel

### ISSUE THREAD

**Issue by martingust** [nopSolutions/nopCommerce#6078]
It would be very handy to get the decimal values of OrderSubtotal, OrderTotal, OrderTotalDiscount in [OrderDetailsModel](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Models/Order/OrderDetailsModel.cs). Also this is needed on order to include these values in the WebApi plugin models.

Will submit a PR for this in a little bit...

**Comment by skoshelev** [comment]
Hi @martingust. Thanks for the help. I've merged your code, but note that I've redone passing all decimal fields as positive values

Closed by https://github.com/nopSolutions/nopCommerce/commit/cea39c11764616fa547237d55a173adafab59886

**Comment by martingust** [comment]
@skoshelev cool, yes that makes more sense. Thanks!
