### ISSUE TITLE
Code Refactoring: Use ViewComponent's type instead of name for strong typing

### ISSUE THREAD

**Issue by DamienLaw** [nopSolutions/nopCommerce#6081]
nopCommerce version: 4.5-rc

Instead of
```
[ViewComponent(Name = "CheckMoneyOrder")]
public class CheckMoneyOrderViewComponent : NopViewComponent
{
}

public class CheckMoneyOrderPaymentProcessor : BasePlugin, IPaymentMethod
{
    public string GetPublicViewComponentName()
    {
        return "CheckMoneyOrder";
    }
}
```

Do this instead
```
public class CheckMoneyOrderViewComponent : NopViewComponent
{
}

public class CheckMoneyOrderPaymentProcessor : BasePlugin, IPaymentMethod
{
    public Type GetPublicViewComponent()
    {
        return typeof(CheckMoneyOrderViewComponent);
    }
}
```

This extends to the entire codebase utilizing ViewComponents including Payment plugins, Shipping plugins, External Login plugins, etc. By using a stronger typing approach, the usages of ViewComponents can tracked across the solution.

According to https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0, 
![image](https://user-images.githubusercontent.com/14930009/149611152-b8a03184-9133-4103-91a2-0fe6863accbe.png)

**Comment by DmitriyKulagin** [comment]
Closed #6081
