### ISSUE TITLE
4.50 rc Uncaught TypeError: $(...).DataTable is not a function

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6083]
nopCommerce version: 4.50 rc

Steps to reproduce the problem: download 4.50 rc , install (region China, import sample data), open "/Admin/Product/List"

Language: ZH or other added language (not import resource file)

I have tested 5 regions at installation page: China,Hong Kong, Japana, USA, Canada

China and Hong Kong (default use Chinese language) have this issue, including adding other language after installation.

At others regions, there is no issue, also no issue after added orther languages like Chinese.

![image](https://user-images.githubusercontent.com/29729100/149645738-8bbcfa9c-60b2-4eea-8bd7-a705eca11b41.png)

![image](https://user-images.githubusercontent.com/29729100/149646652-481d2c96-0b0b-4b5f-bca3-7d00f7b3ae52.png)

**Comment by chensiel** [comment]
It works fine after I unchecked "JavaScript bundling and minification" at App settings page.

**Comment by exileDev** [comment]
@chensiel Hi! Thanks! We've excluded third-party scripts that cause the bundle to crash for these languages. We'll contact the developers to fix log errors in the console for the next version.
