### ISSUE TITLE
vulnerable in affiliates program

### ISSUE THREAD

**Issue by MafdyAzer** [nopSolutions/nopCommerce#6084]
I think that there's a vulnerable in affiliates program which allows store moderators to override customers affiliates.

nopCommerce version: 4.30

Steps to reproduce the problem: 
1- login to admin area.
2- create an affiliate for you.
3- go to Edit customer details for any customer which is not related to any affiliate, or related to another affiliate. 
4- press Place order (impersonate).
5- then open your affiliate link.

You'll see that this customer affiliates has been overridden to your affiliate link.

**Comment by AndreiMaz** [comment]
A store owner can edit any information (it's by design).

**Comment by MafdyAzer** [comment]
@AndreiMaz 
You're right Andrei that A store owner can edit any information, but I think this is a backdoor for untraced edit for some one who is just a moderator or even a call center agent, not an admin.

my suggestion for this issue is to validate SetCustomerAffiliate to not set affiliate to a customer during impersonate!
https://github.com/nopSolutions/nopCommerce/blob/3478554a1f6febe14332164e33d09376d5d909f5/src/Presentation/Nop.Web.Framework/Mvc/Filters/CheckAffiliateAttribute.cs#L74

I think those little enhancements will make nopCommerce more applicable to Enterprise business, If you think it's not, please ignore my message 😊,

Best regards,
