### ISSUE TITLE
Separation of Concerns between nopCommerce base and its payment plugins

### ISSUE THREAD

**Issue by DamienLaw** [nopSolutions/nopCommerce#6085]
This is a discussion to pick some of our brains to make nopCommerce even more extensible than it already is. See if this could lead to somewhere.

I notice that in some core areas like `Order` and `ProcessPaymentRequest`, contain properties such as `CreditCardType`, `CreditCardNumber`, `AuthorizationTransactionId`, etc. I think the core should not concern itself with data like this. This should be handled by payment plugins. If the payment plugin decides to store these data, then the plugin should persists them. It's not like the core has any uses for these data anyway. For example, when viewing Orders in the backoffice, use an extensibility point to pull "Additional Data" that the plugin wants to share and display the data when viewing the order details. If the customer wants to save credit card info to ease future checkouts, set up an extensibility point and get the plugin to do that.

If the core needs to concern itself to store these data, in the future the core would have to also store the blockchain wallet address and smart contract address if cryptocurrency payment becomes a thing (it's slowly becoming a thing now). Then the core would have more and more responsibilities.

The core should only be concerned when to pass a payment request to a payment plugin to process and whether it's successful. For recurring payments, void and refund, the core just needs to know when to delegate to the plugin.
The core shouldn't need to know if a plugin could "RePost" a failed payment. This is something that the plugin decides on its own. The core just displays a ViewComponent from payment plugins on the Order Details page, and the plugin's ViewComponent decides whether to display the button "Retry payment" and what happens when it's clicked. Therefore the method `CanRePostProcessPaymentAsync()` and `PostProcessPaymentAsync()` in the interface `IPaymentMethod` are redundant and could be removed.

Well, I guess what I've been saying is give more control to plugins, and introduce more extensibility points in `IPaymentMethod` in the form of "ViewComponent".

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this.
