### ISSUE TITLE
Redundant Bootstrap stylesheets in admin backoffice

### ISSUE THREAD

**Issue by DamienLaw** [nopSolutions/nopCommerce#6088]
nopCommerce version: 4.50-rc

![image](https://user-images.githubusercontent.com/14930009/150373208-d9b88755-2b59-4126-99c2-ab75b175362a.png)

There are two versions of Bootstrap stylesheets loaded. The older version v4.4.1 which comes together with AdminLTE is overriding the newer version v4.6.0. 

![image](https://user-images.githubusercontent.com/14930009/150374007-2d985987-4634-4d8e-8a9f-22bad2cee0a2.png)

I have reasons to believe that multiple js script files are loaded as well.

**Comment by DmitriyKulagin** [comment]
Closed #6088
