### ISSUE TITLE
Turn off GZIP compression does not work

### ISSUE THREAD

**Issue by jayjupdhig** [nopSolutions/nopCommerce#6097]
nopCommerce version: 4.40 on Debian 11 with nginx and Postgres

Steps to reproduce the problem: 

1.) Add the line ´gzip off;´ in file /etc/nginx/sites-available/default on that place:

` location / {

    # J.M., 2022-01-25 {
    gzip off;
    # } J.M., 2022-01-25

    proxy_pass         http://localhost:5000;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection keep-alive;
    proxy_set_header   Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    }`
    
2.) Restart nopCommerce and Nginx services: ´systemctl restart nopCommerce440 && systemctl restart nginx´

3.) Go to Chome Developer Page and refresh your site. Then, you will still see that, same as before: 

![Unbenannt](https://i.ibb.co/n8t75hy/Unbenannt.jpg)

**Comment by RomanovM** [comment]
Try to disable `CommonSettings.UseResponseCompression` setting in nopCommerce.
Please post all your questions on [our forums](https://www.nopcommerce.com/boards).
