### ISSUE TITLE
Product list (admin area). Filter by stock (in stock, out of stock) option

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#61]
For listing page if we add stock filter will be benefit for user . When we track to products stock and list page if user can select example: 

Stock Status: All, In stock, Out of stock or Low stock (as per "Low stock report" page). So this will be good option for buyer to see which of them in stock without go to product details. Do not forget about attribute combination

Source: http://www.nopcommerce.com/boards/t/31963/feature-request-category-list-page-filter-option-stock-.aspx

The question is whether we should do it. We already have "low stock products" page (report)

**Comment by martingust** [comment]
I think this should be very useful in the public store as well.

**Comment by AndreiMaz** [comment]
We already have "low stock products" page (report)
