### ISSUE TITLE
Google Analytics could skip "placed" orders with redirection payment method used

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#610]
User completes the checkout is using Paypal Standard plugin. It works in such a way that user is presented with "Confirm" button that takes them to the Paypal website. When Confirm buttton is pressed the user is redirected (via POST) to PayPal. Order placed page (which includes google analytics e-commerce tracking) is NOT shown and transaction is not recorded. 

User completes the payment but because the paypal requires two explicit actions for user to return to the store, this very often doesn't happen. User just closes the browser while on paypal page and transaction never gets recorded. 

In my store this is what happens maybe 50% of the time. 

RESULT: 
About 50% of paypal transactions are not recorded which makes making any meaningful marketing decisions very difficult. 

SUGGESTION: 
After user confirms the order, show user the "thank you - your order has been placed page". If Paypal standard payment is used after showing the page create a redirect. A nice "countdown" or something to indicate that redirect is about to happen would be nice. 

But it will count unpaid orders as well

Forum source: http://www.nopcommerce.com/boards/t/23138/google-analytics-not-recording-significant-numer-of-e-commerce-transactions.aspx

The problem is that it's not possible if the browser is closed

Also see related - https://github.com/nopSolutions/nopCommerce/issues/91

**Comment by AndreiMaz** [comment]
moved to https://github.com/nopSolutions/nopCommerce/issues/91
