### ISSUE TITLE
Rename GetWarehousesByIdAsync to GetWarehouseByIdAsync

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6103]
nopCommerce version: 4.50 rc

Steps to reproduce the problem: (no)

Method 'GetWarehouse**s**ByIdAsync' in IProductService should be rename to 'GetWarehouseByIdAsync'

**Comment by RogerSmithR** [comment]
Hi!
I'm working on it.

**Comment by RomanovM** [comment]
Fixed #6136
