### ISSUE TITLE
Wrong html tag

### ISSUE THREAD

**Issue by scorpion86** [nopSolutions/nopCommerce#6104]
https://github.com/nopSolutions/nopCommerce/blob/01be23f4b3fbeeeeb09693a3dbc36c283a8e74df/src/Plugins/Nop.Plugin.MultiFactorAuth.GoogleAuthenticator/Views/Configure.cshtml#L11

it should be "div" i think. Also it doesnt have closing tag.

**Comment by DmitriyKulagin** [comment]
Closed #6104
