### ISSUE TITLE
One page checkout not working when "Order totals on payment info tab" option is enabled

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6105]
nopCommerce version: 4.50

> **Expected Behavior:**
> Checkout completes successfully when "One Page Checkout" is enabled, regardless of "Order totals on payment info tab" option being enabled.
> 
> **Actual Behavior:**
> One page checkout does not work when the "Order totals on payment info tab" is enabled. The checkout process goes through till the "Payment Information" tab, then redirects to the cart page.
> 
> **Steps:**
> 1. Admin Panel -> Configuration -> Settings -> Order Settings -> Advanced
> 2. Enable "Use one page checkout"
> 3. Enable "Order totals on payment info tab" under the "Use one page checkout" option
> 4. Public Store -> Add item to cart
> 5. Cart page -> Checkout
> 6. Select/Enter information on all tabs
> 7. On "Payment Info" tab, click "Continue"
> 8. Instead of going to the "Confirm" tab, the user is redirected to the "Cart" page
> 
> **Workaround:**
> Checkout works successfully with the "Order totals on payment info tab" enabled, when either of these two are applied:
> 1. `asp-anti forgery=false` is added to the form _co-payment-info-form_ in _OnePageCheckout.cshtml_
> 2. `[IgnoreAntiforgeryToken]` is added to the _OpcSavePaymentInfo_ method in the _CheckoutController.cs_ class.

Source: https://www.nopcommerce.com/boards/topic/93066/one-page-checkout-not-working-when-order-totals-on-payment-info-tab-option-is-enabled-nop-version-45

**Comment by DmitriyKulagin** [comment]
Closed #6105
