### ISSUE TITLE
Azure | Marketplace ARM template fails deployment

### ISSUE THREAD

**Issue by AsafJosefMor** [nopSolutions/nopCommerce#6106]
nopCommerce version: `4.50`

Steps to reproduce the problem: Deploy nopCommerce from Azure marketplace / using ARM template.

Getting `HTTP Error 500.30 - ASP.NET Core app failed to start`

#5596
#5694

**Comment by skoshelev** [comment]
Azure no longer supports installation from the old marketplace, so we have no way to check if the template works correctly. We have decided to delete the old branch. You can use the master branch, it contains the latest stable code
