### ISSUE TITLE
4.50 Scheduled Tasks errors

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#6107]
nopCommerce version: 4.50

Steps to reproduce the problem: Getting multiple scheduled task errors (emails, keepalive, delete guests etc) eg.

"The "Send emails" scheduled task failed with the "Specified argument was out of the range of valid values. (Parameter 'value')" error (Task type: "Nop.Services.Messages.QueuedMessagesSendTask, Nop.Services". Store name: "nop4.50". Task run address: "http://nop45.socksandboots.com/scheduletask/runtask")."

"The "Keep alive" scheduled task failed with the "Specified argument was out of the range of valid values. (Parameter 'value')" error (Task type: "Nop.Services.Common.KeepAliveTask, Nop.Services". Store name: "nop4.50". Task run address: "http://nop45.socksandboots.com/scheduletask/runtask")."

I've set plenty of nopC sites up over the years, and not had this before. Don't get this on a default install of 4.40

**Comment by untiedshoes** [comment]
By the way, I don't get these errors running on localhost (IIS10) under https, but I do when installed on the server. 4.40 installed in the same way on the server has no errors.

**Comment by untiedshoes** [comment]
I've managed to find the issue. For some reason, the 'ScheduleTaskRunTimeout' setting in the appsettings file was set to 0. Also, via the App Settings in the Admin, I'm unable to set this to zero, as it only allows numeric values.

**Comment by manuel3108** [comment]
Yep also experienced this yesterday. If your appsettings.json file has a default value for the scheduled task timout of null this is problematic. 

Once you then save th appsettings page in the admin panel, your value gets rewritten to 0, which is fairly inconvenient.

I did not look at the code, but I think the value in the appsettings model probably needs to be changed from an int to an null able int
