### ISSUE TITLE
Multiple problems with connecting Postgres, MySQL and MSSQL with install page

### ISSUE THREAD

**Issue by maggymoller** [nopSolutions/nopCommerce#6109]
nopCommerce version: 4.5
Mac M1 Monterey 12.1
Visual Studio Code 1.63.2
Docker
psql (PostgreSQL) 14.1
Everleap connection string for MSSQL and MySQL

Steps to reproduce the problem: 

- `git clone github repo https://github.com/nopSolutions/nopCommerce.git`
- pull docker postgres image https://hub.docker.com/_/postgres
- `docker build -t nopcommerce .`
- `docker run -d -p 5000 nopcommerce`
- `docker-compose up -d`
--------------------------------------------------------------------------------------------------------------
Problem 1)

Debug and run with "Docker .NET core launch" in VSCode

Try to install with postgres server which is running smoothly locally. 

> Server name: localhost

> Database name: postgres

> SQL Username: postgres

> SQL Password: ******

When I try to connect with a raw connection string, the same error happens.

Tried both versions of connection strings:

`UserID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;Pooling=true;Min Pool Size=0;Max Pool Size=100;Connection Lifetime=0;`

`Data Source=sqlServerName;Initial Catalog=dbName;Persist Security Info=True;User ID=userName;Password=password;`

I get the following error:

Error:
```

An unhandled exception occurred while processing the request.

InvalidOperationException: The ConnectionString property has not been initialized.
Microsoft.Data.SqlClient.SqlConnection.PermissionDemand()

Stack Query Cookies Headers Routing
InvalidOperationException: The ConnectionString property has not been initialized.
Microsoft.Data.SqlClient.SqlConnection.PermissionDemand()
Microsoft.Data.SqlClient.SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)
Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource<DbConnectionInternal> retry, DbConnectionOptions userOptions)
Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource<DbConnectionInternal> retry, DbConnectionOptions userOptions)
Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource<DbConnectionInternal> retry, SqlConnectionOverrides overrides)
Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)
LinqToDB.Data.DataConnection+QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
LinqToDB.Linq.QueryRunner.ExecuteQueryAsync<T>(Query query, IDataContext dataContext, Mapper<T> mapper, Expression expression, object[] ps, object[] preambles, int queryNumber, Func<T, bool> func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
LinqToDB.Linq.QueryRunner.ExecuteQueryAsync<T>(Query query, IDataContext dataContext, Mapper<T> mapper, Expression expression, object[] ps, object[] preambles, int queryNumber, Func<T, bool> func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
LinqToDB.Linq.Builder.FirstSingleBuilder+FirstSingleContext+<>c__DisplayClass4_0<T>+<<GetFirstOrDefaultElement>b__1>d.MoveNext()
LinqToDB.Linq.ExpressionQuery<T>.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
Nop.Services.Customers.CustomerService+<>c__DisplayClass54_0+<<GetCustomerRoleBySystemNameAsync>b__2>d.MoveNext() in CustomerService.cs
Nop.Core.Caching.MemoryCacheManager.GetAsync<T>(CacheKey key, Func<Task<T>> acquire) in MemoryCacheManager.cs
Nop.Services.Customers.CustomerService.GetCustomerRoleBySystemNameAsync(string systemName) in CustomerService.cs
Nop.Services.Customers.CustomerService.InsertGuestCustomerAsync() in CustomerService.cs
Nop.Web.Framework.WebWorkContext.SetCurrentCustomerAsync(Customer customer) in WebWorkContext.cs
Nop.Web.Framework.WebWorkContext.GetCurrentCustomerAsync() in WebWorkContext.cs
Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c+<<UseBadRequestResult>b__4_0>d.MoveNext() in ApplicationBuilderExtensions.cs
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
--------------------------------------------------------------------------------------------------------------
Problem 2)

When I try to Run and debug with ".NET Core Launch (web)" in VS Code, I get the following errors on the install page:

With postgres locally and with raw connection string:
`Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.`

With MS SQL raw connection string:
`Setup failed: An error occurred while creating the database: Login failed for user 'DB_7395_noptest_user'.`

With MySQL raw connection string:
`Setup failed: An error occurred while creating the database: Authentication to host 'my01.everleap.com' for user 'maggy' using method 'mysql_native_password' failed with message: Access denied for user 'maggy'@'123.45.67.89' (using password: YES)`

I've tried to add to web.config the following:

`<connectionStrings>
    <add name="Nop"  connectionString="server=localhost;port=5432;user id=postgres;password=****;database=postgres"    providerName="Npgsql" />
</connectionStrings>`

I've tried to add Npgsql but it didn't change anything. 

All comments appreciated.

This was closed but it continues to trouble me so if someone has a solution I would greatly appreciate it.

**Comment by maggymoller** [comment]
Now when I try to connect through docker in VS Code and PostgeSQL, I get this error on the install page: 

`Setup failed: An error occured while creating the database: Failed to connect to [::1]:5432`

**Comment by sulejmank** [comment]
Have same issue with MSSQL and linux machine. 
Dockers are up and running, I can connect to DB with terminal. But from install page when I try I always get `The ConnectionString property has not been initialized.` 
Any updates or tips?

**Comment by ekjuanrejon** [comment]
having the same issue

**Comment by ekjuanrejon** [comment]
having the same issue. it's buggy

**Comment by ekjuanrejon** [comment]
I had the same issue. The issue for me was line below. I was injecting the plugin service that caused the issuer. to overcome the issue i created a scope on the service provider

`DataSettingsManager.LoadSettings()`

**Comment by ChrisClaude** [comment]
I've got a similar issue when running the app for the first time in visual studio 2022. I'm getting the following error message

### An error occurred while starting the application.
#### Win32Exception: The certificate chain was issued by an authority that is not trusted.
Unknown location

#### SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

#### DependencyResolutionException: An exception was thrown while activating λ:Nop.Core.Domain.Common.CommonSettings.
Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action<ResolveRequestContext> next)

#### Win32Exception: The certificate chain was issued by an authority that is not trusted.

![image](https://user-images.githubusercontent.com/40432185/165512658-e9088e9d-4347-4b0d-bcbc-bc84579d3caa.png)

**Comment by exileDev** [comment]
@maggymoller I've just checked docker on Windows. It works fine:
```
docker pull postgres
docker run -e POSTGRES_PASSWORD=pass postgres
```
```
docker build -t nopcommerce .
docker run -d -p 80:80 nopcommerce
```

```
docker network create docker-nop-network
docker network connect docker-nop-network {postgres_container}
docker network connect docker-nop-network {nopcommerce_container}
```

```
docker network inspect

"Containers": {
            ...,
            "...": {
                "Name": "{postgres_container}",
                "EndpointID": "",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16"
            }
        }
```
When you open the installation page fill the Server name field with the IPv4Address value
