### ISSUE TITLE
Update a hint of the "Quantity returned to stock" field from the "Edit return request details" page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#6111]
nopCommerce version: 4.50

Steps to reproduce the problem: 
Visit the edit return request details page and see that the hint is not clear and doesn't reflect the sense of the field it's related to.
![6228aa59e7](https://user-images.githubusercontent.com/16681184/152129804-e17070de-dacf-4312-aff3-2950b8b1b310.jpg)
.

**Comment by DmitriyKulagin** [comment]
Closed #6111
