### ISSUE TITLE
Add space between  Delete selected  and  Clear log buttons on the Avalara configuration page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#6114]
nopCommerce version: 4.50

Steps to reproduce the problem: 
![5ee760518b](https://user-images.githubusercontent.com/16681184/152358136-001aabe6-eb0e-4ad4-a674-f884416bfa8a.jpg)

**Comment by DmitriyKulagin** [comment]
Closed #6114. Not reproduced on the latest version.
