### ISSUE TITLE
_ProductBox.cshtml ShortDescription is hidden by css in DefaultClean

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6115]
nopCommerce version: 4.5, probably also before

Steps to reproduce the problem: 
* Create a product
* Add a short description
* View the product in frontend-catalog
* You will not see the short description, although it was added to the view:  https://github.com/nopSolutions/nopCommerce/blob/bc20a8b8ebdfe29ee003c643363ec81b81bcdd8c/src/Presentation/Nop.Web/Views/Shared/_ProductBox.cshtml#L55-L57
* Inspect the elements and find that this rule is causing a problem:
https://github.com/nopSolutions/nopCommerce/blob/bc20a8b8ebdfe29ee003c643363ec81b81bcdd8c/src/Presentation/Nop.Web/Themes/DefaultClean/Content/css/styles.css#L1770-L1772

Expected behaviour:
If you add the short description to the view in the product box, it should also be visible in the DefaultClean Theme.

**Comment by Manuel-Innovapps** [comment]
Workaround, without modifying core to much:
Add the following css to your custom css file:
```css
.item-box .description {
    display: block !important;
}
```

**Comment by Manuel-Innovapps** [comment]
@RomanovM Could you please check this code again?

```csharp
            //#6115
            if (!settingService.SettingExistsAsync(catalogSettings, settings => settings.ShowShortDescriptionOnCatalogPages).Result)
            {
                catalogSettings.ShowShortDescriptionOnCatalogPages = false;
                settingService.SaveSettingAsync(catalogSettings, settings => settings.ShowShortDescriptionOnCatalogPages).Wait();
            }

```

I think the default value should be true, as this is the current behavior. Only the css was hiding it in default clean, but this was not the case for extrnal themes

**Comment by RomanovM** [comment]
@Manuel-Innovapps We don't know how this is used in third-party themes. But in a clean theme it didn't display, so it would be strange for those who are using the default theme if the description appears after an upgrade.
Anyway, it's easy to change the setting value.
