### ISSUE TITLE
performance issue when having many Discounts with coupon required 

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6125]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1- Create 1000 discount with coupon required enabled, type is applied to categories.
2- To have some Products on the home page.
3- Inside GetAllowedDiscountsAsync method, it retrieves all discounts and do check and calculations, while it shouldn't as the coupon is required.
4- Performance issue will appear in this case!

**Comment by RomanovM** [comment]
See also: #3663 #2707 #87

**Comment by skoshelev** [comment]
hi @ahmadkq 

I analyzed the code regarding the problem you described, but all the necessary checks are in the code and no extra discounts are involved in the calculations, see the code at the links below:

https://github.com/nopSolutions/nopCommerce/blob/release-4.40.4/src/Libraries/Nop.Services/Catalog/PriceCalculationService.cs#L133

https://github.com/nopSolutions/nopCommerce/blob/release-4.40.4/src/Libraries/Nop.Services/Discounts/DiscountService.cs#L521

Closed #6125

**Comment by ahmadkq** [comment]
Hi @skoshelev,

The issue is on homepage, i checked the code and i know that you apply the discount to the item if the copoun is already applied but this will make an issue at the home page when you have lot of discounts to check. I suggest to check the discounts that has coupons only in the cart.  What do you think?
