### ISSUE TITLE
MySqlConnector instead of MySql.Data Library

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#6135]
I have implemented a linq2db retry logic for resilient database connnnection.

I had some problems managing it. But the I was advised to use MySqlConnector instead of MySql.Data library.

As soon as I switched to MySqlConnector, the performance increased alot and got rid of connection issues.

Is there any good reason to use MySql.Data instead of MySqlConnector api? 
For now I haven't realized any issues.
I works like a charm.

Any advise is appreciated

**Comment by exileDev** [comment]
Duplicated #5985

PS: There are still some issues related to linq2db.

**Comment by streamzyuk** [comment]
> Duplicated #5985
> 
> PS: There are still some issues related to linq2db.

What kind of issues  ?

**Comment by exileDev** [comment]
> What kind of issues ?

Some reports, for example.
