### ISSUE TITLE
 System.IO.DirectoryNotFoundException: /var/www/nopCommerce450/Themes/

### ISSUE THREAD

**Issue by abdullah-bin-hasan** [nopSolutions/nopCommerce#6138]
nopCommerce version: develop

Steps to reproduce the problem: 

Download and latest source code on a windows machine with visual studio installed.
- The windows dev machine has .NET 6.0 SDK installed
- start Developer Command Prompt for Visual Studio
- navigate to
src/Presentation/Nop.Web
folder of the source tree
- run command:
`dotnet publish -c Release -r linux-arm64`

**Comment by skoshelev** [comment]
Try to use the following command:

`dotnet publish Nop.Web.csproj -c Release -r linux-arm64`

Also, please post your question on our forum

Closed #6138
