### ISSUE TITLE
NopHtml.AddScriptParts not working in one page checkout

### ISSUE THREAD

**Issue by aalruthai** [nopSolutions/nopCommerce#6143]
nopCommerce version: 4.50

Steps to reproduce the problem: 
I've created a payment plugin that uses javascript libraries, I add the script file to my plugin's PaymentInfo.cshtml view using the helper method
NopHtml.AddScriptParts(ResourceLocation.Footer, "~/Plugins/Nop.Plugin.Payments.myPlugin/Scripts/myscript.js", "", true, false);

when I use one page checkout the script file is not loaded when I reach the payment step, but when I use the multi-step checkout the script file is loaded when I reach the payment step.
Is this a bug or am I using the NopHtml.AddScriptParts wrong?

**Comment by RomanovM** [comment]
For the one-page checkout, you need to add scripts from the backend, see how this was done in our [Square payment plugin](https://github.com/nopSolutions/square-plugin-for-nopcommerce/blob/nopCommerce-4.50/Nop.Plugin.Payments.Square/Services/EventConsumer.cs#L55).

**Comment by aalruthai** [comment]
Thanks, it worked
