### ISSUE TITLE
Langauges is not loaded by default

### ISSUE THREAD

**Issue by HarunKilic** [nopSolutions/nopCommerce#6144]
Langauges is not loaded by default.
It will only get loaded when I route to:  `Configuration` -> `Languages` -> `Edit`. 
This happens everytime the server gets restarted. 

<img width="1702" alt="Screenshot 2022-02-21 at 10 52 53" src="https://user-images.githubusercontent.com/13366825/154931137-c1ae76c5-f4e1-48d8-b96a-623e386033e9.png">

nopCommerce version: 4.50.0
os: OSX Arm64 M1

Steps to reproduce the problem: 
Create a new project
Go to Admin Area

**Comment by RomanovM** [comment]
All localization resources are loaded and cached on startup (and after restart) by default. And this works fine everywhere. 
So we need more details about the problem. 
Or try to post your question on [our forums](https://www.nopcommerce.com/boards/).

**Comment by HarunKilic** [comment]
Seems more like a bug. I've tried to install a brand new environment on Windows also. Same happens. 
The localization is loaded on Storefront, but not on dashboard.

**Comment by HarunKilic** [comment]
@RomanovM Can we please reopen this issue? 
I've managed to track where the bug might be. 
The function `PrepareLocaleResourceListModelAsync()` in `LanguageModelFactory` seems not to be called on startup or the localizations is not cached. 

I've tried to change this query: https://github.com/nopSolutions/nopCommerce/blob/0d3e2700faa1bef8b49ea172781d67d90e6992e1/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L289

To: simply `query =  query.Where(r => r.ResourceName.StartsWith(NopLocalizationDefaults.AdminLocaleStringResourcesPrefix))` 

That fixed the problem and loaded the localizations at startup. 

Not sure about where the exact problem is, as i am pretty new to the project. But would be nice if you could take a look.
