### ISSUE TITLE
Sitemap not showing up in Footer

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6145]
nopCommerce version: 4.50

Expected Behavior:
Sitemap should be displayed in the footer when the appropriate settings are enabled.

Actual Behavior:
After respectively disabling and enabling the setting Sitemap enabled, Sitemap doesn't show up. Debugging shows the checked value of Sitemap enabled is not passed to the controller.

Steps:
1. Admin Panel -> Configuration -> Settings -> General Settings
2. Uncheck Sitemap enabled on the Sitemap section if it's checked
3. Save
4. Public Store -> Footer -> No Sitemap item under information column, as expected.
5. Return to Admin Panel -> Configuration -> Settings -> General Settings
6. Ensure Display "Sitemap" on the Footer items section is checked
7. Check Sitemap enabled on the Sitemap section
8. Public Store -> Footer -> No Sitemap item under information column

[A.M. comment] Looks like the "Sitemap enabled" setting is not properly saved

Source: https://www.nopcommerce.com/en/boards/topic/93456/sitemap-not-showing-up-in-footer-nop-version-45

**Comment by DmitriyKulagin** [comment]
Closed #6145
