### ISSUE TITLE
Migration Exception  from 3.80  to 4.50.

### ISSUE THREAD

**Issue by luc-cap** [nopSolutions/nopCommerce#6146]
Hi,
    I updated  a Nop_3.80 to Nop_4.50.

From 3.80 to  4.30 I applied scripts.

I got only an Exception  resolved with  this  command:

     INSERT INTO [dbo].[Setting] ([Name],[Value],[StoreId]) VALUES ('shippingsettings.ShippingSortingEnum','1',0)
     GO

Bye

Luca

**Comment by RomanovM** [comment]
Thanks for the info. The problem with settings migration should be solved in #6098.
