### ISSUE TITLE
Sort by A-Z and Z-A not working on product listing pages

### ISSUE THREAD

**Issue by purplepiranha** [nopSolutions/nopCommerce#6150]
nopCommerce version: 4.50.00

Steps to reproduce the problem: 
On a product listing select Sort by: Name A-Z or Name Z-A. Sorting is not alphabetical.

You can replicate this on the demo store using this page:
https://demo.nopcommerce.com/camera-photo

**Comment by RomanovM** [comment]
Seems that it has been broken in #6027 commits

**Comment by skoshelev** [comment]
Closed #6150
