### ISSUE TITLE
Wishlist crashes the system

### ISSUE THREAD

**Issue by volcanodeng** [nopSolutions/nopCommerce#6151]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
1.Anonymous click into any product detail page
2.Add the product to wishlist,and add products to shoppingcart immediately in your wishlist
3.Now you can not visit you nop anymore

Error message:System.IO.IOException: The system cannot open the device or file specified. : '0000029_70.jpeg'

**Comment by RomanovM** [comment]
It works fine on a clean installation. 
Try to post your question on [our forums](https://www.nopcommerce.com/boards), if the problem is confirmed and no solution is found, we'll reopen this issue.
