### ISSUE TITLE
Move customer fields from GenericAttribute table to Customer table. Prepare the upgrade scripts.

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6153]
nopCommerce version: develop

In continuation of #4601.
We should prepare the SQL scripts (for each supported db provider) for the upgrade. It will be needed for users who will update db manually, without migration (for example, if there are many records in the `Customer` and `GenericAttribute` tables).

**Comment by skoshelev** [comment]
Closed #6153
