### ISSUE TITLE
ProductService.SearchProductsAsync: Allow search by gtin

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6158]
nopCommerce version: 4.40.x to now

Steps to reproduce the problem: 
1. Enter a gtin / ean for a product
2. try to use the search on the frontend with the gtin to find the specified product
3. You will not be able to find it

I / We suggest to allow searching by gtin. This is the code block that would require a change

**Comment by Manuel-Innovapps** [comment]
Hey @AndreiMaz 

I personally disagree, because this is just one line of code to be added to nopCommerce. 
Leaving this for customization usually means that you need to override the SearchProductsAsync method, which on a side node is pretty huge. And then you need to add your one line of code, just to add some such basic functionality? And destroy the upgradability for future nopUpdates?

An alternative that we have used is to add the GTIN as a product tag, so that we can easily make the gtin searchable.

We have proposed those two options to some of our customers, but they have always decided to go with the product tags, as it produces less cost on their side.

Please re-consider this decision.

**Comment by AxelAndersen** [comment]
The biggest problem for us is that we cant scan a product with an EAN number and find it in Nop.
There is no barcode on any product which states the SKU, 
SKU is totally irrelevant to us

But to search by GITN is so much more important to us, because you can then scan the product label.
