### ISSUE TITLE
FileRoxyFilemanService throws exception with certain images

### ISSUE THREAD

**Issue by walcher** [nopSolutions/nopCommerce#6161]
nopCommerce version: 
4.50.0

Steps to reproduce the problem: 
Upload attached image using roxy file manager. 
![3_1296](https://user-images.githubusercontent.com/4481186/156838119-5fc23a1c-5a7d-4e52-904b-0795855108c4.jpg)

According to this bug https://github.com/mono/SkiaSharp/issues/1846 a possible workaround should be changing lince 546 on FileRoxyFilemanService.cs to 

var skData = SKData.Create(stream);
var image = SKBitmap.DecodeBounds(skData);

as this:

![fix](https://user-images.githubusercontent.com/4481186/156838339-7192907d-48ba-4759-b7b1-1b0a3240dee8.png)

**Comment by chensiel** [comment]
Hello,
Code 'var image = SKBitmap.DecodeBounds(stream);' in 'FileRoxyFilemanService.cs' also throws exception with some images.
I changed this to 'var image = SKImage.FromEncodedData(stream);', it works fine.
[SkiaSharp issues 1621](https://github.com/mono/SkiaSharp/issues/1621)

**Comment by AndreiMaz** [comment]
@chensiel Could you please some of these images here?

**Comment by DmitriyKulagin** [comment]
Closed #6161
