### ISSUE TITLE
InitializePlugins -- Value cannot be null. (Parameter 'source') 

### ISSUE THREAD

**Issue by ramsingh333** [nopSolutions/nopCommerce#6163]
nopCommerce Version: 4.50.1--latest

Steps to reproduce the problem: 

I just downloaded the code from GitHub in ZIP format, Extracted it over the Local System. Build the Solution and Run it.

it gave me Error:

Value cannot be null. (Parameter 'source') -- Method Name "InitializePlugins"

**Comment by ramsingh333** [comment]
and when i download 4.40 and run it. Installation works perfectly fine. but when I run the solution again, Plugin throw error same method as mentioned above and the error is: 

"Unable to load one or more of the requested types.
Method '<Clone>$' in type 'Nop.Plugin.Misc.Sendinblue.Models.SendinblueMessageTemplateListModel' from assembly 'Nop.Plugin.Misc.Sendinblue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."

**Comment by RomanovM** [comment]
Has been broken in refactoring of #6102, I reopened the initial issue.
