### ISSUE TITLE
If Russia disconnects itself from the global Internet

### ISSUE THREAD

**Issue by cimpok** [nopSolutions/nopCommerce#6164]
[https://twitter.com/nexta_tv/status/1500553480548892679](https://twitter.com/nexta_tv/status/1500553480548892679)

If this is true, (it seems credible, we have witnessed far less likely events happening in the past two weeks) Russia will cut itself off from the global internet in days. If I got it right it will be a physical disconnection, so no VPN or TOR, etc. trick to circumvent it will work either.  

Is there a contingency plan to maintain supporting this software repository by its developers in Russia?  Please be prepared if there's anything you can arrange now.

**Comment by AndreiMaz** [comment]
No worries about that. Please see my reply at https://www.nopcommerce.com/en/boards/topic/93049/nopcommerce-450-is-released/page/4#293435

Furthermore, some of our team members have already relocated to other country.

**Comment by cimpok** [comment]
Thank you, this is somewhat reassuring.
Hope those who relocated and those who stay will reclaim back your beautiful country from that moron soon.
