### ISSUE TITLE
Add antiforgery token

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#6165]
nopCommerce version: 4.50

Steps to reproduce the problem: 

> I set "Hide newsletter box" to true and no Community Poll on home page (no forms) then there is no cookie of .Nop.Antiforgery
> As a result, customers will not be able to add products to Cart on home page or in product page.

Source: https://www.nopcommerce.com/en/boards/topic/93635/no-antiforgery-token

**Comment by eplsoftware** [comment]
I have the same problem.

**Comment by DmitriyKulagin** [comment]
Closed #6165
