### ISSUE TITLE
Add Reply-To for Order Notification Email

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6167]
nopCommerce version: 4.50

> When I receive an order, sometimes I want to reply to the customer directly from the order notification email.  Rather than copy and paste the customers email address from the body of the email, it would be easier to click Reply and the customers email address is already in the To field.

Source: https://www.nopcommerce.com/boards/topic/93657/add-reply-to-for-order-notification-email

We could add a new property to `MessageTemplate` whether to fill in `ReplyTo` with a customer (or admin) email if applicable.
We already have `ReplyTo` parameters in `SendNotification` method, so we should pass them when this new property is set for the particular message template.

**Comment by ChrisClaude** [comment]
If this task has no assignee. I would love to be assigned to it.

**Comment by AndreiMaz** [comment]
@ChrisClaude Please feel free to make to make a pull request

**Comment by micolf** [comment]
i have the same problem

**Comment by micolf** [comment]
@RomanovM do you have find a solution?

**Comment by parshan2** [comment]
I have filled out `replyToEmailAddress` and `replyToName` parameter of `SendNotificationAsync` method for most admin email messages.
@skoshelev any suggestion!

**Comment by skoshelev** [comment]
Hi, @parshan2. I looked at your changes, and have a couple of points:

- part of the code is duplicated from method to method, it is more logical to group it into a separate method
- Initially, the task included a condition that it would be possible to configure filling in the fields for a response within a specific template, since often responses are not expected for email templates

**Comment by parshan2** [comment]
Hi, @skoshelev . do you agree to add a new property named **`AllowToReply`** or **`AllowDirectReply`** to message templates.
When enabled it will allow admin to reply to the messages that is generated based on customer activity.

PS: What should this option mean for the emails that are sent to the customers?

![image](https://user-images.githubusercontent.com/10446385/220038965-0207a127-f350-4b8a-a02d-55991276474b.png)

**Comment by micolf** [comment]
i resolved thank you

Il giorno lun 20 feb 2023 alle ore 14:30 Sergey Koshelev <
***@***.***> ha scritto:

**Comment by parshan2** [comment]
@skoshelev filling `ReplyTo` fields with mail account data makes no sense. currently customer can reply to default sender that is the same as the sender mail account data.
Let me know if you have a better argument for that in mind.

I propose following methods to get ReplyToEmail and ReplyToName for most store owner templates:

        /// <summary>
        /// Get email and name to set ReplyTo property of email from customer 
        /// </summary>
        /// <param name="messageTemplate">Message template</param>
        /// <param name="customer">Customer</param>
        /// <returns>Email address and name when reply to email</returns>
        protected virtual async Task<(string email, string name)> GetCustomerReplyToNameAndEmail(MessageTemplate messageTemplate, Customer customer)
        {
            if (!messageTemplate.AllowDirectReply)
                return ("", "");

            var replyToEmail = await _customerService.IsGuestAsync(customer)
                ? string.Empty
                : customer.Email;
            var replyToName = await _customerService.IsGuestAsync(customer)
                ? string.Empty 
                : await _customerService.GetCustomerFullNameAsync(customer);

            return (replyToEmail, replyToName);
        }

        /// <summary>
        /// Get email and name to set ReplyTo property of email from order
        /// </summary>
        /// <param name="messageTemplate">Message template</param>
        /// <param name="order">Order</param>
        /// <returns>Email address and name when reply to email</returns>
        protected virtual async Task<(string email, string name)> GetCustomerReplyToNameAndEmail(MessageTemplate messageTemplate, Order order)
        {
            if (!messageTemplate.AllowDirectReply)
                return ("", "");

            var billingAddress = await _addressService.GetAddressByIdAsync(order.BillingAddressId);

            return (billingAddress.Email, $"{billingAddress.FirstName} {billingAddress.LastName}");
        }

**Comment by skoshelev** [comment]
Hi @parshan2. I have no better argument than the consistency of behavior. if the AllowDirectReply setting for the template is enabled - fill in the ReplyTo data.

As for the implementation of the GetCustomerReplyToNameAndEmail methods, I have no special comments.

Thanks again for your help
