### ISSUE TITLE
Custom address fields are not saving for vendor

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6168]
nopCommerce version: 4.50

> Step 1:  Create Custom Address fields from admin
> Step 2: Edit Vendor from Admin can put Custom Address Fields.
> its not saving.

Source: https://www.nopcommerce.com/boards/topic/93640/custom-address-fields-are-not-saving-for-vendor

**Comment by DmitriyKulagin** [comment]
Closed #6168
