### ISSUE TITLE
Log error details when picture service cannot process an image

### ISSUE THREAD

**Issue by aquaristar** [nopSolutions/nopCommerce#6170]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. Installed Nop-Templates and enabled CloudZoom
2. upload my some JPEG Pictures for a Product in admin
3. When the product page I got "We're sorry, an internal error occurred."
4. When I check log menu in admin following exception was happened.

System.NullReferenceException: Object reference not set to an instance of an object.
   at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.GetCloudZoomPictureModelForPictureAsync(ProductDetailsModel productModel, MediaSettings mediaSettings, Picture picture, MemoryStream stream)
   at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.GetCloudZoomPictureModelAsync(ProductDetailsModel productModel, MediaSettings mediaSettings, Picture picture)
   at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.PopulateCloudZoomModelAsync(ProductDetailsModel productModel, CloudZoomModel cloudZoomModel)
   at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.InvokeAsync(String widgetZone, ProductDetailsModel additionalData)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)

5.I contacted with CloudZoom team with this problem and after they checked it and replied that's caused by Nop PictureService problem. Following is some of CloudZoom source for debugging.
```

private async Task<CloudZoomPictureModel> GetCloudZoomPictureModelForPictureAsync(
      ProductDetailsModel productModel,
      MediaSettings mediaSettings,
      Picture picture,
      MemoryStream stream)
    {
      string smallImageUrl1 = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, mediaSettings.ProductDetailsPictureSize, true, (string) null, (PictureType) 1);
      int pictureWidth = 0;
      int pictureHeight = 0;
      if (!string.IsNullOrEmpty(smallImageUrl1))
      {
        try
        {
          using (SKBitmap skBitmap = SKBitmap.Decode(await this._pictureService.LoadPictureBinaryAsync(picture)))
          {
            pictureWidth = skBitmap.Width;
            pictureHeight = skBitmap.Height;
          }
        }
        catch (ArgumentException ex)
        {
          await EngineContext.Current.Resolve<ILogger>((IServiceScope) null).ErrorAsync(string.Format("The picture file with id: {0}, URL: {1} appears to be corrupted or damaged.", (object) ((BaseEntity) picture).Id, (object) smallImageUrl1), (Exception) ex, (Customer) null);
        }
      }
      CloudZoomPictureModel zoomPictureModel1 = new CloudZoomPictureModel();
      CloudZoomPictureModel zoomPictureModel2 = zoomPictureModel1;
      string str1;
      if (!string.IsNullOrEmpty(picture.AltAttribute))
        str1 = picture.AltAttribute;
      else
        str1 = string.Format(await this._localizationService.GetResourceAsync("Media.Product.ImageAlternateTextFormat.Details"), (object) productModel.Name);
      zoomPictureModel2.AlternateText = str1;
      CloudZoomPictureModel zoomPictureModel3 = zoomPictureModel1;
      zoomPictureModel3.FullSizeImageUrl = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, 0, true, (string) null, (PictureType) 1);
      zoomPictureModel1.SmallImageUrl = smallImageUrl1;
      CloudZoomPictureModel zoomPictureModel4 = zoomPictureModel1;
      zoomPictureModel4.TinyImageUrl = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, mediaSettings.ProductThumbPictureSizeOnProductDetailsPage, true, (string) null, (PictureType) 1);
      CloudZoomPictureModel zoomPictureModel5 = zoomPictureModel1;
      string str2;
      if (!string.IsNullOrEmpty(picture.TitleAttribute))
        str2 = picture.TitleAttribute;
      else
        str2 = string.Format(await this._localizationService.GetResourceAsync("Media.Product.ImageLinkTitleFormat.Details"), (object) productModel.Name);
      zoomPictureModel5.Title = str2;
      zoomPictureModel1.PictureWidth = pictureWidth;
      zoomPictureModel1.PictureHeight = pictureHeight;
      zoomPictureModel1.DefaultRelation = this.GetRelation("default", smallImageUrl1);
      CloudZoomPictureModel zoomPictureModel6 = zoomPictureModel1;
      string smallImageUrl2 = smallImageUrl1;
      string pictureUrlAsync = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, 0, true, (string) null, (PictureType) 1);
      zoomPictureModel6.GalleryRelation = this.GetRelation("gallery", smallImageUrl2, pictureUrlAsync);
      CloudZoomPictureModel modelForPictureAsync = zoomPictureModel1;
      smallImageUrl1 = (string) null;
      return modelForPictureAsync;
    }
```

6. I attached here one picture file causing the problem. When I open the product url and check wwwroot/images/thumbs dir then generating thumbs of this picture are failed.
![1434730](https://user-images.githubusercontent.com/681512/157871235-f97883b0-85c6-4a5b-8ce9-3ed26080550c.jpg)

**Comment by aquaristar** [comment]
I have checked in detail about the jpeg file if it's corrupted or having something specials than others but I have not found yet.

**Comment by glhays** [comment]
Did you report it to the 3rd party Nop-Templates?


________________________________
From: Mike Zeen ***@***.***>
Sent: Friday, March 11, 2022 5:01:41 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Generate Thumbnails using (Issue #6170)


nopCommerce version: 4.40.3

Steps to reproduce the problem:

  1.  Installed Nop-Templates and enabled CloudZoom
  2.  upload my some JPEG Pictures for a Product in admin
  3.  When the product page I got "We're sorry, an internal error occurred."
  4.  When I check log menu in admin following exception was happened.

System.NullReferenceException: Object reference not set to an instance of an object.
at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.GetCloudZoomPictureModelForPictureAsync(ProductDetailsModel productModel, MediaSettings mediaSettings, Picture picture, MemoryStream stream)
at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.GetCloudZoomPictureModelAsync(ProductDetailsModel productModel, MediaSettings mediaSettings, Picture picture)
at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.PopulateCloudZoomModelAsync(ProductDetailsModel productModel, CloudZoomModel cloudZoomModel)
at SevenSpikes.Nop.Plugins.CloudZoom.Components.CloudZoomComponent.InvokeAsync(String widgetZone, ProductDetailsModel additionalData)
at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)

5.I contacted with CloudZoom team with this problem and after they checked it and replied that's caused by Nop PictureService problem. Following is some of CloudZoom source for debugging.


private async Task<CloudZoomPictureModel> GetCloudZoomPictureModelForPictureAsync(
      ProductDetailsModel productModel,
      MediaSettings mediaSettings,
      Picture picture,
      MemoryStream stream)
    {
      string smallImageUrl1 = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, mediaSettings.ProductDetailsPictureSize, true, (string) null, (PictureType) 1);
      int pictureWidth = 0;
      int pictureHeight = 0;
      if (!string.IsNullOrEmpty(smallImageUrl1))
      {
        try
        {
          using (SKBitmap skBitmap = SKBitmap.Decode(await this._pictureService.LoadPictureBinaryAsync(picture)))
          {
            pictureWidth = skBitmap.Width;
            pictureHeight = skBitmap.Height;
          }
        }
        catch (ArgumentException ex)
        {
          await EngineContext.Current.Resolve<ILogger>((IServiceScope) null).ErrorAsync(string.Format("The picture file with id: {0}, URL: {1} appears to be corrupted or damaged.", (object) ((BaseEntity) picture).Id, (object) smallImageUrl1), (Exception) ex, (Customer) null);
        }
      }
      CloudZoomPictureModel zoomPictureModel1 = new CloudZoomPictureModel();
      CloudZoomPictureModel zoomPictureModel2 = zoomPictureModel1;
      string str1;
      if (!string.IsNullOrEmpty(picture.AltAttribute))
        str1 = picture.AltAttribute;
      else
        str1 = string.Format(await this._localizationService.GetResourceAsync("Media.Product.ImageAlternateTextFormat.Details"), (object) productModel.Name);
      zoomPictureModel2.AlternateText = str1;
      CloudZoomPictureModel zoomPictureModel3 = zoomPictureModel1;
      zoomPictureModel3.FullSizeImageUrl = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, 0, true, (string) null, (PictureType) 1);
      zoomPictureModel1.SmallImageUrl = smallImageUrl1;
      CloudZoomPictureModel zoomPictureModel4 = zoomPictureModel1;
      zoomPictureModel4.TinyImageUrl = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, mediaSettings.ProductThumbPictureSizeOnProductDetailsPage, true, (string) null, (PictureType) 1);
      CloudZoomPictureModel zoomPictureModel5 = zoomPictureModel1;
      string str2;
      if (!string.IsNullOrEmpty(picture.TitleAttribute))
        str2 = picture.TitleAttribute;
      else
        str2 = string.Format(await this._localizationService.GetResourceAsync("Media.Product.ImageLinkTitleFormat.Details"), (object) productModel.Name);
      zoomPictureModel5.Title = str2;
      zoomPictureModel1.PictureWidth = pictureWidth;
      zoomPictureModel1.PictureHeight = pictureHeight;
      zoomPictureModel1.DefaultRelation = this.GetRelation("default", smallImageUrl1);
      CloudZoomPictureModel zoomPictureModel6 = zoomPictureModel1;
      string smallImageUrl2 = smallImageUrl1;
      string pictureUrlAsync = await this._pictureService.GetPictureUrlAsync(((BaseEntity) picture).Id, 0, true, (string) null, (PictureType) 1);
      zoomPictureModel6.GalleryRelation = this.GetRelation("gallery", smallImageUrl2, pictureUrlAsync);
      CloudZoomPictureModel modelForPictureAsync = zoomPictureModel1;
      smallImageUrl1 = (string) null;
      return modelForPictureAsync;
    }


  1.  I attached here one picture file causing the problem. When I open the product url and check wwwroot/images/thumbs dir then generating thumbs of this picture are failed.
[1434730]<https://user-images.githubusercontent.com/681512/157871235-f97883b0-85c6-4a5b-8ce9-3ed26080550c.jpg>

**Comment by aquaristar** [comment]
Yes, I reported and got answer that they use PictureService to generate thumbs in Nopcommerce framework. In my think also it seems not cloud zoom error. The picture has strange problem. I made a function to generate thumb using the picture with python it was failed for the picture. But when you open the picture on image viewer it seems like no problem.

**Comment by AndreiMaz** [comment]
This error is related to SevenSpikes, please contact them to resolve it

**Comment by RomanovM** [comment]
@aquaristar I can confirm that using this image produces an exception. But this is not our `PictureService` problem, the `SkiaSharp` package we are using to transform pictures can't process this image. The file is definitely corrupted, it's not opened in Photoshop too.

**Comment by aquaristar** [comment]
@RomanovM Thanks for your confirm. Yes. I think so that the picture is corrupted. But we have already many images as binary data in PictureBinary table and because the corrupted image error occurs in cloudzoom slider our many product pages is not able to be rendered in the live site. So that I am now trying to find how to identify the corrupted jpeg file before inserted Picture db, but still not yet found good way. Since this situation I hope, if possible, Nopcommerce team add the corrupted exception pass logic in PictureService.

**Comment by aquaristar** [comment]
I guess that many other Nopcommerce users also could upload corrupted pictures to Nop site and also they could use thumbs generation feature like me. I think this exception patch for the PictureService could be required.
