### ISSUE TITLE
_AdminPopupLayout is missing viewport meta tag

### ISSUE THREAD

**Issue by mario-mantese** [nopSolutions/nopCommerce#6171]
On a mobile device, when a popup is shown in admin area, content is not scaled correctly.

Problem is solved by adding this line:
  `<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">`
to _AdminPopupLayout, like in regular _AdminLayout file

Tested on nopCommerce 4.40.3, but seems to be missing in 4.50 also

**Comment by exileDev** [comment]
Thanks! Closed #6171
