### ISSUE TITLE
On Linux: A warning on a file that doesn't exist -  dataSettings.json

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#6172]
nopCommerce version: 4.50

Steps to reproduce the problem: 
See this forum topic
https://www.nopcommerce.com/en/boards/topic/93439/is-it-a-bug-a-warning-on-a-file-that-doesnt-exist

I suspect it's just related to the code / bash command used for Linux (CheckPermissionsInUnix), because the code for Windows does properly handle it - i.e. no "warning on a file that doesn't exist."
        private static bool CheckPermissionsInWindows(...
                if (!(fileProvider.FileExists(path) || fileProvider.DirectoryExists(path)))
                {
                    return true;
                }

**Comment by skoshelev** [comment]
Closed #6172
