### ISSUE TITLE
Microdata. Invalid object type for field "author" in review block

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6179]
nopCommerce version: 4.40

It seems that now it's necessary to follow the author schema when you use the author attribute https://schema.org/author.
Also, there is no need to generate review microdata if reviews are disabled for the product.

Source: https://www.nopcommerce.com/boards/topic/93737/invalid-object-type-for-field-author
See also #6017

**Comment by DmitriyKulagin** [comment]
Closed #6179
