### ISSUE TITLE
Recaptcha on Checkout

### ISSUE THREAD

**Issue by 5teveO** [nopSolutions/nopCommerce#6181]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 
Site was recently used as a card testing platform. We use Eway as a payment gateway - It has cost us a alot of time and money. Eway are useless and didnt stop transactions.

It appears that recaptcha is used on the login page and registration page, however when allowing guest or anonymous checkout there are no safeguards in place. 

What are the options for enabling recaptcha on the one page checkout to prevent these card testing incidents.

Thanks for your work and attention

Steve Oliver

**Comment by AndreiMaz** [comment]
Thanks a lot. Duplicated - https://github.com/nopSolutions/nopCommerce/issues/6182

**Comment by 5teveO** [comment]
> Thanks a lot. Duplicated - #6182

Hi Andrei Thanks we must have posted pretty much at the same time. I appreciate you looking into this.
