### ISSUE TITLE
Add reCAPTCHA to guest checkout 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6182]
Let's add a setting indicating whether reCAPTCHA should be displayed during guest checkout (disabled by default). Let's display it on the last "Confirm order" step (if enabled).

Source:
1. https://www.nopcommerce.com/en/boards/topic/93742/recaptcha-one-page-checkout-how-do-i-do-it 
2. https://www.nopcommerce.com/en/boards/topic/46776/recaptcha
3. https://www.nopcommerce.com/en/boards/topic/35658/any-tips-for-implementing-no-captcha-recaptcha-in-nop#182428

**Comment by ChrisClaude** [comment]
Is anyone working on this? I would love to pick it up.

**Comment by AndreiMaz** [comment]
@ChrisClaude Thanks a lot for interest to contribute. But it's almost done - https://github.com/nopSolutions/nopCommerce/pull/6223
