### ISSUE TITLE
Search term not specified when calling SearchProducts via Web API

### ISSUE THREAD

**Issue by martingust** [nopSolutions/nopCommerce#6185]
nopCommerce version: 4.5

When calling [/api-frontend/Catalog/SearchProducts](https://app.swaggerhub.com/apis/nopCommerceAPI/nop-commerce_web_api_frontend/v1.06#/Catalog/post_api_frontend_Catalog_SearchProducts) no products are returned due to `isSearchTermSpecified` is always false [here](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs#L1722). 

What do you guys think is best way to fix this? Include `q` in the API call query or change the code in `CatalogModelFactory`?

**Comment by skoshelev** [comment]
Please ask your questions on our [forums](https://www.nopcommerce.com/boards), here we collect only issue reports and suggestions for improving nopCommerce.

Regarding your question, it's easier to just include the q parameter in the API request.

Closed #6185

**Comment by martingust** [comment]
@skoshelev thanks for your reply. This issue was opened as a report/suggestion. If the recommended approach is to include `q` in the request query I think that should updated in the Web API. As of right now you have to debug the code on order to figure out why you don't get any products in the response, and the auto generated clients from Swagger won't work.
