### ISSUE TITLE
Option for Conditional product attributes

### ISSUE THREAD

**Issue by abdu292** [nopSolutions/nopCommerce#6189]
Came across this thread today which I was exactly looking for a while. The linked workitem doesn't seem to be exist any more as it's pointing to the codeplex.

Can anyone help me understand if this is already being worked on, or if there is a work around? Not seeing this future in the latest version (4.50.1) as of today.

Source: https://www.nopcommerce.com/en/boards/topic/38699/conditional-product-attributes-
---- thread says ---- 
Hello,

I've just installed nop 3.7 for testing, and it looks great so far. One thing I want to know how to get Conditional Product attributes to allow select the appropriate attributes based on Attribute combinations.

e.g: I have 2 attributes: Color, Size

Color: red, blue
Size: S, M, L

the inventory only has  Red + (M,L), Blue + S

what can I do to make sure when user select red, it only shows Size: M, L, and S for Blue.

Thanks for reading
---------

nopCommerce version: 
4.50.1

Steps to reproduce the problem: 
See above.

**Comment by abdu292** [comment]
Thanks @RomanovM . I set the Inventory type to "Track inventory by product attributes". However, I'm unable to find an option "Display type for attribute value when out of stock". Could you please help me locate where this option is? Below are the only options I see on the page related to inventory. Thanks!

![image](https://user-images.githubusercontent.com/13116312/159285950-ef389735-289d-4179-aff7-cefc49855849.png)

**Comment by abdu292** [comment]
@RomanovM I know this is closed. However just was wondering why is this not the default. Is it because it is not the standard way to enter attributes combination? Are there any other way that we prefer over creating combinations in order to sell products that have different varying colors and sizes as in the question? Your response will be very much helpful & appreciated. Thanks!

**Comment by RomanovM** [comment]
@abdu292 This is not a default option, because we added it recently (in 4.40) and at this point existing store owners may already have their own methods to process such combinations. So, every merchant decides for himself whether he needs this feature.

Regarding the best sales option, you should ask it on [our forums](https://www.nopcommerce.com/boards), our community advises you on how best to proceed.

**Comment by abdu292** [comment]
Great. Thanks @RomanovM for the clarification!
