### ISSUE TITLE
XSS issue in the "Text" parameter (forums)

### ISSUE THREAD

**Issue by trungtin1998** [nopSolutions/nopCommerce#6194]
nopCommerce version: 4.50.1

Description:  A stored cross-site scripting (XSS) vulnerability exists when creating a new post of nopCommerce version 4.50.1 that allows a remote attacker to execute arbitrary JavaScript code at client browser
Steps to reproduce the problem:
- Step 1: Create new topic or reply topic with injecting `[url]javascript:alert(document.domain)[/url]`  to "Text" parameter
![storedxss-topic-Text(comment)-createpost](https://user-images.githubusercontent.com/48832546/159161904-060fbb54-a630-4f84-b8b4-4df2de209374.png)
- Step2: Click a text `javascript:alert(document.domain)` at topic that was created in step 1 to trigger XSS
![storedxss-topic-Text(comment)](https://user-images.githubusercontent.com/48832546/159161939-b3d7eb06-35cb-4bdc-a05b-f2677fc22aa4.png)
Let me know if you require additional information.

**Comment by skoshelev** [comment]
Hi @trungtin1998. Thank you for your help. We fixed this problem by [this commit](https://github.com/nopSolutions/nopCommerce/commit/26b0927a1f872e601e7d9b3be1e70b4fc740c23f)

**Comment by trungtin1998** [comment]
Hi guys, Can you help me request CVE for this issue?

**Comment by AndreiMaz** [comment]
@trungtin1998 Please feel free to report it at https://www.cve.org/

But our team will appreciate if you do after the next version release of nopCommerce (we plan to release a minor version in April)

**Comment by trungtin1998** [comment]
Hi @AndreiMaz, thank you for your information. I will do it after the next version release of nopCommerce.
