### ISSUE TITLE
 Lib: jquery-ui vulnerabilities

### ISSUE THREAD

**Issue by navongol** [nopSolutions/nopCommerce#6197]
nopCommerce version: 
4.501   
Steps to reproduce the problem: 

![image](https://user-images.githubusercontent.com/17260191/159285201-7153f557-a055-4fd9-8a10-e983f96f3f80.png)

https://snyk.io/test/npm/jquery-ui/1.12.1

**Comment by RomanovM** [comment]
Thanks, we'll update it shortly. See #196
