### ISSUE TITLE
nop-editor asp-postfix does't supports unicode characters

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6199]
nopCommerce version: 4.50.1

Steps to reproduce the problem: 
In page '/Admin/Setting/RewardPoints'
Change language to Chinese 
Or just modify setting filed 'Admin.Configuration.Settings.RewardPoints.RegistrationPointsValidity.Postfix' to  '天' (Days in Chinese)
It will display {Days}x5929

![image](https://user-images.githubusercontent.com/29729100/159738820-3b2bc923-d293-4e20-9795-de047ccc6a2e.png)

**Comment by exileDev** [comment]
Closed #6199 by [41ab1ec](https://github.com/nopSolutions/nopCommerce/commit/41ab1ecd0dc3e83e370f90e034f935c68fb5e529)
