### ISSUE TITLE
Incorrect escaping of ' character

### ISSUE THREAD

**Issue by roxxel** [nopSolutions/nopCommerce#6209]
nopCommerce version: 4.50

Steps to reproduce the problem: 
Set Ukrainian language as store language
Add something to cart
While checkout leave City field blank and press continue
U'll get error message in console
![image](https://user-images.githubusercontent.com/64275777/161738223-f6c3f216-ca93-4f56-92cc-7469eee5fb5d.png)

**Comment by RomanovM** [comment]
We could use `’` instead of `'` in localizations, but there can be many such cases in ready-made translations, so it's easier to add escaping.

**Comment by exileDev** [comment]
Closed #6209
