### ISSUE TITLE
Error when running inside docker

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce#6212]
nopCommerce version: 
4.50
Steps to reproduce the problem: 
Setup failed: An error occurred while creating the database: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding. CREATE DATABASE operation failed. Internal service error. Operation cancelled by user.

**Comment by RomanovM** [comment]
Seems the same as in #3143, see [comments](https://github.com/nopSolutions/nopCommerce/issues/3143#issuecomment-404433139) there, it's just a timeout, try one more time.
