### ISSUE TITLE
Bug: Site error Css bundling and minification for rtl lang

### ISSUE THREAD

**Issue by navongol** [nopSolutions/nopCommerce#6220]
Its a bug, why to close it?
https://github.com/nopSolutions/nopCommerce/issues/6219

* Its related To RTL Lang ...

nopCommerce version: 4.501

Steps to reproduce the problem: 

1. Install a clean nopcommerce
2. install Two lang first ltr second rtl
3. Uncheck setting in Bundling & minimization ->Css bundling and minification 
4 In front end change to the rtl lang

**Comment by exileDev** [comment]
Couldn't reproduce. Closed #6220

Perhaps this is due to non-Latin characters in the path to the app files. Try to change the Cache directory setting to `~/wwwroot/bundles` value. Lets me know if it helps you, please.

**Comment by navongol** [comment]
The problem is with nop-template.
I found that Nop-templates Venture Theme installed and enabled, i disable it and everything works fine for rtl.

https://www.nopcommerce.com/en/boards/topic/94076/a-bug-site-error-when-uncheck-css-bundling-and-minification-for-rtl-lang-6220#295169
