### ISSUE TITLE
AKS

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce#6230]
nopCommerce version: 
4.50

Steps to reproduce the problem: 
I want to store appsettings.json and plugin.json with sql server. Which services do I need to modify. I want to run NOP inside AKS and don't want to rely on file mounting...

**Comment by glhays** [comment]
Have you tried asking the forum communities this how to?


________________________________

**Comment by AndreiMaz** [comment]
Please post all questions on our forums
