### ISSUE TITLE
The cookie notification bar is too small

### ISSUE THREAD

**Issue by atomski-mrav** [nopSolutions/nopCommerce#6235]
nopCommerce version: 4.5.0.0

Steps to reproduce the problem:
Step 1: Start Nop.Web
Step 2: Wait for the cookie notification bar to pop up

Description:
The cookie notification bar is too small for German text.

Fix:
one possible fix would be to set the height of .eu-cookie-bar-notification to "auto" instead of "180px"

`.eu-cookie-bar-notification {
  position: fixed;
  top: 50%;
  left: 50%;
  z-index: 1050;
  width: 320px;
  height: 180px;
  margin: -90px 0 0 -160px;
  border: 1px solid #ccc;
  box-shadow: 0 0 2px rgba(0,0,0,0.15);
  background-color: #fff;
  padding: 20px;
  text-align: center;`

![cookie_bug](https://user-images.githubusercontent.com/29491358/163848610-9855b034-dfc0-4c38-8d4c-95cb18fad2f7.png)

**Comment by exileDev** [comment]
Thanks! Closed #6235
