### ISSUE TITLE
Some images trying to load using actual IP of server instead of domain

### ISSUE THREAD

**Issue by roxxel** [nopSolutions/nopCommerce#6237]
nopCommerce version: 4.50

Some of images loaded on server is trying to load using IP and not domain name
(Please do not offer kludge using nginx redirect)

**Comment by RomanovM** [comment]
@roxxel Try to change [UseAbsoluteImagePath](https://admin-demo.nopcommerce.com/Admin/Setting/AllSettings?settingName=UseAbsoluteImagePath) settings whether it helps.

**Comment by roxxel** [comment]
> @roxxel Try to change [UseAbsoluteImagePath](https://admin-demo.nopcommerce.com/Admin/Setting/AllSettings?settingName=UseAbsoluteImagePath) settings whether it helps.

Already done it, default_image_450 (iirc) still loads through servers ip

**Comment by skoshelev** [comment]
Hi @roxxel. Could you, please, specify which images ignore the UseAbsoluteImagePath setting, it would be great if along with screenshots from the debug console
