### ISSUE TITLE
Default value for appsettings.josn 'ForwardedProtoHeaderName'

### ISSUE THREAD

**Issue by jakubmaguza** [nopSolutions/nopCommerce#6238]
Hello,
I belive `ForwardedProtoHeaderName` should be set to null or `X-Forwarded-Proto`
Setting it to empty string is confusing and creating a problem from this topic:
https://www.nopcommerce.com/en/boards/topic/89707/problem-with-ssl

It was easier to set it up with previous `appsetting.json` version, because it was `true` or `false`. This is now string property and if we want to use default option we should set it to null.

**Comment by ekjuanrejon** [comment]
in my opinion all those infrastructure settings should be transparent to the application. The application should be able to handle it. whether it is behind a load balancer or not. should be agnostic whether it runs in docker, azure appservice, k8s, azure container apps

**Comment by exileDev** [comment]
This property will set the header used to retrieve the value for the originating scheme (HTTP/HTTPS) If a proxy uses a different one. And we check it with `string.IsNullOrEmpty` before use, so I don't think it matters. Now the UseProxy property has almost the same behaviour.

Closed #6238

**Comment by jakubmaguza** [comment]
Another thread with the same issue: 
https://www.nopcommerce.com/en/boards/topic/94036/ssl-enabled-causes-infinite-301/page/2

**Comment by chashik** [comment]
> Another thread with the same issue: https://www.nopcommerce.com/en/boards/topic/94036/ssl-enabled-causes-infinite-301/page/2

I believe that this thread emphasizes setting "UseProxy" to "true". That resolves the problem with reverse proxies for the most of cases even if the other Hosting Options remain default.

I still a bit confused why dotnet doesn't listen to 5001 for https. But it is not important.
