### ISSUE TITLE
Take advantage of performance improvement using .NET 7 regex source generator

### ISSUE THREAD

**Issue by acasorran** [nopSolutions/nopCommerce#6241]
nopCommerce version: develop

[System.Text.RegularExpressions work planned for .NET 7](https://github.com/dotnet/runtime/issues/62758)

Related work item - [#6225](https://github.com/nopSolutions/nopCommerce/issues/6225)

**Comment by RomanovM** [comment]
Thanks. We'll consider all related features in the mentioned issue.
