### ISSUE TITLE
can release release-4.50.2 be merged to master

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce#6242]

**Comment by AndreiMaz** [comment]
It's already merged

**Comment by ekjuanrejon** [comment]
hmmm don't think it is

**Comment by AndreiMaz** [comment]
This is a "master" branch - https://github.com/nopSolutions/nopCommerce/commits/master. And it contains the latest version 4.50.2

You can also check the file with version - https://github.com/nopSolutions/nopCommerce/blob/master/src/Libraries/Nop.Core/NopVersion.cs
