### ISSUE TITLE
Change password with customer usernames enabled

### ISSUE THREAD

**Issue by LucaJacopini** [nopSolutions/nopCommerce#6246]
nopCommerce version: 4.50.

Hi

Our site has usernames login enabled and users cannot register but are created by automated jobs.

We have multiple customer with the same email. When one of this customer try to change the password using forgot password/password recovery function only the first one has password changed. The same happens if an admin try to change the password using the specific function in admin area.

This happens because the ChangePasswordRequest is created with customer email and customer are retrieved always by email.
I think customer should be retrieved by email only if usernames option is disabled.
Moreover in password recovery page username should be asked instead of email if usernames option is enabled.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But considering that we do not plan to support https://github.com/nopSolutions/nopCommerce/issues/953#issuecomment-1109774778, we also do not plan to implement this change
