### ISSUE TITLE
nopCommerce first run error

### ISSUE THREAD

**Issue by ChrisClaude** [nopSolutions/nopCommerce#6247]
nopCommerce version: 4.5.0.0

I've got an issue when running the project for the first time in visual studio 2022. I'm getting the following error message

```
An error occurred while starting the application.
Win32Exception: The certificate chain was issued by an authority that is not trusted.
Unknown location

SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action wrapCloseInAction)

DependencyResolutionException: An exception was thrown while activating λ:Nop.Core.Domain.Common.CommonSettings.
Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action next)

Win32Exception: The certificate chain was issued by an authority that is not trusted.
```
Steps to reproduce the problem: 

1. Clone project
2. Open it in visual studio 2022
3. Build and run the project 

I've got SQL installed on my machine. This is the version of SQL Server that I'm running Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19044: ) (Hypervisor)

**Comment by ekjuanrejon** [comment]
@ChrisClaude this more sounds like a issue on your development machine. I clone the repo and everything worked fine. Please check your setting again. If I remember correctly you have to accept the local certificate from kestrel or iis... also run with kestrel instead of local iis

for the sql issue please ensure you have the following in the connection string:
;Trust Server Certificate=True

**Comment by RomanovM** [comment]
Yes, it works.
Please post your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker only.
