### ISSUE TITLE
EditorTemplates Picture is not loading in multi language

### ISSUE THREAD

**Issue by pddobariya** [nopSolutions/nopCommerce#6252]
nopCommerce Version: 4.50

The issue is if I want to add a Picture in multiple languages the EditorTemplates of the picture are not working.

Steps to reproduce the problem: in the plugin, I have added one picture that wants to use in multiple languages
but the EditorTemplates of the picture is not working

**Comment by RomanovM** [comment]
This has already been discussed (see #398 #3081). We don't plan to support it out of the box, so you'll have to customize the solution.
