### ISSUE TITLE
Character set 'utf8mb3' is not supported by .Net Framework.

### ISSUE THREAD

**Issue by oeloe100** [nopSolutions/nopCommerce#6253]
nopCommerce version: 4.4.0

Steps to reproduce the problem: So a couple of days ago I got the following Exception: Character set 'utf8mb3' is not supported by .Net Framework. Then I went to MySQL Release notes and I found the following: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html

MySQL. 8.0.29 Release note: Important Note: The server now uses utf8mb3 rather than utf8 in the following cases....

 Since I'm working from Ubuntu Linux I went to APT and searched for 'MySQL-server'. What I found was 2 versions. 
1. MySQL-server = version: 8.0.29
2. mysql-server-8.0 was version 8.0.28

After downgrading to mysql-server-8.0 after a while (not easy to do, because MySQL does not support downgrading) I got NopCommerce once again up and running. 

Last night MySQL-server once again upgraded to 8.0.29. wich is now the default version for mysql-server-8.0.
![Screenshot from 2022-05-05 11-29-25](https://user-images.githubusercontent.com/16669852/166896752-d2c86584-edf6-4420-899a-e558804f8d65.png)

and once again I got the same exception:
![Screenshot from 2022-05-05 11-30-51](https://user-images.githubusercontent.com/16669852/166896923-70f8d1fd-1c7f-4429-ae4b-d549a391aa59.png)

Please provide a fix. Thank you!

**Comment by oeloe100** [comment]
https://bugs.mysql.com/bug.php?id=105516

**Comment by oeloe100** [comment]
This is the full character set of de databases in mysql 8.0.29
![Screenshot from 2022-05-05 14-09-51](https://user-images.githubusercontent.com/16669852/166920261-4b4f2ef0-c560-46b0-813d-72bb4d4d8c83.png)

Even though nopcommerce does not use this character set or collation
![Screenshot from 2022-05-05 14-11-37](https://user-images.githubusercontent.com/16669852/166920409-606bf9d1-f7ae-41e3-a3d0-e4277b04c8cc.png)

**Comment by oeloe100** [comment]
You guys are pretty quick with closing unfixed issues. Please explain? because I'm still dealing with this what is the fix?

**Comment by exileDev** [comment]
@oeloe100 This issue is caused by the bug in Connector/NET as you pointed out. We've updated the package version recently for the develop branch. In 4.40 you can make these changes yourself in Nop.Data.csproj file.

**Comment by micheleinhorn** [comment]
hi I have the same problem using linux and version 4.4 can you please let me know what i need to change in Nop.Data.csproj file

**Comment by glhays** [comment]
> hi I have the same problem using linux and version 4.4 can you please let me know what i need to change in Nop.Data.csproj file

Open your solution, right-click the Nop.Data project, select manage nuget-packages. You will see there is an update for the MySql.Data package, update it, rebuild the solution and publish, update to your site.

**Comment by micheleinhorn** [comment]
thank you for your help
