### ISSUE TITLE
No promotion discount applied for quantity (tier) pricing on product detail page

### ISSUE THREAD

**Issue by sumnone** [nopSolutions/nopCommerce#6254]
nopCommerce version: 4.40.4

Steps to reproduce the problem: 

1. Create a product, simple or grouped.
2. Create Tier pricing for that product (e.g. 40+ quantity lowers the price to $4).
3. Create a promotional discount (e.g. 10% discount applied to product skus), and apply the discount to the product you created.
4. (Optional, to see it's not a greater issue) Add the product to your cart with the tiered discount quantity.

The Perfect:
The tiered price and discounted price is calculated correctly in the cart section of nopCommerce. For example, if a product has a price of  $5 and has a 40+ quantity tiered price that lowers the price one dollar (i.e. $4), with a 10% discount applied, the product shows a unit cost of $3.60 in the cart (mini flyaway and /cart) when the quantity is 40 or more.

The Issue:
On the product detail page, the discount is applied to the main unit (i.e. $4.50), but the table showing tiered pricing, has the tiered price only (i.e. $4). No percentage discount is applied.

The desired result:
The tier pricing table on the product detail page should reflect the percentage discount price as well (i.e. $3.60).

If anyone knows a quick fix in the meantime, I'd appreciate it. I imagine it can be done in Views\Product\_ProductTierPrices.cshtml? We haven't made any modifications to that file, and looks to be exactly the same in 4.50. Otherwise, I'll try and figure it out and post back here. Thanks!

**Comment by RomanovM** [comment]
@sumnone We already have a setting for this (`DisplayTierPricesWithDiscounts`), but it seems that there is a bug in the previous refactoring of price calculation (#5323), we'll fix it shortly. Thanks for the info.

**Comment by sumnone** [comment]
@RomanovM Excellent, we have `catalogsettings.displaytierpriceswithdiscounts` set to True, but not sure what that applies to. I also looked into some quick cshtml mods and as you mentioned, appears a little more involved than that. Many thanks for addressing it.
