### ISSUE TITLE
Gift cards. Better support for multi currency.

### ISSUE THREAD

**Issue by DB-TORGA** [nopSolutions/nopCommerce#6258]
nopCommerce version: 4.4

Steps to reproduce the problem: 

Gift card notification email is always generated and send to customer using nopcommerce store base currency and base currency amount. 

This can confuse webshop customers, for example customer buys a EUR 100 gift card, but customer recieves an email showing amount USD 110 .

Idea to fix the problem: in GiftCard table , add new columns for GiftCard.OriginalPurchaseCurrency and GiftCard.OriginalPurchaseExchangeRate.

Then the Gift card notification email  can be generated using GiftCard.OriginalPurchaseCurrency  and value as GiftCard.OriginalPurchaseExchangeRate x GiftCard.Amount

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
