### ISSUE TITLE
issue - Map LocalizedProperty with foreign Id

### ISSUE THREAD

**Issue by SpeakOutLoud** [nopSolutions/nopCommerce#6266]
nopCommerce version: 4.60

Hi, this is my first issue ticket :).

What do you think about the `LocalizedProperty` table to create foreign id from 2 columns:
LocalKey and LocalKeyGroup.

Why I am mention this, if a client wants to host many products (tens of thousand) and would like to add multiple languages for those products, than the LocalKey and LocalKeyGroup as string would repeatedly be stored on the table and would indicate a performance issue for reading the data.

As a solution, if approved of course. I would suggest creating 2 other tables, that would host the LocalKeyGroup and LocalKey with a parented to LocalKeyGroup. Then from LocalizedProperty table we would just map the foriegn id from those 2 created tables, in this case we would reduce the size of the table in terms of space, and would improve the performance, instead of reading the same string multiple times, now it would read the foreign Id as int.

Thank You!

**Comment by AndreiMaz** [comment]
Thanks a lot for your contribution. But we think that the current implementation works absolutely fine in 99.99% cases.

If someone experience any performance issues, we would recommend to check your pull request. Perhaps, he/she will manually use or merge it
