### ISSUE TITLE
Slovak translation/localization typo

### ISSUE THREAD

**Issue by killerwife** [nopSolutions/nopCommerce#6275]
nopCommerce version: 4.50

Steps to reproduce the problem:  
1. Add any product  
2. Switch to slovak page  
3. Go to product page  

Result: Crash on FormatException: Input string was not in a correct format.

Fix:  
Change "Products.ProductAttributes.PriceAdjustment" resource  
in SK localisation from  
{0} {{1} {2}}
to  
{0} [{1}{2}]  

Gladly will open up a PR if there was a tutorial how to open a fix for this (I fixed it for myself locally)

**Comment by RomanovM** [comment]
Thanks. We don't store localizations on the solution files, you could fix them on our [Crowdin project](https://crowdin.com/project/nopcommerce/sk) after that the corrected language package will be available for download [here](https://www.nopcommerce.com/translations).

**Comment by AndreiMaz** [comment]
@killerwife we've just fixed it. please re-download the language pack
