### ISSUE TITLE
Overriding SlugRouteTransformer  TransformAsync in my plugin doesn't work in 4.5

### ISSUE THREAD

**Issue by AdiIndoSwiss** [nopSolutions/nopCommerce#6276]
nopCommerce Version:  4.5

Steps to reproduce the problem:  
Why I am doing so: I want to override this method in the catalog controller 
 public override async Task<IActionResult> Category(int categoryId, CatalogProductsCommand command) 

For this matter, I have to override the slugrouteTransformer but it is not hitting, it's always going to the  Nop.Web.Framework.Mvc.Routing.SlugRouteTransformer

Code snippets:

 public class MyCustomRouteTransformer : DynamicRouteValueTransformer
    {
        public override async ValueTask<RouteValueDictionary> TransformAsync(HttpContext httpContext, RouteValueDictionary values)
        {
                 .......
  switch (urlRecord.EntityName.ToLowerInvariant())
            {
                case "category":
                    values[NopPathRouteDefaults.ControllerFieldKey] = "MyCustomCatalog";
                    values[NopPathRouteDefaults.ActionFieldKey] = "Category";
                    values[NopPathRouteDefaults.CategoryIdFieldKey] = urlRecord.EntityId;
                    values[NopPathRouteDefaults.SeNameFieldKey] = urlRecord.Slug;
                    break;

                default:

         }
}

Nopstartup.cs: 
 services.AddScoped<MyCustomRouteTransformer>();

RouteProvider.cs:
public void RegisterRoutes(IEndpointRouteBuilder endpointRouteBuilder)
        {

            var genericPattern = $"/{{SeName}}";
            endpointRouteBuilder.MapDynamicControllerRoute<CustomSideRouteTransformer>(genericPattern);
}

public partial class MyCustomCatalogController : CatalogController
    {
 public override async Task<IActionResult> Category(int categoryId, CatalogProductsCommand command)
        {
              my code

}
}

THanks
Aditya

**Comment by RomanovM** [comment]
Look at commits for [this issue](https://github.com/nopSolutions/nopCommerce/issues/385), they might give you an idea, although they are for 4.60, you can adapt them for your current version.
Anyway, this is related to plugin development and not to the core. So it's unlikely that we can do something unless you have specific ideas of what to change in the core.
