### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID error

### ISSUE THREAD

**Issue by michalwitek1232** [nopSolutions/nopCommerce#6282]
I'm getting this error in browser while being on home page:
Where `999.999.999.999` is IP address of my VPS.

`GET https://999.999.999.999/images/thumbs/0000001_banner_1.jpg net::ERR_CERT_COMMON_NAME_INVALID`

This issue cause problems with loading image on website wchich is presented below:
![image](https://user-images.githubusercontent.com/42500203/173680224-03c9551a-0a69-4b89-bfef-de32d9d12b32.png)

My machine:
Linux vps-0af3bae2 5.10.0-11-cloud-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
with newest .net right from [Linux installation guide](https://docs.nopcommerce.com/en/installation-and-upgrading/installing-nopcommerce/installing-on-linux.html#ssl)

So there is 2 questions:
1. How to map it to my domain name connected to website (To get to my page I'm using my domain name (nginx reverse proxy) with SSL by Certbot ).
2. How to fix this `ERR_CERT_COMMON_NAME_INVALID` error.

nopCommerce version: 4.5

**Comment by AndreiMaz** [comment]
This question is not related to nopCommerce directly. Please check https://kinsta.com/knowledgebase/net-err_cert_common_name_invalid/
