### ISSUE TITLE
products Category

### ISSUE THREAD

**Issue by hossein2408** [nopSolutions/nopCommerce#6283]
nopCommerce version: 4.4

Steps to reproduce the problem: 
each product can have some Category. but when user open product page in frontend its not clear which Category displayed in product page.
plz make this configurable or  all time display first item in product page in frontend  and admin can change First category change.
![image](https://user-images.githubusercontent.com/9799567/174044589-8ad2fb71-78b2-4e5c-952a-c4db422c0c01.png)

**Comment by AndreiMaz** [comment]
@hossein2408 It's already implemented this way. We display the same category in breadcrumb on the product page
