### ISSUE TITLE
Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.

### ISSUE THREAD

**Issue by digitalray** [nopSolutions/nopCommerce#6284]
nopCommerce version: 4.50.3

Steps to reproduce the problem: 

1. Install Mysql 8.0.29 or any 8.x version on Ubuntu 22.04
2. Configure nginx
3. Install dotnet 6
3. Configure systemd service for nopcommerce
4. Open browser with the website configured and you are redirected to /install
5. fill out the mysql information and user admin info
6. Click on Install
You will get 
`Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.`

**Comment by AndreiMaz** [comment]
duplicated - https://github.com/nopSolutions/nopCommerce/issues?q=is%3Aissue+IVersionLoader+is%3Aclosed

**Comment by digitalray** [comment]
I have checked the duplicate issues and found that they were closed without resolution. Please let's continue troubleshooting it or point me to a duplicate issue that has been resolved. It's not right to close these out without further looking at the causes and errors IMO. I am actually looking into partnering with you guys on a bigger scale to develop plugins for our platform and this sort of treatment is uncalled for.

**Comment by exileDev** [comment]
@digitalray Hi. It may be related to the MySql driver. Please update package of the Connector/NET in Nop.Data.csproj file:

`<PackageReference Include="MySql.Data" Version="8.0.28" />`

to

`<PackageReference Include="MySql.Data" Version="8.0.29" />`

**Comment by digitalray** [comment]
@exileDev Thanks for pointing that out. I was using the non-source package downloaded from GitHub releases. This means I will have to compile it from source. I have no issues with that. I will compile it with the suggestion and get back to you with results.

**Comment by digitalray** [comment]
@exileDev Thanks for your help. Bumping the mysql package reference to 8.0.29 did help get rid of that problem.

**Comment by ryanlee714** [comment]
> @digitalray Hi. It may be related to the MySql driver. Please update package of the Connector/NET in Nop.Data.csproj file:
> 
> `<PackageReference Include="MySql.Data" Version="8.0.28" />`
> 
> to
> 
> `<PackageReference Include="MySql.Data" Version="8.0.29" />`

@exileDev If you know how to fix this problem, why don't you recompile it and publish to https://github.com/nopSolutions/nopCommerce, then it will help all of us.

**Comment by digitalray** [comment]
@ryanlee714 I don't have access to do that. You would have to ask nopcommerce team for publishing anything on their GitHub.

There is a [Dockerfile](https://github.com/nopSolutions/nopCommerce/blob/develop/Dockerfile) in their source repo. It is very easy to run that docker file. Once you make the change in [Now.Data.csproj](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/Nop.Data.csproj#L21) run it, it will build it for you. Then you can just copy the build from the container to a desired location and deploy it.

**Comment by BATHIVINOD24** [comment]
> @digitalray Hi. It may be related to the MySql driver. Please update package of the Connector/NET in Nop.Data.csproj file:
> 
> `<PackageReference Include="MySql.Data" Version="8.0.28" />`
> 
> to
> 
> `<PackageReference Include="MySql.Data" Version="8.0.29" />`

is there an option to update mysql version as I have directly downloaded from github, don't wants to work on source files

**Comment by AndreiMaz** [comment]
Fixed in 4.50.4 - https://github.com/nopSolutions/nopCommerce/commit/a873efec8f6f57b6511ef01da30045974eaecb9d
