### ISSUE TITLE
multistore robots.txt

### ISSUE THREAD

**Issue by ABurduli** [nopSolutions/nopCommerce#6285]
nopCommerce version: All

Steps to reproduce the problem: 
there is no option to add robots.custom.txt by store.
it would be nice if a file named something like Eur_Store_Name.robots.custom.txt was supported to.

**Comment by AndreiMaz** [comment]
Thanks for suggestion. But we'll leave it for customization

**Comment by RomanovM** [comment]
Solved in #5261
