### ISSUE TITLE
Possible missing file reference from default template

### ISSUE THREAD

**Issue by michalwitek1232** [nopSolutions/nopCommerce#6286]
nopCommerce version: 
4.5

Hi, I'm missing this file from my store.
[Missing file link](https://m.meendoru.net/images/thumbs/0000001_banner_1.jpg)

This is from clean nopCommerce instance deployed on Debian 11 with .NET 6 and Let's Encrypt SSL assigned.

Steps to reproduce:
After going to my web store website for example: `https://dev.somedomain.com` secured by SSL I'm getting many console logs with error status.

nopCommerce will try to load image under [this address](https://m.meendoru.net/images/thumbs/0000001_banner_1.jpg), and then it will leave me with this view:
![view](https://user-images.githubusercontent.com/42500203/174376373-d157e7f6-2b9b-4e29-9697-bec338a8c298.png)

Web browser output:
```
Request:
GET	https://m.meendoru.net/images/thumbs/0000001_banner_1.jpg

Status:
404
Not Found
```

Also, here is (what I guess) a missing image:
![image](https://user-images.githubusercontent.com/42500203/174384437-ced96eaf-e64b-4b58-8880-e63b078f2ab8.png)

Please be so kind and check it in your spare time. I already tried to localize this reference in source code, but I couldn't find it.

**Comment by AndreiMaz** [comment]
It works fine out of the box. Please post all such questions  on our forums
