### ISSUE TITLE
Add Hidden value to AttributeControlType enum

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#6287]
Sometimes it is necessary to have hidden input fields on the form for automatic filling (without user intervention).

Example. The form has an additional _Address finder_ field, which automatically fills in the standard address fields (state/province, city, adddress, postal code). In addition, for a more accurate calculation of delivery, you need to fill in additional fields, for example, _cityFiasId_, which should not be filled in manually by the user.

Attributes with the value AttributeControlType.Hidden should display as follows
```html
<input asp-for="cityFiasId" type="hidden"/>
```

![1](https://user-images.githubusercontent.com/37818094/174448347-8528bedc-4b03-4419-937c-ba703151f6e2.png)
_cityFiasId_ should be hidden here

![2](https://user-images.githubusercontent.com/37818094/174448349-97b1f7bb-9758-48d0-aecd-6719b9efdea3.png)

**Comment by AndreiMaz** [comment]
Thsi rewuest is quite specific. And we'll leave it for customization
