### ISSUE TITLE
not showing any price in frontend category page when i use Product attributes

### ISSUE THREAD

**Issue by hossein2408** [nopSolutions/nopCommerce#6288]
nopCommerce version: 4.43

Steps to reproduce the problem: 
When we create a product that includes a number of other products ("Product attributes" not simple, Attribute value type: Associated to product) and we select a "Is pre-selected" config for sub-product or products. nopcommerce not showing any price in frontend category page !. Why the system does not calculate price, based on the pre-selected products.

**Comment by AndreiMaz** [comment]
It's by design. Full price is displayed on the product details  page only
