### ISSUE TITLE
Colorado retail delivery fee

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6291]
It looks like Colorado has a new fee / tax that goes into effect July 1st 2022. This will have to be filed with the state separately from standard tax filing. Retailers must also separately state the retail delivery fee on all customer invoices and receipts. It would also need to be displayed at the time of checkout.

Detail: https://tax.colorado.gov/retail-delivery-fee

Unfortunately anyone selling products from NopCommerce that ship to Colorado will have to collect this fee at the time of purchase. They will also need to be a report get the fee total with in a time period to remit to the state.

Of Course this is most likely just the beginning of other states, regions or provinces following this pattern.

Source: https://www.nopcommerce.com/en/boards/topic/94497/colorado-retail-delivery-fee

Currently we recommend using our Avalara plugin that supports it - https://www.nopcommerce.com/en/avalara-tax-provider

**Comment by AndreiMaz** [comment]
One of the solutions will be using our Avalara tax plugin

**Comment by brandon71** [comment]
One concern would be the requirement to show the fee on the checkout and invoice.

from link:
Retailers that make retail deliveries must show the total of the fees on the receipt or invoice as one item called “retail delivery fees”

I'm not sure how the Avalara integration works. Would it have the ability to display this data on checkout page and invoice.

**Comment by glhays** [comment]
👍


________________________________

**Comment by brandon71** [comment]
It looks like on May 9th SB23-143 allowed for changes in Colorado delivery fee that made this simpler for now. I'm sure they were getting a lot of push back. Not only do you have to have 500,000 in the previous year but you can opt to pay this yourself in Colorado. 

The bigger issue isn't just Colorado its that other states are now implementing this requirement. I see Alabama and Minnesota have jumped on the bus. It will be in more states very quickly. Saying this isn't important because Colorado made a change is not addressing a real problem coming down the road. As more states implement this they are not all going to give us the 500,000 get out of jail free card.

**Comment by AndreiMaz** [comment]
**Got the following email from Avalara:**

Last June and September, we communicated information about Colorado’s New Retail Delivery Fee.

We are reaching out again to share that the Colorado Department of Revenue has recently updated components of the Colorado Retail Delivery Fee.

Effective July 1, 2023, the Colorado Retail Delivery Fee (Colorado RDF) will increase from $0.27 to $0.28. Partners and customers should be able to begin testing on June 27, 2023. Avalara has you covered regarding this fee increase, here is how:
•	Avalara product teams continue to work to assess the current solution to meet the Colorado Retail Delivery Fee requirements.
•	Avalara continues to partner with the ERP vendors, eCommerce platforms and underlying connectors leveraged, to collectively explore available and reasonable alternative solutions that provide an improved experience.
•	We will keep you updated through [this article](https://knowledge.avalara.com/bundle/hvp1668662778044_hvp1668662778044/page/ACTION_NEEDED_Colorado_Retail_Delivery_Fee_begins_July_1_2022.html).

Customers will need to make their own determinations regarding the following:
•	Retroactive to July 1, 2022, Colorado waived the retail delivery fee for qualifying new businesses and businesses with less than $500,000 in sales during the previous year. However, the state won’t refund any fees paid between July 1, 2022, and April 1, 2023.
•	Effective May 4, 2023, the new law also permits retailers to elect to pay the fee on behalf of their customers without separately stating the fee amount on a receipt, invoice, or collecting it directly from the customer. If partners/customers pursue this option, they still have an obligation to remit and will need to [add this as an adjustment](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=21186&elqTrackId=fa6db18699564a57bc6ee883ba9b2eb3&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1) as noted in the [FAQs of this article](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=21183&elqTrackId=fecaa4125a6c46a19d97f5f04f00a4ff&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1).

Recommended Actions:
1.)	Review the [pending customer communication](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=21185&elqTrackId=bb82f060305f40f99a57954d2dddcd8d&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1) and [updated Avalara Knowledge Center](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=21183&elqTrackId=38ffbfc39c88433f8cb5dba824667c4e&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1). Article to ensure you are informed, have an opportunity to assess impacts, and are prepared to respond to any customer inquiries.
◦	For detailed implementation and support questions on how to setup the Colorado Retail Delivery Fee (Colorado RDF) as a new SKU and Tax Code, and to ensure your customers can post the fee to their financials with their existing integrations, we recommend you refer your customers to our [knowledge center documentation specific to their accounting systems](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=21184&elqTrackId=bcf8c186723f4b27a9a9e92324065c02&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1).
◦	For more custom integrations, your customers may need to engage with their preferred system integration partner to set up a new inventory item and new Tax Code.
2.)	Review the [Colorado Department of Revenue’s webpage](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=18432&elqTrackId=d9e4b68a3e964252a2bf2cdd666ac7ce&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1) for more information about this fee and its display requirements, if you have not already. Partners can also contact the [CO Taxpayer Helpline for additional clarification](https://app.news.avalara.com/e/er?utm_campaign=AMER_PART_Email_Service-Notif_06_2023_CO%20Retail%20Delivery%20Fee%20Change&utm_medium=email&utm_source=Eloqua&s=706&lid=18435&elqTrackId=6c17194f0ec242e3973ba91a30fed6b4&elq=6ef97e2c367c4c8fa7b197eeb3aa5040&elqaid=35326&elqat=1).

**Comment by brandon71** [comment]
One of the issues with the Retail delivery fee will be that the fee must be stated on the bill of sale, invoice, receipt, etc. Not all companies will be able to absorb this fee and will need to pass it on to customers. If company has to pass the fee on to customers it must be displayed in multiple places. 

As more states see the income potential, this fee will exist on almost all sales in the US. Not all business will want to increase their price to cover these fees. Businesses may also choose to pay the fee for some states but collect the fee from customers for other states.

Should a tax plugin like Avalara have the job of displaying this fee in multiple places in NopCommerce? ie checkout, cart, invoice ect. Should all tax plugins in the future have the job to support retail delivery fees?

Minnesota is adding the retail delivery fee next July.
https://www.avalara.com/blog/en/north-america/2023/06/minnesota-retail-delivery-fee-starts-july-2024.html

The retail delivery fee is ridiculous and making life difficult for all online businesses. A solution to this problem can be pushed off for now with two states allowing companies to pay the fee which removes the requirement to display the fee to users. At some point this will need to be addressed.

**Comment by AndreiMaz** [comment]
Currently we recommend using our Avalara plugin that supports it - https://www.nopcommerce.com/en/avalara-tax-provider

**Comment by dwightbcoder** [comment]
What is the implementation required for this? Everything I see suggests we need to add a non-inventory product and assign it the tax code of `OF400000` but then this item still must be added to the cart.

With the suggestion of using the Avalara plugin how is this configured? Does this really require a plugin to add this item or is there something I'm missing? If there is existing documentation on how to configure this in nopCommerce please provided a link. Thank you!
