### ISSUE TITLE
Roxy fileman errors when listing files when certain images are in the upload folder

### ISSUE THREAD

**Issue by Jitty-n** [nopSolutions/nopCommerce#6297]
nopCommerce version: 4.5

Steps to reproduce the problem: 

1. Edit Topic or Message Template
2. Click Insert/Edit Image from body wysisyg
3. Click Source Button
4. Happens when certain images are in this folder (example attached)
5. Test with attached image in \wwwroot\images\uploaded folder
![UberEats](https://user-images.githubusercontent.com/64054461/177492007-a58a9ebe-9cc6-421e-af70-d3127ae74698.jpg)

This relates to this commit i believe where support was added for WebP format https://github.com/nopSolutions/nopCommerce/commit/c973d847af9180397179d3ce13bb19ce2e885bd9#diff-35122033bc9cebb4b81ab443af98ba63da80678997040edd44c3164a4c1539c8

Exception occurs on line 546 of FileRoxyFilemanService.cs 
`var image = SKBitmap.DecodeBounds(stream);
`
Previously code was 
`
  using (var image = Image.FromStream(stream))
  {
      width = image.Width;
      height = image.Height;
  }
`
which works on these images

**Comment by RomanovM** [comment]
@Jitty-n This file works fine for me. Could you please provide the full exception log?

**Comment by Jitty-n** [comment]
> 

@RomanovM looks like it was fixed with this commit https://github.com/nopSolutions/nopCommerce/commit/3d4fcdafb8c3d5baf36182bfe8ab8f827514db17 with version 4.50.3. Will pull that in. Thanks
