### ISSUE TITLE
Save DataTable state

### ISSUE THREAD

**Issue by gkennedy1** [nopSolutions/nopCommerce#6298]
nopCommerce version: 4.5

Steps to reproduce the problem: 
1) Browse to any area in admin that utilises data tables. Eg: catalog
2) Change data table page size and/or go to another page
3) Edit an item from the table. Eg: product
4) Click the 'back to product list' link or use the browser back button
5) The product list is reset to the first page and the default page size

We have tested using the DataTable setting called [saveState](https://datatables.net/examples/basic_init/state_save.html) on the following partial view:
Nop.Web\Areas\Admin\Views\Shared\_Table.Definition.cshtml

![image](https://user-images.githubusercontent.com/1694515/177897037-207fce8f-0117-47bd-9a59-2a35d886e605.png)

It seems to work well. Can this be added?

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we think that it's better to have the default behavior. So we leave it for customization
