### ISSUE TITLE
Integration with Umbraco

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#63]
As announced on nopdevdays'2015. We can significantly help these CMS and us.

also see #1308

**Comment by dchmir** [comment]
Примерный текст топика:

Интеграция с **Umbraco** и **Orchard**
Коллеги, начинаем сбор требований и пожеланий для интеграции с CMS **Umbraco** и **Orchard**.
Хотелось бы получить feedback с пожеланиями о необходимом уровне интеграции:
1.	Интеграция в качестве плагина для CMS **Umbraco** и **Orchard**;
2.	Интеграция на уровне общих учетных записей.
Каждый из двух вариантов повлечет за собой необходимость вносить изменения в существующий код, и степень этих изменений зависит только от фантазии разработчиков.
Например, если мы решаем интегрироваться в качестве плагина, то необходимо будет поменять такие важные с точки зрения узлы  кода как работа с базой данных, контекст приложения и еще много чего. Фактически, сервисы будут работать по прежнему, но вот код который они будут использовать будет другой. То-есть плагин перерастает в отдельную ветку проекта и будет иметь свой Core.
Второй вариант менее затратный в реализации, но менее удобный в инсталляции.

Возможно есть еще и другие степени интеграции и вы могли бы их предложить исходя из своего опыта. Для этого мы хотели бы предложить вам высказаться на эту тему.
Так же мы просим поделится опытом тех, кто уже имеет успешный опыт по реализации интеграции любой сложности.

**Comment by praveenksharma** [comment]
Hi @AndreiMaz. So this is not coming in 3.80?

**Comment by AndreiMaz** [comment]
It will be release for 3.80

**Comment by converxu** [comment]
Hi @AndreiMaz , just double check. will this included 3.80 the coming release?

**Comment by AndreiMaz** [comment]
We were not going to include it into nopCommerce (out of the box). It'll be released as a separate integration (for nopCommerce 3.80). But there's no certain date for the release (of the integration) yet

**Comment by lsx84** [comment]
Hi @AndreiMaz, will this be Umbraco integration in NopCommerce or NopCommerce integration in Umbraco (like uCommerce)?

**Comment by AndreiMaz** [comment]
please see http://www.nopcommerce.com/boards/t/41254/lets-discuss-the-upcoming-integration-of-nopcommerce-and-umbraco.aspx for more info

**Comment by AndreiMaz** [comment]
P.S. we put all third-party integrations as "on hold /maybe". it'll be done soon =))

**Comment by AndreiMaz** [comment]
should be done as plugin
