### ISSUE TITLE
Use name for specification attribute option as CustomValue when exporting products

### ISSUE THREAD

**Issue by dbgjonah** [nopSolutions/nopCommerce#6301]
nopCommerce version: 4.5

Steps to reproduce the problem: 

1. Go to Admin - Catalog - Products
2. Select some products with specification attribute and export to excel
3. Open up the excel spreadsheeet and expand specification attribute rows.
4. CustomValue column has no value

I had to update/change the code in \Libraries\Nop.Services\ExportImport\ExportManager.cs to bring up the CustomValue.

_private async Task<int> ExportSpecificationAttributesAsync(Product item, PropertyManager<ExportSpecificationAttribute> attributeManager, ExcelWorksheet worksheet, int row, ExcelWorksheet faWorksheet)
{
  ...
  //CustomValue = **psa.CustomValue,**    // original code
  _CustomValue = **(await _specificationAttributeService.GetSpecificationAttributeOptionByIdAsync(psa.SpecificationAttributeOptionId)).Name,**    // new code_
  ...
}_

**Comment by RomanovM** [comment]
@dbgjonah  Well, this works as expected. `CustomValue` is a value for an attribute of the `CustomText` or `Hyperlink` type, and it's null for the `Option` type. 
But perhaps we could use an option name here, as you suggested, and as we [already do](https://github.com/nopSolutions/nopCommerce/blob/master/src/Presentation/Nop.Web/Areas/Admin/Factories/ProductModelFactory.cs#L1502) for the specification attribute table on the product page in the admin area (see `ValueRaw` field).

**Comment by skoshelev** [comment]
Closed #6301
