### ISSUE TITLE
Do not run update migrations after a clean installation

### ISSUE THREAD

**Issue by exileDev** [nopSolutions/nopCommerce#6303]
nopCommerce version: develop

We should prevent redundant execution of update migrations during installation.

**Comment by skoshelev** [comment]
It is also necessary to ignore migrations from other assemblies, not only from Nop.Data. For example, from Nop.Web.Framework (see ticket #6495). But we need not touch the migrations in the plugins, since the processes there may differ from ours.

**Comment by exileDev** [comment]
Closed #6303
