### ISSUE TITLE
Notification when reordering unpublished products

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6309]
> nopCommerce version: 4.50.3
> 
> Steps to reproduce the problem: 
> 1. A user sends an order with multiple products.
> 2. An administrator removes one product's publication.
> 3. The user clicks on the re-order button on the order's page.
> 4. The new cart doesn't contain any unpublished product (that's OK), but there is no notification about the missing products.
> 
> It would be better if nopCommerce would send a message about the missing products, or just a generic text (e.g., "Some products are not available anymore, so they weren't added to the cart.")

Source: https://www.nopcommerce.com/boards/topic/94636/notification-about-missing-products-re-order

**Comment by mike-warren-dev** [comment]
@AndreiMaz I'll do this one if you don't mind.

**Comment by RomanovM** [comment]
@mike-warren-dev Yep, you are welcome.
