### ISSUE TITLE
Shipping rates not displayed

### ISSUE THREAD

**Issue by Freestylemusic** [nopSolutions/nopCommerce#6315]
nopCommerce version: 4.50.3

Steps to reproduce the problem: 
When we put published Fixed shipping rates into the shipping the set up, they are not showing live on the site when a customer estimates shipping cost. 

Am I just looking at this as something out of the box that should work? 

I have even set products to have additional shipping charges and this still fails to show.

**Comment by AndreiMaz** [comment]
It works fine by default. You can check it on our demo website - https://demo.nopcommerce.com/apple-icam

**Comment by glhays** [comment]
Did you clear the cache and or restart the app? Just a thought.


________________________________
From: Freestylemusic ***@***.***>
Sent: Tuesday, July 26, 2022 9:11:00 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] NoP Commerce shipping rates not displayed (Issue #6315)


nopCommerce version: 4.50.3

Steps to reproduce the problem:
When we put published Fixed shipping rates into the shipping the set up, they are not showing live on the site when a customer estimates shipping cost.

Am I just looking at this as something out of the box that should work?

I have even set products to have additional shipping charges and this still fails to show.

**Comment by Freestylemusic** [comment]
> It works fine by default. You can check it on our demo website - https://demo.nopcommerce.com/apple-icam

It doesnt display rates for any shipping on my devices

restarted app and cleared cache also

**Comment by glhays** [comment]
You might try the nop forum, maybe with a little more detail on your setup someone there can help.


________________________________

**Comment by glhays** [comment]
Not sure what this means? Check your settings compared to the demo admin maybe. To hard to know without details of the site your talking about and the related shipping setting. Try the forum.


________________________________
