### ISSUE TITLE
Vendor should get email notification if ordered product belong to that vendor

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6317]
nopCommerce version: 
All version
Steps to reproduce the problem: 
1 Placed the order any product that is belong to Vendor.
2 Check message queue/ email 
3 Email sent to customer & admin but Not to Vendor, Why?

**Comment by AndreiMaz** [comment]
Just enable "OrderPlaced.VendorNotification" or "OrderPaid.VendorNotification" message templates. We use GitHub for work items only, please post all technical questions on our forums - https://www.nopcommerce.com/en/boards/
