### ISSUE TITLE
Why uses AutofacServiceProviderFactory instead of DefaultServiceProviderFactory ?

### ISSUE THREAD

**Issue by hochun836** [nopSolutions/nopCommerce#6321]
nopCommerce version: 4.50.3

According to #4196,
I know nopCommerce 4.50.3 has used the ASP.NET Core internal dependency injection instead of `Autofac`.

But in the [Presentation\Nop.Web\program.cs](https://github.com/nopSolutions/nopCommerce/blob/release-4.50.3/src/Presentation/Nop.Web/Program.cs#L9), why does there still use `AutofacServiceProviderFactory` instead of `DefaultServiceProviderFactory` ?

PS. `DefaultServiceProviderFactory` is used by the ASP.NET Core internal dependency injection. ([LINK](https://source.dot.net/#Microsoft.Extensions.Hosting/HostingHostBuilderExtensions.cs,195))

**Comment by AndreiMaz** [comment]
Could you please post all questions on our forums? We use GitHub for planned work items only
