### ISSUE TITLE
Failed to launch debug adapter

### ISSUE THREAD

**Issue by FHFS** [nopSolutions/nopCommerce#6322]
nopCommerce version: 
[branch develop head](https://github.com/nopSolutions/nopCommerce/commit/6f3c8b847128890020a3efb1c94f365f4f46cd0d)

Steps to reproduce the problem: 
1. In the Visual studio add docker support. Dockerfile example:
```
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY ["Presentation/Nop.Web/Nop.Web.csproj", "Presentation/Nop.Web/"]
COPY ["Libraries/Nop.Services/Nop.Services.csproj", "Libraries/Nop.Services/"]
COPY ["Libraries/Nop.Core/Nop.Core.csproj", "Libraries/Nop.Core/"]
COPY ["Libraries/Nop.Data/Nop.Data.csproj", "Libraries/Nop.Data/"]
COPY ["Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj", "Presentation/Nop.Web.Framework/"]
RUN dotnet restore "Presentation/Nop.Web/Nop.Web.csproj"
COPY . .
WORKDIR "/src/Presentation/Nop.Web"
RUN dotnet build "Nop.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Nop.Web.csproj" -c Release -o /app/publish

FROM base AS final

# add globalization support
# icu-data-full for all cultures/locales https://github.com/dotnet/dotnet-docker/issues/3844
RUN apk update; apk add icu-libs icu-data-full
#RUN apk add --no-cache icu-libs \
    #icu-data-full
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT false

ENV LANGUAGE nl_NL:nl
ENV LC_ALL nl_NL.UTF-8
ENV LANG nl_NL.UTF-8

# installs required packages
RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
RUN apk add libc-dev --no-cache
RUN apk add tzdata --no-cache

# copy entrypoint script
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

WORKDIR /app        
RUN mkdir bin
RUN mkdir logs 
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Nop.Web.dll"]
```
2. Add container orchestration support. docker-compose.yml example:
```
version: '3.4'

services:
  nop.web:
    image: ${DOCKER_REGISTRY-}nopweb
    build:
      context: .
      dockerfile: Presentation/Nop.Web/Dockerfile
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

We would like to debug the container from Visual Studio. However we are unable to attach to the debug adapter.
With the environment variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT set to true, debugging works perfectly. We cant do that since we need it set to false for NopCommerce to work.
Using the normal base image "dotnet/aspnet:6.0 AS base" debugging works, but this runs into problems further down the line.

When creating a basic webapp from aspnet core template, and adding docker support with alpine as base, we can debug with DOTNET_SYSTEM_GLOBALIZATION_INVARIANT set to false without any problems. (edit specified its a basic template)

I am unable to pinpoint the problem any further.
Does anyone here know how to fix this problem?

**Comment by RomanovM** [comment]
Please post your questions on [our forums](https://www.nopcommerce.com/boards), we use GitHub as an issue tracker only. Moreover, our active community helps on the forums.
