### ISSUE TITLE
DistributedCacheManager's internal PerRequestCache out of sync with IDistributed cache

### ISSUE THREAD

**Issue by tobyreid** [nopSolutions/nopCommerce#6324]
nopCommerce version: 4.50.3

Steps to reproduce the problem: 

Any code that calls [`DistributedCacheManager.GetAsync`](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs#L144) or [`DistributedCacheManager.Get`](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs#L209)   where the value is present in the IDistributedCache implementation (redis), but has not yet been loaded into the PerRequestCache; will not be tracked in the `_keys` list.

This can cause sync problems when subsequent calls to [`RemoveByPrefixAsync`](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs#L274)  are called in the same request - and items are not removed from redis.

The bug manifests in shopping carts or wishlists not being updated,  and is easy to re-create when running in k8 with multiple pods, using redis without sticky sessions.

The fix is to add the following after wherever we call [PerRequestCache.Set](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Caching/DistributedCacheManager.cs#L417)

```csharp
using var _ = _locker.Lock();
_keys.Add(key.Key);
```

(or the async equivalent)

**Comment by tobyreid** [comment]
I have created a branch here with the proposed fix and a unit test class: https://github.com/tobyreid/nopCommerce/tree/issue-6324

**Comment by tobyreid** [comment]
Sorry, I renamed my branch to match the contribution guidelines https://docs.nopcommerce.com/en/developer/contribute/source-code.html#branch-descriptions-and-naming

**Comment by skoshelev** [comment]
Closed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/d9ceda703cc63aec899a5204ed0587dc710185cf)
