### ISSUE TITLE
Sales Summary Report is not filtering on Vendor when logged in user is a Vendor

### ISSUE THREAD

**Issue by tonywiredin** [nopSolutions/nopCommerce#6327]
nopCommerce version: 4.5

Steps to reproduce the problem:

1. Ensure that ACL is set to vendors can see the order summary report
2. Login as a vendor
3. Go to Order Summary Report
4. The summary list will contain ALL orders not just orders for the vendor

**Comment by exileDev** [comment]
Closed #6327
