### ISSUE TITLE
DeleteDirectory should be virtual method

### ISSUE THREAD

**Issue by DevPartner** [nopSolutions/nopCommerce#6328]
Please replace 
public void DeleteDirectory(string path)
with
public virtual void DeleteDirectory(string path)
https://github.com/nopSolutions/nopCommerce/blob/12dd4825dfb56bbc64e192cd35d25e3205427646/src/Libraries/Nop.Core/Infrastructure/NopFileProvider.cs#L117

**Comment by exileDev** [comment]
Closed #6328
