### ISSUE TITLE
Is there any built-in feature to make our store private?

### ISSUE THREAD

**Issue by MarshalOfficial** [nopSolutions/nopCommerce#6330]
Consider that we want to make a private store for a company employees only. 
So the home page must be a login page that employees log in via that and after that store home page shows up.
Is there any built-in feature for this need or we must customize the current version?

**Comment by manuel3108** [comment]
In the access control list, disable allow navigation for guests

**Comment by AndreiMaz** [comment]
Please post all question on our forums. We use GitHub for work items only

**Comment by MarshalOfficial** [comment]
> Please post all question on our forums. We use GitHub for work items only

ok, sorry.
