### ISSUE TITLE
Bug in the method GetShipmentTrackerAsync

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6334]
nopCommerce version: 4.50

Described at https://www.nopcommerce.com/en/boards/topic/94765/bug-in-the-method-getshipmenttrackerasync-in-nop-450 (with the fix) 

Also related - https://www.nopcommerce.com/en/boards/topic/94751/odd-shipment-error-after-upgrading-44-to-453

**Comment by skoshelev** [comment]
Closed #6334
