### ISSUE TITLE
Duplicate Executions for Event Consumer

### ISSUE THREAD

**Issue by firoj2005** [nopSolutions/nopCommerce#6335]
**nopCommerce version:** release-4.50.3

**Steps to reproduce the problem:** 
For example CacheEventConsumer is executed multiple times for same  "EventName", "EntityName", and "EntityId" when a Product is updated one time only in Admin.

To repro the issue locally, I am logging (added sample code to insert into Azure Table) "EventName", "EntityName", and "EntityId" from CacheEventConsumer (https://github.com/nopSolutions/nopCommerce/blob/release-4.50.3/src/Libraries/Nop.Services/Caching/CacheEventConsumer.cs#L50).

 I see same "EventName", "EntityName", and "EntityId" 4 times when I update a product one time only in Admin:
![image](https://user-images.githubusercontent.com/16169283/184734712-d742da68-4e44-490a-9871-6a959dbee692.png)

**Comment by AndreiMaz** [comment]
We invoke `ProductService.UpdateProduct()` mulriple times during a product update. Hence this method is invoked  multiple times as well
