### ISSUE TITLE
Adding negative reward points with the "Points validity" field filled causes exception

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#6336]
nopCommerce version: 4.60.0

Steps to reproduce the problem: 
1. Go to the Customer edit page
2. There, proceed to the Reward points panel
3. Fill in the Points filed with any negative value
4. Fill in the Points validity field with some value. Obviously this field should not be used when reducing points but it should not cause an exeption either.

**Comment by khairuzzaman** [comment]
If this task has no assignee. I would like to be assigned to it.

**Comment by RomanovM** [comment]
@khairuzzaman Sure, please feel free to make a pull request.

**Comment by exileDev** [comment]
Thanks @khairuzzaman! Closed #6336
