### ISSUE TITLE
 Parameter name of "search" causing null values on searchModels

### ISSUE THREAD

**Issue by iamsaleeb** [nopSolutions/nopCommerce#6337]
**nopCommerce version:** 4.50, 4.20 (tested for both)

**Steps to reproduce the problem:** 

1. Go to Nop.Web.Areas.Admin.Controllers LogController
2. Change the LogList method parameter name of "searchModel" to just "search". It should look like the following:
BEFORE: `public virtual IActionResult LogList(LogSearchModel searchModel)`
AFTER: `public virtual IActionResult LogList(LogSearchModel search)`
3. If you now try to access the logs in Admin/System/System Log, you will find no values being returned. I have tried to debug this, and it seems that ONLY with the variable name of `search`, the object will be returned with no data. 

I am not sure if this is an intended feature of nopCommerce, I have tried to trace down the cause of this, but was unable to find a root reason/cause.

**Comment by RomanovM** [comment]
Just don't change it to something like this if it doesn't work.
If you're curious, try asking on [our forums](https://www.nopcommerce.com/boards). We only use GitHub to track issues.

**Comment by iamsaleeb** [comment]
This issue is across the entire Nop platform when it comes to searchModels. If I name the variable anything at all, it works fine. The moment I name it `search`, the data that gets passed through is empty.
