### ISSUE TITLE
Allow 'has user agreement' to be selected even for non downloadable products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#634]
downloadable products have option 'has user agreement' ( it appears when you tick the 'downloadable product' box ) should this be an option on all product variants? 

for example, a store sells fireworks - they might want the customer to agree to a user agreement to follow a set of safe firework rules 

I'm not suggesting that we create a new field, just make the current field available for any product type

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
