### ISSUE TITLE
Add Customer GUID

### ISSUE THREAD

**Issue by Alaa-Eddin-jo** [nopSolutions/nopCommerce#6341]
nopCommerce version: 
4.50.2
Steps to reproduce the problem: 
In /api-frontend/Authenticate/GetToken
we need to add Customer GUID 
there are many endpoint using the Customer GUID and it is not available in the Forint API endpoints.
it is good also to add it to Customer Info 
/api-frontend/Customer/Info

**Comment by AndreiMaz** [comment]
Closing it here as it's not related to nopCommerce core. It'll be considered as part of the api plugin

**Comment by Alaa-Eddin-jo** [comment]
Is there Repo for the API Plugin?

**Comment by AndreiMaz** [comment]
Yes, but it's private

**Comment by Alaa-Eddin-jo** [comment]
How to open issue for it ?

**Comment by AndreiMaz** [comment]
We've already opened it

**Comment by Alaa-Eddin-jo** [comment]
How to add the new issue that i have ?
shall i send it here?

**Comment by AndreiMaz** [comment]
Please feel free to describe them here. And we'll consider them in one of the next API releases
