### ISSUE TITLE
Reflection support

### ISSUE THREAD

**Issue by Alaa-Eddin-jo** [nopSolutions/nopCommerce#6343]
Hi,
Is there any chance to support Reflection?
https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/dynamically-loading-and-using-types

The idea is to have a way for adding custom property to the domain classes at runtime - it work also for adding custom type (Table).

For Example: (in someway in my plugin or even without plugin by calling some endpoints) 
I can add a property "CP_something" to the class Customer
so this property will be represented as column in Customer Table in DB
and each time i use method like "GetAllCustomersAsync" i get my property in the Customer object
and each time i make api request to "/api-frontend/Customer/Info" or "/api-backend/Customer/GetCustomerByGuid" i get the property in the Dto.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we do not plan to implement it out of the box

**Comment by skoshelev** [comment]
Hi @Alaa-Eddin-jo. I want to add a couple of points, as I have studied this point quite deeply. Despite the fact that in some scenarios it can be convenient and useful. However, reflections use much more resources than direct work with objects. And if we add to this the need to bypass all the properties of an object in a cycle, the inability to use ORM and other basic language constructs, then all the pluses look very insignificant.
