### ISSUE TITLE
Checkout attributes not formatted int current language

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#6344]
nopCommerce version: 4.50.3

Steps to reproduce the problem: 
CheckoutAttributeFormatter.FormatAttributesAsync - 
LN:87 var currentLanguage = _workContext.GetWorkingLanguageAsync();

Missing 'await' so currentLanguage.Id used below return Task id not the language id

**Comment by skoshelev** [comment]
Hi @kiranbhadani. Thank you for your help.

Closed #6344
