### ISSUE TITLE
"GetWarehouseByIdAsync" is found in two different services

### ISSUE THREAD

**Issue by wEEdONeX** [nopSolutions/nopCommerce#6348]
nopCommerce version: (at least) 4.30 to 4.60

![image](https://user-images.githubusercontent.com/40871547/188645591-7f0043e4-f234-4a35-9988-ad9c366e9ea3.png)

I found these methods that basically do the same thing and both of them are used. I belive the one in IProductService should be removed if there is no particular reason to keep them both.

**Comment by glhays** [comment]
Service based?


________________________________
From: Prisacariu Daniel ***@***.***>
Sent: Tuesday, September 6, 2022 6:31:54 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] "GetWarehouseByIdAsync" is found in two different services (Issue #6348)


nopCommerce version: (at least) 4.30 to 4.60

[image]<https://user-images.githubusercontent.com/40871547/188645591-7f0043e4-f234-4a35-9988-ad9c366e9ea3.png>

I found these methods that basically do the same thing and both of them are used. I belive the one in IProductService should be removed if there is no particular reason to keep them both.

**Comment by ChrisClaude** [comment]
Hi @AndreiMaz. I would like to look at this issue. I just want to make sure I am doing the right thing. Should I remove the GetWarehouseByIdAsync method from IProductService and update its usages to the GetWarehouseByIdAsync method from IShippingService?

**Comment by skoshelev** [comment]
Closed #6348
