### ISSUE TITLE
Sitemap.xml number of elements can go over 50,000 threshold

### ISSUE THREAD

**Issue by professor-k** [nopSolutions/nopCommerce#6349]
nopCommerce version: 
4.50.3

Steps to reproduce the problem: 
1. Site has to have more than one language available 
2. Number of pages to list in sitemap.xml should be between 25,000 and 50,000. 
3. Download sitemap.xml, there will be over 50,000 of urls in it.

I presume, it was introduced in this commit: c0c8a117b8add3f5c691e62b4e7c73df41ab2a45
In this commit it was changed so localized URLs are added each independently, however paging logic still counts each url group as one.

Also it would be nice to take into account size of the resulting file. With multiple languages, even properly paged sitemaps can easily go over 50MB.

**Comment by exileDev** [comment]
Closed #6349
