### ISSUE TITLE
installing nopCommerce stucks 

### ISSUE THREAD

**Issue by lywedo** [nopSolutions/nopCommerce#6350]
nopCommerce version: 

Steps to reproduce the problem: 
![image](https://user-images.githubusercontent.com/21200682/189361732-c40cf20b-7efb-4b50-b540-f717115dae10.png)

**Comment by RomanovM** [comment]
Try to ask on [our forums](https://www.nopcommerce.com/boards). We use GitHub only as an issue tracker, and the installation has no problem.
