### ISSUE TITLE
www.nopcommerce.com can't open

### ISSUE THREAD

**Issue by lywedo** [nopSolutions/nopCommerce#6351]
main website actually can not open!!! unbelievable

**Comment by RomanovM** [comment]
It works. Check your connection.

**Comment by lywedo** [comment]
邮件已收到，谢谢

**Comment by lywedo** [comment]
> 

maybe the problem is before checking?
![image](https://user-images.githubusercontent.com/21200682/189368846-121116b0-6833-41a0-96d9-fc55eecfd2fb.png)
