### ISSUE TITLE
Display warning when admin enters the same discount coupon code

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6353]
nopCommerce version: 4.50

>I noticed that i can define 2 discounts with same coupon code. 

Source: https://www.nopcommerce.com/boards/topic/94925/duplicate-coupons

See #1462. But we should display a warning (`warningValidation`) when admin enters the same discount coupon code.

**Comment by ahmadkq** [comment]
@RomanovM I suggest to prevent having duplicates if there is an active old coupon, otherwise you can allow insert same coupon.

**Comment by DmitriyKulagin** [comment]
Closed #6353

**Comment by AndreiMaz** [comment]
@ahmadkq We allow that, it's used in some scenarios. For example, one coupon code for two different discounts (e.g. for some products 20% and for some products 30%). So it's by design
