### ISSUE TITLE
Issues from Rider Solution-Analysis

### ISSUE THREAD

**Issue by manuel3108** [nopSolutions/nopCommerce#6355]
nopCommerce version: 4.50

Steps to reproduce the problem: 
1. Download and install Rider
2. Wait a long time until the analysis has been completed.

I excluded the `Presentation/Nop.Web/Plugins` folder from the analysis, as this is throwing many unnecessary and incorrect errors. After that, there are mainly two remaining issues:

**<Presentation>\<Nop.Web>\Areas\Admin\Views\Setting\Forum.cshtml:3641 Tag 'section' not closed**
https://github.com/nopSolutions/nopCommerce/blob/f4003005c8d8435ab3139d353257da32dbfadf6a/src/Presentation/Nop.Web/Areas/Admin/Views/Setting/Forum.cshtml#L39-L55

**<Plugins>\<Nop.Plugin.Misc.Sendinblue>\Views\_ViewImports.cshtml:576 Cannot resolve symbol 'Areas'**
Although, this seems to be already resolved in the current develop branch (partially at least): https://github.com/nopSolutions/nopCommerce/blob/f4003005c8d8435ab3139d353257da32dbfadf6a/src/Plugins/Nop.Plugin.Misc.Sendinblue/Views/_ViewImports.cshtml

**Comment by AndreiMaz** [comment]
@manuel3108 Thanks a lot! Agree about the first issue with "section"

But not sure about the second issue with "Areas". What exactly is the issue?

**Comment by manuel3108** [comment]
@AndreiMaz I'm not on my computer right now, but I guess that Nope.Web is not a dependency of the Sendinblue plugin, which could be causing this issue

**Comment by exileDev** [comment]
Thanks. I didn't faced with the second issue, even when I used Rider.

Closed #6355
