### ISSUE TITLE
Impossible to install new version 4.50.3

### ISSUE THREAD

**Issue by AidasMIT** [nopSolutions/nopCommerce#6356]
nopCommerce version:  4.50.3

Steps to reproduce the problem: 
Download the source code. 
Try to install
Go the error 
Setup failed: An error occured executing the following sql: INSERT INTO [dbo].[MigrationVersionInfo] ([Version], [AppliedOn], [Description]) VALUES (637160666562551771, '2022-09-19T07:36:45', N'Nop.Data base schema') The error was Invalid object name 'dbo.MigrationVersionInfo'.
Absolutely fresh installation.

**Comment by RomanovM** [comment]
We cannot reproduce this issue.
See #5946 and #4888 for tips. If none of the suggestions help, then provide more details about the problem (e.g. hosting info, server info, db provider, etc).

**Comment by msavara** [comment]
I have exact same issue 
Ubuntu 22.04 kernel 6.0
aspnet core runtime 6.0.9
MariaDB (ver. 10.6.10
