### ISSUE TITLE
Close order performance

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6359]
nopCommerce version: 4.5

Hi,

in our b2b we have order with many items.
There are alse some discounts and some acl rule (with discounts)

Sometimes we have error 500 time out when a customer close an order.

Looking at the source code we believe it is possible to do some refactoring

In OrderProcessingService.PreparePlaceOrderDetailsAsync
there are two call
await _orderTotalCalculationService.GetShoppingCartSubTotalAsync(details.Cart, true);
await _orderTotalCalculationService.GetShoppingCartSubTotalAsync(details.Cart, false);

and

await _orderTotalCalculationService.GetShoppingCartShippingTotalAsync(details.Cart, true);
await _orderTotalCalculationService.GetShoppingCartShippingTotalAsync(details.Cart, false);

I think that it's possible change this

and this, less important
In CheckoutController.ConfirmOrder

I think that:
//prevent 2 orders being placed within an X seconds time frame
if (!await IsMinimumOrderPlacementIntervalValidAsync(customer))
	throw new Exception(await _localizationService.GetResourceAsync("Checkout.MinOrderPlacementInterval"));
	
	
 it's possible to move some row before

**Comment by kava81** [comment]
Hi, do you have any news about this.
Sorry for the reminder, but alternative we have to do something homemade.
thanks

**Comment by skoshelev** [comment]
Closed #6359
