### ISSUE TITLE
New event trigger for nopcommerce plugins 

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#6362]
nopCommerce version: development 

Steps to reproduce the problem: 

It will be very useful to have events for application start and application shutdown. This will allow plugins to perform any cleanup tasks that are required. 

Also for the entity change event, it will be very useful to have entity before change in the argument of the event so users can consume value before and after.

**Comment by RomanovM** [comment]
@Farshidgolkarihagh It will not be easy to embed our event mechanism in the app life cycle, perhaps we will consider this later.
Regarding the second suggestion, this has already been discussed and decided to leave it for customization.
