### ISSUE TITLE
Reason code for unpublishing products 

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#6364]
nopCommerce version: development 

Steps to reproduce the problem: it will be very useful to have reason code for unpublishing products e.g 

Discontinued 
Pending image review 
Pending seo review 
Etc

You could have a seperate section for modifying or adding reason code.

**Comment by RomanovM** [comment]
Thanks for the suggestion. It looks very specific, we'll leave this for customization.
