### ISSUE TITLE
Customer Role with Multiple Purchased with products

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#6374]
nopCommerce version: 4.50.2

Steps to reproduce the problem: 
Suggestion, when setting up a role and choosing "Purchased with product" allow multiple items to select, not just one.

In the screenshot, have radio buttons to select which products add the customer to that role.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/20989983/194640671-107a9564-e1e4-4be5-a511-122f82662c5e.png">

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
