### ISSUE TITLE
Setup failed: An exception was thrown while activating λ:FluentMigrator.Runner.IVersionLoader.

### ISSUE THREAD

**Issue by msavara** [nopSolutions/nopCommerce#6375]
nopCommerce version: 4.50.3 x64 linux

Steps to reproduce the problem: 
Clean installation with sample data
Ubuntu Server 22.04 kernel 6.0
Nginx 1.22
aspnet core runtime 6.0.9
MariaDB ver. 10.6.10

If you want. i can provide login for that server for your diagnostic. There was other users complain about this issue but they was closed by you. but that doesn't mean that when the issue ticket is closed that the problem doesn't exist :)

**Comment by LaplancheMaxime** [comment]
I have the same problem on docker image 4.50

**Comment by msavara** [comment]
@exileDev do you want access to that server where it's fails?

**Comment by exileDev** [comment]
Hi @msavara! Your issue is simular to this one #6284, I guess. It looks like there is an issue in the Connector/NET (8.0.28 version ). Here is a possible workaround https://github.com/nopSolutions/nopCommerce/issues/6284#issuecomment-1158782260

**Comment by exileDev** [comment]
We are going to bump the package in the next minor version. But in the 4.60, we abandoned the use of Connector/NET in favor of MySqlConnector

**Comment by LaplancheMaxime** [comment]
@exileDev  do you have an approximate date for a minor version correction?
Thank's

**Comment by AndreiMaz** [comment]
@LaplancheMaxime Most probably, this week

**Comment by exileDev** [comment]
Closed #6375
