### ISSUE TITLE
Add a new media setting - "Allow SVG uploads in admin area"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6378]
Continuation of https://github.com/nopSolutions/nopCommerce/issues/6192 and https://www.nopcommerce.com/en/boards/topic/95054/vulnerability-found-in-file-upload-stored-xxs-possible and 

Let's add the new media setting (place it after the existing "Picture zoom" setting). Disabled by default. When enabled, it should be applied to all methods in admin area

**Comment by skoshelev** [comment]
Closed #6378
