### ISSUE TITLE
FilterableSpecificationAttributeOptionsPrefix key issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6380]
Is the FilterableSpecificationAttributeOptionsPrefix  key ok ? because SpecificationAttributeOptionsByCategoryCacheKey contains prefix "Nop.specificationattributeoption.bycategory."

https://github.com/nopSolutions/nopCommerce/blob/78f187b74a16802177fde440d8c7615e4e13932b/src/Libraries/Nop.Services/Catalog/NopCatalogDefaults.cs

  
```
public static CacheKey SpecificationAttributeOptionsByCategoryCacheKey => new("Nop.specificationattributeoption.bycategory.{0}", FilterableSpecificationAttributeOptionsPrefix);

        /// <summary>
        /// Key for specification attribute options by manufacturer ID caching
        /// </summary>
        /// <remarks>
        /// {0} : manufacturer ID
        /// </remarks>
        public static CacheKey SpecificationAttributeOptionsByManufacturerCacheKey => new("Nop.specificationattributeoption.bymanufacturer.{0}", FilterableSpecificationAttributeOptionsPrefix);

        /// <summary>
        /// Gets a key pattern to clear cache
        /// </summary>
        public static string FilterableSpecificationAttributeOptionsPrefix => "Nop.filterablespecificationattributeoptions";
```

Source: https://www.nopcommerce.com/en/boards/topic/95065/filterablespecificationattributeoptionsprefix-is-ok-

**Comment by skoshelev** [comment]
Closed by https://github.com/nopSolutions/nopCommerce/commit/3efa355f1e8d3f616225c225f49d0e82bb7510ca
