### ISSUE TITLE
Async is not used properly

### ISSUE THREAD

**Issue by propellingbits** [nopSolutions/nopCommerce#6381]
Async is not a magic performance keyword. If used improperly, it adds overhead as well. The following code is just an example, I presume it's used improperly or rather overused throughout the entire codebase.
**nopCommerce version:** master branch

**Steps to reproduce the problem:** 
Provided below!
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Installation/InstallationService.cs
### Can you please clarify why async/await was required in the following code?

```
            await settingService.SaveSettingAsync(new EmailAccountSettings { DefaultEmailAccountId = eaGeneral.Id });

            await settingService.SaveSettingAsync(new WidgetSettings
            {
                ActiveWidgetSystemNames = new List<string> { "Widgets.NivoSlider" }
            });

            await settingService.SaveSettingAsync(new DisplayDefaultMenuItemSettings
            {
                DisplayHomepageMenuItem = true,
                DisplayNewProductsMenuItem = true,
                DisplayProductSearchMenuItem = true,
                DisplayCustomerInfoMenuItem = true,
                DisplayBlogMenuItem = true,
                DisplayForumsMenuItem = true,
                DisplayContactUsMenuItem = true
            });
```

**Comment by AndreiMaz** [comment]
> Can you please clarify why async/await was required in the following code?

Please use our [forums](https://www.nopcommerce.com/en/boards) for discussions. We use GitHub for work items only

**Comment by propellingbits** [comment]
Andrei! It was not entirely meant to be a discussion. I was hoping your team can make changes and follow the correct async guidelines.
