### ISSUE TITLE
Schedule Task LastEnd and LastSuccess difference?

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#6382]
nopCommerce version: 
4.50.3

Steps to reproduce the problem: 
What is the point of the 2 dates "LastEnd" and "LastSuccess"? They are always the same? I cannot find in the code where they would be different, or how to set them different because in ScheduleTaskRunner they are set to the same value. I was hoping to only have "LastSuccess" be set when the task I created actually does what it's supposed to do:

Here is the code from ScheduleTaskRunner 
`scheduleTask.LastEndUtc = scheduleTask.LastSuccessUtc = DateTime.UtcNow;`

**Comment by AndreiMaz** [comment]
Sometimes schedule tasks are not completed successfully. In this case values will be different.
