### ISSUE TITLE
"Don't display a customer attribute to customer" option

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#6386]
nopCommerce version: 
4.50.3

Steps to reproduce the problem: 
Just a simple suggestion to NOT display a Custom Customer Attribute in their info page:

Add a new column to display to customer:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/20989983/195684805-e9a87fe2-6166-47c3-906d-5e17f8aafd48.png">

Modify PrepareCustomerInfoModelAsync to only display those fields we want to show them

**Comment by sateeshmunagala** [comment]
We need make sure customer registration is as fast & simple as possible. 
For this we need to show very important fields in Registration page and remaining fields ( ex: company, LinkedIn URL) in customer info page where customer can fill up them when ever he needed. 
We can encourage the customer to fill up other fields by mentioning profile completeness percentage in my account page

To achieve this 
create one more check box  like "Display in Customer Info page Only". 
This can be applicable for all standard fields  and custom attributes .

**Comment by mike-warren-dev** [comment]
I'll work on this one.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
