### ISSUE TITLE
PayPal Commerce. Add a link to our documentation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6387]
Let's update the configuration page of the PayPal Commerce plugin - [your_store_URL]/Admin/PayPalCommerce/Configure

Add the following text to the end of the both tabs: "Learn more about the PayPal Commerce plugin configuration [here](https://docs.nopcommerce.com/en/getting-started/configure-payments/payment-methods/paypal-commerce.html).

**Comment by skoshelev** [comment]
Closed #6387
