### ISSUE TITLE
Use local storage to keep guest user data instead of creating a new Guest in database

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#6391]
nopCommerce version: all

Is there any chance we could keep guest user data in local storage instead of creating a new user. As far as i can see there is no reason to create a user until they actually register or creates an order.

Is there any reason the user is created right a way when visiting the site? I guess having 10.000+ customers visiting a website under a sale is quite taxing on the db when you add an entry for each customer.

**Comment by AndreiMaz** [comment]
@lintho It's an unified approach to store information about all customers. Store shopping cart, visiting history, apply any dynamic segmentation logic, etc. So it's by design.

10K+ records is not so many nowadays. Furthermore, all "empty" guest records are deleted periodically

**Comment by lintho** [comment]
Alright. Thanks :) Then ill have to create another ticket in order to address performance. We have hosted as web apps in azure and the site crashes even with 400 concurrent users.

**Comment by lintho** [comment]
I still think this is causing the performance issues when our stores are having sales and the website get loads of customers entering at the same time from a newsletter. For every customer visiting the website it inserts into db for both customer and customerrole. 2 saves to db for all new customers cant be great for performance?

**Comment by skoshelev** [comment]
Hi @lintho. Yes, if there weren’t these two calls to the database, then under heavy load, performance would be higher, but how do you propose to solve the tasks with storring the shopping cart, wish list, activity history, access control, changing locales and currencies, etc.?

**Comment by lintho** [comment]
What if we create the guest customer only if they actually do something that needs information later on? Like addtocart. A guid could be stored in local storage(browser db) and kept in cookie, and then used when creating the the customer? Not sure if this would be a decent solution.

**Comment by skoshelev** [comment]
You are describing very specific working conditions, but in most cases it will not work this way, and the user will have to be saved after one or two requests, which will not change the performance situation in any way. 

In any case, in the current codebase, the user is so tightly integrated with all the functionality that creating guest records outside the database will require rewriting a huge layer of logic.

**Comment by lintho** [comment]
> You are describing very specific working conditions, but in most cases it will not work this way, and the user will have to be saved after one or two requests, which will not change the performance situation in any way.


Maybe, but saving the user only when they add something to cart is not happening as often as a user visiting the site. 

> In any case, in the current codebase, the user is so tightly integrated with all the functionality that creating guest records outside the database will require rewriting a huge layer of logic.

I agree
