### ISSUE TITLE
Performance issue on powerful server with one web apps in azure + sql server in azure - 200+ concurrent users crashes website

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#6392]
nopCommerce version: all from 3.8 til 4.40.4 atleast

Steps to reproduce the problem: 
We have a single nopcommerce solution on a service plan (server) in azure. The service plan is a P1v3 which has these specs according to azure, 195 minimum ACU/vCPU, 8 GB memory, 2 vCPU which has a estimated cost of **246.74 USD**

We have a stand alone sql server for the solution as well, not shared at all, which has the following specs:  Standard S3: 100 DTUs

If our customer has a sale and the website gets 200+ customers it crashes instantly. We can scale out the solution to more instances, but we need atleast 4 instances (246 usd x 4) to handle 400 concurrent customers.

Considering the prices it seems like the website should handle much more traffic. Since nopcommerce supports azure and webfarms, i hope that you can do some testing in azure under "heavy" load.

I know more people on the forums have the similar experience, and we have the same experience on several solutions.

**Comment by AndreiMaz** [comment]
@lintho It could be related to many configutation settings, customization and specific to a certain website. Could you please clarify your suggestion? It should be more specific, not just "make nopCommerce faster"

**Comment by lintho** [comment]
_It should be more specific, not just "make nopCommerce faster"_. I agree!

I have tried a default nopcommerce without any additional plugins or 'wrong' configuration settings on the same server. It would be nice if you guys tried a stresstest on azure as well. Ive been using loader.io. Maybe you see something obvious. 

This post issue is still relevant for me, at least when hosting nopCommece on a service plan in azure (which is probably what most people will in the future). [](https://github.com/nopSolutions/nopCommerce/issues/5461) These tests seems to be only 100-200 users concurrent, which isnt much at all.

**Comment by lintho** [comment]
I supposed caching product prices would make a huge difference, but since we have using coupon codes and some complex discount requirements we cannot cache prices according to this: 
![image](https://user-images.githubusercontent.com/6866577/198514233-cea5ef91-2a01-4b40-a3d2-238d032fede9.png)

**Comment by AndreiMaz** [comment]
We always try to improve performance. But suggestions should be more specific. So if we see some specific place that could be optimized, we refactor or improve it.

**Comment by lintho** [comment]
If i knew what could be improved i would of course specify. All i know right now is: If 200+ concurrent users visits a default nopCommerce solution hosted on a quite expensive service plan in azure, it crashes or the response time goes up very very fast to 30+ seconds. Ive been using loader.io to test. Has the solution been tested in azure on a service plan? It might be the infrastructure in azure, not sure.

**Comment by mattisax** [comment]
@lintho What are your Garbage Collection settings in Nop.Web.runtimeconfig.json?

**Comment by lintho** [comment]
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "5.0.0"
    },
    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}

**Comment by AndreiMaz** [comment]
> I supposed caching product prices would make a huge difference, but since we have using coupon codes and some complex discount requirements we cannot cache prices according to this: ![image](https://user-images.githubusercontent.com/6866577/198514233-cea5ef91-2a01-4b40-a3d2-238d032fede9.png)

Just replied at https://www.nopcommerce.com/en/boards/topic/95191/cacheproductprices-should-not-be-enabled-if-we-use-complex-discount-requirements-why#300489

Anyway, as I've already mentioned suggestions should be more specific. So if we see some specific place that could be optimized, we refactor or improve it. In the meantime, I'm closing this work item

**Comment by mattisax** [comment]
@lintho 
We've found that setting `"System.GC.Concurrent"` and `"System.GC.Server"` to `true` helps performance.

**Comment by lintho** [comment]
> @lintho We've found that setting `"System.GC.Concurrent"` and `"System.GC.Server"` to `true` helps performance.

Ok. Do you add the file in nop.web and set build action to content and copy to output directory?

**Comment by lintho** [comment]
Oh nevermind. Found it in web.config
