### ISSUE TITLE
Customer Phone Number Validation Issue

### ISSUE THREAD

**Issue by fjaramillo-afw** [nopSolutions/nopCommerce#6393]
Hello,

We have had it reported that at checkout, customer can enter an invalid mobile phone number. 

https://www.afw.com/SecureCheckout/Billing

nopCommerce version: 4.50.2

Steps to reproduce the problem: 

Create a new customer https://www.afw.com/register?returnUrl=%2F (only email, username, password is required)
Create an order and checkout
On check-out you are required to enter a phone number if one doesn't already exist, which one will not
No validation is happening on the phone number entry and some customers are typing in the US country code

Expected:

The customer is not able to enter in an invalid area code or phone number

Actual:

The customer can enter an invalid phone number that is saved to customer profile and no SMS communication can take place

Workaround:

Customers can go here and fix their phone number https://www.afw.com/customer/info

Findings:
We have found in our investigation that even though our "Create Account" form doesn't include a field for phone number. The 'PhoneNumberPropertyValidator.IsValid' method still gets called. We found that there are NOP settings for 'customerSettings.PhoneRequired', 'customerSettings.PhoneNumberValidationEnabled', and 'customerSettings.PhoneNumberValidationRule' being made use of in that IsValid method. There was no check in there to see if the PhoneRequired. We have tweaked that method to get this working for us for now.

Our updated version of that method is as below:
public static bool IsValid(string phoneNumber, CustomerSettings customerSettings)
        {
            if (!customerSettings.PhoneNumberValidationEnabled || string.IsNullOrEmpty(customerSettings.PhoneNumberValidationRule))
                return true;

            **if (string.IsNullOrEmpty(phoneNumber))
            {
                return !customerSettings.PhoneRequired;
            }**

            return customerSettings.PhoneNumberValidationUseRegex
                ? Regex.IsMatch(phoneNumber, customerSettings.PhoneNumberValidationRule, RegexOptions.CultureInvariant | RegexOptions.IgnoreCase)
                : phoneNumber.All(l => customerSettings.PhoneNumberValidationRule.Contains(l));
        }

With the updates above, (currently only on our dev https://dev.afw.com, and qa https://qa.afw.com sites), and the settings below this is now functioning as expected without a phone number field in our version of the form.
customersettings.phonerequired = False;
customersettings.phonenumbervalidationuseregex = True;
customersettings.phonenumbervalidationenabled = True;
customersettings.phonenumbervalidationrule = '^(\([0-9]{3}\)|[0-9]{3}-)([0-9]{3}-[0-9]{4}| [0-9]{3}-[0-9]{4})$'

We suggest that your version of that validation be updated to respect the setting for if 'customersettings.phonerequired '

We would like to make use of the validation for the phone number in the place order steps, but not have it prevent the customer from creating a new customer record when no Phone Number field is present.

Thanks

**Comment by AndreiMaz** [comment]
Already implemented - https://github.com/nopSolutions/nopCommerce/issues/4356

**Comment by AndreiMaz** [comment]
@exileDev please check https://github.com/nopSolutions/nopCommerce/pull/6399

**Comment by exileDev** [comment]
Thank you! Closed #6393
