### ISSUE TITLE
Rename a locale

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6396]
nopCommerce version: 4.50.4

In the software, I found what seems to be an old reference to something called "Manage Stock", but I think it refers to what is now called "Inventory method". It is found within the "Product details" page in the Admin section. Specifically, it is in the roll over message for "Minimum stock qty" within the "Inventory" section.

So let's rename the hint _If you have enabled 'Manage Stock' you can perform a number of different actions when the current stock quantity falls below (reaches) your minimum stock quantity._ to _If you track inventory you can perform a number of different actions when the current stock quantity falls below (reaches) your minimum stock quantity._

**Comment by exileDev** [comment]
Closed #6396
