### ISSUE TITLE
 Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Ubiety.Dns.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#6400]
nopCommerce version: 4.50.4

Host Environment: Ubuntu 20.04 + Nginx

Steps to reproduce the problem: 
After Upgraded to 4.50.4, Nop can not start, there is an exception in logs:
![image](https://user-images.githubusercontent.com/2167369/198861264-f192eab0-78dd-4fce-a062-2a77162506b6.png)

Downgrade Mysql.data.dll from 8.0.31 to 8.0.29 fixed the problem.
![image](https://user-images.githubusercontent.com/2167369/198861291-93cbb09c-2bf6-4085-99cb-629cc17f265b.png)

I am sorry I dont have enough time to dig deep,  but it seems this is somehow related to the unsigned version of Ubiety.Dns.Core.dll

https://bugs.mysql.com/bug.php?id=98204

MySql.Data is buggy and problematic,  update it with caution, lol :)

**Comment by untiedshoes** [comment]
I got the same yesterday after 'upgrading' to MySQL.Data 8.0.31 (Nop 4.5.4). Rolled back to 8.0.29.

**Comment by exileDev** [comment]
Hi! I couldn't reproduce this issue.
The clean nopCommerce 4.50.4
MySQL 8.0.31

Works fine.

**Comment by untiedshoes** [comment]
The issue arises when you update the nop.data.csproj MySQL reference, build, then publish.

**Comment by nextfool** [comment]
@exileDev  Ok I think I found the problem.  In one of my [previous issue](https://github.com/nopSolutions/nopCommerce/issues/5605#issuecomment-817482418),  We talked about replacing "Mysql.Data" with "MySqlConnector". See your comment [here](https://github.com/nopSolutions/nopCommerce/issues/5605#issuecomment-851315923) 

In the following commit, I saw that this job has been done, it's just not merged to latest release yet.
![image](https://user-images.githubusercontent.com/2167369/199138142-b1efd258-c56f-47ad-b7e2-162ef0cd2ce5.png)


In the latest release,  the buggy Mysql.Data is just upgraded, not replaced.

So I think the solution would simply be merging the Connector/NET branch~~

**Comment by exileDev** [comment]
Closed #6400
