### ISSUE TITLE
Discount list page & details startdate/enddate issue

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6401]
nopCommerce version: 4.40

Steps to reproduce the problem: 
1- open the discount list page/open a details page

you will find that the date/time is in UTC not customer date/time.

**Comment by AndreiMaz** [comment]
@ahmadkq It's by design. Its even written in the hint for each these inputs

Also see https://github.com/nopSolutions/nopCommerce/issues/560 (duplicates)
