### ISSUE TITLE
Missing order positions or duplicated order quantities

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#6404]
nopCommerce version: 4.50.x

Steps to reproduce the problem: 
> Some order items, are not added to to the final order. So lets say a customer has 2 products in the cart, only one will appear in the placed order. Additionally, sometimes we also experienced, that the quantity of an cart item is duplicated by placing the order. Lets say we have a product with 10 items, in the cart, the final order will have an order item with the quantity set to 20.

Source: PS-16684

**Comment by glhays** [comment]
Is this a customized solution or a default install?


________________________________
From: Dmitriy Kulagin ***@***.***>
Sent: Monday, November 7, 2022 5:08:42 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Missing order positions or duplicated order quantities (Issue #6404)


nopCommerce version: 4.50.x

Steps to reproduce the problem:

Some order items, are not added to to the final order. So lets say a customer has 2 products in the cart, only one will appear in the placed order. Additionally, sometimes we also experienced, that the quantity of an cart item is duplicated by placing the order. Lets say we have a product with 10 items, in the cart, the final order will have an order item with the quantity set to 20.

Source: PS-16684

**Comment by Manuel-Innovapps** [comment]
In this case, it was a customized installation. But by providing evidence to the NOP team, we were able to determine that this might also happen in a default installation.

**Comment by skoshelev** [comment]
we analyzed the situation and looked at the implementation of the .ForEach method from the standard library, the problem can be reproduced on a clean installation too. Its essence lies in the fact that if you pass an asynchronous function to this method, then it will be converted to Action<T> without any problems, but it will be called without waiting for completion, as if it were a regular synchronous method. As a result, execution of the next code which place after the  .ForEach call may start before the async functions finish.

**Comment by DmitriyKulagin** [comment]
Let me explain a little more with an example.

`details.Cart.ToList().ForEach(async sci => await _shoppingCartService.DeleteShoppingCartItemAsync(sci, false));`

`List<T>.ForEach` does not work with async and all tasks will actually run synchronously.

The solution to this situation is to project each element into an asynchronous operation and then asynchronously wait for them to complete, as shown in the following example:

`await Task.WhenAll(details.Cart.ToList().Select(sci => _shoppingCartService.DeleteShoppingCartItemAsync(sci, false)));`

**Comment by DmitriyKulagin** [comment]
Closed #6404
