### ISSUE TITLE
force to change password after changing password from admin panel

### ISSUE THREAD

**Issue by Steve7394** [nopSolutions/nopCommerce#6406]
hello again!
please add some Security feature to Nop!
add some config that if enabled and change password from admin area 
the customer after login forced to change password.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization

**Comment by AndreiMaz** [comment]
Done in https://github.com/nopSolutions/nopCommerce/issues/7281
