### ISSUE TITLE
is there any optins or setting to disable inserting in QueuedEmail?

### ISSUE THREAD

**Issue by Steve7394** [nopSolutions/nopCommerce#6408]

**Comment by glhays** [comment]
Sounds like a question, not an issue.


________________________________
From: AAHB73 ***@***.***>
Sent: Monday, November 7, 2022 10:15:32 AM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] is there any optins or setting to disable inserting in QueuedEmail? (Issue #6408)

**Comment by RomanovM** [comment]
@Steve7394 Please post all your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub only as an issue tracker.
