### ISSUE TITLE
Override price adjustment in product attribute values with associated product

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#641]
In the case of product attribute values with associated product, the price adjustment is the price of the product, but when building kits/bundles it is very common to make a discount in the products or accessories included in the kit. There is the feature to override prices product attributes combinations, but it can become very complex when you have several attributes or when some are accessories (non-combinable attributes) of the product. For instance for the case of Build Your Own Computer there are 0ver 200 possible combinations. 

So the proposal is to let the user establish the price adjustment for each attribute value that has an associated product. It could be established in 2 ways (it would be great that both could be available): 
1) As a percentage of the associated product price, where 100% would be exactly as it is now. <100% renders a discount (80%= 20% discount) and >100% can be used to charge for assembly services or alike (110% means that there is a 10% extra charge. 

2) As an $ amount. 

It would also be useful that when the resulting price adjustment is less than the associated product value in the value selection text the amount of the discount is displayed: product_name [+$xx.xx (Y% discount)] so if the associated product price is $200 and in option (1) 75% was selected; the text will be product_name [+$150.00 (25% discount)] 

This feature lets to built very complex bundles and also lets use tier (or per store/customer role) prices in the main product of the bundle. 

SOurce: http://www.nopcommerce.com/boards/t/39430/suggestion-override-price-adjustment-in-product-attribute-values-with-associated-product.aspx

**Comment by esbee** [comment]
An absolute must!

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
