### ISSUE TITLE
Add new widget zones to MyAccount section

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6410]
nopCommerce version: 4.50.x

Steps to reproduce the problem: 
There is no problem.

Suggestions:
Currently, i.e. the customer info page in MyAccount does not have a single widget zone. There are only zones for adding new items to the customer page menu on the left, but no zones on the actual pages.
So we suggest adding new widget zones to the MyAccount section on each page at the top and the buttom, like we are doing on many other pages

**Comment by DmitriyKulagin** [comment]
Closed #6410
