### ISSUE TITLE
Remove "PayPal Standard" plugin (move to our marketplace) 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6418]
We already have two PayPal plugins available out of the box. PayPal Commerce is the recommended one (by PayPal). And PayPal Standard is quite old and outdated payment method. 

So let's move it to our [marketplace](https://www.nopcommerce.com/en/marketplace). Of course, it'll be upgraded and supported. But available for download on our marketplace only

**Comment by PerseusTheGreat** [comment]
Hi,
When v4.6 will be available on marketplace?
Currently v4.5 is available.

**Comment by AndreiMaz** [comment]
Most probably, today
