### ISSUE TITLE
Dynamic Social Media Links

### ISSUE THREAD

**Issue by xmenxwk** [nopSolutions/nopCommerce#6420]
nopCommerce version: 4.50.4

Instead of having hard coded options for social media, like Facebook, Youtube and Twitter. There should be a list where you can add or remove the links having image url/id, link and name. So you can add any other social media as well or remove.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion, wbut we're leaving it for customization now. The only option we can consider now is having more options (social networks to be entered in admin area)
