### ISSUE TITLE
Restrictions over Plugins

### ISSUE THREAD

**Issue by xmenxwk** [nopSolutions/nopCommerce#6421]
nopCommerce version: 4.50

with current setup of plugins, there is no restrictions over them. Most plugins code is protected, which is understandable. But there is no way to know what a plugin is doing behind. It could be stealing important data. There must be a list of permissions that can be asked by plugins and that list is shown before installing. A simple plugin must not have all the access to data. A payment plugin must not have access to customers list or all the orders list. It should be something like android, whenever installing an app, it used to show what permissions the app will require.

**Comment by glhays** [comment]
Please define most plugins? Out of the box plugins are open source.


________________________________
From: xmenxwk ***@***.***>
Sent: Monday, November 21, 2022 7:31:41 PM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Restrictions over Plugins (Issue #6421)


nopCommerce version: 4.50

with current setup of plugins, there is no restrictions over them. Most plugins code is protected, which is understandable. But there is no way to know what a plugin is doing behind. It could be stealing important data. There must be a list of permissions that can be asked by plugins and that list is shown before installing. A simple plugin must not have all the access to data. A payment plugin must not have access to customers list or all the orders list. It should be something like android, whenever installing an app, it used to show what permissions the app will require.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we do not plan to complicate nopCommerce by adding this extra level of redundant permissions. We can only recommend you asking your plugin vendors to share source code with you (if you have any doubts)

P.S. Most plugins on our marketplace are available with sourcode code
