### ISSUE TITLE
Add sync version of methods (used during migration)

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#6422]
nopCommerce version: 4.50

We constantly use methods such as IlocalizationService.AddOrUpdateLocaleResourceAsync, IsettingService.SettingExistsAsync, IsettingService.SaveSettingAsync and others in migrations. However, migrations are performed synchronously, so it makes sense to add synchronous versions of commonly used methods

**Comment by skoshelev** [comment]
Closed #6422

**Comment by kava81** [comment]
Good morning, I need help.

I've been having this error on Azuer App service for a few days.

I'm on 4.5 and currently can't upgrade to a later release.

Do you think the changes made in this commit could help me, or at least prevent problems?

We captured the process's thread stack when it was in a suspended state and identified that 30 threads are most likely mixing synchronous and asynchronous code. The code calls Task.Result and is synchronously waiting for the Task object, which can lead to deadlocks in the process. The function that calls Task.Result is Nop.Web.Framework.Infrastructure.NopStartup+<>c__DisplayClass0_0.<ConfigureServices>b__2(System.IServiceProvider), but you need to examine the entire thread call stack to identify the blocking pattern.

I'd specifically look for those related to these files:

IStartupTask
NopEngine
ITTypeFinder
WebAppTypeFinder
DigitareConverterRegistrationStartUpTask
AppDomainTypeFinder: deleted

Thanks

**Comment by RomanovM** [comment]
@kava81 
>Do you think the changes made in this commit could help me, or at least prevent problems?

Probably yes
