### ISSUE TITLE
Add persian calendar and datetimepicker

### ISSUE THREAD

**Issue by MehdiNaz** [nopSolutions/nopCommerce#6426]
nopCommerce version: 
4.6
Steps to reproduce the problem: 
Please add the persian calendar

**Comment by Joshimar1** [comment]
Hello @MehdiNaz I would like to work on this issue. What information do I need when running the program so that i can access the nopCommerce store?

**Comment by MehdiNaz** [comment]
hi 
nuget for persian calendar :
https://github.com/Mds92/MD.PersianDateTime

https://www.nuget.org/packages/MD.BootstrapPersianDateTimePicker

https://www.nuget.org/packages/MD.PersianDateTime.Core

**Comment by Farshidgolkarihagh** [comment]
This will be very useful.

**Comment by hassanelsherbiny** [comment]
@MehdiNaz 
do you think it's only related to  date pickers or dates should be displayed  in Persian also?

**Comment by MehdiNaz** [comment]
The date must be displayed in Persian

**Comment by hassanelsherbiny** [comment]
@MehdiNaz that's what i thought too, i believe it's easy to add the pickers since there is a date editor templates, the problem is displaying dates as you cannot locate all places where dates are used.
anyway i can start by adding date picker , we may also add hijri date pickers too, and let user decide the type of dates in settings

**Comment by MehdiNaz** [comment]
It is great and practical to start with

**Comment by MehdiNaz** [comment]
> @MehdiNaz that's what i thought too, i believe it's easy to add the pickers since there is a date editor templates, the problem is displaying dates as you cannot locate all places where dates are used. anyway i can start by adding date picker , we may also add hijri date pickers too, and let user decide the type of dates in settings

It is great and practical to start with

**Comment by MehdiNaz** [comment]
> @MehdiNaz that's what i thought too, i believe it's easy to add the pickers since there is a date editor templates, the problem is displaying dates as you cannot locate all places where dates are used. anyway i can start by adding date picker , we may also add hijri date pickers too, and let user decide the type of dates in settings

It is great and practical to start with

**Comment by exileDev** [comment]
We've removed Kendo UI, so the standard datepicker one is now used (`datetime-local`). We leave other specific variations for customization.
Closed #6426

![rtl-date-picker](https://github.com/nopSolutions/nopCommerce/assets/17047105/e9492951-07f0-4f90-895b-9831ef125ccb)
