### ISSUE TITLE
Add support for associating predefined product attribute values with products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#643]
Would it be possible for you to add support for associating predefined product attribute values with products, like you can do with product attributes added in the product. 

The predefined product attribute values look like this (http://imgur.com/38ApQhb) 

And i want the option to associate them, like you you can do in the specific product configurations, see this (http://imgur.com/2sraPIJ) 

Source: http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=3#158055

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by AndreiMaz** [comment]
we use copy product for such purposes
