### ISSUE TITLE
Could not find assembly of plugin (during plugin installation)

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#6431]
nopCommerce version: 4.30, probably newer too. Have not checked

**Steps to reproduce the problem:** 

Have two plugins A & B
Plugin A depends on plugin B 

1. Install plugin B
2. Install plugin A, but make sure during installation plugin A fails to install. Now it remains in the PluginNamesToInstall property of plugins.json
(Potentially here, you might also need to have a reference to the assembly of  plugin B, in the installation process of plugin A.)
4. Uninstall plugin B
5. Crash (could not find assembly of "plugin B")

**Workaround** , modify plugins.json and remove plugin A from PluginNamesToInstall 

**Proposed Fix**, when uninstalling a plugin, cleanup PluginNamesToInstall of any plugins that depend on it. Or, rather, remove any failed installation plugin from PluginNamesToInstall on failure to install. 

Edit: Might be a similar problem with combinations of PluginNamesToUninstall but have not tested this

**Comment by skoshelev** [comment]
Hi @alinmircea 
Starting with version 4.30, nopCommerce introduced a mechanism to control how plugins depend on each other. Here is the description of the DependsOnSystemNames parameter from the [official documentation](https://docs.nopcommerce.com/en/developer/plugins/plugin.json.html)
`DependsOnSystemNames - The list of plugins' system names that this plugin depends on.`
Indicate in your plugin A that it depends on plugin B and this guarantees its presence during installation and will not allow you to remove plugin B while plugin A is installed

Closed #6431
