### ISSUE TITLE
Issue in checkout billing address selection

### ISSUE THREAD

**Issue by sk5202** [nopSolutions/nopCommerce#6434]
nopCommerce version:  4.60 beta

Steps to reproduce the problem: 

1. Add any product to card
2. Edit existing billing address and play with country and state selection. on page load country state selection is working fine but after update address it is not working well.
3. moreover existing address selection dropdown disappear sometime after edit address due to country, state cascading dropdown issue. 

here is testing video https://www.loom.com/share/1efd822e4f3b41bf8f50bcbe533b72a5

**Comment by exileDev** [comment]
Closed #6434
