### ISSUE TITLE
Unable to run nop46beta source code project with visual studio

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#6435]
nopCommerce version: 46beta

Steps to reproduce the problem: 

Download 46beta source code and run in visual studio

![image](https://user-images.githubusercontent.com/10364140/206361424-aa6e23c3-4f2c-42d9-8c70-349a1e27283f.png)

**Comment by exileDev** [comment]
@sangeetshah I couldn't reproduce. Try to remove obj/bin directories in each solution project and start over

**Comment by exileDev** [comment]
Couldn't reproduce. Closed #6435

**Comment by sangeet-shah** [comment]
@exileDev I have remove all project's bin/obj file but still getting same error message. Can you please download source code project from nopcommerce site then try to run time. I think you will also get the same issue

**Comment by skoshelev** [comment]
Hi @sangeet-shah. I also could not repeat the problem you described, at least without additional information we cannot assume anything. And still no one joins this ticket with a similar problem, which is quite strange. Please, try to unpack the sources to another directory, delete the bin and obj directories, then open the studio and run the site
