### ISSUE TITLE
Product detail page on videos not display

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6438]
nopCommerce version: nopCommerce 4.60-beta

Steps to reproduce the problem: 
Step 1: Add Embed video URL on admin side
Step 2:  Display product detail page on Page Not Found in iframe of video.

https://prnt.sc/cit0iHvJ_fKx

**Comment by chiragshivaaysoft** [comment]
Hi @SagarKayasth-NopAdvance 
my side it is working
Please see https://prnt.sc/lAxOhQ1ALiVu

**Comment by SagarKayasth-NopAdvance** [comment]
Hello @chiragshivaaysoft 
Please review this issue then after you can reproduce it.
https://github.com/nopSolutions/nopCommerce/issues/6437

**Comment by skoshelev** [comment]
If you enter the URL of the video, then everything works as expected

Closed #6438

**Comment by SagarKayastha** [comment]
Hello @skoshelev
Yes, When i added the URL of the video, Then it is working fine. But I think when we enter only embed code then we need to handle this type of error.
Thank you.

**Comment by SagarKayastha** [comment]
Hello @skoshelev
Yes, When i added the URL of the video, Then it is working fine. But I think when we enter only embed code then we need to handle this type of error.
Thank you.
