### ISSUE TITLE
Missing fields to add picture in product

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6439]
nopCommerce version: nopCommerce 4.60-beta

Steps to reproduce the problem: 
Step 1: Go to product edit page
Step 2: Go to Multimedia panel
Step 3: Select Picture tab
Step 4: Only see picture upload box. Not see Title, Alt and display order textbox.
https://prnt.sc/frZ-4f06cP3N

**Comment by skoshelev** [comment]
Hi @SagarKayastha. This is by design, you can edit the required fields in the table after uploading. We have changed the behavior of this module in favor of loading multiple images at once

**Comment by SagarKayastha** [comment]
Thank you @skoshelev for correct me.
