### ISSUE TITLE
Filter categories based on which ones are published or not published

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#644]
There are a couple of things that would make managing product categories easier. The first would be the ability to publish or un-publish categories directly from the category list view. The second would be the ability to filter categories based on which ones are published or not published. 

Source: http://www.nopcommerce.com/boards/t/38903/enhancement-request-better-product-category-management.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
