### ISSUE TITLE
reCAPTCHA added to guest checkout not working properly

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#6448]
nopCommerce version: 460beta

Steps to reproduce the problem: 

Checkout as guest and last step of checkout user can see the captcha option but its not working.

![image](https://user-images.githubusercontent.com/10364140/206383288-23adbeec-2003-455c-b8db-bc86a1f66a62.png)

I have configure properly recaptcha from admin panel and try to use this feature but I unable to go further. I have checked repatcha but still confirm button is disabled

**Comment by exileDev** [comment]
Works fine. Looks like reCAPTCHA is configured for testing https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
