### ISSUE TITLE
Multi-step checkout in pickup point select on get error message in new address

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6449]
nopCommerce version: nopCommerce 4.60-Beta

Steps to reproduce the problem: 
Step 1: Go to Admin => Configuration => Settings => Order Settings
Step 2: Disabled **Use one page checkout** Checkbox
Step 3: Add Product into cart and click on Checkout button
Step 4: Unchecked **Ship to the same address** checkbox on billing step and click on continue button
Step 5: Checked **Pickup** checkbox and click on next button
Step 6: You can see new address required message (validation)

https://prnt.sc/dAde56XGtBIl

**Comment by skoshelev** [comment]
Closed #6449
