### ISSUE TITLE
Add the multiple warehouses support to import/export

### ISSUE THREAD

**Issue by atiq-bs23** [nopSolutions/nopCommerce#6452]
nopCommerce version: All (4.4, 4.5)

Steps to reproduce the problem: 
1. Add multiple warehouse
2. Add different stock quantity for each warehouse
3. Export the product
4. You will get the wrong StockQuantity and WarehouseId

See below images:

![image](https://user-images.githubusercontent.com/113086917/206452096-fa9cb7b0-fad9-400e-9d23-d8e63c232094.png)

![image](https://user-images.githubusercontent.com/113086917/206453319-b1ddf663-c99e-4102-8cbf-7de0815fc629.png)

**Comment by skoshelev** [comment]
Hi @atiq-bs23. Currently import/export does not support multiple warehouses. The column displays information from the warehouse to which the product was linked without the option of multiple warehouses

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
