### ISSUE TITLE
SVG image support #508

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6453]
nopCommerce version: nopCommerce 4.60 -Beta

Steps to reproduce the problem: 
Step 1:  Upload SVG images on product edit page.
![MicrosoftTeams-image (42)](https://user-images.githubusercontent.com/82799708/206641243-181a6e70-eb66-4c83-928e-d481d3642008.png)

Step 2: SVG file uploaded but in product deatil page in thumbnail images the svg image is showing in black color
In category page in product images slider svg image also showing in black color
![MicrosoftTeams-image (43)](https://user-images.githubusercontent.com/82799708/206641288-b5f3008d-61f3-4c84-8568-d891813852f0.png)
![MicrosoftTeams-image (44)](https://user-images.githubusercontent.com/82799708/206641292-3d39c5ff-8fdf-4490-965d-ca7ef0e2ee49.png)

Source: https://github.com/nopSolutions/nopCommerce/issues/508

**Comment by DmitriyKulagin** [comment]
Closed #6453
