### ISSUE TITLE
Unable to import order from admin panel

### ISSUE THREAD

**Issue by sangeet-shah** [nopSolutions/nopCommerce#6455]
nopCommerce version: 460beta

Steps to reproduce the problem: 
1) I am trying to import one order but I unable to import that order from import order feature.

Every time I am getting success message and I am unable to find any error log to find out what is the issue with that orders

[orders (1).xlsx](https://github.com/nopSolutions/nopCommerce/files/10195949/orders.1.xlsx)

**Comment by skoshelev** [comment]
Hi @sangeet-shah. Have you checked whether the order is added to the database? I didn't have any problems importing your file, I just changed the user GUID and set your SKU to one of the default products.

![image](https://user-images.githubusercontent.com/16875599/207099404-b9078f0b-0cde-49c1-965b-d03003d878ea.png)

**Comment by skoshelev** [comment]
Closed #6455 as not reproducible
