### ISSUE TITLE
Unable to select two language at the same time in robots.txt Disallow languages field

### ISSUE THREAD

**Issue by sangeet-shah** [nopSolutions/nopCommerce#6456]
nopCommerce version: 

Steps to reproduce the problem: 
1) Go to /Admin/Setting/GeneralCommon URL
2) Select two language in Disallow languages field of  robots.txt section and save it
3) After reload page you will find only one field is getting selected

![image](https://user-images.githubusercontent.com/75615233/206734944-56cafdeb-8344-491b-a8fc-f44a7f87b6a7.png)

**Comment by skoshelev** [comment]
Closed #6456
