### ISSUE TITLE
Session Drop Problem

### ISSUE THREAD

**Issue by ercag** [nopSolutions/nopCommerce#6457]
nopCommerce version: 4.4.0.0

Steps to reproduce the problem: 
We have a gcp environment and we use load balancer.
When the project running 1 pod everthing is normal but when we increace the pod count for example 3 sessions are dropping randomly.
We are not using Redis Cache btw.
Has anyone ever been through this before?
Ps: I know I have to ask this question at stackoverflow, but people are more helpful here.

**Comment by AndreiMaz** [comment]
Please post all questrions on our [forums](https://www.nopcommerce.com/en/boards). We use GitHub for work items only
