### ISSUE TITLE
News details page Redirect page not found after reload 

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#6458]
nopCommerce version:   4.60- Beta

Steps to reproduce the problem: 
 - Open news details page, (*) sing are missing for validation 
 - Submit new Comment without putting title and comment 
 - Now page url will change  /nopcommerce-new-release  to /News/NewsCommentAdd?newsitemid=2
 - Please Refresh Page from URL
 - You will redirect into **Page not found** page

**Comment by skoshelev** [comment]
Hi @kalpeshboghara. 

we analyzed the behavior and do not see it as a problem, even if someone wants to do this from users it will not be a problem, you can always click back in the browser and get to the news details page

Closed #6458
