### ISSUE TITLE
Images are not load on open any catalogs pages

### ISSUE THREAD

**Issue by kalpeshboghara** [nopSolutions/nopCommerce#6459]
nopCommerce version: 4.60-Beta

Steps to reproduce the problem: 
- Open any category pages, Manufacture page , Product Tag page after fresh setup 
- Page looks like : https://prnt.sc/OLd3kCS02VmK 
- After page reload again page looks like : https://prnt.sc/mGhAonbecgeX
- Above points is same for every time. like all images are perfect after page reload but last product's images will not load
- Into console show 404 error

**Comment by AndreiMaz** [comment]
Duplicated https://github.com/nopSolutions/nopCommerce/issues/6436
