### ISSUE TITLE
prevent form from submitting multiple times from client side

### ISSUE THREAD

**Issue by codemake2022** [nopSolutions/nopCommerce#6461]
nopCommerce version: 4.5 and 4.6 beta

Steps to reproduce the problem: 
news comments and product reviews, multiple clicks on the submit button will repeatedly submit the same content

![8GL_UBDGP)B9%762_ON$3GR](https://user-images.githubusercontent.com/118972158/207515092-b5d7bd62-61a7-4cf3-9bb1-1b3569f9be1d.png)

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/3873
