### ISSUE TITLE
What3words plugin. Overwrite value when updating existing addresses on checkout

### ISSUE THREAD

**Issue by bowlsey** [nopSolutions/nopCommerce#6465]
nopCommerce version: 4.6

Steps to reproduce the problem: 
Only creating a new address on checkout does the what3words address save on the order. This is not then saved to the customers address for future orders. 
Editing existing customer addresses on checkout does not save at all and wont be passed to the order.

**Comment by RomanovM** [comment]
@bowlsey Yes, now the what3words value can be specified only when creating a new address on checkout, it's not overwritten when editing.
But it's correctly saved for future orders. You can specify it once during creation of the address and it will be present in all orders to this address.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality.
