### ISSUE TITLE
Correios Plugin NopCommerce 4.5

### ISSUE THREAD

**Issue by luizfelipehh** [nopSolutions/nopCommerce#6467]
nopCommerce version: 
4.5
Steps to reproduce the problem: 
There is a plugin to this version?

**Comment by AndreiMaz** [comment]
Please see https://www.nopcommerce.com/en/correios-2

**Comment by luizfelipehh** [comment]
@AndreiMaz I've received this e-mail.

![image](https://user-images.githubusercontent.com/32314454/208413709-9f067b3b-d640-4bef-ab7a-70acc60d5ec1.png)

looks like nopcommerce Brazil does not have support for Correios plugin anymore.

Could you help me?
