### ISSUE TITLE
When installing nopCommerce and selecting Norwegian, the language sets to  NO-NN, which is wrong. It should be NB-NO

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6470]
When installing nopCommerce and selecting Norwegian, the language sets to  NO-NN, which is wrong. It should be NB-NO

Let's check https://en.wikipedia.org/wiki/ISO_3166-1

Also ensure that a valid language pack is installed in this case

**Comment by exileDev** [comment]
Closed #6470
