### ISSUE TITLE
Trim entered values

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6471]
nopCommerce version: 4.60+

Steps to reproduce the problem: Continuation of [this commit](https://github.com/nopSolutions/nopCommerce/issues/6444). It's a wrong approach to fix it this value (trim each entered value individually).

We should find a way to trim all entered values like we did in old previous version (see https://github.com/nopSolutions/nopCommerce/issues/194). That implementation doesn't work anymore. But we have to find a way to trim all entered values (in one single place)

**Comment by skoshelev** [comment]
Closed #6471
