### ISSUE TITLE
Disallow blank path is showing

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6472]
nopCommerce version: 4.60.0

Issue in both multiline text boxes
1 Disallow paths
2 Localizable disallow paths

Steps to reproduce the problem: 
1 Go to robots.txt tab in admin
2 Put cursur at last line of Disallow paths of mulitline text box
3 Press enter key multiple times
4 Click on Save
5 Navigate to robots.txt page

![1 Disallow blank path is showing](https://user-images.githubusercontent.com/96106946/208824324-86046095-86d1-4f5c-8904-b256c0a66e6d.jpg)

**Comment by RomanovM** [comment]
There is no issue. Just don't enter empty lines.
