### ISSUE TITLE
PDF invoice doesn't work for custom currencies (in debug mode)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6473]
nopCommerce version: 4.60.0

The RTM release appears to have introduced a bug. Unable to print PDF Invoice with custom currency symbol (e.g. INR or RUB). It was working fine in nopCommerce 4.60 (Beta).

The issue was introduced in https://github.com/nopSolutions/nopCommerce/issues/6464. But please note that it doesn't work in "debug" configuration only. It works without any issues in "release" configuration.

Anyway, it's better to disable exception even in the "debug" mode as well

**Comment by exileDev** [comment]
Closed #6473

**Comment by rajupaladiya** [comment]
Hi, I submitted issue with Quest PDF for INR currency sign issue.
Kindly track [this issue]( https://github.com/QuestPDF/QuestPDF/issues/663).
