### ISSUE TITLE
PDF invoice should support all currencies 

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6475]
nopCommerce version: 4.60.0

It's continuation of https://github.com/nopSolutions/nopCommerce/issues/6473. We should find a way to support all glyphs (currencies, chars, etc). For example, find a new font (with a license that allows it to be included in an open-source project)

If a font cannot be found, then let's close this task and leave it for store owners to find appropriate local fonts

**Comment by exileDev** [comment]
We haven't found a good solution at the moment. We'll reopen this issue If the the opportunity arises.

Closed #6475
