### ISSUE TITLE
Error route doesn't exist in CommonController

### ISSUE THREAD

**Issue by BryceBarbara** [nopSolutions/nopCommerce#6479]
It seems like RouteProvider is registering a controller route that doesn't exist. Is this intentional? Am I missing something? There is no `Error` method on the `CommonController` or any of its parent classes.

https://github.com/nopSolutions/nopCommerce/blob/71bfc4bd54d9218b5e148546c356e3b15b7bb2bb/src/Presentation/Nop.Web/Infrastructure/RouteProvider.cs#L689-L692

**Comment by skoshelev** [comment]
Closed #6479
