### ISSUE TITLE
Improvements for having different themes (simultaneously)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#648]
Speaking of having different themes simultaneously (allow customer to select theme) , I must say that there could be done many other improvements in that direction. 
1. Theme specific resources - In some of our themes we want to change the value of the manufacturers resource to be Brands instead of Manufacturers. So if you install such a theme this resource is changed and it affect the rest of the themes. It would be great if we could have different language resources per theme (or per store).
2. Theme specific settings - Just like the store specific settings but per theme. I can give you many examples to illustrate this but it is mostly noted in the media settings, catalog settings etc.
3. Media Settings - they can vary per theme as the sizes of the images depend on the theme design i.e mediasettings.manufacturerthumbpicturesize, mediasettings.categorythumbpicturesize, mediasettings.associatedproductpicturesize etc.
4. Catalog settings - Depending again on the design you can have 2, 3 or 4 product boxes per row, so all related settings should be changed to accommodate this i.e catalogsettings.numberofbestsellersonhomepage, catalogsettings.defaultcategorypagesizeoptions, catalogsettings.defaultmanufacturerpagesize etc. 
5. Plugin settings - Not just the settings in nopCommerce could vary per theme but also any plugin settings (we have more than 12 plugins in each theme), which again could be picture size settinsg, element selectors settings etc.

For example we have customers that purchase several themes or have for example the Ultimate Theme Collection that contains 21 themes, and they want to demonstrate these themes to their clients and try to sell one of them. You can imagine what is their frustration when they switch between the themes in the public area and they have to amend so many settings, resources etc. Of course we have made this super easy for them as we have provided an option in each theme's settings page in the administration to "Reset to default (recommended) theme settings" but still they have to go into the administration and reset them and then go back to the public area and continue with their demo. Please note that not all nopCommerce users use our themes, so I can't image what these guys are doing to make a good demo and to try to impress their potential clients. 

I haven't thought about any possible implementations of these features. Maybe it could be just like the multi store settings, search for a theme specific setting first and if not found return the default setting. Anyway I am sure you can find the best possible solutions for the points above (if not for this maybe for future releases of nopCommerce). 

Source: http://www.nopcommerce.com/boards/t/38391/suggestions-for-the-upcoming-version-370.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. I would make the solution really too complex to configure - setting per store, setting per theme, etc
