### ISSUE TITLE
Missing AddComment Views

### ISSUE THREAD

**Issue by BryceBarbara** [nopSolutions/nopCommerce#6480]
It appears that there are some missing `.cshtml` files in the project. Both the `BlogController` and `NewsController` reference views that don't exist.

nopCommerce version: 4.5

Steps to reproduce the problem: 

1. Download the latest version of the project
2. See that `BlogAddComment.cshtml` and `NewsAddComment.cshtml` don't exist

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue. Both files exist

**Comment by RomanovM** [comment]
Possibly it's the same as #6458.

**Comment by BryceBarbara** [comment]
@AndreiMaz Are they supposed to exist here: https://github.com/nopSolutions/nopCommerce/tree/develop/src/Presentation/Nop.Web/Views/Blog ? I might be confused and I apologize if that is the case
