### ISSUE TITLE
Nop 4.6 vulnerabilities checkmarx scanning

### ISSUE THREAD

**Issue by sangeetshah** [nopSolutions/nopCommerce#6481]
nopCommerce version: 4.6

Steps to reproduce the problem: 
1) https://ast.checkmarx.net/ open this website and put zip  source code file for scanning 

I did SAST code scanning of nop commerce 4.6 code and i found a total 2146 vulnerabilities. Are we supposed to fix them or is it ok to keep them?
![image](https://user-images.githubusercontent.com/10364140/209060399-4bc31e79-93e8-409a-866c-0a54090c3074.png)
![image](https://user-images.githubusercontent.com/10364140/209060410-2376c348-21e4-43a5-8375-fbd83949a346.png)

**Comment by loid345** [comment]
Many libraries are outdated (jqery, kendo-ui, etc).  Therefore, there are many vulnerabilities.

**Comment by exileDev** [comment]
All these "vulnerabilities" aren't dangerous in the real cases. In general, most of them related to dependencies that aren't used directly. Remaining part isn't entirely correct. We update packages as soon as they are released.

Closed #6481
