### ISSUE TITLE
Allow the user to enable "required" for the "state" dropdownlist 

### ISSUE THREAD

**Issue by luizfelipehh** [nopSolutions/nopCommerce#6483]
nopCommerce version: 
4.5
Steps to reproduce the problem: 
I would like to set "Required" to field "state" on costumer config.
![image](https://user-images.githubusercontent.com/32314454/209154931-cffd5bb4-513d-4f02-91df-e558f0ece1d4.png)

**Comment by AndreiMaz** [comment]
Very often a list of states is empty for some countries. That's why we've deciced to skip "required" option for this input

**Comment by AndreiMaz** [comment]
Please see comment by Maksim at https://github.com/nopSolutions/nopCommerce/issues/5566 (duplicated)

**Comment by luizfelipehh** [comment]
But the question is, create a option to edit this field as set "required" only if the user would like.

What do you think about ? @AndreiMaz

**Comment by AndreiMaz** [comment]
@luizfelipehh Do you mean allow a store owner to make it optional?

**Comment by luizfelipehh** [comment]
@AndreiMaz Exactly! We have a scenario where the store owner would like to set the field state as required.

**Comment by AndreiMaz** [comment]
@luizfelipehh But it's already required, you have to choose some state (when states are available for selection)

**Comment by luizfelipehh** [comment]
@AndreiMaz Is not required. 

Nop 4.5 we have an option just to enable the field. 

How can I set the required?
