### ISSUE TITLE
Estimate Shipping Errors not showing

### ISSUE THREAD

**Issue by rodoflho** [nopSolutions/nopCommerce#6484]
nopCommerce version: 4.50.3
Steps to reproduce the problem: 
Errors provided by the Property Error in GetShippingOptionResponse is not being shown in frontend.

In Nop.Services.Shipping.GetShippingOptionsResponse:
```csharp
        /// <summary>
        /// Gets a value indicating whether request has been completed successfully
        /// </summary>
        public bool Success => !Errors.Any();
```

It says that Success is only True when there are no Errors.
But:

On Nop.Web.Factories.ShoppingCartModelFactory:
```csharp
 var getShippingOptionResponse = await _shippingService.GetShippingOptionsAsync(cart, address, customer, storeId: store.Id);
                if (getShippingOptionResponse.Success)
                {
                    if (getShippingOptionResponse.ShippingOptions.Any())
                    {
                        foreach (var shippingOption in getShippingOptionResponse.ShippingOptions)
                        {
                            rawShippingOptions.Add(new ShippingOption
                            {
                                Name = shippingOption.Name,
                                Description = shippingOption.Description,
                                Rate = shippingOption.Rate,
                                TransitDays = shippingOption.TransitDays,
                                ShippingRateComputationMethodSystemName = shippingOption.ShippingRateComputationMethodSystemName
                            });
                        }
                    }
                    else
                    {
                        foreach (var error in getShippingOptionResponse.Errors)
                            model.Errors.Add(error);
                    }
                }
```

So
The errors will only add when if (getShippingOptionResponse.Success) is True
But Success indicate no errors.
When Success is False, the code that add the errors will not execute.

This is causing estimate Shipping Errors not showing on estimateshipping popup.
Thx

**Comment by glhays** [comment]
I am not sure I follow your logic on this. I only inquire as I am currently working in my sites shipping config. If there are errors in the Errors list then no success! Have you assured that you have errors and there not being returned to the EstimateShipping routines?

**Comment by RomanovM** [comment]
You are right, there is wrong `else`. The bug is probably introduced in one of the merge commits.
