### ISSUE TITLE
Upload Multiple Picture UI is messed up

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#6485]
nopCommerce version: 4.60

Steps to reproduce the problem: 
Go to Admin > Product List > Product Edit
Upload multiple images from in Multimedia and check UI.

https://prnt.sc/x_YG8VPshb68

**Comment by DmitriyKulagin** [comment]
@rajupaladiya What do you mean by "UI is messed up"? A list of uploaded images is displayed so that it is convenient to keep track of which ones have been added and which have not (for various reasons). Or do you want this information not to be displayed at all?

**Comment by rajupaladiya** [comment]
@DmitriyKulagin - if there some space between each image name line then it wo
![pictures](https://user-images.githubusercontent.com/13154058/209925562-d53de9e0-4694-446a-8b9f-fd500ebcbabd.png)
uld be good

**Comment by DmitriyKulagin** [comment]
That's how it's designed.
