### ISSUE TITLE
RemoteIpAddress always "127.0.0.1"

### ISSUE THREAD

**Issue by Hao80617** [nopSolutions/nopCommerce#6486]
nopCommerce version: 
the latest

Steps to reproduce the problem: 
I added below codes to get the RemoteIpAddress.
```httpContext.Connection.RemoteIpAddress?.MapToIPv4().ToString();```

but,the RemoteIpAddress was always 127.0.0.1.

I followed the advice from : 
https://github.com/aspnet/IISIntegration/issues/140
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

I modified code as below :
```
public static void UseNopProxy(this IApplicationBuilder application)
        {
            var appSettings = EngineContext.Current.Resolve<AppSettings>();

            if (appSettings.Get<HostingConfig>().UseProxy)
            {
                var options = new ForwardedHeadersOptions
                {
                    //ForwardedHeaders = ForwardedHeaders.All,
                    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
```

Then, I can get the accurate RemoteIpAddress now.

**Comment by exileDev** [comment]
Couldn't reproduce
