### ISSUE TITLE
Discount coupon with 1 time limitation using only can be used many times!

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6487]
nopCommerce version: all versions

Steps to reproduce the problem: 
1- Create a discount coupon with code Test, set the discount limitation to N times only with value 1.
2- Open 2 browsers as a guest for each one OR (login with one browser and guest on the other one).
3- Add product on each browser
4- Apply the promo code on each browser.
5- Complete the checkout and stop at final step on each browser.
6- Now, the 2 browsers are waiting the final click to confirm the order and the promo code is applied on each one.
7- Click submit on the first browser, the order is placed and the coupon is applied.
8- Click submit on the second browser, the order is placed also and the coupon is applied!

This is because NopCommerce doesn't validate the coupon at final step (at submit step).

**Comment by glhays** [comment]
Can you share your Test discount complete setup details? Or is it just a default with only the N-Times settings set to N times only and N times =1?

**Comment by ahmadkq** [comment]
@glhays Just a default with only the N-Times settings with N times = 1. We have 2 issues here, first issue is when the second browser submit his order, the coupon will not be applied and the order will be placed without the discount with no notification for the customer as i found the source code will found the discount couonp is already used, and it will be just ignored without any alert.

Second issue, if you submitted the orders (2 orders) at the same time, the coupon will be applied for the 2 orders! I believe we need to lock the part of code where the order is placed, what do you think?

**Comment by glhays** [comment]
I think your not sharing the complete details of your discount settings, I am just trying to see if this issue effects my live site.

**Comment by ahmadkq** [comment]
> I think your not sharing the complete details of your discount settings, I am just trying to see if this issue effects my live site.

Just create a discount with following details:

1- Based on total order.
2- amount is 10
3- Coupon is required, name it "Test"
4- Set the limitation type of "N times only" and value is 1

**Comment by skoshelev** [comment]
hi, @ahmadkq. I checked the behavior you described, but there is no problem with reusing the discount, the coupon is simply reset for the second payment.

We need to add a check at the order confirmation stage and display a message to the user that someone else managed to use this discount, it’s not entirely correct to simply cancel the discount

**Comment by ahmadkq** [comment]
@skoshelev This is one of the issues. Second issue as i descriped before, when 2 customers uses the same discount wiht 1 N time limitted usage AT SAME TIME EXACTLY. Have you tried it?

**Comment by AndreiMaz** [comment]
@ahmadkq What do you mean by the exact time? The same millisecond? If yes, there's no way to "fix" it other than locking the website until an order is processed (placed, payment is processed, etc). So we cannot fix it.

You can apply the lock on your website if it's critical. But we won't do it out of the box because it'll reduce performance for all other users

**Comment by skoshelev** [comment]
@ahmadkq I tested in two browsers and hit the confirm button as fast as I could. None of the 3 attempts resulted in the behavior you describe.

**Comment by ahmadkq** [comment]
> @ahmadkq What do you mean by the exact time? The same millisecond? If yes, there's no way to "fix" it other than locking the website until an order is processed (placed, payment is processed, etc). So we cannot fix it.
> 
> You can apply the lock on your website if it's critical. But we won't do it out of the box because it'll reduce performance for all other users

@AndreiMaz I totaly agree with you that this will affect the performance. I am wondering if you have any solution for this as in our website eShop.jo.zain.com facing this issue when there is a load on the website. I came up with 2 solutions, the first one as you mentioned to lock the place order and the second one to create a queue so the real place order will be done by a schedule job but this will not be a good customer expirence. Any more ideas?

**Comment by ahmadkq** [comment]
> @ahmadkq I tested in two browsers and hit the confirm button as fast as I could. None of the 3 attempts resulted in the behavior you describe.

@skoshelev Try to someone help you to open the website in his laptop and you both click at the same time.

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
