### ISSUE TITLE
Column 'Name' not automapped for AttributeValueModel 

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#6489]
nopCommerce version: 4.60

Steps to reproduce the problem: 

Was importing some products and in the process had to use entity.ToModel<ProductAttributeValueModel<>();
Encountered "MySqlException: Column 'Name' cannot be null"

Looks to be because of ignoring the Name property during automapping:

Line 605 of Nop.Web.Areas.Admin.Infrastructure.Mapper.**AdminMapperConfiguration**

`.ForMember(model => model.Name, options => options.Ignore())`

Oversight or is there something I'm missing?

Workaround: reassign value of name after automapping.

**Comment by skoshelev** [comment]
Hi @alinmircea. As I understand it, your own code is causing the problem, since in our import we do not create models and do not cast them to the object. You have specified everything correctly, the Name property is ignored in the automapper and must be initialized separately
