### ISSUE TITLE
Consider overload for AddProductAttribute

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#6491]
nopCommerce version: 4.60

**To consider**

In the context of Nop.Services.Catalog,ProductAttributeParser -> AddProductAttribut, of interest is the product attribute value, not the mapping. Values are what make up combinations

In the current implementation, passing in the incorrect value can lead to unwanted behaviour.

Please consider overloading the current method, to ensure value is the focus point:

Current Method:
`public virtual string AddProductAttribute(string attributesXml, ProductAttributeMapping productAttributeMapping, string value, int? quantity = null)
`

Overload like this or similarly:
```
public virtual string AddProductAttribute(string attributesXml, ProductAttributeValue productAttributeValue, int? quantity = null)
{
            return AddProductAttribute(attributesXml, productAttributeValue.ProductAttributeMappingId, productAttributeValue.Name, quantity);
}

[Obsolete("AddProductAttribute(string, ProductAttributeMapping, string, int?) is deprecated, please use the other available overloads.")]
public virtual string AddProductAttribute(string attributesXml, ProductAttributeMapping productAttributeMapping, string value, int? quantity = null)
{
            return AddProductAttribute(attributesXml, productAttributeMapping.Id, value, quantity);
}

**protected** virtual string AddProductAttribute(string attributesXml, int productAttributeMappingId, string value, int? quantity = null)
{
        .... exiting code here...
}
```

I submitted this before doing any kind of testing, it's more of a "it feels wrong" than a "it is wrong', It might be that string value is the Id of the PoructAttributeValue instead of the actual string name. Please take 15 minutes to see if there is something to improve here, semantically something feels backwards here.

**Comment by RomanovM** [comment]
The complexity of all possible changes in the attribute system is that it will be difficult to update the data that users already have in db.
If we decide to do it, then it is worth globally revising all the attribute storage/mappings (e.g. #2830).
