### ISSUE TITLE
Required message is not showing and Address getting remove from checkout page

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6492]
nopCommerce version: 4.60.0

Steps to reproduce the problem: 
1. Add any product in cart and click on Checkout button (Customer have already address)
2. Now, Edit address from Billing address page
3. Remove any data of required filed
4. click on Save button
5. Observe that address getting remove from checkout page and save in my account > Address page without required field

Expected Result: Required message should show on checkout page and address should not save without required field 

https://drive.google.com/file/d/1YkVbQA_aM9rKavhl6fD9QKYKYF1MYVJz/view?usp=sharing

**Comment by skoshelev** [comment]
Closed #6492
