### ISSUE TITLE
Redirect on Cart page when Address delete from shipping address page and click on Edit button

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6494]
nopCommerce version: 4.60.0

Steps to reproduce the problem: 
1. Add product in Cart (As guest user/ Customer have no address)
2. click on Checkout button
3. Disable the  Ship to the same address
4. Enter Address and click on Continue button
5. Now Delete address from Shipping address tab
6. Click on Edit button
7. Observe that redirect on shopping cart page

Note: Same issue reproduce with pickup point

Expected Result: Required message should show and should not redirect on cart page

https://drive.google.com/file/d/1WpdhJkcFIuFf207SuSRbjOTDM6Ia6gFc/view
https://drive.google.com/file/d/19P8x7e9rT3AGRHEdnfLrOSchGbOC8Tbb/view

**Comment by skoshelev** [comment]
Closed #6494
