### ISSUE TITLE
MySqlConnector. Disable "XA Transactions" by default

### ISSUE THREAD

**Issue by mhartmann-cu** [nopSolutions/nopCommerce#6497]
nopCommerce version: 4.60

nopCommerce 4.60 uses the MySqlConnector instead of MySql.Data.
TransactionSocpe is used in the EntityRepository.cs:
`using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);`

The Migrating documentation for MySqlConnector states:
> MySqlConnector adds full distributed transaction support (for client code using [System.Transactions.Transaction](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transaction)), while Connector/NET uses regular database transactions. As a result, code that uses TransactionScope or MySqlConnection.EnlistTransaction may execute differently with MySqlConnector. To get Connector/NET-compatible behavior, set UseXaTransactions=false in your connection string.

Also see: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#transactionscope

--- 
We still use nopCommerce 4.50, but have modified it to use MySqlConnector like 4.60 uses it.
We do this, because we use Linq2Db with additional features, which are not supported with MySql.Data.

In our case it seems that XA Transcations are used.
For us this is not the intended behavior.
We are still looking into it, to verify this.
We will look into it in our case, with the modified version of nopCommerce 4.50.
(connection string with UseXaTransactions=false).

We were not able to test 4.60 yet.
We could not find anything like UseXaTransactions in the 4.60 code.

- Does anyone know, if 4.60 uses XA Transactions for queries with TransactionScope?
- Is this the intended behavior?

**Comment by mhartmann-cu** [comment]
I just did an additional check on an BulkInsertEntitiesAsync and the trace shows, that an XA Transaction is started:

`using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);`
`await _dataProvider.BulkInsertEntitiesAsync(entities);`
`transaction.Complete();`

> trce: MySqlConnector.SingleCommandPayloadCreator[0]
      Session1.1 Preparing command payload; CommandText: XA START 'dfdcb422-b0c6-4d9c-8b64-460cf160ed49:1', '1'

Maybe someone can check, if this is the case with nopCommerce 4.60 and if this is intentional.

**Comment by exileDev** [comment]
As mentioned above, in some cases TransactionScope is used. There is no custom settings to manage it, so MySqlConnector uses XA Transactions by default.

Closed #6497

**Comment by mhartmann-cu** [comment]
**About the configuration of XA Transactions with MySqlConnector:**
@exileDev 
What do you mean by

> There is no custom settings to manage it

The official documentation states:
> To get Connector/NET-compatible behavior, set UseXaTransactions=false in your connection string.

I checked it and this indeed works as intended.


**About XA Transactions in general:**
The question of whether the use of XA transactions for nopCommerce is intended does not seem to be answered yet.

Is there a specific use case why nopCommerce should use XA Transactions?

XA Transactions can have unforeseen ramifications.
For example XA Transactions that are stuck in a RECOVERY state and lock tables.

In this case xa recover (with for example xa rollback) has to be used, which is not really intuitive.
Finding the problem alone can be very difficult in this case.


If XA transactions are not really required, then I see them as a risk, not a benefit.
I'm not very familiar with XA Transaction SQL Statements myself, so any explanation or justification would be appreciated.

Thank you

**Comment by exileDev** [comment]
Closed #6497. We've disabled it in the connection string, but only for new connections during installation. This option isn't required for nopCommerce
