### ISSUE TITLE
Random empty statement in Nop.Web.Framework.Validators.ValidatorExtensions

### ISSUE THREAD

**Issue by roughiain** [nopSolutions/nopCommerce#6498]
nopCommerce version: 4.6.0

Nop.Web.Framework.Validators.ValidatorExtensions

Line 80: Random empty statement

```
   ;
```
https://github.com/nopSolutions/nopCommerce/blob/31dda5d5c9521301207d1695aff03743ed9eee73/src/Presentation/Nop.Web.Framework/Validators/ValidatorExtensions.cs#L80

**Comment by skoshelev** [comment]
Closed #6498
