### ISSUE TITLE
Do not use DotNetOpenAuth . Use other library for Facebook extnernal authentication plugin

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#65]
DotNetOpenAuth is almost not supported anymore by its original developers. Please have a look at http://blogs.msdn.com/b/webdev/archive/2014/10/10/announcing-microsoft-aspnet-facebook-1-1-rtm.aspx . We should use Facebook.dll (like it was done in version 2.80) 

We also should find some other library instead of DotNetOpenAuth for "ExternalAuth.OpenId" 

[UPDATE] Looks like it's again supported - https://github.com/DotNetOpenAuth/DotNetOpenAuth

Let's discuss whether it should be done

**Comment by suddenelfilio** [comment]
Again look at IdentityServer to handle this for you
