### ISSUE TITLE
Create "GetAvailableBilling" and "ShippingAddresses" methods

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#650]
I have an suggestion of moving this code into a Service Method (eg. Address or Checkout Service) 
In this way its easier to override the Service for more advanced address "validations" or filter. 

In my case, I want to limit address to only be billing or shipping address. 

CheckoutController.cs

```
protected virtual CheckoutBillingAddressModel PrepareBillingAddressModel(int? selectedCountryId = null, 
        bool prePopulateNewAddressWithCustomerFields = false)
{ 
...
        var addresses = _workContext.CurrentCustomer.Addresses
            //allow billing
            .Where(a => a.Country == null || a.Country.AllowsBilling)
            //enabled for the current store
            .Where(a => a.Country == null || _storeMappingService.Authorize(a.Country))
            .ToList();
... 
} 
```

```
SomeService.cs 
IList<Address> GetAvailableBillingAddresses(Customer customer); 
IList<Address> GetAvailableShippingAddresses(Customer customer); 
```

I also think this is better design of the application to put more logic into services =) 

Source: http://www.nopcommerce.com/boards/t/38340/suggestion-getavailablebillingshippingaddresses.aspx

**Comment by AndreiMaz** [comment]
already done with factories
