### ISSUE TITLE
What3Words.csproj contains illegal character which stops VSMac from loading project

### ISSUE THREAD

**Issue by roughiain** [nopSolutions/nopCommerce#6500]
nopCommerce version: 4.6.0

[Extra char line 17](https://github.com/nopSolutions/nopCommerce/blob/88132eaba6338096bbeed657e05ee98612f19eff/src/Plugins/Nop.Plugin.Widgets.What3words/Nop.Plugin.Widgets.What3words.csproj#L17)

Steps to reproduce the problem: 

Open the file in vscode to see the issue

![image](https://user-images.githubusercontent.com/19661735/209937520-2891dbf7-7f8e-46e3-971a-3900e398def9.png)

![image](https://user-images.githubusercontent.com/19661735/209937821-549a8dc5-11b5-4f7c-9435-d1e1199cda2f.png)

```
Error while trying to load the project '/Users/iainrough/ RiderProjects/NopCommerce/ src/Plugins/
Nop.Plugin.Widgets.What3words
Nop.Plugin.Widgets.What3words csproj': Text content is not allowed inside a Project element / Users/iainrough/RiderProjects/ NopCommerce/src/Plugins/Nop.Plugin.Widgets.What3words
Nop.Plugin.Widgets.What3words.csproj
```

**Comment by DmitriyKulagin** [comment]
Closed #6500
