### ISSUE TITLE
NullReferenceException Error is showing when direct click on Upload button(without upload any avatar image)

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6502]
nopCommerce version: 4.60.0

Steps to reproduce the problem: 
1. Enable the Allow customers to upload avatars from Admin > Configuration > Settings > Customer Setting
2. Now Redirect on Public side Myaccount > Avatar > Click on Upload button (without upload any avatar image)
3. Observe that NullReferenceException error is showing

Can you please refer attachment

![image](https://user-images.githubusercontent.com/121164051/210033912-f8c8268d-e3f0-460b-a8d3-6a428201186a.png)

**Comment by skoshelev** [comment]
Closed #6502
