### ISSUE TITLE
Redirect home page to 302 instead of 301

### ISSUE THREAD

**Issue by beljk** [nopSolutions/nopCommerce#6504]
nopCommerce version: 4.5

Steps to reproduce the problem: 
I am using two languages and when open domain.com it's redirect to domain.com/en with status code 302 not 301 ..
how to change this redirection to be  Permanent Redirect 301 instead of 302
Check screenshot belw
![redirect 302](https://user-images.githubusercontent.com/9088199/210128742-d801df35-2dd7-4efc-8f8b-b82d6db685ae.png)

**Comment by AndreiMaz** [comment]
Please post all questions on our [forums](https://www.nopcommerce.com/en/boards). We use GitHub for wokr items only
