### ISSUE TITLE
Problem with deleting a store from a multi store nop instance 

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#6505]
nopCommerce version: 4.50.4 (but I believe it happens on all versions so far).

Steps to reproduce the problem: 

So at the beginning,  we only have 1 store configuration.  Later, we add another store with different themes, configurations etc.

So that is, Store 1, and Store 2, both shared the same set of plugins we developed. When we added Store 2 later, we enabled the "Multi-store configuration for" function,  

![image](https://user-images.githubusercontent.com/2167369/210159321-7836fb28-3cbd-446d-8046-266c1976e407.png)

So now for the plugin's configuration, we have 3 different versions:
1. The original "old" version when we only have 1 store.
2. The  "new" version for Store 1 when we added Store 2.
3. The    version for Store 2 

Then we decided to separate the two stores because of performance issue, so we deployed Store 2 to a new server. Now we left a "off line" Store 2 in Store 1's server, and we decided to delete obsolete Store 2.

Unfortunately bad things happened when we decide to to it on live server directly:

1. All the plugins' configuration fell back to the original "old" version when we only have 1 store (instead of staying untouched, because we have the latest configuration for Store 1).
2.  Store 1 lost its theme configuration,  and just use Nop's default "clean theme".
3.  Not sure about other problems as we are still trying to recover from the disaster.

Clearly there is something wrong here.

**Comment by AndreiMaz** [comment]
It's by design. When you have only one store, the default configuration is used

You can change this behaviour by writing SQL statement (should be run only once) that will replace all [Value] column in the [Setting] table by new ones with [StoreId] set to your store 1
