### ISSUE TITLE
Full page caching

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#651]
More info at http://www.nopcommerce.com/boards/t/17861/full-page-caching-in-nopcommerce.aspx

Let's discuss. Certain suggestions?

**Comment by AndreiMaz** [comment]
After discussion and investigation we've decided to ignore this task:

1. Usage of additional services (such as Varnish, Squid, etc) would be possible only on dedicated services. And it's not a way to go in 99% cases. So it won't help most of our users
2. Usage of other caching mechanisms (such as Cache API, Service Worker, PWA) is a way too complex right now. And it'll definitely increase a learning curve for new users
3. We prefer the following ways to go - https://github.com/nopSolutions/nopCommerce/issues/3244 and https://github.com/nopSolutions/nopCommerce/issues/159 and https://github.com/nopSolutions/nopCommerce/issues/239
