### ISSUE TITLE
Unable to generate attribute combination with File upload attribute

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6510]
nopCommerce version: All

Unable to generate attribute combination with File upload attribute

Steps to reproduce the problem: 
1 Add Product attributes with file upload attribute
2 Oberve file upload attribute in Generate several attribute pop up
3 Also Oberve file upload attribute in Generate all possible combinations 

![Unable to generate attribute combination with File upload attribute](https://user-images.githubusercontent.com/96106946/210340469-87c2915b-2f57-459e-80a2-6ce12cc5405f.jpg)

**Comment by skoshelev** [comment]
Hi, @JayPatel7348. Please note the warning in the attribute combinations tab: 
`Note that some attribute control types that support custom user input (e.g. file upload, textboxes, date picker) are useless with attribute combinations`
