### ISSUE TITLE
Exception when upgrade from 4.50.4 to 4.60 from source code with mysql database

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#6511]
nopCommerce version: 4.50.4

Steps to reproduce the problem: 
1. Merge latest nop 4.60 source code into our own code base, and fixed all merging conflicts. (not too much conflicts as we didn't modify nop code, all our own code exists in plugins/partial classes/records etc.)
2. Rebuild solution successfully.
3. Lunch website in vs 2022 debug mode.
Then following exception occurs. 
![image](https://user-images.githubusercontent.com/2167369/210470103-7e467dfb-9ac2-4dde-8c99-0b30a736dfb1.png)
Sorry I have to disguise all sensitive information according to company's regulations.

**Comment by nextfool** [comment]
Sorry I am not sure if this is a bug, I managed to fix this by deleting all the plugins in webiste project,  and reinstalling the tax related plugin  after the upgrade. Now everything seems to work fine. If you think this is not a issue, please feel free to close it.

**Comment by RomanovM** [comment]
@nextfool The same was also discussed [here](https://www.nopcommerce.com/boards/topic/94612/database-automatic-upgrade-issue-from-4404-to-4503). Probably, some migration doesn't run correctly with the plugin installed, although we cannot reproduce this error.
