### ISSUE TITLE
Wrong validation on dates when using language 'nb-NO' on a linux web app in azure

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#6512]
nopCommerce version: 4.6

Steps to reproduce the problem: 

1. Host solution on a linux web app in azure
2. Choose Norwegian language nb-NO
3. Press button 'Set CLDR for current culture'
4. Go to product
5. Select product valid from and a date
6. Save
7. See error on top

"The value '03.01.2023 00.00' is not valid for **Tilgjengelig startdato**."

**Comment by exileDev** [comment]
Closed #6512
