### ISSUE TITLE
Wrongly assigned price value

### ISSUE THREAD

**Issue by Peter140** [nopSolutions/nopCommerce#6514]
https://github.com/nopSolutions/nopCommerce/blob/e13b99dab2969b75d624aa3ddc963b225f2835dc/src/Presentation/Nop.Web/Factories/ProductModelFactory.cs#L807

model.PriceValue = finalPriceWithDiscount; //the correct value finalPriceWithoutDiscount;

**Comment by RomanovM** [comment]
@Peter140 Why?

**Comment by Peter140** [comment]
Corect value for model.PriceValue is finalPriceWithoutDiscount

**Comment by RomanovM** [comment]
@Peter140 This is by design. You can customize it if you need another price.
