### ISSUE TITLE
EU Omnibus Directive

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6515]
Check https://www.lexology.com/library/detail.aspx?g=efc2ff9a-2c4e-4291-96cc-613670813093 and https://commission.europa.eu/law/law-topic/consumer-protection-law/unfair-commercial-practices-law/price-indication-directive_en

It's required to display the lowest price in the last 30 days on the product details page. For example, "The cheapest price XXX for the last 30 days" (display it below the main price on the product details page)

So we need to store historical prices for products, tier prices, attributes, combinations (display a minimum price based on attribute selection). Then calculate minimal price from last 30 days based on this history.

Schedule tasks will remove historical prices older than 30 days.

Source: https://www.nopcommerce.com/en/boards/topic/94258/new-ue-omnibus-directive#302482 and https://www.nopcommerce.com/en/boards/topic/96245/lowest-price-in-30-days-new-eu-law-2023

**Comment by Alerinos** [comment]
@AndreiMaz This is a very important feature for sellers in Europe. If you need help running this solution, I can help.

**Comment by d99mj** [comment]
It would be very good if this feature could be implemented in version 4.8 because of the EU law and that we that use nopCommerce must show cheapest price during last 30 days when having a product on sale. :)
