### ISSUE TITLE
Improve distributed caching

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6517]
nopCommerce version: develop

> I tried dynamodb and it has datasize limitation, I tried Redis and for 200 jmeter hit the site become unresponsive, I tried mongodb and it was a performance issue with 200-250 jmeter hit, I tried sqlserve and homepage load took 2-3min.

> By doing some r&d I understood that the less the data size will be the more it will be faster. But the architecture simply does not align with it.

> Again query caching without distributed cache is really a blocker for proper load distribution and auto-scaling.

Source: https://www.nopcommerce.com/boards/topic/95837/distributed-cache

See also: #5593

Let's find a way to improve the current approach with caching.

**Comment by skoshelev** [comment]
see this [PR](https://github.com/nopSolutions/nopCommerce/pull/6531)

**Comment by skoshelev** [comment]
Closed #6517 by [this commit](https://github.com/nopSolutions/nopCommerce/commit/2f8e5a99eb405eb507c73a69cf48d252faaa738f)
