### ISSUE TITLE
Move product reviews to a product page 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6518]
nopCommerce version: develop

> i think it's really bad solution to make seperate page with product opinions and don't show it on product page.
> 
> This is problem for people who use for example themes from nop-templates page (but i thinks it's wrong solution for 100% nopcommerce users) where opinions are on product page tab (duplicate content), also google crawler spend time on "review" page what is mistake and it's wrong SEO solution.
> 
> I think it's time to change this, remove seperate "review pages" and move it to product page with pagination. Also give there form to add opinion without "looking" how to do this... I need write to Clients instruction how it's works, so i think it's bad solution.
> 
> Then CLients spend less time to add new opinion, and more time read about products. Reviews are also important part of all ecommerce, conversion, etc. so i'm not sure why it's moved out from product page. I never see in another ecommerce similiar solution.

Source: https://www.nopcommerce.com/boards/topic/95886/remove-seperated-review-page-and-make-it-part-of-product-page

See also: #5613

**Comment by MeysamNaderi** [comment]
The page is useful when administrators send requests to customers for obtaining feedback or reviews.
while it's true that this page may lead to a higher bounce rate and negatively impact SEO, my suggestion is to relocate all comments to the product details page and implement a pop-up form for reviews, with the URL included.

**Comment by exileDev** [comment]
Closed #6518
