### ISSUE TITLE
Multiple files for Downloadable product

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#652]
now i use nopcommerce 3.6 then i need to upload multiple files for Downloadable product. how to do that. 

Source: http://www.nopcommerce.com/boards/t/38157/how-to-upload-multiple-files-for-downloadable-product.aspx

also see http://www.nopcommerce.com/boards/t/43205/feature-request-add-field-for-version-number-of-digital-products.aspx

**Comment by AndreiMaz** [comment]
duplicate 409
