### ISSUE TITLE
an option for disabling email queue and inserting in its table

### ISSUE THREAD

**Issue by Steve7394** [nopSolutions/nopCommerce#6523]
please provide some option to disable insert queued emails.
thanks

**Comment by AndreiMaz** [comment]
@Steve7394 What exactly do you mean? Please clarify.

You already can delete queue emails. You can also disable "Send emails" schedule task if you want to disable email sending

**Comment by Steve7394** [comment]
as I know in nop always insert in queue email and if disable "Send emails" schedule task the size of table increase...
and the only way for that is to delete it manually from its form or Database.
if there is way to disable inserting in email queue to prevent increasing db size

**Comment by Steve7394** [comment]
No
We dont want to sen any emails and because of that we dont want to insert any thing in queuedemail table

**Comment by RomanovM** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization.
