### ISSUE TITLE
Improving spanish (es-ES) translation during installation

### ISSUE THREAD

**Issue by Croissanito** [nopSolutions/nopCommerce#6524]
nopCommerce version: 4.60.0

File: src/Presentation/Nop.Web/App_Data/Localization/Installation/installation.es-ES.xml

Hi, this is going to be my **first pull request**, so I'm opening this issue just to follow the rules for contributing before actually making it (although it's probably not necessary in this case). I just came across this while trying the app and thought that it could be nice to improve it a little, nothing else (I ~~use Arch btw~~ am spanish btw).

**Comment by RomanovM** [comment]
@Croissanito  Thanks for your help. But we use Crowdin for localization. If you would like to contribute to localization, please visit our [translations page](https://www.nopcommerce.com/translations)

**Comment by Croissanito** [comment]
Got it, thank you for the fast response.
