### ISSUE TITLE
SendinBlue plugin. Use number type for some transactional attributes

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6527]
nopCommerce version: 4.50

> From what I can find, when Category.Enum.Transactional is created for ORDER_PRICE
> It's datatype is set to "Text"
> In the newest version of Sendinblue, text is no longer allowed for SUM[ORDER_PRICE]
> The Attribute type needs to be "Number" in their list (Or from what I can gather, float from the TypeEnum)
> After changing the ORDER_PRICE to Number, the errors went away.

Source: https://www.nopcommerce.com/boards/topic/95882/sendinblue-plugin#302825

**Comment by DmitriyKulagin** [comment]
Closed #6527

**Comment by brandon7171** [comment]
Using Brevo on 4.70.5 I still have to go and manually create two Calculated Values. Is it possible for the plugin to create these values. There are a total of three values that need to exists but only one is added by default.

NOPCOMMERCE_CA_USER
NOPCOMMERCE_LAST_30_DAYS_CA
NOPCOMMERCE_ORDER_TOTAL
