### ISSUE TITLE
Update Version Number in .csproj Files

### ISSUE THREAD

**Issue by brothers28** [nopSolutions/nopCommerce#6534]
nopCommerce version: 4.6

All your .csproj Files are still stating it's Version 4.5 instead of 4.6
https://github.com/nopSolutions/nopCommerce/blob/release-4.60.1/src/Presentation/Nop.Web/Nop.Web.csproj
https://github.com/nopSolutions/nopCommerce/blob/release-4.60.1/src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj
https://github.com/nopSolutions/nopCommerce/blob/release-4.60.1/src/Libraries/Nop.Core/Nop.Core.csproj
https://github.com/nopSolutions/nopCommerce/blob/release-4.60.1/src/Libraries/Nop.Data/Nop.Data.csproj
https://github.com/nopSolutions/nopCommerce/blob/release-4.60.1/src/Libraries/Nop.Services/Nop.Services.csproj

Is there any reason for that?

**Comment by AndreiMaz** [comment]
4.60 is already released. We'll update them in 4.70
