### ISSUE TITLE
PT Translations

### ISSUE THREAD

**Issue by luizfelipehh** [nopSolutions/nopCommerce#6538]
nopCommerce version: 
4.5 and 4.6
Steps to reproduce the problem: 
The word "description" is an English word.
Translation to "description" in PT is "Descrição".

Also, we can see below, many examples where phrases in English were not translated.

![image](https://user-images.githubusercontent.com/32314454/213199206-41bc517e-41f6-46d3-85f0-989d282afa47.png)

**Comment by AndreiMaz** [comment]
It's a language pack. YOu're more than welcome to improve this language pack. Please find more info at https://www.nopcommerce.com/translations-contribute

P.S. According to your screenshot these locales are not related to nopCommerce core. They are from a third-party plugin from nop-templates.
