### ISSUE TITLE
Edit and Delete buttons are not visible for latest address and edit delete buttons should not be displayed when pickup store is enable from shipping address step

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6540]
nopCommerce version: 4.60.1

Steps to reproduce the problem: 
1. Add Product in cart
2. Login user should have at least one address
3. Disable Ship to the same address and Select billing address then click on Continue button
4. On shipping address page only continue button is visible
5. Now, refresh the page and add new address from billing address page
6. Click on Continue button
7. Observe that Edit and Delete buttons are displayed only for old(existing)address 
8. Now, Select old(existing)address and Enable Pickup option from shipping address page
9. Observe that Edit and Delete buttons are still displayed
10. Now, click on Edit button edit address form is not opened

Expected Result:
1. Edit and Delete buttons should be displayed with latest(New) address
2. Edit and Delete buttons should not displayed when Pickup is enabled

https://drive.google.com/file/d/10H9-X7uRxUL9H5PMvQakQVyUqRYPmzGN/view?usp=share_link

**Comment by skoshelev** [comment]
Hi @Muditshah30. The Edit and Delete buttons are not shown at the stage of choosing the shipping address intentionally, since editing them will affect the billing address, which I consider as a wrong

**Comment by skoshelev** [comment]
Closed #6540
