### ISSUE TITLE
Localized customer full name

### ISSUE THREAD

**Issue by GaborFarkas** [nopSolutions/nopCommerce#6541]
nopCommerce version: 4.60

Currently nopCommerce uses the standard English convention of `{firstName} {lastName}` when generating a full name in `CustomerService#GetCustomerFullNameAsync`. As the order of the parts of the name can change between different cultures, I think it would be a nice feature to use a localized resource string with every supported language containing either `{0} {1}` or `{1} {0}`, defaulting to `{0} {1}`.

What do you think?

**Comment by skoshelev** [comment]
Closed #6541
