### ISSUE TITLE
Default svg image is scaled large at many places

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6545]
nopCommerce version: 4.60.1

Recently view image is scaled when svg default image used

Steps to reproduce the problem: 
1 Upload SVG image in /Admin/Setting/Media > Product tab > Default image
2 Dont upload main product image that you viewed recently(Make sure /Admin/Setting/Catalog > Additional section > 'Recently viewed products' enabled is checked )
3 Observe recently view product image in Grid page below Filters

attached sample svg
![209060882-aa86f707-bbdd-43f3-b1c6-c03a8485ffe3](https://user-images.githubusercontent.com/96106946/214212681-d73b83e2-7de5-4c7b-91cb-4fcff4433f17.svg)

Expected
Recently view image should Not be scaled when svg default image used

![4 Recently view image is scaled when use svg default image](https://user-images.githubusercontent.com/96106946/214212584-b3542fc2-3f10-47f6-bea3-66a8e2bc7024.jpg)

**Comment by JayPatel7348** [comment]
**Same issue on Main cart page when add Product(no product image) with default svg image**

![5 Default svg product image is scaled on cart page](https://user-images.githubusercontent.com/96106946/214214473-1eb42243-4b9b-4994-bf2a-1164ae84dd89.jpg)

**Comment by JayPatel7348** [comment]
**Same issue on search auto complete image**
svg Default image is scaled in search auto complete image

![6 svg Default image is scaled in search auto complete image](https://user-images.githubusercontent.com/96106946/214216679-da94a24f-88d4-4c4d-be19-375ed518a462.jpg)

**Comment by JayPatel7348** [comment]
**Same issue on Wishlist page**

![7 svg on wishlist page](https://user-images.githubusercontent.com/96106946/214219013-2cc149f2-eb5d-4c89-8e6b-3eb932a9e62a.jpg)

**Comment by DmitriyKulagin** [comment]
Closed #6545
