### ISSUE TITLE
HTML code is showing in PDF when checkout attribute control type is File upload

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6546]
nopCommerce version: 4.60.1

Steps to reproduce the problem: 
1. Redirect on Admin > Catalog > Attribute > Checkout attribute
2. Add new Checkout attribute with Control type is "File Upload"
3. Now, Add product in cart and upload file in Checkout attribute
4. Placed order and click on PDF invoice
5. Observe that anchor tag is shown in Order PDF

![image](https://user-images.githubusercontent.com/121164051/214257636-59902d8d-0bf5-4c9e-b04e-7b91a033646a.png)

**Comment by DmitriyKulagin** [comment]
Closed #6546
