### ISSUE TITLE
Avalara tax plugin. Add Item Classification functionality

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6547]
nopCommerce version: develop

Adding the HS Item Classification to Avatax functionality would allow customers to expand internationally

https://knowledge.avalara.com/bundle/wsz1663241599932_wsz1663241599932/page/Understand_harmonized_system_tariff_codes.html 
https://developer.avalara.com/api-reference/item-classification/v2/

**Comment by DmitriyKulagin** [comment]
Closed #6547
