### ISSUE TITLE
Export-Import issue for deleted manufacturer/category mapping 

### ISSUE THREAD

**Issue by atiq-bs23** [nopSolutions/nopCommerce#6548]
nopCommerce version: 4.5

Steps to reproduce the problem: 
1. Create a Manufacturer
2. Assign it with Product (new row insert on Product_Manufacturer_Mapping)
3. Delete the Manufacturer
4. Still the mapping is present but the Manufacturer is deleted
5. Export and then Import, it will show the ERROR (Sequence contains no element............)

I think it will do the same thing for Deleted Categories

If you need any kind of help to regenerate the issue you can contact with me (atiqur.foyshal@brainstation-23.com)

**Comment by skoshelev** [comment]
Closed #6548
