### ISSUE TITLE
Icon moves when expanding Admin menu sections

### ISSUE THREAD

**Issue by mike-warren-dev** [nopSolutions/nopCommerce#6549]
**nopCommerce version:** 

4.70.0

**Steps to reproduce the problem:** 

1) Navigate to Admin page. 
2) Watching the caret icon closely, expand the 'Configuration' section. Note that the caret rotates, but does not move/translate:
![image](https://user-images.githubusercontent.com/90517350/214605047-a289defa-4c20-4cc9-81ab-6729590c2acb.png)

3) Keep the 'Configuration' section expanded
4) Watching the caret icon closely, expand the 'Settings' section. Note that the caret rotates and moves/translates down and to the right: 
![image](https://user-images.githubusercontent.com/90517350/214605766-45daebed-e239-4c8b-bc8f-2cb04f345d46.png)

I believe I understand the cause of the issue and would be happy to submit a PR.

**Comment by AndreiMaz** [comment]
@mike-warren-dev Thanks a lot for reporting. Su,re you're more than welcome to submit a pull request

**Comment by exileDev** [comment]
Closed #6549
