### ISSUE TITLE
Length restriction on frontend inputs

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6552]
nopCommerce version: 4.60.1

All details at https://www.nopcommerce.com/en/boards/topic/96120/no-password-length-restriction-leads-to-denial-of-service

Let's investigate whether it can be used for any kind of attacks

Related work item: https://github.com/nopSolutions/nopCommerce/issues/6557

**Comment by skoshelev** [comment]
We have a method [SetStringPropertiesMaxLength](https://github.com/nopSolutions/nopCommerce/blob/b0cd05bc68ece37e0ccb3f7a3e0fef376458356c/src/Presentation/Nop.Web.Framework/Validators/BaseNopValidator.cs#L57) that allows us to set a limit on the length of the field in accordance with the length in the database. We can consider using it not only in the administration area but also in the public store. Then we just need to set restrictions in the table structure.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization because the [original work item](https://github.com/nopSolutions/nopCommerce/issues/6557) is already implemented. The issue with hashing could be reproduced there only and it's not related to other inputs (e.g. first name, etc)
