### ISSUE TITLE
Switch to Google Analytics 4 and the new measurement protocol

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6553]
Currently we use Universal Analytics. On July 1, 2023, standard Universal Analytics properties will stop processing new hits - [source](https://support.google.com/analytics/answer/10759417?hl=en)

So let's wwitch our implementation to Google Analytics 4. Mostly existing websites can be switched online as described [here](https://support.google.com/analytics/answer/9744165). But some extra development actions also could be applied as descriped [here](https://support.google.com/analytics/answer/10759417) in the "Advanced setup needs (if applicable)" section:

1. [Map Universal Analytics custom events to Google Analytics 4](https://support.google.com/analytics/answer/11091025)
2. [Migrate ecommerce measurement](https://developers.google.com/analytics/devguides/migration/ecommerce)
3. [User-ID](https://support.google.com/analytics/answer/9213390)
4. [Measurement protocol](https://support.google.com/analytics/answer/9900444)

Also implement https://github.com/nopSolutions/nopCommerce/issues/5915 when this one is finished

**Comment by DmitriyKulagin** [comment]
Closed #6553

**Comment by calvinzhouroi** [comment]
Hi, Not sure if I can comment here to ask questions. My GA4 don't have any E-commerce tracking, only have the purchase event tracking. I am having trouble following the Google migration steps. Can anyone with E-comm migration?

**Comment by RomanovM** [comment]
@calvinzhouroi It's better to post your questions on [our forums](https://www.nopcommerce.com/boards).
