### ISSUE TITLE
Add KnownNetworks support to HostingConfig

### ISSUE THREAD

**Issue by jmiller-afw** [nopSolutions/nopCommerce#6555]
When using a service such as Cloudflare for the application front door, there may be thousands of proxy IP addresses used to proxy and send the forwarded for headers.  In these cases, being able to utilize the ForwardedHeaderOptions.KnownNetworks, this would allow for the configuration using a network notation such as the following:
173.245.48.0/20
172.64.0.0/13
131.0.72.0/22

I have updated my own copy of the source code to utilize this functionality and will be submitting a pull request for you to review shortly.

**Comment by exileDev** [comment]
Closed #6555
