### ISSUE TITLE
Password length restriction leads to denial of service

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6557]
nopCommerce version: 4.60.1

All details at https://www.nopcommerce.com/en/boards/topic/96120/no-password-length-restriction-leads-to-denial-of-service

Let's add a setting with a maximum length because hashing a large amount of data can cause significant resource consumption

Related work item: https://github.com/nopSolutions/nopCommerce/issues/6552

**Comment by skoshelev** [comment]
Closed #6557
