### ISSUE TITLE
Bug in plugin dependency 

### ISSUE THREAD

**Issue by Alaa-Eddin-jo** [nopSolutions/nopCommerce#6560]
nopCommerce version: 
4.5

Steps to reproduce the problem: 
I have two plugins P1 and P2 and P2 has dependency on P1.
I installed P1 
after that installed P2
then restarted the application.
it shows error "Could not load file or assembly ...p1.dll
at Nop.Web.Framework.Infrastructure.Extensions.ApplicationPartManagerExtensions.InitializePlugins(ApplicationPartManager applicationPartManager, PluginConfig pluginConfig) "

After some investigation i found that the problem is that in the above method it tries to loud plugin regardless the dependency on other plugins.

And if we set the pluginConfig.ClearPluginShadowDirectoryOnStartup to false 
after that we do the following: installed P1 -> restart -> install P2 -> restart it will work.
also, after that if i set the  pluginConfig.ClearPluginShadowDirectoryOnStartup to true the error will show again. 

Note:
in Plugins directory we can see the plugin as:
... other plugins
Misc.P1
... other plugins 
payment.p2
... other plugins

**Comment by skoshelev** [comment]
Hi, @Alaa-Eddin-jo. I do not quite understand the essence of the problem and what it means that a plugin depends on another plugin. If there is a direct dependency, that is, one plugin uses the namespace of another plugin, then you need to make sure that the required assembly is located in the directory with the dependent plugin. In version 4.60, we completely abandoned shadow copying, as it caused a some of other difficulties, try to reproduce the problem by disabling shadow copying (see the UsePluginsShadowCopy setting)

**Comment by Alaa-Eddin-jo** [comment]
Hi @skoshelev, the bug in version 4.5 and its related to the shadow copying, if we add the required assembly is located in the directory with the dependent plugin it will solve the problem.
so, i think there is nothing to do in version 4.6+.
