### ISSUE TITLE
CheckoutAttribute does not save when using datepicker - no POST when changing dropdowns

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#6561]
nopCommerce version: 4.60.1

Steps to reproduce the problem: 
Create a CheckoutAttribute with date and one without date. Try changing the dropdowns and refresh. Not saved. 
Using a checkbox works fine and when checking a checkbox you can see a POST being done to shoppingcart/checkoutattributechange?isEditable=True
This does not happen with date.

**Comment by AndreiMaz** [comment]
The sam can be told about some other inputs (e.g. textbox). We save them only after clicking the "Checkout" button
