### ISSUE TITLE
Add null validation for selected culture during installation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6562]
nopCommerce version: 4.60.1

Steps to reproduce the problem: 
1. Go to the installtion page in debug mode
2. Do not select any country
3. Click "Install"
4. 
An exception will be thrown at https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Controllers/InstallController.cs#L237. Although we have an empty "catch" block, a breakpoint pointing to the exception is still set in VS. It can confuse some developers. Let's add a "NullOrEmpty" validation for the "model.Country" value

**Comment by skoshelev** [comment]
Closed #6562
