### ISSUE TITLE
Move GetTaxDisplayTypeAsync method to ICustomerService

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6566]
nopCommerce version: develop

As a continuation of #6565

See TODO [here](https://github.com/nopSolutions/nopCommerce/blob/4.60-bug-fixes/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L483)

**Comment by mike-warren-dev** [comment]
Hey @RomanovM, I'd be happy to knock this one out. 

I'll move [SetTaxDisplayTypeAsync()](https://github.com/nopSolutions/nopCommerce/blob/7157287f4b1f995bfdd01a03f677d58309a496e7/src/Presentation/Nop.Web.Framework/WebWorkContext.cs#L519) as well unless you have any objections--the two methods are interrelated and will need to stay together to use the shared _cachedTaxDisplayType field as intended.

**Comment by RomanovM** [comment]
@mike-warren-dev You are welcome. Don't forget about the `customer` parameter.

**Comment by parshan2** [comment]
I think we should also move SetTaxDisplayTypeAsync method to ICustomerService too.
let me know about it, then I can submit the pull request.

**Comment by RomanovM** [comment]
@parshan2 @mike-warren-dev Looks like I confused you a bit. Implementation should have been much easier.
