### ISSUE TITLE
Admin.Catalog.Products.Multimedia.SaveBeforeEdit is not defined in install

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#6569]
nopCommerce version: v4.6
Steps to reproduce the problem: 
Check the language - it seems Admin.Catalog.Products.Multimedia.SaveBeforeEdit is not defined in install ?

**Comment by AndreiMaz** [comment]
https://www.nopcommerce.com/en/boards/topic/96151/admincatalogproductsmultimediasavebeforeedit

**Comment by skoshelev** [comment]
Closed #6569
