### ISSUE TITLE
Allow a store owner to find out why a customer has unsubscribed (newsletter)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#657]
Source: http://www.nopcommerce.com/boards/t/37508/newsletter-unsubscribe.aspx
![multiple newsletter unsubscribe form_inline](https://cloud.githubusercontent.com/assets/16681184/12392474/6ce10642-be00-11e5-89ea-562eb7c213f2.png)

**Comment by AndreiMaz** [comment]
it's a task for third-aprty services such as mailchimp
