### ISSUE TITLE
Can't disable Sort by 'Average Rating' option

### ISSUE THREAD

**Issue by janek49** [nopSolutions/nopCommerce#6578]
nopCommerce version: 4.6

Steps to reproduce the problem: 
On the category page there is this sorting option:
![image](https://user-images.githubusercontent.com/68037466/217469799-404054ab-feb8-4ada-95f5-6c65951e586f.png)
We don't want it as our store doesn't use reviews. However in the Admin Area where you can manage sorting options, there is no entry for this:
![image](https://user-images.githubusercontent.com/68037466/217470020-b9c7039f-b7b2-4d5e-aa49-dbf8e78d87ab.png)

**Comment by AndreiMaz** [comment]
There's no such option by default. I presume it's related to some customization
