### ISSUE TITLE
Remove unused services from AvalaraTaxManager class

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#6579]
The AvalaraTaxManager class contains following unused services:

- IActionContextAccessor
- ICheckoutAttributeService
- ILocalizationService
- ISettingService
- ITaxPluginManager
- IUrlHelperFactory
- IWebHelper
- WidgetSettings

**Comment by parshan2** [comment]
`ICheckoutAttributeService` is used in `CreateLinesForCheckoutAttributesAsync`
