### ISSUE TITLE
Allow a store owner to specify an allowed number of product by a vendor

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#658]
Currently as I know so much request have for vendor side developments . Some of our client use dropshipping and have multiple vendors . 
Some vendors trying to uploude 3000 products , some of them trying to uploude 10.000 products to site . 
I think must be option from admin to define limit for vendor uploude products . 

Also need to permission after uploude products etc Because of quality of uplouded products to effect whole site etc . Need approvement etc . And also more reports etc . 

Source: http://www.nopcommerce.com/boards/t/37321/suggestion-product-import-from-vendor-limit-.aspx

**Comment by AndreiMaz** [comment]
done
