### ISSUE TITLE
There is a bug at ReturnRequest GetReturnRequestAvailabilityAsync method

### ISSUE THREAD

**Issue by hertun** [nopSolutions/nopCommerce#6591]
nopCommerce version: 4.6, 4.5

Steps to reproduce the problem: 
At GetReturnRequestAvailabilityAsync method in ReturnRequestService class; the Quantity in the groupby field is wrong, it only needs to be grouped by only orderItemId. You can create the bug with this case: after creating at least two return requests with different numbers separately for a product ,  then the relevant product appears as more than one line on the new return form page. 
For example we ordered five "product A" in an order, then we create a return request with 1(one) Product A item, then create second return request with 2(two) "Product A" item, then open a new return request page you can see "Product A" lines are doubled.

I commented the relevant line in my project, you may check and fix in your repository
Screenshot is:
![image](https://user-images.githubusercontent.com/5729171/217838134-8ba47c6b-92d8-4c86-871a-adf3478067c8.png)

**Comment by DmitriyKulagin** [comment]
Closed #6591
