### ISSUE TITLE
Fixed:Re-index database tables was not work

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/nopCommerce#6592]
https://github.com/nopSolutions/nopCommerce/blob/76e9bf4c3c1c3730367cd88a04ef2dd0061d6dc1/src/Libraries/Nop.Data/DataProviders/MsSqlDataProvider.cs#L233

Issue:When i try to re-index database tables i was get this error Invalid object name "mystoredb.information_schema.tables" and
I change to upper case and its fixed(information_schema.tables->INFORMATION_SCHEMA)

**Comment by skoshelev** [comment]
Hi @mk148a. I couldn't reproduce the problems as I set all my databases to be case-insensitive, but you correctly noted that it's better to use INFORMATION_SCHEMA.TABLES in uppercase for those schemas that are case-sensitive

**Comment by skoshelev** [comment]
Closed #6592
