### ISSUE TITLE
When using the RoxyFileMan - Preview Images creates Error 

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#6599]
nopCommerce version: v4.6

Steps to reproduce the problem: 
Use TinyMce 
Enable - Admin area. HTML Editor. Manage pictures (Could not do on your Demo Website to double check issue)
Edit Product - Full Description 
Insert image and Browse server  
Select an image 
Preview Image or Right mouce click Preview 

![RoxyFileMan - Preview](https://user-images.githubusercontent.com/34350154/219463158-89b51aad-84ee-4d1a-b188-d9d027dc5f51.png)

**Error**
This localtest46.selectsystems.com.au page can’t be found
No web page was found for the web address: 
https://localtest46.selectsystems.com.au/0003986.png
HTTP ERROR 404

Source: https://www.nopcommerce.com/en/boards/topic/94892/roxy-fileman-error-4503/page/2#303942

**Comment by exileDev** [comment]
Closed #6599
