### ISSUE TITLE
Update Australia post API to the latest version

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#66]
the current one is outdated. we need absolutely new integration 

Forum source: http://www.nopcommerce.com/boards/t/24709/australia-post-plug-in-problemnot-adding-handling-charge.aspx?p=2 

http://auspost.com.au/devcentre/pacpcs.html 
http://auspost.com.au/devcentre/samples/pac/

**Comment by owlyowl** [comment]
Hi Mariannk
I was just wondering if this was going to be implemented in the 3.8 release?

Thanks,
Tom

**Comment by AndreiMaz** [comment]
Hi Tom,

we're still think about it

**Comment by owlyowl** [comment]
Thanks for letting me know.
I will see if I can get started on it as well..

On Tue, Feb 9, 2016 at 5:01 PM, Andrei Mazulnitsyn <notifications@github.com

**Comment by ChrisJollyAU** [comment]
Hi

I have written an initial version against the current API and it is currently working. The new current API returns details for satchels as well as the normal parcel options. 

According to http://auspost.com.au/pdfs/pac-api-update-2016.pdf they are changing the API endpoint so have been using that to test against.

Two things though
1) The API does not return the estimated transit dates (though there is an API call in the tutorial that does however it appears to be undocumented)
2) Would be nice to have the customer dynamically tick if they want signature on delivery or insurance

Work still to be done
 - Settings
 - Perhaps add tracking via Delivery Choices API

**Comment by owlyowl** [comment]
Awesome thanks Chris! That sounds awesome.

Any chance we could incorporate volumetric weight calculation so if the
packages only have weight we reverse calc and get the width height and
depth automagically to.pass in to aus post?

Then have that as a setting where if.it is on.it will use that to.calculate
width depth and length if.only weight is supplied?

Also I was thinking we could provide some kind.of filter in settings so we
only look for a certain postage type I.e only display parcel or only
display parcel express etc
