### ISSUE TITLE
Disable SSL button not working 

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#6603]
Try to enable SSL, save configuration.
then try click Disable SSL button , no action.

**Comment by RomanovM** [comment]
@ecommerce-tester  It works fine with the correct SSL configuration. Where you are trying to do these actions localhost or on the server?

**Comment by ecommerce-tester** [comment]
I try it on hosting.

**Comment by ecommerce-tester** [comment]
I try on hosting.

**Comment by AndreiMaz** [comment]
@ecommerce-tester Please record a video demonstaring the issue

**Comment by RomanovM** [comment]
Couldn't reproduce.
