### ISSUE TITLE
Affiliate Link is not set for logged in Customer

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#6604]
nopCommerce version: All

Steps to reproduce the problem: 
Customer is logged out 
Go to the website with an affiliate link 
https://demo.nopcommerce.com/nike-tailwind-loose-short-sleeve-running-shirt/?affiliateid=1
Guest account is now linked to Affiliate and now has AffiliateId set to 1

If you immediately go to login 
https://demo.nopcommerce.com/login?returnUrl=%2Fnike-tailwind-loose-short-sleeve-running-shirt%2F%3Faffiliateid%3D1
The affiliate link is carried through the login process and the logged in Customer is also linked to affiliate 

But if the guest does not directly login and adds a product to the cart then Affiliate link is not carried across
When the customer logs in to purchase then the logged in customer is not linked to the Affiliate 
Any orders created are not affiliated even though the customer came to the site with an Affiliate link 

This maybe the desired outcome ?
Alternatively a fix is to copy the Affiliate Id across at login time 

Add some code in MigrateShoppingCartAsync(Customer fromCustomer, Customer toCustomer

            if (fromCustomer.AffiliateId != 0)
            {
                var affiliatesPreserveOriginal = await _settingService.GetSettingByKeyAsync<bool>("Affiliates.PreserveOriginal");
                toCustomer = await _customerService.GetCustomerByIdAsync(toCustomer.Id);
                if (!affiliatesPreserveOriginal || toCustomer.AffiliateId == 0)
                {
                    toCustomer.AffiliateId = fromCustomer.AffiliateId;
                    await _customerService.UpdateCustomerAsync(toCustomer);
                }
            }

The setting Affiliates.PreserveOriginal is used in case you don’t want an old affiliate Id to be overwritten with the new affiliate Id

I recently made this change in a plugin as the customer identified it as an issue for their requirements
There was also some old forum posts about this issue 
https://www.nopcommerce.com/en/boards/topic/36321/affiliate-customers-seem-to-belong-to-1st-affiliate-only
https://www.nopcommerce.com/en/boards/topic/47065/affiliate-problem

**Comment by parshan2** [comment]
@AndreiMaz I am offering the following solution to set customer venorId from currentCustomer object in SignInCustomerAsync method.
do you have any better argument?
```
                //migrate shopping cart
                await _shoppingCartService.MigrateShoppingCartAsync(currentCustomer, customer, true);

                //migrate vendor
                if (currentCustomer.VendorId > 0)
                { 
                    customer.VendorId = currentCustomer.VendorId;
                    await _customerService.UpdateCustomerAsync(customer);
                }
```

**Comment by kirilchik** [comment]
#6604 [add Affiliate Link in SignInCustomerAsync](https://github.com/nopSolutions/nopCommerce/commit/d5d46d55fc403b9fed792ada61b7d44ebf287b27)
