### ISSUE TITLE
Parameter 'ensureTwoPublishedLanguages' of GetLocalizedAsync in ILocalizationService ​​will bring unexpected effects

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6605]
nopCommerce version: 4.60 and develop

Steps to reproduce the problem: only one language is setted published and set multi-languages in some pages

It only display stand name, can't display the value of the selected language.

[GetLocalizedAsync](https://github.com/nopSolutions/nopCommerce/blob/f2a94556e5172df77baf23ca25e0baf0087de776/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L553)

**Comment by AndreiMaz** [comment]
@chensiel It's by design. That's why its name is "ensureTwoPublishedLanguages"

**Comment by chensiel** [comment]
@AndreiMaz Hi, I know the meaning of this parameter in this method, but in page '/customer/addresses', if I add address attributes and set multi-languages, it will display standard name not that language customer selected.

**Comment by chensiel** [comment]
1. Add two language, english and french, set english published and french not published
2. Add address attribute MembershipNumber, english name > Membership Number, french name > Numéro de membre
3. Edit address then you will see 'MembershipNumber', not 'Membership Number'

**Comment by AndreiMaz** [comment]
This is the expected behaviour. When you have only one language published, then the default values are used. 

You can customize the solution ([this line of code](https://github.com/nopSolutions/nopCommerce/blob/f2a94556e5172df77baf23ca25e0baf0087de776/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L583)) if you want to count all languages (including unpublished ones)

**Comment by chensiel** [comment]
> This is the expected behaviour. When you have only one language published, then the default values are used.
> 
> You can customize the solution ([this line of code](https://github.com/nopSolutions/nopCommerce/blob/f2a94556e5172df77baf23ca25e0baf0087de776/src/Libraries/Nop.Services/Localization/LocalizationService.cs#L583)) if you want to count all languages (including unpublished ones)

OK, Thank you.
