### ISSUE TITLE
Incorrect quantity in printing packing slips

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6608]
nopCommerce version: 4.60

> Steps to reproduce on an order with a quantity of >1 of the same item:
> 1. Add shipment
> 2. enter a Qty to ship of less then the total quantity ordered. For example if 10 ordered enter 5
> 3 click save
> 4 click on the "Print packaging slip" button
> 5 all 10 of the items are shown on the packing slip, but should only be 5

Source: https://www.nopcommerce.com/boards/topic/96340/bug-in-4602-packing-slip-on-partial-shipments

**Comment by exileDev** [comment]
Closed #6608
