### ISSUE TITLE
In My Account-Addresses section, address gets saved when 'country'(required field) is kept empty.

### ISSUE THREAD

**Issue by Muditshah30** [nopSolutions/nopCommerce#6610]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 
1. Open My Account-Addresses menu.
2. Click on "ADD NEW" button.
3. Enter data in all fields except in "Country" field(do not select any country).
4. Click on "SAVE" button.
5. Check that the address gets saved successfully.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/121164051/220570342-95fa71ef-e5ba-4359-a75c-438d3a68328f.png)

**Comment by RomanovM** [comment]
@skoshelev  Perhaps the same as #6492

**Comment by skoshelev** [comment]
Closed #6610
