### ISSUE TITLE
Can we enable the reward points on checkout payment method when all the payment methods are disabled

### ISSUE THREAD

**Issue by JayPatel7348** [nopSolutions/nopCommerce#6613]
nopCommerce version: 4.6

Steps to reproduce the problem: 
1 Add reward points by placing order(registered user)
2 Complete the order from admin
3 Disable all the payment methods from admin
4 Perform checkout for another order till the payment method page(same user)
5 Observe the validation message on payment method page

Expected
User should be able to checkout using their available reward points when all payment methods are disabled (If reward points >= Order total amount otherwise show validation message)
(https://user-images.githubusercontent.com/96106946/220889798-2b9551cc-c4da-4c19-965a-4347e0084e42.jpg)

**Comment by AndreiMaz** [comment]
@JayPatel7348 Thanks for suggestion. But it doesn't make any sense to disable all payment methods. How will other users pay for orders?

that's why we do not consider such scenarios and leave it for customization
