### ISSUE TITLE
Filter products by store not working 

### ISSUE THREAD

**Issue by ajamaeen** [nopSolutions/nopCommerce#6615]
nopCommerce version: 4.6.2

Steps to reproduce the problem: 

1. Admin Panel >> Catalog >> Products
2. In the search page select a store & hit search the products don't filter by store
When I debugged the code I had noticed the following conditions:

            if (!showHidden)
            {
                //apply store mapping constraints
                productsQuery = await _storeMappingService.ApplyStoreMapping(productsQuery, storeId);

                //apply ACL constraints
                var customer = await _workContext.GetCurrentCustomerAsync();
                productsQuery = await _aclService.ApplyAcl(productsQuery, customer);
            }

I think apply store mapping constraints must be outside the if condition.

**Comment by ajamaeen** [comment]
You can find the code in Nop.Services.Catalog >> ProductService >> SearchProductsAsync line 870

**Comment by RomanovM** [comment]
I think we just need to check `storeId` parameter in this case.

**Comment by exileDev** [comment]
Closed #6615
