### ISSUE TITLE
issue with select pagesize in api 

### ISSUE THREAD

**Issue by amirkhanjz** [nopSolutions/nopCommerce#6621]
nopCommerce version: API version 1

Steps to reproduce the problem: 
enabale allowcustomertosetpagesize
add some pagesize option for a category
call that category by ```/catalog/getcategoryproducts``` with a pagesize number in body,
it will return products as many as you set in your body and also set the page size option to that specific number.

fix is here : 
at the beginning of that method, there is if 
```
if (command.PageSize > 0)
            {
                category.PageSizeOptions = command.PageSize.ToString();
            }
```
which is not needed and i don't no why this IF is here.

**Comment by skoshelev** [comment]
Hi @amirkhanjz. I'm sorry, I don't understand what kind of API we are talking about, in our code the GetCategoryProducts method did not and does not contain this code, below you can see its first version, at the time of release 1.0. 

```
var category = await _categoryService.GetCategoryByIdAsync(requestModel.CategoryId);

if (!await CheckCategoryAvailabilityAsync(category))
	return NotFound("The category is not available");

var model = await _catalogModelFactory.PrepareCategoryProductsModelAsync(category, requestModel.Command.FromDto<CatalogProductsCommand>());

var response = new GetCategoryProductsResponse
{
	CatalogProductsModel = model.ToDto<CatalogProductsModelDto>(),
	TemplateViewPath = "_ProductsInGridOrLines"
};
return Ok(response);
```

In any case, it is better to ask questions about WebAPi on the [forum](https://www.nopcommerce.com/en/boards/topic/91619/web-api-official-plugin), this is a repository of nopCommerce
