### ISSUE TITLE
RedisSynchronizedMemoryCache spamming pub/sub channel

### ISSUE THREAD

**Issue by rickardvh** [nopSolutions/nopCommerce#6622]
nopCommerce version: develop branch

Steps to reproduce the problem:

We recently merged the latest version of RedisSynchronizedMemoryCache and related code from develop, from using our own original implementation before. It worked well in the test environment, but when we deployed to production, key events began flooding the channel and eventually choking the entire application.

Majako is currently looking into it and comparing with the previous version, but we wanted to give you a heads up for now.

Best regards,
Rickard von Haugwitz
Majako [majako.net](https://www.majako.net)

**Comment by rickardvh** [comment]
My apologies, this appears to be caused by me in #6618 - I will try to quickly find a better solution that solves the original bug without causing a new one.

**Comment by skoshelev** [comment]
Closed #6622
