### ISSUE TITLE
change model name

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6625]
Hi, 
if it were possible I would recommend renaming the ProductPriceModel class because there is an equal one in the ProductOverviewModel file.

Also they have very similar fields, I don't know if you can use another subclass with these fields

Thank you

https://github.com/nopSolutions/nopCommerce/blob/6b30a973ef1b60756615ac25453d2aa56f4da700/src/Presentation/Nop.Web/Models/Catalog/ProductDetailsModel.cs#L180

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But it works absolutely fine because classes are different and one of them in sub-class
