### ISSUE TITLE
Linux: App restart fails to restart nopCommerce.service properly

### ISSUE THREAD

**Issue by ChicagoDave** [nopSolutions/nopCommerce#6628]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 
Trying to upload a plugin and reload list of plugins. Get Bad Gateway error. One of two things happens. Either the nopCommerce.service dies or it takes 10s to reload, but the site itself shows a Bad Gateway error. You have to refresh to come back to the site.

Seems like the app restart should work more cleanly than this?

**Comment by danFbach** [comment]
I've also experienced this - the site reload is slow on linux.
You _can_ change the setting `commonsettings.restarttimeout` to 10000 or something so the delay is longer and the page reloads more gracefully, but it won't make your application start any faster and anyone else trying to access your site during that time will get the gateway error.

**Comment by ChicagoDave** [comment]
where is that setting?

**Comment by danFbach** [comment]
Configuration => Settings => All Settings, then just search for it
