### ISSUE TITLE
Address attribute warning message localization

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#6630]
https://github.com/nopSolutions/nopCommerce/blob/6b30a973ef1b60756615ac25453d2aa56f4da700/src/Libraries/Nop.Services/Attributes/AttributeParser.cs#L411

In this method, use "ShoppingCart.SelectAttribute" for localization.

It will display wrong message for fields such as textbox.

**Comment by AndreiMaz** [comment]
What exactly do you mean by "wrong message"? What should be displayed?

**Comment by AndreiMaz** [comment]
@chensiel What exactly do you mean by "wrong message"? What should be displayed?

**Comment by chensiel** [comment]
> @chensiel What exactly do you mean by "wrong message"? What should be displayed?

If it's a textbox field, it should display 'Please input {0}'. Now it display 'Please select {0}'.

**Comment by AndreiMaz** [comment]
We'll think how we should better handle it. In the meantime you can enter some more generic locale value. For example, "Please ensure that "{0}" is specified"
