### ISSUE TITLE
New address fields empty saving issue from admin

### ISSUE THREAD

**Issue by chiragshivaaysoft** [nopSolutions/nopCommerce#6631]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 
admin-> customer -> customer -> edit customer> click on add new address --> here without giving  address info -> click on save button,  empty address is saved even every fields empty.

For more details see below video

[https://share-me.video/video/Qkhpo2Ln8HxDlZ5fHfwqSIMFgp5C5pf99UOlCBpRXqwlFi97KSHmqKSPYPXtOehZ](url)

Source: https://www.nopcommerce.com/en/boards/topic/96407/admin-portal-customer-new-address-validation-issue

**Comment by skoshelev** [comment]
Closed #6631
