### ISSUE TITLE
Better Crypto Payment Support 

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#6634]
Now we full support only fiat payment.
But when we enable cryptocurrency payment, we have many problems
For example. Exchange rate, price rounding , decimal price, payment plugins,

**Comment by AndreiMaz** [comment]
Thanks for suggestion

1. "Exhange rate, price rounding, decimal price". Currently we do not plan to support it as replied at https://github.com/nopSolutions/nopCommerce/issues/6600
2. "Payment plugins". If you mean more third-party plugins, then please check our [marketplace](https://www.nopcommerce.com/en/extensions?category=payment-modules). If it doesn't have some payment plugin, then please ask our community to implement and share it (this repository is related to the core only)
