### ISSUE TITLE
Make it possible to rearrange the order of address fields.

### ISSUE THREAD

**Issue by AxelAndersen** [nopSolutions/nopCommerce#6645]
It varies from country to country how an address is build up.
In Denmark we would always set it up in this order:

**Address:   MainStreet 102
ZipCode:  8900
City:         Copenhagen
Country:  Denmark**

In writing for one line:
**"MainStreet 102, 8900 Copenhagen, Denmark"**

In other countries they use it differently, so would be nice to have possibility to arrange the order in configuration.
Could be here:
Admin/Setting/CustomerUser

**Comment by RomanovM** [comment]
We could add a setting `AddressLineMask" as we did for `CustomOrderNumberMask` and use it everywhere, or we could add multiple locales (e.g. "{0} {1} {2}") to compose the address line case-by-case.

**Comment by manuel3108** [comment]
Not that it could also be interesting to re-order the address data input fields accordingly.

**Comment by AxelAndersen** [comment]
> We could add a setting `AddressLineMask` as we did for `CustomOrderNumberMask` and use it everywhere, or we could add multiple locales (e.g. "{0} {1} {2}") to compose the address line case-by-case.

Yes, just as important to be able to re-order the input form fields.
