### ISSUE TITLE
Nopcommerce 4.70 New features 

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#6650]
Please vote.
1. Web API free version
2. Auction
3. Multi Tenant 
4. Multi Price
5. Other.....

**Comment by AndreiMaz** [comment]
There's no need to duplicate or gourp work items. Here is a list of all work items for version 4.70 - https://github.com/nopSolutions/nopCommerce/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+4.70%22
