### ISSUE TITLE
Filtering Of Products by color and show the same colored picture when filter

### ISSUE THREAD

**Issue by fathima1992** [nopSolutions/nopCommerce#6659]
nopCommerce version: 4.60

problem: can we make changes in the filtration of products ( filtering by color attribute) by creating a widget/plugin.
Is it possible ? or
Can we contribute code to existing core source code to extend the above filtering functionality?
Which one is better to follow? Right now, the feature (feature : show the same colored picture when filter) is not in nopcommerce.
 
Steps to reproduce the problem: 
![Screenshot (224)](https://user-images.githubusercontent.com/109781022/227158624-a1ff7e6a-d10b-47ad-bf32-9cea6b46986b.png)

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But it's by design and we do not plan to change this behaviour. Leaving it for customization

Duplicated [#https://github.com/nopSolutions/nopCommerce/issues/6656](https://github.com/nopSolutions/nopCommerce/issues/6656)
