### ISSUE TITLE
File upload product attribute is very slow

### ISSUE THREAD

**Issue by balajivelu147** [nopSolutions/nopCommerce#6662]
nopCommerce version: 4.6

Steps to reproduce the problem: 

- create a sample product
- add one or two product attributes with type file upload
- then preview or go to that product
- upload some file(I uploaded 500kb file) 
- then click on addtocart button 
- it took around 20+ seconds

if I increase number of file upload type product attributes, it becomes terribly slow(tested with 10 file uploads(100 kb each, took more than 2min))..
PFA:
![image](https://user-images.githubusercontent.com/34922609/229704513-73a87a9d-ca72-421c-963e-7967532c9ba4.png)

the method which is getting slower:
![image](https://user-images.githubusercontent.com/34922609/229705004-efcffd43-f0ce-4f78-97be-267711d0fce2.png)

**Comment by itsoftware2022** [comment]
Hi Team,
Can anyone is working on this? If not please assign me.

**Comment by skoshelev** [comment]
Hi @balajivelu147. It looks like a local problem in your environment, I tried to replicate the problem on a clean install and everything works as expected, without any problems

![06-04-2023 083032](https://user-images.githubusercontent.com/16875599/230286589-2c7fd416-dfd0-4ea9-a2f1-9e388205646b.png)

Closed #6662
