### ISSUE TITLE
Widgetzone before attribute filter in Catalog

### ISSUE THREAD

**Issue by fathima1992** [nopSolutions/nopCommerce#6663]
nopCommerce version: 4.60

Steps to reproduce the problem: 
Could you please share if there is any widgetzone when we check any color in the attribute filter.

**Comment by fathima1992** [comment]
![Screenshot (289)](https://user-images.githubusercontent.com/109781022/230042498-89b29682-b2a4-4ec8-9cde-b0cb6e0b3059.png)

**Comment by AndreiMaz** [comment]
Please post all questions on [our forums](https://www.nopcommerce.com/en/boards). We use GitHub for work items only

**Comment by fathima1992** [comment]
Thanks for letting me know
