### ISSUE TITLE
Validation Control at Partial Refund

### ISSUE THREAD

**Issue by mbilalari** [nopSolutions/nopCommerce#6666]
nopCommerce version: 4.60

Steps to reproduce the problem: User can set a bigger refund amount than total amount of order while trying to partial refund a completed order. However it is not effect the max refunded amount, validation control is much better.
![image](https://user-images.githubusercontent.com/45788337/230555560-bb878bfb-b9b4-44c2-8c5e-efbb58b20511.png)

**Comment by AndreiMaz** [comment]
Duplicated https://github.com/nopSolutions/nopCommerce/issues/5424
