### ISSUE TITLE
Product attributes override prices and default price and old price

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6667]
nopCommerce version: all version

Steps to reproduce the problem: 
I want to have a product with product attributes combination. Each combination has different price. if I want to have a discount for each combination as follwoing:

Combination1: Old price = 100, new price = 90
Combination2: Old price = 150, new price = 130,
....

No way to do this as we have only one old price at product level. To solve this, just add a new field for the combination as old override price.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
