### ISSUE TITLE
Wrong token name for VatValidationResult in WorkflowMessageService.cs

### ISSUE THREAD

**Issue by mystiki** [nopSolutions/nopCommerce#6673]
**nopCommerce version:** 4.60.2

**Steps to reproduce the problem:** 

In Tax Settings, check "EU VAT enabled", check "Notify admin when new VAT number is submitted".
In Content management, make sure template "NewVATSubmitted.StoreOwnerNotification" is active.
Register a new customer with a valid EU VAT.
An email is sent to the store owner, however the validated Name and Address from the VAT validation webservice are missing, and only showing the replacement token name.

![image](https://user-images.githubusercontent.com/33549355/231724186-96778fd2-888b-4775-b3ae-481b7beff454.png)

**How to fix the problem:**
In Nop.Services->WorkflowMessageService.cs lines 2246 and 2247 change "VatValidatio" to "VatValidationResult".
VatValidationResult is the actual name of the token in message template "NewVATSubmitted.StoreOwnerNotification".

![image](https://user-images.githubusercontent.com/33549355/231722214-5660b435-300b-4b0b-9412-ea72e6d9be21.png)

**Comment by skoshelev** [comment]
Closed #6673
