### ISSUE TITLE
Localization resource missed 

### ISSUE THREAD

**Issue by SelectSystemsInternational** [nopSolutions/nopCommerce#6676]
nopCommerce version: v4.6 (and previous)

Steps to reproduce the problem: 

Language resource rewardpoints.expired is not defined in Setup
See src\Libraries\Nop.Services\Orders\RewardPointService.cs

Also rewardpoints.fields.date
See src\Presentation\Nop.Web\Themes\Pacific\Views\Order\CustomerRewardPoints.cshtml

**Comment by RomanovM** [comment]
@SelectSystemsInternational Thanks. Btw, "Pacific theme" isn't a default theme.

**Comment by skoshelev** [comment]
Closed #6676
