### ISSUE TITLE
After checkout step 1 (Billing Address) always return to cart page

### ISSUE THREAD

**Issue by Mukeshk1407** [nopSolutions/nopCommerce#6680]
nopCommerce version: 4.60.2

Steps to reproduce the problem: After checkout step 1 (while click a Billing Address screen continue button) always return to cart page.

I am facing this problem in development only.

**Comment by AndreiMaz** [comment]
We cannot rerpoduce the issue. Try logging in. It works fine our [demo website](https://demo.nopcommerce.com/)
