### ISSUE TITLE
DeadLock in ConfirmOrder

### ISSUE THREAD

**Issue by MehdiNaz** [nopSolutions/nopCommerce#6681]
nopCommerce version:4.6

Steps to reproduce the problem: 

When placing an order, the following error is given and some shopping cart items are not registered in the order

Error while placing order. Error 1: Transaction (Process ID 251) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction..

https://mysite.com/RealOnePageCheckout/ConfirmOrder

**Comment by MehdiNaz** [comment]
image error in sql profiler  :
https://ibb.co/vPDKkPQ

Deadlock graph	1328351	1	sa	0X01	17	.\MSSQLSERVER,1433		2023-04-22 03:02:41.483	<deadlock-list>
 <deadlock victim="process23cbf9e8108">
  <process-list>
   <process id="process23cbf9e8108" taskpriority="0" logused="232" waitresource="KEY: 8:72057597023551488 (f69b74d115f6)" waittime="726" ownerId="5389480823" transactionname="MERGE" lasttranstarted="2023-04-22T03:02:40.737" XDES="0x23c4dac8470" lockMode="U" schedulerid="18" kpid="43588" status="suspended" spid="370" sbid="0" ecid="0" priority="0" trancount="3" lastbatchstarted="2023-04-22T03:02:40.737" lastbatchcompleted="2023-04-22T03:02:40.743" lastattention="1900-01-01T00:00:00.743" clientapp="Core Microsoft SqlClient Data Provider" hostname="WIN-G6CNI51E14D" hostpid="42200" loginname="....." isolationlevel="read committed (2)" xactid="5389480823" currentdb="8" currentdbname="....." lockTimeout="4294967295" clientoption1="671219744" clientoption2="128056">
    <stackFrames>
      <frame id="00" address="0x7FFA332A2C24" pdb="ntdll.pdb" age="1" guid="7340D02D-D0E1-FFF0-644B-D6EFFEEE1329" module="ntdll" rva="0xA2C24" /><frame id="01" address="0x7FFA30E263E9" pdb="kernelbase.pdb" age="1" guid="36F8962D-7731-87DC-E7CC-542CC601830B" module="kernelbase" rva="0xC63E9" /><frame id="02" address="0x7FF9DBE269F7" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x69F7" /><frame id="03" address="0x7FF9DBE2691B" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x691B" /><frame id="04" address="0x7FF9DBE21B2B" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x1B2B" /><frame id="05" address="0x7FF9DBE23A77" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x3A77" /><frame id="06" address="0x7FF9DFC09665" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x89665" /><frame id="07" address="0x7FF9DFC09465" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x89465" /><frame id="08" address="0x7FF9DFB8FBB4" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0xFBB4" /><frame id="09" address="0x7FF9DFB99EA8" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x19EA8" /><frame id="10" address="0x7FF9E0B106F1" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0xF906F1" /><frame id="11" address="0x7FF9DFB9A426" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x1A426" /><frame id="12" address="0x7FF9DFB90880" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x10880" /><frame id="13" address="0x7FF9DFBFA77B" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x7A77B" /><frame id="14" address="0x7FF9DFBFA696" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x7A696" /><frame id="15" address="0x7FF9DFC0D4BF" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x8D4BF" /><frame id="16" address="0x7FF9DFBA02C9" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x202C9" /><frame id="17" address="0x7FF9DFBCA27B" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x4A27B" /><frame id="18" address="0x7FF9DFBA02C9" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x202C9" /><frame id="19" address="0x7FF9DFBE10CF" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x610CF" /><frame id="20" address="0x7FF9DCD3E1B8" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xE1B8" /><frame id="21" address="0x7FF9DCD5EF4C" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2EF4C" /><frame id="22" address="0x7FF9DCD5F31A" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2F31A" /><frame id="23" address="0x7FF9DCD3C24F" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC24F" /><frame id="24" address="0x7FF9DCD3C6CC" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC6CC" /><frame id="25" address="0x7FF9DCD3DB47" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xDB47" /><frame id="26" address="0x7FF9DCD3D211" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xD211" /><frame id="27" address="0x7FF9DDC89C87" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF59C87" /><frame id="28" address="0x7FF9DDC8A2C3" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF5A2C3" /><frame id="29" address="0x7FF9DDC8AEFE" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF5AEFE" /><frame id="30" address="0x7FF9DCD5F31A" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2F31A" /><frame id="31" address="0x7FF9DCD3C24F" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC24F" /><frame id="32" address="0x7FF9DCD3C6CC" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC6CC" /><frame id="33" address="0x4642464439464637" /><frame id="34" address="0x6470202236393641" /><frame id="35" address="0x696D6C7173223D62" /><frame id="36" address="0x6120226264702E6E" /><frame id="37" address="0x67202232223D6567" /><frame id="38" address="0x304631223D646975" /><frame id="39" address="0x33382D3145413341" />
       </stackFrames>
    <executionStack>
     <frame procname="dbo.after_update" line="9" stmtstart="296" stmtend="450" sqlhandle="0x03000800b734b870eec10900e9af000000000000000000000000000000000000000000000000000000000000">
update ProductWarehouseInventory 
set StockQuantity=0 
where StockQuantity&lt;     </frame>
     <frame procname="adhoc" line="1" stmtend="1176" sqlhandle="0x020000009c5dc91bd0928833042fe806a427ed2feefc4e360000000000000000000000000000000000000000">
unknown     </frame>
    </executionStack>
    <inputbuf>
MERGE INTO [ProductWarehouseInventory] [Target]
USING (VALUES
	(268664,3,54,2,57195), (238245,2,45,4,57195),
	(230505,2,28,3,57195), (308114,2,22,5,57195),
	(264260,2,19,1,57195), (341566,2,18,6,57195)
) [Source]
(
	[Id],
	[ReservedQuantity],
	[StockQuantity],
	[WarehouseId],
	[ProductId]
)
ON ([Target].[Id] = [Source].[Id])

WHEN MATCHED THEN
UPDATE
SET
	[Target].[ReservedQuantity] = [Source].[ReservedQuantity],
	[Target].[StockQuantity] = [Source].[StockQuantity],
	[Target].[WarehouseId] = [Source].[WarehouseId],
	[Target].[ProductId] = [Source].[ProductId]
;
    </inputbuf>
   </process>
   <process id="process23c5e928108" taskpriority="-10" logused="252" waitresource="KEY: 8:72057597023551488 (7939fb194e43)" waittime="721" ownerId="5389480585" transactionname="user_transaction" lasttranstarted="2023-04-22T03:02:40.537" XDES="0x23c087dc470" lockMode="U" schedulerid="30" kpid="19196" status="suspended" spid="81" sbid="2" ecid="0" priority="10" trancount="3" lastbatchstarted="2023-04-22T03:02:40.690" lastbatchcompleted="2023-04-22T03:02:40.690" lastattention="1900-01-01T00:00:00.690" clientapp="EntityFramework" hostname="WIN-G6CNI51E14D" hostpid="37724" loginname="...." isolationlevel="read committed (2)" xactid="5389480585" currentdb="8" currentdbname="..." lockTimeout="4294967295" clientoption1="671219744" clientoption2="128056">
    <stackFrames>
      <frame id="00" address="0x7FFA3329F4F4" pdb="ntdll.pdb" age="1" guid="7340D02D-D0E1-FFF0-644B-D6EFFEEE1329" module="ntdll" rva="0x9F4F4" /><frame id="01" address="0x7FFA30D9D52E" pdb="kernelbase.pdb" age="1" guid="36F8962D-7731-87DC-E7CC-542CC601830B" module="kernelbase" rva="0x3D52E" /><frame id="02" address="0x7FF9DBE23F0A" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x3F0A" /><frame id="03" address="0x7FF9DBE21B2B" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x1B2B" /><frame id="04" address="0x7FF9DBE23A77" pdb="SqlDK.pdb" age="2" guid="DF33C098-9A00-452D-959F-F820E68C8B32" module="SqlDK" rva="0x3A77" /><frame id="05" address="0x7FF9DFC09665" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x89665" /><frame id="06" address="0x7FF9DFC09465" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x89465" /><frame id="07" address="0x7FF9DFB8FBB4" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0xFBB4" /><frame id="08" address="0x7FF9DFB99EA8" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x19EA8" /><frame id="09" address="0x7FF9E0B106F1" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0xF906F1" /><frame id="10" address="0x7FF9DFB9A426" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x1A426" /><frame id="11" address="0x7FF9DFB90880" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x10880" /><frame id="12" address="0x7FF9DFBFA77B" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x7A77B" /><frame id="13" address="0x7FF9DFBFA696" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x7A696" /><frame id="14" address="0x7FF9DFC0D4BF" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x8D4BF" /><frame id="15" address="0x7FF9DFBA02C9" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x202C9" /><frame id="16" address="0x7FF9DFBCA27B" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x4A27B" /><frame id="17" address="0x7FF9DFBA02C9" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x202C9" /><frame id="18" address="0x7FF9DFBE10CF" pdb="sqlmin.pdb" age="2" guid="1F0A3AE1-83BC-4882-A450-D610CB534214" module="sqlmin" rva="0x610CF" /><frame id="19" address="0x7FF9DCD3E1B8" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xE1B8" /><frame id="20" address="0x7FF9DCD5EF4C" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2EF4C" /><frame id="21" address="0x7FF9DCD5F31A" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2F31A" /><frame id="22" address="0x7FF9DCD3C24F" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC24F" /><frame id="23" address="0x7FF9DCD3C6CC" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC6CC" /><frame id="24" address="0x7FF9DCD3DB47" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xDB47" /><frame id="25" address="0x7FF9DCD3D211" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xD211" /><frame id="26" address="0x7FF9DDC89C87" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF59C87" /><frame id="27" address="0x7FF9DDC8A2C3" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF5A2C3" /><frame id="28" address="0x7FF9DDC8AEFE" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xF5AEFE" /><frame id="29" address="0x7FF9DCD5F31A" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0x2F31A" /><frame id="30" address="0x7FF9DCD3C24F" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC24F" /><frame id="31" address="0x7FF9DCD3C6CC" pdb="sqllang.pdb" age="2" guid="BFE66178-A45A-4266-A816-406AEF56ADB4" module="sqllang" rva="0xC6CC" /><frame id="32" address="0x6470202238423145" /><frame id="33" address="0x616C6C7173223D62" /><frame id="34" address="0x20226264702E676E" /><frame id="35" address="0x202232223D656761" /><frame id="36" address="0x4642223D64697567" /><frame id="37" address="0x412D383731363645" /><frame id="38" address="0x363632342D413534" /><frame id="39" address="0x30342D363138412D" />
       </stackFrames>
    <executionStack>
     <frame procname="dbo.after_update" line="9" stmtstart="296" stmtend="450" sqlhandle="0x03000800b734b870eec10900e9af000000000000000000000000000000000000000000000000000000000000">
update ProductWarehouseInventory 
set StockQuantity=0 
where StockQuantity&lt;     </frame>
     <frame procname="dbo.UpdateProductWarehouseInventory" line="9" stmtstart="358" stmtend="672" sqlhandle="0x03000800da3e0d05dfa9b500ebaf000001000000000000000000000000000000000000000000000000000000">
update ProductWarehouseInventory
set ReservedQuantity=@ReservedQuantity,StockQuantity=@StockQuantity
where WarehouseId=@WarehouseId and ProductId=@productI     </frame>
    </executionStack>
    <inputbuf>
Proc [Database Id = 8 Object Id = 84754138]    </inputbuf>
   </process>
  </process-list>
  <resource-list>
   <keylock hobtid="72057597023551488" dbid="8" objectname="dbo.ProductWarehouseInventory" indexname="PK_ProductWarehouseInventory" id="lock23c18e4dd80" mode="X" associatedObjectId="72057597023551488">
    <owner-list>
     <owner id="process23c5e928108" mode="X"/>
    </owner-list>
    <waiter-list>
     <waiter id="process23cbf9e8108" mode="U" requestType="wait"/>
    </waiter-list>
   </keylock>
   <keylock hobtid="72057597023551488" dbid="8" objectname="dbo.ProductWarehouseInventory" indexname="PK_ProductWarehouseInventory" id="lock23c113b3e80" mode="X" associatedObjectId="72057597023551488">
    <owner-list>
     <owner id="process23cbf9e8108" mode="X"/>
    </owner-list>
    <waiter-list>
     <waiter id="process23c5e928108" mode="U" requestType="wait"/>
    </waiter-list>
   </keylock>
  </resource-list>
 </deadlock>
</deadlock-list>

**Comment by AndreiMaz** [comment]
duplicated DeadLock
