### ISSUE TITLE
Print multiple packingslips to PDF results in a file with wrong file extension

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6684]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 
1. Go to admin area > sales > shipments
2. Select multiple shipments
3. Click the "Print packaging slips (selected)" button
4. It generates a wrong file with PDF extension. But it should "zip"

Source: https://www.nopcommerce.com/en/boards/topic/96819/print-multiple-packingslips-to-pdf-results-in-corrupt-pdf-file

**Comment by skoshelev** [comment]
Closed #6684
