### ISSUE TITLE
SendinBlue plugin. Don't request all contacts when a specific one is needed

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6689]
nopCommerce version: 4.60

Now we're using `GetContactsFromList()` method to get all contacts and then check whether there is a contact with that email.
But we could use `GetContactInfo()` method to get a contact by email directly and avoid loading the full contact list.

**Comment by kirilchik** [comment]
[#6689-SendinBlue-GetContactInfoAsync](https://github.com/nopSolutions/nopCommerce/commit/21663d092c4b18bb0aead6fca6a15fa65fdec409)
