### ISSUE TITLE
Make category/manufacturer/product default values configurable

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#669]
Currently these are hardcoded in CategoryController.Create() and ManufactureryController.Create():
- Allow Customers To Select Page Size = true
- Include In Top Menu = true

We have over 100 Categories and want to have a fixed Page Size of 10. Chances are that Product-Managers forget to set this when they create a new Category.

**Comment by eadameg** [comment]
In Catalog Settings a Default Values section would be useful
