### ISSUE TITLE
FacebookPixel plugin. Custom events support (Conversion API)

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6691]
nopCommerce version: 4.60

Steps to reproduce the problem: 
1- Enable the conversion API
2- Add a new custom event to the facebook pixel as follwoing:
   a- Event name = "MyThankYouPageEvent"
   b- Widget zone = "MyThankYouPageWidgetZone". This is a custom zone added manualy.

3- Visit the page that has MyThankYouPageWidgetZone, the conversion API will not be called with the event name "MyThankYouPageEvent", it will be fired using script

**Comment by RomanovM** [comment]
@ahmadkq This is by design. Custom events are supported only in script implementation.
