### ISSUE TITLE
Rename "Sendinblue" to "Brevo"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6693]
Sendinblue is now Brevo. So we have to rename our plugin as well

1. Replace a logo
2. Replace namespaces, class names, plugin name etc
4. But we should NOT change the plugin system name. This way no actions will be requires for merchants upgrading to the new version
5. Ensure that everything works fine

Assets are available at https://drive.google.com/drive/folders/1Dq8oukRHaSc7YN3gvP5XfMJC1YbZGaJo

**Comment by abdullohmuhamedov** [comment]
May I do this @AndreiMaz?

**Comment by DmitriyKulagin** [comment]
Closed #6693

**Comment by DmitriyKulagin** [comment]
Closed https://github.com/nopSolutions/nopCommerce/issues/6693

**Comment by nealculiner** [comment]
I'm testing the brevo plugin and all seems fine except one error shown at the top:

`Unfortunately, there’s been an error, feel free to reach our support team. Error calling CreateAttribute: {"code":"invalid_parameter","message":"Incorrect formula. Please refer https://help.brevo.com/hc/en-us/articles/209558545-Use-formulas to read the formula"}`

**Comment by RomanovM** [comment]
@nealculiner Please look at [this topic](https://www.nopcommerce.com/boards/topic/96985/brevo-sendinblue-plugin-error-message) on our forums.
