### ISSUE TITLE
Update UK counties

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6698]
I recently had to select the "Hereford & Worcester" county (state) in the UK. 

Please note that the county "Hereford & Worcester" split into two separate counties, "Herefordshire" & "Worcestershire" in 1998.

Technically most cities on the UK are not even considered to be in a county, so even selecting "Herefordshire" when my city/town is "Hereford" is incorrect - there should ideally be a blank county to select in the UK, but it's acceptable to select the nearest county.

The order succeeded anyway, but I thought I'd let you know that your county list is quite out of date

**Comment by DmitriyKulagin** [comment]
Closed #6698
