### ISSUE TITLE
Public store. Add popular search terms page

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#67]
1. We already have a report for a store owner. Let's display the same in public store (filter by store id).
2. We should also allow a store owner to decide whether this page should be enabled (displayed)
3. Allow a store owner to delete "bad" search words. Otherwise, some customers "add" some search terms to this page. For example, some links (of course, not clickable) or company names

Here is an example - http://enterprise-demo.magentocommerce.com/catalogsearch/term/popular/ 

Let's make it configurable

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
