### ISSUE TITLE
Ability to feature blog posts to be shown on main page. 

### ISSUE THREAD

**Issue by tawfiqin** [nopSolutions/nopCommerce#6700]
## New Blogging Feature

give the user the ability to show some blog posts on main page, and to select which blog posts to be shown on main page. 

I already done the required coding to add this feature.

**Comment by AndreiMaz** [comment]
@tawfiqin Thanks a lot for suggestion and contribution (https://github.com/nopSolutions/nopCommerce/pull/6699). But we do not plan to add this functionality out of the box. I would highly recommend creation of widget plugin that will support this fucnationality and then uploading it to our [marketplace](https://www.nopcommerce.com/en/marketplace)

**Comment by tawfiqin** [comment]
@AndreiMaz Thank you.
