### ISSUE TITLE
It will be very useful to have a DeleteResourcesFromXmlAsync

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#6701]
nopCommerce version: 4.7

Steps to reproduce the problem: Inside LocalizationService it will be very useful to have a method to delete language resources from xml input (for a given plugin) just like how it was imported in the first place. This simplify the deleting of resources when the plugin is removed. Somthing like this

       public virtual async Task DeleteResourcesFromXmlAsync(Language language, StreamReader xmlStreamReader)
        {
            if (language == null)
                throw new ArgumentNullException(nameof(language));

            if (xmlStreamReader.EndOfStream)
                return;

            var lsNamesList = _lsrRepository.Table
                .Where(lsr => lsr.LanguageId == language.Id)
                .ToDictionary(lsr => lsr.ResourceName, lsr => lsr, StringComparer.InvariantCultureIgnoreCase);

            var lrsToRemove = new List<LocaleStringResource>();

            foreach (var (name, value) in LoadLocaleResourcesFromStream(xmlStreamReader, language.Name))
            {
                if (lsNamesList.ContainsKey(name))
                {
                    var lsr = lsNamesList[name];
                    lsr.ResourceValue = value;
                    lrsToRemove.Add(lsr);
                }
            }

            await _lsrRepository.DeleteAsync(lrsToRemove, false);

            // clear cache
            await _staticCacheManager.RemoveByPrefixAsync(NopEntityCacheDefaults<LocaleStringResource>.Prefix);
        }

**Comment by skoshelev** [comment]
Hi @Farshidgolkarihagh. Perhaps this would be useful for some very large plugin, but it seems to me that even a very large plugin will have all locales with one prefix, and then all of them can be deleted with one call to the ILocalizationService.DeleteLocaleResourcesAsync method.
