### ISSUE TITLE
Add customer name to order list view in admin

### ISSUE THREAD

**Issue by compito** [nopSolutions/nopCommerce#6702]
Let's display customer names on the order list page in admin section.  There are just email addresses in it now, and it makes it hard to find the order you are looking for. 

It should be displayed (and properly encoded) in the same "Customer" column. Dispaly names on the first row, and then email below.

See PR - https://github.com/nopSolutions/nopCommerce/pull/6706

**Comment by imatoria** [comment]
Please let me know if this is what we are looking for: 
![image](https://github.com/nopSolutions/nopCommerce/assets/5390758/868e9f68-ca20-48ec-bf73-82b0484161a3)

I can do it.

**Comment by AndreiMaz** [comment]
@imatoria Yes, you're absolutely right
