### ISSUE TITLE
Inconsistent store authorization for Orders placed with unmapped Currency/Language to the store

### ISSUE THREAD

**Issue by smitvadher** [nopSolutions/nopCommerce#6704]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 

https://github.com/nopSolutions/nopCommerce/blob/fd96372633927c1d245c49ae84c956d9686ba91e/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L758

And

https://github.com/nopSolutions/nopCommerce/blob/fd96372633927c1d245c49ae84c956d9686ba91e/src/Libraries/Nop.Services/Orders/OrderProcessingService.cs#L765

Both use customers' currency and language. There should be a store authorization.
When a customer has any currency/language selected which is no longer mapped to that store they still will be able to place an order with the old language and currency.

It has an effect on email notifications, orders details, invoices, and any other views where order detail is used.

**Comment by imatoria** [comment]
I believe when the support for a currency is been withdrawn for a store then all associated orders for that currency in that store should be switched to default/another currency.
FYI: I haven't seen the code much so I am not sure if my solution is relevant.

**Comment by RomanovM** [comment]
@imatoria This will be redundant, such changes should be not retroactive.

**Comment by exileDev** [comment]
Closed #6704
