### ISSUE TITLE
Update nugets with each minor release?

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6705]
nopCommerce version: 
4.60
Steps to reproduce the problem: 
I'm new to nop, finally building out my new site from another .net cart provider. I'm also a developer. It would be nice if the nugets could be brought up to date with each update you release. I had to update some such as MailKit to make email work with my Exchange 2019 self hosted server. Some nugets broke the build, others did not. There are constant improvements, security updates, performance enhancements, etc. It would help us to have the latest bits with each release please.

Thank you.

**Comment by skoshelev** [comment]
Hi @nealculiner.

We update packages with every major release, we have an open ticket for this https://github.com/nopSolutions/nopCommerce/issues/196. However, we cannot update packages when minor versions are released, otherwise we will have to update all plugins, which is very difficult.
