### ISSUE TITLE
Create an interface where we can centrally define what pages are available when the store is closed

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#671]
see that on the topics page there is a checkbox option to allow viewing the page if the store is closed - useful of course, but I think there is a better approach. 

There will be many scenarios where a store is closed ( or perhaps not closed but navigation is allowed only for certain roles ) 

In either case, there will most likely be pages that the store owner would want accessible to everyone all the time regardless of the ACL rules or if the store is closed 

(it might just be a topic or the contact us form but it could be several information pages or potentially certain product or category pages and more) 

It seems to me that the most flexible approach would be to have a page in admin where the storeownwer can define what pages are viewable in those circumstances. 

It would be a very simple interface where the storeowner simply types the actual pagename in a text area 

because all the page names already exist, we can use autocomplete when we start typing - 

... exactly like how we enter product tags on product pages. 

Source: http://www.nopcommerce.com/boards/t/35909/create-an-interface-where-we-can-centrally-define-what-pages-are-available-when-the-store-is-closed.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
