### ISSUE TITLE
SqlException: Invalid column name 'PictureId'  in version 4.70

### ISSUE THREAD

**Issue by rahimimohsen24** [nopSolutions/nopCommerce#6710]
nopCommerce version: 4.70

SqlException: Invalid column name 'PictureId'.

Steps to reproduce the problem: 
1- Clone develop branch
2- Rebuild project
3- Run and install with sample data
4- click on a product with combination (for example Build your own computer)

`Nop.Data.EntityRepository<TEntity>+<>c__DisplayClass13_0+<<GetAllAsync>g__getAllAsync|0>d.MoveNext() in EntityRepository.cs
+
                return await query.ToListAsync();
Nop.Core.Caching.MemoryCacheManager.GetAsync<T>(CacheKey key, Func<Task<T>> acquire)
Nop.Core.Caching.MemoryCacheManager.GetAsync<T>(CacheKey key, Func<Task<T>> acquire) in MemoryCacheManager.cs
+
                throw;
Nop.Data.EntityRepository<TEntity>.GetEntitiesAsync(Func<Task<IList<TEntity>>> getAllAsync, Func<IStaticCacheManager, CacheKey> getCacheKey) in EntityRepository.cs
+
            return await _staticCacheManager.GetAsync(cacheKey, getAllAsync);
Nop.Data.EntityRepository<TEntity>.GetAllAsync(Func<IQueryable<TEntity>, IQueryable<TEntity>> func, Func<IStaticCacheManager, CacheKey> getCacheKey, bool includeDeleted) in EntityRepository.cs
+
            return await GetEntitiesAsync(getAllAsync, getCacheKey);
Nop.Services.Catalog.ProductAttributeService.GetAllProductAttributeCombinationsAsync(int productId) in ProductAttributeService.cs
+
            var combinations = await _productAttributeCombinationRepository.GetAllAsync(query =>
Nop.Web.Factories.ProductModelFactory.PrepareProductDetailsModelAsync(Product product, ShoppingCartItem updatecartitem, bool isAssociatedProduct) in ProductModelFactory.cs
+
                    model.InStock = (await _productAttributeService
Nop.Web.Controllers.ProductController.ProductDetails(int productId, int updatecartitemid) in ProductController.cs
+
            var model = await _productModelFactory.PrepareProductDetailsModelAsync(product, updatecartitem, false);
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()`

**Comment by imatoria** [comment]
I think this is not in `develop` branch but `main`. I also encountered it 5 days back.

**Comment by skoshelev** [comment]
Closed #6710

**Comment by skoshelev** [comment]
Closed #6710
