### ISSUE TITLE
Email verification too strict on register page

### ISSUE THREAD

**Issue by wmap-gussun** [nopSolutions/nopCommerce#6714]
nopCommerce version: 
-

Steps to reproduce the problem: 
Navigate to /register
Enter random user information
Enter a email in the following format user@domain
Example: admin@com, info@local
Click on create account.

Expected:
User created

Actual result:
Error saying invalid email

Documentation:
https://en.wikipedia.org/wiki/Email_address
Example from documentation: admin@mailserver1

**Comment by AndreiMaz** [comment]
Email validation rules are valid by default. You'll have to customize the solution if you want to change the default (valid) behavior
