### ISSUE TITLE
Email validation issue

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6715]
nopCommerce version: all versions

Steps to reproduce the problem: 
while checkout process, write a wrong email such as "xxx@yyy", don't put ".com", it will accept it at frontend validation but will catch it at backend level.

**Comment by ahmadkq** [comment]
@RomanovM What i mean, it should not accept such format, the xxx@yyy is not a correct email format, it should be xxx@yyy.com for example

**Comment by RomanovM** [comment]
@ahmadkq Please see [this comment](https://github.com/nopSolutions/nopCommerce/issues/6714#issuecomment-1564039020).

**Comment by ahmadkq** [comment]
@RomanovM Why such thing should be customized! email should be entered in valid format, it should be in xxx@yyy.com format. All eCommerce and website handling such case so why nopCommerce doesn't by default!
