### ISSUE TITLE
Add estimate shipping route to disallow paths in robots.txt

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6716]
nopCommerce version: 4.40.4

> I'm having a strange issue with my site based on nop 4.404 that I can see on Google search console: I'm having tons of 404 errors from pages like
> `product/estimateshipping?ProductId=261248&`

Source: https://www.nopcommerce.com/boards/topic/97059/tons-of-errors-404-with-productestimateshipping

**Comment by RomanovM** [comment]
We should update our default `robotsTxtSettings.DisallowPaths` and add all paths of AJAX requests to it.

**Comment by skoshelev** [comment]
Closed #6716
