### ISSUE TITLE
Issues from Rider Solution-Analysis

### ISSUE THREAD

**Issue by manuel3108** [nopSolutions/nopCommerce#6719]
nopCommerce version: develop

Steps to reproduce the problem: 
1. Download and install Rider
2. Wait a long time until the analysis has been completed.

Continuation of #6355 
Rider is currently reporting 313 errors, most of them seem accurate in my opinion. 4 of those errors are in c# files, the other ones in cshtml files. Currently i mainly see two sources for those errors:

---

**View 'x' cannot be found (Errors in cshtml files)**
1. https://github.com/nopSolutions/nopCommerce/blob/d738e3cc5c98e9d7ecef9559ab1f7aec18e4f5ae/src/Presentation/Nop.Web/Controllers/NewsController.cs#L225
2. https://github.com/nopSolutions/nopCommerce/blob/d738e3cc5c98e9d7ecef9559ab1f7aec18e4f5ae/src/Presentation/Nop.Web/Controllers/BlogController.cs#L239
3. https://github.com/nopSolutions/nopCommerce/blob/d738e3cc5c98e9d7ecef9559ab1f7aec18e4f5ae/src/Presentation/Nop.Web/Controllers/NewsController.cs#L225
4. https://github.com/nopSolutions/nopCommerce/blob/d738e3cc5c98e9d7ecef9559ab1f7aec18e4f5ae/src/Presentation/Nop.Web/Controllers/ProductController.cs#L360

All of those errors report back that the appropriate views cannot be found.

---

**Cannot resolve symbol 'item' (most of the cshtml errors)**
These errors appear to happen on nearly every `Html.LocalizedEditorAsync` Call.
Here is one of the many examples: https://github.com/nopSolutions/nopCommerce/blob/8070bc2dadeb85366705dc946efda8b4a58e2158/src/Plugins/Nop.Plugin.Payments.CheckMoneyOrder/Views/Configure.cshtml#L16

Currently, we usually have something like
```cs
@(await Html.LocalizedEditorAsync<ConfigurationModel, ConfigurationModel.ConfigurationLocalizedModel>("plugin-settings-localized",
     @<div>
....
```

something like this could do the trick (although untested). See `(item) =>` at the end:
```cs
@(await Html.LocalizedEditorAsync<ConfigurationModel, ConfigurationModel.ConfigurationLocalizedModel>("plugin-settings-localized", (item) =>
     @<div>
....
```

---

**Argument type 'System.Threading.Tasks.Task<x>' is not assignable to parameter type 'x' (also in the views)**
I'm not entirely sure who is causing this one, maybe its the code, maybe the soltion analysis.

Here is an example: 
https://github.com/nopSolutions/nopCommerce/blob/b5403186847d7077b73fefc6c60b12fa2f93d046/src/Plugins/Nop.Plugin.Payments.CyberSource/Views/Configure.cshtml#L76

In the code we write:
```cshtml
<nop-select 
    asp-for="PaymentConnectionMethodId" 
    asp-items="@await (((ConnectionMethodType)Model.PaymentConnectionMethodId).ToSelectListAsync())" 
/>
```

and apparently It's currently not happy with the parenthesis placement. Upon further analysis it really looks like one of the parenthesis was misplaced after the `await` although it should be before. This is what the solution analysis accepts:
```cshtml
<nop-select 
    asp-for="PaymentConnectionMethodId" 
    asp-items="@(await ((ConnectionMethodType)Model.PaymentConnectionMethodId).ToSelectListAsync())" 
/>
```

**Comment by MohammadAnsari98** [comment]
Hi i have same problem any update?

**Comment by exileDev** [comment]
These issues are specific to Rider only and don't affect project launch. Perhaps it's difference in razor analizers. You can open PR if you have suggestions that work for both IDEs.

Closed #6719

**Comment by MohammadAnsari98** [comment]
@exileDev  Hi exileDev i opened this project in vs and the problem there still exist but vs default settings don't get error when action method can't find corresponded view

The problem in nutshell : there are some action mehods in controllers that have `return view(something)` and rider neither visual studio fails to find the view for them and in rider it gives error - in visual studio goto view dosn't work for them

**Comment by MohammadAnsari98** [comment]
@exileDev can you please reopen this issue ?

**Comment by curllog** [comment]
@exileDev @manuel3108   Hi i tested nopcommerce 4.70 with last version of rider (2024.1.1) and it's working perfectly, all issued are solved
