### ISSUE TITLE
CheckoutAttributes are not encoded correctly in PDF 

### ISSUE THREAD

**Issue by brothers28** [nopSolutions/nopCommerce#6722]
nopCommerce version: 4.6

Steps to reproduce the problem: 
- Create a CheckoutAttribute containing umlaute (äöü)
- Create order containing containing the previously created CheckoutAttribute
- Download invoice for previously created order. 

Umlaute will not be encoded / displayed correctly inside the created pdf.
![image](https://github.com/nopSolutions/nopCommerce/assets/12660121/bea8b8df-1ecc-4d20-baf7-c5c5cfa72f98)

**Comment by DmitriyKulagin** [comment]
Closed #6722
