### ISSUE TITLE
Sendinblue plugin. Webhook not working

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6728]
nopCommerce version: 4.60

> I have been looking at the code and can see a webhook has been implemented for when a user unsubscribes within Brevo but I can't seem to get the webhook working.
> when I put this into Brevo as a webhook I get a "400 Bad request" response. The nopCommerce log doesn't have and additional information.

Source: https://www.nopcommerce.com/boards/topic/97157/brevosendinblue-unsubscribe-webhook

**Comment by danFbach** [comment]
SendInBlueController has `[AutoValidateAntiforgeryToken]` and brevo not sending the antiforgery token?

**Comment by RomanovM** [comment]
@danFbach Yes, you are right. We should move this method to a separate "public" controller.

**Comment by DmitriyKulagin** [comment]
Closed #6728
