### ISSUE TITLE
Shortcode Support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#673]
Is it possible to create shortcodes that can be used in nop similar to how WordPress does it? For instance, we are wanting to create different plugins, some of which would be very useful to be placed within a topic. So if we created a form that had a shortcode, we could just paste that shortcode in the topic. Then when we view the topic, it would display the form. 

Source: http://www.nopcommerce.com/boards/t/35832/shortcode-support.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
