### ISSUE TITLE
Taxservice doesn't use shoppingCartSettings.roundpricesduringcalculation

### ISSUE THREAD

**Issue by AdiIndoSwiss** [nopSolutions/nopCommerce#6730]
nopCommerce version: 4.5.1

Steps to reproduce the problem: 

This service doesn't include the roundpricesduringcalculation setting anywhere in the service class. Is it changed in later versions? Because of this, the value get changed from two decimal places to four decimal places.

thks
Adi

**Comment by AndreiMaz** [comment]
It's by design. Taxes are not rounded.
