### ISSUE TITLE
It's possible that missing check to showproductreviewsperstore ? thanks

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6733]
https://github.com/nopSolutions/nopCommerce/blob/a9c70171822387aac385b5b14896769775a1aeff/src/Presentation/Nop.Web/Factories/ProductModelFactory.cs#L249

**Comment by AndreiMaz** [comment]
@kava81 Everything works fine. This setting is located above - https://github.com/nopSolutions/nopCommerce/blob/a9c70171822387aac385b5b14896769775a1aeff/src/Presentation/Nop.Web/Factories/ProductModelFactory.cs#L243
