### ISSUE TITLE
Redis Cache Updates For Cluster Mode

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#6737]
I have updated the CacheKey Class Create function as below, and changed the RedisCacheManager with the following code.
Now it works without error with Redis Cluster Mode. And the distribution of keys to nodes looks even.

        public virtual CacheKey Create(Func<object, object> createCacheKeyParameters, params object[] keyObjects)
        {
            

            if (!keyObjects.Any())
            {
                if (Prefixes.Any())
                {
                    var shortestPrefix = Prefixes?.MinBy(p => p.Length);

                    var hastagedPrefixes = Prefixes.Select(p => p.Replace(shortestPrefix, $"{{{shortestPrefix}}}"));

                    var hastagedKey = Key.Replace(shortestPrefix, $"{{{shortestPrefix}}}");

                    var cacheKey = new CacheKey(hastagedKey, hastagedPrefixes.ToArray());

                    return cacheKey;
                }
                else
                {
                    var cacheKey = new CacheKey(Key, Prefixes.ToArray());

                    return cacheKey;

                }
                
            }
            else
            {
                if (Prefixes.Any())
                {
                    var shortestPrefix = Prefixes.MinBy(p => p.Length);

                    var hastagedPrefixes = Prefixes.Select(p => p.Replace(shortestPrefix, $"{{{{{shortestPrefix}}}}}"));

                    var hastagedKey = Key.Replace(shortestPrefix, $"{{{{{shortestPrefix}}}}}");

                    var cacheKey = new CacheKey(hastagedKey, hastagedPrefixes.ToArray());

                    for (var i = 0; i < cacheKey.Prefixes.Count; i++)
                        cacheKey.Prefixes[i] = string.Format(cacheKey.Prefixes[i], keyObjects.Select(createCacheKeyParameters).ToArray());

                    cacheKey.Key = string.Format(cacheKey.Key, keyObjects.Select(createCacheKeyParameters).ToArray());

                    return cacheKey;
                }
                else
                {
                    var cacheKey = new CacheKey(Key, Prefixes.ToArray());

                    cacheKey.Key = string.Format(cacheKey.Key, keyObjects.Select(createCacheKeyParameters).ToArray());

                    for (var i = 0; i < cacheKey.Prefixes.Count; i++)
                        cacheKey.Prefixes[i] = string.Format(cacheKey.Prefixes[i], keyObjects.Select(createCacheKeyParameters).ToArray());

                    return cacheKey;
                }
                
            }
  
        }

RedisCacheManager.cs Override the following method.

protected override string PrepareKeyPrefix(string prefix, params object[] prefixParameters)
        {
            return prefixParameters?.Any() ?? false
                ? $"{{{string.Format(prefix, prefixParameters.Select(CreateCacheKeyParameters).ToArray())}}}"
                : $"{{{prefix}}}";
        }

_Originally posted by @streamzyuk in https://github.com/nopSolutions/nopCommerce/issues/6570#issuecomment-1596287426_

**Comment by skoshelev** [comment]
Hi @streamzyuk. as in the original ticket, we believe that adding support for such functionality is redundant. We decided to leave it for customization to those who know why they need it.

As for your code, it looks confusing and a little unstructured. When I was analyzing this problem, I came to the conclusion that it is enough to add one method to the RedisConnectionWrapper:

```
public IDictionary<int, List<RedisKey>> GetKeyGroups(IEnumerable<RedisKey> keys)
{
	return keys.GroupBy(_connection.GetHashSlot).ToDictionary(item=>item.Key, item=>item.ToList());
}
```

and then use it in RedisCacheManager.RemoveByPrefix methods. This seems to solve the main problem, and looks much clearer

Closed #6737
