### ISSUE TITLE
Common model tests fail without Lazy<ILocalizationservice registered

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#6738]
https://github.com/nopSolutions/nopCommerce/blob/18eac9d7226354b44153d974b8157ec397a2427b/src/Tests/Nop.Tests/BaseNopTest.cs#L316

I have no idea why , because. Would have thought that 
Line 316 would be enough to register both 

but when I run any of the common model factory tests Tests they fail, with an obscure failure that is to do with the getservice function absorbing the actual error when it tries to resolve unregistered

anyway adding the following line fixes the issue and the tests will 100%, seems dumb to have to register this “extra” but maybe somone can figure out why and fix it properly…

services.AddTransient<Lazy<ILocalizationService>>();

I assume this isn’t an issue at runtime. Because of NopStartup line 300 in configure services 

addscoped(typeof(Lazy<>),….

**Comment by awe-source** [comment]
Okay, my bad this is resolved in dev, #6496, but not in 4.6 bugfixes, leaving forinfo

**Comment by skoshelev** [comment]
Closed #6738
