### ISSUE TITLE
Publish event on changing the encryption key

### ISSUE THREAD

**Issue by GaborFarkas** [nopSolutions/nopCommerce#6740]
nopCommerce version: 4.50+

Hello,

I think it would be nice to publish a custom event on a successful encryption key change with both keys after [src/Presentation/Nop.Web/Areas/Admin/Controllers/SettingController.cs#1821](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Areas/Admin/Controllers/SettingController.cs#L1821). This way, plugins would be able to reliably encrypt their sensitive data with the global key using `IEncryptionService` and act properly on key changes.

What do you think? The only issue I can think of is if the application dies somewhere in the middle of the action, but in that case a DB rollback is mandatory anyways.

**Comment by exileDev** [comment]
Closed #6740
