### ISSUE TITLE
Incorrect culture detection on first request when AutomaticallyDetectLanguage disabled

### ISSUE THREAD

**Issue by smitvadher** [nopSolutions/nopCommerce#6743]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 

Have two languages configured from the admin: one with RTL support (e.g., he-IL) and one can be en-US.
Set the display order of he-IL to 0 and en-US to 1. When a customer visits the store for the first time, the default language will be he-IL.

However, the culture selected for the first time is en-US. This causes an issue in loading the RTL CSS. Instead, it loads LTR for the first time.
This happens because of the default language set in the customer's browser. In my case, it was en-US, and the browser sends the "Accept-Language: en-US,en;q=0.9" request header.

The below method is used to set up the cultures of the application:
https://github.com/nopSolutions/nopCommerce/blob/7104b704cad742482bc054152f7d1dc2a578c85d/src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs#L417

By default, .NET Core includes the "[AcceptLanguageHeaderRequestCultureProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.localization.acceptlanguageheaderrequestcultureprovider?view=aspnetcore-7.0)" in the [RequestCultureProviders](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.requestlocalizationoptions.requestcultureproviders?view=aspnetcore-7.0) collection.

Removing it from the culture providers collection solves the issue, as it's going to use default culture when it could not resolve it from the request.

**Comment by smitvadher** [comment]
Hi Romanov
Thanks for the acknowledgment.

The setting "AutomaticallyDetectLanguage" works like a charm to detect a
language based on browsers.

However, I failed to provide the main issue I faced.

The issue I faced is related to CSS selection. Here are the steps:
1. I configured nop to have two languages(he-IL and en-US).
2. The display order for he-IL is set to 0, and for en-US, it is set to 1.
3. The setting "AutomaticallyDetectLanguage" is false.
4. Based on the above configuration, when a customer first opens the store
(I suggest using incognito mode or clearing the cookies in the browser
first), they will see the first language according to the display order. In
my case, I see he-IL.
5. So far, everything works fine. For the first request, the culture is
based on the browser. In my case i.e. en-US. *NOTE: The langue by default
selected on display order is he-IL.*
And
If you take a look at
https://github.com/nopSolutions/nopCommerce/blob/feae8bf04639ab81edc9d4d781686e24b2dbd736/src/Presentation/Nop.Web.Framework/UI/NopHtmlHelper.cs#L584
this. GenerateCssFiles
has the condition to set the bundle prefix to ".rtl".

Here lies the problem. I see the he-IL language which I intend to display
by default. But the CSS loaded the first time is "ltr", not the "rtl".

When I reload the browser, I then see the correct "rtl" style. This happens
because of a cookie (created in the first request from
"WorkContext.SetLanguageCookie") that sets the he-IL culture.

I hope the above explanation makes sense to you. Customers only experience
this issue once, and after that, everything works well.

Thanks

**Comment by RomanovM** [comment]
@smitvadher  You are absolutely right. 
I tested it with setting _"SEO friendly URLs with multiple languages enabled"_ enabled, so [NopSeoUrlCultureProvider](https://github.com/nopSolutions/nopCommerce/blob/master/src/Presentation/Nop.Web.Framework/Globalization/NopSeoUrlCultureProvider.cs#L35) did the trick. But if this setting is disabled, then the culture is indeed detected incorrectly on the first request. 
Thanks for your investigation.

**Comment by smitvadher** [comment]
Happy to help :) @RomanovM
