### ISSUE TITLE
check password

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6745]
hi,
hashed password it's right or it's better customersetting.defaultpasswordformat ?

thanks

https://github.com/nopSolutions/nopCommerce/blob/d77bca25f249499c764a45fb9e188fa6bdf10fda/src/Libraries/Nop.Services/Authentication/External/ExternalAuthenticationService.cs#L169

**Comment by RomanovM** [comment]
@kava81 Please post your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker.
