### ISSUE TITLE
Rendering of lines from parent to nested settings in view are rendered wrong

### ISSUE THREAD

**Issue by markusschnepf** [nopSolutions/nopCommerce#6748]
nopCommerce version:
**4.60.3**

Steps to reproduce the problem: 
1. Add a **nop-nested-setting** containg the attribute **is-condition-invert="true"** and multiple user controls to a view (for example "configure.cshtml"
2. Check nested settings parent (checkbox)

Expected behavior:
When the parent is **unchecked**: The nested settings are shown and the "lines" (from the parent to all children) are shown.
When the parent is **checked**: The nested settings are hidden and the "lines" (from the parent to all children) are hidden.

Actual behavior:
When the parent is **unchecked**: The nested settings are shown and the "lines" (from the parent to all children) are hidden.
When the parent is **checked**: The nested settings are hidden and the "lines" (from the parent to all children) are shown.

Example code:

><div class="form-group row">
                    <div class="col-md-3">
                        <nop-label asp-for="StepsDatabaseIntegratedSecurity" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="StepsDatabaseIntegratedSecurity" />
                        <span asp-validation-for="StepsDatabaseIntegratedSecurity"></span>
                    </div>
                </div>
                <nop-nested-setting asp-for="StepsDatabaseIntegratedSecurity" is-condition-invert="true">
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="StepsDatabaseUser" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="StepsDatabaseUser" asp-required="@(!Model.StepsDatabaseIntegratedSecurity)" />
                            <span asp-validation-for="StepsDatabaseUser"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="StepsDatabasePassword" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="StepsDatabasePassword" asp-required="@(!Model.StepsDatabaseIntegratedSecurity)" html-attributes="@(new { value = Model.StepsDatabasePassword })" / />
                            <span asp-validation-for="StepsDatabasePassword"></span>
                        </div>
                    </div>
                </nop-nested-setting>`

<img width="455" alt="LinesOfNestedSettings" src="https://github.com/nopSolutions/nopCommerce/assets/129297320/da7706dd-152a-49c2-80a8-e06c275539cc">

**Comment by RomanovM** [comment]
@Thanks for your notice. Indeed, such a problem exists, but to fix such a minor thing we need to dig deep into fixing styles, that can lead to other problems. We've already considered it in #5494 and decided to leave it as it is. 

In those cases where it's needed to invert the condition, we don't use nested settings and add the script directly (see an example [here](https://github.com/nopSolutions/nopCommerce/blob/4.60-bug-fixes/src/Presentation/Nop.Web/Areas/Admin/Views/Setting/_Tax.TaxDisplaying.cshtml#L81)).

So, I close this issue for now, but if you're willing to help with a solution, you are very welcome.
