### ISSUE TITLE
Filter by store isn't working correctly in admin area

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6749]
nopCommerce version: 4.60 +

Steps to reproduce the problem: 
1. open the backend
2. go to the categories list page
3. try filtering by store

It will not work, as `showHidden` is set to true, and the store filtering currently only applies when `showHidden` = false. This kinda makes the store filtering selector on the category page useless.

See here for 4.60.x

https://github.com/nopSolutions/nopCommerce/blob/5cc7475339a6c4fcad81ecc2b0dea8c06d15dc06/src/Libraries/Nop.Services/Catalog/CategoryService.cs#L246-L254

See here for 4.50.x

https://github.com/nopSolutions/nopCommerce/blob/5496cc30549b562cd0d87785ea5d77ab6cfb5130/src/Libraries/Nop.Services/Catalog/CategoryService.cs#L250-L257

**Comment by Manuel-Innovapps** [comment]
As per our customer, the same also occurs for Manufacturers

**Comment by RomanovM** [comment]
The same as in #6615

**Comment by RomanovM** [comment]
@exileDev It seems we should revise all changes made in #5134, they are probably not working right now.

**Comment by exileDev** [comment]
#6749 Closed

**Comment by Manuel-Innovapps** [comment]
Thanks!

Do you guys already know if you are planning a minor release with this fix included? So that we can properly communicate this with our customers?

**Comment by AndreiMaz** [comment]
@Manuel-Innovapps Not yet. Maybe, in several weeks
