### ISSUE TITLE
Enabling search feature of Datatables js in DataTablesModel in NopCommerce

### ISSUE THREAD

**Issue by devoidofsilence** [nopSolutions/nopCommerce#6750]
I am using NOPCommerce version 4.5. I need to make search functionality available for the Child DataTables created by using `DataTablesModel` in NOPCommerce. How do I do it? I tried adding `Searchable = true` but it didn't work. I mean the Search filter textbox of Datatables did not appear. Is this feature not available in NOPCommerce `DataTableModel` by default?

**Comment by AndreiMaz** [comment]
Please post all questions on our [forums](https://www.nopcommerce.com/en/boards/). We use GitHub for work items only
