### ISSUE TITLE
`RewardPointService` uses global reward point data to update balances for newly activated points

### ISSUE THREAD

**Issue by evan-at-tusksoft** [nopSolutions/nopCommerce#6752]
nopCommerce version: 4.30

Steps to reproduce the problem: 
1. Make a call to `RewardPointService.AddRewardPointsHistoryEntry()` and pass an activation date
2. Make a call to `RewardPointService.GetRewardPointsQuery()` and pass a `customerId` of `0`
3. The history entry with the activation date receives a balance that is calculated based on the most recent point balance available from _any_ customer

This is primarily due to the following code found in `RewardPointService`:
```cs
protected virtual IQueryable<RewardPointsHistory> GetRewardPointsQuery(int customerId, int? storeId, bool showNotActivated = false)
{
    var query = _rewardPointsHistoryRepository.Table;

    //PROBLEM 1 HERE: No customer filter applied if no customer ID is provided.
    if (customerId > 0)
        query = query.Where(historyEntry => historyEntry.CustomerId == customerId);

    //more code here, omitted for brevity...

    //PROBLEM 2 HERE: This method is always called, even without a customer filter. THIS IS NOT A PURE FUNCTION. It is a side effect that introduces unexpected behavior.
    UpdateRewardPointsBalance(query);

    return query;
}

protected virtual void UpdateRewardPointsBalance(IQueryable<RewardPointsHistory> query)
{
    //more code here, omitted for brevity...

    //PROBLEM 3 HERE: Pulling all reward point entries that are missing a point balance and were created in the past. If no customer ID was provided in the last method, this becomes a global search.
    var notActivatedPoints = query
        .Where(historyEntry => !historyEntry.PointsBalance.HasValue && historyEntry.CreatedOnUtc < nowUtc)
        .OrderBy(historyEntry => historyEntry.CreatedOnUtc).ThenBy(historyEntry => historyEntry.Id).ToList();
    if (!notActivatedPoints.Any())
        return;

    //PROBLEM 4 HERE: The last entry with a points value is pulled for ANY customer, then assigned to ALL entries without a point balance.
    var currentPointsBalance = query
        .OrderByDescending(historyEntry => historyEntry.CreatedOnUtc).ThenByDescending(historyEntry => historyEntry.Id)
        .FirstOrDefault(historyEntry => historyEntry.PointsBalance.HasValue)
        ?.PointsBalance ?? 0;

    foreach (var historyEntry in notActivatedPoints)
    {
        currentPointsBalance += historyEntry.Points;
        historyEntry.PointsBalance = currentPointsBalance;
        UpdateRewardPointsHistoryEntry(historyEntry);
    }
}
```

This is a huge problem for us because it has been undetected for 16 months in production, and the balance calculations have compounded on top of each other, giving thousands of users hundreds of thousands of rewards points that they didn't earn. Our client has lost thousands of dollars in sales as a result.

**Comment by AndreiMaz** [comment]
@evan-at-tusksoft You write:

> Make a call to RewardPointService.GetRewardPointsQuery() and pass a customerId of 0

But we do not make any calls to this method with "customerId" set to 0. You also should not do that. Actually it's clearly stated in the parameter comment in this method - "pass 0 to load all records"

**Comment by CometSoft** [comment]
unsubscribe

**Comment by evan-at-tusksoft** [comment]
@AndreiMaz Please do not close this issue. It is not resolved. I encourage you to read the code carefully to understand how badly it is written.

Your response is conflicting. You say that we shouldn't be calling the method with `customerId` set to `0`. But you also say that the parameter comment accepts this as a valid use case. Which is it? Obviously, it must be the latter or else the method would check for a value of `0` and return no results or throw an exception instead of ignoring the customer filter and executing the query, would it not?

Additionally, I direct your attention to `RewardPointService.GetRewardPointsHistory()`, which calls the `GetRewardPointsQuery()` method. It actually _defaults_ the `customerId` argument to `0`. Clearly, this is presented as a valid use case.

Intentions aside, the fact that a query method actually executes state changes before returning the query results is unconscionable. This outright disregards basic programming principles and best practices.

On top of all that, if you take the `UpdateRewardPointsBalance()` method at face value, the code block it contains makes two opposite and conflicting assumptions. In the first half of the method, it clearly assumes that the query may or may not have a customer filter applied because it uses the `CustomerId` property from the returned `RewardPointHistory` records to insert new expiration records. This makes sense if `customerId` really is an optional argument. However, in the second half of the method, it instead assumes that the query will _always_ have a customer filter applied, because it queries only the most recent `RewardPointHistory` record for ANY customer before applying its balance to the query results for ALL records without a balance. This is obviously a bug, and a really bad one at that.

**Comment by joelmdev** [comment]
If this isn't a bug then I'm terrified of what else may be lurking in the codebase by design.

**Comment by glhays** [comment]
So the complaint here is not so much an issue, but an interpretation of ones own belief of best practices and programming principles. 

> This disregards basic programming principles and best practices.

The lines of code below set the customerId value to 0, hence passing it to the Utility method.
Where the customerId of 0 is basically ignored as it moves through the If statements. Logic says if there is a valid customerId then the first If statement runs.

`
 public virtual IPagedList<RewardPointsHistory> GetRewardPointsHistory(int customerId = 0, int? storeId = null,
            bool showNotActivated = false, Guid? orderGuid = null, int pageIndex = 0, int pageSize = int.MaxValue)
        {
            var query = GetRewardPointsQuery(customerId, storeId, showNotActivated);
`
So again just an argument of who sets the programming principles and best practices in this repository.
That would be @AndreiMaz 
So two thumbs down to each @evan-at-tusksoft & @joelmdev with respect.

**Comment by joelmdev** [comment]
@glhays that whole reply reads like a programmer's version of "alternative facts".

This isn't a private repository for a pet project where the developer can play fast an loose with minimal impact. This is an open source project used by many that deals very directly with people's money. Furthermore, NopCommerce is a vehicle for profit for NopSolutions by way of other premium product and service offerings- we're actually a customer and a partner. So to include dangerous code that runs contrary to widely established best practices and then claim "you're using it wrong" or "his repository his rules" is pretty myopic.

**Comment by danFbach** [comment]
I would just add that this is open source and everything is easily overridable with a basic plugin, no need to change the core code. I've overridden many things that I didn't like or didn't meet my needs. You're all entitled to your opinions but I personally view this, as I view many open source projects that are intended to be customized - the maintainers do their best to provide you a functional base with which to build your needs upon. If it is functional, but not how you'd like, then that's an opinion, and you are fully entitled to override that code with your own implementation - or better yet, try your best to improve it and contribute with a pull request.

**Comment by glhays** [comment]
@joelmdev The only alternative fact is you not liking the facts of the code as written. Which I believe did not cause you any harm.
As a user of NopCommerce since version 2.65 in production, I am very aware that Nop is open source software and licensed as such. I use it with that knowledge. Your deflection of the facts in this case, are apparent in your words that your customer may or may not have suffered harm in your oversight to conduct your own due diligence knowing your using open source software in production environments. The blame is on you and your TuskSoft partner. It is ok to vent, but do not try to pass the blame onwards. 
In that 16 months of unsubstantiated claims you had at your keyboard, all you needed to address the issue If any. This doesn't exist in 4.30 or even in the most current version of Nop. It is OSS free to modify, enhance, and suggest better alternatives.

**Comment by joelmdev** [comment]
> you are fully entitled to override that code with your own implementation - or better yet, try your best to improve it and contribute with a pull request.

And override it we did. However, there's no point in issuing a PR given that the primary maintainer swiftly dismissed the problem at hand.

**Comment by glhays** [comment]
Many folks have submitted pull requests with an attached issue.

**Comment by evan-at-tusksoft** [comment]
I feel like you guys have been sidetracked by my allusion to best practices. While I firmly believe that avoiding state changes in query methods is a best practice, that's only a tangential issue that contributed to this bug. Please reread my comments about the `UpdateRewardPointsBalance()` method, specifically this part:

> the code block it contains makes two opposite and conflicting assumptions. In the first half of the method, it assumes that the query may or may not have a customer filter applied because it uses the CustomerId property from the returned RewardPointHistory records to insert new expiration records. This makes sense if customerId really is an optional argument. However, in the second half of the method, it instead assumes that the query will always have a customer filter applied, because it queries only the most recent RewardPointHistory record for ANY customer before applying its balance to the query results for ALL records without a balance.

If you take the time to study what the code is doing, you'll see that this is a bug, plain and simple. It needs to be fixed by the team that maintains the framework.

**Comment by AndreiMaz** [comment]
@evan-at-tusksoft Thanks a lot for addition al details. 

But could you please provide a list of steps to reproduce the issue? I mean in the default nopCommerce installation (without custom changes)

**Comment by evan-at-tusksoft** [comment]
@AndreiMaz Thank you for your response. As you mentioned earlier, the default nopCommerce installation never calls the `RewardPointService.GetRewardPointsQuery()` method with a `customerId` of `0`, so it is not reproducible without introducing additional code elsewhere that does call it. Our point is that, even if nop never passes `0` to that method, it is presented to consumers as though that is a valid use case. When we take advantage of that use case in our own plugins, that's where the problem comes in.

From where we're standing, the fact that the API surface allows this argument points to a problem with the service, not the way we're using it. If that API surface needs to change such that the `customerId` argument requires a value greater than `0` or it throws an exception/kills the query, that's completely fine with us. But the service should make it clear to consumers what is and what isn't an acceptable use case.

**Comment by glhays** [comment]
@evan-at-tusksoft 

OrderProcessingService passes a valid customeId.
CustomerModelFactory passes a valid customerId.
OrderModelFactory passes a valid customerId.

To the GetRewardPointsHistory method, where the defaulted 0 is overridden.

So are you just stating that the method signature is miss-leading with the default customerId = 0 if there is no customerId explicitly passed to the method. 

If so then why not offer a better solution of how it should work in a pull request.
What if the current solution works for many others not using your custom coding?

I am just trying to understand here for my own use of NopCommerce.
