### ISSUE TITLE
Remove _OldInternetExplorerWarning view

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#6758]
nopCommerce version: 
4.60.3

Steps to reproduce the problem: 
1. go to facebook and message anyone your website. I did www.CoJoCreates.com
2. You get the Orange https://www.cojocreates.com/Themes/CoJoCreates/Content/images/ie_warning.jpg
![image](https://github.com/nopSolutions/nopCommerce/assets/20989983/e8093c46-9ae4-4b33-89ab-de82fa0b543d)
3. I traced it back to _OldInternetExplorerWarning.cshtml
4. I removed the content of _OldInternetExplorerWarning.cshtml
5. Saved
6. Reposted the URL and it is working now
<img width="242" alt="Screenshot 2023-07-08 161633" src="https://github.com/nopSolutions/nopCommerce/assets/20989983/69d6d4c9-1d06-4363-8371-6057d825beda">

Posted here:
https://www.nopcommerce.com/en/boards/topic/97220/facebook-link-is-orange#307111

**Comment by Ochapparel** [comment]
Thanks!

**Comment by exileDev** [comment]
Closed #6758
