### ISSUE TITLE
Microservices

### ISSUE THREAD

**Issue by ekjuanrejon** [nopSolutions/nopCommerce#6765]
nopCommerce version: 
4.60.0
Steps to reproduce the problem: 
Any plans to convert this into microservices?

**Comment by AndreiMaz** [comment]
@ekjuanrejon No, currently we do not plan these changes

**Comment by ekjuanrejon** [comment]
what's the reason of not using micro-services, dapr and project tye?

**Comment by AndreiMaz** [comment]
What's the reason of using micro-services? Specifically in nopCommerce

**Comment by ekjuanrejon** [comment]
leaner development. it can bee seen that nop has matured to the stage of micro-service. The domains are clearly visible, schedule tasks, settings, etc..

**Comment by ekjuanrejon** [comment]
should setting service be using json serialization/deserialization and stop using reflection?
