### ISSUE TITLE
GetOrderTotalDiscountAsync performance

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6766]
nopCommerce version: All

Steps to reproduce the problem: 
When you have lot of discounts; for example 30K. Once the GetOrderTotalDiscountAsync inside OrderTotalCalculationService.cs is called, all discounts will be retrieved, then for each discount it will validate if it is applied by customer by calling (_discountService.ValidateDiscountAsync()) method. Inside ValidateDiscountAsync it will parse the applied discounts each time for each the 30K discount. Why not just get the applied discounts codes for the customer and find them inside the 30K. This will help to improve the performance alot.

**Comment by ahmadkq** [comment]
Initialty, i suggest to change the code inside GetOrderTotalDiscountAsync the as follwoing:

if (allDiscounts != null)
            {
                **var couponCodesToValidate = await _customerService.ParseAppliedDiscountCouponCodesAsync(customer);**

                foreach (var discount in allDiscounts)
                    if (!_discountService.ContainsDiscount(allowedDiscounts, discount) &&
                        **(await _discountService.ValidateDiscountAsync(discount, customer, couponCodesToValidate)).IsValid**)
                    {
                        allowedDiscounts.Add(discount);
                    }
            }

**Comment by ahmadkq** [comment]
@AndreiMaz What do you think?

**Comment by skoshelev** [comment]
Hi @ahmadkq. Thank you, this is a good idea for optimization

**Comment by ahmadkq** [comment]
@skoshelev You are welcome, by the way, the same optimization can be doen for the GetOrderSubtotalDiscountAsync

**Comment by ahmadkq** [comment]
@akinniyThomas @skoshelev Don't create a list for appliedDiscounts as it will already created and returned when call GetPreferredDiscount, otherwise the list will be created twice.

Change the bellow code
 **var appliedDiscounts = new List<Discount>();**
            var discountAmount = decimal.Zero;
            if (_catalogSettings.IgnoreDiscounts)
                return (discountAmount, appliedDiscounts);

to 

var discountAmount = decimal.Zero;
if (_catalogSettings.IgnoreDiscounts)
    **return (discountAmount, new List<Discount>());**

at the end, you can define the appliedDiscounts variable

 **var appliedDiscounts = _discountService.GetPreferredDiscount(allowedDiscounts, orderSubTotal, out discountAmount);**

**Comment by skoshelev** [comment]
Closed #6766

**Comment by kava81** [comment]
may also need to be done in PriceCalculationService.cs, ShoppingCartModelFactory.cs ? thanks

**Comment by skoshelev** [comment]
Hi @kava81. Yes, it seems that all places where the ValidateDiscountAsync(Discount discount, Customer customer) method is called should be reviewed and rewritten to use ValidateDiscountAsync(Discount discount, Customer customer, string[] couponCodesToValidate)
