### ISSUE TITLE
All system file images corrupted after changing the image storge location.  

### ISSUE THREAD

**Issue by manwarhossen** [nopSolutions/nopCommerce#6767]
**nopCommerce version:** 4.3   (No Source code)
Products : 17K
**Nop.web > images** : all images were in good condition before changing.

**Steps to reproduce the problem:**
Images were on system file. But some reason I have to changed the images location to  Database from Media Setting. Once changes to Database all **Nop.web > images** sizes turn 0kb (corrupted). After that All products images are not showing at all. 
**Nop.web > images > thumbs** all images are in good conditions.  

**Tried solutions but not working:** 
1. clear cache and Restart the application.
2. Change the images location to file system.
(Media setting > Pictures are stored into : filesystem)

**Comment by RomanovM** [comment]
@manwarhossen I just checked this feature and it works correctly, both on the latest 4.60 and on 4.30. 
Even if you have many images, they move pageable, so at least some of them should have been moved successfully. 
BTW, what you mean by **Nop.web > images**? When moving images to db, all images from _wwwroot/images_ should be deleted, instead the picture binary data is stored in the db table.

**Comment by manwarhossen** [comment]
[RomanovM](https://github.com/RomanovM) thanks for your reply. Sorry for the mistake. I wanted to mean **www/images** not Nop.web > images.

**Yes, you are right.**  When moving images to db, all images from wwwroot/images should be deleted. 


**GIVING YOU THE  SCENARIO :**
**Stage 1:** Images were in filesystem in the production server (20K Products). Everything working fine.

**Stage 2:** moving images to db.  All images were deleted from  wwwroot/images. Images must be show in the front end. But for me not a single images were showing.

**Stage 3:** Moved images to filesystem. Images created in  the wwwroot/images, but 0kb size. Still not showing.

**Question are:**
1. Where images gone?
2. how to get back images?

All  images size was about 13GB. SQL express community (free version support 10GB). Before & after there was no warning about databse space limit.  

Is because of space capacity limitation  dose the system broken?

**Comment by DmitriyKulagin** [comment]
The system was definitely compromised by database size limitations. In this case, you must control the available space for transferring images yourself.
