### ISSUE TITLE
FacebookPixel IP address issue

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6768]
nopCommerce version: All

Steps to reproduce the problem: 
Sometimes, the facebook pixel plugin faild to send the event, I changed the code to log the response error, the error is related to IP address as shown in the attachment. The IP address contains 2 IPs!. What is the issue here?

![image](https://github.com/nopSolutions/nopCommerce/assets/26964283/249a983a-911e-49ea-9887-3929fed27457)

**Comment by AndreiMaz** [comment]
Let's ensure that passed IP address is valid when passing to Facebook - IPAddress.TryParse

**Comment by skoshelev** [comment]
Hi @ahmadkq. I analyzed the existing code, and so far I do not see a theoretical possibility to get such a problem. Tell me, please, did you change the WebHelper.GetCurrentIpAddress method, or maybe you have a third-party plugin that can change this code, since the [standard implementation](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/WebHelper.cs#L105) seems to be unable to return a double IP

**Comment by ahmadkq** [comment]
@skoshelev Nothing changed in the source code and I don't think any third-party plugin override it, i am using nop-templates plugins. This is the implementaiton for the GetCurrentIpAddress

public virtual string GetCurrentIpAddress()
        {
            if (!IsRequestAvailable())
                return string.Empty;

            var result = string.Empty;
            try
            {
                //first try to get IP address from the forwarded header
                if (_httpContextAccessor.HttpContext.Request.Headers != null)
                {
                    //the X-Forwarded-For (XFF) HTTP header field is a de facto standard for identifying the originating IP address of a client
                    //connecting to a web server through an HTTP proxy or load balancer
                    var forwardedHttpHeaderKey = NopHttpDefaults.XForwardedForHeader;
                    if (!string.IsNullOrEmpty(_appSettings.HostingConfig.ForwardedHttpHeader))
                    {
                        //but in some cases server use other HTTP header
                        //in these cases an administrator can specify a custom Forwarded HTTP header (e.g. CF-Connecting-IP, X-FORWARDED-PROTO, etc)
                        forwardedHttpHeaderKey = _appSettings.HostingConfig.ForwardedHttpHeader;
                    }

                    var forwardedHeader = _httpContextAccessor.HttpContext.Request.Headers[forwardedHttpHeaderKey];
                    if (!StringValues.IsNullOrEmpty(forwardedHeader))
                        result = forwardedHeader.FirstOrDefault();
                }

                //if this header not exists try get connection remote IP address
                if (string.IsNullOrEmpty(result) && _httpContextAccessor.HttpContext.Connection.RemoteIpAddress != null)
                    result = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();
            }
            catch
            {
                return string.Empty;
            }

            //some of the validation
            if (result != null && result.Equals(IPAddress.IPv6Loopback.ToString(), StringComparison.InvariantCultureIgnoreCase))
                result = IPAddress.Loopback.ToString();

            //"TryParse" doesn't support IPv4 with port number
            if (IPAddress.TryParse(result ?? string.Empty, out var ip))
                //IP address is valid 
                result = ip.ToString();
            else if (!string.IsNullOrEmpty(result))
                //remove port
                result = result.Split(':').FirstOrDefault();

            return result;
        }

**Comment by skoshelev** [comment]
I see, please next time specify the version of nopCommerce on which the problem occurs. Since starting from version 4.50 the standard implementation looks like this: 

```cs
public virtual string GetCurrentIpAddress()
{
    if (!IsRequestAvailable())
        return string.Empty;

    if(_httpContextAccessor.HttpContext.Connection?.RemoteIpAddress is not IPAddress remoteIp)
        return "";

    if(remoteIp.Equals(IPAddress.IPv6Loopback))
        return IPAddress.Loopback.ToString();

    return remoteIp.MapToIPv4().ToString();
}
```

and cannot cause the problem you describe
