### ISSUE TITLE
Rounding (away from zero). Configurable (solution attached)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#677]
Seems like currently the tax calculation of NC doesn't include rounding based on the sub-total. Here is an example: 

If the Sales Order Sub-total is: $100.05 
Tax percentage is: 10% 

The calculation result from current NC is: $10.00, while if we consider the the most frequently used rounding (rounding to 1 when great than 0.5), it should be $10.01 

Solution: http://www.nopcommerce.com/boards/t/35157/suggestion-rounding-of-tax.aspx

See related work item - https://github.com/nopSolutions/nopCommerce/issues/1424

Contribution: https://github.com/nopSolutions/nopCommerce/pull/1983

**Comment by AndreiMaz** [comment]
done
