### ISSUE TITLE
ClearShoppingCartAsync optimization

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6779]
nopCommerce version: All

Steps to reproduce the problem: 
Why do we need to call **customer.HasShoppingCartItems = !IsCustomerShoppingCartEmpty(customer);**. For sure the HasShoppingCarItems property should be false. IsCustomerShoppingCartEmpty method will hit the database and it is not needed. Just make **customer.HasShoppingCartItems = false;**

**Comment by skoshelev** [comment]
Hi @ahmadkq The ClearShoppingCartAsync method removes the cart only for the specified store, this does not mean that it does not have a cart left in other stores, we cannot just set it to false
