### ISSUE TITLE
DeleteShoppingCartItemAsync & AddToCartAsync optimization

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6780]
nopCommerce version: All

Steps to reproduce the problem: 

DeleteShoppingCartItemAsync and AddToCartAsync methods has this code:

**customer.HasShoppingCartItems = !IsCustomerShoppingCartEmpty(customer);
            await _customerService.UpdateCustomerAsync(customer);**

No need to call UpdateCustomer everytime and hit the database, we can optimize it as follwoing

            **var hasShoppingCartItems = !IsCustomerShoppingCartEmpty(customer);
            if (hasShoppingCartItems != customer.HasShoppingCartItems)
            {
                customer.HasShoppingCartItems = hasShoppingCartItems;
                await _customerService.UpdateCustomerAsync(customer);
            }**

**Comment by skoshelev** [comment]
Hi @ahmadkq. Thanks, that's a good suggestion.

**Comment by exileDev** [comment]
Closed #6780
