### ISSUE TITLE
MigrateShoppingCartAsync optimization

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6782]
nopCommerce version: 

Steps to reproduce the problem: 
I can't see any need to call await _customerService.UpdateCustomerAsync(toCustomer);, removing it will increase the performance

**Comment by skoshelev** [comment]
Hi @ahmadkq. I agree here, the UpdateCustomerAsync method call is really not needed

**Comment by exileDev** [comment]
Closed #6782
