### ISSUE TITLE
GetRecurringCycleInfoAsync optimization

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6783]
nopCommerce version: All

Steps to reproduce the problem: 
Make **var conflictError = await _localizationService.GetResourceAsync("ShoppingCart.ConflictingShipmentSchedules");** to be ouside the for loop

**Comment by skoshelev** [comment]
Hi @ahmadkq. This change will not greatly affect performance, since all locales are cached, but you are right, it is better to get it out of the loop
