### ISSUE TITLE
CopyProductService optimization

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6784]
nopCommerce version: All

Steps to reproduce the problem: 

Do we realy need to call await _productService.UpdateProductAsync(productCopy); inside CopyWarehousesMappingAsync, CopyDiscountsMappingAsync, CopyProductAsync ?

**Comment by skoshelev** [comment]
Hi @ahmadkq. No, in this case, the call to the UpdateProductAsync method is superfluous and remained from previous implementations when it was really needed

**Comment by exileDev** [comment]
Closed #6784
