### ISSUE TITLE
DeleteInactiveCustomersTask deletes system records

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6787]
nopCommerce version: 4.60

> After much investigation, the cause of the problem was the account for the built-in system record used for background tasks had been deleted.
> Then after a lot more digging around I noticed If I click in scheduled tasks - "Delete inactive customers (GDPR)" it deletes the customer record for the built-in search engine.
> I have tried it three times and it definitely does delete the account.

Source: https://www.nopcommerce.com/boards/topic/97646/built-in-system-record-used-for-background-tasks

We should add a check for customer roles in this scheduled task.

**Comment by exileDev** [comment]
Closed #6787
