### ISSUE TITLE
Rename "Downloadable product" hint

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6788]
Some merchants upload large files (e.g. 50+ MB) to database as downloadable products. In this case a nopCommerce store becomes slow or the appropriate product details page (in admin area) cannot be loaded.

Obviously, that such large files should be upload to some FTP or file sharing hosting. And then merchants should use the "Use download URL" functionality instead of uploading it to the database.

Considering that we do not support such large files (for storing in our database) it's better to rename the hint of the "Downloadable product" to "Check if the product is downloadable. When customers purchase a downloadable product, they can download it direct from your store. The link will be visible after checkout. Please note that it's recommended to use 'Use download URL' feature for large files"

**Comment by Zahidd02** [comment]
Hi Andrei, so if I am understanding this correctly - You want to change the yellow field in the picture to "Check if the product is downloadable. When customers purchase a downloadable product, they can download it direct from your store. The link will be visible after checkout. Please note that it's recommended to use 'Use download URL' feature for large files" correct?

**Comment by AndreiMaz** [comment]
@Zahidd02 You're absolutely right

**Comment by Zahidd02** [comment]
Hi Andrei, I have created a PR. Any updates?
