### ISSUE TITLE
Product search by manufacturer and category name includes deleted entries

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6790]
nopCommerce version: 4.60

> The SearchProductsAsync method is not taking into account deleted Categories and Manufactures, when AllowCustomersToSearchWithCategoryName and/or AllowCustomersToSearchWithManufacturerName are true.

Source: https://www.nopcommerce.com/boards/topic/97641/by-design-or-bug

Probably we should not only filter by `Deleted`, but also take into account all filters for categories (ACL and store mappings, `Published`, etc), like in [this method](https://github.com/nopSolutions/nopCommerce/blob/4.60-bug-fixes/src/Libraries/Nop.Services/Catalog/CategoryService.cs#L240). Same for manufacturers. Let's think it out.

**Comment by exileDev** [comment]
Closed #6790
