### ISSUE TITLE
Sales Summary Report - incorrect profit calculation

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6793]
nopCommerce version: 4.60

> with new installation with sample data, create a product with product cost.
> checkout the new product.
> view the sales summary report group by day. The profit and order total are the same when the profit should be lesser than order total.
> 
> The problem happens when there are multiple orders in a day, the profit calculation is done by selecting the top 1 order of that day.

Source: https://www.nopcommerce.com/boards/topic/97650/sales-summary-report-profit-calculation-and-filtering

**Comment by exileDev** [comment]
Closed #6793
