### ISSUE TITLE
Exception after migrating from 4.50 to 4.60 with MySQL database

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#6796]
nopCommerce version: 4.60

Steps to reproduce the problem: 
1. Install fresh 4.50 and try to update to 4.60

![nop-migrate-to-460_mysql](https://github.com/nopSolutions/nopCommerce/assets/37818094/db47b11b-871c-47dc-a493-75dff464d533)

How to fix:
1. Apply MySqlDateTimeWithPrecisionMigration migration after DataMigration

**Comment by skoshelev** [comment]
Hi @holydk. Thanks, I fixed the problem, I think that the dependence was not on DataMigration, but on SchemaMigration, but this does not change the essence.
