### ISSUE TITLE
Admin UI errors after removing kendo

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#6797]
nopCommerce version: develop

Repoduced after 79205f04b4dd6e0ffb33e5828e32bc6e4aec3e4f

1. No pagination buttons in tables
![image](https://github.com/nopSolutions/nopCommerce/assets/37818094/f2161900-0fe7-4c1c-82b0-0dea059aa27b)
2. **Customer roles** field bug on Customer edit page
![image](https://github.com/nopSolutions/nopCommerce/assets/37818094/64c19d48-29af-41c4-b34c-b8167b8974e8)

**Comment by exileDev** [comment]
Closed #6797
