### ISSUE TITLE
Add widget zone to _OrderDetails.Info

### ISSUE THREAD

**Issue by Maruf61** [nopSolutions/nopCommerce#6798]
nopCommerce version: 4.70

Steps to reproduce the problem: 
There is no widget zone under Admin Area > _OrderDetails.Info, i would like to inject some custom components below payment info.

**Comment by AndreiMaz** [comment]
@Maruf61 Thanks a lot for suggestion! I've just created a more general work item - https://github.com/nopSolutions/nopCommerce/issues/6799
