### ISSUE TITLE
Widgets support for "nop-card"

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6799]
The original suggested was posted at https://github.com/nopSolutions/nopCommerce/issues/6798. But in order to avoid logic duplication for all nop-cards, let's add a general way to add widgets before and after any "card"

So we have to extend the "NopCardTagHelper" class to invoke two new widget zones (before and after the card). Let's pass a specified "NAME_ATTRIBUTE_NAME" as parameter to it, so it could be used to identify what card is rendered now.

**Comment by Zahidd02** [comment]
Hi Andrei, where is the this card being rendered?

**Comment by exileDev** [comment]
Closed #6799
