### ISSUE TITLE
Buy 2 get 1 free discounts. Option to apply multiple times (M of N)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#680]
Version 3.50 already has some enhancements. It allows to specify to which quantity a discount is applied. But it has quite limited functionality (not applied multiple times, not automatically added) - http://www.nopcommerce.com/boards/t/33595/buy-2-get-1-free-buying-just-1-means-that-1-is-free.aspx 

We already have "Maximum discounted quantity" field. Let's add one more field beside it - "of each" where a store owner could specify discounted quantity of "each" N items. It should also be nullable

**Comment by AndreiMaz** [comment]
duplicated
