### ISSUE TITLE
Manually changing an order from Pending to Processing does not send the store/customer emails

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#6801]
nopCommerce version: 4.60.3

Steps to reproduce the problem: Manually changing an order from Pending to Processing does not send the store/customer emails. It adds the note to the order to state the status has been changed, but the customer doesn't receive an email confirming the order.

This scenario comes around for instance if an order is placed, payment is taken and marked as paid, but due to some issues  (i.e. Deadlock), the customer emails aren't sent and the order stays as pending.

Because the order is showing paid, changing the order status doesn't do anything, apart from of course changing the status lol, but because something went wrong during the order process, the customer / store emails haven't been sent, even though the order was marked as paid.

Ideally there should be some form of check to see if the emails have been sent, or if the order notes contain ""Order paid" email"... if so, do nothing but update the notes, otherwise, send the emails.

**Comment by untiedshoes** [comment]
Ignore for now

**Comment by untiedshoes** [comment]
Ignore for now

**Comment by AndreiMaz** [comment]
It's by design. There is a hint - "This option is only for advanced users (not recommended to change manually). All appropriate actions (such as inventory adjustment, **sending notification emails**, reward points, gift card activation/deactivation, etc) should be done manually in this case."
