### ISSUE TITLE
Blog posts. Include only one language in multilingual sitemaps

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6806]
nopCommerce version: 4.60.4

The issue is described at https://www.nopcommerce.com/en/boards/topic/97693/multilingual-blog-post-sitemap-double-language-v4602

So we have to:
1. There should be only one <url> record (for one active language)
2. Do not include xhtml:link rel="alternate" line

For example, in this example on our forums the sitemap should have the following record

```
<url>
    <loc>{website}/en/wonderful-blog</loc>
    <changefreq>weekly</changefreq>
    <lastmod>2022-09-14</lastmod>
  </url>
```

**Comment by skoshelev** [comment]
Closed #6806
