### ISSUE TITLE
ModelPrepared event when using RenderPartialViewToString method 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6808]
nopCommerce version: develop

See explanation in https://www.nopcommerce.com/boards/topic/97696/modelpreparedevent-is-called-after-the-view-starts-processing

**Comment by noptools** [comment]
Any thoughts about adding this to 4.70?  It would be nice to be able to handle events to intercept things, because as mentioned in code
        private void PublishModelPrepared<TModel>(TModel model)
        {
            //Components are not part of the controller life cycle.
            //Hence, we could no longer use Action Filters to intercept the Models being returned

and as I mentioned in the topic
  "it's my preference to handle the event rather than override a method, since others might also override that method ..."

**Comment by skoshelev** [comment]
Closed #6808

**Comment by noptools** [comment]
In testing this, I created a plugin that handles ModelPreparedEvent
```
public class EventConsumer :
    IConsumer<ModelPreparedEvent<BaseNopModel>>
{
...
public async Task HandleEventAsync(ModelPreparedEvent<BaseNopModel> eventMessage)
{
    if (eventMessage.Model is CheckoutShippingAddressModel checkoutShippingAddressModel)
    {
        ...
        return;
    }

    if (eventMessage.Model is CheckoutShippingMethodModel checkoutShippingMethodModel)
    {
        ...
        return;
    }
}
```

In regular checkout it works fine.  In One Page checkout, it works, but **it's being called twice** for each step.

To reproduce:
ordersettings.onepagecheckoutenabled	True
ordersettings.displaypickupinstoreonshippingmethodpage	True  (probably not relevant, but FYI)

During Checkout, ...
Billing address section, clear "Ship to the same address", select billing address and "Continue"
 called twice where eventMessage.Model is CheckoutShippingAddressModel
Select shipping address and "Continue"
 called twice where eventMessage.Model is CheckoutShippingMethodModel

Example Stack traces are attached for after select billing address.

**Comment by skoshelev** [comment]
Hi @noptools. I'll check. Now it seems that the problem is not in this commit, most likely the rendering method is called twice, but the question "why" is still open

**Comment by skoshelev** [comment]
Hi @noptools. Unfortunately, it was not possible to find a way to suppress the extra event in this case, but we did not find a problem with the fact that the event is called twice, so we decided to leave everything as it is for now

**Comment by noptools** [comment]
I disagree with "not find a problem with the fact that the event is called twice".  You don't know how "expensive" the operation being performed by the handler is.  E.g., call an external web service.  Additionally, it probably indicates a problem where core code "calculations" may also be getting called twice (e.g. price calculation, with its discount, tier, tax, etc. is expensive.)

**Comment by skoshelev** [comment]
Of course, I admit that even for such an event the logic may be quite voluminous or resource-consuming, but in this case I think caching will solve the issue. As for the problem with other calls, I don’t think it exists, since at this point we are forced to add an additional call to maintain the correct sequence of data preparation
