### ISSUE TITLE
Add FollowUsLinks Token to all message templates

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#681]
Adding a FollowUsLinks token to message templates will allow stores to connect more with customers and provide an easy mechanism for adding social links to messages 

Source: http://www.nopcommerce.com/boards/t/33962/feature-request-add-followuslinks-token-to-all-message-templates.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
