### ISSUE TITLE
App settings page. Fix a hyperlink to our documentation

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6810]
nopCommerce version: 4.60

Steps to reproduce the problem: 
1. Go admin area > configuration > settings > app settings (/Admin/Setting/AppSettings)
2. Check the description at the top of the page
3. It points to a broken URL (https://docs.nopcommerce.com/en/developer/tutorials/description-of-settings-from-appsettings-json-file-and-NopConfig-class.html) instead of https://docs.nopcommerce.com/en/developer/tutorials/appsettings-json-file.html

P.S. Ensure that all links are valid at \Nop.Services\Common\NopLinksDefaults.cs

**Comment by skoshelev** [comment]
Closed #6810
