### ISSUE TITLE
Mistake in the "Adding CSS and JS resource files into nopCommerce Plugin" documentation page

### ISSUE THREAD

**Issue by aglasencnik** [nopSolutions/nopCommerce#6812]
There is a mistake in the documentation on the page for: "Adding CSS and JS resource files into nopCommerce Plugin", in the first line:
```
//Loading CSS file
@NopHtml.AddCssFileParts(ResourceLocation.Head, "~/Plugins/{PluginName}/Content/{CSSFileName.Css}", excludeFromBundle = false);

//Loading js file
//Third parameter value indicating whether to exclude this script from bundling
@NopHtml.AddScriptParts(ResourceLocation.Footer, "~/Plugins/{PluginName}/Scripts/{JSFileName.js}", excludeFromBundle: true);
```
As you can see in the first line, The `ResourceLocation` doesn't exist for the `AddCssFileParts` method. Also the `excludeFromBundle ` in the first line has a: "=" when it must be a: ":".

**Comment by AndreiMaz** [comment]
@aglasencnik Thanks a lot! Moved to our documention repository - https://github.com/nopSolutions/nopCommerce-Docs/issues/442 (not related to the core repository)
