### ISSUE TITLE
Sendinblue plugin issue

### ISSUE THREAD

**Issue by atiq-bs23** [nopSolutions/nopCommerce#6813]
nopCommerce version: 4.5

Steps to reproduce the problem: 
1. Create a API key (V3),
2. Put it on Sendinblue configuration page (https://YOUR_STORE.com/Admin/Sendinblue/Configure)
3. You will get some errors.
![image](https://github.com/nopSolutions/nopCommerce/assets/113086917/0eed141b-22d4-42be-963b-c532b1500d03)

I have contacted with Bravo support and below is their response.
_After reviewing your account, I noticed that this error is occurring because the API key "MyStore", being used to complete the integration is incorrect. This happens because the API key that was given to you at the moment that the key was created is the complete version and the key that is visible [here](https://app.brevo.com/settings/keys/api) is only an abbreviation of the original key and can not be use for the plugin. 
 
In the case, that you are using the abbreviation, the plugin would not work causing such error, for this reason. Could you please create another API key and copy the one that is originally given at the moment of creation. Once, this has been done the integration, should work correctly._

Can you please check the issue ?

**Comment by AndreiMaz** [comment]
@atiq-bs23 It works absolutely fine. When the key is created, you can see the full key value. Just copy it here. You cannot copy it later by visiting https://app.brevo.com/settings/keys/api (you can do it only at the moment of creation)
