### ISSUE TITLE
problem with resolving view for some action methods

### ISSUE THREAD

**Issue by MohammadAnsari98** [nopSolutions/nopCommerce#6819]
There is problems with some action methods which don't have correct view for processing request and also there is a controller named ExternalAuthenticationController which seems to be not useful because all functionality of it also is inside AuthenticationController 
One of the side effects of this problem apperas when we start to using rider ide with nopcommerce which show unfound views as error and also visual studio goto view dosn't work 
[https://github.com/nopSolutions/nopCommerce/pull/6818](https://github.com/nopSolutions/nopCommerce/pull/6818)

this pull request remove erros about finding correct views

**Comment by AndreiMaz** [comment]
@MohammadAnsari98 Thanks a lot! But we do not support or adjust nopCommerce for third-party IDE such as Rider. It works absolutwly fine without any errors out of the box

P.S. I've just created a separate task for ExternalAuthenticationController - https://github.com/nopSolutions/nopCommerce/issues/6820. It's better to have separate work items for different tasks

**Comment by MohammadAnsari98** [comment]
@AndreiMaz the problem is not about rider or ide .
There is  a problem with finding views in some  if statemens in action methods. 
Because the part of code which has problem typically doesn't executs we  don't normally see the problem please check the code itself with any ide and you will see their is a problem

**Comment by AndreiMaz** [comment]
@MohammadAnsari98 Could you please provide a list of steps to reproduce the issue? The code works fine without your changes
