### ISSUE TITLE
Cost price for combinations

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6821]
nopCommerce version: All

Steps to reproduce the problem: 
Currently, there is a product cost for product not for product combination. I know there is cost and override for attribute itself such as color and size but there is nothing for combination. Let us say we have iPhone product with 2 colors and 2 capacities. Each combination may have its own cost and its own price, it is very hard to do this using a cost price and adjustment for each attribute (color & size). I suggest to add a cost for each combination beside the price that is already exist. Also, to add visible for the combination in case to hide one of the combinations.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we've decided not to implement it - https://github.com/nopSolutions/nopCommerce/issues/3437
