### ISSUE TITLE
ProcessCustomerRolesWithPurchasedProductSpecifiedAsync method performance in OrderProcessingService.cs

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6824]
nopCommerce version: All

Steps to reproduce the problem: 
Remove await _customerService.UpdateCustomerAsync(customer); from ProcessCustomerRolesWithPurchasedProductSpecifiedAsync method as it is not needed

**Comment by skoshelev** [comment]
Closed #6824
