### ISSUE TITLE
UpdateOrderTotalsAsync Performance in OrderProcessingService.cs

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6825]
nopCommerce version: 

Steps to reproduce the problem: 
I can see many UpdateOrderAsync may be called in UpdateOrderTotalsAsync. First time inside the UpdateOrderTotalsAsync, second time when call CheckOrderStatusAsync and third time inside SetOrderStatusAsync that called from CheckOrderStatusAsync. Is there a way to reduce this and call the update once as it will enahnce the perfomrance?

**Comment by skoshelev** [comment]
Closed #6825
