### ISSUE TITLE
Event & Log performance enhancement

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6827]
nopCommerce version: All

Steps to reproduce the problem: 
NopCommerce has lot of event publisher, logs and activity log. Why not making some of them to be as Fire and forget. For example, we can do it for logs and make the page not to wait till the log is finished. Another example when calling InsertActivityAsync. For event publisher, some of events can be done with aproach fire and forget. I have tried this by creating the follwoing new interface and implementaiton:

public partial interface IEventPublisherEx
    {
         /// <summary>
         /// Publish event to consumers
         /// </summary>
         /// <typeparam name="TEvent">Type of event</typeparam>
         /// <param name="event">Event object</param>
         Task PublishAsync<TEvent>(TEvent @event);
     }

public partial class EventPublisherEx : IEventPublisherEx
    {
        #region Methods

        /// <summary>
        /// Publish event to consumers
        /// </summary>
        /// <typeparam name="TEvent">Type of event</typeparam>
        /// <param name="event">Event object</param>
        /// <returns>A task that represents the asynchronous operation</returns>
        public virtual async Task PublishAsync<TEvent>(TEvent @event)
        {
            //get all event consumers
            var consumers = EngineContext.Current.ResolveAll<IConsumer<TEvent>>().ToList();

            foreach (var consumer in consumers)
            {
                try
                {
                    //Fire and forget
                    _ = Task.Run(() => consumer.HandleEventAsync(@event));
                }
                catch (Exception exception)
                {
                    //log error, we put in to nested try-catch to prevent possible cyclic (if some error occurs)
                    try
                    {
                        var logger = EngineContext.Current.Resolve<ILogger>();
                        if (logger == null)
                            return;

                        await logger.ErrorAsync(exception.Message, exception);
                    }
                    catch
                    {
                        // ignored
                    }
                }
            }
        }

        #endregion
    }

What do you think?

**Comment by AndreiMaz** [comment]
@ahmadkq Thanks a lot for suggestion. But we think it's better to wait for each event, so leaving it for customization
