### ISSUE TITLE
Sepration of admin panel and frontend language

### ISSUE THREAD

**Issue by MohammadAnsari98** [nopSolutions/nopCommerce#6830]
I think it will be good idea to seprate language settings for admin panel and frontend (we can achieve this in wordpress by changing user language)

Because in many case admins of website are comfortable with English language but they want to show content to the users with other language 

It will be helpful to add such feature to the nopcommerce to handle admin language separately

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion! But it duplicates already created suggestion - https://github.com/nopSolutions/nopCommerce/issues/3914
