### ISSUE TITLE
Add tags implementation for Topics

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6831]
current nopCommerce version: 4.60.4

Tags are a great feature to find content or even when transitioning to a new site and we may get 404 errors. Take for example I create a topic named "Downloads" and I previously used a URL of "download". If I could add TAGS to TOPICS then this could help people find the content they are looking for. Just as you have TAGS available for the catalog (products), please consider extending other areas such as TOPICS as well.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
