### ISSUE TITLE
[Bug] Can't disable add to wishlist button from settings

### ISSUE THREAD

**Issue by MohammadAnsari98** [nopSolutions/nopCommerce#6832]
![image](https://github.com/nopSolutions/nopCommerce/assets/25693849/d4c72945-8f18-4624-90fa-fc2202a6346b)

nopCommerce version: 4.60 - current github version

Steps to reproduce the problem: 
Go to [Settings ](https://admin-demo.nopcommerce.com/Admin/Setting/AllSettings) and find **producteditorsettings.disablewishlistbutton** make it true and save

clear cache and open frontend and nothing will be change

probelm:
By mistake nopcommerce reads value for DisableWishlistButton from product table !!!

![image](https://github.com/nopSolutions/nopCommerce/assets/25693849/7fb226a9-a041-4708-bcb3-611213fbfe8f)

You know when we updating settings it will change values in other table

I think  we need 2 pull request 
first for fixing this bug so nopcommerce will read this settings from catalogsettings
second remove this column from entity and producteditorsettings.disablewishlistbutton from everwhere

I have pull request for first step 
i don't know about backward compability so inform me if i can make other pull request and delete disablewishlistbutton  stuff 

https://github.com/nopSolutions/nopCommerce/pull/6833

Please Review This and inform me with any problems

**Comment by AndreiMaz** [comment]
@MohammadAnsari98 Everything works fine. "producteditorsettings" is not related to the public store, it's used to manage this setting visibility in admin area.
