### ISSUE TITLE
VAT validation for UK

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6837]
nopCommerce version: 4.60.4

Steps to reproduce the problem: 

Looks like VAT validation is not supported for UK anymore by the default online service we're using. According to it (https://ec.europa.eu/taxation_customs/vies/#/vat-validation):

**Important Disclaimer:**
As of 01/01/2021, the VoW service to validate UK (GB) VAT numbers ceased to exist while a new service to validate VAT numbers of businesses operating under the Protocol on Ireland and Northern Ireland appeared. These VAT numbers are starting with the “XI” prefix, which may be found in the “Member State / Northern Ireland” drop down under the new entry “XI-Northern Ireland”. Moreover, any quote of “Member State” is replaced by “Member State / Northern Ireland” and any quote of “MS” is replaced by “MS / XI”. All traders seeking to validate UK (GB) VAT numbers may address their request to the UK Tax Administration.

Although UK merchants can always manually validate entered VAT numbers, it's better to support auto-validation. Let's choose a new service:
1. For UK only. For example, https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0/oas/page#section/Versioning
2. For all countries (hence replace ec.europa.eu completely)

**Comment by skoshelev** [comment]
Closed #6837
