### ISSUE TITLE
Documentation still mentions Kendo UI as a requirement to developer with nopCommerce

### ISSUE THREAD

**Issue by Tony20221** [nopSolutions/nopCommerce#6838]
Documentation still mentions Kendo UI as a requirement to developer with nopCommerce.

https://docs.nopcommerce.com/en/developer/tutorials/instruction-on-how-to-start-developing-on-nopcommerce.html

**Comment by AndreiMaz** [comment]
Everything is correct. The latest stable version (4.60.4) still uses KendoUI. It's been removed in the upcoming version 4.70.0
