### ISSUE TITLE
Broken HTML structure in page source

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6839]
nopCommerce version: 4.60

> To replicate this defect:
> 
> Using Chrome Version 116.0.5845.111 (Official Build) (64-bit), Win 10
> https://demo.nopcommerce.com/
> 
> Right click > View source. Scroll to the bottom of the response. There is no closing </body> or </html> tags. (Possible this is a defect within the script bundling?)

Source: https://www.nopcommerce.com/boards/topic/97850/closing-bodyhtml-tags-dont-appear-included-in-the-response

**Comment by exileDev** [comment]
Closed. This is the result of html-minification. You can disable it on the General settings page in the admin panel. There are no errors when checking via validator.w3.org
