### ISSUE TITLE
Popup and notifications widget (implement as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#684]
It should allow a store owner to manage custom notifications for customers 

Source: http://www.nopcommerce.com/boards/t/33469/custom-text-on-top-of-shopping-cart-to-inform-customers-about-delivery-on-christmas-payment-gateways-not-functioning-etc.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
