### ISSUE TITLE
'0 plugins and 0 themes have been uploaded' with green bar and no helpful message to cause of issue

### ISSUE THREAD

**Issue by Tony20221** [nopSolutions/nopCommerce#6840]
I cloned the repo, which looks like it's version 4.7 and tried to install the 'Fixed or by weight and by total' plugin and got a '0 plugins and 0 themes have been uploaded' on a green bar. I tried another shipping plugin and got the same issue.

As a new user, this message suggests an error occurred.  A green bar means success. There was no success. There's no message telling me why it wasn't installed.  Searching around it looks like the plugin might not be compatible. This is a plugin from nopCommerce. Are there breaking changes in 4.7 that are causing plugins not to install?
There are some UI/UX issues here.

Do repos usually have the develop branch as the default branch? 

I suggest nopCommerce comes with some installed plugins so new users don't go through these types of instability issues.
WordPress comes with default plugins and it's easy for a user to just check box and hit install and it just works.

**Comment by Tony20221** [comment]
When a plugin doesn't get installed and the app doesn't indicate what the issue is, that's an issue.

**Comment by skoshelev** [comment]
Hi @Tony20221. I do not quite agree with you, since the archive was processed successfully, there is no error. And the fact that the archive did not contain data for installing a plugin or theme for this version of the product is not a mistake, but rather carelessness

**Comment by Tony20221** [comment]
Show a message that the plugin is not compatible with the current version of nopCommerce. Be helpful to the user.
The user can also miss the '0' in the message.
Don't assume the user is a master in nopCommerce and knows every situation. This is not about being careless.
