### ISSUE TITLE
Quantity issue with products that require other product 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6843]
nopCommerce version: develop

Originally reported in https://www.nopcommerce.com/boards/topic/97866/product-requires-other-product-quantity-addupdate-problem

But the issue is not only with the warning. If you try to add more than 1 product again, the required products will be added in less quantity.

Possible related to #6300

**Comment by exileDev** [comment]
Closed #6843

**Comment by RomanovM** [comment]
See also [this topic](https://www.nopcommerce.com/boards/topic/98350/two-bugs-within-related-products).

**Comment by exileDev** [comment]
Closed #6843
