### ISSUE TITLE
Multiselect box display error

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#6844]
nopCommerce version: latest from develop

Steps to reproduce the problem: go to any page that has a multiselect box, select values until the total length of these values exceeds the length of the multiselect box.

**Picture 1**
![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/faff8f14-1397-4ace-a990-90478564dc90)

**Picture 2**
![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/77e76d09-fde8-4ae4-bbd7-1feb4d1c483f)

**Comment by exileDev** [comment]
Closed #6844
