### ISSUE TITLE
request limit

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6845]
https://github.com/nopSolutions/nopCommerce/blob/d76ab2c55df9475bd1e89d902ebdd3797cbca316/src/Presentation/Nop.Web/Areas/Admin/Controllers/ShippingController.cs#L816C24-L816C24

Hi, just for information, in my configuration 2048 is not enough, I put 10240 and works
thanks

**Comment by danFbach** [comment]
Perhaps this view and action should be refactored so that there isn't a form limit issue.
I could see where this could become unmanageable if one defined very many shipping rates.

**Comment by RomanovM** [comment]
We'll leave this for customization. Please see [this comment](https://github.com/nopSolutions/nopCommerce/issues/3411#issuecomment-439314271) for details.
