### ISSUE TITLE
Is there a base path change?

### ISSUE THREAD

**Issue by Alerinos** [nopSolutions/nopCommerce#6847]
Needs to put the system on a domain but as a path.
For example:
``domain.com/shop``
Unfortunately nginx settings:
```
	location /shop {
		proxy_pass http://192.168.1.36:5000;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_cache off;
		proxy_http_version 1.1;
		proxy_buffering off;
		proxy_read_timeout 100s;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
    }
```
Do not work because I still have a redirect to "no-found" or "install".
Is there any minimally invasive way (like config) to change pathbase?

**Comment by RomanovM** [comment]
@Alerinos  Please post your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub only as an issue tracker.

**Comment by Alerinos** [comment]
@RomanovM 
Thank you for contacting me, I believe it is a technical problem. I did not find such a ready-made solution and did it.
You should add ``<base href="~/path"/>` in the head and then ``application.UsePathBase("/path");`.
I think this should be the basic functionality that we can set in appsettings. If you agree then I can prepare a PR.
