### ISSUE TITLE
Web API has swagger exposed to all even with store closed

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6848]
4.60.04

I have your Web API plugin I purchased. I'm implementing it in my site and noticed with store closed and anonymous I can go to my domain/api and swagger shows the methods, etc. I consider this a security risk as it gives anyone the methods at least to work against my site. Granted they won't have the auth, but it's a start to a problem.

Your plugin should offer in the configure page an option to expose the Swagger UI or not and then there needs to be some ACL control of who can view it. At the very least give us a bit to not show swagger UI but if you want to require login, or a permission to view it, go from there.

**Comment by AndreiMaz** [comment]
@nealculiner There is no any security risk. If someone wants to access the swagger, he can always access it. So we're leaving it for customization

**Comment by nealculiner** [comment]
I, your customer, don't want it exposed on my production site. The only one that needs access is me. On my ASP.NET Core Web API's using Swagger I have it coded so it's only exposed in the Development environment. Kindly give me an option to hide it as I do not want it exposed. Thank you.

**Comment by skoshelev** [comment]
Hi @nealculiner. In the basic configuration, we do not have the ability to disable the display of Swagger UI, also there is no way to somehow limit access to the API, however, this does not mean that it is impossible to do this, we distribute our plugin with source codes and you can make any changes you need. You can disable Swagger UI in the PluginNopStartup class in the Configure method. As for restricting access to the API, you can add your code to the AuthorizeAttribute attribute

**Comment by nealculiner** [comment]
> Hi @nealculiner. In the basic configuration, we do not have the ability to disable the display of Swagger UI, also there is no way to somehow limit access to the API, however, this does not mean that it is impossible to do this, we distribute our plugin with source codes and you can make any changes you need. You can disable Swagger UI in the PluginNopStartup class in the Configure method. As for restricting access to the API, you can add your code to the AuthorizeAttribute attribute

Thank you @skoshelev, I didn't realize I had the source. I see that I can make the changes I need in the framework and will try that.
