### ISSUE TITLE
Return token expiration in Web API Authenticate response

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6849]
4.60.04 and your latest Web API [PAID].

I'd like to get the token expiration date in the JSON response so I don't have to continually call the Authenticate method or double my code with checks for 200 vs 401 and how to handle it. If my token is not expired which I can store that date then I know I can access the API without a refresh method call.

**Comment by AndreiMaz** [comment]
@nealculiner Please use our forums to get support about the API plugin - https://www.nopcommerce.com/en/boards/topic/97878/web-api-bearer-token-expiration

We use GitHub for work items only
