### ISSUE TITLE
Add USPS Ground Advantage Service

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#6850]
Is there any plan on when the USPS plugin will be updated to include the new service?

https://www.usps.com/ship/ground-advantage.htm

Thanks 
-Cameron

**Comment by danFbach** [comment]
The newest version available on the nopCommerce site should have it.
Issue was just resolved a few weeks ago.

**Comment by cklenk** [comment]
Okay I will check that out and report back, thank you!

**Comment by cklenk** [comment]
It looks like it was only updated for Nop 4.6 is that correct? I'm looking for a fix for Nop 4.4.

Thanks 
-Cameron

**Comment by glhays** [comment]
Are you using nop source code version 4.40?

If so you can try recompiling with the following change

Nop.Plugin.Shipping.USPS/USPSServices.cs file, change line23 from
[First-Class] = "0",
to
[Ground-Advantage] = "1058",


On Fri, Sep 8, 2023, 1:10 PM Cameron Klenk ***@***.******@***.***>> wrote:

It looks like it was only updated for Nop 4.6 is that correct? I'm looking for a fix for Nop 4.4.

Thanks
-Cameron

**Comment by AndreiMaz** [comment]
Already done
