### ISSUE TITLE
Not accurate "Languages" section in Github

### ISSUE THREAD

**Issue by torabi-ali** [nopSolutions/nopCommerce#6851]
nopCommerce version: develop

Steps to reproduce the problem: 
The "languages" section on Github is mostly for specifying the code we wrote and not libraries we use. So I suggest to remove UI libraries in web project by adding these two lines to `.gitattributes` file:
- `src/Presentation/Nop.Web/wwwroot/lib/** linguist-vendored`
- `src/Presentation/Nop.Web/wwwroot/lib_npm/** linguist-vendored`

Also, you might want to specify the `.cshtml` files as part of C# language:
- `*.cshtml linguist-language=C#`

![Languages](https://github.com/nopSolutions/nopCommerce/assets/15688908/1dbd82f6-b064-46fa-93f7-ba58546d6ef5)

**Comment by skoshelev** [comment]
Closed #6851
