### ISSUE TITLE
Customer role caching should not be cleaned for all customers when a customer role mapping is added/updated

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#6855]
nopCommerce version: 4.5

Steps to reproduce the problem: 
CustomerCustomerRoleMappingCacheEventConsumer - clears cache by prefix CustomerCustomerRolesPrefix ('Nop.customer.customerrole.') which will remove cache for all customers, for e.g. a guest customer record added and it will clear role mapping cache for all customer, it should clear cache only for the specific customer, refer below image

Also this should be check for other entity cache, so that it will improve performance

![image](https://github.com/nopSolutions/nopCommerce/assets/14998556/eec22f9d-df03-48a4-9bcd-1f4c17cfa07b)

**Comment by holydk** [comment]
AddressCacheEventConsumer clears all customer addresses after CRUD. In the simplest solution, we may not clear the cache when adding a new address.

**Comment by skoshelev** [comment]
Hi @kiranbhadani and @holydk. I looked at your suggestions and implemented them, thanks for your help

Closed #6855.
