### ISSUE TITLE
Suggestion: Remember page size in admin areas with lists (show number of items drop down)

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6857]
Writing as of 4.60.04. When I view various lists in the admin area whether catalog, email templates, topics, etc. they all have a default page size drop down. It would be nice if my selection is remembered so when I view an item and return to the list I don't to change the page size every time.

**Comment by AndreiMaz** [comment]
@nealculiner We do not offer a remember option. But you can change a default value with the "adminareasettings.gridpagesizes" setting

**Comment by nealculiner** [comment]
@AndreiMaz perfect - thank you!
