### ISSUE TITLE
MultiPage-Checkout: edit address redirects to 404 when state not selected

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6859]
nopCommerce version: 4.60.1+ (unable to reproduce in 4.60.0)

Steps to reproduce the problem: 
1. Make sure the following prerequisites are in place
 a) One page checkout is disabled
 b) State / province setting for Addresses enabled
2. Put an item in your cart and start an checkout. Proceed to the billing address page
3. Make sure you have an address that you can edit (if not, create a new one first and place an order with it, so that the address gets properly saved)
4. Edit an address
5. Select a country with states, but do not touch the state. If there is already a state set, please select "Select state"
6. Click "Next"

You will be redirect to the 404 page not found page.

Expected behavior:
Show an error message, indicating that a state needs to be selected.

**Comment by skoshelev** [comment]
Closed #6859
