### ISSUE TITLE
Discounts assigned to categories and grouped products issue

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#686]
If you use the discount type assigned to categories, discount are not valid for groupProduct when only the parent group product has categories. For group products it's only necessary to assign categories for the parent products. 

If you add this this lines in the GetAllowedDiscounts Method the problem should solve: 

```
if (product.ParentGroupedProductId != 0) 
{
     productCategories = _categoryService.GetProductCategoriesByProductId(product.ParentGroupedProductId);
} 
```

Source: http://www.nopcommerce.com/boards/t/33403/discounttype-assigned-to-categories-340.aspx 

[AM] Should we do it for grouped products? There are a lot of other places where it's simplified the same way

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development

**Comment by ubiquitas** [comment]
Hi, just bumping this as I have run into an issue here.

I have a website where the Grouped product can contain MANY simple products (up to 50, maybe more).  The simple products are not visible individually, only via the grouped product.

To manually assign each simple product to the category will take a long time. If I change the grouped product category I then need to repeat 50+ updates on the simple products.  If I have 20 Grouped products then that's 1000 updates required!!!

If however the Simple products inherited the Grouped product category I would only need 20 updates.

Please reconsider above, or add an option (checkbox) to include them when creating the discount

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box.
