### ISSUE TITLE
GetCurrentIpAddress with load balancer

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#6860]
nopCommerce version: 4.60

Steps to reproduce the problem: 
When having a load balancer, the GetCurrentIpAddress method returns the load balancer IP.

**Comment by AndreiMaz** [comment]
@ahmadkq Could you please post all questions on [our forums](https://www.nopcommerce.com/en/boards/)? We'll provide a solution on the forums

**Comment by ahmadkq** [comment]
@AndreiMaz I posted it on forums but no one asnwered, this is very cretical to me and i need help

**Comment by danFbach** [comment]
I'm going to guess that your load balancer passes the original IP address using a header.
I'm using an nginx reverse proxy for my store and had to configure:
```
Configuration => Settings => App Settings => Hosting Configuration => "The header used to retrieve the originating client IP"
nginx uses the "X-Forwarded-For" header. 
```
I think if you find the header your load balancer uses to pass client IP and apply it here, you should get what you're looking for.
