### ISSUE TITLE
Product with attribute showing a wrong discounted price

### ISSUE THREAD

**Issue by atiq-bs23** [nopSolutions/nopCommerce#6861]
nopCommerce version: 4.6

Steps to reproduce the problem: 
1. Create a product,
2. Create an attribute
3. Map an attribute with product
4. Add new attribute value with price adjustment
5. Add new discount
6. Map with the product
7. On the public store, visit the product page and choose an attribute 
8. You will get the discounted price as base product discounted price only but calculated with attribute adjustment

![image](https://github.com/nopSolutions/nopCommerce/assets/113086917/fd45ed54-3df0-4683-afef-bcf5c0994bcc)

**Comment by atiq-bs23** [comment]
@AndreiMaz

**Comment by RomanovM** [comment]
@atiq-bs23 I cannot reproduce this on a clean installation. Do you use any third-party plugins or customizations?

**Comment by RomanovM** [comment]
@atiq-bs23 Ok, got it.

**Comment by RomanovM** [comment]
Duplicated #5186
