### ISSUE TITLE
Duplicate entries in ScheduleTask table (from plugins)

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6863]
Using 4.60.04 and I was looking at System > Scheduled Tasks in my site as I'm working on my plugin and making sure my task was being created. I noticed two duplicate entries for two plugins by another developer (2 pairs of the same entry). The "Name" is identical. I tried uninstalling their plugin and only one was removed. It appears I'm going to have to remove the duplicate manually.

It seems when registering a scheduled task there should be a unique check that the Name cannot already be in the database?

**Comment by RomanovM** [comment]
The task name is used only for display to the admin, all interactions are by task type, and types in different plugins cannot be the same. 
Anyway, it's the responsibility of plugin developers to provide unique names and types for their tasks.

**Comment by nealculiner** [comment]
Here are two plugins with identical names and types. Shouldn't there be a unique constraint protecting this?
![tasks](https://github.com/nopSolutions/nopCommerce/assets/203614/6be4062b-c6f4-4b09-af9b-0e7537e4db8a)

**Comment by RomanovM** [comment]
@nealculiner The plugin developer should be concerned about this, as [we do](https://github.com/nopSolutions/nopCommerce/blob/4.60-bug-fixes/src/Plugins/Nop.Plugin.Tax.Avalara/AvalaraTaxProvider.cs#L212), for example. No need to constrain this at the solution level.
