### ISSUE TITLE
ManufacturerService - missing cache for GetAllManufacturersAsync and GetManufacturersByIdsAsync

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#6865]
nopCommerce version: 
v4.5

Steps to reproduce the problem: 
ManufacturerService - should have caching for GetAllManufacturersAsync and GetManufacturersByIdsAsync methods similar to what we have for categories

**Comment by AndreiMaz** [comment]
They should not have caching

P.S. "GetAllCategoriesAsync" (with paging) and "GetCategoriesByIdsAsync" methods also don't have it

**Comment by kiranbhadani** [comment]
Agree, it should not have for paging method, but we can add a new method like GetAllCategoriesAsync(int storeId = 0, bool showHidden = false), for manufacturers - which does have caching
