### ISSUE TITLE
new Customer detail created everytime login 

### ISSUE THREAD

**Issue by prabhath112** [nopSolutions/nopCommerce#6869]
nopCommerce version:  nopCommerce_4.60.4_Source

Steps to reproduce the problem: 
 Every time login with the any account, In DB new instance is created rather than updating current record instance.
![Screenshot 2023-10-06 113642](https://github.com/nopSolutions/nopCommerce/assets/72089340/7caf9cc5-3369-4989-91a0-c2bb92561c56)
![image](https://github.com/nopSolutions/nopCommerce/assets/72089340/1a9bb497-83ff-4cb3-96c9-85cdbd75b00e)

whenever login new customerGuid  is created even if its existing customer in Customer table, along IP, createdOnUtc, lastActivityDateutc, and registerdInStore. rest everything will be null.
i attached screenshot regarding this. and i dindt done any changes, running default.

**Comment by AndreiMaz** [comment]
@prabhath112 These are guest records. They will be deleted autoamtically later. Please ignore them

**Comment by prabhath112** [comment]
Along that i found out; if we add few items as a guest then we login to an account, the items which we added before as a guest are deleted. it shows only cart that user had only, but not adding items that we placed as guest.

**Comment by prabhath112** [comment]
And if you checkout as Guest it throws an exception saying 
![image](https://github.com/nopSolutions/nopCommerce/assets/72089340/a8819975-01dd-4223-bc23-c37d106955c0)

![image](https://github.com/nopSolutions/nopCommerce/assets/72089340/20f51ee3-04e2-4df5-a0eb-2f90be60e331)
