### ISSUE TITLE
@prabhath112 These are guest records. They will be deleted autoamtically later. Please ignore them

### ISSUE THREAD

**Issue by prabhath112** [nopSolutions/nopCommerce#6870]
@prabhath112 These are guest records. They will be deleted autoamtically later. Please ignore them

_Originally posted by @AndreiMaz in https://github.com/nopSolutions/nopCommerce/issues/6869#issuecomment-1750044270_
            
            Along that i found out; if we add few items as a guest then we login to an account, the items which we added before as a guest are deleted. it shows only cart that user had only, but not adding items that we placed as guest.
            And if you checkout as Guest it throws an exception saying

![image](https://user-images.githubusercontent.com/72089340/273127863-3b7d4767-b2ba-44a2-81ea-1054a08cd7d3.png)
![image](https://user-images.githubusercontent.com/72089340/273127877-60cfd868-1885-48a6-a0e6-f27c44d231dc.png)

**Comment by RomanovM** [comment]
Not reproduced. There is no `CheckoutCartService` in nopCommerce. I assume this is customization, so contact its developer.
