### ISSUE TITLE
Remove Miniprofiler

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6871]
Remove Miniprofiler from the solution. It can improve performance.

If some developers need it, they will have to add it back manually.

**Comment by ahmadkq** [comment]
@AndreiMaz If it is disabled, how removing it will increase the performance?

**Comment by exileDev** [comment]
Yes, but some sellers leave it active because it is only visible to administrators. In such cases, this can be a bottleneck.

Closed #6871
