### ISSUE TITLE
Discount requirements caching - should cache all requirements by discount id

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#6872]
https://github.com/nopSolutions/nopCommerce/blob/d963e332f2e53aae6fb984f52395aa3fc3c8523e/src/Libraries/Nop.Services/Discounts/DiscountService.cs#L585

Why we caching only top level discount requirements? isn't that better to cache all discount requirements for the discount and then use that same list also to get discount requirements by parentId

**Comment by skoshelev** [comment]
Closed #6872
