### ISSUE TITLE
Microsoft Dynamics 365

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6879]
Integrate nopCommerce with MS Dynamics. 

A list of possible export features should be finalized. Actually this implementation should be very similar to other CRM/ERP integrations (e.g. MS Dynamics, Salesforce, SAP). We can do the same + any other features (entities) that are supported by MS Dynamics. These other options for export could be chosen from other integrations. 

Good examples of third-party implementations are available internally (check with Andrei)

Here are some main ideas:

**Bi-directional synchronization of products**

- Connector will sync products between systems.
- Support product attibutes
- Support advanced pricing - tier pricing, discounts, etc.
- Decide whether items can be created automatically or only allow updates to existing products.
- Synchronization of inventory levels

**Bi-directional synchronization of customers**

**Import of orders from nopCommerce**

- During import you can automatically create customers in Dynamics 365 Business Central or decide to manage the customers in nopCommerce.
- Shipping costs, gift cards, tips, shipping and payment methods, transactions.
- Perhaps, the option to import back from MS Dynamics to nopCommerce could be considered in the next versions of nopCommerce

**Comment by brothers28** [comment]
Is there already a timeline for this feature?

**Comment by AndreiMaz** [comment]
@brothers28 March 2024 for this specific feature

**Comment by fastflame** [comment]
Very interesting feature! I have two customers who want this.

**Comment by DmitriyKulagin** [comment]
Closed https://www.nopcommerce.com/microsoft-dynamics-365
