### ISSUE TITLE
Applied discount on SubTotal is not showing on the cart.

### ISSUE THREAD

**Issue by atiq-bs23** [nopSolutions/nopCommerce#6882]
nopCommerce version: 4.6.3                    (4.5.4 is working)

Steps to reproduce the problem: 

1. Create a discount on Subtotal
2. Go to cart page (after applying discount)
![image](https://github.com/nopSolutions/nopCommerce/assets/113086917/59cd0a71-623a-4647-b9f4-60936ead73c0)

**Comment by atiq-bs23** [comment]
It is happening with the default nopCommere 4.6.4 as well. I was debugging and found a settings change,

TO GENERATE: Please change the tax settings to including tax, when I am changing to excluding tax it is working.

![image](https://github.com/nopSolutions/nopCommerce/assets/113086917/3af48fc5-a36a-47f9-81e4-10d447f627bd)


@RomanovM

**Comment by RomanovM** [comment]
@atiq-bs23 Got it. This has already been [fixed](https://github.com/nopSolutions/nopCommerce/commit/62f90047f29a8baa48af2c481e1fe042dcd8feb6) in develop, we'll also fix this in the next minor 4.60. Thanks.

**Comment by atiq-bs23** [comment]
Thanks @RomanovM
