### ISSUE TITLE
My account - Reward points

### ISSUE THREAD

**Issue by srdrsvml1986** [nopSolutions/nopCommerce#6887]
nopCommerce version 4.60.5

Steps to reproduce the problem: 
There is an error in the description of point movements on the Reward points page. It does not take the value specified in the language resources. It shows the language resource key assigned to that location on the screen. Rewardpoints.expired is written meaninglessly on the screen. The language value of this expression is not written.
![Screenshot 2023-10-20 194522](https://github.com/nopSolutions/nopCommerce/assets/12673971/67045988-e870-400f-a94e-e5197a957b5e)

**Comment by srdrsvml1986** [comment]
This error is not caused by the theme. It shows an error like this even when in the default theme

**Comment by AndreiMaz** [comment]
@srdrsvml1986 It works fine by default. Just ensure that you have "RewardPoints.Expired" locale in admin area > configuration > languages > edit > locales. Its default value should be "Unused reward points from {0} have expired"

**Comment by srdrsvml1986** [comment]
Yes, it should have been the way you said. but it is not like that. the program is not working. The key is added to my list but it still doesn't work
![Uploading xxxx.png…]()

**Comment by srdrsvml1986** [comment]
![xxxx](https://github.com/nopSolutions/nopCommerce/assets/12673971/528e7a72-36b0-4392-b719-502ae084e1b7)
Yes, it should have been the way you said. but it is not like that. the program is not working. The key is added to my list but it still doesn't work

**Comment by AndreiMaz** [comment]
@srdrsvml1986 

> It shows an error like this even when in the default theme
It's not true. It works absolutely fine in the default installation and theme. So it's definitely related to some customization or custom theme

**Comment by RomanovM** [comment]
@srdrsvml1986 This has been fixed in 4.60.3, see #6676.
