### ISSUE TITLE
"SEO friendly URLs with multiple languages" doesn't properly work for forums

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6889]
nopCommerce version: 4.60

Steps to reproduce the problem: 
1. Ensure that "SEO friendly URLs with multiple languages" option is enabled
2. Enable forums
3. Visit a forum page or a topic page without the language code specified (e.g /boards/forum/1/seo-name or /boards/topic/1/seo-name)
4. It should redirect to a new page with the language code  (e.g /en/boards/forum/1/seo-name). But it'll redirect to the "page not found" page)

It could cause SEO issues

**Comment by exileDev** [comment]
Closed #6889
