### ISSUE TITLE
Remove "Telecommunications, broadcasting, and electronic services" functionality

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6890]
Now a merchant can mark a product as "Telecommunications, broadcasting, and electronic services" to apply special tax rules used in the European Union.

This tax rule is outdated and not used anymore. So we can remove it

**Comment by RomanovM** [comment]
The MOSS (Mini One-Stop Shop) scheme has been running since 2015 and originally allowed sellers to account for VAT in one country for telecommunications, broadcasting, and electronic services. This scheme has been converted into OSS on July 1, 2021.

**Comment by DmitriyKulagin** [comment]
Closed #6890
