### ISSUE TITLE
Add a setting indicating whether customers are required to re-login after password changing

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6891]
Currently there's no way to disable this functionality in \Libraries\Nop.Services\Authentication\CookieAuthenticationService.cs file.

Let's add a setting indicating whether customers are required to re-login after password changing. It can improve website performance when disabled (passwords are loaded for each HTTP request. )

**Comment by DmitriyKulagin** [comment]
Closed #6891
