### ISSUE TITLE
RoxyFilemanFileProvider.FileMove not marked virtual

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#6896]
nopCommerce version: 4.60

Should RoxyFilemanFileProvider.FileMove be marke virtual ?

https://github.com/nopSolutions/nopCommerce/blob/3f6f4d8e49e12b6fc10c5a14c57f176a65058934/src/Libraries/Nop.Services/Media/RoxyFileman/RoxyFilemanFileProvider.cs#L406

**Comment by skoshelev** [comment]
Hi @alinmircea. Yes, it will be useful for consistency if this method is virtual

**Comment by skoshelev** [comment]
Closed #6896
