### ISSUE TITLE
Discount Apply to subcategories does not use hidden categories

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#6897]
nopCommerce version: 4.6

I'm guessing you'll say "we have decided to leave this for customization" but i thought i would bring it to your attention for consideration anyway.

In `CategoryService.cs`, function `public virtual async Task<IList<int>> GetAppliedCategoryIdsAsync(Discount discount, Customer customer)`, `GetChildCategoryIdsAsync` is called without `showHidden` set to true.

In our store, we use some categories for administrative purposes that are hidden. We will have products in hidden categories, not visible individually, but belonging to a grouped product. It makes for easier administration.
However, with the sub-category being hidden, their products are not being included in the parent's discounts. 
On a functional level, I don't see any problem with setting `showHidden` to true so that all possible products are considered for the applicable discount. The only potential downside would be performance, but i expect the impact would be minimal since it's all cached and lightweight anyway.

**Comment by RomanovM** [comment]
That's right, we'll leave this for customization. This is more an administration matter than a coding one. Also, the `showHidden` parameter affects many things like ACL and store mappings, so it'll definitely decrease performance.
