### ISSUE TITLE
Performance optimization for forums

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6900]
Check "PrepareForumTopicRowModelAsync" method of \Nop.Web\Factories\ForumModelFactory.cs

There's no any need to load all posts to prepare this model. We have to replace the following code 

```
var forumPosts = await _forumService.GetAllPostsAsync(topic.Id, 0, string.Empty, 1, _forumSettings.PostsPageSize);
topicModel.TotalPostPages = forumPosts.TotalPages;
```

with

`topicModel.TotalPostPages = (topic.NumPosts / _forumSettings.PostsPageSize) + 1;`

See https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Factories/ForumModelFactory.cs#L1035

**Comment by skoshelev** [comment]
Closed #6900
