### ISSUE TITLE
Language culture dropdown limited to English only on aspnet:7.0-alpine due to icu-libs changes in Alpine 3.16

### ISSUE THREAD

**Issue by wombitchgr** [nopSolutions/nopCommerce#6902]
nopCommerce version:  4.60.x

Steps to reproduce the problem: 
Run a nopCommerce 4.60.x docker image using aspnet:7.0-alpine. The Language culture dropdown when editing a language only consists of the English language.

Starting with Alpine 3.16 the icu-libs package only installs icu-data-en and icu-data-full need to be installed to support all cultures.

See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split

![Screenshot 2023-10-31 093315](https://github.com/nopSolutions/nopCommerce/assets/1703885/733207c6-c1ba-4d29-90a9-4fe20e908b9d)

**Comment by skoshelev** [comment]
Hi @wombitchgr!
Thanks a lot for your help

Closed #6902
