### ISSUE TITLE
Image processing does not preserve colorspace (RGB vs CMYK)

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6904]
nopCommerce version: 4.60.x

Steps to reproduce the problem: 
1. Go to an HTML Editor in the Backend, in example in the product details page.
2. Press Insert > Image, and upload the image
3. Select an image in CMYK colorspace and upload it.
4. Open the image url, download it and check it. 
5. The image was converted back to sRGB, and additionally the DPI value was completely lost

You can check the colorspace of an image in this tool: [PressPdf](https://www.presspdf.com/)
Normally you would have a customer that is providing you with CMYK images (usecase below), and you would upload them. In order to test that, you can also use a converter tool to convert RGB images to CMYK, like this one [RGB2CMYK](https://www.rgb2cmyk.org/) (used in the attached example)

**Workaround**
Just upload the CMYK file via FTP or something else. You can place it in the exact same location and same file name, and you will be able to download the correct CMYK file.

**Usecase**
We are currently working on a BusinessCard-generation plugin for one of our customers, where we need to generate a Print-Ready PDF that will be sent to the factory to be printed. Our customer is able to write custom HTML and CSS in the Backend using the HTML Editor.
We recently noticed that the behavior above is causing problems, as the factory expects a fully CMYK compliant PDF.

**Images**
I have reproduce the steps mentioned above with the nopcommerce logo, and attached the images in ZIP file, to prevent github from Processing the images.
[nop-colorspace-issue.zip](https://github.com/nopSolutions/nopCommerce/files/13224181/nop-colorspace-issue.zip)

Before Upload to nop:
![image](https://github.com/nopSolutions/nopCommerce/assets/54266094/b7e348f1-ced9-486c-a5d8-422c2f53d300)

After download from nop:
![image](https://github.com/nopSolutions/nopCommerce/assets/54266094/7ab0d11a-ac98-4251-8be9-965d4cdd2bb2)

Please Ignore the color change, this is expected, because my computer and monitor are not CMYK compliant. Just focus on the data on the left.

**Comment by DmitriyKulagin** [comment]
Unfortunately, the SkiaSharp library that we use for image processing does not support image conversion in the CMYK color space. In order to resize the image, it is converted to sRGB, and it seems that there is no alternative to this.

You need to provide your own solution to implement your integration.
