### ISSUE TITLE
Created indexes on foreign key constraints

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6906]
Currently a task to delete customers could be very slow. We've found out that indexes to child tables could significatly increase performance of this tasks. For example, there should be the index of [CustomerId] index in the [CustomerPassword] table. Useful links - https://stackoverflow.com/questions/10901299/delete-statement-in-sql-is-very-slow

Also see https://learn.microsoft.com/en-us/sql/relational-databases/tables/primary-and-foreign-key-constraints?view=sql-server-ver16#indexes-on-foreign-key-constraints

**Comment by ChrisClaude** [comment]
Is there a guide on how to add indexes on the project?

**Comment by skoshelev** [comment]
Hi @ChrisClaude. I'm very sorry, but we don't have instructions for such changes. In general, adding an entry to the /Installation/Indexes.cs file will solve the issue only at the installation stage. To add indexes to an already running site, you must add a new migration.

**Comment by skoshelev** [comment]
Closed #6906
