### ISSUE TITLE
Prefer ReadFormAsync over Request.Form

### ISSUE THREAD

**Issue by holydk** [nopSolutions/nopCommerce#6907]
Use `HttpContext.Request.ReadFormAsync` instead of [`HttpContext.Request.Form`](https://github.com/search?q=repo%3AnopSolutions%2FnopCommerce%20Request.Form&type=code). HttpContext.Request.Form uses [sync over async](https://devblogs.microsoft.com/pfxteam/should-i-expose-synchronous-wrappers-for-asynchronous-methods/) and can lead to thread pool starvation.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices?view=aspnetcore-7.0#prefer-readformasync-over-requestform

**Comment by skoshelev** [comment]
Hello Dmitry! thanks for the help

Closed #6907
