### ISSUE TITLE
"Multiple warehouse" (advanced inventory). Add "Minimum stock quantity" property to each warehouse

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#691]
Currently we use such property of the entire product. What about addition it to each warehouse? 

See contribution - https://nopcommerce.codeplex.com/SourceControl/network/forks/hubix2000/MultiwareHouseSupport/contribution/7139

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
