### ISSUE TITLE
use  Timeout.Infinite in TaskThread's TimerHandler method

### ISSUE THREAD

**Issue by AminMhmdi** [nopSolutions/nopCommerce#6912]
sorry for open this little issue 
but in below code is there any reason for not using Timeout.Infinite ??
https://github.com/nopSolutions/nopCommerce/blob/347adb86b82fe89d1a0c730db5ad51051849e2c9/src/Libraries/Nop.Services/ScheduleTasks/TaskScheduler.cs#L224

i mean why this code not like this?
` this._timer.Change(Timeout.Infinite, Timeout.Infinite);`

**Comment by skoshelev** [comment]
Closed #6912
