### ISSUE TITLE
nopCommerce as OAUTH provider

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6913]
I have apps and multiple web sites that share my ecommerce store's login system. While I purchased your Web API and it has the ability to login using the API, everything is moving towards OAUTH. .NET 8, soon to release, has made great strides with asp.net core identity, etc. in this movement. 

My suggestion for 4.70 (next major) is to make nopCommerce an oauth identity server/provider (whatever the right term is) so that my other web sites, mobile apps, etc. can use my nopCommerce site/architecture as an OAUTH provider for user's to login.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
