### ISSUE TITLE
Language Page Enhancement

### ISSUE THREAD

**Issue by hassanelsherbiny** [nopSolutions/nopCommerce#6914]
nopCommerce version: 4.7

Steps to reproduce the problem: 
this is only a simple enhancement
in admin language page
Admin/Language/Create
it would be easier for user to auto select flag and enter seo code directly after selecting the culture as the culture code  already holds these two information and it's quite repetitive for  user to need to manually input it, user still can edit these two fields manually

**Comment by RomanovM** [comment]
Thanks for the suggestion, we'll leave this for admin configuration.
