### ISSUE TITLE
Maintenance. Allow to delete saved PDF invoices

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#6926]
nopCommerce version: 4.60.4

Steps to reproduce the problem: 
Attach pdf invoices to notification emails. 
Pdf's are saved in .../nopdir/wwwroot/exportimport/
They are never deleted or cleaned up - my exportimport directory had ~25Gb of invoices!
Is there a reason they are being saved to disk instead of using a MemoryStream? 
There really is no need for them to persist once the email has been sent, unless you resend the email. Perhaps if the email _fails_ then save it to the disk for re-use, but if it succeeds dispose a stream naturally?

**Comment by RomanovM** [comment]
See also discussion in #5682

**Comment by AndreiMaz** [comment]
We'll allow merchants to delete such files in  admin area on the Maintenance page
