### ISSUE TITLE
Google Products Search now recommends 800px picture size

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#693]
We can submit original images (remove picture size setting for this plugin) or set a default settings to 800 (but what if we don't have so large pictures. they could have low quality in this case)

Forum source: http://www.nopcommerce.com/boards/t/31085/google-feed-specification-changes.aspx

let's discuss it first

**Comment by AndreiMaz** [comment]
no such requirement - https://support.google.com/merchants/answer/7052112?hl=en
