### ISSUE TITLE
Add support for multiple Brevo lists (multiple newsletters)

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6933]
I'm just figuring out Brevo now and have yet to launch my 4.60.5 storefront but it's getting close. One need I have is for the user to be able to subscribe to multiple newsletters, i.e. one for Apple, one for Google Android so I can segment the newsletter marketing. What I envision is both from their My Account area but also on the final checkout page is a list of checkboxes for newsletters to opt into. I've seen this done on other sites, it's typically integrated into the checkout experience and can be automatically associated to products purchased. Imagine a product configuration where we can associate newsletters to it which would allow for a checkbox to be checked at checkout to subscribe to the related newsletter.

**Comment by AndreiMaz** [comment]
@nealculiner Thanks a lot for suggestion. Duplicated https://github.com/nopSolutions/nopCommerce/issues/6874
