### ISSUE TITLE
Registration of a service with Autofac

### ISSUE THREAD

**Issue by jerseycolipot** [nopSolutions/nopCommerce#6936]
nopCommerce version: 4.x

Steps to reproduce the problem: 
![image](https://github.com/nopSolutions/nopCommerce/assets/144749354/d38c2043-f102-4a36-be45-251be61556cd)
![image](https://github.com/nopSolutions/nopCommerce/assets/144749354/f14a1224-a520-4715-bc38-cfc530b0fbaa)

as the picture show 
ITaskScheduler register by AddSingleton  ，but IScheduleTaskService register by AddScoped
I think if I dont use autofac ,there will be a bug ！
Because the  dependency injection in .NET Core does not allow this.

**Comment by skoshelev** [comment]
Hi @jerseycolipot. I checked the functionality of the code, yes it is an anti-pattern and it would be better to get rid of it, but I don’t think that this can be considered a bug. In any case, thank you very much for bringing this to our attention.

**Comment by skoshelev** [comment]
Closed #6936
