### ISSUE TITLE
Add a setting to disable query cache (performance)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#6939]
Let's add a new setting to appsettings.json file indicating whether linq2db should disable LINQ expressions caching for queries. Setting name will be "DisableQueryCache" (disabled by default).

The appropria checkbox on the "App Settings" admin page will be named "Disable query cache" and its hint will be set to "Disable LINQ expressions caching for queries. This cache reduces time, required for query parsing but have several side-effects. For example, cached LINQ expressions could contain references to external objects as parameters, which could lead to memory leaks if those objects are not used anymore by other code. Or cache access synchronization could lead to bigger latencies than it saves"

More info: https://github.com/linq2db/linq2db/issues/256

**Comment by skoshelev** [comment]
Closed #6939
