### ISSUE TITLE
Im  build to docker error (help)

### ISSUE THREAD

**Issue by phanvancan** [nopSolutions/nopCommerce#6945]
nopCommerce version: Version 4.70

Steps to reproduce the problem: 

 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 3.61kB                                                                                0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 4.18kB                                                                             0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0-alpine                                        0.4s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                                  0.3s
 => [internal] load build context                                                                                  2.4s
 => => transferring context: 131.36MB                                                                              2.2s
 => [build  1/63] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:bb65e39b662be0265f780afae9cdbfcaa315ef63edb245ad9f  0.0s
 => [runtime  1/10] FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine@sha256:24d9700c32b29b7215bf7ec669dd034eb74e39  0.0s
 => CACHED [runtime  2/10] RUN apk add --no-cache icu-libs icu-data-full                                           0.0s
 => CACHED [runtime  3/10] RUN apk add tiff --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/  0.0s
 => CACHED [runtime  4/10] RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge  0.0s
 => CACHED [runtime  5/10] RUN apk add libc-dev --no-cache                                                         0.0s
 => CACHED [runtime  6/10] RUN apk add tzdata --no-cache                                                           0.0s
 => CACHED [runtime  7/10] COPY ./entrypoint.sh /entrypoint.sh                                                     0.0s
 => CACHED [runtime  8/10] RUN chmod 755 /entrypoint.sh                                                            0.0s
 => CACHED [runtime  9/10] WORKDIR /app                                                                            0.0s
 => CACHED [build  2/63] WORKDIR /src                                                                              0.0s
 => [build  3/63] COPY ./src ./                                                                                    4.2s
 => [build  4/63] RUN dotnet restore NopCommerce.sln                                                              50.1s
 => [build  5/63] WORKDIR /src/Presentation/Nop.Web                                                                0.2s
 => ERROR [build  6/63] RUN dotnet build Nop.Web.csproj -c Release                                                57.7s
------
 > [build  6/63] RUN dotnet build Nop.Web.csproj -c Release:
0.924 MSBuild version 17.8.3+195e7f5a3 for .NET
2.415   Determining projects to restore...
3.645   All projects are up-to-date for restore.
8.860   Nop.Core -> /src/Libraries/Nop.Core/bin/Release/net8.0/Nop.Core.dll
10.80   Nop.Data -> /src/Libraries/Nop.Data/bin/Release/net8.0/Nop.Data.dll
21.54 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(68,34): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
21.54 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(131,17): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
21.54 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(201,40): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
21.79   Nop.Services -> /src/Libraries/Nop.Services/bin/Release/net8.0/Nop.Services.dll
24.13   Nop.Web.Framework -> /src/Presentation/Nop.Web.Framework/bin/Release/net8.0/Nop.Web.Framework.dll
57.37   Nop.Web -> /src/Presentation/Nop.Web/bin/Release/net8.0/Nop.Web.dll
57.44   You must install or update .NET to run this application.
57.44
57.44   App: /src/Build/ClearPluginAssemblies.dll
57.44   Architecture: x64
57.44   Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
57.44   .NET location: /usr/share/dotnet/
57.44
57.44   The following frameworks were found:
57.44     8.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
57.44
57.44   Learn more:
57.44   https://aka.ms/dotnet/app-launch-failed
57.44
57.44   To install missing framework, download:
57.44   https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-x64&os=debian.12
57.45 /src/Build/ClearPluginAssemblies.proj(21,5): error MSB3073: The command "dotnet "ClearPluginAssemblies.dll" "OutputPath=/src/Build/../Presentation/Nop.Web/bin/Release/net7.0/|PluginPath=|SaveLocalesFolders="" exited with code 150.
57.46
57.46 Build FAILED.
57.46
57.46 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(68,34): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
57.46 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(131,17): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
57.46 /src/Libraries/Nop.Services/Caching/RedisSynchronizedMemoryCache.cs(201,40): warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' [/src/Libraries/Nop.Services/Nop.Services.csproj]
57.46 /src/Build/ClearPluginAssemblies.proj(21,5): error MSB3073: The command "dotnet "ClearPluginAssemblies.dll" "OutputPath=/src/Build/../Presentation/Nop.Web/bin/Release/net7.0/|PluginPath=|SaveLocalesFolders="" exited with code 150.
57.46     3 Warning(s)
57.46     1 Error(s)
57.46
57.46 Time Elapsed 00:00:56.41
------
Dockerfile:14
--------------------
  12 |
  13 |     # build project
  14 | >>> RUN dotnet build Nop.Web.csproj -c Release
  15 |
  16 |     # build plugins
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet build Nop.Web.csproj -c Release" did not complete successfully: exit code: 1

**Comment by AndreiMaz** [comment]
Please post all questions on our forums. We use GitHub for work items only
