### ISSUE TITLE
The header used to retrieve the originating client IP doesn't work

### ISSUE THREAD

**Issue by c0nfus3d** [nopSolutions/nopCommerce#6953]
nopCommerce version: 4.50.3

We use Cloudflare with our nopCommerce website, Cloudflare's IP address is not properly detected (when the "Store IP addresses" setting is enabled)

I found some comments online that said I needed to change the "The header used to retrieve the originating client IP" setting in the "Hosting configuration" section of the App Settings to `CF-Connecting-IP`, which I did, restarted the app, and it is still saving Cloudflare's IP instead of the customer's IP address.

I have tried with the "Use proxy servers" setting on and off, with the "CF-Connecting-IP" value saved, and neither fixed the issue. I've even added Cloudflare's IP ranges in the "Addresses of known proxies" and that did not fix the issue.

I am seeking clarification regarding the functionality of the 'The header used to retrieve the originating client IP' setting in the 'Hosting configuration' section as even the tooltip says "Specify a custom HTTP header name to determine the originating IP address (e.g., CF-Connecting-IP, X-ProxyUser-Ip).", but it is not working as described or expected.

And yes, if I go to the System Information page and expand the "Headers", I do see the cf-connecting-ip header. It is being sent as it should from Cloudflare, nopCommerce is just not parsing it.

Source: https://www.nopcommerce.com/en/boards/topic/98317/cloudflare-issue

**Comment by AndreiMaz** [comment]
@c0nfus3d We use GitHub for work items only. Please post all questions on our forums - https://www.nopcommerce.com/en/boards/topic/98317/cloudflare-issue

**Comment by exileDev** [comment]
Closed #6953

**Comment by sangeet-shah** [comment]
@exileDev I have install latest nopCommerce 4.60.6 version but still i can see wrong location in my test site.

**Comment by sangeet-shah** [comment]
@AndreiMaz @exileDev  I have install latest nopCommerce 4.60.6 version but still i can see wrong location in my test site.

**Comment by sangeet-shah** [comment]
@exileDev 
![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/ff83b09e-0fe0-467d-a3a6-76b554785528)

**Comment by atulrungta** [comment]
It works perfectly when you did the right configuration in App settings like below:
![Screenshot 2024-02-16 151615](https://github.com/nopSolutions/nopCommerce/assets/7768934/a1e34b5d-c1b4-4d30-b3e5-dbbf25d792c9)

and in the Cloudflare, make sure to make changes in below rules:
![Uploading image_2024_02_16T09_41_06_648Z.png…]()

**Comment by atulrungta** [comment]
It works perfectly when you did the right configuration in App settings like below:
![nopCommerce_image](https://github.com/nopSolutions/nopCommerce/assets/7768934/fc259f37-ba81-4ff4-8f01-fd6f9bc12c3e)


and in the Cloudflare, make sure to make changes in below rules:
![clouflare_image](https://github.com/nopSolutions/nopCommerce/assets/7768934/27a76630-4614-4855-8bc8-5141f6430fc0)
