### ISSUE TITLE
Allow saving empty locales

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6954]
nopCommerce version: 4.60

> When a translation is empty the value will is not saved. We need a couple translations to be empty or blank. I believe when there is no value, the resource name is displayed. We just need nothing to be displayed.

Source: https://www.nopcommerce.com/boards/topic/98366/language-translation-empty-value

P.S. But ensure that we do not trim entered values (see [the comment](https://github.com/nopSolutions/nopCommerce/issues/6954#issuecomment-1962434323) below)

**Comment by brandon7171** [comment]
When editing string resources, an empty value when searching brings back all resources. It would be nice for anyone who saves an empty value to have a way to filter the empty resource values. There are a lot of resources to search though to find any you saved as empty. Maybe phase 2.

**Comment by brakim** [comment]
I don't see the purpose of this, but if it is implemented tt should be a setting to allow storing blanks.
It's a pretty good indicator that the key is rendered when a translation is missing.

To allow storing blank as default can be misleading and confusing.

**Comment by SelectSystemsInternational** [comment]
Also with this allow the enter of spaces 
![image](https://github.com/nopSolutions/nopCommerce/assets/34350154/ef1503e8-d083-422a-944b-25e5f39a375b)
formattedattributes.priceadjustment has a space at the front (once you take the spae out you cant put it back)
I have a customer string that I am using but I cant edit put a space at the front

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality and recommend the suggestion posted at https://www.nopcommerce.com/en/boards/topic/98366/language-translation-empty-value#309855
