### ISSUE TITLE
ProductAttributeValues: use percenatge with a value of 0 is displayed differently in product and cart

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6959]
nopCommerce version: 4.60.x

Steps to reproduce the problem: 
1. Open the following product in the backend: "adidas Consortium Campus 80s Running Shoes"
2. Navigate to the product attributes section
3. Edit the Size ProductAttribute
4. Edit the first value "8" and select "Use percentage, and leave the value as "0" and save
5. Open the same product in the frontend
6. Select the size "8"
![image](https://github.com/nopSolutions/nopCommerce/assets/54266094/09708f06-4e34-43a4-8257-b6fe03560bf7)
7. And add that product to the cart.
8. Navigate to the cart
![image](https://github.com/nopSolutions/nopCommerce/assets/54266094/083b0180-8181-44b8-ad20-db8f44dc4a09)

The 0% is displayed in the product details page, but not in the cart. The behavior should be consisted in both places

**Comment by AndreiMaz** [comment]
@exileDev We should not display 0% on the product details page. Display a percent only when its value is not equal to 0 (lie we do in the "FormatAttributesAsync" method of the ProductAttributeFormatter

**Comment by exileDev** [comment]
Closed #6959
