### ISSUE TITLE
Language missmatch between `Order.CustomValues` and `Order.CustomerLanguage`

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#6960]
nopCommerce version: 4.60.x

Steps to reproduce the problem: 
1. You will need to prepare two stores. In the first store (Store 1), publish english and german as languages. In the second store (Store 2), only publish german. You will need to use the same user in both stores. Do not restart the application in between to switch stores. Works best on deployed and production instances
2. Navigate to store 1 and select englisch. 
3. Navigate to store 2. You will see that everything changes to german as expected.
4. Place an order with custom values in store 2. This can be done with the PO Payment in example.
5. In the backend the custom values are shown in german, as expected
6. Check the database for the customer order language, it will be englisch, which you selected in the first store.

If you are now trying to programmatically trying to read the custom values based on the order language, you will not succeed. This might happen if you want to transmit the order to warehouse via an API in example.

Apparently the `Order.CustomerLanguage`  is taken form the `Customer.Language` which still contains the language manually selected in store 1.

**Comment by RomanovM** [comment]
Probably this has been fixed in #6704.
