### ISSUE TITLE
Android Mobile Chrome

### ISSUE THREAD

**Issue by ThomasGrant08** [nopSolutions/nopCommerce#6961]
## nopCommerce version: 4.60.5

Logging in on an android mobile, specifically on chrome returns a 400 error. If you click back you should be logged in fine. 

### Android 13:
Firefox - Works fine
Chrome - Error occurs

### iOS
Safari - Works fine
Chrome - Works fine

## Steps to reproduce the problem: 

1. Open store on Chrome on an android mobile
2. Log in (Takes to 400 error)
4. Click back

**Comment by AndreiMaz** [comment]
@ThomasGrant08 It works fine, cannot reproduce the issue on our demo website - https://demo.nopcommerce.com/
