### ISSUE TITLE
Course / Event Products with Date, Duration and other attributes 

### ISSUE THREAD

**Issue by brothers28** [nopSolutions/nopCommerce#6963]
Hi, this is a general request to create course / training / event products. 
Currently it's possible to create rental products, that have a specific date and timeframe but this is not quite suitable for a course / training application. 
A course takes place on one or multiple specific dates and in a specific place. I tried to implement this using specification attributes but there is no option for adding dates. The only option one has is to add all the dates separately as single options which is not really user-friendly especially if the user want's to filter for these dates.
As a certified nopCommerce developer myself I could theoretically manually alter the code but I think this is something more people than just me (or my customer) would be interested in.
If you need specific details for this feature request, don't hesitate to ask. I can certainly create a more detailed description including acceptance criteria.

**Comment by AndreiMaz** [comment]
@brothers28 Thanks a lot for suggestion! Sure, please share more specific details

**Comment by brothers28** [comment]
@AndreiMaz I will gladly give you more details.

nopCommerce currently recognizes the following product types: 
- Credit products
- Downloadable products
- Rental products
- subscription products. 
This differentiation is essential so that different characteristics and downstream processes can be carried out correctly. 

An important product type that is currently not available is training / events. 
Like the other product types, a training / event has specific attributes: 
- Date (on which the training / event is held, can also be several dates for training courses lasting several days)
- Duration
- Special registration attributes, e.g. customer need state what person will attend for each ticket the want to buy

The main advantage of such a product type is the search for customers as well as automatable downstream processes.
- Customers must be able to search by date of execution (from-to date search). This function is not possible via the current implementation of specification attributes. 
- Products can be sorted by the date (asc., desc.) and the customer can change the sort order using the provided dropdown
- Automated e-mails can be sent to all course participants with a reminder X-days before the event as well as after the event for asking for feedback.
- Participant lists can be exported from the application. 
 
I hope this helps you get an idea what I'm imagining myself for this product.

**Comment by AndreiMaz** [comment]
@brothers28 Could you please share several URLs on third-party websites that work this way?

I've seen such implementation several times but all of them were configured as separate products (each product is a separate event with a specific date) or a product with product attributes (that is much simpler)

**Comment by brothers28** [comment]
@AndreiMaz sure
- [Gebäudehülle Schweiz Events](https://xn--gebudehlle-s5a60a.swiss/Termine)
- [Campus Sursee courses](https://meinbildungszentrum.campus-sursee.ch/education/events?ausbildungsbereich&fachperson&sprache&search=) - these courses take place during a timerange and not on one single date. If you click on a course you can see a registration process on the right, that visualized the different steps including information about the registration prerequisites as well as specific information that is required for the participant to provide.
- [Eventfinder](https://www.eventfinder.de/index.php) - you can search for events happening at a specific place on a specific time.

Generally I'd say a minimum requirement would be to have a date option for specification attributes, including a date filter (from and/or to-date).

**Comment by AndreiMaz** [comment]
@brothers28 Thanks a lot for examples and all these details! But as I've previously written I'm sure that it'll be much easier to configure them as separate products. Each product is a separate event with a specific date or place. 

It'll require much less efforts to configure it:
- create a new group product to display a list of events (child products)
- create a new product template or a new category template to display them

It'll also be much easier to manage available slots (quanity), configure products attributes (e.g. to enter participant names), etc

**Comment by brothers28** [comment]
@AndreiMaz ah we might have a missunderstanding here. My thought process is not to have one mail event with many different subevents. I think like you discribed, one could achieve that using the grouped products feature.
But like with downloadable, rental products and so on it's just a additional option to define a product as a event/course and then have some specific attributes that the admin can define.

**Comment by AndreiMaz** [comment]
@brothers28 I got it. But we're leaving it for customization as quite specific feature.
