### ISSUE TITLE
nopcommerce backupbımı yüklemek istiyorum ama yükleyemiyorum

### ISSUE THREAD

**Issue by ibrahim3737** [nopSolutions/nopCommerce#6965]
nopCommerce version: 

Steps to reproduce the problem: 
nopcommerce backupbımı yüklemek istiyorum ama yükleyemiyorum

**Comment by RomanovM** [comment]
@ibrahim3737 Please post your questions on [our forums](https://www.nopcommerce.com/boards). We use GitHub as an issue tracker.
