### ISSUE TITLE
Add LanguageId field to NewsletterSubscription

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#6978]
nopCommerce version: 4.60

>I was very surprised to see that nopcommerce doesn't store the language (a.e. current UI language) of the user subscribing to the newsletter. I own a shop in a contry with multiple user languages. Informing the user in a language he can read is a very importent sales aspect - and multilanguage newsletters look horrible and uncustomized. So this greate feature is nearly useless.

Source: https://www.nopcommerce.com/boards/topic/98426/newsletter-subscriber-language

An important addition. It works fine for registered customers. But we also should support guest users who are not logged in and use the newsletter box. I think an extra property should be added to `NewsLetterSubscription`. So besides the `StoreId,` the `SubscriptionLanguageId` can be stored here as well. Let's ensure that it's synchronized for registered customers (they have the current language ID stored in database)

**Comment by DmitriyKulagin** [comment]
Closed #6978
