### ISSUE TITLE
NopCommerce Developed MailChimp Plugin Not Accounting For Multi-Store/Multiple Accounts

### ISSUE THREAD

**Issue by MJS-Storis** [nopSolutions/nopCommerce#6992]
nopCommerce version: 4.5

Steps to reproduce the problem: 
Set up a multi-store configuration in NopCommerce with the MailChimp plugin installed. Have a MailChimp account with access to two API keys. Go to each store and enter different API keys in each store and save. Take note if it then pulls any lists/audiences. 

To give a brief overview of the issue, basically companies that have a multi-store configuration and want to use separate MailChimp API keys for each store cannot. It may save both API keys and you can find them in All Settings if you search for MailChimp, but it doesn't make the connection necessary to pull lists/audiences. We also were getting an TLS Handshake error in the logs with one specific API Key that we were not able to resolve, even after contacting MailChimp on two separate occasions. This may be related to the overall issue. We had one of our developers look at the source code and it appears that the MailChimp plugin isn't coded to anticipate more than 1 API key. This we found weird since the plugin also has a drop down to switch between stores and each one has an input field for an API key. I am not sure if this was fixed in a later version after 4.5, but we certainly have it at the current level.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/mailchimp-plugin-for-nopcommerce/issues/24
