### ISSUE TITLE
Beta and Nightly Releases 

### ISSUE THREAD

**Issue by curllog** [nopSolutions/nopCommerce#6993]
Hi can we have a Beta And Nightly Release ?
Like Nightly Release After new commits (using pipelines) And Beta version after major changes (like migrating to .net 8)

**Comment by curllog** [comment]
> You could easily just clone the repo and build your own nightly/beta. The obvious problem with this is that third-party plugins will not work on major version changes.

but the problem is size of the source code is high and for testing purposes it's hard to clone it every time in different computers

**Comment by AndreiMaz** [comment]
We do not plan to add support for such builds. I would recommend following the suggestion of danFbac

**Comment by skoshelev** [comment]
Hi @curllog. You can clone a repository on only one computer. Set up on it, for example, a task for Jenkins that will download changes and build and publish a project, which you can easily take to any test server. In addition, the source files without all the extra folders, such as .git, obj, bin, etc., weigh only 150 megabytes, I think you can easily replicate such a volume
