### ISSUE TITLE
lastLoadedProduct is always null?

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#6995]
https://github.com/nopSolutions/nopCommerce/blob/650c284c28660579f1f6ef1ba92dc904e40559a6/src/Libraries/Nop.Services/ExportImport/ImportManager.cs#L2035

it seems that lastLoadedProduct is always null, thanks

**Comment by skoshelev** [comment]
Hi @kava81. Why did you decide so? Here at the end of the iteration of the root record, there is an assignment of data to this variable https://github.com/nopSolutions/nopCommerce/blob/650c284c28660579f1f6ef1ba92dc904e40559a6/src/Libraries/Nop.Services/ExportImport/ImportManager.cs#L2579

**Comment by kava81** [comment]
Hi @skoshelev ,

I understand, I have a excel with OutlineLevel != 0 but without attribute.

**Comment by skoshelev** [comment]
@kava81 The import/export file has its own structure, first, there is a record with the product, then, if needed, records with its attributes whose OutlineLevel is not equal to 0, if you make changes to the file structure, you will have to change the corresponding code.
