### ISSUE TITLE
Products. Add support for video

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#7]
It would be nice to be able to associate a video with a product like today we have images for products. Allow adding links to youtube, vimeo,... instead of uploading whole video. 

Create a plugin architecture for video, each plugin would be able to convert a link to an embed html code for an appropriate site. Hence, we would have one plugin for Vimeo, another for Youtube and people would be able to create other plugins for other sites. The plugins should create the embed code based on width of page which would be an input parameter of the method

There's no need upload video. Just enter YouTube URL

Example of good implementation with YouTube integration - https://www.detmir.ru/product/index/id/3193108/

**Comment by szocco** [comment]
We've tried the plugin and it works fairly well, however video is not responsive. We have also successfully added youtube link for video in the Long Description, Source Code and we were able to make it responsive.
Example: <p style="position: relative; height: 0; overflow: hidden; padding-bottom: 75%;"><iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://www.youtube.com/embed/B6L3Y5d4mCs" width="300" height="150" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

**Comment by AndreiMaz** [comment]
webtorrent.io helps to download Downloadable products or Sample files via torrent without any torrent client.
webtorrent.io can help to play streaming video with torrent source.

**Comment by c0nfus3d** [comment]
How is this still not a thing?? Would love this feature!!
