### ISSUE TITLE
Grouped Products - Associate Child to Many Parents

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7000]
Any appetite for adding the ability to associate a child product with multiple parents?
It would be particularly useful for me, where we sell replacement parts, and a single part can be applicable to multiple parent products.

Seems like such an extension would be simple enough.
- New Model/Table `Product_Group_Mappings` (Id, ProductId, ParentProductId)
- Copy existing `ParentGroupedProductId` to new table.
- Remove `ParentGroupedProductId` column/field from Product Model
- Replace any code using existing `ParentGroupedProductId` field to use data from new table.

Would be happy to contribute to development if it would be merged into the master.

**Comment by AndreiMaz** [comment]
@danFbach Thanks a lot for suggestion. But we're leaving this feature for customization
