### ISSUE TITLE
Nop.Web.Framework.BaseController.RenderPartialViewToStringAsync strip out javascript tag

### ISSUE THREAD

**Issue by ahinin79** [nopSolutions/nopCommerce#7001]
nopCommerce version: 4.6

Steps to reproduce the problem: 
I have a cshtml file which contains a script tag inside.
Then I want to render the view as html string.

however, the result returned is missing the entire javascript tag, is it the default behavior?
Any advise will be appreciated.

**Comment by RomanovM** [comment]
@ahinin79 Yes, this is a default behavior. You can see how we handled a similar situation in the [Avalara plugin](https://github.com/nopSolutions/nopCommerce/blob/master/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Product/ExportItems.cshtml).
