### ISSUE TITLE
ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 0001/1/1 0:00:00 (Gregorian date) and 9378/10/13 23:59:59 (Gregorian date), inclusive. (Parameter 'time')

### ISSUE THREAD

**Issue by curllog** [nopSolutions/nopCommerce#7002]
nopCommerce version: 4.70

Start Fresh
Choose Iran as country 
Choose mysql or sqlserver (not tested on postgres)
After installation open the site
wait 1 minutes or more
open new link or refresh the page 

We will get this error:

ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 0001/1/1 0:00:00 (Gregorian date) and 9378/10/13 23:59:59 (Gregorian date), inclusive. (Parameter 'time')
Actual value was 50284592391540000.

![image](https://github.com/nopSolutions/nopCommerce/assets/25693849/3d1ffda8-e7ea-4ba2-8b71-a1b7fb568054)

**Comment by AndreiMaz** [comment]
@curllog 
1. What are your OS are using?
2. What are your regional settings (country, calendar, etc) in your OS?
3. Are you experiencing it in previous versions of nopCommerce? For example, 4.60 or 4.50?

**Comment by curllog** [comment]
@AndreiMaz my os is win11 and my region is Iran, date time is iranian date time.

I never had this problem before actually  I didn't have problem with 4.70 for some period of time but it started from the update I can notnl figure it out

**Comment by RomanovM** [comment]
@exileDev  See also [this topic](https://www.nopcommerce.com/boards/topic/98583/after-installation-error) on our forums, perhaps it is related.

**Comment by exileDev** [comment]
Closed #7002 It's been fixed by linq2db
