### ISSUE TITLE
[Setup] Setting Create database if not exist errors if database exists

### ISSUE THREAD

**Issue by jafin** [nopSolutions/nopCommerce#7005]
nopCommerce version: `develop`

## Steps to reproduce the problem: 
- Create the database.
- Run nop web installer
- Tick 'Create Database if it doesn't exist'
- Execute install

## Receive error: 

`Setup failed: An error occurred while creating the database: Database 'nopcommerce' already exists. Choose a different database name.`

If the database does exist, this command shouldn't error.  It has the capability to continue the install (if permissions are correct).

**Comment by skoshelev** [comment]
Hi @jafin. Thank you for your help.

Closed #7005
