### ISSUE TITLE
Admin area. Persist selected products on pop-up windows (related products, add products to category, etc)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#701]
For example Catalog>Products>Manage Products> Related Product .The checkbox checked item doesn't persist each time I check the item and navigate to another page from the related product popup window. 

Forum source: http://www.nopcommerce.com/boards/t/30431/persistance-issue-in-related-product.aspx

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality
