### ISSUE TITLE
Error in OrderModelFactory: Nullable object must have a value

### ISSUE THREAD

**Issue by AxelAndersen** [nopSolutions/nopCommerce#7012]
When a product do not have any shipping method assigned and the product is only one on an order, error is thrown: 
Nullable object must have a value
We have a product "Return label" with no shipping, its just an email we send out, and we cannot view the order in the admin area due to missing Shipping.

https://github.com/nopSolutions/nopCommerce/blame/0c856737caff2f5ca11c5e924bd3ba95af3d654b/src/Presentation/Nop.Web/Areas/Admin/Factories/OrderModelFactory.cs#L650

**Comment by RomanovM** [comment]
@AxelAndersen To avoid the error you should disable `IsShipEnabled` for your product, in this case, an order will have `ShippingStatus.ShippingNotRequired` and the model will be correctly prepared.

**Comment by AxelAndersen** [comment]
@RomanovM We already have this setting set to false:

![image](https://github.com/nopSolutions/nopCommerce/assets/14222668/1cfc15fc-b7bc-4445-9d69-99de731bff84)

I think the problem occurs when an order has the ShippingStatus changed to "Shipped", then this method will fail

**Comment by RomanovM** [comment]
@AxelAndersen If `IsShipEnabled` is disabled for the product and this product is the only item on the order, then this order has `ShippingStatus.ShippingNotRequired`. When and why is it changing to `Shipped` one?

**Comment by AxelAndersen** [comment]
@RomanovM  It has in my situation been done be a plugin.
I have updated the code a bit and moved the call to GetLocalizedEnumAsync(order.ShippingStatus) further down

**Comment by RomanovM** [comment]
@AxelAndersen I cannot reproduce this error. Probably it's due to your plugin. 
If you provide a full list of steps to reproduce the problem on a clean installation, we'll reopen this issue.
