### ISSUE TITLE
Multiple requests for partial refund

### ISSUE THREAD

**Issue by eduard-ca** [nopSolutions/nopCommerce#7015]
nopCommerce version: 4.60.5

Hi

I have the next issue with an Order Partial Refund UI:

Via NopCommerce Admin UI the admin can execute parallel partial refund requests at the same time.

Steps to reproduce the problem:
1. Go to Admin/Orders/Edit
2. Use the partial refund
3. Change the amount to any for the refund
![Screenshot 2024-01-15 174706](https://github.com/nopSolutions/nopCommerce/assets/81959588/0ac8c7cd-f343-4532-922e-52ef8f8fd089)

4. Submit the form via double click
![Screenshot 2024-01-15 174928](https://github.com/nopSolutions/nopCommerce/assets/81959588/3c019414-ac1d-4cb2-8510-285d0db6a1aa)
![Screenshot 2024-01-15 175024](https://github.com/nopSolutions/nopCommerce/assets/81959588/ca7beadf-01ba-43e8-bb6c-b5b997f5b761)

Note. You see an issue with the message `Another transaction is in progress` (error message from payment API) for the second refund request because a Payment Provider API declined the second request during the first request executing

**Comment by RomanovM** [comment]
This is by design. Admin can initiate many partial refunds within the order amount, and the payment plugin should check their correctness (which is what it does in your case).
