### ISSUE TITLE
Implement Cloudflare Turnstile to replace reCaptcha

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7019]
I suggest looking at replacing reCaptcha with Cloudflare's free turnstile which seems to be much better. I'm using it on all of my xenforo sites, works great.

https://www.cloudflare.com/products/turnstile/

**Comment by RomanovM** [comment]
Thanks for the suggestion. It looks like a good idea for a third-party plugin.

**Comment by AndreiMaz** [comment]
Also see https://www.nopcommerce.com/en/boards/topic/98611/recaptcha-price-changes-time-for-cloudflare-turnstile

**Comment by AndreiMaz** [comment]
See https://www.nopcommerce.com/en/boards/topic/102616/cloudflare-turnstile-foxnetsoft

**Comment by nealculiner** [comment]
I asked foxnetsoft to create this and he did within 24 hours. Works great. Highly recommend.
