### ISSUE TITLE
Option to Hide Pay Later in PayPal Commerce payment plugin

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#7020]
I think it's a good improvement that we should add to the official PayPal commerce plugin. See the forum discussion here https://www.nopcommerce.com/en/boards/topic/98549/hide-pay-later-in-paypal-commerce-payment-plugin

**Comment by RomanovM** [comment]
PayPal doesn't recommend hiding this payment option. Anyway, admin has the opportunity to do this using the `disabledfunding` advanced settings.
