### ISSUE TITLE
PrepareProductAttributeValueModelAsync admin model issue

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#7021]
nopCommerce version: All

Steps to reproduce the problem: 
Inside PrepareProductAttributeValueModelAsync, the id for productAttribute is not set in the returned model. In case anyone use a widget inside the attribute popup, he will not get the Id for the attribute.

**Comment by RomanovM** [comment]
There is `ProductAttributeMappingId` in this model, using it you can get the appropriate `ProductAttribute`.

**Comment by ahmadkq** [comment]
@RomanovM but ProductAttribute ID is already there and you can set it in the Model Id! the returned Model Id is 0 and anyone will expect to have it filled!
