### ISSUE TITLE
One page checkout Billing Address add/change problem

### ISSUE THREAD

**Issue by kadri1914** [nopSolutions/nopCommerce#7027]
nopCommerce version: 4.60

Steps to reproduce the problem: 

If there is no address added in the billing addresses section on the One Page Checkout page, the add address screen opens. Here I fill in the information and click on the Continue button. Afterwards, when I click the Back button on the Shipping Methods screen, the add address screen opens again. However, it saved the address I entered. When I change the information here and click Continue, it adds the address as a new record. When I refresh the page, there are 2 address options in the billing addresses section.

**Comment by AndreiMaz** [comment]
@kadri1914 It's by design. Customer can enter multiple addresses. And when a new (unique) address is entered it's saved as a new record. A customer can delete any other addresses on the "my account" page
