### ISSUE TITLE
Create separate FROM and TO email addresses for message templates

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7029]
I'm using 4.60.5 and just launched my store trying to figure out why I'm getting all of these emails at my sales@ email address. This is the FROM address specified for my Store and email account. There are a lot of posts on the forums about this and the users do not like this, me included. We need control of what emails are sent FROM for notifications and then a separate TO address for notifications that owners want to receive. My sales@ address is a help desk inbox so when a user emails sales@ it comes to the help desk team. Therefore every sale notification is going to this help desk inbox which is not desired and causing us many problems. We need control to separate these emails coming from the store and being sent to accounts that want to be notified of activity. Please fix in a future release.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/5599
