### ISSUE TITLE
Suggest adding application.UseDefaultFiles();

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7030]
People like me have a lot of web content that uses default.htm, default.html, index.html type pages which go in the wwwroot as you know. Out of the box nopCommerce (4.60.5) doesn't serve these and results in 404's. This is an easy fix, in the first line of the UseNopStaticFiles method you just need to add the line below and it solves this issue.

application.UseDefaultFiles();

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
