### ISSUE TITLE
Farsi language resource string bug

### ISSUE THREAD

**Issue by raimand13** [nopSolutions/nopCommerce#7032]
nopCommerce version: 4.6.4

The "admin.dt.info" resource key is invalid in Farsi language and text format is wrong in DataTable pagination footer :
![image](https://github.com/nopSolutions/nopCommerce/assets/14857040/bce84968-be04-454f-bee3-48e5cf0da694)

Solution:
Resource key should change from

_START _-_ End_ از _TOTAL_ مورد

 to

_START_-_END_ از _TOTAL_ مورد

**Comment by RomanovM** [comment]
Thanks for your note. We use [Crowdin](https://crowdin.com/project/nopcommerce) for localization. If you would like to contribute to localization, please visit our [translations page](https://www.nopcommerce.com/translations).
