### ISSUE TITLE
Cannot apply new theme into the latest version of project

### ISSUE THREAD

**Issue by quynhnga1006** [nopSolutions/nopCommerce#7033]
nopCommerce version: the latest version: 4.60.5

Steps to reproduce the problem: 
Hi guys, I am trying to apply this theme into project with latest version: http://bakedelightstheme.demo.themes.nopaccelerate.com/
I download source code of theme with many version in here: https://www.nopcommerce.com/en/nopaccelerate-bake-delights-theme

then, i add this folder to Presentation\Nop.Web\Themes\BakedelightsTheme

I build project and i met problem: 

![image](https://github.com/nopSolutions/nopCommerce/assets/73351111/26082e3d-003e-44a3-9ad5-c58b9af848f0)

Do any guys met this problem before? Thanks for your helping.

**Comment by AndreiMaz** [comment]
Please contact developers of this theme
