### ISSUE TITLE
add main image for blog post and show it in blog post list

### ISSUE THREAD

**Issue by Steve7394** [nopSolutions/nopCommerce#7040]
hi there!
is it possible to add main blog image for showing in blog post list and etc...
for now the blog post list that show in main page do not have any image
thanks

**Comment by Steve7394** [comment]
[#6876](https://github.com/nopSolutions/nopCommerce/issues/6876)

**Comment by AndreiMaz** [comment]
You can manually upload an image and included it (<img> tag) to short description

P.S. Please post all questions on our forums

**Comment by Steve7394** [comment]
i know that 
but if we can add blog post to main page just like news (add an option in blog settings)
and add main image for that just like product view in main page.
