### ISSUE TITLE
Add delete to Admin/ProductAttributes Grid

### ISSUE THREAD

**Issue by jafin** [nopSolutions/nopCommerce#7042]
nopCommerce version:  `develop`

Following pattern of other grids, add a `Delete` function tot he Admin Product Attributes data table.
So that you do not have to Edit the attribute to delete it, optimizing time.

![image](https://github.com/nopSolutions/nopCommerce/assets/127927/0cbd395c-b828-4236-ad69-76ef3d1ed9cf)

**Comment by RomanovM** [comment]
@jafin  We mostly use inline delete where there is an inline update, and if there is a separate page for editing, then the delete button is also on it.

But thanks for the suggestion, surely someone in our community will be interested in this approach or we will use it in the future for all such places. For now, we leave this for customization.
