### ISSUE TITLE
Shipping rate computation plugin structure change for additional options form

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#705]
We lack ability to be able to get additional shipping options from customer like our shipping company (B2Cpl) asks to tell them customer preferred time and date of delivery (for Moscow shipments). 
Its possible to get such options using widgets type plugin but it will not be in the line of order placement road. 
So i'v made changes to shipping rate computation plugins scheme that way NopCommerce asks plugin - does it want to show additional options form and if yes then it renders form that is inside plugin. 
This way we can specify conditions for additional options form inside plugin and also specify additional options form (view) inside plugin. 
Please add this changes to new version of NopCommerce. 
Source of changes is included. 
Changes are only for not one page checkout.

[NopCommerce shipping rate computation additional options.zip](https://github.com/nopSolutions/nopCommerce/files/95445/NopCommerce.shipping.rate.computation.additional.options.zip)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
