### ISSUE TITLE
Can not display list payment method default

### ISSUE THREAD

**Issue by quynhnga1006** [nopSolutions/nopCommerce#7050]
nopCommerce version: 4.60.5

Steps to reproduce the problem: 
 Hi guys, I'm connecting to database of server, but when I access page Payment methods in admin management of develop enviroment, I can see 4 methods:

![image](https://github.com/nopSolutions/nopCommerce/assets/73351111/002c39c9-97e7-4365-8b48-60c37163c443)

But when I access page Payment methods in admin management of local enviroment, I got no method here.

![image](https://github.com/nopSolutions/nopCommerce/assets/73351111/dbce9140-6ac2-4521-ad41-f0c9789f0721)

How to fix this problem? Please to help me as soon as posible. Thanks.

**Comment by quynhnga1006** [comment]
I connected the same database.

**Comment by AndreiMaz** [comment]
Please post all technical questions on [our forums](https://www.nopcommerce.com/en/boards/). We use GitHub for work items only
