### ISSUE TITLE
Running behind reverse proxy causes forwarded IP's to not be taken into account

### ISSUE THREAD

**Issue by depeter** [nopSolutions/nopCommerce#7051]
nopCommerce version: 4.5

Steps to reproduce the problem: 

Setup nopcommerce behind a reverse proxy. Hosting nopcommerce using Kestrel webserver at port 5000.
Forward your requests from nginx.

When nopcommerce tries to fetch the IP address of the customer it will always just get the IP address of your nginx server.

https://github.com/nopSolutions/nopCommerce/blob/82a580824c15b9031cd1a8c0f38d1995bb1db07d/src/Libraries/Nop.Core/WebHelper.cs#L105

To support reverse proxy configurations this method should first check if the IP was forwarded in the header (X-Forwarded-For).

We have been running NopCommerce for several years on a Windows machine but have moved to linux since last year. It is running 5x as fast with half the resources. The Linux (debian) + nopcommerce combo is clearly a winner. 

If we can get this fixed I will write a very thorough manual how to setup nopcommerce on linux, inside docker containers.

**Comment by danFbach** [comment]
Do you have it properly configured?
In admin configuration `/Admin/Setting/AppSettings` - `Hosting Configuration`
![image](https://github.com/nopSolutions/nopCommerce/assets/17554977/4e447d3f-7d2e-46a4-9c3d-c233591418af)

**Comment by depeter** [comment]
Yes we do. We are running 4.50 if that matters.

I have set everything up in docker containers. They all get the ip address of the container that's running nginx.

![image](https://github.com/nopSolutions/nopCommerce/assets/8808339/98bf4b6d-4c77-4e0d-89a1-4cf5ff2113f9)

**Comment by danFbach** [comment]
when you look at the nginx logs, is the proper IP address reported?
in my case, the webserver webserver in front of my nginx reverse proxy has to pass the remote IP in the that header to nginx, then nop is able to read the remote ip from the X-Forwarded-For header.
I'm using an apache webserver, so my configuration file for my nop site contains `RemoteIPHeader X-Forwarded-For` to pass the remote ip.

**Comment by depeter** [comment]
Apologies, I wrongly assumed this was just not implemented correctly yet. The documentation for setting up nopcommerce on linux even on the official documentation site is very basic.

When I look at the nginx logs I do see the correct IP address, and according to the nginx documentation the IP is correctly forwarded by nginx.

217.182.175.38 - - [30/Jan/2024:16:43:10 +0000] "GET /productreviews/2789 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)"

The header is set correctly as far as my nginx knowledge goes...

    location / {
      proxy_pass https://172.20.0.10:5000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

After more research from my part I realize that the ForwardedHeaders configuration is done at another level. So you are correct that this is already taken care of in the NopCommerce logic, even for 4.50.

I still don't know what the problem is, but will try to debug this further. Once this IP forwarding is fixed, I will add a post on the nopcommerce forum describing everything step by step as I'm sure many other people are looking for this information. And the documentation available online is non existant.

**Comment by danFbach** [comment]
last bit of info, does your `./App_Data/appsettings.json` HostingConfig section look like this?

```json
  "HostingConfig": {
    "UseProxy": true,
    "ForwardedProtoHeaderName": null,
    "ForwardedForHeaderName": "X-Forwarded-For",
    "KnownProxies": null
  },
```

**Comment by depeter** [comment]
Your assistance is much appreciated Dan, I realize you're going beyong your usual work for this. And it's been an uphill battle for me just the same. I've put everything in docker containers so it's easy to reproduce on other machines once I get it all working properly.

Yes I've tried with that one. I was currently using this one to get rid of the depth limit but the result is the same:

```
  "HostingConfig": {
    "UseProxy": true,
    "ForwardedProtoHeaderName": "X-Forwarded-Proto",
    "ForwardedForHeaderName": "X-Forwarded-For",
    "KnownProxies": "127.20.0.30"
  }

```
I'm just running it on Kestrel if that matters. Starting to run out of ideas 😅

**Comment by depeter** [comment]
Ok I finally got it working. I just had a typo in my HostConfig with the KnownProxies setting. If I define it with the IP of my nginx docker container it works!

**Comment by danFbach** [comment]
I had just typed "How come the IP in your nop log is .30 and .10 in your nginx config?"
Glad you got it!
