### ISSUE TITLE
Backport Google Analytics GA4 update to 4.60

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7054]
Hey, I just backported the google analytics plugin update to support GA4 in nop 4.60.
Since Google Analytics UA is going to be fully deprecated 2024/06/01, i feel there should be a viable GA4 plugin in the 4.60 branch.

Can I make a PR for the 4-60 bug fixes branch? 
The backport only took a few changes to go from 4.7 to 4.6:
Set dotnet version to 7 in csproj
Set supported nop version to 4.6, and set plugin version to 4.60.6 in plugin.json
Had to remove `[NoTrim]` from the `ConfigurationModel` as the attribute is not supported in dotnet 7.

**Comment by AndreiMaz** [comment]
Thanks a lot. But we're leaving it for customization
