### ISSUE TITLE
Reports admin: Add quick pick date ranges for reporting like QuickBooks

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7057]
In account software when running reports there is a drop down with predefined date ranges such as:

-Last Year
-This Year
-Last Quarter
-This Quarter
-Last Month
-This Month

It would be nice to have quick pick dates. For example today I had to run a report on last month's sales. I have to pick the start and end dates and run the report. Not the most efficient, we can make this better.

Using 4.60.5

**Comment by jafin** [comment]
The challenges:
- What is year, calendar, fiscal? .  fiscal is different per country, even per company sometimes.
- If it were to be implemented, you'd possibly require a way to create customized date start/end ranges.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. We do not plan to add this functionality out of the box and leave it for customization

**Comment by nealculiner** [comment]
@jafin I think keeping it simple is the best option. For starters I would use:

- Last Year
- This Year
- Last Quarter
- This Quarter
- Last Month
- This Month
- Yesterday
- Today

This is basic convenience and should be a part of the reporting system.
