### ISSUE TITLE
Plugin order problem

### ISSUE THREAD

**Issue by kava81** [nopSolutions/nopCommerce#7061]
https://github.com/nopSolutions/nopCommerce/blob/5b1649cfc28cc9e2b4680a79ebb75035f949419c/src/Libraries/Nop.Services/Plugins/PluginService.cs#L241

Hi, I need to move a plugin before another.
With this line of code order it's impossible because it's order by group.
Same minor problem on display order in admin panel plugin/list

thanks

**Comment by AndreiMaz** [comment]
@kava81 We display plugins by groups, and then sort them by display order (the next line - https://github.com/nopSolutions/nopCommerce/blob/5b1649cfc28cc9e2b4680a79ebb75035f949419c/src/Libraries/Nop.Services/Plugins/PluginService.cs#L242). So you can sort them within the same group
