### ISSUE TITLE
GetProductCategoriesByProductIdAsync caching problem

### ISSUE THREAD

**Issue by alperkoca** [nopSolutions/nopCommerce#7062]
nopCommerce version: develop

Steps to reproduce the problem: 
Product had 4 categories, but only 3 were returned when I used the GetProductCategoriesByProductIdAsync method. I realized that the fourth category was unpublished, so I republished it. However, the GetProductCategoriesByProductIdAsync method didn't work correctly until the entire cache was cleared because the ProductCategoriesByProductCacheKey used by the method was not defined in the CategoryCacheEventConsumer.

I extended the CategoryCacheEventConsumer in my plugin and attempted to clean the ProductCategoriesByProductCacheKey there. However, it requires a prefix with a productId, and since there is no productId prefix, I couldn't define it. Could you add a prefix without a productId to the CategoryCacheEventConsumer?

**Comment by skoshelev** [comment]
Hi @alperkoca. Thank you for your detailed explanation of the problem, I made the necessary changes

Closed #7062
