### ISSUE TITLE
Mini Shopping Cart Subtotal (with discount) is different from Shopping Cart Summary subtotal

### ISSUE THREAD

**Issue by korifeich** [nopSolutions/nopCommerce#7063]
nopCommerce version: 4.6.3

Steps to reproduce the problem: 
1. Create an Order that is subject for a Discount to be applied
2. Go to Cart page

Sub-Total is shown without Discount:
![image](https://github.com/nopSolutions/nopCommerce/assets/3656411/2d66eb4d-0f15-4a15-bbf2-776d683c9d95)

At the same time Mini Shopping Cart show's subtotal with Discount:
![image](https://github.com/nopSolutions/nopCommerce/assets/3656411/eea2707e-691c-4cc3-8c02-80047f7495f2)

The issue is with the following file:
https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs
method name: PrepareMiniShoppingCartModelAsync
The following line: 
```
var (_, _, _, subTotalWithoutDiscountBase, _) = await _orderTotalCalculationService.GetShoppingCartSubTotalAsync(cart, subTotalIncludingTax);
```
Output value number 4 corresponds to `subTotalWithDiscountBase` for the following method: `GetShoppingCartSubTotalAsync`
```
Task<(decimal discountAmount, List<Discount> appliedDiscounts, decimal subTotalWithoutDiscount, decimal subTotalWithDiscount, SortedDictionary<decimal, decimal> taxRates)> GetShoppingCartSubTotalAsync(IList<ShoppingCartItem> cart,
    bool includingTax)
```

**Comment by RomanovM** [comment]
@korifeich You're right, we messed up with the method parameters. Same like is [here](https://github.com/nopSolutions/nopCommerce/issues/6254).
