### ISSUE TITLE
Action log/audit for admins

### ISSUE THREAD

**Issue by jackalvrus** [nopSolutions/nopCommerce#7065]
This is related to #374 

We have multiple support personnel who log into the store as admin users to perform customer support functions. One of the functions they can perform is refunds. We need to be able to track which user performed a refund and record a reason. Right now we have to ask them to manually add a note to the order when refunding. It would be better for us if it was done automatically.

That is our current use case, but I could see us eventually needing this for other admin functions. So I could see this implemented as a general admin auditing feature with the following characteristics:

- Record which admin user performed any given action
- Record a reason for performing the action. Ideally there would be a setting to make the reason required or optional for each action.

**Comment by astrumcs** [comment]
> This log technically exists here: `/Admin/ActivityLog/ActivityLogs` or `Customers => Activity Log` Since your operators are also considered 'Customers' by the application, nearly all actions they take are logged here.
> 

This is only half true from the view point of usability.   If you go to the ActivityLog, the comment for an order edit is the following:

> Edited an order (Order number = 148424). See order notes for details

It is a generic message that is the same every time.  So, asking a user that is investigating a customer service issue to move back and forth between the order notes and the activity log and then match up possible time stamps of each to then derive who took which action in the order is not a great solution. 

I think either adding a reference to the ActivityLog id in OrderNote table or adding a CustomerId field in the OrderNote table would be appropriate.   The information could then be added to the UI for a customer service person to use.
