### ISSUE TITLE
Replace Brevo affiliate link

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7067]
We have to replace all Brevo affiliate links (ending with `?tap_a=30591-fb13f0&tap_s=840216-5153c7` query string) with a new link - https://get.brevo.com/5f897rrc6cwa

Also let's add back the "Create a Brevo account" block with the "Create free account" button (pointing to https://get.brevo.com/5f897rrc6cwa) the same way like it's been done in the Sendinblue plugin. Now it's not shown in Brevo. Insert it right before the "API v3 key" input:

![image](https://github.com/nopSolutions/nopCommerce/assets/5019111/fc69ac0d-4937-47d0-a9d9-42e1ca81ee92)

**Comment by DmitriyKulagin** [comment]
Closed #7067
