### ISSUE TITLE
Do not validate model when changing password in admin area

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#7071]
nopCommerce version: 4.60

> When attempting to change a customer's password in the backend, a bug has been identified. If you try to click on "change password" in the customers backend with an empty required field, such as "Company Name," the page simply refreshes without altering the password, and no error message is displayed. It leads to confusion as users might expect a notification regarding the missing information.
> 
> However, upon providing the necessary information in the required field and then attempting to change the password, the operation is successful, and a green success message is displayed as expected.
> 
> Additionally, when attempting to save the customer without making any changes, the system correctly displays an error message, indicating a discrepancy in behavior when compared to the password change scenario.
> 
> This inconsistency in error handling poses a usability and feedback challenge for users. The expected behavior is to receive an error message when attempting to change the password with a missing required field, similar to the behavior observed when saving the customer without any changes, or to be able to change the password without the need to check for required fields.
> 
> Please investigate and address this issue promptly to ensure a seamless and reliable user experience.

Source: https://www.nopcommerce.com/boards/topic/98673/issue-with-password-change-in-backend-when-required-field-eg-company-name-is-empty

We already do it for EmailAccount password. 
Also, let's map a password from the entity to the model, but hide it by *, like for EmailAccount.

**Comment by adil-dhada** [comment]
Hello @RomanovM 
I can work on this issue if that's ok for you. 
After reviewing the problem, it appears to be quite straightforward to display the required field error message. 
However, handling the password display with * is not as straightforward as it is with EmailAccount. In the case of EmailAccount, the plain text is stored, whereas the Customer entity stores the hashed password inside CustomerPassword. Unfortunately, it's not feasible to retrieve and display the original password again.

Let me know your thoughts.

**Comment by exileDev** [comment]
Closed #7071
