### ISSUE TITLE
Add support for email ReplyTo Address and Name

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7078]
I'm using 4.60.6 and reviewed code to setup replyTo address and name for my use. You have these properties implemented in your email code but nowhere in the UI can anyone use the reply properties. Please consider adding inputs for reply to address and name and if blank, it's handled as it is now using the default email address, otherwise the reply to can be used.

Use case: I send a user a RMA form which comes from sales@ but I want the reply to go to rma@ so it's directed to the right department.

Plenty of use cases, give us the flexibility to route email please.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/6167
