### ISSUE TITLE
"From [price]" issue with tier prices (when higher qty has higher price)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#708]
Althought could be "fixed" by adding a tier price record with "highest quantity" for overriden customer role price 

Also note that such scenarios are VERY rate (when a higher qty has higher price) 

Forum source: http://www.nopcommerce.com/boards/t/28478/tier-pricing-override-bug-320.aspx

**Comment by AndreiMaz** [comment]
if (product.HasTierPrices)
{
//calculate price for the maximum quantity if we have tier prices, and choose minimal
minPossiblePrice = Math.Min(minPossiblePrice, priceCalculationService.GetFinalPrice(product, workContext.CurrentCustomer, quantity: int.MaxValue));
}
