### ISSUE TITLE
Date column precision (MSSQL) Can it be reduced?

### ISSUE THREAD

**Issue by jafin** [nopSolutions/nopCommerce#7082]
nopCommerce version: `develop`

Steps to reproduce the problem: 

The schema for MsSql creates all date columns as datetime2(6) 
Defined in FluentMigratorExtensions  `DATE_TIME_PRECISION=6`

On observation, all values appear to be stored with 3 decimal place precision, (the last 3 decimal values typically being 000).

Is there any reason these cannot be altered down to a precision of 3?  saving 1 byte per row.

```
6 bytes for precision less than 3.
7 bytes for precision 3 or 4.
All other precision require 8 bytes.2
```

**Comment by RomanovM** [comment]
You are probably right, such precision is excessive (perhaps only for payments and orders this is necessary), but we'll leave it as it is now. Anyone who cares about 1 byte, can easily customize the solution.
