### ISSUE TITLE
Contribution: image thumbnail generation

### ISSUE THREAD

**Issue by biggik** [nopSolutions/nopCommerce#7085]
nopCommerce version: 4.60.6

In accordance with the [Contribution policy](https://github.com/nopSolutions/nopCommerce/blob/2d909a01f919421745b5fc80393f29364a52e7a5/CONTRIBUTING.md), I'm reaching out to the team with a description of a change I've made

While investigating [an issue I ran into](https://www.nopcommerce.com/en/boards/topic/98709/nopcommerce-4606-administration-catalog-products-never-completes) I did discover that the current implementation of thumb generation is not optimal, at least not for Windows NTFS.
The issue is with the number of files in the thumbs folder - as that number grows, every action on that folder will take a longer time.
The current implementation of 'Multiple thumb directories' doesn't really help, since it is currently creating subfolders based on the first three characters of the thumb file name, and the thumb file name starts with a right zero-padded id, so until you have 10k images, you will have a single folder. In that single folder you may then have multiple thumbs of each image. 

For example, I created a command line tool, with code form nopCommerce, to regenerate all thumb images in four resolutions (400, 250, 70, 125) and I have ~25k images in 2 folders and a handful in the third.

My solution uses the product id to create subfolders (buckets), ending with a folder structure like the following:

\images\thumbs\
    \0  <- images with ids from 0 to 9999
         \0\0 <- images with ids from 0-99
         \0\100 <- images with ids from 100-199
    \10 <- images with ids from 10000 to 19999
        \10\0 <- images with ids from 10000 to 10099
        \10\100 <- images with ids from 10100 to 10199

which means that each leaf folder with only have a couple of hundred images, and the container folders will have a max of 100 folders in them

For my image count (50k) images, there is a factor of 2 speed increase with this. 
See sample runs [here](https://docs.google.com/spreadsheets/d/1SL1Yx8BG_JobKG9DXYKLtbXZb_6jLEDBbgM5TuBkVI4/edit?usp=sharing)

![flat-vs-buckets-thumbs](https://github.com/nopSolutions/nopCommerce/assets/5615016/18bc0a4e-a49f-41fc-ad63-47a0f49badef)

I've made this change against the [master branch](https://github.com/nopSolutions/nopCommerce/tree/master) of nopCommerce and can easily submit a pull request if you would entertain pulling this change in.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we'll leave it for customization. Current implemtation with "NopMediaDefaults.MultipleThumbDirectoriesLength" (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Media/NopMediaDefaults.cs#L13) works fine. And users can manage number of picture files in each directory by chaning it value

But you're more than welcome to share your solution. Perhaps, it could be helpful for our community

**Comment by biggik** [comment]
That is a solid suggestion. I implemented such a service based on my earlier changes.

https://github.com/biggik/Nop.Plugin.Services.BucketPictureService
