### ISSUE TITLE
Show message templates assigned to email addresses

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7088]
I'm using 4.60.6 and I have various email addresses in the store. I have no way to see what message templates are assigned to an email without clicking into each message template, or using the database directly. I suggest when viewing an email address a list is shown below with message templates assigned this email address.

**Comment by AndreiMaz** [comment]
@nealculiner Thanks a lot for suggestion. I've just created other task (a little bit different) - https://github.com/nopSolutions/nopCommerce/issues/7089
