### ISSUE TITLE
Allow to filter message templates by email accounts

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7089]
There's no way to see what message templates are assigned to an email without clicking into each message template, or using the database directly.

Let's add a new filter to the "Message templates" page.
Name: "Email account".
Possible values: "All" and a list of email accounts. These email accounts will be displayed in the following format - Email display name (Email address) - the same way as they are displayed now on a message template details page

We should display this dropdownlist when a store has two or more email accounts

**Comment by skoshelev** [comment]
Closed #7089
