### ISSUE TITLE
Add message template filter for owner, vendor, customer, all

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7091]
Related to issue #7089 I also suggest a drop down filter so I can only show desired message templates. For example I only want to see the Customer related templates, or Store Owner, or Vendor. This allows me to style them or set email accounts to templates by recipient.

**Comment by AndreiMaz** [comment]
Thanks a lot for suggestion. But we I think there's no need to implement this functionality out of the box and leave it for customization
