### ISSUE TITLE
Add store filter to all reports

### ISSUE THREAD

**Issue by Innovapps-Development** [nopSolutions/nopCommerce#7095]
nopCommerce version: 4.60.6

Steps to reproduce the problem: 
1. Open any reports, on a multi-store nopcommerce instance
2. Try filtering by store

It wont work. Add store based filter to all reports available in the backend.

**Comment by AndreiMaz** [comment]
@Innovapps-Development It works fine on [our demo website](https://admin-demo.nopcommerce.com/Admin/Report/SalesSummary)

**Comment by Innovapps-Development** [comment]
@AndreiMaz As far as I see, the store filter is only available on 3 out of 8 reports in your demo site. 
Sorry for not mentioning that above!

**Comment by AndreiMaz** [comment]
Thanks a lot for details. 

- We already have filters for "Products never purchased", "Bestsellers" and "Sales summary"
- "Low stock" report cannot have this filter (not related to stores)
- We do not plan to have this filter created for 3 customer reports (leaving it for customization)
- But I think it's a good idea to create filter for "Country sales" report. Here is a new separate work item - https://github.com/nopSolutions/nopCommerce/issues/7097

**Comment by Innovapps-Development** [comment]
@AndreiMaz I agree with the low stock one. 

This demand was raised by one of our customers, and we were quite surprised that this was not supported everywhere. Especially the customer reports make total sense to be filtered by store in my opinion.

Additionally it's quite a weird behavior to only allow filtering by store in half of the reports, and not everywhere where it makes sense. 

As you agree that one of your devs has a look at the one report you mentioned, it would probably also make sense to have a look at the other ones in the same time.
