### ISSUE TITLE
Allow to filter by a store in the "Country sales" report

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7097]
Let's allow a store owner to filter the "Country sales" report by a store

**Comment by Aariyan09** [comment]
Hey @AndreiMaz 
I am very new to Open source it was my very first contribution can you please guide me a little bit like where should i need to update the code ?
I have experience in dot net and git/github

**Comment by DmitriyKulagin** [comment]
Closed #7097
