### ISSUE TITLE
Forum permissions - Allow Customer to Create Post

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7098]
I'd like to utilize the forum a little differently, where only administrators/forum mods can make posts and customers and guests are read-only.

Under `/Admin/Setting/Forum` I'd like to add the setting `Allow Customer to create posts` to enable/disable this functionality.
Or, add permissions to ACL rules `/Admin/Security/Permissions` so that the forum permissions can be assigned to any role.

Would you up-stream either of these changes?

**Comment by AndreiMaz** [comment]
@danFbach Thanks a lot for suggestion. But forums are not the core functionality of nopCommerce (we're an eCommerce solution). So we've decided not to implement this functionality out of the box and leave it for customization
