### ISSUE TITLE
Advanced Search Option: search product By Manufacturer Part Number

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#71]
Add a new parameter to SearchProduct method and use it. I think we should also do similar to "searchSku" parameter

We should search this field by exact match or "starts with..." (the same is about SKU)

http://www.nopcommerce.com/boards/t/38810/searching-by-manufacturer-part-number.aspx

let's discuss before implementation

**Comment by ashleyross** [comment]
I am interested in this functionality, so I took a look at the code in [ProductService.cs](https://github.com/nopSolutions/nopCommerce/blob/e8f64bee790567e6d6470018815c06d3fb1ea29f/src/Libraries/Nop.Services/Catalog/ProductService.cs#L846). I am curious, why is the search against this field an exact match only (Comparison using `==` operator)?

In my case, I would prefer a "contains" or at least "starts with" match, as my one manufacturer has a single public part number that covers several variants. I have loaded the products with the full private part numbers, but users will only know the public part number until they find the variants. However, currently, they will never find those variants.

Why the decision for an exact match only?
