### ISSUE TITLE
Add "Product visibility" option to Product

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7100]
I'm using 4.60.6 and my prior ecommerce platform had a nice setting on a product that controlled the visibility: Public, Hidden, Private:

Public: Same as nop's published, it's visible on the web site

Hidden: The product can only be accessed by a URL such as given to a customer privately

Private: Not viewable other than admin (or some related permission/ACL)

I'd like to see the same feature in nopCommerce as hidden products are handy for products we don't want on the storefront but are used for other purposes.

**Comment by RomanovM** [comment]
Duplicate of #868
