### ISSUE TITLE
Unable to charge tax on non shippable products (manual tax provider)

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7105]
nopCommerce version: 4.60.6

Steps to reproduce the problem: 

I have simple tax rules, one for Virginia, one for Michigan. For any sales with a Michigan billing or shipping address I need to charge 6% sales & use tax. I mainly sell downloadable software and not shippable goods. Regardless of settings such as using billing address, etc. I am unable to get sales tax to generate and be added to the invoice at checkout. It seems taxes are only applied to shippable goods.

**Comment by RomanovM** [comment]
@nealculiner  For applying taxes there is no difference in whether the product is shippable.
I cannot reproduce this error on a clean installation.
Could you please provide more details, such as your Tax settings, tax categories, tax provider configuration, product tax category applied, etc?

**Comment by nealculiner** [comment]
I think I have this resolved, my apologies.
