### ISSUE TITLE
CustomProperties have been marked as JsonIgnore

### ISSUE THREAD

**Issue by poyker** [nopSolutions/nopCommerce#7106]
We use this property to extend the models by attaching data to them and passing the models to javascript.
With the latest changes (see below) we are not able to do that anymore.

Is there an alternative solution for us now if you have made this on purpose?

How could we pass additional data to the exisiting models and use it in js?

https://github.com/nopSolutions/nopCommerce/blob/8c45936960958d75eac5097bcf69fe88c8d10274/src/Presentation/Nop.Web.Framework/Models/BaseNopModel.cs#L42

**Comment by codegeek1001** [comment]
Hi Andrei, this is very critical for us to not lose and we would appreciate backward compatibility to keep Custom Properties.

**Comment by skoshelev** [comment]
Closed #7106
