### ISSUE TITLE
Add OrderCancelled.VendorNotification message

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7108]
I'm using 4.60.6 and I suggest adding a OrderCancelled.VendorNotification message template so vendors know their order is cancelled and not to ship, or bill the store owner, etc. 

Source: https://www.nopcommerce.com/en/boards/topic/98827/missing-vendor-notifications-order-cancelled-and-refunded

P.S. You may also want to consider adding a OrderRefunded.VendorNotification as well and leave it to the store owner to decide if they want to use it or not. Please review VendorNotifications for any others that may be missing and could improve communications.

**Comment by skoshelev** [comment]
Closed #7108
