### ISSUE TITLE
SEO friendly URLs with multiple languages enabled => Page not found if URL contains any parameter

### ISSUE THREAD

**Issue by andrejfilipi** [nopSolutions/nopCommerce#7110]
nopCommerce version: ALL

1. Enable localizationsettings.seofriendlyurlsforlanguagesenabled => True
2. Store by default add language SEO code. Example: http://www.yourStore.com/en/
3. Problem is if you share primary store URL without trailing "/" for example on Meta or any other social media then these social media adds parameters to url (example of redirected URL to store =>  http://www.yourStore.com/en?fb_id=123456 and these URL redirects to Page not found. Same is on default NopCommerce site: https://www.nopcommerce.com/en?fb_id=12334

Please if you could check if is any option to FIX that or give us any solution how to solve that

**Comment by exileDev** [comment]
Closed #7110
