### ISSUE TITLE
QueryProcAsync and ExecuteNonQueryAsync doesn't close connection to DB

### ISSUE THREAD

**Issue by aljaz00** [nopSolutions/nopCommerce#7118]
nopCommerce version: 4.60.2 using MSSQL as DB

When using `await _nopDataProvider.QueryProcAsync<T>` connections are not closed. It's the same with using `await _nopDataProvider.ExecuteNonQueryAsync<T>`.

I think the problem is with method `CreateDbCommand`, it's not disposing connection as it should.

**Comment by exileDev** [comment]
Closed #7118
