### ISSUE TITLE
UPS plugin failing to retrieve rates

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7119]
nopCommerce version: 4.60.6

Official nop UPS plugin is failing to retrieve rates. I believe this just started in the last day.

Here's the error log.
```
Shipping (UPS (United Parcel Service)). Error while getting UPS rates
Could not deserialize the response body stream as Nop.Plugin.Shipping.UPS.API.Rates.RATEResponseWrapper.

Status: 200
Response: 
```
I'm guessing that the problem is occurring in `/API/Rates/RateClient.cs` in the method
`protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(...)` line 200
Not sure how much more i can debug on my own as this appears to be generated code
```
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
```

**Comment by danFbach** [comment]
Correction, the oldest occurrence i have of this error is 03/19/2024 10:28:34 PM CST

Also, just checked their [API Updates](https://developer.ups.com/api/reference/api/updates?loc=en_US) and there is nothing past January...but they don't always post changes.

**Comment by danFbach** [comment]
In reference to that comment, they suggest just removing the `Alert` object from `RateResponse_Response`.
Of course this will work, but is not an ideal solution. 
Changing it from
```cs
public System.Collections.Generic.ICollection<Response_Alert> Alert { get; set; }
```
to 
```cs 
public Response_Alert Alert { get; set; }
```
Also allows it to work.

**Comment by danFbach** [comment]
[https://developer.ups.com/api/reference?loc=en_US#operation/Rate](https://developer.ups.com/api/reference?loc=en_US#operation/Rate)
Official UPS documentation still defines `Alert` as an array of objects - so the existing implementation _should_, and my changes _should not_ fix it.
I've got a ticket open with UPS to get some answers.

**Comment by skoshelev** [comment]
Hi @danFbach. Thank you for your help. We also don’t know how this is possible, but this is not the first such object that can have a dual structure in the new API. Therefore, we were forced to make our implementation of some fields, such as [RateResponse_RatedShipment.RatedPackage](https://github.com/nopSolutions/nopCommerce/blob/6754749621e22a2adc66dbea9260fb60d6e57311/src/Plugins/Nop.Plugin.Shipping.UPS/API/Rates/NopRateClient.cs#L57). 
We will make the necessary changes soon

**Comment by skoshelev** [comment]
Closed #7119

**Comment by sangeet-shah** [comment]
@skoshelev I have taken latest development update of this plugin from git repository. i found that this plugin return wrong rate.


![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/6215bf36-f4a1-471a-8158-1d01e5e99440)
![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/ffc79ca1-bd0c-49d0-a935-acdc07bd8f5b)

If i add CustomerClassification code as "53" in request then 4.6 ups plugin price and new oauth plugin price should be match.

**Comment by sangeet-shah** [comment]
@skoshelev @AndreiMaz 

This plugin still having issue.

![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/9e2440b8-687e-4afc-99e8-aa3ad688a3ed)

![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/4b16618c-49f0-480a-a7c1-b05d7cec910a)

I getting error while RatedShipment property get as object from UPS response.

**Comment by skoshelev** [comment]
Hi @sangeet-shah. This month, UPS updated both the API and documentation; according to the new specification, such problems should no longer exist. We have updated the code to use API version v2403.
