### ISSUE TITLE
Split the InstallationService into several parts

### ISSUE THREAD

**Issue by danzuep** [nopSolutions/nopCommerce#7122]
nopCommerce version: 
- 4.70.8

Steps to reproduce the problem: 
- The InstallationService is massive, making local changes and synching is a pain (e.g. #7121).

Since the InstallationService is already a partial class, splitting it in three makes it easier to work with. An alternative (better?) way of doing this would be to inject two other services.

I've done this in my project [here](https://github.com/danzuep/nopCommerce/tree/develop), but after I re-based I realised I'd missed some changes from @exileDev 21 hours ago, so maybe one of the core team should implement this.

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization

**Comment by skoshelev** [comment]
Closed #7122
