### ISSUE TITLE
Null reference Error, Admin/OrderModelFactory/PrepareOrderModelShippingInfoAsync

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7124]
nopCommerce version: 4.60.6

I'm actively getting an exception thrown here on an order.

`protected virtual async Task PrepareOrderModelShippingInfoAsync(OrderModel model, Order order)`

```cs
if (!order.PickupInStore)
{
    //null reference possibility, as order.ShippingAddressId is never checked to have a value.
    var shippingAddress = await _addressService.GetAddressByIdAsync(order.ShippingAddressId.Value);
    var shippingCountry = await _countryService.GetCountryByAddressAsync(shippingAddress);

    model.ShippingAddress = shippingAddress.ToModel(model.ShippingAddress);
    model.ShippingAddress.CountryName = shippingCountry?.Name;
    model.ShippingAddress.StateProvinceName = (await _stateProvinceService.GetStateProvinceByAddressAsync(shippingAddress))?.Name;
    await _addressModelFactory.PrepareAddressModelAsync(model.ShippingAddress, shippingAddress);
    SetAddressFieldsAsRequired(model.ShippingAddress);
    model.ShippingAddressGoogleMapsUrl = "https://maps.google.com/maps?f=q&hl=en&ie=UTF8&oe=UTF8&geocode=&q=" +
        $"{WebUtility.UrlEncode(shippingAddress.Address1 + " " + shippingAddress.ZipPostalCode + " " + shippingAddress.City + " " + (shippingCountry?.Name ?? string.Empty))}";
}
```

**Comment by AndreiMaz** [comment]
@danFbach Please provide a list of steps to reproduce the issue on the clea installation. Actually this methid is invoked only when shipping is required and after the "Shipping address" step during checkout. Hence, it cannot be null

**Comment by danFbach** [comment]
I have an order that requires shipping, but has no shipping address. The order was created without shipping required. However, the order was actually shipped with a third party fulfillment channel, as it turned out there was something to ship. 
I'm guessing when it posted the shipping method back to nop, it changed the order to require shipping, however the order still does not have a shipping address.
