### ISSUE TITLE
Product reviews

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7126]
nopCommerce version: 4.70 (develop)

Last month I spent some time inspecting the current changes in nopCommerce 4.70 and found a couple of issues with the new Product Reviews functionality.

If anonymous users are not allowed to add product reviews, by default the message "Only Registered Users Can Write Reviews" is not visible. The form fields in the Write Review form are disabled though, so you can't type anything but you don't know why. The message goes visible only if you click the "Submit Review" button, but that doesn't make any sense since you can't type and there is nothing to submit. The message should be always visible to notify the users why they can't post reviews.

If the setting "Allow customer reviews" is disabled for a product, the Write Review form is still visible on the Product Details page for that product, so you can type your review and click the "Submit Review" button, and after that you are redirected to the Home Page without any notification or error message. Either the review form should not be available at all, or there should be a notification that notifies the users why posting reviews is not possible.

The third issue I found is rather a "cosmetic" one - the "page" type of classnames ("page" & "product-reviews-page"), and also the "page-body" element, are no longer needed in the product reviews section as it is no longer a dedicated page in 4.70. Now it's just a section added to Product Details pages so it will be more clean if the classname is changed to "product-reviews" and the page-body element is removed. (If you keep the outdated classnames as they are it could lead to css conflicts in some themes where there is global css code that is targeting all dedicated pages)

Source: https://www.nopcommerce.com/en/boards/topic/98881/a-couple-of-issues-with-product-reviews-in-nopcommerce-470

**Comment by exileDev** [comment]
Closed #7126
