### ISSUE TITLE
IPlugin Update() method

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#713]
Forum source: http://www.nopcommerce.com/boards/t/28030/iplugin-update-method-would-be-nice-to-have.aspx

the question is when should we  invoke this method?

We could check it during aplication startup (check version). But in some cases it's better to put logic in a plugin (when it could be updated without nopCommerce version upgrade). For more details please see https://github.com/nopSolutions/nopCommerce/issues/259

**Comment by keremdemirer** [comment]
I think it will be enough to have a button on plugins list page.

**Comment by skoshelev** [comment]
Closed #713
