### ISSUE TITLE
open-source edition

### ISSUE THREAD

**Issue by brakim** [nopSolutions/nopCommerce#7133]
@AndreiMaz 

Can you explain the future plans of NopCommere as mention here 
#6877 

>Once it's done we can remove ISearchPluginManager from the open-source edition (like we're going to remove some other functionality as well)

What is going to be removed from _**"open-source edition"**_ and what would the _**"closed-source edition"**_ include?

**Comment by AndreiMaz** [comment]
We're not going to release the "closed-source edition". We just plan to release Elasticsearch and Lucene as paid plugins. So this interface (ISearchPluginManager) won't be just required in our open-source edition
