### ISSUE TITLE
Passkey support

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#7138]
As of 4.60.6...I'd like to request Passkey support, it's where password management is going at this time.

**Comment by danFbach** [comment]
Along this same thread, OTP to email/phone would be a cool feature too.

**Comment by AndreiMaz** [comment]
@nealculiner Please provide more information about how exactly it should work

**Comment by nealculiner** [comment]
Hi @AndreiMaz, it may be easier just to point you to XenForo's write-up as they are implementing it. Apple uses it now for their login, 1Password supports it, please see:

https://xenforo.com/community/threads/passwordless-logins-with-passkeys.220458/

**Comment by RomanovM** [comment]
Similar was discussed in #2228

**Comment by AndreiMaz** [comment]
After some consideration we've decided not to implement this functionality out of the box and leave it for customization
