### ISSUE TITLE
Add a confirmation to a switch on the configuration page of "Tax (Fixed or by Country)" plugin

### ISSUE THREAD

**Issue by BryceBarbara** [nopSolutions/nopCommerce#7139]
We've noticed that it's quite easy to leave your store in a broken state if you mistakenly think a switch on the configure page just changes the current view (shown below):

![image](https://github.com/nopSolutions/nopCommerce/assets/24460210/1cbbc95b-b06e-46d0-b9e1-4887a1253c38)

We're seeing users flip that switch, don't realize what has changed, and then wonder why taxes are zero on all purchases. This seems like a perfect situation where some improved UX could avoid users unintentionally shooting themselves in the foot.

Some potential solutions off the top of the dome:

1. Switch the UI element being used to something that more clearly indicates the ramifications of the change
2. Add an extra step to confirm the changes with a warning of the ramifications
3. Add more help text around the element to explain what it is and what it does

----

nopCommerce version: 4.60.6

Steps to reproduce the problem: 

- Go to configure the **Tax (Fixed or by Country)** tax provider (`/Admin/FixedOrByCountryStateZip/Configure`)
- See the toggle switch that in almost all other areas just toggles advanced views
- Toggle the switch thinking you're just seeing another set of data
- Leave store in broken state

**Comment by DmitriyKulagin** [comment]
Closed #7139
