### ISSUE TITLE
Close DataConnections on BaseDataProvider

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7140]
**nopCommerce version:** 4.60
**Steps to reproduce the problem:** 

Call BaseDataProvider.ExecuteNonQueryAsync() on a list of 1000 entries.
Get "Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool"

Probably same issue on any method that is calling BaseDataProvider.CreateDataConnection() and not disposing. 

**Propose:** 

Dispose usages of CommandInfo.DataConnection
Dispose usages of DataConnection

**Comment by alinmircea** [comment]
Checked latest source. Closing.

**Comment by ahmadkq** [comment]
> ExecuteNonQueryAsync

Hi, where is calling of Dispose? I can't see it
