### ISSUE TITLE
Add a way to create specific IConfig settings in plugins

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#7143]
nopCommerce version: 4.60

Right now we can create any `IConfig` settings in the core and they will automatically be registered and bound.
We should find a way to create such `IConfig` settings in plugins so that they are also automatically registered when the app starts.

**Comment by skoshelev** [comment]
Closed #7143

**Comment by D3bo** [comment]
Am I wrong or it worked in version 4.50?
