### ISSUE TITLE
Install Setup failed: Sequence contains more than one element

### ISSUE THREAD

**Issue by mKhaliil** [nopSolutions/nopCommerce#7149]
nopCommerce version:  4.60.6

Steps to reproduce the problem:-
1. Fork the develop branch.
2. Clone the repository to your local machine.
3. Create a new branch.
4. Switch to the new branch.
5. Build the project.
6. Start the project.
7. It will redirect you to the Install page.
8. Fill in all the required details in the fields, including selecting the "Create sample data" option.
9. Click on the "Install" button.
10. After a few minutes, you will receive an error message: "Setup failed: Sequence contains more than one element."

Screenshots are attached for reference.
![step-1](https://github.com/nopSolutions/nopCommerce/assets/38485660/38560785-fed1-4068-b6c6-fdcd83fe5874)

![Step-2](https://github.com/nopSolutions/nopCommerce/assets/38485660/b272a1c1-e275-423b-8188-6f46adbdc1ec)

**Comment by AndreiMaz** [comment]
You should install nopCommerce on the clean database (without tables)
