### ISSUE TITLE
Can't read logo for PDF documents when pictures are stored in Azure Blob

### ISSUE THREAD

**Issue by exileDev** [nopSolutions/nopCommerce#7151]
nopCommerce version: 4.60.6

Steps to reproduce the problem: 

> NopFileProvider fails to read a thumbnail from Azure Blob Storage

Source: https://github.com/nopSolutions/nopCommerce/issues/6588#issuecomment-1799803617

**Comment by exileDev** [comment]
Closed #7151

**Comment by andreiborodin** [comment]
Thanks for making the fix!
