### ISSUE TITLE
The display of addresses is currently inconsistent

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#7152]
nopCommerce version: latest from develop

Steps to reproduce the problem: 
I see that displaying address data is not consistent. 

For example, on the order detail page, AddressFields are used, [source code](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Order/Details.cshtml#L92)
![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/443fd3b0-794e-48b7-b707-fc36d1f26b1f)

but on the shipment detail page, a different method is used for display, [source code](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Views/Order/ShipmentDetails.cshtml#L120) 
![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/b4872b10-d292-4420-b4c6-6c679af78387)

Let's standardize the display method, paying attention to other areas where customer addresses are shown.

**Comment by skoshelev** [comment]
Closed #7152
