### ISSUE TITLE
Email accounts. Add separate locales for Google and Microsoft authentication methods

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7158]
nopCommerce version: 4.70 

![image](https://github.com/nopSolutions/nopCommerce/assets/5019111/6b366d85-143b-45b8-a068-8d644b63b869)

There should be two serapate locales for Google and MS. Currently "Admin.Configuration.EmailAccounts.RedirectUrl.Info" has information related to Google

**Comment by exileDev** [comment]
Closed #7158
