### ISSUE TITLE
Bundles that have products that they themselves have required configurable attributes

### ISSUE THREAD

**Issue by dwhiteddsoft** [nopSolutions/nopCommerce#7159]
nopCommerce version: 4.70

Steps to reproduce the problem: 
Create a product entry for jersey, make it have a required attribute of size
Create a product entry for shorts, make it have a required attribute of size

Create a bundle with the jersey and shorts above in product attributes and make them both required. An error is displayed that looks like the below
![image](https://github.com/nopSolutions/nopCommerce/assets/4751106/03ae6448-abfa-415b-bd86-ed1fa263d60f)

Am I doing something wrong or is this not possible?
I am very comfortable with the NET if I have to write something but am not sure how to override catalog and cart functionality. If that is all that is required I would appreciate a quick steer to the interfaces to start inheriting from. 

Thanks in advance

**Comment by dwhiteddsoft** [comment]
I am new here so apologize for dumb questions. These are associated products, no? If so how to I get the user to not add them to the cart individually but one big "Add to Cart" for the bundle?

**Comment by glhays** [comment]
Have you tried the forums for some help?
https://www.nopcommerce.com/en/boards

**Comment by AndreiMaz** [comment]
It's not supported out of the box. That's why this warning is displayed.
