### ISSUE TITLE
Admin Dashboard X Axis Labels

### ISSUE THREAD

**Issue by brandon71** [nopSolutions/nopCommerce#7162]
nopCommerce version: 4.70

Steps to reproduce the problem: 
The labels on the x axis are no longer showing descriptions for the Orders and New Customers Charts on the admin dashboard.

Previous versions of NopCommerce showed the date and day of the week for example when looking at the Week view. The charts now only show numbers.

**Comment by AndreiMaz** [comment]
@brandon71 Could you please share some screenshots?

**Comment by brandon71** [comment]
4.60
![image](https://github.com/nopSolutions/nopCommerce/assets/4977768/f1fcbde3-2ab3-4cc4-b733-e23bf7f90e58)

4.70
![image](https://github.com/nopSolutions/nopCommerce/assets/4977768/4275a9ad-2793-4998-9611-4bde7b00f49b)

**Comment by exileDev** [comment]
Closed #7162
