### ISSUE TITLE
Read-Only mode (allow a store owner to disable checkout)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#717]
Proposing a read-only mode where ordering can be turned off temporarily. This would be most used when needing to move an installation to another server or host altogether. The site is up, but database changes are prevented. I actually tested nopCommerce with a read-only mode database, but it threw an exception right away due to likely needing to write logs. It'd be great for it to fall back to writing log files instead of the database during this time period. It'd certainly make moving to another server easier while not appearing down during the DNS transition period.

Just display some message on the "Checkout" page

**Comment by skoshelev** [comment]
Closed #717
