### ISSUE TITLE
Display error on the order list page in the admin area

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#7172]
nopCommerce version: 4.7 (latest on develop)

Steps to reproduce the problem: 

Go to the Order list page in admin area.
Please focus on the 'Summary' section of the order list table. All numbers are displayed as 'undefined'

![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/047a4dbe-0fa8-4036-bc2b-43db1814fd46)

**Comment by skoshelev** [comment]
Closed #7172
