### ISSUE TITLE
Error When Importing Customers

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#7181]
nopCommerce version: 4.7 (latest from develop)

Steps to reproduce the problem:
I am unable to import a new customer list from an Excel file in the case of a new customer list.

![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/2a50999d-57e1-41e7-bb48-d8732e16d5b2)

Please check [this code snippet](https://github.com/nopSolutions/nopCommerce/blob/d31bc901064774f61fd92529b30689a4ec45867f/src/Libraries/Nop.Services/ExportImport/ImportManager.cs#L1945)

![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/9b0a377b-1b8b-41e0-9f29-34b970387e55)

If it's a new customer, lastPassword will be null at line 1945, which is the cause of the issue. Perhaps we need to check for null or verify if it's a new customer.

**Comment by skoshelev** [comment]
Closed #7181
