### ISSUE TITLE
Error printing a pdf on linux

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#7192]
nopCommerce version: latest from develop

Steps to reproduce the problem: 

I think there was a mistake in this commit https://github.com/nopSolutions/nopCommerce/commit/aa746f07c09ba6bae3301bd22feab1af0bb404a4
Why did you delete the `HarfBuzzSharp.NativeAssets.Linux` package? 
This brought back issue #6464.

**Comment by skoshelev** [comment]
Hi @duc-tv. Thanks for your help and active tracking of changes, it's my mistake, I'll return the library soon

**Comment by skoshelev** [comment]
Closed #7192
