### ISSUE TITLE
Extend Nopcommerce Admin Views Widgets 

### ISSUE THREAD

**Issue by abodehq** [nopSolutions/nopCommerce#7197]
In nopcommerce i wandered why the placement of admin widgets are inside the main <form tags>
which will prevent us if we want to extend any nopcommerce entity and show our section with custom form tag to save the changes .

for example : 
if we have a custom entity that will extend nopcommerce Product Attribute Value , and we want to show our custom form with its extra fields , so if we want to display this form using AdminWidgetZones.ProductAttributeValueDetailsBottom widget .

then this will not work cause two nested forms are not allowed !!!

i suggest to have an extra widget for each admin view pages which will allow plugin to extend nopcommerce functionalities with ease of use.

thanks,

**Comment by danFbach** [comment]
you could have your custom entity creator/editor open into a new page, as many other things do in the product editor.

**Comment by AndreiMaz** [comment]
@abodehq It'll require too many widgets to be added. Could you please ask an advice on [our forums](https://www.nopcommerce.com/en/boards/) about how to extend the admin area some other way? We use GitHub for issue tracking purposes only

**Comment by abodehq** [comment]
this is an issue cause there is no way that we add custom admin widget in any admin view using widgets cause its located inside nopcommerce form, so no way we can add our form to save our extend properties.

dont u thing this is an issue in the structure , u can just move any admin bottom widget to be placed after nopcommerce form .

what do you think?

**Comment by AndreiMaz** [comment]
@abodehq There are other ways to extend it. Even inside the same form. 

Could you please ask an advice on [our forums](https://www.nopcommerce.com/en/boards/) about how to extend the admin area some other way? We use GitHub for issue tracking purposes only
