### ISSUE TITLE
Suggestions to improvise filters in the admin area

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#7207]
Hi nopCommerce team,

I have a few suggestions to improvise filters in the admin area.

1. On the products list page, can we please add filters for products marked as new and featured products, both?
2. On the categories list page, can we please add an option to display sub-categories as well?
3. On the orders list page, can we please provide a way to filter orders by products?
4. On the customers list page, can we have a filter to search only active customers so we could export them only?
5. Can we also provide an option to select from fixed columns to load in the datatable, for example, out of box you show a few columns, but the admin could select which columns to display if they want to.

**Comment by atulrungta** [comment]
2. On the category list page in admin area, when you search for a category by its name for example, computers, can we also display sub-categories of computers too?
3. My bad, sorry :)
4. Thank you @AndreiMaz 
5. It would be better if you could provide something like this but still okay if you decide not to implement.

**Comment by AndreiMaz** [comment]
2. Thanks for details, Atul! We'll also leave it for customization
