### ISSUE TITLE
Error when importing Customers

### ISSUE THREAD

**Issue by duc-tv** [nopSolutions/nopCommerce#7209]
nopCommerce version: 4.7

Steps to reproduce the problem: 
When importing customers, we encountered an error:

![image](https://github.com/nopSolutions/nopCommerce/assets/52314713/e7acc1ac-2b05-4d21-ab19-b076ac910a02)

I have checked the code, and the error occurs in the function [ImportManager.ImportCustomersFromXlsxAsync](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/ExportImport/ImportManager.cs#L1723)

Currently, in the function, the variable [rolesToSave ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/ExportImport/ImportManager.cs#L1743) is declared for each customer, but it is not cleared after each iteration. This causes the error to occur from the second customer onward.

**Comment by skoshelev** [comment]
Closed #7209
