### ISSUE TITLE
IIS Localhost Issue with css and javascript

### ISSUE THREAD

**Issue by abodehq** [nopSolutions/nopCommerce#7214]
nopCommerce version: 4.7

I have downloaded nopcommerce 4.7 and using iis to run it locally so the path of my new site : http://localhost/EShopWeb/en

i have problem in loading javascript and css files so some time the path of resource http://localhost/EShopWeb/EShopWeb/...

so i fix it by change the code in \Presentation\Nop.Web.Framework\UI\NopHtmlHelper.cs for both css na javascript as below :

in public virtual IHtmlContent GenerateScripts(ResourceLocation location)
{
  if (route.Contains(pathBase))
  {
      result.AppendFormat("<script type=\"{0}\" src=\"{1}{2}\"></script>",
     MimeTypes.TextJavascript, "", route);
  }
  else
  {
      result.AppendFormat("<script type=\"{0}\" src=\"{1}{2}\"></script>",
      MimeTypes.TextJavascript, pathBase, route);
  }
           
}
and for css
public virtual IHtmlContent GenerateCssFiles()
{
 if(route.Contains(pathBase))
 {
     result.AppendFormat("<link rel=\"stylesheet\" type=\"{0}\" href=\"{1}{2}\" />",
  MimeTypes.TextCss, "", route);
 }
 else
 {
     result.AppendFormat("<link rel=\"stylesheet\" type=\"{0}\" href=\"{1}{2}\" />",
   MimeTypes.TextCss, pathBase, route);
 }
          
 result.AppendLine();
}

please let me know if have do it wrong or this actually a bug !!

**Comment by atulrungta** [comment]
@abodehq can you please share screenshot of your store configuration? This must be because of incorrect host value in your store configuration otherwise it's a bug.

**Comment by abodehq** [comment]
![image](https://github.com/nopSolutions/nopCommerce/assets/2095374/cc3da1e5-c1a0-4c33-9192-f2bd6b8440bd)
![image](https://github.com/nopSolutions/nopCommerce/assets/2095374/2d4707d0-4757-4e6e-a1cc-165f70d85299)

**Comment by atulrungta** [comment]
@abodehq can you please share screenshot of store setting? You will able to find store setting from the admin panel.

Something like Your_store_url/Admin/Store/Edit/1

**Comment by glhays** [comment]
If you don't have that registered in your host file of your local machine
it will not resolve when iis fires up so your domains will be different.

There are many community forum posts on Nop that address these local iis
setups for local host.

These git issues are meant for Issues not fixing setup issues on dev
machines. Just saying.

**Comment by AndreiMaz** [comment]
Please post all technical questions on [our forums](https://www.nopcommerce.com/en/boards/). We use GitHub for work items only

**Comment by abodehq** [comment]
![image](https://github.com/nopSolutions/nopCommerce/assets/2095374/3fc3ae16-5177-429a-922d-6ff1f51a55f0)
guys this issue is still exist even in the admin
![image](https://github.com/nopSolutions/nopCommerce/assets/2095374/3059dcf6-e354-4d76-94cc-5c5747e0e8b4)
please let me know if i missed anything

I believe its a bug

**Comment by abodehq** [comment]
i already suggest a fix that can work for any one face the same issue , please check my first post
