### ISSUE TITLE
Order details page (admin area). Responsive problem

### ISSUE THREAD

**Issue by arshyuo2** [nopSolutions/nopCommerce#7218]
nopCommerce version: 4.70.1

In version 4.7.01 in the admin section in the orders section in mobile mode,
There are problems with shipping address and billing grades
![shipping address](https://github.com/nopSolutions/nopCommerce/assets/65789306/671dbcf0-d1cf-44db-9a31-b8f98211c0ca)
![Biling   shipping](https://github.com/nopSolutions/nopCommerce/assets/65789306/c332a13a-83d6-4a9c-9a63-7cc5e87861c4)

**Comment by exileDev** [comment]
Closed #7218
