### ISSUE TITLE
XSS Vulnerability when adding a review to a product.

### ISSUE THREAD

**Issue by iamtron01** [nopSolutions/nopCommerce#7219]
nopCommerce version: 4.70.1

Steps to reproduce the problem: 

1. Login as a customer
2. Click on a product
3. Click Add your review
4. Enter, <script>prompt(1)</script> for the Review title:
5. Enter, <script>prompt(1)</script> for the Review text:
6. Click Submit Review
7. JS popup is displayed

![Screenshot 2024-06-09 133718](https://github.com/nopSolutions/nopCommerce/assets/21244184/d5a46423-9896-4bcd-be76-52e86465d188)

**Comment by AndreiMaz** [comment]
I cannot reproduce the issue on the clean installation. All entered text is encoded and scripts are removed

**Comment by AndreiMaz** [comment]
@iamtron01 I cannot reproduce the issue on the clean installation. All entered text is encoded and scripts are removed. Have you tested in the clean installation without any third-party plugins installed?
