### ISSUE TITLE
Password eye (reveal) support on the login page

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7225]
Let's support the password eye icon on the login page. It'll allow to show/hide entered passwords.

Add a new setting indicating whether this feature is enabled to the admin area > configuration > customer settings > "Password and security" block. It'll be enabled by default

Let's check whether all browsers have this functionality built-in (e.g. [Edge](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal) details). Or should we have a custom implementation for all browsers ([example](https://stackoverflow.com/questions/31224651/show-hide-password-onclick-of-button-using-javascript-only))?

Source: https://www.nopcommerce.com/en/boards/topic/99273/nopcommerce-login-password-reveal-eye-icon-functionality

**Comment by Arunkumarvp** [comment]
Password eye (reveal) support this functionality implementation is done ? let met  know me pls

**Comment by Arunkumarvp** [comment]
@AndreiMaz  can I take proceed to work on the feature assign to me this ticket

**Comment by AndreiMaz** [comment]
@Arunkumarvp You're more than welcome to make a pull request

**Comment by exileDev** [comment]
Closed #7225
