### ISSUE TITLE
I heard about nopcommerce. Conversation among developers that the multi-vendor feature will be removed?

### ISSUE THREAD

**Issue by ksaltik** [nopSolutions/nopCommerce#7227]
nopCommerce version: 

Steps to reproduce the problem: 
I heard about nopcommerce. Conversation among developers that the multi-vendor feature will be removed. Will you illuminate us in this regard

**Comment by AndreiMaz** [comment]
No, of course we do not plan to remove this functionality. It's available and will be available out of the box

**Comment by ksaltik** [comment]
Thank you Andrei
