### ISSUE TITLE
Bulk edit products

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7228]
Usually, when you want to edit a product you go to the edit page of that product. It doesn’t matter with a small change but will become complicated and time-consuming when you need to modify a bunch of products. 

Let's add support for a simple and easy way to bulk edit products. There will be a new page with standard filters - similar to the product list page:
- Select (checkbox)
- Product name
- Category + Search subcategories
- Manufacturer
- Vendor (automatically filter by the current vendor when logged-in by a vendor)
- Warehouse
- Product type
- Published

The grid will have the following columns:
- Product name
- SKU
- Price
- Old price
- Stock quantity
- Published
Each of them will be editable

And there will be a "Bulk save (selected)" button and a "Bulk save (all)" at the top left corner of the page. Once clicked all new entered values will be saved to the database.

A similar functionality already existed in old versions of nopCommerce (e.g. 1.90). But we had to remove it because of the limitations of the new KendoUI grid (we don't use it anymore)

**Comment by ahmadkq** [comment]
What if the product has combination attributes and the admin defines prices and stock there?

**Comment by AndreiMaz** [comment]
@ahmadkq Combinations won't be supported in bulk edit

**Comment by brandon7171** [comment]
It would be very helpful for a couple of our clients if availability start and end date was on this list. They have groups of products in a category that go live on a given date and end on a given date. It has been painful editing these fields one at a time. The other column they would love to see but not as important as availability dates is disable buy button.

**Comment by skoshelev** [comment]
Closed #7228
