### ISSUE TITLE
Customer birthday cannot be edited in admin area

### ISSUE THREAD

**Issue by DhavalPra95** [nopSolutions/nopCommerce#7234]
nopCommerce version: 4.70.0 To 4.70.3

Steps to reproduce the problem: Date not working properly.

EX : Admin > Customer >  Edit > Date of birth
<img width="955" alt="image" src="https://github.com/nopSolutions/nopCommerce/assets/157207999/79cd8594-a0cd-4803-b3fd-83f6dd46c6c2">

**Comment by DhavalPra95** [comment]
I have fixed the issue. Issue is date type. 
I have fixed by changed the type **date** to **date-local**.

**Comment by danFbach** [comment]
standard html date input value should be formatted yyyy-MM-dd.
i'm guessing kendoUI had a polyfill for this or something and dotnet's IHtmlHelper doesn't format dates correctly for inputs.
[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)

**Comment by danFbach** [comment]
sorry for two PR, made the changes through github website instead of project 😅
