### ISSUE TITLE
Allow vendors to manage his own discounts

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7241]
A vendor will be able to manage his own discounts in admin area > promotions > discounts. 

Each discount will have "VendorId" column (similar to what we have with "Product" entity). It'll be applied automatically to the current vendor on the "discounts" page when logged-in as a vendor. But a store owner will be able to filter discounts to the "Vendor" dropdownlist (similar to the "products" page in admin area).

The only support disocunt type for vendors will be "Assigned to products". No other discount types could be created. Then a vendor will be able to assigned his own products only to this discounts (the "Applied to products" tab).

Of course, all appropriate validations will be applied to the CRUD login in admin area, so vendors cannot manage discounts of third-party vendors or apply/remove discounts of other vendors.

**Comment by exileDev** [comment]
Closed #7241
