### ISSUE TITLE
Vendors. Allow customers to PM vendors (private messages)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7243]
Currently customers can contact vendors ("Allow customers to contact vendors" setting). Let's rename the hint of this setting to "Check to allow customers to contact vendors using the contacts form" to avoid misunderstanding. 

And then add a new setting "Allow customers to PM vendors" below with the following hint "Check to allow customers to contact vendors using the private messages". There should be a validation (the yellow warning message displayed - "Private messages are disabled. Do not forget to enable them.") when "ForumSettings.AllowPrivateMessages" is disabled (otherwise, it won't work).

So once enabled customers will see the "Send private message" button on the vendor details page (similar to the "Contact vendor" button)

**Comment by exileDev** [comment]
Closed #7243
