### ISSUE TITLE
Vendor reviews

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7244]
Add support for vendor reviews (written about a vendor).

Or it's ll better to have aggregated reviews, which will calculate the vendor review based on the reviews of its products.  The list of reviews will be displayed on the vendor page, which will be created by aggregating the reviews from all the vendor products sorted by date.

Also see https://www.nopcommerce.com/en/boards/topic/38639/vendor-reviews

**Comment by adityavardhan91** [comment]
Hey @AndreiMaz , can we discuss about it a bit more. I am a .NET full stack dev and interested to collaborate to this open source project. If its ok for you, I request you to arrange a call and give some knowledge transfer about this project (a 30 min call will be really great). If you are interested, just say hi to this message and I will share my zoom Id or something to connect. Thanks
