### ISSUE TITLE
Should be able to change the "Display Order" for Product Images by drag and drop

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#7246]
nopCommerce version: 4.60.3

Steps to reproduce the problem: Most modern application allow for dragging images in order to change the order for which they appear. It would be very nice to allow for this.

**Comment by glhays** [comment]
It is also very nice to order them by the way it currently is.

**Comment by RomanovM** [comment]
Duplicate of #656
