### ISSUE TITLE
Discounts caching issue for discounts with start-end datetime, discount not getting applied on defined time

### ISSUE THREAD

**Issue by ksbhadani** [nopSolutions/nopCommerce#7247]
nopCommerce version: 4.5+

Steps to reproduce the problem: 
Create a discount (applied to category/manufactured) with start date - <today> 3pm, end date - <today> 4pm,
when customers hit the category/product page at between 3pm to 4pm they did not see any discount, discount did not apply even after updating products to clear price cache, also same issue will happen if price cache is disabled

Problem is discounts are cached with start-end datetime filter, I think need to cache all discounts or 'showHidden' parameter should true by default, refer below code snippet

![image](https://github.com/nopSolutions/nopCommerce/assets/165811203/b6bb221e-91c1-447c-9db2-f52003e27195)

**Comment by AndreiMaz** [comment]
@ksbhadani All discounts are cached. And other parameters are filtered later (in memory).

Please see the hint of the "Start date" and "End date" inputs - "The start of the discount period in **Coordinated Universal Time (UTC)**." Do you enter them in UTC?

**Comment by ksbhadani** [comment]
@AndreiMaz Yes I am aware that those are UTC dates, if you check the code discounts are filters by dates before cache, also date filters are applied in memory after cache. We don't need to apply filters before cache

**Comment by skoshelev** [comment]
Closed #7247
