### ISSUE TITLE
Use valid language in message templates (order tokens)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7251]
nopCommerce version: 4.70

"AddOrderTokensAsync" method of the \Nop.Services\Messages\MessageTokenProvider.cs does not properly use "languageId" parameter. In some cases tokens are localized with the default (current working) language. For example, "Order.BillingStateProvince","Order.BillingCountry","Order.ShippingStateProvince","Order.ShippingCountry", "Order.PaymentMethod"

Source: https://www.nopcommerce.com/en/boards/topic/99440/language-in-message-templates

**Comment by skoshelev** [comment]
Closed #7251
