### ISSUE TITLE
Vendor attribute names are not translated in the admin UI

### ISSUE THREAD

**Issue by derBretti** [nopSolutions/nopCommerce#7252]
nopCommerce version: 4.70.3

Steps to reproduce the problem:
1. Create a vendor attribute
2. Add a translation for the vendor attribute name to any language
3. Switch the admin UI to the language, you added the translation for

The translation shows up in the vendor sign up form in the frontend but not in the admin UI.

**Comment by AndreiMaz** [comment]
It's by design. Please see https://github.com/nopSolutions/nopCommerce/issues/2158
