### ISSUE TITLE
Checkout attribute conditions not working as expected

### ISSUE THREAD

**Issue by piotrsz772** [nopSolutions/nopCommerce#7258]
nopCommerce version: 4.70.4

Steps to reproduce the problem: 
Remove all attributes create by default in nopcommerce. 
Add 2 attributes with values

1. Shipping option
  - bringing in furniture

no conditions

2. Floor
 - ground floor
 - floor 1
 - floor 2
 - floor 3
 - floor 4

Set up condition on attribute Floor if is checked bringing in furniture show Floor attribute.

On start it shows 2 attributes condition not working.

If i add thrid attribute textarea and put value inside it back to work

Video with a problem here: 

https://github.com/user-attachments/assets/8b9eecd2-6699-4e86-8b55-6840f4f1c651

**Comment by piotrsz772** [comment]
Comment this check resolve issue
![image](https://github.com/user-attachments/assets/9ae8ec0d-e3f0-4283-90a4-6eca76bf188c)

**Comment by exileDev** [comment]
@skoshelev It looks like these changes have been added here: https://github.com/nopSolutions/nopCommerce/commit/0c505e08eb4e2273c80fcd7a08b4ca5de097eba5

**Comment by skoshelev** [comment]
Closed #7258
