### ISSUE TITLE
Negative `ProductCategory.DisplayOrder` is set to 0

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7260]
nopCommerce version: 4.70.4 +

Steps to reproduce the problem: 
1. Edit a category that contains products
2. In the "products" section at the bottom of the page edit a product to set it's display order
3. Set the value to a negative number
4. Update the product
5. Negative Value is not stored and value is set to 0

## Notes
Using the network tab in your browsers dev-tools reveals that the negative number is transmitted to c#, but the model inside `CategoryController.ProductUpdate` already only contains 0. I could not find any code or action filter that introduce this behavior, so that we would be able to overwrite this functionality for our customers.

This previously worked in nopCommerce 4.60.x

## Expected behavior
Negative values should be store correctly. 

## Additional notes
Our customer relies on this feature heavily, as this increases his capability of sorting products as he likes without the need to change all other products assigned to this category.

Other `DisplayOrders` are unaffected by this change. The display order of the category itself can be changed to a negative value. The same goes for manufacturer.

This seems to only happens where the display order is can be changed inside a table. This can in example also be seen for the display order of payment methods

**Comment by duc-tv** [comment]
It also happens with the order of the product images. Pls check it.

**Comment by exileDev** [comment]
Closed #7260

**Comment by duc-tv** [comment]
@exileDev, please check it once again. I cannot change the order of the product images after upgrading to 4.70.4

**Comment by Manuel-Innovapps** [comment]
As far as I know, this has not yet been published into any release. If you want to experience this right now, you will need to generate a patch file from the commit and apply it locally. At least that's what we have done for our customers.

**Comment by exileDev** [comment]
@duc-tv Also, don't forget to configure the CLDR pattern for localization of client-side validation according to the current culture (Admin area -> Setting -> General settings).

**Comment by duc-tv** [comment]
Thank you all, it works fine now
