### ISSUE TITLE
Move/rename "PayPal Zettle" menu item

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7263]
nopCommerce version: 4.80

Currently the "PayPal Zettle" menu item is located in Admin area > Configuration > POS > PayPal Zettle.

Let's move it to Admin area > Configuration > PayPal Zettle. And rename it to "PayPal Zettle (POS)". So the final way will be Admin area > Configuration >  PayPal Zettle (POS).

It'll be located between "PayPal Commerce" and "Local plugins" menu items

**Comment by AndreiMaz** [comment]
@Mr-Coder-01 Sure, you're more than welcome to create a new pull request

**Comment by RomanovM** [comment]
Done. See https://github.com/nopSolutions/nopCommerce/commit/13dc33b0295b9dc15ac8f224f6bbd909a7ac6a84
