### ISSUE TITLE
Add a new "PayPal Commerce" menu item

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7264]
nopCommerce version: 4.80

Let's add a new "PayPal Commerce" menu item. The final breadcrumb will be in Admin area > Configuration >PayPal Commerce. It'll be located between "Web API" and "PayPal Zettle (POS)" menu items (related work item - https://github.com/nopSolutions/nopCommerce/issues/7263)

**Comment by RomanovM** [comment]
Done. Details in https://github.com/nopSolutions/nopCommerce/commit/0d47801ef2108bf52812514f3e2e1edff3b23398
