### ISSUE TITLE
Setting to make VAT number required or optional

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7265]
Let's add this setting to require VAT numbers to be entered. It could be very useful for B2B shops.

Add this setting to Admin area > Tax settings page > VAT block. It'll be a new child "'VAT number' required" setting displayed below the "EU VAT enabled" (when enabled). This setting will be disabled by deault. And it'll be used on the registation and "customer info" pages

Forum topics:

- https://www.nopcommerce.com/en/boards/topic/99613/make-vatnumber-mandatory-from-plugin
- https://www.nopcommerce.com/en/boards/topic/54032/suggestion-make-vat-field-per-checkbox-as-a-required-field
- https://www.nopcommerce.com/en/boards/topic/13117/vat-on-registration

**Comment by mgkyawkolwin** [comment]
can i work on the item which is already assigned to someone (e.g. this is already assigned to exileDev) and contribute to the project? Thanks.

**Comment by AndreiMaz** [comment]
@mgkyawkolwin You're more than welcome to create a pull request - https://docs.nopcommerce.com/en/developer/contribute/source-code.html

**Comment by exileDev** [comment]
Closed #7265
