### ISSUE TITLE
Add an option to upload file feature to the contact us page

### ISSUE THREAD

**Issue by piotrsz772** [nopSolutions/nopCommerce#7266]
nopCommerce version: 4.70

I would like to propose adding file upload functionality to the contact page in nopCommerce. This option would make it much easier for users to upload files via the contact form. This would make the system more modern and respond to customer needs.

**Comment by glhays** [comment]
I have found the contact us page a source for spammers to abuse. Opening it
to uploading files is a use of I/O storage that costs money. I find this
needs to be an optional feature or a customization. But then again you can
always disable the form all together. Which I have.

**Comment by RomanovM** [comment]
Duplicate of #1832

**Comment by themalikx** [comment]
@AndreiMaz can I contribute on this?
