### ISSUE TITLE
 Duplicate purchase confirmation message

### ISSUE THREAD

**Issue by musle** [nopSolutions/nopCommerce#7268]
nopCommerce version: 4.70.1

Steps to reproduce the problem: 
Digital products are usually purchased only once. If a user tries to repurchase, a refund will be needed, which can cause trouble for the store. So, can you add a feature that prompts a confirmation message saying, "**You have already purchased this item. Do you want to repurchase it?**" when the user adds a non-shippable item (usually a digital product) to their cart?

**Comment by AndreiMaz** [comment]
@musle Thanks a lot for suggestion. But it's quite specific and we'll leave it for customization.
