### ISSUE TITLE
Admin: order item pictures blurred

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7269]
nopCommerce version: 4.70.x

Steps to reproduce the problem: 
1. Go to https://admin-demo.nopcommerce.com/Admin/Order/Edit/5
2. Scroll down to the order items and have a look at that picture
3. Picture is scaled down to 75px but rendered at about 180px

(Github preview not so good, please click on the image or open the url by hand)
![image](https://github.com/user-attachments/assets/5bf24aec-f616-4719-96f2-ce68693b71df)

This does not happen on 4.60.x as the image is being rendered at exactly 75px.

**Comment by cklenk** [comment]
I actually just noticed this issue on a 4.60.6 site. It's only blurry in the admin/product/list. Lokos like it's trying to stretch the 75w thumbnail picture causing them to look blurry. Here is an example:
![image](https://github.com/user-attachments/assets/33caa4ad-f0b3-4077-9ec6-1d4008841888)

**Comment by Manuel-Innovapps** [comment]
@cklenk I think the most obvious product on your image just has a bad image ratio. But indeed in 4.60.6 The images in the product list are being downscaled to 75px as well, but rendered at about 100px

**Comment by exileDev** [comment]
Closed #7269
