### ISSUE TITLE
$0 discounts not applied to order

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7271]
nopCommerce version: 4.60.x

Steps to reproduce the problem: 
1. Create a new discount with a coupon code with $0 discount (same works with percentage based discounts)
2. Go to the cart and apply the discount
3. You will get a message indicating that the discount was applied: 
![image](https://github.com/user-attachments/assets/f83a1e9c-dda7-415d-abf7-799b983d735c)
4. Place the order
5. The discount is not visible in the order details page in the backend

This discount was created by the customer by accident, and he asked us what's wrong with the discount. After some fiddling around, we found out that the discount value was set to zero.

In our opinion, there are three possible solutions to this:
* Allow store admins to create $0 discounts, but also save them in the discount usage history and display them in the backend and frontend
* Give the store own a warning when saving a discount where no discount value is set
* Give the user a warning when applying the discount, that it could not be applied.

The current situation is irritating and will cause confusion for store owners and customers.

**Comment by AndreiMaz** [comment]
@Manuel-Innovapps Thanks a lot for suggestion. But currently we do not plan to widely add "foolproof" protection. Obviously they $0 discounts should not be created

**Comment by Manuel-Innovapps** [comment]
Totally agree, and fully understand.
