### ISSUE TITLE
Option to disable popular tags on catalog pages

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7272]
nopCommerce version: 4.70.x

Steps to reproduce the problem: 
1. Go to a category in the demo store (i.e. https://demo.nopcommerce.com/electronics)
2. See the popular tags / tag cloud in the left below the manufacturers
3. As of now, multiple of our customers wished that this could be disabled. They still want to see the products tags in the product details tags and use them to improve search results

**Comment by miritreus** [comment]
https://github.com/nopSolutions/nopCommerce/pull/7323

**Comment by DmitriyKulagin** [comment]
Closed - PR #7323
