### ISSUE TITLE
Incorrect initialization vector in the EncryptionService

### ISSUE THREAD

**Issue by David-Innovapps** [nopSolutions/nopCommerce#7273]
nopCommerce version: 4.70.4

Steps to reproduce the problem: 

1. In nopCommerce 4.60.6 encrypt a text with the EncryptText method in the EncryptionService
2. Update to 4.70.4
3. Decrypt the encrypted text using the DecryptText method in the EncryptionService
4. The decrypted text does not correspond to the original text

The problem is that the initialization vector is generated differently from version 4.70.x and is therefore not identical to the initialization vector in version 4.60.x.

**Comment by exileDev** [comment]
Hi, @David-Innovapps. After updating, make sure that the UseAesEncryptionAlgorithm setting is disabled. I tried to encrypt the client password, and it works fine. Are there any special conditions to reproduce the issue?

**Comment by David-Innovapps** [comment]
Hello @exileDev.  Yes UseAesEncryptionAlgorithm is set to false:
![Screenshot 2024-08-02 100051](https://github.com/user-attachments/assets/19b21dff-74c6-48d9-b97f-0ad9fbcfb6a2)

My initialization vector in 4.70.4:
![Screenshot 2024-08-02 100129](https://github.com/user-attachments/assets/81d6f7bb-e8af-40d4-8bbb-4c902c0b27e0)

My initialization vector in 4.60.6:
![Screenshot 2024-08-02 104758](https://github.com/user-attachments/assets/97548840-7d9e-4e6d-b640-e06315a6e392)

**Comment by exileDev** [comment]
@David-Innovapps, it looks like your encryption key has incorrect length. It must be 16 characters long, make sure you have entered the correct key on the general settings page. 

Closed #7273

**Comment by Manuel-Innovapps** [comment]
@exileDev I don't understand why you are assuming the key of my colleague is not 16 characters long? As you can clearly see in the screenshot he is showing the debug output of `provider.IV` which has exactly 8 characters, as the code above clearly illustrates.

**Comment by exileDev** [comment]
@Manuel-Innovapps  Um, yes, there are 8 characters, but they are from different places in the encryption key. This reproduces only when the key is longer than 16 characters, otherwise works fine.
