### ISSUE TITLE
Admin: Numbers are saved as text in the Excel order export

### ISSUE THREAD

**Issue by David-Innovapps** [nopSolutions/nopCommerce#7274]
nopCommerce version: 4.70.4

Steps to reproduce the problem: 

1. Go to https://admin-demo.nopcommerce.com/Admin/Order/List
2. Make an Excel export for all orders
3. Open the Excel file
4. For all numbers, it is displayed that they are formatted as text
![Screenshot 2024-07-31 090630](https://github.com/user-attachments/assets/59173195-6280-479c-aa71-a4783966d30b)

In version 4.60.6 the numbers are formatted correctly.
![Screenshot 2024-07-31 092132](https://github.com/user-attachments/assets/cc3f0311-bbd0-4b34-bafb-e0956cbfa11d)

**Comment by skoshelev** [comment]
Closed #7274
