### ISSUE TITLE
"User must change password" customer option

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#7281]
Add a new boolean setting when editing a customer, that forces them to change their password. Let's name it "User must change password at next login"

Often times we have elder customers who struggle to get into their accounts, so we like to set a simple, temporary, recovery password for them to get in, but would like to be able to force them to change the password upon login so that their accounts do not remain secured with a very weak password.

**Comment by exileDev** [comment]
Closed #7281

**Comment by danFbach** [comment]
Awesome! Thanks guys!
