### ISSUE TITLE
Use FirstOrDefaultAsync method on the PermissionService.DeletePermissionRecordCustomerRoleMappingAsync

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#7285]
We need to use the FirstOrDefaultAsync method instead of FirstOrDefault one on the DeletePermissionRecordCustomerRoleMappingAsync method from the PermissionService class

**Comment by skoshelev** [comment]
Closed by [this PR](https://github.com/nopSolutions/nopCommerce/pull/7283)

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/commit/324486b38f31c5730047128f31b7bfb1b1be60f9
