### ISSUE TITLE
URL from Google results redirects to page without CSS

### ISSUE THREAD

**Issue by ArthurInnovapps** [nopSolutions/nopCommerce#7286]
**nopCommerce version: 4.70.4**

We have a bug that the redirection link from the google search results open a URL which is bugged in nopCommerce ( without CSS). It redirects for example to https://demoshop.innovapps.de/tag/products?tagId=3 which has no css. Or a page like /category/products?categoryId=1

**Steps to reproduce the problem**

(optional): find a nopCommerec store via Google and open a url like that
1. or directly go to a store on the version 4.70.4 and go to "/tag/products?tagId=3" (enter a Tag ID that exists and has products mapped to it) 
You can use our examplepage: https://demoshop.innovapps.de/tag/products?tagId=3
![2024-08-08 11_14_01-demoshop innovapps de_tag_products_tagId=3](https://github.com/user-attachments/assets/f1e02942-66ae-483d-acf2-ab879692ddaf)

This page is opened from the method  "public virtual async Task<IActionResult> GetTagProducts(int tagId, CatalogProductsCommand command)" in line 293 in the CatalogController. It opens the partialView wich doesnt have any js or css attached to it.

There are 6 methods in CatalogController that return "PartialView". We should not allow to directly access them with GET (convert them to POST). Let's add them to robots.txt in our 4.70 minor version and then refactor code to POST in version 4.80

Any private modifications you made to your nopCommerce: no

**Comment by exileDev** [comment]
Closed  by https://github.com/nopSolutions/nopCommerce/commit/d4416596f0f3faba4ddc11a6be7d087b71d783ea

**Comment by patel-hitesh** [comment]
@AndreiMaz @exileDev  Recent changes made by the Nop Team have caused a failure.

In the test CanPrepareRobotsTextFile(), the line model.Trim().Split(Environment.NewLine).Length.Should().Be(101) is failing.
I believe the correct assertion should be model.Trim().Split(Environment.NewLine).Length.Should().Be(107).

**Comment by exileDev** [comment]
Thanks @patel-hitesh! Fixed https://github.com/nopSolutions/nopCommerce/issues/7333
