### ISSUE TITLE
VendorModel: Set PictureModel in PrepareVendorModelAsync

### ISSUE THREAD

**Issue by OzanOzcelikk** [nopSolutions/nopCommerce#7289]
nopCommerce version: 4.70

Steps to reproduce the problem: 

In VendorModel, there is a PictureModel property; however, it is not being set in the PrepareVendorModelAsync method. As a result, when users attempt to use the vendor's picture on pages like Views/Catalog/Vendor.cshtml, the picture is unavailable and returned as null. This means the vendor's image cannot be displayed or used on these pages.

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/pull/7291

**Comment by exileDev** [comment]
Closed #7289

**Comment by AndreiMaz** [comment]
See related bug - https://github.com/nopSolutions/nopCommerce/issues/7289
