### ISSUE TITLE
Javascript localizes value and changes the input value

### ISSUE THREAD

**Issue by ArthurInnovapps** [nopSolutions/nopCommerce#7290]
nopCommerce version: 4.70.4

Steps to reproduce the problem: 

1. Go to a Category (backend)
2. Scroll to the Product mappings
3. Change the Display order to -9876
4. Save the changes

Now you can see the display order is just 0.
In the picture you can see that the value in the payload gets localized with a comma:
![image](https://github.com/user-attachments/assets/24a4b316-32fc-4853-834a-2d545b9944f6)

This happens in Presentation\Nop.Web\Areas\Admin\Views\Shared\Table.cshtml in line 280 in the function updateRowData_@(tableName)(currentCells, data, nameData):

![image](https://github.com/user-attachments/assets/e5010c92-fc20-4864-9a8d-7cf16049f7e9)

You can only save displayorders "up" to -999, because on -1000 it adds a comma, changes it to -1.0 and somehow the display order gets set to 0.

**Comment by Manuel-Innovapps** [comment]
Relates: https://github.com/nopSolutions/nopCommerce/issues/7260

**Comment by exileDev** [comment]
Closed #7290
