### ISSUE TITLE
App settings not getting saved if appsettings_Environment.json file is present

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7292]
nopCommerce version: 4.60+

Steps to reproduce the problem: 

If the application contains an environment specific settings file, say for HostingConfig, to use forwarded proxies in production
When you try to disable UseProxy in the application administration (/Admin/Setting/AppSettings) , changes will not be saved, as it won't modify the correct file. It modifies the non environment specific file only. 

Consider checking current environment, if specific environment settings file is present, update that one, otherwise update default.

**Comment by exileDev** [comment]
Hi! Environment settings are an optional feature. If you add an additional appsettings.json file, you can also edit it manually. We don't want to make the basic functionality more complicated for store owners
