### ISSUE TITLE
Consider refactoring SslEnabled implementation for https

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7293]
Consider refactoring the SslEnabled/https logic in nopcommerce. 

Being an ecommerce platform, in majority of cases https will be needed for checkout. Having a forced https->http redirect doesn't have many use cases and leads to various issues, such as "too many redirects" or having to deal with the 301 redirect from https to http if enabling https after one year in production

Please consider dropping this redirect 
https://github.com/nopSolutions/nopCommerce/blob/324486b38f31c5730047128f31b7bfb1b1be60f9/src/Presentation/Nop.Web.Framework/Mvc/Filters/HttpsRequirementAttribute.cs#L108

And allow choosing between (301/302)
(https://github.com/nopSolutions/nopCommerce/blob/324486b38f31c5730047128f31b7bfb1b1be60f9/src/Presentation/Nop.Web.Framework/Mvc/Filters/HttpsRequirementAttribute.cs#L101)

Or even consider splitting SslEnabled into ForceHttps, ForceHttp so the https->http redirect can be disabled.

**Comment by AndreiMaz** [comment]
> in majority of cases https will be needed for checkout
Nowadays, https is required all all pages for security purposes. Not just not checkout pages. 

The current logic is absolutely OK. If someone enables SSL, then it should be enabled for all pages (no matter of number of redirections). Furthermore, redirection cache could be always reset

**Comment by alinmircea** [comment]
That is not the point I was making, redirection to https needs to happen on all pages. It's just not the same with redirection from https to http. That one should never happen. What is the point even, in 2024?
