### ISSUE TITLE
Can't add index on Topic.SystemName becase it's nvarchar(max)

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7294]
nopCommerce version: 4.60 +

Can't add index on Topic.SystemName becase it's nvarchar(max). Let's change it to nvarchar(400)

https://github.com/nopSolutions/nopCommerce/blob/324486b38f31c5730047128f31b7bfb1b1be60f9/src/Libraries/Nop.Data/Mapping/Builders/Topics/TopicTemplateBuilder.cs#L17

Please add SystemName in column definition in the builder so column gets created with limited length.

**Comment by exileDev** [comment]
Closed #7294
