### ISSUE TITLE
New products and slider images

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7301]
Add two new products and new Nivo Slider images

**Comment by curllog** [comment]
@AndreiMaz Hi Andrei , what you think about having swiper slider for demo and default site?

**Comment by AndreiMaz** [comment]
@curllog Thanks a lot for suggestion. I've just created a work item - https://github.com/nopSolutions/nopCommerce/issues/7302

**Comment by exileDev** [comment]
Closed #7301
