### ISSUE TITLE
Replace Nivo Slider with Swiper

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7302]
The Nivo Slider is not supported anymore (https://github.com/Codeinwp/Nivo-Slider-jQuery/issues/412). Let's replace it with a new one. 

The Swiper is good alternative. Find more at https://swiperjs.com/ and https://github.com/nolimits4web/swiper

**Comment by danielnutu** [comment]
it would be a good ideea to not have 5 slides max ...

**Comment by exileDev** [comment]
Closed #7302
