### ISSUE TITLE
IncludeFeaturedProductsInNormalLists parameter cannot be edited from Catalog Settings page

### ISSUE THREAD

**Issue by kadri1914** [nopSolutions/nopCommerce#7319]
nopCommerce version: 4.60.2

Steps to reproduce the problem: 
**_catalogSettings.IncludeFeaturedProductsInNormalLists** parameter cannot be edited from Catalog Settings page in administration panel.

I created a new component and showed the featured manufacturer products on the main page.

Then I realized that these featured products are not displayed when the manufacturer is filtered on the category pages. 

As excludeFeaturedProducts parameter to **_productService.SearchProductsAsync** function, the value is sent by checking **_catalogSettings.IgnoreFeaturedProducts** and **_catalogSettings.IncludeFeaturedProductsInNormalLists** settings. I searched for where to change this parameter in the administration panel but I could not find it.

Then, when I searched for the setting on the All Settings (advanced) page in the panel, I was able to find it and changed the value from false to true. In this way, my featured products started to be displayed on the category pages.

**Comment by dahalsanju741** [comment]
It might be the cache issue as discussed in the forum [https://www.nopcommerce.com/en/boards/topic/99441/4604-caching-issue/page/4](https://www.nopcommerce.com/en/boards/topic/99441/4604-caching-issue/page/4)

Did you verify if the value was also not updated in the Setting table on the database once you made the change in the Catalog setting?

**Comment by skoshelev** [comment]
Hi @kadri1914. This is not an issue, this is how it was intended. This is a rare setting and we did not put it in the UI. There are quite a lot of such settings, this is why we have the All Settings (advanced) page, which allows you to change any existing settings.
