### ISSUE TITLE
Public store. Autocomplete search should highlight matched terms (configurable)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#732]
Something similar to admin area menu search
1. Open \Views\Catalog\SearchBox.cshtml file
2. Add the following code to autocomplete js:
    `
   .data( "autocomplete" )._renderItem = function( ul, item ) {
               //highlight items
               var re = new RegExp("^" + this.term, "i") ;
               var t = item.label.replace(re,"<span class='autocomplete-matched-terms'>" + this.term + "</span>");
               return $("<li></li>")
               .data("item.autocomplete", item)
               .append("<a>" + t + "</a>")
               .appendTo(ul);
           };
   `
3. Add .autocomplete-matched-terms{font-weight:bold;color:black;} CSS style to all your themes

Source: http://stackoverflow.com/questions/2435964/jqueryui-how-can-i-custom-format-the-autocomplete-plug-in-results 

But there's a couple of issues:
1. We should highlight not only the beginning of words, but even matched words in the middle of found product names (it can be easily done). Also do not forget about scenarios when we search by several words and full-text is enabled
2. jQuery UI encodes rendered values by default. The above implementation does not.
   Also do not forget to create a setting in admin area whether to highlight matched terms or not

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
