### ISSUE TITLE
temp table DROPIFEXISTS functionality does not work 'properly'

### ISSUE THREAD

**Issue by awe-source** [nopSolutions/nopCommerce#7320]
nopCommerce version: 4.3+

Steps to reproduce the problem: 
Create a table in the database (such as temp guests to delete) with anything you like in it.
run the system
when the scheduled task runs that will trigger that operation (to delete guest accounts, as example) then the code in "create temp table" will throw SQL exception object with that name already exists, rather than (I assume) the intended behavior of dropping the temp table and just moving on...

MAYBE: this line in TempSqlDataStorage
base(dataConnection, storageName, query, tableOptions: _**TableOptions.NotSet |**_ TableOptions.DropIfExists)

NOTE: this may be a design problem with Linq2db rather than nopcommerce as surely "notset" and ANY other option are intended to be mutually exclusive...?! 
(I also note that from SQLprofiler, it seems as though this does NOT use the (supported according to the doco?) actual TEMPORARY table functionality (at least in SQLSERVER) as far as I can tell and literally just creates a TABLE NAMED TEMP, not an actual temp table... but again not sure if this is a NOP or a L2DB issue... although some of the doco indicates that "will not use temporary table functionality even if the underlying database system supports it", so there's a bit of inconsistency as to what it actually is supposed to do in this regard)

**Comment by AndreiMaz** [comment]
@awe-source Can you reproduce it on nopCommerce 4.70?

**Comment by AndreiMaz** [comment]
@exileDev Also see https://github.com/nopSolutions/nopCommerce/issues/5625

**Comment by awe-source** [comment]
yes 4.7 - the code has not changed, so...
anyway  "yes" you can just drop the table and move on with your life, however:
a) given the line I mentioned, I EXPECT that this "isn't working as intended" (given the flags/options set on that line I mentioned)
b) its really not that easy if you don't control the DB or theres a 3rd party that need to do this for you
c) its a pain/log spam when in dev/testing and the server is often restarted/breaking to always have to remove thsi "additional thing to do"

anyway, was just FYI

**Comment by exileDev** [comment]
This implementation was introduced when l2db didn't fully support temp tables. But it seems that temporary tables implemented by l2db still don't work in nopCommerce architecture. If a solution emerges, we will gladly consider any suggestions
