### ISSUE TITLE
Revisit Runtime Compiltion performance improvement issue

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7321]
nopCommerce version: current

Please revisit https://github.com/nopSolutions/nopCommerce/issues/3432 in .net 8

There are way to implement and to work around any issues. 
Load times without precompiled views are astronomical. 20+ seconds on initial page loads. 

https://www.nopcommerce.com/en/boards/topic/98139/performance-improvement-plugins-w-precompiled-razor-views#315677

**Comment by AndreiMaz** [comment]
Thanks a lot for your contribution. But I absolutely agree with this comment - https://github.com/nopSolutions/nopCommerce/issues/3432#issuecomment-2310260419

**Comment by AndreiMaz** [comment]
> you're constantly rebuilding all the views

That's not true. As stated [here](https://github.com/nopSolutions/nopCommerce/issues/3432#issuecomment-2310260419) Once a page has been built at runtime, it is cached. Furthermore, as stated [here](https://github.com/nopSolutions/nopCommerce/issues/3432#issuecomment-443611389) we cannot use precompiled views, cuz in this case it will be impossible to use themes (that in fact are separate views replaced on runtime)
