### ISSUE TITLE
Installation with the current develop build using MySQL server fail for authentication, but using raw connection string is ok

### ISSUE THREAD

**Issue by mgkyawkolwin** [nopSolutions/nopCommerce#7322]
nopCommerce version: current develop

Steps to reproduce the problem: 
Build and start the project for the first time
Leads to install page
use MySQL and fill out all required field
then it is failed ...
after trying a few times, i try to put the raw connection string at the install page and it worked perfectly

**Comment by skoshelev** [comment]
Closed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/97e37a40a29a220484b52702fab04de995b319c5)
