### ISSUE TITLE
Add some missing locales 

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#7324]
nopCommerce version:  4.70.5

> I tried nopCommerce 4.70.5 no source x64 version with fresh installation and Brevo configuration but saw this warning in log.
> 
> ```
> Log level
> Warning
> Short message
> Resource string (admin.configuration.emailaccounts.fields.tenantid.required) is not found. Language ID = 1
> Full message
> IP address
> 162.158.86.169
> Customer
> Page URL
> https://docs.nopadvance.com/Admin/EmailAccount/Edit/2
> Referrer URL
> https://docs.nopadvance.com/Admin/EmailAccount/Edit/2
> Created on
> 8/29/2024 5:03:23 AM
> ```

Source: https://www.nopcommerce.com/boards/topic/100707/resource-string-missing-adminconfigurationemailaccountsfieldstenantidrequired

Let's check all locales that were added in #7031

**Comment by exileDev** [comment]
Closed #7324
