### ISSUE TITLE
Allow to enable lock for order placement

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7325]
In some cases if could be helpful to allow a store owner to enable a lock when placing an order ("performwithlock").

For example. by executing a single packet attack, wherein multiple purchase requests are sent simultaneously the last bytes of said requests are held back and sent with a single packet. The server then processes the requests in parallel and a race condition occurs.

Let's allo to enable it. But with some conditions such as:
1. Only for the same customer
or
2. For orders that redeem the same gift cards (in order to avoid duplicated redeems)

But allow a store owner to disable it because in some cases it could lead to deadlocks. And this lock (setting) will be disabled by default

P.S.  Contact Andrei to get a detailed list of steps to reproduce the issue.

**Comment by skoshelev** [comment]
Closed #7325
