### ISSUE TITLE
Password validation error interpreting strings as string literal and not as raw html

### ISSUE THREAD

**Issue by coolio986** [nopSolutions/nopCommerce#7326]
nopCommerce version: 
4.70-bugfix

Steps to reproduce the problem: 
Register as a new user, use a password that doesn't meet your platforms password criteria.

In my case I have a 6 character minimum with one uppercase and lowercase character.

I am getting this in the form validation:

```<span class="field-validation-error" data-valmsg-for="Password" data-valmsg-replace="true">```
```"<p>must meet the following rules: </p><ul><li>must have at least 6 characters and not greater than 64 characters</li><li>must have at least one uppercase</li><li>must have at least one lowercase</li></ul>"```
```</span>```

The validation has quotes around the html markup which shows up in the register form as a string literal.

```<p>must meet the following rules: </p><ul><li>must have at least 6 characters and not greater than 64 characters</li><li>must have at least one uppercase</li><li>must have at least one lowercase</li></ul>```

**Comment by exileDev** [comment]
Closed #7326
