### ISSUE TITLE
"Add this" used in the page sharing has been discontinued

### ISSUE THREAD

**Issue by dahalsanju741** [nopSolutions/nopCommerce#7327]
nopCommerce version: 4.7

Steps to reproduce the problem: At the InstallationService, PageShareCode populates the "Add this" widget's code while installing the nopCommerce. But the service has been terminated [https://www.addthis.com/](https://www.addthis.com/ ) effective as of May 31, 2023. it would be better if we remove the code template used or use the alternative like [https://sharethis.com/](https://sharethis.com/)  or [https://www.addtoany.com/](https://www.addtoany.com/)

**Comment by AndreiMaz** [comment]
You cannot reproduce it in verdion 4.70 because it's been replaced in 4.60 - https://github.com/nopSolutions/nopCommerce/issues/6678

**Comment by dahalsanju741** [comment]
Looks like the problem is only on the demo website because it was upgraded rather than installed with 4.7.  [https://admin-demo.nopcommerce.com/Admin/Setting/Catalog](https://admin-demo.nopcommerce.com/Admin/Setting/Catalog)
