### ISSUE TITLE
EditType.Number modifies the decimal value if a leading zero is present in the decimal place

### ISSUE THREAD

**Issue by RenishSkills** [nopSolutions/nopCommerce#7328]
nopCommerce version: **4.70.5**

**Steps to reproduce the problem:** 
Navigate to Admin Area > Configuration > Shipping > Measures:
- In the Dimensions section, click Edit on any grid row.
- Change the "Ratio to primary dimension" to "1.01" (value with a zero after the decimal).

**Expected result:**
The system should save the value as "1.01".

**Actual result:**
The system converts the value to "1.1" and removes zeros after the decimal. It also does incorrect rounding. e.g. 1.0055 becomes 1.6

The problem occurs because the ColumnProperty "EditType" is set to "Number".
Altering Table.cshtml at line 279 as suggested may solve the issue. While these modifications have been tested in my particular scenario, it is crucial to verify them under various conditions.
```
if (input.attr('type') == 'number') {
    value = new Intl.NumberFormat("@CultureInfo.CurrentUICulture.Name", { useGrouping: false }).formatToParts(value)
        .map(({ type, value: vpart }) => //for some locales dotnet accepts latin digits, but still requires localized signs and separators
        {
            if (type == "integer") {
                return Globalize("@CultureInfo.CurrentUICulture.TwoLetterISOLanguageName").numberParser()(vpart);
            }
            else if (type == "fraction") {
                return vpart.split('').map(char => Globalize("@CultureInfo.CurrentUICulture.TwoLetterISOLanguageName").numberParser()(char)).join('');
            }
            else {
                return vpart;
            }
        })
        .reduce((string, part) => {
            return string + part;
        });
}
```

**Comment by exileDev** [comment]
Thank you, @RenishSkills! Closed #7328
