### ISSUE TITLE
Non-monetary discount/promotion type

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#733]
This simple feature will allow to have many promotions that can be processed manualy by the store staff.

Create a Non-Monetary discount (promotion) type which will not affect the order total amount Use percentage: 
Discount amount: could be hidden). It will only display (below the total amount) a description (as commented here) of the promotion such as: "You will be promoted to VIP Cusotmer"; "You will get product xxx for free", "You will get a present/surprise", "You will get double reward points from this order"; etc. This type has to be processed by storeowner in a manual fashion, thus it will be necessary to create a mail token with the list of earend promotions to notyfy/remind the storeowner/customer. Furthermore that list can be added as a note to the order. 

Forum source: http://www.nopcommerce.com/boards/t/17157/suggestion-non-monetary-discountpromotion-type.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
