### ISSUE TITLE
Error E_MISSING_BUNDLE: {"locale":"vi"}

### ISSUE THREAD

**Issue by hongviettien** [nopSolutions/nopCommerce#7330]
nopCommerce version: 4.70.5

Steps to reproduce the problem: 
When i select English in Admin and Edit data at "Shipping providers" table is fine, but if i switch to Vietnamese and Edit data, its will show error E_MISSING_BUNDLE: {"locale":"vi"}. Some others error the same.

**Comment by exileDev** [comment]
You should to configure the CLDR. Find out more in this discussion https://github.com/nopSolutions/nopCommerce/issues/7260#issuecomment-2253002015

**Comment by hongviettien** [comment]
Thanks, it work fine now!!!
