### ISSUE TITLE
IsTelecommunicationsOrBroadcastingOrElectronicServices No default value

### ISSUE THREAD

**Issue by Alerinos** [nopSolutions/nopCommerce#7331]
nopCommerce version: 4.70.4 dated 08.07.2024

Steps to reproduce the problem: 
```
Cannot insert the value NULL into column 'IsTelecommunicationsOrBroadcastingOrElectronicServices', table 'shop.dbo.Product'; column does not allow nulls. INSERT fails. The statement has been terminated.
```

The problem occurs after upgrading from 4.6 to 4.7 when copying a product. It is possible that the automatic migration is missing

```
[IsTelecommunicationsOrBroadcastingOrElectronicServices] BIT NOT NULL,
```
Missing a default value, the possibility of null or simply a value in the code when cloning a product.

**Comment by Alerinos** [comment]
A quick FIX for those with a similar problem:
```
ALTER TABLE [dbo].[Product]
ALTER COLUMN [IsTelecommunicationsOrBroadcastingOrElectronicServices] BIT NULL;
```
NOTE: I have not reviewed the application code, it may cause a side effect.

**Comment by Alerinos** [comment]
Next problem:
```sql
Cannot insert the value NULL into column 'UseDefaultCredentials', table 'shop.dbo.EmailAccount'; column does not allow nulls. INSERT fails.
The statement has been terminated.
```

**Comment by morsalinsobuj** [comment]
ALTER TABLE EmailAccount
ADD CONSTRAINT DF_EmailAccount_UseDefaultCredentials
DEFAULT 0 FOR UseDefaultCredentials;

**Comment by exileDev** [comment]
@Alerinos Seems that data migration (for 4.70) has not been applied. When upgrading from 4.60 to 4.70 out-of-the-box everything works fine. You can try to check the existence of migration record in the MigrationVersionInfo table. Just delete the record if it is there for some reason to reapply the migration

**Comment by exileDev** [comment]
See also #6890 & #7031
