### ISSUE TITLE
Discounts caching issue

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#7337]
nopCommerce version: 4.7

Steps to reproduce the problem: 

Discount cache goes out of sync on production site after some time, I don't know the steps to produce it and no idea about the root cause, problem is that product prices does not update after changing discounts/adding new discounts, also updated data does not show on discounts list page, problem is with all discount types - it works normally after clear cache, but stops again after some time

**Comment by AndreiMaz** [comment]
> I don't know the steps to produce it
Unfortunately, we cannot help here without a list of steps to reproduce the issue.

Just ensure that price caching is disabled on your catalog settings page

**Comment by kiranbhadani** [comment]
it's not just price caching issue, it's something to do with GetAllDiscounts caching as problem is also in discounts list

**Comment by ahmadkq** [comment]
@kiranbhadani I have the same issue. Did you figure out how to solve it?
@AndreiMaz the steps as follwoing (sometimes happened and solved when clear all cache):
1- Create a discount.
2- Customer applied the coupon.
3- Sometimes:
      a. Coupon is applied but discount value still 0.
      b. Coupon not found.

**Comment by kiranbhadani** [comment]
For me it was an issue with cache removal with prefix **RemoveByPrefixAsync(NopEntityCacheDefaults<TEntity>.AllPrefix)** it does not work some times, workaround it to create a CacheEventConsumer<Discount> and remove all discounts cache with key await **RemoveAsync(NopDiscountDefaults.DiscountAllCacheKey, string.Empty, string.Empty, true, discount.StoreId)**
