### ISSUE TITLE
FooterModel.IsHomePage always returns false if SeoFriendlyUrlsForLanguagesEnabled

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7339]
nopCommerce version: 4.70

The .IsHomePage property of the FooterModel will always return false if the setting LocalizationSettings.SeoFriendlyUrlsForLanguagesEnabled is set to true.  This setting is represented as a checkbox in the General Settings area of the Admin user interface as: "SEO friendly URLs with multiple languages enabled".

The IsHomePage property is set on this line of the CommonModelFactory.PrepareFooterModelAsync() method:

`IsHomePage = _webHelper.GetStoreLocation().Equals(_webHelper.GetThisPageUrl(false), StringComparison.OrdinalIgnoreCase)`

(side note: if you're wondering why my code does not exactly match the repository, it is because I am using a simple speed boost that can [perform .Equals() string comparisons 654% faster](https://www.nopcommerce.com/en/boards/topic/100767/possible-performance-boost-stringcomparisonordinalignorecase#316062).)

In that line above, .GetStoreLocation() will never equal _webHelper.GetThisPageUrl(false) when LocalizationSettings.SeoFriendlyUrlsForLanguagesEnabled is set to true because of the language slug that is injected into the url on only the right-hand expression.

Therefore FooterModel .IsHomePage will always return false if SeoFriendlyUrlsForLanguagesEnabled is set to true, regardless of what page the user is on.

Expected Behavior:

If StoreLocation is "https://site.com", FooterModel .IsHomePage should return true for the following urls when SeoFriendlyUrlsForLanguagesEnabled is set to false (this works fine):

"https://site.com"

If StoreLocation is "https://site.com", FooterModel .IsHomePage should return true for the following urls when SeoFriendlyUrlsForLanguagesEnabled is set to true (this does not work):

"https://site.com/en"
"https://site.com/fr"
"https://site.com/de"
Source: https://www.nopcommerce.com/en/boards/topic/100869/footermodel-ishomepage-always-returns-false-if-seofriendlyurlsforlanguagesenabled

UPDATE. See PR - https://github.com/nopSolutions/nopCommerce/pull/7367

**Comment by AndreiMaz** [comment]
See PR - https://github.com/nopSolutions/nopCommerce/pull/7367

**Comment by exileDev** [comment]
Closed #7339
