### ISSUE TITLE
Better social integration for News (and maybe forum, blog)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#734]
When I post a link on facebook to a news item on my Nop site, the preview data that shows up could be improved. The default site meta data is pulled into the preview, but pulling some info from the news story would make better sense. I havent tried the same for a forum or blog post, but assume they could be helped out too. Perhaps we could add the FBML tags to help with this.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
