### ISSUE TITLE
Discount Coupon code support for guest users

### ISSUE THREAD

**Issue by yeumatbeo** [nopSolutions/nopCommerce#7345]
nopCommerce version: 4.6

Steps to reproduce the problem: I've enabled the discount coupon code, and it works well for registered accounts. However, an issue arises with guest users. The problem comes from the function: ApplyDiscountCouponCodeAsync(Customer customer, string couponCode). For guest users, the system doesn’t behave correctly. For example, when guest user A adds a discount coupon code, guest user B will also have the same coupon applied, even though user B hasn't added it themselves. The system can't differentiate between guest users A and B when applying the coupon code.

**Comment by AndreiMaz** [comment]
@yeumatbeo It cannot be repuniroduced. Each guest has unique customer records (a [Customer] table). And discount codes are saved for the current customer (guest) only
