### ISSUE TITLE
Migrations do not respect appsettings command timeout

### ISSUE THREAD

**Issue by Shane32** [nopSolutions/nopCommerce#7346]
nopCommerce version: 4.7

Steps to reproduce the problem: 
- Create a giant nopCommerce database in an old version
- Attempt to migrate to the newest version (fails due to command timeout)
- Change appsettings command timeout property
- Try again (fails)

Suggestion:
- Modify the fluent migrator to utilize the command timeout from appsettings

See attached photos:

Appsettings:

![image](https://github.com/user-attachments/assets/a0ff261a-3498-4b0f-9d00-6b7e60fba46f)

App setting description:

![image](https://github.com/user-attachments/assets/68dcd0c8-bf19-45d6-a14d-13022e618488)

![image](https://github.com/user-attachments/assets/c86943ce-344f-46dc-9b52-d403f352bde5)

Code needed: (`WithGlobalCommandTimeout` was added, but needs to be modified to pull from appsettings)

![image](https://github.com/user-attachments/assets/58144343-a3d2-494d-85ce-f980a4235f11)

**Comment by skoshelev** [comment]
Closed #7346
