### ISSUE TITLE
PrepareOrderReviewDataModelAsync ->PickupAddress -> CountryName Localization

### ISSUE THREAD

**Issue by vilaspm** [nopSolutions/nopCommerce#7347]
https://github.com/nopSolutions/nopCommerce/blob/97e37a40a29a220484b52702fab04de995b319c5/src/Presentation/Nop.Web/Factories/ShoppingCartModelFactory.cs#L709C1-L709C65

Is there a reason why CountryName is not localized in PrepareOrderReviewDataModelAsync ->PickupAddress? 
Like:
CountryName = country != null ? await _localizationService.GetLocalizedAsync(country, x => x.Name, (await _workContext.GetWorkingLanguageAsync()).Id) : string.Empty,

That would eliminate the need to override ShoppingCartModelFactory in my case.

**Comment by skoshelev** [comment]
Hi @vilaspm.

The thing is that all PickupAddress fields are filled by the store owner in the administration area in one language, usually the same language in which reference tables are filled. I think adding localization only for the country and state in this case will not be entirely correct.
