### ISSUE TITLE
Update admin tour according to new PayPal Commerce plugin

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7351]
nopCommerce version: 4.80

Steps to reproduce the problem: 
We're going to introduce a new enhanced PayPal Commerce plugin in the upcoming nopCommerce 4.80. It has a new configuration page. Hence we have to update our admin tour according to new PayPal Commerce plugin

**Comment by exileDev** [comment]
Closed #7351
