### ISSUE TITLE
Login Successful but not working.

### ISSUE THREAD

**Issue by rsanjar** [nopSolutions/nopCommerce#7353]
nopCommerce version: 4.7 (latest as of 2024, Oct 1)

Steps to reproduce the problem: Set up everything. Install. And sign in with admin credentials. 
It says John Smith signed in but redirects back to log in page, basically considers it's not authenticated.

![image](https://github.com/user-attachments/assets/80fba7c4-cbb5-46e3-b671-3ea8baf64572)

**Comment by AndreiMaz** [comment]
Cannot reproduce the issue. The notification says that you're already logged in

**Comment by rsanjar** [comment]
Yes, it says logged in but I cannot go to any other page. I haven't changed
anything. Just set up the database, that's it.

-----------
Sanjar Rahmatov

**Comment by rsanjar** [comment]
I have even registered a new user and it was registered fine, checked the
database. After signing in only the sign in page is working, as if I am not
signed in.

-----------
Sanjar Rahmatov

**Comment by AndreiMaz** [comment]
Looks like you don't have permissions in [PermissionRecord] or [PermissionRecord_Role_Mapping] tables for some reasons. Please post on [our forums](https://www.nopcommerce.com/en/boards/) for more info
