### ISSUE TITLE
Make "Preview" button a dropdown button for multi-store support

### ISSUE THREAD

**Issue by Charlie-Brownie** [nopSolutions/nopCommerce#7355]
We recently changed our Product/Topic/Blog/etc pages so that the `Preview` button supports multi-store, using the same dropdown button as the `Export` button. Being able to select from one of the many stores is super handy for us.

![image](https://github.com/user-attachments/assets/4a10220c-f66e-4406-94e7-99060df12299)

See PR - https://github.com/nopSolutions/nopCommerce/pull/7363

P.S. This selection dropdownlist should be displayed only when you have several stores configured.

**Comment by AndreiMaz** [comment]
@Charlie-Brownie Sure, please make a PR

**Comment by Charlie-Brownie** [comment]
I looked at putting the `Favicon` into the drop down list but discovered that it only works in my company's solution because all of our stores have the same `<link>` format. So trying to support all use cases was never going to work. So I abandoned that idea.

**Comment by AndreiMaz** [comment]
https://github.com/nopSolutions/nopCommerce/pull/7363

**Comment by AndreiMaz** [comment]
@Charlie-Brownie Thanks a lot! We'll check it

**Comment by Charlie-Brownie** [comment]
> P.S. This selection dropdownlist should be displayed only when you have several stores configured.

Updated my PR to reflect this requirement 👍
Makes sense since non-multistore configurations would have to do an extra unnecessary step

**Comment by DmitriyKulagin** [comment]
Closed #7363 #7355
