### ISSUE TITLE
UPS Plugin is not Tracing the rates response

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#7356]
nopCommerce version: 4.70

Steps to reproduce the problem:
 In the UPS plugin, select the **Tracing** checkbox.
 Go through checkout up until you see the shipping methods/rates.
 Go to **System Log.**

You will see messages, from bottom up. (or do SQL query order by Id)
```
UPS rates. Request: Method: POST, RequestUri: 'https://wwwcie.ups.com/security/v1/oauth/token' ...

UPS rates. Response: StatusCode: 200, ReasonPhrase: 'OK', ...
Content: {"token_type":"Bearer",...

UPS rates. Request: Method: POST, RequestUri: 'https://wwwcie.ups.com/api/rating/v2403/Shop?additionalinfo=', ...
Content: {"RateRequest":{"Request":{"RequestOption":"Shop"},...
```

There is no logged message for the response to the rate request.

**Comment by skoshelev** [comment]
Closed #7356
