### ISSUE TITLE
My Account>Change Password -->RegexParseException: Invalid pattern 

### ISSUE THREAD

**Issue by uyanderya** [nopSolutions/nopCommerce#7357]
nopCommerce version: 4.80.0 with .NET 8.0.8

Steps to reproduce the problem: 
Login
My Account
Change Password
-Key in the old and new passwords,-
-Click "Change" button-

Internal server error at Nop.Web.Framework.Validators.PasswordPropertyValidator Line: 52

**Comment by exileDev** [comment]
@uyanderya Couldn't reproduce. Can you provide settings from **Customer settings -> Password and security** section in the admin area?

**Comment by exileDev** [comment]
I've created a task (#7375) to add validation for some password settings. It might help Closed #7357
