### ISSUE TITLE
Runtime Views

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7358]
NopCommerce constantly rebuilds views. It's not just the first time the application starts, it's constantly when you're fighting for memory. 

**Saying this is not a change you want to make because it impacts development is not only lazy, but also missing the whole point of why you're building a platform. Is it not built for production ?**

The whole platform is a big cache, memory should be a priority. 

Runtime views are cached by .net. Switching to build time views is a simple change and has no impact on development. 

Please take a few hours to look through the .net framework code and actually consider what switching to build time views means. It's a very simple change:
if debug -> runtime view
if release -> buildtime view

https://github.com/nopSolutions/nopCommerce/issues/7321#issuecomment-2392036116

**Comment by AndreiMaz** [comment]
Please do not duplicated issues - https://github.com/nopSolutions/nopCommerce/issues/7321
