### ISSUE TITLE
Suggest to put all the language folders to to dedicated one

### ISSUE THREAD

**Issue by fr2e2s** [nopSolutions/nopCommerce#7361]
nopCommerce version: 4.70.5 and all

Steps to reproduce the problem: 
You can find all the language folders in the root folder along with other functional folders. This seems mess to end user, can you put all the language folders into a dedicated one to make the structure more clear?

Thank you.

**Comment by AndreiMaz** [comment]
We do not manage where and how these directories are created. Please see https://www.nopcommerce.com/en/boards/topic/75470/removing-unused-languages
