### ISSUE TITLE
Make VatNumber requireable from backend for registration

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7365]
nopCommerce version: 4.70.0+

Steps to reproduce the problem: 
1. Navigate to https://admin-demo.nopcommerce.com/Admin/Setting/CustomerUser
2. Scroll down to the customer form fields section
3. Have a look at the customer form fields section
4. See that there is no option to make the vat number required during registration

Note: The setting could also be shown in the "Tax settings" if easier, but currently it's also not possible to mark it as required there.

**Comment by AndreiMaz** [comment]
Manuel, Thanks a lot for your suggestion. We already have this work item - https://github.com/nopSolutions/nopCommerce/issues/7265
