### ISSUE TITLE
Encoded validation message in customer registration form

### ISSUE THREAD

**Issue by mario-mantese** [nopSolutions/nopCommerce#7374]
nopCommerce version: demo site

Steps to reproduce the problem: 
Go to registration page, insert dummy data with a really short password like 'aa'
Press register, the validation message is HTML encoded:
![image](https://github.com/user-attachments/assets/85cddf8f-4952-4140-80d7-7b89ae7667a5)

**Comment by mario-mantese** [comment]
Solved in my custom theme with this code swap:
   @* <span asp-validation-for="Password"></span> *@
   <span>@Html.Raw(HttpUtility.HtmlDecode(await Html.ValidationMessageFor(m => m.Password).RenderHtmlContentAsync()))</span>

**Comment by exileDev** [comment]
Duplicate #7326
