### ISSUE TITLE
Find customers and orders by phone number

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#739]
In the admin area under Manage Customers. I mish the possibility to find customers via their phonenumber. Some customers have the most odd email adresses or usernames, and at times they can be spelled in many ways.

Maybe it was an idea to add it to the orders list as well. 

Enable it only when appropriate feature is enabled. For customer list page it's a customer attribute. For order list page it's an address attribute (we'll search in billing addresses in this case)

Partial search

Forum source: http://www.nopcommerce.com/boards/t/14933/manage-customers.aspx

**Comment by skoshelev** [comment]
We already have a possibility to search customer by phone number (https://github.com/nopSolutions/nopCommerce/commit/05abf6e8e991b2b16b8a0e7bafc8bb33e9fae004)

Closed #739
