### ISSUE TITLE
Allow a store owner to define which product attributes are non-combinable

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#74]
We already support non-combinable attributes in version 3.60. Now they are hard-coded to attributes with the following attribute types: textbox, multiline textbox, file upload, date picker. 

Let's add a new property to ProductAttributeMapping entity. This way a store owner can define which exactly product attributes are non-combinable 

Forum source: http://www.nopcommerce.com/boards/t/27525/suggestion-combinablenon-combinable-product-attributes.aspx and http://www.nopcommerce.com/boards/t/27076/suggestion-attribute-combinations-wildcards.aspx 

[AM] By the way, it's quite easy to customize the solution to support it. Just add a new property to ProductAttributeMapping entity and use it in "IsNonCombinable" method of ProductAttributeExtensions

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
