### ISSUE TITLE
'Partially refund (online and offline)' method should mark payment status as 'Refunded' (not 'Partially refunded') if the order total amount is fully refunded

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#740]
'Partially refund (offline)' method should mark payment status as 'Refunded' (not 'Partially refunded') if the order total amount is fully refunded. For example, order total is $100. The first partial refund is $60 (payment status is 'partially refunded'). But the second partial refund is $40 should mark payment status as 'refunded' (now it still marks it as 'partially refunded') 

'PartiallyRefundOffline' method of 'OrderProcessingService'. 
//if (order.OrderTotal == totalAmountRefunded), then set order.PaymentStatus = //PaymentStatus.Refunded; 

P.S. The same should be done for online refunding

**Comment by skoshelev** [comment]
Closed #740
