### ISSUE TITLE
Issue with Override Attribute Price Not Displaying When Product Price is 0

### ISSUE THREAD

**Issue by emregurhan** [nopSolutions/nopCommerce#7401]
nopCommerce version:  4.70.4 and 4.70.5

Steps to reproduce the problem: 
When the Price field is set to 0 in our products and an Override Price value is entered in the Attributes section, the product price appears as 0 in the category view. However, since a specific price is defined in the Override Price field, this value should be displayed.

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/7402
