### ISSUE TITLE
“From” price not updating correctly with product attribute overrides

### ISSUE THREAD

**Issue by emregurhan** [nopSolutions/nopCommerce#7402]
nopCommerce version: 4.70.4 and 4.70.5

Steps to reproduce the problem: 

In the product detail page (and in the category view), when there are prices set in the Product Attribute’s “Override” field, the “From” price is not being recognized if discounts are applied afterward. Additionally, if a price is defined in the product card’s “Price” field, the system consistently pulls the initial value instead of dynamically updating based on selected attributes.

When selecting different attributes with override prices, the “From” price should ideally reflect the override prices defined for each attribute. However, this functionality does not work as expected for products with attributes. This leads to incorrect pricing display, causing user confusion on products with multiple attribute options.

**Comment by AndreiMaz** [comment]
@emregurhan Have you checked with the "catalogSettings.DisplayFromPrices" setting enabled?

**Comment by emregurhan** [comment]
@AndreiMaz 


Settings:
	•.      catalogSettings.DisplayFromPrices= True;
	•	Product price = 0

In this case, when only override prices are available in the AttributeCombination field:

Product List

	•	The lowest override price is displayed: instead of £250.00, it shows as From £175.00.
	•	The minimum price entered in the override field appears.

Product Detail Page

	•	Before applying the discount code, it shows £250.00.
	•	After applying the discount code, it shows only £175.00.

On the product detail page, the “From” price is not displayed; only the amount after applying the discount is shown.


**Scenario 2:**
	•	Product.Price = 175

When I set only the lowest price in the main product price field, this price appears as the “From” price on the product detail page. However, when selecting a different product option, the correct price including the discount is displayed for the selected product, but the “From” price does not update.
