### ISSUE TITLE
 Product Attribute Override Price Discrepancy in Basket with Discount Code

### ISSUE THREAD

**Issue by emregurhan** [nopSolutions/nopCommerce#7404]
nopCommerce version:  4.70.4 and 4.70.5

Steps to reproduce the problem: 

When a discount code is applied on the cart page, the “from price” for a product with overridden product attribute prices does not update as expected. The main price displays correctly, but the override price loses its individual discount calculation and appears as a single discounted price across all attributes.

**Sample;**

Before discount

2,297.00 |   | 2,297.00

After using discount code
1,607.90 |   | 1,607.90You save:689.10

**Comment by AndreiMaz** [comment]
duplicates https://github.com/nopSolutions/nopCommerce/issues/7402
