### ISSUE TITLE
Products can have duplicate Specification Attributes

### ISSUE THREAD

**Issue by Charlie-Brownie** [nopSolutions/nopCommerce#7413]
nopCommerce version:
develop

Steps to reproduce the problem: 
1. Find a product with an existing `Option` attribute
2. Add the same `Attribute Option`
3. There is now 2 of the exact same attribute

This has no adverse effects as everything operates normally in the shop (Haven't tested, but if the `Allow Filtering`, `Show On Product Page`, or `Display Order` are different between duplicates you could get some unexpected behavior), it does make the data a bit muddy (I'm trying to do my own Export/Import with the `SpecificationAttributeOption` `Name` values as opposed to the current Export/Import that uses `Id`).

Any chance this could be addressed to prevent duplicates from entering the DB?

![image](https://github.com/user-attachments/assets/67b5ac79-6268-41c7-87bb-cb3e9bcf4dcd)

**Comment by AndreiMaz** [comment]
Charlie, thanks a lot for your suggestion! But we'll leave it for customization. It should be managed by store owners
