### ISSUE TITLE
Omnisend plugin settings not initialized

### ISSUE THREAD

**Issue by DmitriyKulagin** [nopSolutions/nopCommerce#7414]
nopCommerce version: develop

Steps to reproduce the problem: http://localhost:15536/en/if-you-wait-donation

InvalidOperationException: Nullable object must have a value.

![image](https://github.com/user-attachments/assets/5b51721b-05c3-4bb5-980a-48b3ec38b9bb)

**Comment by skoshelev** [comment]
Closed #7414
