### ISSUE TITLE
Newsletter subscription are not deleted when using SuffixDeletedCustomers setting

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#7419]
nopCommerce version: 4.70.5

> I added one of the existing accounts to the newsletter and deleted his customer record in the admin interface. The email was removed from the NewsLetterSubscription table as you would expect.
> 
> The issue is that we change the setting customersettings.suffixdeletedcustomers to true on all installs so emails are updated with -DELETED at the end.
> 
> I updated this setting to true and added email to the newsletter.   When I deleted customer record, his email was not removed from the NewsLetterSubscription table.

Source: https://www.nopcommerce.com/boards/topic/101350/brevo-newsletter-deleted-accounts

**Comment by skoshelev** [comment]
Closed #7419
