### ISSUE TITLE
Print Packaging Slip with Manufacturer Codes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#742]
Currently when you print a packaging slip, it defaults to the product SKU. It would be nice if there was either a second option or a setting that could be changed to print the order using the manufacturer code's instead. This would be very beneficial for people doing drop shipping. 

Source: http://www.nopcommerce.com/boards/t/13703/feature-request-print-packaging-slip-with-manufacturer-codes.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization
