### ISSUE TITLE
Add activity log for "Delete selected" methods

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#7426]
nopCommerce version: 4.70.5

Currently some "Delete selected" methods in admin area do not properly save activity log (e.g. for products). We should save activity log records for each deleted method. The same way like we do in the "DeleteSelected" method of \Areas\Admin\Controllers\ManufacturerController.cs (see the "foreach")

P.S. Please note that not all methods should have save individual activity log. For example, there is no need to do it for "Log" (\Areas\Admin\Controllers\LogController.cs) or "Queued emails"

**Comment by skoshelev** [comment]
Closed #7426
