### ISSUE TITLE
Error while editing ACL

### ISSUE THREAD

**Issue by Hamidnch** [nopSolutions/nopCommerce#7430]
nopCommerce version: 

Steps to reproduce the problem:
First, I denied admin access to manage Import/Export in the customer section and then granted it again and it worked without any problems.
 When I was checking and opening the sub-items of other sections on this page, I encountered this error as shown in the picture.
 ![image](https://github.com/user-attachments/assets/f549a487-2978-4942-b244-cab70a9ce601)

Apart from this issue, I also had a suggestion, that it would be better if it could be hidden by denying access to the display of that section on the desired page, for example, if Import/Export access was taken in the customer section, as a result those buttons on that page Do not display at all.

**Comment by skoshelev** [comment]
Hi, @Hamidnch.
I couldn't reproduce the problem, maybe it was an isolated failure. 
Do you have a record with error details in your logs?
If you have a systemic problem, please write a full list of steps so that I can check what the problem is.

**Comment by Hamidnch** [comment]
Hi, @skoshelev.
I tried again to make this error happen, but it was not seen anymore!
Maybe the problem is due to reducing the RAM resources of my system.
 I'm sorry for bothering you.
