### ISSUE TITLE
Admin.Common.Validation.NotEmpty

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#7435]
nopCommerce version:  4.80 beta

Steps to reproduce the problem: 
1) I downloaded the latest with source
2) Ran a fresh install on my localhost
3) Went to site settings, saved my site with out a 'logo'
4) Get the error:
![image](https://github.com/user-attachments/assets/37557794-741b-4178-916a-35b84568ae1e)

But I do see it in the local settings:
![image](https://github.com/user-attachments/assets/f77ece4c-477a-4a5d-af55-f8ad0d118e14)

**Comment by exileDev** [comment]
Closed #7435
