### ISSUE TITLE
Change URL structure doesn't work correctly 

### ISSUE THREAD

**Issue by beljk** [nopSolutions/nopCommerce#7436]
nopCommerce version: 4.7

Steps to reproduce the problem: i would like to change url patter for products,categories and tags
we should change this patters from GenericUrlRouteProvider.cs 
` var genericPattern = $"{lang}/{{{NopRoutingDefaults.RouteValue.SeName}}}";
 var genericCatalogPattern = $"{lang}/{{{NopRoutingDefaults.RouteValue.CatalogSeName}}}/{{{NopRoutingDefaults.RouteValue.SeName}}}";
 var productPattern = $"{lang}/product/{{{NopRoutingDefaults.RouteValue.SeName}}}";
 var categoryPattern = $"{lang}/category/{{{NopRoutingDefaults.RouteValue.SeName}}}";
 var tagPattern = $"{lang}/tag/{{{NopRoutingDefaults.RouteValue.SeName}}}";
 var blogPattern = $"{lang}/blog/{{{NopRoutingDefaults.RouteValue.SeName}}}";

 //generic routes (actually routing is processed later in SlugRouteTransformer)
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(genericPattern);
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(genericCatalogPattern);
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(productPattern);
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(categoryPattern);
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(tagPattern);
 endpointRouteBuilder.MapDynamicControllerRoute<SlugRouteTransformer>(blogPattern);

 //routes for not found slugs
 if (!string.IsNullOrEmpty(lang))
 {
     endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.GenericUrlWithLanguageCode,
         pattern: genericPattern,
         defaults: new { controller = "Common", action = "GenericUrl" });

     endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.GenericCatalogUrlWithLanguageCode,
         pattern: genericCatalogPattern,
         defaults: new { controller = "Common", action = "GenericUrl" });
 }

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.GenericUrl,
     pattern: $"{{{NopRoutingDefaults.RouteValue.SeName}}}",
     defaults: new { controller = "Common", action = "GenericUrl" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.GenericCatalogUrl,
     pattern: $"{{{NopRoutingDefaults.RouteValue.CatalogSeName}}}/{{{NopRoutingDefaults.RouteValue.SeName}}}",
     defaults: new { controller = "Common", action = "GenericUrl" });

 //routes for entities that support catalog path and slug (e.g. '/category-seo-name/product-seo-name')category
 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.ProductCatalog,
      pattern: productPattern,
     defaults: new { controller = "Product", action = "ProductDetails" });

 //routes for entities that support single slug (e.g. '/product-seo-name')
 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.Product,
     pattern: productPattern,
     defaults: new { controller = "Product", action = "ProductDetails" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.Category,
     pattern: categoryPattern,
     defaults: new { controller = "Catalog", action = "Category" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.Manufacturer,
     pattern: $"{lang}/{{{NopRoutingDefaults.RouteValue.SeName}}}",
     defaults: new { controller = "Catalog", action = "Manufacturer" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.Vendor,
    pattern: $"{lang}/{{{NopRoutingDefaults.RouteValue.SeName}}}",
     defaults: new { controller = "Catalog", action = "Vendor" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.NewsItem,
     pattern: genericPattern,
     defaults: new { controller = "News", action = "NewsItem" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.BlogPost,
     pattern: blogPattern,
     defaults: new { controller = "Blog", action = "BlogPost" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.Topic,
     pattern: genericPattern,
     defaults: new { controller = "Topic", action = "TopicDetails" });

 endpointRouteBuilder.MapControllerRoute(name: NopRoutingDefaults.RouteName.Generic.ProductTag,
     pattern: tagPattern,
     defaults: new { controller = "Catalog", action = "ProductsByTag" });
   `

All changes done and sample of the product url is shown correctly as i want in all of pages like category and homepage _www.example.com/en/product/{slug}_  but unfortunately when open the product and after 2 second i see the url changes to the default  _www.example.com/en/{slug}_ 
i have check Href also to make sure it's correct
`
<a href="/en/product/coffe-table" title="Show details for Clamy Side table Natural wood with Metal "></a>
`
it was working in v4.5 but in the last version it's not working correctly

**Comment by AndreiMaz** [comment]
Please post all technical questions on [our forums](https://www.nopcommerce.com/en/boards/). We use GitHub for work items only
