### ISSUE TITLE
Make it easier for developers to add entities (tables) that have direct relationships (EF) with existing entities (tables)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#744]
The goal here is allow better integration of extentions (more than what is there with plugins) that allows developers to add tables that have relationships (using Entity Framework) with existing tables while keeping as much as possible a clean separation between the code base and extention so as to make upgrades easier. See discussion http://www.nopcommerce.com/boards/t/11315/how-to-extending-nopcommerce-v20.aspx?p=4

**Comment by AndreiMaz** [comment]
Not possible with EF
