### ISSUE TITLE
Header to select all does not select all

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#7441]
nopCommerce version: 4.80 beta

Steps to reproduce the problem:

1. I downloaded the latest with source
2. Ran a fresh install on my localhost
3. Navigate to any page in admin where there is a list
4. Click the Check Box in the first column to select everything in the list
5. Doesn't select everything

![image](https://github.com/user-attachments/assets/f3e491ff-bd4c-445e-aa70-d2ad8f4d590b)

**Comment by AndreiMaz** [comment]
Please see https://github.com/nopSolutions/nopCommerce/commit/84387d729a8df76967d5bf6f05b96128c8ec4331

**Comment by Ochapparel** [comment]
Thanks!
