### ISSUE TITLE
MessageTokenProvider.WriteTotalsAsync - Extra whitespace between valule and "em" breaks td padding

### ISSUE THREAD

**Issue by alinmircea** [nopSolutions/nopCommerce#7443]
nopCommerce version: current

MessageTokenProvider.WriteTotalsAsync

https://github.com/nopSolutions/nopCommerce/blob/263a16bd8b98f8be5aeb94471496ce820ed8ef6c/src/Libraries/Nop.Services/Messages/MessageTokenProvider.cs#L699C34-L699C50

Extra whitespace between valule and "em" breaks td padding, on multiple lines starting 817:

`padding:0.6em 0.4 em;`

https://github.com/nopSolutions/nopCommerce/blob/263a16bd8b98f8be5aeb94471496ce820ed8ef6c/src/Libraries/Nop.Services/Messages/MessageTokenProvider.cs#L817

**Comment by exileDev** [comment]
Closed #7443
