### ISSUE TITLE
Docker is not create container

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#7448]
nopCommerce version: 4.80

After the changes made in ticket #7428, the docker container stopped building, we need to make corrections to the Dockerfile file

**Comment by skoshelev** [comment]
Closed #7448

**Comment by vfalcata** [comment]
I am getting build errors with the latest version, 4.80.6. 
I am on windows 11, basically a fresh install, with docker desktop. I am following the nopcommerce documentation for using it with docker.
Note that when I pull the older 4.80.1 the image is built fine.
