### ISSUE TITLE
Category sub categories incorrectly show parent category image

### ISSUE THREAD

**Issue by firthy** [nopSolutions/nopCommerce#7456]
nopCommerce version: 4.80.0

Steps to reproduce the problem: 

CatalogModelFactory > PrepareCategoryModelAsync

line:  551
                return new CategoryModel.SubCategoryModel
                {
                    Id = curCategory.Id,
                    Name = await _localizationService.GetLocalizedAsync(curCategory, y => y.Name),
                    SeName = await _urlRecordService.GetSeNameAsync(curCategory),
                    Description = await _localizationService.GetLocalizedAsync(curCategory, y => y.Description),
                    **PictureModel = await PrepareCategoryPictureModelAsync(category)**
                };
Should be
                return new CategoryModel.SubCategoryModel
                {
                    Id = curCategory.Id,
                    Name = await _localizationService.GetLocalizedAsync(curCategory, y => y.Name),
                    SeName = await _urlRecordService.GetSeNameAsync(curCategory),
                    Description = await _localizationService.GetLocalizedAsync(curCategory, y => y.Description),
                    PictureModel = await PrepareCategoryPictureModelAsync(curCategory)
                };

cheers
Mark

**Comment by AndreiMaz** [comment]
@firthy Mark, thanks a lot for reporting. Alerady reported and fixed - https://github.com/nopSolutions/nopCommerce/issues/7453
