### ISSUE TITLE
CSS file paths incorrectly generated when Nop is a Sub Application in IIS

### ISSUE THREAD

**Issue by firthy** [nopSolutions/nopCommerce#7457]
nopCommerce version: 4.80.0

Steps to reproduce the problem: Set Nop as a sub application in IIS

NopHtmlHelper > GenerateCssFiles

line 552

            **result.AppendFormat("<link rel=\"stylesheet\" type=\"{0}\" href=\"{1}\" />",**
                MimeTypes.TextCss, route);

should be:

            **result.AppendFormat("<link rel=\"stylesheet\" type=\"{0}\" href=\"{1}{2}\" />",**
            MimeTypes.TextCss, pathBase, route);
cheers
Mark

**Comment by exileDev** [comment]
Closed #7457
