### ISSUE TITLE
Shipping Rate Computation Method options can’t be updated.

### ISSUE THREAD

**Issue by uyanderya** [nopSolutions/nopCommerce#7459]
nopCommerce version: 4.80.0 (.NET 9.0.0)
Nop.Plugin.Shipping.FixedByWeightByTotal
Problem: Shipping Rate Computation Method options can’t be updated. Option line remains in edit mode after “update” confirmation.
---------------------------------------------------------
Conditions to reproduce the problem:
On Admin panel,
Selected language is Turkish (or any other than English),
In “Fixed Rate” Mode,
There is only one Shipping Rate Computation Method, containing multiple options.
--------------------------------------------------------
Steps to reproduce the problem:
Configure (the only provider)
Edit (change any of the rate values or not)
Update (click to confirm)

Note: This issue disappears, when English is the selected language.**
![ShippingRate1](https://github.com/user-attachments/assets/1339d88d-5cb3-4bf1-be37-ec977d5e315b)
![ShippingRate2](https://github.com/user-attachments/assets/fcdddb29-b53a-430d-b1c4-de93ba6ce298)
![ShippingRate3](https://github.com/user-attachments/assets/ba263d66-9f36-42cd-90af-4e65765839d7)

**Comment by exileDev** [comment]
Hi! Don't forget to set CLDR for the current culture in general settings. Works fine. Closed #7459
