### ISSUE TITLE
Language localizations strings on menu doesn't change on admin panel

### ISSUE THREAD

**Issue by rdcinformatics** [nopSolutions/nopCommerce#7463]
nopCommerce version:  4.80

Steps to reproduce the problem: 
Installed nopcommerce v.4.80 with mariadb database.  On backend the localizations strings on the menu doesn't change when we change the language. They changed only after restart application.

![image](https://github.com/user-attachments/assets/8986a261-eaa9-4875-a660-1d7404f25ffb)

**Comment by skoshelev** [comment]
Closed #7463
