### ISSUE TITLE
Allow to specify default values on the "Add product" page

### ISSUE THREAD

**Issue by dmburgess** [nopSolutions/nopCommerce#7475]
v4.8

- Default Products Template --  Basically giving you a method to configure the default shipping, tax rate, etc for new products, would be the same edit as a new product, but allows you to save all of your options, including inventory,shipping location etc.  

 A simple default options for new products template, that default template would be what is used when 
you add new products.

**Comment by AndreiMaz** [comment]
Thanks a lot for the suggestion. But this feature is quite specific. And after some consideration we've decided not to implement this functionality out of the box and leave it for customization
