### ISSUE TITLE
Streamline Product Edits

### ISSUE THREAD

**Issue by dmburgess** [nopSolutions/nopCommerce#7476]
nopCommerce version:  4.8

-- editing products .. The line, where states, preview, save, save continue etc. that line should be at the top, all of the time, so when you are scrolling in the details, you can just go up and hit save, yes I do know you have the little thing to go back to the top, but its just another click, vs keeping that header up there.   

Another thought as well, would be to allow you to save (maybe in a default template) what options you want where, order.   So that the most commonly used items are at the top.

**Comment by AndreiMaz** [comment]
Thanks a lot for the suggestion. But this feature is quite specific. And after some consideration we've decided not to implement this functionality out of the box and leave it for customization
