### ISSUE TITLE
Address record itself should have a field/checkbox "Is Residential Address?"

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#748]
Store owner ships to both. How can he expect to know whether customer is home or commercial address? Address record itself should have a field/checkbox "Is Residential Address?" Used by FedEx shipping rate computation method 

Source: http://www.nopcommerce.com/boards/t/12222/20-shipping-only-one-choice-in-select-shipping-method.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
