### ISSUE TITLE
Move away from KendoUI grid

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#75]
Anyway it's not included in the latest versions of KendoUI (open-source edition). It becomes outdated

Main suggestion: https://datatables.net/ and https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html

Also see https://material-ui.com/ and https://devexpress.github.io/devextreme-reactive/react/grid/

Suggestion 3 https://github.com/tonytomov/jqGrid and http://www.trirand.com/blog/

Suggestion 4:  http://ui-grid.info/

see http://www.nopcommerce.com/boards/t/29633/using-kendo-ui-legal.aspx and  http://www.nopcommerce.com/boards/t/29633/using-kendo-ui-legal.aspx?p=7#148339 

Once moved we can start using font-awesome icons to edit/delete buttons (maybe)

**Comment by f1ana** [comment]
Performance on ui-grid appears to be poor with semi-large datasets.

**Comment by keremdemirer** [comment]
[D3](https://github.com/d3/d3) is interesting. 
https://d3js.org/
http://bl.ocks.org/ahmohamed/4c4980f31abdef64e7e2

**Comment by ronenelahav** [comment]
if help needed in  https://datatables.net/
I would love to help integrate it into nop.

**Comment by tigran-avdalyan** [comment]
https://datatables.net/ and 
https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html
+1

**Comment by AndreiMaz** [comment]
once implemented see https://github.com/nopSolutions/nopCommerce/issues/2621

**Comment by emumanu** [comment]
If we're moving away from Kendo UI I think [openui5](https://openui5.hana.ondemand.com), the opensource UI javascript library from SAP, offers great controls, and some very powerful ones like the Grid Table, Tree Table, planning calendar, multi input.... and also provides layout support, data binding, etc

**Comment by Durkee** [comment]
I recommend to standardize on:
1. https://material-ui.com/
2. https://devexpress.github.io/devextreme-reactive/react/grid/

**Comment by abilican** [comment]
[SlickGrid ](https://github.com/mleibman/SlickGrid) is awesome but not updated for a long time

**Comment by nguyenhthai** [comment]
Will the new Datatable library support inline editing like before? I have checked out the library itself and seems like the feature is only available through paid version of the editor or build your own by using other libraries.

**Comment by AndreiMaz** [comment]
@nguyenhthai that's right. we'll replace inline editing

**Comment by tigran-avdalyan** [comment]
@DmitriyKulagin in issue #2621 we can use mark.js

**Comment by wize1** [comment]
i guess its too late now... 

but I think DevExtreme's grid would of been a lot better choice then DataTables... DevExpress as far as datagrid controls have been on top for ages now.

You don't get features like they have on any other libraries i have tested. Plus better support. Plus you get whole bunch of other nice controls. Been using they aspx control and wincontrols and devextreme for while now. I think they just best at this moment.

**Comment by tigran-avdalyan** [comment]
![Capture2](https://user-images.githubusercontent.com/17789934/56602502-77ccb800-65b2-11e9-8c58-7c65d3aa07cc.PNG)

**Comment by tigran-avdalyan** [comment]
![Capture3](https://user-images.githubusercontent.com/17789934/56602665-dabe4f00-65b2-11e9-8dbd-1ce5e8ff98fd.PNG)

**Comment by tigran-avdalyan** [comment]
![Capture4](https://user-images.githubusercontent.com/17789934/56602798-207b1780-65b3-11e9-85bc-fd8ac3bae086.PNG)

**Comment by tigran-avdalyan** [comment]
@AndreiMaz please check Country List (http://localhost:15536/Admin/Country/List) page in Mobile Device.
i think css issue.

**Comment by AndreiMaz** [comment]
@tigran-avdalyan do you mean that the country grid is not scrollable (not all columns are visible)? Or something else?

**Comment by tigran-avdalyan** [comment]
@AndreiMaz yes grid is not scrollable, thank you .

**Comment by nguyenhthai** [comment]
Is is possible to pass on JavaScript variable to the RouteValueDictionary when building the DataTable configuration? Previously with KendoUI, since it is client side rendering, you can use JavaScript to modify the configuration. I looked up some example, but could not find one that suggest the way to do it.

Also, will the reload feature be available in the new DataTable like previously in the Kendo grid? It is quite useful feature for some people that do not like to reload the entire page, just the grid to get the updated data.

**Comment by tigran-avdalyan** [comment]
![Capture5](https://user-images.githubusercontent.com/17789934/56800175-467d0380-67cf-11e9-8971-0c41bf5177e2.PNG)
