### ISSUE TITLE
Product - Closeout Item

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#759]
Provide the ability to mark a product as a Closeout Item with a percentage off the price on the product page. 

The customer will see the original price, the discount percentage, and discounted price. 

Source: http://www.nopcommerce.com/boards/t/39412/feature-request-product-closeout-item.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
