### ISSUE TITLE
Use async controller when requesting third-party services

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#76]
1. For example, use it when placing an order (invocation of third-party payment gateways)
2. Or requesting shipping options during checkout (and estimate shipping)
3. etc

also see http://www.nopcommerce.com/boards/t/31878/nopcommerce-with-vnext-.aspx

see comment by Maxim below (Russian - for internal usage)

**Comment by RomanovM** [comment]
Как я понял, основная задача - разгрузить сервер, чтобы при запросе сторонних сервисов (платежки, доставка и прочее) thread сразу возвращался обратно в thread pool, не дожидаясь окончания выполнения запроса к API, так как размер thread pool ограничен, и при большой загруженности и долгих ответах от сторонних сервисов сервер перестанет справляться.

При изучении этой темы я наткнулся на следующие моменты - для того, чтобы сделать действительно асинхронное выполнение действий внутри запроса, при которых thread не будет занят и будет сразу возвращаться (чего мы и хотим) сделать асинхронными только контроллеры, как предлагается в исходной задаче будет недостаточным. Нам нужно будет проваливаться с написанием асинхронного кода глубже и глубже вплоть до кода плагинов, и уже там требовать асинхронных вызовов API, то есть сторонние библиотеки должны предлагать такие методы, либо разработчики плагинов сами должны писать асинхронную обработку запросов к API сервисов. Только в таком случае выполнение кода будет действительно асинхронным.

Другой подход заключается в том, чтобы использовать асинхронные обертки над синхронными методами, тогда будет достаточно обернуть вызовы сторонних сервисов внутри контроллеров. Но такой подход не даст требуемого результата - исходный thread запроса будет возвращаться, но при этом, для обрабоки действий внутри обертки, будет взят другой из thread pool. Единственное, что конечный пользователь сможет совершать другие действия в то время, пока дожидается ответа от сервисов, но выигрыша по количеству свободных thread это не даст.

таким образом, можно:
1. переписать большинство методов с учетом поддержки асинхронного кода и заставить всех разработчиков плагинов также поддерживать асинхронный код (действительно с применением асинхронных методов обработки вызовов API, либо писать обертки поверх обычного кода)
2. сделать в контроллерах асинхронные обертки поверх существующего кода в тех местах, где вызываются сервисы.
3. оставить, как есть, без поддержки асинхронности
4. назначить задачу на кого-то еще и дать поразбираться, не уверен, что я все понял правильно

ссылки:
http://blogs.msdn.com/b/pfxteam/archive/2012/03/24/10287244.aspx
http://stackoverflow.com/questions/21406973/wrapping-synchronous-code-into-asynchronous-call

**Comment by AndreiMaz** [comment]
moved https://github.com/nopSolutions/nopCommerce/issues/2287
