### ISSUE TITLE
Ability to Upload PO as Attachment

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#764]
In one of our stores we allow the ability for customers to select PO as a payment type. Currently they can only input the PO number during checkout. It would be nice if they could also attach the actual PO as an attachment to the order. This would speed up processing as we usually wait to receive the actual PO from the company before processing the order. 

Source: http://www.nopcommerce.com/boards/t/38311/feature-request-ability-to-upload-po-as-attachment.aspx

**Comment by AndreiMaz** [comment]
this plugin is not part of the solution anymore (out of the box)
