### ISSUE TITLE
Allow admins to change username but prevent customer from doing it

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#765]
We should allow administrators to change customer usernames but prevent a customer from doing it

Of course, we should do it only when appropriate setting ("usernames" AND "allow customers to change username") is enabled

Source: http://www.nopcommerce.com/boards/t/38265/suggestion-allow-admins-to-change-username-but-prevent-customer-from-doing-it.aspx

**Comment by skoshelev** [comment]
Closed #765
