### ISSUE TITLE
When "Multiple warehouse" (advanced inventory) is used we should calculate shipping options from distinct warehouses

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#77]
Currently we do it only when distinct products are from distinct warehouses (e.g. product1 from warehouse1 and product2 from warehouse2). 

But we should do the same when a product is in multiple warehouses and a customer orders this product. For example, we have qty 2 in warehosue1 and we have qty 4 in warehouse2, but customer orders qty 5. 

Some notes for developer:
1. It should be implemented in the "CreateShippingOptionRequests" method of "ShippingService".
2. Ensure it works fine when qty in warehouse is 0 (multiple warehouses enabled)
3. Ensure it works for products without warehouses configured (but multiple warehouses enabled)
4. Sort warehouses by location
5. Allow a store owner to use current way (when all qty is shipped from one nearest warehouse)

See attached file. It's for one of the previous versions but it demonstrates how it should be implemented

---

There is one more feature request I wanted to mention. This is about inventory tracking with multiple warehouses. You can setup multiple warehouses and assign available quantities to each one of them for a given product, but there is no way to specify which warehouse the product is going to be shipped from and therefore the quantity needs to be deducted from. It would be nice to be able to programmatically specify it (based on the location perhaps or some other criteria) which warehouse is going to fulfill the order.

[CreateShippingOptionRequests.txt](https://github.com/nopSolutions/nopCommerce/files/566139/CreateShippingOptionRequests.txt)

**Comment by AndreiMaz** [comment]
[CreateShippingOptionRequests.txt](https://github.com/nopSolutions/nopCommerce/files/566138/CreateShippingOptionRequests.txt)

**Comment by nerto09** [comment]
seria importante encontrar una solución a este asunto
