### ISSUE TITLE
Override "Anonymous checkout allowed" per product

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#777]
we want only to make that for our 4 products - sign up fees. We need guests to be able to purchse products cause u know ppl do not like to buy something if they need to register first. We need this only for sign up 4 fee products. We have back office and if they purchase fee products as guest then that will make mess in bakc office and then we have to manual register that customer. Thats why we need to have "must register to purchase this product" for single product not for all. 

Source: http://www.nopcommerce.com/boards/t/37352/i-wish-nop-had-a-setting-to-say-you-must-register-to-purchase-that-product.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
