### ISSUE TITLE
Allow store owners to upload plugins instead of putting them manually into "\Plugins" directory using FTP

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#78]
Allow users to upload new plugins and have the list of plugins updated automatically. In this scenario adding plugins is faster. Please note that in this case all plugins should be in some certain format (e.g. a plugin directory zipped).

If you want to make it really nice...integrate plugin of nop commerce site and have users select them like with web platform installer.

See related work item #55

We shold support many ways to upload plugins (auto download, upload via admin, upload via FTP). Example, - http://www.wpbeginner.com/beginners-guide/step-by-step-guide-to-install-a-wordpress-plugin-for-beginners/

**Comment by suddenelfilio** [comment]
build a nuget based marketplace where nop can download the package using nuget and install the plugin that way. Also provides upgrade support out the box.
