### ISSUE TITLE
Change fields to protected instead of private (services, controllers)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#782]
We have a suggestion. In controllers, make the fields protected instead of private. 

Example from CheckoutController.cs 

private readonly IWorkContext _workContext; 

change to: 

protected readonly IWorkContext _workContext; 

This allows us to inherit CheckoutController with base contructor and use all the fields in the inherited class 

Example: 

CustomCheckoutController : CheckoutController 

public CustomCheckoutController() : base (IWorkContext workContext) 
{ 
//do nothing here. Since I can access the _workContext from base now :) 
} 

P.S. In this case we'll have to remove underscore (_) for all variables

Also see 
https://softwareengineering.stackexchange.com/questions/162643/why-is-clean-code-suggesting-avoiding-protected-variables/162657#162657

**Comment by AndreiMaz** [comment]
Decided not to implement
