### ISSUE TITLE
Allow a store owner (developer) to specify display order of widgets (if multiple widgets used)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#783]
I searched but I couldn't find any information about sorting multiple widgets in same zone. 

For example i have 3 different widgets in home_page_top zone.. How can I set the display order of the widgets or sort them?.. How they are selected and shown in the page currently also? 

Source: http://www.nopcommerce.com/boards/t/37000/how-to-set-display-order-in-same-widget-zone.aspx

**Comment by AndreiMaz** [comment]
Can we use DisplayOrder? Let's check.
