### ISSUE TITLE
Add to Wishlist button for products already added

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#785]
The star on the home page and Add to Wishlist should remember and display a highlighted/selected style for the add to wishlist buttons if the customer already added it to the wish list. 

Source: http://www.nopcommerce.com/boards/t/36799/feature-request-highlight-add-to-wishlist-button-for-products-already-added.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
