### ISSUE TITLE
Password attempt failure Lock-out set to 30 minutes (compliance with PCI DSS 3.2 requirements)

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#786]
Requirement 8.1.7: Password attempt failure Lock-out set to 30 minutes minimum. (may be an admin configured setting). User accounts be locked out after not more than six invalid logon attempts. Without account-lockout mechanisms in place, an attacker can continually attempt to guess a password through manual or automated tools (for example, password cracking), until they achieve success and gain access to a user’s account.

But we already have CAPTCHA. Why should we do it?
setting: Maximum login failures to lockout account. Set 0 to disable this feature. default: 6
setting: Lockout time (minutes). default: 30

Source: http://www.nopcommerce.com/boards/t/38848/nopcommerce-380-roadmap-and-estimated-release-date-lets-discuss.aspx?p=5#159909

[PCI_DSS_v3-2.pdf](https://github.com/nopSolutions/nopCommerce/files/351713/PCI_DSS_v3-2.pdf)

Also see related items - https://github.com/nopSolutions/nopCommerce/issues/2009 and https://github.com/nopSolutions/nopCommerce/issues/2010

**Comment by michalkovy** [comment]
Note that PCI DSS 3.2 is already out and it is worth to get complaint against it.

**Comment by suddenelfilio** [comment]
Can you force or expect a customer to change its password every 90 days? Have not heard of many webshops that do this. Also One-time buyers stalking for password updates will kill any change of them buying again at your store.

**Comment by john-dent** [comment]
I agree with suddenelfilio about customers being frustrated about changing their password every 90 days, and the potential for driving business away....  However to force admins and vendors to change their passwords every 90 day (and inhibit the use of previously used passwords) would be a great addition.

Requirement 8.2 states 'non-consumer users and administrators' anyway.. 👍
