### ISSUE TITLE
"File Upload". When used as a product or checkout attribute (Possibility to limit the number of uploaded files to one only)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#795]
If a product or a checkout attribute is configured as an "Upload File Control" on the administration level. When a customer on the public store tries to upload a file as a checkout attribute before checking out the cart. It is not possible to limit the number of uploaded files to only one. 
Steps to reproduce: 

1- Add any item to cart 
2- Go to cart 
3- Click on "Add File" and select one file, wait till file is uploaded. 
4- Repeat step 3

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
