### ISSUE TITLE
Add "ShippingMethodId" to "ShippingOption"

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#796]
I have another small suggestion that could come in handy. 

Nop.Core.Domain.Shipping.ShippingOption 
Add the property 

public int? ShippingMethodId { get; set; } (or ShippingMethod object) 

This will come in handy in the shippingratecomputation method. You can now in your plugin (example) 
Nop.Plugin.Shipping.ByWeight.ByWeightShippingComputationMethod 

```
foreach (var shippingMethod in shippingMethods)
       {
.... 
shippingOption.Description = shippingMethod.GetLocalized(x => x.Description);
              shippingOption.Rate = rate.Value;
shippingOption.ShippingMethodId = shippingMethod.Id;
```

Now this is very handy if I want to do something special. For instance - one of my shippingmethods is only for pickup locations. So I could put an extensionmethod IsPickup and make it do some ajax stuff (or whatever). 

In any case - it's really usable to be able to know which shipping method a shipping-option is derived from. For instance, I am currently grouping by shippingmethods according to Business, Private etc.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
