### ISSUE TITLE
Allow Vendors to Have Affiliates

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#797]
We are currently working on a multi-vendor site and thinking of different marketing ideas that we can offer for our vendors. One idea that has come up is the ability to offer vendors to setup their own affiliates. In 3.60 the reporting abilities will be expanded and I believe these same types of reports could easily be altered for Vendor use. When logged in as a vendor, the vendor should be able to see affiliates that are signed up under them and should be able to see affiliate reports for only their affiliates so they can do payouts accordingly. 

I would also think that each vendor should have an option if they would like to support affiliates. If so, then on the vendors detail page there should be a link or something to sign up as an affiliate. 

Source: http://www.nopcommerce.com/boards/t/35831/feature-request-allow-vendors-to-have-affiliates.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
