### ISSUE TITLE
Bulk deletion of categories/manufacturers

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#799]
On the Manage Products page in nopCommerce 3.50 you can select a checkbox next to each product and then click a "Delete (Selected)" button to delete all currently selected products. It would be nice if this same functionality was extended to product categories. For one it would ease the process of deleting categories, but it would also maintain consistency in the product. 

Source: http://www.nopcommerce.com/boards/t/35728/enhancement-request-checkboxes-to-delete-categories.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
