### ISSUE TITLE
There are X users viewing this product (as a plugin)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#801]
I am looking at an extension/NOP Feature or Custom Development to implement on our store a pop up like you see when booking Hotels online. 

eg. 
There are currently x users viewing this product 
This product was purchases x times in last 24 hours 
There are currently x users viewing this category 

Has anyone seen this before in a NOP Shop, is it a feature of NOP, is there an Extension or if custom development where can I look?? 

Source: http://www.nopcommerce.com/boards/t/35645/there-are-x-users-viewing-this-product.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
