### ISSUE TITLE
Purchase Order (PDF)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#802]
When viewing an Order in nopCommerce 3.50 there is an "Invoice (PDF)" button in the top right corner to create an invoice. It would be great if there was also a "Purchase Order (PDF)" button. When clicked it could iterate through all manufacturers or vendors and create a PO for each one. 

I imagine a setting that would ask if the button should iterate through manufacturers, vendors, or include all in the same PO. I would also imagine a setting for what number the PO should start with, much like the setting for Order numbers. 

This would allow a store owner that orders product from drop ship companies to easily create a PO per manufacturer if needed rather than re-entering the order information into a billing software to do the same thing

Source: http://www.nopcommerce.com/boards/t/35648/feature-request-purchase-order-pdf.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
