### ISSUE TITLE
Add "Vendor list page enabled" setting

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#803]
e all vendors page (./vendor/all) doesn't work if in the Vendor Settings the "Number of Vendors to display" is set to 0. I believe that the all vendors page should still work even if that number is not set since its description says it only pertains to the Vendors navigation block. 

A new setting indicating whether the "all vendors" page is available could added. But it can be a bit confusing for store owners having "Number of vendors to display" > 0 (obviously it should be enabled in this case). If the existing setting ("Number of Vendors to display") is ignored, then all vendors will be visible to customers (some store owners may want to hide it) 

Source: http://www.nopcommerce.com/boards/t/35621/vendor-all-page-doesnt-work-if.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
