### ISSUE TITLE
Wishlist - Products that have the Buy Button disabled should hide the Add to cart check box

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#804]
Problem 
We have had customers try to purchase products that have their Buy buttons disabled by adding them to the wish list first then try to add it to the cart. The customers have contacted us saying that they can't add items to the cart. Later, we find out that they are trying to add an item to the cart from their wishlist that has the Buy button disabled (typically a discontinued item). 

Proposed Solution 
Do not allow the customer to check an item in the wish list that has its Buy button disabled and display a message underneath the item that "This product can not be purchased at this time. See related products for suggestions." 

Source: http://www.nopcommerce.com/boards/t/35539/enhancement-wishlist-products-that-have-the-buy-button-disabled-should-hide-the-add-to-cart-check-box.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
