### ISSUE TITLE
Maximum discount on category

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#807]
It would be great to apply a maximum quantity discounted by category, rather than by product. For example, if you have a category called '$10 t-shirts', and would like to create a discount rule to give one free shirt from that category, you can't do that. If you apply the discount to the category, the user can get one of each item in the category free. Likewise, if you create a discount that applies to a random set of products not in a category (Assign to Products), you can't limit that either. Would love to see maximum discount per category, or by product set. 

Source: http://www.nopcommerce.com/boards/t/35237/feature-request-maximum-discount-on-category.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
