### ISSUE TITLE
Payments by installments

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#814]
Add support for payments by installments and multiple payments. 

Take into account the following: 
1) It might be a minimum purchased amount to accept this payment method 
2) There should be a formula to calculate the installments. Example Pn=T/n \* Kn where Pn is the monthly amount to pay when the Total (T) will be payed in n installments; and Pn is a factor to reflect the financial cost for thelaying payment in those n installments. 
3) It is very common that the factor Kn will vary from bank (issuer bank of the card) to bank; so it might have to be enhaced to Knb and the customer must select the bank. 

In this case we should add a new entity - "Invoice" (not the same as "Order"). like in magento 

also see http://www.nopcommerce.com/boards/t/34207/suggestion-expand-the-paymentstatus-enum.aspx

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/5
