### ISSUE TITLE
Option to ignore reward points for some products

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#815]
I am keen for an option of some products not being able to earn reward points...so a checkbox when adding a product for doesn't earn reward points. 

Would this be able to be added? 

Source: http://www.nopcommerce.com/boards/t/34114/reward-points.aspx

**Comment by infinito62** [comment]
I agree. For instance, gift card should not allow reward points benefit, as points wii be earned when the card is used. For absurd, if you buy a gift card and with it buy another and so on for tens times, you can earn tons of reward points and shop for free.

**Comment by eadameg** [comment]
I think this could be more flexible to have some high margin products pay more points and low margin less points. You can specify a multiple of reward points for each product. Examples: 2= double, 0.5= half and 0=none
Furthermore, this could be handled in the Promotions sections, similar to discount rules.

**Comment by RomanovM** [comment]
duplicate of https://github.com/nopSolutions/nopCommerce/issues/2048
