### ISSUE TITLE
Add a setting indicating whether "default" items should be displayed in the top menu

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#817]
Source: http://www.nopcommerce.com/boards/t/33461/version-350-adding-a-new-category-overrides-the-menu-bar.aspx and http://www.nopcommerce.com/boards/t/44131/show-both-categories-and-topics-on-top-menu.aspx

By "default" item I mean menu items displayed in case when "no sample" data is installed (no categories). Maybe we should move each of this page to setting?

**Comment by skoshelev** [comment]
Closed #817
