### ISSUE TITLE
Multiple Sitemap XMLs

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#823]
Hello, 

I would like to see multiple dynamic sitemap.xml files being generated. Currently all products, categories, topics etc are put into the one yourstore.com/sitemap.xml location. Although sitemap files can contain up to 50,000 urls, some people have more than 50,000 urls, but in most cases it better to provide more granularity. By creating multiple sitemaps, google webmaster will provide a better breakdown of sitemaps submitted and you can analyse any poor performing urls (duplicate content etc). Also it's much less load on the server to output smaller files. 

Example, split products into separate dynamic files with a limit to the number of urls in the file 
yourstore.com/sitemap-products1.xml (products 0-1000) 
yourstore.com/sitemap-products2.xml (products 1001-2000) 
. 
.. 
... 
yourstore.com/sitemap-category1.xml (categories 1001-2000) 

Source: http://www.nopcommerce.com/boards/t/33113/multiple-sitemap-xmls.aspx

**Comment by AndreiMaz** [comment]
duplicate https://github.com/nopSolutions/nopCommerce/issues/1713
