### ISSUE TITLE
Update "UpdatedOnUtc" product property in "AdjustInventory" method

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#825]
Should we do here? Or should we do it only when editing in admin area? 

Source: http://www.nopcommerce.com/boards/t/33069/stock-qty-change-in-webshop-does-not-adjust-last-updated-date.aspx 

[AM] If we're going to use for work item #12560, then it's better to set only "LastQtyChangeDate" property

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
