### ISSUE TITLE
Permit add to basket for disabled products when impersonating

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#826]
Sometimes, products have the buy button disabled because trading conditions mean that the retailer is prevented from selling an item online. However, they can sell the item if the customer phones in. 

In order to accommodate this, the logic for displaying buy button and handling warnings needs to be changes so that the buy button is shown and add to cart permitted when a customer is impersonated. 

It's a relatively simple change requiring changes to Nop.Web\Views\Product_AddToCart.cshtml and Nop.Services\Orders\ShoppingCartService.cs

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
