### ISSUE TITLE
Add Javascript Events in the Payment flow

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#83]
The problem: 

When developing a payment plugin, you have to keep in mind PCI Compliance requirements. 

Rule #1 is: You don't send Credit Card data to the server. 
Rule #2 is: Read rule #1 ! 

To achieve this we currently have to use jquery hooks on some buttons from the PaymentInfo wizzard. 
For example: 

$(".payment-info-next-step-button").click(function(){ ... }); 

and 

$('.submit-button').click... 

These are important because we need to know when the user has clicked "Submit", after entering his CC data, in order to intercept the request, then send the data to the payment gateway, receive a token, then resume and send the token to the shop's server. 

This works most of the time, except if the shop uses a custom theme or plugin that changes these CSS classes or the payment flow all-together. 

The proposed solution: 

It would be nice if the PaymentInfo object would have some delegate properties, which a third party developer could implement. 

Such as OnPaymentInfoSumbitted() and OnWizzardStepChanged(stepNo). And these delegates should be called internally, then resume the normal flow, just like before. 

The matter can be detailed if you agree it's worth looking into. 

Source: http://www.nopcommerce.com/boards/t/39325/add-javascript-events-in-the-payment-flow.aspx

**Comment by andronachev** [comment]
@AndreiMaz will this not be included in 3.80 ? I see that you removed it. Thanks

**Comment by AndreiMaz** [comment]
@andronachev No. it's postponed

**Comment by AndreiMaz** [comment]
moved to #154
