### ISSUE TITLE
Update .NET framework to 4.5.2 or 4.6

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#834]
Currently we're using 4.5.1. Do it only when this framework is distributed with VS 2013 out of the box. Otherwise, a lot of user won't be able to use nopCommerce without this additional step

also see http://www.gfi.com/blog/hold-off-on-upgrading-to-net-framework-4-6-1/

UPDATE: Decided to postpone it until version 4.00 (asp.net core)?

**Comment by schulz3000** [comment]
4.5.1 is out of support (https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) so I think upgrade to 4.5.2 is a must.

If you want to compile with target 4.5.2 in VS2013 you need to install the 4.5.2 DevPack https://www.microsoft.com/en-US/download/details.aspx?id=42637

**Comment by suddenelfilio** [comment]
do you believe this necessary if you plan to migrate to .net core? I know core can also target 4.6.x, but then it still is stuck on Windows platforms whereas core 1.x could bring nopcommerce multi platform...

**Comment by ginuxone** [comment]
I'm having troubles compiling this on vs2017 with 4.5.1, at this poing i think it's necessary to update the framework

**Comment by techno2mahi** [comment]
Currently, we don't have time and bandwidth to migrate all the functionalities to migrate to .net core. Is there any plan for this v3.0 to be upgraded to the higher supported version. Any pointer would really mean a lot.

**Comment by techno2mahi** [comment]
I have now created a [fork ](https://github.com/techno2mahi/nopCommerce/tree/develop-3.90-framework-v4.5.2)from v3.90 and upgraded it from .NET Framework 4.5.1 to .NET Framework 4.5.2

**Comment by techno2mahi** [comment]
hurrah  its upgraded to .NET Framework v 4.6.2 https://github.com/techno2mahi/nopCommerce/tree/develop-3.90-framework-v4.6.2
