### ISSUE TITLE
Custom customer attributes not exported to Excel or XML

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#835]
Custom customer attributes does not seem to be exported to Excel or XML when choosing to export a customers information. 

Especially custom customer information can be value when finding out more about your customers - like how they found you on the net in the first place. 

Bug was found in v.3.30. 

How to replicate: 

1) Create a custom customer attribute, like a tekstbox 
2) Enter the information in your account 
3) Export your customer to excel 
4) Notice that your custom field information is not exported.

![example](https://cloud.githubusercontent.com/assets/16681184/12414984/25d88a22-beaa-11e5-8ada-bb57ceac1666.png)

**Comment by skoshelev** [comment]
Closed #835
