### ISSUE TITLE
Allow storeowner to set display order of system customer input fields

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#837]
new in 3.30 - we can add/edit customer new input fields but ...
- we should have the ability to set the display order on the hard coded ones.

Different countries have different address formats - eg, it's not normal in uk to have the current default format : 

postcode, 
city, 
country, 
province 

rather, it is 

city, 
province 
postcode, 
country 

forum source: http://www.nopcommerce.com/boards/t/30656/allow-storeowner-to-set-display-order-of-system-customer-input-fields.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
