### ISSUE TITLE
Enhance subtotal discount to exclude products in a certain category

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#840]
Subtotal discount is very powerful: as a simple way of setting a general discount, or in sales seasons or to apply a second discount to purchased products, etc. Sometimes you want to exclude certain products (which are in a certain category) in the calculation of the subtotal to which the % discount is applied. Examples:
- Gift cards as in here (http://nopcommerce.codeplex.com/workitem/11618)
- Products which have high discounts
- Products with low margins which are not apt for any discount
- etc.

The category could be one like "Discounts" or an invisible category (not published) used just for mapping (kind of a hack ;-)) all products excluded from subtotal discount calculation 

Forum source: http://www.nopcommerce.com/boards/t/30322/suggestion-enhance-subtotal-discount-to-exclude-products-in-a-certain-category.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
