### ISSUE TITLE
Use Start Date on Blog pages instead Creation Date.

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#841]
If a blog entry has a start date set in the future the blog entry on the blog site Shows the creation date of the entry instead of the start date. 

So if no start date is set the creation date should be used and if a start date has set the start date should be used instead of the creation date

**Comment by MrChoco88** [comment]
This seems like it should be a given with any blog and it's crazy that it has not been fixed.

**Comment by DJBalogh** [comment]
I agree. This way when a start date is used the blog is placed chronologically based on that date instead of the creation date. Where as now the blog will post but it may still be way down the page or even on page two of the blog.

**Comment by AndreiMaz** [comment]
fixed in 3,80
