### ISSUE TITLE
Issue with PDF invoice table alignment

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#842]
If you view a PDF invoice you'll notice the product name is not in line with the sku, price, quantity, total. 

This is because the text in the name cell is inserted differently (cell created then paragraph added, as opposed to cell being constructed using a phrase) 

To have the name line up correctly with the other fields simply add the two lines below (PaddingTop and UseAscender )

```
string name = p.GetLocalized(x => x.Name, lang.Id);
cell = new PdfPCell();
cell.PaddingTop = 4.5f; //magic value to make alignment work
cell.UseAscender = true; //magic value to make alignment work
cell.AddElement(new Paragraph(name, font));
cell.HorizontalAlignment = Element.ALIGN_LEFT;
var attributesParagraph = new Paragraph(HtmlHelper.ConvertHtmlToPlainText(orderItem.AttributeDescription, true, true), attributesFont);
cell.AddElement(attributesParagraph);
productsTable.AddCell(cell);
```

I'm using this in production

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/nopCommerce/commit/91573988ccc719ab7c39cad10cf053a9c6ab55a7
