### ISSUE TITLE
Template Logic to reduce gaps

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#853]
In the templates that contain the order information, I have as follows: 

%Order.ShippingFirstName% %Order.ShippingLastName% 
%Order.ShippingCompany% 
%Order.ShippingAddress1% 
%Order.ShippingAddress2% 
%Order.ShippingCity%, %Order.ShippingStateProvince% %Order.ShippingZipPostalCode% 
%Order.ShippingCountry% 
%Order.ShippingPhoneNumber% 
%Order.ShippingEmail% 

However, if some of the fields are empty, it creates gaps, looking a bit unprofessional.

I moved from XCart which was SMARTY template based, so I could easily add logic to test if a field had a length>0 and if so, print the field. 

Example: 

John Doe 

My Address1 

Seattle, WA 98116 

me@my.com Customer didn't have a company, address 2 or phone number.

**Comment by AndreiMaz** [comment]
duplicated
