### ISSUE TITLE
Periodically not found bundle errors (e.g. - '/bundles/scripts/3captt5sa5pajvuge4nkgxzedwug-m-8ixoq-ma6vwm1.js)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#854]
Forum source 1: http://www.nopcommerce.com/boards/t/25232/nopcommerce-310-issues-with-shopping-cart-in-ie-and-firefox.aspx 

Forum source 2: http://www.nopcommerce.com/boards/t/25232/nopcommerce-310-issues-with-shopping-cart-in-ie-and-firefox.aspx 

Some investigation required:
1. It could be caused by running in a web farm (not supported for bundles)
2. First HTTP request to a page is made for a page. A bundle is generated and available. Then some new HTTP request to a page is made, then application is restarted (for some reasons), a bunld is not available anymore.

In all toher cases it should work

**Comment by AndreiMaz** [comment]
fixed in 4.00 (saved sa files)
