### ISSUE TITLE
Allow plugins to handle "unknown" URL before nop throws 404

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#857]
Pull request: https://nopcommerce.codeplex.com/SourceControl/network/forks/sproaty/handleUnknownSEORoutes/contribution/5813 

In GenericPathRoute we capture the page name and look up a UrlRecord entity by that page name. If nothing is found, then nop will show a 404 page. There is no extension/hook point here for plugins to run custom code. So, if a plugin wishes to catch an unknown URL then it basically can't. 

This changes it so that when no UrlRecord is found, plugins have a chance to 

I was going to do this using events, however events don't return anything to the publisher, and we need to know if the unknown URL was handled or not, so that nopCommerce can show the 404 page if not. 

An example "unknown seo record route provider" is below:

```
using System.Web.Routing;
using Nop.Core.Infrastructure;
using Nop.Web.Framework.Seo;

namespace Nop.Plugin.Test
{
    public class TestUnknownSeoRecordRouteProvider : IUnknownSEORecordRouteProvider
    {
        public bool HandleSEO404(string slug, RouteData routeData)
        {
            // look up based on media code
            var service = EngineContext.Current.Resolve<ISchemeService>();            
            var scheme = service.getByMediaCode(slug);

            if (scheme == null)
            {
                return false;
            }

            routeData.Values["controller"] = "Scheme";
            routeData.Values["action"] = "LandingPage";
            routeData.Values["mediaCode"] = slug;

            return true;
        }

        public int Priority { get { return 100; } }
    }
}
```

**Comment by DarthSonic** [comment]
Our approach is to have a plugin with it's own custom routes config. The routes are maintained by database over nop Admin. So if there is a 404 request we can add a regex or wildcard over nop Admin to database and the route is dynamically added on next application restart. Unfortunatly the restart is required to register new route but you do not need to change any code to add a new route.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
