### ISSUE TITLE
product filtration & auto populated attributes by customer preferences

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#858]
If a customer knows they like (for example) a couple T-shirt designs or styles of clothing and they have $X.xx amount spending limit, it would be nice to let them enter their sizes, preferred colors and max budget to give them only product results with those attributes. 

Optionally & possibly 2nd phase, resulting images & preferred sizes will be pre-populated to match the customer's needs. Store owners should also be able to create a flexible discount that can bring an item closer to their budget if criteria are met, without going past a certain percentage or dollar amount threshold. 

The result would be almost a concierge shopping experience that helps customers get the most for their budget, while making sure they finish checkout because any flex discount would be time sensitive.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
