### ISSUE TITLE
Record Refunds history

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#860]
Rather than storing a 'refund amount' on the order, it would be good if there were an additional table for all the refunds that have been made, including:
 * Person Who Made the Refund
 * Refund Method
 * Refund Amount
 * Refund Date
 * Refund Reason

For bonus points, it would be good to store the tax on the refund, i.e., select the products being refunded, and if they are tax exempt, determine the refund accordingly. Very similar to how the return product selection works. 

We have a terrible time tracking and reconciling our refunds to orders. It's OK if you have three or four a month, but if you have hundreds, it becomes unmanageable.

**Comment by AndreiMaz** [comment]
Moved to https://github.com/nopSolutions/nopCommerce/issues/5
