### ISSUE TITLE
Enable automatic product picture addition upon upload in flexible and maintainable way (contribution)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#861]
https://nopcommerce.codeplex.com/SourceControl/network/forks/matthewnreid/nopcommerce320/changeset/c52f5a3e0dcf

also see http://www.nopcommerce.com/boards/t/19529/suggestion-simplify-product-picture-upload.aspx

but this way he won't be able to enter display order and other fields

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
