### ISSUE TITLE
Add LocalDb support. Drop SQL Compact?

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#862]
Should we support LocalDb? 
Should we drop SQL Compact support? 

Comparison table: http://blogs.msdn.com/b/jerrynixon/archive/2012/02/26/sql-express-v-localdb-v-sql-compact-edition.aspx

**Comment by dotnetdreamer** [comment]
We used this feature before to avoid shared hosting restrictions. As they limit the SQL server Db but not the harddrive storage.
