### ISSUE TITLE
Name/Email in HeaderLinks

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#877]
In HeaderLinks Name/Email format does not have the format choosen on admin area, but only shows email or username. 
It's very easy to correct it by replacing CustomerEmailUserName assignment in CommonController with CustomerEmailUsername = customer.IsRegistered() ? customer.FormatUserName() : "" 
This would provide more consistency.

Let's make it configurable

Source: http://www.nopcommerce.com/boards/t/10678/customer-name-when-logged-in-not-email.aspx

**Comment by AndreiMaz** [comment]
done
