### ISSUE TITLE
Print Invoice and Packing Slip - Admin's Working Language rather than customer's

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#878]
I noticed that when an Admin prints Invoice and Packing Slip that the Working Language passed in will be the Admin's rather than customer's. Is that by design? (It's the customer who will be getting these documents) 

\Presentation\Nop.Web\Administration\Controllers\OrderController.cs
```
    public ActionResult PdfInvoice(int orderId)
   ...
            _pdfService.PrintOrdersToPdf(stream, orders, _workContext.WorkingLanguage);


    public ActionResult PdfPackagingSlip(int shipmentId)
   ...
            _pdfService.PrintPackagingSlipsToPdf(stream, shipments, _workContext.WorkingLanguage); 
```

Forum source: http://www.nopcommerce.com/boards/t/22956/print-invoice-and-packing-slip-admins-working-language-rather-than-customers.aspx 

It can be fixed. But in this admins wont be able to print PDF in any other language. If you want to get it "fixed", then find all useds of "pdfService.PrintOrdersToPdf" and "pdfService.PrintPackagingSlipsToPdf" and remove the last parameter (language). In this case it'll be detected automatically

**Comment by AndreiMaz** [comment]
done
