### ISSUE TITLE
Extract File IO Functions

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#88]
It would be beneficial if we could extract the usage of System.IO.File related functions into a service layer wrapper. Doing so would give plugin developers the ability to write custom io providers separate from logic. 

PictureService is a prime example, write now you cannot separate where you want to store the files without writing a custom plugin that handles both the logic and the storage. creating a service wrapper would allow for two different plugins one for storage and one to handle the logic in processing pictures. 

Source: http://www.nopcommerce.com/boards/t/36411/extract-file-io-functions.aspx

I think first we should move to ASP.NET Core as seems that it's alrady supported theme (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers)

**Comment by suddenelfilio** [comment]
true I implemented a an AzurePictureService implementation of th IPictureService which stores the pictures in azure blob storage. Just having to implement the IO part would be so much easier instead of the entire interface as it is about 75%-85% copy-pasting the logic

**Comment by skoshelev** [comment]
Closed #88
