### ISSUE TITLE
Suggestion : Add a "request a product" tab at the top navigation bar

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#882]
Add a "request a product" tab at the top navigation bar. 

Would be great if you can have a "Request a Product" official nopcommerce plugin. Purpose of this plugin is to give the potential buyer the ability to submit a product request to the seller if the product is not listed on the sellers website. This will give the seller the opportunity to maximize sales by also selling items not currently listed on his site. This should be easy to do as you can use the current contact us form and modify it slightly. Will be great if it can be dynamic and you can make the changes direct from the admin panel. Will be great if you can enable and disable predefined fields direct from the admin panel. This can greatly increase your sales and give you good indication on what products your customers are looking for.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
