### ISSUE TITLE
Fractional Weights

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#886]
Currently, if you try to enter a weight that is less than 1 lb. (e.g. 0.5 lbs.), a validation error appears that states you must enter a valid number. This would actually be OK if an existing store can be switched from pounds to ounces as the primary weight measure without having to update every single product to correct the value. 

For most shippers, this is not a big deal. However, for USPS, it is, as it supports calculating rates for weights of 1 ounce and up.

**Comment by AndreiMaz** [comment]
After some consideration decided not to implement out of the box (leave for customization)
