### ISSUE TITLE
Add Login page validator

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#889]
Because validator for Login page does not exist, when you add incorrect email, you get not localizable jquery.validate message about it is wrong. For username and password you will not get any answer because jquery.validate does not have such validation answers. 
Fix attached. 

I'v updated fix (use second one) - now it is using UsernameEnabled flag (as should). 
I was forced to use "if" "else" instead of "When" "Unless" rules because FluentValidation "Unless" does not work.

[LoginValidator.zip](https://github.com/nopSolutions/nopCommerce/files/95761/LoginValidator.zip)

**Comment by AndreiMaz** [comment]
works fine
