### ISSUE TITLE
Allow a store owner to specify password rules

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#89]
Allow configuration for password rules: 

Length range 
Must include at least 1 number 
Must include at least 1 Capital letter 
Must include a least 1 lower case letter 
Must be alpha numeric, not allow symbols 
Must include special chars (specified) 

Must be reset after specified number of days 
Limit changes to specified number of time per time frame 
Cannot be same a last password used 
Lockout after specified number of failed log on attempts

**Comment by m1dst** [comment]
We should also log successful and failed login attempts as a ActivityLog as it will show the IP address.

**Comment by m1dst** [comment]
While I think of it, another thing I changed was NOT displaying the login failure reason to the user on the login screen.  If you feed an attacker with more information, they will use it.

**Comment by AndreiMaz** [comment]
duplicate
