### ISSUE TITLE
Allow a store owner to specify expenses per order

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#891]
The need to track expenses such as order Actual Cost and marking whether an order has been fully paid by the store owner is very important. The reason is sometimes distributors will double bill for an order by accident and it is tough to determine unless the order, bank account, and invoices are carefully scrutinized and reconciled. Additionally, distributors and manufacturers have also billed the wrong store owner for someone elses order, and it is very difficult to tell, especially when there is no history within nopCommerce to which order has already been paid for. 

It would be nice to have a fields "Actual Cost" and a button "Store Owner Paid" to denote the order has been paid by the Store Owner. This would also help tremendously with Financial Analysis and determining actual profit per order and per specific periods. 

Forum source: http://www.nopcommerce.com/boards/t/19227/feature-request-need-ability-to-track-expenses-per-order.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
