### ISSUE TITLE
Product level shipping configuration (new plugin - shipping rate computation method)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#9]
Most of my competitors offer FREE UPS Ground for select products and has put my store at a disadvantage. I am willing to pay for this feature, and I'm sure others are willing to contribute. However, I believe the nopCommerce core framework will need to be updated in order to implement this feature. What would be ideal is on the product page to have shipping prices for each option be set to either a fixed price (including FREE/Zero) or the option will work as normal (getting the rate from the shipping carrier's API). Right now, this is the #1 priority for my store and I have seen many others need this level of configuration for their stores. It would solve many requests in these forums such as "FREE Ground and $5 2nd Day Air for specific products" or "FREE Ground shipping for select products", "setting FREE Shipping on a product currently makes all options free", etc. Shipping Director is a third party plug-in and cannot do this, plus it is complicated to configure, or I would have purchased it. A simple solution would be to have a scrollable Product Shipping area on the Product Details or Variant Details screen. 

Forum source: http://www.nopcommerce.com/boards/t/16465/feature-request-product-level-shipping-configuration.aspx 

This work item can be implemented as a new plugin (shipping rate computation method). Hence it won't be available out of the box.

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
