### ISSUE TITLE
Store Referral URL for each customer

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#902]
Forum source: Provide Referral URLs within the Admin for Customers and Customer Orders. This will allow the store owner to get some information on how the customer found the store and where the customer came from to place orders. The Referral URL should be set and persisted once when the customer first accesses the store. 

Forum source: http://www.nopcommerce.com/boards/t/17206/feature-request-customer-and-orders-should-have-a-referral-url.aspx

**Comment by AndreiMaz** [comment]
duplicated
