### ISSUE TITLE
Admin area. Change customer when editing order details

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#904]
I had a customer that created an account and then for some reason when they came back to purchase their products they did not login. Is there a way to associate the order with the existing account?

Forum source: http://www.nopcommerce.com/boards/t/16948/way-to-link-order-with-customer-account.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
