### ISSUE TITLE
Products: Minimum Stock Qty, Add ReOrder Level

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#906]
Currently the product variant supports the minimum stock quantity - which sends an email and works fine. 
Is possible I would like to extend this functionality by adding an additional field called Re-Order Level. 

For example: 
I have product A with Min Stock Qty = 100. 
I set my re-order level to 10. 

When the re-order level hits 10 or below - the email will also contain the minimum stock quantity. 
The NOP Upgrade script could copy the MinStockQty to the ReOrderLevel to facilitate the upgrade process. 

I currently interface automatic PO generation in QuickBooks and this feature will allow me to automatically reorder the correct amount to top-up my stock before its depleted. 

Many thanks 
Piet

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
