### ISSUE TITLE
Sort Product Specification Attributes and Product Attributes by Category

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#907]
it would be nice to have the specification attributes and product attributes grouped by category ... 
it would make finding them easy if they are many, and would also make displaying them more organized ...

**Comment by levioza** [comment]
@mariannk This feature is what I wished to see implemented. I wanted to open a feature request. However, I found this issue.

@AndreiMaz Dp you provide this feature via customization or as a plugin or better if you plan to implement it... Thank you :)
