### ISSUE TITLE
Freight Collect Shipping Method

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#910]
Can a Shipping Method of Freight Collect be added where the customer selects a carrier and carrier delivery method from a drop-down box of admin controlled carriers. The customer then enters their account number for collect billing or third party billing. It would be even better if the shippers' APIs could be used to verify the account number, but that may be asking too much right now :)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
