### ISSUE TITLE
Localize hard-coded locales for relative dates

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#911]
\Presentation\Nop.Web.Framework\Extensions.cs file. RelativeFormat method. 

The issue that logic could be quite complex for languages other than English. For example, in English only "1" is "a minute. But in Russian both "1" and 21 are "a minute", but 2 and 22 are "minutes"

**Comment by RomanovM** [comment]
Look at https://github.com/Humanizr/Humanizer
