### ISSUE TITLE
The FreeShippingOverX should be available on each shipping method

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#912]
For example, I have in my store two shipping method, the fast and expensive one, and the slow and chipper one. 
When I offert shipping over 50€, it is only for the less expensive method. 
It could be a goog option to add FreeShippingOverX on each shipping method

**Comment by AndreiMaz** [comment]
Already possible with "... by order total plugin" which could (maybe) merge to the default "Shipping by weight" plugin
