### ISSUE TITLE
Multi-purpose (wildcat) for each of the most important tables

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#916]
It would be useful to add a couple of multi-purpose (wildcat) for each of the most important tables (example: Field1, Field2,...) , which could make life easier for most of the customisation (and later upgrading) work. Soemtimes for this purpose we have to use some unused field (such as the AdminComment). 

Here are to my knowledege the most important tables in which the multipurpose fields could be useful (with some examples of what we have been needing):
- Product (sometimes require mapping fields to load/update products which have their own Product-Id in ERP)
- Product Variant
- Category (sometimes require mapping fields to load/update from ERP)
- Manufacturer (sometimes require mapping fields to load/update from ERP)
- Customer (I have read in this forum several threads where additional fields are required)
- Address (sometimes require a tax/VAT code for each billing address)
- Order 

The Generic Attribute for Entities (http://nopcommerce.codeplex.com/workitem/10361) is an excelent and very elegant solution for most cases which would give Nop a great flexibility. Nevertheless I think that it will not be useful or performance efficient in some situations such as when a field is used for searches, filtering, mapping and other database operations. 
Therefore I still recommend to hardcode a couple of fields in tables, now just for:
- Product (sometimes require mapping fields to load/update products which have their own Product-Id in ERP)
- Product Variant (same as above)
- Category (sometimes require mapping fields to load/update from ERP)
- Manufacturer (sometimes require mapping fields to load/update from ERP)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
