### ISSUE TITLE
CustomerNavigationModel Missing Settings

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#924]
in Version 3.70 its looks to switch from using the myaccountnavigation view to the customernavigation view. 

In the CustomerController there is a actionresult called CustomerNavigation, this actionresult looks like it sets the CustomerNavigationModel property based on settings. It does not seem to set all the properties, the HideInfo, HideAddresses and HideOrders seem to not get set. 

```
public ActionResult CustomerNavigation(int selectedTabId = 0)
        {
            var model = new CustomerNavigationModel();
            model.HideAvatar = !_customerSettings.AllowCustomersToUploadAvatars;
            model.HideRewardPoints = !_rewardPointsSettings.Enabled;
            model.HideForumSubscriptions = !_forumSettings.ForumsEnabled || !_forumSettings.AllowCustomersToManageSubscriptions;
            model.HideReturnRequests = !_orderSettings.ReturnRequestsEnabled ||
                _returnRequestService.SearchReturnRequests(_storeContext.CurrentStore.Id, _workContext.CurrentCustomer.Id, 0, null, 0, 1).Count == 0;
            model.HideDownloadableProducts = _customerSettings.HideDownloadableProductsTab;
            model.HideBackInStockSubscriptions = _customerSettings.HideBackInStockSubscriptionsTab;

            model.SelectedTab = (CustomerNavigationEnum)selectedTabId;

            return PartialView(model);
        }
```

Looking at the customer settings tab in the admin area, there is the Hide Downloadable products and Hide Back in stock subscriptions, but I would expect to see like Hide Orders Tab etc. Is this located in a different section or done in a different location? 

Thanks for any help.

![customersettings](https://cloud.githubusercontent.com/assets/16681184/12416940/b18c7956-beb5-11e5-9506-24299cdfb2de.jpg)

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
