### ISSUE TITLE
Admin area list pages. Click entity name to view details (remove "Edit" button)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#927]
Provide a link from the customer's name and email on the Order List screen that will navigate to the associated Customer screen so an Admin can view other orders for that customer. 

Source: http://www.nopcommerce.com/boards/t/38600/feature-request-order-list-page-click-customer-name-to-view-customer.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box
