### ISSUE TITLE
Plugin razor intellisense support

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#931]
Find more info at http://alexwolfthoughts.com/fixing-broken-nopcommerce-razor-intellisense/

let's just investigate it first

**Comment by ludlamzgull** [comment]
Hi Andrei with the new framework .net core we wont need this fix i think?

**Comment by AndreiMaz** [comment]
@ludlamzgull It's quite complex to answer right now. please wait a couple of more months =)))
