### ISSUE TITLE
Storeclosed doesn't respect WWW prefix requirement

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#939]
To reproduce: 

1) Set WWW prefix requirement to pages should have WWW prefix 
2) Close the store 
3) Navigate to the store without the www 

The storeclosed page does not respect that setting. As a result, the sitemap links also do not include the www prefix. 

Source: http://www.nopcommerce.com/boards/t/38089/storeclosed-doesnt-respect-www-prefix-requirement.aspx

**Comment by AndreiMaz** [comment]
I cannot reproduce the issue. Works as expected
