### ISSUE TITLE
Performance. Add more SQL Server indexes

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#94]
SQL Profiler would be very helpful

First, let's prepare a list of such columns and tables.
Then, let's discuss which ones to use

**Comment by keremdemirer** [comment]
We are using Azure Sql Database and it provides [Index recommendations](https://azure.microsoft.com/en-us/documentation/articles/sql-database-index-advisor/).

The following ones are recommended to our nopcommerce database (v3.5).

**Index details**
**INDEX KEY COLUMNS (3)**
[Published]
[VisibleIndividually]
[Deleted]

**INCLUDED COLUMNS (2)**
[Id]
[LimitedToStores]

-----------

**Index details**
**INDEX KEY COLUMNS (1)**
[Deleted]

**INCLUDED COLUMNS (10)**
[BillingAddressId]
[CreatedOnUtc]
[Id]
[OrderShippingExclTax]
[OrderStatusId]
[OrderTax]
[OrderTotal]
[PaymentStatusId]
[ShippingStatusId]
[StoreId]

--------

**Index details
INDEX KEY COLUMNS (1)**
[CustomerRole_Id]

**INCLUDED COLUMNS (1)**
[Customer_Id]

----------

**Index details
INDEX KEY COLUMNS (1)**
[IsSystemAccount]

**INCLUDED COLUMNS (2)**
[CreatedOnUtc]
[Id]
