### ISSUE TITLE
Multiple accounts for same email

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#953]
CustomerRegistrationService allows to register users with the same emails, but different usernames. But inside it uses ChangePassword method, that gets the Customer by Email (not username). So if we register multiple users with the same emails and different usernames, password (during the registration process) changed only for the first customer (other have null for this field). So we can't change or set password for other users, except the first one.

![untitled](https://cloud.githubusercontent.com/assets/16681184/12417366/add783b6-beb8-11e5-9f1d-ec7363ab0308.png)

**Comment by AndreiMaz** [comment]
it works fine. cannot reproduce
