### ISSUE TITLE
Warehouses - Provide ability to attach files

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#954]
We need the ability to attach documents to specific warehouses such as order forms needed for order fulfillment. This would make warehouse files easier to locate. 

for example, we have a distributor that requires orders to be entered into their excel order form then sent as an attachment to them. Each time, we have to remember where we put the order form but if it was on the warehouse screen then it would be very easy to find. Most of the time we search old emails for it or remember which folder it is in. They reissue a new order form each year with new products so delete functionality is also important so old order forms can be removed and new ones added. 

Source: http://www.nopcommerce.com/boards/t/37026/feature-request-warehouses-provide-ability-to-attach-files.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
