### ISSUE TITLE
Forums. Close topics ("Mark As Answer" functionality)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#957]
give forum moderator ability to: 
close a TOPIC to further discussion ( but leave it still available to view ) 
close a FORUM to further discussion ( but leave it still available to view ) 
option to unpublish a forum (but keep all the data) so it can be made active at a later date 

include ACL so that certain forums can be accessed only by certian groups 
see also workitem: http://nopcommerce.codeplex.com/WorkItem/View.aspx?WorkItemId=7781

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
