### ISSUE TITLE
Bug: Confirmation mail shows empty shipping address

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#962]
Concerns version 3.6 

Test case 1): Put one product in the basket that has "shipping enabled" and one product that does not have "shipping enabled". Proceed to the checkout and select "Pick up at store" at the delivery page. Confirm the order.

Test case 2): Put one product in the basket that does not have "shipping enabled". Proceed to the checkout. The delivery page is automatically skipped (BTW: I see that as a problem and opened https://nopcommerce.codeplex.com/workitem/12756 for it). Confirm the order. 

Result: 
In both test cases, the confirmation e-mail is sent with an empty shipping address. 

Solution proposal: 
To fix the bug, in the specified cases, the shipping address should be completely left out of the confirmation e-mail rather than showing it empty.

**Comment by AndreiMaz** [comment]
duplicated (email conditions)
