### ISSUE TITLE
Invalid Attribute XML output ("Export orders to XML")

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#967]
The XML for the product attribute XML is not seen as valid XML, the content is encoded and appears as text within its parent attribute. Currently it is rendered in ExportManager.cs as follows:
```
xmlWriter.WriteElementString("AttributesXml", null, orderItem.AttributesXml);
```

By changing it to the following it is output as valid XML:
```
xmlWriter.WriteStartElement("AttributesXml");
xmlWriter.WriteRaw(orderItem.AttributesXml ?? string.Empty);
xmlWriter.WriteEndElement();
```

let's investigate it. let's use some XML validation tools - e.g. http://www.xmlvalidation.com/ and http://www.w3schools.com/xml/xml_validator.asp

**Comment by AndreiMaz** [comment]
works fine. no errors
