### ISSUE TITLE
Admin area. Move the menu to the left

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#97]
We have two way to go. Which one is better?
1. For example, product details page. We can move menu of this page (info, seo, categories, manufacturers, etc) to the left. Anyway usually a lot of empty space is left (wide)
2. Move the entire top menu (catalog, orders, configuration, etc) to the left
See related work item - https://nopcommerce.codeplex.com/workitem/12933

**Comment by AndreiMaz** [comment]
duplicate #34

**Comment by AndreiMaz** [comment]
duplicate #34
