### ISSUE TITLE
implement unit tests with Excel

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#979]
Source: http://www.nopcommerce.com/boards/t/33457/nopservicestestsexportmanagertestscan_export_orders_xlsx-failed-in-version-33.aspx

**Comment by skoshelev** [comment]
Closed #979 (https://github.com/nopSolutions/nopCommerce/commit/a2b45b7116da0ddd94da67d50aae64ca05d2d5c6)
