### ISSUE TITLE
Customer attributes. IsPreSelected bug (for existing customer)

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#980]
Please image the following scenario. You have some custom attributes configured. Some of these attributes have been used for a while and therefore there is existing data.
You add a new dropdown to the attributes with a list of values, one of which has IsPreSelected=true. When the form is rendered, the preselection doesn't work

Source: http://www.nopcommerce.com/boards/t/34474/attributes-ispreselected-bug.aspx 

Source code on the forums also won't work because it won't be possible to clear any selection (default value will be pre-set anyway)

**Comment by AndreiMaz** [comment]
It's by design. A customer already selected a preferred option
