### ISSUE TITLE
Avoid exception when entering more than 400 chars in Meta keywords, etc

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#99]
We can do one of the followings:
1. Remove this limitation in mapping classes
2. Duplicate this requirement in validation classes

Source: http://www.nopcommerce.com/boards/t/37331/limitation-for-seo-meta-keywords-.aspx

See work item #114 (preferred way to fix it)

Similar to #1172

**Comment by skoshelev** [comment]
Resolved [#21da3e1](https://github.com/nopSolutions/nopCommerce/commit/21da3e1db787150902f5f80bbc13c1e5ad551320)

**Comment by skoshelev** [comment]
Closed #99
