### ISSUE TITLE
Admin area. Display product thumbs on all "add product" pages

### ISSUE THREAD

**Issue by mariannk** [nopSolutions/nopCommerce#999]
Show thumbnails on the Related Products Dialog so similarly named items can be easier distinguished. Pages: add related products, add cross-sell products, add products to category/manufacturer, somep plugins, etc 

The issue is in this case that popup page does not fit all grid rows (pictures increase grid row height) and "Save" button is not visible. We can set picture size to 15-18px. But it's too small. 

Problem 
Catalog Administrators can not determine the correct related product by Product Title alone in some cases. 

Solution 
Add thumbnails to the Add Related Products Dialog so Catalog Administrators can find/see the correct related product. This alleviates the need to close the dialog, find the correct related product, go back to the main product, then find and add the related product again. 

Source: http://www.nopcommerce.com/boards/t/32613/enhancement-add-product-thumbnails-to-the-add-related-products-dialog.aspx

**Comment by AndreiMaz** [comment]
After some discussion decided not to implement it out of the box. We leave it for customization or plugin development
